- generators/client/templates/angular/src/main/webapp/app/entities/entity.module.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.module.ts.ejs
As explained in https://angular.io/guide/entry-components, only dynamically loaded components must be in entryComponents array, so leaving only dynamically loaded components there to follow best practice.
This redundancy was found while reviewing #10408 
> Remove redundant entryComponents in Angular

- generators/server/templates/src/main/java/package/domain/AbstractAuditingEntity.java.ejs
You use `@EntityListeners(AuditingEntityListener.class)` to audit some entity like User entity, but this is spring data auditing based on jpa auditing, which use lifecycle call backs like `@Prepersist`, `@Preupdate`  to make auditing works.
But you also added `@Audited` in hibernate enver, which actually do nothing here. What hibernate do behind the `@Audited` is way different than custom jpa auditing, it creates a new auditing table and records every changes, deletion included, which enables entity versioning.
I guess `@Audited` is somewhat duplicate code, since all you need is `@EntityListeners(AuditingEntityListener.class)` here.
> Remove duplicated code.

- generators/server/templates/src/main/resources/config/application.yml.ejs
Using gnome or vte terminals gradle is not very good in detecting it is running in an interactive terminal (depending on some upcoming things in vte based terminals). With this change `./gradlew` outputs colored logs but keeps the auto detection enabled.
https://stackoverflow.com/questions/28783832/getting-spring-boot-color-console-logging-working-within-intellij
> enable colored output for gradle on linux/gnome environment

- generators/server/templates/gradle/profile_dev.gradle.ejs
- test-integration/scripts/21-tests-backend.sh
This PR is follow up to #10392 to fix Gradle part in this line: https://github.com/jhipster/generator-jhipster/pull/10392/files#diff-4451b02339edda1561d29b286ed1d9f7R49
In Gradle exclude task syntax is `-x <taskName>`
Changing also webpack task name in Gradle `dev` profile from `webpackBuildDev` to `webpack` to avoid distributing this inappropriate name as I explained and proposed in https://github.com/jhipster/generator-jhipster/issues/10363#issuecomment-530761661
Gradle allow task name abbreviations as described here: https://docs.gradle.org/current/userguide/command_line_interface.html#task_name_abbreviation so `-x webpack` would work also with current task name `webpackBuildDev`, but I think using abbreviations …
> Gradle: change webpackBuildDev to webpack and fix CI command

- generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs
I'm redoing this change, done with https://github.com/jhipster/generator-jhipster/pull/9681 and reverted accidentally in https://github.com/jhipster/generator-jhipster/commit/75d6a6604de5db112b52c238590d3fa25549e2e9
> Liquibase: Define again DBMS specific properties only at one place (fix accidental revert)

- generators/server/prompts.js
Going through some micro-service workflows, I discovered our recent addition of Caffeine cache has made Caffeine the default option for Micro-services, instead of Hazelcast. This pull fixes that. :smile: 
Related to  #9351
> Default Caching Option for Microservices Should be Hazelcast

- generators/server/templates/gradle/docker.gradle.ejs
- generators/server/templates/pom.xml.ejs
This PR fix https://github.com/jhipster/generator-jhipster/issues/10186
You can find here more details: https://pracucci.com/graceful-shutdown-of-kubernetes-pods.html
> Graceful shutdown of pods with Kubernetes (Set shell to bash)

- generators/common/templates/README.md.ejs
Since the change to Sass happened leaflet.css should be imported in `<%= CLIENT_MAIN_SRC_DIR %>content/scss/vendor.scss` rather than the old `<%= CLIENT_MAIN_SRC_DIR %>content/css/vendor.css`
> Fix markdown link in leaflet installation instructions for importing the css file

- generators/server/templates/pom.xml.ejs
Fixes #10485.
NOTE: It doesn't look like Gradle will support Java 13 until [Gradle 6.0](https://github.com/gradle/gradle/issues/8681#issuecomment-532507276), so we'll need to wait for that until this ticket can be fully resolved.
> Allow Java 13 to be used with JHipster

- generators/client/templates/angular/src/test/javascript/jest.conf.js.ejs
- generators/client/templates/react/package.json.ejs
- generators/client/templates/react/src/test/javascript/jest.conf.js.ejs
since jest-unit 8.0.0 there is no longer an output parameter; Use OutputDirectory and OutputName instead
Fix #10445
> change to supported  jest-junit api from removed api

- generators/client/templates/angular/src/main/webapp/app/admin/admin-routing.module.ts.ejs
This is follow-up to #10443, removes redundant import.
> Remove redundant import from Angular admin routing

- generators/client/templates/angular/src/test/javascript/jest.conf.js.ejs
- generators/client/templates/angular/webpack/utils.js.ejs
- generators/client/templates/react/src/test/javascript/jest.conf.js.ejs
- generators/client/templates/react/webpack/utils.js.ejs
This PR is follow-up to #10252 and is motivated by #10502 - if `paths` is removed from `tsconfig.json` then current implementation gives errors.  
Now checking that `tsconfig.compilerOptions.paths` is defined.
> Survive paths removal from tsconfig.json

- .vscode/launch.json
- cli/commands.js
- cli/import-jdl.js
- cli/utils.js
- package-lock.json
- package.json
- test/cli/import-jdl.spec.js
Makes it possible to invoke import-jdl with inline content
```
jhipster import-jdl --inline \
"application {
config {
baseName jhapp,
testFrameworks [protractor]
}
}"
```
or 
```
jhipster import-jdl --inline "application { config { baseName jhapp, testFrameworks [protractor] }}"
```
> Support inline content for JDL

- generators/server/templates/src/main/resources/logback-spring.xml.ejs
- generators/server/templates/src/test/resources/logback.xml.ejs
Get rid of  warning of netflix URLConfigurationSource
````sh
WARN  [main] c.n.c.s.URLConfigurationSource - No URLs will be polled as dynamic configuration sources.
````
that comes from https://github.com/Netflix/archaius/blob/master/archaius-core/src/main/java/com/netflix/config/sources/URLConfigurationSource.java#L126, defining a new entry in logback.
> Get rid of netflix URLConfigurationSource warning

- generators/server/templates/src/main/java/package/security/jwt/TokenProvider.java.ejs
There's no need to separate exception handling as the type of exception is self-explanatory. 
Also, `{}` should not be used for exception parameter if you want to log the stacktrace.
> Better exception/log for JWT token validation

- generators/server/templates/src/main/java/package/service/MailService.java.ejs
- generators/server/templates/src/test/java/package/service/MailServiceIT.java.ejs
Only `MessagingException` should be thrown by the code, so we should only catch them instead of `Exception`
Testing `isDebugEnabled` while the message is logged at warn level is very strange. If level is configured at DEBUG, no message will be logged because of the `warn` level of the logs. So the `else` branch is useless, and only the `if` branch is useful. Also, logging only the message of the exception is bad practice. …
> Better exception/log for MailService

- generators/entity-server/templates/src/main/resources/config/liquibase/fake-data/table.csv.ejs
Fix #10513
Related to https://github.com/jhipster/generator-jhipster/pull/10332 which fixed the semicolon issue, because we are quoting the string in the CSV, we need to escape any quotes within the string
- escape quotes in regex-generated random string, needed for proper csv format (CSV uses `""` to indicate an escaped quote, [source](https://stackoverflow.com/a/17808731/3737815))
- set max repetitional tokens (such as * or +) to 5 instead of default 100 (similar to [here](https://github.com/jhipster/generator-jhipster/blob/master/generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs#L253-L254))
-   [x] …
> entity faker csv string regex improvements

- generators/client/templates/angular/src/main/webapp/app/shared/login/login.component.ts.ejs
Currently user is not redirected to home page after account activation.
Activation route is in the form `/account/activate?key=...` and this doesn't start with `/account/activate/`
This seems to be regression from #6191 - this PR describes redirect after password reset, but also activation redirect functionality is changed.  
I found this issue while testing #10383
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are …
> Fix redirect on account activation in Angular

- cli/commands.js
- cli/import-jdl.js
- generators/entity-server/files.js
- generators/entity/index.js
- test/cli/import-jdl.spec.js
- test/entity.spec.js
Both from `jhipster import-jdl` or from `jhipster entity`
I used `--skip-db-changelog` since it's a bit more generic than `--skip-liquibase` and we also support database changelog for Cassandra without using Liquibase
Fixes #10059
> Add ability to skip database changelog generation

- generators/client/templates/angular/src/main/webapp/app/account/sessions/sessions.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/audits/audits.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/configuration/configuration.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/gateway/gateway.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/health/health-modal.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/health/health.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/logs/logs.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/tracker/tracker.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.html.ejs
- generators/server/templates/src/main/resources/templates/error.html.ejs
- generators/server/templates/src/main/resources/templates/mail/activationEmail.html.ejs
- generators/server/templates/src/main/resources/templates/mail/creationEmail.html.ejs
- generators/server/templates/src/main/resources/templates/mail/passwordResetEmail.html.ejs
To get our sonar rating forward this PR replaces https://github.com/jhipster/generator-jhipster/pull/10263
updates #10258
> fix sonar issues for core application and entities

- generators/entity/index.js
Create otherEntityFolderName independent of otherEntityFileName
Part of https://github.com/jhipster/generator-jhipster/issues/10160
JHipster uses entityFolderName to define entity's folder.
https://github.com/jhipster/generator-jhipster/blob/a9504de1d0eabc3a849d3f8d2e86358165f9ce47/generators/entity/index.js#L666
So a otherEntityFolderName will allow to make a correct link to the entity instead of using the fileName as folderName.
In the blueprint the entity's folder was changed, so the reference to it (otherEntityFolderName) must be updated.
-   [x] Documentation is added/updated …
> Entity: Implement otherEntityFolderName

- generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs
Columns are declared in liquibase changeset, but not generated in csv file, in the following cases:
- one-to-many relationship
- one-to-one with ownerSide = false or with useJPADerivedIdentifier = true
Fixes https://github.com/jhipster/generator-jhipster/issues/10577
> Faker: don't generate unnecessary column declaration for loading data

- generators/openapi-client/prompts.js
While working on #10491, I realized that the word `default` is used as the default value of the variable `cliName`. Since `default` is a keyword in Java this creates problems in the generated classes. This creates a minor fix for that. 
Related to  #10491
> OpenAPI Client Bug Fix: Set proper default value for `cliName` variable

- generators/client/templates/react/src/main/webapp/app/modules/administration/metrics/metrics.tsx.ejs
The following metric section isn't displayed for React:
> fix metrics for services in react

- generators/gae/index.js
While testing, #10533, I've noticed that the gae generator has the tendency to fail sometimes when the cloud sql instances are created due to `this.gcpCloudSqlInstanceName.split(':')[2]` having a extra new line character at the end. So I've went ahead and added a trim method to get rid of any extra white-space characters. 
Related to: https://github.com/jhipster/generator-jhipster/issues/10533
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/ …
> GAE: Trim gcpCloudSqlInstanceName Variable to Remove White-Spaces

- azure-pipelines.yml
- test-integration/scripts/00-init-env.sh
This is related to jhipster/generator-jhipster#10594
I think we should run OpenJDK 8 to be consistent everywhere. The default Azul OpenJDK provided by Azure cannot be trusted I think given that we saw some inconsistencies in the above issue with Couchbase. smile
> Retiring the use of Azul JDK and go fo OpenJDK

- test-integration/scripts/20-docker-compose.sh
- test-integration/scripts/24-tests-e2e.sh
This reintroduces the Couchbase docker start as discussed in; https://github.com/jhipster/generator-jhipster/issues/10594#issuecomment-541296271
Although this works in [my own fork's Github CI pipeline](https://github.com/SudharakaP/generator-jhipster/runs/257408009) I am unsure if it will have problems here. So we will see how it goes and if there are any problems we will revert this back so that [my other fix](https://github.com/jhipster/generator-jhipster/pull/10596) will take effect.
-   [x] Coding Rules & Commit Guidelines …
> Reintroduce Couchbase Docker Start

- generators/ci-cd/index.js
- generators/ci-cd/prompts.js
- generators/ci-cd/templates/github-ci.yml.ejs
- test/ci-cd.spec.js
* Closes #10599 
* Followed Azure CI template (without external integrations) with Java 8 and Java 11 build support.
* Tested with `yarn + gradle + angular` combination @ https://github.com/vishal423/sample-jhipster-ng-gradle-yarn-app/commit/64d1fd3759b33d53f255566421a44d1b31845603/checks?check_suite_id=262455522
* Tested with `npm + maven + react` combination @ https://github.com/vishal423/sample-jhipster-react-mvn-npm-app/commit/41dfd24c8ad079409008635594fd8dff6dd9f26e/checks?check_suite_id=262455872
---
-   [x] Coding Rules & …
> feat (ci): Support Github CI in the ci-cd sub generator

- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.route.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/no-pagination-template.ejs
- generators/generator-base-private.js
Angular http component routes response to Observable error chain if HTTP error occurs: https://angular.io/guide/http#getting-error-details  
So no need to filter `HttpClient` response with `res.ok`, #10383 removed such code from client sub-generator, this PR removes this from entity client sub-generator to avoid confusion and make code cleaner.
> Remove redundant filter in entity in Angular

- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/infinite-scroll-template.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/no-pagination-template.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/pagination-template.ejs
Seems that initial entity code is copied from user management code. In user management account is used to disable inactivation and deletion of currently logged in user. In entities variable `currentAccount` is unused and can be removed.
> Remove unused currentAccount variable from entity component in Angular

- generators/client/templates/angular/.eslintrc.json.ejs
- generators/client/templates/angular/src/main/webapp/app/account/sessions/sessions.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management-delete-dialog.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management-update.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management.route.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/app.main.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/auth-expired.interceptor.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/errorhandler.interceptor.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/notification.interceptor.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/auth/auth-jwt.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/language/language.helper.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/login/login.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/tracker/tracker.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/home/home.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/shared/alert/alert-error.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/shared/auth/has-any-authority.directive.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/account/password-reset/finish/password-reset-finish.component.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/account/password-reset/init/password-reset-init.component.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/helpers/mock-language.service.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/test.module.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-delete-dialog.component.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.route.ts.ejs
- generators/entity-client/templates/angular/src/test/javascript/e2e/entities/entity-page-object.ts.ejs
- generators/entity-client/templates/angular/src/test/javascript/e2e/entities/entity.spec.ts.ejs
- generators/generator-base.js
This PR switches `@typescript-eslint/no-unused-vars` `args` parameter to default value: `"args": "after-used"`, currently this is turned off: https://github.com/jhipster/eslint-config-jhipster/blob/master/base/index.js#L43
Some of this rule violations were fixed by #10383. This PR fixes remaining problems.
Comment about change in `generator-base.js`: location and reload functions were removed from `JhiLanguageService` by this commit: https://github.com/jhipster/ng-jhipster/commit/39aec06b84dead9e74217dda309ed74d96621c3c and seems that this code was forgotten to be removed from the generator.
This PR is a draft ATM. After CI passes I switch `@typescript-eslint/no-unused-vars` from `error` to `warn`.
-   [x] [Travis …
> Remove unused arguments in Angular

- generators/generator-base-private.js
- test/blueprint/app-blueprint.spec.js
This PR adapts checkJHipsterBlueprintVersion to accept peerDependency on generator-jhipster.
https://github.com/jhipster/generator-jhipster/issues/10611
> Add support to blueprint with peer dependency on generator-jhispter

- generators/server/templates/src/test/java/package/config/DatabaseConfigurationIT.java.ejs
Related to https://github.com/jhipster/generator-jhipster/issues/10594
Reverting this as although it improves Java 8 Daily build problem it seems to reintroduce failing builds for Java 11; also jhipster/generator-jhipster#10594 seems to reduce the java 8 build failures so I think we are okay to remove this change. 
cc: @pascalgrimaud  
> Revert "Couchbase Container Increase Memory Quota"

- generators/server/templates/pom.xml.ejs
With Redis cache, Testcontainers is used for the TI however it should not use database-commons dependency but rather testcontainer-core.
Thanks @ctamisier for pointing it out !
> Redis: Use testcontainers core instead of database-commons

- generators/ci-cd/templates/travis.yml.ejs
Closes #10654
I decided to set the variable instead of dropping the override because the other CI platforms use that variable (hopefully successfully ;-)
> set MAVEN_USER_HOME variable

- generators/server/templates/gradlew
For some reason when I generated the wrapper for 5.6.3 the unix script was generated with ` JAVACMD="/usr/lib/jvm/java-11-openjdk/bin/java"` which does not work in all environments (e.g. gitlab ci). While I prepared my demo for my upcoming talk I generated the wrapper again and it was created with a different command (as in older versions).
> fix gradlew wrapper script

- .github/workflows/applications.yml
> chore: always use the latest JDK 11 release in generator tests

- generators/server/templates/src/main/java/package/config/CacheConfiguration.java.ejs
This is a fix for the Infinispan daily builds. The build is broken due to a bug in Infinispan it seems. When there's a single node infinispan cluster the discovery service seems to run into some problems. 
Fixes part of #10604
> Fix Infinispan Daily Builds

- generators/docker-compose/index.js
This fixes the [error seen in `docker-compose` logs](https://github.com/openzipkin/docker-zipkin/issues/181) due to MariaDB not being accessible. Although I did this as part of my investigations on #10604, I think this will make all MariaDB builds (running under docker) more stable; as you see currently all MariaDB builds in our Daily Builds are flaky. 
Fixes part of #10604 
Reference: https://github.com/openzipkin/docker-zipkin/issues/181 …
> Fix MariaDB Accessibility Issues on E2E Tests in Daily Builds

- generators/server/templates/src/main/docker/app.yml.ejs
This adds a missing part to https://github.com/jhipster/generator-jhipster/pull/10673. Apart from opening port 3306 we need to give a decent sleep time for the `store` app since MariaDB seems to take some time to configure itself especially in CI environments. 
Fixes part of https://github.com/jhipster/generator-jhipster/issues/10604
> Increase Sleep Time for MariaDB to Start

- generators/server/templates/src/main/java/package/web/rest/errors/ExceptionTranslator.java.ejs
Fix typo error in the ExceptionHandler method names
Aready to Already
> Fix typo errors in ExceptionHandler method names

- generators/entity-server/templates/src/main/resources/config/liquibase/fake-data/table.csv.ejs
A different enum value was generated at each request, using faker now to have consistent results
> fix enum faker consistent

- generators/server/templates/gradle/war.gradle.ejs
The includes statement do not include the web.xml for some reason, setting it explictly adds the file to the .war file which fixes the encoding. Used @ruddell description to verify the fix.
closes #10698
> fix encoding in .war file by addin web.xml to generated .war file

- .github/workflows/applications.yml
- .travis.yml
- Dockerfile
- azure-pipelines.yml
- generators/generator-constants.js
Fix #10677
I left the `10.x` test in `.github/workflows/generator.yml`, not sure if that should be removed.  https://github.com/jhipster/generator-jhipster/blob/3a24eace8422107f8d2257f5f5f4114768e51df9/.github/workflows/generator.yml#L11 
I used a script for this that clones all of the repos and replaces the version number, manually validated that it matches the last Node Upgrade PR
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTIN …
> update Node version to v12.13.0, npm to v6.12.1

- generators/kubernetes/templates/README-KUBERNETES.md.ejs
The kubernetes field is called `initialDelaySeconds`
Fixed typo error in the readme template
source: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
> Fix typo in kubernetes readme

- generators/docker-compose/index.js
- test/docker-compose.spec.js
- test/templates/compose/12-oracle/.yo-rc.json
- test/templates/compose/12-oracle/src/main/docker/app.yml
Fix #10708
Also reduce logs by replacing test .war files with jib-cache directory.  The code was changed to check this directory in d602694.  Because of that change, the tests would output an extra log such as:
```
ls: no such file or directory: /private/var/folders/q2/mfm10j8n0ys7k6gqq19tt_540000gn/T/52e95ad4ff659108739889e07d0a990b965eb33f/01-gateway/target/jib-cache
ls: no such file or directory: /private/var/folders/q2/mfm10j8n0ys7k6gqq19tt_540000gn/T/52e95ad4ff659108739889e07d0a990b965eb33f/10-couchbase/target/jib-cache
``` …
> fix oracle docker compose (skip database configuration)

- generators/kubernetes/templates/console/jhipster-elasticsearch.yml.ejs
This PR fixes the `kubernetes` generator when selecting to use the JHipster console for monitoring. 
The fix relies on the Kubernetes documentation around `StatefulSet` https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#pod-selector 
> Fixing elastic search template

- generators/entity-client/files.js
- generators/entity-client/templates/angular/src/test/javascript/e2e/entities/entity.spec.ts.ejs
- generators/entity-client/templates/react/src/test/javascript/e2e/entities/entity.spec.ts.ejs
This adds support to automatically test regex patterns in JDL in our e2e tests. 
Fixes #10704
> Add Support for Generating String Patterns for Regex in JDL

- generators/client/templates/angular/src/main/webapp/app/core/auth/account.service.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/core/user/account.service.spec.ts.ejs
With the upgrade to JHipster 6.4.0 we noticed some behavior surprising to us. I think it is related to https://github.com/jhipster/generator-jhipster/pull/10383/files#.
In particular, we noticed that if we explicitly log out, we will still receive the old `Account` after calling `AccountService.identity().subscribe(..)`. As far as I could see, this is due to the `accountCache` that does not get invalidated, even if the user logs out. In my opinion, it does not make sense to ever return the last cached `Account`, if `AccountService.authenticated` has been switched to `false` meanwhile, i.e. the user has been logged out. This PR changes the behavior to invalidate the cache within `identity()`, if `authenticated == false`. It would also possible to adjust `AccountService.authenticate(null)` …
> invalidate Account cache, if user has logged out

- generators/client/templates/angular/src/main/webapp/app/core/auth/account.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/auth/user-route-access-service.ts.ejs
Fix #10630
Fixes regression from #10383, error was not caught after #10383 any more, this PR restores logic to pre #10383, now error is caught again in `AccountService.identity` function.
> Fix login modal not shown if not authenticated in Angular

- generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
- generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs
- generators/server/templates/src/main/resources/config/application-prod.yml.ejs
Fixes #10650 
Fixes #10653 
Please note that all are verified using the `prod` profile only.
> Persistence improvements using hypersistence optimizer

- generators/server/templates/build.gradle.ejs
- generators/server/templates/gradle/wrapper/gradle-wrapper.properties
* We have some new deprecation warnings, but at least the no-http plugin still works as the announced deprecation was not done, so we are lucky
* Could not test the automatic shortening of jar commands via classpath jar as I don't have a windows at hand. So if someone wants to test if we can remove the custom classpath jar creation https://docs.gradle.org/6.0/release-notes.html#usability-improvements
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/ …
> update to gradle 6

- generators/generator-constants.js
- generators/server/files.js
- generators/server/index.js
- generators/server/templates/build.gradle.ejs
- generators/server/templates/gradle.properties.ejs
- generators/server/templates/gradle/wrapper/gradle-wrapper.properties
- generators/server/templates/gradle/wrapper/gradle-wrapper.properties.ejs
- generators/server/templates/pom.xml.ejs
THis PR does two things:
1. It extrnalizes the gradle version into a constant such that updating should be easier
2. Until the open api plguin has been released in a new version (compatible with gradle 6) when using open api the latest 5.6.4 version is used. This involves minimal branching in two files so the effort to maintain and remove it is quite small
So with this change most of our users will get the latest and greatest gradle version without breaking the open api support.
For details see https://github.com/jhipster/generator-jhipster/pull/10750#issuecomment-552209980
-   [ ] …
> use older gradle version when using openapi plugin

- generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs
- generators/server/templates/src/main/docker/config/realm-config/jhipster-realm.json.ejs
Small bug fix in keycloak config
> fix keycloak webOrigin

- generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs
For MySQL and MariaDB, it should be string.
For PostgreSQL, it should be uuid.
Following https://github.com/jhipster/generator-jhipster/pull/10767#issuecomment-553826284
_____
> Fix fake data with UUID for MySQL and MariaDB

- generators/server/templates/src/main/docker/app.yml.ejs
It seems that MariaDB builds overall is working fine as per #10604, but [once in a while](https://dev.azure.com/hipster-labs/jhipster-daily-builds/_build/results?buildId=7468) I see some failures MariaDB builds timing out. I would like to increase the sleep timeout a bit further to see if we could get the builds not timeout at all; just to make it perfect. :smile: 
Related to https://github.com/jhipster/generator-jhipster/issues/10604 …
> Increase Sleep Timeout for MariaDB a Bit Further

- .github/PULL_REQUEST_TEMPLATE.md
Currently it says "Travis Tests" which doesn't make sense as we use Azure and Github CI; so I've changed it. :smile: 
> Add More Appropriate Title for Test Checkbox in Pull Requests

- generators/gae/index.js
This PR replaces child_process.execSync with shelljs within Google App Engine generator. Issues has been seen with the [child_process.execSync calls in Windows machines](https://github.com/nodejs/node/issues/14967). 
Fixes https://github.com/jhipster/generator-jhipster/issues/10749
> Migrate to shelljs Instead of child_process.execSync

- generators/server/templates/src/main/resources/config/application-dev.yml.ejs
Fixes an issue where Webpack emits file changes causing Devtools to restart.  Devtools will now ignore frontend changes.
I couldn't think of a simple condition that would work together with the checks for `!skipClient` and `h2` so I always excluded `static/**` instead of adding several `if` statements.
Fix #10792
> exclude static folder from Devtools restart

- generators/ci-cd/templates/.gitlab-ci.yml.ejs
Includes `-Pprod` in both, maven and gradle `docker-push` tasks and fixes the tag name strategy to avoid invalid tag names
fix #10795
> fix docker task in GitLab CI-CD sub-gen

- README.md
The logos in our README.md file seems a bit space consuming with their vertical stacking. I re-formatted it to contain in a html table. 
To see how it looks --> https://github.com/SudharakaP/generator-jhipster/tree/modify-readme-page-with-sponsor-logo-alignment
I hope this looks better. :smile: 
> Modify Readme Page with Sponsor Logos Horizontally Aligned

- generators/client/templates/angular/package.json.ejs
- generators/client/templates/react/package.json.ejs
When working in dev, `npm start` occasionally crashes because of eslint (requires restarting `npm start`).  I couldn't find an exact way to reproduce the issue, but I experienced it several times myself and several Gitter users have reported it.
`Parsing error: Cannot read property 'parent' of null`
Related to https://github.com/typescript-eslint/typescript-eslint/issues/1114
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIB …
> upgrade typescript-eslint packages

- generators/client/templates/angular/src/main/webapp/app/layouts/main/main.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-delete-dialog.component.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.module.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.route.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/infinite-scroll-template.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/no-pagination-template.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/pagination-template.ejs
I looked at entity delete component while dealing with #10631 and found heavy code for delete.
In user management module it's light and simple. I looked at Git history and found out that in user management this was simplified by https://github.com/jhipster/generator-jhipster/commit/3d180131fd6e0d47af6888f25695b1ee85f47a2e as part of #7406
I made the same simplification in entities and removed popup router outlet as this is not needed any more now. …
> Use simple modal in entity delete in Angular

- generators/client/templates/angular/src/test/javascript/protractor.conf.js.ejs
Fixes #10806
Seems that something changed in the latest `webdriver-manager` version `12.1.7` to what our clients were updated by #10676. Seems that if UI element is not inside visible area then `Protractor` is not able to get reference to that element any more.
In this PR I changed Chrome window 10 times higher and now Protractor tests are passing.
> Fix Protractor tests in Travis

- generators/cleanup.js
- generators/server/files.js
- generators/server/templates/src/test/java/package/web/rest/ClientForwardControllerTest.java.ejs
Remove SpringBootTest from ClientForwardController test making it a fast unit test
> Remove SpringBootTest from ClientForwardController test

- generators/server/templates/build.gradle.ejs
- generators/server/templates/gradle.properties.ejs
- generators/server/templates/gradle/wrapper/gradle-wrapper.properties.ejs
- generators/server/templates/pom.xml.ejs
This updates the [openapi plugin to 4.2.1
](https://github.com/OpenAPITools/openapi-generator/releases) which has removed the usage of some [deprecated gradle api](https://github.com/OpenAPITools/openapi-generator/pull/4352) such that we can remove the workaround of using gradle 5.6.4 instead of 6.x when using api first option
> Update open api plugin to remove gradle workaround

- generators/kubernetes-base.js
sets the size of db generated passwords in a way, so the resulting password is 60 bytes long and not causing failures for PostgreSQL apps
fix #10803
> reduces db-password size to prevent fail in k8s

- generators/client/files-angular.js
- generators/client/templates/angular/package.json.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/tracker/tracker.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/tracker/tracker.module.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/tracker/tracker.route.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/auth/account.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/auth/auth-jwt.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/auth/auth-session.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/auth/csrf.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/auth/state-storage.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/language/language.helper.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/login/login.model.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/login/login.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/login/logout.model.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/tracker/tracker-activity.model.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/tracker/tracker.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/user/user.service.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/account/password/password.component.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/account/settings/settings.component.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/core/user/account.service.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/core/user/user.service.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/helpers/mock-tracker.service.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/test.module.ts.ejs
- test/app.spec.js
- test/utils/expected-files.js
This PR is next peace for the #10631
This PR resolves problems in the most places of **core module** and entirely in the **tracker module**.
I started only with `core/auth` folder, but as tracker module is related then I included also tracker module.
Unresolved stay after this PR:
* `core/login/login-modal.service.ts` - this can be done after in all places is `open()` used as `void`, account module PR #10639 is doing that already for account module
* `core/user/user.model.ts` - this can be done in conjunction with user-management module
Some notes about changes:
* there where memory leaks in tracker component and service (missing unsubscribes from observables), in my testing these are removed now
* following direction taken in #10220 I removed prefixes from tracker component and service
* …
> Use strict option in the majority of the core module and in the tracker module in Angular

- generators/client/templates/angular/.eslintrc.json.ejs
- generators/client/templates/angular/package.json.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/audits/audits.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/audits/audits.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/audits/audits.service.ts.ejs
- generators/client/templates/angular/src/test/javascript/jest.conf.js.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/admin/audits/audits.component.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/admin/audits/audits.service.spec.ts.ejs
This is next peace for #10631
Some comments about changes.
* Switching on typescript `strict` option forces to look at all kind of corner cases. So I made some changes in logic. I tested all these cases manually, but added also full unit tests.
* For date testing added `jest-date-mock` library.
* All internal methods are now private.
* Error messages were not shown before these changes.
* If start or end date was empty then NPE in server side before these changes.
* I removed `routeData.unsubscribe()`, because this in not necessary according to https://angular.io/guide/router#!#route-parameters (but it states: _Feel free to unsubscribe anyway. It is harmless and never a bad practice._) - currently in `audits` and `user-management` this `unsubscribe` is used, but in `entities` is not used. …
> Use strict typescript option in audits module in Angular

- generators/generator-base-private.js
The issue was that the JDL generated from a current directory will be
created from entities and options. However, in a newer version, the function
used to generate the JDL object has been changed.
> Fixed jhipster-info command

- cli/cli.js
- cli/import-jdl.js
- cli/utils.js
Currently every import-jdl command exits with status 0, this patch will make import-jdl and probably other commands exit with the last non 0 status.
> Exit import-jdl with status from the forked process.

- generators/server/templates/src/main/resources/swagger/api.yml.ejs
fix a part of #9752 by adding `/api` to default servers configuration in openapi api.yml
The generated api will be available under `/api` JHipster default path and available in the springfox ui.
> Add /api to default servers URL to expose them to UI

- .github/workflows/applications.yml
- .github/workflows/generator.yml
- .github/workflows/triage.yml
Related to https://github.com/jhipster/generator-jhipster/issues/10817 but not directly
It's more like using `GitHub Actions`
The 2 labels were already created
_____
> GitHub Actions: add new action for triage issues

- generators/server/templates/src/main/java/package/web/rest/errors/ErrorConstants.java.ejs
- generators/server/templates/src/main/java/package/web/rest/errors/ExceptionTranslator.java.ejs
NoSuchElementException is thrown when calling get() on an empty Optional. That's something that shouldn't happen on the server and should result in a HTTP error 500.
If we want to use an exception for 404, it should be a dedicated one. Although I haven't found a place in the code where this is needed.
> Remove exception mapping of NoSuchElementException

- generators/client/templates/angular/webpack/webpack.prod.js.ejs
- generators/client/templates/react/webpack/webpack.prod.js.ejs
See https://stackoverflow.com/questions/57979835/how-to-fix-uncaught-in-promise-bad-precaching-response-error-with-service-wo/57982417#57982417 to see why this is a solution.
Related: https://groups.google.com/forum/#!topic/jhipster-dev/BO4ywuY4S8I
> Exclude swagger-ui for service-worker so PWAs work out-of-the-box

- generators/server/templates/build.gradle.ejs
- generators/server/templates/gradle/profile_prod.gradle.ejs
The plugin was configured only for the prod profile only (with an older workaround to not fail on no git repo). Now the plugin is configured correctly on global/root level, such that it doesn't fail when not being inside a git repo.
Closes #10867 
> configure gradle git properties plugin to not fail on no git repo

- generators/client/templates/angular/src/main/webapp/app/core/auth/account.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/home/home.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/shared/login/login.component.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/shared/login/login.component.spec.ts.ejs
This is the next piece for the #10631 - home module.
One note about changes: `AccountService.identity()` must be called in `HomeComponent` only if authentication type is oauth2, for other authentication types this is already called in `LoginService.login()`: 
https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/app/core/login/login.service.ts.ejs#L60-L62 …
> Strict option in home module in Angular

- generators/client/templates/angular/src/main/webapp/app/account/password/password.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/account/register/register.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/account/sessions/sessions.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/account/settings/settings.component.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/account/password/password.component.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/account/register/register.component.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/account/settings/settings.component.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/admin/audits/audits.component.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/helpers/mock-account.service.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/helpers/mock-language.service.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/test.module.ts.ejs
* after merging 3 PR (account, audits, core+tracker), strict option reported some problems, which this PR fixes
* also using new `getCurrentLanguage()` from the new `ng-jhipster`
* and also cleans code
Related to #10631 #10639 #10683 #10786
> [Angular] Fix strict in account and audits module

- generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/auth-expired.interceptor.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/errorhandler.interceptor.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/notification.interceptor.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/login/login.service.ts.ejs
This is the next piece for the #10631 - blocks folder.
Some comments below.
https://angular.io/guide/http#getting-error-details says: _The HttpClient captures both kinds of errors in its HttpErrorResponse and you can inspect that response to figure out what really happened._  
So `HttpClient` error is always `HttpErrorResponse` and no need to check is this indeed `HttpErrorResponse`.  
`HttpErrorResponse` can contain HTTP error response or `ErrorEvent` in `HttpErrorResponse.error` (then `HttpErrorResponse.status` is `0`).
NotificationInterceptor: `HttpHeaders.get` is returning `string | null` - so no need to check `if (typeof alert === 'string')`, checking `if (alert)` is enough.
This PR has 2 commits:
* first one https://github.com/jhipster/generator-jhipster/commit/476b5e16314c0869f68791 …
> Strict option in blocks folder in Angular

- generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management-delete-dialog.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management-delete-dialog.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management-detail.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management-update.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management-update.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management.route.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/user/user.model.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/admin/user-management/user-management-delete-dialog.component.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/admin/user-management/user-management-detail.component.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/admin/user-management/user-management-update.component.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/admin/user-management/user-management.component.spec.ts.ejs
User management module for #10631 
Some comments about changes:
* https://github.com/jhipster/generator-jhipster/pull/10383/files#diff-fbe805378490e83898dff42879a82b67L42-R43 changed `userService.find` return type from `Observable<HttpResponse<IUser>>` to `Observable<IUser>` so in detail and update component `ngOnInit` no need to check for `user.body` any more
* `activated` in update form: if reading code then can see that goal is to set `activated=true` in adding new user and disable changing that in update form (because back end forces `activated=true` if adding a new user) but in my testing either didn't work, so I adjusted code to make it work as intended
* http errors were not shown in user list component, added `<<%= jhiPrefixDashed %>-alert-error></<%= jhiPrefixDashed …
> Strict option in user management in Angular

- generators/entity-server/templates/src/main/resources/config/liquibase/fake-data/table.csv.ejs
- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
- generators/generator-base-private.js
- test/generator-base-private.spec.js
This ensures reproducible builds in the fake data generation.  Before this commit, any fields with pattern regex validation would regenerate a new value for each fake-data row, causing Liquibase checksum issues on startup.
Also removes some custom code that does the same thing in `EntityResourceIT.java.ejs`
Let me know if there's a better place to put the new method.
Related to https://github.com/jhipster/generator-jhipster/issues/10372 …
> use a seeded RNG for RandExp regex generation

- generators/entity-server/templates/src/main/java/package/service/dto/EntityDTO.java.ejs
JDL:
```
entity Foo {
name String
}
entity Bar
Foo{bar} to Bar{foo(name)},
}
dto * with mapstruct
paginate * with pagination
service * with serviceClass
filter *
```
Changes:
```patch
public String toString() {
return "BarDTO{" +
"id=" + getId() +
-            ", foo=" + getFooId() +
-            ", foo='" + getFooName() + "'" +
+            ", fooId=" + getFooId() +
+            ", fooName='" + getFooName() + "'" +
"}";
}
```
-   [x] Coding Rules & Commit Guidelines as per our …
> display full field name in DTO toString method

- generators/docker-compose/files.js
- generators/docker-compose/index.js
- generators/kubernetes/templates/deployment.yml.ejs
- generators/kubernetes/templates/service.yml.ejs
- generators/server/files.js
- generators/server/templates/pom.xml.ejs
- generators/server/templates/src/main/java/package/Application.java.ejs
- generators/server/templates/src/main/java/package/security/oauth2/UaaSignatureVerifierClient.java.ejs
- generators/server/templates/src/main/java/package/security/oauth2/UaaTokenEndpointClient.java.ejs
- generators/server/templates/src/main/java/package/web/filter/RouteDetectorFilter.java.ejs
- generators/server/templates/src/main/resources/config/application.yml.ejs
this PR enhances the experience when using microservices (in particular
UAA) without eureka in docker-compose and kubernetes
closes #8967 and #9027
> enable UAA microservices w/o eureka

- generators/server/files.js
- generators/server/templates/build.gradle.ejs
- generators/server/templates/pom.xml.ejs
- generators/server/templates/src/main/java/package/config/MethodSecurityConfiguration.java.ejs
- generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs
- generators/server/templates/src/main/java/package/config/UaaWebSecurityConfiguration.java.ejs
this enables usage of @PreAuthorize('#oauth2.hasScope') and similar for
UAA/OAuth2 applications.
fix #10469
> moves method-security into own config for oauth2 method expressions

- generators/generator-base-private.js
- test/generator-base-private.spec.js
Improve getEntityParentPathAddition logic to count directories, ignoring
parent path '../' and ignoring self path './'
> Entity: getEntityParentPathAddition don't considers paths with '..'

- generators/entity-client/files.js
- generators/entity-server/templates/src/main/resources/config/liquibase/fake-data/table.csv.ejs
- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
This is follow up to #10892 and includes:
* using functionality provided by #10892 generates consistent result also for front end tests pattern fields
* improves #10892 for back end tests pattern fields:
* after #10892 `sampleTextString` and `updatedTextString` were identical and constantly was shown warning in the console that sample and update strings are equal and adding B at the end of `updatedTextString`
* now different consistent values are generated for `sampleTextString` and `updatedTextString`
* while testing this PR found that fake data was not generated for pattern fields if pattern field doesn't allow `"`, this is now fixed, fake data is now generated even if pattern doesn't allow `"`
-   [x] [All …
> Improve randexp usage in test data generation

- generators/client/templates/angular/webpack/webpack.dev.js.ejs
- generators/client/templates/angular/webpack/webpack.prod.js.ejs
Treat component specific SASS styles the same way as vendor and global styles using the autoprefixer.
> [Feature Request] Enable autoprefixer for component specific styles

- generators/client/templates/angular/src/main/webapp/app/admin/gateway/gateway.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/gateway/gateway.module.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/gateway/gateway.route.ts.ejs
Gateway module for #10631 
According to #10220 removed prefix from component name.
> Strict Typescript option in gateway module in Angular

- generators/client/templates/angular/src/main/webapp/app/admin/health/health-modal.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/health/health-modal.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/health/health.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/health/health.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/health/health.module.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/health/health.route.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/health/health.service.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/admin/health/health.component.spec.ts.ejs
This is a health module for the #10631 
Health checking API in Spring Boot changes in version 2.2, new API version V3 will be used, ATM in Spring Boot 2.1 we are using API version V2:
* Spring Boot 2.1: https://docs.spring.io/spring-boot/docs/2.1.10.RELEASE/actuator-api/html/#health
* Spring Boot 2.2: https://docs.spring.io/spring-boot/docs/2.2.1.RELEASE/actuator-api/html/#health
So if we switch to Spring Boot 2.2 then this health checking module needs to be aligned to the health checking API version V3. Or act as described in the referenced Spring Boot 2.2 API documentation: _If you need to return V2 JSON you should use an accept header or application/vnd.spring-boot.actuator.v2+json_.
In this PR I removed all code that processed result from actuator health endpoint and I see identical …
> Strict Typescript option in health module in Angular

- generators/client/templates/angular/src/main/webapp/app/blocks/config/prod.config.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/shared/alert/alert.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/shared/auth/has-any-authority.directive.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/shared/language/find-language-from-key.pipe.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/shared/shared.module.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/shared/util/datepicker-adapter.ts.ejs
This is shared module for #10631
Some notes:
* `alert.component.ts` - in `ngOnDestroy()` was tried to clear messages by `this.alerts = [];` but this doesn't clear messages and the same success message is shown in another form if user quickly navigates to other form, substituted this with `this.alertService.clear();` and now are messages cleared and not shown in another form
* removed memory leak from `has-any-authority.directive.ts`, this happened because not unsubscribed from observable:
* this occurred if using this directive in some component which can created multiple times while navigating in and out, for example if adding to home component: `<p *jhiHasAnyAuthority="'ROLE_ADMIN'">Only for admin</p>`
* in generated code this is used only in navbar so if user didn't use this in any …
> Strict Typescript option in shared module in Angular

- generators/azure-spring-cloud/templates/github/workflows/azure-spring-cloud.yml.ejs
When deploying with GitHub Actions to Azure Spring Cloud, cache Maven archetypes to speed up the build
> add caching support for Maven artefact on Azure Spring Cloud

- test-integration/samples/.jhipster/FieldTestEntity.json
This PR adds test cases for pattern fields which doesn't allow only alphabetical symbols.
These tests will break PR #10921 and would have broken #10892 (which was fixed by #10897).
> Add number pattern to entity tests

- generators/generator-constants.js
following the latest security advice
https://blog.npmjs.org/post/189618601100/binary-planting-with-the-npm-cli
updating npm and yarn for the generated clients
I didn't update/enforce npm version for the generator itself, should we do that? e.g. in `package.json`
> update npm to latest version

- generators/server/templates/src/main/java/package/web/rest/ClientForwardController.java.ejs
- generators/server/templates/src/test/java/package/web/rest/ClientForwardControllerTest.java.ejs
Ensures that websocket fallbacks, such as `xhr_streaming` and `eventsource`, receive requests as expected rather than forwarding to the client.
The issue fixed here was that the regex for `websocket` was searching the end of the path rather than the beginning, due to the prefix of `/**/`.  When websockets don't work, they fallback to other options such as `xhr_streaming` and `eventsource` (URLs end with the method name).    Regular websockets work because the websocket URL ends in `websocket`
Before this PR, request for fallback methods would result in a `405 Method Not Allowed` because they are POST requests going to the client at `/` ([screenshot](https://user-images.githubusercontent.com/4294623/70653256-f725ff00-1c08-11ea-8a1e-8083f5bd7026.png))
Improved version of …
> fix websocket fallback paths in ClientForwardController

- generators/client/templates/angular/src/main/webapp/app/admin/docs/docs.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/docs/docs.module.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/docs/docs.route.ts.ejs
Docs module doesn't have errors if enabling Typescript strict option but according to #10220 removed prefix from component name.
> Remove prefix from DocsComponent in Angular

- .github/workflows/angular.yml
- .github/workflows/react.yml
- README.md
As the builds for React are too flacky, compared to Angular, I prefer to split them.
So it will be easier to restart only React builds.
_____
> GitHub Actions: split Angular and React builds

- generators/server/templates/build.gradle.ejs
This is the follow up to the #10750 - @atomfrede mentioned in the https://github.com/jhipster/generator-jhipster/pull/10750#issue-338838170 that Gradle 6 automatically creates classpath jar if needed and we can probably remove workaround for Windows what is doing the similar job. I tested this in Windows and in my testing this is true what is written in the Gradle 6 release notes (https://docs.gradle.org/6.0/release-notes.html#usability-improvements).
Classpath jar is automatically created if needed, messages from console in `--debug`:
```
[INFO] [org.gradle.process.internal.JavaExecHandleBuilder] Shortening Java classpath [.....] with .....\AppData\Local\Temp\gradle-javaexec-classpath5811139544298465801.jar
[INFO] [org.gradle.process.internal.DefaultExecHandle] Starting process 'command …
```
> Remove Gradle workaround for Windows

- cli/run-yeoman-process.js
- cli/utils.js
As discussed in #10934, remove explicit calls to node exit command (`process.exit()) and use `process.exitCode` instead. 
Reference: https://nodejs.org/api/process.html#process_process_exit_code
> Remove Explicit Calls to process.exit and Set the exitCode Instead

- generators/ci-cd/index.js
- generators/ci-cd/templates/azure-pipelines.yml.ejs
fix Azure Pipeline template for projects generated with --skip-server
Fix #10927
> Fix Azure Pipeline Template for Serverless Projects

- generators/entity-server/templates/src/main/java/package/repository/EntityRepository.java.ejs
- generators/entity-server/templates/src/main/java/package/repository/reactive/EntityReactiveRepository.java.ejs
- generators/entity-server/templates/src/main/java/package/repository/search/EntitySearchRepository.java.ejs
- generators/server/templates/src/main/java/package/service/dto/UserDTO.java.ejs
As `import javax.validation.constraints.*;` is already there then no need for these 2 lines:
```
import javax.validation.constraints.Email;
import javax.validation.constraints.NotBlank;
```
#9691 removed blank line between `package` and first `import`:
* https://github.com/jhipster/generator-jhipster/pull/9691/files#diff-c714ea8c4adde0198c1f03bcd907ad11L19-R21
* https://github.com/jhipster/generator-jhipster/pull/9691/files#diff-ff395df2cf80c27e56d8d22c66a1539fL19-R21
* https://github.com/jhipster/generator-jhipster/pull/9691/files#diff-88927e319149787141a91b8a00d5901fL19-R21
I guess this was accidental and this PR puts this blank line back.
-   [x] [All continuous integration …
> Polish java imports

- .github/workflows/react.yml
- azure-pipelines.yml
As our current Protractor tests with React are too flaky, it's better to disable it.
So no need to restart and restart and restart each PRs...
_____
> CI-CD: disable flaky Protractor tests with React

- generators/aws-containers/index.js
- generators/client/files-react.js
- generators/client/prompts.js
- generators/utils.js
- package-lock.json
- package.json
After Prettier upgrade in Angular to 1.19.1 `page-ribbon.component.ts` is formatted differently. So updating Prettier version in generator to achieve consistent regeneration.
2 commits: upgrading Prettier version and `npm run lint-fix` result.
> Update prettier version

- generators/server/files.js
This fixes the failing e2e tests (here: https://dev.azure.com/hipster-labs/jhipster-daily-builds/_build?definitionId=18)
> use route detector on non-eureka gateways only

- generators/client/templates/angular/src/main/webapp/app/account/password-reset/finish/password-reset-finish.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/account/password-reset/init/password-reset-init.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/account/password/password.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/account/register/register.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/account/settings/settings.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management-delete-dialog.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management-update.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-delete-dialog.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-detail.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.html.ejs
This fixes strict problems inside HTML templates. This PR is for #10631 
After this and #10932 are merged we can try to enable strict option in Angular:
* in `tsconfig.json` and in `tsconfig-aot.json` change
```
"noImplicitAny": false,
```
to
```
"strict": true,
```
* add new rule into `tslint.json`: `"typedef": [true, "call-signature"]`
> Strict Typescript option in HTML templates in Angular

- generators/client/templates/angular/src/main/webapp/app/admin/configuration/configuration.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/configuration/configuration.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/configuration/configuration.module.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/configuration/configuration.route.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/configuration/configuration.service.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/admin/configuration/configuration.component.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/admin/configuration/configuration.service.spec.ts.ejs
This is a configuration module PR for the #10631
Some notes:
* As according to https://angular.io/guide/pipes#appendix-no-filterpipe-or-orderbypipe it's not recommended to perform filtering or ordering with pipe then now filtering and ordering is done in the component method when filter or order change event occurs.
* UI previously didn't show to user that it's possible to order by prefix. Now UI uses standard `jhiSort` + `jhiSortBy` directives to show that.
* According to #10220 removed prefix from configuration service and component. …
> Strict Typescript option in configuration module in Angular

- README.md
I wanted to find the link to our public Gitter Channel recently and it took me a while to finally get to our [Community help](https://www.jhipster.tech/help/) page where it's located. 
Therefore I thought maybe we should add a Gitter badge to our README.md so that users could easily find it. Feel free to suggest an alternative place(s) to add this link. :smile: 
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are …
> Add Gitter Badge to README.md

- cli/commands.js
- generators/generator-base-private.js
1. Add default description to app command
2. Override yeoman usage function to replace `yo jhipster:` to `jhipster`.
> Improvements to --help

- generators/server/templates/src/main/resources/static/microservices_index.html.ejs
Use the same background color (blue) as jhipster.tech for the microservices homepage:
- The current color is dark and sad
- It's more consistent
> Use the same background color as jhipster.tech

- generators/client/templates/angular/src/main/webapp/app/layouts/main/main.component.ts.ejs
- generators/client/templates/angular/src/test/javascript/e2e/account/account.spec.ts.ejs
This fixes regression from #10836 - if user has valid authentication (valid JWT in session storage or valid cookie) then UI shows in home page like user is not logged in.  
That's because no more is executed `accountService.identity()` in `HomeComponent.ngOnInit()`.
This PR fixes that and makes logic better than this was before #10836 - now `accountService.identity()` is executed on app loading in `MainComponent.ngOnInint()` and this has the following advantage:
* this is a central place which is always executed on application loading and if user initially enters some other page than `HomeComponent` then auto login is always tried, even if initially entered component has not `accountService.identity()` in it's `ngOnInit()` method
* it's useful for pages which are not protected (for …
> Fix auto login in Angular for JWT, session and UAA authentication

- test-integration/scripts/10-install-jhipster.sh
- test-integration/scripts/21-tests-backend.sh
- test-integration/scripts/23-package.sh
- test-integration/scripts/25-sonar-analyze.sh
This should remove all the "downloading artefact" clutter in the console log, if this works this is going to be a lot better for reading the logs
> Add Maven  --batch-mode option to improve CI readability in GitHub Actions

- generators/kubernetes-base.js
- generators/kubernetes/index.js
- generators/kubernetes/prompts.js
- generators/kubernetes/templates/console/jhipster-elasticsearch.yml.ejs
- generators/kubernetes/templates/db/couchbase.yml.ejs
- generators/kubernetes/templates/db/elasticsearch.yml.ejs
- generators/kubernetes/templates/db/mariadb.yml.ejs
- generators/kubernetes/templates/db/mongodb.yml.ejs
- generators/kubernetes/templates/db/mssql.yml.ejs
- generators/kubernetes/templates/db/mysql.yml.ejs
- generators/kubernetes/templates/db/postgresql.yml.ejs
- test/kubernetes.spec.js
with this feature, all stateful services (such as `Deployment`, `StatefulSet` for databases) will use persistent volume claims instead of `emptyDir`. There are two new options for the user, so it is possible to enable dynamic storage provisioning and specify a custom storage class.
Another update in context with this PR, is that `StatefulSet`s are no longer generated with `volumeClaimTemplate` by default, as it was before. Instead, the data dirs are either `emptyDir`, if dynamic storage provisioning is disabled, or we use volume claim templates with the same configuration as for the deployments.
close #10804
- …
> introduce dynamic storage provisioning in k8s sub-gen

- generators/client/templates/angular/tsconfig-aot.json.ejs
- generators/client/templates/angular/tsconfig.json.ejs
This PR is motivated by this comment of @vishal423: https://github.com/jhipster/generator-jhipster/issues/10631#issuecomment-567591233
According to https://www.typescriptlang.org/docs/handbook/compiler-options.html `strict` already includes: `noImplicitAny`, `noImplicitThis` and `strictNullChecks`.
As our Angular code currently passes also `noImplicitReturns` and `noFallthroughCasesInSwitch` then I turned these rules on to keep it that way to be better prepared for Angular 9.
-   [ ] Coding Rules & Commit Guidelines …
> Switch on noImplicitReturns and noFallthroughCasesInSwitch in Angular

- generators/openshift/templates/deployment.yml.ejs
Processing the openshift template throw **"Error from server: unrecognized type: int32"**
Openshift templates support non-string parameters. They are represented by double curly braces (e.g. ${{APP_PORT}})
> rectify the non-string parameter value in openshift deployment template

- generators/entity/index.js
The field relationship.otherEntityRelationshipNamePlural is been set with the fallback value without looking at the other side. 
> Fixes #10984

- generators/server/templates/pom.xml.ejs
The Maven build is broken with NoSQL and OAuth2 options.
I suggest to remove the org.glassfish.jaxb:jaxb-runtime dependency with these options.
Related to https://github.com/jhipster/generator-jhipster/commit/2fb2684fb973e795d735a290713a8280b2682b9d cc @xetys 
```
➜  accountancy git:(master) ✗ ./mvnw -ntp
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for org.glassfish.jaxb:jaxb-runtime:jar must be a valid version but is '${jaxb-runtime.version}'. @ line 261, column 22
@
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project io.jsadaoui.trainning:accountancy:0.0.1-SNAPSHOT (/Users/julien/Development/jhipster/jhipster-training/jhipster-microservice-oauth2/accoun …
```
> Fix maven build with NoSQL and OAuth2 options

- generators/openapi-client/files.js
When using the openapi client generator and fill the project name in camel case it transform to snake case (with underscores) to named the java package.
We should use a lower case version to match with java naming convention. underscore are not forbidden but reserved to special case like when there is a special character, digit or reserved java keywords.
source: https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are …
> use lower case package instead of snake case one

- README.md
Minor change of giving more visibility to the contribution guidelines by adding it to the readme page. :smile: 
> Add Contribution Document Link to Readme.md

- generators/openapi-client/files.js
For this given api.yaml
```
definitions:
student:
type: 'object'
properties:
id:
type: 'integer'
format: 'int64'
firstname:
type: 'string'
lastname:
type: 'string'
birthday:
type: 'string'
format: 'date'
teacher:
$ref: '#/definitions/teacher'
```
We have a Student model generated with a birthday date field. With our current configuration 
```
--type-mappings DateTime=OffsetDateTime,Date=LocalDate 
--import-mappings OffsetDateTime=java.time.OffsetDateTime,LocalDate=java.time.LocalDate
```
The generated field is a LocalDate one (as expected) but the import is not present and the file can't be compiled.
We have to change the DateLibrary value, use as parameter `-DdateLibrary=custom`, by removing it or use another value like 'java8'.
According to this issue …
> When using openapi-client with date field the java.time.LocalDate is not imported

- generators/client/templates/angular/src/main/webapp/app/shared/util/datepicker-adapter.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-detail.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.module.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity.model.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity.service.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/enumerations/enum.model.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/ng_validators.ejs
- generators/entity-client/templates/angular/src/test/javascript/e2e/entities/entity-page-object.ts.ejs
- generators/entity-client/templates/angular/src/test/javascript/e2e/entities/entity.spec.ts.ejs
- generators/entity-client/templates/angular/src/test/javascript/spec/app/entities/entity-management-delete-dialog.component.spec.ts.ejs
- generators/entity-client/templates/angular/src/test/javascript/spec/app/entities/entity-management-detail.component.spec.ts.ejs
- generators/entity-client/templates/angular/src/test/javascript/spec/app/entities/entity-management-update.component.spec.ts.ejs
- generators/entity-client/templates/angular/src/test/javascript/spec/app/entities/entity-management.component.spec.ts.ejs
- generators/entity-client/templates/angular/src/test/javascript/spec/app/entities/entity-management.service.spec.ts.ejs
This PR fixes default datetime problem introduced by #11043 and polishes entites in Angular:
* after #11043 `Instant` and `ZonedDateTime` fields are populated with default value both if creating and if updating entity
* this seems to affect only Angular part, in React default value is assigned only if `isNew` is `true`
* correct is to assign default value only if creating entity also in Angular
* moved `Instant` and `ZonedDateTime` default value assignments inside route subscription and assigning these default values only if creating entity in Angular, using condition `if (!entity.id) {`
* removes one `eslint-disable` after applying correct `ejs` if condition
* fixes `eslint` warning if entity contains `LocalDate` field and doesn't contain neither `Instant` nor `ZonedDateTime` field
* …
> Angular entities: fix default datetime and polish dates and templates

- generators/server/prompts.js
- generators/server/templates/src/main/java/package/config/ReactiveSecurityConfiguration.java.ejs
This is a work-in-progress. I created a new project with this branch and made it so login works. See https://github.com/mraible/jhipster-reactive-monolith-oauth2/pull/1 for remaining TODOs.
This PR will eventually contribute to the OAuth / OIDC support for reactive apps, which is being tracked by …
> Add OAuth 2.0 Support for Reactive Monoliths

- generators/gae/index.js
I realized that there's two unnecessary commands printed to the logs when we run the GAE sub-generator. The `maven clean` and `gradle thinReslove` goals not necessary anymore. 
Related to #10420
> Simplify Maven and Gradle Deployment Commands in GAE Subgenerator

- generators/server/prompts.js
- generators/server/templates/src/main/java/package/config/ReactiveSecurityConfiguration.java.ejs
This reverts jhipster/generator-jhipster#11049 since OAuth 2.0 support is not ready for reactive options. See https://github.com/mraible/jhipster-reactive-monolith-oauth2/pull/1 for current work-in-progress and issues.
> Revert "Add OAuth 2.0 Support for Reactive Monoliths"

- Dockerfile
- generators/generator-constants.js
Already updated:
https://github.com/jhipster/generator-jhipster/commit/ce52215f229a7ba6c4b907c143d434b0ae58eb45
https://github.com/jhipster/generator-jhipster/commit/3f45e7c132cac25f549507ed863f15fca5e310ec
https://github.com/jhipster/generator-jhipster/commit/edb5bff7fe908115e1127dbe47449f6c77ab02c1
https://github.com/jhipster/generator-jhipster/commit/40ba1fb3bfdcca120828fa5ae07d803d341e65b8 …
> Update node to version 12.14.0 LTS

- .github/PULL_REQUEST_TEMPLATE.md
-   N/A: ~[ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green~
> remove mention to Travis in the PR template [skip ci]

- generators/server/templates/src/main/java/package/web/rest/AccountResource.java.ejs
- generators/server/templates/src/test/java/package/web/rest/AccountResourceIT.java.ejs
* Return always 200/OK even when a user with the mail doesn't exist
* Log the attempt as warning such that one could add monitoring e.g. to detect multiple attempts
@cbornet Not sure if the reactive part is the most elegant way to do that in the reactive world, but I didn't found something better. So your review is really appreciated.
closes #11019
> do not expose which email exists when requesting password reset

- generators/server/index.js
If we generate a jhipster application with no cache: `"cacheProvider": "no"` in `.yo-rc.json` (note that there is no `this.enableHibernateCache` field)
And then if we run again `jhipster` to regenerate the app with this config, there is the prompt and we have to answer the questions from "yeoman form" again.
This means that the statement....
`this.enableHibernateCache = configuration.get('enableHibernateCache') && !['no', 'memcached'].includes(this.cacheProvider);`
...We have `this.enableHibernateCache` assigned to `undefined` (`undefined` && `false` gives `undefined`)
So in this PR I don't take into consideration `enableHibernateCache` to compute `serverConfigFound` (used to display the prompt or not)
I'm not sure if it is the right way to solve this.
We could also think to do something …
> Use the .yo-rc.json to generate the app when no cache provider is configured

- cli/cli.js
- cli/import-jdl.js
- cli/jhipster.js
- cli/run-yeoman-process.js
- cli/utils.js
Part of https://github.com/jhipster/generator-jhipster/issues/10963
- error behavior changed from terminate the process to don't terminate.
- fatal has the old error behavior.
- Changed all uses of logger.error to logger.fatal.
> Change cli logger.error behavior and implement logger.fatal.

- generators/client/templates/angular/src/main/webapp/app/core/core.module.ts.ejs
We specify icons in [font-awesome-icons.ts.ejs](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/app/core/icons/font-awesome-icons.ts) to enable tree-shaking, but we also import the entire icon pack.  The full icon pack import was added in v6.3.0 in https://github.com/jhipster/generator-jhipster/pull/10254 during a font-awesome upgrade
From the [angular-fontawesome](https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/usage/icon-library.md) docs:
>You can also import entire icon styles. But be careful! This way of importing icons does not support tree-shaking, so all icons from the imported package will end up in the bundle.
With this change, we save quite a bit in the bundle
```git
- …
```
> fix angular fontawesome tree-shaking

- generators/cleanup.js
In v6.6.0 cleanup references to `DefaultProfileUtil.java` and `RandomUtil.java` include extra redundant `package` subfolder and these files are not deleted. This PR fixes paths in cleanup so that in the next version of the JHipster these files are deleted.
> Fix DefaultProfileUtil.java and RandomUtil.java cleanup

- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity.model.ts.ejs
If using self referencing entity like
```
entity MyEntity {
name String required
}
MyEntity{childEntity} to MyEntity{parentEntity(name)}
}
```
then Visual Studio Code complains in generated file `src\main\webapp\app\shared\model\my-entity.model.ts` in generated line (self import) `import { IMyEntity } from 'app/shared/model/my-entity.model';` : **Import declaration conflicts with local declaration of 'IMyEntity'.ts(2440)**
Webpack compiles this file successfully.
But it's better not to generate self import so that Visual Studio Code doesn't show error any more.
This PR removes this self import.
-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) …
> Fix self referencing entities in Angular

- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.ts.ejs
PR #11043 introduced Sonar code smell "Functions should not have identical implementations" for Angular part (default datetime setter functions) for entities that have more than 1 `Instant`/`ZonedDateTime` field.
For React part #11043 didn't create helping functions. This PR changes Angular part implementation similar to React part implementation and this removes code smell from Angular part. …
> Fix default Instant/ZonedDateTime Sonar code smell in Angular

- generators/client/templates/angular/.huskyrc.ejs
- generators/client/templates/angular/angular.json.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/audits/audits.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/health/health.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/logs/log.model.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/auth/account.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/auth/auth-jwt.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/tracker/tracker-activity.model.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/layouts/error/error.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/layouts/navbar/navbar.component.html.ejs
- generators/client/templates/angular/src/main/webapp/content/scss/global.scss.ejs
- generators/client/templates/angular/src/main/webapp/manifest.webapp.ejs
- generators/client/templates/angular/src/test/javascript/jest.conf.js.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/account/password/password-strength-bar.component.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/account/settings/settings.component.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/admin/audits/audits.component.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/core/user/account.service.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/core/user/user.service.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/shared/alert/alert-error.component.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/shared/login/login.component.spec.ts.ejs
- generators/client/templates/angular/webpack/utils.js.ejs
- generators/client/templates/angular/webpack/webpack.dev.js.ejs
- generators/client/templates/angular/webpack/webpack.prod.js.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.ts.ejs
- generators/entity-client/templates/angular/src/test/javascript/e2e/entities/entity.spec.ts.ejs
This PR:
* tries to achieve consistent 2 or 4 space indentation inside each specific file to make templates as readable as possible
* fixes one corrupted licence header
* uses standard spacing in 2 differently spaced license headers
> Polish spacing and fix one broken license header in Angular

- generators/server/templates/src/main/resources/config/couchmove/changelog/V0.1__initial_setup/user__anonymoususer.json.ejs
The initial changeset for CouchBD contains the same email address for the administrative and the anonymous user. This PR fixes it.
> Fix duplicate email adress.

- generators/ci-cd/templates/github-ci.yml.ejs
This add a validation action to our generated github actions which validates the gradle wrapper checksum. Will see if we can do it for the generator too. For details see here https://github.com/gradle/wrapper-validation-action
> add gradle wrapper validation step to generated ci

- generators/client/needle-api/needle-client-webpack.js
- test/needle-api/needle-client-webpack.spec.js
> Make webpack copyExternalAssets needle function usable

- generators/common/templates/gitattributes.ejs
Add CMD ( `.cmd` ) and PowerShell ( `.ps1` ) file extensions to `.gitattributes` template, forcing CRLF.
Just for Windows users who runs `mvnw.cmd` directly. 😄 
> Add Windows-only script formats to .gitattributes template

- generators/server/templates/src/main/resources/config/application-dev.yml.ejs
- generators/server/templates/src/main/resources/config/application-prod.yml.ejs
- generators/server/templates/src/test/resources/config/application.yml.ejs
See https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2-Release-Notes : 
>  Spring Boot now lets Hibernate chose the dialect to use rather than applying a default dialect based on the detected database. If you are interested by this feature, please make sure you don’t specify the database platform explicitly (i.e. via spring.jpa.database or spring.jpa.database-platform).
> If you had a dialect configured previously, you may want to remove your customization.
I only kept the dialects that have been overridden in jhipster framework. …
> Proposal: Remove explicit definition of database platform in Spring configuration

- generators/generator-base.js
Related to https://github.com/hipster-labs/jhipster-daily-builds/issues/28 and https://github.com/hipster-labs/jhipster-daily-builds/pull/37
Trying to get the Windows Daily build working, I noticed that sometimes ShellJS fails when trying to create the keystore directory. This is a workaround to address that. For reference, the error that could be seen is,
```
events.js:187
throw er; // Unhandled 'error' event
^
Error [ShellJSInternalError]: EEXIST: file already exists, mkdir 'C:\Users\VssAdministrator\app\src\main\resources'
at Object.mkdirSync (fs.js:823:3)
at mkdirSyncRecursive (C:\Users\VssAdministrator\generator-jhipster\node_modules\shelljs\src\mkdir.js:32:6)
at mkdirSyncRecursive (C:\Users\VssAdministrator\generator-jhipster\node_modules\shelljs\src\mkdir.js:29:3)
at …
```
> Workaround for ShellJS Directory Creation Problem on Windows

- generators/server/templates/src/main/java/package/web/filter/RefreshTokenFilter.java.ejs
Related to https://github.com/hipster-labs/jhipster-daily-builds/issues/28
I observed that sometimes on [Windows builds the `ms-ngx-gateway-uaa` test fails](https://dev.azure.com/hipster-labs/jhipster-daily-builds/_build?definitionId=41&_a=summary) due to the following error. 
```
[INFO] 
[ERROR] Failures: 
[ERROR]   OAuth2AuthenticationServiceTest.testRefreshGrantNoRefreshToken:221 Expected org.springframework.security.oauth2.common.exceptions.InvalidTokenException to be thrown, but nothing was thrown.
[INFO] 
[ERROR] Tests run: 66, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] Total time:  36.589 s
[INFO] …
```
> Increase Number of Seconds to Expiry of Access Tokens to 90 Seconds

- generators/app/index.js
- generators/client/index.js
- generators/common/index.js
- generators/entity-client/index.js
- generators/entity-i18n/index.js
- generators/entity-server/index.js
- generators/entity/index.js
- generators/languages/index.js
- generators/server/index.js
- generators/spring-controller/index.js
- generators/spring-service/index.js
- test/blueprint/multiple-app-blueprints.spec.js
Blueprinted app generator is forwarding 'options.fromBlueprint=true' to sub-generators.
This makes original generators act like they are blueprints, ignoring loading of blueprints.
This PR makes fromBlueprint option that was need by blueprint not necessary anymore.
It uses calculated fromBlueprint introduced at https://github.com/jhipster/generator-jhipster/pull/10664
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md …
> Fix sub-generators with app blueprint

- generators/server/templates/src/main/resources/config/application-dev.yml.ejs
>**Management Center Default Context Path**
Before version 3.10, default context path was /mancenter, so you would access Hazelcast Management Center by using http://localhost:8080/mancenter. Starting with version 3.10, it is changed to /hazelcast-mancenter, so you can access it by using http://localhost:8080/hazelcast-mancenter.
https://hub.docker.com/r/hazelcast/management-center/
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/ …
> fix hazelcast mancenter context path [ci skip]

- test-integration/scripts/20-docker-compose.sh
- test-integration/scripts/24-tests-e2e.sh
Cassandra containers took a lot of memory
and as the integration tests use testcontainers,
it's not good to start Cassandra 2 times
Related to https://github.com/jhipster/generator-jhipster/issues/11169
_____
> CI: don't start Cassandra containers before launching tests

- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management-update.tsx.ejs
Use the first locale available to set the langKey in user creation.
Otherwise there is an exception while saving the user (validation on langKey, which is required)
> Fix langkey react

- generators/generator-base-private.js
- test/generator-base-private.spec.js
If cloning `generator-jhipster` current master in Windows and running `npm test` (tested in Git Bash) then tests are failing with error:
```
853 passing (14m)
4 failing
1) Generator Base Private
getEntityParentPathAddition
when passing foo/bar
returns ../../:
AssertionError: expected '..\\../' to equal '../../'
+ expected - actual
-..\../
+../../
at Context.<anonymous> (test\generator-base-private.spec.js:295:81)
at processImmediate (internal/timers.js:439:21)
2) Generator Base Private
getEntityParentPathAddition
when passing ../foo
returns an empty string:
AssertionError: expected '..\\../' to equal ''
+ expected - actual
-..\../
at Context.<anonymous> (test\generator-base-private.spec.js:300:80)
at processImmediate (internal/timers.js:439:21)
3) Generator Base Private …
```
> Fix getEntityParentPathAddition logic and tests in Windows

- generators/client/needle-api/needle-client-angular.js
- generators/client/templates/angular/src/main/webapp/app/admin/audits/audits.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/configuration/configuration.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/gateway/gateway.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/health/health.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management-delete-dialog.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management-detail.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management-update.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/core/icons/font-awesome-icons.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-delete-dialog.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-detail.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.html.ejs
- generators/generator-base.js
- generators/utils.js
- test/generator-base-private.spec.js
- test/needle-api/needle-client-angular.spec.js
We are using Font Awesome icons instead of Glyphicons for a long time, so changed variable names and documentation from `glyphicon` --> `icon`.
In some places were still used `[icon]` and `[fixedWidth]`, replacing those with `icon` and `fixedWidth`.
Added needle function to add new icon to imported icons list and use this to import new icons on needle functions related to icons.
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONT …
> Add icon function to needle API and polish icons

- generators/server/templates/src/main/java/package/service/UserService.java.ejs
- generators/server/templates/src/main/java/package/web/rest/UserResource.java.ejs
While working on the neo support and trying reactive option idea and sonar pointed out some issues. This fixes 
* Throwing instead of returning a mono in flatmap
*  (sonar) using primitive boolean if statement with boolean objects (for real there won't be a npe but aiming for a A grade in sonar)
> use Mono.error instead of throwing in flatmap

- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management-update.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/shared/model/user.model.ts.ejs
1)
When we create a new user, the "activated" checkbox should be checked and disabled (as in angular version). In the backend the activated field from a user is set to `true` during creation.
2)
This also fix (by using checked={user.activated} a bug when we first "view" a deactivated user and then go to the user creation page. The activated checkbox state is the previous one. I'm not sure this is the best way to fix this though.. (The user state in Redux is updated many times... causing this bug I think).
> fix: check activated on user creation and fix activated state handling

- generators/utils.js
If in Windows is used Git `autocrlf` and project is regenerated after committing to Git then those needles which content has more than 1 line are added multiple times to templates.
This PR fixes that.
> Fix needles with multiple lines in Windows if Git autocrlf is used

- .github/MAINTAINERS_REPLY_TEMPLATES/DONT_COMMENT_ON_OLD_ISSUE.md
- .github/MAINTAINERS_REPLY_TEMPLATES/GUIDELINES_NOT_FOLLOWED.md
- .github/MAINTAINERS_REPLY_TEMPLATES/USE_STACK_OVERFLOW.md
This adds a Gitter channel link to our reply templates 😄 
> Add Gitter Channel Links to Reply Templates [ci-skip]

- generators/client/templates/react/src/test/javascript/spec/app/shared/auth/private-route.spec.tsx.ejs
Fixed two typos in `private-route.spec.tsx.ejs`.
I think that [skip ci] should be observed with this commit as it only changes a couple of character in a test description.
> Fix typos in react test generation

- generators/server/templates/src/main/java/package/web/filter/RefreshTokenFilter.java.ejs
Fixes #11236
Somehow in Windows machines the token isn't expired when checking but do expire within 30 seconds after the check. So I believe we need to add this condition for throwing the `InvalidTokenException`. 
> Add Condition for Refresh Token Nearing Expiry

- generators/server/templates/build.gradle.ejs
- generators/server/templates/pom.xml.ejs
- generators/server/templates/src/test/java/package/AbstractCassandraTest.java.ejs
- generators/server/templates/src/test/java/package/CassandraKeyspaceIT.java.ejs
- generators/server/templates/src/test/resources/config/application.yml.ejs
Remove cassandra unit dependency.
Historically, `EmbeddedCassandraServerHelper.startEmbeddedCassandra()` feature was used and it was the way to have a running cassandra to perform tests.
Then; testcontainers has been used to start a cassandra instance (jhipster/generator-jhipster@9951387)
Today the only feature we use from cassandra unit is to load CQL files through `dataLoader.load(new ClassPathCQLDataSet(cqlDir + fileName, false, false, CASSANDRA_UNIT_KEYSPACE));`
This dependency is quite heavy, it pulls `org.apache.cassandra:cassandra-all` which is the whole cassandra server that we don't use .
> refactor: remove cassandra unit

- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management-delete-dialog.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management.tsx.ejs
Fix sorting users on React.
The current sort wasn't "sync" to the parameters in the URL.
When the url has 'asc', then 'desc' sorting was applied (and the opposite).
The sort is working for entities so I applied the same logic for users (just move a line).
> fix: sort on users

- generators/client/templates/angular/package.json.ejs
- generators/client/templates/angular/webpack/webpack.prod.js.ejs
webpack-visualizer-plugin is no longer maintained for last 3 years and it raises warnings during `npm install`:
~~~
npm WARN deprecated core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
~~~
Fix #11265
-   [ ] Tests are added where …
> Replace obsolete webpack-visualizer-plugin by webpack-bundle-analyzer.

- generators/server/templates/build.gradle.ejs
Related to #11249
I've noticed that I've mistakenly committed the wrong quotes and this [gives an error](https://github.com/jhipster/generator-jhipster/issues/11249#issuecomment-583884467) in Gradle when deploying to GAE. This PR corrects that. 
> Use Correct Quotes for GAE Deployments in Gradle

- generators/server/templates/src/main/resources/config/liquibase/changelog/initial_schema.xml.ejs
When ext: namespace is applied for open tag, the end tag gets generated as invalid - missing the namespace.
> fix invalid loadData end tag with namespace

- generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
- generators/server/templates/build.gradle.ejs
- generators/server/templates/pom.xml.ejs
- generators/server/templates/src/main/resources/config/liquibase/changelog/initial_schema.xml.ejs
- generators/server/templates/src/main/resources/logback-spring.xml.ejs
- generators/server/templates/src/test/resources/logback.xml.ejs
In conditions like devDatabaseType === 'X' || prodDatabaseType === 'X' the first part is useless because when devDatabaseType is valued with X (e.g. mysql) and X is different from h2Disk and h2Memory, prodDatabaseType is always valued with X too
> Clean confusing conditions on both dev and prod database types

- .github/workflows/angular.yml
- .github/workflows/generator.yml
- .github/workflows/gradle-wrapper-validation.yml
- .github/workflows/react.yml
- azure-pipelines.yml
- generators/ci-cd/templates/github-ci.yml.ejs
Sometime back I've added support for `[skip ci]` and `[ci skip]` in our GitHub CI builds. But I've overlooked the fact that pull request builds should be handled a bit differently. I noticed this once @pascalgrimaud pointed this out at; https://github.com/jhipster/generator-jhipster/pull/11291#issuecomment-585116946
This commit corrects that and now when you add [skip ci] or [ci skip] in the pull request title the GitHub Actions will not be triggered. 
If you see any issues with this feel free to ping me again. :smile: 
@pascalgrimaud 
-   [x] Documentation is …
> Add Support for Pull Request CI Skipping for GitHub Actions

- generators/server/templates/src/main/java/package/aop/logging/LoggingAspect.java.ejs
This lightens the log messages a lot (we don't need to specify the intercepted class anymore, the method alone is enough).
Also, this log can now be tuned per intercepted class.
> Replace LoggingAspect's logger by the logger of the intercepted class.

- generators/server/files.js
- generators/server/prompts.js
- generators/server/templates/src/main/docker/app.yml.ejs
- generators/server/templates/src/main/docker/redis-cluster.yml.ejs
- generators/server/templates/src/main/docker/redis/Redis-Cluster.Dockerfile.ejs
- generators/server/templates/src/main/docker/redis/connectRedisCluster.sh.ejs
- generators/server/templates/src/main/java/package/config/CacheConfiguration.java.ejs
- generators/server/templates/src/main/resources/config/application-dev.yml.ejs
- generators/server/templates/src/main/resources/config/application-prod.yml.ejs
- test/utils/expected-files.js
It's the dev part of https://github.com/jhipster/generator-jhipster/issues/11129
Depends on: https://github.com/jhipster/jhipster/pull/571
By default, it will use the single node. You need to update the application-dev.yml or application-prod.yml to use Redis Cluster. The related properties are commented.
Once it's enabled, you can start the cluster, using `docker-compose -f src/main/docker/redis-cluster.yml up -d` :
Here when playing with the application, and check the different KEYS in my :hamburger: Redis Cluster : 
_____
-   [ ] Documentation is added/updated where …
> Add property to use Redis Cluster

- generators/kubernetes/files.js
- generators/kubernetes/index.js
- generators/kubernetes/templates/README-KUBERNETES.md.ejs
- generators/kubernetes/templates/kubectl-apply.sh.ejs
- generators/kubernetes/templates/kustomize/kustomization.yml.ejs
- generators/kubernetes/templates/kustomize/patch/istio-label.yml.ejs
- generators/kubernetes/templates/kustomize/patch/istio-namespace.yml.ejs
- generators/kubernetes/templates/registry/consul.yml.ejs
- generators/kubernetes/templates/registry/jhipster-registry.yml.ejs
- generators/kubernetes/templates/skaffold/skaffold.yml.ejs
- this doesn't change the existing flow
- kustomize template support is added on top (way to externalize things)
- apply changes through either -f or -k or -s option
- added support for skaffold 
- running skaffold dev turns the cwd to a CI/CD space 
- skaffold will use jib for build and kustomize for deploy
> kustomize template support

- generators/server/templates/src/main/java/package/domain/AbstractAuditingEntity.java.ejs
Updated class-level javadoc string to better reflect field names that are "touched" on create/update.
> Improve class-level javadoc for `domain/AbstractAuditingEntity.java`

- generators/entity-client/files.js
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity.model.ts.ejs
- generators/entity-client/templates/angular/src/test/javascript/spec/app/entities/entity-management.service.spec.ts.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.model.ts.ejs
- generators/entity-server/files.js
- generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
- generators/entity-server/templates/src/main/java/package/service/dto/EntityDTO.java.ejs
- generators/entity-server/templates/src/main/java/package/service/mapper/EntityMapper.java.ejs
- generators/entity-server/templates/src/test/java/package/domain/EntityTest.java.ejs
- generators/entity-server/templates/src/test/java/package/service/dto/EntityDTOTest.java.ejs
- generators/entity-server/templates/src/test/java/package/service/mapper/EntityMapperTest.java.ejs
- generators/entity/index.js
- generators/generator-base-private.js
- generators/generator-base.js
- test-integration/samples/.jhipster/DocumentBankAccount.json
- test-integration/samples/.jhipster/EmbeddedOperation.json
- test-integration/scripts/11-generate-entities.sh
Hello guys,
Following jhipster/generator-jhipster#7944 and jhipster/generator-jhipster#9341 for supporting rich document models on document databases (MongoDB and Couchbase), I added a new embedded option that enables subdocuments as explained here : jhipster/generator-jhipster#7944 (comment)
This PR needs https://github.com/jhipster/jhipster-core/pull/429
> Embedded entities for document databases (Couchbase, MongoDB)

- generators/generator-base.js
- generators/needle-api.js
- generators/server/needle-api/needle-server-logback-spring.js
- generators/server/templates/src/main/resources/logback-spring.xml.ejs
- test/needle-api/needle-server-logback-spring.spec.js
PR to fix #11146 
I created a public method `addLoggerForLogbackSpring()` which takes a logname and a level log into parameters to create a new logger inside logback-spring.xml with the needle` jhipster-needle-logback-add-log`.
> Create a needle to add logger inside logback-spring.xml on server-side

- generators/client/templates/angular/webpack/webpack.dev.js.ejs
- generators/client/templates/react/webpack/webpack.dev.js.ejs
Add some comments on how to disable ghostMode in BrowserSync. 
Related to https://github.com/jhipster/generator-jhipster/issues/11116
> Add Comments about BrowserSync ghostMode Disabling [ci skip]

- generators/client/files-angular.js
- generators/client/templates/angular/src/main/webapp/app/account/password/password.route.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/account/sessions/sessions.route.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/account/settings/settings.route.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/app-routing.module.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/user/user.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/shared/constants/authority.constants.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/admin/user-management/user-management-detail.component.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/admin/user-management/user-management-update.component.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/core/user/account.service.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/core/user/user.service.spec.ts.ejs
- generators/client/templates/react/src/test/javascript/spec/app/modules/administration/user-management/user-management.reducer.spec.ts.ejs
- generators/client/templates/react/src/test/javascript/spec/app/shared/auth/private-route.spec.tsx.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.route.ts.ejs
- test/utils/expected-files.js
As requested by @pascalgrimaud [here](https://github.com/jhipster/jhipster-vuejs/pull/535#issuecomment-577047345) I took a look on how authority are handled in client applications.
While a constant is defined and used in the react application, it's still plain string in the Angular app.
This PR should fix this situation. 
I have still several question: in the react application the authorities are defined as [a javascript object](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/react/src/main/webapp/app/config/constants.ts.ejs). Should I change it to a typescript enumeration to have more consistency between client applications ? If I do so, should I left this constant in the constants.ts (enum and constant are quite different) or should I create …
> Add authority enum to angular client application

- generators/kubernetes/templates/deployment.yml.ejs
this will avoid scheduling pods with the same app label on one node
fix #11186
> adds PodAntiAffinity to k8s deployments

- generators/entity-client/templates/angular/src/main/webapp/app/entities/enumerations/enum.model.ts.ejs
String enums should be initialized to avoid problems when comparing them with backend enums, even when no custom value is specified.
> FIX string enum initialization on angular

- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
- generators/server/templates/src/test/java/package/web/rest/AccountResourceIT.java.ejs
- generators/server/templates/src/test/java/package/web/rest/TestUtil.java.ejs
- generators/server/templates/src/test/java/package/web/rest/UserJWTControllerIT.java.ejs
- generators/server/templates/src/test/java/package/web/rest/UserResourceIT.java.ejs
The constant TestUtil.APPLICATION_JSON is not really useful, it's just an indirection to MediaType.APPLICATION_JSON
> Replace TestUtil.APPLICATION_JSON by MediaType.APPLICATION_JSON

- generators/generator-constants.js
- generators/server/index.js
- generators/server/templates/build.gradle.ejs
- generators/server/templates/pom.xml.ejs
If the JHipster team feels this is something worth switching to; I can make the required changes.
**Reference**: https://blogs.oracle.com/developers/oracle-database-client-libraries-for-java-now-on-maven-central
I believe `[jhipster-framework]` : (https://github.com/jhipster/jhipster/pull/606) will also need updating in the bom in addition to changes in the PR, however I'm sure I can use some help from core team to identify all places needing change.
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CON …
> Use Oracle Database Client libraries from Maven Central

- cli/utils.js
- generators/generator-base-blueprint.js
Current yeoman-environment lookup looks for generators at __dirname's '../../' and '../../../../'.
At the worst case, when running jhipster locally installed it will look at:
- {cwd}/node_modules/yeoman-environment/lib/../../../../
=> {cwd}/../*
So it will lookup for generators/blueprint at current folder siblings.
This can be useful for development but I don't think we should have this behavior by default.
With filterPath it will only consider '../../' and '../../../../' if and only if they are inside node_modules folder.
Ex:
- {cwd}/node_modules/yeoman-environment/lib/../../
=> {cwd}/node_modules/*
- {cwd}/node_modules/generator-jhipster/node_modules/yeoman-environment/lib/../../../../
=> {cwd}/node_modules/*
- {cwd}/node_modules/yeoman-environment/lib/../../../../
=> …
> Pass filterPaths option to lookup

- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.reducer.ts.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs
- generators/entity-client/templates/react/src/test/javascript/spec/app/entities/entity-reducer.spec.ts.ejs
Fix two points (backend calls when delete and update react entities) on 3 for #11321 
> Fix two backend calls when delete and update react entities

- generators/ci-cd/index.js
- generators/ci-cd/prompts.js
- generators/ci-cd/templates/circle.yml.ejs
- test/ci-cd.spec.js
This adds support for generation of CircleCI 2.0 configurations.
Fixes #10671
> Add CircleCI back to the Main Generator

- generators/server/templates/src/main/java/package/config/ReactiveSecurityConfiguration.java.ejs
This fixes an issue @murdos surfaced when implementing entity generation for reactive apps.
> Make reactive microservices stateless

- generators/server/templates/src/main/resources/config/application-dev.yml.ejs
- generators/server/templates/src/main/resources/config/application-prod.yml.ejs
Add a small comment in the configuration files to clarify which cache eviction method that we use in Caffeine.
Fixes #11462
> Add Comment to Clarify Caffeine Cache Eviction Method

- CONTRIBUTING.md
Add a small blob to highlight guidelines for regular contributors and core team members. This was discussed through our mailing list; https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jhipster-dev/xfrODe_g14U/YSoDESxUAAAJ
Fixes #11471
> Add Core/Regular Contributor Guidelines [ci skip]

- generators/server/files.js
- generators/server/templates/src/main/java/package/config/OpenApiConfiguration.java.ejs
- test/utils/expected-files.js
Fixes #9752
By using springfox `RequestHandlerSelectors` it is possible to separate scaffolded endpoints from openapi filtering by base java package. Even if they are sharing the same prefix (`/api`) this configuration will 2 different specs in the swagger ui dropdown menu.
> separate springfox specs for jhipster and openapi controllers

- generators/generator-constants.js
- generators/server/templates/build.gradle.ejs
This PR updates to gradle 6.3 and with that also supports java 14.
For details see https://docs.gradle.org/6.3/release-notes.html
> update to gradle 6.3

- generators/server/templates/src/main/docker/mongodb-cluster.yml.ejs
- generators/server/templates/src/main/docker/mongodb/scripts/init_replicaset.js.ejs
- test/templates/compose/04-mongo/src/main/docker/mongodb-cluster.yml
others points fixed in purpose testing and running the project generated :
- add replica set to configserver => to be able to attach configdb to mongo router
- start node with --shardsvr => to be able to register replicate to mongodb.
- and modify init_replicateset.js to handle the port 27018 (default port for shardsvr)
fix #11519
> fix (issue-11519) : remove related options to old storage engine mmapv1

- generators/server/templates/src/main/resources/config/application-prod.yml.ejs
- Otherwise, when uncommenting that code, it will not be formatted with 2 spaces, as the rest of the file (until Prettier is run)
- This also fixes the alias of the key, which should be "selfsigned", like in the "tls" profile
> Format the YAML comment with 2 spaces

- generators/common/templates/sonar-project.properties.ejs
Fix vulnerabilities for sonar jhipster sample 
[Persistent entities should not be used as arguments of "@RequestMapping" methods
](https://sonarcloud.io/organizations/jhipster/rules?open=java%3AS4684&rule_key=java%3AS4684)
> Jhipster Sample fix vulnerabilities : Change Key squid:s4684 to java:s4684

- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.model.ts.ejs
This prevents a conflict between import and local declarations.  For example, `person.model.ts` should not try to import `IPerson` from itself when it is declared in that file.
Already done for Angular [here](https://github.com/jhipster/generator-jhipster/blob/99eaa8ae078dd806a229890b16dbb6c1654547e3/generators/entity-client/templates/angular/src/main/webapp/app/entities/entity.model.ts.ejs#L29)
Fix #11549 …
> skip importing entity into its own model

- generators/server/files.js
- generators/server/templates/src/main/java/package/config/RestTemplateConfiguration.java.ejs
- generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs
- generators/server/templates/src/main/java/package/security/oauth2/UaaSignatureVerifierClient.java.ejs
- generators/server/templates/src/main/java/package/security/oauth2/UaaTokenEndpointClient.java.ejs
- generators/server/templates/src/main/java/package/web/filter/RouteDetectorFilter.java.ejs
When a gateway application with no service discovery is generated we have a RouteDetectorFilter.java file which refers this method.
Fixes #11551
> Add Missing Method in SecurityConfiguration.java.ejs

- generators/generator-transforms.js
Prettier lookup for plugins at same level node_modules repository.
Workaround prettier-java failing with npm changing it's location.
Fixes https://github.com/jhipster/generator-jhipster/issues/11533
> Register prettier-java plugin.

- README.md
This adds the Windows Daily Builds badge to readme now that the build is working.
Related to https://github.com/hipster-labs/jhipster-daily-builds/issues/48
> Adds the Windows Daily Builds Badge to README.md [skip ci]

- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
To have clean database state we call deleteAll for nosql databases. We forgot that for neo4j until now.
> fix neo4j integration test to have clean database state

- test-integration/scripts/20-docker-compose.sh
This should fix the remaining issue in daily builds regarding e2e tests as no database is available
[ci-skip]
> start neo4j docker compose to run e2e tests

- generators/ci-cd/templates/.gitlab-ci.yml.ejs
This adds docker in docker service to our .gitlab-ci.yml so that the generated gitlab configuration can run tests on GitLab ci.
Reference: https://www.testcontainers.org/supported_docker_environment/continuous_integration/gitlab_ci/
Fixes #11601
> Adds Docker in Docker Service to .gitlab-ci.yml.ejs

- generators/ci-cd/index.js
- generators/ci-cd/templates/.gitlab-ci.yml.ejs
As per our discussion at https://github.com/jhipster/generator-jhipster/pull/11602#issuecomment-616359536 I am opening this PR to increase the speed of the GitLab pipeline. This refactors the code such that the dind service is initiated only within the integration tests. 
Related to https://github.com/jhipster/generator-jhipster/issues/11601
> GitLab Build Speedup: DIND only within Integration Tests

- generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
- generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs
- generators/server/templates/src/main/resources/logback-spring.xml.ejs
- test/needle-api/templates/src/main/resources/config/liquibase/changelog/dummy_changelog.xml.ejs
There's no need to repeat "do not remove" everywhere. Besides people can remove them if they want to remove JHipster.
> remove useless comments

- generators/ci-cd/templates/.gitlab-ci.yml.ejs
This is related to https://github.com/jhipster/generator-jhipster/pull/11603. We've added the DIND initialization in the wrong place. We have to add it within the integration tests as pointed out by @ecostanzi at https://github.com/jhipster/generator-jhipster/pull/11584#discussion_r412358519
Related to #11603, #11602 and #11601
> Fix Mistake in Adding DIND Support for GitLab CI with Gradle

- generators/server/templates/build.gradle.ejs
This adds Testcontainers as a test dependency for Gradle + Redis configuration. I've added the `database-common` artifact just as we do in `Cassandra`. 
@bsideup: Hey, if you don't mind me asking a quick question; I am wondering what is the difference between; `org.testcontainers:database-commons` vs `org.testcontainers:testcontainers` dependencies?  
Fixes https://github.com/jhipster/generator-jhipster/issues/11615 …
> Adds Testcontainers as a Test Dependency for Gradle + Redis Configuration

- .github/workflows/webflux.yml
- generators/server/templates/src/main/java/package/web/rest/errors/ExceptionTranslator.java.ejs
- test-integration/samples/webflux-psql/.yo-rc.json
I've also disabled `webflux-couchbase-session` since there are already 2 other webflux-couchbase integration tests.
> Integration test for webflux and R2DBC

- generators/client/templates/angular/webpack/webpack.common.js.ejs
This removes the es2015 build configuration from webpack so that the default fesm5 is used as I've mentioned in https://github.com/jhipster/generator-jhipster/issues/11566#issuecomment-612653012. 
We could use this until the firefox bug is fixed which I think won't be long since the probable duplicate is moved to critical stage (https://bugzilla.mozilla.org/show_bug.cgi?id=1628719)
Fixes #11566 …
> Remove es2015 from Webpack Configuration

- generators/server/templates/src/main/java/package/domain/PersistentAuditEvent.java.ejs
This pr adds missing property annotations. Currently the Map can't be converted without a custom converter, going to check how to best do that.
> add missing property annotations

- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs
This fixes an error which has been introduced at revision 448d48ec9. When there is a one-to-one relationship to the user entity the correct user is not passed in the request object; rather a null value is passed.
Fixes #11514
> Fix for Null Constraint Violation Error

- generators/server/templates/build.gradle.ejs
- generators/server/templates/pom.xml.ejs
Our CI tests have been very unreliable since we've enabled BlockHound on webflux apps.
I propose to disable BlockHound temporarily and I've open https://github.com/jhipster/generator-jhipster/issues/11599 so we don't forget to re-enable it once blocking issues has been resolved.
> Temporarily disable BlockHound to fix unstable webflux CI tests

- generators/server/templates/src/test/java/package/repository/CustomAuditEventRepositoryIT.java.ejs
As we don't support the data map property with neo4j we should not do assertions on it.
https://github.com/hipster-labs/jhipster-daily-builds/runs/619102137?check_suite_focus=true
> fix audit event repository test to not check data attributes for neo4j

- package.json
This updates the generator node version to 12.16.1 along with respective npm version.
Fixes: #11650
> Update Generator Node Version to 12.16.1

- generators/entity-server/files.js
- generators/entity/index.js
This PR adds reactive neo4j support to the entity server generator.
See https://github.com/hipster-labs/jhipster-daily-builds/runs/628447494?check_suite_focus=true for the failing builds. 
> support reactive neo4j within entity server generator

- generators/server/templates/src/main/java/package/config/OpenApiConfiguration.java.ejs
Reverts jhipster/generator-jhipster#11646
SpringFox 2.9.x has a mixture of java predicates and guava predicates.
> Revert "Fix OpenApiConfiguration to not use google.guava.predicates - which i…"

- generators/heroku/USAGE
- generators/heroku/index.js
- generators/heroku/templates/application-heroku.yml.ejs
The dev plan is quite slow, but the app starts. Right now only neo 3.5 is supported, therefore we don't allow to deploy a reactive/webflux application in that case.
For details https://elements.heroku.com/addons/graphenedb 
closes #11693
> support neo4j via graphene addon

- generators/heroku/USAGE
- generators/heroku/index.js
- generators/heroku/templates/system.properties.ejs
This PR adds a new prompt, which asks which java version to use for building and running the application.
See https://devcenter.heroku.com/articles/java-support#specifying-a-java-version for details
> support different java versions when deploying to heroku

- generators/server/templates/src/main/java/package/config/CacheConfiguration.java.ejs
Finally I found some time to integrate the custom prefixed cash key implementation. For details how keys for spring cache abstractions are generated look at the implementation in the jhipster lib.
https://github.com/jhipster/jhipster/pull/618
closes #9822
> use git hash or build information to prefix cache keys

- generators/server/files.js
- generators/server/templates/src/main/java/package/config/StaticResourcesWebConfiguration.java.ejs
- generators/server/templates/src/main/java/package/config/WebConfigurer.java.ejs
- generators/server/templates/src/test/java/package/config/StaticResourcesWebConfigurerTest.java.ejs
- generators/server/templates/src/test/java/package/config/WebConfigurerTest.java.ejs
Fix #11575 
Removing the usage of CachingHttpHeadersFilter for "/i18n/** ", "/content/** ", "/app/** " paths
I replace it by the usage of ResourceHandler  Configured in a specific WebConfigurer
Headers "Cache-Control","Pragma","Expires" put by CachingHttpHeadersFilter are overwriting by The ResourceHttpRequestHandler
> Fix cache header

- cli/cli.js
- cli/utils.js
- generators/generator-base-private.js
- generators/generator-base.js
- test/cli/cli-utils.spec.js
Implement blueprint auto install when it is passed as a parameter ex:
```
jhipster --blueprints vuejs
```
Or the blueprint already is registered at .yo-rc.json
Prompt to install blueprints cannot be added since it will conflict with blueprints with app generators (the generator has already started)
Closes https://github.com/jhipster/generator-jhipster/issues/11480
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) …
> Implement blueprint auto installation.

- generators/server/templates/src/main/java/package/web/rest/AccountResource.java.ejs
Usually our UI prevents sending forged data, but in case someone uses the api directly we write a user provided text to our logs. This may be used to forge log statements.
As it is not relevant which non existing email was used (e.g. detect bruce force attacks or so) I just removed the mail from the log statement instead of escaping it as it is not worth the effort I would say.
* https://sonarcloud.io/project/issues?id=jhipster-sample-application&open=AXB4zsKh1I-_jbRftkUh&resolved=false&types=VULNERABILITY
* https://owasp.org/www-community/attacks/Log_Injection
* https://www.baeldung.com/jvm-log-forging
-   [ ] …
> prevent potential log forging

- generators/generator-constants.js
- package.json
This sets the template and generator node engine version to >=10.20.1
Related to https://github.com/jhipster/generator-jhipster/pull/11656
> Downgrade node version to 10.20.1 in both templates and generator

- generators/entity/prompts.js
- generators/generator-base-blueprint.js
- generators/generator-base.js
This shouldn't have any behaviour changes.
Current implementation: 
```
this.env.error(`${msg}`);
```
Only generates a new error and emit the event on the environment.
https://github.com/yeoman/environment/blob/d8c706f3f2760d03b033d4c2ae393a894ce74389/lib/environment.js#L242-L250
According to https://nodejs.org/api/events.html#events_error_events.
There are 2 behaviours:
1 - When there isn't any error listener, the error is thrown.
2 - When there is an error listener, the event is emitted and the execution follows.
JHipster creates a new environment and doesn't register any error listeners.
So the behaviour is always 1.
If for some reason an error listener is registered, the execution will continue and unless a process.exit(1) is called. The error will be ignored.
See yo: …
> Change this.error() to throw error

- generators/utils.js
Fixes config synchronization with getAllJhipsterConfig.
When saving config with `this.config.set(‘foo’, ‘bar’);`
getAllJhipsterConfig will not read the updated config until next jhipster execution.
> Try to load config from mem-fs so it can load current working version.

- generators/server/templates/src/main/java/package/security/jwt/TokenProvider.java.ejs
jjwt project has deprecated the `Jwts.parser()` method in favor of `Jwts.parserBuilder()` some months ago. This patch corrects the relevant code to use the updated versions and avoids the deprecation warning.
More info: jwtk/jjwt#499
> Fix Jwts usage to get rid of the deprecation warning

- generators/ci-cd/index.js
I just noticed we are missing the reactive variable inside the ci/cd templates.
[ci-skip]
> Make reactive variable available to ci/cd templates

- generators/client/templates/react/src/test/javascript/e2e/page-objects/navbar-page.ts.ejs
While testing OAuth2 integration with the Micronaut Generator and the end-to-end Protractor tests in the React client, I discovered that the tests were failing due to the application not properly logging out after a test.
Adding the closing `]` to the logout selector seems to have fixed the issue.
> BugFix: Fixes logout link for protractor tests in React client

- generators/client/templates/angular/src/main/webapp/app/shared/alert/alert-error.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/shared/alert/alert.component.ts.ejs
As discussed in https://groups.google.com/forum/?hl=en#!topic/jhipster-dev/7ghhQxp_Tvg use NOSONAR to suppress Sonar false positive while https://github.com/SonarSource/SonarJS/issues/1930 is resolved
> Fix optional call Sonar bugs in Angular

- generators/client/index.js
- generators/client/templates/angular/src/main/webapp/app/account/register/register.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management-update.component.ts.ejs
- generators/client/templates/react/src/main/webapp/app/modules/account/register/register.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management-update.tsx.ejs
- generators/generator-constants.js
- generators/server/index.js
- generators/server/templates/src/main/java/package/config/Constants.java.ejs
This makes the login regex more consistent with the current released version. In particular for example:
* Released version: `foo@bar@com` -> VALID :heavy_check_mark: 
* Current master: `foo@bar@com` -> INVALID :red_circle: 
* New regex: `foo@bar@com` -> VALID :heavy_check_mark: 
closes #11726
> update login regex to be more consistent with current released one

- generators/generator-base.js
this.context doesn't exists outside entity(-*) generators
> Fix getEntityJson when calling outside entity(-*) generators.

- generators/generator-base-private.js
- generators/generator-base.js
- test/entity.spec.js
- test/generator-base.spec.js
Reproducible builds can set changelogDate to future date, so save it to keep changelogs linear.
> Save dateFormatForLiquibase.

- generators/server/templates/src/test/java/package/RedisTestContainerExtension.java.ejs
- generators/server/templates/src/test/resources/config/application.yml.ejs
> Redis: use @DynamicPropertySource to set server url in tests

- generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
- generators/entity-server/templates/src/main/java/package/service/dto/EntityCriteria.java.ejs
- generators/entity-server/templates/src/main/java/package/service/dto/EntityDTO.java.ejs
- generators/server/templates/src/main/java/package/domain/Authority.java.ejs
- generators/server/templates/src/main/java/package/domain/PersistentAuditEvent.java.ejs
- generators/server/templates/src/main/java/package/domain/PersistentToken.java.ejs
- generators/server/templates/src/main/java/package/domain/User.java.ejs
- generators/server/templates/src/main/java/package/service/dto/UserDTO.java.ejs
- generators/server/templates/src/main/java/package/web/rest/vm/LoginVM.java.ejs
- generators/server/templates/src/main/java/package/web/rest/vm/ManagedUserVM.java.ejs
- generators/server/templates/src/main/java/package/web/websocket/dto/ActivityDTO.java.ejs
- generators/server/templates/src/test/java/package/repository/timezone/DateTimeWrapper.java.ejs
Follow up to #11371
In https://github.com/jhipster/generator-jhipster/pull/11371#issuecomment-590238517 was proposed couple of solutions to Java `toString()` formatting.
https://github.com/jhipster/generator-jhipster/pull/11371#pullrequestreview-368593394 decided ATM not to handle Java `toString()` problem.
This PR proposes `// prettier-ignore` to solve `toString()` formatting.
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTR …
> Fix toString() formatting in Java

- generators/server/templates/src/main/java/package/Application.java.ejs
See: https://cloud.spring.io/spring-cloud-commons/multi/multi__spring_cloud_commons_common_abstractions.html#_enablediscoveryclient
"@EnableDiscoveryClient is no longer required. You can put a DiscoveryClient implementation on the classpath to cause the Spring Boot application to register with the service discovery server."
> @EnableDiscoveryClient is no longer required

- generators/client/templates/angular/src/main/webapp/404.html.ejs
- generators/client/templates/angular/src/main/webapp/index.html.ejs
- generators/client/templates/react/src/main/webapp/404.html.ejs
- generators/client/templates/react/src/main/webapp/index.html.ejs
- generators/server/templates/src/main/resources/templates/error.html.ejs
- generators/server/templates/src/main/resources/templates/mail/activationEmail.html.ejs
- generators/server/templates/src/main/resources/templates/mail/creationEmail.html.ejs
- generators/server/templates/src/main/resources/templates/mail/passwordResetEmail.html.ejs
Remove 'shortcut' as the link type is non-conforming & ignored
Reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types
> Remove non-conforming & ignored link type

- generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs
Reason: liquibase.exception.UnexpectedLiquibaseException: loadData type of 'varchar(100)' ' is not supported.  Please use BOOLEAN, NUMERIC, DATE, STRING, COMPUTED, SEQUENCE, UUID or SKIP
> set loadData column type to string instead of varchar

- generators/docker-compose/files.js
- generators/docker-compose/index.js
- generators/docker-compose/templates/central-server-config/application.yml.ejs
- generators/docker-compose/templates/central-server-config/gateway.yml.ejs
- generators/server/templates/src/main/docker/app.yml.ejs
- generators/server/templates/src/test/java/package/AbstractNeo4jIT.java.ejs
This pr makes sure prometheus export is disabled when using elk for monitoring (and vice versa).
@mraible I think we are missing neo4j support in this sub generator. I will add it inside this PR if everyone agrees, such that your demo will eventually work.
update #11819
> enable console exporter only for elk

- generators/app/index.js
- generators/app/prompts.js
- generators/aws-containers/prompts.js
- generators/client/index.js
- generators/client/prompts.js
- generators/generator-base.js
- generators/server/index.js
- generators/server/prompts.js
- generators/statistics.js
> Correct typos

- generators/gae/index.js
This removes the log that prints appengine:run goal for maven and appengineRun goal for gradle. These goals are not available for app.yaml based projects.
References: 
1) https://github.com/GoogleCloudPlatform/app-gradle-plugin/blob/master/USER_GUIDE.md#app-engine-appyaml-based-projects 
2) https://github.com/GoogleCloudPlatform/app-maven-plugin/blob/master/USER_GUIDE.md#app-engine-appyaml-based-project …
> Remove Log for Printing appengineRun and appengine:run Goals

- generators/server/templates/src/main/resources/config/liquibase/master.xml.ejs
-   [ X] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ X] Tests are added where necessary
-   [ X] Documentation is added/updated where necessary
-   [ X] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed
Fixes #11840
> #11840 Allow mariadb to use now()

- generators/server/templates/src/test/java/package/web/rest/AccountResourceIT.java.ejs
I am not sure what is going on, but somehow the gradle tests revealed missing neo4j extension for certain configurations (see https://github.com/hipster-labs/jhipster-daily-builds/runs/705075038?check_suite_focus=true)
> neo4j: fix integration test setup

- generators/client/templates/angular/package.json.ejs
#6338 removed `reflect-metadata` polyfill, but dependency in `package.json` was not removed, this PR removes redundant `reflect-metadata` dependency.
> Remove unused dependency reflect-metadata in Angular

- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs
Send the entire user object (including `login`) instead of just the `id` field
In Angular, we pass the whole User object `"user": {"id": "1", "login": "system", "firstName": "System" .... }`
In React we only pass the ID `"user":{"id":"1"}`, which results in an invalid User since login is a required field. This is because the value returned from the select box only returns the id.
Fixed by finding the `user` in `props.`user with the matching `id`.
Fix #11792 …
> fix react microservice user relation request

- generators/server/templates/gradle.properties.ejs
It was failing with gradle 6.4.1 , 
Please refer here.
https://github.com/liquibase/liquibase-gradle-plugin/issues/70
> Upgrade the liquibase dependency version 

- generators/server/templates/src/main/resources/config/application.yml.ejs
- generators/server/templates/src/test/resources/config/application.yml.ejs
This property was removed in spring-boot 2.2.0.
See: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2.0-M6-Configuration-Changelog
> Remove property spring.mvc.favicon.enabled

- generators/server/templates/build.gradle.ejs
Somehow dependency resolution has changed a little bit in recent gradle version. Therefore boot starter validation is not included anymore and therefore hibernate validators not too. See https://github.com/hipster-labs/jhipster-daily-builds/runs/729654703?check_suite_focus=true 
This fixes this compile error. As we seem not to have this problem in general I added the missing dependency just to the neo4j part in gradle. …
> neo4j: fix dependency error

- generators/client/templates/angular/webpack/webpack.common.js.ejs
Reverts jhipster/generator-jhipster#11580. 
**Note:** This should be ideally merged **after June 06th** when FireFox 77 is released as I've mentioned at https://github.com/jhipster/generator-jhipster/issues/11566#issuecomment-614134292. 
Related to https://github.com/jhipster/generator-jhipster/issues/11566
> Revert "Remove es2015 from Webpack Configuration"

- cli/cli.js
With options been registered to commander, it improves help, but it sets
every default value making options debug very loud.
> Change cli options from info to debug.

- generators/client/index.js
- generators/client/templates/angular/package.json.ejs
- generators/client/templates/angular/tsconfig.json.ejs
`genDir` is unused since Angular v5: https://blog.angular.io/version-5-0-0-of-angular-now-available-37e414935ced and this is no more listed in https://angular.io/guide/angular-compiler-options
> Remove redundant genDir from angularCompilerOptions

- generators/heroku/index.js
- generators/heroku/templates/application-heroku.yml.ejs
- generators/heroku/templates/provision-okta-addon.sh.ejs
- test/heroku.spec.js
I will update our heroku documentation soon to reflect the new features and also document what manual steps are required to setup accounts on the okta addon.
Furthermore this PR
* removes the node buildpack and let maven/gradle handle it (instead of doing npm install two times)
* set the jvm buildpack such that jar deployment works
closes #11698
> support okta as oicd provider when deploying to heroku

- cli/cli.js
- cli/utils.js
- test/cli/cli-utils.spec.js
- test/cli/cli.spec.js
> Fix jhipster cli not passing fromCli option.

- generators/client/needle-api/needle-client-angular.js
- generators/client/templates/angular/src/main/webapp/app/core/icons/font-awesome-icons.ts.ejs
#11665 switched `Prettier` to `v2` which by default adds trailing commas to many places.  
`addIcon` needle function assumed that there is no trailing comma.  
After this change `addIcon` works both with and without trailing comma in icons array.
> Fix addIcon needle function generating double comma

- generators/heroku/index.js
This makes the Heroku sub generator extend BaseBlueprintGenerator, such that blueprints can overwrite e.g. generated property files to match their own configuration. A concrete use case can be found in the [micronaut blueprint](https://github.com/jhipster/generator-jhipster-micronaut/pull/85)  where e.g. the datasource properties and the procfile is different from the main generator.
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master …
> make Heroku sub generator blueprint aware

- generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs
this fixes the `@PreAuthorize`, `@PostAuthorize`, and `@Secured` annotations for UAA auth
Fix #11401
Fix #11928
> restore EnableGlobalMethodSecurity for apps using UAA auth

- generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
- generators/entity-server/templates/src/main/java/package/service/dto/EntityDTO.java.ejs
- generators/entity-server/templates/src/main/java/package/service/mapper/EntityMapper.java.ejs
Unless the other entity is also an embedded one: then the ownerside should be taken into account
This was one of my comment on the original PR: https://github.com/jhipster/generator-jhipster/pull/11239#issuecomment-627612064
And this also cause issues when using both ElasticSearch and MongoDB in Spring Boot 2.3
An illustration, with the following JDL:
```
entity DocumentBankAccount
@embedded
entity EmbeddedOperation
DocumentBankAccount to EmbeddedOperation
}
```
```java
public class DocumentBankAccount implements Serializable {
@Field("embeddedOperation")
private Set<EmbeddedOperation> embeddedOperations = new HashSet<>();
}
public class EmbeddedOperation implements Serializable {
@DBRef
private DocumentBankAccount documentBankAccount;
}
```
```java
public class …
```
> Remove reference to other entities in an embedded entity

- generators/server/templates/src/test/java/package/config/timezone/HibernateTimeZoneIT.java.ejs
It will allow to easily change this property:
https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/test/resources/config/application.yml.ejs#L95
No impact for user with default UTC.
_____
> Integration tests: use time zone from configuration instead of UTC

- cli/import-jdl.js
- generators/generator-base.js
- Change import-jdl options log from info to debug
- Don't lookup when the blueprint is already registered.
- Use filterPaths option to match others lookups.
> Blueprint and cli fixes

- generators/kubernetes-helm/files.js
- test/kubernetes.helm.spec.js
helm dep up only looks for requirements.yaml. Jhipster only generates
requirements.yml which is ignored by helm 3.x. For kubernetes and helm
the standard is usually .yaml.
Fix #11920
> Fix helm requirements

- generators/gae/index.js
This adds information on how to disable the .gcloudignore file generation until https://github.com/GoogleCloudPlatform/app-gradle-plugin/issues/376 is fixed.
Fixes https://github.com/jhipster/generator-jhipster/issues/11880
> Add info on Disabling .gcloudignore file Generation

- .github/dependabot.yml
This adds dependabot.yml file to leverage native support for dependabot through GitHub
Related to https://github.com/jhipster/generator-jhipster/issues/11914
> Add dependabot.yml file for automatic version upgrades [ci skip]

- .github/dependabot.yml
- .github/workflows/angular.yml
- .github/workflows/react.yml
- .github/workflows/webflux.yml
This removes the unnecessary maven configuration from dependabot.yml and adds a label so that GitHub CI is skipped.
Fixes https://github.com/jhipster/generator-jhipster/issues/11962
> Adjust dependabot.yml to skip ci and remove maven config

- azure-pipelines.yml
This adds support to skip builds for Azure for dependabot branches.
Related to https://github.com/jhipster/generator-jhipster/issues/11962
> Add support to skip Azure builds on dependabot

- generators/server/templates/src/main/resources/config/application.yml.ejs
A default value for the license should be set as it is required by multiple other applications. So it would ease my daily duties as a developer.
On the other hand there is automatically a license depending on the country where the new application gets generated. In order to avoid confusion here, a default value can help.
- This is what we do in the package.json (the keyword used is "UNLICENSED" which means this is a private project) -> we need the same thing here to be consistent
- This license name is required by some third-parties
> set default license to unlicensed in order to meet third party standard

- generators/server/templates/src/main/java/package/config/JacksonConfiguration.java.ejs
- generators/server/templates/src/main/java/package/config/LocaleConfiguration.java.ejs
- add `public` modifier for bean definitions for consistency
- remove unnecessary bean qualifier `localeResolver` 
> minor cleanup in configuration files

- .github/dependabot.yml
- .github/workflows/angular.yml
- .github/workflows/react.yml
- .github/workflows/webflux.yml
- azure-pipelines.yml
This changes the logic in dependabot pull request CI skipping. Current logic was created with the hope dependabot creates a label on the PR creation. But unfortunately dependabot adds the label after the PR is created by which time the CI has already been triggered.
Related to https://github.com/jhipster/generator-jhipster/issues/11962
> Change Logic Concerning dependabot CI Skipping

- .github/workflows/angular.yml
- .github/workflows/generator.yml
- .github/workflows/react.yml
- .github/workflows/webflux.yml
- azure-pipelines.yml
- PR branchs considers target branch.
- On conditions don’t show at actions list.
- dependabot builds are duplicating at dependabot/* branch and PR
---
> Dependabot adjustments

- .github/workflows/gradle-wrapper-validation.yml
- azure-pipelines.yml
This fixes some mistakes in the dependabot logic. Currently dependabot only skips for pull request CI. We also need to skip pushes. Also with this change the azure builds are skipped for dependabot.
Related to https://github.com/jhipster/generator-jhipster/issues/11962
> Fix Mistakes in Logic Concerning dependabot CI Exclusions

- generators/entity-i18n/templates/i18n/entity_pt-br.json.ejs
- generators/entity/index.js
Allows i18n to be generated based on the entityI18nVariant like:
Portuguese example:
```
@entityI18nVariant(female)
entity Empresa {
}
entity Usuario {
}
```
Should generate string:
`Um Usuario` for Usuario entity and `Uma Empresa` for Empresa entity.
> Add support to i18n variant

- .github/dependabot.yml
- .github/workflows/generator.yml
- azure-pipelines.yml
- package.json
This PR add a prettier:check script and a github workflow to check.
`skip-ci` is not be applied to this workflow since README.md and others text files should be formatted too.
An alternative is to run prettier:check at pretest script.
---
> Add prettier check workflow

- generators/ci-cd/templates/azure-pipelines.yml.ejs
The pipeline definition generated by the `ci-cd` subgenerator is not working for Azure:
This PR fixes that and also removes not mandatory steps:
- [MySQL service is not running by default](https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1604-README.md)
- Yarn is installed by default
- Unnecessary install/test at the end …
> Refactor and fix Azure pipeline

- azure-pipelines.yml
I've noticed that dependabot isn't still skipped for Azure pipelines. This is another attempt to fix this.
Related to https://github.com/jhipster/generator-jhipster/issues/11914
> Attempt to Skip Azure Pipelines for Dependabot

- generators/kubernetes-knative/templates/service.yml.ejs
- generators/kubernetes/templates/deployment.yml.ejs
- generators/server/templates/src/main/resources/config/application-prod.yml.ejs
- Changed Kubernetes probes: https://docs.spring.io/spring-boot/docs/2.3.0.RELEASE/reference/html/production-ready-features.html#production-ready-kubernetes-probes
- define graceful shutdown: https://docs.spring.io/spring-boot/docs/2.3.0.RELEASE/reference/html/spring-boot-features.html#boot-features-graceful-shutdown
Fix #10770
> [SpringBoot 2.3] Change kubernetes probes and define graceful shutdown

- generators/server/templates/src/main/java/package/config/CacheConfiguration.java.ejs
Clear a cache if it exists when calling the createCache method to avoid exceptions when running tests with @MockBean annotations.
fix #10680
---
> clear cache if exists when calling createCache()

- cli/import-jdl.js
- generators/ci-cd/index.js
- generators/client/index.js
- generators/cloudfoundry/index.js
- generators/docker-base.js
- generators/entity/index.js
- generators/gae/index.js
- generators/generator-base.js
- generators/heroku/index.js
- generators/languages/index.js
- generators/server/index.js
- generators/spring-controller/index.js
- generators/spring-service/index.js
- generators/utils.js
- test/templates/ngx-blueprint/.yo-rc.json
- test/utils.spec.js
- utils/jhipster6-mixin.js
Fixes #12023 
Remove getAllJhipsterConfig and implement getJhipsterConfig alternative.
- getAllJhipsterConfig was implemented as a workaround to blueprint/modules saving config to .yo-rc.json with another namespace.
- Merge implemented by getAllJhipsterConfig is not deterministic (depends on the order blueprints are loaded).
- Fixed by making blueprints always write to 'generator-jhipster' namespace
- `generator/utils` does not have stability guarantee.
Modules can get a Storage instance by: 
- `const jhipsterConfig = this._getStorage('generator-jhipster');` extending plain yeoman-generator.
-  or `const jhipsterConfig = this.getJhipsterConfig();` extending generator-base.
This requires to use `jhipsterConfig.get/set` methods.
If you prefer to use the object directly :
```
const …
```
> Remove getAllJhipsterConfig.

- generators/app/index.js
- generators/aws-containers/index.js
- generators/common/index.js
- generators/entity-client/index.js
- generators/entity-i18n/index.js
- generators/entity-server/index.js
- generators/entity/index.js
- generators/generator-base-blueprint.js
- generators/generator-base.js
- generators/heroku/index.js
- generators/languages/index.js
- generators/server/index.js
- generators/spring-controller/index.js
- generators/spring-service/index.js
- Create jhipsterConfig for easily read/write synchronised configuration.
- Move configOptions initialisation to generator-base since almost every generator implements it.
Breaking change:  `jhipsterConfig` already existed at generator-base-blueprint, but its not documented and probably no blueprint uses it.
Replacement:
Change `const config = this.jhipsterConfig.get('config');` to `const config = this.jhipsterConfig.config;`
Or create getter/setter:
```
const jhipsterConfig = this.jhipsterConfig;
this.jhipsterConfig = {};
this.jhipsterConfig.get = config -> jhipsterConfig[config];
this.jhipsterConfig.set = (config, value) -> jhipsterConfig[config] = value;
```
Related to #10528 
---
-   [ ] [All continuous integration …
> Create jhipsterConfig for synchronised config and move configOptions to generator-base.

- generators/client/templates/angular/webpack/webpack.common.js.ejs
This correctly overrides the swagger index.html to use the generated app's swagger /v2/api-docs endpoint instead of the default swagger petstore endpoint
Fix #12025
---
> fix swagger globptions ignore [v6.x_maintenance]

- generators/client/templates/angular/webpack/webpack.common.js.ejs
- generators/client/templates/react/package.json.ejs
- generators/client/templates/react/webpack/webpack.common.js.ejs
This correctly overrides the swagger index.html to use the generated app's swagger /v2/api-docs endpoint instead of the default swagger petstore endpoint
Fix #12025
---
> fix swagger globptions ignore

- .prettierrc
`jhipster --prettier-java` is generating source code `tabWidth: 2` but creating `.prettierrc` with `tabWidth: 4`.
At first prettier format, every java file will change due to updating tabWidth to 4.
--- …
> Fix prettier-java rule to .prettierrc

- generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
Currently we are not generating fluent id setter.
---
> Add id fluent setter to Entity.

- generators/aws/index.js
- generators/aws/prompts.js
This adds support for custom instance and RDS types so that the user can choose any instance type or RDS type from the following lists respectively;  https://aws.amazon.com/ec2/instance-types/ and https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html
Related to https://github.com/jhipster/generator-jhipster/issues/12017
When …
> Support Custom Instance and RDS types in AWS

- package-lock.json
No sure if this is macOS only but `npm ci` is printing a warning. Github CI isn't affected.
```
> fsevents@1.2.13 install /Users/mshima/git/generator-jhipster/node_modules/watchpack-chokidar2/node_modules/fsevents
> node install.js
internal/modules/cjs/loader.js:985
throw err;
^
Error: Cannot find module 'nan'
Require stack:
- /Users/mshima/git/generator-jhipster/node_modules/watchpack-chokidar2/node_modules/fsevents/[eval]
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
at Function.Module._load (internal/modules/cjs/loader.js:864:27)
at Module.require (internal/modules/cjs/loader.js:1044:19)
at require (internal/modules/cjs/helpers.js:77:18)
at [eval]:1:1
at Script.runInThisContext (vm.js:120:20)
at Object.runInThisContext (vm.js:311:38)
at Object.<anonymous> …
```
> Add missing dependencies

- generators/server/templates/src/test/java/package/service/UserServiceIT.java.ejs
Using mock for dateTimeProvider may affect users test that use dateTimeProvider. To avoid side affect we need to use @MockBean
[issue](https://github.com/jhipster/generator-jhipster/issues/12042)
[pr jhipster-kotlin](https://github.com/jhipster/jhipster-kotlin/pull/247)
> Remove side effect of mock dateTimeProvider

- generators/app/index.js
- generators/languages/index.js
- test/languages.spec.js
generate the native language the first time.
---
> Fix jhipster regeneration showing prompt without --with-entities and

- jdl/bundling/scripts/changed-generated-jdl-files-committer.js
- package-lock.json
- package.json
- scripts/commit-changed-generated-jdl-files.js
- test/jdl/bundling/scripts/commit-changed-generated-jdl-files.test.js
Used the simple-git package to programmatically use git inside a script and
created a script that:
- checked the dist file diffs
- add the files
- commit them
If no file has changed, then no commit is done for a NPM prepare step.
The prepare steps does:
```
Run both BEFORE the package is packed and published,
and on local npm install without any arguments.
This is run AFTER prepublish, but BEFORE prepublishOnly
```
Only does a commit if a JDL dist file has changed.
@pascalgrimaud this is the PR I was talking about :)
--- …
> Prevented commit additions when no JDL dist file have changed

- generators/generator-constants.js
- generators/server/templates/build.gradle.ejs
- test/templates/ci-cd/maven-ngx-yarn/pom.xml
According to v7 roadmap. Remove Java8 support. I suggest to set Java 11 as default version and allow from 1.9 to 14. 
---
> Remove java8 support

- generators/client/templates/vue/src/main/webapp/app/account/change-password/change-password.component.ts.ejs
- generators/client/templates/vue/src/main/webapp/app/account/change-password/change-password.vue.ejs
- generators/client/templates/vue/src/main/webapp/app/account/reset-password/finish/reset-password-finish.component.ts.ejs
- generators/client/templates/vue/src/main/webapp/app/account/reset-password/finish/reset-password-finish.vue.ejs
-   [x ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x ] Tests are added where necessary
-   [x ] Documentation is added/updated where necessary
changes in validations (Vuelidate): check if the passwords match in the views "change-password" and "reset-password-finish". With the use of the sameAs function it is not necessary to check the password length. The same can be applied in the registry but I leave that to you
> Use sameAs function in confirm password in vue module

- generators/ci-cd/index.js
- generators/ci-cd/prompts.js
This adds CircleCI configuration needed for jhipster-online to work.
Related to https://github.com/jhipster/jhipster-online/issues/163
> Add CircleCI auto configuration for jhipster-online

- generators/aws-containers/index.js
- generators/azure-app-service/index.js
- generators/azure-spring-cloud/index.js
- generators/gae/index.js
- generators/heroku/index.js
- Conflicter is called internally from yeoman-generator, shouldn't be used without a specific reason.
- Conflicter is moving from the generator to the environment.
- They are traced back to 4 or more years and don't seems to be necessary anymore.
--- …
> Remove legacy this.conflicter uses.

- README.md
As these builds seem stables enough, include them directly in:
- angular nosql
- react nosql
- vue nosql
Related to https://github.com/hipster-labs/jhipster-daily-builds/commit/78831fe6848de8b68e88dd2acfc13609988b8a25
--- …
> Remove Couchbase and Neo4j builds badges [ci skip]

- generators/client/templates/angular/package.json.ejs
- generators/client/templates/react/package.json.ejs
- generators/client/templates/vue/package.json.ejs
- generators/common/templates/.lintstagedrc.js.ejs
- generators/generator-base-private.js
- generators/generator-base.js
- generators/server/templates/package.json.ejs
- test/app.spec.js
@pascalgrimaud vue prettier transform is missing `js` extension.
Related to https://github.com/jhipster/generator-jhipster/issues/12109
---
> Unify prettier extensions handling.

- generators/server/templates/src/test/java/package/RedisTestContainerExtension.java.ejs
Set system property instead of using dynamic property sources which seem to work only when used directly in a test class.
EDIT: targeting 6.x as we should most likely provide a fix as 6.x will be used for a few more month I guess.
closes #12012
--- …
> do not use dynamic property source in junit callbacks

- generators/server/templates/gradle.properties.ejs
This PR updates some gradle plugins to their latest releases:
* https://github.com/liquibase/liquibase-gradle-plugin/blob/master/CHANGELOG.md
* https://github.com/n0mer/gradle-git-properties/releases
* https://jira.sonarsource.com/secure/ReleaseNote.jspa?projectId=10974&version=15726
* https://github.com/spring-io/nohttp
Furthermore the no obsolete property for springfox version has been removed.
--- …
> update gradle plugins

- .github/workflows/angular.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
The last days/weeks, our GitHub Actions trigger too much builds. The result is a lot of builds are in pending.
For example, it is useless to launch React builds when I changed only Vue template.
Here what I propose:
- if you want to trigger only Angular builds, add `[angular]` in your commit message
- if you want to trigger only React builds, add `[react]` in your commit message
- if you want to trigger only Vue builds, add `[vue]` in your commit message
- by default, it will trigger all builds
Webflux is ignored by default, as it is still in beta and some of these options are not used enough:
- if you want to trigger Webflux build, add `[webflux]` in your commit message
---
-   [ ] [All continuous integration …
> CI: add keyword to trigger specific builds [angular][react][vue]

- generators/server/templates/gradle/docker.gradle.ejs
- generators/server/templates/pom.xml.ejs
fix #12136
This makes the docker container run as a regular user and not as root.
---
> Set the user to 1000 for jib docker build on maven and gradle

- generators/client/templates/angular/package.json.ejs
- generators/client/templates/angular/webpack/webpack.dev.js.ejs
- generators/client/templates/angular/webpack/webpack.prod.js.ejs
- generators/client/templates/react/package.json.ejs
- generators/client/templates/react/webpack/webpack.dev.js.ejs
- generators/client/templates/react/webpack/webpack.prod.js.ejs
- generators/client/templates/vue/config/dev.env.js.ejs
- generators/client/templates/vue/package.json.ejs
- generators/client/templates/vue/webpack/webpack.dev.js.ejs
- generators/client/templates/vue/webpack/webpack.prod.js.ejs
Bumps the `webpack-merge` dependency from `4.2.2` to `5.0.9` for Angular, React and Vue.
---
> Update webpack-merge to 5.0.9

- generators/server/templates/src/main/java/package/web/rest/errors/ExceptionTranslator.java.ejs
This prevents leaking of technical details via the problem message which is by default filled with the message of the exception. Most often the message contain/reveal technical details which should not be leak via an api call to the caller.
closes #12051
**This targets v6.x branch on purpose. I think this should be backported as it impacts security.**
---
> prevent leakage of technical details trough problem message

- generators/app/index.js
- generators/client/index.js
- generators/entity/index.js
- generators/generator-base.js
- generators/server/index.js
- test/app/application-with-entities.js
- test/app/composing.js
- Implement composeWithJHipster to allow mocking generators.
- Load config and entities from applicationWithEntities option.
--- …
> Compose mocking and load entire app config from options.

- generators/server/templates/src/main/java/package/config/ReactiveSecurityConfiguration.java.ejs
- generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs
Removing the non existing feature policy speaker from the csp header. See https://github.com/jhipster/generator-jhipster-micronaut/issues/146
[ci-skip] [skip-ci]
---
> remove invalid csp feature 'speaker'

- generators/server/templates/src/main/java/package/config/cassandra/CassandraConfiguration.java.ejs
- generators/server/templates/src/test/java/package/AbstractCassandraTest.java.ejs
- generators/server/templates/src/test/java/package/config/CassandraConfigurationIT.java.ejs
Fixes https://github.com/jhipster/generator-jhipster/issues/12216
---
> Improve cassandra initialization.

- generators/utils.js
Current ejs error handling is just printing the error and throwing another error without printing the stack trace.
---
> Print ejs stacktrace.

- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
- generators/server/files.js
- generators/server/templates/build.gradle.ejs
- generators/server/templates/pom.xml.ejs
- generators/server/templates/src/test/java/package/ReactiveSqlTestContainerExtension.java.ejs
- generators/server/templates/src/test/java/package/security/DomainUserDetailsServiceIT.java.ejs
- generators/server/templates/src/test/java/package/service/MailServiceIT.java.ejs
- generators/server/templates/src/test/java/package/service/UserServiceIT.java.ejs
- generators/server/templates/src/test/java/package/web/rest/AccountResourceIT.java.ejs
- generators/server/templates/src/test/java/package/web/rest/LogoutResourceIT.java.ejs
- generators/server/templates/src/test/java/package/web/rest/UserResourceIT.java.ejs
This adds testcontainers to reactive sql option (for supported databases). As already stated in the issue #11689 we can't change the datasource to the testcontainers r2dbc url like we do for jdbc as liquibase does not support r2dbc urls (yet). 
Therefore there is now a custom junit extension, which starts a singleton container and sets the required properties, only when started with the testcontainers profile.
closes #11689
EDIT: I forgot to trigger webflux build :facepalm: 
---
-   [ ] Coding Rules & Commit Guidelines as …
> add testcontainers for reactive sql option

- test-integration/samples/ms-react-gateway-consul-jwt/.yo-rc.json
- test-integration/samples/ms-react-gateway-consul-oauth2/.yo-rc.json
Concern ms-react-gateway-consul and ms-react-gateway-consul-oauth2
There is an inversion between ms-react-gateway-consul and ms-react-gateway-consul-oauth2 authentication types
---
> [Samples] Fix inversion authentication type in .yo-rc

- generators/app/index.js
- generators/client/templates/angular/package.json.ejs
- generators/client/templates/react/package.json.ejs
- generators/client/templates/vue/package.json.ejs
- generators/generator-base.js
- generators/server/templates/package.json.ejs
- test/client.spec.js
When developing a blueprint or generator-jhipster, package.json always adds a released version of generator-jhipster*.
This option allows to use global generator-jhipster and blueprints without having to remove from package.json/npm uninstall.
--- …
> Implement --skip-jhipster-dependencies option

- generators/generator-base-private.js
- test/generator-base-private.spec.js
This is a cherry-pick from @murdos from spring-boot 2.3 branch.
---
> [webflux] Fix r2dbc URL for H2 in memory database

- generators/server/templates/src/main/resources/config/application-dev.yml.ejs
Avoid the liquibase exception:
```
Liquibase could not start correctly, your database is NOT ready: A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:file:target/h2db/db/h2db;DB_CLOSE_DELAY=-1".
Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-200]
```
---
When …
> Use absolute path for h2disk jdbc path

- generators/client/files-angular.js
- generators/client/files-react.js
- generators/client/files-vue.js
- generators/utils.js
> Fix vue.js constants usage for outputPathCustomizer

- package-lock.json
- package.json
Forgot this... It needs to prepare the next patch release v6.10.2
---
> [v6] Missing release commit v6.10.1

- package-lock.json
- package.json
Fix version of prettier-plugin-java for v6
---
> fix: fix prettier-plugin-java version

- generators/gae/index.js
This replaces the --format argument of the gcloud SQL command with double quotes.
Fixes https://github.com/jhipster/generator-jhipster/issues/12334
---
> Gcloud sql command: Replace --format option by double quotes

- generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs
- generators/server/templates/src/main/resources/config/liquibase/changelog/initial_schema.xml.ejs
- generators/server/templates/src/main/resources/config/liquibase/master.xml.ejs
Datetime column type doesn't store sub-second informations on MySQL and MariaDB by default, here the precision defaults to 0.
As opposed to PostgreSQL and H2, where it assumes that 6 digit should be stored.
* https://mariadb.com/kb/en/microseconds-in-mariadb/
* https://dev.mysql.com/doc/refman/8.0/en/fractional-seconds.html
* https://www.postgresql.org/docs/current/datatype-datetime.html
* http://h2database.com/html/datatypes.html
--- …
> Datetime column type doesn't store sub-second informations on MySQL and MariaDB

- .github/workflows/angular.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
Base sha is not always updated, use merge commit @~1 instead.
Adjusts to https://github.com/jhipster/generator-jhipster/pull/12198
---
> Change merge reference to previous commit instead of base.sha

- generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs
This PR is to add the `databaseType === 'sql'` to the condition to import the `@Transactional` annotation in the controller. 
---
> [webflux] Remove unused transactional annotation import in resources

- generators/server/templates/src/main/docker/app.yml.ejs
- generators/server/templates/src/main/docker/cassandra-cluster.yml.ejs
- generators/server/templates/src/main/docker/cassandra.yml.ejs
- generators/server/templates/src/main/docker/consul.yml.ejs
- generators/server/templates/src/main/docker/couchbase-cluster.yml.ejs
- generators/server/templates/src/main/docker/couchbase.yml.ejs
- generators/server/templates/src/main/docker/elasticsearch.yml.ejs
- generators/server/templates/src/main/docker/hazelcast-management-center.yml.ejs
- generators/server/templates/src/main/docker/jhipster-control-center.yml.ejs
- generators/server/templates/src/main/docker/jhipster-registry.yml.ejs
- generators/server/templates/src/main/docker/kafka.yml.ejs
- generators/server/templates/src/main/docker/keycloak.yml.ejs
- generators/server/templates/src/main/docker/mariadb.yml.ejs
- generators/server/templates/src/main/docker/memcached.yml.ejs
- generators/server/templates/src/main/docker/mongodb-cluster.yml.ejs
- generators/server/templates/src/main/docker/mongodb.yml.ejs
- generators/server/templates/src/main/docker/monitoring.yml.ejs
- generators/server/templates/src/main/docker/mssql.yml.ejs
- generators/server/templates/src/main/docker/mysql.yml.ejs
- generators/server/templates/src/main/docker/neo4j.yml.ejs
- generators/server/templates/src/main/docker/postgresql.yml.ejs
- generators/server/templates/src/main/docker/redis-cluster.yml.ejs
- generators/server/templates/src/main/docker/redis.yml.ejs
- generators/server/templates/src/main/docker/sonar.yml.ejs
- generators/server/templates/src/main/docker/swagger-editor.yml.ejs
As discussed in #12015 this exposes all docker compose containers only on `127.0.0.1` and adds some hint that the provided configuration is intended only for development purposes. 
Should we do the same for the configurations in the docker-compose subgenerator? 
closes #12015
[ci-skip] [skip-ci]
---
When you are still working on the PR, consider converting …
> expose docker compose containers only on local

- generators/server/templates/src/main/docker/app.yml.ejs
extend wait time to 60 for application when using mssql
Fix #12380
---
> Extend wait time for application start when MSSQL is selected

- generators/server/templates/pom.xml.ejs
Neo4j starter/migrations require `io.github.classgraph:classgraph:jar:4.8.87` while maven resolves it to `4.8.83`. This PR pins the version when neo4j option is used (gradle seem to resolve the compatible one).
closes #12376
--- …
> pin classgraph version for neo4j option

- cli/cli.js
- cli/commands.js
- generators/statistics.js
- test/cli/jdl.js
Related to https://github.com/jhipster/generator-jhipster/issues/11896.
- Stop forcing '--skip-sample-repository' at import-jdl
- Disable features when CI env variable is set.
---
> Changes to cli behaviour.

- .github/workflows/angular.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
Client dependabot is triggering too many build, let's don't trigger builds for another client.
Adjusts to https://github.com/jhipster/generator-jhipster/pull/12415
---
> Ignore push CI when files matches only another client.

- generators/client/templates/angular/package.json.ejs
- generators/client/templates/common/package.json
- generators/client/templates/react/package.json
- generators/client/templates/react/package.json.ejs
- generators/client/templates/vue/package.json.ejs
All front-end frameworks use **Typescript 4** now
---
> Typescript 4 for Angular, React & Vue

- generators/client/templates/react/src/main/webapp/app/shared/layout/menus/account.tsx.ejs
Fix [#12473](https://github.com/jhipster/generator-jhipster/issues/12473)
> Fix unused FontAwesomeIcon import in account menu

- generators/server/templates/src/test/java/package/config/WebConfigurerTest.java.ejs
Fix [#12477](https://github.com/jhipster/generator-jhipster/issues/12477)
> fix unused CachingHttpHeadersFilter import in WebConfigurerTest

- generators/client/templates/react/src/main/webapp/app/shared/DurationFormat.tsx.ejs
Fix #12472 duration should be displayed on the app language.
When a locale is given as an input, this locale should be used to display the duration in a textual way. Otherwise, the locale used by the application should be used.
--- …
> Fix duration displayed in current locale

- generators/client/templates/vue/src/main/webapp/content/css/global.css.ejs
- generators/client/templates/vue/src/main/webapp/content/scss/global.scss.ejs
Fixed #12453 : removed bold property in a:hover + add new css properties for dropdown-item:hover and dropdown-item:focus.
---
> change the hover and focus properties of dropdown-item in css and scss

- generators/openapi-client/prompts.js
- package-lock.json
- package.json
The library sync-request cannot be used in production applications (reference: https://www.npmjs.com/package/sync-request). In jhipster-online, sync-request is I think the root cause of generation being hanging. When I look at the processes always see a stuck process originating from this library. Therefore I would suggest replacing this with then-process instead.
Fixes https://github.com/jhipster/jhipster-online/issues/233
--- …
> Use then-request Instead of sync-request

- .github/dependabot.yml
- generators/client/templates/angular/package.json
- generators/client/templates/angular/package.json.ejs
- generators/generator-base.js
- Implement our own grouped update, dependabot does not support it (https://github.com/dependabot/dependabot-core/issues/1296) and this will create a lot of noise if we migrate to auto update.
- Change dependabot strategy, templates package.json are detected as a library, default strategy is widen for libraries.
With our current practices, we should use increase.
---
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) …
> Improvements to dependabot client updates.

- generators/common/templates/README.md.ejs
Removes extra blank lines in the README code blocks.  For example:
```
./mvnw
npm start
```
Should be:
```
./mvnw
npm start
```
---
> remove extra lines in readme code blocks

- .github/PULL_REQUEST_TEMPLATE.md
This adds a small reminder to update jhipster-online when submitting a pull request.
https://github.com/jhipster/jhipster-online/pull/229#issuecomment-687653077
---
> Add reminder to update jhipster-online

- generators/server/templates/build.gradle.ejs
- generators/server/templates/pom.xml.ejs
Update Java version range to allow Java 15.
---
> Allow JHipster to be run with Java 15

- generators/entity-server/index.js
- generators/entity-server/templates/src/main/java/package/common/get_all_template.ejs
- generators/entity-server/templates/src/main/java/package/common/get_template.ejs
- generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
- generators/entity-server/templates/src/main/java/package/repository/EntityReactiveRepository.java.ejs
- generators/entity-server/templates/src/main/java/package/repository/EntityRepository.java.ejs
- generators/entity-server/templates/src/main/java/package/service/EntityService.java.ejs
- generators/entity-server/templates/src/main/java/package/service/impl/EntityServiceImpl.java.ejs
- generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs
- generators/entity/index.js
- generators/generator-base-private.js
- generators/generator-base.js
- test/app/database-changelog.spec.js
- test/entity.spec.js
- test/entity/database-changelog.spec.js
- test/templates/.jhipster/DtoServicePagination.json
- test/templates/.jhipster/Simple.json
- utils/index.js
- utils/relationship.js
- Creates a shared object containing every prepared entity, so relationships can easily get updated data from the other entity.
- Relationships: make `otherEntity` available to templates. (and workaround cyclic json at stringify).
- Relationships: start loading fields from `otherEntity` for consistency, instead of creating based only on relationship data.
- Relationships: really throw error if other side entity is not found and is not a built-in entity.
- Relationships: replace `@JsonIgnore` in favor of `@JsonIgnoreProperty` with every relationship ignored.
- Relationships: pre calculate what relationships must be eager loaded.
- Indentation fixes.
- Removes unreachable code.
Related to https://github.com/jhipster/generator-jhipster/issues/12562.
---
Please make sure the below checklist …
> Improvements to relationship handling.

- generators/openapi-client/files.js
- generators/server/templates/build.gradle.ejs
- generators/server/templates/gradle.properties.ejs
- generators/server/templates/gradle/profile_dev.gradle.ejs
- generators/server/templates/pom.xml.ejs
- generators/server/templates/settings.gradle.ejs
- test-integration/scripts/13-replace-version-generated-project.sh
- test/needle-api/needle-server-gradle.spec.js
- Refactor gradle.properties file
- snake case -> camel case (https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties)
- Fix mvnrepository.com links
- Remove unused log4j2_mock_version property
--- …
> Properties case style fix

- generators/database-changelog-liquibase/index.js
- utils/entity.js
Currently, if you generate a gateway + microservice with a JDL such as https://github.com/hipster-labs/jhipster-daily-builds/blob/master/test-integration/jdl-samples/templates/microservice-demo.jdl.ejs, the gateway will contain non required liquibase changelogs for entities.
---
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.m …
> Fix: don't generate liquibase changelogs for microservice entities on gateway

- generators/generator-base.js
add vue files in package.json's 'prettier:format' script
Fix #12455
---
> include .vue files in prettier script

- .github/workflows/triage.yml
Before applying these labels: `area: triage` and `theme: undefined`, it will check if one `area` or `theme` already exists.
It will help the core developers to create a new tickets with appropriate labels, without waiting for removing `area: triage` and `theme: undefined`
---
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) …
> GitHub Actions: improve triage

- generators/openapi-client/prompts.js
- package-lock.json
- package.json
This is needed as using the sync-request in production can stuck the generation as evidenced in jhipster-online
Duplicates c0f988d7b, e9fe904dc0, 1e64e9f and f09e68f from the master branch.
Related to https://github.com/jhipster/jhipster-online/issues/233
--- …
> Change sync-request library to then-request

- generators/client/templates/angular/src/test/javascript/e2e/account/account.spec.ts.ejs
- generators/client/templates/react/src/test/javascript/e2e/modules/account/account.spec.ts.ejs
- generators/client/templates/vue/src/main/webapp/app/core/jhi-navbar/jhi-navbar.component.ts.ejs
- generators/client/templates/vue/src/test/javascript/e2e/modules/account/account.spec.ts.ejs
- generators/common/templates/README.md.ejs
Question: If I can't find `Sign in failed!` in Cypress tests, does that mean they're not configured to test Okta?
Related: I was unable to get `run run e2e` to pass even after this change. I did set `E2E_USERNAME` and `E2E_PASSWORD` beforehand.
It seems to be …
> Fix Okta login failure message and add Okta CLI to docs

- generators/client/templates/vue/src/main/webapp/app/locale/translation.service.ts.ejs
change the bahavior in vue to match Angular/React so that when
changing to an RTL laguage (or initially showing an RTL language)
the `dir` attribute will change to `rtl`
Fix #12384
---
When you are still working on the PR, consider converting it to Draft (bellow …
> add RTL support for vue

- generators/client/templates/angular/src/main/webapp/app/core/tracker/tracker.service.ts.ejs
- generators/client/templates/react/src/main/webapp/app/config/websocket-middleware.ts.ejs
- generators/client/templates/vue/src/main/webapp/app/admin/tracker/tracker.service.ts.ejs
fixes deprecation notice in the browser console when using WebSockets:
"DEPRECATED: undefined is not a recognized STOMP version. In next major client version, this will close the connection."
--- …
> set STOMP protocol version

- Dockerfile
By default, Ubuntu or Debian based "apt" or "apt-get" system installs recommended but not suggested packages .
By passing "--no-install-recommends" option, the user lets apt-get know not to consider recommended packages as a dependency to install.
This results in smaller downloads and installation of packages .
Refer to blog at [Ubuntu Blog](https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends) .
Signed-off-by: Pratik Raj <rajpratik71@gmail.com>
> chore : use `--no-install-recommends` flag to `apt-get` in dockerfile to save space

- CONTRIBUTING.md
fix https://github.com/jhipster/generator-jhipster/issues/12553
Adding documentation on command to run before generation of entities
---
> document command necessary before running `jhipster import-jdl`

- generators/server/templates/src/main/java/package/config/ReactiveSecurityConfiguration.java.ejs
This PR allows google analytics script via CSP header, such that enabling it in `index.html` works out of box. Did a test run with an application deployed on heroku and I can see my visits in the analytics dashboard. 
Right now the analytics does not hook into any routing of the frontend, but I think thats fine, we could document that how to do that.
We had a difference between webflux and servlet CSP header, they are now aligned. 
closes #12666
--- …
> add google analytics to allowed CSP policy

- .github/workflows/webflux.yml
Webflux tests run only when explicitly asked for, which make these tests stale, and invalid.
---
> Enable webflux tests for backend

- .github/workflows/angular.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- generators/client/index.js
- generators/client/templates/angular/package.json.ejs
- generators/client/templates/common/package.json
- generators/client/templates/react/package.json.ejs
- generators/client/templates/vue/package.json.ejs
- generators/server/index.js
- generators/server/templates/pom.xml.ejs
- generators/server/templates/src/test/java/package/web/rest/UserResourceIT.java.ejs
This PR adds npm scripts to easily run e2e, create packages, start docker containers..
- Allows e2e to run with 2 commands: `npm run ci:e2e:prepare` and `npm run ci:e2e:run`.
- Switches our GitHub Actions to use those generated scripts.
- Reduce angular/react/vue package.json differences.
- Fix tests failures.
Related to https://github.com/jhipster/generator-jhipster/issues/12489
---
-   [ ] Coding Rules & Commit Guidelines as …
> Integrate scripts blueprint into generator-jhipster.

- generators/server/templates/src/main/java/package/config/WebConfigurer.java.ejs
- generators/server/templates/src/test/java/package/config/WebConfigurerTest.java.ejs
Previously, static ".json" files had "text/html" [+ charset] as a MIME type.
This change ensures that JSON files are properly served using the standard "application/json" [+ charset] MIME type.
This change was briefly discussed with @jdubois in [this CloudFoundry issue](https://github.com/cloudfoundry/gorouter/issues/64#issuecomment-693584848).
---
When you …
> fix(Server Configuration): Rectify content type for serving JSON files

- generators/server/files.js
- generators/server/templates/src/main/docker/config/consul-config/application.yml.ejs
- generators/server/templates/src/main/docker/config/docker-config/application.yml.ejs
- generators/server/templates/src/main/docker/config/localhost-config/application.yml.ejs
BTW, I wonder if we should not remove support for the non base64 encoded config.
WDYT?
---
> fix: some application.yml were still using secret rather than the recommended base64-secret key

- generators/server/files.js
- generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs
This PR fixes the following scenario: Microservice architecture, Oauth2 Authentication, No Service Discovery.
In this scenario the gateway fails to relay authentication token to downstream microservice, resulting in status code 401 when querying microservice's api.
---
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are …
> Fix microservice: auth token now passing from gateway to microservice

- .github/workflows/incremental-changelog.yml
- jdl/converters/jdl-to-json/jdl-to-json-basic-entity-converter.js
- jdl/converters/jdl-to-json/jdl-with-applications-to-json-converter.js
- jdl/converters/jdl-to-json/jdl-without-application-to-json-converter.js
- jdl/converters/parsed-jdl-to-jdl-object/application-converter.js
- jdl/exporters/applications/jhipster-application-formatter.js
- jdl/exporters/jhipster-entity-exporter.js
- jdl/jdl-importer.js
- jdl/jhipster/application-options.js
- jdl/jhipster/json-entity.js
- jdl/utils/format-utils.js
- test/cli/import-jdl.spec.js
- test/jdl/converters/JDLToJSON/jdl-to-json-basic-entity-information-converter.spec.js
- test/jdl/converters/JDLToJSON/jdl-with-applications-to-json-converter.spec.js
- test/jdl/converters/JDLToJSON/jdl-without-application-to-json-converter.spec.js
- test/jdl/converters/parsedJDLToJDLObject/application-converter.spec.js
- test/jdl/jdl-importer.spec.js
- test/jdl/jhipster/json-entity.spec.js
- test/jdl/utils/format-utils.spec.js
Contains the following changes:
- When importing entities only jdls, read `.yo-rc.json` on demand, current it requires `import-jdl` command to always pass `.yo-rc.json` data.
- Stop creating creationTimestamp
- When creationTimestamp exists in jdl, it should be passed as an int.
- Stop creating changelogDate.
--- …
> JDL changes.

- .github/workflows/webflux.yml
- generators/entity-server/templates/partials/it_patch_update.partial.java.ejs
- test-integration/samples/webflux-mysql/.yo-rc.json
This PR uses `isEqualByComparingTo` instead of `isEqualTo` to compare `BigDecimal`s in integration tests
--- …
> correct comparison of big decimals in integration tests

- .github/workflows/webflux.yml
- ~Move sqlfull test to postgres~ There are many-to-many build failures.
- ~Enable testcontainers for mysql.~ Doesn't solve the problem.
mysql driver seems problematic.
e2e responses takes too long to respond and fails too often.
---
When you are still working on …
> Fix webflux builds.

- generators/client/templates/angular/package.json
Reverts jhipster/generator-jhipster#12775
Reference https://github.com/jhipster/generator-jhipster/pull/12762.
> Revert "Bump zone.js from 0.10.3 to 0.11.1 in /generators/client/templates/angular"

- generators/client/templates/angular/package.json
Reverts jhipster/generator-jhipster#12755
Fixes https://github.com/jhipster/generator-jhipster/issues/12803
> Revert "Bump css-loader from 3.6.0 to 5.0.0 in /generators/client/templates/angular"

- generators/server/templates/src/main/java/package/config/OAuth2SsoConfiguration.java.ejs
- generators/server/templates/src/main/java/package/config/ReactiveSecurityConfiguration.java.ejs
- generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs
- generators/server/templates/src/main/java/package/config/UaaConfiguration.java.ejs
- generators/server/templates/src/main/resources/config/application.yml.ejs
- test-integration/scripts/24-tests-e2e.sh
- Fix an issue where liveness and readiness endpoints were not public which failed Kubernetes deployments.
- Improve `curl` tests to check more sample endpoints
---
> Fix liveness and readiness health endpoint access

- generators/generator-base.js
- generators/generator-transforms.js
Moving the `skip-generated-flag` check during the runtime. Adding a sub-generator for `fu` but this blocks me from generating the application. 
Also it looks like we are adding & checking this flag in the base generator, I think this should be in the server, entity-server, spring-{service, controller} generator only. 
--- …
> Allow generators/blueprints to force skipGeneratedFlag

- .github/workflows/angular.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
- cli/cli.js
- cli/environment-builder.js
- cli/import-jdl.js
- generators/app/index.js
- generators/entities-client/index.js
- generators/entities/index.js
- generators/entity-client/index.js
- generators/entity/index.js
- generators/generator-base.js
- jdl/jdl-importer.js
- jdl/validators/jdl-without-application-validator.js
- test/app/application-with-entities.js
- test/app/composing.js
- test/cli/cli.spec.js
- test/cli/import-jdl.spec.js
- test/entities/composing.js
- test/entity/database-changelog.spec.js
- test/jdl/validators/jdl-without-application-validator.spec.js
Changes in this PR:
- Implement entities generator.
- Update entity generator to compose with entities, so relationships can use otherEntity.
- Implement entities-client generator.
- Move rebuild webpack trigger to to entities-client instead of running at the last composed entity generator.
- Refactor import-jdl to use entities generator:
- Changes the behavior to fork only when no application config was found.
- Don't forward jdl exclusive options to generators due to unknown option.
Makes multiples applications compatible with incremental changelog.
Closes https://github.com/jhipster/generator-jhipster/issues/12696
Related to https://github.com/jhipster/generator-jhipster/issues/11896.
---
-   [ ] [All continuous …
> Implement entities generator.

- generators/generator-constants.js
The latest `lint-staged` version is working fine in Windows. So updating this dependency.
Related to #10312 and #11131
--- …
> Update lint-staged version

- generators/server/templates/src/main/java/package/web/rest/errors/ExceptionTranslator.java.ejs
Backported from main branch to 6.x
Fix #12829
---
> Exclude translation of DataAccessException when there's no database

- generators/cleanup.js
Fixes wrong cleanup path from #12400
---
> [angular] Fix #12400 cleanup

- generators/client/templates/angular/src/main/webapp/app/shared/alert/alert-error.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/shared/alert/alert.component.ts.ejs
https://github.com/SonarSource/SonarJS/issues/1930 is resolved.
I tested with the latest SonarQube 8.5.1 and this is resolved in this version.
So removing `NOSONAR` which is no more needed.
---
When you are still working on the PR, consider converting it to Draft …
> [angular] Remove NOSONAR for optional call as this is resolved in SonarJs

- .github/workflows/triage.yml
This adds support to the triage action to gracefully handle the case where both area and theme labels are already added.
Related to https://github.com/jhipster/generator-jhipster/pull/12641
---
When you are still working on the PR, consider converting it to Draft …
> Fix Triage Github Action Failure on Already Existing Labels

- generators/server/templates/build.gradle.ejs
Before invoking e.g. `./gradlew verify -Ptestcontainers` did not start the containers as the reactive test extensions looks for en environment variable `SPRING_PROFILES_ACTIVE` which we don't set. Therefore containers where not used during integration tests. It works for non reactive sql as is.
---
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/m …
> fix testcontainers gradle integration when using sql and reactive

- generators/client/templates/angular/src/main/webapp/app/shared/alert/alert-error.component.ts.ejs
While answering to #12796 found that `alert-error.component` can be simplyfied. This simplification is done in this PR and made also `addErrorAlert` private as this is not used outside the class.
--- …
> [angular] Polish error alert component

- generators/client/templates/angular/src/main/webapp/app/admin/configuration/configuration.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/gateway/gateway.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/health/health-modal.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/health/health-modal.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/health/health.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/health/health.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/health/health.service.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/admin/health/health.component.spec.ts.ejs
The only difference is that Angular `keyvalue` orders keys by default but ng-jhipster `keys` doesn't.
The only place where Spring doesn't return ordered keys is configuration properties, but ordered keys is also there better, can find values easier.
Related to #12909, moves `keys.pipe` to unused list.
--- …
> [angular] Use standard Angular pipe keyvalue instead of ng-jhipster keys

- cli/cli.js
Since removing meow dependency, jhipster exists with code 0 on prettier errors.
This workarounds this bug.
--- …
> Exit jhipster process on unhandledRejection.

- generators/client/templates/angular/src/main/webapp/app/admin/logs/logs.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/logs/logs.component.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/admin/logs/logs.component.spec.ts.ejs
Add sorting icons on table header to reflect sorting status.  
If sorted by level then now secondary sorting is done by name ascending (was random order before).  
This also removes need for `ng-jhipster` pipes `filter.pipe`, `pure-filter.pipe` and `order-by.pipe` in `generator-jhipster`.  
As those are last pipes used from `ng-jhipster` then no pipes is used from `ng-jhipster` in `generator-jhipster` any more after this PR.
FYI:
* exists https://github.com/danrevah/ngx-pipes so if we want to use general purpose pipes in future then we should first consider using this or similar library
* in Vue we are using external library: https://github.com/freearhey/vue2-filters
---
-   [x] [All continuous integration …
> [angular] Improve logs view

- generators/generator-constants.js
The version of JHipster Control Center is wrong. Change version from v0.1.O to v0.1.0.
> Fix version of JHipster Control Center to v0.1.0

- generators/client/templates/angular/src/main/webapp/app/core/request/request-util.ts.ejs
In #12939 I moved request model into separate file. Now I noticed that forgot remove this model from `request-util`. This PR fixes that.
--- …
> [angular] Remove model definitions from request-util

- generators/generator-base.js
- generators/generator-defaults.js
- generators/generator-transforms.js
- test/app.spec.js
After some discussions with @jdubois, we think it's better to not generate this annotation by default.
It will be available by flag + config.
Related to https://github.com/jhipster/generator-jhipster/issues/12459
Following these PRs: https://github.com/jhipster/generator-jhipster/pull/12569 https://github.com/jhipster/generator-jhipster/pull/12811
Is it ok for your blueprint @sendilkumarn ?
---
-   [ ] Coding Rules & Commit …
> Change skipGeneratedFlag to withGeneratedFlag

- generators/server/templates/build.gradle.ejs
- generators/server/templates/pom.xml.ejs
This simplifies the Maven and Gradle builds, as those are forced by the JHipster framework (no project could work without them)
-   [X] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
> Remove direct dependencies to Spring AOP and Logback Encoder

- generators/entity-server/templates/src/main/java/package/service/EntityService.java.ejs
- generators/entity-server/templates/src/main/java/package/service/impl/EntityServiceImpl.java.ejs
- generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs
- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
- utils/entity.js
Both variables are strictly identical since reactive sql has been supported in entity generator, no need to keep both
See https://github.com/jhipster/generator-jhipster/pull/11742#discussion_r489004426
---
When you are still working on the PR, consider converting …
> entity: replace `reactiveRepositories` variable by `reactive`

- generators/utils.js
It is to fix the issue when `lines[otherwiseLineIndex]` is undefined.
I don't know how to reproduce it, but I encounter this issue several times.
This is for securing our code
---
When you are still working on the PR, consider converting it to Draft (bellow …
> Fix rewrite when value is undefined

- generators/client/templates/angular/src/main/webapp/swagger-ui/index.html.ejs
- generators/client/templates/react/src/main/webapp/swagger-ui/index.html.ejs
- generators/client/templates/vue/src/main/webapp/swagger-ui/index.html.ejs
This is my workaround for #12412. It does not remove the Swagger UI `additionalProps: "string"` content but it patches it when detected so that requests to management endpoints from Swagger UI work out of the box (no need to remove the sample request anymore).
---
-   [X] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary …
> remove the sample Swagger UI request body if present fix #12412

- generators/heroku/index.js
The heroku sub-generator still seems to use the master branch instead of main. This resolves that.
Related to https://github.com/jhipster/generator-jhipster/pull/12718 and #11935
---
When you are still working on the PR, consider converting it to Draft (bellow …
> Rename master branch to main in the the heroku sub-generator

- .github/MAINTAINERS_REPLY_TEMPLATES/GUIDELINES_NOT_FOLLOWED.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/angular.yml
- .github/workflows/react.yml
- .github/workflows/release-drafter.yml
- .github/workflows/webflux.yml
- CONTRIBUTING.md
- azure-pipelines.yml
- generators/azure-app-service/templates/github/workflows/azure-app-service.yml.ejs
- generators/azure-spring-cloud/templates/github/workflows/azure-spring-cloud.yml.ejs
- generators/ci-cd/templates/github-ci.yml.ejs
- generators/client/templates/angular/src/main/webapp/index.html.ejs
- generators/client/templates/react/src/main/webapp/index.html.ejs
- generators/heroku/index.js
- generators/server/templates/src/main/docker/config/git2consul.json.ejs
- generators/server/templates/src/main/resources/config/bootstrap-prod.yml.ejs
- generators/server/templates/src/main/resources/config/bootstrap.yml.ejs
- test-integration/scripts/10-install-jhipster.sh
- test-integration/scripts/25-sonar-analyze.sh
- test/heroku.spec.js
- test/upgrade.spec.js
This is needed for jhispter-online to work correctly as jhipster-online is already migrated to main branch
Resolve https://github.com/jhipster/jhipster-online/issues/258
---
When you are still working on the PR, consider converting it to Draft (bellow reviewers) …
> Rename master branch to main in the 6.x maintenance branch

- cli/jhipster-command.js
- cli/program.js
- generators/app/index.js
- generators/generator-base.js
- generators/languages/prompts.js
- utils/language.js
--native-language:
- Without a value, try to detect using user locale.
--language:
- Appends to existing languages.
Native language prompt:
- defaults to detected language.
Closes https://github.com/jhipster/generator-jhipster/issues/12900
--- …
> Implement i18n cli options.

- generators/client/templates/angular/package.json.ejs
- generators/client/templates/common/package.json
- generators/client/templates/react/package.json.ejs
- generators/client/templates/vue/package.json
- generators/client/templates/vue/package.json.ejs
- generators/generator-constants.js
This PR follows https://github.com/jhipster/generator-jhipster/pull/12972
It uses husky and lint-staged from constants, updates some vue dependencies where possible and save (e.g. terser plugin 5.x is not compatible with webpack 4). Some of the common dependencies are can now be managed by dependabot. Didn't put vue core on purpose yet until we are on vue3.
--- …
> [vue] let dependabot manage some vue dependencies

- generators/server/files.js
- generators/server/templates/build.gradle.ejs
- generators/server/templates/pom.xml.ejs
- generators/server/templates/src/test/java/package/config/JHipsterBlockHoundIntegration.java.ejs
- generators/server/templates/src/test/resources/META-INF/services/reactor.blockhound.integration.BlockHoundIntegration.ejs
> [webflux] Re-enable blockhound and whitelist BoundedElasticScheduler.schedule

- jdl/jdl-importer.js
- jdl/validators/jdl-with-application-validator.js
- jdl/validators/jdl-without-application-validator.js
- test/jdl/jdl-importer.spec.js
- test/jdl/validators/jdl-with-application-validator.spec.js
- test/jdl/validators/jdl-without-application-validator.spec.js
> Remove Database validation in jdl

- generators/client/files-react.js
Do not break logo during generation (do the same than in Angular)
> fix: do not break logo during generation

- generators/server/templates/src/test/resources/config/application.yml.ejs
Related to https://github.com/jhipster/generator-jhipster/issues/13038
Apply `hibernate.query.fail_on_pagination_over_collection_fetch: true` in test config as well.
This will avoid to write working SQL requests (just showing a warning) during tests but failing in production.
> fix: add hibernate fail pagination option in test config as well

- generators/client/templates/vue/src/main/webapp/app/account/login.service.ts.ejs
- generators/client/templates/vue/src/main/webapp/app/core/jhi-navbar/jhi-navbar.vue.ejs
- generators/client/templates/vue/src/test/javascript/spec/app/account/login.service.spec.ts.ejs
> Login redirect doesn't work in OAuth2 and Vue

- generators/heroku/index.js
When a Heroku app is not found, the user is prompted to re-run `jhipster heroku` to create a new deployment.  To enable regenerating the Heroku deployment, the `herokuAppName` config is set to `null`.  
The config is later saved with the value of `this.herokuAppName` in the [`saveConfig` step](https://github.com/jhipster/generator-jhipster/blob/e885becfb626467ce077e5fccb274eaa531255c2/generators/heroku/index.js#L308-L317), rather than `null`.
This commit fixes the behavior.  Now, when an app is not found, re-running `jhipster heroku` prompts you to create a new deployment.  It also skips other steps when finding the app fails (such as editing the pom.xml).
Related to [this StackOverflow question](https://stackoverflow.com/questions/64826441/getting-could-not-find-application-error-when-run …
> fix heroku reprompting for app name when not found

- generators/client/templates/angular/angular.json.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/logs/logs.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics-system/metrics-system.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics.model.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/app.main.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/shared/sort/sort-by.directive.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/shared/sort/sort.directive.ts.ejs
- generators/client/templates/angular/tsconfig.json.ejs
Reference: https://angular.io/guide/strict-mode
`fullTemplateTypeCheck` is subset of `strictTemplates` so no need to specify this.
Removed `suppressImplicitAnyIndexErrors` and added `strictInputAccessModifiers` and fixed errors after that, some comments:
* in my Windows 10 metrics for `system.load.average.1m`, `process.files.max` and `process.files.open` are not coming from back end, but those are used in templates, so added those as optional to model
* HMR support is improved lately (see https://github.com/angular/angular-cli/pull/18788), maybe in Angular 11 manual `module.hot` fork can be removed at all
---
-   [ …
> [angular] Use config similar to Angular strict mode

- generators/client/templates/angular/src/main/webapp/app/core/interceptor/notification.interceptor.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/util/alert.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/shared/alert/alert-error.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/shared/alert/alert.component.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/core/util/alert.service.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/shared/alert/alert-error.component.spec.ts.ejs
Follow up to #13022 and closes #12796
In the process of cleaning found and fixed couple of bugs.
* If manually closing alerts then space in HTML page was not released before alert timeout was reached. Reason: as per https://ng-bootstrap.github.io/#/components/alert/api the correct output for listening manual close events is `closed` but was `close`. Changed to `closed` which fixed this.
* If one alert is showed and user closes manually and second alert is showed before first alert timeout reaches then second alert was closed when first alert timeout reached. Fixed.
---
-   [ …
> [angular] Clean and fix alert service and components

- generators/client/templates/angular/tsconfig.json.ejs
Angular strict mode doesn't have this so removing this to be closer to https://angular.io/guide/strict-mode
Follow up to #13065
--- …
> [angular] Remove skipLibCheck from tsConfig

- generators/client/templates/react/.eslintrc.json.ejs
In #12872 I disabled some ESLint rules in order to bump ESLint to v7 in React. I missed one and it caused a daily build to fail.
--- …
> Disable react eslint rule to fix Daily Build

- generators/generator-base-private.js
In the example:
```
entity Department
entity Location
relationship OneToOne {
Department{location} to Location
}
dto * with mapstruct
```
DTOs are now unflattend (in https://github.com/jhipster/generator-jhipster/pull/12947). Instead of calling for `this.locationService.find(department.locationId)`, we should call `this.locationService.find(department.location.id)`.
Fix #13080
-   [x] Coding Rules & Commit Guidelines as per our …
> fix entity query to use unflattened DTO

- generators/client/templates/angular/tsconfig.json.ejs
Daily builds using Angular with Protractor are failing because of #13075  
For example https://github.com/hipster-labs/jhipster-daily-builds/runs/1417030608  
Reason: Jest and Mocha types are conflicting.  
This PR puts `skipLibCheck` back if Protractor tests are used which fixes Protractor tests in Angular.
--- …
> [angular] Fix Protractor tests in Angular

- generators/client/templates/angular/tsconfig.json.ejs
- generators/client/templates/angular/tsconfig.spec.json.ejs
Follow up to #13065 and #13075  
As `Jest` needs `emitDecoratorMetadata` then moved this to `tsConfig.spec`  
After this PR (in conjuction with #13065 and #13075) Angular strict mode: https://angular.io/guide/strict-mode is achieved.
---
When you are still working …
> [angular] Move emitDecoratorMetadata from tsConfig to tsConfig.spec

- generators/client/templates/angular/src/test/javascript/spec/app/shared/translate.directive.spec.ts.ejs
Follow up to #13022 - didn't notice one deprecated function, removing now.
---
> [angular] Remove deprecated functionality

- generators/common/templates/.lintstagedrc.js.ejs
Remove the following `lint-staged` warning:
‼ Some of your tasks use `git add` command. Please remove it from the config since all modifications made by tasks will be automatically added to the git commit index.
--- …
> Remove lint-staged warning about git add

- generators/client/files-angular.js
- generators/client/templates/angular/package.json.ejs
- generators/client/templates/angular/src/main/webapp/app/app.module.ts.ejs
- test/utils/expected-files.js
`DatePipe` as provider was used only in `audits` module. As `audits` module was deleted then we can remove also `DatePipe` from application providers.
`CookieService` is used only on `session` + `websocket` combination, so removing this for other configurations.
Polished code a bit.
---
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBU …
> [angular] Clean app.module

- generators/client/templates/angular/webpack/webpack.custom.js.ejs
While migrating to Angular CLI in #10624 this websockets block was lost which causes Websockets not to work with Browsersync. Putting back which fixes this issue.
---
When you are still working on the PR, consider converting it to Draft (bellow reviewers) and …
> [angular] Fix WebSockets in Browsersync

- generators/cleanup.js
Follow up to #13098
As CsrfService is now used only in very specific case then we need to clean it up for most cases.
--- …
> [angular] Clean up csrf.service

- generators/server/templates/src/main/java/package/web/rest/AccountResource.java.ejs
---
Boolean method 'checkPasswordLength' is always inverted 
Inspection info: Reports methods with a boolean return type, which are only used in a negated context …
> Simplify Code AccountResource

- generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
- generators/entity-server/templates/src/main/java/package/service/dto/EntityDTO.java.ejs
- generators/server/templates/src/main/java/package/domain/User.java.ejs
Use `getClass().hashCode()` instead of `31` as Entity hashCode, as mentioned in #10097 (initially #8656).
I noticed that @Shaolans copied this implementation to `EntityDTO.hashCode` (commit 6a66c401), so I also updated it even if I'm not sure why it absolutely needs to be aligned, as DTOs don't have the same constraints as JPA Entities regarding equals and hashCode.
---
-   [X] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [X] Coding Rules & Commit Guidelines as per our …
> replaced 31 with getClass().hashCode() for Entity hashCode

- generators/server/templates/src/main/resources/config/application-dev.yml.ejs
- generators/server/templates/src/main/resources/config/application-prod.yml.ejs
- generators/server/templates/src/test/resources/config/application.yml.ejs
Use a logger to debug SQL requests.
`spring.jpa.show-sql` writes to standard output.
(https://thorben-janssen.com/hibernate-logging-guide)
> refactor: use a logger to debug SQL

- generators/client/files-angular.js
- generators/client/files-react.js
- generators/client/files-vue.js
- generators/client/templates/angular/.npmrc.ejs
- generators/client/templates/react/.npmrc.ejs
- generators/client/templates/vue/.npmrc.ejs
- generators/upgrade/index.js
- package.json
- test/upgrade.spec.js
- test/utils/expected-files.js
- Add `.npmrc` file to run npm use `legacy-peer-deps` option.
- Change upgrade generator to use `legacy-peer-deps` option.
Related to https://github.com/jhipster/generator-jhipster/issues/12747
--- …
> Fixes for npm 7.

- jdl/validators/relationship-validator.js
- test/jdl/validators/relationship-validator.spec.js
is no more difference on the code when creating a OneToMany or a ManyToOne relationship (with sides inverted), and the resulting code expected is the same.
So I just disabled the check, and it seems to work perfectly
---
-   [X] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
When you are still working on the PR, …
> allow ManyToOne to also use back reference

- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs
Simplify code, this part is no longer required.
Now, the use of normalized DTO ensures that a User is defined (linked to the entity) or not.
There is no "login" field in the handled Entity anymore that can be empty.
(The issue was only when DTO are used).
initial issue: https://github.com/jhipster/generator-jhipster/issues/12784
> Revert "[react] Fix default values in entity form"

- generators/entity/prompts.js
Rename questions on pagination.
Includes 'sorting' wording as it is only available if pagination is enabled.
> refactor: rename pagination questions

- generators/client/templates/react/src/main/webapp/app/modules/home/home.tsx.ejs
Fix
ps: maybe not elegant but we can't update global.json between it's used by Angular and React
--- …
> [react] Fix: No space between words

- jdl/converters/jdl-to-json/jdl-to-json-relationship-converter.js
- jdl/converters/json-to-jdl-entity-converter.js
- jdl/converters/parsed-jdl-to-jdl-object/parsed-jdl-to-jdl-object-converter.js
- jdl/converters/parsed-jdl-to-jdl-object/relationship-converter.js
- jdl/models/jdl-relationship.js
- jdl/parsing/jdl-ast-builder-visitor.js
- jdl/parsing/jdl-parser.js
- jdl/validators/relationship-validator.js
- test/jdl/converters/JDLToJSON/jdl-to-json-relationship-converter.spec.js
- test/jdl/converters/JDLToJSON/jdl-with-applications-to-json-converter.spec.js
- test/jdl/converters/JDLToJSON/jdl-without-application-to-json-converter.spec.js
- test/jdl/converters/parsedJDLToJDLObject/parsed-jdl-to-jdl-object-converter.spec.js
- test/jdl/converters/parsedJDLToJDLObject/relationship-converter.spec.js
- test/jdl/grammar/grammar.spec.js
- test/jdl/jdl-importer.spec.js
- test/jdl/models/jdl-relationship.spec.js
- test/jdl/test-files/annotations.jdl
- test/jdl/test-files/big_sample.jdl
- test/jdl/test-files/capitalized_annotations.jdl
- test/jdl/validators/relationship-validator.spec.js
> Fixes to JDL annotation parsing

- generators/cleanup.js
- generators/entity-client/index.js
This PR has 2 commits:
* first commit is follow up to #13171, instead of deleting whole `spec` folder, delete file by file
* second commit is follow up to #12815, instead of deleting whole `spec/helpers` folder, delete file by file
---
When you are still working on …
> [angular] Improve test files cleanup

- generators/client/templates/angular/src/main/webapp/app/account/activate/activate.route.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/account/password-reset/finish/password-reset-finish.route.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/account/password-reset/init/password-reset-init.route.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/account/password/password.route.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/account/register/register.route.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/account/sessions/sessions.route.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/account/settings/settings.route.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/auth/user-route-access.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/home/home.route.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/layouts/error/error.route.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/login/login.route.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-routing.module.ts.ejs
This PR fixes the following problems related to `UserRouteAccessService` and it's usages.
Some routes require `ROLE_USER` role, but data shown in those routes and operations done there are allowed in back end without role restriction.
Developer can assume that if route is protected in front end then data and operations related to this route should be protected also in back end and this can lead to security issues.
This PR removes role restrictions from such routes in the front end.
If developer defines routes without restricting those to some roles then `UserRouteAccessService` allowed unauthenticated users to go to that page (but page was empty).
Correct is to route to login page and after successful login user is landing in requested page as this is after this PR.
---
Please make sure …
> [angular] Fix UserRouteAccessService

- generators/client/templates/angular/src/main/webapp/app/admin/user-management/list/user-management.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/list/user-management.component.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/list/infinite-scroll-template.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/list/no-pagination-template.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/list/pagination-template.ejs
Having method which has one line which executes another method is not very useful. So removing wrapper and using final method directly.
--- …
> [angular] Remove one line methods for refresh

- generators/client/needle-api/needle-client-angular.js
- generators/entity-client/files.js
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-routing.module.ts.ejs
- generators/generator-base.js
- test/needle-api/needle-client-angular.spec.js
Adds possibility to add page title through needle API to Angular client's entity and admin routes.
Uses this possibility to add page title to entity route in entity generation and removes page title 4-time copy from entity child routes.
--- …
> Improve page title logic for Angular client

- generators/entity-client/files.js
- generators/generator-base.js
Follow up to #13194 - changes after review from @mshima
---
> Simplify addEntityToModule and document better addAdminRoute.pageTitle

- generators/entity-client/files.js
- generators/generator-base.js
Follow up to #13198 
`microserviceName` is missing from `this` in `generator-base.js` but is available in `files.js` (other variables are available in both places). So reverting partially #13198
--- …
> Fix EntityRoutingModule in Angular for microservices

- generators/client/needle-api/needle-client-angular.js
- generators/entity-client/files.js
- generators/generator-base.js
- test/needle-api/needle-client-angular.spec.js
- test/needle-api/needle-client-vue.spec.js
Follow up to #13198 and #13202
This reverts commits 5223cbf3d707bf832ea9f5acb445c36a9b2ffe50 and d46a732b9bf262657669f15af5f6100b18931025 and renames all `microServiceName` occurences to `microserviceName`.
--- …
> Simplify again addEntityToModule and rename microServiceName to microserviceName

- generators/client/templates/angular/src/main/webapp/app/admin/metrics/blocks/metrics-garbagecollector/metrics-garbagecollector.component.html.ejs
Garbage collection title was not translated if `jhiPrefix` was not `jhi`, this PR fixes that.
---
> [angular] Fix garbage collection title translation

- generators/common/templates/sonar-project.properties.ejs
Should fix Angular part of #13232
---
> [angular] Fix Angular Sonar coverage and security hotspots

- generators/common/templates/sonar-project.properties.ejs
Follow up to #13233 to fix bug it introduced and really fix coverage issue and tests related security hotspots in Angular.
Related to #13232 
--- …
> Fix Sonar error and problems related to Angular tests location

- generators/common/templates/sonar-project.properties.ejs
As `sonar.test.inclusions` includes full paths then `sonar.tests` is not needed.
As `sonar.test.inclusions` allows spaces then adding space after comma for better readability.
Follow up to #13235 and #13233
Related to #13232 
---
When you are still working on the …
> Simplify and polish Sonar config for Angular

- generators/client/templates/angular/package.json
- generators/client/templates/angular/package.json.ejs
Should prevent dependabot from creating PRs that contains peer dependency on webpack 5 like https://github.com/jhipster/generator-jhipster/pull/13239
--- …
> [angular] Add dependency on webpack, to help dependabot.

- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-routing.module.ts.ejs
According to https://angular.io/guide/module-types#summary-of-ngmodule-categories routed modules should not export anything. This export is just redundant, no use from this.
---
When you are still working on the PR, consider converting it to Draft (bellow …
> [angular] Remove redundant export from entity routed module

- .github/workflows/angular.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
- test-integration/samples/jdl-entities/entities.jdl
- test-integration/scripts/00-init-env.sh
- test-integration/scripts/11-generate-config.sh
- test-integration/scripts/12-generate-project.sh
JDL entities must be executed after copying `.yo-rc.json` and before generating the project (`jhipster --with-entities`).
- Create `11-generate-config.sh` and deprecate `11-generate-entities.sh`
`11-generate-config.sh` copy `.yo-rc.json`, json entities and generates entities from jdl afterwards.
---
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/ …
> Add support to JDL entities at CI scripts.

- generators/kubernetes/templates/istio/gateway.yml.ejs
remove extra services prefix for istio gateway.
Tagging @saturnism since he updated this previously. Last week when I was demo-ing this on current Istio version, this caused an error. Can we remove this?
> remove services prefix for istio gateway

- generators/server/templates/pom.xml.ejs
Add some missing `<version>${mapstruct.version}</version>` to honor the version defined in the current POM.
Otherwise it takes the one from the BOM.
(or should we remove the `<mapstruct.version>1.4.1.Final</mapstruct.version>` from the properties of the current POM ?)
I realized this after upgrading to IntelliJ 2020.3 that requires mapstruct 1.4.1 to build mapping implementation
> fix: add missing mapstruct version property

- generators/client/templates/react/src/main/webapp/app/shared/util/entity-utils.ts.ejs
- generators/client/templates/react/src/test/javascript/spec/app/shared/util/entity-utils.spec.ts.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs
Fix the root issue of https://github.com/jhipster/generator-jhipster/issues/13182
And fix an underlying issue where the relations from a many-to-many are set from the previous save. 
the `value` from `AvInput` should be set once.
This same "solution" is already applied with: `AvForm model={isNew ? {} : fooEntity}`
> Fix many to many (React)

- test/ci-cd.spec.js
- test/templates/ci-cd/maven-ngx-npm/pom.xml
Following this https://github.com/jhipster/generator-jhipster/pull/12134 when we dropped Yarn support, a lot of tests in CICD have been removed
cc @avdev4j for the review and some :beers:  ! :-)
preparing work on https://github.com/jhipster/generator-jhipster/issues/12441
---
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) …
> CI-CD: add back tests

- generators/common/templates/sonar-project.properties.ejs
Fixes warning "The use of sonar.typescript.lcov.reportPaths for coverage import is deprecated, use sonar.javascript.lcov.reportPaths instead.".
--- …
> Change Sonar deprecated property to non deprecated one

- generators/entity-client/templates/angular/src/main/webapp/app/entities/delete/entity-management-delete-dialog.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/detail/entity-management-detail.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/detail/entity-management-detail.component.spec.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.spec.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/list/infinite-scroll-template.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.spec.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.ts.ejs
`trackById` and `getSelected` functions used to assume that `id` always exists.
Refactor to `trackEntityByField` format and `getSelectedEntity`.
--- …
> [angular] fixes for custom ids

- generators/entity-server/templates/src/main/java/package/common/patch_template.ejs
- generators/entity-server/templates/src/main/java/package/service/EntityService.java.ejs
- generators/entity-server/templates/src/main/java/package/service/impl/EntityServiceImpl.java.ejs
#13232
Fix errors **Call Optional#isPresent() before accessing the value**
---
> Fix some sonar analysis: Call Optional#isPresent() before accessing the value

- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
- generators/server/files.js
- generators/server/templates/src/test/java/package/CassandraKeyspaceIT.java.ejs
- generators/server/templates/src/test/java/package/IntegrationTest.java.ejs
- generators/server/templates/src/test/java/package/config/timezone/HibernateTimeZoneIT.java.ejs
- generators/server/templates/src/test/java/package/security/DomainUserDetailsServiceIT.java.ejs
- generators/server/templates/src/test/java/package/service/MailServiceIT.java.ejs
- generators/server/templates/src/test/java/package/service/UserServiceIT.java.ejs
- generators/server/templates/src/test/java/package/web/rest/AccountResourceIT.java.ejs
- generators/server/templates/src/test/java/package/web/rest/AccountResourceIT_oauth2.java.ejs
- generators/server/templates/src/test/java/package/web/rest/AccountResourceIT_skipUserManagement.java.ejs
- generators/server/templates/src/test/java/package/web/rest/LogoutResourceIT.java.ejs
- generators/server/templates/src/test/java/package/web/rest/UserJWTControllerIT.java.ejs
- generators/server/templates/src/test/java/package/web/rest/UserResourceIT.java.ejs
- generators/server/templates/src/test/java/package/web/rest/errors/ExceptionTranslatorIT.java.ejs
- generators/spring-controller/templates/src/test/java/package/web/rest/ResourceIT.java.ejs
This composite annotation is meant to abstract complexity of common
Integration test annotations in a single file. This commit also adds the
annotation to required integration test files.
Fix #12460
---
When you are still working on the PR, consider converting it …
> Add new IntegrationTest annotation

- generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.spec.ts.ejs
- generators/generator-base-private.js
Follow up to #13257 second commit https://github.com/jhipster/generator-jhipster/pull/13257/commits/f9b8e42b50a61ab6ae3b236a7f57800b3bfb606d which added unit tests.
This PR:
* polishes imports
* adds similar `describe` + `it` hierarchy as previous tests had
* renames variables to better reflect their meaning
* in `getSelected` tests it's not correct to compare object values, instead object references needs to be compared, after switching from value to reference comparing found bug:
- `otherEntity.primaryKey.fields` is empty if `many-to-many` relationship `otherEntityField` is not `id` (JobHistory.employee.otherEntityField = 'firstName') - so used `otherEntity.primaryKey.type` to get fixed tests to pass
* adds more complete tests for `getSelected`
Below is config for tracking …
> Polish and fix entity update tests in Angular

- .github/workflows/angular.yml
- generators/database-changelog-liquibase/index.js
- generators/database-changelog-liquibase/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs
- generators/database-changelog-liquibase/templates/src/main/resources/config/liquibase/changelog/added_entity_constraints.xml.ejs
- generators/database-changelog-liquibase/templates/src/main/resources/config/liquibase/fake-data/table_entity.csv.ejs
- generators/entity-server/index.js
- generators/entity-server/templates/partials/it_patch_update.partial.java.ejs
- generators/entity-server/templates/src/main/java/package/common/patch_template.ejs
- generators/entity-server/templates/src/main/java/package/common/save_template.ejs
- generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
- generators/entity-server/templates/src/main/java/package/repository/EntityRepositoryInternalImpl_reactive.java.ejs
- generators/entity-server/templates/src/main/java/package/repository/rowmapper/EntityRowMapper.java.ejs
- generators/entity-server/templates/src/main/java/package/service/EntityQueryService.java.ejs
- generators/entity-server/templates/src/main/java/package/service/dto/EntityCriteria.java.ejs
- generators/entity-server/templates/src/main/java/package/service/mapper/EntityMapper.java.ejs
- generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs
- generators/entity-server/templates/src/main/resources/config/cql/changelog/added_entity.cql.ejs
- generators/entity-server/templates/src/test/gatling/user-files/simulations/EntityGatlingTest.scala.ejs
- generators/entity-server/templates/src/test/java/package/domain/EntityTest.java.ejs
- generators/entity-server/templates/src/test/java/package/service/dto/EntityDTOTest.java.ejs
- generators/entity-server/templates/src/test/java/package/service/mapper/EntityMapperTest.java.ejs
- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
- generators/entity/index.js
- generators/generator-base-private.js
- generators/server/index.js
- test-integration/samples/jdl-entities/custom-id.jdl
- utils/entity.js
- utils/field.js
This PR adds support to custom ids:
```
entity Foo {
id UUID
}
```
and
```
entity Foo {
@Id customId Long
}
```
Relationships are not complete yet.
Angular and CI changes split into https://github.com/jhipster/generator-jhipster/pull/13257 and https://github.com/jhipster/generator-jhipster/pull/13204
--- …
> Add support to custom ids.

- .mocharc.js
- generators/generator-base.js
- test/templates/ngx-blueprint/HelloVue.html.ejs
HTML files will now be included in prettier command
Fix #13090
---
> Add html to prettier

- generators/client/templates/angular/src/main/webapp/app/account/sessions/sessions.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/account/settings/settings.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/detail/user-management-detail.component.html.ejs
- generators/client/templates/react/src/main/webapp/app/modules/account/sessions/sessions.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management-detail.tsx.ejs
- generators/client/templates/vue/src/main/webapp/app/account/change-password/change-password.vue.ejs
- generators/client/templates/vue/src/main/webapp/app/account/sessions/sessions.vue.ejs
- generators/client/templates/vue/src/main/webapp/app/account/settings/settings.vue.ejs
- generators/client/templates/vue/src/main/webapp/app/admin/user-management/user-management-view.vue.ejs
- generators/common/templates/sonar-project.properties.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-detail.tsx.ejs
- generators/languages/templates/src/main/webapp/i18n/hr/sessions.json
- generators/languages/templates/src/main/webapp/i18n/uz-Cyrl-uz/password.json
- generators/languages/templates/src/main/webapp/i18n/uz-Cyrl-uz/sessions.json
- generators/languages/templates/src/main/webapp/i18n/uz-Cyrl-uz/settings.json
- generators/languages/templates/src/main/webapp/i18n/zh-cn/sessions.json
- generators/languages/templates/src/main/webapp/i18n/zh-tw/sessions.json
As we are not using `<i>` any more for Font Awesome icons then we can enable `BoldAndItalicTagsCheck` in Sonar.
Replaced some `<b>` with `<strong>` to pass Sonar.
---
When you are still working on the PR, consider converting it to Draft (bellow reviewers) and …
> Remove Sonar <i> and <b> exclusions

- generators/client/templates/angular/package.json
As dependabot in some reason is not doing PR-s for `@angular-eslint` then updating manually this version before v7.
In #12835 was migrated from TSLint to Angular ESLint.
As Angular ESLint is still in beta then some comments about that.
In https://github.com/angular-eslint/angular-eslint is list of codelyzer rules which need to be converted to Angular ESLint. Total 53 rules, ATM 44 is done and 9 to do.
If I understand correctly then their aim for 1.0.0 is to offer seemless migration from TSLint to Angular ESLint through Angular CLI. But as 9 rules is not yet migrated then this goal has not yet been met.
So if someone uses some of those 9 unmigrated rules then this user must add TSLint + Codelyzer back after migrating to JHipster v7.
Angular CLI is still generating code with TSLint but in …
> [angular] Update angular-eslint

- generators/server/prompts.js
Fix for Reactive generation. CLI did not take into account reactive answer in server side options.
---
Fix #13298
> Move reactive answer from askForOptionalItems to askForServerSideOpts

- generators/server/templates/src/main/java/package/config/WebConfigurer.java.ejs
- generators/server/templates/src/main/java/package/web/rest/errors/ExceptionTranslator.java.ejs
Fix 2 bugs on Java code related to "Null pointers should not be dereferenced" Sonar rule.
Before
After
Fixed during a stream session : https://www.twitch.tv/avdev4j
---
When you are still working on the PR, consider converting it to Draft (bellow reviewers) and …
> Fix Sonar bugs "Null pointers should not be dereferenced"

- generators/client/templates/angular/src/main/webapp/app/admin/configuration/configuration.component.html.ejs
Working fine in SonarQube 8.6.0 and should work in SonarCloud too as Prettier for HTML anyway moved NOSONAR comment to the next line and no Sonar bug in JHipster default application in SonarCloud.
--- …
> [angular] Remove NOSONAR as latest SonarHTML supports Angular attribute binding

- generators/common/templates/editorconfig.ejs
Prettier indents HTML with 2 spaces. Aligning `.editorconfig` also to that value.
---
> Align .editorconfig with .prettierrc in HTML tabWidth

- generators/client/needle-api/needle-client-angular.js
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.module.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/route/entity-management-routing.module.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.ts.ejs
- test/needle-api/needle-client-angular.spec.js
In #12549 was changed entity module and entity update component.
In current draft PR #12971 entity module will be modified and entity update component changes are deleted.
For v7 beta release I propose to polish entity module and entity update component part with this PR. This PR follows suggestions from Angular module documentation: https://angular.io/guide/module-types
According to this documentation:
* `EntityRoutingModule` belongs to **Routing** module category
* `EntityModule` belongs to **Routed** module category
For #12971 my suggestion is to split detail and update components into 2 different ones, `Component` + `RoutedComponent`:
* `Component` contains entity data related html and has `@Input() entity: IEntity;`, for this component is created separate module `ComponentModule` …
> [angular] Polish entity modules and update component

- generators/client/files-vue.js
- test/vue.spec.js
when we try to generate a vue client without admin ui and no internationalization, it looks to replace translation on admin files that doesn't exist
---
> Replace translation for vue admin ui only when admin ui is generate

- jdl/converters/jdl-to-json/jdl-with-applications-to-json-converter.js
- test/cli/import-jdl.spec.js
- test/jdl/converters/JDLToJSON/jdl-with-applications-to-json-converter.spec.js
- test/jdl/jdl-importer.spec.js
- test/jdl/test-files/applications_with_and_without_entities.jdl
- test/templates/import-jdl/apps-with-and-without-entities.jdl
Fixes bug to include applications with or without entities from the
config file, where applications without entities was ignored from a list
of applications with atleast one application with entities
Fix #13141
--- …
> Generate applications without entities among a mixed list in JDL

- generators/app/index.js
- generators/generator-base-private.js
- generators/generator-transforms.js
- When using vue app using prompts, configuration must be ready when registering prettier.
See https://github.com/jhipster/generator-jhipster/pull/12639#issuecomment-748351773.
- Files with prettier errors are not written to disk, making it more difficult to debug.
Add option to ignore prettier errors, so the broken file is written to disk.
--- …
> Postpone prettier registering and add option to ignore prettier errors.

- generators/generator-constants.js
- generators/server/templates/src/main/docker/jhipster-control-center.yml.ejs
> Upgrade to Jhipster Control Center image Docker to v0.2.0

- generators/generator-constants.js
> Upgrade jhipster-registry to v6.5.0

- generators/client/templates/react/src/main/webapp/app/config/websocket-middleware.ts.ejs
- generators/client/templates/react/src/main/webapp/app/routes.tsx.ejs
- add location hook to Routes component to send router location on change
- export sendActivity to enabling sending path from location hook
- only subscribe to tracker endpoint when user is an admin
- disconnect and unsubscribe on logout
Fix #12729
> fix react websockets implementation

- generators/server/templates/build.gradle.ejs
Correct the version interpolation for checkstyle version in gradle (requires `"` instead `'`).
closes #13348
---
When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result …
> correct checkstyle version interpolation

- generators/client/templates/react/src/main/webapp/app/config/websocket-middleware.ts.ejs
Only call disconnect when `stompClient` is connected.  Also remove unused `onhashchange` method
Currently it is possible to call `stompClient.disconnect` (on logout) before `stompClient` is connected, which throws an error.  Checking the [Angular websocket implementation](https://github.com/jhipster/generator-jhipster/blob/main/generators/client/templates/angular/src/main/webapp/app/core/tracker/tracker.service.ts.ejs#L97-L99), we can see it checks for `stompClient.connected` before calling `stompClient.disconnect`.  With that fix, it works as expected.
related to #13334 and the comment: https://github.com/jhipster/generator-jhipster/pull/13334#issuecomment-748823466
---
-   [ ] [All continuous integration …
> only call disconnect when stompClient is connected

- generators/cleanup.js
Error was:
```
CloudDatabaseConfiguration.java:13: error: cannot find symbol
public class CloudDatabaseConfiguration extends AbstractCloudConfig {
^
symbol: class AbstractCloudConfig
```
Follow up to #13335 
--- …
> Fix error on application upgrade

- generators/entity-client/index.js
- generators/entity-client/templates/angular/src/test/javascript/e2e/entities/entity.spec.ts.ejs
- generators/entity-client/templates/common/src/test/javascript/cypress/integration/entity/entity.spec.ts.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-detail.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.model.ts.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/react_validators.ejs
- generators/entity-client/templates/react/src/test/javascript/e2e/entities/entity-update-page-object.ts.ejs
- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity-details.vue.ejs
- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity-update.component.ts.ejs
- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity-update.vue.ejs
- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity.model.ts.ejs
- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity.vue.ejs
- generators/entity-client/templates/vue/src/test/javascript/e2e/entities/entity-update-page-object.ts.ejs
- generators/entity-client/templates/vue/src/test/javascript/e2e/entities/entity.spec.ts.ejs
- generators/entity-client/templates/vue/src/test/javascript/spec/app/entities/entity-update.component.spec.ts.ejs
- generators/entity-client/templates/vue/src/test/javascript/spec/app/entities/entity.service.spec.ts.ejs
- generators/entity/index.js
This is api bugfix for blueprints.
`fields` should contain id fields now, but as workaround for react an vue not supporting id fields, I've filtered ids at `fields`.
Once the react and vue supports ids, `fields` should not be filtered anymore, becoming a breaking change for blueprints.
- Don't remove ids from fields anymore.
- Filter ids at templates.
--- …
> Drop fieldsNoId.

- generators/client/templates/angular/src/main/webapp/app/core/util/data-util.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/shared/date/format-medium-date.pipe.spec.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/shared/date/format-medium-date.pipe.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/shared/date/format-medium-datetime.pipe.spec.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/shared/date/format-medium-datetime.pipe.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/detail/entity-management-detail.component.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/service/entity.service.spec.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.ts.ejs
- generators/generator-base-private.js
This is follow up to #13358
In https://github.com/jhipster/generator-jhipster/pull/13358#issuecomment-749558087 I found that our entity model definitions are not correct, because non required fields can have value `null` (after reading from server) which is not allowed in model.
This PR fixes that, adds `| null` to non required fields type.
In the second commit using type safe equality operator in Angular entity update `.ts` file.
---
-   [ ] Documentation is added/updated where …
> Fix entity model types in front end

- generators/cleanup.js
Cleanup `CloudDatabaseConfiguration.java` was add after beta.0.
Fix to https://github.com/jhipster/generator-jhipster/pull/13357 related to https://github.com/jhipster/generator-jhipster/pull/13352
--- …
> Fix cleanup for 7.0.0-beta.0 -> 7.0.0-beta.1.

- generators/database-changelog-liquibase/index.js
- generators/database-changelog/index.js
- generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.html.ejs
- generators/entity-server/templates/src/main/java/package/common/patch_template.ejs
- generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
- generators/entity-server/templates/src/main/java/package/service/mapper/EntityMapper.java.ejs
- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
- test-integration/samples/jdl-entities/entities.jdl
- test/utils-field.spec.js
- utils/field.js
- Improve angular readonly fields support (mapstruct expression are readonly).
- Add support to dto only fields (transient fields doesn't generate an Entity field).
- Add support to `@MapstructExpression`.
Motivation:
`otherEntityField` (registry representation) fallback is the `id` field.
Composite id fallback is more than 1 field that would require changes to client handling.
`@MapstructExpression` allow us to map every id fields into 1 field to represent the registry.
---
-   [ ] …
> Add support to `@MapstructExpression`.

- generators/server/templates/src/main/java/package/security/jwt/TokenProvider.java.ejs
- generators/server/templates/src/test/java/package/security/jwt/TokenProviderTest.java.ejs
`StringUtils.isEmpty()` [has been deprecated](https://github.com/spring-projects/spring-framework/issues/25945), so this PR replaces it by `ObjectUtils.isEmpty()` in the constructor of `TokenProvider`.
Besides, as `isEmpty()` is used in a conditional block that is not being tested, I added two unit tests to `TokenProviderTest`.
> Replace deprecated `StringUtils.isEmpty()` by `ObjectUtils.isEmpty()` and cover its usage with tests

- generators/client/templates/react/src/test/javascript/e2e/modules/account/account.spec.ts.ejs
The e2e test changes the admin password to `new-password`, then attempts to change the password back to `admin`.  Before the request is completed, the test would finish and the window reloads in preparation for the next test.
This fix waits for the password to be changed, then moves on to the next test.
related to https://github.com/jhipster/generator-jhipster/issues/13361#issuecomment-752270050
---
-   [x] Coding Rules & …
> fix race condition during react protractor e2e tests

- generators/server/templates/src/main/java/package/config/SecurityConfiguration_reactive.java.ejs
- prevent 401 errors on swagger-ui static resources
- open `swagger-resources` endpoint, it is not secured for non-reactive apps
Originally reported by @sanjitvimal https://github.com/jhipster/generator-jhipster/issues/10330#issuecomment-753611017
Swagger UI is broken for a monolith reactive application (did not test microservices).
The browser console logs 401 errors for static resources ([screenshot](https://user-images.githubusercontent.com/4294623/103564280-3d8d7200-4e8c-11eb-8abd-1912e9268731.png)).
https://github.com/jhipster/generator-jhipster/blob/f601be10d4305d9a81a022043d0b73fbdb62d5ca/generators/server/templates/src/main/java/package/config/SecurityConfiguration_reactive.java.ejs#L200
Changing `"/swagger-ui/index.html"` to `"/swagger-ui/**"` fixes the 401 errors for static …
> fix Swagger UI for reactive applications

- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity-update.component.ts.ejs
- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity.component.ts.ejs
- utils/entity.js
In microservices applications, vue uses keys with prefix as
'microserviceAppName.translationKey' rather than
'frontendAppName.translationKey'. This commit fixes the key using a new
variable i18nAssetHeaderPrefix for entities.
Fix #13384
--- …
> Fix Vue entities translation keys create, update, delete

- generators/client/templates/angular/tsconfig.app.json.ejs
- generators/common/templates/README.md.ejs
- generators/server/index.js
- generators/server/templates/gradle/profile_dev.gradle.ejs
Follow up to Angular CLI migration, minor fixes.
In `tsconfig` and `Gradle` (applies also to React and Vue) part replacing double slash `//` with one slash `/` (variables already are ending with `/`)
In readme replacing "**withWebpack**" with "**with Webpack**" and fixing links to Webpack and Angular CLI sites
In Gradle part: in Angular after moving to Angular CLI there is no more file` webpack.prod.js` and build depends also on file `angular.json` now
--- …
> Fix double slash, missing space, links and Angular Gradle input

- generators/cypress/templates/src/test/javascript/cypress/integration/account/login-page.spec.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/integration/account/password-page.spec.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/integration/account/register-page.spec.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/integration/account/reset-password-page.spec.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/integration/account/settings-page.spec.ts.ejs
- generators/entity-client/templates/common/src/test/javascript/cypress/integration/entity/entity.spec.ts.ejs
> Cypress: Replace all cy.server() and cy.route() by cy.intercept()

- .github/workflows/incremental-changelog.yml
- generators/client/templates/angular/tsconfig.json.ejs
- generators/cypress/templates/cypress.json.ejs
Don't generate Cypress exclude in Angular `tsconfig.json` if Cypress tests are not selected.
Use `BUILD_DIR` constant instead of Maven specific `target` for Cypress screenshots folder.
`incremental-changelog.yml` GitHub Actions workflow was only one containing `app/target/cypress/screenshots` as screenshots path, all other GitHub Actions workflows already use `app/*/cypress/screenshots`.
---
-   [ ] Coding Rules & Commit …
> Polish Cypress related logic

- generators/client/index.js
- generators/client/templates/angular/src/main/webapp/app/layouts/main/main.component.spec.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/layouts/main/main.component.ts.ejs
- generators/client/templates/angular/webpack/webpack.custom.js.ejs
- generators/client/templates/react/webpack/webpack.dev.js.ejs
Use humanized app name in Webpack notifier in Angular and React and in no i18n page title in Angular.
Remove double https in Angular Webpack configuration.
--- …
> Use humanized app name and remove double https

- generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.spec.ts.ejs
> [angular] Remove redundant ActivatedRoute provider from infinite scroll test

- generators/client/templates/react/tsconfig.test.json.ejs
Without this change a lot of warnings on running `npm test` first time after generation (or after deleting `build`/`target` folder).
Noticed while reviewed #13425 
---
When you are still working on the PR, consider converting it to Draft (bellow reviewers) and …
> [react] Fix tests ts-jest warnings

- generators/client/templates/angular/src/main/webapp/app/core/util/alert.service.spec.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/util/alert.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/shared/alert/alert-error.component.spec.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/shared/alert/alert-error.component.ts.ejs
Instead of showing the 'message' field, the alert component will use 'detail' field if present
Fix #13316
--- …
> Add detail field in angular alert component

- generators/kubernetes/templates/db/elasticsearch.yml.ejs
> Allow ElasticSearch to start in Kubernetes using single-node discovery mode

- generators/server/files.js
- generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs
- generators/server/templates/src/main/java/package/security/oauth2/CustomClaimConverter.java.ejs
- generators/server/templates/src/test/java/package/security/oauth2/CustomClaimConverterIT.java.ejs
Add a custom claim converter to fetch the oauth2 `userinfo` endpoint and add custom claims. This only apply to a microservice using oauth2.
Fix #10975 @mraible (can this PR be merged after September for hacktoberfest 👀)
---
> Add custom claim converter in a microservice with oauth2

- generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
- generators/server/files.js
- generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs
Should fix #13467, eventually.
---
Status: Jan 12 21:56 MST, I get the following error when I try to view or edit a blog entity.
```
2021-01-12 21:50:30.846 ERROR 86651 --- [ctor-http-nio-3] o.z.problem.spring.common.AdviceTraits   : Internal Server Error …
```
> Fix R2DBC with OAuth

- generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs
- generators/server/templates/src/main/java/package/config/UaaConfiguration.java.ejs
Ensure /websocket/tracker/ cant bypass
AuthoritiesConstants.ADMIN restriction
Fix #13439
---
> Ensure /websocket/tracker/ cant bypass

- generators/server/templates/src/main/resources/config/application.yml.ejs
Enable more actuator endpoint by default which can be used with JHipster Control Center.
---
> Enable more actuator endpoint by default

- generators/client/templates/vue/package.json
Reverts jhipster/generator-jhipster#13504 because CSS doesn't render in Vue after upgrade.
> Revert "chore(deps-dev): bump css-loader from 3.5.3 to 5.0.1 in /generators/client/templates/vue"

- generators/client/templates/angular/src/test/javascript/e2e/account/account.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/e2e/admin/administration.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/e2e/page-objects/jhi-page-objects.ts.ejs
- generators/client/templates/react/package.json.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/administration.reducer.spec.ts.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management.reducer.spec.ts.ejs
- generators/client/templates/react/src/test/javascript/e2e/modules/account/account.spec.ts.ejs
- generators/client/templates/react/src/test/javascript/e2e/modules/administration/administration.spec.ts.ejs
- generators/client/templates/react/src/test/javascript/e2e/page-objects/navbar-page.ts.ejs
- generators/client/templates/react/src/test/javascript/e2e/page-objects/signin-page.ts.ejs
- generators/client/templates/react/src/test/javascript/protractor.conf.js.ejs
- generators/client/templates/vue/src/test/javascript/e2e/modules/account/account.spec.ts.ejs
- generators/client/templates/vue/src/test/javascript/e2e/modules/administration/administration.spec.ts.ejs
- generators/client/templates/vue/src/test/javascript/e2e/page-objects/signin-page.ts.ejs
- generators/client/templates/vue/src/test/javascript/protractor.conf.js.ejs
- generators/entity-client/templates/angular/src/test/javascript/e2e/entities/entity.spec.ts.ejs
- generators/entity-client/templates/react/src/test/javascript/e2e/entities/entity.spec.ts.ejs
- generators/entity-client/templates/vue/src/test/javascript/e2e/entities/entity.spec.ts.ejs
- generators/server/templates/src/main/docker/app.yml.ejs
It should be possible to set username and password environment variables, then run Protractor tests against Okta.
```
export E2E_USERNAME="foo"
export E2E_PASSWORD="bar"
npm run e2e
```
This PR makes it so Angular, React, and Vue tests all pass against Okta.
---
> Fix Protractor tests so they work with Okta {angular, react, vue}

- generators/entity-server/templates/src/main/java/package/repository/EntityRepositoryInternalImpl_reactive.java.ejs
- generators/server/templates/src/main/java/package/service/EntityManager.java.ejs
Reactive did not set 'where' clause in JDBC query when findById was executed, thus throwing an error when when jhipster displayed detail or update page
--- …
> add where clause from data jpa criteria when reactive

- generators/client/templates/react/package.json
Upgrade Axios to fix a security vulnerability. 
Even after this update, there's still a lot of React dependencies that are out-of-date. If you run [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) in `generators/client/templates/react`, you'll see the list of outdated dependencies.
```
@fortawesome/fontawesome-svg-core     1.2.30  →    1.2.34
@fortawesome/free-solid-svg-icons     5.14.0  →    5.15.2
@fortawesome/react-fontawesome        0.1.12  →    0.1.14
bootstrap                              4.4.1  →     4.5.3
bootswatch                             4.3.1  →     4.5.3
lodash                               4.17.15  →   4.17.20
react-redux                            7.2.0  →     7.2.2
react-redux-loading-bar                4.6.0  →     5.0.0
react-router-dom …
```
> Upgrade Axios to fix security vulnerability

- generators/generator-base-docker.js
- generators/kubernetes/templates/db/neo4j.yml.ejs
- generators/kubernetes/templates/deployment.yml.ejs
- generators/server/templates/gradle.properties.ejs
This adds a simple stateful set for neo4j community database. There are some gotchas to note:
* the docker image only supports setting the initial password, not a database password, therefore we use auth `none`
* the neo4j helm chart does not support the community edition, so we don't have neo4j for the helm part
* tested with minikube (monolith and example from issue) both worked well (after giving the vm some more power)
closes #13477
---
-   [ ] Documentation is added/updated …
> support neo4j with k8s subgenerator

- generators/client/templates/vue/package.json
Reverts jhipster/generator-jhipster#13556
> Revert "chore(deps-dev): bump css-loader from 3.5.3 to 4.3.0 in /generators/client/templates/vue"

- generators/database-changelog-liquibase/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs
When using incremental changelog option, the generated file for CSV doesn't match with the one used in XML.
Here an extract of `src/main/resources/config/liquibase/changelog/20210122125559_added_entity_Beer.xml` :
```xml
<changeSet id="20210122125559-1-data" author="jhipster" context="faker">
<loadData
file="config/liquibase/fake-data/20210122125559_entity_Beer.csv"
separator=";"
tableName="beer">
<column name="id" type="numeric"/>
<column name="name" type="string"/>
</loadData>
</changeSet>
```
Here the generated CSV file: `src/main/resources/config/liquibase/fake-data/20210122125559_entity_beer.csv`
--- …
> Fix name for generated csv file with incremental changelog option

- cli/commands.js
> update commands usage

- generators/server/templates/src/test/java/package/security/jwt/TokenProviderTest.java.ejs
Sonar description below.
Consecutive AssertJ "assertThat" statements should be chained.
AssertJ assertions methods targeting the same object can be chained instead of using multiple assertThat. It avoids duplication and increases the clarity of the code.
---
> Fix Sonar code smell about assertThat

- package-lock.json
Deleted `package-lock.json` and `node_modules` and then ran `npm install` - this updated transitive dependencies and fixed vulnerabilities reported by `npm audit`.
Got idea from commit in Spring Boot 2.4 branch https://github.com/jhipster/generator-jhipster/commit/259e9d7b2ebddabc27749e68e0b9c70524771f1c - so if this is preferred then this PR can be closed.
---
> Update transitive dependencies to fix vulnerabilities

- .github/workflows/angular.yml
- .github/workflows/generator.yml
- .github/workflows/incremental-changelog.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
- generators/generator-constants.js
Fixes https://github.com/jhipster/generator-jhipster/issues/12747.
---
> Switch to npm 7.

- generators/base/index.js
- test/base/base.spec.js
Make generator-base available at yeoman-environment at `jhipster:base` namespace.
---
> Register generator-base at Environment

- generators/heroku/index.js
- test/heroku.spec.js
If the `herokuAppName` is set, we check for the existence of the app.  This only works if it has previously been deployed from the same device and directory (it checks for the Heroku git remote).  If a developer clones the project from a repository then tries to run `jhipster heroku`, it will not find the existing app and reset the `herokuAppName` in the `yo-rc.json`
By passing the `herokuAppName` as a param to `heroku apps:info`, we can find out if the app exists. We also find out if the user has access to the application, otherwise an error is returned.
--- …
> improve check for existing heroku app

- .editorconfig
- generators/docker-compose/index.js
- generators/heroku/templates/heroku.gradle.ejs
Follow up to #13713 - fixes bug introduced in `docker-compose` sub generator.
`npm test` logged error in log but continued without failing the job.
Couple other polishing while tracking why `npm test` constantly timeouts.
---
> Fix docker-compose sub generator

- jdl/converters/json-to-jdl-converter.js
- jdl/exporters/applications/jhipster-application-formatter.js
- jdl/parsing/validator.js
- test/jdl/converters/json-to-jdl-converter.spec.js
- test/jdl/test-files/json_to_jdl_converter/only_app/.yo-rc.json
Exporting Application JDL containing `otherModules` (for example when a blueprint is used) results in a JDL with `otherModules [[object Object]]` which fails when attempting to import.
This PR aligns the logic related to the `otherModules` property with the `blueprints` property, which has the same format. With this change, apps generated with blueprints can export valid JDL.
I am not an expert with JDL parsing so any review is appreciated.
**To reproduce (also happens with beta v7):**
```
mkdir reproduction && cd reproduction
npm i generator-jhipster@6.10.5 generator-jhipster-quarkus@1.0.0
jhipster jdl --inline "application{ config{ blueprints [generator-jhipster-quarkus]} }" --skip-install
jhipster export-jdl
cat jhipster.jdl | grep object
```
---
Please make sure the below checklist is …
> fix export/import of otherModules property

- generators/client/templates/angular/src/test/javascript/e2e/admin/administration.spec.ts.ejs
> Try waiting 5 seconds instead of 2 in Protractor e2e

- generators/client/templates/angular/src/test/javascript/e2e/admin/administration.spec.ts.ejs
- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
Another attempt to fix Protractor since [tests are still failing](https://github.com/hipster-labs/jhipster-daily-builds/runs/1771529176?check_suite_focus=true).
> [Protractor] Sleep and wait for all admin pages to load

- generators/client/templates/react/src/test/javascript/e2e/modules/administration/administration.spec.ts.ejs
- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
Try to fix [failing React e2e test](https://github.com/hipster-labs/jhipster-daily-builds/runs/1771876336?check_suite_focus=true).
> [Protractor] Sleep for metrics page with React too

- generators/client/templates/react/src/test/javascript/e2e/modules/administration/administration.spec.ts.ejs
Still trying to fix the failing [React + OAuth 2.0](https://github.com/hipster-labs/jhipster-daily-builds/actions/runs/513038454) daily build. 
NOTE: We might be able to reduce the e2e times on these jobs by specifying a lighter set of entities, or none at all. Currently, there's a lot.
> [Protractor] Remove sleep because React doesn't need it

- .github/workflows/webflux.yml
- generators/entity-server/templates/src/main/java/package/repository/EntityRepositoryInternalImpl_reactive.java.ejs
- generators/server/templates/src/main/java/package/config/DatabaseConfiguration_sql.java.ejs
- generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs
- generators/server/templates/src/main/java/package/service/ColumnConverter.java.ejs
- generators/server/templates/src/main/java/package/service/EntityManager.java.ejs
> Upgrade R2DBC implementation classes for spring boot 2.4

- generators/server/templates/src/main/java/package/security/jwt/TokenProvider.java.ejs
Since Java 8 support is not dropped in JHipster for now as discussed in https://github.com/jhipster/generator-jhipster/pull/12021#issuecomment-652968697 , the usage of Java 9+ APIs should be prevented.
> Align with Java 8 API.

- generators/server/templates/src/test/java/package/security/SecurityUtilsUnitTest.java.ejs
Since this test is setting a security context, it should clear it afterwards.
I'm also cleaning it upfront with `@BeforeEach` just to make sure it's also clean when starting the test. It's not necessary if all tests are cautious.
A similar code should be added to the reactive part I guess. But I wanted to make sure you agree with the PR first.
Another thing: When the security context is retrieve, it is created directly. So the following code
```java
SecurityContext securityContext = SecurityContextHolder.createEmptyContext();
securityContext.setAuthentication(new UsernamePasswordAuthenticationToken("admin", "admin"));
SecurityContextHolder.setContext(securityContext);
```
can be simplified to
```java
SecurityContextHolder.getContext().setAuthentication(new …
```
> Clear security context after tests

- generators/entity-server/templates/src/main/java/package/service/EntityQueryService.java.ejs
- generators/entity-server/templates/src/main/java/package/service/dto/EntityCriteria.java.ejs
- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
- generators/entity/index.js
- test-integration/samples/jdl-entities/custom-id.jdl
- utils/entity.js
Fix #13695 : Handle custom primary key names in the filtering impleme…
---
> Handle custom primary key names in entity filtering

- generators/entity/index.js
- utils/entity.js
- utils/field.js
There are some attributes that `prepareFieldForTemplates` can update.
So we should process the fields after  `prepareFieldForTemplates` been executed.
---
> Move fields processing to after entity fields preparing.

- generators/client/templates/angular/package.json.ejs
Fix warning since Angular CLI version 11.1 while running `npm test`
```
Support for camel case arguments has been deprecated and will be removed in a future major version.
Use '--log-heap-usage' instead of '--logHeapUsage'.
```
---
> [angular] Fix Angular CLI 11.1 camel case arguments deprecation warning

- generators/client/templates/angular/src/test/javascript/e2e/admin/administration.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/e2e/page-objects/jhi-page-objects.ts.ejs
- generators/client/templates/react/src/test/javascript/e2e/modules/administration/administration.spec.ts.ejs
- generators/client/templates/react/src/test/javascript/e2e/page-objects/signin-page.ts.ejs
- generators/client/templates/vue/src/test/javascript/e2e/page-objects/signin-page.ts.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/13723
Finally, I managed to find the root cause of flaky tests. It's not related at all to metrics page.
It's the line `await browser.wait(ec.presenceOf(this.username), 5000);`
I replaced with `await browser.sleep(1000);`
So it shoud do the job. Don't hesitate to comment this @mraible plz, if you think it's wrong
I launch 5 consecutives builds with this fix, and it seems to work fine:
---
> Protractor fix flaky tests

- generators/client/templates/react/package.json.ejs
- generators/client/templates/vue/package.json.ejs
This fixes a vulnerability in the 5.4.4 version.
Before:
```
┌─────────────────────┬──────────────────────────────────────────────────┐
│ low                 │ Prototype Pollution                              │
├─────────────────────┼──────────────────────────────────────────────────┤
│ Package             │ yargs-parser                                     │
├─────────────────────┼──────────────────────────────────────────────────┤
│ Vulnerable versions │ <13.1.2 || >=14.0.0 <15.0.1 || >=16.0.0 <18.1.2  │
├─────────────────────┼──────────────────────────────────────────────────┤
│ Patched versions    │ >=13.1.2 <14.0.0 || >=15.0.1 <16.0.0 || >=18.1.2 │
├─────────────────────┼──────────────────────────────────────────────────┤
│ More info           │ https://npmjs.com/advisories/1500 …
```
> Upgrade Protractor to v7 for React and Vue

- generators/heroku/index.js
This PR generates a random password for the initial okta login when using heroku. The password is printed to the console afterwards (or can be checked in configuration as before). 
closes #13768
---
> generate random password for initial okta login with heroku

- generators/entity-client/templates/common/src/test/javascript/cypress/integration/entity/entity.spec.ts.ejs
The `startingEntitiesCount` is set in the [`before`](https://github.com/jhipster/generator-jhipster/blob/bb97052279a9870ef0871a4c1e444e366f4c7b7d/generators/entity-client/templates/common/src/test/javascript/cypress/integration/entity/entity.spec.ts.ejs#L61-L72) method at the beginning of the entity E2E test.  If the "create entity" test fails after creating an entity, it will retry that specific test.  But the `before` method does not run again ([docs](https://docs.cypress.io/guides/guides/test-retries.html#How-It-Works)), leading to a stale `startingEntitiesCount` value.
You can see an example of the issue [in the CI logs here](https://github.com/jhipster/generator-jhipster/runs/1823783192?check_suite_focus=true#step:30:559).  You can validate the issue is happening by checking the …
> update startingEntitiesCount at beginning of create e2e test

- generators/entity-server/templates/src/main/java/package/common/patch_template.ejs
Using this JDL:
```
application {
config {
baseName burger
}
entities *
}
entity Beer {
aBeer String
bBeer String
}
dto * with mapstruct
service * with serviceClass
```
Then, you'll have this compilation failure:
```
INFO] ------------------------------------------------------------------------
[INFO] Total time:  52.326 s
[INFO] Finished at: 2021-02-04T15:29:20+01:00
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project burger: Compilation failure: Compilation failure: 
[ERROR] /home/pgrimaud/tmp/17-burger/src/main/java/com/mycompany/myapp/servi …
```
> Fix getter and setter for entity patch

- generators/server/templates/src/main/java/package/config/DatabaseConfiguration_neo4j.java.ejs
This adds reactive and non reactive neo4j transaction managers (as they are not auto-configured anymore after the move from snd-rx to spring umbrella)
closes #13810
---
> add neo4j transaction managers

- generators/server/templates/src/main/docker/app.yml.ejs
It's to avoid having additional line:
```yaml
- MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
- SPRING_CLOUD_CONSUL_HOST=consul
- SPRING_CLOUD_CONSUL_PORT=8500
- SPRING_DATASOURCE_URL=jdbc:postgresql://iloveburger...
- SPRING_LIQUIBASE_URL=jdbc:postgresql://ilovechips...
- JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
```
---
> Format in app.yml

- generators/ci-cd/templates/azure-pipelines.yml.ejs
Our Azure Pipeline failed on E2E tests. These changes fixed it.
We had to enable the headless mode via env variable and install the latest Chrome, because the Azure Ubuntu VM does not include it.
Furthermore we had to change the `protractor.conf.js` file and add the `--no-sandbox` parameter to the Chrome args. I did not know whether I should include this change to the PR, so I left it out for now. But I update the PR and add this if you wish (probably all 3 template files should be changed - for Angular, React and Vue).
---
> Fix Azure CI pipeline template for E2E tests

- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-detail.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs
(which happens with the  gradle-mongodb-react configuration )
https://github.com/hipster-labs/jhipster-daily-builds/runs/1843126537?check_suite_focus=true
The bug was introduced by #13824
---
> Fix when embedded documents are used, which doesn't have primary key.

- generators/common/index.js
- generators/common/templates/sonar-project.properties.ejs
Follow up to #13425
Without this change SonarQube task fails with error "Error during parsing of generic test execution report" because report contains tests from paths which are not declared as test paths in `sonar-project.properties`.
---
> [react] Fix Sonar properties

- generators/client/files-angular.js
- generators/client/templates/angular/src/main/webapp/app/account/activate/activate.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/account/password-reset/finish/password-reset-finish.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/account/password/password.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/account/register/register.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/account/sessions/sessions.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/configuration/configuration.service.spec.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/configuration/configuration.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/gateway/gateway-routes.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/health/health.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/logs/logs.service.spec.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/logs/logs.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics.service.spec.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/service/user-management.service.spec.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/service/user-management.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/app.module.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/auth/account.service.spec.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/auth/account.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/auth/auth-jwt.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/auth/auth-session.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/config/config.service.spec.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/config/config.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/interceptor/auth.interceptor.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/entities/user/user.service.spec.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/entities/user/user.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/layouts/profiles/profile.service.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/service/entity.service.ts.ejs
- test/utils/expected-files.js
Currently, when generating a gateway, microservice endpoint is hardcoded: `SERVER_API_URL + 'services/microservice/api'`.
This PR implements a configuration service:
- makes easier to customize routed endpoints.
- microfront:
- removes reference to app/app.constants. So we don't have to export it for the microfrontends.
- when changing the routed endpoint in the gateway, don't require it to change in the microfrontend.
---
> [angular] Implement ConfigService.

- generators/server/templates/src/main/resources/config/application-dev.yml.ejs
I tried `npm start` with this setting and it doesn't seem to be a problem. That's why I removed the BrowserSync comment.
---
> Allow http://localhost:8100 for CORS by default

- generators/client/templates/angular/src/main/webapp/app/layouts/navbar/navbar.component.html.ejs
- generators/client/templates/react/src/main/webapp/app/shared/layout/menus/admin.tsx.ejs
- generators/client/templates/vue/src/main/webapp/app/core/jhi-navbar/jhi-navbar.vue.ejs
- generators/server/templates/src/main/java/package/config/WebConfigurer.java.ejs
- generators/server/templates/src/main/resources/h2.server.properties.ejs
This PR requires https://github.com/jhipster/jhipster-bom/pull/165. It starts the h2 web server console. I have changed the console port from 8082 to 8092 to minimize the possibility for overlapping ports in a micro-service environment.
closes #13699 
---
> start h2 console in reactive environments

- generators/kubernetes-helm/templates/README-KUBERNETES-HELM.md.ejs
- generators/kubernetes-helm/templates/app/requirements.yml.ejs
- generators/kubernetes-helm/templates/csvc/requirements.yml.ejs
As, Helm chart repositories are moved from
"https://kubernetes-charts-incubator.storage.googleapis.com" and "https://kubernetes-charts.storage.googleapis.com" to
"https://charts.helm.sh/incubator" and "https://charts.helm.sh/stable" respectively so updating.
Also , this suggestion is given by "Helm Cli" upon running
"helm dependency build " on generated helm charts by "kubernetes-helm" sub-generator of "jhipster-generator".
`
Error: repo "https://kubernetes-charts.storage.googleapis.com" is no longer available; try "https://charts.helm.sh/stable" instead
Error: repo "https://kubernetes-charts-incubator.storage.googleapis.com" is no longer available; try "https://charts.helm.sh/incubator" instead
`
Signed-off-by: Pratik raj <rajpratik71@gmail.com>
> fix :  Updating Helm Chart repository for stable and incubator

- generators/ci-cd/prompts.js
- generators/ci-cd/templates/azure-pipelines.yml.ejs
- generators/ci-cd/templates/circle.yml.ejs
- generators/ci-cd/templates/github-actions.yml.ejs
- generators/ci-cd/templates/travis.yml.ejs
- generators/client/templates/angular/package.json.ejs
- generators/client/templates/react/package.json.ejs
- generators/client/templates/vue/package.json.ejs
- test/ci-cd.spec.js
- test/templates/ci-cd/gradle-ngx-npm/.yo-rc.json
- test/templates/ci-cd/maven-ngx-npm/.yo-rc.json
close https://github.com/jhipster/generator-jhipster/issues/13716
> Add cypress dashboard in CI/CD sub generator

- generators/client/templates/react/src/main/webapp/app/shared/layout/menus/admin.tsx.ejs
Following #13868 and https://github.com/jhipster/generator-jhipster/pull/13943
cc @atomfrede : there is no npm test about these configurations. That's why we didn't detect it. We should definitively add these config in npm test :-)
---
> Fix template for Reactive with H2

- generators/ci-cd/templates/.gitlab-ci.yml.ejs
Small fix for gitlab-ci, which has a redondant compilation which increases time of pipeline.
--
See #13854 
---
> Remove compile in gitlab-ci Docker flow

- generators/generator-constants.js
- generators/server/templates/gradle.properties.ejs
Update gradle node plugin from latest RC to latest release version 3.0.1
---
> update gradle node plugin to 3.0.1

- generators/kubernetes/templates/deployment.yml.ejs
- generators/server/templates/src/main/docker/app.yml.ejs
- generators/server/templates/src/main/resources/config/application-dev.yml.ejs
- generators/server/templates/src/main/resources/config/application-prod.yml.ejs
- generators/server/templates/src/test/java/package/AbstractNeo4jIT.java.ejs
We still use the old properties for spring data neo4j. This updates to the [new properties](https://docs.spring.io/spring-data/neo4j/docs/6.0.3/reference/html/#configure-spring-boot-project) and should fix #13890 .
closes #13890
---
> correct neo4j uri

- generators/server/templates/src/main/resources/config/application-dev.yml.ejs
- generators/server/templates/src/main/resources/config/application.yml.ejs
Now running `./gradlew` or `./mvnw` activates profiles `dev, api-docs` again. Running `./gradlew -Pprod` or `./mvnw -Pprod` activates `prod` profile only.
closes #13857 
---
> activate api-docs profile in dev mode by default

- generators/common/templates/gitignore.ejs
Change `.gitignore` file to allow certain VS Code workspace files.
See #13715 
---
> Change .gitignore for VS Code

- generators/client/templates/vue/package.json
- generators/client/templates/vue/webpack/webpack.common.js.ejs
- generators/client/templates/vue/webpack/webpack.dev.js.ejs
~Possibly related to https://github.com/jhipster/generator-jhipster/issues/13862~.
---
> vue: Fix conflicting HtmlWebpackPlugin between webpack.common and webpack.prod.

- generators/kubernetes/templates/monitoring/jhipster-prometheus-cr.yml.ejs
The is a typo in this templete, replica should be replicas, error log for kubectl apply -f jhipster-prometheus-cr.yml:
error: error validating "jhipster-prometheus-cr.yml": error validating data: ValidationError(Prometheus.spec): unknown field "replica" in com.coreos.monitoring.v1.Prometheus.spec; if you choose to ignore these errors, turn validation off with --validate=false
The valid field name is "replicas" as per the documentation: https://docs.openshift.com/container-platform/4.4/rest_api/monitoring_apis/prometheus-monitoring-coreos-com-v1.html 
After changing that line the deployment succeeds.
---
When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you …
> Unknown field "replica" - typo

- generators/client/templates/vue/package.json
- generators/client/templates/vue/src/test/javascript/spec/app/admin/metrics/metrics-modal.component.spec.ts.ejs
Fix upgrade dependabot https://github.com/jhipster/generator-jhipster/pull/13844
Solution: https://vue-test-utils.vuejs.org/api/wrapper-array/setprops.html
---
> Fix upgrade @vue/test-utils from 1.1.2 to 1.1.3

- generators/client/templates/vue/src/main/webapp/app/admin/user-management/user-management-view.vue.ejs
- generators/client/templates/vue/src/main/webapp/app/admin/user-management/user-management.vue.ejs
- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity-details.vue.ejs
- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity.vue.ejs
Refactor router-link tag to v-slot for future support https://next.router.vuejs.org/guide/migration/#removal-of-event-and-tag-props-in-router-link
Fix #13974
---
> [Vue] Refactor router-link to remove tag for v-slot

- generators/server/templates/src/test/resources/logback.xml.ejs
All the JSON checks in the integration tests are creating a lot's of annoying log messages
---
> [backend] No need to spam the tests with JSON path debug messages

- generators/entity-server/templates/src/main/resources/config/cql/changelog/added_entity.cql.ejs
- generators/entity/prompts.js
- jdl/jhipster/field-types.js
- test-integration/samples/.jhipster/CassTestEntity.json
- test-integration/samples/.jhipster/CassTestMapstructEntity.json
- test-integration/samples/.jhipster/CassTestServiceClassEntity.json
- test-integration/samples/.jhipster/CassTestServiceImplEntity.json
- test/jdl/jhipster/field-types.spec.js
- Update JDL to enable enumerations with Cassandra. This is already supported by generator-jhipster since #10414
-  Unify Cassandra date-time JDL types with common-databases JDL types:
- remove Date type, redundant with Instant type
- add LocalDate type
- add Duration type
Fixes #14026
---
> Unify Cassandra date-time JDL types with common-databases JDL types

- generators/database-changelog-liquibase/index.js
- generators/database-changelog/index.js
- generators/entities/index.js
- generators/entity/index.js
- test/app/incremental-changelog.spec.js
- test/entities/composing.js
- test/entities/only-entities.spec.js
- test/entity/single-entity.spec.js
- test/templates/.jhipster/Simple2.json
- test/templates/.jhipster/Simple3.json
Fixes https://github.com/jhipster/generator-jhipster/issues/13833
---
> Improve support for single entities

- generators/entity-server/files.js
- generators/entity-server/templates/src/main/java/package/service/EntityQueryService.java.ejs
- generators/entity-server/templates/src/main/java/package/service/criteria/EntityCriteria.java.ejs
- generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs
- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
This is two smallish change, to enhance the experience using the entity criterias.
* Move the criteria objects into a separate package - which is not a big thing, but previously the DTOs and the criteria objects were in the same package, which seemed a bit messy.
* Adding fluent methods for the individual filters. Previously - due to limitations in generics usage, you had to write something like this:
`        
criteria.setProjectId((UUIDFilter) new UUIDFilter().setEquals(uuid));
` 
Which is a bit verbose, after this change, you can write:
`        
criteria.projectId().setEquals(uuid);
`
--- …
> Polishing the Entity Criteria

- generators/cleanup.js
- generators/client/files-angular.js
- generators/client/templates/angular/.npmrc.ejs
- test/utils/expected-files.js
`legacy-peer-deps` option should not be required for angular anymore.
---
> Drop .npmrc from angular.

- cli/commands.js
- cli/environment-builder.js
- cli/jhipster-command.js
- cli/program.js
- test/cli/cli.spec.js
- test/templates/blueprint-cli/generators/foo/index.js
Run a module using `jhipster run your-favorite-module`.
Closes https://github.com/jhipster/generator-jhipster/issues/13068.
---
> Add support to run modules using jhipster command

- generators/server/templates/src/main/java/package/security/SecurityUtils.java.ejs
- generators/server/templates/src/test/java/package/security/SecurityUtilsUnitTest.java.ejs
> Renames isCurrentUserInRole method

- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs
> Fix: OneToMany id bug in react entity validation form

- generators/client/templates/vue/package.json
- generators/generator-base-private.js
Fix https://github.com/jhipster/generator-jhipster/pull/14174
---
> Fix: bump typescript from 4.1.5 to 4.2.3 in /generators/client/templates/vue

- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
EntityQueryService is not used in EntityResourceIT
---
> [backend] Remove the unused EntityQueryService from the ResourceIT

- generators/generator-base-private.js
fixes #14189 by adding a condition that checks if secondLetter isn't empty
---
> verify if secondLetter isn't empty [skip-ci]

- generators/generator-base.js
- package-lock.json
> use some constants in generator-base

- .github/workflows/angular.yml
- .github/workflows/generator.yml
- .github/workflows/incremental-changelog.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
- generators/generator-constants.js
- test-integration/scripts/10-install-jhipster.sh
- test/generator-constants.spec.js
PR https://github.com/jhipster/generator-jhipster/pull/14187 recreated package-lock.json with npm 7.
npm 6 `npm ci` prints a warning about lockversion 2, let's switch others CIs to npm 7.
Remaining tasks for https://github.com/jhipster/generator-jhipster/issues/12747
- Install npm using constants version.
- GitHub action
- build scripts used by (jhipster-bom)
- Missing to update daily builds. After approval.
---
> Bump npm version to 7.6.1 and use npm version from constants.

- generators/server/templates/src/main/java/package/web/filter/ModifyServersOpenApiFilter.java.ejs
- generators/server/templates/src/test/java/package/web/filter/ModifyServersOpenApiFilterTest.java.ejs
Handle swagger with compression for reactive gateway when using prod profile and compression is true here
```
server:
port: 8081
shutdown: graceful # see https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-graceful-shutdown
compression:
enabled: true
```
Fix #14198 
---
> Handle swagger with compression for reactive gateway

- test-integration/generate-sample.sh
- test-integration/scripts/00-init-env.sh
- test-integration/scripts/01-display-configuration.sh
- test-integration/scripts/02-display-tools.sh
- test-integration/scripts/03-system.sh
- test-integration/scripts/04-git-config.sh
- test-integration/scripts/10-install-jhipster.sh
- test-integration/scripts/11-generate-config.sh
- test-integration/scripts/11-generate-entities.sh
- test-integration/scripts/12-generate-project.sh
- test-integration/scripts/13-replace-version-generated-project.sh
- test-integration/scripts/14-jhipster-info.sh
- test-integration/scripts/20-docker-compose.sh
- test-integration/scripts/20-no-memory-limit-elasticsearch.sh
- test-integration/scripts/21-tests-backend.sh
- test-integration/scripts/22-tests-frontend.sh
- test-integration/scripts/23-package.sh
- test-integration/scripts/24-tests-e2e.sh
- test-integration/scripts/25-sonar-analyze.sh
Some Linux distributions don't have bash available at /bin/bash, e.g. Nixos that I'm using.
Using /usr/bin/env is more portable
---
> Better portability for shebang of integrations tests scripts

- generators/entity-server/templates/partials/it_patch_update.partial.java.ejs
- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
Using the same string in ~30 places is not the nicest thing, and especially when you need to move your REST endpoint to somewhere else.
---
> Introduce constants for the API endpoints in the EntityResourceIT

- generators/server/templates/src/main/resources/config/application.yml.ejs
- generators/server/templates/src/main/resources/config/bootstrap.yml.ejs
This is an alternative to #12923 that wanted to support monolith's frontend with a custom context-path as a minimal support for JHipster 7. So This will only work for the back-end part.
With @pascalgrimaud we realized that there are many places where we should set the context-path for the UI including `cypress.json`, webpack, and this cannot be set dynamically so it would need to be a generator option.
---
> Correctly set the spring context-path for api-docs

- generators/generator-constants.js
- generators/server/templates/build.gradle.ejs
As the used properties have been removed earlier (did not work with the new plugin) we should reference them anymore. Seems I forgot that.
[ci-skip]
---
> fix gradle node/npm version parameters

- generators/client/templates/angular/src/test/javascript/e2e/account/account.spec.ts.ejs
- generators/client/templates/react/src/test/javascript/e2e/modules/account/account.spec.ts.ejs
- generators/client/templates/vue/src/test/javascript/e2e/modules/account/account.spec.ts.ejs
> Fix protractor e2e with Keycloak 12.x

- generators/server/prompts.js
Disable Couchbase as a prompt so v7 does not prompt users. Can be re-enabled once [Couchbase for Spring Boot 2.4](https://github.com/jhipster/generator-jhipster/pull/14184) is fixed.
---
> Disable Couchbase and move WebFlux and Infinispan out of beta

- generators/entity-server/templates/partials/it_patch_update.partial.java.ejs
- generators/entity-server/templates/partials/save_template.ejs
- generators/entity-server/templates/reactive/partials/save_template.ejs
- generators/entity-server/templates/src/main/java/package/common/get_all_template.ejs
- generators/entity-server/templates/src/main/java/package/common/get_filtered_template.ejs
- generators/entity-server/templates/src/main/java/package/common/get_template.ejs
- generators/entity-server/templates/src/main/java/package/common/patch_template.ejs
- generators/entity-server/templates/src/main/java/package/common/search_template.ejs
- generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
- generators/entity-server/templates/src/main/java/package/repository/EntityRepository.java.ejs
- generators/entity-server/templates/src/main/java/package/repository/EntityRepositoryInternalImpl_reactive.java.ejs
- generators/entity-server/templates/src/main/java/package/repository/EntityRepository_reactive.java.ejs
- generators/entity-server/templates/src/main/java/package/repository/rowmapper/EntityRowMapper.java.ejs
- generators/entity-server/templates/src/main/java/package/repository/search/EntitySearchRepository.java.ejs
- generators/entity-server/templates/src/main/java/package/service/EntityQueryService.java.ejs
- generators/entity-server/templates/src/main/java/package/service/EntityService.java.ejs
- generators/entity-server/templates/src/main/java/package/service/criteria/EntityCriteria.java.ejs
- generators/entity-server/templates/src/main/java/package/service/dto/EntityDTO.java.ejs
- generators/entity-server/templates/src/main/java/package/service/impl/EntityServiceImpl.java.ejs
- generators/entity-server/templates/src/main/java/package/service/mapper/EntityMapper.java.ejs
- generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs
- generators/entity-server/templates/src/test/java/package/domain/EntityTest.java.ejs
- generators/entity-server/templates/src/test/java/package/service/dto/EntityDTOTest.java.ejs
- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
- generators/generator-base.js
- utils/entity.js
> Replace asEntity/asDto by pre calculated variables.

- generators/client/templates/vue/src/main/webapp/content/scss/vendor.scss.ejs
Fix #14294 
With Angular, we always do `@import 'bootstrap-variables';` on `vendor.scss` https://github.com/jhipster/generator-jhipster/blob/77288374cf16ec4f74e5ba132a24ad00ceb8bdc5/generators/client/templates/angular/src/main/webapp/content/scss/vendor.scss.ejs#L29 but not with Vue (there is a condition). I don't know why https://github.com/jhipster/generator-jhipster/commit/00c1a2eae1bd47ee7d755b5b0c396d7ef665a113#diff-91bb2f362ad6ae20a3d2f82daaf5cc7e0f76d3e1c7c1e3b525c56e396d0007b1
---
> [Vue] Remove condition to import bootstrap-variables in vendor.scss

- generators/server/files.js
- generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs
This changes things so microservices don't have a `CustomClaimConverter` for looking up a user's attributes. It should only be at the gateway or monolith level. Since it wasn't implemented for reactive, this means it only applies to non-reactive monoliths now. FYI @Falydoor. 
---
> OIDC /userinfo lookup improvements

- cli/utils.js
Now prints the sponsor message again instead of twice the sucess message when doing `jhipster jdl default` for example.
closes #14329
---
> print sponsor message instead of twice the success message

- generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
- generators/server/templates/src/main/java/package/service/ColumnConverter.java.ejs
> Fix userId type when using OAuth 2.0

- generators/app/index.js
- generators/azure-app-service/index.js
- generators/azure-app-service/templates/application-azure.yml.ejs
- generators/azure-spring-cloud/index.js
- generators/azure-spring-cloud/templates/application-azure.yml.ejs
- generators/azure-spring-cloud/templates/github/workflows/azure-spring-cloud.yml.ejs
- generators/ci-cd/index.js
- generators/ci-cd/templates/.gitlab-ci.yml.ejs
- generators/ci-cd/templates/azure-pipelines.yml.ejs
- generators/ci-cd/templates/circle.yml.ejs
- generators/ci-cd/templates/github-actions.yml.ejs
- generators/ci-cd/templates/jenkins/Jenkinsfile.ejs
- generators/ci-cd/templates/travis.yml.ejs
- generators/client/files-react.js
- generators/client/files-vue.js
- generators/client/index.js
- generators/client/prompts.js
- generators/client/templates/angular/package.json.ejs
- generators/generator-base-docker.js
- generators/generator-base-private.js
- generators/generator-base.js
- generators/generator-list.js
- jdl/jhipster/client-framework-types.js
Contributes to #14235, just to give an overview of what it looks like on a generator
---
> azure generators using derived properties

- generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs
- generators/server/templates/src/main/docker/config/realm-config/jhipster-realm.json.ejs
Add `roles` claim in the access token. The change got introduced during Keycloak `v11.x` upgrade.
---
> Add roles claim in the access token

- lib/index.js
- package.json
Allows
```
const {AppGenerator, constants } = require('generator-jhipster');
```
instead of
```
const AppGenerator = require('generator-jhipster/generators/app');
const constants = require('generator-jhipster/generators/generator-constants');
```
---
> Expose public api for blueprint and modules.

- generators/bootstrap/index.js
- generators/client/needle-api/needle-client-angular.js
- generators/generator-base.js
- generators/utils.js
Allows to customize already applied needled detection.
- `prettierAware`: prettier formatting takes line width into account.
Needles must test for dynamic empty space/line breaks count.
- `regexp`: custom detection when testing the entire content is not a good approach, and there is a simpler test to use.
Related to https://github.com/jhipster/generator-jhipster/issues/14388.
---
> Fixes angular duplicated navbar element generation.

- generators/bootstrap/index.js
- generators/client/needle-api/needle-client.js
- generators/utils.js
- package-lock.json
- package.json
- test/needle-api/needle-client-angular.spec.js
- bug-fix: dropped pipeline-pipe due to not handling errors correctly.
- bug-fix: when adding styles, ignore comments when testing if it's already included.
- test added: when adding same needles twice, they should not be added and files should not change.
- misc improvements to needle tests.
Closes https://github.com/jhipster/generator-jhipster/issues/14388.
---
> Add regression tests for duplicated needle and fix css needle.

- generators/server/templates/src/test/java/package/config/JHipsterBlockHoundIntegration.java.ejs
Add the method `SpringValidatorAdapter.validate` in `JHipsterBlockHoundIntegration`
Fix  #14326
---
> add SpringValidatorAdapter.validate in Blockhound

- generators/client/templates/common/package.json
- generators/common/templates/package.json
- generators/generator-constants.js
- Move npm to dependabot
- Revert npm to 7.6.3, version 7.7.0 is quite buggy.
- Revert cypress to 6.6.0. cypress >= 6.7.0 seems to be not stable with our current implementation.
---
> Move npm to dependabot and revert npm and cypress.

- generators/client/templates/vue/src/main/webapp/content/scss/_bootstrap-variables.scss.ejs
- generators/client/templates/vue/src/main/webapp/content/scss/vendor.scss.ejs
Following https://github.com/jhipster/generator-jhipster/pull/14306
---
> Vue: fix bootstrap variables

- generators/kubernetes/templates/db/mysql.yml.ejs
- generators/server/templates/src/main/docker/app.yml.ejs
- generators/server/templates/src/main/docker/mariadb.yml.ejs
- test/templates/compose/01-gateway/src/main/docker/app.yml
- test/templates/compose/01-gateway/src/main/docker/mysql.yml
- test/templates/compose/02-mysql/src/main/docker/app.yml
- test/templates/compose/02-mysql/src/main/docker/mysql.yml
- test/templates/compose/07-mariadb/src/main/docker/app.yml
- test/templates/compose/07-mariadb/src/main/docker/mariadb.yml
- test/templates/compose/08-monolith/src/main/docker/app.yml
- test/templates/compose/08-monolith/src/main/docker/mysql.yml
- test/templates/compose/09-kafka/src/main/docker/app.yml
- test/templates/compose/09-kafka/src/main/docker/mysql.yml
Setting `MYSQL_USER` to `root` seems to fail with latest mySQL version being used when deployed as container
There are two more places where this is set for openshift but to non-root values so I guess that should be fine
here is the error I got
```
kubectl logs product-mysql-55fbb8fdd8-6dbwc -n jhipster         
2021-03-27 13:52:40+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.23-1debian10 started.
2021-03-27 13:52:40+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2021-03-27 13:52:40+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.23-1debian10 started.
2021-03-27 13:52:40+00:00 [ERROR] [Entrypoint]: MYSQL_USER="root", MYSQL_USER and MYSQL_PASSWORD are for configuring a regular user and cannot be used for the root user
Remove …
```
> Remove mysql root user setting

- cli/jhipster.js
- cli/program.js
- generators/bootstrap/index.js
- generators/entity/index.js
- test/bootstrap/bootstrap.spec.js
- test/cli/jdl-fork.spec.js
Fixes https://github.com/jhipster/generator-jhipster/issues/14473
---
> Fix commit of files written after first commit was done.

- cli/program.js
Somehow we have missed supporting the force-insights option. This adds the force-insights option back to the generator. Otherwise passing this option results in a error; 
```
sudharaka@sudharaka-XPS-8700:~/IdeaProjects/GeneratedApplications/jhipsterTest$ jhipster --force-insights
INFO! Using JHipster version installed globally
error: unknown option '--force-insights'
sudharaka@sudharaka-XPS-8700:~/IdeaProjects/GeneratedApplications/jhipsterTest$
```
JHipster Online is also effected by this error which I've opened a PR as well; https://github.com/jhipster/jhipster-online/pull/291
--- …
> Add support for force-insights option

- generators/server/templates/src/main/resources/config/application-dev.yml.ejs
- generators/server/templates/src/main/resources/config/application.yml.ejs
> Allow CORS settings for frontend server

- generators/entity-client/templates/angular/src/main/webapp/app/entities/service/entity.service.spec.ts.ejs
> [angular] Fix @typescript-eslint/no-unused-vars in entity service test

- generators/entity-server/index.js
- utils/field.js
- utils/relationship.js
> fix: small fixes needed for composite key

- generators/client/templates/angular/src/main/webapp/app/app.module.ts.ejs
- generators/client/templates/common/src/main/webapp/swagger-ui/index.html.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/14488
- authenticationToken need parsed
- key name is wrong in localStorage
---
> Fail to get jwt token

- generators/database-changelog-liquibase/templates/src/main/resources/config/liquibase/fake-data/table_entity.csv.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/service/entity.service.spec.ts.ejs
- generators/entity-client/templates/vue/src/test/javascript/spec/app/entities/entity.service.spec.ts.ejs
- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
- utils/faker.js
- utils/field.js
> Faker: use faker.datatype instead of deprecated faker.random

- generators/client/templates/angular/package.json.ejs
- generators/client/templates/angular/webpack/webpack.custom.js.ejs
- generators/server/index.js
- Disable browser sync for 'ng build' without --watch
- Use backend server port when executing 'ng build --watch'
---
> Add watch build script for angular frontend
