- .github/workflows/webflux.yml
- generators/server/templates/src/main/java/package/config/ReactiveSecurityConfiguration.java.ejs
- generators/server/templates/src/test/java/package/service/UserServiceIT.java.ejs
- generators/server/templates/src/test/java/package/web/rest/AccountResourceIT.java.ejs
- test-integration/samples/webflux-nodb-oauth2/.yo-rc.json
Fixes https://github.com/jhipster/generator-jhipster/issues/11620
> Remove AuditEventService from SecurityConfig for reactive and no databaseType

- generators/aws-containers/prompts.js
Remove common code out of if-else construct
> Minor Cleanup

- cli/utils.js
> Print stacktrace with error message.

- package-lock.json
- package.json
> Bump yeoman-environment to 2.9.6 and yeoman-generator to 4.9.0

- generators/client/templates/angular/package.json.ejs
- generators/client/templates/angular/src/main/webapp/app/core/auth/csrf.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/core.module.ts.ejs
- generators/client/templates/angular/webpack/webpack.common.js.ejs
This updates all Angular related dependencies to latest. 
Fixes #11652
> Update all Angular Generator Dependencies

- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
> Refactor the 'block()/collectList.block' Handling in the Integration Tests

- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs
Commit https://github.com/jhipster/generator-jhipster/commit/51afa3310091fbd106682216c5632786d7a7e986 accidentally removed the if-block around the Create new button, introduced by https://github.com/jhipster/generator-jhipster/pull/10562
> Reintroduce check around 'Create new' button

- generators/server/templates/src/main/java/package/config/OpenApiConfiguration.java.ejs
- test-integration/samples/webflux-psql/.yo-rc.json
> Use springFox3 for reactive gateway/monolith

- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
Following the recent test cleanup patch, similarly, these converts the` <% if (something) %>someText<% } %> ` into `<%= variable %>` - which makes the code bit readable, and allows to customize the conditions a bit easier in the future.
> Integration test cleanup

- generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
> fix(sonar): Remove unused import

- generators/generator-constants.js
> Update NPM version to 6.14.5

- generators/aws/lib/eb.js
- generators/statistics.js
> core: fix: remove warning about uuid

- generators/client/templates/react/package.json.ejs
Following:
- https://github.com/jhipster/generator-jhipster/issues/11561
- https://github.com/jhipster/react-jhipster/issues/47
- https://github.com/jhipster/react-jhipster/pull/49
_____
> Upgrade to react-jhipster@0.11.0

- generators/generator-constants.js
> Upgrade to jhipster-registry v6.2.0

- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.model.ts.ejs
Reported issue in https://github.com/jhipster/generator-jhipster/pull/11653 It's a try, I don't know if it's the best solution.
> Fix failing daily react builds 

- generators/generator-constants.js
See https://docs.gradle.org/6.4/release-notes.html for details
> gradle: update gradle to latest version 6.4

- generators/server/templates/src/main/java/package/config/StaticResourcesWebConfiguration.java.ejs
> fix (cache-backend) : append  classpath

- generators/server/templates/src/main/java/package/config/CacheConfiguration.java.ejs
According to Sonar, this change is necessary.
> Providing a parametrized type for generic

- cli/commands.js
- generators/kubernetes-helm/files.js
- generators/kubernetes-helm/templates/csvc/Chart.yml.ejs
- generators/kubernetes-helm/templates/helm-apply.sh.ejs
- generators/kubernetes-helm/templates/helm-upgrade.sh.ejs
- generators/kubernetes-knative/files.js
- generators/kubernetes-knative/templates/helm-apply.sh.ejs
- generators/kubernetes-knative/templates/helm-upgrade.sh.ejs
- generators/kubernetes-knative/templates/kubectl-apply.sh.ejs
- generators/kubernetes/files.js
- generators/kubernetes/templates/kubectl-apply.sh.ejs
- generators/kubernetes/templates/kustomize/kustomization.yml.ejs
- test/knative.spec.js
- test/kubernetes.helm.spec.js
- test/kubernetes.spec.js
- helm chart generator package name updated to avoid conflict/overwrite when generated from the root directory
> cosmetic update to avoid conflict with service names

- .github/workflows/angular.yml
- .github/workflows/react.yml
- .github/workflows/webflux.yml
- azure-pipelines.yml
- generators/generator-constants.js
> Upgrade jhipster dependencies 3.7.0

- generators/entity/index.js
Fixes https://github.com/jhipster/generator-jhipster/issues/11527
> Entity name should be alphanumeric only.

- cli/utils.js
Following https://github.com/jhipster/generator-jhipster/issues/11630.
Add a verification if the registered namespace is correct.
> Add verification of the registered namespace.

- cli/cli.js
Fixes https://github.com/jhipster/generator-jhipster/issues/11727
> Fix jhipster -d

- .github/workflows/angular.yml
- .github/workflows/react.yml
- .github/workflows/webflux.yml
- azure-pipelines.yml
- generators/generator-constants.js
Related to https://github.com/jhipster/generator-jhipster/issues/11734
> Downgrade mysql driver version to 8.0.19

- .github/workflows/angular.yml
- .github/workflows/react.yml
- .github/workflows/webflux.yml
- azure-pipelines.yml
- generators/generator-constants.js
Fix https://github.com/jhipster/generator-jhipster/issues/11734
After the merge of this, I'll restart the builds in Vue.js blueprint and hope it is definitively fixed
_____
> Upgrade jhipster dependencies 3.7.1

- generators/generator-base.js
Fix https://github.com/jhipster/generator-jhipster/issues/11747
> Fix module lookup.

- generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
- generators/server/templates/src/main/java/package/domain/PersistentToken.java.ejs
- generators/server/templates/src/main/java/package/domain/User.java.ejs
> Use "READ_WRITE" cache strategy by default

- generators/client/templates/angular/webpack/webpack.common.js.ejs
> Fix html-loader exclude in Angular for Windows

- package-lock.json
- package.json
> chore: Update prettier-java to v0.8.0

- generators/client/needle-api/needle-client-angular.js
- generators/client/templates/angular/src/main/webapp/app/admin/audits/audit-data.model.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/audits/audits.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management-detail.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/layouts/navbar/navbar.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/shared/alert/alert-error.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/shared/alert/alert.component.ts.ejs
- generators/client/templates/angular/tsconfig.json.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-detail.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-detail.component.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.ts.ejs
- test/needle-api/needle-client-angular.spec.js
> Use strictTemplates in Angular

- generators/client/templates/angular/package.json.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/11762
_____
> Upgrade ng-jhipster to 0.13.0

- generators/server/templates/src/test/java/package/AbstractNeo4jIT.java.ejs
> Neo4j: use constant for docker image in integration tests

- test-integration/samples/.jhipster/CassTestMapstructEntity.json
- test-integration/samples/.jhipster/CassTestServiceClassEntity.json
- test-integration/samples/.jhipster/CassTestServiceImplEntity.json
- test-integration/samples/.jhipster/FieldTestEntity.json
- test-integration/samples/.jhipster/FieldTestInfiniteScrollEntity.json
- test-integration/samples/.jhipster/FieldTestMapstructAndServiceClassEntity.json
- test-integration/samples/.jhipster/FieldTestPaginationEntity.json
- test-integration/samples/.jhipster/FieldTestServiceClassAndJpaFilteringEntity.json
- test-integration/samples/.jhipster/FieldTestServiceImplEntity.json
- test-integration/samples/.jhipster/Operation.json
- test-integration/samples/.jhipster/TestEntity.json
- test-integration/samples/.jhipster/TestInfiniteScroll.json
- test-integration/samples/.jhipster/TestManyToMany.json
- test-integration/samples/.jhipster/TestMapstruct.json
- test-integration/samples/.jhipster/TestPagination.json
- test-integration/samples/.jhipster/TestServiceClass.json
- test-integration/samples/.jhipster/TestServiceImpl.json
- test-integration/samples/.jhipster/TestTwoRelationshipsSameEntity.json
> Make test-integration changelogdate unique

- generators/generator-base.js
- generators/server/needle-api/needle-server-liquibase.js
- generators/server/templates/src/main/resources/config/liquibase/master.xml.ejs
- test/needle-api/needle-server-liquibase.spec.js
> Add incremental liquibase needle.

- package-lock.json
- package.json
> Bump yeoman-environment to 2.10.2 and yeoman-generator to 4.10.1

- generators/generator-constants.js
> update gradle to 6.4.1

- generators/server/templates/src/test/java/package/AbstractNeo4jIT.java.ejs
Align with https://github.com/jhipster/generator-jhipster/pull/11803 and hopefully fixes the daily build with gradle
> use dynamic property source for neo4j integration test

- package-lock.json
- package.json
> Updated the JCore dep to v7.3.1

- .github/workflows/angular.yml
- .github/workflows/generator.yml
- .github/workflows/react.yml
- .github/workflows/webflux.yml
> Implement skip-ci label for drafts PRs.

- generators/client/templates/angular/src/main/webapp/app/admin/audits/audits.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/audits/audits.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/audits/audits.route.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management.route.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/admin/audits/audits.component.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/helpers/mock-route.service.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.route.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/pagination-template.ejs
- generators/entity-client/templates/angular/src/test/javascript/spec/app/entities/entity-management.component.spec.ts.ejs
> Fix double page loading in Angular

- .github/workflows/angular.yml
- .github/workflows/react.yml
- .github/workflows/webflux.yml
- azure-pipelines.yml
- generators/generator-constants.js
> Use jhipster dependencies master 3.8.0-SNAPSHOT

- generators/app/prompts.js
> fix: jhipster version for marketplace

- generators/client/templates/angular/src/main/webapp/app/core/user/user.service.ts.ejs
> Fix eslint warning in OAuth + Angular

- generators/generator-constants.js
Some of the languages differs between the values and the localeId used in Angular resulting this kind of issue #11745
Close #11745
> fix: Angular locale module name

- generators/server/templates/build.gradle.ejs
- generators/server/templates/pom.xml.ejs
- generators/server/templates/src/main/java/package/config/JacksonConfiguration.java.ejs
This removes Jackson Afterburner completely. Please merge this only after we reach a consensus at https://github.com/jhipster/generator-jhipster/pull/10283#issuecomment-616491178
Related to https://github.com/jhipster/generator-jhipster/pull/10283#issuecomment-616491178
> Remove Jackson Afterburner Completely

- generators/generator-base.js
- test/generator-base.spec.js
> Fix to dateFormatForLiquibase

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
>  Run release drafter only on jhipster/generator-jhipster repository

- .github/workflows/angular.yml
- .github/workflows/react.yml
- .github/workflows/webflux.yml
This PR force chalk to enable colors.
> Github actions supports colors but due to a bug its disabled at current chalk release.

- generators/client/needle-api/needle-client-angular.js
- generators/client/templates/angular/src/main/webapp/app/admin/admin-routing.module.ts.ejs
- test/needle-api/needle-client-angular.spec.js
> Fix double trailing comma generation in the entity module

- generators/server/templates/src/main/java/package/service/UserService.java.ejs
> Don't use read-only transaction to persist changes

- generators/server/templates/build.gradle.ejs
- generators/server/templates/pom.xml.ejs
- generators/server/templates/src/main/java/package/config/CloudDatabaseConfiguration.java.ejs
- generators/server/templates/src/main/java/package/config/DatabaseConfiguration.java.ejs
- generators/server/templates/src/main/java/package/config/dbmigrations/InitialSetupMigration.java.ejs
- generators/server/templates/src/main/java/package/config/dbmigrations/package-info.java.ejs
MongoBee is not maintained and doesn't support MongoDB driver v4 that comes with last Spring Data MongoDB release.
FYI #8678 was a previous feature request to switch to Mongock that was declined because the project had not enough github stars and there was a risk that the tool would be short-lived. Things have changed since, the project has 119 stars, is active.
> [SpringBoot 2.3] Replace MongoBee with Mongock

- generators/common/templates/.prettierignore.ejs
> Add .mvn in prettierignore [ci skip]

- generators/common/templates/.huskyrc.ejs
> Format huskyrc [skip ci]

- generators/entity-server/templates/src/main/java/package/common/delete_template.ejs
> Template delete in EntityServiceImpl

- generators/client/templates/angular/package.json.ejs
- generators/client/templates/react/package.json.ejs
- generators/server/templates/package.json.ejs
- package-lock.json
- package.json
> Ordering openapitools/openapi-generator-cli

- generators/languages/templates/src/main/webapp/i18n/zh-tw/audits.json
- generators/languages/templates/src/main/webapp/i18n/zh-tw/global.json.ejs
- generators/languages/templates/src/main/webapp/i18n/zh-tw/health.json.ejs
- generators/languages/templates/src/main/webapp/i18n/zh-tw/home.json
- generators/languages/templates/src/main/webapp/i18n/zh-tw/register.json
> Refine zh-tw localization.

- .github/workflows/angular.yml
- .github/workflows/react.yml
- .github/workflows/webflux.yml
- azure-pipelines.yml
- generators/generator-constants.js
> Upgrade jhipster dependencies 3.8.0

- generators/entity/index.js
Generate the code of search option only when searchEngine option is present.
> Generate the code of search option only when searchEngine option is present

- generators/server/templates/build.gradle.ejs
- generators/server/templates/pom.xml.ejs
These dependencies don't seem to be used.
> fix: remove dependencies

- .github/workflows/angular.yml
- .github/workflows/react.yml
- .github/workflows/webflux.yml
- azure-pipelines.yml
- generators/generator-constants.js
> Use jhipster dependencies master 3.9.0-SNAPSHOT

- generators/generator-transforms.js
> When prettier transform fails, print the file that failed.

- generators/generator-constants.js
> gradle: update to 6.5

- generators/client/templates/angular/webpack/webpack.prod.js.ejs
- generators/client/templates/react/webpack/webpack.prod.js.ejs
> Remove unused variable path from Webpack prod config

- cli/cli.js
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.reducer.ts.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/index.tsx.ejs
- generators/entity-client/templates/react/src/test/javascript/spec/app/entities/entity-reducer.spec.ts.ejs
Display delete entity dialog on top of parent entity component.
This bug is related to issue #11805 on failing React builds.
> React: Delete Entity Bug Fix #11805

- generators/entity/prompts.js
Fixes https://github.com/jhipster/generator-jhipster/issues/11898
> Fix enum not asking for type.

- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-delete-dialog.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs
> Remove pager from react templates

- generators/server/templates/build.gradle.ejs
- generators/server/templates/gradle.properties.ejs
- generators/server/templates/pom.xml.ejs
- generators/server/templates/src/main/java/package/config/LiquibaseConfiguration.java.ejs
- generators/server/templates/src/main/java/package/repository/PersistenceAuditEventRepository.java.ejs
- generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs
> [SpringBoot 2.3] R2DBC

- package-lock.json
- package.json
> Bump jhipster-core to 7.3.2

- generators/cloudfoundry/templates/manifest.yml.ejs
> Fix CloudFoundry manifest

- generators/server/templates/gradle/swagger.gradle.ejs
> set reactive option for open api generator in gradle

- generators/heroku/index.js
- generators/heroku/templates/application-heroku.yml.ejs
- generators/server/templates/src/main/java/package/config/CacheConfiguration.java.ejs
This PR is in draft mode to see if we all agree on the property naming for additional cache properties.
Before we can merge this at least two things must be done:
* Add additional common properties to jhipster(lib)
* Adapt cache configuration to respect these for redis and memcached
closes #11695
closes #11696
> Provide memcached and redis support for heroku

- generators/entity-server/templates/src/main/java/package/service/impl/EntityServiceImpl.java.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/11482
_____
> Do not generate Javadoc for service impl

- generators/ci-cd/templates/.gitlab-ci.yml.ejs
> fix gradle docker-push for non-docker environments

- generators/server/templates/src/test/java/package/AbstractCassandraTest.java.ejs
- generators/server/templates/src/test/java/package/CassandraKeyspaceIT.java.ejs
- add type information to CASSANDRA_CONTAINER
- remove unnecessary Exceptions from throws clauses
- improve code complexity score of applyScripts()
- fix typo in method name
> Update/simplify code in AbstractCassandraTest.java

- generators/generator-constants.js
See 
* https://github.com/GoogleContainerTools/jib/blob/master/jib-gradle-plugin/CHANGELOG.md#240
* https://github.com/GoogleContainerTools/jib/blob/master/jib-maven-plugin/CHANGELOG.md#240
for details.
> update jib plugins to 2.4.0

- cli/cli.js
- cli/run-yeoman-process.js
- Following discussion at commander repository, improve argument handling.
> Improve commander handling.

- package-lock.json
- package.json
> Bump yeoman-generator to 4.11.0

- package-lock.json
- package.json
> Bump jhipster-core to 7.3.4

- generators/entity/index.js
```
@skipClient
entity BackendOnly {}
```
---
> Allow to skipClient just for an entity

- generators/client/files-angular.js
- generators/client/templates/angular/.eslintrc.json.ejs
- generators/client/templates/angular/package.json.ejs
- generators/client/templates/angular/src/main/webapp/index.html.ejs
- generators/client/templates/angular/src/test/javascript/jest.conf.js.ejs
- generators/client/templates/angular/tsconfig.app.json.ejs
- generators/client/templates/angular/tsconfig.base.json.ejs
- generators/client/templates/angular/tsconfig.e2e.json.ejs
- generators/client/templates/angular/tsconfig.json.ejs
- generators/client/templates/angular/webpack/utils.js.ejs
- generators/client/templates/angular/webpack/webpack.common.js.ejs
- test/app-client-custom-path.spec.js
- test/app.spec.js
- test/utils/expected-files.js
> feat (angular): Upgrade angular to v10.0

- generators/gae/index.js
- generators/gae/templates/application-prod-gae.yml.ejs
- generators/gae/templates/dispatch.yaml.ejs
This adds micro-service support for GAE sub-generator
Resolves https://github.com/jhipster/generator-jhipster/issues/10345
> Add Microservice Support for GAE sub-generator

- .github/PULL_REQUEST_TEMPLATE.md
- Currently when creating items, it mixes with checklist title.
> Changes to PR template.

- generators/generator-constants.js
> Upgrade to jhipster-registry v6.3.0

- .github/workflows/angular.yml
- .github/workflows/react.yml
- .github/workflows/webflux.yml
- azure-pipelines.yml
- generators/generator-constants.js
> Upgrade jhipster dependencies 3.9.0

- generators/server/templates/src/main/java/package/Application.java.ejs
> Convert if's into declarative statements

- cli/jdl.js
- test/cli/jdl.js
> cli/jdl: Try to download from samples repository version branch before master.

- generators/app/prompts.js
- generators/client/prompts.js
- generators/entity/prompts.js
- generators/server/prompts.js
- When using this.async(), we should treat promises exceptions by ourselves.
We are not doing that.
- generator.async is kept for legacy compatibility only.
- Promises are recommended.
Reference:
https://yeoman.io/authoring/running-context.html at 'Asynchronous tasks' topic
> Prompts: return promises instead of using generator.async/done

- generators/client/templates/react/package.json.ejs
- generators/client/templates/react/src/main/webapp/index.html.ejs
- generators/client/templates/react/webpack/webpack.common.js.ejs
Upgrade `html-webpack-plugin` dependency 
---
> chore (react): Upgrade html-webpack-plugin dependency 

- generators/client/templates/react/package.json.ejs
- generators/client/templates/react/src/main/webapp/index.html.ejs
- generators/client/templates/react/webpack/webpack.common.js.ejs
Upgrade `html-webpack-plugin` dependency
---
> chore (react): Upgrade html-webpack-plugin dependency

- generators/app/index.js
- generators/generator-base-private.js
Force override files at `.jhipster` folder.
---
> Implement registerForceEntitiesTransform

- cli/import-jdl.js
- generators/aws-containers/index.js
- generators/aws-containers/prompts.js
- generators/entity/index.js
- generators/entity/prompts.js
- generators/export-jdl/index.js
- generators/generator-base-private.js
- generators/generator-base.js
- generators/spring-controller/prompts.js
- generators/utils.js
- jdl/bundling/generated/generated-serialized-grammar.js
- package-lock.json
- package.json
This PR removes the uses of the JCore dep in favor of the files now in the generator.
---
> Remove jcore dep

- generators/server/templates/src/main/docker/sonar.yml.ejs
> 🧹 remove unnecessary exposed port from sonar.yml

- generators/app/index.js
- generators/generator-base.js
Add `--application-type` option and use it to get defaults from jhipster-core.
---
> Use jhipster-core defaults for `jhipster --defaults`.

- generators/app/index.js
> Fix languages skip prompts.

- generators/app/index.js
- generators/generator-defaults.js
- test/app-required-config.js
> Fix default jhiPrefix fallback value.

- jdl/jhipster/application-options.js
It looks like enough but I'm not really sure.
---
> Update application options in JDL with vue

- .github/workflows/angular.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
- azure-pipelines.yml
- generators/generator-constants.js
> Use jhipster dependencies master 3.10.0-SNAPSHOT

- README.md
> Add Vue badge in README [ci skip]

- generators/generator-constants.js
- generators/server/templates/gradle.properties.ejs
- generators/server/templates/pom.xml.ejs
> Update liquibase version to 3.10.1

- generators/cleanup.js
- generators/client/files-vue.js
> Remove audits - Fix

- generators/entity-client/templates/vue/src/test/javascript/spec/app/entities/entity-management-update.component.spec.ts.ejs
Fix some errors with vue test after audits removal.
It’s not passing yet, but improves.
CC @avdev4j, @pascalgrimaud 
---
> Vue: register components to spec.

- test/languages.spec.js
> Drop only from tests.

- generators/entity-client/templates/vue/src/test/javascript/spec/app/entities/entity-management-details.component.spec.ts.ejs
- generators/entity-client/templates/vue/src/test/javascript/spec/app/entities/entity-management-update.component.spec.ts.ejs
Fix https://github.com/jhipster/jhipster-vuejs/issues/567
---
> Improve tests for Vue

- generators/gae/index.js
This updates app engine locations as per; https://cloud.google.com/appengine/pricing
Fixes https://github.com/jhipster/generator-jhipster/issues/12085
---
> Update Google App Engine Locations

- generators/entity-client/templates/vue/src/test/javascript/spec/app/entities/entity-management-update.component.spec.ts.ejs
related to https://github.com/jhipster/generator-jhipster/issues/10575
---
> Fix duplicate user service import for Vue app

- cli/cli.js
- cli/environment-builder.js
- cli/import-jdl.js
- cli/run-yeoman-process.js
- generators/entity/index.js
- generators/export-jdl/index.js
- generators/generator-base.js
- generators/upgrade-config/index.js
- generators/upgrade/index.js
- test/cli/cli.spec.js
- test/cli/import-jdl.spec.js
- Environment 3 will remove callback support and will use the promise alternative.
---
> Use environment promise instead of callback

- generators/generator-constants.js
- generators/server/templates/gradle.properties.ejs
- generators/server/templates/pom.xml.ejs
> Update liquibase version to 4.0.0

- generators/generator-constants.js
> Update NPM version to 6.14.6

- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity-update.component.ts.ejs
Following https://github.com/jhipster/generator-jhipster/pull/12095
---
> Fix duplicate user service import in update component for Vue app

- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity-update.component.ts.ejs
> Fix import service for Vue app

- .github/dependabot.yml
This adds GitHub Actions to dependabot.yml for auto upgrade workflow actions.
Resolves https://github.com/jhipster/generator-jhipster/issues/12103
> Add GitHub Actions Workflow Update to Dependabot

- generators/client/templates/vue/src/main/webapp/app/admin/user-management/user-management.service.ts.ejs
> Fix vue+neo4j app

- README.md
> Add Vue daily builds in README [ci skip]

- generators/languages/index.js
> Call updateLanguagesInLanguagePipe only for Angular and React app

- generators/client/templates/vue/src/test/javascript/spec/app/admin/user-management/user-management-edit.component.spec.ts.ejs
- generators/client/templates/vue/src/test/javascript/spec/app/admin/user-management/user-management.component.spec.ts.ejs
Following https://github.com/jhipster/generator-jhipster/pull/12106
---
> Fix Vue+Neo4j tests

- generators/generator-constants.js
- generators/server/templates/gradle.properties.ejs
- generators/server/templates/pom.xml.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/12105
Reverts jhipster/generator-jhipster#12097
> Revert "Update liquibase version to 4.0.0"

- generators/app/index.js
- generators/client/templates/angular/package.json.ejs
- generators/client/templates/react/package.json.ejs
- generators/client/templates/vue/package.json.ejs
- generators/common/templates/.lintstagedrc.js.ejs
- generators/generator-base-private.js
- generators/generator-base.js
- generators/generator-defaults.js
- generators/generator-transforms.js
- generators/server/templates/package.json.ejs
- test/app.spec.js
- test/generator-transform.spec.js
- test/needle-api/needle-server-cache.spec.js
- test/templates/blueprints/generator-jhipster-prettier-transform/generators/common/index.js
- test/templates/blueprints/generator-jhipster-prettier-transform/package.json
- test/utils/utils.js
Fixes https://github.com/jhipster/generator-jhipster/issues/12109
---
> Enable prettier by default.

- generators/app/index.js
- generators/client/templates/angular/package.json.ejs
- generators/client/templates/react/package.json.ejs
- generators/client/templates/vue/package.json.ejs
- generators/common/templates/.prettierrc.ejs
- generators/entity-server/templates/src/main/java/package/common/search_stream_template.ejs
- generators/generator-base-private.js
- generators/generator-base.js
- generators/generator-defaults.js
- generators/server/templates/package.json.ejs
- test/generator-transform.spec.js
- test/needle-api/needle-server-cache.spec.js
fix https://github.com/jhipster/generator-jhipster/issues/12109
---
> Remove Prettier java option in favor of having it baseline

- .github/workflows/vue.yml
- generators/entity-client/templates/vue/src/test/javascript/e2e/entities/entity.spec.ts.ejs
- generators/server/templates/src/main/java/package/service/UserService.java.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/12139
---
> Vue: fix e2e without fields + fix neo4j

- cli/import-jdl.js
- test/cli/import-jdl.spec.js
- test/utils/utils.js
- Migrate tests to proxyquire.
- Rename JDLProcessor instance from generator to processor.
- Remove log from test/utils.
---
> Cleanup import-jdl

- .github/workflows/angular.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
- generators/client/templates/angular/package.json.ejs
- generators/client/templates/react/package.json.ejs
- generators/client/templates/vue/package.json.ejs
> Fix chromedriver version mismatch

- generators/common/templates/README.md.ejs
- generators/generator-base-docker.js
- generators/generator-constants.js
- generators/server/files.js
- generators/server/index.js
- generators/server/templates/src/main/docker/config/realm-config/jhipster-realm.json.ejs
- generators/server/templates/src/main/docker/jhipster-control-center.yml.ejs
- test/utils/expected-files.js
> Add JHCC docker compose files

- generators/client/templates/vue/src/main/webapp/app/account/settings/settings.vue.ejs
Fix https://github.com/jhipster/jhipster-vuejs/issues/642
---
> Fix i18n in settings for Vue

- generators/generator-base.js
> Don't trigger entity file rewrite for jhipster:info

- generators/client/templates/react/src/main/webapp/app/modules/account/password-reset/init/password-reset-init.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/account/settings/settings.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/logs/logs.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/metrics/metrics.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management-update.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/home/home.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/shared/error/page-not-found.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/shared/layout/header/header.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/shared/layout/menus/account.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/shared/layout/menus/admin.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/shared/layout/menus/entities.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/shared/reducers/locale.ts.ejs
React: : clean code (unused imports & methods, and bad formatting code)
---
> [react] Clean code

- generators/client/index.js
- generators/common/index.js
- generators/statistics.js
Continuation of #10788 (for next major release)
> Correct typos (breaking changes for v7)

- generators/client/templates/vue/package.json.ejs
> Add dependencies openapi-generator-cli for Vue applications [ci skip]

- generators/client/templates/angular/package.json.ejs
- generators/client/templates/angular/tsconfig.base.json.ejs
Update **Angular** version 10.0.0 -> 10.0.6
Commands :
```
ng update
ng update @angular/cli @angular/core rxjs
```
[https://angular.io/guide/migration-update-module-and-target-compiler-options](https://angular.io/guide/migration-update-module-and-target-compiler-options)
---
> [angular] Update Angular version 10.0.0 -> 10.0.6

- generators/client/templates/vue/src/main/webapp/app/admin/configuration/configuration.vue.ejs
- generators/client/templates/vue/src/main/webapp/app/admin/health/health-modal.vue.ejs
- generators/client/templates/vue/src/main/webapp/app/admin/health/health.vue.ejs
- generators/client/templates/vue/src/main/webapp/app/admin/logs/logs.vue.ejs
- generators/client/templates/vue/src/main/webapp/app/admin/metrics/metrics-modal.vue.ejs
- generators/client/templates/vue/src/main/webapp/app/admin/metrics/metrics.vue.ejs
- generators/client/templates/vue/src/main/webapp/app/admin/user-management/user-management.vue.ejs
- generators/client/templates/vue/src/main/webapp/app/core/home/home.vue.ejs
- generators/client/templates/vue/src/main/webapp/app/core/ribbon/ribbon.vue.ejs
- generators/client/templates/vue/src/main/webapp/index.html.ejs
- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity.vue.ejs
Fix [https://github.com/jhipster/jhipster-vuejs/issues/531](https://github.com/jhipster/jhipster-vuejs/issues/531)
---
Before : 
After :
> [vue] Sonar Analyze Vue

- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity.component.ts.ejs
- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity.model.ts.ejs
- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity.service.ts.ejs
- generators/entity-client/templates/vue/src/test/javascript/spec/app/entities/entity-details.component.spec.ts.ejs
- generators/entity-client/templates/vue/src/test/javascript/spec/app/entities/entity-update.component.spec.ts.ejs
- generators/entity-client/templates/vue/src/test/javascript/spec/app/entities/entity.component.spec.ts.ejs
- generators/entity-client/templates/vue/src/test/javascript/spec/app/entities/entity.service.spec.ts.ejs
- generators/entity/index.js
- generators/entity/prompts.js
- generators/generator-base-private.js
- generators/generator-defaults.js
- Extract entities, fields and relationship preparation into functions.
Related to https://github.com/jhipster/generator-jhipster/issues/12178.
---
> Fields and relationships refactoring.

- cli/commands.js
- cli/import-jdl.js
- cli/utils.js
- test/cli/cli-utils.spec.js
- test/cli/import-jdl.spec.js
- test/cli/jdl.js
- test/utils/utils.js
Extract environment run in preparation to make fork optional.
---
> Abstract environment run.

- generators/generator-constants.js
> Upgrade JHCC docker image to 0.1.0

- generators/client/templates/vue/src/main/webapp/app/admin/user-management/user-management.component.ts.ejs
- generators/client/templates/vue/src/test/javascript/spec/app/admin/user-management/user-management.component.spec.ts.ejs
- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity.component.ts.ejs
- generators/entity-client/templates/vue/src/test/javascript/spec/app/entities/entity.component.spec.ts.ejs
- package-lock.json
Fix issue https://github.com/jhipster/jhipster-vuejs/issues/596
---
> [vue] Entity page - default order should be asc

- jdl/exporters/jhipster-application-exporter.js
- jdl/exporters/jhipster-entity-exporter.js
- jdl/jdl-importer.js
- test/jdl/exporters/jhipster-application-exporter.spec.js
- test/jdl/jdl-importer.spec.js
- Unify skipYoRcGeneration and skipEntityFilesGeneration into skipConfigFilesGeneration
---
> Change JDL to return applications with entities.

- cli/import-jdl.js
- Pass skipFileGeneration to jdl and save config files at import-jdl.
---
> Change import-jdl to save config files.

- generators/entity-server/templates/src/main/resources/config/liquibase/fake-data/table.csv.ejs
> Call correct function for "account" column. Fixes #12190.

- README.md
> Add Entando as new Gold Sponsor [skip ci]

- README.md
> [v6] Add Entando as new Gold Sponsor [skip ci]

- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.ts.ejs
> [angular] Quick fix #12202

- generators/client/templates/vue/src/main/webapp/app/account/change-password/change-password.component.ts.ejs
- generators/client/templates/vue/src/main/webapp/app/account/change-password/change-password.vue.ejs
- generators/client/templates/vue/src/main/webapp/app/account/login.service.ts.ejs
- generators/client/templates/vue/src/main/webapp/app/account/register/register.vue.ejs
- generators/client/templates/vue/src/main/webapp/app/account/reset-password/finish/reset-password-finish.vue.ejs
- generators/client/templates/vue/src/main/webapp/app/account/settings/settings.vue.ejs
- generators/client/templates/vue/src/main/webapp/app/admin/user-management/user-management.service.ts.ejs
> [vue] Fix code smells

- .eslintrc.json
- cli/commands.js
- cli/import-jdl.js
- cli/run-yeoman-process.js
- package-lock.json
- package.json
- test/cli/cli-utils.spec.js
- test/cli/import-jdl.spec.js
- Allows to pass objects as options.
---
> Add import-jdl option to run the generator without fork.

- generators/app/index.js
- generators/generator-base.js
- generators/server/files.js
- package-lock.json
- package.json
- test/app/incremental-changelog.spec.js
- Create incremental-liquibase option.
---
> Don't override liquibase master.xml when incremental-liquibase option is set.

- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.ts.ejs
> [angular] Fix: Using Event as an entity name results in a compile error

- generators/client/templates/react/src/main/webapp/app/config/axios-interceptor.ts.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/metrics/metrics.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/shared/layout/menus/account.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-delete-dialog.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-detail.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs
> [react] Fix Sonar smells

- generators/client/templates/angular/package.json.ejs
Update dependencies:
- @angular/cli 
- @angular/core
- rxjs
Commands:
```
ng update
ng update @angular/cli @angular/core rxjs
```
---
> [angular] Update @angular/cli @angular/core rxjs

- generators/generator-constants.js
> Update JIB version to 2.5.0

- generators/client/templates/angular/src/main/webapp/app/account/sessions/sessions.route.ts.ejs
Fix https://github.com/hipster-labs/jhipster-daily-builds/runs/960500583?check_suite_focus=true
---
> [angular] Fix polish file

- generators/generator-constants.js
> Update NPM version to 6.14.7

- generators/languages/templates/src/main/webapp/i18n/ru/global.json.ejs
- generators/languages/templates/src/main/webapp/i18n/uz-Cyrl-uz/global.json
- generators/languages/templates/src/main/webapp/i18n/uz-Cyrl-uz/global.json.ejs
- generators/languages/templates/src/main/webapp/i18n/uz-Latn-uz/global.json.ejs
> Translated keys in 'error.file' section in global.json for Russian and Uzbek locales

- generators/server/templates/pom.xml.ejs
> Update git-commit-id-plugin version to 4.0.2

- generators/heroku/index.js
During preparing the next micronaut blueprint release Matt stumbled across https://github.com/jhipster/generator-jhipster-micronaut/issues/142. This fixes it also for the main generator
[skip-ci] [ci-skip]
---
> check err before printing an invalid warning

- generators/app/prompts.js
> Fix setOptOutStatus

- generators/entity-server/templates/src/test/java/package/domain/EntityTest.java.ejs
- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
- generators/server/templates/src/main/java/package/web/rest/UserJWTController.java.ejs
- generators/server/templates/src/test/java/package/config/StaticResourcesWebConfigurerTest.java.ejs
- generators/server/templates/src/test/java/package/config/WebConfigurerTest.java.ejs
- generators/server/templates/src/test/java/package/config/timezone/HibernateTimeZoneIT.java.ejs
- generators/server/templates/src/test/java/package/security/DomainUserDetailsServiceIT.java.ejs
- generators/server/templates/src/test/java/package/security/SecurityUtilsUnitTest.java.ejs
- generators/server/templates/src/test/java/package/security/jwt/JWTFilterTest.java.ejs
- generators/server/templates/src/test/java/package/security/jwt/TokenProviderTest.java.ejs
- generators/server/templates/src/test/java/package/service/MailServiceIT.java.ejs
- generators/server/templates/src/test/java/package/service/UserServiceIT.java.ejs
- generators/server/templates/src/test/java/package/service/mapper/UserMapperTest.java.ejs
- generators/server/templates/src/test/java/package/web/rest/AccountResourceIT.java.ejs
- generators/server/templates/src/test/java/package/web/rest/ClientForwardControllerTest.java.ejs
- generators/server/templates/src/test/java/package/web/rest/TestUtil.java.ejs
- generators/server/templates/src/test/java/package/web/rest/UserJWTControllerIT.java.ejs
- generators/server/templates/src/test/java/package/web/rest/UserResourceIT.java.ejs
- generators/server/templates/src/test/java/package/web/rest/errors/ExceptionTranslatorIT.java.ejs
Fix java issues reported by Sonar
---
> Sonar: Fix java issues 

- generators/client/templates/vue/src/main/webapp/app/account/account.service.ts.ejs
- generators/client/templates/vue/src/main/webapp/app/admin/user-management/user-management.component.ts.ejs
- generators/client/templates/vue/src/main/webapp/app/core/jhi-navbar/jhi-navbar.component.ts.ejs
- generators/client/templates/vue/src/test/javascript/spec/app/admin/user-management/user-management-edit.component.spec.ts.ejs
- generators/client/templates/vue/src/test/javascript/spec/app/admin/user-management/user-management.component.spec.ts.ejs
Fix https://github.com/jhipster/jhipster-vuejs/issues/220
---
> [vue] Clean npm test logs output

- generators/app/index.js
- generators/client/index.js
- generators/common/index.js
- generators/entity-client/index.js
- generators/entity-i18n/index.js
- generators/entity-server/index.js
- generators/entity/index.js
- generators/entity/prompts.js
- generators/generator-base-private.js
- generators/generator-base.js
- generators/languages/index.js
- generators/page/index.js
- generators/server/index.js
- test/blueprint/client-blueprint-custom-path.spec.js
- test/generator-base.spec.js
- Stop forwarding every option to others generators.
- Run time options should be loaded to configOptions to be shared.
---
> Cleanup options parsing.

- generators/generator-constants.js
> Update NPM version to 6.14.8

- generators/client/templates/angular/package.json.ejs
Update dependencies:
- @angular/cli
- @angular/core
Commands:
```
ng update
ng update @angular/cli @angular/core
```
---
> [angular] Update @angular/cli @angular/core

- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity-update.vue.ejs
> [vuejs] Fix option in select

- generators/heroku/templates/Procfile.ejs
- generators/heroku/templates/application-heroku.yml.ejs
Fixes https://github.com/jhipster/generator-jhipster/issues/12235 by moving PORT definition for Heroku into `application-heroku.yml`. 
---
> Move Heroku PORT to profile so it works in Docker

- generators/server/templates/src/main/java/package/web/rest/errors/ExceptionTranslator.java.ejs
This is the PR for #12051 against master, porting https://github.com/jhipster/generator-jhipster/pull/12128 to master.
closes #12051
---
> prevent implementation details leakage via problem details

- generators/client/needle-api/needle-client-angular.js
- generators/client/needle-api/needle-client-i18n.js
- generators/client/needle-api/needle-client-react.js
- generators/client/needle-api/needle-client-vue.js
- generators/entity-client/files.js
- generators/generator-base-private.js
- generators/generator-base.js
- test/needle-api/needle-client-i18n.spec.js
> Use entityClassHumanized at global translation and needles

- generators/cleanup.js
- generators/entity-client/files.js
- generators/entity-server/files.js
- generators/entity-server/templates/src/main/resources/config/liquibase/fake-data/table.csv.ejs
- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
- generators/entity/index.js
- generators/generator-base-private.js
- generators/utils.js
- test/entity.spec.js
- test/liquibase-utils.spec.js
- test/templates/reproducible/.jhipster/Foo.json
- test/utils-faker.spec.js
- utils/entity.js
- utils/faker.js
- utils/field.js
- utils/liquibase.js
- Move together faker related code.
- Extract faker generation away from csv. 
- Allows to be used by test frameworks.
```
field.generateFakeData();
```
---
> Refactor faker.

- cli/import-jdl.js
- generators/cleanup.js
- generators/generator-base-blueprint.js
- generators/generator-base-private.js
- generators/generator-base.js
- test/cli/cli.spec.js
- test/cli/environment-builder.spec.js
- test/generator-base.spec.js
- test/utils.spec.js
- test/utils/utils.js
> Misc cleanups.

- generators/server/templates/src/main/java/package/web/rest/UserResource.java.ejs
> Fix #12250 : use validation annotations on the method parameter

- generators/client/templates/angular/package.json.ejs
> [angular] Bump bootstrap dependencies.

- generators/entity/index.js
Closes https://github.com/jhipster/generator-jhipster/issues/10528
---
> Move entity-* composing to default priority.

- generators/client/templates/angular/package.json.ejs
- generators/client/templates/react/package.json.ejs
- generators/client/templates/vue/package.json.ejs
Upgrade Jest for Angular, React & Vue
---
> Upgrade Jest for Angular, React & Vue

- generators/entity-client/templates/common/src/test/javascript/cypress/integration/entity/entity.spec.ts.ejs
There was a typo in boolean field test.
---
> [Cypress] Fix vue-session-cassandra-fr tests

- test-integration/samples/ngx-psql-es-noi18n-mapsid/.yo-rc.json
> [Cypress] Remove the last protractor build in the CI

- generators/entity-client/files.js
Correct Path of React dir in file.js
> fix(entity-client): use React constants

- .github/workflows/react.yml
- .github/workflows/webflux.yml
- generators/server/prompts.js
Following this discussion: https://groups.google.com/g/jhipster-dev/c/P_4c1bCMVtI/m/ZE--g7qYBwAJ 
---
> SB 2.3/Couchbase: disable CI tests and advertise option as broken

- package.json
> Export jdl folder to npm package.

- generators/generator-constants.js
regular gradle upgrade to 6.6 https://docs.gradle.org/6.6/release-notes.html
[skip-ci] [ci-skip]
---
> upgrade gradle wrapper to 6.6

- .github/workflows/angular.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
> Add blank space

- generators/client/templates/angular/package.json.ejs
- generators/client/templates/react/package.json.ejs
- generators/client/templates/vue/package.json.ejs
- generators/cypress/templates/src/test/javascript/cypress/support/entity.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/tsconfig.json.ejs
> [Cypress] Upgrade to Cypress 5.0.0

- generators/cypress/templates/src/test/javascript/cypress/tsconfig.json.ejs
Replace extends by references to avoid conflict between client tsconfig and Cypress tsconfig
---
> [Cypress] Replace extends by references

- generators/cypress/templates/src/test/javascript/cypress/support/entity.ts.ejs
- generators/entity-client/templates/common/src/test/javascript/cypress/integration/entity/entity.spec.ts.ejs
> [Cypress] Enable eslint for Cypress

- .github/workflows/angular.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
> Fix chromedriver update script

- generators/cypress/templates/cypress.json.ejs
https://docs.cypress.io/guides/guides/test-retries.html#Introduction
Add retries to enhance e2e testing experience with Cypress
---
> [Cypress] Add retries

- generators/client/templates/angular/package.json.ejs
Update **Angular** version 10.0.0 -> 10.0.6
Commands :
```
ng update
ng update @angular/core 
```
---
> [angular] Update Angular version 10.0.11 -> 10.0.12

- generators/client/templates/angular/package.json.ejs
Update **Angular** version 10.0.12 -> **10.0.14**
Commands :
```
ng update
ng update @angular/cli @angular/core
```
---
> [angular] Update Angular version 10.0.12 -> 10.0.14

- generators/client/templates/vue/package.json.ejs
- package-lock.json
- package.json
- test/needle-api/needle-server-liquibase.spec.js
Update Prettier 2.0.5 -> 2.1.1 for Angular, React & Vue
---
> Update Prettier 2.0.5 -> 2.1.1

- generators/cypress/templates/src/test/javascript/cypress/plugins/index.ts.ejs
Reference https://github.com/cypress-io/cypress/issues/7551.
---
> Add workaround to improve cypress success rate.

- generators/server/templates/src/main/java/package/web/rest/UserResource.java.ejs
- generators/server/templates/src/test/java/package/web/rest/UserResourceIT.java.ejs
> Avoid password and resetKey column to be sorted by the /users API

- generators/client/templates/vue/src/main/webapp/app/core/jhi-navbar/jhi-navbar.component.ts.ejs
> [vue] Fix Languages don't appear with Vue and Internationalization #12322

- generators/server/templates/src/main/java/package/web/rest/UserResource.java.ejs
> Use <%_ instead of <% in ejs templates

- generators/server/templates/src/test/java/package/web/rest/UserResourceIT.java.ejs
> [webflux] Fix to not use sorting by createdDate on reactive cases too

- .github/workflows/vue.yml
- .github/workflows/webflux.yml
> [vue] [webflux] Update workflow

- generators/docker-utils.js
> Use bootJar instead of bootWar

- generators/docker-utils.js
> Use bootJar instead of bootWar for v6

- generators/client/templates/vue/src/test/javascript/e2e/page-objects/navbar-page.ts.ejs
Following changes from Cypress
---
> [vue] Fix admin routes in Protractor tests for Vue applications

- generators/client/templates/react/src/main/webapp/app/shared/util/entity-utils.ts.ejs
The comment field has a typo and this confused me. Just correcting the typo to make it easier to understand what the method is supposed to do.
---
> Fix typo in method description in entity-utils.ts.ejs

- generators/generator-base-blueprint.js
- package.json
- test/client.spec.js
- test/entity.spec.js
- Remove .only and add --forbid-only to npm test.
---
> Make blueprintConfig a storage proxy to match jhipsterConfig.

- generators/server/templates/src/main/java/package/web/rest/UserResource.java.ejs
- generators/server/templates/src/test/java/package/web/rest/UserResourceIT.java.ejs
> [v6] Avoid password and resetKey column to be sorted by the /users API

- package-lock.json
- package.json
> Bump prettier-java-plugin and yeoman-generator.

- .github/workflows/angular.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
- generators/client/templates/angular/package.json.ejs
- test-integration/scripts/00-init-env.sh
- test-integration/scripts/12-generate-project.sh
- Compare generated source.
---
> Detect generated source changes.

- generators/server/templates/build.gradle.ejs
- generators/server/templates/gradle.properties.ejs
- generators/server/templates/pom.xml.ejs
> Remove properties migrator runtime dependency to resolve lib conflicts

- .github/workflows/angular.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
> Adjusts to compare jobs.

- .github/workflows/angular.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
> Skip tests if generated sources didn't changed.

- .github/workflows/webflux.yml
- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
- generators/generator-base.js
- generators/server/files.js
- generators/server/templates/build.gradle.ejs
- generators/server/templates/src/main/java/package/config/DatabaseConfiguration.java.ejs
- generators/server/templates/src/test/java/package/ReactiveSqlTestContainerExtension.java.ejs
- generators/server/templates/src/test/java/package/security/DomainUserDetailsServiceIT.java.ejs
- generators/server/templates/src/test/java/package/service/MailServiceIT.java.ejs
- generators/server/templates/src/test/java/package/service/UserServiceIT.java.ejs
- generators/server/templates/src/test/java/package/web/rest/AccountResourceIT.java.ejs
- generators/server/templates/src/test/java/package/web/rest/LogoutResourceIT.java.ejs
- generators/server/templates/src/test/java/package/web/rest/UserResourceIT.java.ejs
and add converter from BitSet to Boolean which is needed by the MariaDB driver
---
> [webflux] Enable testcontainer support for MariaDB too

- generators/cypress/templates/src/test/javascript/cypress/integration/account/login-page.spec.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/integration/account/password-page.spec.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/integration/account/register-page.spec.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/integration/account/reset-password-page.spec.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/integration/account/settings-page.spec.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/integration/administration/administration.spec.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/support/index.ts.ejs
- generators/entity-client/templates/common/src/test/javascript/cypress/integration/entity/entity.spec.ts.ejs
> [webflux] Fix cypress tests session mode

- test-integration/samples/app-sample-dev/.yo-rc.json
- test-integration/samples/ms-micro-consul/.yo-rc.json
- test-integration/samples/ms-micro-eureka/.yo-rc.json
- test-integration/samples/ms-ngx-gateway-consul/.yo-rc.json
- test-integration/samples/ngx-couchbase-search/.yo-rc.json
- test-integration/samples/ngx-couchbase/.yo-rc.json
- test-integration/samples/ngx-neo4j/.yo-rc.json
- test-integration/samples/webflux-couchbase/.yo-rc.json
- test-integration/samples/webflux-gateway-jwt/.yo-rc.json
- test-integration/samples/webflux-mongodb/.yo-rc.json
- test-integration/samples/webflux-psql/.yo-rc.json
- test/integration-test-reproducibility.spec.js
> Make webflux test samples reproducible.

- generators/app/index.js
- generators/client/index.js
- generators/common/index.js
- generators/cypress/index.js
- generators/entity-client/index.js
- generators/entity-i18n/index.js
- generators/entity-server/index.js
- generators/entity/index.js
- generators/generator-base-blueprint.js
- generators/generator-base-private.js
- generators/generator-base.js
- generators/languages/index.js
- generators/server/index.js
- test/blueprint/client-blueprint.spec.js
- test/generator-base-blueprint.spec.js
- test/generator-base.spec.js
Fixes https://github.com/jhipster/generator-jhipster/issues/12338.
---
> Implement custom priorities.

- generators/app/index.js
> Change git priorities.

- cli/import-jdl.js
- test/cli/import-jdl.spec.js
Fixes https://github.com/jhipster/generator-jhipster/issues/12378.
---
> Rename shouldTriggerInstall and cleanup.

- .github/workflows/angular.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
> Tests should be always triggered for push events.

- cli/cli.js
- cli/environment-builder.js
- cli/utils.js
- test/cli/cli.spec.js
- test/templates/blueprint-cli-shared/cli/commands.js
- test/templates/blueprint-cli-shared/generators/bar/index.js
- test/templates/blueprint-cli/cli/commands.js
Closes https://github.com/jhipster/generator-jhipster/issues/11939.
---
> Load blueprints options.

- cli/cli.js
- test/cli/jdl.js
Related to https://github.com/jhipster/generator-jhipster/issues/11896
- Register common options.
- Use an existing option on test.
---
> Fixes for disabling allow unknown option.

- generators/client/templates/angular/package.json.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/logs/logs.component.ts.ejs
Upgrade **Typescript 4** compatible with **Angular 10.1.0**
---
> [angular] Upgrade Typescript 4

- generators/client/templates/angular/package.json.ejs
- generators/client/templates/react/package.json.ejs
- generators/client/templates/vue/package.json.ejs
Upgrade **Cypress** 5.0.0 -> 5.1.0
---
> Cypress 5.0.0 -> 5.1.0

- .github/MAINTAINERS_REPLY_TEMPLATES/README.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- generators/client/templates/react/src/main/webapp/app/modules/home/home.tsx.ejs
> Documentation: Replace Github by GitHub

- generators/client/templates/angular/package.json.ejs
- test-integration/scripts/23-package.sh
Fixes https://github.com/jhipster/generator-jhipster/issues/11766.
Requires https://github.com/jhipster/ng-jhipster/pull/132.
---
> [angular] Fix protractor waiting for timeout with angular.

- generators/client/templates/angular/package.json.ejs
- test-integration/scripts/23-package.sh
> [v6] Fix protractor waiting for timeout with angular.

- .github/dependabot.yml
- .github/workflows/angular.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- generators/client/index.js
- generators/client/templates/angular/package.json
- generators/client/templates/angular/package.json.ejs
- generators/client/templates/common/package.json
- generators/client/templates/react/package.json
- generators/client/templates/react/package.json.ejs
- generators/client/templates/vue/package.json
- generators/client/templates/vue/package.json.ejs
- generators/generator-base.js
- test/client.spec.js
Closes https://github.com/jhipster/generator-jhipster/issues/12413. 
---
> Initial implementation of dependabot on generated package.json.

- generators/client/templates/angular/package.json.ejs
Update **Angular** version 10.1.0 -> 10.1.1
Commands :
```
ng update
ng update @angular/core
``` 
---
> [angular] Update Angular version 10.1.0 -> 10.1.1

- generators/client/templates/react/package.json
- generators/client/templates/react/package.json.ejs
- generators/client/templates/react/src/main/webapp/app/config/notification-middleware.ts.ejs
Upgrade **Typescript 4** for **React**
---
> [react] Upgrade Typescript 4

- cli/cli.js
- cli/utils.js
- package-lock.json
- package.json
- test/cli/cli-utils.spec.js
- test/cli/cli.spec.js
Closes https://github.com/jhipster/generator-jhipster/issues/11896
---
> Disable allow unknown option.

- cli/cli.js
- cli/utils.js
- package-lock.json
- package.json
- test/cli/cli-utils.spec.js
- test/cli/cli.spec.js
Reverts jhipster/generator-jhipster#12392
> Revert "Disable allow unknown option."

- generators/database-changelog-liquibase/index.js
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.ts.ejs
- generators/entity/index.js
- generators/entity/prompts.js
- generators/generator-base-private.js
- generators/generator-base.js
- generators/server/files.js
- utils/entity.js
- utils/relationship.js
Fixes https://github.com/jhipster/generator-jhipster/issues/12433
---
> Improve relationship other side lookup and fixes to skipUserManagement.

- generators/openapi-client/prompts.js
> Replace sync request with async request.

- generators/server/templates/src/test/java/package/web/rest/UserJWTControllerIT.java.ejs
> import removed

- generators/client/templates/react/src/main/webapp/app/modules/home/home.tsx.ejs
> Fix logo placement on left for React applications issue #12458

- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity-update.component.ts.ejs
Removed unused validators imports
> fix https://github.com/jhipster/generator-jhipster/issues/12471

- generators/server/files.js
- generators/server/templates/src/main/resources/banner-vue.txt
fix https://github.com/jhipster/generator-jhipster/issues/12449
> 12449 Add vue banner

- generators/server/templates/src/test/java/package/web/rest/AccountResourceIT.java.ejs
> Java: clean AccountResourceIT

- generators/client/files-vue.js
- generators/client/templates/vue/src/main/webapp/app/admin/user-management/user-management-edit.component.ts.ejs
- generators/client/templates/vue/src/main/webapp/app/admin/user-management/user-management.component.ts.ejs
- generators/client/templates/vue/src/test/javascript/e2e/modules/account/account.spec.ts.ejs
- generators/client/templates/vue/src/test/javascript/e2e/page-objects/alert-page.ts.ejs
- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity-update.component.ts.ejs
- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity.component.ts.ejs
- generators/entity-client/templates/vue/src/test/javascript/e2e/entities/entity.spec.ts.ejs
Following https://github.com/jhipster/generator-jhipster/pull/12508 to fix https://github.com/jhipster/generator-jhipster/issues/12450 by @fdaudies during JHipster Code
It's for fixing Protractor tests
--- …
> [vue] fix protractor tests with toast

- generators/client/templates/angular/src/main/webapp/content/scss/global.scss.ejs
> [angular] improve view entities

- generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
- generators/entity-server/templates/src/main/java/package/service/dto/EntityDTO.java.ejs
- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
- generators/server/templates/src/main/java/package/domain/User.java.ejs
- generators/server/templates/src/main/java/package/security/DomainUserDetailsService.java.ejs
- generators/server/templates/src/main/java/package/service/UserService.java.ejs
- generators/server/templates/src/main/java/package/service/dto/UserDTO.java.ejs
- generators/server/templates/src/main/java/package/web/rest/UserJWTController.java.ejs
- generators/server/templates/src/main/java/package/web/rest/vm/LoginVM.java.ejs
- generators/server/templates/src/test/java/package/web/rest/AccountResourceIT.java.ejs
- generators/server/templates/src/test/java/package/web/rest/UserResourceIT.java.ejs
> Fix name convention

- README.md
> Add Rajbet bronze sponsor

- jdl/converters/jdl-to-json/jdl-to-json-relationship-converter.js
- test/jdl/converters/JDLToJSON/jdl-to-json-relationship-converter.spec.js
- test/jdl/converters/JDLToJSON/jdl-with-applications-to-json-converter.spec.js
- test/jdl/converters/JDLToJSON/jdl-without-application-to-json-converter.spec.js
- test/jdl/jdl-importer.spec.js
> [jdl] Export otherEntityField for every relationship.

- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.ts.ejs
Fix [#12468](https://github.com/jhipster/generator-jhipster/issues/12468)
> fix unused Validators import in entity management update component

- generators/client/templates/vue/src/main/webapp/app/admin/configuration/configuration.vue.ejs
- generators/client/templates/vue/src/main/webapp/app/admin/health/health-modal.vue.ejs
- generators/client/templates/vue/src/main/webapp/app/admin/health/health.vue.ejs
- generators/client/templates/vue/src/main/webapp/app/admin/logs/logs.vue.ejs
- generators/client/templates/vue/src/main/webapp/app/admin/metrics/metrics-modal.vue.ejs
- generators/client/templates/vue/src/main/webapp/app/admin/metrics/metrics.vue.ejs
- generators/client/templates/vue/src/main/webapp/app/admin/user-management/user-management.vue.ejs
- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity.vue.ejs
> replace table caption by aria-describedby

- generators/client/templates/angular/package.json.ejs
- generators/client/templates/react/package.json.ejs
- generators/client/templates/vue/package.json.ejs
- test-integration/scripts/24-tests-e2e.sh
> npm run e2e now opens cypress menu instead of running headless

- generators/docker-compose/files.js
Following https://github.com/jhipster/generator-jhipster/pull/12438
---
> Fix docker-compose 3.8 for Kafka, Keycloak, Consul

- generators/server/templates/src/main/java/package/web/rest/errors/ExceptionTranslator.java.ejs
- generators/server/templates/src/test/java/package/RedisTestContainerExtension.java.ejs
- package-lock.json
- package.json
> maintenance to master: v6.10.3 release commit

- jdl/converters/jdl-to-json/jdl-to-json-relationship-converter.js
- test/jdl/converters/JDLToJSON/jdl-to-json-relationship-converter.spec.js
- test/jdl/converters/JDLToJSON/jdl-with-applications-to-json-converter.spec.js
- test/jdl/converters/JDLToJSON/jdl-without-application-to-json-converter.spec.js
Related to https://github.com/jhipster/generator-jhipster/pull/12551.
---
> [jdl] Export otherEntityField for every relationship (to side).

- generators/client/templates/angular/package.json
- generators/client/templates/angular/package.json.ejs
- Conditional dependencies are kept out due to test coverage maybe missing.
---
> Move angular dependencies from package.json.ejs to package.json for dependabot.

- generators/languages/templates/src/main/webapp/i18n/zh-tw/user-management.json
> Translate refreshListLabel into Chinese.

- generators/entity-i18n/templates/i18n/entity_pt-br.json.ejs
> Fix(lang): pt-BR

- generators/server/files.js
- generators/server/templates/src/test/java/package/security/oauth2/AuthorizationHeaderUtilTest.java.ejs
> Add unit tests for AuthorizationHeaderUtil

- package.json
- test/app/incremental-changelog.spec.js
- test/cli/cli.spec.js
- test/cli/import-jdl.spec.js
- test/utils/utils.js
> Fixes to running mocha in parallel.

- utils/entity.js
Fixes https://github.com/jhipster/generator-jhipster/issues/12554
---
> Use defaults at prepareEntityForTemplates.

- generators/client/templates/angular/src/main/webapp/swagger-ui/index.html.ejs
- generators/client/templates/react/src/main/webapp/swagger-ui/index.html.ejs
- generators/client/templates/vue/src/main/webapp/swagger-ui/index.html.ejs
To be able to execute directly Swagger request, I automatically click all try it out buttons. 
Fix #12464
---
-   [ x ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ x ] Tests are added where necessary
-   [ x ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ x ] Documentation is added/updated where necessary
-   [ x ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed …
> Automatically click all try it out buttons

- generators/server/templates/gradle.properties.ejs
- generators/server/templates/pom.xml.ejs
> Update mapstruct version to 1.4.0.Final

- generators/entity-client/templates/common/src/main/webapp/app/entities/enumerations/enum.model.ts.ejs
> Remove const from enums making them useful at runtime

- .github/dependabot.yml
> Add client common to dependabot.

- generators/server/templates/src/main/java/package/config/UaaConfiguration.java.ejs
- generators/server/templates/src/test/java/package/security/SecurityUtilsUnitTest.java.ejs
- generators/server/templates/src/test/java/package/web/rest/LogoutResourceIT.java.ejs
Replace literal strings with AuthoritiesConstants.
---
> Use AuthoritiesConstants instead of literal strings

- generators/entity-i18n/templates/i18n/entity_pt-br.json.ejs
- generators/languages/templates/src/main/webapp/i18n/pt-br/user-management.json
> Improve pt-br translation.

- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.html.ejs
After https://github.com/jhipster/generator-jhipster/pull/12615, enums aren't nullable at angular.
--- …
> [angular] Fix enum not nullable.

- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.html.ejs
> Fix UI for checkbox (Angular)

- generators/entity-server/templates/src/test/gatling/user-files/simulations/EntityGatlingTest.scala.ejs
> Replace hard coded server port in gatling simulation files

- generators/entity-client/templates/common/src/test/javascript/cypress/integration/entity/entity.spec.ts.ejs
cc @Hawkurane : it should help to fix jdlms daily builds 
---
> Fix cypress tests for microservices

- generators/client/needle-api/needle-client-angular.js
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-routing.module.ts.ejs
- test/needle-api/needle-client-angular.spec.js
Related to https://github.com/jhipster/generator-jhipster/issues/12640
---
> [angular] Fix routing module with microservice

- .prettierignore
- test-integration/scripts/00-init-env.sh
> Remove last Travis CI marks

- generators/client/templates/angular/src/main/webapp/app/core/auth/auth-jwt.service.ts.ejs
> [Angular] Clear old tokens after successful login

- generators/client/templates/react/package.json.ejs
- test/needle-api/needle-server-liquibase.spec.js
Fix https://github.com/jhipster/generator-jhipster/issues/12593
---
> [v6] Bump @types/enzyme to 3.10.7 for React apps

- generators/generator-constants.js
> Update jib version to 2.6.0

- generators/server/index.js
> Remove console log when generating an app with OAuth 2.0

- .github/workflows/stale.yml
Closes https://github.com/jhipster/generator-jhipster/issues/12694
---
> Implement stale workflow.

- .github/workflows/angular.yml
- .github/workflows/incremental-changelog.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
Closes https://github.com/jhipster/generator-jhipster/issues/12693
---
> Implement github actions caching.

- generators/generator-transforms.js
When prettier fails, print the file.
---
> Print file with prettier error.

- generators/server/templates/gradle.properties.ejs
- generators/server/templates/pom.xml.ejs
> Update mapstruct version to 1.4.1.Final

- generators/entity-server/templates/src/main/java/package/repository/EntityReactiveRepositoryInternalImpl.java.ejs
- generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs
These function is not used by the current code - it was added when reactive sql entities were initially implemented, but they are not needed anymore.
--- …
> [webflux] remove unused functions

- .github/MAINTAINERS_REPLY_TEMPLATES/GUIDELINES_NOT_FOLLOWED.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/angular.yml
- .github/workflows/incremental-changelog.yml
- .github/workflows/react.yml
- .github/workflows/release-drafter.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
- CONTRIBUTING.md
- README.md
- azure-pipelines.yml
- cli/jdl.js
- generators/azure-app-service/templates/github/workflows/azure-app-service.yml.ejs
- generators/azure-spring-cloud/templates/github/workflows/azure-spring-cloud.yml.ejs
- generators/ci-cd/templates/github-ci.yml.ejs
- generators/client/templates/angular/src/main/webapp/index.html.ejs
- generators/client/templates/react/src/main/webapp/index.html.ejs
- generators/client/templates/vue/src/main/webapp/index.html.ejs
- generators/server/templates/src/main/docker/config/git2consul.json.ejs
- generators/server/templates/src/main/resources/config/bootstrap-prod.yml.ejs
- generators/server/templates/src/main/resources/config/bootstrap.yml.ejs
- test-integration/scripts/10-install-jhipster.sh
- test-integration/scripts/25-sonar-analyze.sh
- test/cli/jdl.js
Related to https://github.com/jhipster/generator-jhipster/issues/11935
---
> Change default branch to main

- generators/entity-server/templates/partials/it_patch_update.partial.java.ejs
- generators/entity-server/templates/src/main/java/package/common/patch_template.ejs
- generators/entity-server/templates/src/main/java/package/repository/rowmapper/EntityRowMapper.java.ejs
- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
- generators/generator-base-private.js
- generators/server/templates/src/main/resources/config/application-dev.yml.ejs
- test/generator-base-private.spec.js
This PR tries to fix the reactive microservice example provided by @mraible  in #12640 
Fixed:
updates #12640
--- …
> [webflux] fix compilation errors on tests

- generators/entity-server/index.js
- generators/entity-server/templates/src/main/java/package/repository/EntityReactiveRepositoryInternalImpl.java.ejs
- generators/entity-server/templates/src/main/java/package/repository/rowmapper/EntityRowMapper.java.ejs
- generators/entity/index.js
Fixes https://github.com/jhipster/generator-jhipster/issues/12730
Backend CI is not passing due to partial update return status.
--- …
> Fix webflux compilation.

- generators/server/templates/src/main/java/package/web/rest/errors/ExceptionTranslator.java.ejs
- generators/server/templates/src/test/java/package/web/rest/errors/ExceptionTranslatorIT.java.ejs
> Use default message if not blank

- generators/generator-constants.js
- generators/server/templates/gradle.properties.ejs
- generators/server/templates/pom.xml.ejs
> Update liquibase version to 4.1.1

- generators/generator-base.js
> improve jsdoc - fix param name, types, and missing params

- generators/generator-constants.js
> Update jacoco version to 0.8.6

- generators/generator-base-private.js
- generators/generator-transforms.js
- package-lock.json
- package.json
This PR adds prettier to package.json.
- Adding scripts and dependencies at postWriting makes package.json not ordered, so apply prettier.
- Didn't added as dependency of the generated project, no sure it's worth.
--- …
> Apply prettier to package.json

- generators/client/templates/angular/package.json
Related to https://github.com/jhipster/generator-jhipster/issues/12747.
---
> Downgrade zone.js to fulfill angular peer dependencies.

- package-lock.json
- package.json
> Drop @openapitools/openapi-generator-cli

- generators/client/templates/angular/package.json
- generators/client/templates/angular/package.json.ejs
> Bump codelyzer and tslint for angular

- .github/workflows/angular.yml
- .github/workflows/incremental-changelog.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
- generators/client/templates/angular/package.json.ejs
- generators/client/templates/react/package.json.ejs
- generators/client/templates/vue/package.json.ejs
- test-integration/samples/ms-react-gateway-consul-oauth2/.yo-rc.json
- test-integration/samples/webflux-mariadb-gradle/.yo-rc.json
- webdriver-manager is not used by cypress.
---
> Remove webdriver dependency for cypress.

- generators/client/files-common.js
- generators/client/files-react.js
- generators/client/templates/angular/.eslintrc.json.ejs
- generators/client/templates/angular/package.json.ejs
- generators/client/templates/common/.eslint.common.js.ejs
- generators/client/templates/react/.eslint.react.js.ejs
- generators/client/templates/react/.eslintrc.json.ejs
- generators/client/templates/react/package.json.ejs
- test/utils/expected-files.js
Related to https://github.com/jhipster/generator-jhipster/issues/12747
---
> Drop eslint-config-jhipster dependency.

- azure-pipelines.yml
> Disable e2e at ms-react-gateway-consul-oauth2 test.

- azure-pipelines.yml
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs
> [react] Fix default values in entity form

- .github/workflows/stale.yml
> GitHub Actions: update 'stale' label to 'area: stale' [skip ci]

- Dockerfile
Removing unneeded packages , Using Official  repository for packages
This will help to remove unneeded package from dependency
Signed-off-by: Pratik Raj <rajpratik71@gmail.com>
> chore : limit no. of packages installed

- .github/workflows/angular.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- generators/ci-cd/templates/azure-pipelines.yml.ejs
- generators/ci-cd/templates/circle.yml.ejs
- generators/ci-cd/templates/github-ci.yml.ejs
- generators/ci-cd/templates/travis.yml.ejs
- generators/server/index.js
Related to https://github.com/jhipster/generator-jhipster/issues/12489.
- Not tested
- The missing ci is gitlab, the implementation is quite different.
--- …
> Implement e2e at cicd generator.

- generators/generator-constants.js
- generators/server/templates/gradle.properties.ejs
Updates gradle to 6.7.
See https://gradle.org/releases/
---
> update gradle to latest version 6.7

- generators/server/templates/src/main/java/package/web/rest/errors/ExceptionTranslator.java.ejs
> Exclude translation of DataAccessException when there's no database

- generators/ci-cd/templates/.gitlab-ci.yml.ejs
- generators/client/index.js
- generators/client/templates/angular/package.json.ejs
- generators/client/templates/react/package.json.ejs
- generators/client/templates/vue/package.json.ejs
- generators/server/index.js
Fixes https://github.com/jhipster/generator-jhipster/issues/12805.
---
> Move every npm script with variables to `ci:` prefix

- generators/entities-client/index.js
Closes https://github.com/jhipster/generator-jhipster/issues/12805
---
> Run loadClientConfig at entities generator.

- generators/docker-compose/templates/docker-compose.yml.ejs
- generators/generator-constants.js
Related to https://github.com/jhipster/generator-jhipster/issues/12665
---
> Fix docker compose for JHipster Registry with OAuth2

- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
This adds more consistency between tests, and simplify both ejs templates and mock verification when using Elasticsearch
--- …
> Always use repository to save entity in integration tests

- generators/languages/templates/src/main/webapp/i18n/hi/user-management.json
- generators/languages/templates/src/main/webapp/i18n/mr/user-management.json
Localised a new string (**refresh list**) **user-management.json** that is recently added without translation.
> Localised a string of user-management.json in HIndi(hi) and Marathi(mr)

- generators/client/templates/angular/.eslintrc.json.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/health/health-modal.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management-detail.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/auth.interceptor.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/auth/auth-jwt.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/auth/auth-session.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/auth/state-storage.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/user/user.model.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/layouts/error/error.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/shared/alert/alert-error.component.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/admin/user-management/user-management-detail.component.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/admin/user-management/user-management-update.component.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/core/user/user.service.spec.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-detail.component.ts.ejs
Follow up to work done for #12764
I compared our current config with ESLint and TypeScript ESLint recommended configs and removed our identical config and also fixed some recommended rules.
Below is commit history.
Sort ESLint rules alphabetically for better readability.
In the latest ESLint + TypeScript ESLint is `no-unused-vars` identical to our current config, so deleting unnecessary identical override.
Fix `@typescript-eslint/no-unsafe-return` errors.
Fix `@typescript-eslint/restrict-template-expressions` errors.
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/configs/eslint-recommended.ts and https://github.com/eslint/eslint/blob/master/conf/eslint-recommended.js doesn't contain `no-shadow`, so removing `"no-shadow": "off"`. …
> [angular] Improve linting

- generators/client/index.js
> Fix frontend test executing twice

- generators/client/templates/angular/.eslintrc.json.ejs
- generators/client/templates/react/.eslintrc.json.ejs
> Fix json format in eslintrc

- .github/workflows/angular.yml
- .github/workflows/incremental-changelog.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
- azure-pipelines.yml
- generators/generator-constants.js
> Change generator to use jhipster-bom project

- cli/cli.js
- cli/commands.js
- cli/jhipster-command.js
- generators/generator-base.js
Closes https://github.com/jhipster/generator-jhipster/issues/12876
Related to https://github.com/jhipster/generator-jhipster/issues/11896.
---
When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you …
> Fixes to import-jdl unknown options.

- cli/cli.js
- cli/commands.js
- cli/import-jdl.js
- test/cli/import-jdl.spec.js
> More jdl command with unknown options adjusts.

- generators/generator-base-private.js
- test/enforcements.spec.js
> Remove hard coded in generator-base-private and add tests on it

- generators/docker-compose/files.js
- generators/docker-compose/index.js
- generators/docker-compose/templates/central-server-config/application.yml.ejs
- generators/docker-compose/templates/central-server-config/gateway.yml.ejs
- generators/docker-compose/templates/docker-compose.yml.ejs
- generators/kubernetes-knative/templates/service.yml.ejs
- generators/kubernetes/templates/deployment.yml.ejs
- generators/openshift/templates/deployment.yml.ejs
related to https://github.com/jhipster/generator-jhipster/pull/12880
---
> Remove old values about metrics

- generators/client/templates/angular/src/main/webapp/app/admin/health/health.service.ts.ejs
> [angular] Add livenessState and readinessState to HealthKey type

- generators/client/templates/angular/package.json
> Remove codelyzer from package.json

- generators/entity-server/templates/src/test/java/package/service/dto/EntityDTOTest.java.ejs
- generators/entity-server/templates/src/test/java/package/service/mapper/EntityMapperTest.java.ejs
- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
- generators/server/templates/src/test/java/package/CassandraKeyspaceIT.java.ejs
- generators/server/templates/src/test/java/package/cucumber/CucumberIT.java.ejs
- generators/server/templates/src/test/java/package/gateway/responserewriting/SwaggerBasePathRewritingFilterTest.java.ejs
- generators/server/templates/src/test/java/package/repository/CustomN1qlCouchbaseRepositoryTest.java.ejs
- generators/server/templates/src/test/java/package/security/oauth2/AudienceValidatorTest.java.ejs
- generators/server/templates/src/test/java/package/security/oauth2/AuthorizationHeaderUtilTest.java.ejs
- generators/server/templates/src/test/java/package/security/oauth2/CookieCollectionTest.java.ejs
- generators/server/templates/src/test/java/package/security/oauth2/CookieTokenExtractorTest.java.ejs
- generators/server/templates/src/test/java/package/security/oauth2/OAuth2AuthenticationServiceTest.java.ejs
- generators/server/templates/src/test/java/package/security/oauth2/OAuth2CookieHelperTest.java.ejs
- generators/server/templates/src/test/java/package/web/rest/AccountResourceIT.java.ejs
- generators/server/templates/src/test/java/package/web/rest/LogoutResourceIT.java.ejs
- generators/server/templates/src/test/java/package/web/rest/UserJWTControllerIT.java.ejs
- generators/spring-controller/templates/src/test/java/package/web/rest/ResourceIT.java.ejs
See Sonar rule S5786: https://jira.sonarsource.com/browse/RSPEC-5786
---
> Change visibility of JUnit5 tests from public to package-private

- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.html.ejs
> Fix angular enum with nullable value

- generators/app/index.js
- generators/client/index.js
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/user/user.model.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/admin/user-management/user-management-detail.component.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/admin/user-management/user-management-update.component.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/admin/user-management/user-management.component.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/core/user/user.service.spec.ts.ejs
- generators/client/templates/vue/src/main/webapp/app/admin/user-management/user-management-edit.component.ts.ejs
- generators/client/templates/vue/src/main/webapp/app/admin/user-management/user-management-view.component.ts.ejs
- generators/client/templates/vue/src/main/webapp/app/admin/user-management/user-management.component.ts.ejs
- generators/client/templates/vue/src/main/webapp/app/admin/user-management/user-management.service.ts.ejs
- generators/client/templates/vue/src/test/javascript/spec/app/admin/user-management/user-management-edit.component.spec.ts.ejs
- generators/client/templates/vue/src/test/javascript/spec/app/admin/user-management/user-management-view.component.spec.ts.ejs
- generators/client/templates/vue/src/test/javascript/spec/app/admin/user-management/user-management.component.spec.ts.ejs
- generators/database-changelog-liquibase/index.js
- generators/entities-client/index.js
- generators/entities/index.js
- generators/entity-server/index.js
- generators/entity/index.js
- generators/generator-base-private.js
- generators/server/index.js
- generators/server/templates/src/main/java/package/domain/User.java.ejs
- generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs
- generators/server/templates/src/main/resources/config/liquibase/changelog/initial_schema.xml.ejs
- utils/entity.js
- utils/relationship.js
- Simplifies future changes to User
- Simplifies relationships with User
- Starts calculating custom primary keys.
This is required for https://github.com/jhipster/generator-jhipster/issues/7112, https://github.com/jhipster/generator-jhipster/issues/12844
Simplifies implementation of https://github.com/jhipster/generator-jhipster/issues/11062, https://github.com/jhipster/generator-jhipster/issues/11760
Related to https://github.com/jhipster/generator-jhipster/issues/12374
---
-   [ …
> Implement a mocked User entity and share it.

- generators/generator-constants.js
> Change version of jhipster bom to 0.2.0-SNAPSHOT

- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.ts.ejs
Fix #12928
Bug was introduced by #12889
---
> [angular] Fix many to many with User

- generators/client/templates/angular/src/main/webapp/app/home/home.component.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/home/home.component.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/layouts/navbar/navbar.component.spec.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/login/login.component.spec.ts.ejs
> [angular] Polish imports

- generators/client/templates/angular/src/main/webapp/app/login/login.component.html.ejs
> [angular] Tune login page responsiveness

- generators/database-changelog-liquibase/index.js
- generators/database-changelog/index.js
- generators/entity-client/index.js
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-detail.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.html.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-detail.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs
- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity-details.vue.ejs
- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity-update.component.ts.ejs
- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity-update.vue.ejs
- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity.vue.ejs
- generators/entity-server/files.js
- generators/entity-server/index.js
- generators/entity-server/templates/src/main/java/package/common/field_validators.ejs
- generators/entity-server/templates/src/main/java/package/common/save_template.ejs
- generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
- generators/entity-server/templates/src/main/java/package/service/dto/EntityDTO.java.ejs
- generators/entity-server/templates/src/main/java/package/service/mapper/EntityMapper.java.ejs
- generators/entity-server/templates/src/test/java/package/service/mapper/EntityMapperTest.java.ejs
- generators/entity/index.js
- generators/generator-base-private.js
- generators/server/templates/src/main/java/package/service/mapper/UserMapper.java.ejs
- test/generator-base-private.spec.js
- utils/entity.js
- utils/field.js
- utils/index.js
- utils/relationship.js
Based on @yelhouti dto proposal.
Closes https://github.com/jhipster/generator-jhipster/issues/12707.
Related to https://github.com/jhipster/generator-jhipster/issues/7112.
---
When you are still working on the PR, consider converting it to Draft (bellow reviewers) …
> Refactor dto to be unflatten.

- generators/generator-base-private.js
- generators/utils.js
> Call destinationPath to customize webpack path

- generators/client/files-angular.js
- generators/client/templates/angular/src/main/webapp/app/core/core.module.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/interceptor/index.ts.ejs
- test/utils/expected-files.js
Barrels are not promoted by Angular Documentation, but exists one place where this is suggested: put interceptors to barrel in https://angular.io/guide/http
So this PR introduces barrel for interceptors - this makes `core.module` smaller and better readable.  
Polished also imports order in `core.module`.
--- …
> [angular] Use barrel for interceptors

- jdl/validators/application-validator.js
- test/jdl/validators/application-validator.spec.js
> JDL: throw an error when uaaBaseName isn't present for uaa apps

- generators/client/templates/angular/.eslintrc.json.ejs
- generators/client/templates/angular/package.json
- generators/client/templates/angular/package.json.ejs
Removed also rules from `.eslintrc.json` which are already in `@angular-eslint/recommended` - https://github.com/angular-eslint/angular-eslint/blob/master/packages/eslint-plugin/src/configs/recommended.json.
Upgraded also `@angular-eslint` version.
Follow up to issue #12764 and PR #12835
---
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CON …
> [angular] Use @angular-eslint/recommended

- generators/entity-client/index.js
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-detail.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.html.ejs
- generators/entity-client/templates/angular/src/test/javascript/e2e/entities/entity.spec.ts.ejs
- generators/entity-client/templates/angular/src/test/javascript/spec/app/entities/entity-management.service.spec.ts.ejs
- generators/entity-client/templates/common/src/test/javascript/cypress/integration/entity/entity.spec.ts.ejs
- generators/generator-base-private.js
> Implement custom ids on angular.

- generators/generator-constants.js
> [v6] - upgrade jhipster lib to 3.9.1

- cli/jdl.js
Fixes https://github.com/jhipster/generator-jhipster/issues/12808.
---
> Change jdl command to use main branch.

- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.html.ejs
- generators/generator-base-private.js
- utils/relationship.js
Fixes https://github.com/jhipster/generator-jhipster/issues/12962
---
> [angular] Fix relationship reference.

- generators/ci-cd/templates/azure-pipelines.yml.ejs
- generators/ci-cd/templates/circle.yml.ejs
- generators/ci-cd/templates/github-ci.yml.ejs
- generators/ci-cd/templates/travis.yml.ejs
Related with #12489 
cc @mshima
---
> Fix CI:e2e test generator

- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-detail.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-routing.module.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.html.ejs
- generators/entity-client/templates/angular/src/test/javascript/e2e/entities/entity.spec.ts.ejs
- generators/entity/index.js
- generators/generator-base-private.js
- utils/entity.js
- utils/field.js
- utils/relationship.js
- Revert translation to global one.
- Hide input when null.
---
> [angular] Adjusts to built-in id.

- generators/server/templates/src/test/java/package/web/rest/AccountResourceIT.java.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/12817
---
> Fix tests for AccountResourceIT with Redis

- README.md
> V6 - Update README [skip ci]

- cli/cli.js
- cli/commands.js
- cli/download.js
- cli/import-jdl.js
- cli/jdl.js
- cli/jhipster-command.js
- cli/program.js
- cli/utils.js
- generators/app/index.js
- generators/entities/index.js
- generators/entity/USAGE
- test/cli/cli-utils.spec.js
- test/cli/cli.spec.js
- test/cli/import-jdl.spec.js
- test/cli/jdl-fork.spec.js
- test/cli/jdl.js
- test/cli/program.spec.js
Closes https://github.com/jhipster/generator-jhipster/issues/11896.
---
> Refactor cli.

- generators/generator-constants.js
> Update bom version to 7.0.0-SNAPSHOT

- generators/database-changelog-liquibase/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs
- generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
- generators/server/templates/src/main/java/package/domain/User.java.ejs
- generators/server/templates/src/main/resources/config/liquibase/changelog/initial_schema.xml.ejs
- generators/server/templates/src/test/java/package/repository/timezone/DateTimeWrapper.java.ejs
since sequences are supported since MariaDB 10.3
Fixes #12981
---
> Use Hibernate SEQUENCE strategy with MariaDB

- generators/generator-defaults.js
Following @Tcharl's PR and this comment https://github.com/jhipster/generator-jhipster/pull/12749#discussion_r519429737
Thanks @mshima for the suggestion
I'm going to merge this as soon as the CI is green
--- …
> Fix npm test related to localeId

- generators/client/templates/react/package.json.ejs
- generators/client/templates/react/src/test/javascript/jest.conf.js.ejs
Upgrade `ts-jest`  to latest version. 
---
-   [x] Tests are added where necessary - NA
> Chore[React]: upgrade ts-jest dependency 

- generators/app/index.js
- generators/generator-base-private.js
- generators/generator-base.js
- test-integration/samples/jdl-default/app.jdl
- test/generator-base.spec.js
- utils/db.js
Fixes https://github.com/jhipster/generator-jhipster/issues/11025
---
> Change relationship table name.

- generators/entity-server/templates/partials/it_patch_update.partial.java.ejs
- generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
- generators/entity-server/templates/src/main/java/package/repository/EntityRepository.java.ejs
- generators/entity-server/templates/src/main/java/package/repository/EntityRepository_reactive.java.ejs
- generators/entity-server/templates/src/main/java/package/service/EntityService.java.ejs
- generators/entity-server/templates/src/main/java/package/service/dto/EntityDTO.java.ejs
- generators/entity-server/templates/src/main/java/package/service/impl/EntityServiceImpl.java.ejs
- generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs
- generators/entity-server/templates/src/main/resources/config/cql/changelog/added_entity.cql.ejs
- generators/entity-server/templates/src/test/java/package/domain/EntityTest.java.ejs
- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
Replacing logic on database types by logic on primaryKey types + a few changes that I had in a branch locally and forgot to push 
--- …
> Minor improvements on entity templates

- generators/client/templates/react/package.json.ejs
Updates few dependencies for react application
> chore[react]: update dependencies (minor)

- generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
> Update backReference at fluent and setter.

- generators/app/prompts.js
- generators/server/prompts.js
> Questions reordering

- .github/workflows/angular.yml
- .github/workflows/generator.yml
- .github/workflows/incremental-changelog.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
- Dockerfile
- azure-pipelines.yml
- generators/generator-constants.js
fix https://github.com/jhipster/generator-jhipster/issues/12877
---
> Upgrade to Node 14.15.0 LTS

- .github/workflows/webflux.yml
Our default database is Postgresql now, we should use the complete test at postgres.
---
> [webflux] Change sqlfull from MariaDB to Postgresql

- jdl/parsing/api.js
- test/jdl/grammar/validator.spec.js
- test/jdl/jdl-importer.spec.js
> Improved error messages when encountering invalid tokens

- generators/client/files-react.js
- generators/client/templates/react/src/main/webapp/app/modules/home/home.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/login/login-redirect.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/routes.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/shared/auth/private-route.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/shared/util/url-utils.ts.ejs
> Login redirect doesn't work in OAuth2 and React

- .github/workflows/webflux.yml
Reverts jhipster/generator-jhipster#13031
Postgres test with sqlfull is broken. Reverting.
> Revert "[webflux] Change sqlfull from MariaDB to Postgresql"

- generators/app/index.js
- generators/generator-base.js
- generators/generator-defaults.js
- generators/languages/index.js
- generators/languages/prompts.js
- test/languages.spec.js
- test/needle-api/needle-client.spec.js
Fixes https://github.com/jhipster/generator-jhipster/issues/13025.
---
> Fix nativeLanguage not been generated using prompts.

- generators/languages/prompts.js
Related to https://github.com/jhipster/generator-jhipster/issues/13025
---
> Generate only the native language when using prompt.

- generators/client/templates/react/src/main/webapp/app/shared/layout/menus/admin.tsx.ejs
Do not force the width to 140%.
Let it auto.
**Before**
**After**
> fix: width in admin menu

- generators/app/index.js
- generators/app/prompts.js
- generators/generator-base.js
- generators/generator-defaults.js
- generators/server/prompts.js
- Move reactive prompt to server generator.
- Fix regeneration with skipServer option.
Related to https://github.com/jhipster/generator-jhipster/issues/13055
--- …
> Fixes related to skipServer option

- generators/entity-server/templates/src/main/resources/config/liquibase/fake-data/table.csv.ejs
> fix entity with field account not working

- .github/workflows/webflux.yml
Related to https://github.com/jhipster/generator-jhipster/pull/12736 and https://github.com/jhipster/generator-jhipster/issues/13072
--- …
> [webflux] Disable webflux-mariadb-gradle test.

- generators/common/templates/README.md.ejs
> [angular] Update Angular README

- generators/client/templates/angular/tsconfig.json.ejs
> [angular] Add comment why need skipLibCheck if using Protractor

- generators/client/templates/angular/src/main/webapp/app/core/event-manager/event-manager.service.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/core/event-manager/event-manager.service.spec.ts.ejs
> [angular] Add multiple subscription feature to event manager

- generators/entity/index.js
- generators/entity/prompts.js
- generators/generator-base.js
- generators/generator-transforms.js
- test/blueprint/client-blueprint-custom-path.spec.js
- test/blueprint/client-blueprint.spec.js
- test/blueprint/sbs-blueprint.spec.js
- test/blueprint/server-blueprint.spec.js
- test/blueprint/spring-controller-blueprint.spec.js
- test/blueprint/spring-service-blueprint.spec.js
- test/needle-api/needle-client-angular.spec.js
- test/needle-api/needle-client-vue.spec.js
- test/needle-api/needle-server-cache.spec.js
- test/needle-api/needle-server-gradle.spec.js
- test/needle-api/needle-server-liquibase.spec.js
- test/needle-api/needle-server-logback-spring.spec.js
- test/needle-api/needle-server-maven.spec.js
- test/templates/fake-blueprint/generators/server/index.js
- Remove 'changelogDate is missing in ' log on a new entity.
- Remove setup*Options.
- Improve prettierTransform error handling.
--- …
> Cleanups an improvements.

- generators/client/templates/angular/angular.json.ejs
> The order of global and vendor scss files is incorrect in angular.json

- generators/cleanup.js
> [angular] Fix csrf.service cleanup

- generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics-cache/metrics-cache.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics-datasource/metrics-datasource.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics-endpoints-requests/metrics-endpoints-requests.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics-garbagecollector/metrics-garbagecollector.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics-modal-threads/metrics-modal-threads.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics-request/metrics-request.component.html.ejs
- generators/server/templates/src/main/java/package/service/mapper/UserMapper.java.ejs
> [Sonar] Fix some code smells

- generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics-cache/metrics-cache.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics-datasource/metrics-datasource.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics-endpoints-requests/metrics-endpoints-requests.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics-garbagecollector/metrics-garbagecollector.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics-modal-threads/metrics-modal-threads.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics-request/metrics-request.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics.component.html.ejs
End of #13109 
cc @kaidohallik 
---
> [angular] Sonar: add IDs for aria-describedby

- generators/client/templates/angular/src/main/webapp/app/core/util/data-util.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/index.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-detail.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-detail.component.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.ts.ejs
- generators/entity-client/templates/angular/src/test/javascript/spec/app/entities/entity-management-detail.component.spec.ts.ejs
While reviewing #13110 found some Sonar code smells in Angular part which this PR fixes:
* parameters with default values should be last
* remove commented out code (as service worker is managed by Angular CLI after #10624 then this comment was outdated and could remove)
---
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) …
> [angular] Fix some sonar issues

- README.md
Following https://github.com/hipster-labs/jhipster-daily-builds/pull/75
> Daily builds: add SQL in builds name [ci skip]

- cli/cli.js
> Add logger at unhandled rejection.

- generators/client/templates/vue/src/test/javascript/spec/app/account/account.service.spec.ts.ejs
- generators/client/templates/vue/src/test/javascript/spec/app/account/activate/activate.component.spec.ts.ejs
- generators/client/templates/vue/src/test/javascript/spec/app/account/change-password/change-password.component.spec.ts.ejs
- generators/client/templates/vue/src/test/javascript/spec/app/account/login-form/login-form.component.spec.ts.ejs
- generators/client/templates/vue/src/test/javascript/spec/app/account/login.service.spec.ts.ejs
- generators/client/templates/vue/src/test/javascript/spec/app/account/register/register.component.spec.ts.ejs
- generators/client/templates/vue/src/test/javascript/spec/app/account/reset-password/finish/reset-password-finish.component.spec.ts.ejs
- generators/client/templates/vue/src/test/javascript/spec/app/account/reset-password/init/reset-password-init.component.spec.ts.ejs
- generators/client/templates/vue/src/test/javascript/spec/app/account/sessions/sessions.component.spec.ts.ejs
- generators/client/templates/vue/src/test/javascript/spec/app/account/settings/settings.component.spec.ts.ejs
- generators/client/templates/vue/src/test/javascript/spec/app/admin/configuration/configuration.component.spec.ts.ejs
- generators/client/templates/vue/src/test/javascript/spec/app/admin/health/health.component.spec.ts.ejs
- generators/client/templates/vue/src/test/javascript/spec/app/admin/logs/logs.component.spec.ts.ejs
- generators/client/templates/vue/src/test/javascript/spec/app/admin/metrics/metrics.component.spec.ts.ejs
- generators/client/templates/vue/src/test/javascript/spec/app/admin/tracker/tracker.component.spec.ts.ejs
- generators/client/templates/vue/src/test/javascript/spec/app/admin/user-management/user-management-edit.component.spec.ts.ejs
- generators/client/templates/vue/src/test/javascript/spec/app/admin/user-management/user-management-view.component.spec.ts.ejs
- generators/client/templates/vue/src/test/javascript/spec/app/admin/user-management/user-management.component.spec.ts.ejs
- generators/entity-client/templates/vue/src/test/javascript/spec/app/entities/entity.service.spec.ts.ejs
> stub axios with sinon

- generators/generator-constants.js
> Update NPM version to 6.14.9

- generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
Fixes https://github.com/jhipster/generator-jhipster/issues/13142
---
> Fix name conflict

- generators/client/templates/angular/.eslintrc.json.ejs
- generators/client/templates/angular/src/main/webapp/app/account/password/password-strength-bar.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/docs/docs.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/metrics/blocks/metrics-request/metrics-request.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/home/home.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/layouts/navbar/navbar.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/layouts/profiles/page-ribbon.component.ts.ejs
> [angular] Use linting rule @angular-eslint/relative-url-prefix

- jdl/converters/parsed-jdl-to-jdl-object/parsed-jdl-to-jdl-object-converter.js
- test/jdl/converters/parsedJDLToJDLObject/parsed-jdl-to-jdl-object-converter.spec.js
- test/utils-entity.spec.js
- utils/entity.js
- Adopt field with id name as `@Id`
--- …
> [jdl] Don't ignore fields with id name.

- generators/client/templates/angular/src/main/webapp/app/core/auth/user-route-access.service.ts.ejs
> [angular] Simplify UserRouteAccessService

- generators/client/templates/react/src/main/webapp/app/shared/util/entity-utils.ts.ejs
- generators/client/templates/react/src/test/javascript/spec/app/shared/util/entity-utils.spec.ts.ejs
> Fix: Can't save 2 entities consecutively (React + manytomany)

- generators/app/index.js
- generators/app/prompts.js
> Fix application base name question in Windows Command Prompt

- generators/openshift/templates/deployment.yml.ejs
- generators/openshift/templates/registry/jhipster-registry.yml.ejs
bug fixes for issue #13183 and #13184
> bug fixes for the yml file templates used by openshift sub-generator

- generators/database-changelog-liquibase/index.js
- generators/entity/index.js
- generators/generator-base-private.js
- test/liquibase-utils.spec.js
- utils/entity.js
- utils/field.js
- utils/index.js
- utils/liquibase.js
- utils/relationship.js
> Extract prepareFieldForLiquibaseTemplates and improvements to primaryKey.

- generators/cleanup.js
Instead of removing folders, remove just files in `core` and `shared`, because those folders can be used by users, 2 commits:
* `core`, changes https://github.com/jhipster/generator-jhipster/commit/d8ca06d214c3535d6c9f4a0e94d9547488109319 cleanup
* `shared`, changes https://github.com/jhipster/generator-jhipster/commit/5ae25531dddc31aa4c8a005aef5d968481408894 cleanup
--- …
> [angular] Improve cleanup

- generators/client/templates/angular/package.json
Reverts jhipster/generator-jhipster#13239
> Revert "chore(deps-dev): bump copy-webpack-plugin from 6.4.0 to 7.0.0 in /generators/client/templates/angular"

- generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.html.ejs
> [angular] Remove double empty line from entity update html

- generators/ci-cd/templates/circle.yml.ejs
> CI-CD: fix CircleCI build

- generators/ci-cd/templates/azure-pipelines.yml.ejs
> CI-CD: use Ubuntu 20.04 for Azure Pipelines

- generators/ci-cd/prompts.js
- generators/ci-cd/templates/.gitlab-ci.yml.ejs
- generators/ci-cd/templates/azure-pipelines.yml.ejs
- generators/ci-cd/templates/circle.yml.ejs
- generators/ci-cd/templates/github-actions.yml.ejs
- generators/ci-cd/templates/jenkins/Jenkinsfile.ejs
- generators/ci-cd/templates/travis.yml.ejs
- test/ci-cd.spec.js
Related to https://github.com/jhipster/generator-jhipster/issues/12441
---
> Snyk support

- .github/workflows/angular.yml
- .github/workflows/incremental-changelog.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
- azure-pipelines.yml
See https://github.com/actions/virtual-environments/issues/1499#issuecomment-689467080
---
> Configured maven to avoid Connection Reset issues

- generators/client/templates/angular/package.json
- generators/client/templates/angular/package.json.ejs
- generators/client/templates/common/package.json
- generators/client/templates/react/package.json
- generators/client/templates/react/package.json.ejs
- generators/client/templates/vue/package.json
- generators/client/templates/vue/package.json.ejs
Each framework can have it's own typescript dependency.
---
> Move typescript from common to framework package.json.

- generators/openshift/templates/deployment.yml.ejs
fix for the yaml template of openshift sub-generator.
> bug fix for #13281 and #13282

- generators/database-changelog-liquibase/index.js
- generators/database-changelog-liquibase/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs
- generators/database-changelog-liquibase/templates/src/main/resources/config/liquibase/changelog/added_entity_constraints.xml.ejs
- generators/database-changelog-liquibase/templates/src/main/resources/config/liquibase/changelog/updated_entity.xml.ejs
- generators/database-changelog-liquibase/templates/src/main/resources/config/liquibase/changelog/updated_entity_constraints.xml.ejs
- generators/database-changelog-liquibase/templates/src/main/resources/config/liquibase/changelog/updated_entity_migrate.xml.ejs
- generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
- generators/entity-server/templates/src/main/java/package/repository/EntityRepositoryInternalImpl_reactive.java.ejs
- generators/entity-server/templates/src/main/java/package/repository/EntityRepository_reactive.java.ejs
- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
- generators/entity/index.js
- test-integration/samples/jdl-entities/custom-id.jdl
- utils/entity.js
- utils/relationship.js
Allows relationships with entities with custom ids and add tests.
--- …
> Fixes for relationships with custom ids.

- generators/entity-client/templates/angular/src/main/webapp/app/entities/route/entity-management-routing.module.ts.ejs
Follow up to #13318 - fixes bug it introduced.
---
> [angular] Fix routing module name in microservices

- generators/generator-constants.js
> Update NPM version to 6.14.10

- generators/server/templates/src/test/java/package/web/rest/PublicUserResourceIT.java.ejs
following https://github.com/jhipster/generator-jhipster/pull/13048
---
> Use IntegrationTest in PublicUserResource

- generators/client/templates/vue/src/main/webapp/app/admin/user-management/user-management.service.ts.ejs
- generators/client/templates/vue/src/test/javascript/spec/app/admin/user-management/user-management-edit.component.spec.ts.ejs
- generators/client/templates/vue/src/test/javascript/spec/app/admin/user-management/user-management-view.component.spec.ts.ejs
- generators/client/templates/vue/src/test/javascript/spec/app/admin/user-management/user-management.component.spec.ts.ejs
> Fix users API for Vue applications

- generators/app/index.js
- generators/generator-base.js
- test/vue.spec.js
Another fix prettifying vue.
See https://github.com/jhipster/generator-jhipster/pull/13327#issuecomment-748442442.
--- …
> Fix first run of prettier with vue client.

- .github/workflows/angular.yml
- .github/workflows/incremental-changelog.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
- azure-pipelines.yml
- generators/generator-constants.js
The release is available at https://repo.maven.apache.org/maven2/tech/jhipster/jhipster-parent/
--- …
> Upgrade jhipster lib 7.0.0 beta.0

- generators/client/templates/react/package.json.ejs
> Upgrade react-jhipster to 0.12.0

- test/blueprint/app-blueprint.spec.js
- test/templates/blueprints/generator-jhipster-prettier-transform/package.json
- test/upgrade.spec.js
- Bump test version dependencies.
- Disable test that depends on a not compatible released blueprint.
--- …
> Fix npm test

- generators/server/templates/src/main/java/package/service/dto/UserDTO.java.ejs
- generators/server/templates/src/main/java/package/web/rest/PublicUserResource.java.ejs
- generators/server/templates/src/test/java/package/web/rest/PublicUserResourceIT.java.ejs
> Use https in license header

- generators/cleanup.js
- generators/entity-client/index.js
For example if user decides to keep audit module then without this change new releases until final 7.0.0 will delete again those kept files.
---
When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you …
> Avoid deleting again in cleanup

- generators/app/index.js
- generators/generator-base-private.js
- generators/generator-base.js
- generators/server/templates/src/main/java/package/domain/User.java.ejs
- generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs
- generators/server/templates/src/main/java/package/service/dto/AdminUserDTO.java.ejs
- generators/server/templates/src/main/java/package/service/dto/UserDTO.java.ejs
- generators/server/templates/src/main/java/package/service/mapper/UserMapper.java.ejs
- generators/server/templates/src/main/resources/config/liquibase/changelog/initial_schema.xml.ejs
- generators/server/templates/src/main/resources/config/liquibase/data/user.csv.ejs
- generators/server/templates/src/main/resources/config/liquibase/data/user_authority.csv.ejs
- generators/server/templates/src/test/java/package/service/mapper/UserMapperTest.java.ejs
- generators/server/templates/src/test/java/package/web/rest/UserResourceIT.java.ejs
- test-integration/samples/.gitignore
- test-integration/samples/jdl-entities/user-relationships/entities.jdl
- utils/field.js
Add support to use a primary key type globally.
Related to https://github.com/jhipster/generator-jhipster/issues/13278.
--- …
> Add support to --pk-type

- cli/jhipster-command.js
- cli/program.js
- package-lock.json
- package.json
> Bump commander to 7.0.0-2

- .github/workflows/angular.yml
- .github/workflows/incremental-changelog.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
- azure-pipelines.yml
- generators/generator-constants.js
> Use jhipster lib master 7.0.0-SNAPSHOT

- generators/client/templates/angular/src/main/webapp/app/admin/logs/logs.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.html.ejs
Current style is to use type-safe equality and non-null assertion for `editForm.get` where possible. This PR aligns code to this style.
--- …
> [angular] Use type-safe equality operator and non-null assertion

- generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs
The method findAll(Pageable pageable) is unnecessary because the PagingAndSortingRepository interface already has it
--- …
> Remove unnecessary method

- generators/entity-client/templates/vue/src/test/javascript/e2e/entities/entity.spec.ts.ejs
Fixes https://github.com/jhipster/generator-jhipster/pull/13347#issuecomment-750065962.
---
> Fix vue protractor e2e.

- generators/app/index.js
- generators/aws-containers/index.js
- generators/aws/index.js
- generators/azure-app-service/index.js
- generators/azure-spring-cloud/index.js
- generators/ci-cd/index.js
- generators/cloudfoundry/index.js
- generators/docker-compose/index.js
- generators/entity/index.js
- generators/gae/index.js
- generators/generator-base-docker.js
- generators/generator-base-private.js
- generators/generator-base.js
- generators/heroku/index.js
- generators/openapi-client/index.js
- generators/server/index.js
- package-lock.json
- package.json
- test/client.spec.js
- test/languages.spec.js
- test/needle-api/needle-client-angular.spec.js
- test/needle-api/needle-client-vue.spec.js
- test/needle-api/needle-client.spec.js
- test/needle-api/needle-server-cache.spec.js
Fix some transforms not been applied at some generators like entity.
Fixes https://github.com/jhipster/generator-jhipster/issues/13308
--- …
> Register transformers at generator-base instead of at each generator.

- generators/entity-server/templates/src/main/java/package/common/get_all_stream_template.ejs
- generators/entity-server/templates/src/main/java/package/common/get_filtered_template.ejs
- generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
- generators/entity-server/templates/src/main/java/package/domain/relationship_validators.ejs
- generators/entity-server/templates/src/main/java/package/repository/EntityRepository.java.ejs
- generators/entity-server/templates/src/main/java/package/repository/EntityRepository_reactive.java.ejs
- generators/entity-server/templates/src/main/java/package/service/EntityService.java.ejs
- generators/entity-server/templates/src/main/java/package/service/dto/EntityCriteria.java.ejs
- generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs
- generators/entity-server/templates/src/main/resources/config/cql/changelog/added_entity.cql.ejs
Simplifies fields/relationships filtering by id and others attributes.
---
> Change from 'idx in' to 'item of' for fields and relationships at server templates.

- generators/entity-client/templates/angular/src/main/webapp/app/entities/detail/entity-management-detail.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/service/entity.service.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.ts.ejs
- generators/entity-client/templates/angular/src/test/javascript/e2e/entities/entity.spec.ts.ejs
Simplifies fields/relationships filtering by id and others attributes.
---
> Change from 'idx in' to 'item of' for fields and relationships at angular templates.

- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity.vue.ejs
> Update i18n key Refresh list

- generators/client/templates/angular/src/main/webapp/app/admin/user-management/list/user-management.component.html.ejs
Screenshot for the same is available in #13316
---
> Fix typo for 'Refresh' in User listing page [angular]

- generators/server/templates/src/main/java/package/config/WebConfigurer.java.ejs
- generators/server/templates/src/test/java/package/security/jwt/TokenProviderTest.java.ejs
[Fix some code smells](https://sonarcloud.io/project/issues?id=jhipster-sample-application&resolved=false&types=CODE_SMELL)
--- …
> Fix Sonar code smells

- generators/entity-server/templates/src/main/java/package/service/impl/EntityServiceImpl.java.ejs
> Typo update [skip ci]

- generators/generator-constants.js
- generators/server/templates/gradle.properties.ejs
- generators/server/templates/pom.xml.ejs
* Updates gradle to 6.7.1
* Updates the gradle node plugin to the latest RC which I use for ~2 month in another project without any problems
* Updates archunit to 0.15.0
---
When you are still working on the PR, consider converting it to Draft (bellow reviewers) …
> update gradle to 6.7.1, gradle node plugin to latest RC

- generators/generator-base.js
- generators/generator-defaults.js
- jdl/jhipster/default-application-options.js
> Wrong config for microservices in .yo-rc.json

- generators/ci-cd/templates/.gitlab-ci.yml.ejs
- generators/ci-cd/templates/jenkins/Jenkinsfile.ejs
- generators/client/index.js
- generators/client/templates/angular/package.json.ejs
- generators/client/templates/angular/src/main/webapp/content/scss/vendor.scss.ejs
- generators/client/templates/angular/src/main/webapp/index.html.ejs
- generators/client/templates/react/package.json.ejs
- generators/client/templates/react/src/main/webapp/index.html.ejs
- generators/client/templates/vue/package.json.ejs
- generators/client/templates/vue/src/main/webapp/content/css/vendor.css.ejs
- generators/client/templates/vue/src/main/webapp/content/scss/vendor.scss.ejs
- generators/client/templates/vue/src/main/webapp/index.html.ejs
- generators/common/templates/README.md.ejs
- generators/generator-base-private.js
- generators/server/index.js
- generators/server/templates/gradle/profile_dev.gradle.ejs
- generators/server/templates/gradle/profile_prod.gradle.ejs
- generators/server/templates/pom.xml.ejs
- test-integration/scripts/21-tests-backend.sh
> Server common scripts

- generators/entity-client/templates/angular/src/main/webapp/app/entities/detail/entity-management-detail.component.html.ejs
Use similar HTML tags to ensure similar look if HTML elements CSS is changed.
---
> [angular] Polish entity detail view

- generators/client/templates/angular/tsconfig.json.ejs
- generators/client/templates/angular/tsconfig.spec.json.ejs
Among other things fixes wrong tests folder (tests are now next to the files they test).
---
> [angular] Sync tsconfig files with ones generated by Angular CLI

- generators/server/templates/src/main/resources/config/application-dev.yml.ejs
- generators/server/templates/src/main/resources/config/application-prod.yml.ejs
- generators/server/templates/src/main/resources/config/application-tls.yml.ejs
- generators/server/templates/src/main/resources/config/application.yml.ejs
- generators/server/templates/src/main/resources/config/bootstrap-prod.yml.ejs
- generators/server/templates/src/main/resources/config/bootstrap.yml.ejs
`.yml` files are formatted by Prettier with `tabWith=2`, using the same `tabWidth` also in templates.
In some places in template already was `tabWidth=2` used, now it's everywhere so.
Commented out sections are now with correct spacing after generation.
Fixed some odd number of spaces to correct ones.
Added one missing license header.
--- …
> Polish app config spacing

- generators/client/templates/angular/package.json.ejs
> [angular] Update Protractor related and Node types dependencies

- generators/server/templates/src/main/java/package/gateway/responserewriting/SwaggerBasePathRewritingFilter.java.ejs
- generators/server/templates/src/test/java/package/gateway/responserewriting/SwaggerBasePathRewritingFilterTest.java.ejs
> Broken Swagger with Microservices

- generators/client/templates/vue/src/main/webapp/app/main.ts.ejs
- generators/server/templates/src/main/resources/config/liquibase/changelog/initial_schema.xml.ejs
- generators/server/templates/src/main/resources/config/liquibase/master.xml.ejs
> Fix indentation in templates

- generators/kubernetes/templates/deployment.yml.ejs
> Generate proper R2DBC configuration for Reactive apps running in Kubernetes

- generators/client/templates/vue/package.json.ejs
- generators/client/templates/vue/webpack/webpack.prod.js.ejs
> [Vue] Add workbox webpack plugin to add service worker

- generators/client/files-vue.js
- generators/client/templates/vue/src/main/webapp/app/entities/user/user.oauth2.service.ts.ejs
- generators/client/templates/vue/src/main/webapp/app/main.ts.ejs
- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity-update.component.ts.ejs
- generators/entity-client/templates/vue/src/test/javascript/spec/app/entities/entity-update.component.spec.ts.ejs
> Creating a Vue app with a relationship to Users fails to display users

- generators/entity-server/templates/src/main/java/package/common/field_validators.ejs
- generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
- generators/entity-server/templates/src/main/java/package/service/dto/EntityDTO.java.ejs
- generators/server/templates/src/test/java/package/web/rest/errors/ExceptionTranslatorTestController.java.ejs
The solution is from https://stackoverflow.com/a/65432593/65681. Fixes #13479. 
---
> Fix reactive tests by assigning @NotNull a default message

- generators/client/templates/vue/src/main/webapp/app/account/login-form/login-form.component.ts.ejs
Similar to https://github.com/jhipster/generator-jhipster/issues/12147 and https://github.com/jhipster/generator-jhipster/pull/12610 but for Vue
--- …
> Vue: clean old token at successful login

- generators/server/templates/src/test/java/package/security/oauth2/CustomClaimConverterIT.java.ejs
Fix https://github.com/jhipster/generator-jhipster/pull/13462#issuecomment-759315014
---
> Remove Transactional when using no db

- generators/client/templates/vue/src/test/javascript/spec/app/account/login.service.spec.ts.ejs
Not sure why these are in my fork and not in the main repo. Creating PR to add them for Vue. 
---
> [Vue] Add tests

- generators/client/templates/vue/src/test/javascript/spec/app/account/login.service.spec.ts.ejs
- generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
- generators/entity-server/templates/src/main/java/package/repository/rowmapper/EntityRowMapper.java.ejs
- generators/server/templates/src/main/java/package/repository/rowmapper/UserRowMapper.java.ejs
More fixes for R2DBC with OAuth.
---
> [WebFlux] Fix R2DBC with OAuth

- generators/entity-server/templates/src/main/java/package/common/get_all_template.ejs
- generators/entity-server/templates/src/main/java/package/repository/EntityRepository.java.ejs
- generators/entity-server/templates/src/main/java/package/service/mapper/EntityMapper.java.ejs
- utils/relationship.js
> Minor fixes.

- generators/docker-base.js
- generators/docker-compose/index.js
- generators/docker-utils.js
- generators/kubernetes-helm/index.js
- generators/kubernetes-knative/index.js
- generators/kubernetes/index.js
- generators/openshift/index.js
Fixes first item of https://github.com/jhipster/generator-jhipster/issues/13477.
---
> Don't override warning from generator.

- generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs
Fix [code smell](https://sonarcloud.io/project/issues?id=jhipster-sample-application&open=AXZmicqdf809r-2l-9Gj&resolved=false)
---
When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see …
> Sonar: unused StreamSupport class

- generators/client/templates/angular/src/main/webapp/index.html.ejs
- generators/client/templates/react/src/main/webapp/index.html.ejs
- generators/client/templates/vue/src/main/webapp/index.html.ejs
After these changes, the following JDL looks pretty good!
```
application {
config {
applicationType monolith,
baseName HealthPoints
packageName com.okta.developer,
authenticationType oauth2,
prodDatabaseType postgresql,
buildTool gradle,
searchEngine elasticsearch,
testFrameworks [protractor],
enableTranslation true,
nativeLanguage en,
languages [en, es]
}
entities Points, BloodPressure, Weight, Preferences 
}
// JDL definition for application 'TwentyOnePoints' generated with command 'jhipster export-jdl'
entity BloodPressure {
timestamp ZonedDateTime required
systolic Integer required
diastolic Integer required
}
entity Weight {
timestamp ZonedDateTime required
weight Double required
}
entity Points {
date LocalDate required
exercise Integer
meals Integer
alcohol Integer
notes String …
```
> PWA Polishing

- .github/dependabot.yml
> Customize dependabot labels

- generators/client/templates/vue/package.json
- generators/client/templates/vue/package.json.ejs
- Group protractor dependency.
- Remove optional (not tested) dependency from dependabot.
---
> Improvements to vue package.json

- generators/generator-constants.js
- generators/server/templates/pom.xml.ejs
> Update spring-boot version to 2.3.8.RELEASE and other dependencies

- generators/heroku/index.js
- generators/heroku/templates/application-heroku.yml.ejs
Remove mLabs MongoDB and graphene neo4j addons as they don't exist anymore.
closes #13424
[ci-skip] [skip-ci]
---
When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result …
> remove mlabs and graphene addons from heroku configuration

- generators/client/templates/react/package.json
> Upgrade react-jhipster to 0.13.0

- .github/workflows/angular.yml
- .github/workflows/incremental-changelog.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
- azure-pipelines.yml
- generators/generator-constants.js
> Upgrade jhipster lib 7.0.0 beta.1

- generators/generator-constants.js
Just that, updating to gradle 6.8.
https://docs.gradle.org/6.8/release-notes.html
---
> update gradle to 6.8

- generators/client/templates/react/package.json
Fixes https://github.com/jhipster/generator-jhipster/security/dependabot/generators/client/templates/react/package.json/lodash/open
> Upgrade lodash to fix security vulnerability

- generators/generator-constants.js
> Upgrade jhipster registry v6.6.0 jhipster control center v0.3.0

- generators/client/templates/vue/package.json
- generators/client/templates/vue/package.json.ejs
> [Vue] Upgrade webpack-cli

- generators/client/templates/angular/package.json
- generators/client/templates/angular/package.json.ejs
Fixes https://github.com/jhipster/generator-jhipster/issues/13526.
---
> [angular] Make @types/node managed by dependabot.

- generators/entity/index.js
- utils/relationship.js
Fixes incremental changelog
Fix for https://github.com/jhipster/generator-jhipster/pull/13496
---
> Don't add removed relationships to differentTypes and differentRelationships

- generators/server/templates/src/main/java/package/service/UserService.java.ejs
close https://github.com/jhipster/generator-jhipster/issues/13441
---
> Sync activated field according to the email_verified value

- generators/client/templates/react/package.json
- generators/client/templates/react/src/main/webapp/app/modules/login/login-modal.tsx.ejs
> Bump reactstrap to 8.9.0

- generators/client/templates/angular/package.json.ejs
> [angular] Update WebSocket dependencies

- generators/client/templates/angular/package.json
> Bump zone.js from 0.10.3 to 0.11.3

- generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.ts.ejs
- generators/generator-base-private.js
> Remove redundant method toArrayString

- generators/client/templates/angular/.eslintrc.json.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/list/pagination-template.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.ts.ejs
Also changed recently added method `loadRelationshipsOptions` in entity update from `public` to `private` (follow up to #13496).
--- …
> [angular] Check field and method order with lint

- generators/client/templates/angular/angular.json.ejs
> angular: add robots.txt to assets

- generators/entity-client/templates/angular/src/main/webapp/app/entities/route/entity-management-routing-resolve.service.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/service/entity.service.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.ts.ejs
Make all private providers and methods to protected and export declared types to allow to use those in side by side approach.
---
> [angular] Improve entities SBS support

- generators/server/templates/src/test/java/package/config/WebConfigurerTest.java.ejs
Minor changes. It's to avoid:
---
> Sonar: Web Configurer Test

- .editorconfig
> Align EditorConfig with Prettier

- generators/entity-server/files.js
- generators/entity-server/templates/src/test/java/package/domain/EntityTest.java.ejs
When generating an application with entitySuffix property, the generated test files are not correct:
```
➜ jhjdl jdl/beer.jdl
INFO! Using JHipster version installed globally
INFO! Executing import-jdl jdl/beer.jdl
INFO! The JDL is being parsed.
INFO! Found entities: Beer.
INFO! The JDL has been successfully parsed
INFO! Generating 0 applications.
INFO! Generating 1 entity.
INFO! Generating entities for application undefined in a new parallel process
Found the /home/pgrimaud/projects/app/.jhipster/Beer.json configuration file, entity can be automatically generated!
info Creating changelog for entities Beer
create src/test/gatling/user-files/simulations/BeerGatlingTest.scala
create src/main/resources/config/liquibase/changelog/20210122125559_added_entity_Beer.xml
create …
```
> Fix entity suffix for Entity Test file

- generators/app/index.js
- generators/generator-base.js
Related to https://github.com/jhipster/generator-jhipster/issues/13642.
---
> Add --client-package-manager option

- generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.spec.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.ts.ejs
As component internal methods should not be public then changing to protected.
---
> [angular] Make entity list component sort() method protected

- .github/workflows/incremental-changelog.yml
- cli/import-jdl.js
- generators/app/index.js
- generators/database-changelog-liquibase/index.js
- generators/database-changelog-liquibase/templates/src/main/resources/config/liquibase/fake-data/table_entity.csv.ejs
- generators/generator-base.js
- test/cli/import-jdl.spec.js
Fixes https://github.com/jhipster/generator-jhipster/issues/13688
---
> Fix csv data for incremental changelog

- .github/workflows/angular.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
> Fix diff with npm 7

- .editorconfig
- generators/aws-containers/templates/bootstrap-aws.yml.ejs
- generators/azure-app-service/templates/application-azure.yml.ejs
- generators/azure-spring-cloud/templates/application-azure.yml.ejs
- generators/azure-spring-cloud/templates/bootstrap-azure.yml.ejs
- generators/cloudfoundry/templates/application-cloudfoundry.yml.ejs
- generators/cypress/templates/src/test/javascript/cypress/fixtures/users/user.json.ejs
- generators/database-changelog-liquibase/templates/src/main/resources/config/liquibase/fake-data/table_entity.csv.ejs
- generators/docker-compose/templates/alertmanager-conf/config.yml.ejs
- generators/docker-compose/templates/central-server-config/application.yml.ejs
- generators/docker-compose/templates/docker-compose.yml.ejs
- generators/entity-server/templates/src/main/java/package/common/field_validators.ejs
- generators/entity-server/templates/src/main/java/package/domain/relationship_validators.ejs
- generators/gae/templates/application-prod-gae.yml.ejs
- generators/gae/templates/dispatch.yaml.ejs
- generators/heroku/templates/application-heroku.yml.ejs
- generators/heroku/templates/bootstrap-heroku.yml.ejs
- generators/page/templates/vue/src/main/webapp/app/pages/page.service.ts.ejs
- generators/page/templates/vue/src/main/webapp/app/pages/page.vue.ejs
Polish templates spacing in 11 subfolders of generators. Separate commits for each subfolder.
Still 6 folders need `tabWidth` polishing after this PR:
* ci-cd
* client
* entity-client
* entity-i18n
* kubernetes
* languages
---
> Polish spacing in templates

- .github/workflows/angular.yml
- .github/workflows/incremental-changelog.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
- azure-pipelines.yml
- generators/generator-constants.js
> Change version jhipster bom to 7.0.0 snapshot after 7.0.0 beta.1

- generators/client/templates/angular/src/test/javascript/e2e/admin/administration.spec.ts.ejs
- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
> Try to fix Protractor e2e

- generators/generator-base-private.js
- generators/generator-base.js
- generators/generator-transforms.js
- test/app.spec.js
Related to https://github.com/jhipster/generator-jhipster/issues/13691.
---
> Add option to disable prettier and use it in app tests.

- generators/client/files-angular.js
- generators/client/files-common.js
- generators/client/files-react.js
- generators/client/files-vue.js
- generators/client/index.js
- generators/common/files.js
- generators/common/index.js
- generators/cypress/files.js
- generators/database-changelog-liquibase/index.js
- generators/entity-client/files.js
- generators/entity-client/index.js
- generators/entity-server/files.js
- generators/entity-server/index.js
- generators/generator-base-private.js
- generators/generator-base.js
- generators/page/files-vue.js
- generators/page/index.js
- generators/server/files.js
- generators/utils.js
- test/generator-base.spec.js
- test/needle-api/needle-server-liquibase.spec.js
> Promisify writeFilesToDisk and move needles to postWriting.

- generators/client/templates/angular/package.json.ejs
- generators/client/templates/react/package.json.ejs
- generators/client/templates/vue/package.json.ejs
- generators/server/templates/package.json.ejs
> Add prettier:check

- README.md
Following https://github.com/hipster-labs/jhipster-daily-builds/pull/85, the badges need to be updated too
cc @mraible 
---
> Update badges [skip ci]

- generators/common/templates/sonar-project.properties.ejs
> update sonar rule links

- generators/generator-constants.js
- generators/server/templates/build.gradle.ejs
- generators/server/templates/gradle.properties.ejs
- generators/server/templates/settings.gradle.ejs
This PR 
* updates gradle wrapper to 6.8.1
* remove no needed plugins (apt)
* update node plugin to rc7
* fix npm version definition for node plugin
* cleanup repositories
closes #13593
closes #13746
---
> update gradle build configuration

- generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
- generators/entity-server/templates/src/main/java/package/repository/EntityRepository.java.ejs
- generators/entity-server/templates/src/main/java/package/repository/EntityRepository_reactive.java.ejs
- generators/server/templates/build.gradle.ejs
- generators/server/templates/pom.xml.ejs
- generators/server/templates/src/main/java/package/config/DatabaseConfiguration_neo4j.java.ejs
- generators/server/templates/src/main/java/package/domain/AbstractAuditingEntity.java.ejs
- generators/server/templates/src/main/java/package/domain/Authority.java.ejs
- generators/server/templates/src/main/java/package/domain/PersistentToken.java.ejs
- generators/server/templates/src/main/java/package/domain/User.java.ejs
- generators/server/templates/src/main/java/package/repository/AuthorityRepository.java.ejs
- generators/server/templates/src/main/java/package/repository/PersistentTokenRepository.java.ejs
- generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs
This is the rebased version of https://github.com/jhipster/generator-jhipster/pull/13161.  I am not exactly sure everything is as intended (somehow the changes seem so small compared to the original PR). Will try to test further later today.
---
> Rework for neo4j and boot 2.4

- generators/server/templates/build.gradle.ejs
Should fix this failure:
https://github.com/hipster-labs/jhipster-daily-builds/runs/1795057754?check_suite_focus=true
> Fix comment in build.gradle

- jdl/jhipster/application-options.js
> jdl: Support svelte as client framework

- generators/database-changelog-liquibase/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs
- generators/database-changelog-liquibase/templates/src/main/resources/config/liquibase/changelog/added_entity_constraints.xml.ejs
- generators/database-changelog-liquibase/templates/src/main/resources/config/liquibase/changelog/updated_entity_constraints.xml.ejs
- generators/database-changelog-liquibase/templates/src/main/resources/config/liquibase/fake-data/table_entity.csv.ejs
- generators/entity-client/templates/angular/src/test/javascript/e2e/entities/entity.spec.ts.ejs
- generators/entity-client/templates/common/src/test/javascript/cypress/integration/entity/entity.spec.ts.ejs
- generators/entity-client/templates/react/src/test/javascript/e2e/entities/entity.spec.ts.ejs
- generators/entity-client/templates/vue/src/test/javascript/e2e/entities/entity.spec.ts.ejs
- generators/entity-server/index.js
- generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
- generators/entity/index.js
- generators/entity/prompts.js
- test-integration/samples/.jhipster/MapsIdChildEntityWithDTO.json
- test-integration/samples/.jhipster/MapsIdChildEntityWithoutDTO.json
- test-integration/samples/.jhipster/MapsIdUserProfileWithDTO.json
- utils/entity.js
> Replace useJPADerivedIdentifier with id

- generators/client/files-angular.js
- generators/client/templates/angular/src/main/webapp/app/core/util/operators.spec.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/util/operators.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/entities/user/user.service.spec.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/entities/user/user.service.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity.model.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/service/entity.service.spec.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/service/entity.service.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.spec.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.ts.ejs
- generators/generator-base-private.js
- test/utils/expected-files.js
- utils/entity.js
- utils/field.js
Fixes https://github.com/jhipster/generator-jhipster/issues/13510
---
> [angular] Fix empty selects when the current value is not returned from the server.

- generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.spec.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.ts.ejs
Follow up to #13592
Tried to split different changes into different commits.
Made also `updateForm` protected.
---
> [angular] Polish angular entity update test

- generators/entity/index.js
- utils/relationship.js
When it's used for specific use cases like incremental changelog.
---
> Function prepare*ForTemplates should not change entity.

- generators/server/templates/gradle.properties.ejs
- generators/server/templates/pom.xml.ejs
> Update mapstruct version to 1.4.2.Final

- generators/generator-base.js
> Allow some options to set empty values.

- .github/workflows/angular.yml
ngx-default test is too big split additional features into a separated test.
---
> Split ngx-default test.

- generators/client/templates/common/package.json
> Update Cypress to the 6.4.0 version

- generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.spec.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.ts.ejs
> Change subscribeToSaveResponse to use finally for cleaning isSaving.

- .github/workflows/angular.yml
- .github/workflows/generator.yml
- .github/workflows/incremental-changelog.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
- generators/generator-constants.js
> Update NPM version to 7.5.2

- generators/common/templates/README.md.ejs
> Display Angular CLI link only for Angular app

- generators/server/templates/src/test/java/package/security/SecurityUtilsUnitTest.java.ejs
> Rename variable in Security Utils Unit Test

- generators/common/templates/editorconfig.ejs
> Add vue in editorconfig

- generators/server/templates/src/main/java/package/security/oauth2/CustomClaimConverter.java.ejs
> Fix Sonar Analysis for initializing HttpHeaders

- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-delete-dialog.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-detail.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-reducer.spec.ts.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.model.ts.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs
- generators/generator-base-private.js
> [react] Enable use of custom id fields for react - not 100% finished

- generators/entity-server/templates/src/main/java/package/service/dto/EntityCriteria.java.ejs
> Fix toString in Criteria, as it is ignored by prettier [ci skip]

- generators/generator-transforms.js
> Add Generated annotation to Enum

- azure-pipelines.yml
Simplify the installation of Chrome for Azure pipeline.
See also #13837
---
> Simplify Chrome installation in Azure pipeline

- generators/kubernetes/templates/db/neo4j.yml.ejs
> Fix Neo4j Kubernetes YAML file

- generators/entity-i18n/templates/i18n/entity_de.json.ejs
Add missing entity translation for the German language.
---
> Add missing entity translation (de)

- generators/client/templates/angular/src/main/webapp/app/login/login.service.ts.ejs
Remove LOGOUT_URL for session authentication.
---
> [webflux] Fix angular session logout url

- jdl/converters/jdl-to-json/jdl-to-json-relationship-converter.js
> fix case where many to one broke because of missing injected field

- cli/utils.js
> Add Okta message after generation as part of platinum sponsorship

- generators/server/templates/src/main/java/package/config/WebConfigurer.java.ejs
Following https://github.com/jhipster/generator-jhipster/pull/13868
It's for fixing:
```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/pgrimaud/tmp/06-eureka-oauth2-main-full-reactive/crm/src/main/java/io/github/pascalgrimaud/crm/config/WebConfigurer.java:[37,45] cannot find symbol
symbol:   variable JHipsterConstants
location: class io.github.pascalgrimaud.crm.config.WebConfigurer
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] Total …
```
> Fix import for h2 + microservices applications

- generators/server/templates/src/main/java/package/security/oauth2/CustomClaimConverter.java.ejs
> microservice+OAuth2: Prevent NPE when user-info doesn't have 'groups' attribute

- generators/server/templates/src/main/java/package/security/oauth2/CustomClaimConverter.java.ejs
- generators/server/templates/src/test/java/package/security/oauth2/CustomClaimConverterIT.java.ejs
And some cleanup / improvements for CustomClaimConverterIT
---
> Unit test for #13944

- .github/dependabot.yml
- generators/common/templates/package.json
> Downgrade husky due to change of license #13940

- .github/dependabot.yml
> Prettier fix

- generators/server/templates/src/main/java/package/config/DatabaseConfiguration_mongodb.java.ejs
- generators/server/templates/src/main/java/package/config/DatabaseConfiguration_sql.java.ejs
- generators/server/templates/src/main/resources/config/application.yml.ejs
- generators/server/templates/src/test/resources/config/application.yml.ejs
https://www.mongock.io/quick-start#building-and-running-mongock-annotation-vs-builder
It's less verbose, and should ease following mongock versions upgrade.
---
> Mongock: switch to configuration by annotation

- generators/client/templates/angular/.eslintrc.json.ejs
- generators/client/templates/angular/package.json
- generators/client/templates/react/.eslintrc.json.ejs
- generators/client/templates/react/package.json
FIx dependabot:
https://github.com/jhipster/generator-jhipster/pull/14040
https://github.com/jhipster/generator-jhipster/pull/14041 
---
> Fix: upgrade eslint-config-prettier from 7.2.0 to 8.0.0 (Angular, React)

- generators/client/templates/angular/package.json
Reverts jhipster/generator-jhipster#14060
> Revert "chore(deps-dev): bump copy-webpack-plugin from 6.4.1 to 7.0.0 in /generators/client/templates/angular"

- generators/generator-base-private.js
- generators/generator-base.js
- test/app/application-with-entities.js
Related to https://github.com/jhipster/generator-jhipster/issues/13278
---
> Adopt User id field type when present in User.json.

- generators/client/files-angular.js
- generators/client/templates/angular/src/main/webapp/app/core/auth/auth-jwt.service.spec.ts.ejs
- package-lock.json
- test/utils/expected-files.js
I saw that the Auth JWT wasn't tested so I added some unit tests to have it covered to 100% !
---
> [angular] improve auth jwt service test coverage

- .github/workflows/angular.yml
> Disable sonar analyse for ngx-default-additional profile

- generators/client/templates/vue/src/main/webapp/app/router/index.ts.ejs
- generators/client/templates/vue/src/main/webapp/app/shared/config/config.ts.ejs
Fix https://github.com/jhipster/generator-jhipster/pull/14071
---
> [Vue] Fix: bump typescript from 4.1.5 to 4.2.2

- jdl/parsing/validator.js
- test/jdl/grammar/validator.spec.js
Related to https://github.com/jhipster/generator-jhipster/issues?q=gateway+reactive
Following https://github.com/jhipster/generator-jhipster/pull/14013
---
> Fix JDL validator for SpringCloudGateway value

- generators/ci-cd/index.js
> Ability to extend the ci-cd sub-generator in blueprints

- .github/workflows/webflux.yml
> Disable testcontainers for webflux-psql job

- generators/languages/templates/src/main/webapp/i18n/de/global.json.ejs
Add missing translation for German global i18n.
---
> Add missing German translation

- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs
> Fix React + MongoDB

- generators/server/templates/pom.xml.ejs
> Specifies maven "start-class" property in pom.xml

- generators/database-changelog-liquibase/index.js
- generators/database-changelog-liquibase/templates/src/main/resources/config/liquibase/changelog/updated_entity_constraints.xml.ejs
- generators/database-changelog-liquibase/templates/src/main/resources/config/liquibase/fake-data/table_entity.csv.ejs
- generators/generator-base-private.js
- utils/relationship.js
Fixes https://github.com/jhipster/generator-jhipster/issues/14158.
---
> Fix fake data for required unique relationships.

- .github/workflows/angular.yml
- .github/workflows/generator.yml
- .github/workflows/incremental-changelog.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
- generators/generator-constants.js
> Bump npm to 7.6.0

- generators/database-changelog-liquibase/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs
- generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
- generators/entity-server/templates/src/main/java/package/service/dto/EntityDTO.java.ejs
- generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs
- generators/entity-server/templates/src/test/java/package/domain/EntityTest.java.ejs
- generators/entity-server/templates/src/test/java/package/service/dto/EntityDTOTest.java.ejs
- generators/entity-server/templates/src/test/java/package/service/mapper/EntityMapperTest.java.ejs
- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
- generators/entity/index.js
- utils/entity.js
Reduce complexity of UUID import.
---
> Postpone processEntityFields to preparingRelationships so derived fields are available.

- .github/workflows/angular.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
- generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
- generators/server/templates/src/test/resources/config/application.yml.ejs
Depends on https://github.com/jhipster/jhipster-bom/pull/203.
> Upgrade to Mongock 4.3.7

- generators/entity-i18n/templates/i18n/entity_es.json.ejs
- generators/languages/templates/src/main/webapp/i18n/es/global.json.ejs
- generators/languages/templates/src/main/webapp/i18n/es/health.json.ejs
- generators/languages/templates/src/main/webapp/i18n/es/register.json
- generators/languages/templates/src/main/webapp/i18n/es/user-management.json
Update spanish translations
---
> Update es translation

- generators/entity/index.js
- generators/utils.js
Convert files to absolute before read/write.
---
> Don't rely on process.cwd() for absolute path.

- generators/generator-base-private.js
- jdl/jhipster/database-types.js
- jdl/jhipster/field-types.js
The goal of this PR is to reuse constants amongs generated file.
For now, it targets the base private file
---
> use some constant in generator-base-private

- generators/app/index.js
- generators/app/prompts.js
- generators/aws-containers/index.js
- generators/aws-containers/prompts.js
- generators/aws/index.js
- generators/aws/lib/s3.js
- generators/utils.js
- test/blueprint/entity-blueprint.spec.js
- test/blueprint/spring-controller-blueprint.spec.js
Use constants in app generator and aws
---
> fixed some unit tests, use constants in app and aws generators

- generators/entity/prompts.js
- jdl/jhipster/reserved-keywords.js
- jdl/jhipster/reserved-keywords/paging.js
- jdl/validators/jdl-with-application-validator.js
- jdl/validators/jdl-without-application-validator.js
- test/jdl/test-files/realistic_sample.jdl
> Filter out page/sort/size as field names

- generators/bootstrap/index.js
- generators/client/templates/angular/package.json.ejs
- generators/client/templates/react/package.json.ejs
- generators/client/templates/vue/package.json.ejs
- generators/common/index.js
- generators/generator-base-blueprint.js
- generators/generator-base-docker.js
- generators/generator-base-private.js
- generators/generator-base.js
- generators/info/index.js
- generators/page/index.js
- generators/server/templates/package.json.ejs
Partially fixes https://github.com/jhipster/generator-jhipster/issues/14178#issuecomment-792026861.
- package.json: https://github.com/jhipster/generator-jhipster/issues/14178#issuecomment-792079250
- yo-rc.json
- force prettier on unchanged config files.
- related to docker-compose: execute prettier on every '.yo-rc.json' not only current path one.
---
> Fix prettier

- generators/ci-cd/index.js
- generators/database-changelog-liquibase/index.js
- generators/entity/index.js
- generators/generator-base.js
- test/app.spec.js
- test/app/application-with-entities.js
- test/app/composing.js
- test/cli/import-jdl.spec.js
- test/cli/jdl-fork.spec.js
- test/client.spec.js
- test/entity.spec.js
- test/page.spec.js
- test/utils/utils.js
> Tests improvements and cleanup.

- Dockerfile
Fix daily builds with Docker:
- https://github.com/hipster-labs/jhipster-daily-builds/actions/workflows/docker-image.yaml
- stacktrace:
```
internal/modules/cjs/loader.js:883
throw err;
^
Error: Cannot find module 'semver'
Require stack:
- /home/jhipster/generator-jhipster/cli/jhipster.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
at Function.Module._load (internal/modules/cjs/loader.js:725:27)
at Module.require (internal/modules/cjs/loader.js:952:19)
at require (internal/modules/cjs/helpers.js:88:18)
at Object.<anonymous> (/home/jhipster/generator-jhipster/cli/jhipster.js:20:16)
at Module._compile (internal/modules/cjs/loader.js:1063:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
at Module.load …
```
> Fix Docker image with npm install

- Dockerfile
Following https://github.com/jhipster/generator-jhipster/pull/14192.
I don't think dev dependencies are useful here.
---
> Dockerfile: Execute npm ci with --production.

- generators/client/index.js
- generators/cypress/templates/src/test/javascript/cypress/support/entity.ts.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs
Revert #14121
Fix #13989
Fix #14163 
---
> Fix beta issues for React

- generators/server/templates/src/main/docker/jhipster-control-center.yml.ejs
> Improve JHCC docker-compose configuration

- generators/server/templates/src/main/resources/config/application.yml.ejs
> Enable caches and liquibase exposure in management when it makes sense

- generators/docker-compose/templates/docker-compose.yml.ejs
- generators/server/templates/src/main/docker/app.yml.ejs
- generators/server/templates/src/main/docker/consul.yml.ejs
cc @avdev4j : as during your stream, Consul spammed you :)
> Reduce logs in Consul

- generators/generator-constants.js
> Update NPM version to 7.6.2

- .github/workflows/angular.yml
- .github/workflows/incremental-changelog.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
- test-integration/scripts/10-install-jhipster.sh
> Don't fail if install npm target version fails.

- generators/generator-constants.js
> Update NPM version to 7.6.3

- generators/client/templates/angular/src/main/webapp/app/admin/configuration/configuration.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/layouts/navbar/navbar.component.ts.ejs
Fix:
- https://sonarcloud.io/project/issues?id=jhipster-sample-application&open=AXelGvoXagrqeG1fw62M&resolved=false&severities=MAJOR&types=CODE_SMELL
- https://sonarcloud.io/project/issues?id=jhipster-sample-application&open=AXelGviBagrqeG1fw616&resolved=false&severities=MAJOR&types=CODE_SMELL
---
> Sonar: fix code smells

- generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.ts.ejs
Fix:
https://sonarcloud.io/project/issues?id=jhipster-sample-application&open=AXelIeD3r3QB7K3jBmyO&resolved=false&severities=MINOR
---
> Sonar: fix

- generators/client/templates/angular/src/main/webapp/app/account/password/password-strength-bar/password-strength-bar.component.ts.ejs
Fix:
https://sonarcloud.io/project/issues?id=jhipster-sample-application&open=AXZl6J06f809r-2l7_o0&resolved=false&types=CODE_SMELL
---
> Sonar: fix code smell

- .github/workflows/angular.yml
- .github/workflows/generator.yml
- .github/workflows/incremental-changelog.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
- Dockerfile
- azure-pipelines.yml
- generators/generator-constants.js
> Update Nodejs version to 14.16.0

- generators/server/templates/src/main/resources/config/application-dev.yml.ejs
- generators/server/templates/src/main/resources/config/application.yml.ejs
I noticed the issue in the svelte blueprint while consuming APIs using `fetch`.
> Expose success and error alert headers in cors requests

- generators/client/templates/angular/src/main/webapp/app/core/util/event-manager.service.ts.ejs
Fix:
https://sonarcloud.io/project/issues?id=jhipster-sample-application&open=AXelGvowagrqeG1fw62O&resolved=false&severities=MINOR&types=CODE_SMELL
---
> Sonar: fix issue

- generators/entity-client/templates/angular/src/main/webapp/app/entities/service/entity.service.ts.ejs
Fix some code smells:
- https://sonarcloud.io/project/issues?id=jhipster-sample-application&open=AXelIeBpr3QB7K3jBmyI&resolved=false&severities=MINOR&types=CODE_SMELL
- https://sonarcloud.io/project/issues?id=jhipster-sample-application&open=AXelId_5r3QB7K3jBmyD&resolved=false&severities=MINOR&types=CODE_SMELL
- https://sonarcloud.io/project/issues?id=jhipster-sample-application&open=AXelIeR9r3QB7K3jBmyl&resolved=false&severities=MINOR&types=CODE_SMELL
- https://sonarcloud.io/project/issues?id=jhipster-sample-application&open=AXelIeIjr3QB7K3jBmyV&resolved=false&severities=MINOR&types=CODE_SMELL
- https://sonarcloud.io/project/issues?id=jhipster-sample-application&open=AXelIeYYr3QB7K3jBmzA&resolved=false&severities=MINOR&types=CODE_SMELL
- …
> [Angular] Sonar: fix code smells

- generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs
- generators/server/templates/src/main/docker/config/realm-config/jhipster-realm.json.ejs
> Fix groups claim in Keycloak's web_app client

- cli/program.js
- generators/generator-base-blueprint.js
- test/cli/cli.spec.js
- test/templates/fake-blueprint/generators/app/index.js
> Fix loading of blueprint options.

- generators/ci-cd/templates/.gitlab-ci.yml.ejs
- generators/ci-cd/templates/jenkins/Jenkinsfile.ejs
- generators/common/templates/sonar-project.properties.ejs
- generators/server/templates/pom.xml.ejs
> Use default maven properties for jacoco report files

- .github/workflows/angular.yml
- .github/workflows/incremental-changelog.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
- azure-pipelines.yml
- generators/generator-constants.js
Following:
- https://github.com/jhipster/jhipster-bom/releases/tag/7.0.0
- https://repo.maven.apache.org/maven2/tech/jhipster/jhipster-parent/7.0.0/
> Upgrade jhipster lib 7.0.0

- generators/client/templates/react/package.json
- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs
Fix #14390 
cc @pascalgrimaud @gzsombor @deepu105
[cause](https://github.com/jhipster/react-jhipster/commit/1266c1e27dc35e355b5811d6a9506aa37c81bfe3)
---
> [React] Upgrade react-jhipster 0.15.0

- generators/generator-constants.js
- test-integration/scripts/20-docker-compose.sh
Following:
- https://github.com/jhipster/jhipster-registry/releases/tag/v6.7.1
- https://github.com/jhipster/jhipster-control-center/releases/tag/v0.4.1
---
> Upgrade jhipster-registry to v6.7.1

- .github/workflows/angular.yml
- .github/workflows/incremental-changelog.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
- azure-pipelines.yml
- generators/generator-constants.js
> Upgrade jhipster lib to 7.0.1-SNAPSHOT

- generators/client/index.js
Fix https://github.com/jhipster/generator-jhipster/pull/14383#issuecomment-804712773
---
> Fix client generator when User is not available.

- generators/generator-constants.js
> Update NPM version to 7.7.0

- generators/client/templates/vue/src/main/webapp/content/scss/_bootstrap-variables.scss.ejs
- generators/client/templates/vue/src/main/webapp/content/scss/vendor.scss.ejs
> [Vue] Use clientThemeNone

- generators/cloudfoundry/index.js
- generators/cloudfoundry/templates/manifest.yml.ejs
- generators/common/templates/README.md.ejs
- generators/common/templates/sonar-project.properties.ejs
- generators/cypress/files.js
- generators/cypress/templates/cypress.json.ejs
- generators/cypress/templates/src/test/javascript/cypress/integration/account/login-page.spec.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/integration/account/password-page.spec.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/integration/account/register-page.spec.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/integration/account/reset-password-page.spec.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/integration/account/settings-page.spec.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/integration/administration/administration.spec.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/plugins/index.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/support/commands.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/support/index.ts.ejs
- generators/database-changelog-liquibase/index.js
- generators/database-changelog-liquibase/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs
- generators/database-changelog-liquibase/templates/src/main/resources/config/liquibase/changelog/added_entity_constraints.xml.ejs
- generators/database-changelog-liquibase/templates/src/main/resources/config/liquibase/changelog/updated_entity.xml.ejs
- generators/database-changelog-liquibase/templates/src/main/resources/config/liquibase/changelog/updated_entity_constraints.xml.ejs
- generators/database-changelog-liquibase/templates/src/main/resources/config/liquibase/changelog/updated_entity_migrate.xml.ejs
- generators/docker-base.js
- generators/generator-base.js
Contributes to [14235](https://github.com/jhipster/generator-jhipster/issues/14235)
---
> use constants in generator-common and cypress

- generators/generator-constants.js
- generators/server/templates/gradle.properties.ejs
- generators/server/templates/pom.xml.ejs
Related with https://github.com/jhipster/generator-jhipster/issues/14463
---
> Update liquibase version to 4.3.2

- generators/client/templates/vue/webpack/webpack.dev.js.ejs
Fix #14474 (not sure if it is the best solution)
---
> [Vue] npm start doesn't refresh correctly

- generators/client/templates/angular/src/main/webapp/app/layouts/navbar/navbar.component.html.ejs
- generators/client/templates/react/src/main/webapp/app/shared/layout/menus/admin.tsx.ejs
- generators/client/templates/vue/src/main/webapp/app/core/jhi-navbar/jhi-navbar.vue.ejs
- generators/generator-base.js
- generators/server/templates/src/main/java/package/config/WebConfigurer.java.ejs
- generators/server/templates/src/main/resources/config/application-dev.yml.ejs
Workaround undertow by adding a trailing / to h2-console link.
Fixes https://github.com/jhipster/generator-jhipster/issues/14406
---
> Fix h2-console not accessible from menu.

- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs
> [React] Entity listing table has an extra column for id

- generators/server/templates/build.gradle.ejs
- generators/server/templates/pom.xml.ejs
- generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs
- generators/server/templates/src/main/java/package/service/UserService.java.ejs
> fix: retrieve users authorities in user management page (reactive)

- generators/server/templates/src/test/java/package/web/rest/UserResourceIT.java.ejs
added missing tests for #14475 
---
> reactive: improve UserResource tests

- generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs
- generators/server/templates/src/main/java/package/service/UserService.java.ejs
> reactive: fix user edit

- generators/client/needle-api/needle-client-webpack.js
- generators/client/templates/angular/package.json
- generators/client/templates/angular/package.json.ejs
- generators/client/templates/angular/webpack/webpack.custom.js.ejs
- generators/client/templates/react/webpack/webpack.common.js.ejs
- generators/client/templates/vue/webpack/webpack.common.js.ejs
- generators/generator-base.js
- test/needle-api/needle-client-webpack.spec.js
> Add support to webpack config needle

- utils/entity.js
> id other entity field to be able to loop on ids in the frontend

- generators/languages/templates/src/main/webapp/i18n/de/global.json.ejs
Add German translations for missing global values.
---
> Translate new global values (DE)

- test/utils-entity.spec.js
- test/utils-field.spec.js
- utils/entity.js
- utils/field.js
> primaryKey usedRelationships

- .github/workflows/angular.yml
- .github/workflows/incremental-changelog.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
- azure-pipelines.yml
- generators/generator-constants.js
Following:
- https://github.com/jhipster/jhipster-bom/releases/tag/7.0.1
- https://repo.maven.apache.org/maven2/tech/jhipster/jhipster-parent/7.0.1/
---
> Upgrade jhipster lib 7.0.1

- generators/client/templates/angular/src/main/webapp/app/account/sessions/sessions.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/health/modal/health-modal.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/metrics/blocks/metrics-modal-threads/metrics-modal-threads.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/metrics/blocks/metrics-modal-threads/metrics-modal-threads.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/delete/user-management-delete-dialog.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/service/user-management.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/entities/user/user.service.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/delete/entity-management-delete-dialog.component.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/service/entity.service.ts.ejs
For entities use `protected` and for client main files `private` for internal variables as such style is used currently.
---
> [angular] Align modifier style

- generators/server/templates/src/main/java/package/service/mapper/UserMapper.java.ejs
Fix:
https://sonarcloud.io/project/issues?id=jhipster-sample-application&open=AXXcCbOmDYpc0p2-rIVB&resolved=false&types=CODE_SMELL
---
> Sonar - Fix

- generators/cypress/templates/cypress.json.ejs
- generators/cypress/templates/src/test/javascript/cypress/fixtures/users/user.json.ejs
- generators/cypress/templates/src/test/javascript/cypress/integration/account/login-page.spec.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/integration/account/password-page.spec.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/integration/account/register-page.spec.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/integration/account/reset-password-page.spec.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/integration/account/settings-page.spec.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/integration/administration/administration.spec.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/plugins/index.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/support/commands.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/support/entity.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/support/index.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/support/management.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/support/navbar.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/support/oauth2.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/tsconfig.json.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.html.ejs
- generators/entity-client/templates/common/src/test/javascript/cypress/integration/entity/entity.spec.ts.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs
- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity-update.vue.ejs
- Add copyright headers.
- Remove unnecessary page visits
- Be verbose on skipped tests
- Reduces runtime 20-30%
Related to https://github.com/jhipster/generator-jhipster/issues/14441
---
> [cypress] Remove unnecessary page visits and be verbose on skipped tests.

- utils/entity.js
> fix name dotted asserted

- generators/client/templates/angular/src/main/webapp/app/core/auth/account.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/home/home.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/home/home.component.spec.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/home/home.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/layouts/navbar/navbar.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/layouts/navbar/navbar.component.spec.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/layouts/navbar/navbar.component.ts.ejs
Navbar.
In my testing every mouse click or key press called both `isAuthenticated()` and `getImageUrl()` 4-20 times depending on action performed (so 8-40 function calls on every click or key press in any page).
Now performance improved: variables are used which are calculated once on login change only and no more those function calls.
Home.
On every key press or click in home page was `isAuthenticated()` called 2-10 times.
Now those function calls are removed.
---
> [angular] Optimize navbar and home components

- generators/client/templates/react/src/main/webapp/app/modules/administration/administration.reducer.spec.ts.ejs
- generators/client/templates/react/src/main/webapp/app/shared/layout/menus/account.spec.tsx.ejs
> [React] Unused code

- generators/client/templates/vue/src/main/webapp/app/admin/user-management/user-management.component.ts.ejs
> [Vue] Unused code

- utils/entity.js
> Fix Faker reproducibility for entities

- .github/workflows/angular.yml
- .github/workflows/incremental-changelog.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
- generators/azure-app-service/templates/github/workflows/azure-app-service.yml.ejs
- generators/azure-spring-cloud/templates/github/workflows/azure-spring-cloud.yml.ejs
- generators/ci-cd/templates/github-actions.yml.ejs
> Bump actions/setup-java from v1 to v2

- generators/server/templates/src/test/java/package/config/StaticResourcesWebConfigurerTest.java.ejs
> Fix typo in method name.

- generators/client/templates/react/webpack/webpack.common.js.ejs
- generators/client/templates/react/webpack/webpack.dev.js.ejs
- generators/client/templates/react/webpack/webpack.prod.js.ejs
- generators/client/templates/vue/config/dev.env.js.ejs
- generators/client/templates/vue/config/prod.env.js.ejs
- generators/client/templates/vue/webpack/webpack.dev.js.ejs
- generators/client/templates/vue/webpack/webpack.prod.js.ejs
- generators/generator-base.js
Related to https://github.com/jhipster/generator-jhipster/issues/13796
---
> Enable on disk build cache available at webpack 5.

- generators/client/templates/vue/webpack/webpack.dev.js.ejs
> [vue] Readd path to webpack.dev.js

- generators/languages/templates/src/main/webapp/i18n/zh-tw/global.json.ejs
> Add missed translation.

- generators/client/templates/react/src/main/webapp/app/shared/layout/password/password-strength-bar.tsx.ejs
Fix:
Same fix that I did with Angular few weeks ago
---
> [React] Sonar

- generators/client/templates/angular/src/main/webapp/app/app.module.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/util/data-util.service.spec.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/util/event-manager.service.spec.ts.ejs
> [angular] Polish and add some tests

- generators/docker-base.js
- generators/docker-compose/index.js
- generators/docker-compose/templates/README-DOCKER-COMPOSE.md.ejs
- generators/docker-compose/templates/docker-compose.yml.ejs
- generators/generator-base-docker.js
- generators/generator-base.js
- generators/kubernetes-knative/files.js
- generators/kubernetes-knative/templates/service.yml.ejs
- generators/openshift/templates/deployment.yml.ejs
- test/knative.spec.js
- Fix docker compose regression using oauth2.
- Prefer blueprint api.
- Improve derived properties.
Related to https://github.com/jhipster/generator-jhipster/pull/14629 and https://github.com/jhipster/generator-jhipster/pull/14563
---
> Fixes and improvements to docker compose

- generators/client/templates/angular/src/main/webapp/app/core/util/event-manager.service.spec.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/shared/pagination/item-count.component.spec.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/shared/pagination/item-count.component.ts.ejs
> [angular] Fix typo and simplify + add tests to item count component

- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity-details.vue.ejs
- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity-update.component.ts.ejs
- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity-update.vue.ejs
- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity.component.ts.ejs
- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity.service.ts.ejs
- generators/entity-client/templates/vue/src/main/webapp/app/entities/entity.vue.ejs
- generators/entity-client/templates/vue/src/test/javascript/e2e/entities/entity-update-page-object.ts.ejs
- generators/entity-client/templates/vue/src/test/javascript/e2e/entities/entity.spec.ts.ejs
- generators/entity-client/templates/vue/src/test/javascript/spec/app/entities/entity-update.component.spec.ts.ejs
- generators/entity-client/templates/vue/src/test/javascript/spec/app/entities/entity.component.spec.ts.ejs
- generators/entity-client/templates/vue/src/test/javascript/spec/app/entities/entity.service.spec.ts.ejs
> derived constant in generator vue

- generators/client/templates/react/src/main/webapp/app/shared/layout/menus/menu-item.tsx.ejs
> [React] Sonar fix

- generators/client/templates/vue/src/main/webapp/app/account/account.service.ts.ejs
Fix sonar issues:
- Replace this trivial promise with Promise.resolve 
- Expected a for-of loop instead of a for loop with this simple iteration
---
> [Vue] Sonar

- generators/server/templates/.mvn/wrapper/maven-wrapper.properties
> Update maven wrapper version to 3.8.1

- generators/entity-server/templates/src/test/gatling/user-files/simulations/EntityGatlingTest.scala.ejs
- generators/entity-server/templates/src/test/java/package/domain/EntityTest.java.ejs
- generators/entity-server/templates/src/test/java/package/service/dto/EntityDTOTest.java.ejs
- generators/entity-server/templates/src/test/java/package/service/mapper/EntityMapperTest.java.ejs
- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
- generators/export-jdl/index.js
- generators/gae/index.js
- generators/gae/templates/application-prod-gae.yml.ejs
- generators/gae/templates/pom-profile.xml.ejs
- generators/generator-base-private.js
- generators/generator-base.js
- generators/generator-list.js
- package-lock.json
- utils/entity.js
- utils/field.js
> using constants on entity test classes

- generators/client/templates/angular/src/main/webapp/app/admin/metrics/blocks/jvm-threads/jvm-threads.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/metrics/blocks/metrics-modal-threads/metrics-modal-threads.component.ts.ejs
> [Angular] Use enum ThreadState

- generators/server/templates/build.gradle.ejs
> Remove redundant blank line from build.gradle

- generators/entity-client/templates/common/src/test/javascript/cypress/integration/entity/entity.spec.ts.ejs
Fix daily builds.
Daily builds samples are generating values not compatible with regexp.
Switch from regexp comparison to normal equality for strings.
Drop non required force.
Minor adjusts.
---
> Fix cypress string assertion.

- generators/client/templates/angular/src/main/webapp/app/entities/user/user.service.spec.ts.ejs
> [angular] Improve user service test coverage

- generators/client/templates/angular/src/main/webapp/app/login/login.component.spec.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/login/login.component.ts.ejs
Using Non-null assertion operator (!) for ViewChild according to https://angular.io/api/core/ViewChild
---
> [angular] Improve login component test coverage

- generators/client/templates/angular/src/main/webapp/app/admin/user-management/list/user-management.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/config/pagination.constants.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.ts.ejs
> [Angular] Add constants pagination

- generators/client/templates/angular/src/main/webapp/app/home/home.component.spec.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/home/home.component.ts.ejs
> [angular] Improve home component test coverage

- generators/client/templates/angular/src/main/webapp/app/layouts/main/main.component.spec.ts.ejs
> [angular] Add tests to main component RTL functionality

- generators/entity-client/templates/angular/src/main/webapp/app/entities/service/entity.service.spec.ts.ejs
> [angular] Improve entity service test coverage

- generators/entity-client/templates/common/src/test/javascript/cypress/integration/entity/entity.spec.ts.ejs
- utils/field.js
> Simplify cypress assertions.

- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/shared/util/pagination.constants.ts.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs
Same as Angular https://github.com/jhipster/generator-jhipster/pull/14774
---
> [React] Add constants for pagination

- generators/client/files-angular.js
- generators/client/templates/angular/src/main/webapp/app/layouts/profiles/page-ribbon.component.spec.ts.ejs
- test/utils/expected-files.js
Add test for page-ribbon component
---
> [Angular] Add page-ribbon test

- generators/bootstrap/index.js
- generators/generator-transforms.js
- package-lock.json
- package.json
> Bump yeoman-environment to 3.3.0 and yeoman-test to 6.0.0

- generators/client/files-angular.js
- generators/client/templates/angular/src/main/webapp/app/admin/health/modal/health-modal.component.spec.ts.ejs
- test/utils/expected-files.js
> [Angular] Add health-modal test

- generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.ts.ejs
Fix https://sonarcloud.io/project/issues?id=jhipster-sample-application&open=AXkQ7FjSRjkXPPWKFUsL&resolved=false&types=CODE_SMELL
---
> [Angular] Sonar: Unused import

- generators/server/templates/src/test/java/package/security/SecurityUtilsUnitTest.java.ejs
> Fix cases of test method signature.

- generators/client/templates/react/webpack/webpack.dev.js.ejs
- generators/client/templates/vue/webpack/webpack.dev.js.ejs
> Fix react and vue webpack cache.

- generators/heroku/templates/Procfile.ejs
I tested it with:
* deploy via jhipster heroku and git
* add github actions integration 
* failing deployment
* adapt procfile, push to github
* deployment works
Sample repo: https://github.com/atomfrede/jh-14814-sample
closes #14814
---
> remove release phase from procfile

- generators/entity/prompts.js
> Fix: Cannot read property 'includes' of undefined when adding Enumeration field to a jhipster entity 

- cli/commands.js
- generators/entity/index.js
- generators/entity/prompts.js
- jdl/converters/json-to-jdl-entity-converter.js
- package-lock.json
- package.json
Fix dependabot https://github.com/jhipster/generator-jhipster/pull/14918
---
> Update Prettier 2.2.1 -> 2.3.0

- .github/dependabot.yml
- generators/client/templates/angular/package.json
> Bump zone.js to 0.11.4 and remove dependencies from dependabot ignore.

- generators/server/templates/src/main/java/package/web/rest/GatewayResource.java.ejs
> remove condition on reactive for Gateways

- generators/aws/index.js
- generators/aws/lib/aws.js
- package-lock.json
- package.json
- test/blueprint/app-blueprint.spec.js
Fix https://github.com/jhipster/generator-jhipster/pull/15072
---
> Upgrade eslint-plugin-import 2.22.1 to 2.23.0

- generators/server/index.js
- generators/server/templates/build.gradle.ejs
Bug fix to https://github.com/jhipster/generator-jhipster/pull/14315
---
> Fix gradle install with skipClient

- generators/client/files-angular.js
- generators/client/templates/angular/jest.conf.js.ejs
- generators/client/templates/angular/src/main/webapp/app/app.constants.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/config/translation.config.ts.ejs
- generators/client/templates/angular/tsconfig.app.json.ejs
- generators/client/templates/angular/webpack/environment.js.ejs
- generators/client/templates/angular/webpack/webpack.custom.js.ejs
- test/utils/expected-files.js
Add `"types": []`, to `tsconfig.app.json` like angular-cli fresh generated application.
---
> Adjust angular to not require node typings.

- generators/client/prompts.js
It will allow to use the new themes :-D
- https://bootswatch.com/quartz/
- https://bootswatch.com/vapor/
- etc
---
> Bootswatch update theme

- generators/client/templates/common/package.json
- generators/cypress/templates/src/test/javascript/cypress/support/index.ts.ejs
- generators/generator-base.js
Fix: https://github.com/jhipster/generator-jhipster/pull/14942 & https://github.com/jhipster/generator-jhipster/pull/15103
---
> Cypress 7.4.0

- .github/release-drafter.yml
Adding more categories, in particular add `pr: bug-fix` to the `Bugs` category.
[skip-ci][ci-skip]
---
> refine release drafter categories

- generators/cleanup.js
- generators/client/needle-api/needle-client-react.js
- generators/client/templates/react/package.json
- generators/client/templates/react/package.json.ejs
- generators/client/templates/react/src/main/webapp/app/config/notification-middleware.spec.ts.ejs
- generators/client/templates/react/src/main/webapp/app/config/notification-middleware.ts.ejs
- generators/client/templates/react/src/main/webapp/app/config/store.ts.ejs
- generators/client/templates/react/src/main/webapp/app/modules/account/password-reset/finish/password-reset-finish.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/account/password-reset/init/password-reset-init.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/account/password/password.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/account/register/register.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/account/settings/settings.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management-update.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/login/login-modal.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/shared/reducers/reducer.utils.ts.ejs
- generators/client/templates/react/src/main/webapp/app/shared/util/entity-utils.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/integration/account/login-page.spec.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/integration/account/password-page.spec.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/integration/account/register-page.spec.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/integration/account/reset-password-page.spec.ts.ejs
- generators/cypress/templates/src/test/javascript/cypress/support/commands.ts.ejs
- generators/entity-client/templates/common/src/test/javascript/cypress/integration/entity/entity.spec.ts.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-reducer.spec.ts.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.reducer.ts.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/react_validators.ejs
- generators/entity-client/templates/react/src/test/javascript/e2e/entities/entity-update-page-object.ts.ejs
- generators/entity-client/templates/react/src/test/javascript/e2e/entities/entity.spec.ts.ejs
- package-lock.json
Fix #15127 
Fix #13774 
Ooff. This ended up being way more work then I anticipated :(
---
> React validation migration

- .github/workflows/webflux.yml
Webflux workflow only uses angular.
Related to https://github.com/jhipster/generator-jhipster/issues/14566.
---
> Disable on push at webflux workflow for react and vue changes.

- generators/server/templates/pom.xml.ejs
This hopefully should fix the `jhipster-bom` failures.
---
> Use generate-resources phase to calculate checksum

- .github/workflows/angular.yml
- .github/workflows/generator.yml
- .github/workflows/gradle-wrapper-validation.yml
- .github/workflows/incremental-changelog.yml
- .github/workflows/jdl.yml
- .github/workflows/react.yml
- .github/workflows/vue.yml
- .github/workflows/webflux.yml
Related to https://github.com/jhipster/generator-jhipster/issues/15205.
---
> Cancel PR builds on close.

- generators/client/templates/angular/package.json.ejs
- generators/client/templates/vue/package.json.ejs
Workaround current daily builds failures.
---
> Use fixed chromedriver version.

- generators/generator-constants.js
> Update gradle version to 7.0.2
