jhipster/generator-jhipster

.github/dependabot.yml
package.json

Fixes https://github.com/jhipster/generator-jhipster/issues/14492.
ajv-format broke compatibility with npm@6/npm@7 with legacy-peer-deps at https://github.com/ajv-validator/ajv-formats/pull/15.
conf@9.0.2 only change is add ajv-format dependency at https://github.com/sindresorhus/conf/pull/144
Pin conf to 9.0.1 so ajv-format is not pulled to our dependency tree.
---

Revert conf to 9.0.1

---

cli/commands.js
cli/import-jdl.js
generators/entity/index.js
jdl/converters/jdl-to-json/jdl-to-json-relationship-converter.js
jdl/converters/jdl-to-json/jdl-with-applications-to-json-converter.js
jdl/converters/jdl-to-json/jdl-without-application-to-json-converter.js
jdl/converters/parsed-jdl-to-jdl-object/parsed-jdl-to-jdl-object-converter.js
jdl/converters/parsed-jdl-to-jdl-object/relationship-converter.js
jdl/jdl-importer.js
jdl/models/jdl-relationship.js
jdl/validators/jdl-with-application-validator.js
jdl/validators/jdl-without-application-validator.js
jdl/validators/relationship-validator.js
test/jdl/converters/json-to-jdl-entity-converter.spec.js
test/jdl/jdl-importer.spec.js
test/jdl/models/jdl-relationship.spec.js

Related to https://github.com/jhipster/generator-jhipster/issues/13885, https://github.com/jhipster/generator-jhipster/issues/14196#issuecomment-801770359
Closes https://github.com/jhipster/generator-jhipster/issues/13305.
---

Add support to unidirectional relationships.

---

generators/client/templates/angular/package.json.ejs
generators/common/templates/README.md.ejs
generators/server/index.js

Also simplify `watch` script and optimize `backend:start` script for `Gradle` (exclude `webapp` task as this is done for `Maven`).
HMR by default was requested in https://github.com/jhipster/generator-jhipster/pull/13118#issuecomment-732024690 and in https://github.com/jhipster/generator-jhipster/issues/14028#issuecomment-784388044
And follow up to #14524
---

Use HMR by default in Angular

---

.github/workflows/angular.yml
.github/workflows/incremental-changelog.yml
.github/workflows/react.yml
.github/workflows/vue.yml
.github/workflows/webflux.yml
azure-pipelines.yml
generators/generator-constants.js

Upgrade jhipster lib 7.0.2 snapshot

---

generators/client/templates/angular/src/main/webapp/app/admin/user-management/detail/user-management-detail.component.spec.ts.ejs
generators/client/templates/angular/src/main/webapp/app/app-routing.module.ts.ejs
generators/client/templates/angular/src/main/webapp/app/config/uib-pagination.config.ts.ejs
generators/client/templates/angular/src/main/webapp/app/core/interceptor/auth.interceptor.ts.ejs
generators/client/templates/angular/src/main/webapp/app/core/util/alert.service.ts.ejs
generators/client/templates/angular/src/main/webapp/app/core/util/data-util.service.ts.ejs
generators/client/templates/angular/src/main/webapp/app/layouts/profiles/page-ribbon.component.ts.ejs
generators/client/templates/angular/src/main/webapp/app/login/login.component.ts.ejs
generators/client/templates/angular/src/main/webapp/app/login/login.route.ts.ejs
generators/client/templates/angular/src/main/webapp/app/shared/shared.module.ts.ejs

[Angular] Minor style code

---

generators/entity-client/templates/common/src/test/javascript/cypress/integration/entity/entity.spec.ts.ejs

Improve url patterns for [cypress 7](https://docs.cypress.io/guides/references/migration-guide#URL-matching-is-stricter).
---

[cypress] Improve url patterns.

---

generators/server/templates/build.gradle.ejs
generators/server/templates/pom.xml.ejs

Since https://github.com/jhipster/generator-jhipster/pull/14459 passes, allow developers to use Java 16 with JHipster.

Allow JHipster to be used with Java 16

---

generators/client/templates/angular/src/main/webapp/app/app.module.ts.ejs
generators/client/templates/angular/src/main/webapp/app/core/auth/account.service.spec.ts.ejs
generators/client/templates/angular/src/main/webapp/app/core/auth/account.service.ts.ejs
generators/client/templates/angular/src/main/webapp/app/core/auth/auth-jwt.service.ts.ejs
generators/client/templates/angular/src/main/webapp/app/core/auth/state-storage.service.ts.ejs
generators/client/templates/angular/src/main/webapp/app/core/interceptor/auth.interceptor.ts.ejs
generators/client/templates/angular/src/main/webapp/app/layouts/navbar/navbar.component.ts.ejs

Uses similar style for `SessionStorageService` and `LocalStorageService` variable names:
* using `sessionStorageService` and `localStorageService` everywhere
* previously also `sessionStorage`, `$sessionStorage`, `localStorage` and `$localStorage` was used, names `$sessionStorage` and `$localStorage` are probably AngularJs relicts
Adds more tests to `AccountService`.
Improves automatic language change logic:
* previously when navigating away and back to application then chosen language was reapplied only if valid authentication existed
* now previously chosen language is reapplied also if user is not authenticated
--- …

[angular] Polish, add tests and improve automatic language change logic

---

generators/entity-client/templates/angular/src/main/webapp/app/entities/detail/entity-management-detail.component.html.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.html.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.ts.ejs
generators/entity-client/templates/angular/src/test/javascript/e2e/entities/entity-page-object.ts.ejs
generators/entity-client/templates/angular/src/test/javascript/e2e/entities/entity.spec.ts.ejs
generators/entity-client/templates/common/src/test/javascript/cypress/integration/entity/entity.spec.ts.ejs
generators/entity-client/templates/react/src/main/webapp/app/entities/entity-delete-dialog.tsx.ejs
generators/entity-client/templates/react/src/main/webapp/app/entities/entity-detail.tsx.ejs
generators/entity-client/templates/react/src/main/webapp/app/entities/entity-reducer.spec.ts.ejs
generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs
generators/entity-client/templates/react/src/main/webapp/app/entities/entity.reducer.ts.ejs
generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs
generators/entity-client/templates/react/src/main/webapp/app/entities/index.tsx.ejs
generators/entity-client/templates/react/src/main/webapp/app/entities/react_validators.ejs
generators/entity-client/templates/react/src/test/javascript/e2e/entities/entity-page-object.ts.ejs
generators/entity-client/templates/react/src/test/javascript/e2e/entities/entity-update-page-object.ts.ejs
generators/entity-client/templates/react/src/test/javascript/e2e/entities/entity.spec.ts.ejs
generators/generator-base-private.js
jdl/jhipster/entity-options.js
utils/entity.js

Use derived constant in entity-react generator

---

generators/server/templates/gradle/swagger.gradle.ejs
generators/server/templates/pom.xml.ejs

The OpenAPI model should be generated in the package service.dto
From
`<modelPackage>*.web.api.model</modelPackage>`
To
`<modelPackage>*.service.dto</modelPackage>`
---

Fixes #13995: OpenAPI modelPackage

---

generators/entity-server/index.js
generators/entity-server/templates/src/main/java/package/repository/EntityRepository.java.ejs
utils/relationship.js

Closes #14626 
When using a table name with an SQL keyword (example: `Order`), the generated query throws an exception:
Example:
```java
@Query("select distinct order from Order order left join fetch order.products")
List<Order> findAllWithEagerRelationships();
```
Produces the following error:
```
Caused by: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: order near line 1, column 17 [select distinct order from com.mycompany.myapp.domain.Order order left join fetch order.products]
at org.hibernate.hql.internal.ast.QuerySyntaxException.convert(QuerySyntaxException.java:74)
at org.hibernate.hql.internal.ast.ErrorTracker.throwQueryException(ErrorTracker.java:93)
at org.hibernate.hql.internal.ast.QueryTranslatorImpl.parse(QueryTranslatorImpl.java:301)
at …
```

add prefix in generated eager relationship queries

---

generators/entity-server/templates/partials/it_patch_update.partial.java.ejs
generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs
generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
utils/field.js

Related to https://github.com/jhipster/generator-jhipster/pull/14659 and https://github.com/jhipster/generator-jhipster/issues/14108
---

Improve autoGenerate logic.

---

generators/entity-server/templates/src/main/java/package/repository/EntityRepository.java.ejs
generators/entity-server/templates/src/main/java/package/repository/EntityRepositoryInternalImpl_reactive.java.ejs
generators/entity-server/templates/src/main/java/package/repository/EntityRepository_reactive.java.ejs
generators/entity-server/templates/src/main/java/package/repository/rowmapper/EntityRowMapper.java.ejs
generators/entity-server/templates/src/main/java/package/repository/search/EntitySearchRepository.java.ejs
generators/entity-server/templates/src/main/java/package/service/EntityQueryService.java.ejs
generators/entity-server/templates/src/main/java/package/service/EntityService.java.ejs
generators/entity-server/templates/src/main/java/package/service/criteria/EntityCriteria.java.ejs
generators/entity-server/templates/src/main/java/package/service/dto/EntityDTO.java.ejs
generators/entity-server/templates/src/main/java/package/service/impl/EntityServiceImpl.java.ejs
generators/entity-server/templates/src/main/java/package/service/mapper/EntityMapper.java.ejs
generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs
generators/entity-server/templates/src/main/resources/config/cql/changelog/added_entity.cql.ejs
generators/entity/index.js
utils/entity.js
utils/field.js

use constants in entity-server

---

generators/bootstrap/index.js
generators/database-changelog-liquibase/index.js
generators/entity-client/files.js
generators/entity-client/templates/common/src/test/javascript/cypress/integration/entity/entity.spec.ts.ejs
generators/entity-server/files.js
generators/utils.js
test/entity.spec.js

Currently, reproducibility depends on factors like order of entity generation.
Eg: Adding a new entity may change source of others entities, and regenerating just after, changes again.
With this PR, reproducibility is done for each file. The source should change only if the entity changes or the source file changes.
Closes https://github.com/jhipster/generator-jhipster/issues/14549
---

Improve faker seed for better reproducibility.

---

generators/client/templates/angular/src/main/webapp/app/home/home.component.html.ejs
generators/client/templates/react/src/main/webapp/app/modules/home/home.tsx.ejs
generators/server/templates/src/main/resources/static/microservices_index.html.ejs

change the urls for stackoverflow tag to https throughout the application to address security hotspot finding in sonarqube for mixed content
Fix #14735
---

change urls for stackoverflow tag from http to https

---

generators/client/templates/angular/src/main/webapp/app/admin/metrics/blocks/metrics-cache/metrics-cache.component.ts.ejs
generators/client/templates/angular/src/main/webapp/app/admin/metrics/blocks/metrics-datasource/metrics-datasource.component.ts.ejs
generators/client/templates/angular/src/main/webapp/app/admin/metrics/blocks/metrics-request/metrics-request.component.ts.ejs
generators/client/templates/angular/src/main/webapp/app/core/util/operators.spec.ts.ejs
generators/client/templates/angular/src/main/webapp/app/core/util/operators.ts.ejs

Externalyze `filterNaN` in a file
---

[Angular] Externalyze method filterNaN

---

generators/client/templates/angular/src/main/webapp/app/layouts/main/main.component.spec.ts.ejs
generators/client/templates/angular/src/main/webapp/app/layouts/main/main.component.ts.ejs

Routing to /404 on NavigationError with code 404 was redundant here, this code was never called, because at some point was added https://github.com/jhipster/generator-jhipster/blob/4fbd5ce03f477f754e3ad983494fbffdb4eb6879/generators/client/templates/angular/src/main/webapp/app/layouts/error/error.route.ts.ejs#L47-L50
---

[angular] Improve main component test coverage

---

generators/client/templates/vue/src/test/javascript/e2e/modules/account/account.spec.ts.ejs
generators/cypress/templates/src/test/javascript/cypress/integration/account/login-page.spec.ts.ejs
generators/cypress/templates/src/test/javascript/cypress/integration/account/reset-password-page.spec.ts.ejs
generators/cypress/templates/src/test/javascript/cypress/integration/account/settings-page.spec.ts.ejs
generators/cypress/templates/src/test/javascript/cypress/integration/administration/administration.spec.ts.ejs
generators/entity-client/templates/common/src/test/javascript/cypress/integration/entity/entity.spec.ts.ejs
generators/page/templates/vue/src/test/javascript/e2e/pages/page.spec.ts.ejs

With Protractor, we allow username/password to be overridden by environment variables. We should do the same for Cypress.
---

Allow env variables to override Cypress credentials

---

generators/bootstrap/index.js

For example Cypress `src/test/javascript/cypress/.eslintrc.json` was not prettified on generation before this change
---

Prettier files starting with dot (.) in subfolders already on generation

---

generators/client/index.js
generators/server/index.js

This allows to respect `buildTool` variable so that for Gradle users is generated `gradlew` instead of `mvnw`.
Also fixed `e2e:dev` command second part, using `npm run e2e` instead of `e2e`.
---

Move e2e scripts from client sub generator to server sub generator

---

generators/generator-base-private.js

Just a small fix to correct the java version check of the generator to be aligned with the support on maven/gradle side.
---

adapt java version check to support jdk > 12

---

generators/server/templates/pom.xml.ejs

Conditionally skip frontend build tasks

---

generators/client/templates/react/src/main/webapp/app/config/notification-middleware.spec.ts.ejs
generators/client/templates/react/src/main/webapp/app/config/notification-middleware.ts.ejs

the login popup shows an error message therefore a notification is not needed
Fix #14738

Fix bug where 401 errors trigger a notification

---

.mocharc.js
generators/bootstrap/index.js
generators/docker-base.js
generators/docker-prompts.js
generators/kubernetes-base.js
generators/server/index.js
generators/utils.js
package-lock.json
package.json
test/__snapshots__/kubernetes.spec.js.snap
test/kubernetes.spec.js

Deployment test suites currently tests:
- generated file names.
- a few generated contents.
There is no real execution tests and generated contents coverage is too low.
This PR implements generated files snapshot tests for kubernetes.
- A full generated content regression test.
Old tests are kept for now but could be dropped.
---

Implement generated files snapshot test for kubernetes.

---

generators/generator-base.js

Fix jhipster/generator-jhipster#14932
---

Fix "table name is too long for Oracle" error when --skipCheckLengthOfIdentifier config is true

---

generators/bootstrap/index.js
generators/server/files.js
generators/server/index.js
generators/server/templates/gradle.properties.ejs
generators/server/templates/npmw
generators/server/templates/npmw.cmd
generators/server/templates/pom.xml.ejs
test-integration/scripts/10-install-jhipster.sh

Closes https://github.com/jhipster/generator-jhipster/issues/14249
---

Prefer project scoped node/npm binaries over global binaries

---

generators/server/index.js
generators/server/templates/build.gradle.ejs
generators/server/templates/gradle/profile_dev.gradle.ejs
generators/server/templates/gradle/profile_prod.gradle.ejs
generators/server/templates/npmw
generators/server/templates/pom.xml.ejs

Workaround https://github.com/npm/cli/issues/2715.
Closes https://github.com/jhipster/generator-jhipster/issues/14934.
---

Disable audit at npm install

---

generators/server/templates/pom.xml.ejs

Fix #14991
fixes 
```
java.lang.NoClassDefFoundError: org/apache/maven/doxia/siterenderer/DocumentContent
```
during
```
mvn site
```
---

update maven-site-plugin to 3.7.1

---

.github/release-drafter.yml

The current view when looking at the release page here on github is not very nice to read. I know the primary source for our changelogs is the website, but I think a little more structure here makes sense. 
This PR creates a first categorization for pull requests. Most important the dependency updates are separated from other features. 
[ci-skip] [skip-ci]
---

categorize changes in release drafter config

---

generators/server/templates/src/main/java/package/web/rest/UserResource.java.ejs

Add "createdBy", "createdDate", "lastModifiedBy" and "lastModifiedDate" to the allowlist of properties that can be sort in the Users list. (Otherwise a 400 is thrown when calling the sort)

fix: add missing allowed ordered properties

---

generators/server/templates/src/main/resources/logback-spring.xml.ejs

close #13835
closes #14444 
It now looks like this:
---

supress noisy logs on startup in dev profile

---

generators/aws/index.js

The right value of `dbEngine` is "postgres" not  "postgresql" as [documented in AWS](https://docs.aws.amazon.com/cli/latest/reference/rds/create-db-instance.html#options).
I haven't tested it with AWS, I only did a code review and saw which commit introduced the regression: 972b1e87e8d5fe09942705c2da29de555e349685
Fix: #15151
---

AWS: wrong dbEngine for PostgreSQL

---

generators/server/index.js

fix cypress e2e ci packaging error on copy

---

generators/server/templates/src/main/java/package/config/StaticResourcesWebConfiguration.java.ejs

Caching is now working as expected. It really seems like a bug introduced when the app was directly compiled to `/static` instead of `/static/app`. 
You can see the first requests load the files with correct caching headers while the reload serves everything from cache.
closes #15126
---

cache frontend application files

---

.github/workflows/angular.yml
.github/workflows/generator.yml
.github/workflows/gradle-wrapper-validation.yml
.github/workflows/incremental-changelog.yml
.github/workflows/jdl.yml
.github/workflows/label-cleanup.yml
.github/workflows/react.yml
.github/workflows/triage.yml
.github/workflows/vue.yml
.github/workflows/webflux.yml

Related to https://github.com/jhipster/generator-jhipster/issues/15205 and https://github.com/jhipster/generator-jhipster/issues/14566.
Using group name as `worflowName-${{ github.head_ref || (github.ref == 'refs/heads/main' && github.sha) || github.ref }}`.
PRs should resolve as `worflowName-refs/heads/branchName`
Push events to main should resolve as `worflowName-commitHash`, so will not cancel running workflows.
Push events to others branches should resolve as `worflowName-refs/heads/branchName`.
---

Cancel outdated workflow runs.

---

jdl/parsing/jdl-parser.js
test/jdl/grammar/grammar.spec.js

allow javadoc comments before and after enum values

---

generators/ci-cd/templates/azure-pipelines.yml.ejs
test/__snapshots__/ci-cd.spec.js.snap

Upates Azure DevOps subgenerator:
- Publish test results for backend and frontend tests
- Publish Cypress screenshots if E2E tests failed
---

Publish test results on Azure pipeline generator

---

generators/generator-base-private.js
generators/server/templates/build.gradle.ejs
generators/server/templates/pom.xml.ejs
generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs
generators/server/templates/src/main/java/package/repository/rowmapper/UserRowMapper.java.ejs
generators/server/templates/src/main/java/package/service/UserService.java.ejs
generators/server/templates/src/main/resources/config/liquibase/changelog/initial_schema.xml.ejs
generators/server/templates/src/test/java/package/web/rest/UserResourceIT.java.ejs
test/app.spec.js
test/generator-base.spec.js

This PR fixes all issues mentioned in #15032 
* using `asEntity('User')` everywhere
* correcting the mssql r2dbc url
* adding the necessary setting to liquibase migration
closes #15032
---

fix mssql and r2dbc integration

---

generators/client/templates/react/webpack/webpack.common.js.ejs
generators/client/templates/react/webpack/webpack.dev.js.ejs
generators/client/templates/react/webpack/webpack.prod.js.ejs
generators/client/templates/vue/webpack/webpack.common.js.ejs
generators/client/templates/vue/webpack/webpack.dev.js.ejs
generators/client/templates/vue/webpack/webpack.prod.js.ejs

Related to https://github.com/jhipster/generator-jhipster/issues/14566.
Reduces React and Vue builds by ~1m.
---

Enable webpack cache at production builds for react and vue.

---

generators/server/templates/src/main/resources/logback-spring.xml.ejs

Following https://github.com/jhipster/generator-jhipster/pull/15004. Suppressing noisy logs for reactive applications as the handler are different 
relates to #14444
---

supress detailed debug logging of handler mappings for reactive apps

---

generators/server/templates/gradle.properties.ejs
generators/server/templates/pom.xml.ejs

Related with https://github.com/jhipster/generator-jhipster/issues/14287
- Updates the version of openapi generator maven plugin for server side code generation.
- Does not update the version of the npm package for client side code generation. Versioning has changed, I have to dig into it (see Configuration section in https://www.npmjs.com/package/@openapitools/openapi-generator-cli)
I was thinking about 2 separate PRs, but if you folks think it should be done here I'll keep this PR to fix the client too. 

update openapi generator to version 5.1.1

---

generators/server/templates/src/main/java/package/security/jwt/JWTRelayGatewayFilterFactory.java.ejs

When relay requests, gateways should not assume that there is always authorization header. There are scenarios that services expose endpoints that allow anonymous access, which in most cases contain no authorization header. Current behavior of throwing an exception is not quite reasonable IMHO.
e.g. In my case, I use a user service instead of gateway to provide authentication service thus I permit all visits to /services/user/api/authenticate, no authorization header needed of course. 

JWTRelay allow no authorization header

---

generators/server/templates/src/test/java/package/web/rest/KafkaResourceIT.java.ejs

When generating a reactive service (e.g. gateway), api base name in KafkaResourceIT tests does not match the actual api base name, which leads to integration tests fail eventually.
In generated Resource class, api is:
```
@RestController
@RequestMapping("/api/<%= dasherizedBaseName %>-kafka")
public class <%= upperFirstCamelCase(baseName) %>KafkaResource {
@PostMapping("/publish/{topic}")
public ........
```
in generated rest tests, it was :
```
@Test
void producesMessages()<% if (!reactive) { %> throws Exception<% } %> {
<%_ if (!reactive) { _%>
restMockMvc.perform(post("/api/<%= dasherizedBaseName %>-kafka/publish/topic-produce?message=value-produce"))
.andExpect(status().isOk())
.andExpect(content().contentType(MediaType.APPLICATION_JSON));
<%_ } else { _%> …
```

Correct api base name in kafkaResourceIT reactive tests

---

.github/workflows/jdl.yml
cli/import-jdl.js
generators/client/index.js
generators/client/templates/angular/webpack/proxy.conf.js.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.module.ts.ejs
generators/generator-base.js
generators/server/templates/src/main/resources/static/microservices_index.html.ejs
test/__snapshots__/server.spec.js.snap
test/client/__snapshots__/angular.spec.js.snap
test/client/angular.spec.js
test/client/react.spec.js
test/client/vue.spec.js
test/server.spec.js

- Add generator tests.
- Change microservice/microfrontend web server proxy to use gateway port.
- Throw error when generating Microfrontend with others client frameworks.
---

Adjusts to Microfrontend.

---

generators/client/templates/angular/src/test/javascript/e2e/account/account.spec.ts.ejs

https://github.com/jhipster/generator-jhipster/pull/15286 added the application name to angular home page at:
https://github.com/jhipster/generator-jhipster/blob/5fd39520478f61469133ccb656c3d1acdb459779/generators/client/templates/angular/src/main/webapp/app/home/home.component.html.ejs#L25
This can be helpful to identify a webapp now that microfrontends have one webapp each.
Adjust protractor test according to this change.
---

Fix protractor.

---

generators/entity-client/templates/vue/src/main/webapp/app/entities/entity-update.vue.ejs

[vue] Fix OneToOne fields binding in update entity select

---

generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs

I ran into this bug in one of my project, generated code is:  
```
@JsonIgnoreProperties(value = { "student" }, allowSetters = true)
@OneToOne(mappedBy = "student")
private StudentForeignerInfo foreignerInfo;
......
public void setForeignerInfo(StudentForeignerInfo studentForeignerInfo) {
if (this.foreignerInfo != null) {
this.foreignerInfo.setStudent(null);
}
if (foreignerInfo != null) {
foreignerInfo.setStudent(this);
}
this.foreignerInfo = studentForeignerInfo;
}
```
should be:  
```
@JsonIgnoreProperties(value = { "student" }, allowSetters = true)
@OneToOne(mappedBy = "student")
private StudentForeignerInfo foreignerInfo;
......
public void setForeignerInfo(StudentForeignerInfo studentForeignerInfo) {
if (this.foreignerInfo != null) {
this.foreignerInfo.setStudent(null);
}
if …
```

Fix wrong otherEntityName in relationship setter

---

azure-pipelines.yml
generators/ci-cd/templates/azure-pipelines.yml.ejs
test/__snapshots__/ci-cd.spec.js.snap

Uses `-q` flag on wget to download Chrome quietly. Otherwise ~1000 lines of download progress are printed.
---

Download Chrome quietly on pipeline

---

generators/server/templates/pom.xml.ejs

Skip svelte dynamic files

---

generators/ci-cd/templates/jenkins/Jenkinsfile.ejs

Prefixing npm commands with 'sh' ensures compatibility with the jenkins environment
---

Prefixing npm command with sh in Jenkinsfile

---

generators/generator-constants.js
generators/server/templates/build.gradle.ejs

Downgrade gradle to see if its related. Moving spring boot devtools to main build files as development only ensures its not packaged in the executable jar.
updates #15359
---

downgrade gradle

---

generators/server/templates/src/main/java/package/web/rest/AccountResource.java.ejs

Following https://github.com/jhipster/generator-jhipster/pull/15349
It's for fixing compilation error, detected by daily builds:
```
[INFO] -------------------------------------------------------------
Error:  COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
Error:  /home/runner/work/jhipster-daily-builds/jhipster-daily-builds/app/src/main/java/com/mycompany/myapp/web/rest/AccountResource.java:[47,9] cannot find symbol
symbol:   variable log
location: class com.mycompany.myapp.web.rest.AccountResource
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] …
```

Fix import for no database configuration

---

generators/ci-cd/templates/jenkins/Jenkinsfile.ejs
test/__snapshots__/ci-cd.spec.js.snap

Updating the CI-CD generator Jenkinsfile.
- This fixes the node install bug for Gradle
- use prod builds
- and use the same commands described in [the docs](https://www.jhipster.tech/docker-compose/#3).
---

Fix 'publish docker' stage in Jenkinsfile

---

generators/client/templates/vue/package.json
generators/client/templates/vue/package.json.ejs
generators/client/templates/vue/src/main/webapp/app/constants.ts.ejs
generators/client/templates/vue/src/main/webapp/app/locale/translation.service.ts.ejs
generators/client/templates/vue/src/main/webapp/app/shims-vue.d.ts.ejs
generators/client/templates/vue/src/test/javascript/jest.conf.js.ejs
generators/client/templates/vue/webpack/dev.env.js.ejs
generators/client/templates/vue/webpack/prod.env.js.ejs
generators/client/templates/vue/webpack/webpack.common.js.ejs
generators/client/templates/vue/webpack/webpack.dev.js.ejs
generators/client/templates/vue/webpack/webpack.prod.js.ejs

Migrate vue to use i18n hash instead of build timestamp.
---

Fix index reproducibly in vue framework 

---

cli/import-jdl.js
test/cli/import-jdl.spec.js

Problem: when executing jdl with a custom blueprint option (from app generator) like `jhipster jdl microservice.jdl --blueprints kotlin --skip-ktlint-format`, jdl command with fork serializes options back to cli options and executes deployments generators using cli with every option (eg: jhipster docker-compose --blueprints kotlin --skip-ktlint-format), causing an unknown option error.
Fork is supposed to run multiples generators in parallel making it faster, but deployments are small and will not have a big impact on the execution time.
Drop fork support for deployments, preventing the unknown option error.
Closes https://github.com/jhipster/generator-jhipster/issues/14870.
---
When you are still working on the PR, …

Disable fork for deployments.

---

generators/server/templates/src/main/java/package/Application.java.ejs

Current App.logApplicationStartup() show 'active' profiles by calling Environment.getActiveProfiles(), which is empty if there is no active profiles explicitly set.
According to [Spring docs of Environment](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/env/Environment.html#getActiveProfiles--):
- Environment.getActiveProfiles() returns the set of profiles explicitly made active for this environment. 
- Environment.getDefaultProfiles() returns the set of profiles to be active by default when no active profiles have been set explicitly.
This change is to  show  default profiles when active profile is empty.
---
When you are still working on the PR, consider converting it to Draft …

app startup show default profiles when no active profiles set

---

generators/server/index.js
generators/server/templates/gradle/profile_dev.gradle.ejs

This PR sets names and relative path properties for webpack task inputs in gradle. With this it is in general possible to cache the task (still missing the cache buster being the hash of all i18n files instead of timestamp). This was found during our evaluation of gradle enterprise. 
---

refine webpack task input for gradle caching

---

generators/server/index.js
generators/server/templates/pom.xml.ejs

This PR splits maven up-to-date checksum into 2.
1. Generate a checksum to compare against reference.
2. Generate a complete checksum (generated webapp included) for reference.
Fixes problems where the generated webapp mutated but not the source.
Eg: `./mvn -Pprod`, `npm run clean-www`, `jhipster --with-entities`.
---

Improve maven up-to-date.

---

generators/database-changelog-liquibase/templates/src/main/resources/config/liquibase/changelog/updated_entity.xml.ejs

Attribute remarks is not allowed for add column. And fix closing change set.
---

Fix liquibase incremental changelog

---

generators/server/templates/src/main/resources/config/application.yml.ejs

According to [the documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.health.auto-configured-health-indicators) the indicator for the Database should be `db`.
But I think the best way would be to remove this configuration entirely. Because Spring automatically includes them:
> The following HealthIndicators are auto-configured by Spring Boot when appropriate
What to you think?
---

Fix readiness include

---

generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs

Fix #14862 Internal Server Error after creating a new user.
The reason is about null value for `Optional<>`. So I added default values. Please checkout PR changes. 
---

#14862 fix findFirst() null value

---

generators/server/templates/src/main/java/package/config/OAuth2Configuration.java.ejs
generators/server/templates/src/main/java/package/config/WebConfigurer.java.ejs
generators/server/templates/src/main/java/package/web/filter/OAuth2ReactiveRefreshTokensWebFilter.java.ejs
generators/server/templates/src/main/java/package/web/filter/OAuth2RefreshTokensWebFilter.java.ejs

Fixes to refresh tokens.

---

generators/database-changelog-liquibase/templates/src/main/resources/config/liquibase/changelog/updated_entity_constraints.xml.ejs

Add trailing `_id` for column name of not null constraint.
---

Fix column name for not null constraint

---

generators/client/templates/angular/src/main/webapp/app/admin/configuration/configuration.component.html.ejs
generators/client/templates/angular/src/main/webapp/app/admin/logs/logs.component.html.ejs
generators/client/templates/angular/src/main/webapp/app/admin/user-management/list/user-management.component.html.ejs
generators/client/templates/angular/src/main/webapp/app/shared/sort/sort-by.directive.spec.ts.ejs
generators/client/templates/angular/src/main/webapp/app/shared/sort/sort-by.directive.ts.ejs
generators/client/templates/angular/src/main/webapp/app/shared/sort/sort.directive.spec.ts.ejs
generators/client/templates/angular/src/main/webapp/app/shared/sort/sort.directive.ts.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.html.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.ts.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/list/infinite-scroll-template.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/list/pagination-template.ejs

Fix #14138
As by default Elasticsearch can order by `numeric`, `boolean` and `datetime` fields then allowing to sort only by those fields after searching.
The second commit increases test coverage of the changed sort directive.
---

[angular] Fix infinite scroll sort if search is done 

---

cli/commands.js
generators/config.js
generators/generator-base.js
generators/generator-list.js
generators/init/index.js
generators/init/options.js
generators/options.js
generators/project-name/config.js
generators/project-name/index.js
generators/project-name/options.js
test/init/__snapshots__/init.spec.js.snap
test/init/init.spec.js
test/project-name/project-name.spec.js

Project name and base name are required by every generator.
Split them in another generator, this will allow others generators to don't depend on init generator.
Related to https://github.com/jhipster/generator-jhipster/pull/15540 and https://github.com/jhipster/generator-jhipster/issues/15490
---

Move project name out from init generator.

---

.github/dependabot.yml

Fix dependabot p-queue ignored version

---

generators/server/templates/src/test/java/package/web/rest/KafkaResourceIT.java.ejs

Replace deprecated Java API for Kafka testcontainer and use the `DockerImageName` class.
---

Replace deprecated API for Kafka testcontainer

---

.github/workflows/angular.yml
.github/workflows/jdl.yml
.github/workflows/react.yml
.github/workflows/vue.yml
.github/workflows/webflux.yml
azure-pipelines.yml

Dependabot at root package.json is unlikely to break a specific application/workflow. It will break the generation.
Testing a few builds is enough.
- Enable at azure for PR and merge.
- Disable at gh actions for merge, PR is disabled already.
Related to https://github.com/jhipster/generator-jhipster/issues/14566.
---

Adjusts workflows filters.

---

generators/server/index.js

Fixes webflux-oauth2 random failures.
Wait for 30s and don’t fail on timeout to don’t affect others oauth2 servers.
---

Wait for keycloak to start.

---

generators/client/templates/angular/src/main/webapp/app/core/util/data-util.service.spec.ts.ejs
generators/client/templates/angular/src/main/webapp/app/core/util/data-util.service.ts.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/detail/entity-management-detail.component.spec.ts.ejs

Big images not are loaded after click on it on chrome 91.0.4472.124 or Microsoft Edge 91.0.864.67 under windows 10. Works fine on Firefox.
The error can be reproduced with this project.
https://github.com/CGarces/testimgJHipster
Fails with the bigger image at fake data, the others works fine.
https://github.com/CGarces/testimgJHipster/tree/main/src/main/resources/config/liquibase/fake-data/blob
And can be fixed with this patch
https://github.com/CGarces/testimgJHipster/compare/fix_img?expand=1
The error only happens if is loaded by the openFile function. 
The proposed solution just works for me on angular, I haven't test the issue on other web frameworks. I don't know why the iframe is needed, please give me some background about that to improve the PR.
---
Please make sure the below …

Fix visualization of large images on angular

---

utils/liquibase.js

use constants in utils folder

---

generators/server/templates/src/main/java/package/service/UserService.java.ejs

Use ChronoUnit.Days instead of seconds
---

Use Days instead of seconds

---

generators/client/templates/angular/src/main/webapp/app/login/login.service.ts.ejs
generators/client/templates/angular/src/main/webapp/app/login/logout.model.ts.ejs
generators/client/templates/react/src/main/webapp/app/modules/login/logout.tsx.ejs
generators/client/templates/react/src/main/webapp/app/shared/reducers/authentication.spec.ts.ejs
generators/client/templates/react/src/main/webapp/app/shared/reducers/authentication.ts.ejs
generators/client/templates/vue/src/main/webapp/app/core/jhi-navbar/jhi-navbar.component.ts.ejs
generators/common/templates/README.md.jhi.ejs
generators/cypress/templates/src/test/javascript/cypress/support/oauth2.ts.ejs
generators/server/templates/src/main/java/package/config/SecurityConfiguration_reactive.java.ejs
generators/server/templates/src/main/java/package/security/SecurityUtils.java.ejs
generators/server/templates/src/main/java/package/security/oauth2/CustomClaimConverter.java.ejs
generators/server/templates/src/main/java/package/service/UserService.java.ejs
generators/server/templates/src/main/java/package/web/rest/LogoutResource.java.ejs
generators/server/templates/src/test/java/package/config/TestSecurityConfiguration.java.ejs
generators/server/templates/src/test/java/package/security/SecurityUtilsUnitTest.java.ejs
generators/server/templates/src/test/java/package/security/oauth2/CustomClaimConverterIT.java.ejs

feat: Support Auth0 as OIDC provider

---

generators/entity-server/templates/src/main/java/package/service/EntityQueryService.java.ejs
generators/entity-server/templates/src/main/java/package/service/criteria/EntityCriteria.java.ejs

This PR enables entity filtering with distinct keyword. This is useful when the filter includes properties from child entities.
See also [jhipster-bom/374](https://github.com/jhipster/jhipster-bom/pull/374).
---

Add distinct query for entity filtering

---

generators/generator-base-blueprint.js
generators/generator-base.js

Fix blueprint templates folders.

---

generators/entity/index.js

persist --skip-client or --skip-server cli options to .jhipster/*.json configuration files
add skipClient or skipServer options to .jhipster/*.json files on entity creation via cli options. When these entities are regenerated, will have their desired options skipped
Fix #15366
---

persist --skip-client or --skip-server cli options to .jhipster/*.json configuration files

---

generators/client/templates/react/package.json

Revert https://github.com/jhipster/generator-jhipster/commit/3e25a056b38d60285397155e478fcbc7286178e1#diff-45ad775caf02ce958066eda2b4a911763e810750a9dfaf3ca618a09306bbed87
`npm start` not working with the new version
Without `--inline`, there is an other error
Need a fix to upgrade
Doc is here https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md
---

[React] Downgrade webpack-dev-server (error)

---

generators/cypress/templates/src/test/javascript/cypress/integration/lighthouse.audits.ts.ejs

This PR fixes typo in Lighthouse Audits cypress integration test declaration. It also removes unnecessary white spaces at the end of the line accordingly to .editorconfig.
---

Fix typo Lighthoyse -> Lighthouse

---

generators/client/templates/vue/package.json.ejs
generators/client/templates/vue/webpack/webpack.dev.js.ejs

`npm start` not working
Migration webpack-dev-server https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md
---

[Vue] Fix 'npm start' (webpack-dev-server 4.0.0)

---

generators/generator-base.js
generators/server/templates/build.gradle.ejs
generators/server/templates/src/main/java/package/config/WebConfigurer.java.ejs

No Database selection project generation issue fix

---

generators/entity-server/templates/src/main/java/package/domain/enumeration/Enum.java.ejs
generators/utils.js
jdl/converters/jdl-to-json/jdl-to-json-field-converter.js
jdl/converters/json-to-jdl-entity-converter.js
jdl/models/jdl-enum-value.js
jdl/models/jdl-enum.js
jdl/parsing/api.js
jdl/parsing/jdl-ast-builder-visitor.js
jdl/parsing/jdl-parser.js
test/jdl/converters/JDLToJSON/jdl-to-json-field-converter.spec.js
test/jdl/grammar/grammar.spec.js
test/jdl/models/jdl-enum.spec.js
test/utils.spec.js

---
Adds javadocs to Enum types and enum values from JDL. 
Related to #14869

Add jdl enum comments

---

generators/generator-base.js
generators/server/index.js
generators/server/prompts.js
test/client/__snapshots__/angular.spec.js.snap

Closes https://github.com/jhipster/generator-jhipster/issues/16103
Closes https://github.com/jhipster/generator-jhipster/pull/16010.
Partially reverts https://github.com/jhipster/generator-jhipster/pull/15846.
---

Readd server configuration task.

---

.github/workflows/angular.yml
generators/server/templates/src/main/java/package/config/DatabaseConfiguration_couchbase.java.ejs
generators/server/templates/src/main/java/package/repository/AuthorityRepository.java.ejs
generators/server/templates/src/main/java/package/repository/N1qlCouchbaseRepository.java.ejs
generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs
generators/server/templates/src/main/resources/config/couchmove/changelog/V0__create_indexes.n1ql.ejs
generators/server/templates/src/test/java/package/web/rest/PublicUserResourceIT.java.ejs
generators/server/templates/src/test/java/package/web/rest/UserResourceIT.java.ejs

When trying to fix Couchbase tests, I discovered that since Spring Boot 2.5.4, the application doesn't use `JacksonAutoConfiguration#jacksonObjectMapper()` bean, which causes the application to fail since the modules are not loaded anymore. Adding manually the bean fixed the problem.
---

Fix and enable back Couchbase tests

---

generators/client/templates/angular/package.json.ejs
generators/client/templates/react/package.json.ejs
generators/client/templates/vue/package.json.ejs
generators/cypress/index.js

Update cypress e2e scripts to consider default headless mode and add a new npm script to execute tests in headed mode (default mode in JHipster).
Related #16127 

fix: Update cypress e2e npm scripts

---

.github/actions/build-matrix/action.yml
.github/workflows/devserver.yml
generators/client/__workflow/devserver-angular.json
generators/client/__workflow/devserver-react.json
generators/client/__workflow/devserver-vue.json
generators/client/templates/angular/package.json.ejs
generators/client/templates/react/package.json.ejs
generators/client/templates/react/webpack/webpack.common.js.ejs
generators/client/templates/react/webpack/webpack.dev.js.ejs
generators/client/templates/vue/package.json.ejs
generators/server/index.js
test-integration/scripts/99-print-matrix.js

- Fixes react development server
- Update npm scripts
- Update webpack config
- Disable source-map to workaround https://github.com/jhipster/generator-jhipster/issues/16116
- Add build-matrix action to allow dynamic workflows for modularized tests
- Add trailing `--` to composite npm scripts.
- Allows scripts to call others scripts passing escaped parameters (-- --arg) correctly.
Without needing double escaping `-- -- --arg`
- Add Dev Server workflow for testing webpack-devserver, browser sync and dev profile.
---

Fix react development server and add GitHub action for dynamic workflows.

---

generators/common/templates/README.md.jhi.ejs

Improve Auth0 documentation in README. 
NOTE: I was not able to get Cypress to work with Auth0. I set `E2E_USERNAME` and `E2E_PASSWORD`, but there are no successful tests.
```
Spec                                              Tests  Passing  Failing  Pending  Skipped
┌────────────────────────────────────────────────────────────────────────────────────────────────┐
│ ✖  administration/administration.spec.      00:03        5        -        1        -        4 │
│    ts                                                                                          │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✖  entity/album.spec.ts                     00:03        6        -        1        -        5 │ …
```

Minor Auth0 improvements

---

generators/client/templates/angular/src/main/webapp/app/login/login.service.ts.ejs
generators/client/templates/angular/src/main/webapp/app/login/logout.model.ts.ejs
generators/client/templates/react/src/main/webapp/app/modules/login/logout.tsx.ejs
generators/client/templates/react/src/main/webapp/app/shared/reducers/authentication.spec.ts.ejs
generators/client/templates/react/src/main/webapp/app/shared/reducers/authentication.ts.ejs
generators/client/templates/vue/src/main/webapp/app/core/jhi-navbar/jhi-navbar.component.ts.ejs
generators/cypress/templates/src/test/javascript/cypress/support/oauth2.ts.ejs
generators/server/templates/src/main/java/package/web/rest/LogoutResource.java.ejs
generators/server/templates/src/test/java/package/web/rest/LogoutResourceIT.java.ejs

Refactor OAuth2 logout REST API to prepare absolute logout URL on the server-side. With this change, we shall not need to change the API contract (to send additional data in response) and client code (to read/parse additional data to prepare the final URL) to support a new OAuth2 provider. 

chore: Refactor OAuth2 logout url preparation logic

---

generators/client/templates/vue/package.json
generators/client/templates/vue/src/main/webapp/app/shared/data/data-utils.service.ts.ejs
generators/client/templates/vue/src/test/javascript/spec/app/shared/data/data-utils.service.spec.ts.ejs

Fix: https://github.com/jhipster/generator-jhipster/pull/16071
But **IE support** is removed, is it a good solution?
**msSaveOrOpenBlob** is deprecated https://developer.mozilla.org/en-US/docs/Web/API/Navigator/msSaveOrOpenBlob
---

Vue: Upgrade Typescript / Remove IE support to open file?

---

generators/client/templates/angular/src/main/webapp/app/core/util/data-util.service.ts.ejs

Same as #16076
[msSaveOrOpenBlob ](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/msSaveOrOpenBlob) is deprecated and #16069 will faill.
[createObjectURL](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL) is supported since IE 10 (2012), so is safe to remove msSaveOrOpenBlob.
---

[Angular] Remove deprecated msSaveOrOpenBlob

---

generators/server/templates/pom.xml.ejs

The git-commit-id-plugin is moved to https://github.com/git-commit-id/git-commit-id-maven-plugin
---

Update git-commit-id-plugin 

---

generators/server/templates/pom.xml.ejs
generators/server/templates/src/main/java/package/config/DatabaseConfiguration_couchbase.java.ejs
generators/server/templates/src/main/java/package/config/WebConfigurer.java.ejs
generators/server/templates/src/main/java/package/web/rest/AccountResource.java.ejs

and fix one issue in the generated code
Modernizer Maven Plugin detects uses of legacy APIs which modern Java versions supersede - 
More about it here: https://github.com/gaul/modernizer-maven-plugin
---

Add modernizer-maven-plugin to detect legacy/deprecated API usage

---

generators/entity-server/templates/couchbase/src/main/java/package/repository/EntityRepository.java.ejs
generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs
generators/server/templates/src/test/java/package/web/rest/TestUtil.java.ejs

It seems that I was wrong here https://github.com/jhipster/generator-jhipster/pull/16102#issuecomment-910468828: the tests were passing because we are testing only using id. The `REQUEST_PLUS` consistency is still not available to N1QL Search requests.
---

Revert "Add consistency to search requests"

---

generators/server/templates/build.gradle.ejs
generators/server/templates/gradle.properties.ejs
generators/server/templates/settings.gradle.ejs

This plugin is a wrapper around modernizer-maven-plugin, but works in Gradle.
---

Add gradle-modernizer-plugin to detect legacy/deprecated API usage

---

generators/app/index.js

Related to https://github.com/jhipster/generator-jhipster-quarkus/pull/223#issuecomment-903716516
Currently:
1. Config are written at main generator
2. Custom options are written at main generator
3. Config are written again at blueprint, overwriting custom options.
Remove third step.
---

Don't overwrite .yo-rc.json at blueprint.

---

generators/server/templates/build.gradle.ejs
generators/server/templates/pom.xml.ejs
generators/server/templates/src/main/java/package/config/FeignConfiguration.java.ejs
generators/server/templates/src/main/resources/config/application.yml.ejs

This PR is an incomplete approach to replace spring cloud hystrix with spring cloud resilience4j. Open things:
* Health indicator or not. By default health indicators are disabled, see [here for the reason](https://resilience4j.readme.io/docs/getting-started-3#health-endpoint).
* OpenFeign does not yet support webflux/reactive. We use it in the gateway (which is now reactive only) and for reactive microservices. [Spring suggest](https://docs.spring.io/spring-cloud-openfeign/docs/current/reference/html/#reactive-support) to use https://github.com/Playtika/feign-reactive until spring cloud can support it via open feign. What should we do?
* I have create a "reactive microservice sample" via `jhipster jdl reactive-ms` and at least everything seems to work well
updates #14031
---
Please make …

replace spring-cloud-hystrix with spring-cloud-resilience4j

---

.github/release-drafter.yml

This PR excludes dependabot PRs from the auto generated changelist as this becomes totally unclear what is relevant and what not.
[skip-ci]
---

exclude dependabot from changelist

---

generators/server/templates/build.gradle.ejs
generators/server/templates/pom.xml.ejs

Allow Java 17, because it seems to work. https://twitter.com/mraible/status/1437859171110621188
---

Allow Java 17 to be used

---

.github/workflows/docker-image-publish-github-registry.yml

Use github CI to build latest Docker image on git push and store docker image on github registry
Signed-off-by: Pratik Raj <rajpratik71@gmail.com>
---

feat [CI] : Docker Image Build CI for Push image to github registry

---

generators/common/templates/.husky/pre-commit
generators/init/templates/.husky/pre-commit

Fixes https://github.com/jhipster/generator-jhipster/issues/16336
---

Replace npm exec with npx.

---

generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs
generators/server/templates/src/main/java/package/config/SecurityConfiguration_reactive.java.ejs

Replacing deprecated feature policy with permissions policy.
https://securityheaders.com/?q=https%3A%2F%2Fpermissionpolicy.herokuapp.com%2Fscotthelme.co.uk&followRedirects=on
closes #16362
---

replace feature policy with permission policy

---

.github/actions/compare-base/action.yml
.github/actions/compare/action.yml
.github/actions/generate/action.yml
.github/actions/setup/action.yml
test-integration/scripts/00-init-env.sh
test-integration/scripts/10-install-jhipster.sh
test-integration/scripts/12-generate-project.sh

Related to https://github.com/jhipster/generator-jhipster-quarkus/pull/225
---

Add custom cli to actions for blueprints.

---

generators/server/templates/settings.gradle.ejs

Generate build cache confguration when gradle enterprise is selected.
---

enabled build cache when gradle enterprise is selected

---

.github/workflows/docker-image-publish-github-registry.yml

Related to https://github.com/jhipster/generator-jhipster/issues/15881
---

Conditionally publish to docker hub.

---

generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.html.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.ts.ejs

[Angular] Loop for enums

---

.github/workflows/lock-maintenance.yml

Weekly bump transitional dependencies.
Package lock needs to be updated in order to keep transitional dependencies updated.
`npm install generator-jhipster` always installs latest transitional dependencies, we should not lag behind.
---

Add lock-maintenance workflow. [skip ci]

---

.github/workflows/label-cleanup.yml
.github/workflows/triage.yml

Label cleanup and triage actions are failing after an upgrade (https://github.com/jhipster/generator-jhipster/commit/a0ffa3017c5b21b78f4794a67afc9011554a9c62)
After upgrade to github-actions v5, the api for issues has changed to
`github.rest.issues` instead of `github.issues` https://github.com/actions/github-script#breaking-changes-in-v5
---

Fix triage and cleanup labeler actions

---

generators/server/templates/src/main/java/package/config/LocaleConfiguration.java.ejs

Importing WebFluxAutoConfiguration doesn't seem necessary and it causes issues with Spring Native.
---

Remove WebFluxAutoConfiguration for Spring Native compatibility

---

generators/client/files-vue.js
generators/client/templates/vue/src/main/webapp/app/admin/user-management/user-management-edit.component.ts.ejs
generators/client/templates/vue/src/main/webapp/app/admin/user-management/user-management-view.component.ts.ejs
generators/client/templates/vue/src/main/webapp/app/admin/user-management/user-management.component.ts.ejs
generators/client/templates/vue/src/main/webapp/app/main.ts.ejs
generators/client/templates/vue/src/main/webapp/app/shared/alert/alert.service.ts.ejs
generators/client/templates/vue/src/test/javascript/spec/app/admin/user-management/user-management-edit.component.spec.ts.ejs
generators/client/templates/vue/src/test/javascript/spec/app/admin/user-management/user-management-view.component.spec.ts.ejs
generators/client/templates/vue/src/test/javascript/spec/app/admin/user-management/user-management.component.spec.ts.ejs
generators/client/templates/vue/src/test/javascript/spec/app/shared/alert/alert.service.spec.ts.ejs
generators/entity-client/templates/vue/src/main/webapp/app/entities/entity-details.component.ts.ejs
generators/entity-client/templates/vue/src/main/webapp/app/entities/entity-update.component.ts.ejs
generators/entity-client/templates/vue/src/main/webapp/app/entities/entity.component.ts.ejs
generators/entity-client/templates/vue/src/test/javascript/spec/app/entities/entity-details.component.spec.ts.ejs
generators/entity-client/templates/vue/src/test/javascript/spec/app/entities/entity-update.component.spec.ts.ejs
generators/entity-client/templates/vue/src/test/javascript/spec/app/entities/entity.component.spec.ts.ejs

Add error handling for multiple scenarios in Vue with a toast.
Approach:- The errors are being shown in the toast through a service instead of interceptor to allow users more choice over generated code to pick and choose errors they wish to show/handle.
Fix #16393
---

[vue] Add error handling toast

---

CONTRIBUTING.md

jhipster/jhipster was changed to jhipster/jhipster-bom project as the former is deprecated now.
issue template link fix
---

Update links CONTRIBUTING guide.

---

generators/client/templates/react/package.json

Reverts jhipster/generator-jhipster#16907

Revert "chore(deps): bump react-router-dom from 5.3.0 to 6.0.0 in /generators/client/templates/react"

---

.github/workflows/lock-maintenance.yml

Force `npm install` to workaround eslint peer dependency conflict. [skip ci]

---

generators/server/templates/src/test/java/package/security/oauth2/AuthorizationHeaderUtilTest.java.ejs

OAuth2AccessToken require expiryTime to be after issuedTime.
Fix #16570
I've redone this PR reverting the change of the enforcer plugin back to 3.0.0-M3,
The enforcer plugin now remains at version 3.0.0
---

Fix error for expired oauth2 token in unit test

---

generators/server/templates/src/main/java/package/security/oauth2/CustomClaimConverter.java.ejs
generators/server/templates/src/main/java/package/service/UserService.java.ejs
generators/server/templates/src/test/java/package/security/oauth2/CustomClaimConverterIT.java.ejs

Add logic to handle `name` and `email` claims when acting as a resource server. Makes it so Ionic4J will work with Auth0. 
---

Handle Auth0 claims when acting as an OAuth 2.0 resource server

---

generators/aws/lib/eb.js

**Summary:**
Upgrade AWS beanstalk platform
FROM => Tomcat 8.5 with Java 8 running on 64bit Amazon Linux
TO => Tomcat 8.5 with Corretto 11 running on 64bit Amazon Linux 2
Fix [#16152](https://github.com/jhipster/generator-jhipster/issues/16152)
Fix [#12394](https://github.com/jhipster/generator-jhipster/issues/12394)
**Context:**
The most recent version of Jhipster requires a minimum JDK 11. However, the selected beanstalk platform only supported version JDK 8.
Old tomcat does not deploy Jhipster, which causes 404 errors in both issues.
**Fix:**
The function filterSolutionStackNames returns the first result with pattern "Tomcat 8" which is wrong. I propose to change the pattern with "Tomcat 8.5 Corretto 11" to fix.
```
console.table(data.SolutionStacks.filter((element) => …
```

Upgrade AWS Tomcat version [skip-ci]

---

cli/import-jdl.js
cli/program.js
generators/bootstrap/index.js
generators/generator-transforms.js
generators/upgrade/index.js

When file conflicts, it becomes invalid.
So prettier fails to parse its configuration (package.json, .prettierrc) or to parse the file.
Upgrade must ignore prettier errors.
Related to https://github.com/jhipster/generator-jhipster/issues/17072.
---

Adjusts to upgrade on files conflicts.

---

.github/workflows/stale.yml

Add v8 label to stale exempt

---

cli/import-jdl.js
generators/app/index.js
generators/bootstrap/index.js
generators/client/index.js
generators/client/needle-api/needle-client-angular.js
generators/client/templates/vue/src/main/webapp/app/declarations.d.ts.ejs
generators/client/templates/vue/src/main/webapp/app/main.ts.ejs
generators/client/templates/vue/src/main/webapp/app/router/entities.ts.ejs
generators/client/templates/vue/src/main/webapp/app/router/index.ts.ejs
generators/client/templates/vue/src/test/javascript/jest.conf.js.ejs
generators/client/templates/vue/tsconfig.json.ejs
generators/client/templates/vue/tsconfig.spec.json.ejs
generators/client/templates/vue/webpack/webpack.microfrontend.js.jhi.vue.ejs
generators/cypress/templates/cypress.json.ejs
generators/entity-client/files.js
generators/entity-client/index.js
generators/entity-client/templates/common/src/test/javascript/cypress/integration/entity/entity.spec.ts.ejs
generators/entity/index.js
generators/generator-base.js
generators/server/index.js
test-integration/jdl-samples/vue-blog-store-microfrontend/blog-store.jdl
test/client/__snapshots__/angular.spec.js.snap
test/client/__snapshots__/vue.spec.js.snap
test/client/angular.spec.js
test/client/react.spec.js
test/client/vue.spec.js
test/needle-api/needle-client-vue.spec.js

jhipster-internals:
- Make commit pipeline easier to understand.
microfrontend support:
- Deprecate microfrontend cli option. Since it is experimental, it will be removed for v7.5.0
- Fixes to vue microfrontend jest test, top level await will not be testable by jest anytime soon (requires esm), the alternative implementation is bigger.
- Move cypress tests to the microservice side, instead of the gateway. (vue, angular still pending).
Related to https://github.com/jhipster/generator-jhipster/issues/17031
---

Improvements to microfrontend support.

---

generators/entity-server/files.js
generators/entity-server/templates/src/main/java/package/repository/search/EntitySearchRepository.java.ejs
generators/entity-server/templates/src/main/java/package/repository/search/SortToFieldSortBuilderConverter.java.ejs
test/entity.spec.js

Fix #17018
Add SortToFieldSortBuilderConverter for SearchRepositoryInternal to append ".keyword" suffix to sort property for elasticsearch paginated queries.
---

add sort converter to elasticsearch search repository

---

generators/server/templates/src/main/java/package/config/neo4j/Neo4jMigrations.java.ejs

Fixes broken build mentioned in #17308.

Adapt to Neo4j-Migrations 1.x API.

---

generators/server/index.js

The profile webapp is meant for dev profile only, prod profile has webapp steps included.
Disabling webapp profile with `-P-webapp` won't work for prod, switch to `-Dskip.installnodenpm -Dskip.npm` that should work with both.
---

Improve logic to skip frontend. [maven]

---

generators/server/templates/build.gradle.ejs

While reading the Gradle documentation to configure Gradle to use my private Nexus repository, I ran into this advice in the [official documentation](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:case-for-maven-local) regarding maven repositories:
> As a general advice, you should avoid adding `mavenLocal()` as a repository...
Existing code: 
https://github.com/jhipster/generator-jhipster/blob/1b76ae1b002eaf9498e9cbc190fb675de991624f/generators/server/templates/build.gradle.ejs#L283-L285
As stated in the doc's chapter ["Obtaining module metadata"](https://docs.gradle.org/current/userguide/dependency_resolution.html#obtaining_module_metadata):
> - Each repository is inspected in order.
>   - Depending on the type of repository, Gradle looks for metadata files …

Avoid using mavenLocal() in build.gradle?

---

.github/dependabot.yml
generators/client/templates/angular/package.json.ejs

Use new npm overrides to force webpack version.
angular-cli force a specific version and requires it to be the same.
By forcing our version we will not need to manually since webpack version.
---

Override angular webpack version.

---

.github/dependabot.yml
.github/workflows/generator.yml
Dockerfile
generators/client/templates/angular/package.json
generators/client/templates/react/package.json
generators/client/templates/vue/package.json
generators/generator-constants.js
test-integration/scripts/99-print-node-version.sh
test/__snapshots__/ci-cd.spec.js.snap

`@types/node` should match supported node major version.
We support node 16 at generated projects. So adjust `@types/node` to version 16.
---

Bump node to 16.13.1 and adjust @types/node

---

generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs

Fix some sonar issues:
- https://sonarcloud.io/project/issues?id=jhipster-sample-application&open=AW7IFzYozz0zKTgJXRom&resolved=false&types=CODE_SMELL
- https://sonarcloud.io/project/issues?id=jhipster-sample-application&open=AW7IFzYWzz0zKTgJXRoi&resolved=false&types=CODE_SMELL
- ...
---

Sonar: Remove this unused import 'org.springframework.http.HttpStatus'

---

generators/client/templates/react/package.json.ejs
generators/client/templates/react/src/main/webapp/app/shared/layout/header/header.scss.ejs
generators/client/templates/react/src/main/webapp/app/shared/layout/header/header.tsx.ejs
generators/cypress/templates/cypress.json.ejs
generators/cypress/templates/src/test/javascript/cypress/integration/account/login-page.spec.ts.ejs
generators/cypress/templates/src/test/javascript/cypress/integration/account/password-page.spec.ts.ejs
generators/cypress/templates/src/test/javascript/cypress/integration/account/register-page.spec.ts.ejs
generators/cypress/templates/src/test/javascript/cypress/integration/account/reset-password-page.spec.ts.ejs
generators/cypress/templates/src/test/javascript/cypress/integration/account/settings-page.spec.ts.ejs
generators/cypress/templates/src/test/javascript/cypress/integration/administration/administration.spec.ts.ejs
generators/cypress/templates/src/test/javascript/cypress/support/commands.ts.ejs
generators/cypress/templates/src/test/javascript/cypress/support/index.ts.ejs
generators/cypress/templates/src/test/javascript/cypress/support/navbar.ts.ejs
generators/cypress/templates/src/test/javascript/cypress/support/oauth2.ts.ejs
generators/entity-client/templates/common/src/test/javascript/cypress/integration/entity/entity.spec.ts.ejs

Fixes https://github.com/jhipster/generator-jhipster/issues/16545.
- No page visits is done at login process.
- Removes forced clicks.
- Reduces differences between authentication implementations.
- Reduces differences between client framework implementations.
- Big gain in oauth2 authentication performance.
- Small loss in jwt/session authentication performance due to each test cleanup overhead.
---

Implement cypress session

---

generators/client/templates/vue/src/main/webapp/app/shared/config/formatter.ts.ejs
generators/client/templates/vue/src/main/webapp/app/shared/data/data-utils.service.ts.ejs

Fix: **_Use a regular expression literal instead of the 'RegExp' constructor_**
Related to https://github.com/jhipster/generator-jhipster/issues/17468
---

[Vue] Sonar

---

generators/generator-constants.js

Got me crazy why local jhipster-dependencies wasn't working.
---

Bump jhipster-dependencies to 7.5.2-SNAPSHOT

---

generators/entity-server/templates/src/main/java/package/repository/rowmapper/EntityRowMapper.java.ejs
generators/server/__snapshots__/generator.spec.mjs.snap
generators/server/files.js
generators/server/index.js
generators/server/templates/src/main/java/package/repository/ColumnConverter.java.ejs
generators/server/templates/src/main/java/package/repository/rowmapper/UserRowMapper.java.ejs

Related to https://github.com/jhipster/generator-jhipster/issues/17520 and https://github.com/jhipster/generator-jhipster/pull/17521
ColumnConverter is only used at repository layer, move there.
---

Move ColumnConverter from service to repository

---

test-integration/jdl-samples/blog-store/blog-store.jdl

Microservices tests are randomly failing.
Probably due to slow startup.
Switch from mongodb to Postgres to improve that.
---

Switch jdl sample to postgres.

---

generators/client/templates/vue/src/main/webapp/app/admin/user-management/user-management-edit.component.ts.ejs
generators/client/templates/vue/src/main/webapp/app/admin/user-management/user-management-view.component.ts.ejs
generators/client/templates/vue/src/main/webapp/app/admin/user-management/user-management.component.ts.ejs
generators/client/templates/vue/src/main/webapp/app/main.ts.ejs
generators/client/templates/vue/src/test/javascript/spec/app/admin/user-management/user-management-edit.component.spec.ts.ejs
generators/client/templates/vue/src/test/javascript/spec/app/admin/user-management/user-management-view.component.spec.ts.ejs
generators/client/templates/vue/src/test/javascript/spec/app/admin/user-management/user-management.component.spec.ts.ejs

[Vue] Fix: this.userManagementService is not a function

---

generators/cypress/files.js
package-lock.json
package.json
utils/faker.js

Since original faker was abruptly discontinued, the community got involved and there is an 'official' fork maintained at https://github.com/faker-js/faker.
Is this fork 'official'?
Yes, at least for opencollective https://opencollective.com/fakerjs.
The fakerjs collective has been transferred to the new maintainers. The new maintainers transferred the old funds to fakers-legacy collective.
More info https://fakerjs.dev/update.html#funding-yml.
IMO it's safe to move on.
---

Switch to @faker-js/faker

---

generators/server/templates/pom.xml.ejs

Bump maven-jar-plugin to 3.2.2

---

generators/server/templates/src/main/resources/config/application-dev.yml.ejs

Replace `allowed-origins` setting with `allowed-origin-patterns` to allow simplified CORS support for both local and GitHub Codespaces usages
Co-authored-by: Sandra Ahlgrimm <Sandra.Kriemann@gmail.com>
---

Fix CORS config for usage in Codespaces

---

generators/common/templates/sonar-project.properties.ejs

A multicriteria issue exclusion uses the rule key 'squid:S4502' that has been changed. The pattern should be updated to 'java:S4502'
From SonarCloud:
---

Sonar rule key 'squid:S4502' has been changed to 'java:S4502'

---

generators/server/templates/src/main/resources/config/application.yml.ejs

This PR Fix #17777
Exposes any property from the Environment whose name starts with `info.`.
Docs: https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#:~:text=info.properties%20resource.-,env,None.,-git
Fix the missing `display-ribbon-on-profiles` in the `/management/info` call (I just upgraded from JHipster v7.4.0 to v7.6.0 and noticed its missing) 
Before:
After:
---

Expose properties from the Environment whose name starts with info

---

generators/client/templates/angular/package.json
generators/client/templates/react/package.json
generators/client/templates/vue/package.json

Our swagger plugins are broken at >=4.3.0
---

Downgrade swagger-ui to 4.2.1

---

generators/generator-base-docker.js
generators/generator-constants.js
generators/server/__snapshots__/generator.spec.mjs.snap
generators/server/files.js
generators/server/index.js
generators/server/templates/pom.xml.ejs
generators/server/templates/src/main/docker/zipkin.yml.ejs
generators/server/templates/src/main/resources/config/application-dev.yml.ejs
generators/server/templates/src/main/resources/config/application-prod.yml.ejs
test-integration/scripts/20-docker-compose.sh
test/__snapshots__/app-client-custom-path.spec.js.snap
test/__snapshots__/app.spec.js.snap
test/__snapshots__/server.spec.js.snap
test/blueprint/__snapshots__/app-blueprint.spec.js.snap
test/blueprint/__snapshots__/scoped-blueprint.spec.js.snap

fix #17487
This pull request :
- fixes the wrong zipkin dependency
- fixes sleuth async executor
- add a docker compose zipkin
---

Update sleuth/zipkin dependencies

---

generators/entity-client/templates/react/src/main/webapp/app/entities/entity-reducer.spec.ts.ejs
generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs

Fixes #17823
Makes sure the right names are being used in the generated frontend tests. And not static "id".
---

Fix compilation error on custom primary key fields

---

cli/jhipster.js
cli/program.js

- cli:
- change message from `Using JHipster version installed globally` to `Using bundled JHipster`
- change message from `Using JHipster version installed locally in current project's node_modules` to `Switching to JHipster installed locally in current project's node repository (node_modules)`
- print `Using bundled JHipster` if the current jhipster is already in current project's repository. Ex: `npx jhipster`
- allow commands to set a custom `useOptions` to force some options.
Or current cli switching to current project repository jhipster is not node/npm default, so we need to improve our messages.
---
When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, …

Improve jhipster cli global/local messages.

---

test-integration/jdl-samples/blog-store-react-jwt-consul/blog-store.jdl
test-integration/jdl-samples/blog-store/blog-store.jdl

Caused by https://github.com/jhipster/generator-jhipster/pull/17853.
Changes to test samples doesn't trigger tests due to before/after identical source.
Workaround https://github.com/jhipster/generator-jhipster/pull/17778.
And a bug with user synchronization https://github.com/jhipster/generator-jhipster/issues/17889.
---

Workaround bugs.

---

generators/client/templates/vue/src/main/webapp/app/core/jhi-navbar/jhi-navbar.component.ts.ejs

fixes bug where the browser window hangs when hasAnyAuthority is used multiple times
with different roles on the same page
Fixes #17627
---

fix application hanging with multiple role checks

---

generators/generator-base-private.js

fix the reversed version problem for maven-enforcer-plugin rule config
when generating jhipster with a low version of java
Fix #18038
---

fix the reversed version problem for maven-enforcer-plugin rule config

---

generators/client/templates/angular/jest.conf.js.ejs
generators/client/templates/vue/src/test/javascript/jest.conf.js.ejs

Other linting warnings that we might want to fix:
```
/Users/mraible/dev/21-points/src/test/javascript/cypress/integration/entity/blood-pressure.spec.ts
1:10  warning  'entityItemSelector' is defined but never used  @typescript-eslint/no-unused-vars
21:22  warning  Unexpected any. Specify a different type        @typescript-eslint/no-explicit-any
48:11  warning  Forbidden non-null assertion                    @typescript-eslint/no-non-null-assertion
72:18  warning  Forbidden non-null assertion                    @typescript-eslint/no-non-null-assertion
113:18  warning  Forbidden non-null assertion                    @typescript-eslint/no-non-null-assertion
124:18  warning  Forbidden non-null assertion                    @typescript-eslint/no-non-null-assertion
134:18  warning  Forbidden …
```

Fix issue: Replace any occurrences of 'ts-jest/utils' with just 'ts-jest`

---

generators/server/templates/src/main/java/package/security/jwt/JWTFilter.java.ejs
generators/server/templates/src/main/java/package/security/jwt/TokenProvider.java.ejs
generators/server/templates/src/test/java/package/security/jwt/JWTFilterTest.java.ejs

Replace deprecated Mono.subscriberContext by Mono.contextWrite

---

generators/bootstrap-application/generator.spec.mjs
generators/entity-server/templates/src/main/java/package/common/inject_template.ejs
generators/entity-server/templates/src/main/java/package/service/mapper/EntityMapper.java.ejs
generators/server/templates/src/main/resources/config/application.yml.ejs
generators/server/templates/src/test/resources/config/application.yml.ejs
utils/field.js
utils/relationship.js

Mapstruct mapper were reusing relationship otherEntity mappers causing a circular dependency.
With this PR, relationship mappers are generated at the entity mapper itself, removing external mappers reuse.
Fixes https://github.com/jhipster/generator-jhipster/issues/17774.
---

Drop allow-circular-references.

---

generators/server/templates/src/main/docker/mysql.yml.ejs

Just adding the mentioned configuration to support running mysql under m1 architecture
closes #18085
---

configure mysql docker image to run with m1 macs

---

generators/entity-client/templates/common/src/test/javascript/cypress/integration/entity/entity.spec.ts.ejs
generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
test-integration/samples/.jhipster/MapsIdChildEntityWithDTO.json
test-integration/samples/.jhipster/MapsIdChildEntityWithoutDTO.json
test-integration/samples/.jhipster/MapsIdGrandchildEntityWithDTO.json
test-integration/samples/.jhipster/MapsIdGrandchildEntityWithoutDTO.json
test-integration/samples/.jhipster/MapsIdParentEntityWithDTO.json
test-integration/samples/.jhipster/MapsIdParentEntityWithoutDTO.json
test-integration/samples/.jhipster/MapsIdUserProfileWithDTO.json
test-integration/scripts/11-generate-config.sh
test-integration/scripts/11-generate-entities.sh
utils/relationship.js

when a relationship is used with the jpaDerivedIdentifier option and the
related entity also has a relationship with that option set the
`updateEntityMapsIdAssociationWithNewId` test fails. This
is caused by the `createUpdatedEntity` reusing the needed parent
entity. This can't work because a parent entity, which already has a child,
can't be used as the parent for a new entity. The reason being
jpaDerivedIdentifier enforces that parent and child share the same id,
which can't be fulfilled with a reused parent entity.
Remove the reuse of the parent entity in `createUpdatedEntity` when the
entity uses jpaDerivedIdentifier to fix the test.
Fixes #17906
--- …

fix test when nested jpaDerivedIdentifier is used

---

test-integration/scripts/99-build-changes.sh

`git diff` is always recursive.
Fix condition by splitting the non recursive condition.
---

Fix build-matrix common detection.

---

generators/generator-constants.js

Solves this error on Java 18:
```
[INFO] --- maven-enforcer-plugin:3.0.0:enforce (enforce-versions) @ flickr-2 ---
[WARNING] Rule 1: org.apache.maven.plugins.enforcer.RequireJavaVersion failed with message:
You are running an incompatible version of Java. JHipster supports JDK 11 to 17.
```
---

Add support for Java 18

---

generators/client/templates/vue/src/main/webapp/app/core/jhi-navbar/jhi-navbar.component.ts.ejs

OAuth2+Logout is broken since v7.5.0
It was removed here https://github.com/jhipster/generator-jhipster/pull/17162/files
---

OAuth2: fix logout

---

generators/server/templates/src/test/java/package/service/MailServiceIT.java.ejs

When generating a project with i18n support, but without choosing English as either the default language or an additional language, a test case in `MailServiceIT` won't pass as the language key "en" is hardcoded.
I have included a log file showing the result of `mvnw -ntp -Pprod verify` with the given configuration. This is the interesting part
```
[INFO] Running com.mycompany.myapp.service.MailServiceIT
2022-03-28 11:48:10.804  WARN 2694 --- [           main] com.mycompany.myapp.service.MailService  : Email could not be sent to user 'john.doe@example.com'
org.springframework.mail.MailSendException: null
[ERROR] Tests run: 10, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.758 s <<< FAILURE! - in com.mycompany.myapp.service.MailServiceIT
[ERROR] …
```

fix email test without "en" i18n

---

.github/workflows/angular.yml
.github/workflows/devserver.yml
.github/workflows/generator.yml
.github/workflows/generators.yml
.github/workflows/gradle-wrapper-validation.yml
.github/workflows/labeler.yml
.github/workflows/lock-maintenance.yml
.github/workflows/react.yml
.github/workflows/release-drafter.yml
.github/workflows/vue.yml

- Pinned actions by SHA https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
>Pin actions to a full length commit SHA
>Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release. Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository, as they would need to generate a SHA-1 collision for a valid Git object payload.
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
Also, dependabot supports upgrading based on SHA.
Signed-off-by: naveensrinivasan …

Add permissions to GitHub actions

---

generators/entity-server/templates/src/main/java/package/repository/EntityRepositoryInternalImpl_reactive.java.ejs
generators/entity-server/templates/src/main/java/package/repository/EntityRepository_reactive.java.ejs
generators/server/templates/src/main/java/package/repository/EntityManager.java.ejs

Instead of using criteria for where clause this workaround uses conditions directly where needed (find by id).
closes #18269
---

use conditions instead of criteria as workaround

---

.github/release-drafter.yml

With this configuration dependabot PRs are excluded and only PRs with label "release-notes" (must be added manually to a PR) are added to release notes. Hope this works now, at least thats what the documentation says.
Relates too #18319 
---

adapt release drafter config to have smaller github release notes

---

generators/common/templates/README.md.jhi.ejs
generators/generator-constants.js
generators/openapi-client/files.js
generators/openapi-client/index.js
generators/server/templates/pom.xml.ejs

Fix #14287
This PR update the openapi-cli to the latest version (not sure if people use the `openapi-client` generator).
The command was renamed to `openapi-generator-cli` instead of `openapi-generator` with the new version.
---

Update open-api version

---

generators/languages/templates/src/main/webapp/i18n/hr/global.json.ejs

The Croatian translation for global.entity.action.view is correct #18386

fix Croatian translation for global.entity.action.view #18386 

---

generators/server/templates/gradle/profile_dev.gradle.ejs

We define it already in main build file, no need to have it dev profile again.
---

define boot dev tools only in main gradle

---

generators/server/cleanup-angular.js
generators/server/cleanup-cassandra.js
generators/server/cleanup-cucumber.js
generators/server/cleanup-elasticsearch.js
generators/server/cleanup-gradle.js
generators/server/cleanup-h2.js
generators/server/cleanup-hazelcast.js
generators/server/cleanup-kafka.js
generators/server/cleanup-maven.js
generators/server/cleanup-mongodb.js
generators/server/cleanup-oauth2.js
generators/server/cleanup-postgresql.js
generators/server/cleanup-reactive.js
generators/server/cleanup.js

This pr is meant to help the future split of server variant into multiple generator or sub folders
---

Split server cleanup in multiple files

---

generators/database-changelog-liquibase/index.js

details explained here on why this is needed
https://stackoverflow.com/questions/25517989/why-cant-i-redefine-a-property-in-a-javascript-object
---

Fix prepareFakeData with recursive relationships

---

generators/server/templates/gradle/profile_dev.gradle.ejs
generators/server/templates/gradle/profile_prod.gradle.ejs

This sets the derived profiles for bootRun command. I will open another issue for something else I discovered while fixing this.
closes #18531
---

set profiles for bootRun command

---

generators/server/templates/gradle.properties.ejs

This fixes the annoying slf4 logger binding warning when using e.g. bootRun. See https://github.com/n0mer/gradle-git-properties/issues/203 for details.
CC @mraible 
---

update gradle git properties to get rid of slf4j warnings

---

generators/client/templates/vue/src/test/javascript/jest.conf.js.ejs

Temporary reduce threshold to resume dependabot.
Related to https://github.com/jhipster/generator-jhipster/issues/18567.
---

Reduce vue branch threshold to 57 for microfrontends.

---

generators/server/templates/src/test/java/package/web/rest/UserResourceIT.java.ejs

Use randomAlphanumeric instead of random for password in tests codes 

---

generators/entity/index.js
generators/entity/prompts.js
generators/generator-base.js
generators/sql-constants.js
test/generator-base.spec.js

Fix https://github.com/jhipster/generator-jhipster/issues/18424
---
- [n/a] Tests are added where necessary
- [n/a] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [n/a] Documentation is added/updated where necessary

Increase oracle name limit

---

generators/client/needle-api/needle-client-angular.js
generators/client/templates/angular/src/main/webapp/declarations.d.ts.ejs
generators/cypress/files.js
generators/entity-client/files.js
generators/entity-client/index.js
jdl/jhipster/default-application-options.js
test-integration/jdl-samples/ms-mf-ngx-consul-jwt-neo4j/blog-store.jdl
test-integration/jdl-samples/ms-mf-react-eureka-oauth2-mariadb-infinispan/blog-store.jdl
test-integration/jdl-samples/ms-mf-vue-consul-oauth2-mysql-memcached/blog-store.jdl
test-integration/workflow-samples/angular.json
test-integration/workflow-samples/react.json
test-integration/workflow-samples/vue.json
utils/entity.js

Before https://github.com/jhipster/generator-jhipster/pull/18254 entities were required to link a gateway to microfrontends. For this reason, entities with microserviceName needed to be skipped.
This PR reenable microservices entities generation at gateway side (frontend) when microfrontend support is enabled.
This is a breaking change to existing microfrontend gateway applications.
Microfrontend entities need to be deleted from gateway’s `.jhipster` folder, otherwise the entities will have its frontend generated at gateway side.
- Enable microservices entities frontend generation at gateways when microfrontend flag is enabled.
- Removes legacy per entity microfrontend support from angular.
- Don’t generate some cypress common tests at microfrontend side.
- Convert vue and react mf test …

Add support to mixed microservice/microfrontend.

---

generators/entity-server/templates/src/main/java/package/domain/Entity.java.jhi.elastic_search.ejs

to allow elasticsearch repositories detect id fields
fixes #18704
---

Add spring data annotation for custom id fields

---

cli/import-jdl.js

throw when different client frameworks are used for microfrontends

---

generators/common/files.js
generators/common/index.js

This fixes a error you get from husky after trying to commit for the first time after starting a new project:
```
hint: The '.husky/pre-commit' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.
```
I think `_install()` is the right function to put this in. Tried putting it in `_postWriting()`, but the chmod was running too early it seems. Also tried `_end()`, but it was getting run after the git repo and initial commit were already made. But please let me know if there's a better place to put this.
And I formatted the log message similar to how I had seen it elsewhere:
https://github.com/jhipster/generator-jhipster/blob/v7.8.1/generators/kubernetes-helm/index.js#L177-L186
Fix #18537
---
Please make sure the …

Make husky script executable

---

generators/cypress/templates/src/test/javascript/cypress/support/commands.ts.ejs

Since the login function is defined here:
https://github.com/jhipster/generator-jhipster/blob/b474b1ea960d604da6fa19fc06cac43acbec434c/generators/cypress/templates/src/test/javascript/cypress/support/commands.ts.ejs#L133-L136
and used here without constraints:
https://github.com/jhipster/generator-jhipster/blob/61a47dbe197873286f815b5fc37e55445842e477/generators/entity-client/templates/common/src/test/javascript/cypress/integration/entity/entity.spec.ts.ejs#L61-L63
the constraints around the declaration should be removed.
---

Remove constraint for login function

---

generators/server/index.js

Fixes daily-build regressions related to npm scripts migration.
---

fixes daily-build regressions related to npm scripts migration

---

cli/import-jdl.js
generators/workspaces/index.js

Current jdl generation makes npm workspaces unsuitable for auto install.
So disable it by default.
npm 8.<something> changed the workspaces behavior by deduping dependencies to the root.
We generate applications in parallel, so `install` will be executed 3 times in same npm tree causing lots of problems.
We need to execute `npm install` only once.
---

skip applications install when generating workspaces.

---

generators/entity-server/templates/src/main/java/package/domain/Entity.java.jhi.elastic_search.ejs
generators/entity-server/templates/src/main/java/package/repository/search/EntitySearchRepository.java.ejs
test-integration/samples/jdl-entities/custom-id.jdl

when elasticsearch is enabled. We do add Spring Data
Transient annotation on the non-owning side
of relationships to break the artificial cycle introduced with the
bidirectional relationship model
Fix #18729
Fix #14840
Fix #16136
---

Avoid StackoverflowError when updating entity

---

generators/docker-compose/index.js
generators/server/templates/src/main/docker/app.yml.ejs
generators/server/templates/src/main/docker/cassandra-migration.yml.ejs
test-integration/jdl-samples/ms-react-consul-jwt-cassandra-redis/blog-store.jdl
test/__snapshots__/docker-compose.spec.js.snap
test/templates/compose/05-cassandra/src/main/docker/cassandra.yml

- don't generate cassandra-node at app.yml and docker compose, it's not required.
- adjust cassandra template
- cassandra+reactive is not supported, use imperative instead and add TODO
- cassandra+gateway(reactive) is not supported, nodb + jwt is not supported, use gateway with postgresql.
---

switch cassandra sample to cassandra db

---

generators/client/templates/vue/webpack/webpack.dev.js.ejs
generators/client/templates/vue/webpack/webpack.prod.js.ejs

Fix #17573 
> basically, cache invalidation was removed with [this commit](https://github.com/jhipster/generator-jhipster/commit/89364a74735f19bab0f54d437b4d08fe0f216a54)
---

Restored cache invalidation for Vue client

---

generators/client/templates/react/src/main/webapp/app/shared/error/error-loading.tsx.ejs
generators/client/templates/react/src/main/webapp/app/shared/error/page-not-found.tsx.ejs
generators/client/templates/react/src/main/webapp/app/shared/layout/menus/menu-item.tsx.ejs

Remove class component usage

---

generators/generator-base.js
generators/server/needles.cjs
lib/support/base.cjs
lib/support/base.spec.mjs
lib/support/needles.cjs

Allows needles to cascade with file defined by the needle:
```js
insertFooInSpecificFile(generator)(
insertBar(),
insertBar2()
)
```
Old notation needs the file:
```js
generator.editFile(
'specificFile',
insertFooInSpecificFile(),
insertBar(),
insertBar2()
)
```
`editFile` is new so it’s not a breaking change.
---

allow editFile to cascade callbacks.

---

.github/workflows/angular.yml
.github/workflows/react.yml
.github/workflows/vue.yml

The build fails otherwise with the missing results.
Example: https://github.com/jhipster/generator-jhipster/runs/6917256799?check_suite_focus=true
---

disable sonar at ci if frontend or backend were skiped.

---

test-integration/samples/ngx-gradle-fr/.yo-rc.json
test-integration/samples/ngx-mariadb-oauth2-sass-infinispan/.yo-rc.json

- switch devDatabaseType to h2disk at ngx-gradle-fr
fix https://github.com/hipster-labs/jhipster-daily-builds/runs/6934779695?check_suite_focus=true
- [switch devDatabaseType to h2disk at ngx-mariadb-oauth2-sass-infinispan](https://github.com/jhipster/generator-jhipster/pull/18947/commits/b0edf95a7d6464b092303148282565d2afb4f681)
fix https://github.com/hipster-labs/jhipster-daily-builds/runs/6934779784?check_suite_focus=true
---

update samples for daily builds

---

generators/database-changelog-liquibase/templates/src/main/resources/config/liquibase/fake-data/table_entity.csv.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/route/entity-management-routing-resolve.service.spec.ts.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/route/entity-management-routing-resolve.service.ts.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.html.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.spec.ts.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.ts.ejs

With typed forms, we will probably switch to more strict types like making id required.
A empty Entity will not be valid.
Related to https://github.com/jhipster/generator-jhipster/issues/18817 and https://github.com/jhipster/generator-jhipster/pull/18586.
---

angular: when creating, resolve routing to null

---

generators/generator-base-private.js
test/generator-base-private.spec.js
utils/field.js

`getTypescriptKeyType` only maps ids types, create `getTypescriptType` for all field types.
Related to https://github.com/jhipster/generator-jhipster/issues/18817 and https://github.com/jhipster/generator-jhipster/pull/18586.
---

implement getTypescriptType

---

generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.html.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.ts.ejs

Leave list unsorted if non-sortable field is used
Especially corrects broken search for non-sortable primary keys
Fixes https://github.com/jhipster/generator-jhipster/issues/18720
Also corrects the issue of non-clearable filters that had been implemented by me in #18621 but was missed to be changed in #18884 (there, the sort change event handler was updated, same is now also done for the filtering)
---

Clear sort if unsortable

---

generators/server/templates/src/main/docker/app.yml.ejs

The spring cloud config file directories configured in app.yml ,should be the docker-config, not be localhost-config.
---

fix config directories in app.yml

---

generators/workspaces/index.js

There is a new RXJS version.
When installing workspaces, concurrently is installing v7.5.6, while inside workspaces the required version is v7.5.5.
This is causing conflict between RXJS imported directly and RXJS imported by angular.
---

Use specific RXJS version at workspace root.

---

generators/client/templates/vue/package.json
generators/client/templates/vue/src/main/webapp/app/account/login-form/login-form.component.ts.ejs
generators/client/templates/vue/src/main/webapp/app/admin/user-management/user-management-edit.component.ts.ejs
generators/client/templates/vue/src/main/webapp/app/shared/alert/alert.service.ts.ejs
generators/client/templates/vue/src/test/javascript/spec/app/account/register/register.component.spec.ts.ejs
generators/entity-client/templates/vue/src/main/webapp/app/entities/entity-update.component.ts.ejs

Fix https://github.com/jhipster/generator-jhipster/pull/19137
---

[Vue] Upgrade 2.7.5

---

generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs

Fix
```
2022-07-18 22:36:52.353  WARN 80665 --- [  restartedMain] o.s.s.c.a.web.builders.WebSecurity       : You are asking Spring Security to ignore Ant [pattern='/**', OPTIONS]. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
2022-07-18 22:36:52.353  WARN 80665 --- [  restartedMain] o.s.s.c.a.web.builders.WebSecurity       : You are asking Spring Security to ignore Ant [pattern='/app/**/*.{js,html}']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
2022-07-18 22:36:52.353  WARN 80665 --- [  restartedMain] o.s.s.c.a.web.builders.WebSecurity       : You are asking Spring Security to ignore Ant [pattern='/i18n/**']. This is not recommended -- please use permitAll via …
```

fix spring security warning

---

.github/dependabot.yml
generators/client/templates/angular/package.json.ejs
generators/client/templates/react/package.json
generators/client/templates/react/package.json.ejs
generators/client/templates/vue/package.json
generators/client/templates/vue/package.json.ejs

Reverts jhipster/generator-jhipster#19159
bootstrap@5.2.0 has been released.

Revert "workaround intrusive warning due to deprecated bootstrap property"

---

generators/generator-constants.js
generators/kubernetes/templates/ingress.yml.ejs
generators/kubernetes/templates/monitoring/jhipster-grafana.yml.ejs
test/__snapshots__/kubernetes.helm.spec.js.snap
test/__snapshots__/kubernetes.spec.js.snap

Since Kubernetes version 1.22 the `Ingress` resource version `v1beta1` is deprecated and no longer supported.
Using the old version prevents users of k8s version 1.22+ to deploy our generated k8s manifests
---

updates k8s ingress resource to generate the current non-deprecated format

---

generators/gae/index.js

Update spring-boot-thin-layout to version 1.0.28.RELEASE
fix #17639
Error: An API incompatibility was encountered while executing org.springframework.boot:spring-boot-maven-plugin:2.5.8:repackage: java.lang.AbstractMethodError: Receiver class org.springframework.boot.loader.thin.ThinLayout does not define or inherit an implementation of the resolved method 'abstract java.lang.String getLibraryLocation(java.lang.String, org.springframework.boot.loader.tools.LibraryScope)' of interface org.springframework.boot.loader.tools.Layout.
---

Update spring-boot-thin-layout to version 1.0.28.RELEASE

---

generators/client/templates/react/src/main/webapp/app/modules/account/password/password.tsx.ejs

Fix for mixed messages on repeat save. When used saves new password successfully then clicks save button again, both success and failure messages appear. Fix allows use to repeat new password process more than once if desired.
---

React password component allow repeat save

---

generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.html.ejs
generators/languages/templates/src/main/webapp/i18n/pt-br/global.json.ejs

translate filter to pt-br and fix page translation

---

cli/import-jdl.js
cli/jdl.js
cli/program.js
generators/generator-base-blueprint.js
generators/generator-base.js

Current cli allows blueprints to create an environment for generators, but not for jdl command.
Implement a factory for EnvironmentBuilder and use it at jdl command.
---

reuse enviroment builder factory method and improve blueprint check

---

.github/release-drafter.yml

Reverts jhipster/generator-jhipster#18320

Revert "adapt release drafter config to have smaller github release notes"

---

test-integration/samples/.jhipster/FieldTestEntity.json
test/templates/reproducible/.jhipster/Foo.json

Fix https://sonarcloud.io/project/issues?resolved=false&severities=MINOR&types=CODE_SMELL&id=jhipster-sample-application&open=AYEG0QoT0HaWLliKRoX_
---

Sonar: Use concise character class syntax '\d' instead of '[0-9]'

---

generators/server/templates/src/main/resources/config/application-prod.yml.ejs

Changing Blog Url link to the correct one.
from: https://maximilian-boehm.com/hp2121/Create-a-Java-Keystore-JKS-from-Let-s-Encrypt-Certificates.htm --> which is not working
to: https://maximilian-boehm.com/en-gb/blog/create-a-java-keystore-jks-from-lets-encrypt-certificates-4220323/  --> which is working
---

Fix Blog Url for Let's Encrypt Java JKS generation

---

generators/common/templates/sonar-project.properties.ejs
generators/entity-server/templates/src/main/java/package/common/get_all_template.ejs
generators/entity-server/templates/src/main/java/package/service/EntityQueryService.java.ejs
generators/server/__snapshots__/generator.spec.mjs.snap
generators/server/__snapshots__/needles.spec.mjs.snap
generators/server/files.js
generators/server/templates/src/main/java/package/Application.java.ejs
generators/server/templates/src/main/java/package/config/CRLFLogConverter.java.ejs
generators/server/templates/src/main/resources/logback-spring.xml.ejs
test/__snapshots__/app-client-custom-path.spec.js.snap
test/__snapshots__/app.spec.js.snap
test/__snapshots__/server.spec.js.snap
test/blueprint/__snapshots__/app-blueprint.spec.js.snap
test/blueprint/__snapshots__/scoped-blueprint.spec.js.snap

Reverts https://github.com/jhipster/generator-jhipster/pull/19270, which introduced many code smells.
And follows @atomfrede advise to filter logs.
- add logs safe list.
- uses colored replacement character.
- add `CRLFLogConverter.CRLF_SAFE_MARKER` to skip filter.
Closes https://github.com/jhipster/generator-jhipster/pull/19292
Closes https://github.com/jhipster/generator-jhipster/issues/14949
---

Fix sonar security issues

---

generators/server/templates/sql/common/src/test/java/package/config/MsSqlTestContainer.java.ejs

This PR fixes 2 issues present when generating an application with MS SqlServer as test database.
1.  public class defined inside MsSqlTestContainer.java differs from its filename (resulting in compile errors)
2.  MSSQLServerContainer provided by org.testcontainers does not support withDatabaseName() method (resulting in a UnsupportedOperationException during tests runtime)
---

Fix MSSQL Server testcontainer issues

---

generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs

Ignoring h2 console path for csrf
closes #19310
---

ignore h2-console for csrf usage

---

generators/server/templates/build.gradle.ejs
generators/server/templates/gradle.properties.ejs
generators/server/templates/pom.xml.ejs
generators/server/templates/src/main/java/package/config/SecurityConfiguration_reactive.java.ejs
generators/server/templates/src/main/java/package/security/oauth2/CustomClaimConverter.java.ejs

This PR replaces the unbounded hashmap to cache user information with a simple in memory/node local caffeine cache which seems to be simplest and easiest to use caching solution. 
We could of course use the selected caching type, but it seems to complicated or use some distributed solution for even better scaleability, but I think having each node to do the cache lookup is fine and everything else would be too much.
closes #18868
---

use caffeine cache for caching user information

---

generators/client/templates/vue/src/test/javascript/jest.conf.js.ejs
generators/client/templates/vue/src/test/javascript/spec/app/shared/alert/alert.service.spec.ts.ejs

[Vue] Increase Vue code coverage

---

generators/entity-server/templates/src/main/java/package/domain/Entity.java.jhi.spring_data_persistable.ejs
generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
generators/server/__snapshots__/generator.spec.mjs.snap
generators/server/cleanup-elasticsearch.js
generators/server/files.js
generators/server/templates/src/main/java/package/Application.java.ejs
generators/server/templates/src/test/java/package/config/ElasticsearchTestConfiguration.java.ejs
generators/server/templates/src/test/java/package/config/ElasticsearchTestContainer.java.ejs
generators/workspaces/index.js

- configure non reactive elastic search to use RefreshPolicy.IMMEDIATE, reactive already uses it.
- move elasticsearch cleanup to a dedicated AfterEach block and verify the cleanup
- add `xpack.security.enabled=false` setting to elasticsearch testcontainer which is already set at docker compose file (stops generating tons of warnings)
- when implementing Persistable interface, `new` field should be ignored by Jackson.
- add log safe marker to an initialization log.
- add `docker-compose` npm script for Microservices+workspaces.
---

Fix elasticsearch test configuration and others fixes/improvements

---

generators/entity-client/templates/angular/src/main/webapp/app/entities/detail/entity-management-detail.component.html.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.html.ejs

remove unnecessary optional properties from angular templates that cause warnings in the console
Fix #19373
---

remove unnecessary optional property

---

generators/server/templates/npmw.cmd

When Node.js is not already pre-installed globally on the system Windows building a generated project that relies on Node.js tooling for frontend fails. This is caused by NPM scripts not being able to locate Node.js, because the local installation is not added to the PATH by npmw.cmd. As the result NPM scripts that rely on Node.js fail to run.
The fix makes sure that the local Node.js installation, when present, is added to the PATH for all downstream scripts to see. The local Node.js is added temporarely,  for the duration of CMD session, leaving the global installation still accessible elsewhere.
**To recreate the issue, before applying this fix:**
1. Make sure there is no Node.js installed on a Windows machine or global PATH variable does NOT contain path to a Node.js installation.
2. …

fix npmw.cmd failing to set the local node.js up

---

.github/workflows/depsreview.yml

disable dependency review workflow at forks

---

generators/server/templates/build.gradle.ejs

we use node 16.x by default which has arm64 binaries, so we don't need the workaround anymore.
closes #19302
---

replace arm64 workaround for gradle node download

---

generators/server/templates/src/main/java/package/security/oauth2/CustomClaimConverter.java.ejs

Alternative fix for https://github.com/jhipster/generator-jhipster/issues/19309.
The following is new at v7.9.0
```
// Only look up user information if identity claims are missing
if (claims.containsKey("given_name") && claims.containsKey("family_name")) {
return claims;
}
```
it removes the default claim converter from the next line.
---

fix: jwt claims should always be converted.

---

generators/client/templates/angular/src/main/webapp/app/core/request/request-util.ts.ejs
generators/client/templates/angular/src/main/webapp/app/shared/filter/filter.component.html.ejs
generators/client/templates/angular/src/main/webapp/app/shared/filter/filter.component.ts.ejs
generators/client/templates/angular/src/main/webapp/app/shared/filter/filter.model.spec.ts.ejs
generators/client/templates/angular/src/main/webapp/app/shared/filter/filter.model.ts.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.html.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.spec.ts.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.ts.ejs

- add support to multiples values for each filter
- decouple filter changes from the filter component. (subscribe changes at the filter model, instead of at the component)
make easier to use a custom component
- cleanup exported interfaces
---

[angular] improve filter component/model

---

generators/client/templates/vue/src/main/webapp/app/core/jhi-navbar/jhi-navbar.component.ts.ejs

Browser Language Preference Needs To Be Honored

---

generators/entity-server/templates/src/main/java/package/repository/EntityRepositoryInternalImpl_reactive.java.ejs

This PR ensures non long ids are correctly wrapper with `'`. Used following entities to test it out:
```
entity Example {
id String
name String
}
entity Example2 {
name String
}
entity Example3 {
id UUID
name String
}
```
Both `Example` and `Example3` need the wrapping.
closes #18804
---

wrap non long ids with ' to have valid sql where clause

---

generators/server/__snapshots__/generator.spec.mjs.snap
generators/server/files.js
generators/server/templates/src/main/java/package/config/EurekaWorkaroundConfiguration.java.ejs
test/__snapshots__/server.spec.js.snap

The upstream issue seems to be fixed and will be in the next spring cloud release 2021.0.4 which is due for end of august. In any case this works now and we are not depending on release of spring cloud such we could do a next minor release.
closes https://github.com/jhipster/jhipster-registry/issues/537
Further discussion here, but other issue https://github.com/jhipster/generator-jhipster/issues/18533
---

fix incorrect eureka status message

---

generators/entity-server/templates/src/main/java/package/domain/Entity.java.jhi.ejs
generators/generator-base-blueprint.js
generators/generator-base-entities.cjs
generators/generator-base.js
generators/server/templates/src/main/java/package/domain/AbstractAuditingEntity.java.ejs
generators/server/templates/src/main/java/package/domain/User.java.ejs
lib/index.js

- Make AbstractAuditingEntity generic with `getId()` method.
This method exists at spring-data [Auditable](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/Auditable.html
) interface inherited from [Persistable](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/Persistable.html) interface
Current [workaround](https://github.com/hipster-labs/generator-jhipster-entity-audit/blob/4b1f89553dcf7e72e080a9f4cd16a7edaaf30fe1/generators/spring-boot-custom-audit/templates/src/main/java/package/audit/AsyncEntityAuditEventWriter.java.ejs#L75-L78) uses some fields introspections and doesn't work with custom id name nor derived entities.
- Improve writeFiles JSDoc.
- Add more multistep template customization to entity …

A few more adjusts to entity audit.

---

generators/server/templates/pom.xml.ejs

Fixes #19626. 
I tried this fix on both my M1 and Intel Macs and didn't experience any issues.
---

Move Netty dependency to fix reactive compilation

---

generators/server/templates/src/test/java/package/config/JHipsterBlockHoundIntegration.java.ejs

…ialize class io.netty.channel.DefaultChannelId on the Cassandra integration tests
Fixes https://github.com/jhipster/generator-jhipster/issues/19649.
A blocking call caused java.lang.NoClassDefFoundError: Could not initialize class io.netty.channel.DefaultChannelId on the Cassandra integration tests
---

Issue 19649 Fix

---

generators/info/index.js

A better alternative might be to delete the keys altogether since they'll be regenerated.

Add better message for jwtSecret and rememberMe keys with `jhipster info`

---

.eslintignore
.eslintrc.json
.gitignore
.prettierignore
cli/environment-builder.js
package-lock.json
package.json
test-integration/scripts/10-install-jhipster.sh
tsconfig.json

Initial set up of TypeScript.
---

Set up TypeScript

---

Dockerfile

Otherwise, npm install fails because it can't find tsc.
Related to #19763 
---

Add `npm ci` before `npm install`

---

generators/client/templates/angular/src/main/webapp/app/admin/docs/docs.component.scss.ejs
generators/client/templates/angular/src/main/webapp/app/layouts/navbar/navbar.component.scss.ejs
generators/client/templates/angular/src/main/webapp/content/scss/global.scss.ejs
generators/client/templates/angular/src/main/webapp/content/scss/vendor.scss.ejs

[Angular] Warnings: tilde imports is deprecated

---

generators/client/templates/react/package.json
generators/client/templates/react/src/main/webapp/app/shared/auth/private-route.tsx.ejs

[React] Bump react-router-dom from 6.4.1 to 6.4.2

---

generators/server/templates/build.gradle.ejs
generators/server/templates/gradle.properties.ejs
generators/server/templates/pom.xml.ejs
generators/server/templates/src/test/java/package/TechnicalStructureTest.java.ejs

I updated ArchUnit version from `0.22.0` to `1.0.0`. 
In order to handle the braking changes, I upgraded following the list in the description published in the releases [1.0.0](https://github.com/TNG/ArchUnit/releases/tag/v1.0.0) and [1.0.0-rc1](https://github.com/TNG/ArchUnit/releases/tag/v1.0.0-rc1).
The breaking change I found is the following one:
- `layeredArchitecture()` now forces to decide how to deal with dependencies by adding .considering...Dependencies() in the beginning of the declaration. To restore the old behavior declare it as ` layeredArchitecture().consideringAllDependencies()` (see https://github.com/TNG/ArchUnit/pull/892)
Therefore I upgraded `TechnicalStructureTest.java.ejs`
from:
```java
@ArchTest
static final ArchRule respectsTechnicalArchitectureLayers = …
```

Update archunit-junit5 version to 1.0.0

---

generators/app/generator.cjs
generators/base/generator-base.cjs
generators/base/generator.cjs
generators/bootstrap/generator.mts
generators/client/generator.cjs
generators/database-changelog-liquibase/generator.cjs
generators/database-changelog-liquibase/incremental-liquibase.spec.mts
generators/database-changelog/generator.mts
generators/database-changelog/generator.spec.mts
generators/entity/generator.cjs
generators/server/generator.cjs
test/app/composing.spec.mts
test/generator-base.spec.mts

This method was added to prevent running a generator multiple times back in late jhipster v6 cycle.
Environment now has a feature that prevents running a generator more than once for each application root, which is the desired behavior for most of the generators.
This feature can be dropped from jhipster.
---

Drop registerComposedGenerator and compose once

---

generators/server/templates/npmw.cmd

Yes, this is a super small PR. I tested jhipster for the first time today and I regulary run a check in my projects to see if all files match the .editorconfig. This trailing whitespace came up. So I thought why not make a PR out of it and here we are.
---

remove a trailing whitespace

---

generators/client/templates/entity/angular/src/main/webapp/app/entities/update/entity-management-update.component.html.ejs

Fix missing interpolation on Angular client when translation is disabled

---

generators/cypress/templates/src/test/javascript/cypress/e2e/account/settings-page.cy.ts.ejs

A race condition is probably happening where cypress tries to clear an input that’s not yet loaded. The end result is the old value concatenated with the new value.
The fix is to wait the input to have the expected value before clearing it.
---

fix cypress race condition that causes random failures at react frontend 

---

generators/server/templates/src/test/resources/config/application.yml.ejs

At least the integration tests worked fine for me with the additional setting.
This might also be related to https://github.com/jhipster/generator-jhipster/issues/18198
---

support mongock for reactive applications

---

generators/app/__snapshots__/generator.spec.mts.snap
generators/server/templates/build.gradle.ejs
generators/server/templates/gradle.properties.ejs
generators/server/templates/pom.xml
generators/server/templates/pom.xml.ejs

Hazelcast versions will not be managed by spring-boot anymore.
Should fix sb3 error: https://github.com/jhipster/generator-jhipster/actions/runs/3450840319/jobs/5759813396.
hazelcast-hibernate53 version 2.3.0 is supposed to support hibernate6.
Targeting main to avoid future conflicts.
---

manage halzelcast version.

---

generators/cypress/__snapshots__/generator.spec.mts.snap
generators/cypress/files.mts
generators/cypress/templates/src/test/javascript/cypress/e2e/account/settings-page.cy.ts.ejs
generators/cypress/templates/src/test/javascript/cypress/support/account.ts.ejs
generators/cypress/templates/src/test/javascript/cypress/support/index.ts.ejs
generators/server/templates/src/main/java/package/config/dbmigrations/InitialSetupMigration.java.ejs

Rework cypress settings page.

---

generators/server/templates/entity/src/main/java/package/domain/Entity.java.jhi.jakarta_persistence.ejs

This should fix the `ng-default` job in the SB3 branch. For more details, see https://github.com/jhipster/generator-jhipster/pull/19791#issuecomment-1316370985. 
---

Don't lazy-load ManyToOne if relationship is required

---

test-integration/jdl-samples/ms-mf-react-eureka-oauth2-mariadb-infinispan/blog-store.jdl
test-integration/jdl-samples/ms-mf-vue-consul-oauth2-mysql-memcached/blog-store.jdl

MariaDB driver is not compatible with current r2dbc version.
Reference https://github.com/spring-projects/spring-data-relational/issues/1364#issuecomment-1289124846
---

disable mariadb/mysql webflux tests

---

test-integration/scripts/10-install-jhipster.sh

We need development dependencies to build the typescript project.
Related to windows daily builds.
---

drop --prod from npm ci at scripts

---

generators/angular/templates/src/main/webapp/app/entities/_entityFolder/update/_entityFile-update.component.html.ejs

While developing 21-Points Health for the JHipster Mini-Book v7, I noticed the labels and input fields don't line up on the update form. Removing the `row` CSS class seems to fix this.
Before:
After:
---

[Angular] Remove `row` CSS class on update form

---

generators/cypress/templates/src/test/javascript/cypress/plugins/index.ts.ejs

When developing 21-Points Health for the JHipster Mini-Book v7, I encountered a Cypress e2e testing issue that took me _hours_ to solve. The problem was caused by one of the list screens and I was finally able to figure it out by logging the response with `cy.task('table', response)`. When I did this, I saw it was intercepting `/points-by-week` (a new endpoint I'd added) instead of `/points` (the list screen's endpoint). 
I changed to the interception logic to fix this:
```diff
-    cy.intercept('GET', '/api/points+(?*|)').as('entitiesRequest');
+    cy.intercept('GET', '/api/points?size=*').as('entitiesRequest');
```
Since I found these methods helpful, I figured we should add them by default.
---

Add Cypress task for logging

---

generators/docker-compose/__snapshots__/docker-compose.spec.mts.snap
generators/docker/templates/src/main/docker/elasticsearch.yml.ejs
generators/generator-constants.cjs

sb3: bump elasticseach container to v8.5.0

---

generators/server/templates/entity/src/main/java/package/service/mapper/EntityMapper.java.ejs
test-integration/samples/jdl-entities/entities.jdl

Fix #19845
Currently if the .jdl contains a mapstructExpression it works for direct fields but not for related fields. This results in a compile error. 
---

allow mapstructExpression also in related fields

---

.mocharc.cjs
package-lock.json
package.json
test/cli/import-jdl.spec.cjs
test/cli/jdl.spec.cjs

`@node-loaders/mock` provides esm and commonjs modules mocking support.
This will make the cli transition to esm easier due to existing module mocking usage.
---

switch from proxyquire to @node-loaders/mock

---

package.json
test/mocha-update-snapshots.config.cjs

Try to fix `npm run update-snapshots` on windows.
---

add mocha config to update snapshots

---

generators/server/templates/build.gradle.ejs

The `GenerateGitPropertiesTask` Gradle task pulled by the `com.gorylenko.gradle-git-properties` plugin is executed systematically as using `upToDateWhen { false }`.
Marking the task as non cacheable is interesting to first avoid overhead and second ease detection of performance regression as this one won't appear anymore as a cache miss.

Mark GenerateGitPropertiesTask as non cacheable

---

test-integration/scripts/99-print-matrix.js

Mongodb + webflux backend tests still running even after https://github.com/jhipster/generator-jhipster/pull/20599
---

use string value for matrix

---

generators/base/generator-base.mjs

Ejs cache is misbehaving in some use cases.
Mainly when regenerating multiples applications (microservices) samples.
Reproduce, execute twice:
```
jhipster jdl https://raw.githubusercontent.com/jhipster/generator-jhipster/main/test-integration/jdl-samples/mf-ng-eureka-jwt-psql-ehcache/blog-store.jdl --skip-install
```
---

disable ejs cache

---

generators/angular/templates/src/main/webapp/app/home/home.component.scss.ejs
generators/angular/templates/src/main/webapp/app/layouts/navbar/navbar.component.scss.ejs
generators/client/templates/src/main/webapp/content/css/loading.css.ejs
generators/react/templates/src/main/webapp/app/modules/home/home.scss.ejs
generators/react/templates/webpack/webpack.dev.js.ejs
generators/react/templates/webpack/webpack.prod.js.ejs
generators/vue/templates/src/main/webapp/app/core/jhi-navbar/jhi-navbar.vue.ejs
generators/vue/templates/src/main/webapp/content/scss/global.scss.ejs
generators/vue/templates/webpack/vue.utils.js.ejs

With relative paths files are hashed, and cause miss hit from caches, in my case I'm using a CDN.
Related to https://github.com/jhipster/jhipster.github.io/pull/1248 
~~I have changed and tested the angular application. Please confirm if I should modify also the other web frameworks.~~
---

Use absolute path for static images.

---

generators/base-docker/docker-base.mjs
generators/base/generator-base.mjs
generators/base/support/config.mts
generators/base/support/config.spec.mts
generators/base/support/index.mts
generators/entity/generator.mjs

When prompts are ignored, a null value is set to the store so subsequent prompts are ignored (`--ask-answered` option will show those questions again).
A null value at config will override the default value with the null value, causing a wrong config to be applied.
This PR removes undefined and null values so the default value will be correctly be returned.
---

cleanup config before applying defaults

---

generators/cassandra/__snapshots__/generator.spec.mts.snap
generators/couchbase/__snapshots__/generator.spec.mts.snap
generators/elasticsearch/__snapshots__/generator.spec.mts.snap
generators/mongodb/__snapshots__/generator.spec.mts.snap
generators/server/__snapshots__/needles.spec.mjs.snap
generators/server/__snapshots__/neo4j.spec.mts.snap
generators/server/__snapshots__/sql.spec.mts.snap
generators/server/cleanup.mts
generators/server/files.mjs
generators/server/templates/src/test/resources/testcontainers.properties.ejs
test/blueprint/__snapshots__/app-blueprint.spec.mts.snap
test/blueprint/__snapshots__/scoped-blueprint.spec.mts.snap

`testcontainers.reuse.enable` in testcontainers.properties file is not used as it is a per environment property (not a per project property)
see here: https://github.com/testcontainers/testcontainers-java/issues/3780
We could also delete testcontainers.properties file but some developers may have defined some other properties in this file (?)
I realized this when I saw this docker logs during startup:
_Reuse was requested but the environment does not support the reuse of containers
To enable reuse of containers, you must set 'testcontainers.reuse.enable=true' in a file located at /Users/ctamisier/.testcontainers.properties_
So when `testcontainers.reuse.enable=true` is defined in ~/.testcontainers.properties the docker containers are indeed not removed after tests.

remove unused testcontainers property

---

generators/liquibase-changelogs/__snapshots__/incremental-liquibase.spec.mts.snap
generators/liquibase-changelogs/generator.mjs
generators/liquibase-changelogs/incremental-liquibase.spec.mts
generators/liquibase-changelogs/templates/src/main/resources/config/liquibase/changelog/updated_entity.xml.ejs
test-integration/incremental-changelog-samples/liquibase-jdl-rename-field-post/app.jdl
test-integration/incremental-changelog-samples/liquibase-jdl-rename-field/app.jdl

fix add and drop fk relationships with involved primary key columns not named 'id'

---

generators/app/generator.mjs
generators/base/generator-base-private.mjs
generators/base/generator.mts
generators/cleanup.mjs
generators/docker-compose/files.mjs
generators/languages/generator.mjs
generators/languages/index.mts
generators/languages/upgrade-files-task.mts
generators/upgrade/generator.mjs

- move some methods to base/generator.mts (typescript).
- extract upgradeFilesTask.
- move `gitMove` implementation locally at upgradeFilesTask it's used only once for now. (shouldn't be exposed due to api contract).
---

cleanup generator-private methods

---

generators/base-application/generator-ts.mts
generators/base-application/generator.mjs
generators/base-application/support/entities.mts
generators/base/generator-base.mjs
generators/base/generator.mts
generators/bootstrap-application-base/utils.mjs
generators/entities/generator.mjs
generators/entity/generator.mjs
generators/info/generator.mts
test/cli/environment-builder.spec.mts

Move entity operations from generators/base to generators/base-application.
Generate a temporary `generator-ts.mts` to keep ts implementation while `generator` is js.
---

move entity to base-application

---

.github/actions/build-matrix/action.yml
.github/actions/compare-base/action.yml
.github/actions/compare/action.yml
.github/actions/setup/action.yml
test-integration/scripts/99-build-changes.sh

GitHub Actions have depreciated the set-output command to avoid vulnerabilities
See changelog https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
---

ci: use GITHUB_OUTPUT to expose outputs

---

generators/common/__snapshots__/generator.spec.mjs.snap
generators/common/templates/package.json

Bump lint-staged from 13.1.0 to 13.1.1 in /generators/common/templates

---

.github/dependabot.yml

Dependabot is taking too long.
When a PR is merged, many times it causes a rebase due to conflicts on unrelated package.json.
Add time to schedule to make dependabot's PRs behave better
---

add time to dependabot schedule

---

generators/server/templates/gradle.properties.ejs

Upgrade Gradle Enterprise plugin to 3.12.3

Update Gradle Enterprise plugin version

---

generators/base-application/generator.mts
generators/base/generator-base-blueprint.mts
generators/base/generator-base.mts
generators/bootstrap/generator.mts
generators/bootstrap/support/index.mts
generators/bootstrap/support/sort-config-files-transform.mts

Sorts config files even if not written with storage object.
Related to https://github.com/jhipster/generator-jhipster/issues/21080
---

sort json config files using transform

---

generators/base-application/support/prepare-relationship.mjs
generators/liquibase-changelogs/__snapshots__/incremental-liquibase.spec.mts.snap
generators/liquibase-changelogs/generator.mjs
generators/liquibase-changelogs/incremental-liquibase.spec.mts
generators/liquibase-changelogs/templates/src/main/resources/config/liquibase/changelog/added_entity_constraints.xml.ejs
generators/liquibase-changelogs/templates/src/main/resources/config/liquibase/changelog/updated_entity.xml.ejs
generators/liquibase-changelogs/templates/src/main/resources/config/liquibase/changelog/updated_entity_constraints.xml.ejs
generators/liquibase/generator.mts
generators/liquibase/support/relationship.mts
jdl/jhipster/index.mts
jdl/jhipster/relationship-on-handler-options.ts

Fix #18751
---
TBD: Maybe the mentioned improvement to display a nice error message if deletion fails (I'll probably split this into a separate Merge request then to keep focus here on jdl / backend changes only)

allow defining onDelete and onUpdate in relationships

---

generators/server/templates/src/main/resources/config/application.yml.ejs

Since the YAML array ends up being multi-line, it does not make sense to use the array syntax rather than the block sequence syntax. 
And it makes the template more readable.
---

Use YAML block sequence syntax

---

generators/react/templates/src/main/webapp/app/app.scss.ejs

I had an issue with overriding bootstrap variables only with **react** client
In `bootstrap-variables.scss`
`$primary: red;`
To make it work, we need to add `@import 'bootstrap-variables’`; in `app.scss`
---
- [X ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ X] Tests are added where necessary
- [X ] The JDL part is updated if necessary
- [X ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [X ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed …

React - Import bootstrap variable scss file

---

.github/actions/compare-base/action.yml

since https://github.com/jhipster/generator-jhipster/pull/21208 was merged, we can change the base compare to use jit.
- reduces base compare step by 3min
---

change base compare to use jit

---

bin/jhipster.mjs
cli/jhipster.mjs
cli/program.mjs
generators/base/__snapshots__/generator.spec.mts.snap

Switch to locally installed package is not a good practice and not adopted by any other package I known of.
JHipster v7 installed globally will fail to load a jhipster 8 installed locally due to the switch to esm.
Drop this behavior and add a warning about this behavior change.
---

don't try to execute locally installed jhipster

---

generators/generate-blueprint/files.mjs

(fix): Fix 'ERROR! Template file cli/commands.mjs was not found at..'

---

generators/app/__snapshots__/generator.spec.mts.snap
generators/server/generator.mjs

fix configureServer with --defaults

---

generators/server/templates/src/main/resources/config/application.yml.ejs
generators/sql/templates/src/test/java/package/config/timezone/HibernateTimeZoneIT.java.ejs
generators/sql/templates/src/test/resources/config/application-testdev.yml.ejs
generators/sql/templates/src/test/resources/config/application-testprod.yml.ejs

So it will be stored as UTC values inside the database, instead of Local timezone. 
This was a breaking change introduced Hibernate 6, this fix restores the previous behavior, and re-enables the test which could warn about in the future, if similar thing happens.
---

Fix broken Hibernate mapping of Instants

---

generators/server/templates/pom.xml.ejs
generators/server/templates/src/main/resources/banner-no-color.txt
generators/server/templates/src/main/resources/banner.txt
generators/server/templates/src/main/resources/banner_react.txt
generators/server/templates/src/main/resources/banner_vue.txt
test-integration/workflow-samples/react.json

Reduce pom duplications.
Print profiles passed to spring at banner for easy reference.
---

move maven-failsafe-plugin out of profiles

---

generators/base/generator-base-todo.mjs
generators/client/generator.mjs
generators/client/needle-api/needle-client.mts
generators/client/needle-client.spec.mts
generators/client/types.d.mts
test/needle-api/needle-client.spec.mts

Remove one generator-base-todo method.
---

cleanup one todo method

---

generators/languages/support/languages.mts
generators/languages/templates/entity/i18n/entity_az-Latn-az.json.ejs
generators/languages/templates/src/main/resources/i18n/messages_az_Latn_AZ.properties.ejs
generators/languages/templates/src/main/webapp/i18n/az-Latn-az/activate.json.ejs
generators/languages/templates/src/main/webapp/i18n/az-Latn-az/configuration.json
generators/languages/templates/src/main/webapp/i18n/az-Latn-az/error.json
generators/languages/templates/src/main/webapp/i18n/az-Latn-az/gateway.json
generators/languages/templates/src/main/webapp/i18n/az-Latn-az/global.json.ejs
generators/languages/templates/src/main/webapp/i18n/az-Latn-az/health.json.ejs
generators/languages/templates/src/main/webapp/i18n/az-Latn-az/home.json
generators/languages/templates/src/main/webapp/i18n/az-Latn-az/login.json
generators/languages/templates/src/main/webapp/i18n/az-Latn-az/logs.json
generators/languages/templates/src/main/webapp/i18n/az-Latn-az/metrics.json
generators/languages/templates/src/main/webapp/i18n/az-Latn-az/password.json
generators/languages/templates/src/main/webapp/i18n/az-Latn-az/register.json
generators/languages/templates/src/main/webapp/i18n/az-Latn-az/reset.json.ejs
generators/languages/templates/src/main/webapp/i18n/az-Latn-az/sessions.json
generators/languages/templates/src/main/webapp/i18n/az-Latn-az/settings.json
generators/languages/templates/src/main/webapp/i18n/az-Latn-az/tracker.json
generators/languages/templates/src/main/webapp/i18n/az-Latn-az/user-management.json
generators/languages/templates/src/test/resources/i18n/messages_az_Latn_AZ.properties.ejs
test-integration/samples/ng-default/.yo-rc.json
test-integration/samples/react-default/.yo-rc.json
test-integration/samples/vue-fulli18n-es/.yo-rc.json

 azerbaijani lang support added

---

cli/environment-builder.mjs
generators/base/api.d.mts
generators/base/generator-base-blueprint.mts
generators/base/generator-base-todo.mjs
generators/base/generator-base.mts

- add options from local blueprint 
- add sbsBlueprint to features instead of setting at constructor
- add jhipster7Migration feature for jhipster 7 context migration.
- allow composeWithJHipster with absolute path.
---

add features and disable jhipster 7 context by default

---

generators/workspaces/generator.mjs

angular-cli uses a fixed webpack version, but not locked as a peer dependency.
It's not possible to detect the used webpack version to match at others dependencies and avoid conflicts.
We set our own webpack version and override the one angular uses.
At monorepository this overrides is not applied, we need set the overrides at the root package.json too.
---

add overrides at workspaces if angular is used

---

.github/workflows/generator-generate-blueprint.yml
generators/app/__snapshots__/generator.spec.mts.snap
generators/app/generator.spec.mts
package.json

Version 7.10.0 won't happen.
This will allow to update [jhipster samples](https://github.com/jhipster/jdl-samples) with new jdl specifications at v7.10.0 branch.
---

change version to 7.10.0

---

generators/vue/__snapshots__/generator.spec.mts.snap
generators/vue/files-vue.mjs
generators/vue/templates/package.json
generators/vue/templates/package.json.ejs
generators/vue/templates/src/main/webapp/app/admin/configuration/configuration.component.ts.ejs
generators/vue/templates/src/main/webapp/app/admin/configuration/configuration.vue.ejs
generators/vue/templates/src/main/webapp/app/admin/logs/logs.component.ts.ejs
generators/vue/templates/src/main/webapp/app/admin/logs/logs.vue.ejs
generators/vue/templates/src/main/webapp/app/admin/metrics/metrics-modal.component.ts.ejs
generators/vue/templates/src/main/webapp/app/admin/metrics/metrics-modal.vue.ejs
generators/vue/templates/src/main/webapp/app/admin/user-management/user-management.component.ts.ejs
generators/vue/templates/src/main/webapp/app/entities/_entityFolder/_entityFile.component.ts.ejs
generators/vue/templates/src/main/webapp/app/shared/computables/arrays.ts.ejs
generators/vue/templates/src/main/webapp/app/shared/computables/index.ts.ejs
generators/vue/templates/src/main/webapp/app/shared/config/config.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/admin/metrics/metrics-modal.component.spec.ts.ejs
generators/vue/templates/webpack/webpack.microfrontend.js.jhi.vue.ejs

Vue 3 dropped filters support.
- removes class-component and property-decorators from dependabot package.json.
- Implement orderBy and filterBy replacement
Related to https://github.com/jhipster/generator-jhipster/issues/12558.
---

Drop vue2-filters

---

generators/vue/templates/src/main/webapp/app/admin/user-management/user-management-edit.component.ts.ejs
generators/vue/templates/src/main/webapp/app/admin/user-management/user-management-view.component.ts.ejs
generators/vue/templates/src/main/webapp/app/admin/user-management/user-management.component.ts.ejs
generators/vue/templates/src/main/webapp/app/app.component.ts.ejs
generators/vue/templates/src/main/webapp/app/entities/_entityFolder/_entityFile-details.component.ts.ejs
generators/vue/templates/src/main/webapp/app/entities/_entityFolder/_entityFile-update.component.ts.ejs
generators/vue/templates/src/main/webapp/app/entities/_entityFolder/_entityFile.component.ts.ejs
generators/vue/templates/src/main/webapp/app/main.ts.ejs
generators/vue/templates/src/main/webapp/app/shared/alert/alert.service.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/admin/user-management/user-management-edit.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/admin/user-management/user-management-view.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/entities/_entityFolder/_entityFile-details.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/entities/_entityFolder/_entityFile-update.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/entities/_entityFolder/_entityFile.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/shared/alert/alert.service.spec.ts.ejs

Providing a factory is not a good practice, the class needs to be instantiated at each use.
- provide a singleton instead of a factory.
- move from main to app component. At main vue instance is not available yet.
- remove vue instance from methods parameters.
- implement a composable useAlertService.
Related to https://github.com/jhipster/generator-jhipster/issues/12558
---

Rework alertService

---

generators/sql/templates/src/main/java/package/repository/rowmapper/ColumnConverter_reactive.java.ejs

Fixes a spelling/grammar mistake in `ColumnConverter_reactive.java.ejs` where `it it's` should be `if it's`. See https://github.com/jhipster/generator-jhipster/issues/21969 for more detail.
- fixes #21969 
---

chore: fix spelling mistake in ColumnConverter_reactive.java.ejs

---

generators/vue/templates/package.json
generators/vue/templates/package.json.ejs
generators/vue/templates/webpack/webpack.prod.js.ejs

- vue-template-compiler is not required since vue 2.7.
- latest fork-ts-checker-webpack-plugin doesn't support vue and vue 3 has no support at any version.
Related to https://github.com/jhipster/generator-jhipster/issues/12558
---

Drop vue dependencies

---

generators/docker-compose/__snapshots__/docker-compose.spec.mts.snap
generators/docker/templates/src/main/docker/postgresql.yml.ejs

This makes the following fatal warning go away.
```
gateway-postgresql-1            | 2023-05-15 16:02:46.432 UTC [106] FATAL:  role "root" does not exist
```
---

Add username to PostgreSQL healthcheck

---

generators/app/generator.mjs
generators/base/generator-base-blueprint.mts
generators/base/generator-base-todo.mts
generators/base/generator-base.mts
generators/client/needle-client.spec.mts
generators/entities/generator.mjs
generators/entity/generator.mjs
generators/generate-blueprint/templates/generators/generator/generator.mjs.jhi.ejs
generators/jdl/generator.mts
generators/languages/generator.mjs
generators/liquibase/generator.mts
generators/spring-controller/generator.mjs
generators/spring-service/generator.mjs
generators/workspaces/generator.mjs
lib/global.d.ts
test/needle-api/needle-client-i18n.spec.mts
test/needle-api/needle-client-react-generator.spec.mts
test/needle-api/needle-client-react.spec.mts
test/needle-api/needle-client-vue-generator.spec.mts
test/needle-api/needle-client-webpack.spec.mts
tsconfig.json

`composeWith` has too many optional parameters. Convert to a single `options`.
Closes https://github.com/jhipster/generator-jhipster/issues/21959
---

Rework composeWith api

---

generators/server/templates/src/main/java/package/config/CRLFLogConverter.java.ejs

Add javadoc to CRLFLogConverter
---

add CRLFLogConverter.java javadoc

---

generators/server/templates/entity/src/main/java/package/domain/enumeration/Enum.java.ejs
test-integration/samples/.jhipster/FieldTestEnumWithValue.json

In sections where incorrect code was being generated, the process has been redefined to include the 'without CustomValue' state when the key equals the value. The area of correction is confined to the Java enum declaration. 
(More significant modifications such as a complete redefinition of 'without CustomValue' would impact the client side. If that's deemed necessary, I'm willing to implement it.)
Related tests have been added.
I have checked the differences in the generated code for 'ng-default', 'react-default', and 'vue-default' in jhipster-samples, and confirmed that the changes are as intended.
Resolves #22192
---
When you are still working on the PR, consider converting it to Draft (below reviewers) and adding …

Fix generation of incorrect code for enums where key equals value.

---

generators/server/templates/src/main/java/package/web/rest/errors/ExceptionTranslator.java.ejs
generators/server/templates/src/test/java/package/web/rest/AccountResourceIT.java.ejs
generators/server/templates/src/test/java/package/web/rest/errors/ExceptionTranslatorIT_reactive.java.ejs

This PR does two things:
For imperative and reactive during registration we do not expose an error (e.g. username already exists) via the api. Therefore for the caller successful registration and failed registration look the same, so there is no way (except some sophisticated things like measuring response times) to gain knowledge about existing users and emails.
Second thing is only for reactive as for imperative spring security already took care of it. 
In case authentication fails we do not expose the exact error to the caller/the api (e.g. invalid password) as this would also reveal that the login was correct. The generic error now only states `Invalid credentials` which is the same for non reactive apps.
closes #21731
---
Please make sure the below checklist is followed for Pull …

prevent leakage of user information via api

---

generators/angular/templates/src/main/webapp/content/scss/_bootstrap-variables.scss.ejs
generators/react/templates/src/main/webapp/app/_bootstrap-variables.scss.ejs

fix #22406 
I have fixed the background color for both Angular and React by setting it to white. No adjustment was needed for Vue, as it was already set to white (it uses a different style from the others).
With this change, the default theme now closely resembles that of JHipster 7.
---

Background Color Correction

---

generators/react/templates/src/main/webapp/app/config/notification-middleware.spec.ts.ejs
generators/react/templates/src/main/webapp/app/config/notification-middleware.ts.ejs

Resolves #22483
- Using the URL defined in `AxiosError` instead of `data`, which was becoming empty.
- Adjusted the expected action value in Jest to reflect the current situation.
- Implemented the use of `AxiosError` type after `isAxiosError` check (I initially wanted to also define a type for `data`. This remains an issue to be addressed in the future).

Fix unauthorized error handling

---

generators/react/templates/src/main/webapp/app/entities/_entityFolder/_entityFile.tsx.ejs
generators/react/templates/src/main/webapp/app/modules/administration/user-management/user-management.tsx.ejs

Resolves #22581
I've confirmed the changes on the following pages:
- Item list page as an entity
- User management page
I've also verified that in non-i18n environments, unnecessary tags do not appear.
---

Fix react pagination translation

---

CONTRIBUTING.md
generators/ci-cd/__snapshots__/ci-cd.spec.mts.snap
generators/ci-cd/templates/jenkins/idea.gdsl.ejs

docs: use consistent uppercase "J"

---

generators/server/templates/npmw
generators/server/templates/npmw.cmd

See https://github.com/jhipster/generator-jhipster/pull/22744#issuecomment-1620475540.
Running as a command like I've said in https://github.com/jhipster/generator-jhipster/pull/22744#issuecomment-1620475540 will cause conflicts running `jhipster --defaults` twice. Second execution will compare source without spotless against source with spotless, spotless execution will happen after compare and commit.
Unfortunately the only way to fully integrate spotless is by integration it into mem-fs using transforms.
---

drop spotless npmw integration

---

CONTRIBUTING.md

Update documentation for Generator development setup in CONTRIBUTING.md
Change order so that `npm ci` is run before `npm link`.
Close #22732
---
- [] Tests are added where necessary
- [] The JDL part is updated if necessary
- [] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

Update documentation for Generator development setup 

---

generators/server/templates/build.gradle.ejs

By default spotless also tries to keep generated sources spotless, thats why it failed. Configured spotless to just check real sources.
Side note, I am not sure, but  I supposed generating an app should execute spotless, but it looks like it was not executed on test classes. Running spotlessApply fixed all unused imports
closes #22840
---

prevent spotless from trying to handle generated sources

---

generators/client/templates/src/main/webapp/swagger-ui/index.html.ejs

Swagger implementation probes every service for an openapi endpoint.
The stack trace is shown because consul doesn't have the endpoint.
Since consul is known to doesn't have the openapi endpoint, this pr removes it.
Fixes https://github.com/jhipster/generator-jhipster/issues/22654.
---

remove consul from openapi lookup

---

generators/languages/templates/src/main/webapp/i18n/bn/reset.json.ejs
generators/languages/templates/src/main/webapp/i18n/da/reset.json.ejs
generators/languages/templates/src/main/webapp/i18n/en/reset.json.ejs
generators/react/templates/src/main/webapp/app/modules/account/password-reset/password-reset.reducer.ts.ejs
generators/vue/templates/src/main/webapp/app/account/reset-password/init/reset-password-init.vue.ejs

I have changed "emails" to "email" in the existing alert message for reset password: "Check your emails for details on how to reset your password."
---

Fix typo in the alert message for "reset password"

---

generators/client/support/update-languages.mts

Fix https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYYImbn4jT0F0g-yuSk2
---

Sonar: 'dayjs/esm/locale/en' import is duplicated

---

generators/vue/templates/package.json.ejs
generators/workspaces/generator.mjs

Drop prettier and jest workarounds.
Prettier 3.0 is supported now and we have switched to vitest.
Fixes https://github.com/jhipster/generator-jhipster/issues/22877.
---

drop vue dependency workarounds

---

generators/server/templates/entity/src/main/java/package/common/inject_template.ejs

Related to #22945 
The variable id unused for reactive and non reactive project
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AXgYXBxAM8GLQdCnBrhu
---

Sonar: Remove this unused 'xxxRepository' private field (not just for reactive)

---

generators/base-application/support/prepare-field.mjs
generators/base/support/faker.mts
generators/cypress/templates/src/test/javascript/cypress/e2e/entity/_entity_.cy.ts.ejs
generators/liquibase-changelogs/__snapshots__/incremental-liquibase.spec.mts.snap
generators/liquibase-changelogs/incremental-liquibase.spec.mts

https://fakerjs.dev/api/random.html#random is deprecated
Replaced by https://fakerjs.dev/api/lorem.html#lorem 
https://v7.fakerjs.dev/api/name.html
Replaced by https://fakerjs.dev/api/person.html

Fakerjs 8 deprecated method

---

generators/entity/generator.mjs

An entity on mem-fs only is not discoverable, it needs to be written to disk or at entities list.
Fixes https://github.com/jhipster/generator-jhipster/issues/22873
---

Add entity to entities list

---

generators/server/templates/build.gradle.ejs
generators/server/templates/pom.xml.ejs

Regenerating projects with spotless always causes many conflicts.
This is a major problem at jhipster development, but a minor at generated project since it's 1 line to change.
---

disable spotless removeUnusedImports

---

generators/docker-compose/__snapshots__/docker-compose.spec.mts.snap
generators/docker/__snapshots__/generator.spec.mts.snap
generators/generator-constants.mts
generators/kubernetes-helm/__snapshots__/kubernetes.helm.spec.mts.snap
generators/kubernetes-knative/__snapshots__/knative.spec.mts.snap
generators/kubernetes/__snapshots__/kubernetes.spec.mts.snap
generators/liquibase-changelogs/__snapshots__/incremental-liquibase.spec.mts.snap
generators/liquibase/templates/src/main/resources/config/liquibase/master.xml.ejs
generators/openshift/__snapshots__/openshift.spec.mts.snap
generators/server/templates/src/main/resources/config/application.yml.ejs
generators/spring-data-relational/support/database-data.mts
generators/spring-data-relational/support/database-url.spec.mts
generators/spring-data-relational/templates/src/test/java/package/config/timezone/HibernateTimeZoneIT.java.ejs
generators/spring-data-relational/templates/src/test/resources/config/application-testdev.yml.ejs
generators/spring-data-relational/templates/src/test/resources/config/application-testprod.yml.ejs

The initial ideal was to use `hibernate.timezone.default_storage: NORMALIZE_UTC` configuration, but `dev` (h2) tests never matches the `prod` test. `prod` succeeds while `dev` fails.
One possibility is that `NORMALIZE_UTC` will only make difference if db supports native timezone, which h2 supports but postgresql, mysql and mariadb don't.
Tested locally at local timezone:
- Postgresql/H2 using dev/prod profiles 👍 
- MySql/H2 using dev/prod profiles 👍 
- MariaDB/H2 using dev/prod profiles 👍 
I want to do some additional tests using `NORMALIZE_UTC`, but can be done later.
My initial tests, `NORMALIZE_UTC` succeed using Postgresql and MySql but fails with H2.
I want to test if data stored at db changes.
Fixes https://github.com/jhipster/generator-jhipster/issues/22874.
Related to …

Switch to hibernate 6.2.x

---

generators/server/templates/src/test/java/package/TechnicalStructureTest.java.ejs

Java tests fail for default app without user management

---

generators/react/templates/src/main/webapp/app/modules/account/register/register.tsx.ejs

Fixed the login link in the account page which was broken before
Before update:
https://github.com/jhipster/generator-jhipster/assets/30769960/bfcfbcea-1a06-462c-9cc4-215193ba0364
After update:
https://github.com/jhipster/generator-jhipster/assets/30769960/056535cb-02a4-4f3f-9305-95b4a7206927
---

React template: Add missing link for login in the register page

---

generators/server/templates/src/main/java/package/config/CRLFLogConverter.java.ejs

Related to #23141 
Fix:
- https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYT5NKBUoub84d7atcQe
- https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYT5NKBUoub84d7atcQf
---

Sonar: Remove this use of 'getMarker'; it is deprecated

---

generators/angular/templates/src/main/webapp/app/entities/_entityFolder/service/_entityFile.service.spec.ts.ejs
generators/angular/templates/src/main/webapp/app/entities/_entityFolder/service/_entityFile.service.ts.ejs
generators/base-application/support/prepare-entity.mts
generators/bootstrap-application-server/generator.mts
generators/server/support/prepare-entity.mjs

Closes https://github.com/jhipster/generator-jhipster/pull/22867.
Fixes https://github.com/jhipster/generator-jhipster/issues/22866.
---

allow searchEngine with boolean value at entities

---

generators/server/templates/src/main/java/package/config/SecurityConfiguration_reactive.java.ejs

cache simple Mono of JWT instead the whole pipe, because previously OAuth2 /userinfo calls were performed each time cached Monos were accessed
Fix #20063
---

Fix gateway users cache

---

.github/actions/compare-base/action.yml
generators/kubernetes-helm/__snapshots__/kubernetes.helm.spec.mts.snap
generators/kubernetes-knative/__snapshots__/knative.spec.mts.snap
generators/kubernetes/__snapshots__/kubernetes.spec.mts.snap
generators/kubernetes/kubernetes-base.mjs

Make Kubernetes generated files at microservice samples reproducible.
---

Try to reproduce kubernetes.

---

generators/server/templates/src/main/java/package/aop/logging/LoggingAspect.java.ejs

Fix #21304
`logger.error()` may not work rightly with logback, because the cause is a exception.
Maybe use `String.valueof()` to wrap the cause.
---

add String.valueof() for correct log message

---

generators/server/templates/src/main/java/package/config/LocaleConfiguration_imperative.java.ejs

With https://github.com/jhipster/jhipster-bom/releases/tag/8.0.0-beta.3 we can finish https://github.com/jhipster/generator-jhipster/issues/23141
Fix: https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYT5NKCfoub84d7atcQh
---

Sonar: Remove this use of 'setCookieName'; it is deprecated

---

cli/program.mjs
generators/base/api.d.mts
generators/generate-blueprint/templates/generators/generator/generator.mjs.jhi.ejs

- enable jhipster 7 migration by default.
- follow option import at blueprints.
- allow blueprints to override main options.
related to https://github.com/jhipster/generator-jhipster/issues/23449
---

Follow option imports at blueprints.

---

generators/generate-blueprint/templates/generators/generator/generator.mjs.jhi.ejs

Example: In the 'server' sub-generator:
- Generated template file:
```
server
templates
template-file-server.ejs
```
- Code from 'generator.mjs':
```javascript
files: [{ templates: ['template-file-base-application'] }],
```
---

fix writing task filename in generate-blueprint

---

generators/app/__snapshots__/generator.spec.mts.snap
generators/app/support/config.mts
generators/base-application/types.d.mts
generators/bootstrap-application/generator.mts
generators/ci-cd/__snapshots__/ci-cd.spec.mts.snap
generators/common/__snapshots__/generator.spec.mjs.snap
generators/common/templates/README.md.jhi.ejs
generators/gatling/files.mts
generators/gatling/templates/README.md.jhi.gatling.ejs
generators/server/files.mjs
generators/server/templates/README.md.jhi.spring-boot.ejs

Related to https://github.com/jhipster/generator-jhipster/issues/23449
---

Split README fragments

---

generators/base-core/generator.mts

Related to https://github.com/jhipster/generator-jhipster/pull/23668?notification_referrer_id=NT_kwDOABWf37I3ODcwNDExMTMwOjE0MTcxODM#issuecomment-1741763461
---

use posix relative at templates

---

generators/cypress/templates/src/test/javascript/cypress/e2e/account/login-page.cy.ts.ejs
generators/server/templates/src/main/java/_package_/config/SecurityConfiguration_imperative.java.ejs
generators/server/templates/src/main/java/_package_/config/SecurityConfiguration_reactive.java.ejs

Fixes https://github.com/jhipster/generator-jhipster/issues/22843.
---

allow /login to be accesed directly at session auth

---

generators/gradle/constants.mjs

https://docs.gradle.org/8.4/release-notes.html
Java 21 is now supported!
---

Upgrade to Gradle 8.4

---

generators/base-application/generator.mts
generators/base-application/generator.spec.mts
generators/base-application/tasks.d.mts
generators/base-core/generator.mts
generators/base/generator.mts
generators/base/priorities.mjs
generators/base/tasks.d.mts
generators/entity/generator.mjs
generators/entity/prompts.mjs
generators/server/generator.mjs

- add a postPreparing priority
- move entity prompts to postPreparing
- rework entity to use shared application.
Related to https://github.com/jhipster/generator-jhipster/issues/23449
---

Rework entity generator

---

.github/workflows/stale.yml

- use `ascending` options to process old issues first
- use `main` branch for [optimized calls and caching feature](https://github.com/actions/stale/pull/1033)
Current `operations-per-run` is kept low to give time for contributors to give feedback if needed.
Related to https://github.com/jhipster/generator-jhipster/issues/22252.
---

stale workflow adjusts

---

generators/java/templates/src/main/java/_package_/_entityPackage_/domain/_persistClass_.java.jhi.ejs

Using getter in equals() methods to be Hibernate-safe
Fix #23753  The implementation of the equals method is not Hibernate-safe #23753 
---

Using getter in equals() methods to be Hibernate-safe

---

generators/bootstrap-application/generator.mts
generators/bootstrap/generator.mts
generators/common/__snapshots__/generator.spec.mjs.snap
generators/common/templates/README.md.jhi.ejs
generators/generator-constants.mts
generators/info/generator.mts
generators/server/templates/README.md.jhi.spring-boot.ejs

- prettier 3 doesn't looks for plugins anymore, adding an extension without the plugin results in error. Drop svelte extension for this reason.
- allow bootstrap prettier support to be customized.
- adjust README.
- info adjusts (fix workspaces support and make custom commit conditional).
Related to https://github.com/jhipster/generator-jhipster/issues/23449.
---

Adjusts for blueprint support

---

generators/base-application/support/prepare-entity.mts

Related to https://github.com/jhipster/generator-jhipster/issues/23917.
---

use defaults utility at relationships.

---

generators/server/templates/src/main/java/_package_/web/rest/errors/ExceptionTranslator.java.ejs
generators/server/templates/src/test/java/_package_/web/rest/AccountResourceIT.java.ejs

This reverts the change for hiding registration errors.
relates to #21731
---

do not hide registration errors (login/email already used)

---

generators/server/templates/pom.xml.ejs

This PR fixes only the warning emitted by the maven-resource-plugin
* It uses a specific execution ID to not have the configuration applied to the default resources:resources mojo
* It removes the copy of non-filtered files which is already done by resources:resources
---

fix(#22487): Remove warning for resources plugins

---

generators/kubernetes/__snapshots__/kubernetes.spec.mts.snap
generators/kubernetes/templates/ingress.yml.ejs

Fix #23962
k8s sub-generator, remove deprecated annotation from Kubernetes ingress template
---

remove deprecated annotation from kubernetes ingress template

---

.github/workflows/generator-generate-blueprint.yml
test-integration/generate-blueprint-samples/default/.yo-rc.json

it's stable enough but is timing out too often.
---

drop app generator from generate-blueprint sample

---

generators/react/resources/package.json
generators/react/templates/package.json.ejs
generators/react/templates/src/main/webapp/app/config/icon-loader.ts.ejs
generators/react/templates/src/main/webapp/app/routes.tsx.ejs
generators/react/templates/src/main/webapp/app/shared/layout/menus/entities.tsx.ejs
generators/react/templates/tsconfig.test.json.ejs
generators/react/templates/webpack/webpack.microfrontend.js.jhi.react.ejs

Fixes https://github.com/jhipster/generator-jhipster/issues/21990
---

fix react admin menu using module federation.

---

README.md

Fixes https://github.com/jhipster/generator-jhipster/issues/23933.

Add Java and Node versions supported

---

generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/list/_entityFile_.component.html.ejs
generators/react/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_.tsx.ejs
generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_.vue.ejs

Fix #22801
It is interesting to note, that tabs were already supported by react, so there was nothing to do for react. With this PR the view and edit "buttons" for angular and vue (here only authentication type "session") work in the same way like react. Vue produces an error for links opened in new tabs when authentication type is not "session". Working with tabs works best in session mode, e.g. with JWT authentication a login for each tab is required. But even when a login is required, this PR makes it still easier to copy or share view/edit links.
---

allow view/edit in new tabs from list view

---

generators/languages/generator.mjs
generators/languages/translation-data.mjs
generators/server/__snapshots__/generator.spec.mjs.snap

ensure when skipClient option is set, only server files are generated
Fix #23943
---

add validation of skipClient in language generator

---

generators/project-name/generator.mjs

Fixed Hyphen issue the base application name
---

Fixed Hyphen issue the base application name

---

generators/base-application/support/prepare-entity.mts
generators/base-application/support/prepare-entity.spec.mts
generators/bootstrap-application-server/generator.mts
generators/liquibase/generator.mts

Related to https://github.com/jhipster/generator-jhipster/issues/23449#issuecomment-1784390389.
---

remove warning for microfrontends

---

.github/workflows/angular.yml
.github/workflows/cache.yml
.github/workflows/devserver.yml
.github/workflows/generator-database-changelog-liquibase.yml
.github/workflows/generator-generate-blueprint.yml
.github/workflows/generator.yml
.github/workflows/issue-check.yml
.github/workflows/lock-maintenance.yml
.github/workflows/react.yml
.github/workflows/vue.yml

Or matrix is quite big, a save/restore cache action is not really useful.
We use different frameworks angular/react/vue and optional dependencies to be cached, we would require a 1-to-1 cache/sample but cache limit is not big enough (~40 samples).
Our build-cache brings a very wide cache support, use it everywhere.
Switch every action/cache usage to be restore only except the build-cache.
---

optimize caching restore

---

generators/react/templates/src/main/webapp/app/modules/home/home.tsx.ejs
generators/react/templates/src/main/webapp/app/shared/layout/header/header-components.tsx.ejs
generators/react/templates/src/main/webapp/app/shared/layout/header/header.scss.ejs
generators/vue/templates/src/main/webapp/app/core/jhi-navbar/jhi-navbar.vue.ejs

I created apps using the following commands:
```
jhipster --defaults --skip-install --client-framework angular
jhipster --defaults --skip-install --client-framework react
jhipster --defaults --skip-install --client-framework vue
```
Here are the results:
This PR makes the banners more similar. You might notice there are still some differences. Notably, Angular has no line around the body content, React has a line with a silver background, and Vue has no line but does have a gray background. 
---

Make banners similar between frameworks

---

.github/actions/cache-java-dependencies/action.yml

websocket should be disabled for reactive applications.
---

adjust cache

---

.blueprint/generate-sample/generator.mjs
generators/base-application/support/index.mts
generators/base-application/support/update-application-entities-transform.mts
generators/jdl/generator.mts
generators/jdl/generator.spec.mts

`generate-sample` mixes in-memory file operations with disk operations.
Additional work should be applied to synchronize them.
related to https://github.com/jhipster/generator-jhipster/issues/24135.
---

adjusts to generate-sample

---

generators/app/__snapshots__/generator.spec.mts.snap
generators/entities/__snapshots__/generator.spec.mts.snap
generators/languages/generator.mjs
generators/languages/languages.spec.mjs
generators/languages/prompts.mjs
generators/server/__snapshots__/generator.spec.mjs.snap
jdl/jhipster/default-application-options.ts

fixes https://github.com/jhipster/generator-jhipster/issues/24125
---

languages adjusts

---

.mocharc.cjs
generators/base-application/generator.mts
generators/base/api.d.mts
generators/bootstrap-application-base/generator.spec.mts
generators/bootstrap-application-client/generator.spec.mts
generators/bootstrap-application-server/generator.spec.mts
generators/ci-cd/__snapshots__/ci-cd.spec.mts.snap
generators/common/__snapshots__/generator.spec.mjs.snap
generators/cucumber/__snapshots__/generator.spec.mts.snap
generators/entities/generator.spec.mts
generators/export-jdl/__snapshots__/export-jdl.spec.mts.snap
generators/gatling/__snapshots__/generator.spec.mts.snap
generators/heroku/__snapshots__/heroku.spec.mts.snap
generators/server/__test-support/index.mts
generators/upgrade/upgrade.spec.mts
test/mocha.config.cjs
test/support/tests.mjs
testing/helpers.mts

- add a default creationTimestamp
- pass useVersionPlaceholders and fakeKeytool using test utilities defaults instead of env variable at mocha config bootstrap.
They will be applied at blueprints too.
- deprecate applicationWithEntities option. It's mainly used by tests now and `withJHipsterConfig` can be used instead.
---

Improve test defaults

---

generators/angular/support/translate-angular.mjs
generators/languages/support/translate.mts

Related to https://github.com/jhipster/generator-jhipster/pull/24207
---

escape html characters

---

generators/base-core/generator.mts
generators/base/api.d.mts
generators/entities/__snapshots__/generator.spec.mts.snap
generators/languages/generator.mjs

Fixes https://github.com/jhipster/generator-jhipster/issues/24204
---

write translation files even for entity only generation

---

generators/app/__snapshots__/generator.spec.mts.snap
generators/base-application/generator.mts
generators/base-entity-changes/generator.mts
generators/bootstrap-application-base/generator.mts
generators/bootstrap-application/generator.spec.mts
generators/export-jdl/generator.mts
generators/jdl/__snapshots__/generator.spec.mts.snap
generators/server/generator.mjs
jdl/__snapshots__/jdl-importer.spec.ts.snap
jdl/__test-files__/annotations.jdl
jdl/converters/jdl-to-json/jdl-to-json-basic-entity-converter.ts
jdl/converters/jdl-to-json/jdl-to-json-basic-entity-information-converter.spec.ts
jdl/converters/jdl-to-json/jdl-with-applications-to-json-converter.spec.ts
jdl/converters/jdl-to-json/jdl-without-application-to-json-converter.spec.ts
jdl/converters/json-to-jdl-entity-converter.ts
jdl/converters/parsed-jdl-to-jdl-object/entity-converter.spec.ts
jdl/converters/parsed-jdl-to-jdl-object/entity-converter.ts
jdl/converters/parsed-jdl-to-jdl-object/parsed-jdl-to-jdl-object-converter.spec.ts
jdl/converters/parsed-jdl-to-jdl-object/parsed-jdl-to-jdl-object-converter.ts
jdl/exporters/jhipster-entity-exporter.ts
jdl/integration-test.spec.ts
jdl/jdl-importer.spec.ts
jdl/jhipster/json-entity.spec.ts
jdl/jhipster/json-entity.ts
jdl/models/jdl-entity.ts
jdl/models/jdl-field.ts
jdl/models/jdl-object.spec.ts
jdl/models/jdl-object.ts
jdl/models/jdl-relationship.spec.ts
jdl/models/jdl-relationship.ts

- move annotations a separate object to don’t mixup with other fields.
- move changelogDate to that annotation object
Maybe changelogDate should be kept at root and exported like an annotation as an exception.
Fixes https://github.com/jhipster/generator-jhipster/issues/24262
---

Export annotations

---

.github/workflows/angular.yml
.github/workflows/devserver.yml
.github/workflows/generators.yml
.github/workflows/react.yml
.github/workflows/vue.yml

We always create PR for others branches, CI on push are not useful for us.
Enable most CI workflow only for 
- main
- **maintenance
---

ignore most CI workflows at every non main/maintenance branch

---

generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_.model.ts.ejs
generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/detail/_entityFile_-detail.component.html.ejs
generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/list/_entityFile_.component.html.ejs
generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/update/_entityFile_-form.service.spec.ts.ejs
generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/update/_entityFile_-form.service.ts.ejs
generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/update/_entityFile_-update.component.html.ejs
generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/update/_entityFile_-update.component.spec.ts.ejs
generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/update/_entityFile_-update.component.ts.ejs
generators/base-application/support/prepare-entity.mts
generators/base-application/support/prepare-relationship.mjs
generators/base-application/types/relationship.d.mts
generators/cypress/templates/src/test/javascript/cypress/e2e/entity/_entity_.cy.ts.ejs
generators/java/command.mts
generators/java/entity-files.mts
generators/java/generator.mts
generators/java/templates/src/main/java/_package_/_entityPackage_/domain/_persistClass_.java.jhi.jackson_identity_info.ejs
generators/react/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_-detail.tsx.ejs
generators/react/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_-update.tsx.ejs
generators/react/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_.tsx.ejs
generators/server/support/prepare-entity.mjs
generators/spring-data-neo4j/generator.mts
generators/spring-data-neo4j/templates/src/main/java/_package_/_entityPackage_/domain/_persistClass_.java.jhi.spring_data_neo4j.ejs
generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_-details.vue.ejs
generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_-update.component.spec.ts.ejs
generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_-update.component.ts.ejs
generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_-update.vue.ejs
generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_.vue.ejs
test-integration/samples/jdl-entities/custom-id.jdl

Neo4j fetches and persists the entire graph.
- add warn about DTO incompatibility.
- add warn about User relationship security (User will be persisted).
- every relationship is editable.
- use `@JsonIdentityInfo` instead of `@JsonIgnore`.
Fixes https://github.com/jhipster/generator-jhipster/issues/24076
Fixes https://github.com/jhipster/generator-jhipster/issues/13797
---

add persistableRelationship and adjust Neo4j

---

generators/app/__snapshots__/generator.spec.mts.snap
generators/docker/__snapshots__/generator.spec.mts.snap
generators/server/templates/gradle/profile_dev.gradle.ejs
generators/server/templates/gradle/profile_prod.gradle.ejs
generators/spring-data-relational/generator.mts
generators/spring-data-relational/internal/dependencies.mts
generators/spring-data-relational/support/database-data.mts
generators/spring-data-relational/support/database-url.spec.mts
generators/spring-data-relational/templates/src/test/java/_package_/config/SqlTestContainersSpringContextCustomizerFactory.java.ejs
test-integration/jdl-samples/ms-mf-react-eureka-oauth2-mariadb-infinispan/blog-store.jdl
test-integration/workflow-samples/react.json

- switch mariadb to use r2dbc-mysql (again) commit https://github.com/jhipster/generator-jhipster/pull/24199/commits/a768dd3c92ae99f0407ed7decce117c0cb8a40c9
- add prodDatabaseDriver to application
Fixes https://github.com/jhipster/generator-jhipster/issues/20363.
---

reinstate reactive mariadb tests using r2dbc-mysql

---

generators/angular/templates/angular.json.ejs

Fixes deprecating warning when using `npm start` with Angular.
```
$ npm start
> blog@0.0.1-SNAPSHOT start
> ng serve --hmr
Option "browserTarget" is deprecated: Use 'buildTarget' instead.
NOTICE: Hot Module Replacement (HMR) is enabled for the dev server.
```
---

[Fix] Option "browserTarget" is deprecated: Use 'buildTarget' instead.

---

generators/server/templates/src/main/java/_package_/_entityPackage_/repository/_entityClass_Repository.java.ejs
generators/server/templates/src/main/java/_package_/config/SecurityConfiguration_imperative.java.ejs
generators/server/templates/src/main/java/_package_/config/SecurityConfiguration_reactive.java.ejs

related to https://github.com/jhipster/generator-jhipster/issues/24374
---

configure principal claim name for oauth2

---

generators/server/templates/src/main/java/_package_/service/MailService.java.ejs

Calling a `@Async` without been proxied is reported by sonar as a code smell.
Add a non async internal method since calling a `@Async` method from a `@Async` method creates an unnecessary twice async.
Fixes https://github.com/jhipster/generator-jhipster-native/issues/101
Implement https://github.com/jhipster/generator-jhipster/pull/24034#pullrequestreview-1702797684
---

don't use self reference

---

generators/languages/templates/entity/i18n/entity_pt-br.json.ejs
generators/server/templates/build.gradle.ejs
generators/server/templates/src/main/java/_package_/_entityPackage_/service/mapper/_entityClass_Mapper.java.ejs
generators/spring-data-elasticsearch/templates/src/main/java/_package_/_entityPackage_/domain/_persistClass_.java.jhi.elastic_search.ejs

Syntax coloring in IDE (i.e. yeoman IJ plugin) are broken when comments are made with //, this PR aligns template comments using /**/ which makes it accurate again
---

use /**/ for template comments

---

generators/server/templates/build.gradle.ejs

As the linked issue in open api generator is closed and we don't have javax.validation api anymore in general I have just remove it from gradle too.
---

[gradle] cleanup javax.validation usage

---

generators/base/__snapshots__/generator.spec.mts.snap
generators/base/api.d.mts
generators/base/blueprints.spec.mts
generators/base/command.mts
generators/base/generator.mts

Related to https://github.com/jhipster/generator-jhipster/pull/24190.
---

[internal] add support to disable blueprints

---

generators/angular/templates/src/main/webapp/app/app.config.ts.ejs

This PR uses https://angular.io/api/router/withNavigationErrorHandler to handle navigation error events, which can't be handled by our http interceptor error handlers. 
I tried to extract a dedicated class, but failed miserable to have that injected in the config.ts file. Either I got no injector defined or the injected class was wrong/not constructed such that it failed with `... has not method ...`. Looks like I need to refresh my angular skills :(
updates #24396
---

Handle Angular navigation errors

---

.blueprint/from-issue/generator.mjs
.github/workflows/linked-issue-check.yml

Resolve https://github.com/jhipster/generator-jhipster/issues/24183

[internal] add linked issue workflow that check closing issues samples

---

generators/git/templates/.gitignore.jhi.ejs
generators/gradle/__snapshots__/generator.spec.js.snap
generators/gradle/files.ts
generators/gradle/generator.ts
generators/gradle/internal/needles.ts
generators/gradle/needles.spec.ts
generators/gradle/templates/buildSrc/build.gradle.ejs
generators/gradle/types.d.ts
generators/server/templates/build.gradle.ejs

This PR adds the needed "infrastructure" part to use gradle convention plugins.
updates #19615
---

[gradle] generate initial files for convention plugin usage

---

generators/ci-cd/ci-cd.spec.ts
generators/ci-cd/command.ts

Fixes https://github.com/jhipster/generator-jhipster/issues/24564
---

fix ci-cd prompts

---

generators/server/command.ts
generators/server/support/__snapshots__/needles.spec.ts.snap

Added a when to the feingClient command where it checks if the application type is not a Monolith
closes #24560
---

Do not prompt for feign clients when creating a monolith 

---

.github/actions/build-matrix/action.yml
.github/actions/setup-default-node-java/action.yml
.github/workflows/generator.yml
.github/workflows/lock-maintenance.yml
.mocharc.cjs
cli/cli.spec.mts
generators/java/support/checks/check-java.spec.ts
package-lock.json
package.json

- node 18.19.0 backported dynamic loader register
Use dynamic register and drop support for test using node < 18.19.0
- bump node to 18.19.0
- switch to quibble for dependencies mocking
related to https://github.com/jhipster/generator-jhipster/pull/23980
---

[internal] Use the quibble for dependency mock in tests

---

generators/gatling/__snapshots__/generator.spec.ts.snap
generators/gatling/files.ts
generators/gatling/generator.spec.ts
generators/gatling/generator.ts
generators/gatling/templates/buildSrc/src/main/groovy/jhipster.gatling-conventions.gradle.ejs
generators/generator-constants.js
generators/gradle/__snapshots__/generator.spec.js.snap
generators/gradle/files.ts
generators/gradle/generator.ts
generators/gradle/internal/needles.ts
generators/gradle/needles.spec.ts
generators/gradle/templates/buildSrc/gradle/libs.versions.toml.ejs
generators/gradle/templates/gradle/libs.versions.toml.ejs
generators/gradle/types.d.ts
generators/server/templates/build.gradle.ejs
generators/server/templates/gradle.properties.ejs
generators/server/templates/settings.gradle.ejs

This is the first and initial part to use gradle convention plugins and mostly replace the current apply from approach.
The gatling generator now creates a convention plugin in `buildSrc` and applied it to main `build.gradle`. Dependencies and configurations are encapsulated in the convention plugin.
Open points I would like to fix are mostly (snapshot) tests
---

gradle gatling convention plugin

---

generators/cucumber/__snapshots__/generator.spec.ts.snap
generators/cucumber/files.ts
generators/cucumber/generator.spec.ts
generators/cucumber/generator.ts
generators/cucumber/templates/buildSrc/src/main/groovy/jhipster.cucumber-conventions.gradle.ejs
generators/server/templates/build.gradle.ejs

This uses the newly introduced convention plugin mechanism and creates a cucumber convention plugin (instead of if constructs and direct configuration in the main `build.gradle`).
updates #19615
---

[gradle] add gradle cucumber convention plugin

---

generators/angular/__snapshots__/generator.spec.ts.snap
generators/app/__snapshots__/generator.spec.ts.snap
generators/app/support/config.ts
generators/base-application/support/relationship.ts
generators/base-application/types.d.ts
generators/bootstrap-application-base/generator.ts
generators/jdl/__snapshots__/generator.spec.ts.snap
generators/react/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_-update.tsx.ejs
generators/server/command.ts
generators/server/generator.js
generators/server/jdl/application-definition.ts
generators/server/options/sync-user-with-idp.spec.ts
generators/server/options/sync-user-with-idp.ts
generators/server/types.d.ts
generators/spring-data-cassandra/__snapshots__/generator.spec.ts.snap
generators/spring-data-couchbase/__snapshots__/generator.spec.ts.snap
generators/spring-data-elasticsearch/__snapshots__/generator.spec.ts.snap
generators/spring-data-elasticsearch/__test-support/elastic-search-matcher.ts
generators/spring-data-elasticsearch/cleanup.js
generators/spring-data-elasticsearch/files.js
generators/spring-data-mongodb/__snapshots__/generator.spec.ts.snap
generators/spring-data-neo4j/__snapshots__/generator.spec.ts.snap
generators/spring-data-relational/__snapshots__/generator.spec.ts.snap
generators/spring-data-relational/__snapshots__/sql-entities.spec.ts.snap
generators/vue/__snapshots__/generator.spec.ts.snap
test-integration/jdl-samples/ms-mf-react-eureka-oauth2-mariadb-infinispan/blog-store.jdl
test-integration/jdl-samples/ms-mf-vue-consul-oauth2-mysql-memcached/blog-store.jdl

Fixes https://github.com/jhipster/generator-jhipster/issues/24600.
Fixes https://github.com/jhipster/generator-jhipster/issues/18755.
---

add syncUserWithIdp option

---

.blueprint/generate-sample/support/generate-sample.js
generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_-details.component.spec.ts.ejs
generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_-details.component.ts.ejs
generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_-details.vue.ejs
generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_-update.component.spec.ts.ejs
generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_-update.component.ts.ejs
generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_-update.vue.ejs
generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_.component.spec.ts.ejs
generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_.component.ts.ejs
generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_.service.spec.ts.ejs
generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_.service.ts.ejs
generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_.vue.ejs
test-integration/workflow-samples/vue.json

[Vue] Vue frontend doesn't detect custom primary key names

---

generators/server/files.js
generators/server/generator.js
generators/server/templates/build.gradle.ejs
generators/server/templates/buildSrc/src/main/groovy/jhipster.code-quality-conventions.gradle.ejs
generators/server/templates/buildSrc/src/main/groovy/jhipster.docker-conventions.gradle.ejs
generators/spring-data-cassandra/__snapshots__/generator.spec.ts.snap
generators/spring-data-couchbase/__snapshots__/generator.spec.ts.snap
generators/spring-data-elasticsearch/__snapshots__/generator.spec.ts.snap
generators/spring-data-mongodb/__snapshots__/generator.spec.ts.snap
generators/spring-data-neo4j/__snapshots__/generator.spec.ts.snap
generators/spring-data-relational/__snapshots__/generator.spec.ts.snap

the next PR which extracts functions into a dedicated gradle convention plugin instead "apply from" in main build file.
updates #19615
---

extract gradle jib config to dedicated conventions plugin

---

.github/workflows/stale.yml

This is needed so copyright-update workflow works
---

Remove copyright dates from stale workflow

---

generators/server/generator.js
generators/server/templates/src/test/java/_package_/_entityPackage_/web/rest/_entityClass_ResourceIT.java.ejs
test-integration/samples/jdl-entities/cyclic.jdl

Disable junit tests in case of cyclic required relationships.
Fixes https://github.com/jhipster/generator-jhipster/issues/19801
---

disable junit test for cyclic required relationships

---

generators/server/generator.js
generators/server/templates/src/test/java/_package_/IntegrationTest.java.ejs
generators/server/templates/src/test/java/_package_/config/JHipsterBlockHoundIntegration.java.ejs
generators/server/templates/src/test/resources/junit-platform.properties.ejs
generators/server/types.d.ts
generators/spring-data-mongodb/generator.js
test-integration/jdl-samples/ms-ng-consul-oauth2-mongodb-caffeine/blog-store.jdl
test-integration/workflow-samples/angular.json

- enable backend test for webflux + mongodb
- set mongodb workspaces sample to use mongodb database
- add needles for blockhound
- customize blockhound for mongodb
- use default test timeouts for mongodb
Closes https://github.com/jhipster/generator-jhipster/issues/17478.
---

Reinstate webflux + mongodb tests

---

.blueprint/from-issue/generator.mjs
.github/workflows/linked-issue-check.yml

Fixes https://github.com/jhipster/generator-jhipster/issues/24749
---

check for existing sample at closing issue

---

generators/angular/templates/src/main/webapp/app/admin/user-management/detail/user-management-detail.component.spec.ts.ejs
generators/angular/templates/src/main/webapp/app/admin/user-management/detail/user-management-detail.component.ts.ejs
generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/detail/_entityFile_-detail.component.ts.ejs

remove not necessary ActivatedRoute usages

---

generators/angular/__snapshots__/generator.spec.ts.snap
generators/angular/entity-files-angular.ts
generators/angular/generator.ts
generators/angular/support/needles.ts
generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_.routes.ts.ejs
generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/update/_entityFile_-form.service.spec.ts.ejs
generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/update/_entityFile_-update.component.html.ejs
generators/base-application/types/entity.d.ts
generators/bootstrap-application-base/utils.js
generators/client/generator.js
generators/cypress/__snapshots__/generator.spec.ts.snap
generators/cypress/files.ts
generators/cypress/generator.ts
generators/cypress/templates/src/test/javascript/cypress/e2e/entity/_entity_.cy.ts.ejs
generators/languages/entity-files.js
generators/languages/generator.js
generators/react/entity-files-react.js
generators/vue/entity-files-vue.js
generators/vue/files-vue.js
test-integration/samples/jdl-entities/02-authority-relationship.jdl

Fixes https://github.com/jhipster/generator-jhipster/issues/22106.
Closes https://github.com/jhipster/generator-jhipster/pull/22105.
Authority Customizations
- Remove ui:
```
@SkipClient
entity Authority
```
- Make it read only:
```
@ReadOnly
entity Authority
```
- Allow users to view:
```
@EntityReadAuthority(ROLE_USER)
entity Authority
```
---

Add authority angular ui.

---

generators/base-application/support/prepare-field.js

FakerJS 8.4.0: faker.number.float({ precision }) is deprecated

---

generators/angular/templates/src/main/webapp/app/account/password-reset/init/password-reset-init.component.spec.ts.ejs
generators/angular/templates/src/main/webapp/app/account/register/register.component.spec.ts.ejs
generators/angular/templates/src/main/webapp/app/account/sessions/sessions.component.spec.ts.ejs
generators/angular/templates/src/main/webapp/app/login/login.component.spec.ts.ejs

The signature '(error: any): Observable<never>' of 'throwError' is deprecated
Fix
Deprecated
---

[Angular] The signature '(error: any): Observable<never>' of 'throwError' is deprecated

---

.github/workflows/stale.yml

v8 label is a feature request. Not goals anymore.
Drop from stale.
Increase stale operations since it already did a triage in every issue.
---

drop v8 from stale exempt labels.

---

generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_.model.ts.ejs

Fixes https://github.com/jhipster/generator-jhipster/issues/24653
---

ignore not relevant fields at model

---

generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_.routes.ts.ejs
generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/list/_entityFile_.component.spec.ts.ejs
generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/list/_entityFile_.component.ts.ejs

Remove unnecessary method and parameters from methods.
---

[angular] simplify list component

---

generators/server/templates/src/test/java/_package_/security/jwt/JwtAuthenticationTestUtils.java.ejs

Observed a misspelling in the `JwtAuthenticationTestUtils.java.ejs` template using the `JwtClaimsSet.builder` setting claims via a Lambda expression.
`s/customClain/customClaim`
Fixes #25079
---

chore: correct misspelling in lambda expression

---

generators/spring-boot/templates/_global_partials_entity_/it_patch_update.partial.java.ejs
generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/web/rest/_entityClass_ResourceIT.java.ejs

Create should fail in some conditions.
Tests relies on findAll `last` item, but it's not correct for some databases and some primary key types (like string and uuid) since the result is ordered by default.
- test the rest result and the inserted registry using findById.
---

[server] improve create integration test. 

---

generators/spring-data-relational/templates/src/test/java/_package_/config/MsSqlTestContainer.java.ejs
generators/spring-data-relational/templates/src/test/resources/config/application-testdev.yml.ejs

- **Explicitly accepting the license programmatically**: This eliminates the need for users to manually create a `container-license-acceptance.txt` file, streamlining setup.
- **Removing outdated comments**: The configuration file has been updated to remove comments about manual license acceptance, as this is now handled automatically.
- This change is aligned with the official Testcontainers documentation for [MSSQL Server modules](https://java.testcontainers.org/modules/databases/mssqlserver/#:~:text=test%20as%20normal-,EULA%20Acceptance,-Due%20to%20licencing).
- The documentation states that license acceptance can be done either programmatically or via a resource file, and this PR adopts the programmatic approach for a more streamlined experience.
---
Please make sure the below …

Simplify MSSQL Server testcontainer setup for integration tests

---

generators/base-application/generator.ts
generators/base-application/tasks.d.ts
generators/bootstrap-application-base/generator.ts

Currently LOADING_ENTITIES is not really useful. It was just for internal use.
---

pass entity object at LOADING_ENTITIES

---

generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/detail/_entityFile_-detail.component.spec.ts.ejs

Related to #25137 
Fix this coverage on a lot of Angular files https://sonarcloud.io/component_measures?id=jhipster-sample-application&metric=coverage&selected=jhipster-sample-application%3Asrc%2Fmain%2Fwebapp%2Fapp%2Fentities%2Ffield-test-entity%2Fdetail%2Ffield-test-entity-detail.component.ts
Before merge

[Angular] Improve coverage

---

generators/spring-data-relational/templates/src/main/java/_package_/_entityPackage_/repository/_entityClass_RepositoryWithBagRelationshipsImpl.java.ejs

https://sonarcloud.io/project/issues?open=AX8O6J1sAp4U05lfRflU&id=jhipster-sample-application
---

fix duplicated literal code smell

---

generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/service/criteria/_entityClass_CriteriaTest.java.ejs

Introduced to meet a coverage condition but is considered a bug by sonar
---

fix sonar issue

---

generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/web/rest/_entityClass_ResourceIT.java.ejs

Fixes https://github.com/jhipster/generator-jhipster/issues/25137
Fixes sonar https://sonarcloud.io/project/issues?open=AXTEizECShI07f3zq3pb&id=jhipster-sample-application and https://sonarcloud.io/project/issues?open=AXTEizFQShI07f3zq3pj&id=jhipster-sample-application
---

fix sonar issues

---

generators/upgrade/generator.js

And pass `--no` to npx to force local binary.
---

add missing --with-entities option to v7

---

cli/cli.mjs
generators/upgrade/README.md
generators/upgrade/USAGE

Related to https://github.com/jhipster/generator-jhipster/pull/25203.

Minor updates to upgrade messages

---

generators/upgrade/command.ts
generators/upgrade/generator.js
generators/upgrade/index.ts

This is quite useful to change configuration.
Like if it's needed to change database from mysql to postgres:
```
jhipster upgrade --apply-config --db postgresql
```
---

add --apply-config support to upgrade

---

generators/server/templates/src/test/java/_package_/web/rest/AccountResourceIT.java.ejs

Related to #25137 
Fix https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AXTEizEpShI07f3zq3pg
---

Sonar: Replace these 3 tests with a single Parameterized one

---

generators/jdl/__snapshots__/generator.spec.ts.snap
generators/jdl/generator.spec.ts
generators/jdl/internal/application.ts

Fixes https://github.com/jhipster/generator-jhipster/issues/25175
---

add check for entity microservice

---

cli/program.mjs
generators/upgrade/command.ts
generators/upgrade/generator.js

Blueprints custom cli should have upgrade support now.
---

improve upgrade for blueprints

---

generators/upgrade/generator.js
generators/upgrade/generator.spec.js

Follow-up to https://github.com/jhipster/generator-jhipster/pull/25203
---

fix upgrade executable and add tests.

---

generators/common/__snapshots__/generator.spec.js.snap
generators/common/templates/sonar-project.properties.ejs

Fix https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AXZiLoQ8RzWdFtSYLf2r
---

Sonar: Disable S1192 on CacheConfiguration

---

generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/detail/_entityFile_-detail.component.html.ejs

so that everywhere `entityPage` is being used as attribute
I noticed that the only place where the links to entity pages are being created differently is in the entity detail page. Everywhere else (e.g. list view), entityPage is already being used. 
So this change improves consistency in the code base and also makes it easier for e.g. Blueprints to change something here consistently (that's why I came here ;-))
---

Unify creation of links to entity pages

---

ARCHITECTURE.md
BLUEPRINTS.md
CODE_OF_CONDUCT.md

Fix some typos in markdown files

---

generators/feign-client/templates/src/main/java/_package_/client/AuthorizedFeignClient.java.ejs

The `decode404` attribute has been deprecated and replaced with `dismiss404` in the **Spring Cloud OpenFeign** library version `4.0.0-RC1` Milestone.
- **Spring Cloud OpenFeign** - Remove deprecations and outdated API usage. [#768](https://github.com/spring-cloud/spring-cloud-openfeign/pull/768)
---

Update `@AuthorizedFeignClient` to use `dismiss404` instead of deprecated `decode404`

---

cli/program.mjs
generators/jdl/__snapshots__/generator.spec.ts.snap
generators/jdl/command.ts
generators/jdl/generator.spec.ts
generators/jdl/generator.ts
generators/workspaces/command.ts
generators/workspaces/generator.js

jdl and workspaces generators will compose with the entrypoint generator.
Allows to run jdl in react-native and ionic without backend
---

allow custom entrypoint generator

---

generators/react/templates/package.json.ejs

change webpack tls environment option
---

fix npm start-tls in react app

---

generators/gradle/generator.ts
generators/gradle/internal/needles.ts
generators/gradle/types.d.ts
generators/java/generator.ts
generators/java/support/artifacts.ts
generators/java/support/index.ts
generators/java/types.d.ts
generators/maven/types.d.ts
generators/server/templates/build.gradle.ejs
generators/server/templates/gradle.properties.ejs
generators/server/types.d.ts
generators/spring-data-cassandra/generator.js

- adds a generic addJavaDependencies api.
- add more gradle apis.
---

use api to inject cassandra dependencies

---

generators/java/generator.ts
generators/liquibase/support/maven-plugin.ts
generators/server/templates/build.gradle.ejs
generators/server/templates/gradle.properties.ejs
generators/server/templates/gradle/profile_dev.gradle.ejs
generators/server/templates/gradle/profile_prod.gradle.ejs
generators/server/templates/pom.xml.ejs
generators/spring-boot/generator.ts
generators/spring-cache/__snapshots__/generator.spec.ts.snap
generators/spring-cache/internal/dependencies.ts
generators/spring-data-couchbase/generator.js
generators/spring-data-elasticsearch/generator.js
generators/spring-data-mongodb/generator.js
generators/spring-data-neo4j/generator.ts
generators/spring-data-relational/generator.ts
generators/spring-data-relational/internal/dependencies.ts
generators/spring-websocket/generator.ts

inject db gradle dependencies using api

---

generators/server/templates/pom.xml.ejs

Fixes the following warnings with Maven builds:
<code>Warning:  Some problems were encountered while building the effective model for com.okta.developer.gateway:gateway:jar:8.1.0-git
Warning:  'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.springframework.boot:spring-boot-configuration-processor:jar -> duplicate declaration of version (?) @ line 95, column 21
Warning:  'build.plugins.plugin.version' for org.springframework.boot:spring-boot-maven-plugin is missing. @ line 321, column 21</code>
Closes https://github.com/jhipster/generator-jhipster/pull/25522

Fix Maven build so there are no warnings

---

cli/download.mts

fixes cli hang on node 20.
---

switch download command to use axios

---

generators/common/__snapshots__/generator.spec.js.snap
generators/common/generator.js
generators/init/generator.js

Fix deprecated command. 
Fixes https://github.com/jhipster/generator-jhipster/issues/25544. 
---

Replace `husky install` with `husky`

---

.github/dependabot.yml
generators/server/resources/Dockerfile

Reverts jhipster/generator-jhipster#25532 to fix #25548.

Revert "build(deps): bump mongo from 7.0.6 to 7.0.7 in /generators/server/resources"

---

generators/liquibase/__snapshots__/incremental-liquibase.spec.ts.snap
generators/liquibase/generator.ts
generators/liquibase/incremental-liquibase.spec.ts

caused by using shallow copies of being modified data
Fix #25564
---

Avoid inconsistent incremental changelog files

---

generators/angular/generator.ts
generators/bootstrap-application-base/generator.ts
generators/client/generator.js
generators/common/generator.js
generators/docker/generator.js
generators/feign-client/generator.ts
generators/java/generator.ts
generators/liquibase/generator.ts
generators/react/generator.js
generators/server/generator.js
generators/spring-boot/generator.ts
generators/spring-cache/generator.ts
generators/spring-cloud-stream/generators/kafka/generator.ts
generators/spring-cloud-stream/generators/pulsar/generator.ts
generators/spring-data-cassandra/generator.js
generators/spring-data-couchbase/generator.js
generators/spring-data-elasticsearch/generator.js
generators/spring-data-mongodb/generator.js
generators/spring-data-neo4j/generator.ts
generators/spring-data-relational/generator.ts
generators/vue/generator.js

remove type inferrence from delegateTasksToBlueprint calls

---

generators/server/resources/settings.gradle

Try to fix dependabot with gradle's versions catalog
---

add settings.gradle to fix dependabot

---

generators/angular/generator.ts
generators/angular/support/index.ts
generators/angular/support/translate-angular.spec.ts
generators/angular/support/translate-angular.ts
generators/angular/templates/src/main/webapp/app/account/password/password.component.html.ejs
generators/angular/templates/src/main/webapp/app/account/sessions/sessions.component.html.ejs
generators/angular/templates/src/main/webapp/app/account/settings/settings.component.html.ejs
generators/angular/templates/src/main/webapp/app/admin/logs/logs.component.html.ejs
generators/angular/templates/src/main/webapp/app/admin/user-management/delete/user-management-delete-dialog.component.html.ejs
generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/delete/_entityFile_-delete-dialog.component.html.ejs
generators/angular/templates/src/main/webapp/app/home/home.component.html.ejs
generators/languages/support/translate.spec.js
generators/languages/support/translate.ts
test/support/check-enforcements.ts

add simplified and improved translation process.

---

generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs
generators/docker/templates/docker/realm-config/jhipster-realm.json.ejs
generators/kubernetes/__snapshots__/kubernetes.spec.ts.snap
generators/kubernetes/templates/keycloak/keycloak-configmap.yml.ejs

Fix #25675 
I'm not an expert of Keycloak but it fixes the bug.
https://www.keycloak.org/docs/latest/upgrading/index.html#removed-registrationprofile-form-action
---

Keycloak: remove registration-profile-action

---

generators/angular/templates/src/main/webapp/app/admin/user-management/detail/user-management-detail.component.html.ejs
generators/angular/templates/src/main/webapp/app/admin/user-management/detail/user-management-detail.component.spec.ts.ejs
generators/angular/templates/src/main/webapp/app/admin/user-management/detail/user-management-detail.component.ts.ejs
generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/detail/_entityFile_-detail.component.html.ejs
generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/detail/_entityFile_-detail.component.spec.ts.ejs
generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/detail/_entityFile_-detail.component.ts.ejs

[Angular] Migrate Input to Signal Input

---

generators/angular/templates/src/main/webapp/app/layouts/main/main.component.spec.ts.ejs

[Angular] Fix console warnings when running `main.component.spec.ts`

---

generators/angular/support/translate-angular.ts
generators/languages/support/translate.ts

adjusts to translate api

---

generators/base-core/generator.ts
generators/base/api.d.ts
generators/base/generator.ts
generators/server/generator.js

Allow generator-less blueprints to specify generators to be composed.
---

add compose to command definition.

---

.github/actions/setup-generator-jhipster-jit/action.yml
.github/workflows/angular.yml
.github/workflows/react.yml
.github/workflows/vue.yml
generators/base-core/generator.ts
generators/base/api.d.ts
generators/client/__workflow/devserver-angular.json
generators/client/__workflow/devserver-react.json
generators/client/__workflow/devserver-vue.json
generators/client/generator.js
generators/common/__snapshots__/generator.spec.js.snap
generators/common/command.ts
generators/common/generator.js
generators/server/generator.js
generators/spring-boot/command.ts
generators/spring-boot/generator.ts
test-integration/scripts/99-write-matrix.js
test-integration/workflow-samples/angular.json
test-integration/workflow-samples/react.json
test-integration/workflow-samples/vue.json

- workflows samples allow generic generatorOptions
- remove generator-jhipster/.github/actions/setup
- add defaultEvironment and defaultPacking to command
- keep matrix backward compatibility for jhipster-bom workflow for now.
Related to https://github.com/jhipster/generator-jhipster/issues/24135
---

finalize angular/react/vue workflows migration to jhipster/actions

---

generators/server/templates/src/main/java/_package_/config/SecurityConfiguration_imperative.java.ejs

In the production configuration, the server has enabled the compression feature (as shown below):
```yaml
server:
port: 8080
shutdown: graceful # see https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-graceful-shutdown
compression:
enabled: true
mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json,image/svg+xml
min-response-size: 1024
```
This implies that the server might be vulnerable to [BREACH](https://en.wikipedia.org/wiki/BREACH) attacks. Currently, in the `SecurityConfiguration`, we're using `CsrfTokenRequestAttributeHandler` to manage Csrf Tokens. However, according to the official documentation, "[The primary use of CsrfTokenRequestAttributeHandler is to opt-out of BREACH protection of the …

use customized `SpaCsrfTokenRequestHandler` to handle CSRF token

---

generators/gatling/__snapshots__/generator.spec.ts.snap
generators/gatling/templates/buildSrc/src/main/groovy/jhipster.gatling-conventions.gradle.ejs
generators/server/resources/gradle/libs.versions.toml

Fix #25952 
https://github.com/gatling/gatling-gradle-plugin/commit/41a43f4d2074f28571556ba86dd0cee7d1409774
---

Fix: bump io.gatling.gradle from 3.10.5.1 to 3.11.1

---

generators/angular/templates/webpack/webpack.custom.js.ejs

`config.devServer.https` is deprecated so `ng server --ssl` is now passing `config.devServer.server.type=https`.

https is deprecated so --ssl is now passing a server type

---

generators/spring-cache/templates/src/main/java/_package_/config/CacheConfiguration.java.ejs

Breaking change in redisson-3.19.0:
Default codec updated to Kryo5Codec.
Switched codec to SerializationCodec to resolve
Redis failures.
Fixes https://github.com/jhipster/generator-jhipster/issues/22889
---

Codec Update: SerializationCodec for Redis Fix

---

generators/server/templates/gradle/profile_dev.gradle.ejs
generators/server/templates/gradle/profile_prod.gradle.ejs
generators/server/templates/pom.xml.ejs
generators/server/templates/src/main/resources/config/application.yml.ejs
generators/server/templates/src/main/resources/config/bootstrap.yml.ejs

Update the generator templates for Gradle and Maven to use the Spring default delimiter of the commercial-at sign (`@`). Remove the JHipster configuration of the delimiter and default to Spring Boot Parent's configuration and allow it to inherit. This will properly scope the `config/bootstrap*.yml` and allow Spring Boot's root resources definition to handle the `**/application*.yml` files.
Fixes #25979
---

build(generator): default maven-resources-plugin to the spring-boot-parent definition

---

generators/angular/__snapshots__/generator.spec.ts.snap
generators/app/support/config.ts
generators/base-application/types.d.ts
generators/bootstrap-application-base/generator.ts
generators/bootstrap-application-server/generator.ts
generators/server/generator.js
generators/spring-boot/command.ts
generators/vue/__snapshots__/generator.spec.ts.snap

`syncUserWithIdp` config in server generator is forcing ionic and react-native blueprints to set `syncUserWithIdp` option.
---

move syncUserWithIdp to bootstrap-application-base

---

generators/app/__snapshots__/generator.spec.ts.snap
generators/base-core/generator.ts
generators/base/api.d.ts
generators/jdl/__snapshots__/generator.spec.ts.snap
generators/server/command.ts
generators/spring-boot/command.ts
generators/spring-boot/prompts.js

Related to https://github.com/jhipster/generator-jhipster/issues/24318.
---

Move some prompts to command config

---

generators/java/support/add-java-annotation.spec.ts
generators/java/support/add-java-annotation.ts
generators/java/support/generated-annotation-transform.spec.ts
generators/java/support/generated-annotation-transform.ts
generators/java/support/index.ts

- implement addJavaImport
- add parameters support to addJavaAnnotation
- implement callbacks for editFile `editFile('Foo.java', addJavaImport('package.Class'))`
---

improvements to addJavaAnnotation

---

generators/angular/templates/src/main/webapp/app/shared/alert/alert-error.component.spec.ts.ejs
generators/client/generators/common/__snapshots__/generator.spec.ts.snap
generators/client/generators/common/command.ts
generators/client/generators/common/generator.spec.ts
generators/client/generators/common/generator.ts
generators/client/generators/common/index.ts
generators/client/generators/common/templates/src/main/webapp/app/shared/jhipster/headers.ts.ejs
generators/client/generators/common/templates/src/main/webapp/app/shared/jhipster/problem-details.ts.ejs
generators/react/__snapshots__/generator.spec.ts.snap
generators/react/generator.js
generators/react/templates/src/main/webapp/app/config/axios-interceptor.spec.ts.ejs
generators/react/templates/src/main/webapp/app/config/axios-interceptor.ts.ejs
generators/react/templates/src/main/webapp/app/config/notification-middleware.spec.ts.ejs
generators/react/templates/src/main/webapp/app/config/notification-middleware.ts.ejs
generators/react/templates/src/main/webapp/app/config/store.ts.ejs
generators/react/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_.reducer.ts.ejs
generators/react/templates/src/main/webapp/app/shared/reducers/reducer.utils.ts.ejs
generators/server/templates/src/main/resources/swagger/api.yml.ejs

- add a client/common generator with problem-details and headers to be rendered in `app/shared/jhipster` designed to not be client specific.
Fixes https://github.com/jhipster/generator-jhipster/issues/25674.
---

rework react error handling

---

generators/vue/templates/tsconfig.app.json.ejs

Paths need to be relative to baseUrl
Fix #26092

change tsconfig.app.json.ejs to properly find imports

---

generators/entity/generator.js
generators/entity/prompts.js

Fixes https://github.com/jhipster/generator-jhipster/issues/26073.
---

Fix bidirectional/unidirectional question

---

generators/base-application/support/entity.ts
generators/base-application/support/relationship.ts
generators/base/shared-data.ts
generators/bootstrap-application-base/support/export-jdl-transform.ts
generators/info/generator.ts
generators/server/support/relationship.ts
jdl/converters/jdl-to-json/jdl-to-json-field-converter.ts
jdl/converters/jdl-to-json/jdl-with-applications-to-json-converter.spec.ts
jdl/converters/json-to-jdl-converter.ts
jdl/converters/json-to-jdl-entity-converter.ts
jdl/converters/types.ts
jdl/exporters/jdl-exporter.spec.ts
jdl/models/abstract-jdl-option.ts
jdl/models/jdl-application-configuration-factory.ts
jdl/models/jdl-application-configuration-option.ts
jdl/models/jdl-application-configuration.ts
jdl/models/jdl-application-definition.ts
jdl/models/jdl-application-entities.ts
jdl/models/jdl-application.ts
jdl/models/jdl-binary-option.spec.ts
jdl/models/jdl-binary-option.ts
jdl/models/jdl-deployment.ts
jdl/models/jdl-field.ts
jdl/models/jdl-unary-option.spec.ts
jdl/models/string-jdl-application-configuration-option.ts
jdl/parsing/jdl-parsing-types.d.ts
jdl/readers/json-reader.ts

Type safety - Incremental step 2

---

generators/angular/templates/src/main/webapp/app/admin/metrics/blocks/metrics-modal-threads/metrics-modal-threads.component.html.ejs
generators/angular/templates/src/main/webapp/app/shared/filter/filter.component.html.ejs

Sonar: Add a 'onKeyPress|onKeyDown|onKeyUp' attribute to this <span> tag

---

generators/angular/templates/src/main/webapp/app/admin/metrics/blocks/metrics-modal-threads/metrics-modal-threads.component.html.ejs

[Angular] style broken on the threads dump modal

---

cli/cli.spec.mts
cli/environment-builder.spec.mts
generators/base-application/generator.spec.ts
generators/client/generator-needles.spec.ts
generators/client/needle-client.spec.ts
generators/entity/database-changelog.spec.ts
generators/entity/single-entity.spec.ts
generators/gradle/needles.spec.ts
generators/java/support/checks/check-java.spec.ts
generators/java/support/doc.ts
generators/liquibase/needles.spec.ts
generators/maven/generator.spec.ts
generators/maven/needles.spec.ts
generators/server/options/database-migration.spec.ts
generators/server/options/message-broker.spec.ts
generators/server/support/needles.spec.ts
generators/upgrade/upgrade.spec.ts
testing/helpers.ts
tsconfig.spec.json

Test types adjusts

---

generators/jdl/__snapshots__/generator.spec.ts.snap
generators/jdl/generator.spec.ts
generators/jdl/generator.ts

only add applicationIndex if there is more than one application

---

.blueprint/generate-sample/command.mts
.blueprint/generate-sample/generator.mjs
.blueprint/generate-sample/support/generate-sample.js
.blueprint/generate-sample/support/index.ts

Related to https://github.com/jhipster/generator-jhipster/issues/24135
Allow to generate a sample using `.yo-rc.json` folder.
Related to https://github.com/hipster-labs/jhipster-daily-builds/pull/156.
---

improvements to generate-sample

---

.github/workflows/update-spring-boot-dependencies.yml

Add support to download pre-releases spring-boot-dependencies bom.
---

add repository to update-spring-boot-dependencies workflow

---

generators/server/templates/src/test/java/_package_/security/DomainUserDetailsServiceIT.java.ejs

don't delete all Users in DomainUserDetailsServiceITs

---

generators/server/templates/src/main/java/_package_/service/mapper/UserMapper.java.ejs
generators/server/templates/src/test/java/_package_/service/mapper/UserMapperTest.java.ejs
generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/web/rest/UserResourceIT.java.ejs

Related to https://github.com/jhipster/generator-jhipster/issues/26226.
---

move UserMapperTest to correct class

---

generators/server/templates/src/test/java/_package_/service/mapper/UserMapperTest.java.ejs

Fix:
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=jhipster-sample-application&open=AY92SBUezvwT9Xfig0tM
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=jhipster-sample-application&open=AY92SBUezvwT9Xfig0tN
---

Sonar: Rename 'user' which hides the field declared at line 25

---

generators/server/templates/build.gradle.ejs
generators/server/templates/pom.xml.ejs
generators/server/templates/src/main/java/_package_/config/SecurityConfiguration_imperative.java.ejs
generators/server/templates/src/main/java/_package_/config/SecurityConfiguration_reactive.java.ejs
generators/server/templates/src/main/java/_package_/config/SecurityJwtConfiguration.java.ejs
generators/server/templates/src/main/resources/config/application.yml.ejs
generators/server/templates/src/test/resources/config/application.yml.ejs
generators/spring-boot/resources/spring-boot-dependencies.pom
generators/spring-cache/__snapshots__/generator.spec.ts.snap
generators/spring-cache/internal/dependencies.ts
generators/spring-data-cassandra/generator.js

Follow https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.3-Release-Notes.
Fixes https://github.com/jhipster/generator-jhipster/issues/26205.
---

Bump spring-boot to v3.3.0

---

generators/gatling/README.md
generators/gatling/templates/src/test/java/gatling/simulations/_entityClass_GatlingTest.java.ejs

Should remove a lot of Sonar code smells like https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=jhipster-sample-application&open=AY92SBeNzvwT9Xfig0tw
---

Sonar: This block of commented-out lines of code should be removed

---

generators/spring-boot/generator.ts
generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/service/UserServiceIT.java.ejs
generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/web/rest/PublicUserResourceIT.java.ejs
generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/web/rest/UserResourceIT.java.ejs

Should fix https://github.com/hipster-labs/jhipster-daily-builds/actions/workflows/neo4j.yaml
---

cleanup cache in tests

---

generators/angular/templates/src/main/webapp/app/login/login.component.spec.ts.ejs
generators/angular/templates/src/main/webapp/app/login/login.component.ts.ejs

[Angular] Use viewChild signal

---

generators/angular/templates/src/main/webapp/app/admin/user-management/delete/user-management-delete-dialog.component.html.ejs
generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/delete/_entityFile_-delete-dialog.component.html.ejs

Related to https://github.com/SonarSource/sonar-html/pull/291#issuecomment-2109599752.
The dismiss button in the header is duplicated of the cancel button action.
We can remove the button from the header or ignore the error.
---

remove close button from the header.

---

generators/angular/templates/src/main/webapp/app/shared/auth/has-any-authority.directive.ts.ejs

use input instead of @Input

---

generators/cypress/templates/src/test/javascript/cypress/e2e/account/login-page.cy.ts.ejs
generators/cypress/templates/src/test/javascript/cypress/e2e/account/password-page.cy.ts.ejs
generators/cypress/templates/src/test/javascript/cypress/e2e/account/register-page.cy.ts.ejs
generators/cypress/templates/src/test/javascript/cypress/e2e/account/reset-password-page.cy.ts.ejs
generators/cypress/templates/src/test/javascript/cypress/e2e/entity/_entity_.cy.ts.ejs

Fix warn
Already done here https://github.com/jhipster/generator-jhipster/blob/f360fb3c4cb8411ef05f1dbd75032d5334a0d50f/generators/cypress/templates/src/test/javascript/cypress/e2e/account/settings-page.cy.ts.ejs#L77
---

Cypress: Fix warn 'response is possibly undefined'

---

generators/server/templates/src/main/java/_package_/service/dto/UserDTO.java.ejs

Fix https://sonarcloud.io/project/issues?impactSoftwareQualities=RELIABILITY&resolved=false&id=jhipster-sample-application&open=AY_K3S5AJ3L5BOxqA_oV
Related to this commit https://github.com/jhipster/generator-jhipster/commit/f4bcd720b5ca3f99d29beff51ca78ab0668277ef#diff-74a9bef6a216cf7520da272552264e5fdec702069061d42c1fe73908d3768c7e
---

Sonar: This class overrides 'equals()' and should therefore also override 'hashCode()'

---

generators/java/support/add-java-annotation.spec.ts
generators/java/support/add-java-annotation.ts

don't add annotations to inner classes.

---

generators/client/support/filter-entities.ts

Avoid filtering out relationships where entities support filtering

---

generators/docker/templates/docker/keycloak.yml.ejs

required to run keycloak in GitHub MacOS runners.
---

increase keycloak docker retries

---

generators/server/generator.js

always add ci:server:await script

---

.blueprint/from-issue/generator.mts
generators/server/templates/gradle/profile_dev.gradle.ejs
generators/server/templates/gradle/profile_prod.gradle.ejs
generators/server/templates/pom.xml.ejs
generators/server/templates/src/main/resources/config/application-dev.yml.ejs
generators/server/templates/src/main/resources/config/application.yml.ejs
generators/server/templates/src/main/resources/config/bootstrap.yml.ejs

Default implementation from spring-boot-starter-parent will be used.
Fixes https://github.com/jhipster/generator-jhipster/issues/26333
---

don't override maven-resources-plugin

---

generators/ci-cd/__snapshots__/ci-cd.spec.ts.snap
generators/ci-cd/templates/docker-registry.yml.ejs
generators/ci-cd/templates/jenkins/jenkins.yml.ejs

https://github.com/compose-spec/compose-spec/blob/master/spec.md#version-and-name-top-level-elements
---

Docker compose version is obsolete

---

generators/java/generators/node/templates/npmw

Setting there variables seems redundant since they are overridden. They were not working anyway since `builddir` doesn't exist,

Unnecessary npmw variables

---

generators/client/templates/README.md.jhi.client.ejs

Installing node and running `npm install` duplicates the npm installation. We should use the one done by maven/gradle all the time. Also, asking to install node without telling it should be the version matching the one in pom.xml is unreliable.

The documentation should tell to use ./npmw instead of requiring to install node

---

generators/base-application/generator.ts
generators/base-core/generator.ts
generators/base/support/config.ts
generators/base/support/jhipster7-context.js
generators/bootstrap-application/generator.ts
generators/ci-cd/generator.js
generators/heroku/generator.js
generators/java/generators/bootstrap/generator.ts
generators/java/generators/build-tool/command.ts
generators/jdl/generator.ts
generators/languages/generator.js
generators/maven/command.ts
generators/maven/generator.ts
generators/maven/internal/xml-store.ts
generators/maven/support/pom-store.ts

Description in each commit.
---

Adjusts for kotlin blueprint.

---

generators/bootstrap/generator.ts
generators/bootstrap/support/eslint-worker.js
lib/eslint/base.js
lib/eslint/recommended.ts
package-lock.json
package.json
tsconfig.types.json

Related to https://github.com/jhipster/generator-jhipster/issues/26471
Fixes https://github.com/jhipster/generator-jhipster/issues/26457.
---

add eslint/recommended exports

---

generators/docker-compose/__snapshots__/docker-compose.spec.ts.snap
generators/docker-compose/templates/docker-compose.yml.ejs
generators/docker-compose/templates/realm-config/keycloak-health-check.sh
generators/docker/templates/docker/keycloak.yml.ejs
generators/docker/templates/docker/realm-config/keycloak-health-check.sh
generators/server/resources/Dockerfile

Upgrade Keycloak 25.0.0

---

generators/base-application/types.d.ts
generators/base-core/generator.ts
generators/base/api.d.ts
generators/base/command.ts
generators/bootstrap/support/multi-step-transform/template-file.js

Description in each commit.
---

more adjusts for blueprints

---

.gitignore
generators/gatling/generator.ts

The Gatling Maven Plugin deprecated the use of the `resourcesFolder` configuration option. See commit,
https://github.com/gatling/gatling-maven-plugin/commit/99faad8d54a0ad59bcd0a839a642da4c67a5b5ad
Add exclusion for NetBeans (we're still out there...)
---
Fixes #26492

fix(generator,gatling): remove deprecated plugin configuration option

---

generators/react/templates/src/main/webapp/app/modules/home/home.tsx.ejs
generators/react/templates/src/main/webapp/app/modules/login/login-redirect.tsx.ejs
generators/react/templates/src/main/webapp/app/modules/login/logout.tsx.ejs
generators/react/templates/src/main/webapp/app/routes.tsx.ejs
generators/react/templates/src/main/webapp/app/shared/auth/private-route.spec.tsx.ejs
generators/react/templates/src/main/webapp/app/shared/auth/private-route.tsx.ejs
generators/react/templates/src/main/webapp/app/shared/layout/menus/account.spec.tsx.ejs
generators/react/templates/src/main/webapp/app/shared/layout/menus/account.tsx.ejs
generators/react/templates/src/main/webapp/app/shared/util/url-utils.ts.ejs

When creating an application with OAuth2 and React, the following issues were discovered:
> JHipster version is v8.5.0
1. When a user who is not logged in visits the logout page, infinite logout requests are sent to the backend.
https://github.com/jhipster/generator-jhipster/assets/97726491/d82099cf-e6c3-4294-b7d0-3a243d369575
2. If there is a non-private route, such as the About page (`/about`), and the user clicks login on that page and logs in, the Redirect functionality breaks because the local storage records an incorrect redirect URL.
https://github.com/jhipster/generator-jhipster/assets/97726491/83dc568f-441d-42b9-9033-cb751c4b7764
```
application {
config {
baseName blog,
applicationType monolith
authenticationType oauth2
packageName com.jhipster.demo.blog
prodDatabaseType …
```

Fix OAuth2 login and logout issues in React application

---

README.md

add java 22 to README

---

generators/base-core/generator.ts

generator-jhipster@7.9.3/7.9.4 has a bug in serverFiles that 2 ejs templates are treated as non ejs templates.
Add workaround to this issue.
Related to https://github.com/jhipster/jhipster-kotlin/issues/378.
---

workaround v7 files structure bug

---

generators/angular/templates/src/main/webapp/app/admin/health/health.component.spec.ts.ejs

[Angular] throwError function is deprecated

---

generators/angular/templates/src/main/webapp/app/admin/metrics/blocks/jvm-threads/jvm-threads.component.ts.ejs
generators/angular/templates/src/main/webapp/app/app-page-title-strategy.ts.ejs
generators/angular/templates/src/main/webapp/app/config/uib-pagination.config.ts.ejs
generators/angular/templates/src/main/webapp/app/core/interceptor/auth-expired.interceptor.ts.ejs
generators/angular/templates/src/main/webapp/app/core/interceptor/auth.interceptor.ts.ejs
generators/angular/templates/src/main/webapp/app/core/interceptor/error-handler.interceptor.ts.ejs
generators/angular/templates/src/main/webapp/app/layouts/error/error.component.ts.ejs
generators/angular/templates/src/main/webapp/app/layouts/navbar/active-menu.directive.ts.ejs
generators/angular/templates/src/main/webapp/app/shared/language/find-language-from-key.pipe.ts.ejs
generators/angular/templates/src/main/webapp/app/shared/language/translation.module.ts.ejs

[Angular] Sonar: Fields that are only assigned in the constructor should be readonly

---

generators/angular/templates/src/main/webapp/app/shared/sort/sort.directive.spec.ts.ejs

[Angular] Fix deprecated signature for tableRow.injector.get

---

generators/maven/generator.ts
generators/maven/internal/xml-store.ts
generators/maven/support/pom-store.ts
generators/maven/types.d.ts

add maven mergeMavenPomContent and sort build configuration

---

generators/feign-client/templates/src/main/java/_package_/client/AuthorizationHeaderUtil.java.ejs
generators/liquibase/templates/src/main/java/_package_/config/LiquibaseConfiguration.java.ejs
generators/server/templates/src/main/java/_package_/config/AsyncConfiguration.java.ejs
generators/server/templates/src/main/java/_package_/config/SecurityJwtConfiguration.java.ejs
generators/server/templates/src/main/java/_package_/config/WebConfigurer.java.ejs
generators/server/templates/src/main/java/_package_/security/DomainUserDetailsService.java.ejs
generators/server/templates/src/main/java/_package_/security/PersistentTokenRememberMeServices.java.ejs
generators/server/templates/src/main/java/_package_/security/oauth2/AudienceValidator.java.ejs
generators/server/templates/src/main/java/_package_/service/MailService.java.ejs
generators/server/templates/src/main/java/_package_/web/rest/AccountResource.java.ejs
generators/server/templates/src/main/java/_package_/web/rest/AccountResource_oauth2.java.ejs
generators/server/templates/src/main/java/_package_/web/rest/AccountResource_skipUserManagement.java.ejs
generators/server/templates/src/main/java/_package_/web/rest/AuthenticateController.java.ejs
generators/spring-boot/templates/src/main/java/_package_/_entityPackage_/service/UserService.java.ejs
generators/spring-boot/templates/src/main/java/_package_/_entityPackage_/service/_entityClass_QueryService.java.ejs
generators/spring-boot/templates/src/main/java/_package_/_entityPackage_/service/impl/_entityClass_ServiceImpl.java.ejs
generators/spring-boot/templates/src/main/java/_package_/_entityPackage_/web/rest/PublicUserResource.java.ejs
generators/spring-boot/templates/src/main/java/_package_/_entityPackage_/web/rest/UserResource.java.ejs
generators/spring-boot/templates/src/main/java/_package_/_entityPackage_/web/rest/_entityClass_Resource.java.ejs
generators/spring-cache/templates/src/main/java/_package_/config/CacheConfiguration.java.ejs
generators/spring-cloud-stream/generators/kafka/templates/src/main/java/_package_/broker/KafkaConsumer_imperative.java.ejs
generators/spring-cloud-stream/generators/kafka/templates/src/main/java/_package_/broker/KafkaConsumer_reactive.java.ejs
generators/spring-cloud-stream/generators/kafka/templates/src/main/java/_package_/web/rest/KafkaResource_imperative.java.ejs
generators/spring-cloud-stream/generators/kafka/templates/src/main/java/_package_/web/rest/KafkaResource_reactive.java.ejs
generators/spring-data-couchbase/templates/src/main/java/_package_/config/DatabaseConfiguration.java.ejs
generators/spring-data-relational/templates/src/main/java/_package_/config/DatabaseConfiguration.java.ejs

Same as #26531 without renaming
---

Loggers should be 'private static final'

---

.blueprint/from-issue/generator.mts
.github/workflows/linked-issue-check.yml
generators/spring-data-neo4j/generator.ts
test-integration/jdl-samples/ms-mf-ng-consul-oauth2-neo4j/blog-store.jdl

Fixes https://github.com/jhipster/generator-jhipster/issues/26378
---

fix cyclic entities in neo4j sample

---

generators/server/templates/src/test/java/_package_/web/rest/errors/ExceptionTranslatorTestController.java.ejs

Fix:
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=jhipster-sample-application&open=AZBahczf7zsW3EZMzlzM
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=jhipster-sample-application&open=AZBahczf7zsW3EZMzlzN
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=jhipster-sample-application&open=AZBahczf7zsW3EZMzlzO
---

Sonar: Add a nested comment

---

generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/web/rest/_entityClass_ResourceIT.java.ejs

Fix:
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=jhipster-sample-application&open=AZBahc4z7zsW3EZMzl0S
---

Sonar: Remove this unused 'longCount' private field.

---

generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/web/rest/PublicUserResourceIT.java.ejs

Fix:
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=jhipster-sample-application&open=AZBahc227zsW3EZMzlz1
---

Sonar: Remove this unused 'DEFAULT_LOGIN' private field.

---

generators/angular/templates/webpack/webpack.custom.js.ejs
generators/server/templates/src/main/resources/config/application-dev.yml.ejs

We add special fields on the proxy. They are picked up by the ForwardedHeaderFilter on the server side to modify the incoming request. This is used for the baseUrl when oauth2 is called. The impact is that oauth2 will redirect to 9000 after authentication instead of 8080. Which is what we want.

Forward proxy URI from proxy to server to let it pass to oauth2 authentication

---

generators/angular/templates/src/main/webapp/app/admin/user-management/user-management.route.ts.ejs

Sonar: Rename UserManagementResolve function to match the regular expression

---

generators/angular/templates/src/main/webapp/app/core/auth/account.service.spec.ts.ejs

[Angular] Refactor this code to not nest functions more than 4 levels deep

---

.github/dependabot.yml
generators/vue/resources/package.json
generators/vue/templates/eslint.config.js.jhi.vue.ejs
generators/vue/templates/package.json.ejs

Drop @vue/eslint-config-typescript, it's just a wrapper around eslint-plugin-vue and typescript-eslint that looks not required anymore.
Related to https://github.com/jhipster/generator-jhipster/issues/26471
---

update vue eslint to v9

---

generators/liquibase/__snapshots__/incremental-liquibase.spec.ts.snap
generators/liquibase/incremental-liquibase.spec.ts
generators/liquibase/templates/src/main/resources/config/liquibase/changelog/updated_entity_constraints.xml.ejs

when updating constraints
Fix #26910
---

Correct issue with invalid contraint being generated for ManyToMany relationships

---

generators/base/support/jhipster7-context.js
generators/maven/internal/pom-sort.ts

Dependency management pom import order is first served and will define transitional dependencies version.
Reordering changes the end result, so move to the top and keep insert ordering.
---

Don't sort maven dependency imports

---

generators/angular/templates/src/main/webapp/app/account/password-reset/init/password-reset-init.component.html.ejs
generators/angular/templates/src/main/webapp/app/account/register/register.component.html.ejs
generators/angular/templates/src/main/webapp/app/admin/user-management/list/user-management.component.spec.ts.ejs
generators/angular/templates/src/main/webapp/app/config/translation.config.ts.ejs
generators/angular/templates/src/main/webapp/app/core/auth/user-route-access.service.ts.ejs
generators/angular/templates/src/main/webapp/app/core/util/alert.service.spec.ts.ejs
generators/angular/templates/src/main/webapp/app/core/util/data-util.service.ts.ejs
generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_.routes.ts.ejs
generators/angular/templates/src/main/webapp/app/layouts/main/main.component.spec.ts.ejs
generators/angular/templates/src/main/webapp/app/login/login.component.html.ejs
generators/angular/templates/src/main/webapp/app/shared/alert/alert-error.component.ts.ejs
generators/angular/templates/src/main/webapp/app/shared/filter/filter.model.ts.ejs
generators/angular/templates/src/main/webapp/app/shared/language/translation.module.ts.ejs
generators/angular/templates/webpack/webpack.custom.js.ejs
generators/client/templates/src/main/webapp/index.html.ejs
generators/client/templates/src/main/webapp/swagger-ui/index.html.ejs

apply eslint/prettier to angular templates

---

generators/base-core/generator.ts
generators/bootstrap/support/eslint-transform.ts
generators/bootstrap/support/eslint-worker.js
generators/bootstrap/support/java-unused-imports-transform.ts
generators/bootstrap/support/prettier-support.ts

add ESLintPool and PrettierPool classes

---

.github/actions/sonar/action.yml
.github/dependabot.yml
.github/workflows/angular.yml
generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/web/rest/_entityClass_ResourceIT.java.ejs
renovate.json
test-integration/sonar-pr/Dockerfile
test-integration/sonar-pr/docker-compose.yml

This PR introduces a custom GitHub Action to address Issue #19467 by adding SonarQube reports to PRs, enabling the detection of newly introduced issues and helping maintain high code quality in the project.
- **Implementation**: Introduces a GitHub Action that runs SonarQube analysis using Docker.
- **Caching Mechanism**: On pushes to the `main` branch, the entire generated application is cached. This cache is then restored during PR analysis.
- **PR Analysis**: The cached `main` branch project is analyzed first, followed by the analysis of the PR changes. This process allows to identify and report only the issues newly introduced in the PR.
We could simplify the approach by analyzing the generated project directly instead of focusing on the changes. This would streamline the workflow, …

Add SonarQube Analysis for PRs

---

generators/spring-boot/templates/src/main/resources/config/application.yml.ejs

add the yml property management.metrics.tags.application with value ${spring.application.name} Fix #27047
---

application field not sent to prometheus

---

eslint.config.js
lib/eslint/base.js
package-lock.json
package.json

eslint-plugin-import-x is a fork from eslint-plugin-import.
eslint-plugin-import-x didn't looked an alternative to eslint-plugin-import at the time, but since npm is waning about eslint-plugin-import lets try.
Follow-up to https://github.com/jhipster/generator-jhipster/issues/26471.
Fixes https://github.com/jhipster/generator-jhipster/issues/27091.
---

replace eslint-plugin-import with eslint-plugin-import-x

---

generators/angular/templates/src/main/webapp/app/app.component.ts.ejs
generators/react/templates/eslint.config.js.jhi.react.ejs

Remove duplicate imports

---

generators/angular/templates/src/main/webapp/app/admin/metrics/metrics.component.html.ejs
generators/angular/templates/src/main/webapp/app/admin/metrics/metrics.component.spec.ts.ejs
generators/angular/templates/src/main/webapp/app/admin/metrics/metrics.component.ts.ejs

[Angular] Use let on metrics component

---

generators/angular/templates/src/main/webapp/app/admin/user-management/list/user-management.component.html.ejs
generators/angular/templates/src/main/webapp/app/admin/user-management/list/user-management.component.ts.ejs
generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/list/_entityFile_.component.html.ejs
generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/list/_entityFile_.component.spec.ts.ejs
generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/list/_entityFile_.component.ts.ejs

Fix call to track function on entity list component template
---

Fix call to track function on entity list component template

---

generators/base-core/generator.ts
generators/base/api.d.ts
generators/base/command.ts
generators/base/types.d.ts
generators/client/command.ts
generators/client/types.d.ts
generators/index.ts
generators/java/command.ts
generators/java/generators/bootstrap/command.ts
generators/java/generators/build-tool/command.ts
generators/java/generators/openapi-generator/command.ts
generators/java/types.d.ts
generators/server/support/update-languages.ts
generators/type-utils.ts

export types from command

---

jdl/__snapshots__/jdl-importer.spec.ts.snap
jdl/__test-files__/deployments.jdl
jdl/built-in-options/index.ts
jdl/built-in-options/jdl-application-definition.spec.ts
jdl/built-in-options/jdl-application-definition.ts
jdl/converters/jdl-to-json/jdl-to-json-option-converter.ts
jdl/converters/parsed-jdl-to-jdl-object/deployment-converter.spec.ts
jdl/converters/parsed-jdl-to-jdl-object/option-converter.spec.ts
jdl/exporters/jdl-exporter.spec.ts
jdl/jdl-importer.spec.ts
jdl/jhipster/application-options.ts
jdl/jhipster/deployment-options.spec.ts
jdl/jhipster/deployment-options.ts
jdl/jhipster/index.ts
jdl/models/jdl-application-configuration-factory.ts
jdl/models/jdl-deployment.ts
jdl/parsing/jdl-ast-builder-visitor.ts
jdl/parsing/lexer/deployment-tokens.ts
jdl/parsing/validator.spec.ts
jdl/parsing/validator.ts
jdl/types/types.d.ts
jdl/validators/deployment-validator.spec.ts
jdl/validators/deployment-validator.ts

Related to https://github.com/jhipster/generator-jhipster/issues/27136
---

cleanup jdl and reduce dependency on jhipster

---

jdl/built-in-options/jdl-application-definition.ts
jdl/jhipster/application-options.ts
jdl/models/jdl-application-configuration-factory.ts
jdl/parsing/validator.ts
jdl/types/types.d.ts

Related to https://github.com/jhipster/generator-jhipster/issues/27136
---

make jdl types decoupled

---

eslint.config.js
package-lock.json
package.json

Upgrade eslint-plugin-import-x 4.2.1

---

generators/app/command.ts
generators/base-application/generator.ts
generators/base-core/generator.ts
generators/client/command.ts
generators/client/prompts.ts
generators/client/types.d.ts
generators/spring-boot/command.ts
lib/command/types.d.ts
lib/types/application/yo-rc.d.ts

Related to https://github.com/jhipster/generator-jhipster/issues/26114
---

add types to jhipsterConfig and jhipsterConfigWithDefaults

---

generators/server/generator.ts
generators/spring-boot/generator.ts

Fix #27244
Actual behavior on the main branch:
`./npmw install` is executed whereas the file `npmw` is not created (it works if we do `jhipster --force` after)
```
 quentin  ~    JHipster  appreactmicro2  jhipster
WARNING! Since JHipster v8, the jhipster command will not use the locally installed generator-jhipster.
If you want to execute the locally installed generator-jhipster, run: npx jhipster
██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
╚═════╝  ╚═╝ …
```

npmw created after ./npmw started

---

generators/base-application/generator.ts
generators/base-application/support/prepare-field.ts
generators/base-application/support/prepare-property.ts
generators/bootstrap-application-base/generator.ts
generators/client/support/template-utils.spec.ts
generators/client/support/template-utils.ts
generators/client/support/types-utils.ts
generators/info/generator.ts
generators/server/generator.ts
generators/server/support/build-specification-mapper.ts
generators/spring-boot/generator.ts
lib/application/field-types.ts
lib/command/__snapshots__/jdl.spec.ts.snap
lib/jdl/__snapshots__/jdl-importer.spec.ts.snap
lib/jdl/converters/jdl-to-json/jdl-to-json-field-converter.spec.ts
lib/jdl/converters/jdl-to-json/jdl-to-json-field-converter.ts
lib/jdl/converters/jdl-to-json/jdl-with-applications-to-json-converter.spec.ts
lib/jdl/converters/jdl-to-json/jdl-without-application-to-json-converter.spec.ts
lib/jdl/converters/json-to-jdl-entity-converter.spec.ts
lib/jdl/converters/json-to-jdl-entity-converter.ts
lib/jhipster/field-types.spec.ts
lib/jhipster/field-types.ts
lib/types/application/entity.d.ts
lib/types/application/field.d.ts
lib/types/base/field.d.ts

JDL currently converts *Blob types to `byte[]` and contentType.
Move conversion to generators.
Improve field types.
I think we can close https://github.com/jhipster/generator-jhipster/issues/27136 and https://github.com/jhipster/generator-jhipster/issues/26114.
Close https://github.com/jhipster/generator-jhipster/issues/26114
Close https://github.com/jhipster/generator-jhipster/issues/27136
---

don't convert blob types in jdl

---

generators/maven/internal/pom-sort.ts
generators/maven/support/pom-file-sort.spec.ts

don't reorder plugins inside pom profile

---

generators/generator-constants.js
test-integration/integration-test-constants.js

Use jhipster-framework release so a generated application using main will work out-of-the-box.
CI still uses jhipster-bom main.
Related to https://github.com/jhipster/generator-jhipster/issues/26628.
---

use jhipster-framework release

---

generators/generate-blueprint/__snapshots__/generator.spec.ts.snap
generators/generate-blueprint/files.ts
generators/generate-blueprint/generator.ts
generators/generate-blueprint/templates/vitest.config.ts.ejs
generators/generate-blueprint/templates/vitest.test-setup.ts.ejs

Related to https://github.com/jhipster/generator-jhipster/issues/27357.
---

generate-blueprint: drop vitest.test-setup.ts

---

generators/java/generators/node/generator.ts
generators/server/generator.ts

move npmw install task to java:node

---

generators/spring-boot/templates/src/main/resources/config/application-dev.yml.ejs

disable docker compose integration if there is no container to start

---

.blueprint/generate-generator/templates/command.ts.ejs
eslint.config.js
generators/angular/generator.ts
generators/base-core/generator.ts
generators/bootstrap/support/eslint-transform.ts
generators/bootstrap/support/java-unused-imports-transform.ts
generators/bootstrap/support/prettier-support.ts
generators/common/generator.ts
generators/docker-compose/generator.ts
generators/generate-blueprint/command.ts
generators/generate-blueprint/generator.ts
generators/java/generators/openapi-generator/generator.ts
generators/javascript/generators/bootstrap/command.ts
generators/javascript/types.d.ts
generators/react/generator.ts
generators/spring-boot/cleanup.ts
generators/spring-cloud/generators/gateway/generator.ts
generators/vue/generator.ts
lib/types/application/options.d.ts
lib/types/application/yo-rc.d.ts

Related to https://github.com/jhipster/generator-jhipster/issues/27357
---

generate-blueprint: adjusts

---

generators/base-core/generator.ts
generators/base/api.d.ts
generators/generate-blueprint/command.ts
generators/generate-blueprint/files.ts
generators/generate-blueprint/generator.ts

Related to https://github.com/jhipster/generator-jhipster/issues/27357
---

generate-blueprint: add skipWorkflows and ignoreExistingGenerators options

---

generators/generate-blueprint/templates/generators/generator/command.mjs.ejs
generators/generate-blueprint/templates/generators/generator/generator.mjs.jhi.ejs
generators/generate-blueprint/templates/generators/generator/index.mjs.ejs

Related to https://github.com/jhipster/generator-jhipster/issues/27357
---

generate-blueprint: enable queueCommandTasks

---

cli/jhipster-command.mjs
generators/base-core/generator.ts
generators/ci-cd/generator.spec.ts
lib/command/converter.ts

Fixes https://github.com/jhipster/generator-jhipster/issues/27405
---

base-core: fix varargs cli argument handling

---

.github/workflows/angular.yml
.github/workflows/react.yml
.github/workflows/vue.yml
generators/base-workspaces/internal/docker-base.ts
generators/base/generator.ts
generators/docker-compose/command.ts
generators/docker-compose/generator.ts
generators/java/command.ts
generators/kubernetes-helm/index.ts
generators/kubernetes-knative/index.ts
generators/kubernetes/command.ts
test-integration/scripts/99-write-matrix.js

make deployments reproducible

---

cli/cli.spec.mts
cli/commands.mts
cli/environment-builder.mjs
cli/jhipster-command.mjs
cli/program.mts
cli/program.spec.mts
cli/types.d.ts
cli/utils.mjs
generators/ci-cd/generator.spec.ts
lib/testing/helpers.ts
lib/utils/logger.ts

- convert parts of cli to typescript to ensure correct api usage.
- cli api adjusts
Fixes https://github.com/jhipster/generator-jhipster/issues/27409
---

testing: add runCli helper

---

cli/program.mts
lib/command/generator-command.spec.ts
lib/command/types.d.ts
lib/testing/helpers.spec.ts
lib/testing/helpers.ts

testing: improve types, fix options, and improve api

---

generators/angular/templates/src/main/webapp/app/admin/user-management/service/user-management.service.ts.ejs
generators/angular/templates/src/main/webapp/app/app.component.ts.ejs
generators/angular/templates/src/main/webapp/app/core/auth/account.service.ts.ejs
generators/angular/templates/src/main/webapp/app/core/auth/state-storage.service.ts.ejs
generators/angular/templates/src/main/webapp/app/layouts/main/main.component.ts.ejs
generators/angular/templates/src/main/webapp/app/layouts/profiles/profile.service.ts.ejs
generators/angular/templates/src/main/webapp/app/shared/auth/has-any-authority.directive.ts.ejs
generators/angular/templates/src/main/webapp/app/shared/sort/sort.service.ts.ejs

Sonar: Member is never reassigned; mark it as readonly

---

generators/bootstrap-application-base/generator.ts
lib/command/lookup-commands-configs.ts

Fixes https://github.com/jhipster/generator-jhipster/issues/27353.
Related to https://github.com/jhipster/generator-jhipster/issues/27433.
---

internal: always load main generators configs

---

generators/app/__snapshots__/generator.spec.ts.snap
generators/base-core/generator.ts
generators/init/__snapshots__/generator.spec.ts.snap
generators/jdl/__snapshots__/generator.spec.ts.snap
lib/command/converter.ts
lib/command/generator-command.spec.ts

internal: adjust command parsing with default option value

---

cli/cli.spec.mts
generators/java/support/checks/check-java.spec.ts
package-lock.json
package.json

drop quibble dependency

---

generators/client/templates/webpack/webpack.microfrontend.js.jhi.ejs
generators/react/generator.ts
generators/react/resources/package.json
generators/react/templates/package.json.ejs
generators/vue/generator.ts
generators/vue/resources/package.json
generators/vue/templates/module-federation.config.cjs.ejs

switch to react and vue to @module-federation/enhanced

---

generators/liquibase/__snapshots__/incremental-liquibase.spec.ts.snap
generators/liquibase/incremental-liquibase.spec.ts
generators/liquibase/templates/src/main/resources/config/liquibase/changelog/add_relationship_constraints.ejs
generators/liquibase/templates/src/main/resources/config/liquibase/changelog/added_entity_constraints.xml.ejs
generators/liquibase/templates/src/main/resources/config/liquibase/changelog/updated_entity_constraints.xml.ejs

Fixes #27598 and adds additional conditions to the existing tests (which were missing)
---

Liquibase foreign key relationship column names  

---

generators/app/__snapshots__/generator.spec.ts.snap
generators/java/generators/build-tool/generator.ts
generators/maven/__snapshots__/needles.spec.ts.snap
generators/maven/needles.spec.ts
generators/maven/types.d.ts
generators/spring-boot/templates/gradle/profile_dev.gradle.ejs
generators/spring-boot/templates/gradle/profile_prod.gradle.ejs
generators/spring-data-relational/generator.ts
generators/spring-data-relational/internal/dependencies.ts

spring-boot: adjust gradle dev dependencies

---

generators/spring-boot/templates/src/main/java/_package_/Application.java.ejs
generators/spring-boot/templates/src/main/java/_package_/config/WebConfigurer.java.ejs
generators/spring-boot/templates/src/main/resources/config/application-dev.yml.ejs
generators/spring-data-relational/templates/src/main/java/_package_/config/DatabaseConfiguration.java.ejs

spring-boot: allow h2 console to be enabled/disabled using spring.h2.console.enabled property

---

generators/cypress/__snapshots__/generator.spec.ts.snap
generators/cypress/files.ts
generators/cypress/templates/src/test/javascript/cypress/e2e/account/login-page.cy.ts.ejs
generators/cypress/templates/src/test/javascript/cypress/e2e/account/logout.cy.ts.ejs

There isn't a logout test. React logout is not stable in oauth2 and dev.
Related to https://github.com/jhipster/generator-jhipster/issues/25875
---

cypress: add logout test

---

generators/gradle/internal/needles.ts
generators/gradle/types.d.ts
generators/java/generators/build-tool/generator.ts
generators/java/types.d.ts
generators/spring-data-relational/generator.ts

Related to https://github.com/jhipster/generator-jhipster/issues/25875
---

exclude commons-logging

---

.blueprint/github-build-matrix/__snapshots__/generator.spec.ts.snap
.blueprint/github-build-matrix/generator.ts
.blueprint/github-build-matrix/samples/graalvm.ts
.blueprint/github-build-matrix/support/git-changes.ts
generators/base/shared-data.ts
generators/java/generators/graalvm/__snapshots__/generator.spec.ts.snap
generators/java/generators/graalvm/generator.ts
generators/java/generators/graalvm/internal/maven-definition.ts
generators/java/generators/graalvm/templates/gradle/native.gradle.ejs
generators/liquibase/generator.ts

java/graalvm: polish

---

generators/server/types.d.ts
lib/command/support/merge-union.d.ts
lib/command/types.d.ts
lib/command/types.spec.ts
lib/types/application/application.d.ts

internal: adjust application type to don't allow unknown fields

---

generators/spring-boot/templates/src/main/java/_package_/config/SecurityConfiguration_imperative.java.ejs
generators/spring-boot/templates/src/main/java/_package_/config/SecurityConfiguration_reactive.java.ejs

Add workaround for Spring Cloud Gateway https://github.com/spring-cloud/spring-cloud-gateway/issues/3568.
---

Add workaround for Spring Cloud Gateway from Spring Boot 3.3.5

---

generators/spring-boot/templates/README.md.jhi.spring-boot.ejs

adjust docker support in README

---

generators/spring-boot/generator.ts
generators/spring-cache/generator.ts
lib/jhipster/default-application-options.spec.ts
lib/jhipster/default-application-options.ts

Related to https://github.com/jhipster/generator-jhipster/issues/27672
---

spring-cache: improve cache config validation

---

generators/docker-compose/__snapshots__/docker-compose.spec.ts.snap
generators/docker/templates/docker/mysql.yml.ejs

MySql is not ready to receive connections yet.
Related to https://github.com/jhipster/generator-jhipster/issues/27433
---

docker: add sleep in mysql healthcheck

---

generators/generate-blueprint/__snapshots__/generator.spec.ts.snap
generators/generate-blueprint/files.ts
generators/generate-blueprint/templates/generators/generator/generator.spec.mjs.ejs
generators/generate-blueprint/templates/vitest.config.ts.ejs
generators/generate-blueprint/templates/vitest.test-setup.ts.ejs
lib/testing/helpers.ts
test/__snapshots__/api.spec.js.snap

Related to https://github.com/jhipster/generator-jhipster/issues/27433
---

testing: add blueprint support to helpers

---

generators/base/shared-data.ts
generators/base/types.d.ts

Related to https://github.com/jhipster/generator-jhipster/issues/27433
---

add currentVersion to cleanupFiles.

---

generators/bootstrap-application-base/generator.ts
generators/java/generators/bootstrap/generator.ts
generators/java/generators/server/__snapshots__/generator.spec.ts.snap
generators/java/generators/server/command.ts
generators/java/generators/server/generator.spec.ts
generators/java/generators/server/generator.ts
generators/java/generators/server/index.ts
generators/server/generator.ts
generators/spring-boot/generator.ts

Move java logic out of server generator.
Some to spring-boot generator and others to new java:server generator.
Related to https://github.com/jhipster/generator-jhipster/issues/27764 and https://github.com/jhipster/generator-jhipster-nodejs/issues/538
---

java: add java:server generator

---

README.md

The version from [npm.chart.dev](https://npm.chart.dev/generator-jhipster?primary=sky&gray=cool&theme=dark) is much prettier.

Update npm downloads chart

---

generators/angular/generator.ts
generators/base-application/generator.ts
generators/base-application/types.d.ts
generators/base-entity-changes/generator.ts
generators/bootstrap-application-base/generator.ts
generators/bootstrap-application/generator.ts
generators/client/types.d.ts
generators/java/types.d.ts
generators/server/generator.ts
generators/server/types.d.ts
lib/types/application/application.d.ts
lib/types/application/tasks.d.ts

add type to applicationDefaults

---

generators/ci-cd/__snapshots__/ci-cd.spec.ts.snap
generators/ci-cd/templates/.gitlab-ci.yml.ejs

This pull request includes the following changes:
1. Remove the unnecessary `REGISTRY_URL` variable, as the predefined `CI_REGISTRY` can be used instead.
2. Update the Docker push configuration to use the predefined `CI_REGISTRY_USER` and `CI_REGISTRY_PASSWORD` variables instead of `"gitlab-ci-token"` and `CI_BUILD_TOKEN`.
3. Update comments to reflect changes and improve clarity.

Update GitLab CI Docker push job

---

generators/spring-boot/templates/src/main/java/_package_/config/SecurityConfiguration_imperative.java.ejs

From Spring Security 6 onwards, the CSRF Token is stored in `HttpSession` by default, and CSRF Token is lazy-loaded to improve performance.
However, for SPA applications, we store the CSRF Token in a cookie. Since SPA applications must include the CSRF Token in the request header when calling protected APIs, lazy-loading the CSRF Token on the server side causes the client to fail to retrieve the CSRF Token from the cookie on the first call to a protected API, resulting in a `403 Forbidden` error (due to CSRF Token validation failure).
JHipster uses `CookieCsrfFilter` to ensure the CSRF Token is written to the cookie, but I believe the current implementation has the following issue:
- The implementation and name of the `CookieCsrfFilter` are confusing because the filter extracts the CSRF …

Improve CSRF Token Handling for SPA

---

generators/spring-boot/templates/src/main/java/_package_/_entityPackage_/service/UserService.java.ejs

With this fix all tests from daily builds should be green :)
https://github.com/jhipster/generator-jhipster/issues/27490

Evict user login cache for couchbase

---

test-integration/sonar-pr/Dockerfile

Reverts jhipster/generator-jhipster#28065
Local sonar seems to be broken.

Revert "build(deps): bump sonarqube from 10.7.0-community to 24.12.0.100206-community in /test-integration/sonar-pr"

---

.blueprint/github-build-matrix/support/git-changes.ts
generators/spring-boot/templates/src/main/java/_package_/_entityPackage_/repository/UserRepository.java.ejs
generators/spring-boot/templates/src/main/java/_package_/_entityPackage_/service/UserService.java.ejs
generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/web/rest/UserResourceIT.java.ejs
test-integration/samples/ng-couchbase/.yo-rc.json

couchbase: enable cache in sample

---

generators/generate-blueprint/files.ts
generators/generate-blueprint/templates/.gitignore.jhi.blueprint.ejs

generate-blueprint: ignore package-lock files inside generators folder

---

.github/dependabot.yml

It has a flexible dependency version.
---

angular: drop jest-preset-angular from dependabot group

---

.blueprint/github-build-matrix/__snapshots__/generator.spec.ts.snap
.blueprint/github-build-matrix/samples/dev-server.ts

MacOS doesn’t have docker support.
Make sure `./mvnw` works without docker.
---

ci: switch test to macos

---

generators/angular/templates/src/main/webapp/app/shared/sort/sort-by.directive.spec.ts.ejs
generators/angular/templates/src/main/webapp/app/shared/sort/sort-by.directive.ts.ejs

[Angular] Migrate to signals (sort-by.directive.ts)

---

generators/spring-boot/prompts.ts

Fixes https://github.com/jhipster/generator-jhipster/issues/28193
---

internal: omit value from prompts if value is not defined

---

generators/spring-boot/templates/src/main/java/_package_/service/MailService.java.ejs

Remove redundant `this` keyword
---

Minor cleanup in MailService.java

---

generators/angular/templates/eslint.config.js.jhi.angular.ejs

Fixed with https://github.com/angular-eslint/angular-eslint/pull/1924
---

[Angular] eslint: remove workaround

---

generators/generate-blueprint/command.ts

Related to https://github.com/jhipster/generator-jhipster/issues/28291
---

generate-blueprint: don't generate gitDependency by default

---

generators/languages/command.ts

Fix workaround
https://github.com/jhipster/generator-jhipster-native/blob/43ddcec225dd18ae13f6797c27da9b2cf59f5f86/generators/spring-boot/generator.js#L33
Related to https://github.com/jhipster/generator-jhipster/issues/28291
---

languages: add languagesDefinition to command

---

generators/angular/templates/webpack/webpack.custom.js.ejs
generators/docker/templates/docker/jhipster-control-center.yml.ejs
generators/languages/templates/src/main/webapp/i18n/fr/reset.json.ejs
generators/react/templates/webpack/webpack.dev.js.ejs

Clean code

---

generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_.model.ts.ejs
generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/detail/_entityFile_-detail.component.html.ejs
generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/update/_entityFile_-update.component.html.ejs
generators/cypress/templates/src/test/javascript/cypress/e2e/entity/_entity_.cy.ts.ejs
generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/service/criteria/_entityClass_CriteriaTest.java.ejs
generators/spring-data-relational/templates/src/main/java/_package_/_entityPackage_/repository/_entityClass_RepositoryInternalImpl_reactive.java.ejs
generators/spring-data-relational/templates/src/main/java/_package_/_entityPackage_/repository/_entityClass_Repository_reactive.java.ejs
generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_-update.component.ts.ejs

Clean code: Remove unused constant

---

generators/base-application/support/task-type-inference.ts
generators/base/support/secret.ts
generators/bootstrap-application-base/utils.ts

Clean code: remove unused function

---

lib/testing/github-group.ts

Allows to add support files to templates folder
---

ignore files/directories starting with _ when looking for samples groups

---

generators/react/__snapshots__/generator.spec.ts.snap
generators/react/generator.ts
generators/react/resources/package.json
generators/workspaces/generator.ts

Fix #28571 
https://www.npmjs.com/package/browser-sync-webpack-plugin no longer appears to be maintained
---

[React] Fix bump browser-sync from 2.29.3 to 3.0.3

---

generators/spring-boot/templates/src/main/java/_package_/web/rest/LogoutResource_imperative.java.ejs
generators/spring-boot/templates/src/main/java/_package_/web/rest/LogoutResource_reactive.java.ejs

This update enhances the `LogoutResource` to dynamically resolve the OAuth2 client registration based on the currently authenticated user's `OAuth2AuthenticationToken`.
---

Enhance LogoutResource to dynamically resolve OAuth2 client registration

---

generators/maven/templates/mvnw.cmd

fix could not perform Maven update when the Windows user name contains space. 
This is based on a fix for maven-wrapper, see https://github.com/apache/maven-wrapper/pull/152
Fix #28585
---

Fix Maven Wrapper when the Windows user name contains spaces

---

generators/java/generators/graalvm/internal/constants.ts
renovate.json

Try to fix graalvm metadata renovate auto update
Related to https://github.com/jhipster/generator-jhipster/issues/27958
---

graalvm: renovate adjusts

---

generators/spring-boot/templates/src/main/java/_package_/web/rest/AccountResource.java.ejs
generators/spring-boot/templates/src/main/java/_package_/web/rest/AccountResource_oauth2.java.ejs
generators/spring-boot/templates/src/main/java/_package_/web/rest/AccountResource_skipUserManagement.java.ejs
generators/spring-boot/templates/src/main/java/_package_/web/rest/AuthenticateController.java.ejs
generators/spring-boot/templates/src/test/java/_package_/security/jwt/TestAuthenticationResource.java.ejs
generators/spring-boot/templates/src/test/java/_package_/security/jwt/TokenAuthenticationIT.java.ejs
generators/spring-boot/templates/src/test/java/_package_/security/jwt/TokenAuthenticationSecurityMetersIT.java.ejs
generators/spring-boot/templates/src/test/java/_package_/web/filter/SpaWebFilterIT_imperative.java.ejs
generators/spring-boot/templates/src/test/java/_package_/web/filter/SpaWebFilterIT_reactive.java.ejs
generators/spring-boot/templates/src/test/java/_package_/web/rest/AccountResourceIT.java.ejs
generators/spring-boot/templates/src/test/java/_package_/web/rest/AccountResourceIT_oauth2.java.ejs
generators/spring-boot/templates/src/test/java/_package_/web/rest/AccountResourceIT_skipUserManagement.java.ejs

spring-boot: fix sonar security issue

---

generators/react/templates/src/main/webapp/app/entities/menu.tsx.ejs
generators/react/templates/src/main/webapp/app/entities/routes.tsx.ejs

Unused imports eslint plugin is not added to generated application resulting in unknown rule error.
Related to https://github.com/jhipster/generator-jhipster/pull/29048.
Should fix failures in daily builds.
---

react: remove eslint rule name

---

.github/workflows/angular.yml
.github/workflows/devserver.yml
.github/workflows/docker-compose-integration.yml
.github/workflows/docker-image-publish-github-registry.yml
.github/workflows/generator-database-changelog-liquibase.yml
.github/workflows/generator-generate-blueprint.yml
.github/workflows/generator.yml
.github/workflows/issue-check.yml
.github/workflows/react.yml
.github/workflows/vue.yml
eslint.config.js
package-lock.json
package.json

Related https://github.com/un-ts/eslint-plugin-import-x/issues/266
cc @mshima
---

chore: update eslint-plugin-import-x

---

README.md
generators/generator-constants.js

Gradle still doesn't support java 24
---

java: revert supported java version to 23

---

generators/app/__snapshots__/generator.spec.ts.snap
generators/base-core/generator.ts
generators/base/api.d.ts
generators/base/support/contents.ts
generators/base/support/needles.ts
generators/base/support/os.ts
generators/base/support/write-files.ts
generators/bootstrap-application-base/generator.ts
generators/bootstrap/command.ts
generators/bootstrap/generator.ts
generators/bootstrap/support/auto-crlf-transform.ts
generators/init/__snapshots__/generator.spec.ts.snap
generators/java/generators/node/generator.ts
generators/jdl/__snapshots__/generator.spec.ts.snap
generators/spring-boot/generator.ts

- Windows now defaults to enable autoCrlf
- make editFile aware of crlf by converting to lf when required
- remove crlf handling from joinCallbacks and insertContentBeforeNeedle since handling is done by editFile now..
---

internal: adjusts to crlf support

---

cli/cli.mjs

We have the warning in place for long enough.
---

cli: remove jhipster 8 warning

---

generators/server/resources/Dockerfile

Version 5.0.4 seems to break our ci.
---

switch cassandra docker image to 5.0.2

---

generators/cypress/templates/src/test/javascript/cypress/e2e/account/logout.cy.ts.ejs

cypress: adjusts to logout test

---

package-lock.json
package.json

Fix: bump prettier-plugin-packagejson from 2.5.10 to 2.5.11

---

generators/spring-data-elasticsearch/templates/src/main/java/_package_/_entityPackage_/domain/_persistClass_.java.jhi.elastic_search.ejs

Enhance Elasticsearch String field mapping

---

generators/spring-boot/templates/README.md.jhi.spring-boot.ejs

Upcoming changes to Okta's free plan offerings will cause the old instructions to not work. This PR removes the part of the instructions which is impacted while not touching the alternative instructions that will continue to work as before. 
More information on free plan changes at https://developer.okta.com/blog/2025/05/13/okta-developer-edition-changes
---

update Okta instructions in generated READMEs

---

.blueprint/generate-sample/generator.mts
generators/angular/generator.ts
generators/angular/types.d.ts
generators/base-application/generator.ts
generators/base-application/support/task-type-inference.ts
generators/base-core/generator.ts
generators/base-core/types.d.ts
generators/base-entity-changes/generator.ts
generators/base-workspaces/generator.ts
generators/base-workspaces/internal/deployments.ts
generators/base/generator.ts
generators/bootstrap/generator.ts
generators/client/generator.ts
generators/git/generator.ts
generators/info/generator.ts
generators/jdl/generator.ts
generators/project-name/generator.ts
generators/spring-boot/prompts.ts
generators/workspaces/generator.ts
lib/command/generator-command.spec.ts
lib/jhipster/service-discovery-types.ts
lib/types/application/yo-rc.d.ts

- ~remove custom angularEntities from angular.~
- ~convert usage to needles~
- add generic support to base-core
- jhipsterConfig
- jhipsterConfigWithDefaults
---

internal: add types to base-core

---

generators/base-workspaces/generator.ts
generators/base/generator.ts
generators/bootstrap-workspaces/generator.ts
generators/docker-compose/generator.ts
generators/kubernetes-helm/files.ts
generators/kubernetes-helm/generator.ts
generators/kubernetes-knative/files.ts
generators/kubernetes-knative/generator.ts
generators/kubernetes/files.ts
generators/kubernetes/generator.ts
generators/kubernetes/kubernetes-base.ts

Contributes a bit to https://github.com/jhipster/generator-jhipster/issues/28235 by using tasks groups on workspace generators.
Next steps: use of template framework and workspace types to avoid generator being stateful
FYI, didn't modify any line of logic or object: just moved code into different functions (using the new APIs)
---

Use of tasks groups for workspace generators

---

generators/cypress/templates/src/test/javascript/cypress/e2e/account/login-page.cy.ts.ejs
generators/cypress/templates/src/test/javascript/cypress/e2e/account/reset-password-page.cy.ts.ejs

Made the login e2e tests more stable.
---

fix: ensure login e2e tests target visible fields

---

generators/base-application/support/prepare-entity.ts

In #28730 there were a few additional changes, especially concerning the handling of `entityClassHumanized` and `entityClassPluralHumanized`. The mutateData call was changed there from a string value (return value of the function) to passing a function. 
According to the docs of the mutateData function (and the actual behaviour), it would now always override the values with the values produced from the functions:
https://github.com/jhipster/generator-jhipster/blob/88050b594ce34b2b639a01d8b9b7134eed933446/lib/utils/object.ts#L73-L75
This leaves the two (non-internal!) annotations broken, i.e. the value set there in jdl does not have any effect anymore.
https://github.com/jhipster/generator-jhipster/blob/88050b594ce34b2b639a01d8b9b7134eed933446/generators/app/README.md?plain=1#L47-L55
--- …

Correct non-working EntityClass*Humanized annotations
