generators/client/templates/react/src/main/webapp/app/modules/account/register/register.tsx.ejs
generators/client/templates/react/src/test/javascript/e2e/modules/account/account.spec.ts.ejs

Fix hipster-labs daily builds
---

fix protractor e2e tests for noi18n case

---

.github/actions/setup/action.yml

Use generator repository and main branch

---

cli/commands.js
cli/import-jdl.js
jdl/jdl-importer.js

JDL filters unchanged entities, forceNoFiltering option allow to not filter entities.
Create an option and expose it.
---

Forward force-no-filtering option to jdl

---

README.md

Add Snyk badge. https://snyk.io/test/npm/generator-jhipster

Add Snyk badge

---

jdl/validators/application-validator.js
test/jdl/validators/application-validator.spec.js

Forbid reactive JDL apps with websockets

---

generators/server/templates/src/main/java/package/security/jwt/TokenProvider.java.ejs

Fix https://github.com/jhipster/generator-jhipster/issues/14952
---

Use by default Base64-encoded JWT secret

---

generators/generator-constants.js

update gradle to 7.1

---

.github/workflows/webflux.yml
generators/server/templates/build.gradle.ejs

fix webflux + mariadb and gradle ci job

---

.github/actions/setup/action.yml
.github/workflows/cache.yml
azure-pipelines.yml
generators/generator-constants.js

Following:
- https://github.com/jhipster/jhipster-bom/releases/tag/7.1.0
- https://repo.maven.apache.org/maven2/tech/jhipster/jhipster-parent/7.1.0/
---

Upgrade jhipster bom 7.1.0

---

generators/generator-constants.js
test/__snapshots__/docker-compose.spec.js.snap
test/__snapshots__/knative.spec.js.snap
test/__snapshots__/kubernetes.helm.spec.js.snap
test/__snapshots__/kubernetes.spec.js.snap
test/__snapshots__/openshift.spec.js.snap

Upgrade jhipster-registry to v6.8.0

---

generators/common/templates/package.json

Bump NPM version to 7.18.1

---

generators/generator-constants.js
test/__snapshots__/ci-cd.spec.js.snap

Bump node to 14.17.1

---

.github/actions/compare-base/action.yml
.github/actions/compare/action.yml
.github/actions/setup/action.yml

Implement compare/compare-base action.

---

generators/generator-constants.js

Following https://github.com/jhipster/jhipster-control-center/releases/tag/v0.5.0
---

Upgrade jhipster-control-center to v0.5.0 [ci skip]

---

generators/server/index.js
generators/server/templates/build.gradle.ejs
generators/server/templates/gradle/profile_dev.gradle.ejs
generators/server/templates/pom.xml.ejs

Original issue is fixed https://github.com/jhipster/generator-jhipster/pull/14315#issuecomment-844149669
---

Drop --no-audit workaround.

---

.github/actions/setup/action.yml
azure-pipelines.yml
generators/generator-constants.js

Upgrade jhipster lib to 7.1.1-SNAPSHOT

---

generators/client/templates/react/jest.conf.js.ejs
generators/client/templates/react/package.json
generators/client/templates/react/package.json.ejs
generators/client/templates/react/src/main/webapp/app/shared/reducers/locale.ts.ejs
generators/client/templates/react/src/main/webapp/app/typings.d.ts.ejs
generators/client/templates/react/webpack/webpack.common.js.ejs
generators/client/templates/react/webpack/webpack.dev.js.ejs
generators/client/templates/react/webpack/webpack.prod.js.ejs

Migrate react to use i18n hash instead of build timestamp.
---

Fix index reproducibility in react framework.

---

generators/client/files-angular.js
generators/client/templates/angular/package.json
generators/client/templates/angular/package.json.ejs
generators/client/templates/angular/src/main/webapp/app/app.constants.ts.ejs
generators/client/templates/angular/src/main/webapp/app/app.module.ts.ejs
generators/client/templates/angular/src/main/webapp/app/config/translation.config.ts.ejs
generators/client/templates/angular/src/main/webapp/declarations.d.ts.ejs
generators/client/templates/angular/webpack/environment.js.ejs
generators/client/templates/angular/webpack/webpack.custom.js.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.module.ts.ejs
test/client/__snapshots__/angular.spec.js.snap
test/utils/expected-files.js

Change angular to use i18n hash instead of build timestamp.
---

Fix index reproducibility in angular framework.

---

generators/client/templates/react/src/main/webapp/app/config/constants.ts.ejs
generators/client/templates/react/src/main/webapp/app/config/error-middleware.ts.ejs
generators/client/templates/react/src/main/webapp/app/modules/home/home.tsx.ejs
generators/client/templates/react/src/main/webapp/app/shared/util/date-utils.ts.ejs

Sonar - React

---

generators/server/templates/pom.xml.ejs

Fix: missing dependency spring-data-commons

---

.github/actions/compare-base/action.yml
.github/workflows/angular.yml
.github/workflows/jdl.yml
.github/workflows/react.yml
.github/workflows/vue.yml
.github/workflows/webflux.yml
test-integration/scripts/10-install-jhipster.sh

Closes https://github.com/jhipster/generator-jhipster/issues/15129.
Use composite action to generate application to compare changes and another to show the diff.
---

Migrate compare to github actions.

---

generators/cypress/templates/src/test/javascript/cypress/integration/account/login-page.spec.ts.ejs
generators/cypress/templates/src/test/javascript/cypress/integration/account/password-page.spec.ts.ejs
generators/cypress/templates/src/test/javascript/cypress/integration/account/register-page.spec.ts.ejs
generators/cypress/templates/src/test/javascript/cypress/integration/account/reset-password-page.spec.ts.ejs
generators/cypress/templates/src/test/javascript/cypress/integration/account/settings-page.spec.ts.ejs

Remove some warnings like:
---

Cypress - Remove warnings

---

generators/client/templates/angular/package.json.ejs
generators/client/templates/common/package.json
generators/client/templates/react/package.json.ejs
generators/client/templates/vue/package.json.ejs
generators/cypress/templates/src/test/javascript/cypress/integration/administration/administration.spec.ts.ejs
generators/cypress/templates/src/test/javascript/cypress/plugins/index.ts.ejs
generators/cypress/templates/src/test/javascript/cypress/support/oauth2.ts.ejs
generators/entity-client/templates/common/src/test/javascript/cypress/integration/entity/entity.spec.ts.ejs

OIDC: Use Okta APIs in cypress tests to authenticate user instead of Puppeteer

---

generators/client/templates/angular/webpack/webpack.microfrontend.js.ejs

Fixes https://github.com/jhipster/generator-jhipster/issues/15390.
---

Fix microfrontend gateway failing to generate without microservices.

---

package-lock.json
package.json

Reverts jhipster/generator-jhipster#15470

Revert "chore(deps): bump commander from 7.2.0 to 8.0.0"

---

generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs

Fix test IT: unique validation

---

generators/generator-constants.js

This seems to fix #15359 too.
---

update to gradle 7.1.1

---

generators/cleanup.js
generators/client/files-angular.js
generators/client/templates/angular/.npmrc.ejs
test/client/__snapshots__/angular.spec.js.snap
test/utils/expected-files.js

Drop legacy-peer-deps from angular.

---

generators/client/templates/vue/src/main/webapp/app/account/reset-password/init/reset-password-init.component.ts.ejs
generators/client/templates/vue/src/main/webapp/app/admin/health/health.service.ts.ejs
generators/client/templates/vue/src/main/webapp/app/admin/metrics/metrics.service.ts.ejs

[Vue] Clean code

---

generators/client/templates/react/jest.conf.js.ejs
generators/client/templates/react/src/main/webapp/app/config/axios-interceptor.spec.ts.ejs
generators/client/templates/react/src/main/webapp/app/modules/account/settings/settings.reducer.spec.ts.ejs
generators/client/templates/react/src/main/webapp/app/shared/auth/private-route.spec.tsx.ejs
generators/client/templates/react/src/main/webapp/app/shared/error/error-boundary-route.spec.tsx.ejs
generators/client/templates/react/src/main/webapp/app/shared/error/error-boundary.spec.tsx.ejs
generators/client/templates/react/src/main/webapp/app/shared/layout/header/header.spec.tsx.ejs
generators/client/templates/react/src/main/webapp/app/shared/layout/menus/account.spec.tsx.ejs
generators/client/templates/react/src/main/webapp/app/shared/reducers/authentication.spec.ts.ejs

Improve my PR https://github.com/jhipster/generator-jhipster/pull/15128 like it is for Vue https://github.com/jhipster/generator-jhipster/pull/15262
---

[React] Improve migration to Jest 27

---

generators/generator-constants.js

downgrade gradle to 7.0.2

---

jdl/parsing/validator.js
test/jdl/grammar/validator.spec.js

Fixed syntax error when parsing ingressType option

---

cli/jhipster-command.js
package-lock.json
package.json

Bump commander to 8.0.0

---

generators/client/templates/angular/src/main/webapp/app/admin/user-management/list/user-management.component.ts.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.ts.ejs

Use the nullish coalescing operator ??
---

[Angular] Typescript: use the nullish coalescing operator ??

---

generators/client/templates/vue/src/main/webapp/app/account/reset-password/finish/reset-password-finish.component.ts.ejs

[Vue] Use optional chaining

---

generators/client/templates/angular/src/main/webapp/app/admin/health/modal/health-modal.component.ts.ejs
generators/client/templates/angular/src/main/webapp/app/admin/metrics/blocks/metrics-system/metrics-system.component.ts.ejs
generators/client/templates/angular/src/main/webapp/app/admin/user-management/list/user-management.component.ts.ejs
generators/client/templates/angular/src/main/webapp/app/config/error.constants.ts.ejs

[Angular] Use Template Literals

---

generators/client/templates/common/package.json
generators/cypress/templates/src/test/javascript/cypress/plugins/index.ts.ejs

Fix PR https://github.com/jhipster/generator-jhipster/pull/15649
Due to https://github.com/GoogleChrome/lighthouse/pull/12690
---

Fix upgrade Lighthouse 8.0.0 -> 8.1.0

---

generators/client/templates/vue/package.json

Reverts jhipster/generator-jhipster#15678

Revert "chore(deps-dev): bump eslint from 6.8.0 to 7.31.0 in /generators/client/templates/vue"

---

generators/client/templates/angular/package.json
generators/client/templates/react/package.json

Fix:
- https://github.com/jhipster/generator-jhipster/pull/15692
- https://github.com/jhipster/generator-jhipster/pull/15690
---

Upgrade eslint-webpack-plugin 3.0.1 (Angular, React)

---

generators/client/templates/angular/src/main/webapp/app/admin/health/modal/health-modal.component.ts.ejs
generators/client/templates/angular/src/main/webapp/app/layouts/main/main.component.ts.ejs

[Angular] Clean code

---

CONTRIBUTING.md
cli/program.js
generators/add/index.cjs
generators/generator-base.js
lib/support/index.cjs
package.json

Improve documentation and add experimental annotation to modular apis.

---

generators/client/templates/angular/package.json
generators/client/templates/angular/package.json.ejs

- Fixes microfrontend support
- Fixes `npm start` (with hmr support)
---

Force webpack version at angular.

---

generators/client/templates/vue/src/main/webapp/app/account/account.service.ts.ejs
generators/client/templates/vue/src/main/webapp/app/core/jhi-navbar/jhi-navbar.component.ts.ejs

[Vue] Sonar: 'Unexpected empty arrow function'

---

generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs

Add "application/json"  mediaType supports to patch method

---

generators/client/templates/angular/src/main/webapp/app/admin/health/health.component.ts.ejs
generators/client/templates/angular/src/main/webapp/app/admin/logs/logs.service.ts.ejs
generators/client/templates/angular/src/main/webapp/app/layouts/navbar/navbar.component.ts.ejs

Angular: clean code

---

generators/client/templates/vue/package.json
generators/client/templates/vue/package.json.ejs
generators/client/templates/vue/src/main/webapp/app/shared/config/axios-interceptor.ts.ejs
generators/client/templates/vue/src/main/webapp/app/shared/config/config.ts.ejs
generators/client/templates/vue/src/test/javascript/spec/app/shared/config/axios-interceptor.spec.ts.ejs

Added interceptor, that can be hooked to some UI finctionality
---
Fixes: #15722

Vue client - add interceptor for status >= 500

---

generators/client/templates/angular/package.json
generators/client/templates/angular/package.json.ejs

Bump @angular/cli and synchronize webpack.

---

generators/server/templates/src/main/java/package/web/rest/AccountResource.java.ejs
generators/server/templates/src/test/java/package/web/rest/AccountResourceIT_skipUserManagement.java.ejs

Discovered this while trying to reproduce https://github.com/jhipster/generator-jhipster/issues/15507. 
---

Fix gateway when skipUserManagement is true

---

.npmignore
package.json

Don't publish test files.

---

generators/client/templates/react/src/main/webapp/app/shared/reducers/index.ts.ejs

[React] Remove unused code

---

generators/client/templates/vue/src/main/webapp/app/admin/logs/logs.service.ts.ejs
generators/client/templates/vue/src/main/webapp/app/constants.ts.ejs

[Vue] Use template strings

---

generators/languages/index.js
generators/languages/prompts.js
generators/server/files.js
test/blueprint/languages-blueprint.spec.js
test/needle-api/needle-client-i18n.spec.js

Adjusts to languages generator.

---

generators/client/templates/vue/src/main/webapp/app/account/change-password/change-password.component.ts.ejs
generators/client/templates/vue/src/main/webapp/app/account/settings/settings.component.ts.ejs
generators/client/templates/vue/src/main/webapp/app/admin/user-management/user-management.component.ts.ejs
generators/client/templates/vue/src/main/webapp/app/core/home/home.component.ts.ejs

[Vue] Use nullish coalescing

---

generators/client/templates/vue/src/main/webapp/app/admin/configuration/configuration.component.ts.ejs
generators/client/templates/vue/src/main/webapp/app/admin/health/health.component.ts.ejs
generators/client/templates/vue/src/main/webapp/app/admin/logs/logs.component.ts.ejs
generators/client/templates/vue/src/main/webapp/app/admin/user-management/user-management.service.ts.ejs

Vue: improve code

---

generators/generator-base.js

Related to https://github.com/jhipster/generator-jhipster/issues/15490.
- Allow to execute writeFiles with sections, blocks or templates.
- Replace noEjs with transform.
- Don't fail with condition not met.
---

Fixes and improvements to writeFiles.

---

generators/generator-base.js

Fix condition

---

generators/client/files-react.js
generators/client/templates/react/jest.conf.js.ejs
generators/client/templates/react/src/main/webapp/app/config/axios-interceptor.ts.ejs
generators/client/templates/react/src/main/webapp/app/config/constants.ts.ejs
generators/client/templates/react/src/main/webapp/app/config/error-middleware.ts.ejs
generators/client/templates/react/src/main/webapp/app/config/logger-middleware.ts.ejs
generators/client/templates/react/src/main/webapp/app/shared/error/error-boundary.tsx.ejs
generators/client/templates/react/src/main/webapp/app/shared/layout/header/header-components.tsx.ejs
generators/client/templates/react/src/main/webapp/app/typings.d.ts.ejs
generators/client/templates/react/webpack/environment.js.ejs
generators/client/templates/react/webpack/webpack.common.js.ejs
test/__snapshots__/app.spec.js.snap

Fixes https://github.com/jhipster/generator-jhipster/issues/15074.
Apply same fix used for angular https://github.com/jhipster/generator-jhipster/pull/15107. 
---

Replace node especific process.env with injected variables at React.

---

generators/generator-base-blueprint.js
test/blueprint/app-blueprint.spec.js

Don't throw error when generator-jhipster dependency is a git commit.

---

generators/server/templates/src/main/java/package/service/UserService.java.ejs

Fix
Due to this commit https://github.com/jhipster/generator-jhipster/commit/0f20effd4d5a669d3befb9918b5132c6a7f91bcb#diff-8d3857a49120e9cdab3ecb40c78ff1022a997bbfc3c0f892bf09b50a0a443ab5
---

Sonar: duplicated import

---

generators/server/templates/src/main/java/package/web/rest/AccountResource.java.ejs

Sonar: unused import

---

generators/client/templates/react/src/main/webapp/app/modules/administration/health/health.tsx.ejs

[React] Sonar: Extract this nested ternary operation into an independent statement

---

generators/maven/templates/.mvn/wrapper/maven-wrapper.properties
generators/server/templates/.mvn/wrapper/maven-wrapper.properties

Update maven wrapper version to 3.8.2

---

generators/client/index.js
generators/entity-i18n/files.js
generators/generator-base-private.js
generators/generator-base.js
generators/languages/files.js
generators/languages/index.js
test/blueprint/entity-blueprint.spec.js
test/languages.spec.js

Reimplement client languages/i18n files.

---

generators/database-changelog-liquibase/templates/src/main/resources/config/liquibase/changelog/updated_entity_constraints.xml.ejs
test-integration/incremental-changelog-samples/liquibase-jdl-rename-field-post/app.jdl

Fixes https://github.com/jhipster/generator-jhipster/issues/15282.
---

Fix incremental changelog for relationships.

---

generators/cypress/index.js

Fixes https://github.com/jhipster/generator-jhipster/pull/16149#discussion_r702092409.
---

Fix broken script

---

generators/common/index.js
generators/generator-base.js
generators/init/index.cjs

Closes https://github.com/jhipster/generator-jhipster/issues/16172
---

Fix husky on existing monorepository.

---

package-lock.json

Run npm audit fix to update package-lock

---

generators/client/templates/angular/package.json

Reverts jhipster/generator-jhipster#16069

Revert "chore(deps-dev): bump typescript from 4.3.5 to 4.4.2 in /generators/client/templates/angular"

---

generators/docker-compose/templates/README-DOCKER-COMPOSE.md.ejs
generators/kubernetes-knative/templates/service.yml.ejs
generators/kubernetes/templates/deployment.yml.ejs
generators/openshift/templates/deployment.yml.ejs
generators/server/templates/src/main/docker/app.yml.ejs
test/__snapshots__/docker-compose.spec.js.snap
test/templates/compose/10-couchbase/src/main/docker/app.yml
test/templates/compose/10-couchbase/src/main/docker/couchbase.yml

Docker-compose files were using old configuration from Spring Data Couchbase 3.
---

Fix Couchbase docker-compose configuration

---

generators/entity-server/templates/couchbase/src/main/java/package/repository/EntityRepository.java.ejs
generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
generators/server/templates/couchbase/src/main/java/package/repository/JHipsterCouchbaseRepository.java.ejs
generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs
generators/server/templates/src/test/java/package/config/JHipsterBlockHoundIntegration.java.ejs
generators/server/templates/src/test/java/package/web/rest/TestUtil.java.ejs

This includes https://github.com/jhipster/generator-jhipster/pull/16209
---

Fix Pageable in Couchbase Reactive

---

generators/server/templates/src/main/java/package/security/SecurityUtils.java.ejs
generators/server/templates/src/test/java/package/security/SecurityUtilsUnitTest.java.ejs

To provide some handy methods in scenario:   
- want to check if a user has any authority in a list of authorities
- want to check if a user has none of authority in a list of authorities
---

Authority check in SecurityUtils support array parameter

---

.github/actions/setup/action.yml
azure-pipelines.yml
generators/generator-constants.js

Following:
- https://github.com/jhipster/jhipster-bom/releases/tag/7.2.0
- https://repo.maven.apache.org/maven2/tech/jhipster/jhipster-parent/7.2.0/
---

Upgrade jhipster bom 7.2.0

---

generators/generator-constants.js
test/__snapshots__/docker-compose.spec.js.snap
test/__snapshots__/knative.spec.js.snap
test/__snapshots__/kubernetes.helm.spec.js.snap
test/__snapshots__/kubernetes.spec.js.snap
test/__snapshots__/openshift.spec.js.snap

Upgrade jhipster-registry to v7.0.0

---

package-lock.json
package.json

It's to fix the issue, detected by Snyk:
https://snyk.io/test/npm/generator-jhipster
---

Upgrade to axios 0.21.4

---

utils/liquibase.js

Fixed #16244 load data issue for date columns

---

.github/workflows/angular.yml
.github/workflows/devserver.yml
.github/workflows/incremental-changelog.yml
.github/workflows/jdl.yml
.github/workflows/react.yml
.github/workflows/vue.yml
.github/workflows/webflux.yml
generators/azure-app-service/templates/github/workflows/azure-app-service.yml.ejs
generators/azure-spring-cloud/templates/github/workflows/azure-spring-cloud.yml.ejs
generators/ci-cd/templates/github-actions.yml.ejs
test/__snapshots__/ci-cd.spec.js.snap

After #16193 adoptopenjdk is changed to eclipse-temurin
This PR changes all the references from adopt to temurin
---

Migrate to Eclipse Temurin

---

generators/server/templates/src/main/java/package/security/PersistentTokenRememberMeServices.java.ejs

Remove the dead link. It seems to require basic auth now, so it is not available anymore.
---

remove dead link in code comment

---

generators/heroku/index.js

* check if okta is selected before prompting for additional okta properties
* add timeout to heroku create command such that we can react on invalid credentials
closes #16299
---

do not ask for additional okta properties if not selected

---

generators/generator-constants.js

Let's see if 7.2.0 resolves the problem with https://github.com/jhipster/generator-jhipster/issues/15359.
See too https://github.com/jhipster/generator-jhipster/pull/15576
---

update gradle to 7.2.0

---

.github/labeler.yml
.github/workflows/labeler.yml

Add labels based on updated files.
---

Implement labeler workflow.

---

.github/actions/setup/action.yml
azure-pipelines.yml
generators/generator-constants.js
generators/server/templates/src/main/java/package/config/JacksonConfiguration.java.ejs

Upgrade problem-spring verstion to 0.27.0

---

.github/actions/setup/action.yml
azure-pipelines.yml

Switch back to jhipster depedency snapshot version

---

generators/entity-client/templates/react/src/main/webapp/app/entities/entity-delete-dialog.tsx.ejs

[React] Fix double calls when deleting entity

---

generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs
generators/server/templates/src/main/java/package/config/SecurityConfiguration_reactive.java.ejs

Order Permissions Policy

---

generators/client/templates/angular/src/main/webapp/app/admin/configuration/configuration.service.spec.ts.ejs
generators/client/templates/angular/src/main/webapp/app/admin/logs/logs.service.spec.ts.ejs
generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics.service.spec.ts.ejs
generators/client/templates/angular/src/main/webapp/app/admin/user-management/service/user-management.service.spec.ts.ejs
generators/client/templates/angular/src/main/webapp/app/core/auth/account.service.spec.ts.ejs
generators/client/templates/angular/src/main/webapp/app/entities/user/user.service.spec.ts.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/route/entity-management-routing-resolve.service.spec.ts.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/service/entity.service.spec.ts.ejs

Some **describe** are useless
---

[Angular] Tests: delete 'describe' useless

---

.github/actions/setup/action.yml
.github/workflows/angular.yml
.github/workflows/cache.yml
.github/workflows/devserver.yml
.github/workflows/incremental-changelog.yml
.github/workflows/jdl.yml
.github/workflows/react.yml
.github/workflows/vue.yml
.github/workflows/webflux.yml
generators/server/index.js

Related to https://github.com/jhipster/generator-jhipster/pull/16339.
Fixes https://github.com/jhipster/generator-jhipster/pull/16332#issuecomment-922041653
---

Switch from 13-replace-version-generated-project.sh to environment variable.

---

cli/jdl.js

[JDL] Add fallback message in case file not found

---

cli/environment-builder.js

Fixes https://github.com/jhipster/generator-jhipster/issues/16148
---

Set environment max listeners to 0

---

utils/field.js

Fixes https://github.com/jhipster/generator-jhipster/issues/16421.
---

Fix generator reference

---

generators/entity-server/files-couchbase.js
generators/entity-server/files.js
generators/entity-server/templates/couchbase/src/main/java/package/repository/EntityRepository.java.ejs
generators/entity-server/templates/couchbase/src/main/resources/config/couchmove/changelog/entity.fts.ejs
generators/entity-server/templates/src/main/java/package/domain/Entity.java.jhi.ejs
generators/entity-server/templates/src/main/java/package/domain/enumeration/Enum.java.ejs
generators/entity-server/templates/src/main/java/package/repository/EntityRepository.java.ejs
generators/entity-server/templates/src/main/java/package/repository/EntityRepositoryInternalImpl_reactive.java.ejs
generators/entity-server/templates/src/main/java/package/repository/EntityRepository_reactive.java.ejs
generators/entity-server/templates/src/main/java/package/repository/rowmapper/EntityRowMapper.java.ejs
generators/entity-server/templates/src/main/java/package/repository/search/EntitySearchRepository.java.ejs
generators/entity-server/templates/src/main/java/package/service/EntityQueryService.java.ejs
generators/entity-server/templates/src/main/java/package/service/EntityService.java.ejs
generators/entity-server/templates/src/main/java/package/service/criteria/EntityCriteria.java.ejs
generators/entity-server/templates/src/main/java/package/service/dto/EntityDTO.java.ejs
generators/entity-server/templates/src/main/java/package/service/impl/EntityServiceImpl.java.ejs
generators/entity-server/templates/src/main/java/package/service/mapper/BaseEntityMapper.java.ejs
generators/entity-server/templates/src/main/java/package/service/mapper/EntityMapper.java.ejs
generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs
generators/entity-server/templates/src/test/java/package/domain/EntityTest.java.ejs
generators/entity-server/templates/src/test/java/package/repository/search/EntitySearchRepositoryMockConfiguration.java.ejs
generators/entity-server/templates/src/test/java/package/service/dto/EntityDTOTest.java.ejs
generators/entity-server/templates/src/test/java/package/service/mapper/EntityMapperTest.java.ejs
generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
generators/entity/index.js
generators/server/index.js
generators/server/needle-api/needle-server-cache.js
generators/server/templates/src/main/java/package/config/DatabaseConfiguration_sql.java.ejs
test-integration/samples/jdl-entities/custom-domain.jdl

This PR allows entities to be organized by packages.
```
@EntityPackage(custom)
entity CustomPackageChild
```
Will generate every CustomPackageChild file at packageName.custom package.
---

Allow entities to be organized by packages.

---

generators/kubernetes-helm/templates/app/Chart.yml.ejs
generators/kubernetes-helm/templates/app/requirements.yml.ejs
generators/kubernetes-helm/templates/csvc/Chart.yml.ejs
generators/kubernetes-helm/templates/csvc/requirements.yml.ejs
test/__snapshots__/knative.spec.js.snap
test/__snapshots__/kubernetes.helm.spec.js.snap

The [Helm Chars repository](https://github.com/helm/charts) is deprecated and marked obsolete. Some of the particular charts have linked to the new maintainer. I've changed the repo URLs for these charts. Some other charts had no link or it was not explicit enough.
Furthermore since Helm v3 [the dependencies are managed](https://helm.sh/docs/helm/helm_dependency/) inside Chart.yaml file. To support v2 and v3 I left both files with the dependencies.
---

Improve Helm dependencies

---

package-lock.json
package.json

Fix https://github.com/jhipster/generator-jhipster/pull/16441
---

Upgrade prettier-plugin-packagejson 2.2.13

---

generators/bootstrap/index.js
generators/client/templates/angular/package.json.ejs
generators/client/templates/react/package.json.ejs
generators/client/templates/vue/package.json.ejs
generators/generator-base.js
generators/server/index.js
generators/server/templates/pom.xml.ejs
generators/server/templates/src/main/resources/config/application.yml.ejs

Related to https://github.com/jhipster/jhipster-registry/pull/518.
---

Allow more customizations.

---

.github/actions/build-matrix/action.yml
.github/workflows/angular.yml
.github/workflows/jdl.yml
.github/workflows/react.yml
.github/workflows/vue.yml
.github/workflows/webflux.yml
generators/client/__workflow/devserver-angular.json
generators/client/__workflow/devserver-react.json
generators/client/__workflow/devserver-vue.json

- Only execute backend or client tests if there are changes that will affect them.
- Skip the workflow entirely if changes that needs be tested are not detected.
- Reduced entities generated for devserver tests.
---

Execute tests based on changed files.

---

.github/actions/build-matrix/action.yml
.github/workflows/angular.yml
.github/workflows/jdl.yml
.github/workflows/react.yml
.github/workflows/vue.yml
.github/workflows/webflux.yml

Build matrix

---

.github/workflows/angular.yml
.github/workflows/jdl.yml
.github/workflows/react.yml
.github/workflows/vue.yml
.github/workflows/webflux.yml

Related to https://github.com/jhipster/generator-jhipster/pull/16435.
---

Adjusts to build-matrix.

---

generators/heroku/index.js

Skip writing Okta admin password when useOkta false and printing okta admin password at the end of the console

---

.github/dependabot.yml

Ignore vue3 only dependency vue-loader@16

---

.github/actions/setup/action.yml
azure-pipelines.yml
generators/generator-constants.js

Following:
https://github.com/jhipster/jhipster-bom/releases/tag/7.3.0
https://repo.maven.apache.org/maven2/tech/jhipster/jhipster-parent/7.3.0/
---

Upgrade jhipster bom 7.3.0

---

generators/generator-constants.js
test/__snapshots__/docker-compose.spec.js.snap
test/__snapshots__/knative.spec.js.snap
test/__snapshots__/kubernetes.helm.spec.js.snap
test/__snapshots__/kubernetes.spec.js.snap
test/__snapshots__/openshift.spec.js.snap

Upgrade jhipster-registry to v7.1.0

---

generators/client/templates/vue/package.json
generators/client/templates/vue/src/main/webapp/app/account/account.service.ts.ejs
generators/client/templates/vue/src/main/webapp/app/admin/configuration/configuration.service.ts.ejs

Fix https://github.com/jhipster/generator-jhipster/pull/16518
---

[Vue] Upgrade Axios

---

generators/maven/templates/.mvn/wrapper/maven-wrapper.properties
generators/server/templates/.mvn/wrapper/maven-wrapper.properties

Update maven wrapper version to 3.8.3

---

generators/generator-constants.js
generators/server/templates/gradle.properties.ejs
generators/server/templates/pom.xml.ejs

Update liquibase version to 4.5.0

---

generators/client/templates/react/package.json

Upgrade react-jhipster to 0.17.0

---

generators/client/templates/vue/src/main/webapp/app/account/settings/settings.vue.ejs

Generated code:
Before
```
<h2 v-if="username" id="settings-title">
<span v-html="$t('settings.title', { username: username })"
>User settings for [<strong>{{ username }}</strong
>]</span
>
</h2>
```
After
```
<h2 v-if="username" id="settings-title">
<span v-html="$t('settings.title', { username: username })">
User settings for [
<strong>
{{ username }}
</strong>
]
</span>
</h2>
```
---

[Vue] Improve format code

---

generators/client/templates/vue/src/main/webapp/app/account/account.service.ts.ejs
generators/client/templates/vue/src/main/webapp/app/admin/configuration/configuration.vue.ejs
generators/client/templates/vue/src/main/webapp/app/admin/metrics/metrics.component.ts.ejs

[Vue] code improvements

---

generators/client/templates/react/package.json
generators/client/templates/vue/package.json

Webpack upgrade

---

generators/client/templates/react/package.json
generators/client/templates/vue/.eslintrc.js.ejs
generators/client/templates/vue/package.json

Upgrade eslint dependencies (Vue, react)

---

generators/server/templates/src/main/java/package/security/oauth2/CustomClaimConverter.java.ejs

Fix #16943
@mraible I can't test on my Mac (problem with Docker :/)
---

Fix sonar issues

---

generators/generator-constants.js
generators/kubernetes-knative/templates/istio/gateway.yml.ejs
generators/kubernetes/templates/istio/destination-rule.yml.ejs
generators/kubernetes/templates/istio/gateway.yml.ejs
generators/kubernetes/templates/istio/gateway/grafana-gateway.yml.ejs
generators/kubernetes/templates/istio/gateway/jhipster-grafana-gateway.yml.ejs
generators/kubernetes/templates/istio/gateway/kiali-gateway.yml.ejs
generators/kubernetes/templates/istio/gateway/zipkin-gateway.yml.ejs
test/__snapshots__/knative.spec.js.snap
test/__snapshots__/kubernetes.helm.spec.js.snap
test/__snapshots__/kubernetes.spec.js.snap

Still need to fix gateways
Fix #16985 
---

k8s: istio: update to latest specs

---

generators/common/templates/package.json

Upgrade utils dependencies

---

package-lock.json
package.json

Upgrade prettier dependencies

---

generators/client/templates/react/package.json
generators/client/templates/vue/package.json

[React/Vue] Upgrade webpack-dev-server

---

generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs

Fix User relationship names

---

CONTRIBUTING.md

document npm ci in setup guide for contributing

---

generators/bootstrap/index.js

Closes https://github.com/jhipster/generator-jhipster/issues/16520.
---

Implement ignore option (do not override and remember).

---

generators/server/__snapshots__/generator.spec.mjs.snap
generators/server/files.js
generators/server/templates/src/main/java/package/management/SecurityMetersService.java.ejs
generators/server/templates/src/main/java/package/security/jwt/TokenProvider.java.ejs
generators/server/templates/src/test/java/package/management/SecurityMetersServiceTests.java.ejs
generators/server/templates/src/test/java/package/security/jwt/JWTFilterTest.java.ejs
generators/server/templates/src/test/java/package/security/jwt/TokenProviderSecurityMetersTests.java.ejs
generators/server/templates/src/test/java/package/security/jwt/TokenProviderTest.java.ejs
test/__snapshots__/app-client-custom-path.spec.js.snap
test/__snapshots__/app.spec.js.snap
test/__snapshots__/server.spec.js.snap
test/blueprint/__snapshots__/app-blueprint.spec.js.snap
test/blueprint/__snapshots__/scoped-blueprint.spec.js.snap
test/utils/expected-files.js

add a service to track token validation errors, use it into the existing TokenProvider class and add corresponding tests
Closes #16269
---

add invalid tokens metrics + tests

---

generators/generator-constants.js
generators/server/templates/gradle.properties.ejs
generators/server/templates/pom.xml.ejs

Update server dependencies

---

.github/workflows/generator.yml
Dockerfile
generators/client/templates/vue/src/test/javascript/jest.conf.js.ejs
generators/generator-constants.js
generators/init/constants.cjs
package.json
test/__snapshots__/ci-cd.spec.js.snap
test/client/__snapshots__/vue.spec.js.snap
test/client/react.spec.js
test/client/vue.spec.js
test/jdl/converters/parsedJDLToJDLObject/parsed-jdl-to-jdl-object-converter.spec.js
test/jdl/jhipster/default-application-options.spec.js

Bump node and fix tests.

---

generators/generator-constants.js

Update spring-boot version to 2.5.7

---

.github/actions/setup/action.yml
azure-pipelines.yml
generators/generator-constants.js

Upgrade generator jhipster 7.4.0

---

.github/actions/setup/action.yml
azure-pipelines.yml
generators/generator-constants.js

Upgrade jhipster-dependencies to 7.4.1-SNAPSHOT

---

generators/client/templates/angular/package.json

Reverts #16906.
Fixes #17073.
---

Revert ngx-cookie-service version

---

generators/client/templates/react/package.json

React: upgrade dependencies

---

generators/server/index.js
test/server.spec.js

Closes https://github.com/jhipster/generator-jhipster/issues/17092.
---

Force reactive when gateway application type is selected.

---

generators/client/needle-api/needle-client-vue.js
generators/client/templates/vue/src/main/webapp/app/entities/entities.component.ts.ejs
generators/entity-client/files.js
generators/generator-base.js
test/needle-api/needle-client-vue.spec.js

Closes https://github.com/jhipster/generator-jhipster/issues/17075.
---

Fix `jhipster entity` for vue.

---

.github/workflows/stale.yml

Exclude PR and Issue with specific labels in stale workflow

---

generators/generator-base-blueprint.js
generators/generator-base.js

Closes https://github.com/jhipster/generator-jhipster/pull/16734.
---

Handle error on fail to parse blueprint templates folder.

---

test-integration/samples/ngx-gradle-mongodb-kafka-cucumber/.yo-rc.json

Add regression test for https://github.com/jhipster/generator-jhipster/issues/17073
---

Switch angular test to session + websocket.

---

generators/common/templates/README.md.jhi.ejs

Fixes https://github.com/jhipster/generator-jhipster/issues/17016.
---

Add Project Structure to Readme

---

generators/client/files-common.js
generators/entity-client/templates/common/src/test/javascript/cypress/integration/entity/entity.spec.ts.ejs

Closes https://github.com/jhipster/generator-jhipster/issues/17099
---

Misc fixes

---

generators/cypress/templates/src/test/javascript/cypress/plugins/index.ts.ejs

Added missing semicolon

---

generators/cypress/index.js

Should be reverted once https://github.com/cypress-io/cypress/issues/19097 is fixed.
---

Workaround cypress bug.

---

package-lock.json
package.json

Fixes https://github.com/jhipster/generator-jhipster/issues/17124
---

Bump yeoman-environment to 3.8.1

---

generators/cypress/index.js

Reverts jhipster/generator-jhipster#17125
Keep track of https://github.com/cypress-io/cypress/issues/19097.

Revert "Workaround cypress bug."

---

generators/client/templates/vue/src/test/javascript/spec/app/account/login-form/login-form.component.spec.ts.ejs

[Vue] Fix one test for Node 16

---

generators/languages/templates/src/main/webapp/i18n/vi/login.json

fix: correct typo in i18n/vi

---

.github/workflows/angular.yml
.github/workflows/devserver.yml
.github/workflows/jdl.yml
.github/workflows/react.yml
.github/workflows/vue.yml
.github/workflows/webflux.yml

Reenable sonar at workflows.

---

generators/client/templates/vue/src/main/webapp/app/account/account.service.ts.ejs
generators/client/templates/vue/src/main/webapp/app/core/jhi-navbar/jhi-navbar.component.ts.ejs
generators/client/templates/vue/src/test/javascript/spec/app/admin/user-management/user-management-edit.component.spec.ts.ejs
generators/client/templates/vue/src/test/javascript/spec/app/admin/user-management/user-management.component.spec.ts.ejs
generators/client/templates/vue/src/test/javascript/spec/app/core/jhi-navbar/jhi-navbar.component.spec.ts.ejs
generators/cypress/templates/src/test/javascript/cypress/support/index.ts.ejs
generators/entity-client/templates/vue/src/main/webapp/app/entities/entity-update.component.ts.ejs
generators/entity-client/templates/vue/src/test/javascript/spec/app/entities/entity-update.component.spec.ts.ejs
generators/entity-client/templates/vue/src/test/javascript/spec/app/entities/entity.component.spec.ts.ejs

Fix vue unhandled exceptions. Or partially.
Related to https://github.com/jhipster/generator-jhipster/issues/17096 and https://github.com/jhipster/generator-jhipster/issues/16744.
---

Fix vue unhandled exceptions.

---

generators/app/index.js
generators/generator-base.js

Should fix jdl builds of daily builds.
---

Adjust microservice defaults and microfrontend detection.

---

.github/actions/setup/action.yml
azure-pipelines.yml
generators/generator-constants.js

Following:
https://github.com/jhipster/jhipster-bom/releases/tag/7.4.1
https://repo.maven.apache.org/maven2/tech/jhipster/jhipster-parent/7.4.1/
---

Upgrade jhipster bom 7.4.1

---

generators/server/templates/src/main/resources/config/application.yml.ejs

Fixes spring liveness and readiness probes configuration

---

.github/actions/setup/action.yml
azure-pipelines.yml
generators/generator-constants.js

Upgrade jhipster bom to 7.4.2-SNAPSHOT

---

generators/client/templates/angular/src/main/webapp/app/account/password/password-strength-bar/password-strength-bar.component.ts.ejs

Fix https://sonarcloud.io/project/issues?id=jhipster-sample-application&open=AX1ygcOK2farvsyMs7mo&resolved=false&types=CODE_SMELL
---

[Angular] Fix Sonar

---

generators/server/templates/src/test/java/package/management/SecurityMetersServiceTests.java.ejs
generators/server/templates/src/test/java/package/security/jwt/TokenProviderSecurityMetersTests.java.ejs

Fix:
- https://sonarcloud.io/project/issues?id=jhipster-sample-application&open=AX1ygcau2farvsyMs7m6&resolved=false&types=CODE_SMELL
- https://sonarcloud.io/project/issues?id=jhipster-sample-application&open=AX1ygcad2farvsyMs7mx&resolved=false&types=CODE_SMELL
---

Sonar: Use isZero()

---

generators/client/templates/react/src/main/webapp/app/config/axios-interceptor.spec.ts.ejs
generators/cypress/templates/src/test/javascript/cypress/support/index.ts.ejs
generators/entity-client/templates/common/src/test/javascript/cypress/integration/entity/entity.spec.ts.ejs
generators/entity-client/templates/react/src/main/webapp/app/entities/entity.reducer.ts.ejs

Closes https://github.com/jhipster/generator-jhipster/issues/16982
---

Fix react unhandled exceptions

---

.github/actions/setup/action.yml
azure-pipelines.yml

Revert to jhipster-bom main branch

---

generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
generators/server/templates/src/main/java/package/repository/AuthorityRepository.java.ejs
generators/server/templates/src/main/java/package/service/UserService.java.ejs

Fix some errors with option 'entitySuffix' active

---

generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs
generators/server/templates/src/main/java/package/config/SecurityConfiguration_reactive.java.ejs

format template file: SecurityConfiguration.java.ejs
---

format template file: SecurityConfiguration.java.ejs

---

generators/client/templates/vue/src/test/javascript/spec/app/admin/user-management/user-management-edit.component.spec.ts.ejs
generators/client/templates/vue/src/test/javascript/spec/app/admin/user-management/user-management.component.spec.ts.ejs
test-integration/samples/vue-default/.yo-rc.json

Needs to match:
https://github.com/jhipster/generator-jhipster/blob/cac20375b504deae9be837078de6667a13336692/generators/client/templates/vue/src/main/webapp/app/admin/user-management/user-management.component.ts.ejs#L98-L99
Should fix current daily builds failures.
Related to https://github.com/jhipster/generator-jhipster/issues/17096.
---

Fix wrong headers at vue tests.

---

.github/workflows/devserver.yml

Fixes main build failures.
---

Switch devserver workflow to opt-in sonar.

---

generators/entity/index.js

Remove duplicate constant CLIENT_FRAMEWORK_NO

---

generators/server/templates/pom.xml.ejs

Fixes https://github.com/jhipster/generator-jhipster/issues/17294.
---

Remove jdk specific profiles

---

generators/entity-server/templates/src/main/java/package/repository/EntityRepository.java.ejs
generators/entity-server/templates/src/main/java/package/repository/EntityRepositoryInternalImpl_reactive.java.ejs
generators/entity-server/templates/src/main/java/package/repository/EntityRepository_reactive.java.ejs
generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
generators/generator-constants.js
generators/gradle/constants.cjs
generators/server/templates/build.gradle.ejs
generators/server/templates/pom.xml.ejs
generators/server/templates/src/main/java/package/config/DatabaseConfiguration_sql.java.ejs
generators/server/templates/src/main/java/package/config/ElasticsearchConfiguration.java.ejs
generators/server/templates/src/main/resources/config/liquibase/master.xml.ejs
package-lock.json

Should fix https://github.com/jhipster/generator-jhipster/issues/17271 when it will be achieved
---

WIP -use spring reactive repository implementation as implementation parent

---

generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs

optimize template file: UserRepository.java.ejs

---

generators/server/templates/build.gradle.ejs

Adjust gradle local maven repository

---

generators/client/templates/vue/src/main/webapp/app/account/account.service.ts.ejs

[Vue] Fix: Admin pages accessible for normal user

---

generators/client/templates/react/src/main/webapp/app/shared/reducers/authentication.spec.ts.ejs

[React] Fix: Variabilize language in test

---

generators/cleanup.js
generators/server/cleanup.js
generators/server/index.js

https://github.com/jhipster/generator-jhipster/blob/b4ee21c6c26df280bde8d22486821d167dea4db3/generators/server/files.js#L1741
Follows tasks notation and returns an object and it's unused.
Convert to a plain function.
Fix variables.
---

Adjust server cleanup.

---

generators/server/templates/src/main/java/package/security/oauth2/CustomClaimConverter.java.ejs

Refresh token won't work without this, in multi instances
---

Fix OAuth2 refresh token with concurrency

---

generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
generators/server/__snapshots__/generator.spec.mjs.snap
generators/server/files.js
generators/server/templates/build.gradle.ejs
generators/server/templates/pom.xml.ejs
generators/server/templates/src/test/java/package/AbstractCassandraTest.java.ejs
generators/server/templates/src/test/java/package/AbstractNeo4jIT.java.ejs
generators/server/templates/src/test/java/package/IntegrationTest.java.ejs
generators/server/templates/src/test/java/package/MongoDbTestContainerExtension.java.ejs
generators/server/templates/src/test/java/package/ReactiveSqlTestContainerExtension.java.ejs
generators/server/templates/src/test/java/package/TestContainersSpringContextCustomizerFactory.java.ejs
generators/server/templates/src/test/java/package/web/rest/AccountResourceIT.java.ejs
generators/server/templates/src/test/java/package/web/rest/AccountResourceIT_oauth2.java.ejs
generators/server/templates/src/test/java/package/web/rest/AccountResourceIT_skipUserManagement.java.ejs
generators/server/templates/src/test/java/package/web/rest/PublicUserResourceIT.java.ejs
generators/server/templates/src/test/java/package/web/rest/UserJWTControllerIT.java.ejs
generators/server/templates/src/test/java/package/web/rest/UserResourceIT.java.ejs
generators/server/templates/src/test/java/package/web/rest/errors/ExceptionTranslatorIT.java.ejs
generators/server/templates/src/test/resources/META-INF/spring.factories.ejs
generators/server/templates/src/test/resources/config/application.yml.ejs
test/__snapshots__/app.spec.js.snap

Use test containers for mongodb
---

Skip ci spring boot 2.6.0 mongo

---

generators/common/templates/package.json

Upgrade lint-staged 12.1.3 -> 12.1.4
---

Upgrade lint-staged

---

generators/client/templates/angular/src/main/webapp/app/app.module.ts.ejs
generators/client/templates/angular/src/main/webapp/app/shared/language/translation.module.ts.ejs

Fix:
- https://sonarcloud.io/project/issues?id=jhipster-sample-application&open=AX2_vH23IXrGCfmZB4Hm&resolved=false&types=CODE_SMELL
- https://sonarcloud.io/project/issues?id=jhipster-sample-application&open=AX2_vH5gIXrGCfmZB4Hn&resolved=false&types=CODE_SMELL
---

[Angular] Sonar

---

generators/client/templates/react/package.json

[React] Upgrade dependencies

---

generators/common/templates/README.md.jhi.ejs
generators/server/__snapshots__/generator.spec.mjs.snap
generators/server/files.js
generators/server/index.js
generators/server/templates/build.gradle.ejs
generators/server/templates/npmw
generators/server/templates/npmw.cmd
test/__snapshots__/app.spec.js.snap

Add gradle support to npmw.

---

generators/server/templates/src/main/java/package/security/jwt/TokenProvider.java.ejs

Fix:
https://sonarcloud.io/project/issues?id=jhipster-sample-application&open=AX1ygaLQ2farvsyMs7mn&resolved=false&types=CODE_SMELL
---

Sonar: Define a constant instead of duplicating this literal 

---

generators/server/templates/npmw.cmd

Build https://github.com/hipster-labs/jhipster-daily-builds/runs/4675195797?check_suite_focus=true
---

Fix npmw for windows.

---

generators/client/templates/angular/package.json

[Angular] Upgrade eslint 8.5.0

---

generators/client/templates/angular/src/main/webapp/app/account/activate/activate.component.ts.ejs
generators/client/templates/angular/src/main/webapp/app/account/password-reset/finish/password-reset-finish.component.ts.ejs
generators/client/templates/angular/src/main/webapp/app/account/password/password.component.ts.ejs
generators/client/templates/angular/src/main/webapp/app/account/register/register.component.ts.ejs
generators/client/templates/angular/src/main/webapp/app/admin/health/health.component.ts.ejs
generators/client/templates/angular/src/main/webapp/app/admin/user-management/list/user-management.component.ts.ejs
generators/client/templates/angular/src/main/webapp/app/admin/user-management/update/user-management-update.component.ts.ejs
generators/client/templates/angular/src/main/webapp/app/login/login.component.ts.ejs
generators/client/templates/angular/src/main/webapp/app/shared/language/translate.directive.ts.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/list/infinite-scroll-template.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/list/no-pagination-template.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/list/pagination-template.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.ts.ejs

Since RxJs 7.5.1 https://github.com/jhipster/generator-jhipster/commit/011bf9d7135d4beb2db09ab28f67b8b4255e8be3
A lot of Sonar issues:
- https://sonarcloud.io/project/issues?id=jhipster-sample-application&open=AX4MW77dDj-Pau3OPzGZ&resolved=false&types=CODE_SMELL
- https://sonarcloud.io/project/issues?id=jhipster-sample-application&open=AX4MW76cDj-Pau3OPzGX&resolved=false&types=CODE_SMELL
- https://sonarcloud.io/project/issues?id=jhipster-sample-application&open=AX4MW76KDj-Pau3OPzGW&resolved=false&types=CODE_SMELL
- https://sonarcloud.io/project/issues?id=jhipster-sample-application&open=AX4MW77EDj-Pau3OPzGY&resolved=false&types=CODE_SMELL
- ...
Solution: https://rxjs.dev/deprecations/subscribe-arguments
---
When you are …

[Angular] 'subscribe' is deprecated

---

generators/client/files-vue.js
generators/client/templates/vue/src/main/webapp/app/entities/entities.component.ts.ejs
generators/client/templates/vue/src/main/webapp/app/entities/user/user.service.ts.ejs
generators/client/templates/vue/src/main/webapp/app/main.ts.ejs
generators/entity-client/templates/common/src/test/javascript/cypress/integration/entity/entity.spec.ts.ejs
generators/entity-client/templates/vue/src/main/webapp/app/entities/entity-update.component.ts.ejs
generators/entity-client/templates/vue/src/test/javascript/spec/app/entities/entity-update.component.spec.ts.ejs
test/client/__snapshots__/vue.spec.js.snap

Fix https://github.com/jhipster/generator-jhipster/issues/17387
- Switches entities to use UserService instead of UserManagementService.
- Switches cypress tests to use `user` user. 
---

Fix vue public user service usage.

---

.github/actions/setup/action.yml
azure-pipelines.yml
generators/generator-constants.js

Following:
https://github.com/jhipster/jhipster-bom/releases/tag/7.5.0
https://repo.maven.apache.org/maven2/tech/jhipster/jhipster-parent/7.5.0/
---

Upgrade jhipster bom 7.5.0

---

.github/actions/setup/action.yml
azure-pipelines.yml
generators/generator-constants.js

Update bom version to 7.5.1-SNAPSHOT

---

rfcs/3-jhipster-rfc-unambiguous-priorities.md

Unambiguous Priorities RFC

---

generators/client/templates/vue/.eslintrc.js.ejs
generators/client/templates/vue/package.json
generators/client/templates/vue/package.json.ejs

Follow https://github.com/vuejs/eslint-config-typescript#vueeslint-config-typescriptrecommended.
Closes https://github.com/jhipster/generator-jhipster/pull/17406
Closes https://github.com/jhipster/generator-jhipster/pull/17405.
---

Bump @vue/eslint-config dependencies.

---

generators/server/index.js
generators/server/templates/build.gradle.ejs
generators/server/templates/gradle/profile_prod.gradle.ejs

Removes duplicated frontend tests at ci.
---

Skip frontend test at gradle backend:unit:test.

---

generators/client/templates/common/src/main/webapp/swagger-ui/index.html.ejs

Fixes https://github.com/jhipster/generator-jhipster/issues/17489
---

Fix swagger authenticationToken prefix.

---

generators/cypress/templates/src/test/javascript/cypress/integration/account/register-page.spec.ts.ejs

Fixes https://github.com/jhipster/generator-jhipster/issues/17497
---

Fix node <16 compatibility at cypress template.

---

generators/cypress/templates/src/test/javascript/cypress/plugins/index.ts.ejs

Fixes https://github.com/jhipster/generator-jhipster/issues/17506
---

Adjust cypress coverage template.

---

test-integration/samples/ngx-default/.yo-rc.json

Enable cypress coverage at ngx-degault

---

generators/cypress/templates/src/test/javascript/cypress/plugins/index.ts.ejs

Fix cypress coverage plugin

---

generators/common/templates/.husky/pre-commit
generators/server/templates/npmw

Fixes https://github.com/jhipster/generator-jhipster/issues/17516
---

Improve npmw and switch husky to use npmw.

---

package-lock.json
package.json

Bump prettier-plugin-java version to 1.6.1

---

generators/cypress/templates/src/test/javascript/cypress/integration/account/login-page.spec.ts.ejs

Fix no database daily builds.

---

generators/client/templates/angular/webpack/webpack.custom.js.ejs
generators/client/templates/react/webpack/webpack.dev.js.ejs
generators/client/templates/vue/webpack/webpack.dev.js.ejs

[Angular] Fix: Browsersync not updating web after upgrading to 7.5.0 with Angular

---

generators/server/templates/gradle.properties.ejs

Bump up Gradle plugin dependencies

---

generators/client/templates/common/src/main/webapp/swagger-ui/index.html.ejs

Fixes https://github.com/jhipster/generator-jhipster/issues/17531
---

Improve swagger lookup.

---

generators/server/templates/src/test/java/package/TechnicalStructureTest.java.ejs

Fix TechnicalStructureTest for no database.

---

.github/actions/setup/action.yml
azure-pipelines.yml
generators/generator-constants.js

Following:
- https://github.com/jhipster/jhipster-bom/releases/tag/7.6.0
- https://repo.maven.apache.org/maven2/tech/jhipster/jhipster-parent/7.6.0/
---

Upgrade jhipster bom 7.6.0

---

generators/generator-constants.js
test/__snapshots__/docker-compose.spec.js.snap
test/__snapshots__/knative.spec.js.snap
test/__snapshots__/kubernetes.helm.spec.js.snap
test/__snapshots__/kubernetes.spec.js.snap
test/__snapshots__/openshift.spec.js.snap

Upgrade jhipster-registry to v7.2.0

---

.github/actions/setup/action.yml
azure-pipelines.yml
generators/generator-constants.js

Upgrade jhipster-dependencies to 7.6.1-SNAPSHOT

---

.github/workflows/generate-blueprint.yml

Drop sonar from generate-blueprint workflow

---

generators/server/templates/src/main/java/package/web/filter/OAuth2ReactiveRefreshTokensWebFilter.java.ejs

Maybe related to https://github.com/jhipster/generator-jhipster/issues/17384.
---

Fix oauth2 unhandled error at reactive side.

---

.github/workflows/jdl.yml
generators/cypress/templates/src/test/javascript/cypress/integration/account/settings-page.spec.ts.ejs

Try to fix 2 random failures.

---

generators/client/templates/angular/package.json.ejs

Workaround broken transitional dependency

---

.github/dependabot.yml

Merging a PR makes dependabot to rebase an unrelated PR.
Try to improve this behavior.
---

Disable dependabot rebase strategy.

---

generators/client/templates/angular/angular.json.ejs
generators/client/templates/angular/package.json
generators/client/templates/angular/package.json.ejs

Bump @angular/cli to 13.2.2

---

generators/cypress/templates/src/test/javascript/cypress/integration/account/settings-page.spec.ts.ejs

Should fix a random failure.
---

[cypress] Wait for admin email to be saved.

---

.github/workflows/generate-blueprint.yml
generators/generate-blueprint/esm.mjs
generators/generate-blueprint/files.mjs
generators/generate-blueprint/generator.mjs
generators/generate-blueprint/generator.spec.mjs
generators/generate-blueprint/index.mjs
generators/generate-blueprint/templates/.github/workflows/generator.yml.ejs
generators/generate-blueprint/templates/.mocharc.cjs.ejs
generators/generate-blueprint/templates/.prettierignore.jhi.blueprint.ejs
generators/generate-blueprint/templates/README.md.ejs
generators/generate-blueprint/templates/cli/commands.cjs.ejs
generators/generate-blueprint/templates/generators/generator/generator.mjs.jhi.ejs
generators/generate-blueprint/templates/generators/generator/generator.spec.mjs.ejs
generators/generate-blueprint/templates/generators/generator/index.mjs.ejs
generators/server/templates/couchbase/src/test/java/package/CouchbaseTestContainerExtension.java.ejs
generators/server/templates/src/main/java/package/config/LocaleConfiguration_reactive.java.ejs
generators/server/templates/src/main/java/package/security/oauth2/CustomClaimConverter.java.ejs
generators/server/templates/src/main/java/package/web/rest/LogoutResource_reactive.java.ejs
generators/server/templates/src/test/java/package/security/SecurityUtilsUnitTest_reactive.java.ejs
generators/server/templates/src/test/java/package/security/oauth2/CustomClaimConverterIT.java.ejs
generators/server/templates/src/test/java/package/web/rest/errors/ExceptionTranslatorIT_reactive.java.ejs
lib/constants/logo.cjs
test/utils/utils.mjs

Update copyright headers.

---

generators/entity-server/templates/src/main/java/package/service/criteria/EntityCriteria.java.ejs

Related to https://github.com/jhipster/generator-jhipster/issues/17776.
---

Add org.springdoc.api.annotations.ParameterObject to EntityCriteria.

---

generators/common/files.js
generators/common/index.js
generators/common/templates/.husky/pre-commit
generators/common/templates/.husky/pre-commit.ejs
generators/common/templates/README.md.jhi.ejs
generators/generator-base.js
generators/server/__snapshots__/generator.spec.mjs.snap
generators/server/files.js
generators/server/templates/npmw
test/__snapshots__/app.spec.js.snap

Local node is disabled for gradle and apple silicon, improves apple silicon support.
---

npmw: revert to global node if local is not found.

---

generators/entity-server/templates/src/main/java/package/domain/Entity.java.jhi.ejs
generators/entity-server/templates/src/main/java/package/repository/rowmapper/EntityRowMapper.java.ejs

add missing imports for UUID based relationships

---

generators/client/templates/vue/src/main/webapp/app/main.ts.ejs
generators/client/templates/vue/src/main/webapp/app/shared/config/axios-interceptor.ts.ejs
generators/client/templates/vue/src/main/webapp/app/shared/config/config.ts.ejs

Related to https://github.com/jhipster/generator-jhipster/issues/17316
---

Handle expired session at vue.

---

.github/workflows/jdl.yml
test-integration/jdl-samples/blog-store-react-jwt-consul/blog-store.jdl

Add jwt-consul microservice test.

---

generators/server/__snapshots__/generator.spec.mjs.snap
generators/server/files.js
generators/server/index.js
generators/server/templates/src/test/java/package/web/rest/UserResourceIT.java.ejs

Fixes https://github.com/jhipster/generator-jhipster/issues/17889
---

Stop generating UserResource for OAuth2

---

generators/server/templates/src/main/java/package/config/SecurityConfiguration_reactive.java.ejs

set x-frame-options header to deny in reactive stack

---

generators/server/__snapshots__/generator.spec.mjs.snap
generators/server/files.js
test/__snapshots__/app-client-custom-path.spec.js.snap
test/__snapshots__/app.spec.js.snap
test/__snapshots__/server.spec.js.snap
test/blueprint/__snapshots__/app-blueprint.spec.js.snap
test/blueprint/__snapshots__/scoped-blueprint.spec.js.snap
test/server.spec.js

Related to https://github.com/jhipster/generator-jhipster/pull/17615. 
---

Conditionally include Zipkin Docker container

---

generators/entity-server/files.js
generators/entity-server/templates/partials/it_patch_update.partial.java.ejs
generators/entity-server/templates/src/main/java/package/common/get_all_template.ejs
generators/entity-server/templates/src/main/java/package/repository/EntityRepository.java.ejs
generators/entity-server/templates/src/main/java/package/repository/EntityRepositoryInternalImpl_reactive.java.ejs
generators/entity-server/templates/src/main/java/package/repository/EntityRepositoryWithBagRelationships.java.ejs
generators/entity-server/templates/src/main/java/package/repository/EntityRepositoryWithBagRelationshipsImpl.java.ejs
generators/entity-server/templates/src/main/java/package/repository/EntityRepository_reactive.java.ejs
generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
generators/entity/index.js

Fixes https://github.com/jhipster/generator-jhipster/issues/13038
Following discussion at https://github.com/jhipster/generator-jhipster/issues/13038.
This PR implements https://vladmihalcea.com/hibernate-multiplebagfetchexception/ by adding functions to fetch `*-to-many` relationships collections.
--- …

Improve multiple bags fetch.

---

.github/workflows/generator.yml
generators/generator-constants.js
test/__snapshots__/ci-cd.spec.js.snap

Fix https://github.com/jhipster/generator-jhipster/issues/17921
---

Update Nodejs version to 16.14.0

---

generators/bootstrap/index.js
generators/entity/index.js
utils/entity.js

Fixes https://github.com/jhipster/generator-jhipster/issues/17796
---

Load entity domain at user entity.

---

generators/ci-cd/templates/github-actions.yml.ejs
test/__snapshots__/ci-cd.spec.js.snap

Using prod profile for docker container

---

generators/client/templates/angular/src/main/webapp/app/layouts/navbar/navbar.component.html.ejs
generators/entity-client/templates/react/src/test/javascript/e2e/entities/entity-update-page-object.ts.ejs
generators/entity-client/templates/vue/src/test/javascript/e2e/entities/entity-update-page-object.ts.ejs
generators/entity-client/templates/vue/src/test/javascript/e2e/entities/entity.spec.ts.ejs
test/enforcements.spec.js

Related to https://github.com/jhipster/generator-jhipster/issues/17957
---

Fix custom jhiPrefix

---

generators/server/templates/pom.xml.ejs

Fix https://github.com/jhipster/generator-jhipster/issues/17957
---

Revert maven-compiler-plugin to 3.9.0

---

test-integration/jdl-samples/ms-ngx-eureka-oauth2-mongodb-caffeine/blog-store.jdl

Switch mongodb workflow to mongodb.

---

generators/generator-constants.js
test/__snapshots__/docker-compose.spec.js.snap
test/__snapshots__/knative.spec.js.snap
test/__snapshots__/kubernetes.helm.spec.js.snap
test/__snapshots__/kubernetes.spec.js.snap
test/__snapshots__/openshift.spec.js.snap

Bump jhipster-registry to 7.3.0

---

generators/client/templates/react/package.json

Bump react-jhipster to 0.19.0

---

.github/actions/setup/action.yml
generators/generator-constants.js

Bump jhipster dependencies 7.7.0

---

generators/common/templates/README.md.jhi.ejs

- fix https://github.com/jhipster/generator-jhipster/issues/17874
It would be better to fix the https://github.com/jhipster/documentation-archive project but this patch is better than having broken links
---

Update link in generated README

---

.github/actions/setup/action.yml
generators/generator-constants.js

Use jhipster dependencies 7.7.1 snapshot

---

.github/workflows/jdl.yml
.github/workflows/vue.yml
generators/entity-server/templates/couchbase/src/main/java/package/domain/Entity.java.jhi.spring_data_couchbase.ejs
generators/entity-server/templates/couchbase/src/main/java/package/repository/EntityRepository.java.ejs
generators/entity-server/templates/src/main/java/package/repository/search/EntitySearchRepository.java.ejs
test-integration/jdl-samples/ms-vue-eureka-jwt-couchbase-hazelcast/blog-store.jdl

- Drop vue-gateway in favor of a full microservice stack.
---

Add microservice with vue and couchbase test sample

---

.github/workflows/jdl.yml
generators/entity-server/templates/couchbase/src/main/java/package/repository/EntityRepository.java.ejs
generators/entity-server/templates/src/main/java/package/common/get_all_template.ejs
generators/entity-server/templates/src/main/java/package/common/get_template.ejs
generators/entity-server/templates/src/main/java/package/repository/EntityRepository.java.ejs
generators/entity-server/templates/src/main/java/package/repository/EntityRepositoryInternalImpl_reactive.java.ejs
generators/entity-server/templates/src/main/java/package/repository/EntityRepository_reactive.java.ejs
generators/entity-server/templates/src/main/java/package/service/EntityService.java.ejs
generators/entity-server/templates/src/main/java/package/service/impl/EntityServiceImpl.java.ejs
generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs
generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
generators/entity/index.js

`relationshipsContainEagerLoad` name doesn't represent the intended purpose.
---

Add implementsEagerLoadApis variable so it's easier to track eager load apis

---

generators/entity-server/templates/couchbase/src/main/java/package/repository/EntityRepository.java.ejs
generators/server/templates/couchbase/src/main/java/package/repository/JHipsterCouchbaseRepository.java.ejs
test-integration/jdl-samples/ms-vue-eureka-jwt-couchbase-hazelcast/blog-store.jdl
test-integration/samples/.jhipster/Place.json

- Fix JOIN pagination requests.
- Use pagination in Place test entity to be sure that the bug is covered by the tests.
---

[Couchbase] Fix pagination requests for entities with relationships

---

.github/workflows/jdl.yml
generators/docker-compose/index.js
generators/server/index.js
test-integration/jdl-samples/ms-react-consul-jwt-cassandra-redis/blog-store.jdl
test/__snapshots__/docker-compose.spec.js.snap

Fixes https://github.com/jhipster/generator-jhipster/issues/17978
More than 1 application with Cassandra DB fails.
---

Switch 1 application to cassandra db at cassandra workflow

---

generators/app/index.js
generators/generator-base.js

Move from native blueprint https://github.com/jhipster/generator-jhipster-native/commit/3e2d7e75ad3e2f429be72af6ef4d7344d97f8cf6
---

Add cli option for cacheProvider and enableHibernateCache

---

generators/entity-server/templates/src/main/java/package/repository/EntityRepositoryWithBagRelationshipsImpl.java.ejs

Inject EntityManager using PersistenceContext

---

generators/entity/index.js

Fixes https://github.com/jhipster/generator-jhipster/issues/18017
---

Embedded entities don't need manual fetch.

---

.github/workflows/angular.yml
.github/workflows/react.yml
.github/workflows/vue.yml
.github/workflows/webflux.yml
test-integration/samples/vue-mongodb-kafka-cucumber/.yo-rc.json
test-integration/samples/webflux-gradle-session-mariadb-es/.yo-rc.json

Remove:
- choose between gradle or maven if duplicated (maven and gradle dependency test should be tested by microservice full stack).
- duplicate backend test if frontend features is tested by others tests.
Workflows:
- ngx-mariadb-oauth2-infinispan -> ngx-gradle-mariadb-oauth2-infinispan
- ngx-gradle-mongodb-kafka-cucumber -> ngx-mongodb-kafka-cucumber 
- ngx-gradle-mysql-es-noi18n-mapsid -> ngx-mysql-es-noi18n-mapsid
- react-maven-mysql-es-noi18n-mapsid -> react-gradle-mysql-es-noi18n-mapsid
- react-maven-cassandra-session-redis -> react-gradle-cassandra-session-redis
- react-gradle-h2mem-memcached  -> react-maven-h2mem-memcached
- vue-oauth2 -> vue-noi18n-ws-oauth2
- vue-mongodb-kafka-cucumber -> ngx-mongodb-kafka-cucumber 
- webflux-gateway-jwt -> microservice full stack with jwt
- …

Cleanup workflows.

---

generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management.tsx.ejs
generators/client/templates/react/src/main/webapp/app/modules/login/login-modal.tsx.ejs

fix eslint error no-misused-promises in react

---

generators/gradle/constants.cjs

Recommended by Gradle: https://twitter.com/gradle/status/1501641492179427337
---

Upgrade to Gradle 7.4.1

---

generators/entity-server/templates/src/main/java/package/repository/EntityRepositoryWithBagRelationshipsImpl.java.ejs

Fix 13 bugs: https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=jhipster-sample-application
---

Sonar: Call Optional isPresent()  before accessing the value

---

generators/entity-server/index.js
generators/entity-server/templates/src/main/java/package/repository/EntityRepositoryInternalImpl_reactive.java.ejs

Related to https://github.com/jhipster/generator-jhipster/pull/17837.
---

Calculate joinColumnNames derived property.

---

.github/workflows/auto-merge.yml

Implement auto-merge workflow

---

.github/workflows/angular.yml
.github/workflows/devserver.yml
.github/workflows/generate-blueprint.yml
.github/workflows/jdl.yml
.github/workflows/react.yml
.github/workflows/vue.yml
.github/workflows/webflux.yml
generators/server/index.js
generators/workspaces/index.js

Make docker logs always available at workflows.

---

.github/actions/build-matrix/action.yml
.github/workflows/angular.yml
.github/workflows/react.yml
.github/workflows/vue.yml
test-integration/workflow-samples/angular.json
test-integration/workflow-samples/react.json
test-integration/workflow-samples/vue.json

Allow jhipster-bom project to auto pick samples changes.
---

Move workflow samples to external files

---

generators/maven/templates/.mvn/wrapper/maven-wrapper.properties
generators/maven/templates/pom.xml.jhi.ejs
generators/server/templates/.mvn/wrapper/maven-wrapper.properties
generators/server/templates/pom.xml.ejs

Update maven version to 3.8.5

---

.github/dependabot.yml

Set dependabot rebase-strategy to auto

---

.github/actions/build-matrix/action.yml
.github/workflows/angular.yml
.github/workflows/devserver.yml
.github/workflows/react.yml
.github/workflows/vue.yml

Export workflow-(angular/react/vue) output at build-matrix and replace workflow conditions with task condition.
---

More adjusts to workflows.

---

generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs

Motivated by https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter. 
---

Spring Security without the WebSecurityConfigurerAdapter

---

.github/workflows/angular.yml
.github/workflows/devserver.yml
.github/workflows/generators.yml
.github/workflows/react.yml
.github/workflows/vue.yml

Related to https://github.com/jhipster/generator-jhipster/pull/18180#issuecomment-1076328671
---

Fail required checks instead of skipping.

---

generators/server/templates/build.gradle.ejs

Spring Spring EL in Queries

---

.github/actions/setup/action.yml
generators/generator-constants.js
generators/server/templates/src/test/java/package/web/rest/PublicUserResourceIT.java.ejs
generators/server/templates/src/test/java/package/web/rest/UserResourceIT.java.ejs

Update spring-boot version to 2.6.5

---

generators/server/needle-api/needle-server-gradle.js
generators/server/templates/settings.gradle.ejs

This PR add two additional needles to add a plugin/repository to gradle plugin management block.
See https://github.com/jhipster/generator-jhipster-native/pull/25
---

add additional gradle needles

---

generators/generator-base.js

This PR exposes the before added additional gradle needles to the base generator to use.
---

expose additional gradle needles to base generator

---

generators/entity-i18n/templates/i18n/entity_fr.json.ejs

Fix a typo in french

---

.github/actions/build-matrix/action.yml
test-integration/scripts/99-build-changes.sh

Related to https://github.com/jhipster/jhipster-bom/pull/727#issuecomment-1082214766
---

Improve build-matrix action

---

generators/gradle/constants.cjs
test-integration/scripts/99-build-changes.sh

Recommended by Gradle: https://twitter.com/gradle/status/1509562973630697479?s=21
---

Upgrade to Gradle 7.4.2

---

generators/generator-constants.js

Depends on https://github.com/jhipster/jhipster-bom/pull/730
---

Update spring-boot version to 2.6.6

---

generators/client/templates/angular/src/main/webapp/app/admin/user-management/list/user-management.component.ts.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.ts.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.ts.ejs

Fix:
- https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=jhipster-sample-application&open=AX_heYYo_nqaxBDha7f0
- https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=jhipster-sample-application&open=AX_heYYe_nqaxBDha7fz
- https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=jhipster-sample-application&open=AX_heYZW_nqaxBDha7f3
- https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=jhipster-sample-application&open=AX_heYZf_nqaxBDha7f4
- ...
---
When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you …

[Angular] Sonar: Rename it to _index to make intention explicit

---

generators/generator-constants.js
generators/server/templates/gradle.properties.ejs
generators/server/templates/pom.xml.ejs

Update some dependencies

---

generators/client/templates/angular/src/main/webapp/app/core/util/parse-links.service.ts.ejs

Fix:
- https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AX_heYlQ_nqaxBDha7g1
- https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AX_heYlQ_nqaxBDha7g2
---

[Angular] Sonar: Rename unused parameter

---

generators/client/templates/react/package.json

Bump react-jhipster to 0.20.0

---

.github/actions/setup/action.yml
generators/generator-constants.js

Bump jhipster dependencies 7.8.0

---

.github/actions/setup/action.yml
generators/generator-constants.js

Use jhipster dependencies 7.8.1 snapshot

---

generators/maven/templates/.mvn/wrapper/maven-wrapper.properties
generators/maven/templates/pom.xml.jhi.ejs
generators/server/templates/.mvn/wrapper/maven-wrapper.properties
generators/server/templates/pom.xml.ejs

Reverts jhipster/generator-jhipster#18165

Revert "Revert "Update maven version to 3.8.5""

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md

Add note about security policy in ISSUE_TEMPLATE

---

.github/actions/setup/action.yml
generators/generator-constants.js

Bump jhipster-bom version to 7.8.1

---

generators/server/templates/src/main/docker/jib/entrypoint.sh.ejs

Allow env vars to be populated by secret files

---

generators/generate-blueprint/constants.mjs
generators/generate-blueprint/generator.mjs
generators/generate-blueprint/templates/cli/commands.cjs.ejs
generators/generate-blueprint/templates/generators/generator/generator.mjs.jhi.ejs
generators/generate-blueprint/templates/generators/generator/generator.spec.mjs.ejs
generators/generator-base-private.js
generators/project-name/index.cjs
test-integration/generate-blueprint-samples/default/.yo-rc.json

Related to https://github.com/jhipster/generator-jhipster/issues/18304.
---

Add support to generate custom generators at generate-blueprint (replaces modules)

---

.github/actions/setup/action.yml
generators/generator-constants.js
generators/server/templates/gradle.properties.ejs
generators/server/templates/pom.xml.ejs

depends on https://github.com/jhipster/jhipster-bom/pull/768
---

Update spring-boot version to 2.6.7 and other dependencies

---

generators/common/templates/README.md.jhi.ejs

Fix typo in generated readme

---

generators/server/templates/build.gradle.ejs

add correct springdoc dependency version depending on reactive/webmvc

---

generators/server/templates/build.gradle.ejs
generators/server/templates/gradle/profile_dev.gradle.ejs

move h2 deps to dev profile for gradle

---

generators/database-changelog-liquibase/templates/src/main/resources/config/liquibase/changelog/updated_entity_constraints.xml.ejs

fix for https://github.com/jhipster/generator-jhipster/issues/18484
---

fix for unique constraint incremental changelog

---

generators/server/templates/gradle.properties.ejs
generators/server/templates/pom.xml.ejs

Update jaxb-runtime version to 2.3.6

---

.github/actions/build-matrix/action.yml
.github/workflows/generator.yml
.github/workflows/lock-maintenance.yml
generators/generate-blueprint/templates/.github/workflows/generator.yml.ejs
generators/generator-constants.js
test/__snapshots__/ci-cd.spec.js.snap

Update node version to 16.15.0

---

.github/actions/build-matrix/action.yml
.github/workflows/generator.yml
.github/workflows/lock-maintenance.yml
generators/azure-app-service/templates/github/workflows/azure-app-service.yml.ejs
generators/azure-spring-cloud/templates/github/workflows/azure-spring-cloud.yml.ejs
generators/generate-blueprint/templates/.github/workflows/generator.yml.ejs
generators/generator-constants.js
test/__snapshots__/ci-cd.spec.js.snap

Update GitHub Actions to version 3

---

generators/server/templates/src/test/java/package/security/DomainUserDetailsServiceIT.java.ejs
generators/server/templates/src/test/java/package/service/UserServiceIT.java.ejs
generators/server/templates/src/test/java/package/service/mapper/UserMapperTest.java.ejs
generators/server/templates/src/test/java/package/web/rest/AccountResourceIT.java.ejs
generators/server/templates/src/test/java/package/web/rest/UserResourceIT.java.ejs

Use randomAlphanumeric instead of random for password in tests codes

---

generators/generate-blueprint/__snapshots__/generator.spec.mjs.snap
generators/generate-blueprint/generator.mjs
generators/generate-blueprint/templates/.github/workflows/generator.yml.ejs
generators/generator-base-blueprint.js

- Disable husky by default for blueprints. (doesn't work correctly)
- Add permission to workflow
- Fix _isPriorityMissing.
- Others tweaks.
---

Improvements to generate-blueprint

---

generators/statistics.js

Make sure insight is not called at mocha using parallel tests and add some checks

---

generators/client/templates/angular/package.json
generators/cypress/templates/src/test/javascript/cypress/support/navbar.ts.ejs

Force menu click at angular

---

generators/cypress/templates/cypress.json.ejs

Fixes https://github.com/jhipster/generator-jhipster/issues/18536.
---

Set cypress downloads and videos folders.

---

generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.html.ejs

Fixes https://github.com/jhipster/generator-jhipster/issues/18525.
---

Fix relationship reference at microfrontends.

---

generators/kubernetes/templates/db/couchbase.yml.ejs
generators/kubernetes/templates/db/mongodb.yml.ejs
generators/kubernetes/templates/registry/consul.yml.ejs
generators/kubernetes/templates/registry/jhipster-registry.yml.ejs
generators/openshift/templates/registry/consul.yml.ejs
generators/openshift/templates/registry/jhipster-registry.yml.ejs
test/__snapshots__/knative.spec.js.snap
test/__snapshots__/kubernetes.helm.spec.js.snap
test/__snapshots__/kubernetes.spec.js.snap
test/__snapshots__/openshift.spec.js.snap

Use publishNotReadyAddresses: true for Kubernetes

---

generators/client/templates/vue/src/main/webapp/app/admin/metrics/metrics.vue.ejs
generators/client/templates/vue/src/main/webapp/app/core/jhi-navbar/jhi-navbar.component.ts.ejs
generators/client/templates/vue/src/main/webapp/app/shared/date/filters.ts.ejs

fix admin menu not being shown until after a navigation

---

generators/server/templates/src/main/java/package/config/SecurityConfiguration_reactive.java.ejs

fix: Correctly configure cors in reactive applications

---

.github/actions/compare-base/action.yml
test-integration/jdl-samples/ms-ngx-eureka-oauth2-mongodb-caffeine/blog-store.jdl

Closes https://github.com/jhipster/generator-jhipster/issues/18746
---

Switch microservice test to MongoDB

---

.github/dependabot.yml
generators/generator-base.js
generators/server/__snapshots__/needles.spec.mjs.snap
generators/server/esm.mjs
generators/server/needles.cjs
generators/server/needles.spec.mjs
generators/server/templates/src/main/java/package/config/ApplicationProperties.java.ejs
generators/utils.js
lib/support/needles.cjs
lib/support/needles.spec.mjs
package-lock.json
package.json

Implement a new base for needles with tests. This will allow to replace some methods from `generators/utils.js`.
Implement ApplicationProperties needle.
Improve utils jsdoc.
Related to https://github.com/jhipster/generator-jhipster/issues/18652.
Closes https://github.com/jhipster/generator-jhipster/issues/17838.
---

Implement a new base for needles and add ApplicationProperties needle.

---

generators/server/__snapshots__/needles.spec.mjs.snap
generators/server/needles.spec.mjs

Updates snapshots

---

generators/heroku/index.js
generators/heroku/templates/application-heroku.yml.ejs
generators/heroku/templates/heroku.gradle.ejs
generators/heroku/templates/pom-profile.xml.ejs
test/__snapshots__/heroku.spec.js.snap

enforce compatible es version when deploying to heroku

---

generators/spring-controller/index.js
test/blueprint/spring-controller-blueprint.spec.js
test/spring-controller.spec.js

spring-controller subgenerator to load derived serverConfig

---

generators/generator-base.js

chore: Support prettier transformation of svelte files

---

generators/generator-base.js

fix: cleanup .yo-rc.json entities config

---

generators/server/templates/pom.xml.ejs

Update maven-failsafe-plugin and maven-surefire-plugin version to 3.0.0-M7

---

test-integration/jdl-samples/ms-mf-react-eureka-oauth2-mariadb-infinispan/blog-store.jdl

Test if https://github.com/jhipster/generator-jhipster/issues/18745 still applies.
---

enable mariadb+reactive test samples.

---

generators/app/prompts.js
generators/generator-defaults.js

Closes https://github.com/jhipster/generator-jhipster/issues/17031
---

add prompt support to microfrontend/microfrontends

---

generators/client/transform-react.cjs
generators/client/transform-react.spec.mjs
generators/entity-client/templates/react/src/main/webapp/app/entities/react_validators.ejs
test-integration/workflow-samples/react.json

Try to fix https://github.com/hipster-labs/jhipster-daily-builds/runs/6824231096?check_suite_focus=true
related to https://github.com/jhipster/generator-jhipster/issues/18652
---

fix transform react for interpolate + string

---

generators/client/files-vue.js
generators/client/index.js
generators/client/transform-vue.cjs
generators/client/transform-vue.spec.mjs
generators/entity-client/files-vue.cjs
generators/entity-client/files.js
generators/entity-client/index.js
generators/utils.js

Related to https://github.com/jhipster/generator-jhipster/issues/18652
---

convert vue to writeFiles/transform

---

generators/entity-server/templates/src/main/java/package/repository/search/EntitySearchRepository.java.ejs

Fix https://github.com/jhipster/generator-jhipster/issues/18191
---

Fix pagination for elasticsearch

---

generators/server/templates/pom.xml.ejs

Update maven-enforcer-plugin version to 3.1.0

---

generators/client/templates/react/src/main/webapp/app/entities/menu.tsx.ejs
generators/client/templates/react/src/main/webapp/app/shared/error/error-loading.tsx.ejs
generators/client/templates/react/src/main/webapp/app/shared/layout/menus/entities.tsx.ejs
generators/client/templates/react/src/main/webapp/app/typings.d.ts.ejs

This PR improves some types. I noticed that they are suboptimal while working on #18654.
---

Improve typing related to entities menu and routes

---

generators/server/templates/gradle.properties.ejs
generators/server/templates/pom.xml.ejs

Update mapstruct version to 1.5.2.Final

---

rfcs/5-jhipster-rfc-inclusive-property-in-generator.md

added RFC on inclusive properties

---

generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.html.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.spec.ts.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.ts.ejs

Cleanup some few templates, mostly by indent
---

indent angular forms templates

---

generators/server/templates/src/main/resources/config/liquibase/master.xml.ejs

fix https://github.com/jhipster/generator-jhipster/pull/18513#issuecomment-1160219003
---

adjust h2 clobType

---

generators/server/templates/pom.xml.ejs

fix jacoco plugin (and sonar)

---

.github/actions/build-matrix/action.yml

Always execute frontend, backend and sonar at merge.
---

don't skip steps at merge

---

generators/server/templates/src/main/resources/config/liquibase/master.xml.ejs

Another fix for daily builds.
---

adjust uuidType for h2 with mariadb and mysql

---

.github/workflows/generator.yml
generators/generator-constants.js
test/__snapshots__/ci-cd.spec.js.snap

Update nodejs version to 16.15.1

---

.github/dependabot.yml

Allow dependabot update of bootstrap v5 version for angular

---

generators/server/templates/src/main/java/package/security/oauth2/CustomClaimConverter.java.ejs

Remove redundant check on RequestContextHolder#getRequestAttributes

---

generators/entity-client/templates/angular/src/main/webapp/app/entities/entity.model.ts.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/route/entity-management-routing-resolve.service.spec.ts.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/service/entity.service.spec.ts.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.spec.ts.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.ts.ejs

Typescript classes can change object behavior, the generated class don't change the behavior, only set the object defaults.
Object defaults should be set at form.
It’s simpler to use typed plain objects.
Related to https://github.com/jhipster/generator-jhipster/issues/18817 and https://github.com/jhipster/generator-jhipster/pull/18586.
---

angular: don't generate typescript class.

---

generators/client/templates/react/src/main/webapp/app/modules/administration/administration.reducer.ts.ejs
test/__snapshots__/app.spec.js.snap
test/app.spec.js

fix for issue #19039
---
- [ X] Tests are added where necessary
- [ X] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

syntax error fix for react administration.reducer

---

generators/cypress/templates/src/test/javascript/cypress/tsconfig.json.ejs
generators/entity-client/files.js
generators/entity-client/index.js
generators/entity-client/templates/cypress/src/test/javascript/cypress/e2e/entity/entity.cy.ts.ejs
generators/generator-base-private.js
utils/field.js

- add cypress test for edit existing entity
- add enumFileName property
- set cypress target at compilerOptions
- fix cypress lint warning
---

cypress and enum adjusts

---

generators/entity-client/files-angular.cjs
generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-form.service.spec.ts.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-form.service.ts.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.spec.ts.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.ts.ejs

Closes https://github.com/jhipster/generator-jhipster/issues/10198
---

angular: implement formService

---

cli/environment-builder.js
cli/import-jdl.js
cli/jhipster-command.js
generators/bootstrap/index.js
generators/docker-utils.js
generators/entity-server/cleanup.js
generators/generator-base-blueprint.js
generators/generator-base-private.js
generators/generator-base.js
generators/java/index.cjs
generators/project-name/index.cjs
jdl/exporters/applications/jhipster-application-formatter.js
jdl/validators/jdl-with-application-validator.js
jdl/validators/jdl-without-application-validator.js
lib/support/needles.cjs
lib/support/shared-data.cjs
utils/blueprint.js

Update/Correct method parameter documentation
---

💡 update/correct method parameter documentation

---

generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs

Related to https://github.com/jhipster/generator-jhipster/pull/19184
---

change frameOptions to sameOrigin

---

generators/entity-server/templates/src/main/java/package/repository/EntityRepositoryWithBagRelationships.java.ejs

Related to https://github.com/jhipster/generator-jhipster/pull/19183
---

another fix for bag relationships with @EntityPackage

---

.github/actions/setup/action.yml
generators/entity-server/templates/src/main/java/package/domain/Entity.java.jhi.spring_data_cassandra.ejs
generators/generator-constants.js

Depends on https://github.com/jhipster/jhipster-bom/pull/902
---

Update spring-boot version to 2.7.2

---

generators/database-changelog-liquibase/files.js

fix csv file with incremental-changelog and recreate flag.

---

generators/entity/index.js
utils/relationship.js

Fixes for specific use cases.
---

fix no database and unidirectional relationships

---

generators/entity-server/files.js

Prepare for modularization.
---

split entity-server files

---

generators/generator-base.js
test/__snapshots__/server.spec.js.snap

An undefined response is considered non existent and ignored instead of a negative response.
---

fix: resolveCallback should not resolve to undefined.

---

generators/app/index.js
generators/cypress/files.js
generators/cypress/index.js
generators/cypress/templates/src/test/javascript/cypress/plugins/index.ts.ejs
generators/cypress/templates/src/test/javascript/cypress/support/commands.ts.ejs
generators/generator-base.js

Fixes https://github.com/jhipster/generator-jhipster/issues/19265
---

make cypress-audit optional (disable with --no-cypress-audit)

---

generators/entity-server/templates/src/main/java/package/common/get_all_template.ejs
generators/entity-server/templates/src/main/java/package/service/EntityQueryService.java.ejs

Error example:
https://sonarcloud.io/project/issues?resolved=false&types=VULNERABILITY&id=jhipster-sample-application&open=AXk8Ulf6mxD5nLr49ZDa
Error description and workaround:
https://sonarcloud.io/organizations/jhipster/rules?open=javasecurity%3AS5145&rule_key=javasecurity%3AS5145
```
Noncompliant Code Example
protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws IOException {
String param1 = req.getParameter("param1");
Logger.info("Param1: " + param1 + " " + Logger.getName()); // Noncompliant
// ...
}
Compliant Solution
protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws IOException {
String param1 = req.getParameter("param1");
// Replace pattern-breaking characters
param1 = param1.replaceAll("[\n\r\t]", "_");
Logger.info("Param1: " + …
```

fix sonar vulnerabilities

---

.github/workflows/generator.yml
generators/generator-constants.js
test/__snapshots__/ci-cd.spec.js.snap

Update nodejs version to 16.16.0

---

.github/actions/setup/action.yml
generators/generator-constants.js

Update bom version to 7.9.0

---

.github/release-drafter.yml

Related with https://github.com/jhipster/generator-jhipster/issues/18319
---

Exclude labels 'theme: dependencies' in release drafter

---

.github/dependabot.yml
.github/release-drafter.yml

Relates to https://github.com/jhipster/generator-jhipster/issues/18319
---

Fine-tune release-drafter configuration

---

generators/common/templates/README.md.jhi.ejs

Update link to documentation archive in template

---

utils/field.js

fix: replace invalid chars at fake data

---

test-integration/samples/.jhipster/FieldTestEntity.json
test/templates/reproducible/.jhipster/Foo.json

adjust sample regex.

---

test-integration/samples/.jhipster/FieldTestEntity.json

fix another test-integration sample

---

generators/client/templates/react/src/main/webapp/app/index.tsx.ejs

React 18: https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis
Related to #19308 
---

[React] Switch to createroot

---

generators/client/templates/vue/package.json

Reverts jhipster/generator-jhipster#19212

Revert "chore(deps): bump vue from 2.7.5 to 2.7.8 in /generators/client/templates/vue"

---

generators/sql-constants.js
test/generator-base.spec.js
test/templates/compose/11-mssql/src/main/docker/app.yml

Generated application now works in development with MS SqlServer container

---

generators/server/templates/src/test/java/package/config/JHipsterBlockHoundIntegration.java.ejs
generators/server/templates/src/test/java/package/config/TestContainersSpringContextCustomizerFactory.java.ejs

Fix mssqlserver reactive integration tests

---

generators/client/files-vue.js
generators/client/templates/vue/src/test/javascript/spec/app/shared/config/formatter.spec.ts.ejs
generators/client/templates/vue/src/test/javascript/spec/app/shared/sort/sorts.spec.ts.ejs
test/client/__snapshots__/vue.spec.js.snap

[Vue] Increase Vue code coverage

---

generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.html.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.ts.ejs

fix infinite scroll not load next page data

---

generators/client/templates/angular/src/main/webapp/app/admin/user-management/update/user-management-update.component.ts.ejs
generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management.model.ts.ejs
generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management.route.ts.ejs

Fixes https://github.com/jhipster/generator-jhipster/issues/19369.
---

[angular] fix user insertion.

---

generators/server/__snapshots__/generator.spec.mjs.snap
generators/server/__snapshots__/needles.spec.mjs.snap
generators/server/files.js
generators/server/templates/.npmrc.ejs
test/__snapshots__/app-client-custom-path.spec.js.snap
test/__snapshots__/app.spec.js.snap
test/__snapshots__/server.spec.js.snap
test/blueprint/__snapshots__/app-blueprint.spec.js.snap
test/blueprint/__snapshots__/scoped-blueprint.spec.js.snap

Reverts jhipster/generator-jhipster#18936
Fixes https://github.com/jhipster/generator-jhipster/issues/19360
Fixes https://github.com/jhipster/generator-jhipster/issues/19350
Fixes https://github.com/jhipster/generator-jhipster/issues/19225.

Revert "add .npmrc to force npm to use bash."

---

generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-form.service.ts.ejs

checked the templates for vue and react, it seems like everything is ok, could not find any obvious error.
closes #19304
---

correct entity template to use fieldname correctly

---

.github/actions/setup/action.yml
generators/generator-constants.js

Update BOM version to 7.9.3-SNAPSHOT

---

generators/entity/index.js

related to https://github.com/jhipster/generator-jhipster/issues/19399
---

Fix Microservices with neo4j

---

generators/client/templates/angular/webpack/webpack.microfrontend.js.ejs
generators/server/templates/src/main/docker/app.yml.ejs
test-integration/jdl-samples/ms-mf-ngx-consul-oauth2-neo4j/blog-store.jdl
test-integration/workflow-samples/angular.json

Fix https://github.com/jhipster/generator-jhipster/issues/19342.
---

fix(angular): entities should not be exposed by microfrontends

---

generators/entity-client/templates/angular/src/main/webapp/app/entities/service/entity.service.ts.ejs
generators/server/templates/src/main/java/package/web/rest/UserResource.java.ejs

UserResource is not generated for oauth2.
Fix elastic search url for microfrontends.
---

cleanup UserResource and fix elasticsearch url for microfrontends

---

generators/entity-server/templates/src/main/java/package/common/delete_template.ejs
generators/entity-server/templates/src/main/java/package/service/EntityService.java.ejs
generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
generators/server/templates/src/main/java/package/config/SecurityConfiguration_reactive.java.ejs
generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs

improve templates formatting

---

generators/client/templates/vue/webpack/webpack.common.js.ejs
generators/client/templates/vue/webpack/webpack.dev.js.ejs

fix vue cache invalidation for at dev profile

---

.github/actions/setup/action.yml
generators/generator-constants.js
generators/server/templates/gradle.properties.ejs
generators/server/templates/pom.xml.ejs

Fix https://github.com/jhipster/generator-jhipster/issues/19464
---

Update spring-boot version to 2.7.3 and other dependencies

---

.github/workflows/angular.yml
.github/workflows/react.yml
.github/workflows/vue.yml

adjust workflow timeout

---

.github/workflows/generator.yml
generators/generator-constants.js
test/__snapshots__/ci-cd.spec.js.snap

Update node version to 16.17.0

---

jdl/jhipster/binary-options.js
jdl/jhipster/entity-options.js
jdl/jhipster/search-engine-types.js
test/jdl/grammar/grammar.spec.js
test/jdl/jhipster/binary-options.spec.js

Fixes https://github.com/jhipster/generator-jhipster/issues/19149
---

allow jdl search option with no value.

---

.github/workflows/angular.yml
.github/workflows/react.yml
.github/workflows/vue.yml

increase workflow task timeout

---

generators/client/templates/vue/src/test/javascript/jest.conf.js.ejs

Fixes https://github.com/jhipster/generator-jhipster/issues/19504.
---

workaround tough-cookie breaking change

---

.gitattributes
.github/dependabot.yml
generators/app/index.js
generators/bootstrap/index.js
generators/generator-base.js
generators/utils.js
lib/support/base.cjs
package-lock.json
package.json
test/utils.spec.js

Fixes https://github.com/jhipster/generator-jhipster/issues/19461
Fixes https://github.com/jhipster/generator-jhipster/issues/17115
---

add option to detect and normalize line endings.

---

.github/workflows/angular.yml
.github/workflows/cache.yml
.github/workflows/react.yml
.github/workflows/vue.yml
generators/bootstrap/index.js

Increase workflow timeout, improve cache workflow and fix lf/crlf condition

---

generators/entity-server/templates/src/main/java/package/domain/Entity.java.jhi.ejs
generators/entity-server/templates/src/main/java/package/service/EntityQueryService.java.ejs
generators/entity-server/templates/src/main/java/package/service/criteria/EntityCriteria.java.ejs
generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
generators/entity/index.js
generators/generator-base-entities.cjs
generators/generator-base.js
generators/server/templates/src/main/java/package/domain/AbstractAuditingEntity.java.ejs
utils/field.js

This is a series of adjust to improve blueprint customizations.
Related to https://github.com/jhipster/generator-jhipster/issues/18471.
---

Misc improvements

---

generators/client/templates/angular/src/main/webapp/app/core/util/data-util.service.ts.ejs
generators/client/templates/angular/src/main/webapp/app/core/util/parse-links.service.ts.ejs

Ignore Security hot spots as identified by Sonar

---

generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.ts.ejs

Fix https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYLgOFmOWE-guYVzrIc-
---

[Angular] Sonar: Remove this unused import of 'filter'

---

generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.ts.ejs

Fix https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYLgOFmOWE-guYVzrIc_
---

[Angular] Sonar: Remove this unused import of 'ITEM_DELETED_EVENT'

---

generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.ts.ejs

Fix https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYLgOFYqWE-guYVzrIcx 
---

[Angular] Sonar: Remove this unused import of 'PAGE_HEADER'

---

generators/client/templates/vue/package.json
generators/entity-client/templates/vue/src/main/webapp/app/entities/entity.component.ts.ejs

[Vue] Typescript 4.8.2

---

generators/client/templates/react/package.json

Bump react-jhipster 0.22.0

---

.github/actions/setup/action.yml
generators/generator-constants.js

Bump jhipster-bom to 7.9.3

---

.github/actions/setup/action.yml
generators/generator-constants.js

Bump to jhipster-bom 7.9.4-SNAPSHOT

---

package.json

Fix https://github.com/jhipster/generator-jhipster/issues/18588
---

Bump node dependency to 16 lts

---

.github/workflows/angular.yml
.github/workflows/generator-database-changelog-liquibase.yml
.github/workflows/react.yml
.github/workflows/vue.yml
generators/client/templates/common/README.md.jhi.client.ejs
generators/common/templates/README.md.jhi.ejs
generators/docker-compose/index.js
generators/docker-compose/templates/README-DOCKER-COMPOSE.md.ejs
generators/info/index.js
generators/server/index.js
generators/server/templates/src/main/resources/static/microservices_index.html.ejs
generators/workspaces/index.js
test-integration/scripts/24-tests-e2e.sh
test-integration/scripts/25-sonar-analyze.sh
test/__snapshots__/docker-compose.spec.js.snap

Related to https://github.com/jhipster/generator-jhipster/issues/19462.
---

switch from docker-compose to docker compose

---

generators/generator-constants.js

Update liquibase version to 4.16.0

---

generators/client/templates/react/src/main/webapp/app/shared/layout/menus/account.tsx.ejs

[React] Profile menus labels are not updated after login using react

---

generators/server/templates/src/main/docker/app.yml.ejs

Related to https://github.com/jhipster/generator-jhipster-ionic/pull/712#issuecomment-1236377397
---

increase sleep time for monolith oauth2

---

generators/client/templates/react/package.json
generators/client/templates/react/src/main/webapp/app/modules/login/login-redirect.tsx.ejs
generators/client/templates/react/src/main/webapp/app/modules/login/login.tsx.ejs

[React] Bump react-router-dom from 6.3.0 to 6.4.0

---

generators/generator-constants.js
test/__snapshots__/docker-compose.spec.js.snap
test/__snapshots__/knative.spec.js.snap
test/__snapshots__/kubernetes.helm.spec.js.snap
test/__snapshots__/kubernetes.spec.js.snap
test/__snapshots__/openshift.spec.js.snap

Update jhipster-registry version to 7.4.0

Update jhipster-registry version to 7.4.0

---

generators/entity-i18n/files.js
generators/entity-i18n/index.js

Related to https://github.com/jhipster/generator-jhipster/issues/19111
---

stop using generator as data at entity-i18n generator

---

generators/client/files-angular.js
generators/client/files-common.js
generators/client/files-react.js
generators/client/files-vue.js
generators/client/index.js
generators/client/needle-api/needle-client-webpack.js
generators/client/templates/angular/webpack/webpack.custom.js.ejs
generators/client/templates/react/webpack/webpack.dev.js.ejs
generators/client/templates/vue/webpack/webpack.common.js.ejs
generators/client/templates/vue/webpack/webpack.dev.js.ejs
generators/client/transform-angular.cjs
generators/client/transform-angular.spec.mjs
generators/client/transform-react.cjs
generators/client/transform-react.spec.mjs
generators/client/transform-vue.cjs
generators/client/transform-vue.spec.mjs
generators/entity-client/files-angular.cjs
generators/entity-client/files-react.cjs
generators/entity-client/files-vue.cjs
generators/entity-client/files.js
generators/generator-base.js

Related to https://github.com/jhipster/generator-jhipster/issues/19111 
---

Stop using generator as template data at client generator.

---

generators/client/needle-api/needle-client-i18n.js
generators/entity-client/files-angular.cjs
generators/entity-client/files-cypress.cjs
generators/entity-client/files-react.cjs
generators/entity-client/files-vue.cjs
generators/entity-client/files.js
generators/entity-client/index.js
generators/entity-client/index.mjs
generators/entity-client/templates/cypress/src/test/javascript/cypress/e2e/entity/entity.cy.ts.ejs
generators/entity/index.js
generators/generator-base.js

Includes https://github.com/jhipster/generator-jhipster/pull/19817
Related to https://github.com/jhipster/generator-jhipster/issues/19111.
---

Stop using generator as template data at entity-client generator

---

utils/liquibase.js

word error fixed, improved readability in formatDateForChangelog method.

---

generators/base/generator-base-blueprint.cjs

Remove using blueprint info.

---

package-lock.json
package.json
watch.mjs

We are using typescript and the source needs to be build.
This allows to build source files on demand.
---

improve watch script

---

generators/server/templates/src/main/java/package/web/rest/ClientForwardController.java.ejs
generators/server/templates/src/main/resources/config/application.yml.ejs
generators/server/templates/src/test/java/package/web/rest/ClientForwardControllerTest.java.ejs
generators/server/templates/src/test/resources/config/application.yml.ejs

polish ClientForwardController

---

generators/server/files-sql.js

export sql files

---

README.md

From https://snyk.io/advisor/npm-package/generator-jhipster

Add package health badge

---

generators/cypress/files.js

Dynamic PATH is causing problem for dotnet blueprint https://github.com/jhipster/jhipster-dotnetcore/pull/1103.
---

cypress template path should be constant

---

package-lock.json
package.json

Related to https://github.com/jhipster/generator-jhipster/issues/19627.
---

bump yeoman-environment to 3.12.0

---

package-lock.json
package.json

Should fix dependabot for chevrotain package https://github.com/jhipster/generator-jhipster/pull/20209.
---

drop @chevrotain/types direct dependency

---

.github/actions/compare/action.yml
generators/common/generator.mjs
generators/git/generator.mts
generators/git/options.mjs
generators/init/generator.mjs
generators/init/generator.spec.mts
generators/workspaces/generator.mjs
generators/workspaces/templates/.gitignore.ejs

Related to https://github.com/jhipster/generator-jhipster/pull/20243.
---

workspaces: use .gitignore from git generator

---

generators/server/templates/entity/src/main/java/package/domain/Entity.java.jhi.jakarta_persistence.ejs

sb3: set relationships as lazy load.

---

generators/server/files.mjs
generators/server/templates/src/test/java/package/security/jwt/AuthenticationIntegrationTest.java.ejs
generators/server/templates/src/test/java/package/security/jwt/JwtAuthenticationTestUtils.java.ejs
generators/server/templates/src/test/java/package/security/jwt/TestAuthenticationResource.java.ejs

sb3: fix jwt integration tests at microservices

---

generators/app/__snapshots__/generator.spec.mts.snap
generators/base/generator-base-private.mjs
generators/bootstrap-application-base/generator.mts
generators/ci-cd/__snapshots__/ci-cd.spec.mts.snap
generators/ci-cd/generator.mjs
generators/ci-cd/templates/azure-pipelines.yml.ejs
generators/ci-cd/templates/github-actions.yml.ejs
generators/ci-cd/templates/travis.yml.ejs
generators/client/templates/angular/package.json.ejs
generators/client/templates/react/package.json.ejs
generators/openapi-client/files.mjs
generators/server/files.mjs
generators/server/generator.mjs
generators/server/templates/build.gradle.ejs
generators/server/templates/gradle/docker.gradle.ejs
generators/server/templates/package.json.ejs
generators/server/templates/pom.xml.ejs
generators/vue/templates/package.json.ejs

Replace constants with variables

---

generators/server/templates/src/test/java/package/config/TestContainersSpringContextCustomizerFactory.java.ejs

Prevent OutOfMemory error in integration tests

---

generators/liquibase/templates/src/main/resources/config/liquibase/master.xml.ejs
generators/server/templates/src/main/java/package/config/SecurityConfiguration_reactive.java.ejs

sb3: fix sql reactive workflows.

---

generators/server/__snapshots__/cassandra.spec.mts.snap
generators/server/__snapshots__/couchbase.spec.mts.snap
generators/server/__snapshots__/elasticsearch.spec.mts.snap
generators/server/__snapshots__/mongodb.spec.mts.snap
generators/server/__snapshots__/neo4j.spec.mts.snap
generators/server/__snapshots__/sql.spec.mts.snap
generators/server/files.mjs
generators/server/templates/src/main/java/package/config/neo4j/Neo4jMigrations.java.ejs
generators/server/templates/src/test/java/package/config/JHipsterBlockHoundIntegration.java.ejs

See https://github.com/jhipster/generator-jhipster/pull/19791#issuecomment-1316049812. 
---

Fix PublicUserResourceIT#getAllPublicUsers() for WebFlux + Neo4j

---

generators/server/templates/src/main/java/package/web/rest/errors/ExceptionTranslator.java.ejs
generators/server/templates/src/test/java/package/web/rest/PublicUserResourceIT.java.ejs

Found when debugging `PublicUserResourceIT`.
---

Minor fixes in ExceptionTranslator

---

package.json

Fix watch npm script in Windows

---

generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs
generators/docker/templates/src/main/docker/config/realm-config/jhipster-realm.json.ejs
generators/server/templates/Dockerfile

Upgrade Keycloak to v20 and realm configurations

---

jdl/chevrotain.d.ts
package-lock.json
package.json
tsconfig.json

Fixed at https://github.com/Chevrotain/chevrotain/pull/1881.
---

drop chevrotain types copy

---

generators/docker/__snapshots__/generator.spec.mts.snap
generators/docker/files.mjs
generators/docker/generator.mjs
lib/index.mjs
test/jdl/converters/json-to-jdl-converter.spec.ts
test/jdl/exporters/jhipster-application-exporter.spec.ts
test/jdl/exporters/jhipster-deployment-exporter.spec.ts
test/jdl/exporters/jhipster-entity-exporter.spec.ts
test/jdl/utils/files-utils.spec.ts
test/utils/utils.cjs

Try to fix:
- microservice + oauth2 daily builds.
- windows daily builds.
Fix:
- test warnings.
---

Misc fixes.

---

generators/docker-compose/generator.mjs
generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs
generators/docker/generator.mjs
generators/docker/templates/src/main/docker/config/realm-config/jhipster-realm.json.ejs

fix: Replace asterisk with UUID and conditional inject internal client

---

generators/server/templates/Dockerfile

Update cassandra docker image version to 3.11.14

---

generators/server/templates/src/main/resources/config/application.yml.ejs

sb3: disable health check for neo4j + reactive

---

test-integration/scripts/99-print-matrix.js

add support to disable samples

---

test-integration/workflow-samples/angular.json
test-integration/workflow-samples/vue.json

disable couchbase samples

---

test-integration/workflow-samples/react.json
test-integration/workflow-samples/vue.json

disable cassandra samples

---

.github/actions/setup/action.yml
generators/generator-constants.cjs

Depends on https://github.com/jhipster/jhipster-bom/pull/1101. 
---

Upgrade to Spring Cloud 2022.0.0

---

test-integration/jdl-samples/ms-ng-eureka-oauth2-mongodb-caffeine/blog-store.jdl
test-integration/samples/ng-mongodb-kafka-cucumber/.yo-rc.json
test-integration/samples/vue-mongodb-kafka-cucumber/.yo-rc.json
test-integration/samples/webflux-mysql-kafka/.yo-rc.json

disable kafka tests.

---

.github/workflows/angular.yml
.github/workflows/generator-generate-blueprint.yml
.github/workflows/react.yml
.github/workflows/vue.yml
test-integration/jdl-samples/ms-ng-eureka-oauth2-mongodb-caffeine/blog-store.jdl
test-integration/scripts/99-print-matrix.js
test-integration/workflow-samples/angular.json

Some background: https://github.com/jhipster/generator-jhipster/pull/19791#issuecomment-1329016181
---

Disable mongodb webflux backend tests

---

.github/actions/setup/action.yml
generators/generator-constants.cjs

Needs https://github.com/jhipster/jhipster-bom/pull/1104
---

Update spring-boot version to 3.0.1

---

generators/common/templates/README.md.jhi.ejs

Fix typo in gatling documentation

---

generators/server/templates/pom.xml.ejs

Related with https://github.com/jhipster/jhipster-bom/pull/1111
---

Extend mysql dependency management to new Maven identifiers

---

generators/server/templates/build.gradle.ejs
generators/server/templates/gradle.properties.ejs
generators/server/templates/pom.xml.ejs

Migrate to liquibase-hibernate6

---

generators/app/generator.mjs
generators/base/api.d.mts
generators/base/generator-base-private.mjs
generators/base/generator.mts
generators/server/generator.mjs
generators/server/prompts.mjs
generators/server/support/checks/check-java.mjs
generators/server/support/checks/check-java.spec.mjs
generators/server/support/checks/index.mjs
package-lock.json
package.json

Move checkJava to server generator

---

.github/FUNDING.yml
.github/dependabot.yml
.github/labeler.yml
.github/release-drafter.yml
.github/workflows/angular.yml
.github/workflows/auto-merge.yml
.github/workflows/cache.yml
.github/workflows/depsreview.yml
.github/workflows/devserver.yml
.github/workflows/docker-image-publish-github-registry.yml
.github/workflows/generator-database-changelog-liquibase.yml
.github/workflows/generator-generate-blueprint.yml
.github/workflows/generator.yml
.github/workflows/generators.yml
.github/workflows/gradle-wrapper-validation.yml
.github/workflows/label-cleanup.yml
.github/workflows/labeler.yml
.github/workflows/lock-maintenance.yml
.github/workflows/react.yml
.github/workflows/release-drafter.yml
.github/workflows/triage.yml
.github/workflows/vue.yml

Update copyright header for workflows

---

.github/workflows/copyright-update.yml

Add new script to update year

---

generators/client/generator.mjs
jdl/jhipster/default-application-options.ts

increment devServerPort based on applicationIndex

---

.eslintignore
.gitignore
.prettierignore
.vscode/launch.json
.vscode/settings.json
generators/base-docker/utils.spec.mts

Improve developer experience: add vscode mocha explorer configuration.

---

generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs
test-integration/workflow-samples/vue.json

fix spring-boot 3 session authentication

---

generators/elasticsearch/templates/src/main/java/package/repository/search/UserSearchRepository.java.ejs
generators/elasticsearch/templates/src/main/java/package/repository/search/_EntityClass_SearchRepository.java.ejs
generators/server/templates/entity/src/main/java/package/common/delete_template.ejs
generators/server/templates/entity/src/main/java/package/common/patch_template.ejs
generators/server/templates/src/main/java/package/service/UserService.java.ejs
generators/server/templates/src/test/java/package/service/UserServiceIT.java.ejs

Avoids failures when infrastructure (elasticsearch) is having performance problems.
Also fixes an issue with user updates not being saved to (SQL) database when a user already exists.
---
Fix #20548 
Fix #19267

Perform write calls to elasticsearch async & save user updates into database 

---

README.md

Remove Octo Consulting from Gold sponsors [ci skip]

---

generators/cypress/templates/cypress.config.ts.ejs

Option is not experimental anymore.
---

drop experimentalSessionAndOrigin

---

.github/dependabot.yml
generators/angular/generator.spec.mts
generators/languages/entity-files.mjs
package-lock.json
package.json

Workaround https://github.com/jhipster/generator-jhipster/issues/20782.
---

revert prettier to 2.8.1

---

.github/dependabot.yml

fix dependabot ignore prettier

---

generators/base-docker/docker-base.mjs
generators/base/generator-base.mjs
generators/base/support/config.mts
generators/base/support/config.spec.mts
generators/entity/generator.mjs

Improves PR method names and variability
---

split deepCleanup into two methods, use more meaninful names

---

generators/base/generator-base.mjs
test/generator-base.spec.mts
utils/db.mjs

Fix https://github.com/jhipster/generator-jhipster/issues/18584
---

Review join table and constraints name limits

---

generators/angular/templates/src/main/webapp/app/admin/user-management/update/user-management-update.component.ts.ejs

https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYVQENtr9mTDbKDoDzmJ

Sonar: angular/forms import is duplicated

---

generators/server/templates/src/main/java/package/web/rest/errors/ExceptionTranslator.java.ejs

- https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYT5NJzcoub84d7atcP3&tab=code
- https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYT5NJzcoub84d7atcQE
- https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYT5NJzcoub84d7atcPr
- https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYT5NJzcoub84d7atcQB
- https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYT5NJzcoub84d7atcQC
---
When you are still working on the PR, consider converting it to Draft (below …

Sonar: ExceptionTranslator

---

generators/couchbase/templates/src/main/java/package/repository/JHipsterCouchbaseRepository.java.ejs
generators/elasticsearch/templates/src/main/java/package/repository/search/_EntityClass_SearchRepository.java.ejs
generators/server/templates/entity/src/main/java/package/common/get_all_stream_template.ejs
generators/server/templates/entity/src/main/java/package/common/get_filtered_template.ejs
generators/server/templates/entity/src/main/java/package/common/search_stream_template.ejs
generators/server/templates/src/main/java/package/security/oauth2/CustomClaimConverter.java.ejs
generators/server/templates/src/main/java/package/service/UserService.java.ejs
generators/server/templates/src/main/java/package/service/mapper/UserMapper.java.ejs
generators/server/templates/src/main/java/package/web/rest/PublicUserResource.java.ejs
generators/server/templates/src/test/java/package/web/rest/PublicUserResourceIT.java.ejs

Fix all https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYT5NJ47oub84d7atcQN
---

Sonar: Replace this usage of 'Stream.collect(Collectors.toList())' with 'Stream.toList()'

---

generators/languages/templates/entity/i18n/entity_tr.json.ejs
generators/languages/templates/src/main/resources/i18n/messages_tr.properties.ejs
generators/languages/templates/src/main/webapp/i18n/tr/configuration.json
generators/languages/templates/src/main/webapp/i18n/tr/error.json
generators/languages/templates/src/main/webapp/i18n/tr/gateway.json
generators/languages/templates/src/main/webapp/i18n/tr/global.json.ejs
generators/languages/templates/src/main/webapp/i18n/tr/home.json
generators/languages/templates/src/main/webapp/i18n/tr/logs.json
generators/languages/templates/src/main/webapp/i18n/tr/user-management.json
generators/languages/templates/src/test/resources/i18n/messages_tr.properties.ejs

Fixed some Turkish language typos and added new updates.
---

Fixed some Turkish language typos and added new updates.

---

generators/common/__snapshots__/generator.spec.mjs.snap
generators/common/templates/package.json

Bump lint-staged from 13.0.3 to 13.1.0

---

generators/vue/templates/package.json
generators/vue/templates/webpack/webpack.common.js.ejs

[Vue] Bump axios from 0.27.2 to 1.2.3

---

generators/react/templates/package.json
generators/react/templates/webpack/webpack.common.js.ejs

[React] Bump axios from 0.27.2 to 1.2.3

---

generators/generator-constants.mjs

Update spring-boot version to 3.0.2

---

generators/base/support/configuration-helpers/enum.mjs
generators/base/support/configuration-helpers/options.mjs
generators/base/support/configuration-helpers/sequences.mjs
generators/base/support/index.mjs
generators/base/support/templates/doc-formatters.mjs

cleanup https://github.com/jhipster/generator-jhipster/pull/20286.
---

remove unused methods

---

generators/server/templates/src/main/java/package/web/rest/errors/ExceptionTranslator.java.ejs

Fix 4 bugs
https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=jhipster-sample-application
---

Sonar: Bugs

---

generators/server/templates/src/main/java/package/web/rest/errors/ExceptionTranslator.java.ejs
generators/server/templates/src/test/java/package/security/jwt/TokenAuthenticationIT.java.ejs
generators/server/templates/src/test/java/package/security/jwt/TokenAuthenticationSecurityMetersIT.java.ejs

Fix:
- https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYT5NJzcoub84d7atcP1
- https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYT5NJzcoub84d7atcP7
- https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYT5NJzcoub84d7atcP8
- https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYT5NJqmoub84d7atcPZ&tab=why
- https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYT5NJrBoub84d7atcPd
---
When you are still working on the PR, consider converting it to Draft …

Sonar code smells

---

generators/bootstrap-application-server/generator.mts
generators/liquibase-changelogs/generator.mjs
generators/liquibase/support/index.mts
generators/liquibase/support/prepare-field.mjs

move utils/liquibase to generators/liquibase/support/prepare-field

---

generators/server/templates/src/main/java/package/web/filter/SpaWebFilter.java.ejs
generators/server/templates/src/main/java/package/web/filter/SpaWebFilter_reactive.java.ejs
generators/server/templates/src/test/java/package/web/filter/SpaWebFilterIT.java.ejs

Related to https://github.com/jhipster/generator-jhipster/pull/20107#issuecomment-1414109437
---

adjusts to SpaWebFilter.

---

generators/angular/templates/src/main/webapp/app/admin/logs/logs.component.html.ejs
generators/angular/templates/src/main/webapp/app/admin/logs/logs.component.spec.ts.ejs
generators/angular/templates/src/main/webapp/app/admin/logs/logs.component.ts.ejs
generators/angular/templates/src/main/webapp/app/admin/logs/logs.service.ts.ejs

This adds the ability to set the logger level of the microservices.
---

Add microservices to admin log view

---

.github/workflows/docker-image-publish-github-registry.yml

Reverts jhipster/generator-jhipster#21022

Revert "Bump docker/build-push-action from 3.3.0 to 4.0.0"

---

generators/common/__snapshots__/generator.spec.mjs.snap
generators/common/templates/README.md.jhi.ejs
generators/docker/templates/src/main/docker/sonar.yml.ejs
package-lock.json

Fix #20773
Fixed config and usage instructions for local sonar setup and code coverage
---
Signed-off-by: Pratik Raj <rajpratik71@gmail.com>

chore: fix config and usage instructions for local sonar setup and code coverage

---

generators/base-application/support/prepare-entity.mts
generators/base/support/faker.mts
generators/base/support/index.mts
generators/bootstrap-application-base/generator.mts
generators/cypress/generator.mts
generators/docker-compose/generator.mjs
generators/docker/generator.mjs

Due to new parallelism, microservices generated fake data is not guaranteed to be reproducible.
We should not use provided faker instance to avoid non reproducible fake data.
---

don't use global faker instance.

---

generators/bootstrap/generator.mts
test/__snapshots__/openapi-client.spec.mts.snap

not needed anymore since fork is dropped.
related to https://github.com/jhipster/generator-jhipster/issues/21080
---

don't load manually written config file to mem-fs

---

.github/dependabot.yml

drop ignored dependencies from dependabot.

---

generators/languages/support/detect-language.mts
generators/statistics.mts
package-lock.json
package.json

bump os-locale to 6.0.2

---

cli/environment-builder.mjs
cli/program.mjs
generators/app/__snapshots__/generator.spec.mts.snap
generators/app/command.mts
generators/app/generator.mjs
generators/app/generator.spec.mts
generators/app/index.mts
generators/base-docker/generator.mjs
generators/base/api.d.mts
generators/base/generator-base-blueprint.mts
generators/base/generator-base-todo.mjs
generators/base/generator-base.mts
generators/bootstrap-application-server/generator.mts
generators/bootstrap/generator.mts
generators/client/command.mts
generators/client/generator.mjs
generators/client/index.mts
generators/common/command.mts
generators/common/generator.mjs
generators/common/index.mts
generators/entities/generator.mjs
generators/init/__snapshots__/generator.spec.mts.snap
generators/server/command.mts
generators/server/generator.mjs
generators/server/index.mts
generators/server/prompts.mjs
generators/upgrade/generator.mjs

related to https://github.com/jhipster/generator-jhipster/issues/21080
---

convert options to new format

---

generators/bootstrap/command.mts
generators/bootstrap/generator.mts

Improves commit performance
Related to https://github.com/jhipster/generator-jhipster/issues/21080.
---

filter stream before transform

---

generators/angular/entity-files-angular.mts
generators/angular/files-angular.mjs
generators/angular/generator.mts
generators/angular/support/index.mts
generators/angular/support/translate-angular.mjs
generators/angular/support/translate-angular.spec.mts
generators/react/entity-files-react.mjs
generators/react/files-react.mjs
generators/react/generator.mjs
generators/react/support/index.mts
generators/react/support/translate-react.mjs
generators/react/support/translate-react.spec.mjs
generators/vue/entity-files-vue.mjs
generators/vue/files-vue.mjs
generators/vue/generator.mjs
generators/vue/support/index.mts
generators/vue/support/translate-vue.mjs
generators/vue/support/translate-vue.spec.mjs

Translation will apply to
- needles.
- blueprint files.
---

Apply translations and i18n removal at transforms.

---

generators/common/__snapshots__/generator.spec.mjs.snap
generators/common/templates/package.json

Bump lint-staged from 13.1.1 to 13.1.2

---

generators/server/templates/gradle/profile_dev.gradle.ejs
generators/server/templates/gradle/profile_prod.gradle.ejs

Related with https://github.com/jhipster/jhipster-bom/pull/1111
---

Extend mysql dependency management to new Maven identifier

---

generators/docker/templates/src/main/docker/jhipster-registry.yml.ejs

Fix search locations for JHipster Registry in Docker

---

.github/dependabot.yml
package-lock.json
package.json
tsconfig.json

add node to types

---

generators/base/generator-base.mts
generators/openapi-client/__snapshots__/openapi-client.spec.mts.snap

when deleting files, delete from memory fs too.

---

.github/dependabot.yml

fix dependabot yml

---

test-integration/jdl-samples/ms-mf-ng-consul-oauth2-neo4j/blog-store.jdl
test-integration/scripts/12-generate-sample.js

Fixes https://github.com/jhipster/generator-jhipster/issues/18744.
---

enable neo4j+gateway at test sample.

---

generators/project-name/generator.mjs

Related to https://github.com/jhipster/generator-jhipster/issues/21463.
Fixes https://github.com/jhipster/generator-jhipster/issues/21462.
---

fix existing project detection on multiples project-name composing

---

generators/java/support/generated-annotation-transform.mts
generators/java/support/generated-annotation-transform.spec.mts

Related to https://github.com/jhipster/generator-jhipster/issues/21463.
Fixes https://github.com/jhipster/generator-jhipster/issues/20432.
---

add @GeneratedByJHipster to @inteface.

---

generators/react/templates/src/main/webapp/app/entities/_entityFolder/_entityFile.tsx.ejs
generators/react/templates/src/main/webapp/app/modules/administration/user-management/user-management.tsx.ejs

[react] change sort icons for entity

---

generators/cassandra/__snapshots__/generator.spec.mts.snap
generators/cassandra/cleanup.mjs
generators/cassandra/files.mjs
generators/cassandra/generator.mjs
generators/cassandra/templates/src/test/java/package/CassandraKeyspaceIT.java.ejs
generators/cassandra/templates/src/test/java/package/config/CassandraTestContainer.java.ejs
generators/cassandra/templates/src/test/java/package/config/CassandraTestContainersSpringContextCustomizerFactory.java.ejs
generators/server/templates/build.gradle.ejs
generators/server/templates/pom.xml.ejs
generators/server/templates/src/test/java/package/config/TestContainersSpringContextCustomizerFactory.java.ejs
test-integration/jdl-samples/ms-react-consul-jwt-cassandra-redis/blog-store.jdl

- drop cassandra-unit
- enable cassandra with reactive test.
closes https://github.com/jhipster/generator-jhipster/pull/19662.
closes https://github.com/jhipster/jhipster-bom/pull/967.
related to https://github.com/jhipster/generator-jhipster/issues/18747.
---

fix cassandra with reactive.

---

generators/languages/generator.mjs
generators/server/generator.mjs

related to https://github.com/jhipster/generator-jhipster/issues/21558.
---

migrate indonesian language.

---

cli/environment-builder.spec.mts
jdl/converters/json-to-jdl-converter.ts
test/jdl/converters/json-to-jdl-converter.spec.ts
test/jdl/exporters/export-utils.spec.ts
test/jdl/exporters/jdl-exporter.spec.ts
test/jdl/exporters/jhipster-deployment-exporter.spec.ts
test/jdl/exporters/jhipster-entity-exporter.spec.ts
test/jdl/integration/test.spec.ts
test/jdl/linter/jdl-linter.spec.ts
test/jdl/readers/file-reader.spec.ts
test/jdl/readers/jdl-reader.spec.ts

fixes some random failures and prepare for https://github.com/jhipster/generator-jhipster/issues/21555
---

[jdl] use temporary dir at jdl tests.

---

generators/base/generator-base.mts
generators/languages/generator.mjs
generators/languages/generator.spec.mjs

https://github.com/jhipster/generator-jhipster/pull/21560 was not enough to migrate languages.
Related to https://github.com/jhipster/generator-jhipster/issues/21558.
---

fix language migration

---

generators/server/templates/pom.xml.ejs

drop eureka pre release repository

---

.github/workflows/cache.yml

add actions/setup-java to cache workflow

---

generators/server/templates/pom.xml.ejs
generators/spring-cache/templates/gradle/cache.gradle.ejs

switch ehcache to jakarta classifier

---

generators/server/templates/build.gradle.ejs
generators/server/templates/pom.xml.ejs

drop bucket4j dependency

---

.github/workflows/cache.yml
test-integration/scripts/11-generate-config.sh
test-integration/scripts/11-generate-entities.sh

Cache workflow still failing.
---

additional fixes to cache workflow

---

generators/server/templates/pom.xml.ejs

use spring-boot 3 at open-api

---

.github/actions/setup/action.yml
test-integration/scripts/01-configure-azure.sh

drop useOldISOCodes option

---

generators/maven/__snapshots__/needles.spec.mts.snap
generators/maven/generator.mts
generators/maven/needles.spec.mts
generators/maven/support/pom-store.mts
generators/maven/types.d.mts

- add support to array.
- fix properties with dots
---

Improve maven needles

---

generators/cassandra/generator.mjs
generators/couchbase/generator.mjs
generators/elasticsearch/generator.mjs
generators/kafka/generator.mts
generators/maven/types.d.mts
generators/mongodb/generator.mjs
generators/neo4j/generator.mts
generators/pulsar/generator.mts
generators/server/templates/pom.xml.ejs
generators/spring-cache/generator.mts
generators/sql/generator.mts

modularize pom.xml

---

generators/cucumber/generator.mts
generators/gatling/generator.mts
generators/mongodb/generator.mjs
generators/pulsar/generator.mts
generators/server/templates/pom.xml.ejs
generators/spring-websocket/generator.mts

Modularize more pom dependencies

---

generators/liquibase/files.mts
generators/liquibase/generator.mts
generators/liquibase/support/maven-plugin.mts
generators/liquibase/templates/gradle/liquibase.gradle.ejs
generators/server/templates/build.gradle.ejs
generators/server/templates/gradle.properties.ejs
generators/server/templates/gradle/profile_dev.gradle.ejs
generators/server/templates/gradle/profile_prod.gradle.ejs
generators/server/templates/pom.xml.ejs
generators/server/templates/settings.gradle.ejs
generators/server/templates/src/main/java/package/Application.java.ejs
generators/server/templates/src/main/resources/config/application-dev.yml.ejs
generators/server/templates/src/main/resources/config/application-prod.yml.ejs
generators/server/templates/src/main/resources/config/application.yml.ejs
generators/server/templates/src/main/resources/logback-spring.xml.ejs
generators/server/templates/src/test/resources/config/application.yml.ejs
generators/server/templates/src/test/resources/logback.xml.ejs

- modularize almost every liquibase customization except application_xx.yml, a couple of pom customization and main class.
Related to https://github.com/jhipster/generator-jhipster/pull/17956.
---

rework liquibase generator

---

generators/sql/internal/dependencies.mts

Fixes https://github.com/jhipster/generator-jhipster/issues/21701
---

generate testcontainer test dependency in main dependencies.

---

generators/vue/templates/webpack/config.js.ejs

Fix default version in DEV for Vue.js

---

generators/server/templates/build.gradle.ejs
generators/server/templates/pom.xml.ejs

drop unnecessary exclusion

---

generators/common/templates/package.json
generators/upgrade/generator.mjs
package-lock.json
package.json

Fixes https://github.com/jhipster/generator-jhipster/issues/21138
---

use npm exec jhipster for npm 9

---

generators/common/templates/package.json
generators/upgrade/generator.mjs
generators/upgrade/upgrade.spec.mts

use local jhipster to test upgrade command and bump husky

---

.github/workflows/cache.yml

Allows to replace a broken cache
---

don’t restore cache at build cache workflow.

---

generators/liquibase/templates/gradle/liquibase.gradle.ejs
generators/server/templates/gradle/libs.versions.toml

Fixes the error from https://github.com/jhipster/generator-jhipster/pull/21510
---

Bumps org.liquibase.gradle from 2.1.1 to 2.2.0.

---

generators/docker/templates/src/main/docker/app.yml.ejs
generators/elasticsearch/__snapshots__/generator.spec.mts.snap
generators/liquibase/files.mts
generators/liquibase/generator.mts
generators/liquibase/templates/gradle/liquibase.gradle.ejs
generators/liquibase/templates/src/main/java/package/config/LiquibaseConfiguration.java.ejs
generators/liquibase/templates/src/main/resources/config/liquibase/changelog/initial_schema_neo4j.xml.ejs
generators/liquibase/templates/src/main/resources/config/liquibase/changelog/initial_schema_sql.xml.ejs
generators/liquibase/templates/src/main/resources/config/liquibase/master.xml.ejs
generators/neo4j/__snapshots__/generator.spec.mts.snap
generators/neo4j/cleanup.mts
generators/neo4j/files.mts
generators/neo4j/generator.mts
generators/neo4j/templates/src/test/java/package/config/Neo4jTestContainersSpringContextCustomizerFactory.java.ejs
generators/server/files.mjs
generators/server/generator.mjs
generators/server/jdl/application-definition.mts
generators/server/options/database-migration.mts
generators/server/options/database-migration.spec.ts
generators/server/options/message-broker.spec.ts
generators/server/templates/build.gradle.ejs
generators/server/templates/src/main/java/package/domain/User.java.ejs
generators/server/templates/src/main/resources/config/application-dev.yml.ejs
generators/server/templates/src/main/resources/config/application-prod.yml.ejs
generators/server/templates/src/main/resources/config/application.yml.ejs
generators/server/templates/src/test/java/package/config/JHipsterBlockHoundIntegration.java.ejs
generators/server/templates/src/test/java/package/config/TestContainersSpringContextCustomizerFactory.java.ejs
generators/server/templates/src/test/resources/config/application.yml.ejs
test-integration/jdl-samples/ms-mf-ng-consul-oauth2-neo4j/blog-store.jdl

This PR does not remove neo4j-migration. It adds liquibase as alternative.
Closes https://github.com/jhipster/generator-jhipster/pull/17956.
---

add liquibase support to neo4j.

---

.vscode/launch.json
generators/server/templates/entity/src/main/java/package/common/get_all_stream_template.ejs
generators/server/templates/entity/src/main/java/package/common/get_filtered_template.ejs
test-integration/scripts/lib/get-workflow-samples.js
test-integration/workflow-samples/daily-neo4j.json

Related to https://github.com/jhipster/generator-jhipster/issues/21558
---

fix daily-builds webflux-neo4j sample

---

generators/server/templates/src/main/java/package/domain/User.java.ejs
generators/sql/__snapshots__/generator.spec.mts.snap
generators/sql/__snapshots__/sql-entities.spec.mts.snap
generators/sql/entity-files.mjs

Fixes daily builds ms + oauth2 workflow.
Related to https://github.com/jhipster/generator-jhipster/issues/21558
---

implement persistable interface at User if needed

---

generators/java/support/package-info-transform.mts

fix package name on windows

---

generators/server/generator.mjs

Fix npm install command on Windows

---

generators/vue/__snapshots__/generator.spec.mts.snap
generators/vue/files-vue.mjs
generators/vue/templates/src/main/webapp/app/entities/_entityFolder/_entityFile-update.component.ts.ejs
generators/vue/templates/src/test/javascript/jest.conf.js.ejs
generators/vue/templates/src/test/javascript/spec/app/entities/_entityFolder/_entityFile-update.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/shared/config/axios-interceptor.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/setup.js.ejs

Fix bug introduced at https://github.com/jhipster/generator-jhipster/pull/21852
---

Fix vue test calling jhipster site at tests.

---

generators/angular/templates/src/main/webapp/app/entities/_entityFolder/list/_entityFile.component.ts.ejs

Fixes https://github.com/jhipster/generator-jhipster/issues/21894
---

fix page refresh with infinite scroll

---

generators/vue/templates/package.json
generators/vue/templates/package.json.ejs
generators/vue/templates/src/main/webapp/app/account/change-password/change-password.component.ts.ejs
generators/vue/templates/src/main/webapp/app/account/change-password/change-password.vue.ejs
generators/vue/templates/src/main/webapp/app/account/register/register.component.ts.ejs
generators/vue/templates/src/main/webapp/app/account/register/register.vue.ejs
generators/vue/templates/src/main/webapp/app/account/reset-password/finish/reset-password-finish.component.ts.ejs
generators/vue/templates/src/main/webapp/app/account/reset-password/finish/reset-password-finish.vue.ejs
generators/vue/templates/src/main/webapp/app/account/reset-password/init/reset-password-init.component.ts.ejs
generators/vue/templates/src/main/webapp/app/account/reset-password/init/reset-password-init.vue.ejs
generators/vue/templates/src/main/webapp/app/account/settings/settings.component.ts.ejs
generators/vue/templates/src/main/webapp/app/account/settings/settings.vue.ejs
generators/vue/templates/src/main/webapp/app/admin/user-management/user-management-edit.component.ts.ejs
generators/vue/templates/src/main/webapp/app/admin/user-management/user-management-edit.vue.ejs
generators/vue/templates/src/main/webapp/app/entities/_entityFolder/_entityFile-update.component.ts.ejs
generators/vue/templates/src/main/webapp/app/entities/_entityFolder/_entityFile-update.vue.ejs
generators/vue/templates/src/main/webapp/app/shared/config/config.ts.ejs
generators/vue/templates/webpack/webpack.common.js.ejs
generators/vue/templates/webpack/webpack.microfrontend.js.jhi.vue.ejs

Related to https://github.com/jhipster/generator-jhipster/issues/12558.
---

Migrate to vuelidate v2

---

generators/vue/templates/src/main/webapp/app/admin/user-management/user-management-edit.component.ts.ejs
generators/vue/templates/src/main/webapp/app/admin/user-management/user-management-view.component.ts.ejs
generators/vue/templates/src/main/webapp/app/admin/user-management/user-management.service.ts.ejs

user-management uses the login(string) to edit users

---

generators/vue/templates/src/main/webapp/app/account/login-form/login-form.component.ts.ejs
test-integration/samples/vue-default/.yo-rc.json

fix token name

---

generators/languages/translation-data.mjs
generators/vue/generator.mjs
generators/vue/generator.spec.mts
generators/vue/support/translate-vue.mts
generators/vue/support/translate-vue.spec.mts
generators/vue/templates/src/main/webapp/app/account/sessions/sessions.vue.ejs
generators/vue/templates/src/main/webapp/app/entities/_entityFolder/_entityFile-update.vue.ejs
test/support/helpers.mts

Closes https://github.com/jhipster/generator-jhipster/issues/18743
---

translate vue applications

---

generators/vue/__snapshots__/generator.spec.mts.snap
generators/vue/files-vue.mjs
generators/vue/templates/src/main/webapp/app/entities/_entityFolder/_entityFile-update.component.ts.ejs
generators/vue/templates/src/main/webapp/app/entities/_entityFolder/_entityFile-update.vue.ejs
generators/vue/templates/src/main/webapp/app/entities/_entityFolder/_entityFile.component.ts.ejs
generators/vue/templates/src/main/webapp/app/shared/composables/index.ts.ejs
generators/vue/templates/src/main/webapp/app/shared/composables/validation.ts.ejs

- validate with composition api provides a better type inference.
Related to https://github.com/jhipster/generator-jhipster/issues/12558.
---

rework vue validation at entities

---

generators/vue/templates/src/test/javascript/spec/app/account/activate/activate.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/account/change-password/change-password.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/account/login-form/login-form.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/account/register/register.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/account/reset-password/finish/reset-password-finish.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/account/reset-password/init/reset-password-init.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/account/sessions/sessions.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/account/settings/settings.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/admin/configuration/configuration.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/admin/gateway/gateway.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/admin/health/health-modal.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/admin/health/health.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/admin/logs/logs.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/admin/metrics/metrics-modal.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/admin/metrics/metrics.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/admin/tracker/tracker.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/admin/tracker/tracker.service.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/admin/user-management/user-management-edit.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/admin/user-management/user-management-view.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/admin/user-management/user-management.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/core/error/error.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/core/home/home.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/core/jhi-navbar/jhi-navbar.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/core/ribbon/ribbon.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/entities/_entityFolder/_entityFile-details.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/entities/_entityFolder/_entityFile-update.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/entities/_entityFolder/_entityFile.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/entities/entities-menu.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/setup.js.ejs

- use mount utility stubs.
- move i18n to tests setup.
Related to https://github.com/jhipster/generator-jhipster/issues/12558.
---

Vue tests adjusts.

---

generators/cypress/templates/cypress-audits.config.ts.ejs
generators/cypress/templates/cypress.config.ts.ejs

Enable cypress experimentalRunAllSpecs

---

test-integration/jdl-samples/ms-react-consul-jwt-cassandra-redis/blog-store.jdl

Disable failures due to transitive dependencies.
Unlock merges.
---

disable gradle + cassandra sample

---

generators/jdl/generator.mts

Related to https://github.com/jhipster/generator-jhipster/issues/21990#issuecomment-1543892148.
---

don't run npm at monorepository childs

---

generators/docker-compose/generator.mjs
generators/docker/__snapshots__/generator.spec.mts.snap
generators/docker/templates/src/main/docker/app.yml.ejs

Related to https://github.com/jhipster/generator-jhipster/issues/21990
---

Remove basename from app.yml urls and re-add at docker-compose

---

cli/download.mts

use v{major} as jdl sample repository

---

test-integration/samples/webflux-gradle-session-h2mem-es/.yo-rc.json

Broken due to transitional dependency.
---

disable enableSwaggerCodegen at gradle sample

---

generators/angular/templates/src/main/webapp/app/entities/_entityFolder/service/_entityFile.service.spec.ts.ejs
generators/angular/templates/src/main/webapp/app/entities/_entityFolder/service/_entityFile.service.ts.ejs
generators/elasticsearch/__snapshots__/generator.spec.mts.snap
generators/elasticsearch/files.mjs
generators/elasticsearch/templates/src/main/java/package/web/rest/errors/ElasticsearchExceptionMapper.java.ejs
generators/elasticsearch/templates/src/main/java/package/web/rest/errors/QuerySyntaxException.java.ejs
generators/elasticsearch/templates/src/main/java/package/web/web/rest/errors/ElasticsearchExceptionMapper.java.ejs
generators/elasticsearch/templates/src/main/java/package/web/web/rest/errors/QuerySyntaxException.java.ejs
generators/elasticsearch/templates/src/test/java/package/web/rest/errors/ElasticsearchExceptionMapperTest.java.ejs
generators/languages/templates/src/main/webapp/i18n/de/global.json.ejs
generators/languages/templates/src/main/webapp/i18n/en/global.json.ejs
generators/server/templates/entity/src/main/java/package/common/search_stream_template.ejs
generators/server/templates/entity/src/main/java/package/common/search_template.ejs
generators/server/templates/entity/src/main/java/package/web/rest/_EntityClass_Resource.java.ejs

angular/elasticsearch: exception handling for queries, handle exceptions caused by syntax errors in queries
Fix #21699
---

angular/elasticsearch: exception handling for queries

---

generators/elasticsearch/templates/src/main/java/package/domain/_PersistClass_.java.jhi.elastic_search.ejs

[elasticsearch] Type conflicts with dynamic field mapping

---

package-lock.json
package.json

bump yeoman dependencies

---

generators/app/generator.mjs
generators/base-application/generator.mts
generators/base/generator-base-todo.mts
generators/base/generator-base-todo.spec.mts
generators/base/generator-base.mts
package-lock.json
package.json

- removes a missing `this.async()`
Closes https://github.com/jhipster/generator-jhipster/issues/22132
Related to https://github.com/jhipster/generator-jhipster/issues/21959
---

update some apis.

---

.github/actions/compare-base/action.yml
.github/workflows/angular.yml
bin/jhipster.cjs
generators/app/__snapshots__/generator.spec.mts.snap
generators/git/command.mts
generators/git/generator.mts
generators/info/generator.mts
generators/jdl/__snapshots__/generator.spec.mts.snap
generators/workspaces/command.mts
generators/workspaces/generator.mjs
test-integration/scripts/99-build-changes.sh

- try to fix workspaces workflow always changing.
- print workspaces applications at jhipster info.
---

git adjusts

---

generators/base/generator-base-blueprint.mts
generators/base/generator-base-todo.mts
package-lock.json
package.json

bump yeoman dependencies.

---

generators/languages/translation-data.mjs
generators/vue/support/translate-vue.mts
generators/vue/templates/src/main/webapp/app/account/activate/activate.component.ts.ejs
generators/vue/templates/src/main/webapp/app/account/login-form/login-form.component.ts.ejs
generators/vue/templates/src/main/webapp/app/admin/user-management/user-management-edit.component.ts.ejs
generators/vue/templates/src/main/webapp/app/admin/user-management/user-management-view.component.ts.ejs
generators/vue/templates/src/main/webapp/app/admin/user-management/user-management.component.ts.ejs
generators/vue/templates/src/main/webapp/app/entities/_entityFolder/_entityFile-details.component.ts.ejs
generators/vue/templates/src/main/webapp/app/entities/_entityFolder/_entityFile-update.component.ts.ejs
generators/vue/templates/src/main/webapp/app/entities/_entityFolder/_entityFile.component.ts.ejs
generators/vue/templates/src/main/webapp/app/main.ts.ejs
generators/vue/templates/src/main/webapp/app/shared/alert/alert.service.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/account/activate/activate.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/account/login-form/login-form.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/admin/tracker/tracker.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/admin/tracker/tracker.service.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/admin/user-management/user-management-edit.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/admin/user-management/user-management-view.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/admin/user-management/user-management.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/core/error/error.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/core/jhi-navbar/jhi-navbar.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/entities/_entityFolder/_entityFile-details.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/entities/_entityFolder/_entityFile-update.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/entities/_entityFolder/_entityFile.component.spec.ts.ejs
generators/vue/templates/src/test/javascript/spec/app/shared/alert/alert.service.spec.ts.ejs

Related to https://github.com/jhipster/generator-jhipster/issues/12558
---

Vue router and alert improvements.

---

generators/base-application/support/prepare-entity.mts
jdl/__test-files__/jhipster_app/.jhipster/Country.json
jdl/__test-files__/relationship_built_in_entity.jdl
jdl/converters/jdl-to-json/jdl-to-json-relationship-converter.ts
jdl/converters/jdl-to-json/jdl-with-applications-to-json-converter.spec.ts
jdl/converters/jdl-to-json/jdl-without-application-to-json-converter.spec.ts
jdl/converters/json-to-jdl-entity-converter.spec.ts
jdl/converters/json-to-jdl-entity-converter.ts
jdl/converters/parsed-jdl-to-jdl-object/parsed-jdl-to-jdl-object-converter.spec.ts
jdl/converters/parsed-jdl-to-jdl-object/relationship-converter.spec.ts
jdl/jdl-importer.spec.ts
jdl/jhipster/relationship-options.spec.ts
jdl/jhipster/relationship-options.ts
jdl/models/jdl-relationship.spec.ts
jdl/parsing/generated/generated-serialized-grammar.js
jdl/parsing/grammar.spec.ts
jdl/parsing/jdl-ast-builder-visitor.ts
jdl/parsing/jdl-parser.ts
jdl/parsing/lexer/lexer.ts
jdl/validators/relationship-validator.spec.ts
jdl/validators/relationship-validator.ts

Related to https://github.com/jhipster/generator-jhipster/issues/21959
---

drop jpaDerivedIdentifier option from jdl

---

generators/angular/templates/src/main/webapp/app/entities/_entityFolder/_entityFile.model.ts.ejs
generators/client/support/entity-definition.mjs
generators/client/support/template-utils.mjs
generators/vue/templates/src/test/javascript/spec/app/entities/_entityFolder/_entityFile.service.spec.ts.ejs

Adjusted code generation for enum fields in entities to use key type. 
Updated code generation functions in Angular, React, and Vue templates. 
Also fixed test code generation in Angular and Vue to prevent errors.
Fix #22199
---

Fix adjust enum field code generation to use key type

---

generators/angular/templates/src/main/webapp/app/core/request/request-util.ts.ejs

do send 0 (number) query param values to backend

---

generators/generator-constants.mts

https://github.com/jhipster/generator-jhipster/issues/20849
---

Update jhipster-bom version to 8.0.0-beta.1

---

generators/react/resources/package.json
generators/react/templates/src/main/webapp/app/modules/login/login-modal.tsx.ejs

Related with https://github.com/jhipster/generator-jhipster/issues/20849
---

Update jhipster-react version to 0.24.0

---

generators/maven/templates/.mvn/wrapper/maven-wrapper.properties

Update using wrapper:
mvn org.apache.maven.plugins:maven-wrapper-plugin:3.2.0:wrapper -Dmaven=3.9.2
---

Update maven version to 3.9.2

---

generators/server/templates/src/main/resources/logback-spring.xml.ejs

Fix logback shutdown hook class name

---

package-lock.json
package.json

move noist to dev

---

cli/cli.spec.mts
cli/environment-builder.mjs
cli/environment-builder.spec.mts
cli/program.mjs
generators/base/generator-base-blueprint.mts
generators/base/generator-base-todo.spec.mts
generators/jdl/generator.mts
generators/kubernetes/prompts.mjs

- adjusts for environment 4.
---

workaround npm test taking a long time with kubectl installed without a server.

---

test-integration/scripts/lib/copy-jdl-entity-samples.js

fix generate sample using samples dir.

---

generators/angular/templates/src/main/webapp/app/app-routing.module.ts.ejs
generators/angular/templates/src/main/webapp/app/entities/_entityFolder/_entityFile.routes.ts.ejs
generators/angular/templates/src/main/webapp/app/entities/_entityFolder/detail/_entityFile-detail.component.html.ejs
generators/angular/templates/src/main/webapp/app/entities/_entityFolder/detail/_entityFile-detail.component.spec.ts.ejs
generators/angular/templates/src/main/webapp/app/entities/_entityFolder/detail/_entityFile-detail.component.ts.ejs
generators/angular/templates/src/main/webapp/app/entities/_entityFolder/route/_entityFile-routing-resolve.service.spec.ts.ejs
generators/angular/templates/src/main/webapp/app/entities/_entityFolder/route/_entityFile-routing-resolve.service.ts.ejs

Follow-up to https://github.com/jhipster/generator-jhipster/pull/22182.
---

replace deprecated class based Resolve with a ResolveFn

---

generators/react/resources/package.json

Update jhipster-react version to 0.25.2

---

generators/client/resources/package.json
generators/cypress/templates/src/test/javascript/cypress/plugins/index.ts.ejs

bump lighthouse from 9.6.8 to 10.2.0

---

generators/react/templates/src/main/webapp/app/config/store.ts.ejs

Resolves #22490 
The revision policy can be found [here](https://github.com/jhipster/generator-jhipster/issues/22490#issuecomment-1586179064).
---

Fix non-serializable detect error

---

.github/actions/setup/action.yml
generators/base/blueprints.spec.mts
generators/base/generator-base-blueprint.mts
generators/generator-constants.mts

Update jhipster-bom version to 8.0.0-SNAPSHOT

---

generators/react/resources/package.json

Update jhipster-react version to main

---

generators/app/__snapshots__/generator.spec.mts.snap
generators/app/generator.mjs
generators/base-docker/generator.mjs
generators/entities/generator.mjs
generators/jdl/__snapshots__/generator.spec.mts.snap
generators/page/generator.mjs
generators/spring-controller/generator.mjs
generators/spring-service/generator.mjs
generators/upgrade/generator.mjs

- drop some generator options that matches common option.
- drop some default value. Default values can override option values from others sources (like common options).
- replace 'npm show' with latest-version dependency.
Fixes https://github.com/jhipster/generator-jhipster/issues/22495.
---

fixes and improvements.

---

package-lock.json
package.json

Switch to yeoman-environment v4.

---

generators/server/resources/pom.xml
generators/server/templates/entity/src/test/java/package/web/rest/_EntityClass_ResourceIT.java.ejs
generators/server/templates/pom.xml.ejs
generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs
generators/server/templates/src/main/java/package/security/PersistentTokenRememberMeServices.java.ejs
generators/server/templates/src/main/java/package/service/UserService.java.ejs
generators/server/templates/src/main/java/package/web/rest/AccountResource.java.ejs
generators/server/templates/src/main/java/package/web/rest/UserResource.java.ejs
generators/server/templates/src/test/java/package/web/rest/AccountResourceIT.java.ejs
generators/server/templates/src/test/java/package/web/rest/UserResourceIT.java.ejs

Update modernizer-maven-plugin version to 2.6.0

---

generators/languages/templates/entity/i18n/entity_ja.json.ejs
generators/languages/templates/src/main/resources/i18n/messages_ja.properties.ejs
generators/languages/templates/src/main/webapp/i18n/ja/error.json
generators/languages/templates/src/main/webapp/i18n/ja/gateway.json
generators/languages/templates/src/main/webapp/i18n/ja/global.json.ejs
generators/languages/templates/src/main/webapp/i18n/ja/health.json.ejs
generators/languages/templates/src/main/webapp/i18n/ja/home.json
generators/languages/templates/src/main/webapp/i18n/ja/login.json
generators/languages/templates/src/main/webapp/i18n/ja/metrics.json
generators/languages/templates/src/main/webapp/i18n/ja/register.json
generators/languages/templates/src/main/webapp/i18n/ja/reset.json.ejs
generators/languages/templates/src/main/webapp/i18n/ja/user-management.json

Regarding the Japanese translation for i18n, I have added updates where there had been no changes since https://github.com/jhipster/generator-jhipster/pull/1207 . 
I have also fixed some parts to make them more understandable.
I would be delighted if this could be merged in preparation for the v8 release. :smile:
---

Update Japanese localization

---

generators/angular/templates/src/main/webapp/app/shared/filter/filter.model.ts.ejs
generators/client/templates/src/main/webapp/index.html.ejs

Fix:
- https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYfeFdiPJUy2bJLKtS5N&tab=code
- https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYfeFdh4JUy2bJLKtS5M
---

Sonar code smells fixes 

---

.github/actions/build-matrix/action.yml
.github/dependabot.yml
.github/workflows/lock-maintenance.yml
Dockerfile
generators/generate-blueprint/generator.mjs
generators/generate-blueprint/templates/.github/workflows/generator.yml.ejs

Related to https://github.com/jhipster/generator-jhipster/issues/22586.
https://github.com/jhipster/generator-jhipster/issues/22582#issuecomment-1595765859
---

Adjusts to Dockerfile and node version.

---

generators/server/templates/src/main/java/package/security/DomainUserDetailsService.java.ejs
generators/server/templates/src/main/java/package/web/rest/errors/BadRequestAlertException.java.ejs
generators/server/templates/src/main/java/package/web/rest/errors/ExceptionTranslator.java.ejs

Fix:
- https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYT5NJzcoub84d7atcQD
- https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYT5NJ0Boub84d7atcQF
- https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYT5NKD1oub84d7atcQm&tab=why
---

Sonar code smells fixes

---

generators/base/generator-base.mts
generators/base/support/write-files.mts
generators/server/generator.mjs

Fixes https://github.com/jhipster/generator-jhipster/issues/22582
---

Fix npe at windows.

---

generators/angular/templates/src/main/webapp/app/admin/user-management/user-management.route.ts.ejs

Deprecated: https://angular.io/api/router/Resolve
Replace: https://angular.io/api/router/ResolveFn
Sonar: https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYaCqUeVB7Ez8b_HG4mZ
---

[Angular] Resolve is deprecated

---

generators/angular/templates/src/main/webapp/app/core/auth/user-route-access.service.ts.ejs

Deprecated: https://angular.io/api/router/CanActivate
Sonar: https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYaCqUizB7Ez8b_HG4ma
---

[Angular] CanActivate is deprecated

---

README.md

Remove Datastax from Gold Sponsor

---

.github/actions/setup/action.yml
.github/workflows/generator.yml
generators/generator-constants.mts
generators/init/constants.mjs
generators/init/generator.mjs
generators/init/templates/package.json.ejs
generators/openapi-client/__snapshots__/openapi-client.spec.mts.snap

Update spring-boot version to 3.1.1

---

generators/gradle/constants.mjs

Upgrade to Gradle 8.1.1

---

generators/server/templates/pom.xml.ejs

Remove fork parameter from Spring Boot Maven Plugin

---

generators/server/support/spring-factories.mts
generators/server/support/spring-factories.spec.mts
package-lock.json
package.json

- avoid injection of duplicated values.
---

edit properties file using dto-properties lib

---

generators/client/templates/src/main/webapp/swagger-ui/index.html.ejs

Fix: https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYZRyJypeuW-M749ZN0o
---

Sonar: Extract this nested ternary operation into an independent statement

---

generators/server/templates/src/test/java/package/web/filter/SpaWebFilterIT_imperative.java.ejs
generators/server/templates/src/test/java/package/web/filter/SpaWebFilterIT_reactive.java.ejs

Fix: https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYYTa0y2wLq37qdi-9eI
---

Sonar: Remove this 'public' modifier

---

generators/gradle/constants.mjs

https://docs.gradle.org/8.2/release-notes.html
---

Upgrade to Gradle 8.2

---

generators/server/templates/src/main/java/package/config/SecurityConfiguration_imperative.java.ejs

Fix: https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYYTa0_kwLq37qdi-9eJ
---

Sonar: Replace this lambda with method reference 'FrameOptionsConfig::sameOrigin'

---

generators/server/templates/src/main/java/package/web/rest/AccountResource.java.ejs

Fix https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYT5NJ1houb84d7atcQI
---

Sonar: Remove this unused import 'jakarta.servlet.http.HttpServletRequest'

---

generators/generator-constants.mts
generators/kubernetes-helm/templates/app/Chart.yml.ejs
generators/kubernetes-helm/templates/app/requirements.yml.ejs
generators/kubernetes/kubernetes-base.mjs

fix typos in constants names
---

fix: typos

---

.github/actions/setup/action.yml
generators/generator-constants.mts

Update jhipster-bom version to 8.0.0-beta.2

---

generators/base-application/support/prepare-field.mjs
generators/base/support/faker.mts
generators/docker-compose/generator.mjs
generators/docker/generator.mjs
generators/liquibase-changelogs/__snapshots__/incremental-liquibase.spec.mts.snap
generators/liquibase-changelogs/incremental-liquibase.spec.mts
generators/liquibase-changelogs/templates/src/main/resources/config/liquibase/fake-data/table_entity.csv.ejs
package-lock.json
package.json
test-integration/samples/webflux-gradle-session-h2mem-es/.yo-rc.json

Fix https://github.com/jhipster/generator-jhipster/pull/22134
---

build(deps): bump @faker-js/faker from 7.6.0 to 8.0.2

---

generators/gradle/constants.mjs

https://docs.gradle.org/8.2.1/release-notes.html
---

Upgrade to Gradle 8.2.1

---

generators/base-application/support/prepare-field.mjs

Fakerjs 8: fix phone number

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.eslintignore
.gitignore
.prettierignore
CONTRIBUTING.md
generators/server/templates/.devcontainer/devcontainer.json.ejs
test-integration/scripts/99-print-npm-version.sh

Fixes https://github.com/jhipster/generator-jhipster/issues/22762.
---

add devcontainer for jhipster development

---

generators/base-application/support/prepare-field.mjs

WIP: Fakerjs 8: address replace by location

---

generators/base-application/support/prepare-field.mjs

Reverts jhipster/generator-jhipster#22861

Revert "Fakerjs 8: address replace by location"

---

cli/cli.spec.mts
cli/environment-builder.mjs

Fixes https://github.com/jhipster/generator-jhipster/issues/22728
---

fix custom command parsing on windows.

---

generators/base-application/support/prepare-field.mjs
generators/base/support/faker.mts
generators/liquibase-changelogs/__snapshots__/incremental-liquibase.spec.mts.snap

Fakerjs 8: address replace by location

---

generators/base-application/support/prepare-field.mjs

Fakerjs 8: commerce.color is deprecated

---

generators/common/templates/sonar-project.properties.ejs
generators/server/templates/src/main/java/package/web/rest/errors/ExceptionTranslator.java.ejs

- Ignore gatling empty tests.
- Fix https://sonarcloud.io/project/issues?resolved=false&severities=CRITICAL&types=CODE_SMELL&id=jhipster-sample-application&open=AYT5NJzcoub84d7atcPs
---

Fix sonar issues.

---

.devcontainer/devcontainer.json
.gitignore

add .devcontainter to gitignore

---

cli/cli.mjs
generators/upgrade/generator.mjs

Fixes https://github.com/jhipster/generator-jhipster/issues/22617#issuecomment-1634969460.
---

allow upgrade to use node 16.

---

generators/angular/templates/src/main/webapp/app/admin/user-management/list/user-management.component.ts.ejs

Fix https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYVQENyD9mTDbKDoDzmK 
---

[Angular] Sonar: '@angular/router' import is duplicated

---

generators/server/templates/src/main/java/package/web/rest/errors/ExceptionTranslator.java.ejs

Fix 9 sonar issues in ExceptionTranslator
Fix https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYT5NJzcoub84d7atcP6
---

Fix sonar issue.

---

generators/server/templates/entity/src/main/java/package/common/inject_template.ejs
generators/server/templates/entity/src/main/java/package/web/rest/_EntityClass_Resource.java.ejs

Fix https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AXgYXBxAM8GLQdCnBrhu 
---

Sonar: Remove this unused 'xxxRepository' private field

---

generators/server/templates/src/main/java/package/Application.java.ejs

Fix https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYjpbfx98DFj_1c0h8kx
---

Sonar: Invoke method only conditionally

---

generators/angular/support/translate-angular.mjs

[Angular] French JHipster generation failed

---

jdl/converters/json-to-jdl-converter.spec.ts
jdl/converters/json-to-jdl-converter.ts

Fixes https://github.com/jhipster/generator-jhipster/issues/22978.
---

fix export jdl with nullish configs

---

generators/server/support/relationship.mts

Fixes https://github.com/jhipster/generator-jhipster/issues/22887
---

add one-to-one back reference for sql only

---

generators/base-core/generator-base.mts

Fixes https://github.com/jhipster/generator-jhipster/issues/22979
---

Make sure yeoman-generator will not throw on empty tasks due to filtered priorities

---

generators/base-application/support/prepare-field.mjs
generators/liquibase-changelogs/__snapshots__/incremental-liquibase.spec.mts.snap
generators/liquibase-changelogs/incremental-liquibase.spec.mts
generators/liquibase-changelogs/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs
generators/liquibase/templates/src/main/resources/config/liquibase/changelog/initial_schema_sql.xml.ejs
generators/server/templates/src/test/java/package/web/filter/SpaWebFilterIT_reactive.java.ejs

Fix https://github.com/jhipster/generator-jhipster/issues/23067 caused by duplicated ids due to fake data.
Fix ng-webflux-default random failures.
Workaround https://github.com/jhipster/generator-jhipster/issues/20036.
---

workaround h2 failures.

---

generators/cucumber/__snapshots__/generator.spec.mts.snap
generators/cucumber/generator.mts
generators/cucumber/templates/src/test/java/package/cucumber/stepdefs/UserStepDefs.java.ejs

- Adds a profile to be used at cucumber tests.
Related to https://github.com/jhipster/generator-jhipster/pull/22689.
Should fix some daily builds failures.
---

adjusts to cucumber

---

generators/server/templates/entity/src/main/java/package/service/impl/_EntityClass_ServiceImpl.java.ejs
generators/server/templates/entity/src/main/java/package/web/rest/_EntityClass_Resource.java.ejs
generators/spring-data-elasticsearch/templates/src/main/java/package/repository/search/_EntityClass_SearchRepository.java.ejs

Unused imports

---

generators/server/templates/gradle/swagger.gradle.ejs

fix compilation failure for openapi and gradle

---

generators/spring-data-relational/templates/src/test/java/package/config/timezone/HibernateTimeZoneIT.java.ejs

Fix time zone issue with hibernate 6.2.x

---

.blueprint/generate-sample/support/generate-sample.js
.eslintrc.json
generators/angular/templates/src/main/webapp/app/home/home.component.scss.ejs
generators/angular/templates/src/main/webapp/app/layouts/navbar/navbar.component.scss.ejs
generators/angular/templates/webpack/proxy.conf.js.ejs
generators/base/generator-base-blueprint.mts
generators/base/support/constants.mts
generators/client/templates/src/main/webapp/content/css/loading.css.ejs
generators/client/templates/src/main/webapp/swagger-ui/index.html.ejs
generators/server/templates/src/main/java/package/web/filter/SpaWebFilter_imperative.java.ejs

Related to https://github.com/jhipster/generator-jhipster/issues/22542
---

Fixes deploying with context-path

---

generators/server/templates/src/main/java/package/config/SecurityConfiguration_imperative.java.ejs
generators/server/templates/src/main/java/package/web/filter/SpaWebFilter_imperative.java.ejs

Fix H2 console not working

---

generators/server/templates/src/main/java/package/config/OAuth2Configuration.java.ejs

Fixes https://github.com/jhipster/generator-jhipster/issues/23140
---

remove deprecated method call

---

README.md
cli/utils.mjs

Depends on https://github.com/jhipster/jhipster.github.io/pull/1299.

Remove Okta as a sponsor

---

generators/vue/templates/src/main/webapp/app/account/login-form/login-form.vue.ejs

Fixes https://github.com/jhipster/generator-jhipster/issues/23179
---

fix vue translation

---

generators/gradle/constants.mjs

https://docs.gradle.org/8.3/release-notes.html
---

Upgrade to Gradle 8.3

---

generators/server/templates/entity/src/main/java/package/common/patch_template.ejs

Fix a lot of Sonar issues like https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AX1ygaBS2farvsyMs7mU
---

Sonar: Remove useless curly braces

---

generators/server/templates/src/main/java/package/config/SecurityConfiguration_imperative.java.ejs
generators/server/templates/src/main/java/package/config/SecurityConfiguration_reactive.java.ejs

Fix https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYoP01yfUhc4kJe9Qn8I 
https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurer.html#jwt()
---

Sonar: Remove this call to a deprecated method, it has been marked for removal

---

jdl/index.ts

export more jdl stuff

---

.github/workflows/generator.yml
generators/generator-constants.mts

Update Node version to 18.17.1

---

.github/dependabot.yml
generators/angular/generator.mts
generators/base-application/generator.mts
generators/base-core/generator-base.mts
generators/generate-blueprint/generator.mjs
generators/generate-blueprint/resources/package.json
generators/init/templates/package.json.ejs

blueprint support and generate-blueprint improvements

---

generators/base-core/generator-base.mts
generators/base/api.d.mts
generators/bootstrap-application-base/generator.mts
generators/bootstrap-application-client/generator.mts
generators/bootstrap-application-server/generator.mts
generators/bootstrap-application/generator.mts
generators/bootstrap/generator.mts
generators/info/generator.mts

don't compose info with bootstrap

---

generators/maven/templates/.mvn/wrapper/maven-wrapper.properties

Update using wrapper:
mvn org.apache.maven.plugins:maven-wrapper-plugin:3.2.0:wrapper -Dmaven=3.9.4
---

Update maven version to 3.9.4

---

.github/actions/setup/action.yml
generators/generator-constants.mts

depends on https://github.com/jhipster/jhipster-bom/pull/1418
---

Update spring-boot version to 3.1.3

---

generators/generator-constants.mts
generators/openapi-client/__snapshots__/openapi-client.spec.mts.snap

Update @openapitools/openapi-generator-cli version to 2.7.0

---

generators/server/resources/pom.xml

Update openapi-generator-maven-plugin version to 7.0.0

---

generators/base-core/generator-base.mts
generators/base/api.d.mts
generators/entity/generator.mjs
generators/jdl/generator.mts
generators/jdl/generator.spec.mts

fix composing with entities

---

.github/workflows/issue-check.yml

fix issue number reference

---

generators/server/templates/entity/src/main/java/package/service/impl/_EntityClass_ServiceImpl.java.ejs
generators/server/templates/src/main/java/package/domain/User.java.ejs
generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs
generators/spring-data-elasticsearch/templates/src/main/java/package/repository/search/UserSearchRepository.java.ejs
generators/spring-data-relational/templates/src/main/java/_package_/repository/rowmapper/UserRowMapper_reactive.java.ejs

fix https://github.com/jhipster/generator-jhipster/issues/21735 
close #15042
---

fix compilation errors in reactive app

---

.github/workflows/issue-check.yml

comment should not be always executed.

---

generators/react/resources/package.json
generators/react/templates/jest.conf.js.ejs

[React] Fix bump sinon from 15.1.2 to 15.2.0

---

generators/app/__snapshots__/generator.spec.mts.snap
generators/app/generator.mjs
generators/app/support/config.mts
generators/base-core/generator.mts
generators/base/__snapshots__/generator.spec.mts.snap
generators/base/command.mts
generators/base/generator-base-todo.mts
generators/base/generator.mts
generators/base/shared-data.mts
generators/base/types.d.mts
generators/bootstrap-application-client/generator.mts
generators/bootstrap-application/generator.mts
generators/bootstrap/generator.mts
generators/client/generator.mjs
generators/common/generator.mjs
generators/cypress/generator.mts
generators/entities/generator.mjs
generators/generate-blueprint/generator.mjs
generators/jdl/__snapshots__/generator.spec.mts.snap
generators/languages/generator.mjs
generators/page/generator.mjs
generators/server/generator.mjs
generators/workspaces/generator.mjs

Related to https://github.com/jhipster/generator-jhipster/issues/18652
---

remove parseCommonRuntimeOptions and loadRuntimeOptions

---

.blueprint/from-issue/generator.mjs
.blueprint/generate-sample/support/generate-sample.js
generators/base-core/generator.mts
generators/base/api.d.mts
generators/info/generator.mts
generators/info/support/index.mts
generators/info/support/utils.mts

- pass `--skip-checks` at generate-samples
- print the entire `.yo-rc.json` to print blueprints configs.
---

Info and generate-samples adjusts

---

package-lock.json
package.json

bump p-queue from 7.3.4 to 7.4.1

---

cli/environment-builder.mjs
cli/program.mjs
generators/base-core/generator-core.spec.mts
generators/base-core/generator.mts
generators/jdl/generator.mts

- allows blueprints to implement its own dev-blueprint.
- fix argument parsing using composeWith
---

Expose dev blueprint to blueprints and improvements to argument parsing.

---

generators/app/generator.mjs
generators/app/prompts.mjs
generators/client/generator.mjs
generators/client/prompts.mjs
generators/client/prompts.spec.mts
generators/server/generator.mjs
generators/server/prompts.mjs

Fixes https://github.com/jhipster/generator-jhipster/issues/12902.
---

split client/server testFramework prompt

---

cli/cli.mjs
cli/environment-builder.mjs
generators/base-application/generator.mts
generators/base-core/generator-core.spec.mts
generators/base-core/generator.mts
generators/base/api.d.mts
generators/base/generator.mts
generators/bootstrap/generator.mts
generators/bootstrap/support/prettier-support.mts
generators/generate-blueprint/__snapshots__/generator.spec.mjs.snap
generators/generate-blueprint/files.mjs
generators/generate-blueprint/generator.mjs
generators/generate-blueprint/templates/.blueprint/cli/commands.mjs.ejs
generators/generate-blueprint/templates/.blueprint/generate-sample/command.mjs.ejs
generators/generate-blueprint/templates/.blueprint/generate-sample/generator.mjs.ejs
generators/generate-blueprint/templates/.blueprint/generate-sample/index.mjs.ejs
generators/generate-blueprint/templates/.blueprint/generate-sample/templates/samples/sample.jdl.ejs
generators/generate-blueprint/templates/.eslintrc.json.ejs
generators/generate-blueprint/templates/.github/workflows/generator.yml.ejs
generators/generate-blueprint/templates/cli/cli.cjs.ejs
generators/generate-blueprint/templates/generators/generator/generator.mjs.jhi.ejs
generators/generate-blueprint/templates/vitest.config.ts.ejs
generators/init/generator.mjs
generators/jdl/generator.mts
generators/server/generator.mjs

Related to https://github.com/jhipster/generator-jhipster-ionic/issues/927 and https://github.com/jhipster/generator-jhipster-ionic/pull/926
---

Many adjusts

---

generators/app/__snapshots__/generator.spec.mts.snap
generators/app/generator.mjs
generators/base-application/generator.mts
generators/client/generator.mjs
generators/jdl/__snapshots__/generator.spec.mts.snap
generators/jdl/generator.mts
generators/server/command.mts
generators/spring-data-relational/command.mts
generators/spring-data-relational/generator.mts

Add cli options and allow read jdl file from mem-fs

---

generators/client/templates/src/main/webapp/swagger-ui/index.html.ejs
generators/cypress/templates/src/test/javascript/cypress/e2e/administration/administration.cy.ts.ejs

fix swagger for gateway/microservices

---

package-lock.json
package.json

Related with https://github.com/jhipster/generator-jhipster/issues/19112
---

Remove aws-sdk dependency

---

generators/server/support/doc.mjs
generators/server/support/doc.spec.mts

fix jdl multi-line javadoc issue

---

generators/angular/templates/src/main/webapp/app/entities/_entityFolder/update/_entityFile-form.service.ts.ejs
generators/base-application/support/prepare-entity.mts
generators/bootstrap-application/generator.spec.mts
generators/liquibase/generator.mts
generators/liquibase/support/post-prepare-entity.mts
generators/liquibase/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs
generators/liquibase/templates/src/main/resources/config/liquibase/changelog/initial_schema_sql.xml.ejs
generators/server/support/prepare-field.mjs
generators/server/support/templates/field-values.mjs
generators/server/templates/entity/src/test/java/package/domain/_PersistClass_Test.java.ejs
generators/server/templates/entity/src/test/java/package/web/rest/_EntityClass_ResourceIT.java.ejs
generators/server/templates/src/main/java/package/domain/User.java.ejs
generators/spring-data-relational/templates/src/main/java/_package_/domain/_PersistClass_.java.jhi.jakarta_persistence.ejs
test-integration/samples/jdl-entities/custom-id.jdl

Fixes https://github.com/jhipster/generator-jhipster/issues/21435
---

add tests for Integer ids

---

generators/server/support/dependabot-maven.mts
package-lock.json
package.json

Upgrade fast-xml-parser 4.3.0

---

generators/languages/templates/src/main/webapp/i18n/pl/global.json.ejs
generators/languages/templates/src/main/webapp/i18n/pl/health.json.ejs
generators/languages/templates/src/main/webapp/i18n/pl/register.json
generators/languages/templates/src/main/webapp/i18n/pl/user-management.json

I added some missing translations in polish.

Add translation to polish.

---

.github/actions/setup/action.yml
generators/generator-constants.mts

Depends on https://github.com/jhipster/jhipster-bom/pull/1441
---

Update spring-boot version to 3.1.4

---

generators/server/support/dependabot-maven.mts
package-lock.json
package.json

Upgrade fast-xml-parser from 4.3.0 to 4.3.1

---

generators/generate-blueprint/templates/generators/generator/generator.mjs.jhi.ejs
package-lock.json
package.json

Generate beforeQueue at full blueprints

---

generators/jdl/generator.mts

Fixes https://github.com/jhipster/generator-jhipster/issues/23660
---

fix jdl download

---

generators/base-application/generator.mts
generators/base-application/support/prepare-entity.mts
generators/base-core/generator.mts
generators/base-entity-changes/generator.mts
generators/base/support/needles.mts
generators/maven/types.d.mts
generators/server/support/dependabot-gradle.mts
generators/server/support/needles.mts
generators/server/types.d.mts
generators/spring-cloud-stream/cleanup.mts

Typos: mjs files

---

generators/angular/templates/src/main/webapp/app/core/util/event-manager.service.spec.ts.ejs
generators/angular/templates/src/main/webapp/app/entities/user/user.service.spec.ts.ejs
generators/angular/templates/src/main/webapp/app/login/login.component.spec.ts.ejs
generators/angular/templates/src/main/webapp/app/shared/filter/filter.model.spec.ts.ejs
generators/vue/templates/src/main/webapp/app/shared/config/axios-interceptor.spec.ts.ejs

Typos: spec files

---

generators/angular/templates/src/main/webapp/app/admin/metrics/metrics.component.spec.ts.ejs

[Angular] Improve coverage on MetricsComponent

---

generators/angular/__snapshots__/generator.spec.mts.snap
generators/angular/files-angular.mjs
generators/angular/templates/src/main/webapp/app/admin/metrics/blocks/metrics-modal-threads/metrics-modal-threads.component.spec.ts.ejs

Add tests and improve coverage: https://sonarcloud.io/component_measures?id=jhipster-sample-application&metric=coverage&selected=jhipster-sample-application%3Asrc%2Fmain%2Fwebapp%2Fapp%2Fadmin%2Fmetrics%2Fblocks%2Fmetrics-modal-threads%2Fmetrics-modal-threads.component.ts
**Before**
**After**
---

[Angular] Add tests for MetricsModalThreadsComponent

---

generators/generate-blueprint/templates/cli/cli.cjs.ejs

fix https://github.com/jhipster/generator-jhipster/issues/23694.
---

fix blueprint cli without generator- prefix

---

generators/kubernetes/__snapshots__/kubernetes.spec.mts.snap
generators/kubernetes/kubernetes.spec.mts
generators/kubernetes/prompts.mjs

Use recently added spawn mock to avoid outside calls.
- Add calls snapshots
Fixes https://github.com/jhipster/generator-jhipster/issues/22475.
---

use spawn mocks to avoid outside calls

---

generators/ci-cd/__snapshots__/ci-cd.spec.mts.snap
generators/ci-cd/templates/.github/workflows/main.yml.ejs
generators/generate-blueprint/templates/.github/workflows/generator.yml.ejs

update actions/checkout at templates

---

generators/generate-blueprint/templates/vitest.config.ts.ejs

increase blueprint test timeout
