jhipster/generator-jhipster

test-integration/scripts/99-build-changes.sh
=> add java generator to server changes

generators/maven/templates/.mvn/wrapper/maven-wrapper.properties
Update using wrapper:
mvn org.apache.maven.plugins:maven-wrapper-plugin:3.2.0:wrapper -Dmaven=3.9.5
---
=> Update maven version to 3.9.5

generators/base-workspaces/internal/docker-prompts.mjs
Fixes https://github.com/jhipster/generator-jhipster/issues/23863
---
=> adjust docker-prompts lookups

package-lock.json, package.json
Related to https://github.com/jhipster/generator-jhipster/issues/23868.
---
=> bump yeoman-stack

cli/jhipster-command.mjs, cli/program.mjs, generators/angular/templates/package.json.ejs, generators/common/__snapshots__/generator.spec.mjs.snap, generators/common/generator.mjs, generators/common/templates/.lintstagedrc.js.ejs, generators/common/templates/.prettierrc.ejs, generators/init/generator.mjs, generators/jdl/__snapshots__/generator.spec.mts.snap, generators/react/templates/package.json.ejs, generators/server/templates/package.json.ejs, generators/vue/templates/package.json.ejs
Related to https://github.com/jhipster/generator-jhipster/issues/23449.
---
=> More blueprint adjusts.

generators/entity/prompts.mjs
Fixes https://github.com/jhipster/generator-jhipster/issues/13604.
Fixes https://github.com/jhipster/generator-jhipster/issues/14525.
---
=> entity prompt improvements

generators/generator-constants.mts
=> Update spring-boot version to 3.1.5

.github/workflows/generator.yml, generators/generator-constants.mts
=> Update nodejs version to 18.18.2

generators/angular/generator.mts, generators/common/generator.mjs, generators/react/generator.mjs, generators/vue/generator.mjs
Fixes https://github.com/jhipster/generator-jhipster/issues/23939.
Writing step is skipped when only generating entities.
---
=> move queueTransformStream to default step

generators/base-application/support/prepare-entity.mts
Related to https://github.com/jhipster/generator-jhipster/issues/23917.
---
=> don't override relationshipEagerLoad

jdl/converters/jdl-to-json/jdl-to-json-relationship-converter.ts, jdl/integration-test.spec.ts
Related to https://github.com/jhipster/generator-jhipster/issues/23917
---
=> fix populate right side relationship with annotation

generators/server/templates/src/main/java/_package_/config/JacksonConfiguration.java.ejs
Fix #23917
In fact, I wanted to add integration or e2e tests for the related entities, but it seemed time-consuming, so I decided to skip it for now. I'll propose it as an enhancement later.
---
=> modified to return related entity IDs

generators/server/resources/pom.xml
=> Upgrade to Maven Checkstyle Plugin 3.3.1

generators/base-application/support/prepare-entity.mts, jdl/__snapshots__/jdl-importer.spec.ts.snap, jdl/converters/jdl-to-json/jdl-to-json-option-converter.ts, jdl/integration-test.spec.ts, jdl/parsing/grammar.spec.ts, jdl/parsing/jdl-ast-builder-visitor.ts, jdl/parsing/jdl-parser.ts
Fixes https://github.com/jhipster/generator-jhipster/issues/23981.
---
=> set correct annotations types

generators/angular/resources/package.json, generators/angular/templates/package.json.ejs, generators/angular/templates/webpack/webpack.microfrontend.js.ejs, generators/app/__snapshots__/generator.spec.mts.snap, generators/client/templates/webpack/webpack.microfrontend.js.jhi.ejs, generators/react/templates/webpack/webpack.microfrontend.js.jhi.react.ejs, generators/vue/resources/package.json, generators/vue/templates/package.json.ejs, generators/vue/templates/src/main/webapp/app/core/jhi-navbar/jhi-navbar.component.ts.ejs, generators/vue/templates/src/main/webapp/app/router/index.ts.ejs, generators/vue/templates/webpack/webpack.microfrontend.js.jhi.vue.ejs
Fixes https://github.com/jhipster/generator-jhipster/issues/23457
---
=> simplify microfrontend config and change vue to lazy load remotes

rfcs/1-jhipster-rfc-k8s-operator.md
=> Typo: concreate=>concrete

generators/server/templates/src/main/java/_package_/service/MailService.java.ejs
Fix:
- https://sonarcloud.io/project/issues?id=jhipster-sample-application&open=AYtcNvyK53CW9POPAr8D
- https://sonarcloud.io/project/issues?id=jhipster-sample-application&open=AYtcNvyK53CW9POPAr8E
- https://sonarcloud.io/project/issues?id=jhipster-sample-application&open=AYtcNvyK53CW9POPAr8F
- https://sonarcloud.io/project/issues?id=jhipster-sample-application&open=AYtcNvyK53CW9POPAr8G
---
=> Sonar: Call async methods via an injected dependency instead of directly via 'this'

generators/server/templates/src/main/java/_package_/web/rest/PublicUserResource.java.ejs, generators/server/templates/src/main/java/_package_/web/rest/UserResource.java.ejs, generators/spring-data-elasticsearch/templates/src/main/java/_package_/_entityPackage_/repository/search/_entityClass_SearchRepository.java.ejs
=> Fix Elasticsearch deprecations

generators/server/templates/src/main/java/_package_/_entityPackage_/_partials_entity_/get_all_template.ejs
Fixes https://github.com/jhipster/generator-jhipster/issues/24033
---
=> eager load list view by default

generators/angular/templates/src/main/webapp/app/layouts/navbar/navbar.component.scss.ejs, generators/client/templates/src/main/webapp/content/css/loading.css.ejs
Related to Issue after the login oauth2 redirect with PROD profile on angular #23991
See angular/angular-cli#4806
---
=> Use reference asset instead of relative path

generators/java/templates/src/test/java/_package_/_entityPackage_/domain/_persistClass_Test.java.ejs
=> increase coverage

generators/server/templates/src/main/java/_package_/web/rest/PublicUserResource.java.ejs
Fix https://github.com/jhipster/generator-jhipster/pull/23554
---
=> fix user search api to follow new standards

cli/environment-builder.mjs, generators/base/generator.mts, generators/base/support/jhipster7-context.mjs, generators/bootstrap/generator.mts, generators/cypress/templates/src/test/javascript/cypress/e2e/account/settings-page.cy.ts.ejs, generators/java/generator.mts, generators/java/generator.spec.mts, generators/languages/generator.mjs, generators/liquibase/generator.mts, generators/server/generator.mjs
Related to https://github.com/jhipster/generator-jhipster/issues/23449 and quarkus migration.
Fixes https://github.com/jhipster/generator-jhipster/issues/24028.
---
=> Adjusts for v8

generators/base-application/support/prepare-entity.mts, generators/base-application/support/prepare-entity.spec.mts
=> improve warning message

generators/base-application/support/prepare-relationship.mjs, generators/bootstrap-application/generator.mts, generators/java/templates/src/main/java/_package_/_entityPackage_/domain/_persistClass_.java.jhi.ejs, generators/java/templates/src/test/java/_package_/_entityPackage_/domain/_persistClass_Test.java.ejs, generators/server/support/relationship.mts, generators/spring-data-neo4j/templates/src/main/java/_package_/_entityPackage_/domain/_persistClass_.java.jhi.spring_data_neo4j.ejs, test-integration/samples/.jhipster/JpaFilteringRelationship.json
Should fix comment https://github.com/jhipster/generator-jhipster/issues/23449#issuecomment-1787106439.
Related to https://github.com/jhipster/generator-jhipster/issues/24076.
---
=> start replacing ownerSide property

README.md
=> Remove last gold sponsor: Entando

README.md
Update "Revved up by Develocity" badge
---
=> Update "Revved up by Develocity" badge

.github/actions/setup/action.yml, generators/generator-constants.mts
=> Update jhipster-bom version to 8.0.1-SNAPSHOT

.blueprint/generate-sample/command.mts, .blueprint/generate-sample/generator.mjs, .blueprint/generate-sample/support/generate-sample.js, .github/workflows/angular.yml, .github/workflows/react.yml, .github/workflows/vue.yml, bin/jhipster.cjs, cli/program.mjs
=> Use generate-sample at CI

generators/server/templates/src/main/resources/config/application.yml.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/24101
---
- [X ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [X ] Tests are added where necessary
- [X ] The JDL part is updated if necessary
- [X ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [X ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed
When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your …
=> Modified default values for metrics export

README.md, cli/environment-builder.mjs
Related to https://github.com/hipster-labs/jhipster-daily-builds/pull/155.
Fixes https://github.com/jhipster/generator-jhipster/issues/23995
---
=> allow local blueprints to have custom commands

generators/spring-data-elasticsearch/templates/src/main/java/_package_/_entityPackage_/repository/search/_entityClass_SearchRepository.java.ejs, generators/spring-data-elasticsearch/templates/src/main/java/_package_/repository/search/UserSearchRepository.java.ejs
fixes https://github.com/jhipster/generator-jhipster/issues/24173.
---
=> adjusts to elasticsearch for entitySuffix

generators/base-application/support/prepare-relationship.mjs
Fixes https://github.com/jhipster/generator-jhipster/issues/22844
---
=> add user back reference error

generators/docker-compose/generator.mjs
Fixes https://github.com/jhipster/generator-jhipster/issues/24191
---
=> update docker check

.github/workflows/angular.yml, .github/workflows/react.yml, .github/workflows/vue.yml, generators/generator-constants.mjs, test-integration/scripts/00-init-env.sh, test-integration/scripts/99-write-matrix.js, test-integration/workflow-samples/angular.json, test-integration/workflow-samples/react.json, test-integration/workflow-samples/vue.json
Fixes https://github.com/jhipster/generator-jhipster/issues/23958.
---
=> test node 18/20 and java 17/21 matrix

generators/bootstrap-application/generator.mts
This PR adds the entity's name that is causing an issue while importing a JDL file.
---
=> Adding entity's name to error

.github/dependabot.yml
This might help with #24092. 
---
=> Group dependabot updates for Angular

.blueprint/from-issue/generator.mjs, .github/workflows/issue-check.yml
=> improve from-issue

generators/vue/templates/package.json.ejs
Fixes https://github.com/jhipster/generator-jhipster/issues/24256
---
=> add missing webapp:dev script to vue

generators/server/templates/pom.xml.ejs
=> fix warnings.

generators/react/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_.tsx.ejs
Fixes https://github.com/jhipster/generator-jhipster/issues/24115
---
=> Fix error during entity deletion process

.blueprint/from-issue/command.mts
Allows `jhipster from-issue --dev-database-type h2Disk` for easier kickstart.
---
=> import cli options at from-issue

.github/actions/compare/action.yml, test-integration/samples/jdl-entities/custom-id.jdl
=> Compare adjusts

generators/docker/generator.mjs, test-integration/samples/jdl-entities/custom-id.jdl
=> increase sleep for cassandra and changelogDate adjusts

.github/workflows/stale.yml
=> increase stale operations

generators/docker-compose/__snapshots__/docker-compose.spec.mts.snap, generators/docker/templates/docker/cassandra.yml.ejs, generators/server/resources/Dockerfile
closes https://github.com/jhipster/generator-jhipster/pull/22994
---
=> Update to cassandra 4

generators/spring-data-relational/templates/src/main/java/_package_/repository/EntityManager_reactive.java.ejs
=> Bad SQL grammar is thrown when sorting using foreign key

generators/angular/templates/src/main/webapp/app/home/home.component.html.ejs, generators/angular/templates/src/main/webapp/app/layouts/navbar/navbar.component.html.ejs, test/needle-api/needle-client-angular-generator.spec.mts
=> [Angular 17] Control flow syntax for 'switch'

generators/liquibase/incremental-liquibase.spec.mts
=> Rename variable (typo)

generators/gradle/constants.mjs
https://docs.gradle.org/8.5/release-notes.html
=> Upgrade to Gradle 8.5

generators/server/templates/src/main/java/_package_/web/rest/LogoutResource_imperative.java.ejs, generators/server/templates/src/main/java/_package_/web/rest/LogoutResource_reactive.java.ejs
no special handling for auth0 anymore, using well known meta data.
closes #22020
---
=> use session endpoint metadata for oauth logout

.github/dependabot.yml
=> group more dependencies

.github/workflows/labeler.yml
Reverts jhipster/generator-jhipster#24476
=> Revert "build(deps): bump actions/labeler from 4 to 5"

.github/actions/setup/action.yml, generators/generator-constants.mjs
=> Update bom version to 8.1.1-SNAPSHOT

generators/maven/templates/.mvn/wrapper/maven-wrapper.properties
Update using wrapper:
mvn org.apache.maven.plugins:maven-wrapper-plugin:3.2.0:wrapper -Dmaven=3.9.6
---
=> Update maven version to 3.9.6

generators/liquibase/generator.mts, generators/liquibase/templates/gradle/liquibase.gradle.ejs
Partial fix for https://github.com/jhipster/generator-jhipster/issues/24533
---
=> [liquibase, neo4j] exclude slf4j dependency from liquibase-neo4j

.github/workflows/stale.yml
=> [internal] switch to actions/stale release.

generators/ci-cd/__snapshots__/ci-cd.spec.ts.snap, generators/ci-cd/templates/.circleci/config.yml.ejs, generators/ci-cd/templates/.github/workflows/main.yml.ejs, generators/ci-cd/templates/.gitlab-ci.yml.ejs, generators/ci-cd/templates/.travis.yml.ejs, generators/ci-cd/templates/jenkins/Jenkinsfile.ejs, ~
Without this change, [things fail](https://github.com/mraible/jhipster8-demo/actions/runs/7206131395/job/19630370752). After upgrading, everything succeeds!
---
=> Upgrade to the latest version of the Heroku Maven Plugin

.github/workflows/linked-issue-check.yml, generators/server/generator.js
fixes https://github.com/jhipster/generator-jhipster/issues/24544.
---
=> [server] check for composite ids.

generators/angular/templates/src/main/webapp/app/admin/metrics/metrics.model.ts.ejs
=> Angular: ThreadState.Terminated is not used

generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/route/_entityFile_-routing-resolve.service.ts.ejs
=> Angular: Fix duplicate exports

generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/update/_entityFile_-update.component.ts.ejs
Related to #24585 
Fix https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=jhipster-sample-application&open=AYx-USDqEHMvvUCDADZt
---
=> [Angular] Sonar: Unexpected empty constructor

generators/angular/templates/src/main/webapp/app/app.component.ts.ejs
=> [Angular] Metric page not showing metric params

generators/angular/templates/src/main/webapp/app/admin/user-management/detail/user-management-detail.component.ts.ejs
so that back link works
Fix #24641
---
=> add missing import to UserManagementDetailComponent

generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_-update.component.ts.ejs, generators/vue/templates/src/main/webapp/app/shared/composables/validation.ts.ejs
Fix #21263 
https://vuelidate-next.netlify.app/validators.html#numeric
---
=> [Vue] Accept negative number for Integer and Long

generators/vue/templates/vite.config.ts.ejs
=> [Vue] Expose a "host" to display in the network

generators/server/__snapshots__/generator.spec.js.snap, generators/server/files.js, generators/server/support/__snapshots__/needles.spec.ts.snap, generators/server/templates/src/test/java/_package_/config/CRLFLogConverterTest.java.ejs, generators/spring-data-cassandra/__snapshots__/generator.spec.ts.snap, generators/spring-data-couchbase/__snapshots__/generator.spec.ts.snap, generators/spring-data-elasticsearch/__snapshots__/generator.spec.ts.snap, generators/spring-data-mongodb/__snapshots__/generator.spec.ts.snap, generators/spring-data-neo4j/__snapshots__/generator.spec.ts.snap, generators/spring-data-relational/__snapshots__/generator.spec.ts.snap
=> Add tests for CRLFLogConverter.java

generators/server/templates/pom.xml.ejs
=> Sort maven dependencies by alphabetical order

generators/server/templates/build.gradle.ejs, generators/server/templates/gradle/profile_dev.gradle.ejs, generators/server/templates/gradle/profile_prod.gradle.ejs
Fix #18760
Related to #24701 
---
=> Sort gradle dependencies by alphabetical order

generators/angular/templates/src/main/webapp/app/app.config.ts.ejs
=> fix angular with session and websocket

.github/workflows/issue-check.yml
=> disable blueprints at issue check

generators/angular/templates/package.json.ejs, generators/workspaces/generator.js
Fixes https://github.com/jhipster/generator-jhipster/issues/24745.
---
=> Adjusts for angular microfrontend support

generators/spring-data-relational/generator.ts
Set both sides of the relationship as persistable.
---
=> change many-to-many behavior for spring-data-relational

generators/server/templates/src/main/java/_package_/config/SecurityConfiguration_imperative.java.ejs
Matches session authentication type.
---
=> add loginPage to oauth2 config

generators/angular/templates/src/main/webapp/content/scss/_bootstrap-variables.scss.ejs
=> [Angular] Buttons have black text on colored background

.github/actions/build-matrix/action.yml, .github/workflows/generator.yml, generators/generator-constants.js
=> Upgrade Node 20.11.0

generators/generate-blueprint/generator.js, generators/generate-blueprint/templates/generators/generator/generator.mjs.jhi.ejs, generators/generate-blueprint/templates/generators/generator/index.mjs.ejs
- set local blueprint as dynamic by default based on https://github.com/mshima/local-blueprints/blob/main/app/generator.mjs.
- local blueprint adjusts
Fixes https://github.com/jhipster/generator-jhipster/issues/24792
---
=> adjusts to local blueprint

generators/common/resources/package.json, generators/server/templates/build.gradle.ejs
=> bump npm to 10.3.0

generators/angular/templates/src/main/webapp/app/core/util/alert.service.ts.ejs
=> [Angular] Remove unused NgZone

generators/angular/templates/src/main/webapp/app/layouts/navbar/navbar.component.html.ejs, generators/angular/templates/src/main/webapp/app/layouts/navbar/navbar.component.ts.ejs
=> [Angular] Use Signal to handle isNavbarCollapsed

generators/react/resources/package.json, generators/react/templates/src/main/webapp/app/app.tsx.ejs
=> [React] bump react-toastify from 9.1.3 to 10.0.0

generators/angular/templates/src/main/webapp/app/admin/user-management/update/user-management-update.component.html.ejs, generators/angular/templates/src/main/webapp/app/admin/user-management/update/user-management-update.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/admin/user-management/update/user-management-update.component.ts.ejs
=> [Angular] Use Signal to handle isSaving

cli/environment-builder.mjs
=> replace alias with customizeNamespace

generators/angular/resources/package.json, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/service/_entityFile_.service.ts.ejs, generators/angular/templates/src/main/webapp/app/entities/user/user.service.ts.ejs
=> [Angular] typescript-eslint 6.19.0

generators/angular/templates/src/main/webapp/app/account/activate/activate.component.html.ejs, generators/angular/templates/src/main/webapp/app/account/activate/activate.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/account/activate/activate.component.ts.ejs, generators/angular/templates/src/main/webapp/app/layouts/navbar/navbar.component.html.ejs, generators/angular/templates/src/main/webapp/app/layouts/navbar/navbar.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/layouts/navbar/navbar.component.ts.ejs
=> Angular: Use Signals

generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_.routes.ts.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/detail/_entityFile_-detail.component.html.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/list/_entityFile_.component.html.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/service/_entityFile_.service.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/service/_entityFile_.service.ts.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/update/_entityFile_-form.service.ts.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/update/_entityFile_-update.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/update/_entityFile_-update.component.ts.ejs, generators/base-application/support/prepare-entity.ts, generators/cypress/templates/src/test/javascript/cypress/e2e/entity/_entity_.cy.ts.ejs, generators/server/templates/_global_partials_entity_/update_template.ejs, generators/server/templates/reactive/_global_partials_entity_/update_template.ejs, generators/server/templates/src/main/java/_package_/_entityPackage_/_partials_entity_/patch_template.ejs, generators/server/templates/src/main/java/_package_/_entityPackage_/service/impl/_entityClass_ServiceImpl.java.ejs, generators/server/templates/src/main/java/_package_/_entityPackage_/web/rest/_entityClass_Resource.java.ejs, generators/server/templates/src/test/java/_package_/_entityPackage_/web/rest/_entityClass_ResourceIT.java.ejs, test-integration/samples/jdl-entities/01-non-updatable-entity.jdl
Non updatable entity has only the id which is immutable.
- use persistableEntity to calculate instead of ownerSide
- remove update apis and edit ui for angular
Related to https://github.com/jhipster/generator-jhipster/pull/24885
---
=> rework non updatable entities

generators/spring-cloud-stream/templates/src/test/java/_package_/web/rest/KafkaResourceIT_imperative.java.ejs
fix missing csfr in the Kafka integration test
Fix #24912
---
=> fix missing CSRF in Kafka test

generators/server/templates/_global_partials_entity_/save_template.ejs, generators/server/templates/reactive/_global_partials_entity_/save_template.ejs, generators/server/templates/src/main/java/_package_/_entityPackage_/web/rest/_entityClass_Resource.java.ejs
=> simplify save_template

generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/list/_entityFile_.component.ts.ejs
=> [Angular] Using Entity 'Refresh list' button makes pagination links multiply requests

generators/angular/templates/src/main/webapp/app/admin/user-management/detail/user-management-detail.component.html.ejs
=> [Angular] Fix warnings: '?.' operator can be replaced with the '.' operator

.prettierrc, generators/common/__snapshots__/generator.spec.js.snap, generators/common/templates/.prettierrc.ejs, package-lock.json, package.json
Fix #24884 
Waiting https://github.com/prettier/prettier/pull/15958 
---
=> Prettier 3.2.4

generators/angular/templates/src/main/webapp/app/admin/logs/logs.component.html.ejs
[screen-capture.webm](https://github.com/jhipster/generator-jhipster/assets/9989211/900a00a9-405a-4380-b416-266d3d4b43d7)
---
=> [Angular] Use Deferrable Views for logs page

generators/angular/templates/src/main/webapp/app/admin/user-management/list/user-management.component.html.ejs
=> [Angular] Simplify template for UserManagementComponent

generators/angular/templates/src/main/webapp/app/admin/user-management/list/user-management.component.html.ejs
=> [Angular] Remove duplicated condition

generators/angular/templates/src/main/webapp/app/admin/metrics/blocks/jvm-memory/jvm-memory.component.html.ejs
=> [Angular] Simplify template for JvmMemoryComponent

generators/angular/templates/src/main/webapp/app/account/password-reset/init/password-reset-init.component.html.ejs
=> [Angular] Simplify template for PasswordResetInitComponent

generators/angular/__snapshots__/generator.spec.ts.snap, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/update/_entityFile_-update.component.ts.ejs, generators/angular/templates/src/main/webapp/app/layouts/navbar/navbar.component.html.ejs, generators/bootstrap-application-base/utils.js
Move authority to adminfolder to don't mix with others entities.
Others small adjusts.
---
=> Move authority to admin client-root-folder.

generators/angular/entity-files-angular.ts, generators/angular/files-angular.js
=> [angular] generate user-management at entities

generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/list/_entityFile_.component.ts.ejs
=> [angular] fix ng-zone warning

generators/liquibase/generator.ts, generators/liquibase/templates/gradle/liquibase.gradle.ejs
Related to https://github.com/jhipster/generator-jhipster/pull/24945
Caused by https://github.com/liquibase/liquibase-parent-pom/issues/127
---
=> fix neo4j liquibase dependencies

generators/client/support/entity-definition.js, generators/client/support/template-utils.js, generators/client/support/template-utils.spec.js
Apply changes made in #25007 to the React & Vue templates.
Resolves #24653  
---
=> Filter relevant model fields in React & Vue

generators/angular/templates/src/main/webapp/app/admin/configuration/configuration.component.html.ejs, generators/angular/templates/src/main/webapp/app/admin/configuration/configuration.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/admin/configuration/configuration.component.ts.ejs
=> [Angular] Signals to handle allBeans beans propertySources

generators/angular/templates/src/main/webapp/app/admin/logs/logs.component.html.ejs, generators/angular/templates/src/main/webapp/app/admin/logs/logs.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/admin/logs/logs.component.ts.ejs
=> [Angular] Signals to handle loggers filteredAndOrderedLoggers

generators/vue/resources/package.json
Fixes https://github.com/jhipster/generator-jhipster/issues/25075
---
=> [vue] downgrade bootswatch

.prettierrc, generators/common/__snapshots__/generator.spec.js.snap, generators/common/templates/.prettierrc.ejs, package-lock.json, package.json
Revert some updates #24898 mandatory for the `3.2.4` version
---
=> Prettier 3.2.5

generators/angular/templates/src/main/webapp/app/layouts/error/error.component.html.ejs, generators/angular/templates/src/main/webapp/app/layouts/error/error.component.ts.ejs
=> [Angular] Signals to handle errorMessage

generators/server/templates/pom.xml.ejs
=> enable logs at surefire tests

generators/angular/templates/src/main/webapp/app/shared/sort/sort.service.ts.ejs
=> [Angular] Sonar: Unnecessary use of conditional expression for default assignment

.github/workflows/angular.yml, .github/workflows/react.yml, .github/workflows/vue.yml
=> execute npm install after backend test and if frontend tests will be executed

generators/server/templates/src/test/java/_package_/IntegrationTest.java.ejs, generators/server/templates/src/test/java/_package_/web/rest/AccountResourceIT.java.ejs, generators/server/templates/src/test/java/_package_/web/rest/AuthenticateControllerIT.java.ejs, generators/server/templates/src/test/java/_package_/web/rest/TestUtil.java.ejs, generators/spring-boot/templates/_global_partials_entity_/it_patch_update.partial.java.ejs, generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/web/rest/UserResourceIT.java.ejs, generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/web/rest/_entityClass_ResourceIT.java.ejs
The serialized object doesn't match the returned one.
---
=> use spring boot injected ObjectMapper to serialize tests.

generators/angular/templates/src/main/webapp/app/admin/user-management/list/user-management.component.ts.ejs, generators/angular/templates/src/main/webapp/app/core/auth/account.service.ts.ejs, generators/angular/templates/src/main/webapp/app/layouts/navbar/navbar.component.ts.ejs, generators/angular/templates/src/main/webapp/app/shared/auth/has-any-authority.directive.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/shared/auth/has-any-authority.directive.ts.ejs
=> add a signal to track current account

generators/maven/templates/.mvn/wrapper/maven-wrapper.properties, generators/spring-boot/files.ts, renovate.json
Related with https://github.com/jhipster/jhipster-lite/issues/8512
---
=> Add renovate configuration to update maven-wrapper

renovate.json
=> Renovate: disable Dependency Dashboard

generators/liquibase/__snapshots__/incremental-liquibase.spec.ts.snap, generators/liquibase/templates/liquibase-changelog-header.ejs, generators/liquibase/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs, generators/liquibase/templates/src/main/resources/config/liquibase/changelog/added_entity_constraints.xml.ejs, generators/liquibase/templates/src/main/resources/config/liquibase/changelog/initial_schema_neo4j.xml.ejs, generators/liquibase/templates/src/main/resources/config/liquibase/changelog/initial_schema_sql.xml.ejs, generators/liquibase/templates/src/main/resources/config/liquibase/changelog/updated_entity.xml.ejs, generators/liquibase/templates/src/main/resources/config/liquibase/changelog/updated_entity_constraints.xml.ejs, generators/liquibase/templates/src/main/resources/config/liquibase/changelog/updated_entity_migrate.xml.ejs
=> add liquibase header partial template

generators/spring-data-relational/generator.ts
=> remove hibernate incubating logs from tests

generators/angular/templates/src/main/webapp/app/admin/user-management/service/user-management.service.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/admin/user-management/service/user-management.service.ts.ejs, generators/react/templates/src/main/webapp/app/modules/administration/user-management/user-management.reducer.ts.ejs, generators/vue/templates/src/main/webapp/app/admin/user-management/user-management.service.ts.ejs
=> fix authorities in user management ui.

generators/angular/entity-files-angular.ts, generators/client/generator.js, generators/client/support/filter-entities.ts, generators/client/support/index.ts, generators/react/entity-files-react.js, generators/vue/entity-files-vue.js
=> add filter entities utilities.

cli/cli.spec.mts, package-lock.json, package.json
=> Commander 12.0.0

generators/java/templates/src/test/java/_package_/domain/AssertUtils.java.ejs, generators/server/templates/src/test/java/_package_/web/rest/TestUtil.java.ejs, generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/web/rest/_entityClass_ResourceIT.java.ejs
Related to https://github.com/jhipster/generator-jhipster/issues/25137
---
=> fix partialUpdate test code smells

generators/angular/templates/src/main/webapp/app/shared/alert/alert-error.component.ts.ejs
Related to #25137 
Fix https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AYLgOGNeWE-guYVzrIdf
---
=> Sonar: Refactor this function to reduce its Cognitive Complexity from 30 to the 15 allowed

generators/server/templates/src/main/java/_package_/_entityPackage_/service/dto/_dtoClass_.java.ejs
https://sonarcloud.io/project/issues?resolved=false&id=jhipster-sample-application&open=AYT5NJtvoub84d7atcPi
---
=> fix unused import code smell

generators/bootstrap/support/eslint-transform.ts, generators/bootstrap/support/eslint-worker.js, generators/bootstrap/support/java-lint-worker.js, generators/bootstrap/support/java-unused-imports-transform.ts, generators/bootstrap/support/prettier-support.ts, generators/bootstrap/support/prettier-worker.js, package-lock.json, package.json
=> move eslint/prettier tasks to workers

generators/app/generator.js
Allows to generate all projects with custom defaults.
---
=> load default config from global config

.github/actions/build-matrix/action.yml, .github/workflows/generator.yml, generators/generator-constants.js
=> Node 20.11.1

cli/cli.spec.mts
=> revert commander test to test implicit negative flags

generators/app/README.md, generators/liquibase/README.md, generators/server/README.md, generators/spring-boot/README.md, generators/spring-data-elasticsearch/README.md, generators/spring-data-relational/README.md, generators/upgrade/README.md
=> improve upgrade readme

README.md
Related to https://github.com/jhipster/generator-jhipster/issues/25231
---
=> add sample code-smells badge

generators/base/support/needles.ts, generators/liquibase/generator.ts, generators/liquibase/templates/src/main/java/_package_/config/LiquibaseConfiguration.java.ejs, generators/server/support/__snapshots__/needles.spec.ts.snap, generators/server/support/needles.spec.ts, generators/server/support/needles.ts, generators/server/templates/src/main/java/_package_/config/ApplicationProperties.java.ejs, generators/server/types.d.ts, generators/spring-boot/generator.ts
Related to https://github.com/jhipster/generator-jhipster/issues/25231
Fixes https://sonarcloud.io/project/issues?open=AXZiLoQ8RzWdFtSYLf2s&id=jhipster-sample-application.
---
=> add liquibase async-start property to ApplicationProperties

generators/liquibase/templates/src/main/java/_package_/config/LiquibaseConfiguration.java.ejs
Fix https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=jhipster-sample-application&open=AY25zOpQzYQvoSsZXYD5&tab=code
---
=> Sonar: Use a primitive boolean expression

generators/client/templates/src/main/webapp/index.html.ejs
Fixes https://sonarcloud.io/project/issues?open=AW7IFzV9zz0zKTgJXRn-&id=jhipster-sample-application
Related to https://github.com/jhipster/generator-jhipster/issues/25231.
---
=> cleanup index.html

generators/common/__snapshots__/generator.spec.js.snap, generators/common/templates/sonar-project.properties.ejs, generators/server/templates/src/main/resources/logback-spring.xml.ejs
Related to https://github.com/jhipster/generator-jhipster/issues/25231
---
=> Disable sonar rule S125 at logback-spring.xml

generators/base-application/support/prepare-relationship.js, generators/liquibase/generator.ts, generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/web/rest/_entityClass_ResourceIT.java.ejs, generators/spring-data-relational/templates/src/main/java/_package_/_entityPackage_/domain/_persistClass_.java.jhi.jakarta_persistence.ejs
=> reorganize relationship preparation

generators/server/templates/src/main/java/_package_/security/PersistentTokenRememberMeServices.java.ejs
Fixed closing HTML list item element.
---
=> fix typo in Javadoc

generators/generate-blueprint/__snapshots__/generator.spec.js.snap, generators/generate-blueprint/constants.js, generators/generate-blueprint/generator.js, generators/generate-blueprint/templates/.eslintrc.json.ejs, generators/init/files.js, generators/init/generator.js
- default to js extension.
- drop airbnb-base dependency. It's not good for esm.
- fix readme generation
---
=> improve generate-blueprint defaults.

generators/server/types.d.ts, generators/spring-boot/generator.ts
=> add addApplicationPropertiesProperty needle

DEVELOPMENT.md
=> Typo: Runnning=>Running

generators/client/resources/package.json
=> bump cypress 13.6.6

generators/jdl/internal/utils.js
=> fix new application logic for jdl without applications

generators/base-application/support/prepare-relationship.js, generators/generate-blueprint/templates/.blueprint/generate-sample/generator.mjs.ejs, generators/jdl/generator.ts
=> improve relatedField validation and others adjusts

generators/bootstrap/generator.ts
=> don't override a file with a partial template

generators/angular/templates/src/main/webapp/app/core/interceptor/auth-expired.interceptor.ts.ejs
Fixes https://github.com/jhipster/generator-jhipster/issues/24608
---
=> clear session for non authenticated

generators/angular/templates/src/main/webapp/app/admin/user-management/delete/user-management-delete-dialog.component.html.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/delete/_entityFile_-delete-dialog.component.html.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/detail/_entityFile_-detail.component.html.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/list/_entityFile_.component.html.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/update/_entityFile_-update.component.html.ejs, generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_-details.vue.ejs, generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_-update.vue.ejs, generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_.vue.ejs
Related to https://github.com/jhipster/generator-jhipster/issues/25231.
---
=> fix new sonar issues

generators/angular/templates/src/main/webapp/app/account/sessions/sessions.service.ts.ejs, generators/react/templates/src/main/webapp/app/modules/account/sessions/sessions.reducer.ts.ejs, generators/vue/templates/src/main/webapp/app/account/sessions/sessions.component.ts.ejs
fixes https://github.com/jhipster/generator-jhipster/issues/25297.
---
=> fix sessions api

generators/angular/templates/src/main/webapp/app/admin/user-management/delete/user-management-delete-dialog.component.html.ejs, generators/angular/templates/src/main/webapp/app/admin/user-management/update/user-management-update.component.html.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/delete/_entityFile_-delete-dialog.component.html.ejs
Related to https://github.com/jhipster/generator-jhipster/issues/25231.
---
=> fix user-management sonar issues and adjust modal close button.

generators/bootstrap/support/eslint-transform.ts, generators/bootstrap/support/java-unused-imports-transform.ts, generators/bootstrap/support/prettier-support.ts, package-lock.json, package.json
=> bump Piscina 4.4.0

generators/generate-blueprint/templates/generators/generator/generator.spec.mjs.ejs, test-integration/generate-blueprint-samples/default/.yo-rc.json
=> Jdl blueprint fix 25385

generators/server/templates/src/main/java/_package_/config/WebConfigurer.java.ejs, generators/server/templates/src/test/java/_package_/security/jwt/JwtAuthenticationTestUtils.java.ejs
=> Fix: The declaration exception is never thrown

generators/server/templates/src/main/java/_package_/config/SecurityConfiguration_imperative.java.ejs, generators/server/templates/src/main/java/_package_/config/SecurityConfiguration_reactive.java.ejs
=> Fix: Unnecessarly qualified statically imported element

generators/angular/resources/package.json, generators/react/resources/package.json, generators/vue/resources/package.json, package-lock.json, package.json
=> bump @types/node

generators/server/templates/src/main/java/_package_/config/StaticResourcesWebConfiguration.java.ejs
=> Clean code: Redundant new expression in constant array creation

generators/languages/generator.js
=> adjust loading supportedLanguages in language generator

.github/actions/build-matrix/action.yml, .github/workflows/devserver.yml, generators/angular/templates/package.json.ejs, generators/base/generator.ts, generators/languages/generator.js
Fixes https://github.com/jhipster/generator-jhipster/issues/25489
Closes https://github.com/jhipster/generator-jhipster/pull/25490
---
=> Pass arguments to blueprints 

generators/gradle/generator.ts, generators/gradle/internal/needles.ts, generators/gradle/needles.spec.ts, generators/gradle/templates/gradle/libs.versions.toml.ejs, generators/gradle/types.d.ts, generators/server/templates/build.gradle.ejs, generators/server/templates/gradle.properties.ejs, generators/server/templates/pom.xml.ejs, generators/server/templates/settings.gradle.ejs, generators/spring-boot/generator.ts
- improve gradle needle api
- use version catalog
---
=> inject jhipster-bom gradle/maven dependencies using api.

generators/gradle/constants.js
https://docs.gradle.org/8.6/release-notes.html
---
=> Upgrade to Gradle 8.6

generators/spring-data-neo4j/templates/src/main/java/_package_/_entityPackage_/repository/_entityClass_Repository.java.ejs
Fixes issue found when testing 8.2. https://github.com/jhipster/generator-jhipster/issues/25259#issuecomment-2004435865
---
=> Fix Neo4j reactive implementation

generators/server/support/relationship.ts
=> ignore addEntitiesOtherRelationships for builtIn entities

.github/dependabot.yml, generators/react/resources/package.json, generators/vue/resources/package.json
Fix module federation warning
---
=> downgrade module federation utils

generators/gradle/generator.ts, generators/gradle/internal/needles.ts, generators/gradle/types.d.ts, generators/java/generator.ts, generators/java/support/artifacts.ts, generators/java/types.d.ts, generators/maven/support/pom-store.ts, generators/spring-boot/generator.ts, generators/spring-cache/generator.ts, generators/spring-cache/internal/dependencies.ts, generators/spring-data-relational/internal/dependencies.ts
=> add JavaDependencyVersion and addJavaDefinition abstraction

generators/feign-client/templates/src/main/java/_package_/client/AuthorizedFeignClient.java.ejs, test-integration/scripts/99-build-changes.sh
=> Resolve deprecation warning for annotation attribute overrides in AuthorizedFeignClient

generators/generator-constants.js
=> Update @openapitools/openapi-generator-cli version to 2.13.1

.github/workflows/devserver.yml, generators/generator-constants.js, test-integration/scripts/99-build-changes.sh
=> switch to node 20

generators/base-application/support/prepare-entity.ts
Fixes https://github.com/jhipster/generator-jhipster/issues/25550
---
=> adjust builtIn entities for microservices

package.json
related to https://github.com/jhipster/generator-jhipster/issues/25259#issuecomment-2009840878.
---
=> add prebuild script

package.json
=> add postbuild script

.github/actions/setup/action.yml, generators/generator-constants.js
=> Update jhipster-bom version to 8.3.0-SNAPSHOT

generators/bootstrap/internal/transform-utils.js, generators/bootstrap/internal/transform-utils.ts, generators/bootstrap/support/eslint-transform.ts, generators/bootstrap/support/java-unused-imports-transform.ts, generators/bootstrap/support/prettier-worker.js
=> add line numbers to transform errors

generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/web/rest/_entityClass_ResourceIT.java.ejs, generators/spring-data-elasticsearch/generator.js
Related to https://github.com/jhipster/generator-jhipster/issues/25565.
---
=> drop commons-collections4 dependency

generators/vue/templates/src/main/webapp/app/account/account.service.spec.ts.ejs, generators/vue/templates/src/main/webapp/app/account/account.service.ts.ejs
=> [Vue] Fix login menu

generators/angular/templates/src/main/webapp/app/admin/tracker/tracker.component.html.ejs, generators/angular/templates/src/main/webapp/app/admin/tracker/tracker.component.ts.ejs, generators/angular/templates/src/main/webapp/app/core/tracker/tracker.service.ts.ejs, generators/cypress/templates/src/test/javascript/cypress/e2e/administration/administration.cy.ts.ejs, generators/react/templates/src/main/webapp/app/modules/administration/tracker/tracker.tsx.ejs, generators/vue/resources/package.json, generators/vue/templates/package.json.ejs, generators/vue/templates/src/main/webapp/app/admin/tracker/tracker.service.ts.ejs, generators/vue/templates/src/main/webapp/app/admin/tracker/tracker.vue.ejs, generators/vue/templates/src/main/webapp/app/main.ts.ejs, generators/vue/templates/vite.config.mts.ejs
fixes https://github.com/jhipster/generator-jhipster/issues/25255
---
=> fix vue websocket and add cypress

generators/server/templates/build.gradle.ejs, generators/server/templates/pom.xml.ejs
=> exclude tomcat, undertow is used by default

generators/angular/templates/src/main/webapp/app/admin/user-management/detail/user-management-detail.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/admin/user-management/list/user-management.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/core/auth/account.service.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/detail/_entityFile_-detail.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/list/_entityFile_.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/route/_entityFile_-routing-resolve.service.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/update/_entityFile_-update.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/home/home.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/layouts/main/main.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/layouts/navbar/navbar.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/login/login.component.spec.ts.ejs
https://angular.io/api/router/testing/RouterTestingModule
=> [Angular] RouterTestingModule is deprecated since Angular 17.3

bin/fix-bin.cjs, package.json
fixes https://github.com/jhipster/generator-jhipster/issues/25598
---
=> add fix-bin helper

.github/actions/build-matrix/action.yml, .github/workflows/generator.yml, generators/generator-constants.js
=> Update node version to 20.12.0

generators/server/templates/build.gradle.ejs, generators/server/templates/pom.xml.ejs
It's currently added through jhipster-framework
---
=> include spring-boot-starter-validation in imperative applications

generators/generate-blueprint/__snapshots__/generator.spec.js.snap, generators/generate-blueprint/files.js, generators/generate-blueprint/templates/vitest.test-setup.ts.ejs
=> add vitest.test-setup.ts to generate-blueprint

generators/server/templates/build.gradle.ejs, generators/server/templates/pom.xml.ejs
Depends through jhipster-framework.
---
=> add dependency on starter-aop

generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs, generators/docker/templates/docker/realm-config/jhipster-realm.json.ejs, generators/kubernetes/__snapshots__/kubernetes.spec.ts.snap, generators/kubernetes/templates/keycloak/keycloak-configmap.yml.ejs
=> Keycloak: fix http challenge

generators/angular/templates/src/main/webapp/app/admin/health/modal/health-modal.component.html.ejs
=> [Angular] Fix close button on health modal

generators/angular/support/translate-angular.ts
Closes https://github.com/jhipster/generator-jhipster/pull/25683
---
=> fix warning

generators/angular/templates/src/main/webapp/app/admin/metrics/blocks/jvm-memory/jvm-memory.component.html.ejs, generators/angular/templates/src/main/webapp/app/admin/metrics/blocks/jvm-memory/jvm-memory.component.ts.ejs, generators/angular/templates/src/main/webapp/app/admin/metrics/blocks/metrics-cache/metrics-cache.component.html.ejs, generators/angular/templates/src/main/webapp/app/admin/metrics/blocks/metrics-cache/metrics-cache.component.ts.ejs, generators/angular/templates/src/main/webapp/app/admin/metrics/blocks/metrics-datasource/metrics-datasource.component.html.ejs, generators/angular/templates/src/main/webapp/app/admin/metrics/blocks/metrics-datasource/metrics-datasource.component.ts.ejs, generators/angular/templates/src/main/webapp/app/admin/metrics/blocks/metrics-endpoints-requests/metrics-endpoints-requests.component.html.ejs, generators/angular/templates/src/main/webapp/app/admin/metrics/blocks/metrics-endpoints-requests/metrics-endpoints-requests.component.ts.ejs, generators/angular/templates/src/main/webapp/app/admin/metrics/blocks/metrics-garbagecollector/metrics-garbagecollector.component.html.ejs, generators/angular/templates/src/main/webapp/app/admin/metrics/blocks/metrics-garbagecollector/metrics-garbagecollector.component.ts.ejs, generators/angular/templates/src/main/webapp/app/admin/metrics/blocks/metrics-request/metrics-request.component.html.ejs, generators/angular/templates/src/main/webapp/app/admin/metrics/blocks/metrics-request/metrics-request.component.ts.ejs, generators/angular/templates/src/main/webapp/app/admin/metrics/blocks/metrics-system/metrics-system.component.html.ejs, generators/angular/templates/src/main/webapp/app/admin/metrics/blocks/metrics-system/metrics-system.component.ts.ejs
=> [Angular] Migrate Input to Signal Input

generators/angular/support/translate-angular.ts, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/delete/_entityFile_-delete-dialog.component.html.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/detail/_entityFile_-detail.component.html.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/list/_entityFile_.component.html.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/update/_entityFile_-update.component.html.ejs, generators/languages/entity-files.js
=> convert entities to new translate api

generators/react/templates/src/main/webapp/app/modules/administration/tracker/tracker.tsx.ejs, test-integration/samples/react-gradle-mysql-es-noi18n-mapsid/.yo-rc.json
=> fix websocket in react and add to test sample

package-lock.json, package.json
Doesn't looks necessary anymore.
---
=> drop hoist workaround

generators/base/support/needles.ts, package-lock.json, package.json
=> drop escape-string-regexp

.github/actions/build-matrix/action.yml, .github/workflows/generator.yml, generators/generator-constants.js
=> Update node version to 20.12.1

generators/angular/templates/src/main/webapp/app/admin/configuration/configuration.service.ts.ejs
Fix https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=jhipster-sample-application&open=AY6gpfuRZCZzLaFHMWKA&tab=code
---
=> Sonar: Add an initial value to this reduce() call

generators/spring-cloud/generators/gateway/generator.spec.ts, generators/spring-cloud/generators/gateway/generator.ts
=> require experimental flag for imperative gateway

generators/statistics.ts, package-lock.json, package.json
=> Dependency adjusts

.github/actions/setup/action.yml, generators/generator-constants.js
=> Update jhipster-bom version to 8.3.1-SNAPSHOT

.github/actions/build-matrix/action.yml, .github/workflows/generator.yml
=> Node 20.12.2 for GitHub actions and workflows

.blueprint/generate-sample/generator.mjs, .github/workflows/angular.yml, .github/workflows/react.yml, .github/workflows/vue.yml, test-integration/integration-test-constants.js, test-integration/scripts/99-write-matrix.js
Partially migrate to jhipster/actions
---
=> use jhipster/actions

generators/server/support/prepare-field.js, generators/server/support/prepare-relationship.ts
Fixes https://github.com/jhipster/generator-jhipster/issues/25729
---
=> add missing propertyApiDescription

generators/vue/templates/vitest.config.mts.ejs
=> fix vite coverage path

.github/actions/cache-java-dependencies/action.yml, .github/actions/setup-generator-jhipster-jit/action.yml
=> adjusts to cache

.github/actions/setup-default-node-java/action.yml
=> drop unused java-version input

.github/workflows/vue.yml
=> fix vue workflow

generators/maven/templates/.mvn/wrapper/maven-wrapper.properties, generators/maven/templates/mvnw, generators/maven/templates/mvnw.cmd
Reverts jhipster/generator-jhipster#25905
=> Revert "chore(deps): update dependency maven-wrapper to v3.3.0"

generators/angular/templates/src/main/webapp/app/account/password-reset/finish/password-reset-finish.component.html.ejs, generators/angular/templates/src/main/webapp/app/account/password-reset/init/password-reset-init.component.html.ejs, generators/angular/templates/src/main/webapp/app/account/password/password.component.html.ejs, generators/angular/templates/src/main/webapp/app/account/register/register.component.html.ejs, generators/angular/templates/src/main/webapp/app/account/settings/settings.component.html.ejs, generators/angular/templates/src/main/webapp/app/admin/user-management/update/user-management-update.component.html.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/update/_entityFile_-update.component.html.ejs, generators/angular/templates/src/main/webapp/app/login/login.component.html.ejs, generators/vue/templates/src/main/webapp/app/account/change-password/change-password.vue.ejs, generators/vue/templates/src/main/webapp/app/account/login-form/login-form.vue.ejs, generators/vue/templates/src/main/webapp/app/account/register/register.vue.ejs, generators/vue/templates/src/main/webapp/app/account/reset-password/finish/reset-password-finish.vue.ejs, generators/vue/templates/src/main/webapp/app/account/reset-password/init/reset-password-init.vue.ejs, generators/vue/templates/src/main/webapp/app/account/settings/settings.vue.ejs, generators/vue/templates/src/main/webapp/app/admin/user-management/user-management-edit.vue.ejs, generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_-update.vue.ejs
Related to https://github.com/jhipster/generator-jhipster/issues/25231
---
=> fix 48 sonar bugs

.blueprint/generate-sample/generator.mjs, test-integration/scripts/99-build-changes.sh
=> adjust project version for sonar

generators/maven/templates/.mvn/wrapper/maven-wrapper.properties, generators/maven/templates/mvnw, generators/maven/templates/mvnw.cmd
Reverts jhipster/generator-jhipster#25953
=> Revert "chore(deps): update dependency maven-wrapper to v3.3.1"

generators/spring-boot/generator.ts
Fixes https://github.com/jhipster/generator-jhipster/issues/17129.
---
=> add warning about non-dto entity relationship with user

generators/java/generators/domain/generator.ts
Fixes https://github.com/jhipster/generator-jhipster/issues/17694
---
=> add tests for java keywords for entities, fields and relationships

generators/spring-boot/generator.ts
Fixes https://github.com/jhipster/generator-jhipster/issues/15822
---
=> add warning about dto and non-dto relationships

generators/react/templates/webpack/webpack.microfrontend.js.jhi.react.ejs, generators/vue/templates/webpack/webpack.microfrontend.js.jhi.vue.ejs
Fixes https://github.com/jhipster/generator-jhipster/issues/20986
---
=> drop unused _I18N_RESOURCES_PREFIX variable

generators/server/generator.js, generators/spring-data-relational/support/h2-reserved-keywords.ts
Fixes https://github.com/jhipster/generator-jhipster/issues/19858
---
=> add reserved words for h2

.github/workflows/angular.yml, .github/workflows/react.yml, .github/workflows/vue.yml
=> replace setup-generator-jhipster-jit

generators/app/__snapshots__/generator.spec.ts.snap, generators/export-jdl/__snapshots__/export-jdl.spec.ts.snap, generators/server/jdl/application-definition.ts, jdl/converters/json-to-jdl-converter.spec.ts, jdl/converters/json-to-jdl-converter.ts, jdl/exporters/jdl-exporter.spec.ts, jdl/integration-test.spec.ts, jdl/models/jdl-object.spec.ts, jdl/models/jdl-object.ts, jdl/models/jdl-relationships.ts, jdl/parsing/lexer/lexer.ts, jdl/validators/jdl-with-application-validator.ts
Related to https://github.com/jhipster/generator-jhipster/pull/25817
---
=> improve jdl serialization and types

generators/docker-compose/__snapshots__/docker-compose.spec.ts.snap, generators/docker/templates/docker/mysql.yml.ejs, generators/kubernetes-knative/__snapshots__/knative.spec.ts.snap, generators/kubernetes/__snapshots__/kubernetes.spec.ts.snap, generators/kubernetes/templates/db/mysql.yml.ejs, generators/server/resources/Dockerfile
=> MySQL 8.4.0

generators/base-application/support/prepare-relationship.js, generators/entity/prompts.js, generators/languages/generator.js, generators/server/support/config.ts, generators/server/support/prepare-entity.js, generators/server/support/relationship.ts
Use of some more constants instead of pure strings
---
=> some more use of constants instead of string

generators/client/command.ts, generators/java/generators/build-tool/command.ts, generators/spring-boot/prompts.js
Fix typos in questions that are asked. Related to https://github.com/jhipster/generator-jhipster/issues/26057#issuecomment-2099530507.
=> Fix typos in questions

generators/base-core/generator.ts, generators/generate-blueprint/command.ts, generators/generate-blueprint/files.js, generators/generate-blueprint/generator.js, generators/generate-blueprint/templates/.blueprint/cli/commands.mjs.ejs, generators/generate-blueprint/templates/.blueprint/generate-sample/command.mjs.ejs, generators/generate-blueprint/templates/.blueprint/generate-sample/generator.mjs.ejs, generators/generate-blueprint/templates/.blueprint/github-build-matrix/build-matrix.mjs.ejs, generators/generate-blueprint/templates/.blueprint/github-build-matrix/generator.mjs.ejs, generators/generate-blueprint/templates/.blueprint/github-build-matrix/index.mjs.ejs, generators/generate-blueprint/templates/.eslintrc.json.ejs, generators/generate-blueprint/templates/README.md.ejs, generators/generate-blueprint/templates/vitest.config.ts.ejs, generators/init/generator.js
=> Updates to generated blueprint.

generators/server/templates/src/main/java/_package_/_entityPackage_/service/dto/_dtoClass_.java.ejs
=> use OAS sdk requiredMode instead of deprecated api

package-lock.json, package.json
Reverts jhipster/generator-jhipster#26083
=> Revert "build(deps-dev): bump octokit from 4.0.1 to 4.0.2"

.devcontainer/devcontainer.json
Ability to run tests within devcontainers
---
=> more params to devcontainer

.devcontainer/devcontainer.json, generators/info/generator.ts, jdl/converters/json-to-jdl-converter.ts, jdl/converters/json-to-jdl-entity-converter.spec.ts, jdl/converters/json-to-jdl-entity-converter.ts, jdl/converters/json-to-jdl-option-converter.ts, jdl/converters/types.ts, jdl/models/abstract-jdl-option.ts, jdl/models/jdl-application.ts, jdl/models/jdl-binary-option.ts, jdl/models/jdl-entity.ts, jdl/models/jdl-field.ts, jdl/models/jdl-object.ts, jdl/models/jdl-options.ts, jdl/models/jdl-unary-option.ts, jdl/readers/json-reader.ts
Improve typesafety of the generators.
Many PRs will come, incrementally improving the type safety of the overall
---
=> Type safety - Incremental step 1

generators/info/generator.ts, package-lock.json, package.json
Fix https://github.com/jhipster/generator-jhipster/pull/26101
---
=> bump execa from 8.0.1 to 9.0.2

generators/spring-boot/generator.ts
Fixes https://github.com/jhipster/generator-jhipster/issues/26077
---
=> ignore dto warning for built in entities.

generators/vue/templates/vite.config.mts.ejs
Recommended by https://github.com/sapphi-red/vite-plugin-static-copy#usage.
---
=> normalize paths for vite-plugin-static-copy

generators/server/generator.js
=> adjust search engine warning.

generators/react/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_-update.tsx.ejs, generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_-details.vue.ejs, generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_-update.vue.ejs, generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_.vue.ejs
Related to https://github.com/jhipster/generator-jhipster/pull/25976#issuecomment-2117035357.
---
=> ignore relationships with embedded entities in react and vue

generators/server/__snapshots__/generator.spec.js.snap, generators/server/templates/src/main/java/_package_/config/Constants.java.ejs, generators/server/templates/src/main/java/_package_/security/SecurityUtils.java.ejs, generators/server/templates/src/main/java/_package_/web/rest/AccountResource_skipUserManagement.java.ejs, generators/spring-boot/files.ts, generators/spring-data-cassandra/__snapshots__/generator.spec.ts.snap, generators/spring-data-elasticsearch/__snapshots__/generator.spec.ts.snap, generators/spring-data-neo4j/__snapshots__/generator.spec.ts.snap
Fixes https://github.com/jhipster/generator-jhipster/issues/26152
---
=> add details to UserVM

test-integration/samples/.jhipster/DocumentBankAccount.json
Drop recently added relationship due to daily build failures.
---
=> drop broken embedded relationship in react and vue

generators/java/generators/domain/templates/src/test/java/_package_/_entityPackage_/domain/_persistClass_Test.java.ejs
Fix
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=jhipster-sample-application&open=AY92SBGOzvwT9Xfig0rR
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=jhipster-sample-application&open=AY92SBGOzvwT9Xfig0rQ
- ...
Before 
After
TODO
---
=> Sonar: Remove the declaration of thrown exception 'java.lang.Exception', as it cannot be thrown from method's body

generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/web/rest/UserResourceIT.java.ejs
Fix:
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=jhipster-sample-application&open=AY92SBKhzvwT9Xfig0rx
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=jhipster-sample-application&open=AY92SBKhzvwT9Xfig0ry
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=jhipster-sample-application&open=AY92SBKhzvwT9Xfig0rz
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=jhipster-sample-application&open=AY92SBKhzvwT9Xfig0r0
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=jhipster-sample-application&open=AY92SBKhzvwT9Xfig0r1
- …
=> Sonar: Rename 'user' which hides the field declared at line 80

generators/server/templates/src/test/java/_package_/web/rest/AccountResourceIT.java.ejs, generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/web/rest/UserResourceIT.java.ejs
Related to https://github.com/jhipster/generator-jhipster/issues/26226.
---
=> don't delete all Users in AccountResourceIT

generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/web/rest/_entityClass_ResourceIT.java.ejs
=> don't deleteAll in entities tests.

generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/web/rest/UserResourceIT.java.ejs
Fix
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=jhipster-sample-application&open=AY-ptPwg_Ij2mB81EP9O
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=jhipster-sample-application&open=AY-ptPwg_Ij2mB81EP9P
---
=> Sonar: Remove this unused 'databaseSizeBeforeCreate' local variable

generators/spring-boot/generator.ts
Follow up to https://github.com/jhipster/generator-jhipster/pull/26271
Fix daily builds https://github.com/hipster-labs/jhipster-daily-builds/actions/runs/9245261150
---
=> adjust to neo4j

generators/angular/templates/src/main/webapp/app/account/password-reset/finish/password-reset-finish.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/account/password-reset/finish/password-reset-finish.component.ts.ejs, generators/angular/templates/src/main/webapp/app/account/password-reset/init/password-reset-init.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/account/password-reset/init/password-reset-init.component.ts.ejs, generators/angular/templates/src/main/webapp/app/account/register/register.component.ts.ejs
=> [Angular] Use viewChild signal

generators/spring-data-relational/templates/src/test/java/_package_/config/SqlTestContainersSpringContextCustomizerFactory.java.ejs
Fix https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=jhipster-sample-application&open=AY92SBW7zvwT9Xfig0tO
---
=> Sonar: This block of commented-out lines of code should be removed

generators/angular/templates/src/main/webapp/app/core/auth/user-route-access.service.ts.ejs
=> [Angular] Remove useless space

generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/detail/_entityFile_-detail.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/route/_entityFile_-routing-resolve.service.spec.ts.ejs, generators/base-application/generator.spec.ts, generators/vue/templates/src/main/webapp/app/admin/tracker/tracker.service.spec.ts.ejs, generators/vue/templates/src/main/webapp/app/shared/alert/alert.service.spec.ts.ejs, generators/vue/templates/src/main/webapp/app/shared/data/data-utils.service.spec.ts.ejs
=> Jest: toBeCalledWith is deprecated

generators/server/templates/src/main/java/_package_/service/dto/UserDTO.java.ejs, generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/web/rest/PublicUserResourceIT.java.ejs
=> rework PublicUserResourceIT to don’t depend on User order

generators/base/blueprints.spec.ts, generators/base/generator.ts, generators/generate-blueprint/generator.js
Fixes https://github.com/jhipster/generator-jhipster/issues/26263
---
=> check blueprints using engines

generators/angular/templates/src/main/webapp/app/shared/sort/sort-by.directive.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/shared/sort/sort-by.directive.ts.ejs
=> [Angular] Use signal contentChild

generators/angular/templates/src/main/webapp/app/core/auth/account.service.spec.ts.ejs
=> [Angular] Fix deprecated method (angular/core/testing)

generators/java/generators/bootstrap/generator.ts, generators/java/types.d.ts, generators/server/types.d.ts, generators/spring-boot/generator.ts
=> add editJavaFile

generators/docker-compose/__snapshots__/docker-compose.spec.ts.snap, generators/docker/templates/docker/mariadb.yml.ejs, generators/server/resources/Dockerfile
=> Upgrade MariaDB 11.4.2

generators/generate-blueprint/generator.js
=> ignore files in blueprints.

generators/docker-compose/__snapshots__/docker-compose.spec.ts.snap, generators/docker/templates/docker/mysql.yml.ejs, generators/kubernetes-knative/__snapshots__/knative.spec.ts.snap, generators/kubernetes/__snapshots__/kubernetes.spec.ts.snap, generators/kubernetes/templates/db/mysql.yml.ejs
=> Fix MySQL 8.4.0 so it starts in Docker

.blueprint/from-issue/generator.mts, generators/generate-blueprint/files.js, generators/generate-blueprint/templates/.blueprint/github-build-matrix/generator.mjs.ejs, generators/generate-blueprint/templates/.github/workflows/build-cache.yml.ejs, generators/generate-blueprint/templates/.github/workflows/samples.yml.ejs
=> improvements to blueprints

generators/base-core/generator.ts
=> fix load config of generator scope

generators/angular/entity-files-angular.ts, generators/base/types.d.ts, generators/bootstrap-application-client/generator.ts, generators/client/generator.js, generators/react/entity-files-react.js, generators/vue/entity-files-vue.js
=> allow blueprints to override filterEntitiesForClient

generators/server/resources/gradle/libs.versions.toml, generators/server/templates/src/main/resources/config/application.yml.ejs, generators/server/templates/src/test/resources/config/application.yml.ejs
=> Upgrade mongock-bom 5.4.3

generators/client/templates/src/main/webapp/index.html.ejs, generators/react/templates/src/main/webapp/app/app.tsx.ejs, generators/react/templates/src/main/webapp/app/config/translation.ts.ejs, generators/react/templates/src/main/webapp/app/shared/layout/header/header.tsx.ejs
Fixes #26400
Closes https://github.com/jhipster/generator-jhipster/pull/26407
---
=> Fix initial text direction setting

generators/server/resources/gradle/libs.versions.toml, generators/server/templates/src/main/resources/config/application.yml.ejs, generators/server/templates/src/test/resources/config/application.yml.ejs
Revert some updates from `5.4.3` https://github.com/jhipster/generator-jhipster/commit/66ea57b916a34fa48408b629e3f55db3114aa78d
---
=> Upgrade mongock-bom 5.4.4

generators/client/templates/.eslintignore.ejs
Fixes https://github.com/jhipster/generator-jhipster/issues/26450
---
=> cleanup .eslintignore

generators/angular/templates/src/main/webapp/app/app.component.ts.ejs, generators/angular/templates/src/main/webapp/app/app.config.ts.ejs
Fix:
- https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&id=jhipster-sample-application&open=AZAmY_KIpkzo1MOvd4ea
- https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&id=jhipster-sample-application&open=AZAmY_KIpkzo1MOvd4eb
---
=> [Angular] Sonar: HttpClientModule is deprecated

generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/list/_entityFile_.component.ts.ejs
Fix:
- https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&id=jhipster-sample-application&open=AZAmY-26pkzo1MOvd4eY
- https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&id=jhipster-sample-application&open=AZAmY-26pkzo1MOvd4eZ
- https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&id=jhipster-sample-application&open=AZAmY-sspkzo1MOvd4eW
- https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&id=jhipster-sample-application&open=AZAmY-sspkzo1MOvd4eX
- https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&id=jhipster-sample-application&open=AZAmY-ngpkzo1MOvd4eU
- https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&id=jhipster-sample-application&open=AZAmY-ngpkzo1MOvd4eV …
=> [Angular] Sonar: InfiniteScrollModule is deprecated

.github/dependabot.yml
=> add vue-eslint dependabot group

cli/commands.mjs, cli/program.mjs, generators/base/__snapshots__/generator.spec.ts.snap
Related to https://github.com/jhipster/jhipster.github.io/pull/1335#issuecomment-2179271517
---
=> don't show removed commands in help

package-lock.json, package.json
Reverts https://github.com/jhipster/generator-jhipster/pull/26496.
---
=> revert typescript to 5.4.5

.github/workflows/auto-merge.yml
Related to https://github.com/jhipster/generator-jhipster/pull/26509
---
=> disable auto merge for typescript

generators/angular/templates/src/main/webapp/content/scss/global.scss.ejs
=> [Angular] Fix input fields style on Bootswatch Quartz theme

generators/angular/templates/src/main/webapp/app/core/util/alert.service.spec.ts.ejs
=> Angular: Rename Jhipster to JHipster

generators/init/resources/package.json
=> bump husky and lint-staged version in init generator

cli/program.mjs, generators/base-core/generator.ts, generators/base/api.d.ts, generators/base/shared-data.ts, generators/base/types.d.ts, generators/spring-cloud/generators/gateway/command.ts, testing/helpers.ts
See each commit
Related to https://github.com/jhipster/generator-jhipster/issues/26471
---
=> Internal improvements

.blueprint/generate-sample/generator.mjs, generators/base-core/generator.ts, generators/base/api.d.ts, generators/base/generator.ts, generators/bootstrap/generator.ts, generators/ci-cd/command.ts, lib/internal/config-def.ts
Add a feature to run common command handling without manual declaration.
This will reduce duplicated code.
---
=> add queueCommandTasks feature

generators/liquibase/templates/src/main/java/_package_/config/LiquibaseConfiguration.java.ejs
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/env/Environment.html#acceptsProfiles(org.springframework.core.env.Profiles)
=> acceptProfiles is deprecated

generators/angular/templates/webpack/proxy.conf.js.ejs
=> Local variables should not be declared and then immediately returned or thrown

generators/gatling/templates/src/test/java/gatling/simulations/_entityClass_GatlingTest.java.ejs
Fix:
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=jhipster-sample-application&open=AZBahc7h7zsW3EZMzl1R
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=jhipster-sample-application&open=AZBahc7h7zsW3EZMzl1S
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=jhipster-sample-application&open=AZBahc7h7zsW3EZMzl1T
- ...
---
=> Sonar: Rename this field to match the regular expression

generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/web/rest/UserResourceIT.java.ejs
Fix:
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=jhipster-sample-application&open=AZBahc0Y7zsW3EZMzlzX
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=jhipster-sample-application&open=AZBahc0Y7zsW3EZMzlzY
---
=> Sonar: Remove this unused  private field

generators/java/generators/domain/templates/src/test/java/_package_/_entityPackage_/domain/_persistClass_Asserts.java.ejs
Fix:
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=jhipster-sample-application&open=AZBahcwp7zsW3EZMzly1
- ...
---
=> Sonar: Add a nested comment

generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/web/rest/_entityClass_ResourceIT.java.ejs
Fix:
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=jhipster-sample-application&open=AZBklDKfH9mGYNNa5iw6
---
=> Sonar: Remove this unused 'random' private field

generators/client/types.d.ts, generators/init/__snapshots__/generator.spec.ts.snap, generators/init/generator.js, generators/init/generator.spec.ts, generators/javascript/generators/bootstrap/__snapshots__/generator.spec.ts.snap, generators/javascript/generators/bootstrap/command.ts, generators/javascript/generators/bootstrap/generator.spec.ts, generators/javascript/generators/bootstrap/generator.ts, generators/javascript/generators/bootstrap/index.ts, generators/javascript/generators/bootstrap/templates/package.json.ejs, generators/javascript/types.d.ts
=> add javascript:bootstrap generator

generators/server/templates/src/main/java/_package_/web/rest/AccountResource_oauth2.java.ejs
=> Unnecessary SuppressWarning annotations in generated code

generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/web/rest/_entityClass_ResourceIT.java.ejs
Reverts jhipster/generator-jhipster#26583
=> Revert "Sonar: Immediately return this expression instead of assigning it to the temporary variable"

generators/generate-blueprint/__snapshots__/generator.spec.js.snap, generators/generate-blueprint/files.js, generators/generate-blueprint/generator.js, generators/generate-blueprint/templates/eslint.config.js.jhi.blueprint.ejs, generators/init/generator.js, generators/init/generator.spec.ts, generators/javascript/generators/eslint/__snapshots__/generator.spec.ts.snap, generators/javascript/generators/eslint/command.ts, generators/javascript/generators/eslint/generator.spec.ts, generators/javascript/generators/eslint/generator.ts, generators/javascript/generators/eslint/index.ts, generators/javascript/generators/eslint/templates/eslint.config.js.jhi.ejs, generators/javascript/resources/package.json, generators/javascript/types.d.ts
Related to https://github.com/jhipster/generator-jhipster/issues/26471.
---
=> add javascript:eslint generator

generators/cucumber/templates/src/test/java/_package_/cucumber/CucumberIT.java.ejs
https://github.com/cucumber/cucumber-jvm/blob/main/CHANGELOG.md
---
=> Deprecated @Cucumber

generators/angular/templates/src/main/webapp/app/layouts/error/error.component.html.ejs
=> [Angular] Referencing the conditional expression's result

generators/angular/templates/src/main/webapp/app/admin/configuration/configuration.component.ts.ejs
=> [Angular] Reorganize imports

generators/angular/templates/src/main/webapp/content/scss/global.scss.ejs
=> [Angular] Unexpected duplicate selector

generators/angular/templates/src/main/webapp/app/layouts/main/main.component.spec.ts.ejs
=> [Angular] Refactor this code to not nest functions more than 4 levels deep

generators/spring-data-mongodb/templates/src/main/java/_package_/_entityPackage_/repository/_entityClass_Repository.java.ejs
=> Remove unnecessary SuppressWarning(unused)

.blueprint/generate-sample/generator.mjs
=> adjusts to generate-sample command

generators/workspaces/generator.js
=> add prettier to monorepository root

generators/base-application/support/prepare-entity.ts, generators/client/support/files.ts, generators/cypress/generator.ts, generators/java/support/files.ts, generators/jdl/generator.ts, generators/spring-data-relational/support/database-data.ts, generators/upgrade/generator.js, package-lock.json, package.json
=> Upgrade Prettier 3.3.3

generators/angular/templates/src/main/webapp/app/account/password-reset/finish/password-reset-finish.component.html.ejs, generators/angular/templates/src/main/webapp/app/account/password-reset/init/password-reset-init.component.html.ejs, generators/angular/templates/src/main/webapp/app/account/password/password.component.html.ejs, generators/angular/templates/src/main/webapp/app/account/register/register.component.html.ejs, generators/angular/templates/src/main/webapp/app/account/settings/settings.component.html.ejs, generators/angular/templates/src/main/webapp/app/admin/metrics/blocks/metrics-datasource/metrics-datasource.component.html.ejs, generators/angular/templates/src/main/webapp/app/admin/metrics/blocks/metrics-garbagecollector/metrics-garbagecollector.component.html.ejs, generators/angular/templates/src/main/webapp/app/admin/metrics/blocks/metrics-request/metrics-request.component.html.ejs, generators/angular/templates/src/main/webapp/app/admin/metrics/blocks/metrics-system/metrics-system.component.html.ejs, generators/angular/templates/src/main/webapp/app/admin/user-management/update/user-management-update.component.html.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/update/_entityFile_-update.component.html.ejs, generators/angular/templates/src/main/webapp/app/home/home.component.html.ejs, generators/angular/templates/src/main/webapp/app/layouts/navbar/navbar.component.html.ejs
https://blog.angular.dev/introducing-let-in-angular-686f9f383f0f
---
=> [Angular] let syntax

test-integration/jdl-samples/mf-ng-eureka-jwt-psql-ehcache/blog-store.jdl
Related to https://github.com/jhipster/generator-jhipster/issues/26707.
---
=> check if roles are passed to jwt microservices

.blueprint/generate-generator/command.mts, .blueprint/generate-generator/generator.mjs, .blueprint/generate-generator/index.mjs, .blueprint/generate-generator/templates/command.ts.ejs, .blueprint/generate-generator/templates/generator.spec.ts.ejs, .blueprint/generate-generator/templates/generator.ts.ejs, .blueprint/generate-generator/templates/index.ts.ejs
simplifies adding new generators.
---
=> add generate-generator dev blueprint command

generators/javascript/resources/package.json, test-integration/scripts/99-build-changes.sh
Fixes some daily builds failures.
Reverts https://github.com/jhipster/generator-jhipster/pull/26748
---
=> revert husky to 9.0.11

generators/docker/files.js, generators/docker/templates/eslint.config.js.jhi.docker.ejs, generators/javascript/generators/eslint/support/index.ts, generators/javascript/generators/eslint/support/tasks.ts, generators/react/generator.js
Related to https://github.com/jhipster/generator-jhipster/issues/26471.
Fixes some daily builds failures.
---
=> ignore js files in docker folder.

generators/languages/templates/entity/i18n/entity_ar-ly.json.ejs
The ar-ly language translator is as same as the en translator. So i have modified it and wrote in the arabic-libya language
=> corrected the ar-ly fron english to ar-ly

generators/react/resources/package.json, generators/react/templates/eslint.config.js.jhi.react.ejs, generators/react/templates/src/main/webapp/app/config/axios-interceptor.ts.ejs, generators/react/templates/src/main/webapp/app/config/notification-middleware.ts.ejs, generators/react/templates/webpack/webpack.common.js.ejs
=> react: update eslint to v9

.github/dependabot.yml
Related to https://github.com/jhipster/generator-jhipster/issues/26471
---
=> dependabot ajusts for eslint 9

generators/gradle/internal/needles.ts
=> fix gradle implementation platform scope

generators/base-application/types.d.ts, generators/base-core/generator.ts, generators/base/support/index.ts, generators/base/support/jhipster7-context.js, generators/java/generators/domain/generator.ts
=> customizeTemplatePaths adjusts

generators/gradle/generator.ts, generators/gradle/internal/needles.ts, generators/gradle/types.d.ts, generators/server/templates/build.gradle.ejs
=> sort build.gradle dependencies

generators/maven/internal/xml-store.ts, generators/maven/support/dependabot-maven.spec.ts, generators/maven/support/dependabot-maven.ts
Related to https://github.com/jhipster/generator-jhipster-micronaut/pull/378?notification_referrer_id=NT_kwDOABWf37MxMTcwODUzNjEwNToxNDE3MTgz#issuecomment-2276576498
---
=> keep xml tag value as string when parsing pom.xml

generators/angular/templates/src/main/webapp/app/admin/gateway/gateway-route.model.ts.ejs, generators/angular/templates/src/main/webapp/app/admin/gateway/gateway.component.html.ejs, generators/angular/templates/src/main/webapp/app/admin/gateway/gateway.component.ts.ejs, generators/angular/templates/src/main/webapp/app/shared/language/translation.module.ts.ejs, generators/angular/templates/webpack/webpack.custom.js.ejs, generators/client/generators/common/templates/src/main/webapp/app/shared/jhipster/headers.ts.ejs, generators/client/generators/common/templates/src/main/webapp/app/shared/jhipster/problem-details.ts.ejs, generators/java/generators/domain/templates/src/test/java/_package_/domain/AssertUtils.java.ejs, generators/spring-boot/templates/src/main/java/_package_/_entityPackage_/service/UserService.java.ejs, generators/spring-boot/templates/src/main/java/_package_/web/rest/AuthenticateController.java.ejs, generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/service/UserServiceIT.java.ejs, generators/spring-cache/templates/src/main/java/_package_/config/CacheConfiguration.java.ejs
=> apply prettier to templates

eslint.config.js, generators/angular/templates/src/main/webapp/app/core/util/data-util.service.ts.ejs, lib/eslint/base.js
Removed rules are deprecated from base and are style related which is handled by prettier.
---
=> add more eslint rules to base

generators/cypress/templates/src/test/javascript/cypress/e2e/entity/_entity_.cy.ts.ejs, generators/cypress/templates/src/test/javascript/cypress/support/oauth2.ts.ejs, test-integration/scripts/99-build-changes.sh
=> Cypress adjusts

generators/liquibase/templates/src/main/java/_package_/config/LiquibaseConfiguration.java.ejs, generators/spring-boot/templates/src/main/java/_package_/_entityPackage_/repository/UserRepository.java.ejs, generators/spring-boot/templates/src/main/java/_package_/_entityPackage_/service/UserService.java.ejs, generators/spring-boot/templates/src/main/java/_package_/_entityPackage_/web/rest/UserResource.java.ejs, generators/spring-boot/templates/src/main/java/_package_/config/Constants.java.ejs, generators/spring-boot/templates/src/main/java/_package_/config/SecurityConfiguration_reactive.java.ejs, generators/spring-boot/templates/src/main/java/_package_/security/DomainUserDetailsService.java.ejs, generators/spring-boot/templates/src/main/java/_package_/security/PersistentTokenRememberMeServices.java.ejs, generators/spring-boot/templates/src/main/java/_package_/security/SecurityUtils.java.ejs, generators/spring-boot/templates/src/main/java/_package_/service/mapper/UserMapper.java.ejs, generators/spring-boot/templates/src/main/java/_package_/web/rest/AccountResource.java.ejs, generators/spring-boot/templates/src/main/java/_package_/web/rest/errors/ErrorConstants.java.ejs, generators/spring-boot/templates/src/main/java/_package_/web/rest/errors/ExceptionTranslator.java.ejs, generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/web/rest/UserResourceIT.java.ejs, generators/spring-boot/templates/src/test/java/_package_/management/SecurityMetersServiceTests.java.ejs, generators/spring-boot/templates/src/test/java/_package_/security/SecurityUtilsUnitTest_imperative.java.ejs, generators/spring-boot/templates/src/test/java/_package_/service/mapper/UserMapperTest.java.ejs, generators/spring-boot/templates/src/test/java/_package_/web/rest/AccountResourceIT.java.ejs, generators/spring-boot/templates/src/test/java/_package_/web/rest/errors/ExceptionTranslatorIT_reactive.java.ejs
=> apply prettier to java templates

generators/react/generator.spec.ts, generators/react/templates/eslint.config.js.jhi.react.ejs, generators/react/templates/jest.conf.js.ejs, generators/react/templates/src/main/webapp/app/app.tsx.ejs, generators/react/templates/src/main/webapp/app/config/error-middleware.ts.ejs, generators/react/templates/src/main/webapp/app/config/notification-middleware.ts.ejs, generators/react/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_-update.tsx.ejs, generators/react/templates/src/main/webapp/app/modules/account/password-reset/password-reset.reducer.ts.ejs, generators/react/templates/src/main/webapp/app/modules/account/register/register.reducer.spec.ts.ejs, generators/react/templates/src/main/webapp/app/modules/administration/administration.reducer.spec.ts.ejs, generators/react/templates/src/main/webapp/app/modules/administration/administration.reducer.ts.ejs, generators/react/templates/src/main/webapp/app/modules/administration/user-management/user-management-detail.tsx.ejs, generators/react/templates/src/main/webapp/app/modules/administration/user-management/user-management.reducer.spec.ts.ejs, generators/react/templates/src/main/webapp/app/modules/administration/user-management/user-management.tsx.ejs, generators/react/templates/src/main/webapp/app/routes.tsx.ejs, generators/react/templates/src/main/webapp/app/shared/DurationFormat.tsx.ejs, generators/react/templates/src/main/webapp/app/shared/layout/header/header-components.tsx.ejs, generators/react/templates/src/main/webapp/app/shared/reducers/authentication.spec.ts.ejs, generators/react/templates/src/main/webapp/app/shared/reducers/reducer.utils.ts.ejs, generators/react/templates/src/main/webapp/app/shared/reducers/user-management.spec.ts.ejs
=> apply eslint/prettier to react templates

generators/cucumber/generator.ts, generators/java/generators/build-tool/generator.ts, generators/java/generators/openapi-generator/__snapshots__/generator.spec.ts.snap, generators/java/generators/openapi-generator/generator.ts, generators/java/types.d.ts, generators/spring-boot/generator.ts, generators/spring-cache/__snapshots__/generator.spec.ts.snap, generators/spring-cache/generator.ts, generators/spring-data-neo4j/generator.ts, generators/spring-data-relational/generator.ts, testing/helpers.ts
A method that supports multiple conditional dependencies in a single call.
Allows  simplified dependencies injection
---
=> add addJavaDefinitions api to sources.

generators/angular/templates/src/main/webapp/app/admin/user-management/detail/user-management-detail.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/admin/user-management/user-management.route.ts.ejs, generators/angular/templates/src/main/webapp/app/app.routes.ts.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_.routes.ts.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/detail/_entityFile_-detail.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/layouts/error/error.route.ts.ejs
Command: `ng g @angular/core:route-lazy-loading`
---
=> [Angular] Angular 18.2.0 migrate route-lazy-loading

generators/angular/templates/src/main/webapp/app/shared/sort/sort-by.directive.ts.ejs
Seen with `ng g @angular/core:inject`
---
=> [Angular] Angular 18.2.0 migrate dependency injection

generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/update/_entityFile_-update.component.html.ejs
=> [Angular] NG8112 @let xxx is declared but its value is never read

generators/spring-data-relational/templates/src/main/resources/.h2.server.properties.ejs
Fixes https://github.com/jhipster/generator-jhipster/issues/26826.
---
=> fix h2 console data

generators/angular/resources/package.json, generators/angular/templates/src/main/webapp/app/layouts/navbar/navbar.component.ts.ejs
=> [Angular] typescript-eslint 8.2.0

generators/docker-compose/__snapshots__/docker-compose.spec.ts.snap, generators/docker-compose/generator.js, jdl/utils/objects/logger.ts, package-lock.json, package.json
- replace js-yaml with yaml
- replace winston with jhipster logger
- drop non used conf
- replace `@types/lodash` with `@types/lodash-es`, we use lodash-es
- override vulnerable ejs from ejs-lint
Closes https://github.com/jhipster/generator-jhipster/security/dependabot/35
---
=> cleanup dependencies

.github/ISSUE_TEMPLATE/BUG_REPORT.md
Make more clear we need `jhipster info` output.
---
=> improve BUG_REPORT.md

generators/app/__snapshots__/generator.spec.ts.snap, generators/generator-constants.js, test-integration/scripts/99-write-matrix.js
We should not support java versions that are not officially supported.
---
=> adjust supported java versions to official support

generators/app/__snapshots__/generator.spec.ts.snap, generators/java/generators/bootstrap/generator.ts, generators/server/types.d.ts, generators/spring-boot/templates/src/main/java/_package_/web/rest/AccountResource.java.ejs, generators/spring-boot/templates/src/main/java/_package_/web/rest/AccountResource_oauth2.java.ejs, generators/spring-boot/templates/src/main/java/_package_/web/rest/AccountResource_skipUserManagement.java.ejs, generators/spring-boot/templates/src/main/java/_package_/web/rest/AuthenticateController.java.ejs
=> adjust /authenticate api

generators/maven/__snapshots__/needles.spec.ts.snap, generators/maven/internal/pom-sort.ts
=> move org.apache.maven.plugins plugins to the top

.github/workflows/angular.yml, .github/workflows/react.yml, .github/workflows/vue.yml, generators/spring-boot/templates/src/main/java/_package_/web/rest/AccountResource.java.ejs, generators/spring-boot/templates/src/main/java/_package_/web/rest/AccountResource_oauth2.java.ejs, generators/spring-boot/templates/src/main/java/_package_/web/rest/AccountResource_skipUserManagement.java.ejs, generators/spring-boot/templates/src/main/java/_package_/web/rest/AuthenticateController.java.ejs, generators/spring-boot/templates/src/test/java/_package_/security/jwt/TestAuthenticationResource.java.ejs, generators/spring-boot/templates/src/test/java/_package_/web/rest/AccountResourceIT.java.ejs, generators/spring-boot/templates/src/test/java/_package_/web/rest/AccountResourceIT_oauth2.java.ejs, generators/spring-boot/templates/src/test/java/_package_/web/rest/AccountResourceIT_skipUserManagement.java.ejs
=> add produces to /authenticate endpoint

generators/info/generator.ts, generators/workspaces/support/applications-lookup.ts, generators/workspaces/support/index.ts
Fixes https://github.com/jhipster/generator-jhipster/issues/27050
---
=> look for applications in `jhipster info`

generators/angular/resources/package.json, generators/angular/templates/src/main/webapp/app/account/sessions/sessions.component.ts.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/route/_entityFile_-routing-resolve.service.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/shared/filter/filter.model.spec.ts.ejs
=> [Angular] Upgrade typescript-eslint from 8.2.0 to 8.3.0

generators/base/api.d.ts, generators/base/internal/merge-union.d.ts, generators/client/types.d.ts, jdl/jhipster/client-framework-types.ts, jdl/jhipster/test-framework-types.ts
=> add derived properties types using command choices

generators/angular/support/translate-angular.spec.ts, generators/angular/support/translate-angular.ts, generators/languages/support/translate.ts, generators/react/support/translate-react.ts
Fixes https://github.com/jhipster/generator-jhipster/issues/27174
Closes https://github.com/jhipster/generator-jhipster/pull/27190
---
=> fix translation with empty values

generators/javascript/generators/bootstrap/generator.ts, package-lock.json, package.json
=> Upgrade Eslint 9.10.0

generators/spring-boot/templates/build.gradle.ejs
Fix #27244 
Related to https://github.com/jhipster/generator-jhipster/commit/9e945449e446029499c62e44c91f6c2c902c5ced
---
=> Missing com.github.node-gradle.node

generators/spring-boot/templates/build.gradle.ejs
Reverts jhipster/generator-jhipster#27253
=> Revert "Missing com.github.node-gradle.node"

generators/angular/resources/package.json
=> Upgrade Angular 18.2.4

.github/workflows/auto-merge.yml
=> enable typescript auto merge

generators/spring-boot/templates/src/main/resources/logback-spring.xml.ejs
=> Prevent logback from outputting its own status

README.md
Change the first sentence to end in a period.
=> Minor improvement to README.md

generators/liquibase/__snapshots__/incremental-liquibase.spec.ts.snap, package-lock.json, package.json
=> Upgrade faker-js 9

.github/workflows/angular.yml, .github/workflows/react.yml, .github/workflows/vue.yml
=> skip install step if source matches

.github/dependabot.yml
=> enable ignored dependencies

package-lock.json, package.json
=> override `@types/node`

package-lock.json, package.json
=> bump eslint and adjust types.

generators/generate-blueprint/templates/eslint.config.js.jhi.blueprint.ejs, lib/eslint/index.js, package.json
Ignore coverage folder in blueprints
---
=> fix eslint exports

generators/generate-blueprint/command.ts, generators/generate-blueprint/generator.ts
=> generate-blueprint: add recreatePackageLock option

generators/base/generator.ts, generators/generate-blueprint/generator.ts, generators/generate-blueprint/templates/generators/generator/generator.spec.mjs.ejs
Related to https://github.com/jhipster/generator-jhipster/issues/27357
---
=> generate-blueprint: migrate tests to blueprint as array

.github/workflows/auto-merge.yml
Makes history more linear and it's easier to find the PR through history.
---
=> switch auto merge from merge to squash

generators/git/generator.ts
Related to https://github.com/jhipster/generator-jhipster/issues/27433
---
=> git: run commit with --no-verify

generators/client/prompts.ts
Related to https://github.com/jhipster/generator-jhipster/issues/27464
---
=> client: retrieve bootstrap v4 themes for vue

generators/spring-boot/templates/src/main/resources/config/application-dev.yml.ejs, generators/spring-boot/templates/src/main/resources/config/application.yml.ejs
don't generate docker compose integration when:
- no services was detected
Fixes https://github.com/jhipster/generator-jhipster/issues/27435
---
=> spring-boot: adjusts to docker compose integration

generators/vue/generator.ts
=> vue: @module-federation/utilities dependency is gateway only

cli/jhipster-command.mjs, generators/base-application/types.d.ts, generators/project-name/command.ts, generators/project-name/generator.spec.ts, generators/project-name/generator.ts, lib/command/converter.ts, lib/command/types.d.ts, lib/types/application/options.d.ts, lib/types/application/yo-rc.d.ts
=> project-name: make it configurable by options

generators/docker/templates/docker/keycloak.yml.ejs
=> docker: increase keycloak retries

generators/app/generator.spec.ts, generators/base-core/generator.ts, generators/spring-boot/prompts.ts, lib/jdl/core/parsing/validator.ts, package-lock.json, package.json
Allows new version of `@types/lodash`.
---
=> update @yeoman/adapter to v2.0.0

generators/spring-boot/resources/spring-boot-dependencies.pom
=> Add couchmove version

generators/common/__snapshots__/generator.spec.ts.snap, generators/javascript/generators/bootstrap/__snapshots__/generator.spec.ts.snap, generators/javascript/generators/bootstrap/generator.ts
May cause issues with webpack.
---
=> fix: omit package.json type if commonjs

.blueprint/generate-sample/generator.mts, .blueprint/github-build-matrix/command.ts, .blueprint/github-build-matrix/generator.ts, .blueprint/github-build-matrix/samples/dev-server.ts, .blueprint/github-build-matrix/support/git-changes.ts, .blueprint/github-build-matrix/support/github-ci-matrix.ts, .github/workflows/devserver.yml, generators/base-core/generator.ts, generators/vue/templates/package.json.ejs
Enable for react only, vue and angular are not stable.
---
=> reimplement devserver workflow

.blueprint/github-build-matrix/generator.ts
=> enable angular in devserver

generators/base-application/support/prepare-relationship.ts, generators/base-application/support/task-type-inference.ts, generators/base-workspaces/generator.ts, generators/base/api.d.ts, generators/bootstrap-application-base/generator.ts, generators/bootstrap-workspaces/command.ts, generators/bootstrap-workspaces/generator.ts, generators/bootstrap-workspaces/index.ts, generators/client/generator.ts, generators/languages/entity-files.ts, generators/languages/generator.ts, generators/server/generator.ts, generators/workspaces/generator.ts, lib/application/field-types.ts, lib/types/application/entity.d.ts, lib/types/application/relationship.d.ts, lib/types/base/entity.d.ts
=> internal: types adjusts

lib/jhipster/default-application-options.ts, test-integration/samples/vue-session-cassandra-fr/.yo-rc.json
Hibernate cache depends on cacheProvider and databaseType postponed defaults calculation.
Related to https://github.com/jhipster/generator-jhipster/issues/25875
---
=> internal: cacheProvider defaults adjusts

generators/server/generator.ts
Related to https://github.com/jhipster/generator-jhipster/issues/25875
---
=> server: increase keycloak wait due to MacOS

.github/workflows/react.yml, .github/workflows/vue.yml
=> switch react and vue workflows to github-build-matrix

.github/workflows/angular.yml, .github/workflows/devserver.yml, .github/workflows/docker-compose-integration.yml, .github/workflows/generator-database-changelog-liquibase.yml, .github/workflows/generator-generate-blueprint.yml, .github/workflows/generator.yml, .github/workflows/generators.yml, .github/workflows/issue-check.yml, .github/workflows/react.yml, .github/workflows/vue.yml
=> force color in ci workflows

generators/spring-boot/templates/src/main/java/_package_/domain/User.java.ejs, generators/spring-data-relational/templates/src/main/java/_package_/_entityPackage_/domain/_persistClass_.java.jhi.spring_data_persistable.ejs, generators/spring-data-relational/templates/src/main/java/_package_/_entityPackage_/domain/_persistClass_.java.jhi.spring_data_reactive.ejs
=> Avoid isPersisted being saved in elasticsearch index

lib/jdl/core/linters/relationship-linter.ts, lib/jdl/core/linters/rules.ts, package-lock.json, package.json
=> Upgrade typescript-eslint from 8.11.0 to 8.12.1

generators/angular/resources/package.json, generators/angular/templates/src/main/webapp/app/admin/health/health.model.ts.ejs, generators/angular/templates/src/main/webapp/app/admin/metrics/metrics.model.ts.ejs
=> [Angular] Upgrade typescript-eslint from 8.11.0 to 8.12.1

.github/actions/sonar/action.yml, generators/common/__snapshots__/generator.spec.ts.snap, generators/common/templates/sonar-project.properties.ejs
=> sonar: ignore cycle issue for entities

generators/java/generators/graalvm/generator.ts, generators/java/generators/graalvm/templates/gradle/native.gradle.ejs, generators/spring-boot/templates/src/main/java/_package_/web/rest/LogoutResource_imperative.java.ejs, generators/spring-boot/templates/src/main/java/_package_/web/rest/LogoutResource_reactive.java.ejs, generators/spring-data-relational/generator.ts
Related to https://github.com/jhipster/generator-jhipster/issues/27739.
---
=> graalvm: adjusts

generators/angular/support/translate-angular.spec.ts, generators/angular/support/translate-angular.ts, generators/base/types.d.ts, generators/languages/generator.ts, generators/languages/support/translate.ts, generators/react/generator.ts, generators/react/support/translate-react.spec.ts, generators/react/support/translate-react.ts, generators/vue/support/translate-vue.spec.ts, generators/vue/support/translate-vue.ts, lib/types/base/translation.d.ts
=> add GetWebappTranslationCallback type

generators/react/files-react.ts, generators/react/generator.ts, generators/react/templates/src/main/webapp/app/shared/layout/header/header.spec.tsx.ejs, generators/react/templates/src/main/webapp/microfrontends/entities-menu.tsx.ejs, generators/react/templates/src/main/webapp/microfrontends/entities-routes.tsx.ejs, generators/react/templates/tsconfig.test.json.ejs
=> react: use mock in mf test

generators/liquibase/generator.ts, generators/spring-boot/generator.ts, generators/spring-boot/templates/settings.gradle.ejs
=> spring-boot: load liquibase.version property

.github/dependabot.yml
=> dependabot: add ngx-translate group

generators/angular/__snapshots__/generator.spec.ts.snap, generators/angular/generator.spec.ts, generators/angular/generator.ts, generators/client/generator.ts, generators/client/support/config.ts, generators/cypress/__snapshots__/generator.spec.ts.snap, generators/cypress/generator.spec.ts, generators/react/__snapshots__/generator.spec.ts.snap, generators/react/generator.spec.ts, generators/vue/__snapshots__/generator.spec.ts.snap, generators/vue/generator.spec.ts, test-integration/samples/ng-h2mem-ws-nol2/.yo-rc.json
Related to https://github.com/jhipster/generator-jhipster/issues/27770
---
=> client: default client source dir to src if clientRootDir is not empty and add to ci sample

generators/client/generator.ts
Related to https://github.com/jhipster/generator-jhipster-nodejs/issues/538
---
=> client: inject workspace instead of override

.github/actions/sonar/action.yml
=> print sonar result to summary

generators/base-application/generator.ts, generators/base-core/generator.ts, generators/base/shared-data.ts, generators/bootstrap-application-base/generator.ts, lib/types/base/entity.d.ts
Fixes https://github.com/jhipster/generator-jhipster/issues/27884
---
=> internal: add relationship microserviceName check

generators/liquibase/generator.ts, generators/liquibase/templates/src/main/java/_package_/config/LiquibaseConfiguration.java.ejs
Move Liquibase's `asyncStart` default value (`true`) from `@Value` annotation to `ApplicationProperties`.
=> Move Liquibase `asyncStart` default value to `ApplicationProperties`

generators/spring-boot/templates/src/main/java/_package_/config/SecurityConfiguration_imperative.java.ejs, generators/spring-boot/templates/src/main/java/_package_/config/SecurityConfiguration_reactive.java.ejs
Related to https://github.com/jhipster/generator-jhipster/pull/27677 and https://github.com/jhipster/generator-jhipster/pull/27959
---
=> spring-boot: revert v3.3.5 workarounds

generators/common/__snapshots__/generator.spec.ts.snap, package-lock.json, package.json
=> Fix upgrade: dot-properties from 1.0.1 to 1.1.0

generators/cypress/templates/src/test/javascript/cypress/e2e/account/register-page.cy.ts.ejs
=> cypress: replace faker deprecated method

generators/spring-boot/templates/pom.xml.ejs
Add workaround to https://github.com/jhipster/generator-jhipster/issues/26603
---
=> spring-boot: set default spring.profiles.active

generators/spring-boot/templates/gradle/profile_dev.gradle.ejs, generators/spring-boot/templates/gradle/profile_prod.gradle.ejs, generators/spring-boot/templates/pom.xml.ejs
=> spring-boot: add test profile in addiction testdev/testprod profiles

generators/angular/__snapshots__/generator.spec.ts.snap, generators/angular/files-angular.ts, generators/angular/generator.ts, generators/angular/templates/angular.json.ejs, generators/angular/templates/src/main/webapp/app/app.config.ts.ejs, generators/angular/templates/src/main/webapp/app/layouts/navbar/navbar.component.ts.ejs, generators/angular/templates/src/main/webapp/declarations.d.ts.ejs, generators/angular/templates/src/main/webapp/environments/environment.development.ts.ejs, generators/angular/templates/src/main/webapp/environments/environment.ts.ejs, generators/angular/templates/webpack/environment.js.ejs, generators/angular/templates/webpack/webpack.custom.js.ejs
Related to https://github.com/jhipster/generator-jhipster/issues/27930
---
=> angular: add environments files

generators/angular/templates/src/main/webapp/app/layouts/main/main.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/shared/auth/has-any-authority.directive.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/shared/language/translate.directive.spec.ts.ejs
Related to https://github.com/jhipster/generator-jhipster/issues/27930
---
=> angular: add standalone to missing components

generators/angular/templates/webpack/webpack.custom.js.ejs, generators/app/__snapshots__/generator.spec.ts.snap, generators/client/command.ts, generators/client/generator.ts, generators/docker-compose/generator.ts, generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs, generators/java/generators/server/generator.ts, generators/kubernetes/__snapshots__/kubernetes.spec.ts.snap, generators/kubernetes/files.ts, generators/kubernetes/templates/keycloak/keycloak-configmap.yml.ejs, generators/react/templates/webpack/webpack.dev.js.ejs, generators/spring-boot/templates/src/main/resources/config/application-dev.yml.ejs, generators/vue/generator.ts, generators/vue/templates/vite.config.mts.ejs, generators/vue/templates/webpack/webpack.dev.js.ejs, lib/jhipster/default-application-options.ts
Related to https://github.com/jhipster/generator-jhipster/issues/27930
---
=> client: adjust devServerPort

generators/languages/prompts.ts
Fixes https://github.com/jhipster/generator-jhipster/issues/28004
---
=> languages: fix languages prompts

generators/java/generators/domain/templates/src/test/java/_package_/domain/AssertUtils.java.ejs
Related to #27962 
Fix https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&issueStatuses=OPEN%2CCONFIRMED&id=jhipster-sample-application&open=AZOKMTSbpQRzGQ3OLsrB
---
=> Sonar: Replace this lambda with method reference

generators/cypress/templates/src/test/javascript/cypress/e2e/entity/_entity_.cy.ts.ejs
Fixes `Remove this unit test or explain why it is ignored.` issues
---
=> cypress: add reason to skipped tests

generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/service/criteria/_entityClass_CriteriaTest.java.ejs, generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/web/rest/_entityClass_ResourceIT.java.ejs
Related to https://github.com/jhipster/generator-jhipster/issues/27962
---
=> spring-boot: sonar fixes

generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/service/UserServiceIT.java.ejs, generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/web/rest/UserResourceIT.java.ejs, generators/spring-boot/templates/src/test/java/_package_/security/DomainUserDetailsServiceIT.java.ejs, generators/spring-boot/templates/src/test/java/_package_/service/mapper/UserMapperTest.java.ejs, generators/spring-boot/templates/src/test/java/_package_/web/rest/AccountResourceIT.java.ejs
=> spring-boot: remove deprecated RandomStringUtils usage

generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/service/criteria/_entityClass_CriteriaTest.java.ejs
=> spring-boot: fix sonar issues

generators/cypress/templates/src/test/javascript/cypress/e2e/entity/_entity_.cy.ts.ejs
=> cypress: adjust skip

generators/spring-boot/templates/src/main/java/_package_/config/SecurityConfiguration_imperative.java.ejs
Fix https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&issueStatuses=OPEN%2CCONFIRMED&id=jhipster-sample-application&open=AZOONpn8ciMbrnoN3sTv 
Related to #27962
---
=> permissionsPolicy is deprecated

lib/jdl/converters/jdl-to-json/jdl-to-json-basic-entity-information-converter.spec.ts, lib/jdl/converters/jdl-to-json/jdl-to-json-option-converter.spec.ts, lib/jdl/converters/jdl-to-json/jdl-with-applications-to-json-converter.spec.ts, lib/jdl/converters/jdl-to-json/jdl-without-application-to-json-converter.spec.ts, package-lock.json, package.json
=> Fix upgrade Chai

.github/ISSUE_TEMPLATE/BUG_REPORT_CUSTOM.md
Issues with missing info have been opened.
At more checkboxes to direct people to correct template.
---
=> add more checkboxes to custom issues.

generators/cypress/generator.ts, generators/java/generators/node/generator.ts, generators/java/generators/node/templates/npmw.cmd.ejs, generators/java/generators/node/templates/npmw.ejs, generators/java/generators/server/generator.ts
- only generate build tool specific code in npmw
- npm script adjusts
---
=> script adjusts

generators/angular/templates/src/main/webapp/app/shared/language/translate.directive.ts.ejs
=> [Angular] Migrate to signals (translate.directive.ts)

generators/angular/templates/src/main/webapp/app/shared/filter/filter.component.html.ejs, generators/angular/templates/src/main/webapp/app/shared/filter/filter.component.ts.ejs
=> [Angular] Migrate to signals (filter.component.ts)

package-lock.json, package.json
=> Bump to Rimraf 6

generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/list/_entityFile_.component.html.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/list/_entityFile_.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/list/_entityFile_.component.ts.ejs
Related to https://github.com/jhipster/generator-jhipster/issues/28195
Fixes https://github.com/jhipster/generator-jhipster/issues/28215
---
=> angular: convert entity array to signal

generators/react/templates/src/main/webapp/app/config/notification-middleware.ts.ejs
=> [React] fix spelling of Toast

generators/java/generators/graalvm/internal/constants.ts, renovate.json
Fixes https://github.com/jhipster/generator-jhipster/issues/27958
---
=> graalvm: add graalvm reachability metadata to renovate

.blueprint/from-issue/generator.mts, generators/info/support/extract-info.ts
Related to https://github.com/jhipster/generator-jhipster/issues/27314
---
=> from-issue: add support for entity json files

generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/web/rest/UserResourceIT.java.ejs
=> Remove unused import

generators/spring-boot/templates/src/main/java/_package_/_entityPackage_/web/rest/UserResource.java.ejs
=> Handle import to avoid unused import

generators/angular/templates/src/main/webapp/app/admin/metrics/blocks/metrics-garbagecollector/metrics-garbagecollector.component.html.ejs
Duplicate here https://github.com/jhipster/generator-jhipster/blob/80e53e6bd876ee1e6cfc0757686e25b98b43f2a4/generators/angular/templates/src/main/webapp/app/admin/metrics/blocks/metrics-garbagecollector/metrics-garbagecollector.component.html.ejs#L19
---
=> [Angular] Duplicate id reference

generators/spring-boot/templates/src/main/java/_package_/_entityPackage_/web/rest/UserResource.java.ejs
=> Use a before a consonant sound

generators/angular/templates/src/main/webapp/content/scss/global.scss.ejs
=> Unit of measure px is redundant

generators/angular/templates/src/main/webapp/app/account/password/password-strength-bar/password-strength-bar.component.scss.ejs, generators/react/templates/src/main/webapp/app/shared/layout/password/password-strength-bar.scss.ejs
=> Properties may be safely replaced with margin shorthand

package-lock.json, package.json
https://github.com/jhipster/generator-jhipster/blob/8f7305187a2f6df2592d7cfdadfa15333cdff391/generators/workspaces/support/applications-lookup.ts#L21
Related to https://github.com/jhipster/generator-jhipster/issues/28291
---
=> workspaces: add missing globby dependency

generators/vue/resources/package.json, generators/vue/templates/src/main/webapp/content/scss/vendor.scss.ejs, generators/vue/templates/vite.config.mts.ejs
=> [Vue] Fix upgrade to Vite 6

generators/client/generator.ts, generators/cypress/generator.ts
Fix workaround https://github.com/jhipster/generator-jhipster-nodejs/blob/0cf3d4ec6d4a68b275fc9c33b8ba598a45508a34/generators/cypress/generator.js#L26-L33
Related to https://github.com/jhipster/generator-jhipster/issues/28291.
---
=> cypress: scripts adjusts

generators/generate-blueprint/templates/.blueprint/generate-sample/command.mjs.ejs, generators/generate-blueprint/templates/.blueprint/generate-sample/generator.mjs.ejs
Update samples workflow to latest version.
Fixes https://github.com/jhipster/generator-jhipster/issues/28291
---
=> generate-blueprint: add samplesGroup option

generators/server/resources/pom.xml, generators/spring-boot/templates/src/main/java/_package_/config/WebConfigurer.java.ejs, generators/spring-boot/templates/src/test/java/_package_/config/WebConfigurerTest.java.ejs, generators/spring-boot/templates/src/test/java/_package_/service/MailServiceIT.java.ejs
=> Fix upgrade org.gaul:modernizer-maven-plugin from 2.9.0 to 3.0.0

generators/cypress/templates/src/test/javascript/cypress/support/entity.ts.ejs
=> Sonar: Braces and parentheses should be used consistently with arrow functions

generators/cypress/templates/src/test/javascript/cypress/support/commands.ts.ejs
=> Unused selector

generators/client/templates/src/main/webapp/content/css/loading.css.ejs
=> Redundant measure unit

generators/angular/templates/src/main/webapp/app/account/password-reset/finish/password-reset-finish.component.html.ejs, generators/angular/templates/src/main/webapp/app/account/password-reset/init/password-reset-init.component.html.ejs, generators/angular/templates/src/main/webapp/app/account/register/register.component.html.ejs, generators/angular/templates/src/main/webapp/app/login/login.component.html.ejs
=> [Angular] Remove unused constant

generators/angular/templates/src/main/webapp/app/shared/sort/sort-by.directive.spec.ts.ejs
=> [Angular] Remove unused field

generators/angular/templates/src/main/webapp/app/shared/sort/sort-state.ts.ejs
=> [Angular] Remove unused type alias

generators/angular/templates/src/main/webapp/app/core/util/alert.service.ts.ejs
=> [Angular] Mismatched JSDoc

generators/cypress/templates/src/test/javascript/cypress/support/entity.ts.ejs
=> Local variable is redundant

generators/client/templates/src/main/webapp/swagger-ui/index.html.ejs
=> Unused parameter

generators/react/templates/src/main/webapp/app/app.scss.ejs, generators/react/templates/src/main/webapp/app/shared/layout/header/header.scss.ejs
=> [React] Redundant mesure unit

generators/react/templates/webpack/webpack.common.js.ejs
=> [React] Local variable rules is redundant

generators/react/templates/jest.conf.js.ejs
=> [React] Statement can be simplifiable

generators/client/templates/src/main/webapp/index.html.ejs, generators/client/templates/src/main/webapp/swagger-ui/index.html.ejs
=> Var is used instead of Let/Const

generators/vue/templates/src/main/webapp/app/core/jhi-navbar/jhi-navbar.vue.ejs
=> [Vue] Redundant measure unit

generators/vue/templates/src/main/webapp/app/admin/user-management/user-management-view.component.spec.ts.ejs
=> [Vue] Unused type alias

generators/vue/templates/src/main/webapp/app/account/register/register.component.ts.ejs, generators/vue/templates/src/main/webapp/app/account/reset-password/finish/reset-password-finish.component.ts.ejs, generators/vue/templates/src/main/webapp/app/account/reset-password/init/reset-password-init.component.ts.ejs, generators/vue/templates/src/main/webapp/app/admin/user-management/user-management.component.ts.ejs, generators/vue/templates/src/main/webapp/app/core/ribbon/ribbon.component.ts.ejs
=> [Vue] Unused parameter prop

generators/vue/templates/src/main/webapp/app/account/login.service.ts.ejs, generators/vue/templates/src/main/webapp/app/locale/translation.service.ts.ejs
=> [Vue] Field can be readonly

generators/cypress/templates/src/test/javascript/cypress/support/entity.ts.ejs, generators/docker/templates/docker/jhipster-control-center.yml.ejs, generators/vue/templates/src/main/webapp/app/shared/config/axios-interceptor.spec.ts.ejs
=> Clean code

generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_-details.component.spec.ts.ejs, generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_-update.component.spec.ts.ejs, generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_.component.spec.ts.ejs, generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_.service.spec.ts.ejs, generators/vue/templates/src/main/webapp/app/router/entities.ts.ejs, generators/vue/templates/src/main/webapp/app/router/pages.ts.ejs
=> [Vue] Remove old ref to TSLint

generators/app/support/check-node.ts, generators/base/support/configuration-helpers/options.ts, generators/base/support/contents.ts, generators/base/support/needles.ts, generators/generate-blueprint/constants.ts, generators/maven/support/pom-store.ts, generators/server/support/database.ts, generators/spring-data-relational/support/h2-reserved-keywords.ts, generators/spring-data-relational/support/oracle-reserved-keywords.ts, generators/spring-data-relational/support/postgresql-reserved-keywords.ts, lib/jdl/converters/exporters/applications/jhipster-application-formatter.ts, lib/jdl/core/linters/jdl-linter.ts, lib/jdl/core/models/jdl-enum.ts, test-integration/scripts/99-write-matrix.js
=> Clean code: Braces and parentheses should be used consistently with arrow functions

generators/angular/templates/webpack/webpack.custom.js.ejs
=> [Angular] Fix OAuth2/Keycloak Forces HTTPS Redirects in Development Mode

generators/base-application/generator.ts, generators/base-entity-changes/generator.ts, generators/base-entity-changes/tasks.d.ts, generators/base/shared-data.ts, generators/bootstrap-application-server/generator.ts, generators/liquibase/generator.ts, generators/liquibase/support/prepare-field.ts, generators/server/support/database.ts, lib/types/application/field.d.ts, lib/types/application/tasks.d.ts
Some typescript types in the generator
---
=> Add some more typescript types on generator

generators/base-core/generator.ts, generators/base-workspaces/internal/docker-prompts.ts, generators/react/generator.ts, generators/vue/generator.ts, lib/jdl/converters/validators/jdl-with-application-validator.ts, lib/jdl/converters/validators/jdl-without-application-validator.ts
=> Fix: Mismatched JSDoc and function signature

generators/java/generators/domain/templates/src/main/java/_package_/_entityPackage_/domain/_persistClass_.java.jhi.ejs, generators/react/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_-update.tsx.ejs
=> Unused chars

generators/docker/constants.ts, generators/generator-constants.js, generators/gradle/constants.ts, generators/maven/constants.ts, generators/project-name/constants.ts, lib/jhipster/deployment-options.ts
=> Clean code: remove unused constant

generators/java/types.d.ts, lib/command/support/merge-union.d.ts, lib/command/types.d.ts, lib/types/application/entity.d.ts
=> Clean code: remove unused type alias

generators/angular/resources/package.json
=> [Angular] angular-builders beta to stable version

generators/base/support/jhipster7-context.ts
=> Clean code: can be simplified to true

generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/web/rest/_entityClass_ResourceIT.java.ejs
=> Fix operand

generators/maven/support/dependabot-maven.ts
=> Clean code: unused type

generators/kubernetes-knative/templates/kubectl-apply.sh.ejs, generators/react/templates/src/main/webapp/app/config/translation.ts.ejs
=> Clean code: remove unused parameter

generators/angular/resources/package.json
=> [Angular] bump Angular

generators/angular/templates/src/main/webapp/app/shared/pagination/item-count.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/shared/pagination/item-count.component.ts.ejs
=> [Angular] Migrate to signal (item-count component)

generators/angular/templates/src/main/webapp/app/account/password/password-strength-bar/password-strength-bar.component.ts.ejs
=> [Angular] Migrate to signal (password-strength-bar component)

generators/angular/templates/src/main/webapp/app/shared/auth/has-any-authority.directive.spec.ts.ejs
=> [Angular] Simplify tests

generators/angular/resources/package.json, generators/angular/templates/eslint.config.js.jhi.angular.ejs
=> [Angular] Upgrade typescript-eslint 8.20.0

generators/angular/resources/package.json
=> [Angular] Upgrade Typescript 5.7.3

generators/client/templates/src/main/webapp/swagger-ui/index.html.ejs
=> Sonar: var is used instead of let/const

generators/angular/templates/src/main/webapp/app/admin/metrics/blocks/metrics-modal-threads/metrics-modal-threads.component.spec.ts.ejs
=> [Angular] Sonar: duplicate code

generators/client/templates/src/main/webapp/index.html.ejs
=> Sonar: Unchanged variables should be marked as const

package-lock.json, package.json
=> Generator: upgrade Typescript 5.7.3

generators/angular/resources/package.json, generators/client/resources/package.json, generators/common/resources/package.json, generators/generate-blueprint/resources/package.json, generators/javascript/resources/package.json, generators/react/resources/package.json, generators/vue/resources/package.json
Workaround https://github.com/dependabot/dependabot-core/issues/11373
---
=> add packageManager to package.json to fix dependabot

.github/dependabot.yml
=> fix dependabot gradle path.

generators/spring-boot/prompts.ts
Fixes https://github.com/jhipster/generator-jhipster/issues/28461
---
=> spring-boot: remove rate limit text

generators/spring-boot/templates/src/test/java/_package_/service/MailServiceIT.java.ejs
Fixes https://github.com/jhipster/generator-jhipster/issues/28615
---
=> fix backend test in Windows

generators/client/templates/src/main/webapp/swagger-ui/index.html.ejs, generators/server/resources/gradle/libs.versions.toml, generators/spring-boot/generator.ts, generators/spring-boot/templates/src/main/java/_package_/web/rest/errors/ExceptionTranslator.java.ejs, generators/spring-boot/templates/src/test/java/_package_/config/JHipsterBlockHoundIntegration.java.ejs
- [spring-boot: add springdoc method to blockhound](https://github.com/jhipster/generator-jhipster/pull/28660/commits/b1e207f11f0a7a27b6ce3153a1c5e8ff4dd691ce)
- [spring-boot: add logger to ExceptionTranslator](https://github.com/jhipster/generator-jhipster/pull/28660/commits/f40925120a9573d5da93bdff0697df78fc6c3535)
- [client: add swagger fallback url](https://github.com/jhipster/generator-jhipster/pull/28660/commits/f60fa0d4eb598fdd2445998ecad1fdbb83a02489)
Fixes https://github.com/jhipster/generator-jhipster/pull/28552
---
=> spring-boot: bump springdoc-openapi-starter-webmvc-api to v8.4.0

lib/jdl/converters/parsed-jdl-to-jdl-object/parsed-jdl-to-jdl-object-converter.ts
=> fix the handling of falsy values in field annotations

generators/jdl/generator.spec.ts
Related to https://github.com/jhipster/generator-jhipster/pull/28753
---
=> internal: add jdl annotation test

generators/base-application/support/update-application-entities-transform.ts
Fixes https://github.com/jhipster/generator-jhipster/issues/26380
---
=> jdl: normalize windows path when looking for entities

package-lock.json, package.json
=> Fix bump typescript from 5.7.3 to 5.8.2

generators/angular/resources/package.json, generators/angular/templates/src/main/webapp/app/core/util/data-util.service.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/detail/_entityFile_-detail.component.spec.ts.ejs
=> [Angular] Fix bump typescript from 5.7.3 to 5.8.2

generators/spring-boot/templates/src/main/java/_package_/Application.java.ejs
Fixes https://github.com/jhipster/generator-jhipster/issues/28745
Fixes https://github.com/jhipster/generator-jhipster/issues/27121
---
=> spring-boot: workaround hazelcast issue

generators/angular/templates/src/main/webapp/app/app.component.ts.ejs, generators/angular/templates/src/main/webapp/app/layouts/main/main.component.html.ejs
=> [Angular] Migrate to self-closing tags

generators/generate-blueprint/templates/.blueprint/generate-sample/command.mjs.ejs
=> generate-blueprint: fix generate-sample command

cli/environment-builder.mjs, generators/generate-blueprint/constants.ts, generators/generate-blueprint/files.ts
=> internal: allow nested generators in local blueprints.

generators/generate-blueprint/templates/generators/generator/generator.mjs.jhi.ejs
=> generate-blueprint: add type to dynamic blueprints

generators/generate-blueprint/generator.ts
=> generate-blueprint: adjusts to generate-snapshot option

.github/workflows/generator-database-changelog-liquibase.yml, .github/workflows/generator-generate-blueprint.yml, .github/workflows/issue-check.yml, generators/spring-boot/templates/src/main/java/_package_/_entityPackage_/service/_entityClass_QueryService.java.ejs, test-integration/integration-test-constants.js
Fixes https://github.com/jhipster/generator-jhipster/issues/26913
Related to https://github.com/jhipster/generator-jhipster/issues/25231.
---
=> spring-relational: simplify query service

generators/base/support/needles.spec.ts, generators/base/support/needles.ts
=> internal: fix supporting needles apis

generators/liquibase/generator.ts, generators/server/types.d.ts, generators/spring-boot/__snapshots__/generator.spec.ts.snap, generators/spring-boot/generator.spec.ts, generators/spring-boot/generator.ts, lib/testing/helpers.ts
=> spring-boot: simplify adding properties to ApplicationProperties

generators/java/__snapshots__/generator.spec.ts.snap, generators/java/generator.spec.ts, generators/java/generators/bootstrap/generator.ts, generators/java/support/index.ts, generators/java/support/java-file-edit.spec.ts, generators/java/support/java-file-edit.ts, generators/java/types.d.ts, lib/testing/helpers.ts
=> java: add more options to editJavaFile

generators/server/types.d.ts, generators/spring-boot/generator.spec.ts, generators/spring-boot/generator.ts, generators/spring-boot/templates/src/main/resources/config/application.yml.ejs
=> spring-boot: add addApplicationYamlDocument to source

generators/angular/resources/package.json, generators/angular/templates/src/main/webapp/app/app-page-title-strategy.ts.ejs, generators/angular/templates/src/main/webapp/app/core/util/alert.service.ts.ejs
=> [Angular] Fix: bump typescript-eslint from 8.27.0 to 8.28.0

cli/download.mts, lib/testing/github.ts, package-lock.json, package.json
=> internal: drop axios dependency

generators/base/support/needles.spec.ts, generators/base/support/needles.ts
=> internal: improve needles behavior with prettier.

package-lock.json, package.json
=> drop @actions/core dependency

generators/angular/templates/src/main/webapp/app/admin/configuration/configuration.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/admin/health/modal/health-modal.component.ts.ejs, generators/angular/templates/src/main/webapp/app/admin/logs/logs.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/admin/user-management/delete/user-management-delete-dialog.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/admin/user-management/detail/user-management-detail.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/admin/user-management/list/user-management.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/admin/user-management/update/user-management-update.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/delete/_entityFile_-delete-dialog.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/detail/_entityFile_-detail.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/list/_entityFile_.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/service/_entityFile_.service.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/update/_entityFile_-update.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/home/home.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/layouts/navbar/navbar.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/layouts/profiles/page-ribbon.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/login/login.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/shared/alert/alert-error.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/shared/alert/alert.component.spec.ts.ejs
=> Angular - Tests: Replace Should by should

generators/angular/templates/src/main/webapp/app/account/password-reset/finish/password-reset-finish.component.html.ejs, generators/angular/templates/src/main/webapp/app/account/password-reset/init/password-reset-init.component.html.ejs, generators/angular/templates/src/main/webapp/app/account/password/password.component.html.ejs, generators/angular/templates/src/main/webapp/app/account/register/register.component.html.ejs, generators/angular/templates/src/main/webapp/app/account/settings/settings.component.html.ejs, generators/angular/templates/src/main/webapp/app/admin/metrics/metrics.component.html.ejs, generators/angular/templates/src/main/webapp/app/admin/user-management/delete/user-management-delete-dialog.component.html.ejs, generators/angular/templates/src/main/webapp/app/admin/user-management/list/user-management.component.html.ejs, generators/angular/templates/src/main/webapp/app/admin/user-management/update/user-management-update.component.html.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/delete/_entityFile_-delete-dialog.component.html.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/detail/_entityFile_-detail.component.html.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/list/_entityFile_.component.html.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/update/_entityFile_-update.component.html.ejs
=> Angular: use Self Closing Tags

generators/angular/templates/src/main/webapp/app/account/activate/activate.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/account/password-reset/finish/password-reset-finish.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/account/password/password.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/account/sessions/sessions.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/account/settings/settings.component.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/login/login.component.spec.ts.ejs
=> Angular: replace noop with error factory

generators/angular/templates/src/main/webapp/app/layouts/profiles/page-ribbon.component.ts.ejs
=> [Angular] Observable to Signal (ribbon component)

generators/angular/templates/src/main/webapp/app/account/password/password.component.html.ejs, generators/angular/templates/src/main/webapp/app/account/password/password.component.ts.ejs
=> [Angular] Observable to Signal (password component)

.github/workflows/issue-check.yml
=> ci: adjust issue check

.blueprint/from-issue/generator.mts, .github/workflows/issue-check.yml
=> ci: more issue-check adjusts

generators/app/__snapshots__/generator.spec.ts.snap, generators/base-core/generator.ts, generators/bootstrap/command.ts, generators/init/__snapshots__/generator.spec.ts.snap, generators/jdl/__snapshots__/generator.spec.ts.snap
Due to https://github.com/jhipster/generator-jhipster/pull/29078#issuecomment-2782657423
and https://github.com/jhipster/generator-jhipster/issues/27906
---
=> internal: disable autoCrlf on Windows by default

generators/react/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_-delete-dialog.tsx.ejs
=> [React] Unused pageLocation

generators/react/templates/src/main/webapp/app/shared/reducers/reducer.utils.ts.ejs
=> [React] Unused action

generators/react/templates/src/main/webapp/app/shared/reducers/application-profile.spec.ts.ejs
=> [React] Unused store in test

generators/angular/templates/README.md.jhi.client.angular.ejs
=> [Angular] Update URL for Angular CLI

generators/react/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_.reducer.ts.ejs
=> [React] Hide unused thunkAPI

generators/vue/templates/src/main/webapp/app/main.ts.ejs
=> [Vue] Fix warning vue/order-in-components

generators/vue/templates/src/main/webapp/app/account/account.service.ts.ejs, generators/vue/templates/src/main/webapp/app/account/login-form/login-form.component.ts.ejs
=> [Vue] Remove unused vars

generators/vue/templates/src/main/webapp/app/admin/metrics/metrics-modal.vue.ejs
=> [Vue] Variable key is already declared in the upper scope

generators/angular/resources/package.json, generators/angular/templates/eslint.config.js.jhi.angular.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/update/_entityFile_-update.component.html.ejs, generators/javascript/generators/eslint/templates/eslint.config.js.jhi.ejs
=> [Angular] bump typescript-eslint 8.31.0

cli/environment-builder.mjs, generators/base/api.d.ts, generators/bootstrap/generator.ts, lib/testing/apply-patch-to-template.ts
Fixes https://github.com/jhipster/generator-jhipster/issues/29240
---
=> feat(internal): add option to copy conflicted file back to the template

generators/vue/templates/src/main/webapp/app/account/account.service.ts.ejs, generators/vue/templates/src/main/webapp/app/account/activate/activate.service.ts.ejs, generators/vue/templates/src/main/webapp/app/account/login.service.ts.ejs, generators/vue/templates/src/main/webapp/app/account/register/register.service.ts.ejs, generators/vue/templates/src/main/webapp/app/admin/configuration/configuration.service.ts.ejs, generators/vue/templates/src/main/webapp/app/admin/gateway/gateway.service.ts.ejs, generators/vue/templates/src/main/webapp/app/admin/health/health.service.ts.ejs, generators/vue/templates/src/main/webapp/app/admin/logs/logs.service.ts.ejs, generators/vue/templates/src/main/webapp/app/admin/metrics/metrics.service.ts.ejs, generators/vue/templates/src/main/webapp/app/admin/tracker/tracker.service.ts.ejs, generators/vue/templates/src/main/webapp/app/admin/user-management/user-management.service.ts.ejs, generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_.service.ts.ejs, generators/vue/templates/src/main/webapp/app/entities/user/user.service.ts.ejs, generators/vue/templates/src/main/webapp/app/locale/translation.service.ts.ejs, generators/vue/templates/src/main/webapp/app/shared/alert/alert.service.ts.ejs
=> [Vue] Remove public visibility (default) on methods

generators/angular/templates/src/main/webapp/app/core/tracker/tracker.service.ts.ejs, generators/angular/templates/src/main/webapp/app/shared/sort/sort.service.ts.ejs
=> [Angular] Remove public visibility (default) on methods

generators/vue/templates/src/main/webapp/app/account/change-password/change-password.vue.ejs, generators/vue/templates/src/main/webapp/app/account/settings/settings.vue.ejs, generators/vue/templates/src/main/webapp/app/core/home/home.vue.ejs
=> [Vue] Property shorthand

generators/cypress/templates/src/test/javascript/cypress/support/oauth2.ts.ejs
=> Property shorthand

generators/react/resources/package.json, generators/react/templates/src/main/webapp/app/shared/util/entity-utils.ts.ejs
=> [React] Fix bump  react-hook-form from 7.54.2 to 7.56.1

generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/list/_entityFile_.component.ts.ejs, generators/angular/templates/src/main/webapp/app/shared/auth/has-any-authority.directive.ts.ejs
=> [Angular] Remove unnecessary public visibility

generators/docker-compose/__snapshots__/docker-compose.spec.ts.snap, generators/docker-compose/templates/central-server-config/application.yml.ejs, generators/languages/templates/src/main/resources/i18n/messages_bg.properties.ejs, generators/react/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_-update.tsx.ejs, generators/react/templates/src/main/webapp/app/shared/layout/header/header.tsx.ejs, generators/react/templates/src/main/webapp/app/shared/layout/menus/account.spec.tsx.ejs, generators/react/templates/src/main/webapp/app/shared/layout/menus/account.tsx.ejs, generators/react/templates/src/main/webapp/app/shared/reducers/authentication.ts.ejs, generators/spring-boot/templates/gradle/profile_prod.gradle.ejs, generators/spring-boot/templates/src/main/java/_package_/_entityPackage_/service/impl/_entityClass_ServiceImpl.java.ejs, generators/spring-boot/templates/src/main/java/_package_/_entityPackage_/web/rest/_entityClass_Resource.java.ejs, generators/spring-boot/templates/src/main/java/_package_/service/MailService.java.ejs, generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/service/criteria/_entityClass_CriteriaTest.java.ejs, generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/web/rest/_entityClass_ResourceIT.java.ejs, generators/spring-boot/templates/src/test/java/_package_/config/SpringBootTestClassOrderer.java.ejs, generators/spring-boot/templates/src/test/java/_package_/web/filter/SpaWebFilterIT_reactive.java.ejs, generators/spring-cache/templates/src/test/java/_package_/config/EmbeddedRedis.java.ejs, generators/spring-cloud-stream/generators/kafka/templates/src/test/java/_package_/config/EmbeddedKafka.java.ejs, generators/spring-cloud-stream/generators/pulsar/templates/src/test/java/_package_/config/EmbeddedPulsar.java.ejs, generators/spring-data-cassandra/templates/src/test/java/_package_/config/EmbeddedCassandra.java.ejs, generators/spring-data-couchbase/templates/src/test/java/_package_/config/EmbeddedCouchbase.java.ejs, generators/spring-data-elasticsearch/templates/src/test/java/_package_/config/EmbeddedElasticsearch.java.ejs, generators/spring-data-mongodb/templates/src/test/java/_package_/config/EmbeddedMongo.java.ejs, generators/spring-data-relational/templates/src/main/java/_package_/repository/rowmapper/UserRowMapper_reactive.java.ejs, generators/spring-data-relational/templates/src/test/java/_package_/config/EmbeddedSQL.java.ejs, generators/spring-data-relational/templates/src/test/java/_package_/config/PostgreSqlTestContainer.java.ejs, generators/vue/templates/src/main/webapp/app/router/account.ts.ejs, generators/vue/templates/src/main/webapp/content/scss/vendor.scss.ejs, lib/jdl/core/__test-support__/files/field_comments.jdl, lib/jdl/core/__test-support__/files/realistic_sample.jdl
=> Remove unnecessary lines

generators/vue/templates/src/main/webapp/app/account/change-password/change-password.component.spec.ts.ejs, generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_.vue.ejs
=> [Vue] Remove unnecessary spaces

generators/angular/templates/src/main/webapp/app/app-page-title-strategy.ts.ejs, generators/docker/templates/docker/pulsar.yml.ejs, generators/java/generators/domain/templates/src/main/java/_package_/_entityPackage_/domain/enumeration/_enumName_.java.ejs, generators/liquibase/templates/src/main/resources/META-INF/native-image/liquibase/reflect-config.json, generators/liquibase/templates/src/main/resources/config/liquibase/changelog/add_relationship_constraints.ejs, generators/spring-boot/templates/src/main/java/_package_/web/filter/SpaWebFilter_imperative.java.ejs, generators/spring-boot/templates/src/test/java/_package_/config/TestContainersSpringContextCustomizerFactory.java.ejs
=> Remove some spaces

generators/app/__snapshots__/generator.spec.ts.snap, generators/app/command.ts, generators/app/generator.ts, generators/app/support/config.ts, generators/base-core/generator.ts, generators/base/generator.ts, generators/bootstrap-application-base/generator.ts, generators/bootstrap-application-client/generator.ts, generators/bootstrap-application/generator.ts, generators/bootstrap/generator.ts, generators/client/generator.ts, generators/common/generator.ts, generators/jdl/__snapshots__/generator.spec.ts.snap, generators/languages/command.ts, generators/server/command.ts, generators/server/generator.ts, lib/command/types.d.ts
loadStoredAppOptions used control object.
---
=> internal: drop loadStoredAppOptions function

generators/base-core/generator.ts, generators/base-core/internal/index.ts, generators/base-core/internal/write-files.ts, generators/base/api.d.ts, generators/liquibase/changelog-files.ts
=> internal: improve writeFile types.

generators/angular/generator.ts, generators/base-core/generator.ts, generators/base-workspaces/generator.ts, generators/base/generator.ts, generators/base/types.d.ts, generators/bootstrap-application-base/generator.ts, generators/react/generator.ts, generators/vue/generator.ts, package-lock.json, package.json
Related to https://github.com/jhipster/generator-jhipster/issues/29499
---
=> internal: cleanup control api

generators/base-application/support/constants.ts, generators/base-core/generator.ts, generators/base/generator.ts, generators/base/support/constants.ts, generators/languages/generator.ts, generators/languages/prompts.ts, generators/languages/support/constants.ts, generators/project-name/generator.ts
control was used as shared state storage, replace it with context data.
Fixes https://github.com/jhipster/generator-jhipster/issues/29499.
---
=> internal: remove control usages as generic state usage

generators/angular/generator.ts, generators/base-application/generator.ts, generators/base-core/generator.ts, generators/base/generator.ts, generators/base/types.d.ts, generators/jdl/generator.ts, generators/react/generator.ts, generators/vue/generator.ts, lib/types/base/tasks.d.ts
- make control type strict
- rework control and make it private
- move control and jhipsterConfigWithDefaults calculation from base-core to base
---
=> internal: improve base and base-core

.blueprint/github-build-matrix/generator.ts, generators/base-core/generator.ts, generators/base/api.d.ts, generators/bootstrap-application-base/generator.ts, generators/bootstrap-application-client/generator.ts, generators/bootstrap-application-server/generator.ts, generators/bootstrap-application/generator.ts, generators/bootstrap/generator.ts, generators/generate-blueprint/templates/.blueprint/generate-sample/generator.mjs.ejs, generators/generate-blueprint/templates/.blueprint/github-build-matrix/generator.mjs.ejs, generators/info/generator.ts, generators/javascript/generators/bootstrap/generator.spec.ts
=> internal: rework jhipsterBootstrap feature implementation

.blueprint/code-workspace/command.mts, .blueprint/from-issue/command.mts, .blueprint/generate-generator/command.mts, .blueprint/generate-sample/command.mts, .blueprint/update-vscode/command.mts, generators/angular/command.ts, generators/base-workspaces/command.ts, generators/bootstrap/command.ts, generators/ci-cd/command.ts, generators/client/generators/common/command.ts, generators/common/command.ts, generators/cypress/command.ts, generators/entities/command.ts, generators/entity/command.ts, generators/java/generators/code-quality/command.ts, generators/java/generators/domain/command.ts, generators/java/generators/jib/command.ts, generators/java/generators/node/command.ts, generators/maven/command.ts, generators/maven/generators/code-quality/command.ts, generators/maven/generators/frontend-plugin/command.ts, generators/maven/generators/jib/command.ts, generators/upgrade/command.ts, generators/workspaces/command.ts
=> internal: make constants all commands types

.blueprint/cli/commands.mts, .blueprint/generate-generator/generator.mts, .blueprint/update-generators/command.ts, .blueprint/update-generators/generator.ts, .blueprint/update-generators/index.ts, generators/base-application/generator.ts, generators/base-core/generator.ts, generators/types.ts
=> internal: improve compose types

cli/environment-builder.mjs, cli/program.mts, generators/app/__snapshots__/generator.spec.ts.snap, generators/base-application/generator.ts, generators/base/__snapshots__/generator.spec.ts.snap, generators/base/command.ts, generators/base/generator.ts, generators/base/internal/blueprint.spec.ts, generators/base/internal/blueprint.ts, generators/base/types.d.ts, generators/bootstrap/generator.ts, generators/export-jdl/command.ts, generators/export-jdl/generator.ts, generators/jdl/__snapshots__/generator.spec.ts.snap, lib/command/types.d.ts
=> internal: api cleanup

generators/app/cleanup.ts, generators/base-core/generator.ts, generators/base/generator.ts, generators/base/types.d.ts, generators/common/generator.ts, generators/generate-blueprint/constants.ts, generators/generate-blueprint/generator.ts, generators/jdl/generator.ts, generators/spring-boot/cleanup.ts, generators/upgrade/generator.ts, package-lock.json, package.json
=> internal: use new yeoman-generator generic type

generators/bootstrap-application-base/generator.ts, generators/java/generators/bootstrap/generator.ts, lib/jhipster/application-options.ts, lib/jhipster/default-application-options.ts
=> internal: adjusts to packageFolder configuration handling

generators/base-application/generator.ts, generators/base-application/index.ts, generators/base-application/types.d.ts, generators/base-entity-changes/generator.ts, generators/base-entity-changes/index.ts, generators/base-entity-changes/types.d.ts, generators/base-simple-application/generator.ts, generators/base-simple-application/types.d.ts, generators/base-workspaces/generator.ts, generators/base-workspaces/types.d.ts, generators/base/generator.ts, generators/base/tasks.d.ts, generators/base/types.d.ts, generators/liquibase/generator.ts, generators/liquibase/types.d.ts, generators/server/types.d.ts, lib/types/application/application.d.ts, lib/types/application/tasks.d.ts
This PR allows source from tasks to be customized.
---
=> internal: expose source to generics

generators/bootstrap-application-base/generator.ts, generators/java/generators/bootstrap/generator.ts
=> internal: move project-name customization to java:bootstrap

generators/client/resources/package.json, generators/cypress/templates/eslint.config.js.jhi.cypress.ejs
Fix #29646 
https://github.com/cypress-io/eslint-plugin-cypress/releases
---
=> Bump eslint-plugin-cypress to v5

generators/base-application/support/constants.ts, generators/base-workspaces/types.d.ts, generators/base/generator.ts, generators/base/support/constants.ts, generators/bootstrap-workspaces/generator.ts, generators/docker-compose/generator.ts, generators/project-name/generator.ts
=> internal: replace existingWorkspaces with existingProject

generators/base-application/application-config-all.d.ts, generators/base-application/application-options-all.d.ts, generators/base-application/application-properties-all.d.ts, generators/base-core/types.d.ts, generators/base-simple-application/index.ts, generators/base-workspaces/support/config.ts, generators/bootstrap-application-base/generator.ts, generators/ci-cd/ci-cd.spec.ts, generators/client/types.d.ts, generators/gradle/types.d.ts, generators/java/generator.ts, generators/java/generators/build-tool/generator.ts, generators/java/generators/code-quality/generator.ts, generators/java/generators/graalvm/generator.spec.ts, generators/java/generators/jib/generator.ts, generators/java/generators/openapi-generator/generator.ts, generators/java/generators/server/generator.ts, generators/java/types.d.ts, generators/javascript/generator.ts, generators/javascript/generators/bootstrap/generator.ts, generators/javascript/generators/eslint/generator.ts, generators/javascript/generators/husky/generator.ts, generators/javascript/generators/prettier/generator.ts, generators/javascript/types.d.ts, generators/liquibase/types.d.ts, generators/maven/types.d.ts, generators/server/types.d.ts, lib/command/load.ts, lib/jhipster/build-tool-types.ts
=> internal: continue types modularization.

generators/base-application/application-config-all.d.ts, generators/base-workspaces/generator.ts, generators/base-workspaces/internal/docker-prompts.ts, generators/base-workspaces/prompts.ts, generators/base-workspaces/support/task-type-inference.ts, generators/base/types.d.ts, generators/bootstrap-workspaces/generator.ts, generators/docker-compose/generator.ts, generators/kubernetes-helm/generator.ts, generators/kubernetes-knative/generator.ts, generators/kubernetes-knative/prompts.ts, generators/kubernetes/generator.ts, generators/kubernetes/prompts.ts
Relates to https://github.com/jhipster/generator-jhipster/issues/28235,
Try to improve base workspace and descendants.
I know its not ready yet, but is it at least going in the right direction?
I didn't fix the shouldaddfor prompt and regenerate method, but at least this one is compiling and moving forward
---
=> use existingproject as a guard for workspace generators

generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/list/_entityFile_.component.ts.ejs
Fix #29785 
Related to https://github.com/jhipster/generator-jhipster/pull/26504
---
=> [Angular] Fix infinite-scroll

generators/cypress/templates/src/test/javascript/cypress/e2e/entity/_entity_.cy.ts.ejs
=> Template literal expression is unnecessary and can be simplified

generators/react/templates/src/main/webapp/app/config/error-middleware.ts.ejs, generators/react/templates/src/main/webapp/app/shared/reducers/authentication.ts.ejs
=> [React] Prefer using an optional chain expression instead, as it's more concise and easier to read

generators/react/templates/src/main/webapp/app/config/notification-middleware.ts.ejs
=> [React] Unnecessary optional chain on a non-nullish value

generators/vue/templates/src/main/webapp/app/admin/metrics/metrics-modal.component.spec.ts.ejs, generators/vue/templates/src/main/webapp/app/core/ribbon/ribbon.component.spec.ts.ejs, generators/vue/templates/src/main/webapp/app/shared/alert/alert.service.spec.ts.ejs
=> [Vue] Async arrow function has no await expression

generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_.service.ts.ejs
=> [Vue] Template literal expression is unnecessary and can be simplified

generators/react/templates/src/main/webapp/app/shared/layout/header/header.tsx.ejs
=> [React] This expression unnecessarily compares a boolean value to a boolean instead of using it directly

generators/vue/templates/src/main/webapp/app/account/account.service.ts.ejs, generators/vue/templates/src/main/webapp/app/shared/config/axios-interceptor.ts.ejs
=> [Vue] Prefer using nullish coalescing operator instead of a logical or, as it is a safer operator

generators/vue/templates/src/main/webapp/app/core/jhi-navbar/jhi-navbar.component.ts.ejs
=> [Vue] Use String#startsWith method instead of indexOf

generators/kubernetes-knative/files.ts
Completes https://github.com/jhipster/generator-jhipster/pull/29914 for Knative
---
=> use writeFile api for knative generator

generators/java/generators/domain/templates/src/test/java/_package_/_entityPackage_/domain/_persistClass_TestSamples.java.ejs, generators/spring-boot/templates/src/test/java/_package_/_entityPackage_/web/rest/_entityClass_ResourceIT.java.ejs
=> Fix incorrect use of 2 * Integer.MAX_VALUE

.gitignore, .idea/runConfigurations/_template__of_Mocha.xml
fix https://github.com/jhipster/generator-jhipster/issues/29916
Help any newcomer to bootstrap the project if they use intellij
---
=> add intellij run configuration

generators/base-application/generator.ts, generators/cypress/generator.ts, generators/languages/generator-needles.spec.ts, generators/languages/generator.ts, generators/languages/types.d.ts, generators/liquibase/needles.spec.ts, generators/maven/needles.spec.ts, generators/server/needle-logback.spec.ts, generators/spring-cache/needles.spec.ts, generators/spring-cloud-stream/generators/kafka/generator.ts, generators/spring-cloud/generators/gateway/generator.ts, generators/spring-cloud/types.d.ts, generators/spring-data-relational/generator.ts, generators/spring-data-relational/types.d.ts, lib/types/source-all.d.ts
=> internal: don't use SourceAll by default

generators/app/__snapshots__/generator.spec.ts.snap, generators/app/generator.ts, generators/base-application/generator.ts, generators/base-application/support/prepare-entity.ts, generators/bootstrap-application-server/generator.ts, generators/client/support/update-languages.ts, generators/common/command.ts, generators/common/types.d.ts, generators/java/generators/node/generator.ts, generators/java/index.ts, generators/jdl/__snapshots__/generator.spec.ts.snap, generators/languages/generator.ts, generators/server/command.ts, generators/server/support/update-languages.ts, generators/spring-boot/generator.ts, generators/spring-boot/index.ts, generators/spring-boot/prompts.ts, generators/spring-boot/types.d.ts, generators/spring-cache/types.d.ts, generators/spring-data-neo4j/generator.ts, generators/spring-data-relational/types.d.ts
=> internal: don't use ConfigAll by default

generators/base-workspaces/internal/deployments.ts, generators/base-workspaces/internal/docker-base.ts, generators/base-workspaces/internal/docker-dependencies.ts, generators/base-workspaces/support/config.ts, generators/base-workspaces/types.d.ts, generators/docker-compose/generator.ts, generators/docker/support/check-docker.ts, generators/kubernetes-helm/files.ts, generators/kubernetes-helm/generator.ts, generators/kubernetes-knative/files.ts, generators/kubernetes-knative/generator.ts, generators/kubernetes-knative/prompts.ts, generators/kubernetes/files.ts, generators/kubernetes/generator.ts, generators/kubernetes/kubernetes-base.ts, generators/kubernetes/prompts.ts
Drop ts-nocheck from kubernetes generators
---
=> kubernetes: types adjusts

generators/base-workspaces/generator.ts, generators/base-workspaces/index.ts, generators/base-workspaces/support/task-type-inference.ts, generators/base-workspaces/tasks.d.ts, generators/base-workspaces/types.d.ts, generators/bootstrap-workspaces/generator.ts, generators/docker-compose/generator.ts, generators/workspaces/generator.ts
`workspaces` is not necessary for now.
It's making logic more complex.
Related to https://github.com/jhipster/generator-jhipster/pull/29991, https://github.com/jhipster/generator-jhipster/issues/28235
---
=> base-workspaces: remove workspaces state object

generators/java/generators/domain/templates/src/main/java/_package_/_entityPackage_/domain/_persistClass_.java.jhi.ejs, generators/spring-boot/templates/src/main/java/_package_/_entityPackage_/service/criteria/_entityClass_Criteria.java.ejs, generators/spring-boot/templates/src/main/java/_package_/domain/AbstractAuditingEntity.java.ejs, generators/spring-boot/templates/src/main/java/_package_/domain/PersistentToken.java.ejs, generators/spring-boot/templates/src/main/java/_package_/domain/User.java.ejs, generators/spring-boot/templates/src/main/java/_package_/security/PersistentTokenRememberMeServices.java.ejs, generators/spring-boot/templates/src/main/java/_package_/security/UserNotActivatedException.java.ejs, generators/spring-boot/templates/src/main/java/_package_/service/EmailAlreadyUsedException.java.ejs, generators/spring-boot/templates/src/main/java/_package_/service/InvalidPasswordException.java.ejs, generators/spring-boot/templates/src/main/java/_package_/service/UsernameAlreadyUsedException.java.ejs, generators/spring-boot/templates/src/main/java/_package_/service/dto/AdminUserDTO.java.ejs, generators/spring-boot/templates/src/main/java/_package_/service/dto/PasswordChangeDTO.java.ejs, generators/spring-boot/templates/src/main/java/_package_/service/dto/UserDTO.java.ejs, generators/spring-boot/templates/src/main/java/_package_/web/rest/AccountResource_oauth2.java.ejs, generators/spring-boot/templates/src/main/java/_package_/web/rest/AccountResource_skipUserManagement.java.ejs, generators/spring-boot/templates/src/main/java/_package_/web/rest/errors/BadRequestAlertException.java.ejs, generators/spring-boot/templates/src/main/java/_package_/web/rest/errors/EmailAlreadyUsedException.java.ejs, generators/spring-boot/templates/src/main/java/_package_/web/rest/errors/FieldErrorVM.java.ejs, generators/spring-boot/templates/src/main/java/_package_/web/rest/errors/InvalidPasswordException.java.ejs, generators/spring-boot/templates/src/main/java/_package_/web/rest/errors/LoginAlreadyUsedException.java.ejs, generators/spring-data-elasticsearch/templates/src/main/java/_package_/web/rest/errors/QuerySyntaxException.java.ejs, generators/spring-data-elasticsearch/templates/src/main/java/_package_/web/web/rest/errors/QuerySyntaxException.java.ejs, generators/spring-data-relational/templates/src/test/java/_package_/repository/timezone/DateTimeWrapper.java.ejs
It is recommended to annotated serialization code with `@Serial`. IntelliJ even gives a warning about it.
---
=> Add @Serial on all serialVersionUID

generators/heroku/command.ts, generators/heroku/generator.ts, generators/heroku/types.d.ts
=> heroku: drop @ts-nocheck

generators/kubernetes-knative/files.ts, generators/kubernetes-knative/generator.ts, lib/jdl/jdl-importer.ts
=> Fix warnings: unused-imports/no-unused-vars

cli/cli.spec.mts
=> Remove any to CliCommand

cli/program.mts
=> Remove any to LookupOptions

lib/jhipster/default-application-options.spec.ts
=> Remove any on default-application-options

lib/jdl/converters/exporters/export-utils.spec.ts, lib/jdl/converters/exporters/jdl-exporter.spec.ts, lib/jdl/converters/exporters/jhipster-deployment-exporter.spec.ts, lib/jdl/converters/exporters/jhipster-entity-exporter.spec.ts, lib/jdl/core/linters/jdl-linter.spec.ts, lib/jdl/core/readers/jdl-reader.spec.ts, lib/jdl/integration-test.spec.ts
Related to https://github.com/jhipster/generator-jhipster/issues/30062
---
=> internal: use yeoman-test helpers instead of custom helpers in jdl

lib/jdl/converters/jdl-to-json/jdl-without-application-to-json-converter.spec.ts
Related to https://github.com/jhipster/generator-jhipster/issues/30065.
---
=> drop lots of any usage

generators/client/generator.ts, generators/react/application/entities/index.ts, generators/react/generator.ts
=> react: add entityReactState to react types.

generators/bootstrap-application-base/generator.ts, generators/project-name/support/basename-properties.ts, lib/jdl/converters/jdl-to-json/jdl-to-json-field-converter.ts, lib/jdl/converters/jdl-to-json/jdl-to-json-relationship-converter.ts, lib/jdl/converters/json-to-jdl-entity-converter.ts, lib/jdl/converters/parsed-jdl-to-jdl-object/field-converter.ts, lib/jdl/converters/parsed-jdl-to-jdl-object/relationship-converter.ts, lib/jdl/core/basic-types/json-entity.ts, lib/utils/string-utils.ts, lib/utils/string_utils.spec.ts, lib/utils/yo-rc.ts
=> internal: drop custom string utilities

generators/angular/generator.spec.ts, generators/base-application/support/prepare-entity.ts, generators/base-application/types.d.ts, generators/base-core/support/jhipster7-context.ts, generators/generator-constants.js, lib/command/types.d.ts, lib/constants/jhipster.ts, lib/constants/yeoman.ts, lib/jdl/converters/exporters/export-utils.ts, lib/jhipster/deployment-options.ts, lib/jhipster/types/field.d.ts, lib/jhipster/types/yo-rc.d.ts, lib/utils/logger.ts, lib/utils/object.ts, lib/utils/secret.ts, lib/utils/yo-rc.ts, package-lock.json, package.json, test/support/check-enforcements.ts, tsconfig.any.json
Related to https://github.com/jhipster/generator-jhipster/issues/30062.
---
=> chore: start enabling implicit any

generators/base-core/priorities.ts, generators/base-entity-changes/generator.ts, generators/base-entity-changes/types.d.ts, generators/liquibase/changelog-files.ts, generators/liquibase/generator.ts, generators/liquibase/types.d.ts, generators/server/support/relationship.ts
Related to https://github.com/jhipster/generator-jhipster/issues/30062.
---
=> improve base-entity-changes types

generators/server/resources/pom.xml
Reverts jhipster/generator-jhipster#29103
=> Revert "build(deps): bump org.apache.maven.plugins:maven-surefire-plugin from 3.5.2 to 3.5.3 in /generators/server/resources"

.github/dependabot.yml
=> adjust fontawesome dependabot groups

lib/jdl/converters/jdl-to-json/jdl-to-json-field-converter.spec.ts, lib/jdl/converters/jdl-to-json/jdl-to-json-option-converter.spec.ts, lib/jdl/converters/jdl-to-json/jdl-to-json-relationship-converter.spec.ts, lib/jdl/converters/jdl-to-json/jdl-with-applications-to-json-converter.spec.ts
=> Drop some any usage

generators/base-application/generator.ts, generators/base-core/generator.ts, generators/base-core/types.d.ts, generators/base-simple-application/generator.ts, generators/base-workspaces/generator.ts, generators/base/generator.ts
Task groups will return a Record with existing keys in the group.
---
=> rework as*TaskGroup utilities

package-lock.json, package.json
=> Fix bump TypeScript to 5.9.2

generators/angular/resources/package.json, generators/angular/templates/src/main/webapp/app/admin/metrics/blocks/metrics-system/metrics-system.component.ts.ejs
=> [Angular] Fix bump typescript-eslint to 8.39.0

generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/detail/_entityFile_-detail.component.html.ejs
=> [Angular] Fix warnings: Operator ?? can be safely removed

generators/react/resources/package.json, generators/react/templates/package.json.ejs
=> [React] Remove unused dependency: uuid

lib/jdl/core/models/jdl-application-factory.ts
=> Fix duplicate exports

lib/command/generator-command.spec.ts
=> Remove generic argument any

generators/base-application/support/prepare-field.ts, generators/client/support/entity-definition.ts, generators/react/generator.ts, generators/vue/generator.ts
=> Use destructuring syntax

generators/maven/support/pom-store.ts
=> Remove default visibility

generators/entity/generator.ts, generators/entity/prompts.ts, generators/server/generator.ts, generators/spring-boot/command.ts, generators/spring-cloud/generators/gateway/command.ts, generators/upgrade/generator.ts, lib/jdl/core/built-in-options/validation-patterns.ts, lib/jdl/core/parsing/validator.ts
=> Simplify Regex

lib/jdl/jdl-importer.ts
=> The value assigned to applicationType is never used

generators/maven/support/dependabot-maven.ts
=> Remove unused function getPomProperties

lib/utils/object.ts
Related to https://github.com/jhipster/generator-jhipster/pull/30380.
---
=> improve mutateData jsdoc

lib/jdl/jdl-importer.ts
=> Parameter logger described in JSDoc does not appear in function signature

generators/base-application/generators/bootstrap/generator.ts, generators/base-core/support/needles.ts, generators/base-simple-application/generators/bootstrap/generator.ts, generators/entity/generator.ts, generators/react/support/translate-react.ts, generators/server/generator.ts, generators/server/support/prepare-field.ts, generators/spring-data-neo4j/generator.ts, generators/vue/support/translate-vue.ts, lib/jdl-config/jhipster-jdl-config.ts
=> Nullish coalescing should be preferred

generators/base-application/__snapshots__/entity.spec.ts.snap, generators/base-application/entity.spec.ts, generators/base-application/entity.ts, generators/base-application/support/prepare-entity.ts, generators/base-application/support/prepare-field.ts, generators/client/support/prepare-entity.ts, generators/server/generators/bootstrap/generator.ts, generators/server/support/prepare-field.ts, lib/testing/index.ts, lib/testing/mutate-data.ts, lib/utils/derived-property.spec.ts, lib/utils/derived-property.ts, lib/utils/object.ts, test/__snapshots__/api.spec.js.snap
Related to https://github.com/jhipster/generator-jhipster/issues/30447.
---
=> add mutateEntity and test support

generators/angular/resources/package.json
=> [Angular] Bump TypeScript 5.9.2

generators/client/templates/README.md.jhi.client.ejs, generators/spring-boot/templates/src/main/resources/config/application-prod.yml.ejs
=> Update spring-boot URLs

generators/base/generator.ts, generators/jdl/generator.ts, lib/command/types.d.ts, lib/jdl/core/models/jdl-relationships.spec.ts, lib/jhipster/types/entity.d.ts
=> Fix some typos

.github/actions/cache-java-dependencies/action.yml
Related to https://github.com/jhipster/generator-jhipster/issues/29194
---
=> replace setup-generator-jhipster-jit with setup-runner

.github/actions/setup-default-node-java/action.yml
Related to https://github.com/jhipster/generator-jhipster/issues/29194.
---
=> remove 00-init-env usage

generators/react/resources/package.json, generators/react/templates/src/main/webapp/app/modules/administration/health/health.tsx.ejs, generators/react/templates/src/main/webapp/app/modules/administration/metrics/metrics.tsx.ejs, generators/react/templates/src/main/webapp/app/modules/administration/user-management/user-management-delete-dialog.tsx.ejs, generators/react/templates/src/main/webapp/app/modules/administration/user-management/user-management-detail.tsx.ejs, generators/react/templates/src/main/webapp/app/modules/administration/user-management/user-management-update.tsx.ejs, generators/react/templates/src/main/webapp/app/modules/administration/user-management/user-management.tsx.ejs, generators/react/templates/src/main/webapp/app/shared/layout/header/header-components.tsx.ejs, generators/react/templates/src/main/webapp/app/shared/layout/menus/admin.tsx.ejs, generators/react/templates/tsconfig.json.ejs
Fix #30492 
https://github.com/FortAwesome/react-fontawesome/releases
https://docs.fontawesome.com/web/use-with/react/add-icons
---
=> Fix: bump @fortawesome/react-fontawesome from 0.2.6 to 3.0.0

generators/javascript/generators/eslint/templates/eslint.config.js.jhi.ejs
=> Remove unnecessary ts-check

generators/server/resources/gradle/libs.versions.toml
Reverts jhipster/generator-jhipster#30517
=> Revert "build(deps): bump org.sonarqube from 6.2.0.5505 to 6.3.0.5676 in /generators/server/resources"

.github/actions/cache-java-dependencies/action.yml
=> cache adjusts

generators/languages/templates/src/main/webapp/i18n/az-Latn-az/metrics.json, generators/languages/templates/src/main/webapp/i18n/by/metrics.json, generators/languages/templates/src/main/webapp/i18n/ca/metrics.json, generators/languages/templates/src/main/webapp/i18n/cs/metrics.json, generators/languages/templates/src/main/webapp/i18n/da/metrics.json, generators/languages/templates/src/main/webapp/i18n/el/metrics.json, generators/languages/templates/src/main/webapp/i18n/es/metrics.json, generators/languages/templates/src/main/webapp/i18n/hi/metrics.json, generators/languages/templates/src/main/webapp/i18n/hu/metrics.json, generators/languages/templates/src/main/webapp/i18n/it/metrics.json, generators/languages/templates/src/main/webapp/i18n/ko/metrics.json, generators/languages/templates/src/main/webapp/i18n/kr-Latn-kr/metrics.json, generators/languages/templates/src/main/webapp/i18n/mr/metrics.json, generators/languages/templates/src/main/webapp/i18n/nl/metrics.json, generators/languages/templates/src/main/webapp/i18n/pt-pt/metrics.json, generators/languages/templates/src/main/webapp/i18n/ro/metrics.json, generators/languages/templates/src/main/webapp/i18n/ru/metrics.json, generators/languages/templates/src/main/webapp/i18n/sk/metrics.json, generators/languages/templates/src/main/webapp/i18n/sv/metrics.json, generators/languages/templates/src/main/webapp/i18n/ta/metrics.json, generators/languages/templates/src/main/webapp/i18n/tr/metrics.json, generators/languages/templates/src/main/webapp/i18n/uz-Latn-uz/metrics.json, generators/languages/templates/src/main/webapp/i18n/vi/metrics.json, generators/languages/templates/src/main/webapp/i18n/zh-cn/metrics.json, generators/languages/templates/src/main/webapp/i18n/zh-tw/metrics.json
=> Add missing translations in metrics.json

eslint.config.ts, lib/command/types.d.ts, lib/jdl/core/parsing/validator.ts, lib/utils/object.ts, package-lock.json, package.json, tsconfig.spec.json, types/eslint-plugin-chai-friendly.d.ts
=> Convert eslint.config.js to eslint.config.ts

generators/angular/templates/src/main/webapp/app/core/util/alert.service.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/shared/filter/filter.model.spec.ts.ejs, generators/client/generators/i18n/templates/src/main/webapp/i18n/en/home.json.ejs, generators/client/generators/i18n/templates/src/main/webapp/i18n/fr/global.json.ejs, generators/java/generators/i18n/templates/src/main/resources/i18n/messages_fr.properties.ejs, generators/react/support/translate-react.spec.ts, generators/react/templates/src/main/webapp/app/modules/home/home.tsx.ejs, generators/react/templates/src/main/webapp/app/shared/reducers/locale.spec.ts.ejs, generators/spring-boot/templates/src/main/resources/static/index_microservices.html.ejs
=> Fix some typos and translations

generators/spring-boot/generators/jwt/templates/src/test/java/_package_/security/jwt/AuthenticationIntegrationTest.java.ejs, generators/spring-boot/generators/jwt/templates/src/test/java/_package_/security/jwt/JwtAuthenticationTestUtils.java.ejs
https://docs.spring.io/spring-boot/api/java/org/springframework/boot/test/mock/mockito/MockBean.html
---
=> Switch MockBean (deprecated) to MockitoBean

generators/angular/templates/src/main/webapp/app/shared/alert/alert-error.ts.ejs, generators/angular/templates/src/main/webapp/app/shared/alert/alert.ts.ejs
=> Angular: Import only NgClass and not all CommonModule 

generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_.vue.ejs
=> Vue: Simplify code

generators/angular/templates/src/main/webapp/app/account/settings/settings.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/admin/health/modal/health-modal.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/admin/metrics/blocks/metrics-modal-threads/metrics-modal-threads.spec.ts.ejs
=> Angular: remove some unnecessary provideHttpClient in tests

generators/angular/templates/src/main/webapp/app/core/util/alert.service.ts.ejs, generators/angular/templates/src/main/webapp/app/core/util/data-util.service.ts.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/update/_entityFile_-form.service.spec.ts.ejs
=> Angular: some improvements

generators/angular/templates/src/main/webapp/app/admin/user-management/delete/user-management-delete-dialog.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/delete/_entityFile_-delete-dialog.spec.ts.ejs
=> [Angular] Rework mock functions

generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/list/_entityFile_.spec.ts.ejs
=> [Angular] Remove unnecessary SpyInstance

generators/angular/templates/src/main/webapp/app/account/activate/activate.ts.ejs, generators/angular/templates/src/main/webapp/app/account/password-reset/finish/password-reset-finish.ts.ejs, generators/angular/templates/src/main/webapp/app/account/register/register.ts.ejs, generators/angular/templates/src/main/webapp/app/admin/user-management/detail/user-management-detail.ts.ejs, generators/angular/templates/src/main/webapp/app/admin/user-management/list/user-management.ts.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/detail/_entityFile_-detail.ts.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/list/_entityFile_.ts.ejs, generators/angular/templates/src/main/webapp/app/home/home.ts.ejs, generators/angular/templates/src/main/webapp/app/layouts/navbar/navbar.ts.ejs, generators/angular/templates/src/main/webapp/app/login/login.ts.ejs
=> [Angular] Not import all RouterModule

generators/angular/templates/src/main/webapp/app/account/password-reset/finish/password-reset-finish.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/account/password-reset/init/password-reset-init.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/account/password/password.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/account/register/register.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/account/settings/settings.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/admin/user-management/update/user-management-update.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/update/_entityFile_-update.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/login/login.spec.ts.ejs
=> [Angular] Tests: Remove unnecessary FormBuilder

generators/angular/templates/src/main/webapp/app/core/util/alert.service.spec.ts.ejs
=> [Angular] Remove duplicated describe

generators/react/templates/src/main/webapp/app/config/notification-middleware.spec.ts.ejs
=> [React] Rewrite sinon tests

generators/react/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_-update.tsx.ejs, generators/react/templates/src/main/webapp/app/modules/account/password-reset/finish/password-reset-finish.tsx.ejs, generators/react/templates/src/main/webapp/app/modules/account/sessions/sessions.tsx.ejs, generators/react/templates/src/main/webapp/app/modules/administration/configuration/configuration.tsx.ejs, generators/react/templates/src/main/webapp/app/modules/administration/health/health.tsx.ejs, generators/react/templates/src/main/webapp/app/modules/administration/metrics/metrics.tsx.ejs, generators/react/templates/src/main/webapp/app/modules/administration/user-management/user-management-detail.tsx.ejs, generators/react/templates/src/main/webapp/app/modules/administration/user-management/user-management-update.tsx.ejs, generators/react/templates/src/main/webapp/app/modules/administration/user-management/user-management.tsx.ejs, generators/react/templates/src/main/webapp/app/modules/login/login-modal.tsx.ejs, generators/react/templates/src/main/webapp/app/shared/layout/header/header.tsx.ejs, generators/react/templates/src/main/webapp/app/shared/layout/menus/locale.tsx.ejs
=> [React] Remove ternary operator

generators/react/templates/src/main/webapp/app/modules/administration/health/health.tsx.ejs, generators/react/templates/src/main/webapp/app/modules/administration/logs/logs.tsx.ejs, generators/react/templates/src/main/webapp/app/modules/administration/metrics/metrics.tsx.ejs
=> [React] Avoid duplicated code

generators/cypress/templates/cypress.config.ts.ejs
=> Unused eslint-disable directive

generators/vue/templates/src/main/webapp/app/admin/health/health-modal.component.ts.ejs, generators/vue/templates/src/main/webapp/app/admin/metrics/metrics-modal.component.ts.ejs, generators/vue/templates/src/main/webapp/app/shared/jhi-item-count.component.ts.ejs, generators/vue/templates/src/main/webapp/app/shared/sort/jhi-sort-indicator.component.ts.ejs
=> [Vue] Fix vue/require-default-prop warnings

generators/vue/templates/src/main/webapp/app/admin/user-management/user-management-view.component.spec.ts.ejs
=> [Vue] Remove unused code

generators/vue/templates/src/main/webapp/app/admin/tracker/tracker.service.spec.ts.ejs, generators/vue/templates/src/main/webapp/app/shared/alert/alert.service.spec.ts.ejs
=> Vue: use toHaveBeenCalledOnce and toHaveBeenCalledExactlyOnceWith

generators/angular/templates/src/main/webapp/app/home/home.ts.ejs
=> [Angular] Fix warning: RouterLink is not used

generators/vue/templates/src/main/webapp/app/admin/user-management/user-management-edit.component.spec.ts.ejs, generators/vue/templates/src/main/webapp/app/admin/user-management/user-management-view.component.spec.ts.ejs, generators/vue/templates/src/main/webapp/app/admin/user-management/user-management.component.spec.ts.ejs, generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_-details.component.spec.ts.ejs, generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_-update.component.spec.ts.ejs, generators/vue/templates/src/main/webapp/app/entities/_entityFolder_/_entityFile_.component.spec.ts.ejs, generators/vue/templates/src/main/webapp/app/shared/alert/alert.service.spec.ts.ejs, generators/vue/templates/src/main/webapp/app/shared/alert/alert.service.ts.ejs
https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/2155
=> [Vue] useToastController is deprecated

generators/angular/templates/src/main/webapp/app/layouts/navbar/navbar.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/login/login.spec.ts.ejs
=> [Angular] Remove useless jest.mock

generators/vue/templates/tsconfig.app.json.ejs
=> [Vue] Fix path in tsconfig.app.json

generators/cypress/templates/README.md.jhi.cypress.ejs
=> Fix readme

generators/angular/templates/src/main/webapp/app/core/util/data-util.service.ts.ejs, generators/angular/templates/src/main/webapp/app/core/util/operators.ts.ejs, generators/angular/templates/src/main/webapp/app/core/util/parse-links.service.ts.ejs
Fix:
- https://sonarcloud.io/project/issues?impactSoftwareQualities=RELIABILITY&issueStatuses=OPEN%2CCONFIRMED&id=jhipster-sample-application&open=AZl2F-AyX95Gr0TMtVBI&tab=code
- https://sonarcloud.io/project/issues?impactSoftwareQualities=RELIABILITY&issueStatuses=OPEN%2CCONFIRMED&id=jhipster-sample-application&open=AZl2F-AJX95Gr0TMtVBE
- https://sonarcloud.io/project/issues?impactSoftwareQualities=RELIABILITY&issueStatuses=OPEN%2CCONFIRMED&id=jhipster-sample-application&open=AZl2F-AcX95Gr0TMtVBG
=> Angular/Sonar Fix some code smells

generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/update/_entityFile_-form.service.ts.ejs
Fix:
- https://sonarcloud.io/project/issues?impactSoftwareQualities=RELIABILITY&issueStatuses=OPEN%2CCONFIRMED&id=jhipster-sample-application&open=AZl2F92cX95Gr0TMtVA2
- https://sonarcloud.io/project/issues?impactSoftwareQualities=RELIABILITY&issueStatuses=OPEN%2CCONFIRMED&id=jhipster-sample-application&open=AZl2F9iOX95Gr0TMtVAA
- ...
=> [Angular] Sonar: Do not use an object literal as default for parameter

package-lock.json, package.json
Reverts jhipster/generator-jhipster#30869
=> Revert "build(deps): bump yeoman-environment from 5.0.0-beta.2 to 5.0.0"

generators/angular/templates/src/main/webapp/app/account/password-reset/finish/password-reset-finish.ts.ejs, generators/angular/templates/src/main/webapp/app/account/password/password.ts.ejs, generators/angular/templates/src/main/webapp/app/account/register/register.ts.ejs, generators/angular/templates/src/main/webapp/app/admin/user-management/update/user-management-update.ts.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/update/_entityFile_-update.ts.ejs, generators/angular/templates/src/main/webapp/app/shared/sort/sort.directive.ts.ejs
Fix all issues like https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&issueStatuses=OPEN%2CCONFIRMED&id=jhipster-sample-application&open=AZl2F-DDX95Gr0TMtVBP
=> [Angular] Sonar: Unexpected negated condition

generators/angular/templates/src/main/webapp/app/admin/user-management/update/user-management-update.ts.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/detail/_entityFile_-detail.spec.ts.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/detail/_entityFile_-detail.ts.ejs, generators/angular/templates/src/main/webapp/app/entities/_entityFolder_/update/_entityFile_-update.ts.ejs
Fix all issues like https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&issueStatuses=OPEN%2CCONFIRMED&id=jhipster-sample-application&open=AZl2F96-X95Gr0TMtVA-
=> [Angular] Sonar: Prefer globalThis over window

generators/angular/templates/src/main/webapp/app/shared/pagination/item-count.ts.ejs
Fix https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&issueStatuses=OPEN%2CCONFIRMED&id=jhipster-sample-application&open=AZl2F-CHX95Gr0TMtVBN
=> [Angular] Sonar: Prefer Math.min() to simplify ternary expressions

generators/angular/templates/src/main/webapp/app/admin/metrics/blocks/jvm-threads/jvm-threads.ts.ejs, generators/angular/templates/src/main/webapp/app/admin/metrics/blocks/metrics-modal-threads/metrics-modal-threads.ts.ejs
Fix:
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&issueStatuses=OPEN%2CCONFIRMED&id=jhipster-sample-application&open=AZl2F954X95Gr0TMtVA9
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&issueStatuses=OPEN%2CCONFIRMED&id=jhipster-sample-application&open=AZl2F95eX95Gr0TMtVA8
=> [Angular] Sonar: Use for…of instead of .forEach(…)

generators/angular/templates/src/main/webapp/bootstrap.ts.ejs, generators/angular/templates/src/main/webapp/main.ts.ejs
Fix:
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&issueStatuses=OPEN%2CCONFIRMED&id=jhipster-sample-application&open=AZl2F-FjX95Gr0TMtVBT
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&issueStatuses=OPEN%2CCONFIRMED&id=jhipster-sample-application&open=AZl2F-FSX95Gr0TMtVBS
=> [Angular] Sonar: Prefer top-level await over using a promise chain

generators/angular/templates/src/main/webapp/bootstrap.ts.ejs, generators/angular/templates/src/main/webapp/main.ts.ejs
Reverts jhipster/generator-jhipster#30941
Generate an other issue: https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&issueStatuses=OPEN%2CCONFIRMED&id=jhipster-sample-application&open=AZmiO3nhSH5T9lrKk5hi
=> Revert "[Angular] Sonar: Prefer top-level await over using a promise chain"

generators/angular/templates/src/main/webapp/app/core/util/data-util.service.ts.ejs
Fix: https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&issueStatuses=OPEN%2CCONFIRMED&id=jhipster-sample-application&open=AZl2F-AyX95Gr0TMtVBH&tab=code
=> [Angular] Sonar: Prefer node:buffer over buffer

generators/docker-compose/__snapshots__/docker-compose.spec.ts.snap, generators/docker-compose/templates/docker-compose.yml.ejs, generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs, generators/docker-compose/templates/realm-config/keycloak-health-check.sh.ejs, generators/docker/templates/docker/keycloak.yml.ejs, generators/docker/templates/docker/realm-config/jhipster-realm.json.ejs, generators/docker/templates/docker/realm-config/keycloak-health-check.sh, generators/server/resources/Dockerfile
=> Fix bump keycloak/keycloak from 26.3.4 to 26.4.0

generators/angular/templates/src/main/webapp/app/core/util/data-util.service.ts.ejs
Fix: https://sonarcloud.io/project/issues?impactSoftwareQualities=RELIABILITY&issueStatuses=OPEN%2CCONFIRMED&id=jhipster-sample-application&open=AZmpNuBKkxjtWor8mX5H
=> [Angular] Sonar: Prefer String#codePointAt() over String#charCodeAt()

generators/angular/templates/src/main/webapp/bootstrap.ts.ejs
=> [Angular] Fix: $localize is not defined

generators/angular/templates/src/main/webapp/bootstrap.ts.ejs, generators/angular/templates/src/main/webapp/main.ts.ejs
Fix:
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&issueStatuses=OPEN%2CCONFIRMED&id=jhipster-sample-application&open=AZl2F-FSX95Gr0TMtVBS
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&issueStatuses=OPEN%2CCONFIRMED&id=jhipster-sample-application&open=AZl2F-FjX95Gr0TMtVBT
=> [Angular] Sonar: Disable Prefer top-level await over using a promise chain

generators/angular/__snapshots__/generator.spec.ts.snap, generators/angular/generator.ts, generators/react/__snapshots__/generator.spec.ts.snap, generators/react/generator.ts, generators/vue/__snapshots__/generator.spec.ts.snap, generators/vue/generator.ts
=> Fix double slashes in paths

rfcs/2-jhipster-rfc-jhipster-control-center.md
=> Fix URL: Spring Boot Admin
