generators/upgrade/index.js

This PR has two changes
1. Stop using jhipster cli when regenerate project. Because it's reason for many related issues 
I tried to use jhipster cli in new versions. Ref https://github.com/jhipster/generator-jhipster/pull/5966
An other issuse `jhipster --force` not working: Ref: https://github.com/jhipster/generator-jhipster/commit/0b9767307f33797d1384ef445fa1c792390ee45d
2. Use exist generated keystore instead of generate new keystore. Less confict, tested on generating uaa project.

Remove new keystore

---

generators/server/templates/src/main/java/package/config/audit/_AuditEventConverter.java

#6114 NPE from `null` resultset when expected AuditEvent is single object

#6114 prevent NPE in Audit Event

---

generators/docker-prompts.js

Currently, if the path entered into the `jhipster docker-compose` does not end in a `/`, the generator will not find any apps.

docker prompts - accept paths not ending with a slash

---

.travis.yml

Following the @deepu105's comments [here](https://github.com/jhipster/generator-jhipster/issues/6051#issuecomment-315560699)
> The build either failed or stalled but its reported as passed. Any idea?
I have the same when running in my computer. As @sendilkumarn said, it's more a WARNING than an ERROR and the build finished with 0 code. So for me, it's ok.
Looking our code [here](https://github.com/jhipster/generator-jhipster/blob/master/travis/scripts/05-run.sh#L72-L75), we should exit the build when there are error
> @pascalgrimaud not just one most of our recent prod builds are stalled at that point so technically we are never testing the prod AOT builds https://travis-ci.org/jhipster/generator-jhipster/jobs/253721138#L3322
The code …

Travis: remove travis_wait

---

generators/generator-base.js
generators/server/templates/src/main/resources/config/liquibase/master.xml

This change enables liquibase tasks other than liquibaseDiffChangeLog.  Tested with `mvn` and `gradle`
Fix #4216

remove classpath prefix from liquibase config

---

generators/kubernetes/templates/_README-KUBERNETES.md

removes redundant kubectl in k8s readme [ci skip]

---

generators/rancher-compose/index.js
generators/rancher-compose/templates/_docker-compose.yml
generators/rancher-compose/templates/_rancher-compose.yml

This adds Zipkin to the rancher-compose subgen when it's chosen.  I copied the config from the docker-compose subgen.

add zipkin to rancher-compose subgen

---

generators/heroku/index.js

Monoliths should prompt for the registry URL when deploying to Heroku if they use Eureka

prompt for registry url when app uses eureka

---

generators/upgrade/index.js

fix command path in upgrade/index.js for windows users

---

generators/server/templates/_pom.xml

Hello Guys,
This is a simple pull request, I've noticed when I was working with docker building with 'Dev' profile is that I got blank page after I run the application. After investigating, it turned out that the source folder is being copied instead of the pre-compiled front end folder 'target/www'. For my purposes I need to build docker images with dev profile. Anyways so I was able to achieve what I wanted by simply changing the property in the pom.xml.
Commits Summary:
1) Updated pom.xml to correctly include built frontend under 'target/www' directory instead of source files

Fixed docker build with dev profile

---

generators/upgrade/index.js

Npm scripts of generator-jhipster are useful for global installation but they are not required in the context of an upgrade where the focus is on code and dependencies.
These scripts can make the upgrade fail for bad reasons like issue #6162 about tabtab. 
This change adds `--ignore-scripts` option  to `yarn add` or `npm install` during upgrade.

Ignore JHipster package.json scripts during upgrade

---

generators/languages/templates/src/main/webapp/i18n/el/_global.json

In case of selecting greek language to the application, the webpack build is broken. eg
{
"packageName": "com.mycompany.company",
"nativeLanguage": "en"
}, 
"jhipsterVersion": "4.6.2",
"baseName": "company",
"packageName": "com.mycompany.company",
"packageFolder": "com/mycompany/company",
"authenticationType": "jwt",
"hibernateCache": "ehcache",
"clusteredHttpSession": false,
"websocket": "spring-websocket",
"devDatabaseType": "h2Disk",
"prodDatabaseType": "mysql",
"searchEngine": "elasticsearch",
"messageBroker": false,
"serviceDiscoveryType": false,
"buildTool": "maven",
"enableSocialSignIn": false,
"jwtSecretKey": "5e51fc29a7e22c1b7ac3aa3a00476c0f25b98221",
"clientFramework": "angularX",
"useSass": …

remove problematic character from greek global.json

---

generators/client/templates/angular/src/main/webapp/app/shared/login/_login.component.ts

The paths used in comparison did not match the actual routes. Also, it makes sense to limit the regular expression to match only if the path *begins* with the string - we do not want to lose a valid deep link like /customer/order/activate.

Redirect to home page after logging in from password reset page

---

generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-popup.service.ts

The problem is the wrong pattern that used for set up the time ("hh" instead "HH")
In addition, today there is no ability to edit the seconds, so I will also add "ss" to the pattern.
This is how the pattern should look like: yyyy-MM-ddTHH:mm:ss

Fix issue #6072 - Fix the wrong date pattern

---

generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management-dialog.component.html

On line [58](https://github.com/jhipster/generator-jhipster/blob/master/generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management-dialog.component.html#L58) the <label> component of the select has a class attribute (`class="form-control-label"`), but not on those two.

Missing class="form-control-label" on select <label> components

---

generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management-dialog.component.ts

If the entity's name was `event` (or `field`) and the entity contained a blob field, a TS error would occur because two variables in the function have the same name.  This makes it so the entity name doesn't matter
Fix #6198

fix "event" entity name

---

generators/client/templates/angular/src/main/webapp/app/shared/login/_login.component.ts

so it wont'get redirect on the second time on login. This could happen, with a quick logout, and login, where the user should stay on the home screen, but without clearing the field, the old value is reused.

Clear out the stored previous url after login

---

generators/client/templates/angular/_package.json
generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management-dialog.component.ts

Dependent on my [pull request](https://github.com/jhipster/ng-jhipster/pull/44) in ng-jhipster and a new release of that library.  Travis will fail until then

move setFileData to ng-jhipster's data-utils

---

generators/entity/files.js
generators/entity/index.js
generators/entity/prompts.js
generators/entity/templates/server/src/main/java/package/common/get_all_template.ejs
generators/entity/templates/server/src/main/java/package/common/inject_template.ejs
generators/entity/templates/server/src/main/java/package/repository/_EntityRepository.java
generators/entity/templates/server/src/main/java/package/service/_EntityQueryService.java
generators/entity/templates/server/src/main/java/package/service/dto/_EntityCriteria.java
generators/entity/templates/server/src/main/java/package/service/impl/_EntityServiceImpl.java
generators/entity/templates/server/src/main/java/package/web/rest/_EntityResource.java
generators/entity/templates/server/src/test/java/package/web/rest/_EntityResourceIntTest.java
generators/generator-base-private.js
generators/server/templates/_pom.xml
generators/server/templates/gradle/_mapstruct.gradle
travis/samples/.jhipster/BankAccount.json
travis/samples/.jhipster/CassTestServiceClassEntity.json
travis/samples/.jhipster/CassTestServiceImplEntity.json
travis/samples/.jhipster/FieldTestServiceClassEntity.json
travis/samples/.jhipster/MicroserviceBankAccount.json
travis/samples/.jhipster/MicroserviceLabel.json
travis/samples/.jhipster/TestEntity.json
travis/samples/.jhipster/TestServiceClass.json
travis/samples/.jhipster/TestServiceImpl.json

Add automatically the static metamodel generation/JPASpecificationExecution, and generate criteria classes and filtering code for JPA (with spring's JPA Specifications)
This is a first version, only SQL is checked, and with 'service' class generation. And the REST controller is not modified yet.
What do you think?

Generate criteria class and backend for filtering

---

cli/jhipster.js

`cli/jhipster.js` now detects whether there's a project local version of `cli/cli.js`so that it is loaded in priority over globally installed version.
Fix #6208

JHipster CLI now runs project local module

---

package.json
yarn.lock

warning generator-jhipster > chalk@2.0.1: Please upgrade to Chalk 2.1.0 - template literals in this version (2.0.1) are quite buggy.

Upgrade chalk to fix warning

---

generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management-dialog.component.html

Workaround for an Angular / IE11 issue. Empty options are removed as soon as a real option has been selected.
fixes #6148

Add empty option for dynamically populated select boxes

---

cli/jhipster.js

This is a follow-up of #6219.
Using local version of upgrade.js could have bugs that have been fixed in more recent version, this is why global version is better for upgrading.
Ref #6208

jhipster upgrade should load global version

---

generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management-dialog.component.html

Internet Explorer 11 seems to have a problem with dynamically filled select boxes. The jhiTranslate directive seems to be evaluated too late in the lifecycle, so IE shows only blank options. It works with Angular's translate pipe, though.
Fixes #6147

Replace directive with translate pipe to fix IE rendering issue

---

generators/generator-base.js
generators/upgrade/index.js

As a user's project grows, the build process can fail due to the same issue as in #6059, a specific example is @dancancro's [Great Big Example Application](https://github.com/dancancro/great-big-example-application). The only way for a developer to work around this is to modify `generator-jhipster` code.
I took the default value from `execa` which [uses 10MB](https://github.com/nodejs/node/issues/9829#issuecomment-263492464).  NodeJS was going to use 1024*1024 but the PR was closed for inactivity (https://github.com/nodejs/node/pull/11196) and this doesn't seem to be enough (see @dancancro's [comment here](https://github.com/jhipster/generator-jhipster/pull/6060#issuecomment-321712546)).

increase exec max buffer

---

generators/server/templates/src/main/resources/config/_application-dev.yml
generators/server/templates/src/main/resources/config/_application-prod.yml

This line results in a blank `data:` in the config for default gateways.  It was used in the past when gateways used Cassandra for rate-limiting.

remove empty data config for gateways

---

generators/openshift/templates/db/_mongodb.yml

"mongodb-bc" port name was used twice, preventing the app to deploy in
openshift
Fix #6240
Note that I could not find tests related to the kind of file I changed

Renamed mongodb port in openshift generator

---

generators/server/templates/gradle/_profile_dev.gradle
generators/server/templates/gradle/_profile_prod.gradle
generators/server/templates/src/main/java/package/config/_LoggingConfiguration.java
generators/server/templates/src/main/java/package/config/_MetricsConfiguration.java
generators/server/templates/src/main/resources/_logback-spring.xml
generators/server/templates/src/main/resources/config/_application.yml
generators/server/templates/src/main/resources/config/_bootstrap.yml
generators/server/templates/src/test/resources/config/_application.yml

Some updates for the integration with the JHipster Console:
- Fix bad InstanceId forwarded to the Console (see https://github.com/jhipster/jhipster-console/issues/55)
- Add artifact version to logs forwarded to the console (for visibility when doing canaries)
- Add JvmAttributeGaugeSet to Dropwizard so that we can have the "uptime" metrics (planned for the registry).
And most important feature:
- When metrics logs are enabled, they are now filtered from the console and file appenders and only sent to logstash !
I'm sure this was a blocker for a lot of people.

Console log forwarding improvements

---

generators/client/templates/angular/src/main/webapp/app/admin/user-management/_user-management-dialog.component.html

Added the missing email validator for the email input.
Angular supports validating emails, but it needs to actively enabled by adding the `email` directive to an `input[type=email]`. More detail can be found [here](https://github.com/angular/angular/issues/13706).

fix email validation in user-management dialog for angular 4

---

generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity.model.ts

When generating an Entity containing an enumeration, this enumeration should be exported in the Angular model.
See discussion : https://stackoverflow.com/questions/45615044/entity-enum-is-not-exported/45616603#45616603

Exporting entity enum

---

cli/jhipster.js
generators/generator-base-private.js
generators/generator-base.js
generators/upgrade/index.js

This will ease debugging `jhipster upgrade` issues.
- Use log.ok() standard method in success() logging method
- Skip install if there are conflicts in `package.json` file
- List the conflicting files  at the end if any
- Set verbose output by default
- Add a `--silent`option
Fix #6237

Improve output of jhipster upgrade

---

generators/heroku/index.js

This change prevents a duplicate DB addon from being created if a user has manually added an addon of another type. For example, if a user has manually added a ClearDB addon, this will not add a JawsDB addon. Fixes #6284

Added explicit name for heroku db creation to prevent duplicates

---

generators/client/templates/angular/webpack/_utils.js
generators/client/templates/angularjs/gulp/_utils.js

After `jhipster upgrade`, pom.xml was not fully merged and so contained `>>>`markers and frontend build failed without any helpful message.
Now it fails with a message indicating the line number of the problem.
I made the change for angularjs and angular.

Show error message when pom.xml parsing failed

---

generators/entity/templates/server/src/test/java/package/web/rest/_EntityResourceIntTest.java

change 'Alice' to entityClass using EJS synthax.
the integration test generator was hardcoded to produce the following comment: 'Validate the Alice in the database'

fix test comment generator _EntityResourceIntTest.java

---

generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management-dialog.component.ts

Error handling seems to be unnecessary at this point:
1. There is a global HTTP error handling routine in alert-error.component.ts
2. The local error handling seems to be broken because if the error response contains json (which is the regular case), response.message stays undefined, so there is no message to show
If there is no specific reason for save error handling in the dialog component, I would propose to remove the code for now.

Remove redundant and broken error handling when saving entities

---

generators/server/templates/_build.gradle
generators/server/templates/_gradle.properties
generators/server/templates/_pom.xml

Fixed #6150 
The `org.reflections.reflections` dependency of `com.github.mongobee.mongobee` needs `com.google.guava:guava version` >= 20. Currently version 18 is imported automatically.
Without this fix the following error occurs:
`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongobee' defined in class path resource [com/company/example/config/DatabaseConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;`
Link to the POM of the `org.reflections.reflections` dependency:
https://github.com/ronmamo/reflections/blob/0.9.11/pom.xml

Fixed Guava version for reflections dependency

---

generators/server/files.js
generators/server/templates/_pom.xml
generators/server/templates/gradle/_docker.gradle
generators/server/templates/src/main/docker/.dockerignore

Fix #6194
I much prefer this new plugin which is more simple in its approach and more "native" to docker.
I have changed some little things, for example I set the full war file name in the dockerfile, this will prevent the issue when you were force to clean the target/ directory because there were two versions of the war file, then the `ADD *.war app.war` instruction was confused.
Also this new plugin paves the way for a new strategy for docker tagging. As it will tag the version of the docker image and store this version in maven build metadata files, I would like to exploit this in the docker-compose and k8s subgen.

Migrate to Dockerfile maven plugin

---

generators/client/templates/angular/_package.json

Update the merge-jsons-webpack-plugin to 1.0.11 where the .json file change detection is fixed,
see: https://github.com/tettusud/merge-jsons-webpack-plugin/issues/21
Add --watch-content-base to the start script of the webpack-dev-server.
Fix #6308

Fixed reload on i18n file changes

---

generators/client/templates/angular/src/main/webapp/app/layouts/navbar/_navbar.component.html
generators/client/templates/angular/src/main/webapp/app/layouts/navbar/_navbar.css
generators/client/templates/angular/src/main/webapp/app/layouts/navbar/_navbar.scss

Initial migration: https://github.com/jhipster/generator-jhipster/commit/4627a9bf0d1f6932b6a18eac2271fafb76631f65
Initial migration appplied constant link colors.
Better migration is to replace old css class `navbar-inverse` with new `navbar-dark` as this changed in Bootstrap 4 beta: https://github.com/twbs/bootstrap/commit/36e482ed2728eec37188b5ec486283334bb3034f
Among other things this change makes active menu highlighted again.

improve navbar migration from bootstrap 4 alpha to beta

---

.travis.yml

Yarn 1.X introduces breaking changes: https://github.com/yarnpkg/yarn/releases/tag/v1.0.0
I have some ideas in how to fix those problems and upgrade to yarn 1.X but it can be done later as it's not straightforward.

Fix Travis protractor builds by fixing yarn version to pre 1.X

---

generators/server/templates/src/main/resources/mails/activationEmail.html
generators/server/templates/src/main/resources/mails/creationEmail.html
generators/server/templates/src/main/resources/mails/passwordResetEmail.html
generators/server/templates/src/main/resources/mails/socialRegistrationValidationEmail.html

The baseUrl is not correctly used in thymeleaf template, so the favicon url is not resolved. Not sure which email client use this, but it seemed wrong.

Fix favicon link in the email template

---

generators/server/templates/src/main/java/package/repository/_UserRepository.java
generators/server/templates/src/main/java/package/service/_SocialService.java
generators/server/templates/src/main/java/package/service/_UserService.java
generators/server/templates/src/main/java/package/web/rest/_AccountResource.java
generators/server/templates/src/main/java/package/web/rest/_UserResource.java
generators/server/templates/src/test/java/package/service/_SocialServiceIntTest.java
generators/server/templates/src/test/java/package/web/rest/_AccountResourceIntTest.java

Currently it is possible to register twice with the same email address, but different case - example@Example.com and example@example.com - which is confusing. And when you ask for a password remainder, currently the user needs to enter with the same case. AFAIK the host names are case-insensitives by some RFC, and the user names by conventions (I haven't seen an email provider, which allowed to register duplicate accounts with different cases.
This patch fixes the problem only for relational dbs, where it can be fixed easily by query.

Email address check should be case insensitive - fixed only for SQL apps

---

generators/server/templates/src/main/java/package/repository/_CustomAuditEventRepository.java
generators/server/templates/src/test/java/package/repository/_CustomAuditEventRepositoryIntTest.java

I got the case while working on a PR for using logstash to report audit events for microservices.
It was causing an exception because the column data is a varchar(255): "JdbcSQLException: Value too long for column".
Now, data is truncated and a warning is logged:
> Event data for test-key too long (265) has been truncated to 255. Consider increasing column width.

Truncate AuditEvent data when length exceeds 255

---

generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management-dialog.component.ts
generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management.component.ts
generators/entity/templates/client/angular/src/main/webapp/app/entities/infinite-scroll-template.ejs
generators/entity/templates/client/angular/src/main/webapp/app/entities/no-pagination-template.ejs
generators/entity/templates/client/angular/src/main/webapp/app/entities/pagination-template.ejs

This prevents conflicts from an entity named `Alert` injecting `AlertService`.  This issue does not affect NG1 apps as the entity service is named `Alert`.
Fix #6257

add jhi prefix to alertService variables in entity pages

---

generators/client/templates/angular/_package.json
generators/client/templates/angular/src/test/javascript/_karma.conf.js
generators/client/templates/angular/src/test/javascript/_protractor.conf.js
generators/client/templates/angularjs/_package.json
generators/client/templates/angularjs/src/test/javascript/_karma.conf.js
generators/client/templates/angularjs/src/test/javascript/_protractor.conf.js
generators/server/templates/gitignore

PhantomJS deprecation announcement: https://groups.google.com/forum/m/#!topic/phantomjs/9aI5d-LDuNE
Last release of PhantomJS: v2.1.1 Jan 24, 2016
This is working great in my tests, hopefully we will even notice performance improvements in Travis

Replace PhantomJS by chromiumHeadless and puppeteer

---

generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity.service.ts

not just a fake object, which has similar structure.
This is useful, if the user adds methods to the entity class later.
The current implementation is confusing, because the user expects, that if he adds some code to the entity.model, then he can use it from the various components

Fix to use the proper entity class on the client side

---

generators/server/templates/src/main/java/package/config/_MicroserviceSecurityConfiguration.java
generators/server/templates/src/main/java/package/config/_SecurityConfiguration.java

CorsFilter needs to be before CsrfFilter or else a CSRF issue blocks the CORS headers from being applied.  Very similar to https://github.com/jhipster/generator-jhipster/issues/4704, related [StackOverflow answer](https://stackoverflow.com/a/46269353/3737815) with more explanation.
This affects Session apps and UAA gateways (now using CSRF) receiving requests from a client that requires CORS headers.
Instructions to reproduce:
- Generate an app with session auth
- Start it in `dev` at localhost:8080, `dev` has CORS on by default
- Go to http://jruddell.com/examples/test.html and open the console.  It's the example from the StackOverflow linked above, hosted so that it requires CORS headers.   It makes a POST request to localhost:8080/api/authenticate to login as user (you can view the …

fix csrf + cors filter chain order

---

generators/aws/lib/aws.js

The main difference with this change is that if you are developing with a locally linked generator-jhipster (mostly just the team), you will need to install the dependencies in that folder.  I can add this to the docs if needed.
Fix #6316

install aws-sdk locally instead of in generator-jhipster folder

---

.travis.yml
generators/generator-constants.js
generators/server/templates/_pom.xml
travis/scripts/02-generate-project.sh

- Yarn 1.0.2
- NodeJS 6.11.3
- NPM 5.4.2
- frontend-maven-plugin 1.6
- remove cache, and use global node 6.11.3
- use yarn global add file, instead of yarn link
Fix https://github.com/jhipster/generator-jhipster/issues/6362
_____

Upgrade Yarn, NodeJS, NPM, frontend-maven-plugin

---

generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/_auth-expired.interceptor.ts
generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/_http.provider.ts

Fixing the js problem "ERROR TypeError: _this.authServerProvider.logout is not a function
at CatchSubscriber.eval [as selector] (VM8171 auth-expired.interceptor.ts:42)
at CatchSubscriber.error (VM7476 catch.js:104)..."
Which caused by wrong dependency declarations - which cause that in AuthExpiredInterceptor
the loginServiceModal is null, and authServerProvider is actually a JhiEventManager.
Unfortunately injecting the AuthServerProvider would cause a cyclic dependency, so the Injector is used,
and the AuthServerProvider is acquired lazily

Fixing the auth-interceptor

---

generators/server/templates/_pom.xml

Change compilation documents to reference `npm start/yarn start`
in order to avoid unnecessary confusion.
Closes #6445

Update continutous compilation documents in pom.xml

---

generators/server/templates/src/main/java/package/domain/_User.java
generators/server/templates/src/main/java/package/service/dto/_UserDTO.java
generators/server/templates/src/main/resources/config/liquibase/changelog/_initial_schema.xml

[UN M.49](https://en.wikipedia.org/wiki/UN_M.49) format is actually 6 characters. An example is "es-419". It is correctly supported by Spring but we do not allow it because of the 5 characters restriction.

UN M.49 format is 6 characters

---

generators/server/templates/gradle/_swagger.gradle

close #6447 by let the file eobject handle win/unix path seperators.

make swagger input spec environment aware

---

generators/client/templates/angular/src/main/webapp/app/admin/audits/_audits.component.ts

Original Fix /audit query date generated with datepipe which under default locale. 
It make a mistake when default locale is not `en` ,for example it may be 2017年-10月-3日

Fix /audit query date format

---

generators/client/files-angular.js
generators/client/files-angularjs.js
generators/client/templates/angular/src/main/webapp/app/account/password-reset/init/_password-reset-init.component.ts
generators/client/templates/angular/src/main/webapp/app/account/register/_register.component.ts
generators/client/templates/angular/src/main/webapp/app/shared/_index.ts
generators/client/templates/angular/src/main/webapp/app/shared/constants/_error.constants.ts
generators/client/templates/angular/src/test/javascript/spec/app/account/password-reset/init/_password-reset-init.component.spec.ts
generators/client/templates/angular/src/test/javascript/spec/app/account/register/_register.component.spec.ts
generators/client/templates/angularjs/src/main/webapp/app/account/register/_register.controller.js
generators/client/templates/angularjs/src/main/webapp/app/account/reset/request/_reset.request.controller.js
generators/client/templates/angularjs/src/main/webapp/app/components/util/_error.constants.js
generators/client/templates/angularjs/src/test/javascript/spec/app/account/register/_register.controller.spec.js
generators/client/templates/angularjs/src/test/javascript/spec/app/account/reset/request/_reset.request.controller.spec.js
generators/entity/templates/server/src/main/java/package/web/rest/_EntityResource.java
generators/server/files.js
generators/server/templates/src/main/java/package/web/rest/_AccountResource.java
generators/server/templates/src/main/java/package/web/rest/_UserResource.java
generators/server/templates/src/main/java/package/web/rest/errors/_BadRequestAlertException.java
generators/server/templates/src/main/java/package/web/rest/errors/_EmailAlreadyUsedException.java
generators/server/templates/src/main/java/package/web/rest/errors/_EmailNotFoundException.java
generators/server/templates/src/main/java/package/web/rest/errors/_ErrorConstants.java
generators/server/templates/src/main/java/package/web/rest/errors/_ExceptionTranslator.java
generators/server/templates/src/main/java/package/web/rest/errors/_InvalidPasswordException.java
generators/server/templates/src/main/java/package/web/rest/errors/_LoginAlreadyUsedException.java
generators/server/templates/src/test/java/package/web/rest/_AccountResourceIntTest.java
test/utils/expected-files.js

Throw `Problem` exceptions that will be treated by the `ExceptionTranslator` instead of returning `ResponseEntity` with an unchecked body
See #6404

Refactor AccountResource, UserResource and EntityResource to use Problem

---

generators/server/templates/gitattributes

Without this parameter, you can have an issue using Docker on Windows
for project on Git environment:
- when you clone an existing JHipster project, the EOL of sh files could
be updated to CRLF on Windows OS (depending on local Git configuration)
- when you run Docker with these sh files (for instance Couchbase, see #6327),
Docker can't execute them as they are not recognized.
It is the same thing with bat files on Windows, and it is already forced
as CRLF in the same file. On the sample repo you chose, you can notine it defines this rule as
well for Web profiles:
https://github.com/alexkaratarakis/gitattributes/blob/master/Web.gitattributes

Configure sh files with LF as default EOL

---

generators/generator-base.js

Small change - generates the key store for UAA apps synchronously instead of async.  This lets the project fully generate before committing to git

make generateKeyStore synchronous to finish before git init

---

generators/client/templates/angular/webpack/_webpack.common.js
generators/generator-base.js
generators/modules/index.js

Add External contents to webpack

---

generators/entity/templates/server/src/main/java/package/service/mapper/_EntityMapper.java

Currently:
```
@Mapper(componentModel = "spring", uses = {FormationMapper.class, SessionMapper.class, })
public interface EntretienFormationMapper extends EntityMapper <EntretienFormationDTO, EntretienFormation> {
```
This PR:
```
@Mapper(componentModel = "spring", uses = {FormationMapper.class, SessionMapper.class})
public interface EntretienFormationMapper extends EntityMapper<EntretienFormationDTO, EntretienFormation> {
```

Formatting and avoid last comma on mappers list

---

generators/app/index.js
test/app.spec.js

Fix bug where jhiPrefix would default to 'jhi' in Angular components and .angular-cli.json because this.configOptions.jhiPrefix was never assigned a value.
Fix #6525

Fix for custom jhiPrefix not being assigned correctly

---

generators/client/templates/angular/src/main/webapp/app/admin/user-management/_user-management.component.html
generators/client/templates/angularjs/src/main/webapp/app/admin/user-management/_user-management.html
generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management.component.html

Apply this fix https://github.com/jhipster/generator-jhipster/issues/4347 on:
Angular 4: Entity and User
AngularJS: User
(This is to be able to override `this.itemsPerPage = ITEMS_PER_PAGE;` by something like `this.itemsPerPage = 8;` and have the directive working. Otherwise itemsPerPage is assigned to ITEMS_PER_PAGE (20), `uib-pagination.config.ts`)

add pageSize (or items-per-page) on pagination directive

---

generators/server/templates/src/test/java/package/service/_UserServiceIntTest.java

The UserService test is brittle since it relies on a predefined state of the User repository (eg. it assumes that an `admin` user [is present](https://github.com/jhipster/generator-jhipster/blob/v4.9.0/generators/server/templates/src/test/java/package/service/_UserServiceIntTest.java#L69)). So if a previous test does a cleaning of the User repository (eg. [UserResourceIntTest](https://github.com/jhipster/generator-jhipster/blob/v4.9.0/generators/server/templates/src/test/java/package/web/rest/_UserResourceIntTest.java#L196) if for some reason your tests are not executed in alphabetical path order), then the test will fail. See #6269 for a test failure case.

Make UserService test more robust

---

generators/server/templates/src/main/java/package/gateway/_TokenRelayFilter.java

Some people could use it to abuse the system, as you could have 2 "authorization" headers. It's better not to trust the one from the browser.
See #6519

Keep the "authorization" ignored header with OIDC

---

generators/client/templates/angular/src/test/javascript/_karma.conf.js
generators/client/templates/angularjs/src/test/javascript/_karma.conf.js

add no-sandbox to chromium options
option allows chromium tests to be run as root, typically in a docker context
Fix #6545
- [X ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [X ] Tests are added where necessary
- [ X] Documentation is added/updated where necessary
- [ X] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

add no-sandbox to chromium options

---

generators/client/templates/angular/src/main/webapp/app/admin/configuration/_configuration.component.html
generators/client/templates/angular/src/main/webapp/app/admin/logs/_logs.component.html
generators/client/templates/angular/src/main/webapp/app/admin/metrics/_metrics-modal.component.html
generators/client/templates/angular/src/main/webapp/app/admin/metrics/_metrics.component.html
generators/client/templates/angular/src/main/webapp/content/css/_global.css
generators/client/templates/angular/src/main/webapp/content/scss/_global.scss

Fix styling issues and remove animated progressbars from metrics page (I think they make the view very uneasy  to look at.
Close #6529

Ui fixes 6529

---

generators/entity/templates/server/src/test/java/package/web/rest/_EntityResourceIntTest.java
generators/server/templates/src/test/java/package/web/rest/_TestUtil.java

where the date is not formatted as ISO
In this case, we pass the LocalDate as a string in the URL, for example as /api/bank-accounts?openingDay.equals=1970-01-01 , but in the test context, the date formatter is not configured properly, so it is expecting the date formatted as 1970/01/01 or some other locale specif way. Fortunately this works in dev/prod mode, where the {packageName}/config/DateTimeFormatConfiguration takes care of the DateTimeFormatterRegistrar's configuration

Fix error running the filtering tests on locales

---

generators/server/templates/src/main/java/package/service/_MailService.java

I did not find this error in the issues, I just ran into it and fixed. It can be reproduced by signing in using Spring Social in newly generated project.
Error log:
> 2017-10-22 19:50:04.427 DEBUG 20656 --- [list-Executor-2] c.a.myapp.service.MailService         : Sending social registration validation email to 'some-random-email@gmail.com'
> 2017-10-22 19:50:04.680 ERROR 20656 --- [list-Executor-2] org.thymeleaf.TemplateEngine             : [THYMELEAF][myapp-Executor-2] Exception processing template "socialRegistrationValidationEmail": Link base "null/favicon.ico" cannot be context relative (/) or page relative unless you implement the org.thymeleaf.context.IWebContext interface (context is of class: org.thymeleaf.context.Context) (socialRegistrationValidationEmail:6)
> 2017-10-22 …

Fix exception when sending social registration validation email

---

generators/server/templates/gradle/_liquibase.gradle

Gradle and liquibase allows only diffChangeLog command.
With this change, you can specify others with task liquibase and -PliquibaseCommand, e.g. 
gradlew liquibase -PliquibaseCommand=clearChecksums
This is similar to Maven liquibase:clearChecksums
The existing task liquibaseClearChecksums is retained for compatibility.

Allow multiple liquibase commands in Gradle, similar to Maven

---

generators/app/templates/_skipClientApp.package.json

When generating an app without client code, upgrade generator fails because yarn complains about no licence. Adding `"private": true` to `package.json` avoids this error and makes a lot of sense as there's no npm module to publish anyway.
See https://github.com/yarnpkg/yarn/issues/3821

Fix yarn failure when upgrading microservices

---

generators/upgrade/index.js

Provide user with a helpful message when jhipster upgrade is run from a directory that is not a JHipster project.
Fix #6596

Check that upgrade is run from a JHipster project directory

---

generators/client/files-angular.js
generators/client/templates/angular/src/main/webapp/app/_app-routing.module.ts
generators/client/templates/angular/src/main/webapp/app/_app.module.ts
generators/client/templates/angular/src/main/webapp/app/account/_account.module.ts
generators/client/templates/angular/src/main/webapp/app/admin/_admin.module.ts
generators/client/templates/angular/src/main/webapp/app/layouts/_index.ts
generators/client/templates/angular/src/main/webapp/app/layouts/navbar/_navbar.route.ts
generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management.module.ts

This PR is an anwser to the discussion #6565 thus #5833.
I replaced the `forRoot` by `forChild` to have only one Root Router module dealing with errors, navbar and so on.
I have replce the `layout-routing.module` by a more standard top-level `app-routing.module`
See https://angular.io/tutorial/toh-pt5 for further details.

Update Angular routing strategy

---

generators/server/templates/src/main/java/package/service/dto/_UserDTO.java
generators/server/templates/src/main/java/package/web/rest/vm/_ManagedUserVM.java
generators/server/templates/src/test/java/package/web/rest/_AccountResourceIntTest.java
generators/server/templates/src/test/java/package/web/rest/_UserResourceIntTest.java

- Define setters in UserDTO and ManagedUserVM
- Avoid to have a constructor with "too" many arguments..
- Knowing what fields are set, (vs comments in the constructor call)
- Avoid pass `null` for several fields in Tests (`createdBy`, `createdDate`, `lastModifiedBy`, `lastModifiedDate`)
- having UserDTO and ManagedUserVM looking the same that EntityDTO (getters + setters)
It is mostly about readability (big constructor vs setters) and people taste as well (?), so feel free to close it if the added value is not worth or if I missed something. thx.

use setters instead of constructor for UserDTO and ManagedUserVM

---

generators/client/templates/angularjs/src/test/javascript/_protractor.conf.js

Related to @deepu105's https://github.com/jhipster/generator-jhipster/pull/6474#issuecomment-340284102
The reason why the build failed, is because you used NPM instead of Yarn. With that, we detected this issue. As the `node_modules` folder is managed differently between Yarn and NPM, the selenium folder is not at the same place.
It should fix the build in the [generator-jhipster-entity-audit](https://github.com/hipster-labs/generator-jhipster-entity-audit)
___

Fix protractor tests for NPM

---

generators/server/templates/src/test/resources/config/_application.yml

When I was refactoring the OIDC / OAuth integration, I found I needed to have the security settings duplicated in the test directory's `application.yml`. This seemed strange, especially since the property values are the same as the ones in the main directory's `application.yml`. Now, it seems this is no longer necessary.
I tested this by making this modification in the generator-jhipster project and then running `npm link`. 
Then I generated three different projects with OAuth 2.0, Session Auth, and JWT. I ran `./mvnw test` in each to confirm everything worked. I did not test UAA, but I'm guessing the behavior should be the same.

Remove duplicate security configuration

---

generators/server/templates/_build.gradle
generators/server/templates/_gradle.properties
generators/server/templates/_pom.xml

This removes two dependencies that aren't used by the generated app, one of which (thymeleaf-layout-dialect) was transitively pulling in all of groovy (at a whopping 4.5 MB!).
Of course if people want to use the thymeleaf dialect after all it's easy enough for them to remove the exclusion.

Remove unused dependencies: awaitility and thymeleaf-layout-dialect

---

generators/client/templates/angular/src/main/webapp/app/shared/auth/_auth-jwt.service.ts
generators/client/templates/angularjs/src/test/javascript/spec/app/services/auth/_auth.services.spec.js

When using traefik, signout should go to gateway : /gateway/auth/logout and not root /auth/logout
I verified with angular4.
Fix #6652

Fix for signout when using uaa and traefik

---

generators/cloudfoundry/USAGE
generators/cloudfoundry/index.js
generators/generator-base.js
generators/heroku/USAGE
generators/heroku/index.js
generators/server/templates/_build.gradle
generators/server/templates/_pom.xml

Sorry for all these PRs guys, I'm trying to keep my proposals small and topical.
As you probably guessed by now, I am attempting to reduce the size of my WAR and submitting changes I make that I think might be generally useful here.
In this case I would like to exclude the provider-specific cloud connectors from the build, until the user indicates s/he wants them by running the relevant subgenerator.
This makes a largish difference, particularly because the jar for the CloudFoundry connector is pretty huge -- it includes most of Jackson, for some reason.

Exclude cloudfoundry and heroku connectors until needed

---

generators/aws/index.js

I will update the docs in the next days - just to mention that mariadb is supported. The aws generator also needs some better error checks, but that's another issue.
I need to go back and try docker-compose - I think this would be simpler for my user-case.

AWS also supports mariadb.

---

generators/client/templates/angular/src/main/webapp/swagger-ui/_index.html
generators/client/templates/angularjs/src/main/webapp/swagger-ui/_index.html

UAA apps now use an XSRF Token and expect the token to change on every request. UAA apps also no longer use a token header for authentication (switched to cookies in v4.9.0).
This doesn't seem to affect the other auth types so I left them as is.
Fix #6657

fix swagger for UAA apps

---

generators/generator-base-private.js
generators/generator-constants.js
generators/server/index.js
generators/server/templates/_build.gradle
generators/server/templates/_gradle.properties
generators/server/templates/_pom.xml
generators/server/templates/gradle/_liquibase.gradle
generators/server/templates/gradle/_prometheus.gradle
generators/server/templates/src/test/resources/_cassandra-random-port.yml

See https://github.com/jhipster/generator-jhipster/issues/6061
So with this PR, almost all (*) dependencies are managed by the new `jhipster-dependencies` BOM, and unified across Maven and Gradle. There's one extra commit that can be discarded once 0.0.4 of the BOM is released with upgraded Cassandra driver artifacts.
(*) one exception are the inner deps within plugin configuration.

Use jhipster-dependencies BOM

---

generators/client/templates/angular/src/main/webapp/app/layouts/navbar/_navbar.component.ts
generators/client/templates/angular/src/main/webapp/app/layouts/profiles/_page-ribbon.component.ts
generators/client/templates/angular/src/main/webapp/app/layouts/profiles/_profile.service.ts

Twice for opening the home page, one call is from the navbar.component.ts, the second is from the page-ribbon.

Fix to not call unnecessarily the /api/profile-info method multiple times

---

generators/server/templates/_build.gradle
generators/server/templates/_pom.xml
generators/server/templates/gradle/_profile_dev.gradle
generators/server/templates/src/main/java/package/config/_DatabaseConfiguration.java
generators/server/templates/src/main/java/package/config/_WebConfigurer.java

When users select different databases for development and production (as when following the default choices) they will end up with two drivers in their package. This PR will make sure that they only get the appropriate one for the profile they're packaging.
It slightly increases the complexity of the generator(*) -- I wanted to keep the dependency in the general section in case dev and prod are the same database -- will have no effect on the complexity on the generated maven/gradle build, and will make the packaged artifact simpler.
Hope this makes sense!
(*) Alternatively, if you prefer, I could just put the driver in the profiles even when they're the same for dev and prod, which would not increase the generator complexity at all.
- Please make sure the below checklist is followed for …

Don't put two database drivers in a single package

---

README.md

URL changed from sonarqube.com to sonarcloud.io.  Currently the links take you to the Sonar home page.

fix sonar links in readme [ci skip]

---

generators/server/templates/src/main/java/package/config/_LoggingConfiguration.java

In the SpringCloudConfig, Spring will refresh its configuration even the app is already running.  Spring will call the `LoggerContext` to refresh all the logger config. which will `StopAndReset` the log config. it will stop all the logappender and remove all the `LoggerContextListener`.   After that, `LoggerContext `will load the new configuration based on the configuration file (logback-spring.xml) . then, Spring will call the configuration class ...... , but here, the `LoggingConfiguration` bean is a singleton and already been created. 
In this case, the above `LoggingConfiguration`  won't be created again (even the `logstash-appender` has been stopped).
We add the `@RefreshScope` here to force Spring to recreate this bean when there is configuration refresh
- Please make sure the below …

6668 -  fix the logstash-appender stopping working issues

---

generators/docker-compose/templates/_jhipster-console.yml

Docker-compose : don't expose jhipster-elasticsearch port 9200 on the host

---

generators/server/templates/_pom.xml

I hope it will fix https://github.com/jhipster/generator-jhipster/issues/6741
_____

Fix packaging for Microservices

---

generators/entity-server/templates/src/test/java/package/web/rest/_EntityResourceIntTest.java

in order to update the entity trough the api we need to disconnect the
created entity from the em session because else the changes of the
entity will be propagated directly to the db and errors in the api call
will not be detected
Fix #6671

disconnect created entity in update test from em session

---

generators/server/templates/_build.gradle
generators/server/templates/_pom.xml
travis/scripts/04-tests.sh

Recently we have seen several questions or issues due to users using JDK 9. This commit makes maven and gradle fail in this case.
Display env info at start of Travis build
Ref  #6391

Prevent from using JDK 9

---

CONTRIBUTING.md

After linking the local generator, I have problems to see the changes when running jhipster in my local app. The problem was that I need to run `jhipster --with-entities` because the changes that I have done in the generator were in the entity template.
Such a hint will save times for newbies like me.

Add hint for how to run jhipster after linking local generator

---

generators/server/templates/_pom.xml

disable the proxy setting for un-necessary jobs for the frontend plugin
which may cause error

disable the auto proxy for un-necessary jobs

---

.travis.yml
generators/entity-server/templates/src/main/java/package/domain/_Entity.java
generators/entity-server/templates/src/main/java/package/repository/search/_EntitySearchRepository.java
generators/entity-server/templates/src/test/java/package/web/rest/_EntityResourceIntTest.java
generators/server/prompts.js
generators/server/templates/src/main/java/package/config/_DatabaseConfiguration.java
generators/server/templates/src/main/java/package/domain/_User.java
travis/samples/app-ng2-mongodb-elasticsearch/.yo-rc.json
travis/scripts/01-generate-entities.sh

This is a first attempt to fix this issue https://github.com/jhipster/generator-jhipster/issues/1810
@jdubois @deepu105 Let me know if you have any feedback on this. I also would like to add tests to this and solve this non-blocking issue:
`org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [file:/Users/rmaalej/Documents/dev/workspace/expensy/expensy-analytics/build/classes/scala/main]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
at org.reflections.vfs.Vfs.fromURL(Vfs.java:109)
at org.reflections.vfs.Vfs.fromURL(Vfs.java:91)`

Add elasticsearch option when mongo is selected

---

generators/server/prompts.js

‘hazelcast session clustering’ and ‘oauth2’ options are incompatible and login doesn’t work when the two options are selected. See  #6756's related comments and conclusion for more details.
Fix #6756

disable 'Clustered HTTP sessions using Hazelcast' option when oauth2 is selected

---

generators/client/templates/angular/src/main/webapp/app/shared/model/_request-util.ts

**filter**  url param need to be passed in the url when we use _*-is-null_ filter to get the entities not already linked.
The server use it through this template `get_all_stream_template.ejs`.
Related to https://github.com/jhipster/generator-jhipster/issues/6735

add filter url param

---

generators/entity/index.js

Microservices are failing to save `microserviceName` in the entity's JSON file, which leads to a failure if manually importing it into the gateway.
```
Using JHipster version installed locally in current project's node_modules
Executing jhipster:entity Foo
Options: 
The entity Foo is being created.
? Do you want to generate this entity from an existing microservice? Yes
? Enter the path to the microservice root directory: ../ms
Found the .jhipster/Foo.json configuration file, entity can be automatically generated!
Error: ERROR! Microservice name for the entity is not found. Entity cannot be generated!
at Environment.error (/private/tmp/jh/gway/gway/node_modules/yeoman-environment/lib/environment.js:157:40)
at Object.error (/private/tmp/jh/gway/gway/node_modules/generator-jhipster/generator …
```

fix generating microservice entities on a gateway

---

generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/_auth.interceptor.ts

If a developer specifies a separate backend server as the SERVER_API_URL, we should allow the Authorization header to go to that server.  The current behavior when authenticating in a separated client/server is that the login modal closes with successful call to `/api/authenticate` but then a 401 is received from `/api/account` due to no Authorization header.
This still prevents any URLs containing `http` other than the SERVER_API_URL
Fix #6798

allow Authorization header to the specified SERVER_API_URL

---

generators/server/templates/src/main/resources/config/_application-dev.yml
generators/server/templates/src/main/resources/config/_application.yml

If you try to access the user-management page or any entity page from an app using a separated client/server, the call to `this.links = this.parseLinks.parse(headers.get('link'));` fails because the `link` header is not exposed to the client.  Same situation for the `X-Total-Count` header.

expose link and x-total-count headers when using CORS

---

generators/client/index.js
generators/client/templates/angular/src/main/webapp/app/_app.constants.ts
generators/client/templates/angular/src/main/webapp/app/account/activate/_activate.service.ts
generators/client/templates/angular/src/main/webapp/app/account/password-reset/finish/_password-reset-finish.service.ts
generators/client/templates/angular/src/main/webapp/app/account/password-reset/init/_password-reset-init.service.ts
generators/client/templates/angular/src/main/webapp/app/account/password/_password.service.ts
generators/client/templates/angular/src/main/webapp/app/account/register/_register.service.ts
generators/client/templates/angular/src/main/webapp/app/account/sessions/_sessions.service.ts
generators/client/templates/angular/src/main/webapp/app/admin/audits/_audits.service.ts
generators/client/templates/angular/src/main/webapp/app/admin/configuration/_configuration.service.ts
generators/client/templates/angular/src/main/webapp/app/admin/gateway/_gateway-routes.service.ts
generators/client/templates/angular/src/main/webapp/app/admin/health/_health.service.ts
generators/client/templates/angular/src/main/webapp/app/admin/logs/_logs.service.ts
generators/client/templates/angular/src/main/webapp/app/admin/metrics/_metrics.service.ts
generators/client/templates/angular/src/main/webapp/app/layouts/profiles/_profile.service.ts
generators/client/templates/angular/src/main/webapp/app/shared/auth/_account.service.ts
generators/client/templates/angular/src/main/webapp/app/shared/auth/_auth-jwt.service.ts
generators/client/templates/angular/src/main/webapp/app/shared/auth/_auth-session.service.ts
generators/client/templates/angular/src/main/webapp/app/shared/user/_user.service.ts
generators/client/templates/angular/src/test/javascript/spec/app/shared/user/_user.service.spec.ts
generators/client/templates/angular/webpack/_webpack.common.js
generators/client/templates/angularjs/src/main/webapp/app/services/auth/_account.service.js
generators/client/templates/angularjs/src/main/webapp/app/services/auth/_activate.service.js
generators/client/templates/angularjs/src/main/webapp/app/services/auth/_password-reset-finish.service.js
generators/client/templates/angularjs/src/main/webapp/app/services/auth/_password-reset-init.service.js
generators/client/templates/angularjs/src/main/webapp/app/services/auth/_password.service.js
generators/client/templates/angularjs/src/main/webapp/app/services/auth/_register.service.js
generators/client/templates/angularjs/src/main/webapp/app/services/auth/_sessions.service.js
generators/client/templates/angularjs/src/main/webapp/app/services/user/_user.service.js

Simplified the three API url variables into one - `this.apiUaaPath` which is only used on routes that the UAA controls (user auth/management).

add SERVER_API_URL to UAA apps

---

generators/client/templates/angularjs/src/test/javascript/_protractor.conf.js

Fix protractor builds for ng1 application:
See https://travis-ci.org/jhipster/generator-jhipster/jobs/314358422 :
```
[03:39:50] E/direct - Error message: Could not find chromedriver at /home/travis/app/node_modules/webdriver-manager/selenium/chromedriver_2.33. Run 'webdriver-manager update' to download binaries.
[03:39:50] E/direct - Error: Could not find chromedriver at /home/travis/app/node_modules/webdriver-manager/selenium/chromedriver_2.33. Run 'webdriver-manager update' to download binaries.
at Direct.getNewDriver (/home/travis/app/node_modules/gulp-protractor/node_modules/protractor/built/driverProviders/direct.js:68:27)
at Runner.createBrowser (/home/travis/app/node_modules/gulp-protractor/node_modules/protractor/built/runner.js:195:43)
at q.then.then …
```

Fix version of selenium chromedriver to 2_34 for AngularJS

---

generators/client/templates/angular/src/main/webapp/app/shared/_shared-common.module.ts
generators/generator-base.js
generators/generator-constants.js
package-lock.json

Fix for https://github.com/jhipster/generator-jhipster/issues/6836. Let's see about the coding rules (using a constructor ?)
check 'Pipes, i18n and breaking changes' in http://blog.ninja-squad.com/2017/11/02/what-is-new-angular-5/

import locale for angular

---

generators/server/templates/src/main/java/package/config/_WebConfigurer.java

Separate client/server apps need CORS configured on `/management/**` or several of the admin pages don't fetch data properly

configure CORS for the management path

---

generators/entity-server/templates/src/main/resources/config/liquibase/changelog/_added_entity.xml
generators/entity/prompts.js
generators/generator-constants.js
travis/samples/.jhipster/Division.json

This is a pull request for single-field unique constraints, as discussed in this issue: [Adding commands for unique constraints](https://github.com/jhipster/jhipster-core/issues/18)
It includes fixes for the findings detailed in the [previous pull request](https://github.com/jhipster/generator-jhipster/pull/6678).

Add "unique" field validation

---

generators/client/templates/angular/_package.json

Angular 5.1.0 officially supports TypeScript 2.5.x

Upgrade Angular to 5.1.0 / TypeScript to 2.5.3

---

generators/entity-client/templates/angular/src/main/webapp/app/entities/_entity.service.ts
generators/entity-client/templates/angular/src/test/javascript/spec/app/entities/_entity-management.service.spec.ts

The SERVER_API_URL be used everywhere.  Related to https://github.com/jhipster/generator-jhipster/pull/6833, I forgot to change the entity services.

use SERVER_API_URL in gateway entities using uaa

---

generators/client/templates/angular/_package.json

`tslint --project './tsconfig.json' -e 'node_modules/**'`
failed on Windows due to `./` path

Fix lint script for Windows

---

generators/server/templates/src/test/java/package/config/_WebConfigurerTest.java

On Master, the tests failed when choosing Clustered HTTP Session with Hazelcast:
```
{
"packageName": "io.github.pascalgrimaud",
"nativeLanguage": "en"
},
"jhipsterVersion": "4.13.0",
"baseName": "jhipster",
"packageName": "io.github.pascalgrimaud",
"packageFolder": "io/github/pascalgrimaud",
"authenticationType": "jwt",
"cacheProvider": "hazelcast",
"enableHibernateCache": true,
"clusteredHttpSession": "hazelcast",
"websocket": false,
"devDatabaseType": "h2Disk",
"prodDatabaseType": "mysql",
"searchEngine": false,
"messageBroker": false,
"serviceDiscoveryType": false,
"buildTool": "maven",
"enableSocialSignIn": false,
"enableSwaggerCodegen": false,
"jwtSecretKey": …
```

Fix tests for Clustered HTTP Session with Hazelcast

---

generators/kubernetes/templates/console/_logstash-config.yml

The Kubernetes generator did not include the TCP listener in the Logstash config.
Would love to add some tests, but not sure how to test this.

Kubernetes logstash config: added TCP listener

---

generators/docker-compose/templates/_docker-compose.yml

Fix of invalid docker-compose.yml file structure when both Prometheus and Keycloak are used.
- [] Documentation is added/updated where necessary

Fixes #6920

---

generators/client/templates/angular/src/test/javascript/spec/app/admin/audits/_audits.component.spec.ts

Fix #6926
just a little refactorization to remove the duplicate code that builds 2 digits date parts in the function getDate of the audits component tests

Refactorization of the 2 digits date part code in audit component tests

---

generators/server/templates/_pom.xml
generators/server/templates/gradle/_profile_dev.gradle
generators/server/templates/gradle/_profile_prod.gradle
generators/server/templates/src/main/resources/config/_application.yml

Fix profile substitutions for all configurations that were broken :
- microservice, gateway, uaa with maven
- monolith + service discovery, it was actually working partially as the profile was correctly set in application.yml. However this is subtly wrong as it prevent from retrieving the right profile specific configuration from the config server.

Fix spring profile yml substitution for apps using service discovery

---

generators/client/templates/angular/_package.json
generators/client/templates/angular/webpack/_webpack.prod.js

This is a fix for a major issue that made prod builds to fail for some users.
Only solution found (thanks  @kaidohallik) was to upgrade workbox-webpack-plugin from 2.1.2 to 3.0.0-alpha.3.
Tested successfully on Ubuntu 17.10 and Windows 10 with JHipster 4.13.2 using maven where it was failing systematically.
Fix #6945

Fix build error with sw-workbox

---

generators/generator-base.js

When you run `jhipster` in an existing UAA application, the regeneration is blocked because `done()` is never called when a keystore.jks already exists. This PR lets regeneration continue.  
<details>
<summary>Example output showing the issue, jhipster exits here</summary>
<pre>
Executing jhipster:app
Options: 
██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
http://www.jhipster.tech
Welcome …

fix blocking of uaa app regeneration

---

.travis.yml
generators/generator-constants.js
travis/scripts/00-install-jhipster.sh

Improve the installation:
- it will help jhipster-dependency, jhipster (lib) projects, as it will use the same scripts to install the full stack
- the branch spring-boot-2 won't need to wait new release because this new installation can use specific distant branch
By default, the current Travis won't use any branch or master, but official release instead.
_____

Travis: new install script for jhipster-dependency and jhipster lib

---

generators/client/templates/angular/src/main/webapp/app/_app.module.ts
generators/client/templates/angular/src/main/webapp/swagger-ui/_index.html

In scenario where jhi-prefix option is provided to override default, use same as storage prefix as well as in swagger ui while retrieving token

Use jhi-prefix option instead of default jhi

---

generators/aws/prompts.js

Added support for deploying JHipster projects on AWS `eu-west-2` (London) region

added 'eu-west-2' to supported deployment regions

---

generators/client/templates/angular/_package.json
generators/client/templates/react/_package.json

The `--progress` option on webpack will fail for any non-interactive terminal. This breaks JHipster on CI servers, and Heroku (if deploying with `git`, which is not the default option today) with an error like:
```
[ERROR]  30% building modules 167/212 modules 45 active .sed: couldn't write 237439 items to stdout: Resource temporarily unavailable
```
For more information see https://github.com/webpack/webpack/issues/1553
If this change is not accepted, I recommend a new script entry `"webpack:prod:ci"` or similar. I will add this myself if desired.

Remove --progress from production webpack build

---

generators/entity/index.js

Update context with prefixed table name and prints instructions for user about how to change it to a better name.
Fix #7028

Save table name to JSON entity definition when prefix is added

---

generators/client/templates/angular/_tslint.json
generators/client/templates/angular/src/main/webapp/app/account/password/_password-strength-bar.component.ts
generators/client/templates/angular/src/main/webapp/app/shared/model/_base-entity.ts
generators/client/templates/angular/src/main/webapp/app/shared/model/_request-util.ts
generators/client/templates/angular/src/test/javascript/spec/app/account/password-reset/init/_password-reset-init.component.spec.ts
generators/client/templates/angular/src/test/javascript/spec/app/account/register/_register.component.spec.ts
generators/client/templates/angular/src/test/javascript/spec/app/admin/audits/_audits.component.spec.ts
generators/client/templates/angular/src/test/javascript/spec/app/shared/login/_login.component.spec.ts
generators/client/templates/angular/src/test/javascript/spec/app/shared/user/_user.service.spec.ts
generators/client/templates/angular/src/test/javascript/spec/helpers/_mock-state-storage.service.ts
generators/entity-client/templates/angular/src/test/javascript/e2e/entities/_entity.spec.ts
generators/entity-client/templates/angular/src/test/javascript/spec/app/entities/_entity-management.service.spec.ts

4d6bf48:
```
"semicolon": [
"always"
]
```
should be
```
"semicolon": [
true,
"always"
]
```
5718bba:
fix tslint warning

fix tslint semicolon config for Angular

---

generators/entity-client/templates/angular/src/main/webapp/app/entities/_entity.service.ts

ensures the service queries an API relative to the URL if SERVER_API_URL not set
also fixes any apps that hosted on a context path
Fix #7036

remove forward slash before entity API url

---

generators/server/templates/src/main/java/package/security/jwt/_TokenProvider.java

This pull request fixes #7009: TokenProvider#createToken rememberMe should not be an Object (Boolean), but a primitive (boolean). Trivial change: Just one variable type is adjusted. :)

Fix for: #7009 TokenProvider#createToken rememberMe should not be an Object

---

generators/server/templates/src/main/java/package/config/_OAuth2SsoConfiguration.java

Seems to make sense since the `SecurityConfiguration` for OAuth with a monolith does the [same thing](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/config/_SecurityConfiguration.java#L190). I found this change necessary to get an Ionic app talking to a gateway in a microservices architecture.

Add CORS support to OAuth in microservices

---

generators/server/templates/src/main/java/package/config/audit/_AuditEventConverter.java

using Objects.toString (already imported) and directly entry#getValue
don't know if it's policy to do these kind of minor refactoring on the maintenance branch
* it should succeed on the relevant tests (as the result on {{null}} objects toString is also "null")
my arguments;
* it's less and more standard code
* using the intermediate var for the remaining 2 usages was didn't feel useful
* the naming of the var didn't make it more readable the just using entry#getValue directly

minor refactoring on AuditEventConverter#convertDataToStrings

---

generators/server/templates/src/main/java/package/repository/_UserRepository.java
generators/server/templates/src/main/java/package/security/_DomainUserDetailsService.java
generators/server/templates/src/main/java/package/service/_UserService.java
generators/server/templates/src/test/java/package/security/_DomainUserDetailsServiceIntTest.java

Greetings JHipsters!
Fixes for issue #6987
This PR closes the cache evict bugs, the "email can not signIn with email containing upperCase" and unnecessary email db lookup issue.
This PR does not store email toLowerCase always, as i suggested premature as a fix.
Reason:
Although it is quite common to identify the locale-part of email-addresses containing upper-case letters and the equivalent lowerCase as the same email-address locale-part, RFC5321 and RFC5322 are allowing email providers to distinguish strict between lowerCase and upperCase within locale-parts.
Due to this, converting/storing the email always toLowerCase could prevent users from receiving mails/the activation mail,  in case they have an email containing upperCase chars and their email-provider handles this strict.
Although …

Cache evict and email login

---

generators/generator-base.js
generators/modules/index.js

The needle was added to `_build.gradle` in this commit https://github.com/jhipster/generator-jhipster/commit/a1a89b3f3ba9cd201d7b82da5835b478140721ba but was apparently never implemented.
I would love to use it for a jhipster module im creating.
Maybe the name is not great `addGradlePluginToPluginsBlock` since `addGradlePlugin` is already taken by the needle adding to the buildscripts block

support unused needle

---

generators/server/templates/src/main/java/package/service/_SocialService.java

Google users (or facebook users) with space in lastname or firstname can't register into JHipster app because of : ConstraintViolationException in User Entity. 
This is a fix to replace space with '_'

fix: remove blank space in social auth users names

---

generators/server/templates/src/main/java/package/web/rest/_AuthResource.java

With 200 OK response without body, Firefox gives warning on console as it expects
root xml element (treating response as text/xml in absence of content-type header)

For logout resource, return 204 OK response instead of 200 OK

---

generators/client/templates/angular/src/main/webapp/app/core/auth/_auth-session.service.ts

Remove the unecessary call to get a new CSRF token when CSRF is disabled.
Fix #7090

Remove the unecessary api call

---

generators/heroku/index.js
test/heroku.spec.js
test/templates/default-elasticsearch/.yo-rc.json

This will automatically create a *free* Elasticsearch add-on attached to the Heroku app when the generator detects `"searchEngine": "elasticsearch"` in the config. For this to really work, I think the elasticsearch generator needs to add these to the `application.yml`
```
spring:
data:
elasticsearch:
cluster-name:
cluster-nodes:
properties:
path:
logs: target/elasticsearch/log
data: target/elasticsearch/data
```

Added support for Elasticsearch to the Heroku generator

---

README.md

New badges are available on SonarCloud, and the old ones will be removed soon.
You can read more at https://about.sonarcloud.io/news/2018/02/05/new-project-badges.html
And BTW: congrats guys for the great figures you get for JHipster!

Use the new SonarCloud badges

---

generators/client/templates/angular/src/main/webapp/app/admin/health/_health-modal.component.ts

Fix display for healthcheck details when the values are objects and not plain text
If the health check details returned from the server are objects and not just a plain strings, fallback to displaying a JSON.stringify'ed version instead of [object Object]
Fix #7152
- [] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

Fix display for healthcheck details when the values are objects and not plain text

---

generators/client/templates/angular/src/main/webapp/app/core/auth/_user-route-access-service.ts

When an authenticated user tries to navigate to a route and is denied access because of insufficient authorities, the UserRouteAccessService now logs an error in console:
> User has not any of required authorities: [ROLE_ADMIN]
This is enabled only in Angular dev mode.

Log an error in browser console when access to route is denied

---

generators/docker-prompts.js
generators/generator-constants.js
generators/kubernetes/files.js
generators/kubernetes/index.js
generators/kubernetes/prompts.js
generators/kubernetes/templates/_README-KUBERNETES.md
generators/kubernetes/templates/_apply.sh
generators/kubernetes/templates/_deployment.yml
generators/kubernetes/templates/monitoring/_jhipster-grafana-dashboard.yml
generators/kubernetes/templates/monitoring/_jhipster-grafana.yml
generators/kubernetes/templates/monitoring/_jhipster-prometheus-cr.yml
generators/kubernetes/templates/monitoring/_jhipster-prometheus-crd.yml
generators/kubernetes/templates/monitoring/_jhipster-prometheus-sm.yml
test/kubernetes.spec.js

- Grafana added with pre-configured dashboard view
- Prometheus operator is included (as the app specific bits like service monitor and rbac objects are dependent on the operator crd)
- Aligned some of the prompts (jhipster console and prometheus) to be in sync with docker-compose
- Added a shell script pgm to deploy all of the k8s objects at one go
- Added init-container check to deployment object to wait for dependent services initialisation
- Output file structure is been refactored
- README and test spec updated accordingly

add grafana with pre-configured dashboard view and few refactoring updates

---

generators/client/templates/angular/_package.json
generators/client/templates/react/_package.json

Prettier wants quotes instead of apostrophes in Windows.
Without this fix there is Prettier error in Windows:
Angular: [error] No matching files. Patterns tried: '**/*.ts' !**/node_modules/** !./node_modules/**
React: [error] No matching files. Patterns tried: '**/*.{ts,tsx}' !**/node_modules/** !./node_modules/**

fix Prettier error in Windows

---

generators/generator-base.js
generators/server/templates/build.gradle.ejs

We're using jhipster for a bunch of microservices, project specific configs are then added by applying a jhipster-module on top of the default generator. Adding specific maven repositories is still done by search and replace. I guess using the needle functionality is way nicer and maybe helpful for others too.
Please feel free to ask for improvements of any kind

Add needle to add maven repositories

---

generators/client/templates/react/src/main/webapp/app/shared/layout/header/header.tsx.ejs

- replace UncontrolledNavDropdown with UncontrolledDropdown
- add nav prop
Fixes error message in console:
```
The "UncontrolledNavDropdown" component has been deprecated.
Please use component "UncontrolledDropdown" with nav prop.
```
My first React PR 😄 

update deprecated reactstrap component

---

generators/server/templates/src/main/java/package/Application.java.ejs

It is to fix this:
```diff
import java.util.Arrays;
import java.util.Collection;
-@SpringBootApplication@EnableConfigurationProperties({LiquibaseProperties.class, ApplicationProperties.class})
+@SpringBootApplication
+@EnableConfigurationProperties({LiquibaseProperties.class, ApplicationProperties.class})
public class JhipsterApp {
```

Fix indentation [ci skip]

---

generators/client/files-react.js
generators/client/templates/react/package.json.ejs
generators/client/templates/react/src/main/webapp/app/config/store.ts.ejs
generators/client/templates/react/src/main/webapp/app/config/websocket-middleware.ts.ejs
generators/client/templates/react/src/main/webapp/app/modules/administration/administration.reducer.ts.ejs
generators/client/templates/react/src/main/webapp/app/modules/administration/index.tsx.ejs
generators/client/templates/react/src/main/webapp/app/modules/administration/tracker/tracker.tsx.ejs
generators/client/templates/react/src/main/webapp/app/shared/layout/header/header.tsx.ejs
generators/client/templates/react/src/test/javascript/spec/app/modules/administration/administration.reducer.spec.ts.ejs

- add Tracker frontend
- add `tracker` in Administration reducer for storing user activities
- add Administration reducer test
- add websocket middleware
- add sockjs and webstomp to package.json
The standard place for websockets in a React+Redux project seems to be in a middleware, a developer normally wants access to the redux store when receiving messages.  The tracker page is now working and uses the new `tracker` key in the Administration reducers for keeping track of user activities.
I'm still new to React on web so there are probably things I'm missing (ex: I couldn't figure out how to subscribe to the route changes so I used `window.onhashchange` to send pages to the tracker).

implement websockets tracker for react

---

generators/entity-client/templates/react/src/main/webapp/app/entities/entity-dialog.tsx.ejs

I added a case where the field is a number (Integer, Long, Float, Double) to make sure the generated dialog uses the type number for the corresponding AvInput.
It could be a good idea to display an Alert if the server returns a 400 at entity creation. 

React : Entity dialog generation, number case

---

generators/server/index.js

`this.cacheManagerIsAvailable` is always false on the first generation because it was declared before the prompts.  This PR moves the declaration to after prompts are answered.
Fix #7261

fix java compile issue

---

generators/client/templates/angular/package.json.ejs
generators/client/templates/angular/src/main/webapp/app/shared/shared-libs.module.ts.ejs
generators/client/templates/angular/src/main/webapp/app/shared/shared.module.ts.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-dialog.component.ts.ejs
generators/entity-client/templates/angular/src/test/javascript/spec/app/entities/entity-management-dialog.component.spec.ts.ejs
generators/entity-client/templates/angular/src/test/javascript/spec/app/entities/entity-management.service.spec.ts.ejs

Angular2-moment makes the application bundle contains `moment` twice, which is quite huge... I think we should only use moment to do date manipulation.

Angular: Remove angular2-moment

---

generators/client/templates/angular/package.json.ejs
generators/client/templates/angular/webpack/webpack.dev.js.ejs
generators/client/templates/angular/webpack/webpack.test.js.ejs

Had some issues after updating a file with "yarn start" running, webpack crashed, I needed to bump some versions to make it work.

Fix webpack 4 issues with "start" script

---

generators/heroku/index.js

This fixes a problem where the Heroku sub-generator was inserting newlines into the middle of the build output
Output used to look like this:
```
------------------
-----------------------
[I
NFO] Total time: 9.075
s
[INFO]
Finished at: 2018-03-13T19:05
:32-05:00
[INFO] -
-----------------
-----------------
----------------
---------------
------
```
Now it looks like this:
```
[INFO] BUILD SUCCESS
[INFO] Total time: 9.251 s
[INFO] Finished at: 2018-03-13T19:13:23-05:00
```

Fix build output buffering issue in Heroku sub-generator

---

generators/client/templates/angular/src/main/webapp/content/scss/vendor.scss.ejs

Tools like Intellij Karma plugin fails if the reference is 'hard coded', using relative reference (~) fixes the issue.
- [ x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ x] Tests are added where necessary
- [ x] Documentation is added/updated where necessary

Use relative reference to node_modules

---

Dockerfile
generators/client/templates/angular/package.json.ejs
generators/client/templates/angular/src/test/javascript/karma.conf.js.ejs
generators/client/templates/angular/src/test/javascript/protractor.conf.js.ejs
generators/client/templates/react/package.json.ejs
generators/client/templates/react/src/test/javascript/karma.conf.js.ejs

With the migration to puppeteer in this [commit](https://github.com/jhipster/generator-jhipster/commit/ad7b3f9185ed9c86d522ff457a732cea1c9820ee), we introduced some bugs, I tried to fix in this PR.
- fix the Docker image [jhipster/jhipster](https://hub.docker.com/r/jhipster/jhipster/) using the @PierreBesson's code in this PR https://github.com/jhipster/generator-jhipster/pull/6623
```
18 03 2018 06:34:27.992:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
18 03 2018 06:34:27.994:INFO [launcher]: Launching browser ChromiumHeadless with unlimited concurrency
18 03 2018 06:34:28.006:INFO [launcher]: Starting browser ChromiumHeadless
18 03 2018 06:34:28.629:ERROR [launcher]: Cannot start ChromiumHeadless
/home/jhipster/app/node_modules/puppeteer/.local-chromium/linux-536395/ …
```

Fix issues with puppeteer

---

generators/generator-base.js
generators/server/templates/pom.xml.ejs

Gradle build uses jcenter which is a superset of maven central.
I think we should do the same for the pom.xml at least for consistency.

Add jcenter to pom.xml and a needle to add a repository to the pom

---

generators/import-jdl/index.js
package-lock.json
package.json
test/generator-base.spec.js
test/import-jdl.spec.js
test/templates/import-jdl/apps-and-entities.jdl
yarn.lock

Notice the subtle bump from v1.4.6 to v2.0.1 ;)

Added application generation support for the JDL based on JCore v2

---

generators/app/index.js
generators/entity/index.js
generators/entity/prompts.js
generators/generator-base.js

Add an option [--skip-check-length-of-identifier] to skip check the length of identifier when generate entity

Add an option [--skip-check-length-of-identifier] to skip check the length of identifier when generate entity

---

generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs

I believe the lowercase in the entityName is what caused the issues in the i18n with microservices.
Fix #7124

fix issues with i18n for microservices

---

generators/client/files-react.js
generators/entity-client/templates/react/src/main/webapp/app/entities/entity-dialog.tsx.ejs

Fix a visual bug that prevents blob image preview to be displayed when creating a new entity instance.

Fix blob preview and Fix session auth generation

---

generators/server/templates/build.gradle.ejs

Classpath is already too long to be handled on windows, so classpath should be **replaced** with classpath jar (btw, renamed task and jar to better reflect what it does). In current version of jhipster, classpath jar is **added** to already-too-long-classpath, so workaround doesn't work. Btw, this workaround is not needed on Windows 10, if "Long Paths" feature is enabled (see https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/), basically LongPathsEnabled should be "1" under HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem registry path.

Fix classpath jar workaround for Windows

---

generators/docker-prompts.js
test/docker-compose.spec.js

Force adding a trailing slash in docker prompt.
This fixes the issue when the user input a path that doesn't end with a trailing slash.
Currently this broke the subgen and was very confusing for users.

Fix issue in docker-prompt when directory path doesn't have a trailing slash

---

generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs

The duplication was occurring when importing a JDL like this:
```
entity Employee {
firstName String
}
relationship ManyToOne {
Employee{manager} to Employee
}
```

React: Fix a possible import duplication

---

generators/entity-server/templates/src/main/java/package/common/get_all_template.ejs
travis/samples/.jhipster/TestManyRelWithPaginationAndDTO.json
travis/samples/.jhipster/TestMapstruct.json
travis/scripts/01-generate-entities.sh

Fix #7430 
The `page` variable is already mapped to DTO in the code above the `return` 

remove extra call to DTO mapper

---

generators/client/templates/angular/src/main/webapp/app/admin/logs/logs.component.html.ejs
generators/client/templates/react/src/main/webapp/app/modules/administration/logs/logs.tsx.ejs

Allow the user to set the log level to OFF.
I change the color too:
- trace -> primary (instead of error)
- debug -> success (instead of warning)
- info -> info
- warning -> warning (instead of success)
- error -> error (instead of primary)

Add log level OFF + change color

---

generators/client/templates/angular/webpack/webpack.test.js.ejs

Related to https://github.com/jhipster/generator-jhipster/pull/7341
Currently, when launching `yarn test`:
```
WARNING in ./node_modules/@angular/core/esm5/core.js
6558:15-36 Critical dependency: the request of a dependency is an expression
@ ./node_modules/@angular/core/esm5/core.js
@ ./node_modules/@angular/common/esm5/http/testing.js
@ ./src/test/javascript/spec/app/admin/audits/audits.service.spec.ts
@ ./src/test/javascript/spec sync \.spec
@ ./src/test/javascript/spec/entry.ts
WARNING in ./node_modules/@angular/core/esm5/core.js
6578:15-102 Critical dependency: the request of a dependency is an expression
@ ./node_modules/@angular/core/esm5/core.js
@ ./node_modules/@angular/common/esm5/http/testing.js
@ ./src/test/javascript/spec/app/admin/audits/audits.service.spec.ts
@ …
```

Fix webpack warning during tests

---

generators/aws/index.js
generators/aws/lib/aws.js
generators/aws/lib/eb.js
generators/aws/lib/iam.js
generators/aws/lib/rds.js

In AWS environments where an elastic-beanstalk application hasn't been deployed via the environment management console initially, then two dependent roles are missing from IAM: [aws-elasticbeanstalk-ec2-role](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/iam-instanceprofile.html#iam-instanceprofile-verify), and [aws-elasticbeanstalk-service-role](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/iam-servicerole.html). This fix will generate the appropriate default roles, based on the documentation, allowing the environment to start once deployed.
I'm hoping it fixes #7086

AWS Elastic-beanstalk role creation for new environments

---

generators/entity-server/files.js
generators/entity-server/templates/src/main/java/package/common/inject_template.ejs
generators/entity-server/templates/src/main/java/package/repository/reactive/EntityReactiveRepository.java.ejs
generators/entity-server/templates/src/main/java/package/service/EntityService.java.ejs
generators/entity-server/templates/src/main/java/package/service/impl/EntityServiceImpl.java.ejs
generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs
generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIntTest.java.ejs
generators/entity/index.js
generators/server/templates/build.gradle.ejs
generators/server/templates/pom.xml.ejs
generators/server/templates/src/main/java/package/config/DatabaseConfiguration.java.ejs
generators/server/templates/src/main/java/package/config/cassandra/CassandraConfiguration.java.ejs
travis/samples/.jhipster/CassBankAccount.json
travis/samples/.jhipster/CassTestMapstructEntity.json
travis/samples/.jhipster/DocumentBankAccount.json
travis/samples/.jhipster/FieldTestMapstructEntity.json
travis/samples/ngx-couchbase/.yo-rc.json
travis/samples/ngx-mongodb-kafka-cucumber/.yo-rc.json
travis/samples/ngx-session-cassandra-fr/.yo-rc.json

This PR:
- creates a reactive repository if the reactive option is on for Mongo and Couchbase
- creates a streaming reactive WebFlux endpoint with mediatype application/stream+json
- adds a test using WebTestClient for this endpoint
This endpoint has the advantage to be fully reactive end-to-end. It can be used to fetch large collections out of the database without OOM (and without the drawbacks of pagination fetching such as add/delete of entities during the extract and repeated queries to the database).
Cassandra could also be done but this would require to completely move to spring-data-cassandra.
For JPA, there could be some interesting things to do with Scrollable ResultSets but I need to investigate more.

Add a streaming/reactive endpoint for Mongo and Couchbase

---

generators/aws/lib/eb.js
generators/aws/lib/iam.js

As part of #7443 I failed to correctly define the instance profile as part of the role creation process. When the instance profile is not available, the application will not deploy correctly in Elastic Beanstalk. 
@jdubois would you mind having a look at this PR before it's merged. You'll want to remove the following roles via the web-interface to verify the creation process:
- aws-elasticbeanstalk-ec2-role
- aws-elasticbeanstalk-service-role

AWS Elastic-beanstalk instance profile creation missing from new iam class

---

generators/server/templates/src/main/docker/.dockerignore.ejs

Fix https://github.com/jhipster/generator-jhipster/issues/7455
I keep the exclusion for jar, war, cassandra and couchbase for securing the Docker build.
Hope this new version will work on Mac / Windows.

dockerignore: remove full ignore **/*, and use blacklist instead

---

generators/server/files.js
generators/server/templates/src/test/resources/config/application.yml.ejs

Fixes #7487 since `AccountResource`, and its test, are never used by the UI when the app is a microservice. 
Also sets `eureka.client.enabled` to false for tests to avoid stacktraces like the following when testing.
```
2018-04-17 08:51:29.420 ERROR 84830 --- [      Thread-10] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_BLOG/blog:555c1d1d2470cd0cb69b74fc7c9a058d - de-registration failedCannot execute request on any known server
com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112)
at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.cancel(EurekaHttpClientDecorator.java:71)
at …
```

Remove AccountResource and test for microservice

---

generators/aws-containers/index.js
generators/aws-containers/prompts.js

Modified the AWS Containers generator to use the new JHipsterDatabaseTypes changes from JHipster-Core [#178](https://github.com/jhipster/jhipster-core/issues/178).

AWS Containers Generator Using Old DatabaseType

---

generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.ts.ejs

One parameter was useless on Angular update component
- [x ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green

Remove unused parameter

---

generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management-update.tsx.ejs

Using `model={isNew ? {} : user}` was sometimes displaying outdated values in form when updating an User. For instance, if you were editing `user` and then directly switching to `admin`, you had 50% chances that values in the form were still about `user` and not `admin` as you would expect.

React : fix user management update page

---

generators/client/templates/angular/src/main/webapp/app/layouts/profiles/profile.service.ts.ejs
generators/server/files.js
generators/server/templates/gradle/profile_prod.gradle.ejs
generators/server/templates/src/main/java/package/config/LoggingConfiguration.java.ejs
generators/server/templates/src/main/java/package/config/MicroserviceSecurityConfiguration.java.ejs
generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs
generators/server/templates/src/main/resources/config/application.yml.ejs
generators/server/templates/src/main/resources/config/bootstrap.yml.ejs

Linked to https://github.com/jhipster/jhipster/pull/53
- Migrate the ProfileInfoResource to standard spring boot configuration.
- Migrate the development ribbon mechanism to the front-end
- Display build data in  `/management/info` endpoint as such:
```
{
"display-ribbon-on-profiles" : "dev",
"git" : {
"commit" : {
"id" : {
"abbrev" : "92e2d29",
"describe" : "92e2d29-dirty"
}
},
"branch" : "master"
},
"build" : {
"version" : "0.0.1-SNAPSHOT",
"artifact" : "sb-2-t-2",
"name" : "Sb 2 T 2",
"group" : "com.mycompany.myapp",
"time" : "2018-01-26T16:59:48Z"
},
"active-profiles" : [ "swagger", "dev" ]
}
```

Remove ProfileInfoResource and improve info endpoint

---

generators/generator-base.js
test/generator-base.spec.js

Fix #7537
Related to #7489
We used the same logic as when we shorten the table name, but only reduced the length by two when we add `_id` (length 3)

fix constraint truncation when too long

---

generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs
generators/generator-base-private.js
test/generator-base-private.spec.js

If description is defined for Entity and/or Field(s), it will be added to Table and/or Column(s) description in liquibase remarks tag in entity changelog.

Add table/column description into liquibase remarks tag

---

generators/client/templates/angular/webpack/webpack.dev.js.ejs
generators/client/templates/react/webpack/webpack.dev.js.ejs

fixes the issue of swagger using the wrong port (9060 instead of 9000) from the host header
this affects both OAuth and UAA auth types as they use cookies auth
I tested to make sure 301 redirects for keycloak still work as expected when using the webpack proxy
Fix #7185

override host header for webpack dev proxy

---

generators/kubernetes/templates/db/mysql.yml.ejs

Fix the syntax of the mysql kubernetes yaml and add some missing args that appears in the src/main/docker/mysql.yml like --character_set_server=utf8 and --explicit_defaults_for_timestamp

Fix the syntax of the mysql kubernetes yaml

---

generators/client/templates/react/package.json.ejs
generators/client/templates/react/src/main/webapp/app/modules/administration/audits/audits.tsx.ejs
generators/client/templates/react/src/main/webapp/app/modules/administration/gateway/gateway.tsx.ejs
generators/client/templates/react/src/main/webapp/app/modules/administration/health/health.tsx.ejs
generators/client/templates/react/src/main/webapp/app/modules/administration/metrics/metrics.tsx.ejs
generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management-delete-dialog.tsx.ejs
generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management-detail.tsx.ejs
generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management-update.tsx.ejs
generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management.tsx.ejs
generators/client/templates/react/src/main/webapp/app/shared/layout/header/header.tsx.ejs
generators/client/templates/react/tslint.json.ejs
generators/entity-client/templates/react/src/main/webapp/app/entities/entity-delete-dialog.tsx.ejs
generators/entity-client/templates/react/src/main/webapp/app/entities/entity-detail.tsx.ejs
generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs
generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs
generators/generator-base.js

Related to #7516.
@gomesp Here's the PR.
@deepu105 The lib [documentation](https://github.com/FortAwesome/react-fontawesome/blob/master/README.md#build-a-library-to-reference-icons-throughout-your-app-more-conveniently) specifies that we could do something like this:
```javascript
import ReactDOM from 'react-dom';
import fontawesome from '@fortawesome/fontawesome'
import FontAwesomeIcon from '@fortawesome/react-fontawesome'
import brands from '@fortawesome/fontawesome-free-brands'
import faCheckSquare from '@fortawesome/fontawesome-free-solid/faCheckSquare'
import faCoffee from '@fortawesome/fontawesome-free-solid/faCoffee'
fontawesome.library.add(brands, faCheckSquare, faCoffee)
```
to add every icons we need once and then use a simmple string as key for the icon prop, `<FontAwesomeIcon …

React : Upgrade font-awesome lib

---

generators/generator-base.js

@jdubois It should fix what we discussed earlier.
This was preventing element duplication detection. It shouldn't write links to a regenerated entity in the header and the entities index.

Fix React needles

---

generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs

For the db type `ZonedDateTime` and `Instant` , we use convert it into `timestamp` for the db type. but there is limitation in mysql that the 'timestamp' only support a range of '1970-01-01 00:00:01' UTC to '2038-01-19 03:14:07'.

change dbtype from timestamp to datetime for mysql

---

generators/server/templates/src/main/resources/config/liquibase/changelog/initial_schema.xml.ejs

Having unique constraints on login and email,
`<constraints unique="true" nullable="false" uniqueConstraintName="ux_user_login"/>`
`<constraints unique="true" nullable="true" uniqueConstraintName="ux_user_email"/>`
It acts as an index:
`explain select login from jhi_user where login = 'admin';`
```
QUERY PLAN
-------------------------------------------------------------------------------------
Index Only Scan using ux_user_login on jhi_user  (cost=0.14..8.16 rows=1 width=118)
Index Cond: (login = 'admin'::text)
(2 rows)
```
So we don't need those index creation:
```
<createIndex indexName="idx_user_login"
tableName="<%= jhiTablePrefix %>_user"
unique="true">
<column name="login" type="varchar(50)"/>
</createIndex>
<createIndex indexName="idx_user_email"
tableName="<%= jhiTablePrefix …
```

remove duplicated index on email and login

---

generators/client/templates/angular/package.json.ejs
generators/client/templates/angular/webpack/webpack.prod.js.ejs
generators/client/templates/react/package.json.ejs
generators/client/templates/react/webpack/webpack.prod.js.ejs
generators/generator-base-private.js
generators/languages/index.js

Moment is quite a big library as it imports ALL the locales by default. We can use [this plugin](https://github.com/iamakulov/moment-locales-webpack-plugin) in order to keep only the locales the user wants to use and remove the rests, which result in a reduced bundle size 🎉 

Remove useless Moment locales from production build

---

generators/server/templates/src/main/java/package/config/DatabaseConfiguration.java.ejs

This will prevent having a Mongobee exception when the database name is in the property **spring.data.mongodb.uri** (ex: mongodb://localhost:27017/jhipster) and the property **spring.data.mongodb.database** is null.
Looking at the source of [MongoProperties](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/mongo/MongoProperties.java#L169) shows that **getMongoClientDatabase()** will act as **getDatabase()** when the property **spring.data.mongodb.database** is not null.
I understand that this PR doesn't fix anything but it will save time for people that changed properties to use only **spring.data.mongodb.uri**.

Use getMongoClientDatabase() instead of getDatabase()

---

.travis.yml

Travis: use release of jhipster lib 2.0.3, instead of master branch

---

generators/client/templates/angular/src/main/webapp/swagger-ui/index.html.ejs

Fix a bug that was added by #7444 
`ng-webstorage` stores keys in lower case.

Fix Angular's swagger

---

generators/entity-client/templates/angular/src/test/javascript/e2e/entities/entity-page-object.ts.ejs

Page-Objects - add return types for setters and ElementFinders in order to encourage the use of protractor promise by the end user.
Not testes for now (made with github edit), please wait for travis build to complete in order to assess completness

page-objects - add return types

---

generators/server/files.js
test/app.spec.js
test/utils/expected-files.js

Cucumber tests are generated in the wrong directory, it's missing the `java` prefix, I think it started in https://github.com/jhipster/generator-jhipster/commit/8c2e42bc682533f68b41bbe14d15dd5547ccb7a9, it's fine in v4
#currently generated in
src/test/com/mycompany/myapp/cucumber/CucumberTest.java
src/test/java/com/mycompany/myapp/cucumber/CucumberTest.java

generate cucumber tests under java folder

---

Dockerfile

I added `[ci skip]`, as there are no tests for Docker here.
But the [hipster-labs/jhipster-travis-build branch](https://github.com/hipster-labs/jhipster-travis-build/tree/docker) has one
Tested on my computer and it works well

Docker: use ubuntu 18.04 LTS [ci skip]

---

generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/notification.interceptor.ts.ejs

Lower casing all the alert headers names seems to fix the issue  #7641 
It appears that all the headers names are now in lowercase in new browsers, except when using Firefox with port 8080 (dev/prod profile does not matter)

Fix alert not displaying issue in Firefox

---

generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIntTest.java.ejs
generators/entity/index.js
generators/generator-base-private.js
travis/samples/.jhipster/TestTwoRelationshipsSameEntity.json

Fix #6860
This creates only one instance of each related entity, preventing issues with multiple required relationships to an entity with a unique field.
Added tests which led me to fix a bug with relationships between entities with different client-root-folders

Allow multiple required relationships to entity with unique field

---

generators/entity/index.js

Fix #7124
Entity translations are already prefixed by the microservice app name, adding the same prefix to the entity translation key is unnecessary.  The microservice also doesn't know of the `clientRootFolder` so it doesn't send that as part of the entity translation key.

fix microservice entity translations

---

test/entity.spec.js

@jdubois the file name is case sensitive on Travis, so Foo != foo related to #7651

lowercase file name in test to match name exactly

---

generators/client/templates/react/src/main/webapp/app/modules/account/settings/settings.tsx.ejs
generators/client/templates/react/src/main/webapp/app/modules/home/home.tsx.ejs
generators/client/templates/react/src/main/webapp/app/modules/login/login.tsx.ejs
generators/client/templates/react/src/main/webapp/app/modules/login/logout.tsx.ejs

This change will make upgrading React in the future easier.
* remove componentWill[update|mount|receiveProps] methods and either replace them with componentDid... or use props directly. 
See: [Update on Async Rendering](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html)

React: remove (to-be) deprecated lifecycle functions

---

generators/client/templates/react/src/main/webapp/app/modules/administration/metrics/metrics.tsx.ejs

In Kubernetes the metrics page is not working, because of the `jvm.garbage.PS-MarkSweep.count` name difference It is actually `jvm.garbage.MarkSweep.count`

fix metrics page in kubernetes

---

generators/client/templates/angular/src/main/webapp/app/vendor.ts.ejs

These imports are no longer needed as we switched to pipeable operators.
Related to https://github.com/jhipster/generator-jhipster/pull/6899 and https://github.com/jhipster/generator-jhipster/pull/7582

remove old rxjs imports from before pipeable operators

---

generators/server/templates/src/main/java/package/domain/AbstractAuditingEntity.java.ejs
generators/server/templates/src/test/java/package/service/UserServiceIntTest.java.ejs

Set updatable = false for createdDate to ensure that createdDate is not updated on every change to the entity
Fix #7664

set updatable = false for createdDate

---

generators/client/templates/angular/package.json.ejs
generators/client/templates/react/package.json.ejs

This will ensure that Yarn is installed (with the correct version) on platforms like Heroku.
Normally, Heroku looks for a `yarn.lock` file, and installs and runs `yarn` accordingly. But in some cases (either with apps generated from https://start.jhipster.tech or `jhipster --skip-install`) no `yarn.lock` is present. But Heroku should still work.

Add Yarn to engines

---

generators/client/templates/angular/src/main/webapp/app/layouts/navbar/navbar.component.html.ejs

Fix #7716
Thanks to https://github.com/ng-bootstrap/ng-bootstrap/issues/2343#issuecomment-389265228

move ngIf out of ngbDropdownToggle element

---

generators/entity-client/templates/react/src/test/javascript/e2e/entities/entity.spec.ts.ejs

It's for fixing this error:
```
[18:01:02] E/launcher - Error: TSError: ⨯ Unable to compile TypeScript
src/test/javascript/e2e/entities/cass-bank-account-my-suffix/cass-bank-account-my-suffix.spec.ts (40,71): Argument of type '"64c99148-3908-465d-8c4a-e510e3ade974"' is not assignable to parameter of type 'RegExp'. (2345)
at getOutput (/home/travis/app/node_modules/ts-node/src/index.ts:307:15)
at /home/travis/app/node_modules/ts-node/src/index.ts:336:16
at Object.compile (/home/travis/app/node_modules/ts-node/src/index.ts:498:11)
at Module.m._compile (/home/travis/app/node_modules/ts-node/src/index.ts:392:43
```
_____

Fix match regexp for e2e with React+Cassandra

---

generators/client/templates/angular/webpack/webpack.prod.js.ejs
generators/client/templates/react/webpack/webpack.common.js.ejs
generators/client/templates/react/webpack/webpack.prod.js.ejs

For Angular, CSS files are stored at the root of the of the app.  For React, CSS files and images referenced in CSS are stored at the root of the app.  This means those files [don't receive the caching headers](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/config/WebConfigurer.java.ejs#L181-L182).  I updated the Webpack config to put the CSS and referenced image files in the `content` folder like what was done in AngularJS
React also has a static folder with images such as the navbar logo, it isn't hashed by webpack or cached.  Not sure what we wanted to do with that so the react config may need tweaking.

Caching Improvements

---

generators/server/templates/build.gradle.ejs
generators/server/templates/pom.xml.ejs
generators/server/templates/src/main/java/package/security/PersistentTokenRememberMeServices.java.ejs
generators/server/templates/src/main/java/package/security/oauth2/OAuth2AuthenticationService.java.ejs
generators/server/templates/src/main/java/package/security/oauth2/OAuth2CookieHelper.java.ejs

I'd like to get rid of the huge Guava dependency, which we only use for two "small" purposes that are easily replaced.
Specifically, this PR
- Replaces an Guava cache (which is needlessly complex anyway, we don't need the concurrency features here) with a simple linked map. 
- Uses apache's httpclient to do some public suffix / TLD magic instead of Guava.
This has a counterpart PR on the server lib, [here](https://github.com/jhipster/jhipster/pull/71).
I will cancel failing Travis due to this mutual dependence, see here for passing tests with both PRs applied:
https://travis-ci.org/erikkemperman/generator-jhipster/builds/385181814
https://travis-ci.org/erikkemperman/jhipster/builds/385181785

Less guava

---

generators/server/templates/README.md.ejs
generators/server/templates/build.gradle.ejs
generators/server/templates/gradle/swagger.gradle.ejs
generators/server/templates/pom.xml.ejs
generators/server/templates/src/main/resources/swagger/api.yml.ejs

[openapi-generator](https://openapi-generator.tech) is a community-driven fork of swagger-codegen. Using it has the following advantages:
* Supports both swagger v2.0 and OpenAPI v3.0 formats
* Will generate "delegate" interfaces that are called from the controller classes. So you don't need to add annotations such as `@RequestParam` in the implementation methods.
* Supports Webflux so it can be used with the future `reactive` option.

Use openapi-generator for API-first option

---

generators/entity-client/templates/react/src/main/webapp/app/entities/entity-delete-dialog.tsx.ejs
generators/entity-client/templates/react/src/main/webapp/app/entities/entity-detail.tsx.ejs
generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs

Fix jhipster/jhipster-core#220
By extending RouteComponentProps in update/delete/detail React pages, we run into conflicts if an entity has the name `history`, `location`, etc.  This PR adds a suffix to the entity props object on those pages.  Another possible fix is to add the words to the reserved list, `Location` is in the example on JDL Studio so I went with this solution instead.
```
export interface RouteComponentProps<P, C extends StaticContext = StaticContext> {
history: H.History;
location: H.Location;
match: match<P>;
staticContext: C | undefined;
}
```

fix entity conflicts with RouteComponentProps in React

---

generators/ci-cd/templates/.gitlab-ci.yml.ejs

Currently jhipster is using deprecated CI variable.
[https://docs.gitlab.com/ee/ci/variables/#9-0-renaming](https://docs.gitlab.com/ee/ci/variables/#9-0-renaming)
This PR will update to use recommended one.

update the gitlab ci deprecated variable

---

generators/server/templates/src/main/java/package/client/OAuth2InterceptedFeignConfiguration.java.ejs
generators/server/templates/src/main/java/package/client/OAuth2UserClientFeignConfiguration.java.ejs
generators/server/templates/src/main/java/package/client/OAuth2_UserFeignClientInterceptor.java.ejs

Fix #7756 
I left the `@Component` annotation on the `JWT_UserFeignClientInterceptor.java` because it is not declared as a bean like `OAuth2_UserFeignClientInterceptor.java`, not sure if that matters.  That class is copied for jwt microservices only

remove feign annotations causing duplicate interceptors

---

generators/client/templates/angular/src/main/webapp/app/account/password-reset/finish/password-reset-finish.route.ts.ejs
generators/client/templates/angular/src/main/webapp/app/account/password-reset/init/password-reset-init.route.ts.ejs

addresses an issue with uaa auth type where 401 redirects to home page
modeled the route config after the `register` route which doesn't request the account
Fix #7773

dont request account on password reset screens

---

generators/ci-cd/templates/.gitlab-ci.yml.ejs
generators/ci-cd/templates/jenkins/Jenkinsfile.ejs
generators/client/templates/angular/package.json.ejs
generators/client/templates/angular/src/test/javascript/jest.conf.js.ejs
generators/client/templates/react/package.json.ejs
generators/client/templates/react/src/test/javascript/jest.conf.js.ejs

I'm working on the CICD sub generator and there is a missing config for Jest, similar to what we had with Karma:
```js
junitReporter: {
outputFile: '../../../../<%= BUILD_DIR %>test-results/karma/TESTS-results.xml'
},
```
Related to https://github.com/jhipster/generator-jhipster/pull/7636
_____

Jest junit

---

generators/client/templates/angular/package.json.ejs
generators/client/templates/angular/src/test/javascript/jest.conf.js.ejs
generators/client/templates/react/package.json.ejs
generators/client/templates/react/src/test/javascript/jest.conf.js.ejs
generators/server/templates/pom.xml.ejs

It seems that sonar wasn't seeing the front unit tests, they probably changed their XML format. @jdubois pointed that to me, thanks !
I couldn't find a way to externalize the jestSonar config so I put it in the package.json file as the [doc](https://github.com/3dmind/jest-sonar-reporter) says...

Fix Sonar Reporting for Jest

---

generators/heroku/index.js

The term "toolbelt" is no longer used by Heroku.

Improve error message when Heroku CLI is not installed

---

generators/ci-cd/prompts.js
generators/ci-cd/templates/circle.yml.ejs
generators/ci-cd/templates/jenkins/Jenkinsfile.ejs
generators/ci-cd/templates/travis.yml.ejs

Fixes #7821 
I was hoping we could automatically set the env var, but that was too optimistic. We would have to require the `travis` CLI be installed, and such.
Includes a bump to the heroku-maven-plugin version.

Improvements to Heroku deploy in CI/CD generator

---

generators/server/templates/build.gradle.ejs

fix #7845 
maybe surrounding that exclusion when there spring-cloud is used?

removes micrometer exclusion from gradle

---

generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs

fix #7868 
While looking at the relationship field generation for React I saw a bunch of duplicated stuff and other useless things. There's definitely room for improvement in there. Someone (me if I got enough time) should try to take a look and clean it.

Fix required relationship for React

---

generators/client/templates/react/src/main/webapp/app/config/translation.ts.ejs
generators/client/templates/react/src/main/webapp/app/shared/layout/header/header-components.tsx.ejs
generators/client/templates/react/src/main/webapp/app/shared/layout/header/menus/account.tsx.ejs
generators/client/templates/react/src/main/webapp/app/shared/layout/header/menus/admin.tsx.ejs
generators/client/templates/react/src/main/webapp/app/shared/layout/header/menus/entities.tsx.ejs
generators/generator-base-private.js
generators/languages/index.js

fix #7786 
For some reason, in the languages sub-gen, `this.config.set('languages', _.union(this.currentLanguages, this.languagesToApply));` was not updating languages during the generation but after. It was preventing the subgen to properly add the new desired language.
On the other side, RTL support was a bit messed up for React. I fixed it because it was preventing the needle from being printed in the file when there was no RTL languages selected.

Fix jhlang and react rtl support

---

generators/client/templates/react/package.json.ejs

Without this change, for React application, it will use the global version of JHipster
_____

React: add missing generator-jhipster dependencies

---

generators/app/index.js
generators/client/index.js
generators/docker-compose/index.js
generators/gae/index.js
generators/kubernetes/index.js
generators/openshift/index.js
generators/rancher-compose/index.js
generators/server/index.js

Weird issue - when you change your answers on the second run of a generator, the config isn't saved. 
Saving the config items at once instead of separately updates the `.yo-rc.json` with the new prompt answers, I went ahead and changed it everywhere to be consistent.  Not sure why this works and setting individually doesn't work
Steps to reproduce:
- Generate a monolith (use `--skip-install` for faster generation)
- Make docker-compose config directory
- Run `jhipster docker-compose` to generate Docker Compose config, choosing any options
- Re-run `jhipster docker-compose` and change any of the prompt answers
- Check the `.yo-rc.json` and see the new choices aren't saved

set config at once to ensure updates are saved

---

generators/client/files-react.js
generators/client/templates/react/src/main/webapp/app/config/translation.ts.ejs
generators/client/templates/react/src/main/webapp/app/index.tsx.ejs
generators/client/templates/react/src/main/webapp/app/shared/layout/header/menus/locale.tsx.ejs
generators/client/templates/react/src/main/webapp/app/shared/reducers/locale.ts.ejs
generators/client/templates/react/src/test/javascript/spec/app/shared/reducers/locale.spec.ts.ejs

- By default load default/current locale i18n bundle.
- On locale change, check if translations for changed locale are cached. If yes, use those, otherwise, fetch from server.
- Unit tests for locale reducer

Lazy load locale specific i18n bundles

---

generators/docker-compose/templates/keycloak.yml.ejs
generators/server/templates/src/main/docker/keycloak.yml.ejs

Keycloak's vendor database detection is broken as of v4 (from https://github.com/jboss-dockerfiles/keycloak/pull/119), [this section](https://github.com/jboss-dockerfiles/keycloak/pull/119/files#diff-d0463d5d7460c28597180b6a29b001b8R20) always defaults to postgresql instead of h2
This is a workaround to set h2 by default so the Keycloak docker-compose file we provide doesn't crash on startup.
Mentioned in #7865

default to h2 for keycloak container [ci skip]

---

generators/server/prompts.js

This prevents generation of projects that don't compile
Fix #7669
Fix #7889 

only allow no-db for non-oauth ms and uaa gway

---

generators/spring-controller/index.js
generators/spring-controller/templates/src/main/java/package/web/rest/Resource.java.ejs
generators/spring-controller/templates/src/test/java/package/web/rest/ResourceIntTest.java.ejs
generators/spring-service/index.js
generators/spring-service/templates/src/main/java/package/service/Service.java.ejs
generators/spring-service/templates/src/main/java/package/service/impl/ServiceImpl.java.ejs

This PR ensures that when you use the service/controller subgenerators, it doesn't end in a double suffix.  For example, running `jhipster service FooService` generated `FooServiceService` instead of `FooService`
This would also make it easier to configure the suffixes with a flag in case a user wants to use "Controller" instead of "Resource" (in the future)

avoid double suffixes in service/controller subgenerators

---

generators/kubernetes/files.js

Any JWT apps not using service-discovery need this file for Kubernetes to deploy correctly ([used here](https://github.com/jhipster/generator-jhipster/blob/master/generators/kubernetes/templates/deployment.yml.ejs#L104-L110))

create jwt-secret.yml for apps not using ingress or service discovery [k8s]

---

generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/errorhandler.interceptor.ts.ejs
generators/client/templates/react/src/main/webapp/app/config/axios-interceptor.ts.ejs
generators/client/templates/react/src/main/webapp/app/config/constants.ts.ejs
generators/client/templates/react/src/main/webapp/app/config/notification-middleware.ts.ejs
generators/client/templates/react/src/main/webapp/app/modules/account/activate/activate.reducer.ts.ejs
generators/client/templates/react/src/main/webapp/app/modules/account/password-reset/password-reset.reducer.ts.ejs
generators/client/templates/react/src/main/webapp/app/modules/account/password/password.reducer.ts.ejs
generators/client/templates/react/src/main/webapp/app/modules/account/register/register.reducer.ts.ejs
generators/client/templates/react/src/main/webapp/app/modules/account/settings/settings.reducer.ts.ejs
generators/client/templates/react/src/main/webapp/app/modules/administration/administration.reducer.ts.ejs
generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management.reducer.ts.ejs
generators/client/templates/react/src/main/webapp/app/shared/reducers/application-profile.ts.ejs
generators/client/templates/react/src/main/webapp/app/shared/reducers/authentication.ts.ejs
generators/client/templates/react/src/main/webapp/app/shared/reducers/locale.ts.ejs
generators/client/templates/react/src/main/webapp/app/shared/reducers/user-management.ts.ejs
generators/client/templates/react/src/main/webapp/index.html.ejs
generators/entity-client/templates/react/src/main/webapp/app/entities/entity.reducer.ts.ejs

This PR does the following:
- Fix React Gateway UAA paths (currently can't register or use user-management)
- Implements `SERVER_API_URL` for all requests in the React client (through Axios Interceptor)
- Fixes React app when running on a context-path other than `/`
- Fixes error notifications on 401 when running on a context-path other than `/`
- Removes unused/empty register.ts file

React UAA paths and SERVER_API_URL

---

generators/client/templates/angular/src/test/javascript/spec/test.module.ts.ejs

fix :
when set a custom jhiPrefix and enabled spring-websocket, there get a error on run jhipster command:
ERROR in /xxxx/xxxx/src/test/javascript/spec/test.module.ts
(8,56): Module '"/xxxx/xxxx/src/main/webapp/app/core/index"' has no exported member 'JhiTrackerService'.
ERROR in /xxxx/xxxx/src/test/javascript/spec/test.module.ts
(22,22): Cannot find name 'DfsTrackerService'.

Fix 'has no exported member 'JhiTrackerService'' Error

---

generators/client/templates/react/src/main/webapp/app/config/axios-interceptor.ts.ejs

Related to #7890
OAuth2, session, and UAA auth types use cookies

only add bearer header interceptor for JWT apps

---

generators/client/templates/react/src/main/webapp/app/shared/layout/header/header-components.tsx.ejs
generators/client/templates/react/src/main/webapp/app/shared/layout/header/menus/entities.tsx.ejs
generators/generator-base.js

Fix #7946
Also fixes the Home text on React apps without translation (only the Home icon was showing)

fix missing translation for react navbar entity and home

---

generators/client/templates/angular/webpack/webpack.common.js.ejs

Fixes #7798
`HTMLWebpackPlugin` doesn't seem to like the generated chunks from webpack in prod profile... Couldn't find why he was freezing but this manual order fixes the issue.

Manually order chunks

---

generators/client/templates/angular/package.json.ejs
generators/client/templates/angular/src/test/javascript/jest.conf.js.ejs
generators/client/templates/react/package.json.ejs
generators/client/templates/react/src/test/javascript/jest.conf.js.ejs
generators/server/templates/pom.xml.ejs

Fix #7928
Adding jest-junit back, and adjust filename reports with Jenkins and Sonar.
Jenkins and Sonar needs different files.

Fix #7928 : Adding jest-junit back, and adjust filename reports

---

generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs

`getEntities()` was using the wrong page number

Fix React pagination with links

---

generators/client/templates/react/src/main/webapp/app/modules/account/settings/settings.tsx.ejs
generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management-detail.tsx.ejs
generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management-update.tsx.ejs
generators/client/templates/react/src/main/webapp/app/shared/layout/header/menus/locale.tsx.ejs

- Language key to name mapping on user-management and settings page
- Removed unused imports

Fix (react):  Language key to name mapping on user-mgmt and settings page

---

generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs

When it deals with an entity name with MultipleCamelCaseWord in relationship It was populating links like this:
`<Link to={`otherEntityName/${entityInstance.otherEntityName.id}`}>{entityInstance.otherEntityName.id}</Link>`
while it should have had it like this:
`<Link to={`other-entity-name/${entityInstance.otherEntityName.id}`}>{entityInstance.otherEntityName.id}</Link>`

fixed broken relationship link in listing page

---

generators/spring-controller/index.js
generators/spring-controller/prompts.js
generators/spring-service/index.js
test/service.spec.js
test/spring-controller.spec.js

Related to https://github.com/jhipster/generator-jhipster-blueprint/issues/5#issuecomment-405186956
Now, you can use:
- `jhipster spring-controller hello --default`
- `jhipster spring-service hello --default`
_____

Add --default flag for spring-service and spring-controller

---

generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIntTest.java.ejs

Update the comment in the `updateNonExistingEntity` case  for `EntityResourceTest`
- in the Jhipter 4.x:  when we updateNonExistingEntity, it will create a new one.
- in the Jhipster 5.x: when we updateNonExistingEntity, it will throw a error.

correct the comment for entityRecourceTest

---

generators/client/templates/react/package.json.ejs

- downgrade `moment-locales-webpack-plugin` from `1.0.7` to `1.0.5`
- be consistent with Angular
- fix https://github.com/jhipster/generator-jhipster/issues/8012
Probably a temporary fix. We need to investigate why the version 1.0.7 failed.
_____

Fix build in prod for React (with some languages)

---

generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs

This reverts commit d41ebd2cb0f5aca8ceaf5aed98c04baa35d83126.
When build the application in prod profile, and start the application with `--spring.profiles.active=prod,swagger`, the swagger page can't be displayed.
_____

Fix access to Swagger page in prod profile

---

.travis.yml
generators/server/templates/src/main/resources/config/application-prod.yml.ejs

When starting Couchbase application in prod profile, it should work out of the box, like other configuration. So I changed the default password to be the same as the container.
______

Fix couchbase in prod profile

---

generators/client/templates/angular/src/test/javascript/jest.conf.js.ejs
generators/client/templates/react/src/test/javascript/jest.conf.js.ejs

@deepu105 : I found some time after lunch time to fix this because all our builds failed.
Helped by https://stackoverflow.com/questions/51554366/npm-test-fail-with-jest
_____

Fix tests with jest

---

generators/server/templates/gradle/profile_dev.gradle.ejs
generators/server/templates/pom.xml.ejs

React projects currently rebuild the frontend on every call to maven/gradle

fix react webpack profile to look for correct file

---

generators/client/templates/angular/src/main/webapp/app/admin/audits/audits.component.html.ejs
generators/client/templates/angular/src/main/webapp/app/admin/configuration/configuration.component.html.ejs
generators/client/templates/angular/src/main/webapp/app/admin/gateway/gateway.component.html.ejs
generators/client/templates/angular/src/main/webapp/app/admin/health/health.component.html.ejs
generators/client/templates/angular/src/main/webapp/app/admin/logs/logs.component.html.ejs
generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics.component.html.ejs
generators/client/templates/angular/src/main/webapp/app/admin/tracker/tracker.component.html.ejs
generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management.component.html.ejs
generators/client/templates/angular/src/main/webapp/app/home/home.component.html.ejs
generators/client/templates/angular/src/main/webapp/app/shared/login/login.component.html.ejs
generators/client/templates/angular/src/test/javascript/e2e/account/account.spec.ts.ejs
generators/client/templates/angular/src/test/javascript/e2e/admin/administration.spec.ts.ejs
generators/client/templates/angular/src/test/javascript/e2e/page-objects/jhi-page-objects.ts.ejs
generators/client/templates/angular/src/test/javascript/protractor.conf.js.ejs
generators/client/templates/angular/tslint.json.ejs
generators/client/templates/react/src/main/webapp/app/shared/reducers/locale.ts.ejs
generators/entity-client/templates/angular/src/test/javascript/e2e/entities/entity-page-object.ts.ejs
generators/entity-client/templates/angular/src/test/javascript/e2e/entities/entity.spec.ts.ejs

As the Selenium promise manager will surely be deprecated in the future, we should use async/await to handle promises and it is more readable than .then() imo

Make Angular e2e tests use async/await

---

generators/client/templates/angular/src/main/webapp/app/account/password/password-strength-bar.css.ejs
generators/client/templates/angular/src/main/webapp/app/account/password/password-strength-bar.scss.ejs
generators/client/templates/angular/src/main/webapp/app/home/home.css.ejs
generators/client/templates/angular/src/main/webapp/app/home/home.scss.ejs
generators/client/templates/angular/src/main/webapp/app/layouts/navbar/navbar.css.ejs
generators/client/templates/angular/src/main/webapp/app/layouts/profiles/page-ribbon.css.ejs
generators/client/templates/angular/src/main/webapp/app/layouts/profiles/page-ribbon.scss.ejs
generators/client/templates/react/src/main/webapp/app/app.scss.ejs
generators/client/templates/react/src/main/webapp/app/shared/layout/password/password-strength-bar.css.ejs
generators/client/templates/react/src/main/webapp/app/shared/layout/password/password-strength-bar.scss.ejs

update css files to match sonar requirements for css adding leading dash to browser specific css entries and removing dups
Fix #8044
To my knowledge these changes aren't testable for issue #8044 Sonar is generally the coverage for this and I have run sonar locally using the docker compose command and verified all green. Screenshot attached below.
- [N/A ] Documentation is added/updated where necessary

update css to match new SonarQube css rules

---

.vscode/launch.json
cli/commands.js
generators/login/USAGE
generators/login/index.js
generators/logout/USAGE
generators/logout/index.js
generators/statistics.js
package-lock.json

- Improve `jhipster login`
- Add new `jhipster logout`
- Add a JHIPSTER_ONLINE_URL env var to point the cli to another JHOnline instance
Note: As discussed today with Julien, the login/logout commands are disabled for now (but I'm keeping the code from @agaspardcilia and @chrisdns as it works well!), we need to uncomment the lines from cli.js to re-enable them.

JHipster Online statistics login / logout feature (temporarily disabled for now)

---

generators/cleanup.js
generators/server/templates/src/main/java/package/client/OAuth2InterceptedFeignConfiguration.java.ejs
generators/server/templates/src/main/java/package/config/OAuth2SsoConfiguration.java.ejs
generators/server/templates/src/main/java/package/config/UaaConfiguration.java.ejs

Fixes compilation issues after upgrade from v4.14.5 ( #8086 )

Remove profile-info resource and it's security mappings during upgrade to v5.x

---

generators/upgrade/index.js

Avoids issues like [this StackOverflow](https://stackoverflow.com/questions/51923119/trying-to-upgrade-to-jhipster-release-5-2-1-stops-on-anonymous-statistics-promp).  Also makes the statistics more accurate as the upgrade generator runs `jhipster` twice 

skip insight on upgrade

---

generators/generator-base.js

prevents conflicts with the gateway's generated routes for login (`/auth/login`)
Fix #8107

prevent 'auth' from being a UAA baseName

---

generators/client/templates/angular/package.json.ejs
generators/client/templates/angular/webpack/webpack.common.js.ejs
generators/client/templates/angular/webpack/webpack.dev.js.ejs
generators/client/templates/angular/webpack/webpack.prod.js.ejs
generators/client/templates/react/webpack/webpack.common.js.ejs
generators/client/templates/react/webpack/webpack.dev.js.ejs

Just made some changes to make the Webpack configurations more consistent and replaced deprecated `loaders` by `use`.
I also removed jquery from the Angular dependencies, it doesn't seem used.

Webpack polish

---

generators/server/templates/gradle/profile_prod.gradle.ejs

add h2 to prod profile for tests 
so that this command ./gradlew -P prod build buildDocker works
Fix #7888
I don't think this is testable other than adding the above build command to the CI scripts to ensure the prod profile tests always run correctly.  I also, ran the same process with maven `mvn clean package dockerfile:build` and it works correctly as the plugin inherits the test h2 dependency from the main pom section.

update gradle prod profile with h2 testCompile dependency

---

generators/client/templates/angular/src/main/webapp/index.html.ejs
generators/client/templates/react/src/main/webapp/index.html.ejs

In general, you should wait for the window load event before registering your service worker. This will allow the browser to prioritize assets for the page and will prevent any risk of precaching interfering with the page.

Register service worker the right way

---

generators/cleanup.js

- Fixes client compilation issue as listed in #8086 after upgrade to 5.x

Remove client side (angular) files during upgrade

---

generators/server/index.js
generators/server/prompts.js

64 bytes is sufficient since that's 512 bytes - the max needed for any JWT HMAC SHA algorithm.

Use 64 bytes of JWT Secret Key length

---

generators/entity/index.js

Fixes the i18n header sent on entity CRUD actions from the microservice [entity's Resource.java](https://github.com/jhipster/generator-jhipster/blob/78318d79240ba228f1e7863a4a19ad4b25b63b85/generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs#L94-L98).  This is already [set as the default value](https://github.com/jhipster/generator-jhipster/blob/78318d79240ba228f1e7863a4a19ad4b25b63b85/generators/entity/index.js#L420-L422) when generating microservice entities on the gateway.
Fix #7124

set default clientRootFolder for microservice entities

---

generators/server/files.js
generators/server/templates/src/main/resources/config/liquibase/changelog/initial_schema.xml.ejs
generators/server/templates/src/main/resources/config/liquibase/users_authorities.csv.ejs
generators/server/templates/src/test/java/package/web/rest/UserResourceIntTest.java.ejs

Fix #8018
This PR does the following:
- Adds missing constraint between `jhi_user <-> jhi_authorities` that `liquibase:diff` will generate on a fresh OAuth2 app.  
- Prevents the copy and import of the `.csv` files that are unused in OAuth2 microservices.
- Eventually we could cleanup the User/Authority relationship in OAuth2 microservices since it is unused (only the User is synced for relationships in OAuth2 microservices), but it would definitely complicate the templates and might be a breaking change
- Removes the invalid entries in `jhi_authorities` that point to non-existant users.  These prevents the constraint from being added for OAuth apps
OAuth2 apps upgrading from a previous version will need to delete the old invalid values in `jhi_user_authority` and add the constraint.  The …

add missing constraint for oauth apps

---

generators/client/templates/react/package.json.ejs

I'm working on https://github.com/jhipster/generator-jhipster/issues/8162
When generating a React application with NPM, I got this error, that I don't have with Yarn:
```
ERROR in /home/pgrimaud/tmp/react-npm/node_modules/@types/react/index.d.ts
ERROR in /home/pgrimaud/tmp/react-npm/node_modules/@types/react/index.d.ts(2232,33):
TS2339: Property 'exact' does not exist on type 'typeof import("/home/pgrimaud/tmp/react-npm/node_modules/@types/prop-types/index")'.
ERROR in /home/pgrimaud/tmp/react-npm/node_modules/@types/react/index.d.ts
ERROR in /home/pgrimaud/tmp/react-npm/node_modules/@types/react/index.d.ts(2312,54):
TS2694: Namespace '"/home/pgrimaud/tmp/react-npm/node_modules/@types/prop-types/index"' has no exported member 'InferProps'.
ERROR in …
```

Fix React+NPM applications

---

generators/client/templates/react/src/main/webapp/app/shared/auth/private-route.tsx.ejs
generators/client/templates/react/src/main/webapp/app/shared/reducers/authentication.ts.ejs
generators/client/templates/react/src/test/javascript/spec/app/shared/auth/private-route.spec.tsx.ejs

fix #7850 
So here's the idea. When you refresh your browser, private routes are rendered before the getSession is done. This redirects the application to home. The easy fix is to ask private routes to wait before at least one getSession is performed before doing anything.
I made a some simple modifications to fix that but it's kinda ugly tbh. I'll prolly make better version tomorrow.

Fix oauth redirect issue

---

generators/client/templates/react/src/main/webapp/app/modules/account/settings/settings.reducer.ts.ejs
generators/client/templates/react/src/main/webapp/app/shared/reducers/authentication.ts.ejs
generators/client/templates/react/src/test/javascript/spec/storage-mock.ts.ejs

It seems that the storage mocks for Jest were wrong on React. This caused the tests to fail on Node 10, I don't know why this worked on the LTS...
Also, I had some errors on async reducers tests so I needed to add `await` keywords before some `dispatch()`, I'm not a React expert so tell me if that's a normal way to dispatch actions or not...

Fix react tests on node 10

---

generators/entity/index.js

related to #8178, this fixes entity generation when it loads from the JSON file.  This also fixes old entities when upgrading, since regenerating your entities [doesn't update the `Entity.json` file](https://github.com/jhipster/generator-jhipster/blob/7461029601bfc4db9911c8f9204a68f74f2cde7e/generators/entity/index.js#L433-L435).
The JDL -> JSON conversion doesn't set the value in the microservice entity JSON, but that's a fix in `jhipster-core`. I'll try to look into it this weekend.  
Currently, the `client-root-folder` for microservices [is ignored in JDL](https://github.com/jhipster/jhipster-core/blob/40971397069abf04b9ac70b08e53718361d68a91/lib/parser/document_parser.js#L286-L290) but it's needed if you want the translation keys to match (only when mixing entities with default and …

set default client root folder for microservices with JDL

---

generators/statistics.js
package.json

I noticed strange patterns when looking at the graphs. They looked like they are produced by an automated system. Look how openshift and k8s stats follow the exact same trend !
It seems the --no-insight option is correctly set for Travis builds, however after adding some log in the analytics code, I noticed that it's our unit tests that are causing the issue.
The solution is to pass the --no-insight flag to npm test as well.

Prevent sending insight stats when running unit tests

---

generators/server/templates/src/main/docker/app.yml.ejs
generators/server/templates/src/main/docker/mssql.yml.ejs
generators/server/templates/src/main/resources/config/application-dev.yml.ejs
generators/server/templates/src/main/resources/config/application-prod.yml.ejs

Fix #8215 
at the moment the output in docker-compose.yml is not well formatted:
`
command:             /bin/bash -c /opt/mssql/bin/sqlservr & echo "wait $$MSSQL_SLEEP sec for
DB to start "; sleep $$MSSQL_SLEEP; /opt/mssql-tools/bin/sqlcmd -U sa -P
$$SA_PASSWORD -d tempdb -q "EXIT(CREATE DATABASE $$MSSQL_DATABASE)";
wait;
`
I guess that when the mssql.yml is read and printed [here](https://github.com/jhipster/generator-jhipster/blob/master/generators/docker-compose/templates/docker-compose.yml.ejs#L22) then the layout of the  command is changed.

WIP: add command to create the app DB in MSSQL

---

generators/heroku/index.js
generators/heroku/templates/Procfile.ejs
generators/heroku/templates/pom-profile.xml.ejs

The change disabled liquibase migrations from running inline with the web process, and moves them to the [Heroku Release phase](https://devcenter.heroku.com/articles/release-phase). This will significantly improve startup time, and prevents common problems related to concurrency (i.e. migrations running on more than one server process at the same time).
In more detail, this will add special Liquibase configuration to the Maven profile, and a `release` command to the `Procfile`. Heroku treats the `release` process type specially, and runs it when appropriate (i.e. after a deploy, or when a new database is attached).
The change only affects Git deploy (which will eventually become the default deploy mechanism for this generator).
*NOTE:* This PR includes the changes from #8225 because they …

[heroku] move Liquibase migrations to release phase

---

generators/heroku/index.js

This change makes Git deployment the default option for the Heroku generator.
Git has been a very popular option, but it also has a better experience now with #8229 merged. Git deployed apps will start up faster.

Make Git the default for Heroku deploy

---

generators/client/templates/angular/src/main/webapp/app/shared/alert/alert-error.component.ts.ejs
generators/client/templates/react/src/main/webapp/app/config/notification-middleware.ts.ejs

In addition to #7641 and #7653, my team noticed alerting messages on IE11 on prod profile were displayed randomly... Some `.toLowerCase()` were missing every time we tried to use header parameters...
We added them and alerting messages are now correctly displayed...
(OK... It's IE11 bullshit... Some companies still want to use it 👎 )
(Not sure about React fix, it seems obvious but still....)

Fix some IE11 incompatibilities when header attributes on HTTP response are used

---

generators/server/templates/src/main/docker/elasticsearch.yml.ejs

Limit the ES container memory usage
Fix #8249

ES docker-compose limit java memory

---

test/cli.spec.js

To reproduce the issue:
- `git clone https://github.com/jhipster/generator-jhipster toto`
- `cd toto`
- `npm run test:unit test/cli.spec.js` or `npm test`
Here the logs:
```
jhipster cli test
1) verify correct cmd format
✓ --help should run without errors (567ms)
✓ --version should run without errors (561ms)
✓ should return error on unknown command (593ms)
3 passing (2s)
1 failing
1) jhipster cli test
verify correct cmd format:
AssertionError: expected 'node /home/pgrimaud/tmp/toto/cli/jhipster ' to match /node (.*)generator-jhipster\/cli\/jhipster/g
at Context.it (test/cli.spec.js:21:24)
```

Fix cli tests when cloning with specific name

---

generators/server/templates/src/main/java/package/config/AsyncConfiguration.java.ejs

The Async configuration currently only allows us to set the async pool size and not the scheduler pool size.
This results in spring scheduled tasks having only one thread to execute all it's tasks.
The proposed change allows us to have the number of scheduler tasks to be the size of the core pool.
Ideally we should have one more configuration value in application.yml which will dictate the size of the executor pool.
See: https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/scheduling/annotation/EnableScheduling.html
"By default, will be searching for an associated scheduler definition: either a unique TaskScheduler bean in the context, or a TaskScheduler bean named "taskScheduler" otherwise; the same lookup will also be performed for a ScheduledExecutorService bean. …

Allow Spring boot Scheduled tasks to have multiple threads

---

generators/client/files-angular.js
generators/client/templates/angular/package.json.ejs
generators/client/templates/angular/webpack/webpack.prod.js.ejs
test/utils/expected-files.js

Extract-text-webpack-plugin is no longer recommended for CSS (See https://github.com/webpack-contrib/extract-text-webpack-plugin). We should use the mini-css-extract-plugin, as we do in Webpack.

Use mini-css-extract-plugin

---

generators/entity/index.js

When creating a relationship with `User`, it shouldn't warn about `User` not having `DTO`
This should close #8293

avoid warning on user relationship

---

generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs

This allows the JHipster for Ionic and Ignite JHipster to work out-of-the-box. Without this change, the modules would need to 1) include instructions for how to turn it on or 2) manually parse the default realm and change the behavior (which doesn't seem that easy).
Fixes #8314.

Keycloak: Enable implicit flow for web_app client by default

---

README.md
generators/server/files.js
generators/server/templates/build.gradle.ejs
generators/server/templates/src/main/java/package/config/ElasticsearchConfiguration.java.ejs
generators/server/templates/src/main/java/package/config/JacksonConfiguration.java.ejs

Spring Data Jest use by default Gson and is not configured to map the Java Date JSR310. This config switch the DefaultJestResultsMapper to Jackson with jackson-datatype-jsr310 module.
Fix #8249

Spring Data Jest : Restore and adapt ES config to handle JSR310

---

generators/client/templates/angular/package.json.ejs
generators/client/templates/angular/webpack/webpack.dev.js.ejs
generators/client/templates/react/package.json.ejs
generators/client/templates/react/webpack/webpack.dev.js.ejs

- Fixes #8275 
- Default timeout is 5 seconds which may not suit in poor performing application.

Fix browsersync refresh loop

---

generators/server/templates/src/main/java/package/service/UserService.java.ejs
generators/server/templates/src/test/java/package/web/rest/AccountResourceIntTest.java.ejs

Making delete activated user equall for both login and email so both have the flush and fixing test which wrongly hit duplicated login while trying to test duplicated email with casing.
checking that

fixing: UserService missing flush #8303

---

generators/server/templates/src/main/java/package/Application.java.ejs
generators/server/templates/src/main/resources/static/microservices_index.html.ejs

As discussed here: https://github.com/jhipster/generator-jhipster/pull/8151#issuecomment-4154188038151#issuecomment-415418803
```
2018-09-14 14:12:03.763  INFO 75207 --- [  restartedMain] com.mycompany.myapp.App0914App           :
----------------------------------------------------------
Application 'app' is running! Access URLs:
Local: 		http://localhost:8081/app
External: 	http://172.32.67.148:8081/app
Profile(s): 	[dev, swagger]
----------------------------------------------------------
```

Servlet context-path startup log

---

generators/languages/index.js

- Should close the last open item in #8086 fix #8086
- As per yeoman docs, `configuring` priority queue is the correct phase to save/update configurations. All sub-generators except languages were following that.
- Ideally, main generator should also follow to save configurations in `configuring` phase instead of `default` phase, but, that doesn't seems to work at moment and need to be looked further.

Move saveConfig() method from 'default' to 'configuring' priority queue

---

generators/server/templates/gradle/sonar.gradle.ejs

I just corrected the junit report path. The coverage results for both maven and gradle are the same (empty, default projects each).
fix #8220

correct gradle sonar config

---

generators/server/files.js
generators/server/templates/src/main/resources/config/application.yml.ejs

also adds context-path to uaa without serviceDiscoveryType
This restores the authentication code to UAA Gateways with no service discovery.  Logging in won't work out-of-the-box because it points to the UAA, a developer who chooses these options will need to update the path to point to their UAA or set up a proxy like Istio does.  This is the same situation for regular microservices with no service discovery type (fetching entities doesn't work out-of-the-box).
It should work with a proxy or Istio though thanks to the new context-path for UAAs with no service discovery (this is how microservices work, and the UAA functions the same - it's requested by including the base name in the URL).
Fix #8297

restore uaa auth files when serviceDiscoveryType is false

---

generators/kubernetes/templates/deployment.yml.ejs
generators/openshift/templates/deployment.yml.ejs
generators/server/templates/src/main/docker/app.yml.ejs
test/templates/compose/03-psql/src/main/docker/app.yml

Fix #8326
- spring-data-jest uses port 9200 instead of 9300 (which spring-data-elasticsearch used)
- url must begin with a scheme

update elasticsearch port and use http scheme

---

generators/ci-cd/templates/.gitlab-ci.yml.ejs

This will ensure the app uses the right buildpack, even if a Git deploy has been done with `jhipster heroku`, which sets a different buildpack.

Add heroku/jvm buildpack to ci deploy

---

generators/ci-cd/templates/circle.yml.ejs
generators/ci-cd/templates/jenkins/Jenkinsfile.ejs
generators/ci-cd/templates/travis.yml.ejs

Follow up for https://github.com/jhipster/generator-jhipster/pull/8375 
Adding the heroku build pack to all mvn commands for all generators. The required change for gradle is contained here: https://github.com/jhipster/generator-jhipster/pull/8368

add heroku buildpack to all mvn commands for all providers

---

generators/server/templates/src/main/resources/swagger/api.yml.ejs

Starting an application with `enableSwaggerCodegen` currently fails with:
```
> There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
| Error count: 1, Warning count: 0
Errors: 
-attribute info.title is missing
```

add title to swagger api.yml

---

generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management-update.component.ts.ejs

Changed how the previousState functions to redirect to previous page
instead of going to default user-management page.
fixes #8398

fix user management previous state to redirect to previous page

---

generators/server/templates/src/main/docker/Dockerfile.ejs

These improvements were lost when merging #7722.
@gclayburg, @PierreBesson was this intentional. If not, please refer to #6744 for explanation.

Re introduced Docker image cache improvments from #6744

---

.travis.yml
generators/client/templates/angular/src/test/javascript/protractor.conf.js.ejs
generators/client/templates/angular/webpack/webpack.dev.js.ejs
generators/client/templates/react/src/test/javascript/protractor.conf.js.ejs
generators/client/templates/react/webpack/webpack.dev.js.ejs

When launching Protractor in Azure DevOps, I need to use Chrome in Headless mode.
So I added a new environment variable in Protractor config for that, beginning with `JH_` , so few chance to have same variable in their environment
I rename `DISABLE_WEBPACK_LOGS` to `JH_DISABLE_WEBPACK_LOGS` to be consistent (recently added by @wmarques)
```
export JH_E2E_HEADLESS=true
npm run e2e
```
Another solution would be to create a new goal in `package.json`, like `e2e-headless` but I don't know how to achieve this.
_____
-   [ ] Coding …

New env var for e2e in headless mode

---

generators/docker-compose/index.js

Fix #8428 
I actually did two changes in this PR:
- Max line width is now unlimited (by default it's 80 chars):
I don't see any issue having unlimited line width and it avoids having to replace weird characters (>-) added by the js-yaml library when the line is too long.
- Simple quotes are no longer removed:
The js-yaml library adds simple quotes when the value is an url or contains special characters. I decided to keep those simple quotes since they don't make the yaml invalid and it's more simple than having a special case for mssql to avoid removing the simple quotes when they are actually needed (could happen for an other component than mssql).
@stevehouel: can you take a look and let me know if you agree with the changes?
-   Please make sure the below checklist is followed for Pull …

Avoid removing simple quotes when using docker-compose with mssql

---

generators/client/templates/react/src/test/javascript/e2e/modules/account/account.spec.ts.ejs
generators/client/templates/react/src/test/javascript/e2e/util/utils.ts.ejs

As Cassandra doesn't have the audit code, that button does not exist
@pascalgrimaud this should solve one error in the hipster lab builds

Do not click on the "modified by" button when using Cassandra

---

generators/entity-client/templates/react/src/test/javascript/spec/app/entities/entity-reducer.spec.ts.ejs

Fix #8441 
A gateway with React, UAA and no database was generating a wrong pk's value when generating an entity from a microservice using a SQL db.

Fix how pk's type is checked for a gateway using React

---

generators/server/templates/gradle/swagger.gradle.ejs
generators/server/templates/src/main/resources/swagger/api.yml.ejs

Fixed invalid openapi spec (title must be in info object) and enabled validation explicitly (which is the default for the latest gradle plugin)

fix invalid open api spec

---

generators/server/templates/gradle/profile_dev.gradle.ejs
generators/server/templates/gradle/profile_prod.gradle.ejs

We have build some special handling to decided when to run the frontend build (I guess because we need to do something similar in maven). With gradle we can use the build in up-to-date check mechanism. So basically we can rely on `Task has outputs and inputs and they have not change`. It works quite well. As an example you can also have look at this (incomplete) guide: https://guides.gradle.org/running-webpack-with-gradle/ …

use gradles build in up-to-date checking

---

generators/server/templates/pom.xml.ejs

Sorry, forgot to update the maven plugins when I did the same for gradle.

align openapi plugin with current gradle implementation [ci-skip]

---

generators/ci-cd/index.js
generators/ci-cd/prompts.js
test/ci-cd.spec.js

That PR is to update the Gitlab to include autogeneration option, like Travis and Jenkins.
The motivation is the issue in jhipster/jhipster-online#80

Add a flag to auto-configure Gitlab

---

generators/server/templates/pom.xml.ejs

When running pod ok k8s, I have an error : (on my local docker it's fine)
sh: /entrypoint.sh : Text file busy
Looking in https://github.com/moby/moby/issues/9547,  it seems that the script can't start because the file is still busy with chmod.
I added a sync between the chmod and the script startup.
After that, all my microservices started correctly on kubernetes.
Changed in the pom.xml : 
`chmod +x /entrypoint.sh && /entrypoint.sh`
with
`chmod +x /entrypoint.sh && sync && /entrypoint.sh`

fix docker start with jib : added a sync before starting /entrypoint.sh

---

generators/client/templates/angular/package.json.ejs
generators/client/templates/angular/src/test/javascript/protractor.conf.js.ejs
generators/entity-client/templates/angular/src/test/javascript/e2e/entities/entity.spec.ts.ejs

Wip: Use promise.all to parallelize protractor inputs.
This as reduced the time of our build by two on a big project!

use promise to parallelise protractor input

---

generators/server/templates/src/main/docker/elasticsearch.yml.ejs

Following this PR https://github.com/jhipster/generator-jhipster/pull/8264
I'm working on using Azure Pipelines (https://github.com/jhipster/generator-jhipster/issues/8337)
512m is not enough, and I have a lot of random failures.
Increasing to 1024m seems to solve my issues. Hope you're ok with this change, @ndywicki
Here the logs:
```
2018-10-04T04:28:15.6246473Z 04:28:15.615 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
2018-10-04T04:28:15.6248413Z org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'entityWithPaginationAndDTOResource' defined in URL [jar:file:/home/vsts/app/app.war!/WEB-INF/classes!/com/mycompany/myapp/web/rest/EntityWithPaginationAndDTOResource.class]: Unsatisfied dependency expressed …
```

Elasticsearch: limit memory to 1024m

---

.eslintrc.json
test/app.spec.js
test/blueprint/client-blueprint.spec.js
test/blueprint/entity-blueprint.spec.js
test/blueprint/server-blueprint.spec.js
test/ci-cd.spec.js
test/client.spec.js
test/docker-compose.spec.js
test/ejslint.js
test/entity.spec.js
test/export-jdl.spec.js
test/generator-base-private.spec.js
test/generator-base.spec.js
test/heroku.spec.js
test/kubernetes.spec.js
test/languages.spec.js
test/load.spec.js
test/openshift.spec.js
test/rancher-compose.spec.js
test/server.spec.js
test/service.spec.js
test/spring-controller.spec.js
test/utils.spec.js
test/utils/utils.js

Rather than using global instructions in the header of each test, declares mocha environment globally for tests in .eslintrc.json.

Clean eslint oriented instructions in tests, declare global mocha env

---

generators/client/templates/angular/webpack/webpack.common.js.ejs

Fixing the order that chuncks are loaded so that the global file is loaded after the main.  This will ensure CSS overrides of bootstrap in the global.css/global.sass work.  https://github.com/jantimon/html-webpack-plugin#options

Chunk Order Fix

---

generators/server/templates/src/main/resources/templates/mail/activationEmail.html.ejs
generators/server/templates/src/main/resources/templates/mail/creationEmail.html.ejs
generators/server/templates/src/main/resources/templates/mail/passwordResetEmail.html.ejs

Use `th:with` syntax to define variables instead of duplicate URLs.
(https://www.thymeleaf.org/doc/articles/standardurlsyntax.html) 

Use variable for URLs in Thymeleaf templates

---

generators/client/templates/angular/src/main/webapp/app/core/auth/csrf.service.ts.ejs

It's better to use the default parameter than checking manually in the code 

Angular: use default parameter in CSRF service

---

generators/client/templates/angular/package.json.ejs

We should remove `rxjs-compat` as it is provided for migration between rxjs 5.5 and rxjs 6. Now all of our dependencies uses rxjs6 we can safely remove it.
It also allow to do tree-shaking on rxjs operators which save some kB (27 to be precise) 🎉 

Angular: remove rxjs-compat and bump ngx-infinite-scroll

---

generators/client/index.js

With @jdubois we had the problem today because we mistakenly used `angular` instead of `angularX` in our app JDL, which caused the app to not generate entities. So I'm adding a fallback to convert **angular** to **angularX**.
Example app:
```
application {
config {
baseName store,
applicationType gateway,
packageName com.jhipster.demo.store,
serviceDiscoveryType eureka,
authenticationType jwt,
prodDatabaseType mysql,
cacheProvider hazelcast,
buildTool maven,
messageBroker kafka,
clientFramework angular,
testFrameworks [protractor]
}
entities *
}
```
-   [ ] Coding Rules & Commit Guidelines as per …

Fallback clientFramework=angular to the angularX

---

generators/server/templates/src/main/resources/templates/mail/creationEmail.html.ejs

It will also align URLs for both react and angular apps.
It has already been done for other thymeleaf templates
Fix #8522 

Fix creationEmail link for react

---

generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs

Fix #8454, this will avoid a wrong user_id type when having a relationship called 'user' that does not refer to the entity User.

Use 'otherEntityName' instead of 'relationshipName'

---

generators/heroku/templates/application-heroku.yml.ejs
generators/heroku/templates/bootstrap-heroku.yml.ejs

Non eureka apps don't require ${JHIPSTER_REGISTRY_URL}

Heroku: set ${JHIPSTER_REGISTRY_URL} only for eureka apps

---

generators/generator-base-private.js

The import's path was wrong for a gateway since a folder is created for each microservice and user.model.tsx is in the parent folder.

Use absolute path to user's model with React

---

generators/client/templates/react/src/main/webapp/app/modules/account/settings/settings.reducer.ts.ejs
generators/client/templates/react/src/main/webapp/app/shared/reducers/authentication.ts.ejs
generators/client/templates/react/src/test/javascript/spec/app/shared/reducers/authentication.spec.ts.ejs

In the #8525 , there is a issue for the Storage, previour we only import it for JWT. but now since we add the language logic to the getSession, the Storage will be imported when the enableTranslation is true.

fix-issue-for-PR#8525

---

generators/ci-cd/templates/.gitlab-ci.yml.ejs

Fix gitlab-ci generator for maven:
Compile project before launching Sonar analyse
Use values from generator for Sonar URL and Organization

fix gitlab-ci sonar-analyse with maven

---

generators/cloudfoundry/index.js
generators/server/templates/build.gradle.ejs
generators/server/templates/pom.xml.ejs
generators/server/templates/src/main/java/package/config/CloudDatabaseConfiguration.java.ejs
generators/server/templates/src/main/java/package/config/Constants.java.ejs

Fix #8518 #8169 
#8169 
First time deployment would have failed, because the updated pom.xml (with cf connectors) from the CF sub-generator would have been written to the file system after the build that got triggered from the same sub-generator. So the build would have had happened not with the updated pom.xml. When the subsequent re-deployment happens, pom.xml was already updated (in the previous run) and hence the service binding would have gone through without any issues.
I noticed spring-cloud-spring-service-connector in the main pom.xml and in CF sub-generator cf specific connectors are being added. I've replaced everything with spring-boot-starter-cloud-connectors in the main pom.xml that includes both service and cloud specific connectors. There is no harm keeping it in the main …

update spring connector auto-config - Fix for #8518 #8169 

---

generators/client/files-react.js
generators/client/templates/react/src/main/webapp/app/shared/reducers/index.ts.ejs

fixes non-OAuth2 React apps with `skipUserManagement = true`
`skipUserManagement` is set to true for OAuth2 apps [here](https://github.com/jhipster/generator-jhipster/blob/50df54efe80d1127c6ebd816e2de86f1379150ec/generators/generator-base.js#L2856-L2858), using just an `else` breaks it for other auth types
Fix jhipster/jhipster-core#268
Fix #8549

only import OAuth2 user-management files for OAuth2

---

generators/app/index.js

Need to call done() when the project is not a git repo otherwise other generator end() methods won't be called.

All generator end() methods not getting called when project is not a git repo

---

generators/client/templates/angular/src/main/webapp/app/account/activate/activate.route.ts.ejs

This makes me wonder how many people actually use the UAA...
Same change as #7779, modeled the route config after the register route which doesn't request the account
Fix #8617

fix uaa user activation for angular apps

---

generators/entity-client/templates/react/src/test/javascript/e2e/entities/entity.spec.ts.ejs

Fix https://github.com/jhipster/generator-jhipster/issues/8379
Here a full builds with React+Protractor, using my code:
https://travis-ci.org/hipster-labs/jhipster-travis-build/builds/444291196
_____

React: fix delete e2e tests

---

generators/ci-cd/templates/.gitlab-ci.yml.ejs
generators/server/templates/gradle/profile_dev.gradle.ejs

we don't need the additional check it is basically useless.
closes #8626

remove not required check for executing npm/yarn_install tasks

---

generators/client/templates/angular/src/main/webapp/app/app.module.ts.ejs
generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/auth-expired.interceptor.ts.ejs
generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/auth.interceptor.ts.ejs
generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/errorhandler.interceptor.ts.ejs
generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/notification.interceptor.ts.ejs

Since Angular 5.2.3 we can use @Injectable for classes which implement HttpInterceptor (without the cyclic dependency error)
Angular thread: https://github.com/angular/angular/pull/19809
I tested it and it seems working fine.

Remove deps in favor of injectable for http interceptors

---

generators/client/templates/angular/package.json.ejs

Related to #8149 
Seems to work fine for dev environment at least
Need to wait for https://github.com/angular/angular/issues/25200 in order to have `@ngtools` accepting TS3.

Angular: Update to Typescript 3 and Angular 7

---

generators/server/templates/src/main/resources/banner-react.txt

I think it's better with CYAN color.
We can now use the blue color for https://github.com/jhipster/jhipster-vuejs
_____

React: use CYAN color for banner [ci skip]

---

generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs

Add 'unique = true' to the @Column if the field validate rule is "unique"
Before:
`@Column(name = "just_a_test", nullable = false, unique = true)`
After:
`@Column(name = "just_a_test", nullable = false)`

Add 'unique = true' to the @Column when needed

---

generators/kubernetes/templates/console/jhipster-dashboard-console.yml.ejs

- removed redundant dashboard import call in K8s manifest as it is already taken care in the Dockerfile itself.

remove redundant dashboard import call

---

generators/generator-base-private.js

Since it's unlikely that a blueprint will override all jhipster subgenerators, warn each time a subgen is not found is bit too loud

Change log level when blueprint subgen not found

---

generators/client/templates/angular/package.json.ejs
generators/generator-constants.js

- Upgrade yarn to `v1.12.1`
- Fix `test:watch` script in angular. If we pass `--clearCache` option to Jest, then, that would clear the cache, but, wouldn't execute the tests. I also checked equivalent script in react and don't see usage of `--clearCache`. If we have any specific reason to support this, then, we should support it as separate script. I didn't use `&&` to execute test script twice (one with `--clearCache` and other with `--watch`) as that would also execute `lint` script twice (again not sure why lint is executed along with test script)
-   [x] Documentation is …

Upgrade yarn and fix test:watch script in angular

---

generators/server/templates/pom.xml.ejs

This is a temporary fix until the surefire team have fixed this in a new version (after 2.22.1)
see: #8693

resolve: Failed to execute goal maven-surefire #8693

---

generators/client/templates/angular/package.json.ejs
generators/client/templates/react/package.json.ejs

Related to #8709. Sorry I just realised that I didn't also update `lint-staged` to apply changes to JSON files and `tslint-config-prettier` should be updated to work with the latest prettier. I'm still learning how this all fits together.

Use Prettier for Json for lint-staged

---

generators/server/templates/pom.xml.ejs

Maven projects using Elasticsearch fail to start without these dependencies.
Pinging @Tcharl since they may know a better way to fix this (these dependencies were removed in #8475).  I don't notice anything wrong when adding these dependencies back to the pom.xml.
related to #8739 

fix maven elasticsearch missing dependencies

---

generators/server/templates/src/main/java/package/config/ElasticsearchConfiguration.java.ejs

Custom MappingElasticsearchConverter to support mongodb relations
Based on https://github.com/deshetti/mongo-es-issue/commit/2c54dec25ced959cf0faac3930cecdfdb082a3d7
Fix #8666

add custom MappingElasticsearchConverter to ElasticsearchConfiguration

---

generators/server/templates/pom.xml.ejs

Fixes maven compilation warning on microservices
-   [ x] Tests are added where necessary
-   [ x] Documentation is added/updated where necessary
-   [ x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

do not declare frontend-maven-plugin when no client

---

generators/generator-base.js

In the PR #8632 , we read the `skipClient` from the .json file. But if the `skipClient` is not in the .json file. the value will be `undifined`. As a result, the `skipClient` will be overwrite to `undefined`, when we update the entity in the microservice app, it will generate the frontend code. 
1.  use any generator v5.6.0 or v5.6.1
1.  generate a microservice app
1.  generate any entity (first it will succeed): `jhipster entity book`
1.  rerun the command  `jhipster entity book` to regenerate the entity, it will generate the frontend code.
-   [x] Documentation is added/updated …

fix issue with skipClient

---

generators/server/templates/src/main/resources/config/bootstrap.yml.ejs

This is to achieve parity with our Eureka configuration.

Report the git version/branch/commit in consul instance metadata

---

generators/client/index.js
generators/common/index.js
generators/entity-client/index.js
generators/entity-i18n/files.js
generators/entity-i18n/index.js
generators/entity-server/index.js
generators/entity/index.js
generators/generator-base-blueprint.js
generators/server/index.js
generators/spring-controller/index.js
generators/spring-service/index.js
test/blueprint/client-blueprint.spec.js
test/blueprint/common-blueprint.spec.js
test/blueprint/entity-blueprint.spec.js
test/blueprint/server-blueprint.spec.js
test/templates/ngx-blueprint/.yo-rc.json
test/utils/utils.js

This parent class holds the public API that can be used for developers of blueprint.
See [this discussion](https://github.com/jhipster/generator-jhipster/pull/8623#discussion_r226876596) for the rationale.
This PR replaces #8677 : I've given up the factorization for now since it introduced regressions, but I've added more unit tests and fixed entity-i18n subgenerator and related entity-blueprint test.
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob …

Blueprint base api : parent class for generator extendable through a blueprint

---

test-integration/scripts/10-install-jhipster.sh

Related to https://github.com/jhipster/jhipster/pull/124
No impact here, as we only use release version -> that's why I put `[ci skip]`
@DanielFran : same comment, I'll cherry pick to spring boot 2.1, unless you're not OK
_____

CI: migrate jhipster/jhipster to test-integration folder [ci skip]

---

generators/generator-base-private.js

- info logging when composition worked (subgen found)
- debug logging when composition failed (subgen not found), but this is an expected error since blueprint usually overrides only a few subgenerators .

Inverse logic for blueprint composition logging and improve wording and formatting

---

generators/client/templates/react/src/main/webapp/app/shared/layout/header/header.tsx.ejs

Whe should use Storage.session for both setting an get langKey value
#8541

Fix loosing design direction (RTL) when refresh the page

---

generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs

Let Liquibase determine the correct field type for the database
Closes: #8765

Use boolean instead of bit for the Boolean type

---

package.json

Currently running `npm prettier:format` generates the following error : 
```
[error] No matching files. Patterns tried: '{,**/}*.{js,json,md}' !**/node_modules/** !./node_modules/**
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! generator-jhipster@5.7.0 prettier:format: `prettier --write '{,**/}*.{js,json,md}'`
npm ERR! Exit status 2
```

Fix prettier:format script

---

generators/server/templates/pom.xml.ejs

Hi team,
I just ran into some errors when running `mvn site` on a multimodule project which includes one jhipster-generated monolith. It turns out it can be easily prevented, by moving the eclipse lifecycle plugin (which isn't actually a really existing plugin, which is why the maven goal fails) into a separate profile which is activated automatically if the m2e eclipse plugin is active.
See also the accepted answer at:
https://stackoverflow.com/questions/7905501/get-rid-of-pom-not-found-warning-for-org-eclipse-m2elifecycle-mapping
-   [x] Documentation is added/updated where …

Move eclipse lifecycle mapping to separate profile

---

generators/app/index.js
generators/client/index.js
generators/common/index.js
generators/generator-base-private.js
generators/generator-base.js
generators/languages/index.js
generators/server/index.js
test/app.spec.js

Composed common subgen after client and server, since they're defining and prompring their own options that common will uses, and add missing `'client-hook'` parameter.
Changed the way common subgen loads its variables: mainly from `this.config` and `this.configOptions`.
Fixes #8783.

Fix loading of variables in common subgen

---

generators/ci-cd/index.js
generators/ci-cd/templates/.gitlab-ci.yml.ejs
generators/ci-cd/templates/azure-pipelines.yml.ejs
generators/ci-cd/templates/circle.yml.ejs
generators/ci-cd/templates/jenkins/Jenkinsfile.ejs
generators/ci-cd/templates/travis.yml.ejs
generators/client/templates/react/package.json.ejs
test-integration/scripts/22-tests-frontend.sh

Following https://github.com/jhipster/generator-jhipster/pull/8816, this simply cleans up the script and add a new script to run `jest --updateSnapshot` by itself.

Improve npm/yarn scripts to run jest tests

---

CONTRIBUTING.md
test-integration/generate-sample.sh
test-integration/scripts/00-init-env.sh
test-integration/scripts/11-generate-entities.sh

Last steps before deleting old `travis/` folder.
Currently, we have `build-samples.sh` which can:
- list
- generate
- build
- clean
I change it to this new `generate-sample.sh`, which will only:
- list all samples
- generate: it will copy the `.yo-rc.json` and all entities
This new script won't generate any more a new JHipster project, either won't launch test.
The reason is the new shell scripts are compatible with Travis and Azure, not locally. A non-set variable could delete all your folders (I delete accidently my `~/app/`, so I don't want it happened to our users).
_____
-   [ …

CI: add generate sample script

---

test-integration/scripts/22-tests-frontend.sh

Thanks @sahbi-ktifa for reporting me this
_____

CI: fix condition for launching npm test by default

---

generators/docker-compose/templates/jhipster-registry.yml.ejs

With this PR I will give users a hint on how to tune the registry to use with a custom named UAA server (see https://github.com/jhipster/jhipster-registry/pull/314)
It doesn't change the default behavior but is helpful if the user will search for how to change that.

add UAA environment var for JHipster Registry in docker-compose

---

azure-pipelines.yml
generators/client/templates/angular/src/test/javascript/spec/app/core/user/account.service.spec.ts.ejs

Following this merge https://github.com/jhipster/generator-jhipster/pull/8513
There are some nightly failed builds, related to Websocket:
- https://dev.azure.com/hipster-labs/jhipster-daily-builds/_build/results?buildId=209&view=logs
- https://dev.azure.com/hipster-labs/jhipster-daily-builds/_build/results?buildId=211&view=logs
So I found that I removed accidentaly the build with Websocket.
1st commit is to put back the build with Websocket.
2nd commit is for the fix.
_____ …

CI: add websocket to Azure builds

---

generators/server/templates/build.gradle.ejs
generators/server/templates/gradle/profile_dev.gradle.ejs
generators/server/templates/gradle/profile_prod.gradle.ejs
test-integration/scripts/23-package.sh

the original war is now also created when building an executable war via `bootWar` task.
closes #8811
closes #8860

enable original war packaging 

---

test-integration/scripts/23-package.sh

Following https://github.com/jhipster/generator-jhipster/pull/8866
I'd prefer to keep `./gradlew bootWar -P"$JHI_PROFILE" -x test` so it is similar to what our end users will use. Are you ok with that @atomfrede ?
_____

CI: use default build for Gradle and copy the non original war

---

generators/client/templates/angular/webpack/webpack.prod.js.ejs
generators/client/templates/react/webpack/webpack.prod.js.ejs
generators/common/templates/README.md.ejs
generators/docker-base.js
generators/docker-utils.js
generators/server/templates/gradle/docker.gradle.ejs
generators/server/templates/pom.xml.ejs

This PR is a WIP to fix #8586.
When introducing JIB, the static assets were generated to a standard Spring MVC static location ( `classpath:/public`) to then be integrated into the JIB resource layer.
This feature broke the webserver compatibility of JHipster (Tomcat, Undertow, etc.)
The main action is to rollback to the standard `www` folder for static assets …

Fix JIB integration www folder issue

---

generators/generator-base.js
test-integration/samples/.jhipster/SuperMegaLargeTestEntity.json
test-integration/samples/.jhipster/TestManyToMany.json
test-integration/samples/.jhipster/TestManyToOne.json
test-integration/samples/.jhipster/TestOneToOne.json
test-integration/scripts/11-generate-entities.sh
travis/samples/.jhipster/SuperMegaLargeTestEntity.json
travis/samples/.jhipster/TestCustomTableName.json
travis/samples/.jhipster/TestManyToMany.json
travis/samples/.jhipster/TestManyToOne.json
travis/samples/.jhipster/TestOneToOne.json
travis/scripts/01-generate-entities.sh

PostgreSQL has 63 byte identifier length limit.
See: https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS
"The system uses no more than NAMEDATALEN-1 bytes of an identifier;
longer names can be written in commands, but they will be truncated. By
default, NAMEDATALEN is 64 so the maximum identifier length is 63
bytes."

[PostgreSQL] Add constraint name length limit

---

generators/server/templates/src/main/resources/config/liquibase/changelog/initial_schema.xml.ejs

1. Postgres Exception @ users loadData
In case of postgresql the id is considered as varying value
instead of numeric. The loadData failed. We have to force the type when load data.
It seems to be a regression but don't any information about it.
> Reason: liquibase.exception.DatabaseException: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO public.jhi_user(id, login, password_hash, first_name, last_name, email, image_url, activated, lang_key, created_by, last_modified_by) VALUES('1', 'system', '$2a$10$mE.qmcV0mFU5NcKh73TZx.z4ueI/.bDWbj0T1BYyqP481kGGarKLG', 'System', 'System', 'system@localhost', '', 'TRUE', 'en', 'system', 'system') was aborted: ERROR: column "id" is of type bigint but expression is of type character varying
-   [ ] [Travis …

Force user id to be considered as numeric value when loadData with postgresql and Liquibase

---

generators/server/templates/src/main/resources/config/application-dev.yml.ejs
generators/server/templates/src/main/resources/config/application-prod.yml.ejs

When using MariaDb or MysqlDb we should add this property
to prevent error when both JVM and database
are not on the same timezone
fix #8896

Add 'serverTimezone=UTC' in properties MariaDb, Mysql

---

generators/server/templates/src/main/resources/config/application-dev.yml.ejs

Fixes restarting on h2 connection in dev.  Connecting to h2 modifies `src/main/resources/.h2.server.properties` with the current date, which can cause a live-reload to happen.
FIx #6858
[Spring Boot Live Reload exclusion docs](https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html#using-boot-devtools-restart-exclude)

exclude .h2.server.properties from devtools restart

---

generators/languages/templates/src/main/webapp/i18n/fa/global.json.ejs

The correct Spell of settings in Farsi is "تنظیمات"
Fix #8918

Correct spell of settings in Farsi

---

generators/server/templates/src/main/docker/elasticsearch.yml.ejs

Revert to version 2 otherwise it does not start
Remove command network.host deprecated (it seems that we don't need it anymore)
Move command discovery.type to environment (-e command is no longer recognized)
#8683

Fix Docker elasticsearch settings

---

generators/upgrade/index.js
test/upgrade.spec.js

2 fixes:
- incorrect npm syntax for installing dev dependency
- extraneous commits were generated
I've created a unit test for this subgenerator, that is bit long to run since it generates a new application, and then run the upgrade process. This is not perfect, but it's still better than nothing.

Fixes for the upgrade subgenerator

---

generators/server/templates/src/test/java/package/AbstractCassandraTest.java.ejs

Fixes NoClassDefFoundError: com/codahale/metrics/JmxReporter 
Change benefits from the fix done for https://github.com/jsevellec/cassandra-unit/issues/255

Fix cassandra unit tests with java 8

---

test/entity.spec.js

Before:
After:
Excepted the addition of `assert.file(expectedFiles.server);` in the test with elastisearch, there's no other changes than reordering, adding context, rewording.

Reorganize entity tests: reorder, regroup by context, reword

---

generators/common/files.js
generators/common/index.js
test/app.spec.js

Prettier configuration needs to be written before all other files, all subgenerators considered
This regression is (re)formatting all javascript, typescript, json, ... with 2 spaces tab with, instead of 4 spaces.
See e.g. https://github.com/jhipster/jhipster-sample-app/commit/f4758950c6a14f107040c6167232bad6330fafba#diff-9f0810dd246846b72b1e562d738464d4

Fix regression with prettier transform after the move to common subgen in 5.7.1

---

generators/server/templates/src/main/resources/config/application-dev.yml.ejs
generators/server/templates/src/main/resources/config/application-prod.yml.ejs

I think the current comment is now obsolete. The base64 secret needs to be very long and created from non-alphanumeric characters. So a simple echo doesn't work. Using openssl works.

Tell how to generate a valid base64 HMAC secret

---

generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIntTest.java.ejs

Fix comment in EntityResourceIntTest
Replace `Get` with `Delete`

Fix comment in EntityResourceIntTest

---

generators/server/templates/build.gradle.ejs

pretty simple, we rename the `-original.war` to `.war.original` and delete the `-original.war` file. So now when executing `./gradlew bootWar` we will have the executable war file and the `.original` file similar to what maven generates.
closes #8972

rename the `-original.war` to `.war.original` to have only one war file

---

generators/client/templates/react/src/main/webapp/app/config/constants.ts.ejs

change "hh" lowercase to "HH" capital letters because cause an error when an entity to be updated is fetched, the time is shown in 12 hour format in update view and in 24 hour format in detail view

change APP_LOCAL_DATETIME_FORMAT constant

---

generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
generators/entity/index.js

fix issue with relationship.otherEntityRelationshipName and entity generation
- initialize relationship.otherEntityRelationshipName properly
- do not generate @JsonIgnoreProperties when
otherEntityRelationshipNamePlural is undefined or empty
- fix add/remove for @ManyToMany for the owner side
Fix #8991

fix issue with relationship.otherEntityRelationshipName and entity generation

---

generators/server/templates/src/main/resources/config/application.yml.ejs

Use deferred mode for JPA repositories, to speed up start up.
See #8954

Use deferred mode for JPA repositories, to speed up start up

---

generators/server/templates/src/main/java/package/Application.java.ejs
generators/server/templates/src/main/resources/config/application-dev.yml.ejs
generators/server/templates/src/main/resources/config/application-prod.yml.ejs
generators/server/templates/src/main/resources/config/application.yml.ejs

Remove JMX setup by default.
If this works well, this should be set to false by default: https://github.com/jhipster/jhipster/blob/2.0.28/jhipster-framework/src/main/java/io/github/jhipster/config/JHipsterDefaults.java#L156
See #8954

Remove JMX to improve start-up performance

---

generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.html.ejs

see #8989 for the react version, safari does not show datetime picker.

add placeholder to datetime-local input (angular version)

---

generators/generator-base.js
generators/server/templates/gradle.properties.ejs

Add needle and utility method for adding a gradle property
Fix #9015 

Add needle and utility method for adding a gradle property

---

generators/generator-base.js

Change addGradlePlugin method to use double instead of single quotes to allow for string interpolation
Fix #9017

Change addGradlePlugin method to use double instead of single quotes to allow for string interpolation

---

test-integration/scripts/25-sonar-analyze.sh

Quick fix for now. 
I'll put jq back when I'll start to work on Sonar analyze which will failed the build if the coverage is under a specific percentage

Spring Boot 2: Sonar: no use of jq

---

generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs
generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity_constraints.xml.ejs

fix #8447
This issue suggests to singularize `JoinColumn` names in ManyToMany relationships, actually I also think it would be better logic to use singular here.
The author of the issue gives also some articles that shows this is considered as a "best practice".
ps: this might annoy people with jhipster migration 

Singularize JoinColumn names in ManyToMany

---

generators/server/templates/src/test/java/package/config/timezone/HibernateTimeZoneTest.java.ejs

Fix #8790
UAA settings need to be bypassed at testing phase so they do not interfere testing. For that SecurityBeanOverrideConfiguration class needs to be included in @SpringBootTest which is missing in HibernateTimeZoneTest class.

override UAA specific beans in test phase

---

generators/server/files.js
generators/server/templates/src/test/java/package/cucumber/CucumberContextConfiguration.java.ejs
generators/server/templates/src/test/java/package/cucumber/stepdefs/CucumberContextConfiguration.java.ejs
test/utils/expected-files.js

Cucumber no longer allows multiple classes to configure the Spring context
see https://github.com/cucumber/cucumber-jvm/issues/1420
Fix #9043

ensure only one glue class configures the Spring context

---

generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs

Liquibase - fix floatType for mariadb

---

generators/server/templates/src/main/docker/elasticsearch.yml.ejs
test-integration/scripts/20-no-memory-limit-elasticsearch.sh

So the real problem seemed to be at `test-integration/scripts/20-no-memory-limit-elasticsearch.sh` which was commenting out `environment` and the fact that `discovery.type` was moved out of `commands` group and within `environment`.

Fix elastic docker compose error for azure ci

---

generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIntTest.java.ejs

I stumbled on this one while doing the Kotlin entity generator where the Kotlin compiler does not allow duplicate imports. Its a minor improvement as the Java compiler does not complain.

EntityResourceIntTest - Avoid duplicate imports of relationship domain classes

---

generators/client/templates/angular/src/main/webapp/app/account/password/password.component.html.ejs
generators/client/templates/angular/src/main/webapp/app/account/sessions/sessions.component.html.ejs
generators/client/templates/angular/src/main/webapp/app/account/settings/settings.component.html.ejs
generators/client/templates/angular/src/main/webapp/app/admin/logs/logs.component.html.ejs
generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management-delete-dialog.component.html.ejs
generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management-update.component.html.ejs
generators/client/templates/angular/src/main/webapp/app/home/home.component.html.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-delete-dialog.component.html.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.html.ejs
generators/generator-base.js

In order to start fixing #9048, I need to have proper objects sent as parameter and not as strings.
So i use the `[ ]` notation to send object in the `jhiTranslate` directive.
This needs https://github.com/jhipster/ng-jhipster/pull/87  to be merged before.

angular: send objects instead of strings

---

generators/server/templates/src/test/java/package/web/rest/AccountResourceIntTest.java.ejs

- Fix `AccountResourceIntTest.testChangePasswordEmpty()` to pass a `PasswordChangeDTO` instead of a `String`
- Change `AccountResourceIntTest.testChangePasswordTooSmall()` and `AccountResourceIntTest.testChangePasswordTooLong()` to use the MIN and MAX constants for generating the passwords and introduced variable for new password to improve code readability

Fix AccountResourceIntTest.testChangePasswordEmpty() to pass a PasswordChangeDTO

---

generators/client/templates/angular/src/main/webapp/app/core/login/login.service.ts.ejs
generators/client/templates/angular/webpack/webpack.dev.js.ejs
generators/client/templates/react/src/main/webapp/app/shared/util/url-utils.ts.ejs
generators/client/templates/react/webpack/webpack.dev.js.ejs

The `webpack proxy` is really useful for frontend dev only. We can test and debug the frontend without to build it again and deploy it again. We can simply do a `yarn start` or `npm start`. of cause, we need to setup the proxy in the `webpack.dev.js`.
when we create a a new gateway microserivce with oauth2. it will have some issue with the `webpack proxy`.
> case 1:  we generate the gateway with 8080 port, we build the image, and run container with a 8080:8080 port mapping. we can do easily do a `yarn start` (or `npm start`) for frontend dev only. 
> case 2: we generate the gateway with 8080 port, we build the image, and run the container with 8081:8080 port mapping,  the `yarn start`(or `npm start`) **will not work**. 
> case 3: we generate the gateway with 8080 port, we build the image, …

enhancement for using webpack proxy via oauth

---

generators/server/index.js
generators/server/templates/build.gradle.ejs
generators/server/templates/gradle/profile_dev.gradle.ejs
generators/server/templates/gradle/profile_prod.gradle.ejs

- Define separate logic for the creation of SpringBoot `buildInfo` for the dev and pro profiles. For prod it remains the same but for dev we do not generate a build timestamp as it is not really needed and it triggers constant re-compilation, etc. Also removed clean of resources as it is not needed and always triggers a full re-build regardless if anything has changed or not
- Fix duplicate war creation. The `bootWar` task is actually extending the `war` task hence defining it again and with a separate name was causing the duplication. Removed tasks for renaming and deleting the war file as they are no longer necessary
- Fix the `webpackBuildDev` task to execute `npm install` only when needed. Moved the dependency within the task and now also checking for changes of the webpack config …

Speed up gradle build

---

generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.module.ts.ejs
test/entity.spec.js

This exported name must match the name set [in the lazy-loaded entity module needle](https://github.com/jhipster/generator-jhipster/blob/55f76b4a656cac7592534080f2aed6add73b000e/generators/generator-base.js#L297-L299).  This only affects Angular Microservice entities since it uses a different module name in that case.

fix exported entity module class name

---

generators/client/templates/angular/src/main/webapp/app/core/auth/auth-session.service.ts.ejs
generators/client/templates/react/src/main/webapp/app/shared/reducers/authentication.ts.ejs
generators/entity-server/templates/src/test/gatling/user-files/simulations/EntityGatlingTest.scala.ejs
generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs

Because:
* [Policy 1](https://www.jhipster.tech/policies/)
* The reactive version currently doesn't support custom param names

Use Spring security default auth form param names

---

generators/client/templates/angular/package.json.ejs

Due to https://github.com/jhipster/ng-jhipster/pull/84
We need to add ngx-translate dependencies in order to have a working JHipster app.
It wasn't a good practice to embed some dependencies in our lib as it can result into duplicated dependencies versions if our end users install ngx-translate on their JHipster app.
cf: https://github.com/ng-packagr/ng-packagr/blob/master/docs/dependencies.md
**Warning:** Please wait the 0.7.0 (or 1.0) version of `ng-jhipster` to be available before merging this.
-   [ ] Coding Rules & Commit …

angular: add ngx-translate as dependency

---

generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics.component.html.ejs

The endpoint returns json with metrics.services instead of metrics.endpoints.
With this little change, the endpoint requests are displayed properly

Fix display of endpoints requests in new metrics implementation in Angular

---

generators/client/templates/angular/src/main/webapp/app/layouts/main/main.component.ts.ejs

Fix #8801
There's still a blank page when you go to non-existant entities, such as http://localhost:8080/foo/3/view when you only have one Foo entity.  I didn't want to force any HTTP 404 to send to `/404` since a developer may be integrating an external API, so I handled the NavigationError that is thrown.

handle 404 errors for angular entities

---

generators/client/templates/react/src/main/webapp/app/modules/administration/metrics/metrics.tsx.ejs

```json
{
"jvm": {
"PS Eden Space": {
"committed": 664272896,
"max": 664272896,
"used": 50715328
},
"Code Cache": {
"committed": 13238272,
"max": 251658240,
"used": 13201664
},
"Compressed Class Space": {
"committed": 10665984,
"max": 1073741824,
"used": 9928464
},
"PS Survivor Space": {
"committed": 22544384,
"max": 22544384,
"used": 22225336
},
"PS Old Gen": {
"committed": 105381888,
"max": 1431830528,
"used": 37493560
},
"Metaspace": {
"committed": 73818112,
"max": -1,
"used": 69989576
}
},
"databases": {},
"http.server.requests": {
"all": {
"count": 7
},
"percode": {
"200": {
"max": 0,
"mean": 262.8261046,
"count": 5
},
"401": {
"max": 0,
"mean": 60.9113105,
"count": 2
}
}
},
"cache": {},
"garbageCollector": {
"jvm.gc.max.data.size": 1431830528,
"jvm.gc.pause": {
"0.0": 0,
"1.0": 0, …
```

fix: mongo return empty databases object

---

generators/internal/needle-api/needle-client-angular.js

In the angular needle Api we are calling a this.stripMargin() method that does not exist. 'stripMargin()' belongs to generator-base.js so I changed it to this.generator.stripMargin().
@murdos 
I don't use to handle maintenance branch with JHipster. I open a new PR and close the other one. I hope this is what you wanted me to do ;).

Fix call to the wrong stripMargin method

---

generators/client/templates/angular/package.json.ejs
generators/client/templates/react/package.json.ejs

This reverts commit 11594152ff54275bec7427e54c4b558efed16444.
I'm reverting my previous PR as it is already fixed by terser project: https://github.com/terser-js/terser/releases
@DanielFran : so, no need to report this fix in v5 maintenance branch
_____

Revert "Use fixed dependency: terser 3.14.1"

---

generators/server/templates/gradle/profile_dev.gradle.ejs

Use underscore syntax to run `npm install` and `yarn install` as documented in https://github.com/srs/gradle-node-plugin/blob/master/docs/node.md.

use underscore syntax to access command

---

generators/generator-transforms.js

We need to always call callback(null, file) otherwise the program
is stopped prematurely
My first fix was not totally good because this could stop the program before it was really finished.
The callback is not called and the generator finish like this, before handling all files: 
>     force src/main/webapp/app/admin/configuration/configuration.component.ts
>     force src/main/webapp/app/admin/configuration/configuration.service.ts
>     force src/main/webapp/app/admin/docs/docs.route.ts
>     force src/main/webapp/app/admin/docs/docs.component.ts
>     force src/main/webapp/app/admin/health/health.route.ts
>     force src/main/webapp/app/admin/health/health.component.ts
>     force src/main/webapp/app/admin/health/health-modal.component.ts
>     force …

Update condition when applying prettierTransform

---

generators/server/templates/build.gradle.ejs
generators/server/templates/gradle/docker.gradle.ejs
generators/server/templates/gradle/profile_dev.gradle.ejs
generators/server/templates/gradle/profile_prod.gradle.ejs
generators/server/templates/gradle/sonar.gradle.ejs

Cleanup how we apply gradle plugins. Whenever possible we use the new plugin syntax (as we always apply the plugin). All plugin/script applications are at one place.
* Open Api plugin is apllied as buildscript, as the plugin is not yet in the plugin portal
* Same for propdeps plugin
* To support variable replacement (`${spring_boot_version}`) the boot plugin is also added in the buildscript block and applied afterwards
This is no breaking change, but I used this to prepare gradle 5 for v6 already, therefore I put the v6 label. …

clean up gradle plugin application

---

README.md

As discussed with @deepu105 here https://github.com/jhipster/jhipster-vuejs/pull/288, this badge show downloads per month on npm.

Add npm charts badge to README

---

.travis.yml
generators/aws/USAGE
generators/aws/index.js
generators/aws/lib/eb.js
generators/aws/lib/s3.js
generators/ci-cd/templates/.gitlab-ci.yml.ejs
generators/ci-cd/templates/azure-pipelines.yml.ejs
generators/ci-cd/templates/circle.yml.ejs
generators/ci-cd/templates/jenkins/Jenkinsfile.ejs
generators/ci-cd/templates/travis.yml.ejs
generators/cloudfoundry/index.js
generators/common/templates/README.md.ejs
generators/docker-base.js
generators/gae/USAGE
generators/generator-base.js
generators/heroku/USAGE
generators/heroku/index.js
generators/heroku/templates/Procfile.ejs
generators/heroku/templates/heroku.gradle.ejs
generators/heroku/templates/pom-profile.xml.ejs
generators/server/templates/build.gradle.ejs
generators/server/templates/pom.xml.ejs
generators/server/templates/src/main/resources/config/application-prod.yml.ejs
generators/server/templates/src/main/resources/config/application.yml.ejs
generators/server/templates/src/main/resources/config/bootstrap.yml.ejs
test-integration/scripts/23-package.sh
test-integration/scripts/24-tests-e2e.sh

This needs review and a lot of testing to make sure it works for every case.
In order to build the war, you can run:
`./mvnw -Pprod,war verify`
In my testing, running the produced war file in tomcat and deploying to GAE worked well.

Change the packaging to jar and configure a war profile

---

generators/client/templates/angular/webpack/webpack.dev.js.ejs
generators/client/templates/react/webpack/webpack.dev.js.ejs
generators/docker-compose/index.js
generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs
generators/server/templates/src/main/docker/config/realm-config/jhipster-realm.json.ejs

Fix #9086 
I tried to test these patches, but didn't manage to generate a correct `jhipster-realm.json` with `"redirectUris": ["http://localhost:8080/*", "https://localhost:8080/*"` (I don't have the second url in the generated app).
But I'm not sure if I'm doing `npm link` correctly... could somebody check if this really fixes #9086 please?

fixes #9086 'Wrong login URL when using OAuth2 and TLS'

---

generators/cleanup.js
generators/entity-server/files.js
generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
generators/server/files.js
generators/server/templates/build.gradle.ejs
generators/server/templates/pom.xml.ejs
generators/server/templates/src/test/java/package/CassandraKeyspaceIT.java.ejs
generators/server/templates/src/test/java/package/config/CassandraConfigurationIT.java.ejs
generators/server/templates/src/test/java/package/config/DatabaseConfigurationIT.java.ejs
generators/server/templates/src/test/java/package/config/timezone/HibernateTimeZoneIT.java.ejs
generators/server/templates/src/test/java/package/cucumber/CucumberIT.java.ejs
generators/server/templates/src/test/java/package/repository/CustomAuditEventRepositoryIT.java.ejs
generators/server/templates/src/test/java/package/security/DomainUserDetailsServiceIT.java.ejs
generators/server/templates/src/test/java/package/service/MailServiceIT.java.ejs
generators/server/templates/src/test/java/package/service/UserServiceIT.java.ejs
generators/server/templates/src/test/java/package/service/mapper/UserMapperIT.java.ejs
generators/server/templates/src/test/java/package/web/rest/AccountResourceIT.java.ejs
generators/server/templates/src/test/java/package/web/rest/AuditResourceIT.java.ejs
generators/server/templates/src/test/java/package/web/rest/LogoutResourceIT.java.ejs
generators/server/templates/src/test/java/package/web/rest/LogsResourceIT.java.ejs
generators/server/templates/src/test/java/package/web/rest/UserJWTControllerIT.java.ejs
generators/server/templates/src/test/java/package/web/rest/UserResourceIT.java.ejs
generators/server/templates/src/test/java/package/web/rest/errors/ExceptionTranslatorIT.java.ejs
generators/spring-controller/index.js
generators/spring-controller/templates/src/test/java/package/web/rest/ResourceIT.java.ejs
test/spring-controller.spec.js
test/utils/expected-files.js

currently JHipster mix unit tests and integration tests, this change allows to run unit test via `mvn test` and unit+integration via `mvn verify`
Fixes #8868
Currently in WIP until all discussions are resolved in #8868

rename Integration tests to *IT.java

---

generators/client/templates/angular/webpack/webpack.dev.js.ejs
generators/client/templates/react/webpack/webpack.common.js.ejs

Closed https://github.com/jhipster/generator-jhipster/pull/9270 and opened a new PR here with a new commit SHA to trigger fresh CI builds

Add note about `require('os').cpus()` inaccuracy in some CI environments

---

generators/server/templates/src/main/resources/config/application.yml.ejs
generators/server/templates/src/test/resources/config/application.yml.ejs

The following PR fixes issue reported by @cbornet at https://github.com/jhipster/generator-jhipster/pull/9283#issuecomment-465360644 caused by merge of #9283 
It contains the following changes:
- Add missing `jhipster.clientApp.name` to `application.yml` used for tests.
- Enclose `jhipster.clientApp.name` within double quotes

Add missing jhipster.clientApp.name to application.yml used for tests.

---

generators/app/index.js
generators/client/index.js
generators/common/index.js
generators/entity-client/index.js
generators/entity-i18n/index.js
generators/entity-server/index.js
generators/entity/index.js
generators/generator-base-private.js
generators/generator-base.js
generators/languages/index.js
generators/server/index.js
generators/spring-controller/index.js
generators/spring-service/index.js
test/blueprint/app-blueprint.spec.js
test/blueprint/entity-blueprint.spec.js
test/blueprint/spring-controller-blueprint.spec.js
test/blueprint/spring-service-blueprint.spec.js
test/utils/utils.js

This PR contains the following fixes:
1. Fix to not check for blueprint existence when `skipChecks` is true to allow for running mocha tests in blueprints as well, even if the npm module is no linked 
2. Fix to pass `options` and `configOptions` to blueprint generators and sub-generators
3. Add mocha tests for `spring-controller` and `service-blueprints` generators
I have tested(meaning `npm test`) these changes in the generator and also with the Kotlin and VueJS blueprints
Relates to issue 1 of #9232 
-   [x] Coding Rules & …

Blueprint issues

---

generators/gae/index.js
package.json

Related to https://github.com/jhipster/generator-jhipster/commit/c7fb5c6108487be127c4e8da4b05625e521bd06c#r32293602 and fix https://github.com/jhipster/generator-jhipster/issues/9290
With this change:
- if the code is not well formated, the `npm test` will fail :
```
07:46:08 in projects/jhipster/generator-jhipster on  master [⇡!] 
➜ npm test
> generator-jhipster@5.8.1 pretest /home/pgrimaud/projects/jhipster/generator-jhipster
> npm run lint
> generator-jhipster@5.8.1 lint /home/pgrimaud/projects/jhipster/generator-jhipster
> npm run eslint && npm run ejs-lint
> generator-jhipster@5.8.1 eslint /home/pgrimaud/projects/jhipster/generator-jhipster
> eslint .
/home/pgrimaud/projects/jhipster/generator-jhipster/generators/gae/index.js
560:38   error  Insert `⏎···················` …
```

Apply npm lint before npm test

---

generators/generator-base.js
generators/internal/needle-api/index.js
test/needle-api/needle-client.spec.js

According to https://github.com/sudheerj/generator-jhipster-primeng/issues/67 the needle API PR broke compatibility. I would like to handle needleApi construction in the generator-base constructor but it seems not working since module not always extend directly the generator-base.
To fix that I suggest to add a needleApi getter which initialise the variable if needed.
Also when during my tests I found a bug  in the addExternalResourcesToRoot and I fix that too.
@sudheerj
Could you please test this PR for me and tell me if you always have the problem ?
If it's ok for you I will remove the WIP tag.
thanks you
Regards,
PS: need to be merged to master to
- …

[v5 maintenance] Fix needleApi injection, external resources public API and add unit tests

---

generators/internal/needle-api/needle-base.js
generators/internal/needle-api/needle-server-maven.js
test/needle-api/needle-client-i18n.spec.js
test/needle-api/needle-client-webpack.spec.js
test/needle-api/needle-server-cache.spec.js
test/needle-api/needle-server-gradle.spec.js
test/needle-api/needle-server-liquibase.spec.js
test/needle-api/needle-server-maven.spec.js
test/needle-api/templates/src/main/resources/config/liquibase/changelog/dummy_changelog.xml.ejs

same as #9254 but for v5 maintenance

[v5 maintenance] add needle api unit tests

---

generators/client/templates/angular/webpack/webpack.prod.js.ejs

Fix #9289
Copied the config from React's webpack.prod.js
SCSS works fine, there's a separate issue with css for Angular, the `main.*.css` file gives a 404.  This happens on master though so is unrelated to this.  I can open a separate issue tomorrow.

fix angular prod css location for caching

---

generators/docker-base.js
generators/kubernetes/templates/deployment.yml.ejs
generators/openshift/templates/deployment.yml.ejs
generators/server/templates/src/main/docker/app.yml.ejs
generators/server/templates/src/main/resources/config/application-dev.yml.ejs
generators/server/templates/src/main/resources/config/application-prod.yml.ejs

Unlike servlet-based apps that queue requests when there's no thread available in the network pool (default 200 for Tomcat, 8*available cpus for undertow), Webflux will subscribe to a new reactive chain for each request without limit.
Each concurrent request will be queued waiting for a mongo connexion from the pool.
The default maxWaitQueueSize of the mongo driver is 500 so as soon as there are more than about 500 concurrent requests you get MongoWaitQueueFullException.
This PR increases a lot the mongo maxWaitQueueSize so it cannot be the limiting factor (at least for < 100000 concurrent connexions).
See https://github.com/spring-projects/spring-framework/issues/22332 for details.
-   [x] [Travis …

Increase mongo driver's waitQueueMultiple for reactive apps

---

test/needle-api/needle-client-angular.spec.js

As promise, here is the rest of the Angular needle api tests.
With this PR the needle API is totally tested.
Maybe this test suite can help you (about #9179) @wmarques and @afillatre especially this part :
```
this.addEntityToModule(
'entityInstance',
'entityClass',
'entityName',
'entityFolderName',
'entityFileName',
'entityUrl',
'angularX',
'microServiceName'
);
```
```
it('entity module contains the microservice object added by needle api', () => {
assert.fileContent(
`${CLIENT_MAIN_SRC_DIR}app/entities/entity.module.ts`,
'            {\n' +
"                path: 'entityUrl',\n" +
"                loadChildren: './entityFolderName/entityFileName.module#MicroServiceNameentityNameModule'\n" +
'            }'
);
});
```
we could call `this.addEntityToModule` twice and then test that …

Complete client Angular needle api unit tests

---

generators/client/templates/angular/package.json.ejs
generators/client/templates/react/package.json.ejs

Fix #9298 (Windows + Jest issue)  by upgrading Jest to v24.1.0
I cherrypicked @DanielFran's Angular dependency update from master (which had this change), upgraded React's Jest for on its own.
I can open another PR for master React, but I'll probably leave it for #9285

upgrade jest for v5.x

---

generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs
generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
generators/server/templates/src/main/java/package/web/rest/UserResource.java.ejs
generators/server/templates/src/test/java/package/web/rest/UserResourceIT.java.ejs

This is mentionned here https://github.com/jhipster/jhipster-vuejs/issues/180.
To be more consistent with good practices, we should return correct HTTP codes when using DELETE Request and thus use 204 instead of 200.

Prevent wrong http code on empty body response

---

.travis.yml
azure-pipelines.yml
generators/client/templates/angular/package.json.ejs
generators/client/templates/react/package.json.ejs
generators/generator-base-private.js
generators/server/templates/src/main/docker/app.yml.ejs
generators/server/templates/src/main/docker/couchbase.yml.ejs
generators/server/templates/src/main/docker/kafka.yml.ejs
generators/server/templates/src/main/docker/keycloak.yml.ejs
generators/server/templates/src/main/resources/config/application-dev.yml.ejs
generators/server/templates/src/main/resources/config/application.yml.ejs
generators/server/templates/src/main/resources/swagger/api.yml.ejs
generators/server/templates/src/test/resources/config/application.yml.ejs
package-lock.json
package.json

Added formatting of YAML files to Prettier, formatted comments in YAML files so that they end up in the correct indentation and changed YAML files that are formatted with an indent of 2 space to 4
Fix #8805

Use Prettier to format YAML

---

generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
generators/server/templates/src/main/java/package/domain/Authority.java.ejs
generators/server/templates/src/main/java/package/domain/PersistentAuditEvent.java.ejs
generators/server/templates/src/main/java/package/domain/PersistentToken.java.ejs
generators/server/templates/src/main/java/package/domain/User.java.ejs

accept subclasses as parameter to equals to avoid problems with proxies, and provide consistent hashCode with database generated identifiers
fix #8656
this is the most reliable equals and hashCode implementation when using database generated identifiers with JPA and Hibernate (and still compatible with anything else).
As explained in https://vladmihalcea.com/the-best-way-to-implement-equals-hashcode-and-tostring-with-jpa-and-hibernate/, the constant hashCode provides consistency but can decrease performance when using huge sets and maps.
-   [ ] Documentation is added/updated where …

rewrite Entity equals and hashCode to fix #8656

---

generators/entity-server/templates/src/main/java/package/common/get_all_template.ejs
generators/entity-server/templates/src/main/java/package/common/search_template.ejs
generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs
generators/server/templates/src/main/java/package/web/rest/AuditResource.java.ejs
generators/server/templates/src/main/java/package/web/rest/UserResource.java.ejs
generators/server/templates/src/main/java/package/web/rest/util/PaginationUtil.java.ejs
generators/server/templates/src/test/java/package/web/rest/util/PaginationUtilUnitTest.java.ejs

Fix https://github.com/jhipster/generator-jhipster/issues/9194
1. Created universal single method PaginationUtil.generatePaginationHttpHeaders(HttpServletRequest request, Page<T> page). HttpServletRequest need for get URI and query params.
2. Tests adapted for new method calls. Assets not changed.
3. New test for sort and criteria params
4. Change templates for new call
5. Previous methods marks as deprecated.

#9194 Fix paging link headers for use all query parameters.

---

generators/entity-server/templates/src/test/gatling/user-files/simulations/EntityGatlingTest.scala.ejs

The generated gatling scripts are now compatible with gatling 3. I will update the documentation accordingly and how to call gatling. This is a breaking change as the scripts won't work with gatling 2.x anymore.
Tested with jwt and oauth. Will do it for session auth later, but I don't see why that should not work.
closes #9080

update gatling scripts to be compatible with gatling 3.x

---

package-lock.json
package.json

After release of 5.8.2 we need to bump the version in master as well otherwise `npm test` fails for the upgrade sub-gen.

Bump version to 5.8.2

---

generators/client/templates/angular/src/main/webapp/app/core/login/login.service.ts.ejs

Fix #9349
Session auth makes a logout request, then requests the account.  It needs to wait for the logout request to finish before requesting the account, or the home page and navbar show as if the user is logged in.  This causes the Protractor test to fail because it looks for the "Login" link.

complete the logout request before fetching account

---

generators/client/templates/angular/webpack/webpack.common.js.ejs

This reverts commit 8115e8cb as it was meant to make upgrade of `ngx-cookie` work in #9354 . Since `ngx-cookie` was been reverted back to 4.0.2 this is no longer needed and I forgot to revert it.

Revert "Use Webpack IgnorePlugin to ignore @nguniversal/express-engine"

---

generators/generator-base.js
generators/server/needle-api/needle-server-gradle.js
generators/server/templates/build.gradle.ejs
generators/server/templates/gradle/profile_dev.gradle.ejs
test/needle-api/needle-server-gradle.spec.js

Gradle 5 now supports [Maven BOMs natively](https://docs.gradle.org/current/userguide/upgrading_version_4.html#rel5.0:bom_import)
The following changes have been made which **break** compatibility:
1. Switch to Gradle 5 native BOM support and remove `io.spring.dependency-management` plugin
2. Remove method `addGradleDependencyManagement() ` as the `dependencyManagement` block is no longer available. Code can use the [Gradle's native BOM support instead](https://docs.gradle.org/5.0/userguide/managing_transitive_dependencies.html#sec:bom_import)
Relates to  #9081 
-   [x] Documentation is …

Use Gradle 5 native BOM support

---

generators/server/templates/pom.xml.ejs

Remove extra arg lines arguments used for surefire and failsafe and use only `argLine` as a property.
`argLine` is automatically picked up by all three plugins:
`maven-surefire-plugin`, `maven-failsafe-plugin` and `jacoco-maven-plugin`
See also https://www.eclemma.org/jacoco/trunk/doc/prepare-agent-mojo.html
I have tested it with IDEA and command line and it works and generates proper sonar reports at least locally.
Fixes #9393  …

Remove extra arg lines arguments used for surefire and failsafe and

---

generators/server/templates/build.gradle.ejs

The correct configuration for the BOM is 'platform' in order to allow for version overriding.
This is needed at least in the Kotlin blueprint where Kotlin version used is different from the one declared by Spring Boot and probably will be a problem for other users as well who want to override versions manually.
The distinction is clear in the [documentation](https://docs.gradle.org/5.0/userguide/managing_transitive_dependencies.html#sec:bom_import) but I misunderstood it when implementing the Gradle native BOM support at #9385  
- …

Change configuration of BOM import to platform to allow version overriding

---

generators/server/templates/build.gradle.ejs
generators/server/templates/gradle/profile_dev.gradle.ejs
generators/server/templates/gradle/profile_prod.gradle.ejs

As discussed in #9081 this PR switches the gradle plugin used for client tasks to https://github.com/node-gradle/gradle-node-plugin which is more active than the one currently used.
It also contains a fix to avoid constantly re-running webpack when nothing has changed.
**NOTE:** This PR is based on the branches of #9385 and #9388 to avoid conflicts, hence they should be merge first. Will do a rebase if needed. …

Switch gradle node plugin and fix webpackBuildDev task to not execute if no client file has changed

---

generators/generator-base.js
test/needle-api/needle-client-react.spec.js

related to #9234
When I added the needle API I figured out that we did not have a working public API for React. I added a needle API for both React and Angular but only Angular had a Public API.
First I thought doing this PR on demand only but since we have a needle api and unit tests added method in public API seems to be very easy and takes no times.
I added 2 methods for both React CSS and SCSS case. Updated the unit tests to test public API instead of needle API.
With this addition people will be able to add their own style even if they have a react application.
-   [x] …

Add react SCSS needle public API

---

generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.html.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.ts.ejs
generators/entity-client/templates/angular/src/test/javascript/spec/app/entities/entity-management.service.spec.ts.ejs
generators/entity-server/templates/src/main/resources/config/liquibase/data/table.csv.ejs

- entity form should use relationshipFieldNamePlural for many-to-many relationships to match the entity fields to the form fields
- mapping form data to entity can't use model constructor as some fields should not be sent in request but are in the constructor (such as `many-to-one` relations) 
- faker data can only have a max userId of 2 (oauth doesn't have > 2)
Fix #9347
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are …

several relationship fixes for Angular forms

---

generators/server/templates/src/test/java/package/cucumber/CucumberContextConfiguration.java.ejs
generators/server/templates/src/test/java/package/cucumber/CucumberIT.java.ejs

This fixes the failing integration tests for Cucumber in the `ngx-mongodb-kafka-cucumber` sample.
Example logs: also https://travis-ci.org/jhipster/generator-jhipster/jobs/503656883

Fix Cucumber tests to use @DirtiesContext to have a clean context for each scenario

---

Dockerfile

Need to update the base container from ubuntu:bionic to ubuntu:cosmic. The open jdk in ubuntu-bionic is in fact a jdk 10.
See https://github.com/jhipster/generator-jhipster/issues/9145

Update jdk version in docker image to openjdk-11

---

generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management.component.ts.ejs
generators/client/templates/angular/tsconfig-aot.json.ejs
generators/client/templates/angular/tsconfig.json.ejs
generators/client/templates/angular/webpack/webpack.prod.js.ejs
generators/client/templates/react/tsconfig.json.ejs
generators/client/templates/react/webpack/webpack.prod.js.ejs

Considering evergreen browsers support almost all ES6 features, we should enable it as default (reference: https://kangax.github.io/compat-table/es6/). It will reduce bundle size by few KiB.

Change ts compilation target to es6 as default

---

generators/client/templates/react/package.json.ejs

React Router Dom uses `^` to specify the React Router version, so it pulls in v4.4.0 even though we are using v4.3.1.
This should also be cherry-picked to the v5 maintenance branch.
Fix #9438
Fix #9436

pin react-router version to v4.3.1 to fix transitive deps

---

generators/server/templates/build.gradle.ejs

Just add the workaround mentioned in gradle forum/example. Linking to the repository in the build file. Of course a user should use e.g. a project property in order not to hard code credentials in the build file.
Closes #8731

add workaround for oracle maven repo. 

---

generators/server/templates/gradle/profile_dev.gradle.ejs
generators/server/templates/gradle/profile_prod.gradle.ejs

This PR contains the following fixes
1. Switched back to the synthetic tasks, i.e `npm_install` and `yarn_install` as there is no `yarnInstall` task.
2. Fix input file for yarn is `yarn.lock`
Fixes #9451

Fix install task and lock file used for yarn

---

generators/server/needle-api/needle-server-cache.js
generators/server/templates/src/main/java/package/config/CacheConfiguration.java.ejs
generators/server/templates/src/test/java/package/cucumber/CucumberContextConfiguration.java.ejs
test/needle-api/needle-server-cache.spec.js

This PR reverts #9404 and instead uses a different approach where it first deletes a previously configured cache with the same name if it already exists before trying to create it.
Usage of '@DirtiesContext' creates other issues when using Infinispan instead of EhCache as mentioned by @pascalgrimaud in comment https://github.com/jhipster/generator-jhipster/pull/9404#issuecomment-475850157 and can bee seen at https://dev.azure.com/hipster-labs/jhipster-daily-builds/_build/results?buildId=1721.
**NOTE:** I have chosen to delete previous cache instead of ignoring creation as in theory the `jcacheConfiguration` could be different, although under normal circumstances the `CacheConfiguration ` is a singleton and would only be instantiated once hence the `JCacheManagerCustomizer` only created …

Change EhCache creation logic to fix Cucumber test failures

---

.vscode/launch.json

Debug scripts target 'travis' folder instead of the 'test-integration' one

Fix `cwd` values for vscode debug launch.json

---

generators/server/templates/gradle/profile_dev.gradle.ejs

Fix Gradle `webpackBuildDev` task to not fail when either `package-lock.json` or `yarn.lock` is missing when using either npm or  yarn respectively.
When using `inputs.file(file)` and the referenced file is missing then gradle will throw an error and fail. Instead when using `inputs.files(file)`(mind the s) gradle considers it as a collection of paths and if any is missing it is simply ignored. We should not fail when the `package-lock.json` is missing but instead continue to execute `npm install` when `./gradlew` is executed.
This is another regression after merging #9389.
-   [] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] …

Fix gradle webpackBuildDev task to not fail when package-lock.json or `yarn.lock is missing

---

generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.html.ejs
generators/entity-client/templates/angular/src/test/javascript/e2e/entities/entity.spec.ts.ejs
generators/entity-client/templates/angular/src/test/javascript/spec/app/entities/entity-management.service.spec.ts.ejs
generators/entity-client/templates/react/src/test/javascript/e2e/entities/entity.spec.ts.ejs
generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
generators/entity-server/templates/src/main/java/package/service/dto/EntityCriteria.java.ejs
generators/entity-server/templates/src/main/java/package/service/dto/EntityDTO.java.ejs
generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs
generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
generators/entity/index.js
generators/entity/prompts.js
generators/generator-base-private.js
generators/server/templates/src/main/java/package/config/CloudDatabaseConfiguration.java.ejs
test-integration/samples/.jhipster/BankAccount.json
test-integration/samples/.jhipster/FieldTestEntity.json

use the duration to long converter instance
treat Duration as a number client-side
add a Duration field to the base test
add a missing import
consider the Duration field in the search criteria
Fix #9095

#9095: Support for java.time.Duration

---

generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management-delete-dialog.component.ts.ejs
generators/client/templates/angular/src/test/javascript/spec/app/admin/user-management/user-management-delete-dialog.component.spec.ts.ejs
generators/client/templates/angular/src/test/javascript/spec/helpers/mock-active-modal.service.ts.ejs

change action of the modal when confirmation on user
delete is provided
Fix #9421

change action from `dismiss` to `close`

---

generators/server/templates/build.gradle.ejs

make eclipse remember the generated source folder

---

generators/server/templates/src/main/resources/config/application.yml.ejs

This fixes gateway routes for consul microservices with uppercase in their names
fix #9435

Force lowercase for consul microservice application names

---

generators/server/templates/src/main/resources/config/application.yml.ejs

Some of the metrics properties were depracated in the new versions of Spring Boot/Micrometer. I changed the configuration to reflect these changes.
Every metrics is enabled by default : these properties are here just to let the user know he can disable them

fix deprecated metrics properties

---

generators/client/files-angular.js
generators/client/templates/angular/src/main/webapp/app/core/login/login.service.ts.ejs
generators/client/templates/angular/src/main/webapp/app/layouts/main/main.component.ts.ejs
generators/client/templates/angular/src/main/webapp/app/shared/login/login.component.ts.ejs
generators/client/templates/angular/src/test/javascript/spec/app/layouts/main/main.component.spec.ts.ejs
generators/client/templates/angular/src/test/javascript/spec/app/shared/login/login.component.spec.ts.ejs
generators/client/templates/angular/src/test/javascript/spec/helpers/mock-account.service.ts.ejs
generators/client/templates/angular/src/test/javascript/spec/helpers/mock-route.service.ts.ejs

- Closes #9446 
- Fix redirection issue to the `/login` resource if you directly try to access protected view.
- Correctly navigate to stored url in `jwt`/`uaa` flow.

oauth2: navigate to stored url post successful authentication

---

generators/server/templates/pom.xml.ejs

When using `mvn liquibase:update` to update database schema with latest changes then the test table `jhi_date_time_wrapper` pop up in our database. By default we do not want this, but one could override this settings in command line if needed :)

chore: avoid include test tables in liquibase

---

generators/common/templates/README.md.ejs
test-integration/scripts/25-sonar-analyze.sh

Fix the test-integrations scripts for sonar analysis.
With the properties maven plugin we need to have, at least, an initialize phase to load sonar-project.properties.
related to #9423

Add initialize phase when call sonar:sonar

---

generators/server/files.js
generators/server/index.js
generators/server/templates/src/main/docker/grafana/provisioning/dashboards/JVM.json.ejs
generators/server/templates/src/main/docker/grafana/provisioning/dashboards/dashboard.yml.ejs
generators/server/templates/src/main/docker/grafana/provisioning/datasources/datasource.yml.ejs
generators/server/templates/src/main/docker/monitoring.yml.ejs
generators/server/templates/src/main/docker/prometheus/prometheus.yml.ejs

Create by default some Docker Compose files for using Prometheus and Grafana to monitor your applications, with an autoconfigured default dashboard in Grafana.
For the moment in this PR, Prometheus listen for instances on : 
- localhost:8080
- localhost:8081
- localhost:8082
- localhost:8083
I'm not sure if it's ok ?
-   [] Documentation is added/updated where necessary

Add default docker-compose files for Prometheus and Grafana

---

.travis.yml
generators/server/templates/pom.xml.ejs

Change travis image to java. This makes building with multiple jdks easier. The travis java image comes with nvm. The node version can be set with nvm in "before_install". Install node version via nvm and remove node_js key in travis.yml.
See https://github.com/jhipster/generator-jhipster/issues/9145

Multiple travis builds with jdk8 and jdk11

---

generators/client/templates/react/package.json.ejs

Updated `@types/react` to 16.8.10 and aligned versions in `devDependencies` and `resolutions`.
The misalignment of versions was causing yarn build to fail as reported by @pascalgrimaud in comment https://github.com/jhipster/generator-jhipster/pull/9444#issuecomment-477910992

Updated @types/react to 16.8.10 and aligned versions in devDependencies and resolutions

---

.travis.yml

The java version is still 1.8. Forget to set jdk11 as default.
The post from https://www.linuxuprising.com/2019/01/how-to-install-openjdk-11-in-ubuntu.html says: "After the installation, your Java version should now be 11:"
But this seems not to bee the case in travis.
Now it is set to jdk 11.
Follow up from: https://github.com/jhipster/generator-jhipster/pull/9410

use jdk 11 via update-java-alternatives

---

.travis.yml
azure-pipelines.yml

Following this PR https://github.com/jhipster/generator-jhipster/pull/9507 by @cremich
- Travis: use JDK8 by default, as downloading JDK11 is too long
- Azure: use JDK11 by default and add 1 build with JDK8
- switch jdl, infinispan builds to Azure
2 builds will fail, because of JDK11 :
- infinispan
- uaa

CI: update JDK8 / JDK11 builds

---

generators/cleanup.js

Menu components are now directly present under `layout/menus` directory

react: upgrade: remove menu components from layout/headers directory

---

generators/server/templates/build.gradle.ejs
generators/server/templates/gradle.properties.ejs
generators/server/templates/pom.xml.ejs

This PR fixes the problem of missing JAXB implementation at runtime when using JDK 11.
It includes the following changes:
- Dependency changed to [org.glassfish.jaxb:jaxb-runtime](https://search.maven.org/artifact/org.glassfish.jaxb/jaxb-runtime/2.3.2/jar) as is also recommended by the Spring team [here]( https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-with-Java-9-and-above#jaxb)
- The dependency is explicitly included when using UAA as authentication type as it is also required by `spring-security-oauth2` at runtime.
- Fix has been applied for both Maven and Gradle
Fix #9514 
-   [x] Tests are added where …

Change to jaxb-runtime and explicitly include it when using UAA

---

.travis.yml
Dockerfile
azure-pipelines.yml

Use SDKMAN to provision Open JDK 11 in Azure build
Fixes #9513 

Use SDKMan to provision Open JDK 11

---

generators/server/templates/src/main/docker/prometheus/prometheus.yml.ejs

Update prometheus metrics route if no service discovery is used with microservices or uaa

fix metrics_path in Prometheus configuration file (with Docker)

---

generators/client/templates/react/package.json.ejs

This PR restores usage of `resolutions` feature for yarn to avoid dep resolution problem for `@types/react`.
This was removed in https://github.com/jhipster/generator-jhipster/pull/9508/commits/abfe4175a5d9f88c7bd2e5aa29efd15214c84df1 but problem reappeared in https://dev.azure.com/hipster-labs/jhipster-daily-builds/_build/results?buildId=2176 as reported by @pascalgrimaud in comment https://github.com/jhipster/generator-jhipster/pull/9508#issuecomment-480573655.
I believe the problem is related to old dependencies of https://github.com/jhipster/react-jhipster and could be solved when https://github.com/jhipster/react-jhipster/issues/24 is implemented
-   [ ] [Travis …

Fix resolution problem for @types/react dep when using yarn

---

.editorconfig

The property `indent_style = space` is already defined in the parent `[*]` and could be removed in `[package.json]`.

Remove duplicated property in editorconfig file

---

.travis.yml
Dockerfile
azure-pipelines.yml

We discussed with @jdubois during our last JHipster day, and I think we should stick with a more classic installation of OpenJDK, instead of using SDKMAN.
@pvliss: do you agree with that ?
@PierreBesson : what do you think too ?
_____

Switch to OpenJDK11

---

generators/server/templates/gradle/swagger.gradle.ejs
generators/server/templates/pom.xml.ejs

Fixes #9555 by adding `title` property both in maven and gradle 

Add title configOption to openapi generator plugin

---

generators/client/templates/angular/tslint.json.ejs

Codelyzer rule `use-life-cycle-interface` has been renamed to `use-lifecycle-interface` at version [5.0.0
](https://github.com/mgechev/codelyzer/releases/tag/5.0.0)
There is an error emitted when building although it does not fail:
```
[INFO] > travis-psql-es-noi-18-n-maps-id-with-ngx@0.0.0 webpack /home/pav/Development/temp/jhipster-java/ngx-psql-es-noi18n-mapsid
[INFO] > node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "webpack/webpack.dev.js" "--env.stats=minimal"
[INFO] 
[INFO] Webpack: Starting ...
[INFO] Starting type checking service...
Webpack: Starting ...
[INFO] 
[INFO]    ✔ Compile modules
[INFO]    ❯ Build modules (33%)
[INFO]      → 5 of 7 modules :: src/main/webapp/app/app.main.ts ~ internal
[ERROR] 
[ERROR] Could not find implementations for the …
```

Fix Angular codelyzer rule name

---

generators/server/templates/gradle/docker.gradle.ejs
generators/server/templates/gradle/profile_dev.gradle.ejs
generators/server/templates/gradle/profile_prod.gradle.ejs
generators/server/templates/pom.xml.ejs

Pass proper JVM arguments to Spring Boot run in order to fix jgroups errors when using Infinispan
This PR fixes errors generated by JGroups when using Infinispan such as the following which is fired once at startup: 
```
019-03-31 19:41:22.839 DEBUG 7903 --- [  restartedMain] org.jgroups.stack.Configurator           : set property TCP.diagnostics_addr to default value /224.0.75.75
2019-03-31 19:41:22.844 DEBUG 7903 --- [  restartedMain] org.jgroups.protocols.TCP                : thread pool min/max/keep-alive: 0/200/60000 use_fork_join=false, internal pool: 0/8/30000 (8 cores available)
2019-03-31 19:41:22.849 DEBUG 7903 --- [  restartedMain] org.jgroups.protocols.MPING              : bind_addr=/127.0.0.1, mcast_addr=/228.2.4.6, mcast_port=43366
2019-03-31 19:41:22.861 DEBUG 7903 --- [ …
```

Pass proper JVM arguments to Spring Boot run in order to fix jgroups errors when using Infinispan

---

cli/commands.js
cli/utils.js
test/cli/cli.spec.js

Blueprints can easily modify main generator behavior, however, quickly grows the need to define custom subgenerator for specific tasks.
To ensure that possibility, this PR enables to define a subgenerator in a blueprint using a simple file formatted as such:
*generator-jhipster-testblueprint/commands.js*
```
module.exports = {
foo: {
desc: 'bar', // A little description that will be displayed using --help
blueprint: 'generator-jhipster-testblueprint' // This is required to determine the blueprint issuing the custom command
}
};
```
When using `jhipster foo --blueprint testblueprint`, the foo subgenerator from the blueprint will be called directly.
I'd like some reviews on this one, as on the feature itself as on the code. This will clearly enable users to define specific stuff on their …

Enable blueprint to define custom subgenerator

---

generators/client/templates/react/src/main/webapp/app/shared/reducers/authentication.ts.ejs
generators/client/templates/react/src/test/javascript/spec/app/shared/reducers/authentication.spec.ts.ejs

- Closes #9297 
~~I have also removed the dispatch to `getSession()` in logout action as I couldn't think about a reason to justify that. Post successful logout, that call should always fail with `401`. If anyone sees a valid reason to have that, I will be happy to add that back.~~

react: fix logout reducer to handle success logout event

---

cli/commands.js
test/cli/cli.spec.js

This finalize #9574 as it prevents generator to throw errors using blueprint.

Prevent error while looking for custom command within blueprint

---

generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs

The precision was changed from (10,2) to (21,2) in #9338, so the condition no longer matched.
Related to [this StackOverflow post](https://stackoverflow.com/questions/55787123/error-column-own-amount-is-of-type-numeric-but-expression-is-of-type-characte), I couldn't reproduce the error message myself but this should fix it.

fix decimal fake-data column type

---

generators/client/templates/angular/webpack/webpack.dev.js.ejs
generators/client/templates/react/webpack/webpack.dev.js.ejs

One should also update [the TLS documentation](/jhipster/jhipster.github.io/blob/master/pages/tls.md) in order to tell the developer to go to https://localhost:9000 instead http address

fixes #9529 "Can't use OAuth2 in dev with start-tls"

---

generators/server/templates/src/test/java/package/web/rest/AccountResourceIT.java.ejs

Emergency fix : my PR on skipUserManagement telescoped with the switch to JUnit5 and we don't have CI test on skipUserManagement option.

Fix skipUserManagement tests on monolith

---

generators/server/templates/build.gradle.ejs

Two changes here:
* Use junit platform otherwise no tests are executed
* log skipped and failed test to the console (find it helpful)
Is/can cucumber also run with junit platform? If yes we need to add it for that too. 

use junit platform

---

generators/client/templates/angular/package.json.ejs
generators/client/templates/react/package.json.ejs

This fix was used for our samples at Okta. For example, in https://github.com/okta/samples-js-angular/pull/31.

Fix Protractor by pinning Selenium version to 3.14

---

generators/client/templates/angular/src/main/webapp/app/admin/admin.module.ts.ejs

There also was the no-prettier comment that could have been used or maybe changing the addToAdminModule method in needle-client-angular.js, but this was a simple solution
Fixes [#9656](https://github.com/jhipster/generator-jhipster/issues/9656).
I am still learning how to program the sub-generators, so I am still trying to make a test that will check the bug.

Changing the needle position fixed the bug

---

generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
generators/server/templates/src/test/java/package/web/rest/TestUtil.java.ejs
test-integration/samples/jdl-default/app.jdl

Checks if a required entity is already created in the createEntity method,
adds the creatUpdatedEntity using the UPDATED_ constants and
adds the findAll method to TestUtils.
Fix #9666

generated java tests now passes with unique validation

---

test/app.spec.js

The file `gradle/yeoman.gradle` is no longer generated since we moved from bower to webpack. So the test about this file can be removed.
@jdubois I noticed a strange thing about the automatic project update process. The `yeoman.gradle` file is still present in the [jhipster-sample-app-gradle repo](https://github.com/jhipster/jhipster-sample-app-gradle/tree/master/gradle).  
Why does this file have not been removed. I don't know properly the process for the update of all github repos.
-   [ ] Coding Rules & Commit Guidelines as …

Remove old test about yeoman

---

generators/client/templates/angular/webpack/webpack.prod.js.ejs

I think this was a small typo leftover from the webpack upgrade, but source maps aren't being generated the way it is now

Fix source map generation for webpack prod

---

generators/entity-server/templates/src/main/java/package/repository/EntityRepository.java.ejs

Use principal.preferredUsername instead of principal.username
Fix #9696

Change findByUserIsCurrentUser for OAuth2 apps

---

generators/client/templates/angular/webpack/webpack.common.js.ejs
generators/client/templates/angular/webpack/webpack.prod.js.ejs

Fix #9714 
With lazy loading I don't think it's useful to externalize the dependencies in a vendor chunk.

angular: remove vendors chunk

---

generators/client/templates/angular/src/main/webapp/app/shared/alert/alert-error.component.ts.ejs
generators/client/templates/angular/src/main/webapp/app/shared/alert/alert.component.ts.ejs
generators/client/templates/angular/src/main/webapp/content/scss/global.scss.ejs

Fix #9447 
It was due to a conflict with Bootstrap v4 which add a `toast` class. So I renamed our `toast` class into `jhi-toast` to avoid conflicts with Bootstrap class.

angular: fix toast alert

---

generators/server/templates/build.gradle.ejs
generators/server/templates/gradle.properties.ejs
generators/server/templates/pom.xml.ejs

Update JHipster dependencies
According to : https://github.com/jhipster/generator-jhipster/commit/96f524baa230b18762e4fec37120fb75cb26f085
We need a new snapshot release for JHipster dependencies. @jdubois could you please do that?
Thanks

Update JHipster dependencies to 3.0.2-SNAPSHOT

---

generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs
generators/entity-server/templates/src/main/resources/config/liquibase/data/table.csv.ejs

With PR #9704, the issue was fixed but data was not loaded as expected.
Now importing and displaying the textblob data correctly.

Fix syntax error and remove unnecessary variable

---

generators/server/templates/gradle/sonar.gradle.ejs

When looking into https://github.com/jhipster/generator-jhipster/issues/9631 I found that the jacoco report (html/xml) is not generated for all test tasks. With this change the report is generated for e.g. test and integration test.

generate jacoco report for all test tasks

---

test-integration/scripts/21-tests-backend.sh
test-integration/scripts/23-package.sh
test-integration/scripts/25-sonar-analyze.sh

Related to #7785.
Maven has now an option to suppress the transfer progress when downloading/uploading in interactive mode.
This is only for automated tests for main generator. Not for generated project.
See more at https://maven.apache.org/docs/3.6.1/release-notes.html

Add option to suppress the transfer progress for maven download

---

generators/server/templates/pom.xml.ejs

JAXB runtime must always be present in maven-compiler-plugin config when using JPA
Fix #9788

JAXB runtime must always be present in maven-compiler-plugin config when using JPA

---

generators/server/templates/src/main/docker/config/realm-config/jhipster-realm.json.ejs

For instance, I use swagger-ui watcher to do hot reload of swagger-ui and which is served on localhost:8000.
This shouldn't be a security issue since the docker config shall only be used in dev (you would have other security issues in prod such as the secret being known)

Allow all redirect URIs and CORS origin for keycloak

---

cli/utils.js

Closes #9782 
Refactored the command suggestion logic such that it suggests matching commands as intended. 

Refactor command suggestion logic

---

generators/server/templates/src/main/resources/config/application.yml.ejs

Health details might contain some sensitive information so it should be showed to admin user only.
Example of health details response:
```
{
"status": "UP",
"details": {
"diskSpace": {
"status": "UP",
"details": {
"total": 254930841600,
"free": 29542526976,
"threshold": 10485760
}
},
"mongo": {
"status": "UP",
"details": {
"version": "4.0.6"
}
}
}
}
```

Only show health details for admin user

---

generators/client/templates/angular/src/main/webapp/app/core/auth/user-route-access-service.ts.ejs
generators/client/templates/angular/src/main/webapp/app/core/login/login.service.ts.ejs
generators/client/templates/angular/src/main/webapp/app/layouts/error/error.component.html.ejs

- Should correctly show access denied page post authentication.
- Should remove unnecessary redirect to access denied followed by login page to improve user experience
- Should correctly handle redirect to oauth2 login considering base ref.
---

angular: Improve login redirect handling

---

generators/server/templates/src/main/java/package/config/CacheConfiguration.java.ejs

InfinispanCacheConfigurer now sets TTL properties with TimeUnit.SECONDS, which is coherent with the properties names (time-to-live-seconds)

Fix TimeUnit setting in InfinispanCacheConfigurer

---

generators/heroku/templates/heroku.gradle.ejs

fix #9814
Currently jhipster master version fails in Heroku when choosing `compile on Heroku` with error
```
Could not find io.github.jhipster:jhipster-dependencies:3.0.2-SNAPSHOT
```
Seems that same issue as #9753
If applying this fix to app which is generated with released JHipster 6.0.1 then `compile on Heroku` works.
`compile locally` option works fine after doing `./mvnw clean install -Dgpg.skip` in project github.com/jhipster/jhipster as suggested in #9753 (without that the same io.github.jhipster:jhipster-dependencies:3.0.2-SNAPSHOT not found error occurs)
-   [ ] …

fix gradle compile on Heroku

---

generators/client/templates/react/src/test/javascript/e2e/modules/account/account.spec.ts.ejs
generators/client/templates/react/src/test/javascript/e2e/util/utils.ts.ejs

An attempt to fix intermittent failures seen on Azure for default react build. It's still not full proof as the presence of an overlay can cause an element to be not clickable.

react: Fix intermittent e2e failures

---

.github/FUNDING.yml

Just need to enable showing sponsoring button via https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository []

[ci-skip] add sponsoring configuration to show sponsor button in github

---

generators/entity-server/templates/src/main/resources/config/liquibase/data/table.csv.ejs

The other issue raised in 9721 (uniqueness in relationships) is already mentionned in #9579.
Fix #9721 

Remove extra column in fake data generation

---

generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.html.ejs

If we do not put this comparison, no field is present in the editForm.get method
Fix #9780 

fix feedback for update entity angular template

---

generators/server/templates/build.gradle.ejs

In continuation of #9789 this fixes the same problem reported in #9788 for Gradle projects as well.

Gradle - JAXB runtime must always be present when using JPA and JDK 11

---

generators/server/templates/src/main/java/package/config/DatabaseConfiguration.java.ejs

Fix #9803
This fixes the javadoc issue that causes the javadoc tool to crash and fail the build when using Couchbase and JDK 11. See logs of `ngx-couchbase` at https://dev.azure.com/hipster-labs/jhipster-daily-builds/_build/results?buildId=3139
While the javadoc was invalid the javadoc tool should also not crash and emit a warning instead. This has been reported at https://bugs.openjdk.java.net/browse/JDK-8200432 and fixed at JDK 12. …

Fix javadoc issue that prevents JDK 11 from building the javadoc when using Couchbase

---

.travis.yml
generators/client/templates/angular/package.json.ejs
generators/client/templates/angular/src/main/webapp/app/polyfills.ts.ejs
generators/client/templates/angular/src/test/javascript/jest-global-mocks.ts.ejs
generators/client/templates/angular/src/test/javascript/spec/app/admin/health/health.component.spec.ts.ejs

Bump angular dependencies

---

generators/server/templates/gradle/profile_dev.gradle.ejs

No need to launch Spring Boot dev tools when running tests. 
This is also the recommended configuration fro Gradle as per [docs](https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html).
More info here: https://github.com/spring-projects/spring-boot/issues/14451

Gradle - Use custom configuration to avoid launching the Spring Boot devtools when running tests

---

generators/server/templates/src/test/resources/config/application.yml.ejs

In some cases the daily builds terminate due to timeout(see `gradle-ms-ngx-gateway-eureka-uaa` and `gradle-ms-ngx-gateway-consul-uaa` at https://dev.azure.com/hipster-labs/jhipster-daily-builds/_build/results?buildId=3172.
The problem is called by a deadlock issue due to the use of the H2 in-memory DB. This bug has already been reported at https://github.com/h2database/h2database/issues/1841 and https://github.com/h2database/h2database/issues/1870. It has been fixed at https://github.com/h2database/h2database/pull/1842 and will be available with the next release of H2.
Added `MULTI_THREADED=FALSE`(enabled by default in 1.4.198) to the URL in order to workaround this problem. Once the next version is out we can then try again removing this option.
Please make sure the below checklist is …

Disable H2 MULTI_THREADED feature to avoid possible deadlock when running ITs

---

generators/client/templates/angular/webpack/webpack.dev.js.ejs
generators/client/templates/react/webpack/webpack.dev.js.ejs

When using separate client/server, ClientForwardController and index.html do not exist on the backend.  Refreshing http://localhost:9000/account/settings when using the webpack-dev-server (port 9000) gives a server-side 404.  
To fix that we need to add the paths back to the webpack proxy so it will know to load the frontend for non-server routes (currently all requests go to backend based on `/`).
Then webpack gives a 404 of its own, which is fixed by adding [`historyApiFallback`](https://webpack.js.org/configuration/dev-server/#devserverhistoryapifallback)
Very simple to reproduce with the JDL in the linked issue, just try going directly to http://localhost:9000/account/settings after running `npm start`
Fix #9839
- …

fix webpack proxy when client/server are separated

---

generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs

by setting `content-security`, `feature-policy`, `referrer-policy` header and deny embedding in an iframe.
Due to angular or an ng plugin we need to allow unsafe inline and eval (same for inline styles). Did not check if that is required for react or vue. Before the `X-Frame-Options` where disabled at all, now it is set to `deny` so embedding is not allowed by default.
See #9549 for the open question (thats why it is currently in draft mode). I tested also with local development via npm and gradle it works fine and I couldn't see any problems.
These are the current results for security headers https://securityheaders.com/?q=https%3A%2F%2Fgradleheroku.herokuapp.com%2F&followRedirects=on
And this is the deployed application https://gradleheroku.herokuapp.com/
closes #9549
-   Please make …

improve security headers

---

generators/client/templates/react/src/main/webapp/index.html.ejs

Hi Guys,
I apologize if I get the below wrong as I am a bit new to contributing. I encountered a small issue when generating a jhipster react app in that the css file is not loaded because the folder is incorrect. "content" rather than "static".
For your review and perhaps approval.

Fix for the default CSS not loading on index.html

---

generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs
generators/server/templates/src/main/docker/config/realm-config/jhipster-realm.json.ejs

These are necessary to run Ionic for JHipster on iOS and Android with Keycloak.

Add Ionic 4 redirect URIs to Keycloak web_app client

---

generators/entity/index.js

The check was using databaseType rather than prodDatabaseType, and thus was returning false positive.
Eg: 'label' is only a reserved word for Oracle, but was considered as a reserved word for MySQL or PostgreSQL

Entity: fix check of reserved word for field 

---

generators/generator-constants.js

Adoptopenjdk have been approved by the docker hub as official images now, see https://github.com/docker-library/official-images/pull/5710
However alpine is not offered as it is not recommended for now (see the PR). IMO if the people from the adoptopenjdk project don't recommend using those images, then we refrain from using them for now.

Use official adoptopenjdk docker image now that it is available from docker hub

---

generators/server/templates/build.gradle.ejs

After upgrading to JHipster 6, the Eclipse build path for generated classes has changed from:
`build/generated/source/apt/main` 
to 
`build/generated/sources/annotationProcessor/java/main`
This is related to https://github.com/jhipster/generator-jhipster/issues/9134 and https://github.com/jhipster/generator-jhipster/pull/9468
-   [X ] Tests are added where necessary

Switch eclipse to use new generated sources directory

---

generators/client/templates/angular/package.json.ejs

ng-bootstrap `v4.2.1` fixes the date validation issues observed in `v4.2.0`

Bump ng-bootstrap dependency

---

cli/cli.js

I believe there's no reason for options to be determined in each iteration, as they are not changing.
Best regards!

improve performance

---

generators/server/templates/src/test/java/package/web/rest/UserResourceIT.java.ejs

This PR is to make sure when the memcached is disabled, the tests are taking note of it.
Fixes #9901 

Added a noopcachemanager verification for user resources tests

---

generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs
generators/generator-base.js
generators/server/needle-api/needle-server-liquibase.js
test/needle-api/needle-server-liquibase.spec.js
test/needle-api/templates/src/main/resources/config/liquibase/changelog/dummy_changelog.xml.ejs

With regards to the discussion in #9862 (which addresses approach 2 of #9804) a less invasive change:
* moved 'load data' section to end of file
* added new needle to allow 3rd party extensions to add additional 'load columns' (```jhipster-needle-liquibase-add-loadcolumn```)
Open issue/topic: 
* Do we need a special treatment to disable foreign key constraint checks during load process (e.g.
```<sql dbms="h2">SET REFERENTIAL_INTEGRITY FALSE</sql>``` or 
```<sql dbms="mysql">SET FOREIGN_KEY_CHECKS = 0</sql>```
(of course re-enable at end of load changeset))?
Fix: #9804 (utilizing slightly modified Approach 1)
-   [x] Tests …

Loading of fake data

---

generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs

This is a follow up of https://github.com/jhipster/generator-jhipster/pull/9834
While trying out the latest vue blueprint I found that e.g. background images in scoped styles are put into data uris when building with prod profile. The current csp does not allow data uris as image sources (it might be dangerous). This PR configures the csp to allow data uris as image source.
See https://javaprosample.herokuapp.com/ (the bow tie in the navbar is a data uri). But maybe it would be better to make sure no frontend uses data uris eventually.
-   [ ] Documentation is added/updated where …

allow data uris as image source via csp

---

test/upgrade.spec.js

The target version is now forced, it should prevent issue when beta releases are done

Re-enable unit tests for upgrade subgenerator

---

generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.ts.ejs

creating inline variable for `reateFromForm()` and removing unused parameters in `subscribeToSaveResponse`.

Creating inline variable && removing unused params

---

test-integration/samples/.jhipster/FieldTestEntity.json
test-integration/samples/.jhipster/FieldTestInfiniteScrollEntity.json
test-integration/samples/.jhipster/FieldTestMapstructEntity.json
test-integration/samples/.jhipster/FieldTestPagerEntity.json
test-integration/samples/.jhipster/FieldTestPaginationEntity.json
test-integration/samples/.jhipster/FieldTestServiceClassEntity.json
test-integration/samples/.jhipster/FieldTestServiceImplEntity.json

Those fields are not generated because not supported anymore, but are still printed in the jhipster info phase. 
By removing them, it is easier to reproduce the errors by copy/pasting jdl

remove unsuported fields in test integration

---

generators/server/templates/build.gradle.ejs
generators/server/templates/gradle/swagger.gradle.ejs
generators/server/templates/pom.xml.ejs
generators/server/templates/src/main/resources/swagger/api.yml.ejs

* Updating open api plugin to 4.0.1
* Add new required dependency for `json-nullable` (because of updated templates in swagger templates)
* Add import mapping for zalando problem, such these classes are not generated
closes #9911 

import mappings for zalando problem

---

generators/aws-containers/index.js
generators/aws-containers/templates/base.template.yml.ejs

change aws parameters to be lower-case where necessary

---

generators/server/templates/src/test/java/package/service/MailServiceIT.java.ejs

In the `MailServiceIT.java.ejs` the value of sender is hard-coded. This value is, by default, the same one as given in the `application.yml` file under the key `jhipster.mail.from`. In the case we change the `test@localhost` value in the `application.yml` file, the tests will fail. This change will make tests pass in this case without having to do anything further.

replace hard-coded value of `test@localhost` with property value

---

generators/entity-client/index.js
generators/entity-i18n/index.js
generators/entity-server/index.js
test/blueprint/entity-client-blueprint.spec.js
test/blueprint/entity-i18n-blueprint.spec.js
test/blueprint/entity-server-blueprint.spec.js
test/needle-api/needle-client-react.spec.js
test/needle-api/needle-server-liquibase.spec.js
test/templates/ngx-blueprint/.yo-rc.json
test/templates/ngx-blueprint/HelloKotlin.kt.ejs
test/templates/ngx-blueprint/HelloVue.html.ejs
test/templates/ngx-blueprint/custom-i18n.json.ejs

Fix `jhipsterContext` for entity client, server and i18n sub-gens and allow creating blueprints without having to override the parent entity sub-gen.
The problem is actually described by @yelhouti at https://github.com/jhipster/generator-jhipster-blueprint/issues/38 and I used the same workaround for https://github.com/jhipster/jhipster-kotlin/pull/146.
This fixes the problem and will make the workaround obsolete and further simplify the code for the blueprints, for  example:
**Before:**
```
module.exports = class extends EntityServerGenerator {
constructor(args, opts) {
super(args, { fromBlueprint: true, ...opts }); // fromBlueprint variable is important
const jhContext = (this.jhipsterContext = this.options.jhipsterContext || opts.jhipsterContext);
if (!jhContext) {
this.error(`This is …
```

Fix jhipsterContext for entity client, server and i18n blueprints and

---

generators/server/templates/gradle/profile_dev.gradle.ejs
generators/server/templates/gradle/profile_prod.gradle.ejs

Before, when first compiling the project with Gradle `dev` profile and then, without cleaning the
project, with Gradle `prod` profile, the list of active Spring profiles was not updated. Now it is.

use correct Spring profiles when building app with different Gradle profile

---

generators/server/templates/build.gradle.ejs

We decided to not use `latest` as the tag for the Docker image built by jib, but the Gradle project version. While I think changing the default Docker image tag is not a good change for JHipster in general, moving the project version up allows it to be referenced by Jib. Not knowing too much about Gradle project configuration before, we stumbled over this and I want to save others this learning.

allow using Gradle project version in jib configuration

---

generators/client/templates/angular/package.json.ejs
generators/client/templates/angular/webpack/utils.js.ejs
generators/client/templates/angular/webpack/webpack.common.js.ejs
generators/client/templates/react/package.json.ejs
generators/client/templates/react/webpack/utils.js.ejs
generators/client/templates/react/webpack/webpack.common.js.ejs
generators/server/templates/gradle/profile_dev.gradle.ejs
generators/server/templates/gradle/profile_prod.gradle.ejs
generators/server/templates/pom.xml.ejs

Currently, the webpack `DefinePlugin` sets the `VERSION` by parsing it from either `build.gradle`
(in case of a Gradle build) or from `pom.xml` (in case of a Maven build). The problem with this is
that if the version is not statically set, but rather dynamically calcualted (e.g. using
https://github.com/palantir/gradle-git-version to determine it from the Git repo), the parsing
breaks.
Thus, this PR changes this by passing the version to show in the frontend from the server build
tool (Gradle/Maven) as an environment variable to the NPM webpack task. This is more robust and
does not rely on parsing the Gradle/maven file. The downside is that if only `npm start` is run,
instead of the version, `UNKNOWN` is shown.
I think the advantages (allowing dynamic version in Gradle, removing parsing …

pass app version to NPM as env var instead of parsing it from build file

---

generators/client/templates/angular/webpack/utils.js.ejs
generators/client/templates/angular/webpack/webpack.common.js.ejs
generators/client/templates/react/webpack/utils.js.ejs
generators/client/templates/react/webpack/webpack.common.js.ejs

1. Follow up on #9986
If `skip server` option is used, then, consider `package.json` version to be displayed on the UI. Current default was hard coded to '0.0.1-SNAPSHOT'
2. Remove non used function from utils

Use client side package version if build tool is undefined

---

generators/generator-base.js
generators/utils.js
test/upgrade.spec.js
test/utils.spec.js

Allow changing the parent root directory of the `.yo-rc.json`. The default remains the` cwd`.
The use case is to allow jhipster modules to take advantage of existing code and e.g. re-use the existing entity sub-gen while loading the configuration from a directory other than the `cwd`. See https://github.com/oktadeveloper/generator-jhipster-ionic/pull/109

Allow loading .yo-rc.json from an alternate root path other than cwd

---

generators/server/files.js
generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs
generators/server/templates/src/main/java/package/security/SecurityUtils.java.ejs
generators/server/templates/src/main/java/package/security/oauth2/AuthorizationHeaderUtil.java.ejs
generators/server/templates/src/main/java/package/security/oauth2/JwtAuthorityExtractor.java.ejs
generators/server/templates/src/main/java/package/security/oauth2/OAuthIdpTokenResponseDTO.java.ejs
generators/server/templates/src/main/java/package/service/UserService.java.ejs
package-lock.json
test/utils/expected-files.js

Handle another oauth2 use case: communicating from the  gateway to a microservice, the token kind changes from Oauth2AuthenticationToken to JwtAuthenticationToken.
Also, refreshes the access token when calling Feign, also, consider the token as a JWT one when the gateway is calling a microservice via Feign.
so relates to #9707. 
It's functional, but I'm not sure that we can't achieve the same thing with some higher level spring capabilites.
@mraible , WDYT of this PR?
Regards, …

Feign token refresh

---

generators/client/files-angular.js
generators/client/needle-api/needle-client-angular.js
generators/client/templates/angular/package.json.ejs
generators/client/templates/angular/src/main/webapp/app/app-routing.module.ts.ejs
generators/client/templates/angular/src/test/javascript/protractor.conf.js.ejs
generators/client/templates/angular/tsconfig-aot.json.ejs
generators/client/templates/angular/tsconfig.e2e.json.ejs
generators/client/templates/angular/tsconfig.json.ejs
package-lock.json
test/needle-api/needle-client-angular.spec.js

Fix #9926 
Had to add the `acorn` dependency to force webpack to use the correct versions, thanks npm...
See there for more info on the issue: https://github.com/webpack/webpack/issues/8656

angular: use dynamic import syntax

---

generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs

related to https://github.com/jhipster/generator-jhipster/pull/9923 and #9834
If you open https://javaprosample.herokuapp.com/, you will see 60 errors logged to the console complaining about the font-src.  A fixed app is https://font-fix.herokuapp.com/

allow data uris as font source via csp

---

generators/client/templates/react/src/main/webapp/app/modules/home/home.tsx.ejs

This extra call is not necessary since it is already done in the main app component

[react] remove useless second /api/account call 

---

generators/client/templates/angular/src/main/webapp/app/layouts/navbar/navbar.component.html.ejs

This PR is to position the dropdown menu dynamically to have this:
instead of
(previously fixed by placement="bottom-right")
The **display="dynamic"** attribute seems required using ng-bootstrap 4.2.1 (it was working well with 4.1.3) and only because the ngbDropdown is inside a navbar.
I found this out after having a look at:
- https://github.com/ng-bootstrap/ng-bootstrap/issues/3269
- https://ng-bootstrap.github.io/#/positioning#dropdown
This fix implies a rendering for mobile like this:
instead of
What do you think ?

Position ngbDropdown dynamically

---

generators/server/templates/src/test/java/package/service/UserServiceIT.java.ejs

`UserServiceIT.testUserDetailsWithLangKey` is failing with oauth2/mongodb.

Fix UserServiceIT.testUserDetailsWithLangKey

---

generators/ci-cd/templates/.gitlab-ci.yml.ejs
generators/ci-cd/templates/jenkins/Jenkinsfile.ejs
generators/ci-cd/templates/travis.yml.ejs

Sonar does not use the sonar-project.properties with Maven during the quality analysis stage. Adding the initialize goal fixes it - as described in `README.md`.
Fixed on Jenkins pipeline, GitLab CI and Travis CI. 
Fix #10101

Use sonarqube external conf file #10101

---

generators/client/templates/angular/src/main/webapp/index.html.ejs
generators/client/templates/react/src/main/webapp/index.html.ejs

For some reason, `google` meta tag had attribute `value` instead of `content`. According to the [documentation](https://support.google.com/webmasters/answer/79812?hl=en) this is wrong. Therefore, this commit introduces `content` attribute instead of `value`.

fix `google` meta tag attribute

---

generators/client/templates/angular/src/main/webapp/content/scss/global.scss.ejs

With c55634ed99317aedebf5efad441a3a3e87f3f23b, it was decided to override the link color and font-weight of Bootstrap/the Bootswatch theme for passing the Lighthouse accessibility audit.
I think this is a bad idea since 1. the picked color might not match the color scheme of the Bootswatch theme and 2. it should be the responsibility of the theme to consider accessibility concerns and not JHipster building on top of this. This also again reduces the JHipster provided CSS (which I think is in general a good idea).
I thus suggest to remove this custom overriding of the link colors again.

use default link colors of Bootstrap/Bootswatch theme

---

generators/server/index.js
generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs

Allow google fonts as style and font source such that csp is less strict when using bootswatch themes
closes #10091

allow google fonts as style and font sources in csp

---

generators/client/templates/angular/src/main/webapp/content/scss/vendor.scss.ejs

Currently, the `_bootstrap_variables.scss` file is not included into `vendor.scss`. Thus, the overriden variables in there are not affecting the bootstrap components. This commit fixes that. Now, the variables defined in this file influence the bootstrap component colors and other styles.
Since `_bootstrap-variables.scss` is also present (but being empty) when generating without a Bootswatch client theme, I think it still makes sense to also include it in this case. But in order to allow overriding variables already set in the `variables.scss` file of the Bootswatch theme, `_bootstrap-variables.scss` needs to be imported after this file.
The downside of this change is that now, the default layout has a white box on gray background:
I suggest to thus also change the value of `$body-bg` in …

make variable overrides in _bootstrap-variables.scss change components

---

generators/languages/index.js

Add a skipUserManagement variable in the language generator to reflect the behaviour of the server generator. I'm not sure if it's the correct place to initialize the variable.
Fix #10136 

Fix "Unable to find MailServiceIT.java" in translations

---

generators/server/templates/gradle/profile_dev.gradle.ejs

This is very minor, but to be consistent we should consider `build.gradle` when building the frontend in dev mode as the version comes from that file now. Without this change you would change the version and in case nothing else has changed the frontend won't be rebuild so the old version number is displayed in the navbar.

consider build.gradle for up2date check

---

generators/upgrade/index.js

Signed-off-by: Arjun Nayak <arjunglobal09@gmail.com>
Problem: We found that when running the jhipster upgrade process, when there were new prompts added in the newer version of our blueprint, the re-run of the blueprint did not allow for interactivity to answer the new prompts. 
This was a result of using `shelljs` which does not allow for interactivity by default. We followed the workaround described [here](https://github.com/shelljs/shelljs/wiki/FAQ#running-interactive-programs-with-exec). With the fix, the blueprint re-ran as a child process and allowed for normal prompt interaction.
Question: We manually tested this with our blueprint and it works as expected, however we could not figure out how to properly test this in the upgrade unit tests. Do you have any suggestions on how to …

Use child_process in upgrade to allow interaction with cli.

---

generators/ci-cd/templates/travis.yml.ejs

Container based infrastructure has been deprecated and thus sudo: false no longer holds; https://docs.travis-ci.com/user/reference/trusty/#container-based-infrastructure

Remove sudo key value

---

generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.html.ejs

Customizing entityUrl with 'foo/' will break the delete button
Replace
[routerLink]="['/', '<%= entityUrl %>'
With
[routerLink]="['/<%= entityUrl %>'

Fix delete routerLink

---

generators/client/templates/angular/webpack/webpack.common.js.ejs

Fixes #10166.
Note: the RxJS path mappings are not needed anymore as they are correctly resolved via the `mainFields` property and the corresponding entry in the `package.json` of RxJS.

Fix #10166 ESM5 version of libraries are bundled

---

generators/ci-cd/templates/travis.yml.ejs

I've removed the jdk option of travis; this I believe is useless since it's only used when used in conjunction with ```language: java```. 
Also I've changed the linux distro to bionic since the default distro used by travis seems to be trusty and that doesn't have openjdk11 preinstalled (bionic does). This I believe makes the travis pipeline cleaner so that we don't have to manually install stuff on it and also could get rid of the ```jdk_switcher use oraclejdk8``` part (which seems redundant anyways).
-   [x] Coding Rules & …

Upgrade Travis pipeline to OpenJDK11

---

package.json

Few builds/tests are intermittently failing due to timeouts like:
https://travis-ci.org/jhipster/generator-jhipster/jobs/566793051

Increase timeout to 30s to fix intermittent failures

---

generators/server/templates/src/test/resources/config/application.yml.ejs

cc @pascalgrimaud 
fix https://github.com/jhipster/generator-jhipster/issues/10065

disable logstash appender during tests

---

.travis.yml
Dockerfile
azure-pipelines.yml
generators/generator-constants.js

For unknown reason, Node 10.16.1 doesn't work well.
I encountered some strange behaviour with this version of Node, on my local computer.
I hope this PR will fix the Cassandra build.
_____

Upgrade to Node 10.16.2 and NPM 6.10.2

---

generators/client/templates/angular/src/main/webapp/app/core/login/login.service.ts.ejs
generators/docker-compose/index.js
generators/docker-compose/templates/central-server-config/application.yml.ejs
generators/docker-compose/templates/traefik/traefik.toml.ejs

Fix https://github.com/jhipster/generator-jhipster/issues/9769
Fix https://github.com/jhipster/generator-jhipster/issues/9770
Add a message when traefik is use with oauth2, and a link to the documentation for complete the configuration.
Add a variable to simplify the configuration with traefik
Documentation update in https://github.com/jhipster/jhipster.github.io/pull/754
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are …

Add message when traefik is use with oauth2 and a link to documentation

---

generators/client/templates/angular/package.json.ejs
generators/client/templates/angular/webpack/webpack.common.js.ejs
generators/client/templates/react/package.json.ejs
generators/client/templates/react/webpack/webpack.common.js.ejs

This uses the version from package.json in case it is not provided via environment from maven/gradle task. To make it rock solid we could try to update the version in `package.json` from [maven](https://github.com/ASzc/jsonpath-maven-plugin)/gradle, but in that case both frontend and backend always have the same version (which is ok, but maybe there are usecases where they must be different).
closes #10192 …

use version from package.json when not provided via environment

---

generators/server/templates/build.gradle.ejs
generators/server/templates/gradle.properties.ejs
generators/server/templates/gradle/wrapper/gradle-wrapper.properties
generators/server/templates/settings.gradle.ejs

* regular upgrade to latest and final gradle 5.x version
* using the new [plugin management](https://docs.gradle.org/5.6/userguide/plugins.html#sec:plugin_version_management) to define plugin versions via properties
* removed the [propdeps plugin](https://github.com/spring-gradle-plugins/propdeps-plugin) as (at least) we don't use it directly and it seems quite outdated
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are …

upgrade to gradle 5.6 and using plugin management

---

generators/app/index.js
generators/entity/index.js
generators/generator-base.js
generators/server/index.js

Follow up to #10185
@vishal423 pointed out in the review of the #10185 that `isJhipsterVersionLessThan` function is not working correctly.  
I found same conclusions in issue #9204:
* in @clement26695 comment: https://github.com/jhipster/generator-jhipster/issues/9204#issuecomment-461030165
* in @pmverma comment: …

Fix old JHipster version check in cleanup

---

generators/entity-client/files.js

Entity's json service is created with name '${generator.entityServiceFileName}.service.ts' but is imported as '<%= entityFileName %>.service'.
Fix this bug.
https://github.com/jhipster/generator-jhipster/blob/a1023e100dce9689289383f57fbe7a064b1b84d8/generators/entity-client/files.js#L98

Fix import angular service filename

---

generators/client/needle-api/needle-client-angular.js
generators/generator-base.js

Add parameter translationKeyMenu to addElementToMenu and addElementToAdminMenu.
This will make easier to blueprints add menus.
Just like addEntityToMenu.
https://github.com/jhipster/generator-jhipster/blob/a1023e100dce9689289383f57fbe7a064b1b84d8/generators/generator-base.js#L103

Improve addElementToAdminMenu and addElementToMenu api

---

generators/client/templates/angular/src/main/webapp/app/home/home.component.html.ejs
generators/client/templates/angular/src/main/webapp/index.html.ejs
generators/client/templates/react/src/main/webapp/index.html.ejs

This fixes the vulnerabilities detected by sonar for external links. React already had `noopener noreferrer` for external links.
updates #10258

add noopener to all external links

---

CONTRIBUTING.md

I believe it's more appropriate to put ```mvnw``` instead of ```mvn``` here as maven might not be globally installed and even if that's the case ```mvnw``` will still work (this is the case in my local setup for example). 

mvnw command instead of mvn for verifying

---

generators/client/templates/angular/src/test/javascript/jest.conf.js.ejs
generators/client/templates/angular/webpack/utils.js.ejs
generators/client/templates/angular/webpack/webpack.common.js.ejs
generators/client/templates/react/src/test/javascript/jest.conf.js.ejs
generators/client/templates/react/webpack/utils.js.ejs
generators/client/templates/react/webpack/webpack.common.js.ejs

If adding new alias to Typescript then currently must add this alias both to Typescript and Webpack config. After this change it's enough to add alias to Typescript config. Webpack reads aliases directly from Typescript config.
If in current version adding new path only to `tsconfig.json` into section `compilerOptions.paths` then on building app the following error occur: `Module not found: Error: Can't resolve '...'`.
This improves developer experience:
* for these who doesn't know Webpack and Typescript in depth this can save time which it takes to understand and resolve errors if changing only `tsconfig.json`
* for these who know Webpack and Typescript well this avoids annoying double change, for example developers and testers of the ng-jhipster can route generated application to use …

Define Typescript aliases in a single place

---

README.md

This corrects the 404 error when clicking the bug template url link. 

Fix 404 error on clicking bug template url

---

generators/server/files.js
generators/server/templates/build.gradle.ejs
generators/server/templates/pom.xml.ejs
generators/server/templates/src/main/java/package/service/EmailAlreadyUsedException.java.ejs
generators/server/templates/src/main/java/package/service/InvalidPasswordException.java.ejs
generators/server/templates/src/main/java/package/service/LoginAlreadyUsedException.java.ejs
generators/server/templates/src/main/java/package/service/UserService.java.ejs
generators/server/templates/src/main/java/package/service/UsernameAlreadyUsedException.java.ejs
generators/server/templates/src/main/java/package/web/rest/errors/ExceptionTranslator.java.ejs
generators/server/templates/src/test/java/package/ArchTest.java.ejs

As already proposed in [this sample](https://github.com/atomfrede/jh-9876) this PR does the following:
* Adding [archunit](https://www.archunit.org/) to check that the service layer does not depend on the web layer
* Add new exceptions in service layer package which are used by the userservice instead of the web excetions/problems
* Instead of renaming the web exceptions to something like `...WebException` or `...Problem` I just kept the name and use in the translator a fully qualified classname. Otherwise we would have had to rename/remove the all exceptions, change all imports elsewhere. With the current approach updating e.g. is easy and the diff will be pretty small.
I will take care of adding a paragraph about arch unit to our documentation after it is merged.
-   Please make sure …

make service layer not depend on web layer

---

generators/client/templates/angular/package.json.ejs
generators/client/templates/angular/src/main/webapp/app/app.module.ts.ejs
generators/client/templates/angular/src/main/webapp/app/vendor.ts.ejs

- Closes #10209 
- Bumped `angular` and associated library versions.
- Removed direct dependency on `acorn` that was added to fix dynamic import issue. Related to https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/upgrading/0.4.0-0.5.0.md
- Updated usage of font awesome library to fix warnings. Related to https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/upgrading/0.4.0-0.5.0.md
--- …

angular: Bumped library versions, remove acorn dependency

---

generators/server/templates/src/main/resources/config/application-dev.yml.ejs
generators/server/templates/src/main/resources/config/application-prod.yml.ejs

This fixes a a typo in a infinispan related property in application-dev.yml and application-prod.yml templates, which was not activating caches statistics.

Fix typos in Infinispan property

---

generators/cleanup.js
generators/client/templates/react/.eslintrc.json.ejs

- Closes #10304 
- Instead of static `tsconfig`, decide one based on chosen frameworks.
- Delete `tslint.json` on upgrade.
---

Instead of static tsconfig, decide one based on chosen frameworks

---

generators/client/templates/angular/src/main/webapp/app/account/account.module.ts.ejs
generators/client/templates/angular/src/main/webapp/app/admin/admin.module.ts.ejs
generators/client/templates/angular/src/main/webapp/app/entities/entity.module.ts.ejs
generators/client/templates/angular/src/main/webapp/app/home/home.module.ts.ejs
generators/client/templates/angular/src/main/webapp/app/shared/shared.module.ts.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.html.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.module.ts.ejs

This PR removes `CUSTOM_ELEMENTS_SCHEMA` from Angular modules. Apps generated by JHipster are not using custom elements schemas by default, so this is unnecessary to add this.  
Also _Angular CLI_ and Angular default tutorial app _Tour of Heroes_ doesn't have this.  
Angular is doing more checks after removing this and with help of Travis was caught error in …

Remove CUSTOM_ELEMENTS_SCHEMA and fix error found after that

---

generators/client/templates/angular/src/main/webapp/app/app.module.ts.ejs
generators/client/templates/angular/src/main/webapp/app/shared/shared-libs.module.ts.ejs
generators/client/templates/angular/src/main/webapp/app/shared/shared.module.ts.ejs

`SharedLibsModule` and `SharedModule` has no providers in `forRoot` method, so these methods are doing nothing and can be deleted.  
This PR is doing this cleaning.

Remove redundant forRoot methods in Angular part

---

generators/client/files-angular.js
generators/client/files-react.js
generators/client/templates/angular/.lintstagedrc.js.ejs
generators/client/templates/angular/package.json.ejs
generators/client/templates/react/.lintstagedrc.js.ejs
generators/client/templates/react/package.json.ejs
test/utils/expected-files.js

- Closes #10312  
- Revert to old `lint-staged` dependency version that works on windows and doesn't degrade initial commit performance.
- Move lint-stage configurations to separate file, so, that future upgrade can be easy.
- Upgrade husky, lint-staged and prettier dependencies on react codebase to keep them in sync with angular.
---

Revert to old lint-staged version to fix issue on windows

---

generators/generator-base.js
generators/server/index.js
generators/server/templates/build.gradle.ejs
generators/server/templates/pom.xml.ejs

This adds support for creating a non executable jar through specifying the embeddableLaunchScript property in .yo-rc.json.
Fix #10255

Add support for creating non-executable jar

---

package-lock.json
package.json

Fix warning available in CI:
````sh
> yo@2.0.6 postinstall /home/travis/build/jhipster/generator-jhipster/node_modules/yo
> yodoctor
Yeoman Doctor
Running sanity checks on your system
✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version
✖ yo version
Your yo version is outdated.
Upgrade to the latest version by running:
npm install -g yo@latest
````
-   [x] Coding Rules & Commit Guidelines as per our …

Update yo version to 3.1.0

---

generators/app/index.js
test-integration/samples/app-sample-dev/.yo-rc.json

Linked to #10282 
Set embeddableLaunchScript to true for apps generated with old JHipster versions
We don't want to surprise users that were relying on this feature to be enable by default.

Use embeddableLaunchScript=true for apps generated by older JHipster versions

---

generators/kubernetes/templates/db/mssql.yml.ejs
test/kubernetes.spec.js
test/templates/compose/11-mssql/.yo-rc.json
test/templates/compose/11-mssql/src/main/docker/app.yml
test/templates/compose/11-mssql/src/main/docker/mssql.yml

Reported in the Gitter, `jhipster kubernetes` fails for apps using MSSQL because there are two `volume` keys in the yml.  Also added it to the tests.
<details>
<summary>Stacktrace</summary>
<pre>
```
(node:19906) UnhandledPromiseRejectionWarning: SyntaxError: Map keys must be unique; "volumes" is repeated (16:7)
14 |         app: msmssqldb-mssql
15 |     spec:
> 16 |       volumes:
|       ^^^^^^^^^^^^^^^^^
> 17 |       - name: data
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 18 |         emptyDir: {}
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 19 |       containers:
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 20 |       - name: mysql
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 21 |         image: microsoft/mssql-server-linux:latest
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 22 |         env: …
```

merge duplicate volume sections in mssql.yml kubernetes

---

generators/client/templates/angular/src/main/webapp/swagger-ui/index.html.ejs
generators/client/templates/react/src/main/webapp/swagger-ui/index.html.ejs

previously this was "bearer" whereas api.yml uses "jwt" as the security
key name causing authorization headers to not be sent
Fix #10330

change swagger client auth key to match api.yml

---

generators/client/templates/angular/package.json.ejs
generators/client/templates/angular/src/main/webapp/app/admin/admin.module.ts.ejs
generators/client/templates/angular/src/main/webapp/app/app.module.ts.ejs
generators/client/templates/angular/src/main/webapp/app/core/language/language.helper.ts.ejs
generators/client/templates/angular/src/main/webapp/app/shared/shared-libs.module.ts.ejs
generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.module.ts.ejs

Because of ng-jhipster packaging, we had one instance of TranslateModule per lazy loaded modules. This caused some issues when we introduced lazy-loading and we had to do some strange hacks. 
You can see the removed code in this PR to check the hacks.
We should do one `forRoot` call in our `AppModule` instead of doing it multiple times, so I think we should remove the `forRoot` in the ng-jhipster lib and do that in the generated app instead.
We need https://github.com/jhipster/ng-jhipster/pull/99 to be closed and a `ng-jhipster` release before merging this. …

Fix TranslateModule usage

---

generators/generator-base-private.js

Use require.resolve to find yeoman library when checking blueprint version.

---

generators/client/templates/react/package.json.ejs

It will fix the daily builds for React+Yarn:
https://dev.azure.com/hipster-labs/jhipster-daily-builds/_build/results?buildId=5298&view=logs&j=1325b5b4-61f4-5784-74f4-9f398d404aa2
_____

Fix React+Yarn build, using resolution for redux lib

---

generators/server/templates/src/test/java/package/ArchTest.java.ejs

`./mvnw verify` fails on my Mac with the following error:
```
[INFO] Running com.mycompany.myapp.ArchTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.016 s <<< FAILURE! - in com.mycompany.myapp.ArchTest
[ERROR] servicesAndRepositoriesShouldNotDependOnWebLayer  Time elapsed: 0.011 s  <<< ERROR!
java.lang.Error: 
Unresolved compilation problem: 
Syntax error on token ";", delete this token
at com.mycompany.myapp.ArchTest.<init>(ArchTest.java:5)
```
```
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
git version 2.20.1
node: v10.16.0
npm: 6.10.1
```
-   [ ] [Travis …

remove extra semicolon causing 'mvn verify' failure

---

generators/utils.js
test/templates/ngx-blueprint/.yo-rc.json
test/utils.spec.js

I encountered this bug while upgrading one of my project using a blueprint.
The .yo-rc.json contains somethings like that: 
```
{
...
"blueprint": "generator-jhipster-xxxx",
"blueprintVersion": "0.2.5",
"blueprints": [
{
"name": "generator-jhipster-xxxx",
"version": "0.3.0"
}
]
}
}
```
During the automatic upgrade I noticed that it was detecting twice the blueprint, and then trying to install both version.
The bug comes from the code merging new `blueprints` info and old `blueprint` info in `getAllJhipsterConfig()`. I added a test to verify the issue, and another new test for verify configuration merge with multiple generators (jhipster and blueprints) are involved.
Also: the second commit is an attempt to factorize the code that merges old and new blueprints …

Fix duplicated blueprints loaded from config

---

generators/client/templates/angular/package.json.ejs
generators/client/templates/react/package.json.ejs
generators/server/templates/package.json.ejs
package-lock.json
package.json

If we upgrade to `0.0.19-4.1.2`, there are some problems:
- `npm test` failed
- after using openapi-client, the project won't compile
- it is related to missing `ApiKeyRequestInterceptor.java` and `ClientConfiguration.java`
The easiest way for now is to revert the upgrade for now.
cc @DanielFran 
_____

Revert upgrade openapitools

---

generators/server/templates/build.gradle.ejs
generators/server/templates/pom.xml.ejs

They are already covered by the pattern '**/*IT*'

Maven: Removes useless exclude/include pattern for ''**/*CucumberIT*'

---

generators/client/templates/react/src/main/webapp/app/modules/administration/gateway/gateway.tsx.ejs

Fix #10412
This only commit fixes the bug when lauching again `./mvnw` on the React API gateway but there are other external links with target="_blank" that should maybe be fixed in : 
- gateway.component.html.ejs
- microservices_index.html.ejs
What do you think about that?

add noopener noreferrer to external link in React gateway
