jhipster/generator-jhipster

- generators/client/templates/angular/src/main/webapp/content/scss/_vendor.scss
- generators/generator-base.js
- generators/modules/index.js
> Add third-party resources to Vendor.scss

- generators/entity/index.js
- generators/server/index.js
- generators/server/templates/src/main/java/package/domain/_Authority.java
- generators/server/templates/src/main/java/package/domain/_PersistentAuditEvent.java
- generators/server/templates/src/main/java/package/domain/_PersistentToken.java
- generators/server/templates/src/main/java/package/domain/_SocialUserConnection.java
- generators/server/templates/src/main/java/package/domain/_User.java
- generators/server/templates/src/main/resources/config/liquibase/changelog/_initial_schema.xml
> Use jhiPrefix to prefix JHipster tables

- generators/client/templates/angular/src/main/webapp/_index.html
- generators/generator-base.js
- generators/modules/index.js
> Add third-party resources to root(index.xhtml)

- package.json
- yarn.lock
> Updated JHipster Core to v1.3.6

- generators/server/templates/_README.md
- generators/server/templates/src/main/resources/config/_application.yml
- generators/server/templates/src/test/resources/config/_application.yml
> Remove oauth.issuer as a property

- package.json
- yarn.lock
@jdubois yesterday, I completely forgot to include the bulk microservice setting when having this kind of setup (sorry about that!):
- a microservice app
- a JDL file inside it like this:
```
entity A
entity B
...
entity Z
```
- when importing the JDL, the microservice option is set to every entity (like a `microservice * with <PROJECT_NAME>`.
Plus, I've improved error reporting, especially the reserved keyword reportings. With Deepu's changes, I think we're pretty good with the JDL reporting parsing errors.
> Updated JHipster Core to v1.3.7

- generators/server/files.js
- generators/server/templates/src/main/java/package/config/_CacheConfiguration.java
- generators/server/templates/src/main/java/package/domain/_User.java
- generators/server/templates/src/main/java/package/web/rest/_AccountResource.java
- generators/server/templates/src/main/resources/config/liquibase/changelog/_initial_schema.xml
> Skips user management when oauth2 is selected as the auth irrespective of app type

- generators/server/templates/_build.gradle
- generators/server/templates/_gradle.properties
- generators/server/templates/gradle/_gatling.gradle
Using gradle galting plugin to remove custom coded gatling tasks. Update #6252
> use gradle gatling plugin

- generators/server/files.js
- generators/server/templates/src/main/java/package/config/_CacheConfiguration.java
- generators/server/templates/src/main/java/package/domain/_User.java
- generators/server/templates/src/main/java/package/web/rest/_AccountResource.java
- generators/server/templates/src/main/resources/config/_application.yml
- generators/server/templates/src/main/resources/config/liquibase/changelog/_initial_schema.xml
- generators/server/templates/src/test/resources/config/_application.yml
> Add User Synchronization to OAuth Monolith

- generators/client/templates/angular/src/main/webapp/app/layouts/navbar/_navbar.component.html
> fixing left margin when dropdown is toggled

- generators/server/templates/src/main/java/package/web/rest/errors/_BadRequestAlertException.java
- generators/server/templates/src/main/java/package/web/rest/errors/_EmailAlreadyUsedException.java
- generators/server/templates/src/main/java/package/web/rest/errors/_EmailNotFoundException.java
- generators/server/templates/src/main/java/package/web/rest/errors/_ErrorConstants.java
- generators/server/templates/src/main/java/package/web/rest/errors/_InvalidPasswordException.java
- generators/server/templates/src/main/java/package/web/rest/errors/_LoginAlreadyUsedException.java
> Formatting

- generators/server/templates/src/main/java/package/service/_UserService.java
> [Sonar] remove duplicate String

- generators/server/templates/src/main/java/package/config/_LoggingConfiguration.java
> [Sonar] remove unused variable

- generators/server/templates/src/main/java/package/web/rest/errors/_BadRequestAlertException.java
> Remove Sonar warnings

- generators/server/files.js
- generators/server/templates/src/main/java/package/config/_OAuth2SsoConfiguration.java
- generators/server/templates/src/main/java/package/gateway/_TokenRelayFilter.java
- generators/server/templates/src/main/java/package/security/oauth2/_AuthorizationHeaderUtil.java
> Make Zuul requests work with OAuth2

- generators/server/index.js
> Do not force JWT when Eureka is selected, see #6519

- generators/server/files.js
- generators/server/templates/_README.md
- generators/server/templates/src/main/java/package/web/rest/_UserResource.java
- generators/server/templates/src/test/java/package/web/rest/_UserResourceIntTest.java
Adding `UserResource` allows many-to-one relations to the `User` object.
> Add UserResource to OAuth Monolith

- generators/server/templates/src/main/java/package/gateway/_TokenRelayFilter.java
> add uaa back to tokenRelay filter

- generators/generator-base.js
> Add resource block as a Map type

- generators/app/index.js
- generators/app/prompts.js
- generators/client/index.js
- generators/client/prompts.js
- generators/generator-base.js
- generators/generator-constants.js
- generators/server/index.js
- generators/server/prompts.js
As per discussion in https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jhipster-dev/Xqwd3hYOmx0/FhJtCzxZBAAJ
This reduces some complexity
> Remove questions for app generation

- generators/server/templates/_gradle.properties
- generators/server/templates/_pom.xml
> upgrade to Spring Boot 1.5.8

- generators/server/templates/src/main/resources/config/_bootstrap.yml
> add consul host and port properties to bootstrap.yml

- generators/server/templates/src/test/java/package/web/rest/_AccountResourceIntTest.java
> Correct UserResourceIntTest with OIDC support

- generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management.component.html
Adding max size parameter to pagination avoid having all pages as clickable links. See https://ng-bootstrap.github.io/#/components/pagination/examples for details.
close #6577
> pagination show at most 5 pages

- generators/entity/templates/server/src/main/java/package/service/_EntityQueryService.java
- generators/entity/templates/server/src/main/java/package/service/dto/_EntityCriteria.java
- generators/entity/templates/server/src/test/java/package/web/rest/_EntityResourceIntTest.java
and add tests for the relation filtering.
> Enable filtering for many-to-many and many-to-one relations too

- generators/app/index.js
- generators/client/index.js
- generators/entity/index.js
- generators/generator-base-private.js
- generators/generator-base.js
- generators/server/index.js
- package-lock.json
For #6372 
Here is a sample blueprint which overrides the client generator https://github.com/hipster-labs/generator-jhipster-sample-blueprint
> WIP: Blueprint support

- generators/server/templates/gradle/_docker.gradle
Just a small update of the gradle docker plugin
> update docker gradle plugin to latest version

- generators/server/templates/src/main/java/package/web/rest/_UserJWTController.java
- generators/server/templates/src/main/java/package/web/rest/_UserResource.java
- generators/server/templates/src/test/java/package/web/rest/_UserJWTControllerIntTest.java
> Declare ResponseEntity class in UserJWTController and UserResource

- generators/client/templates/angular/webpack/_webpack.dev.js
Fix https://github.com/jhipster/generator-jhipster/issues/6126
Solution provided by @ygokirmak
_____
> Fix random failed hot reload

- generators/server/templates/src/test/java/package/web/rest/_UserResourceIntTest.java
sometimes the test are creating multiple users and hose need to have a
unique login and email.
Fixes #6521
> make users login and email to be unique during tests

- generators/server/templates/gradle/_liquibase.gradle
> [BUG-Fix] #6602 Fixed gradle script for generating liquibase changesets

- generators/server/templates/src/main/java/package/web/rest/_AccountResource.java
The closing if statement has a useless semicolon
> Getting rid of useless semicolon

- generators/client/files-angular.js
- generators/client/templates/angular/src/main/webapp/app/_app.module.ts
- generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/_http.provider.ts
- generators/client/templates/angular/src/main/webapp/app/shared/_shared.module.ts
- generators/client/templates/angular/src/main/webapp/app/shared/login/_login.service.ts
Fix #6389
remove the `skipServer` test in http.provider.ts and login.service.ts
Also set to true the default condition for `generator.skipServer`
> Fix the --skip-server option

- generators/server/templates/src/main/docker/_jhipster-registry.yml
> #6612 add default jhipster registry password in server docker compose

- generators/server/templates/src/main/java/package/service/_UserService.java
- generators/server/templates/src/main/java/package/web/rest/_AccountResource.java
- generators/server/templates/src/main/java/package/web/rest/_UserResource.java
ManagedUserVM must not be imported from UserService as it results in a cyclic dependency between packages
On the other hand, it's OK to use UserDTO in the controller layer so it's better to use it instead of ManagedUserVM when possible.
> Remove dependency from service layer to view layer

- generators/server/templates/src/main/java/package/service/_UserService.java
- generators/server/templates/src/main/java/package/web/rest/_AccountResource.java
- generators/server/templates/src/test/java/package/web/rest/_AccountResourceIntTest.java
> Refactor and move OAuth getUser code from AccountResource to UserService

- .travis.yml
- Dockerfile
- generators/generator-constants.js
Fix https://github.com/jhipster/generator-jhipster/issues/6629
But I don't see where to update the documentation, as we always refer to LTS version.
_____
> Upgrade to node 8.9.0 LTS

- generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management-dialog.component.html
The code introduced two consecutive white spaces when there was no validation
> Get rid of white space

- generators/entity/templates/server/src/main/java/package/common/get_all_template.ejs
- generators/entity/templates/server/src/main/java/package/common/search_template.ejs
- generators/entity/templates/server/src/main/java/package/service/_EntityQueryService.java
- generators/entity/templates/server/src/main/java/package/web/rest/_EntityResource.java
- generators/server/templates/_build.gradle
- generators/server/templates/gradle/_liquibase.gradle
- generators/server/templates/src/main/java/package/web/rest/_AuditResource.java
- generators/server/templates/src/main/java/package/web/rest/_UserResource.java
> Miscellaneous little polishing

- generators/server/templates/src/main/java/package/gateway/ratelimiting/_RateLimitingFilter.java
- generators/server/templates/src/main/java/package/repository/_UserRepository.java
- generators/server/templates/src/main/java/package/security/_SecurityUtils.java
- generators/server/templates/src/main/java/package/security/_SpringSecurityAuditorAware.java
- generators/server/templates/src/main/java/package/service/_UserService.java
- generators/server/templates/src/main/java/package/web/rest/_AccountResource.java
- generators/server/templates/src/test/java/package/security/_SecurityUtilsUnitTest.java
- generators/server/templates/src/test/java/package/web/rest/_AccountResourceIntTest.java
> Change return type to Optional for some methods that possibly return null

- generators/server/templates/src/main/java/package/service/_UserService.java
> Fix mapping OIDC family_name to User's lastName field

- Dockerfile
- generators/client/templates/angular/_package.json
- generators/client/templates/angular/src/test/javascript/_karma.conf.js
- generators/client/templates/angularjs/_package.json
- generators/client/templates/angularjs/src/test/javascript/_karma.conf.js
- package-lock.json
> Upgrade chromium headless puppeteer + setup fixes

- generators/server/templates/src/main/java/package/service/_UserService.java
- generators/server/templates/src/main/java/package/web/rest/_AccountResource.java
> Map OIDC picture claim to User imageUrl

- generators/client/templates/angular/src/main/webapp/app/admin/user-management/_user-management-delete-dialog.component.ts
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/_user-management-dialog.component.ts
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/_user-modal.service.ts
- generators/client/templates/angular/src/test/javascript/spec/app/admin/user-management/user-management-detail.component.spec.ts
aligns code in user-modal.service.ts with entity-popup.service.ts
Fix #6593
> fix for console error on user management create dialog

- generators/server/templates/_build.gradle
- generators/server/templates/_pom.xml
@jdubois 
There was some minor polishing merged in master that wasn't in my BOM PR yet...
> Fix polish regressions

- generators/server/files.js
- generators/server/templates/src/main/java/package/client/_AuthorizedUserFeignClient.java
- generators/server/templates/src/main/java/package/client/_FeignClientInterceptor.java
- generators/server/templates/src/main/java/package/client/_OAuth2InterceptedFeignConfiguration.java
- generators/server/templates/src/main/java/package/client/_OAuth2UserClientFeignConfiguration.java
- generators/server/templates/src/main/java/package/client/_UserFeignClientInterceptor.java
- generators/server/templates/src/main/resources/config/_application.yml
fix jhipster/generator-jhipster#6227 and remove _OAuth2InterceptedFeignConfiguration.java useless packages.
> uaa suport  ROPC(resource owner password credentials) grant of OAuth2

- Dockerfile
- generators/client/templates/angular/_package.json
- generators/client/templates/angular/src/test/javascript/_karma.conf.js
- generators/client/templates/angular/src/test/javascript/_protractor.conf.js
- generators/client/templates/angularjs/_package.json
- generators/client/templates/angularjs/src/test/javascript/_karma.conf.js
- generators/client/templates/angularjs/src/test/javascript/_protractor.conf.js
- generators/server/templates/gitignore
Fix https://github.com/jhipster/generator-jhipster/issues/6567
_____
> Switch back to PhantomJS

- generators/client/templates/angular/_package.json
> Fix indentation [ci skip]

- generators/client/templates/angularjs/src/main/webapp/app/services/auth/_auth.jwt.service.js
Related to https://github.com/jhipster/generator-jhipster/pull/6653
The fix was for Angular, but the tests were for AngularJS.
In this PR, I applied the fix for AngularJS too.
_____
> Fix signout when using uaa, traefik and ng1

- generators/server/templates/_build.gradle
- generators/server/templates/_pom.xml
> Remove exclusion (redundant with latest jhipster-dependencies)

- generators/client/templates/angular/src/main/webapp/content/scss/_vendor.scss
Fix https://github.com/jhipster/generator-jhipster/issues/6665
> Fix typo for instructions in vendor.scss [ci skip]

- cli/utils.js
- generators/aws/lib/eb.js
- generators/client/index.js
- generators/client/templates/angular/src/main/webapp/app/admin/metrics/_metrics.component.ts
- generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/_auth-expired.interceptor.ts
- generators/client/templates/angular/src/main/webapp/app/layouts/profiles/_profile.service.ts
- generators/client/templates/angular/src/main/webapp/app/shared/auth/_principal.service.ts
- generators/client/templates/angular/src/test/javascript/_karma.conf.js
- generators/client/templates/angularjs/src/main/webapp/app/admin/metrics/_metrics.controller.js
- generators/entity/index.js
- generators/entity/prompts.js
- generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management-dialog.component.html
- generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management-dialog.component.ts
- generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity.model.ts
- generators/entity/templates/client/angular/src/main/webapp/app/entities/ng_validators.ejs
- generators/entity/templates/server/src/main/java/package/common/field_validators.ejs
- generators/entity/templates/server/src/main/java/package/domain/_Entity.java
- generators/entity/templates/server/src/main/java/package/service/dto/_EntityDTO.java
- generators/entity/templates/server/src/main/java/package/service/mapper/_EntityMapper.java
- generators/entity/templates/server/src/main/resources/config/liquibase/changelog/_added_entity.xml
- generators/entity/templates/server/src/test/java/package/web/rest/_EntityResourceIntTest.java
- generators/heroku/index.js
- generators/server/index.js
- generators/server/templates/_README.md
- generators/upgrade/index.js
- generators/utils.js
- test/utils/utils.js
> use includes instead of indexOf everywhere

- generators/server/templates/_README.md
> Do not display angular-cli in README for microservices [ci skip]

- generators/server/files.js
- generators/server/templates/src/main/java/package/config/_SecurityConfiguration.java
- test/app.spec.js
Generate SecurityConfiguration when choosing monolith + skip user management
FIx https://github.com/jhipster/generator-jhipster/issues/6689
_____
> Fix security configuration skip user management

- CONTRIBUTING.md
- generators/ci-cd/templates/_.gitlab-ci.yml
- generators/ci-cd/templates/_circle.yml
- generators/ci-cd/templates/_travis.yml
- generators/ci-cd/templates/jenkins/_Jenkinsfile
- generators/docker-base.js
- generators/generator-base.js
- generators/server/templates/_README.md
- travis/scripts/05-run.sh
> use mvnw verify instead of mvnw package to execute the verify phase of Maven

- generators/client/templates/angular/_package.json
- generators/client/templates/angular/webpack/_webpack.prod.js
> Adding workbox for sw management

- generators/client/templates/angular/webpack/_webpack.prod.js
See https://github.com/jhipster/generator-jhipster/pull/6716#pullrequestreview-78626345
> Correct another output path, for Gradle

- generators/server/templates/src/main/resources/_logback-spring.xml
- generators/server/templates/src/main/resources/config/_application.yml
> set dynamic log levels configuration in yaml properties

- generators/server/templates/src/main/java/package/config/_LoggingConfiguration.java
This introduced a line break from JHipster 4.10
> Getting rid of a line break

- .travis.yml
- generators/generator-constants.js
> Upgrade to NodeJS 8.9.1 and Yarn 1.3.2

- generators/server/templates/src/main/docker/_Dockerfile
> Improve Docker image cache usage by reordering commands in app template Docker file

- .vscode/launch.json
- CONTRIBUTING.md
- travis/samples/README.md
Debugging JHipster is now as simple as pressing F5 in VSCode. No more complex setups !
> VSCode debugging configuration and docs

- travis/scripts/05-run.sh
Improve Travis tests for Microservices.
Related to https://github.com/jhipster/generator-jhipster/issues/6741
_____
> Travis: curl Microservices

- generators/languages/templates/src/main/webapp/i18n/pl/_global.json
- generators/languages/templates/src/main/webapp/i18n/pl/error.json
- generators/languages/templates/src/main/webapp/i18n/pl/metrics.json
> Updated pl-PL translation

- generators/client/templates/angular/_package.json
- generators/client/templates/angular/src/test/javascript/e2e/admin/_administration.spec.ts
- generators/client/templates/angular/src/test/javascript/spec/app/account/activate/_activate.component.spec.ts
- generators/client/templates/angular/src/test/javascript/spec/app/account/password-reset/finish/_password-reset-finish.component.spec.ts
- generators/client/templates/angular/src/test/javascript/spec/app/account/password-reset/init/_password-reset-init.component.spec.ts
- generators/client/templates/angular/src/test/javascript/spec/app/account/password/_password-strength-bar.component.spec.ts
- generators/client/templates/angular/src/test/javascript/spec/app/account/password/_password.component.spec.ts
- generators/client/templates/angular/src/test/javascript/spec/app/account/register/_register.component.spec.ts
- generators/client/templates/angular/src/test/javascript/spec/app/account/sessions/_sessions.component.spec.ts
- generators/client/templates/angular/src/test/javascript/spec/app/account/settings/_settings.component.spec.ts
- generators/client/templates/angular/src/test/javascript/spec/app/admin/audits/_audits.component.spec.ts
- generators/client/templates/angular/src/test/javascript/spec/app/admin/health/_health.component.spec.ts
- generators/client/templates/angular/src/test/javascript/spec/app/admin/user-management/user-management-detail.component.spec.ts
- generators/client/templates/angular/src/test/javascript/spec/app/shared/login/_login.component.spec.ts
- generators/client/templates/angular/src/test/javascript/spec/helpers/_mock-route.service.ts
- generators/entity-client/files.js
- generators/entity-client/templates/angular/src/main/webapp/app/entities/_entity-management-dialog.component.ts
- generators/entity-client/templates/angular/src/main/webapp/app/entities/_entity-management.component.ts
- generators/entity-client/templates/angular/src/main/webapp/app/entities/_entity-management.route.ts
- generators/entity-client/templates/angular/src/main/webapp/app/entities/pagination-template.ejs
- generators/entity-client/templates/angular/src/test/javascript/e2e/entities/_entity.spec.ts
- generators/entity-client/templates/angular/src/test/javascript/spec/app/entities/_entity-management-detail.component.spec.ts
- generators/entity-client/templates/angular/src/test/javascript/spec/app/entities/_entity-management.component.spec.ts
- generators/entity-client/templates/angular/src/test/javascript/spec/app/entities/_entity-management.service.spec.ts
Related to https://github.com/jhipster/generator-jhipster/issues/6581
> Add entity karma unit tests

- generators/app/index.js
- generators/generator-base.js
> add opencollective appeal

- generators/server/templates/_gradle.properties
- generators/server/templates/_pom.xml
Some polishing, to align versions with the jhipster-dependencies BOM (see also the comments in pom.xml and grade.properties, to see which properties have to be checked with each upgrade to jhipster-dependencies).
> Align versions with jhipster-dependencies 0.10

- generators/server/templates/_pom.xml
> add project basedir on swagger-codegen-maven-plugin

- package-lock.json
- package.json
- yarn.lock
> Updated the JCore dep to v1.4.2

- generators/client/templates/angular/src/main/webapp/app/admin/gateway/_gateway.route.ts
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/_user-management.component.ts
- generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/_auth-expired.interceptor.ts
- generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/_http.provider.ts
- generators/client/templates/angular/src/main/webapp/app/shared/auth/_auth-jwt.service.ts
- generators/client/templates/angular/src/main/webapp/app/shared/login/_login.service.ts
- generators/client/templates/angular/src/main/webapp/app/shared/user/_user.service.ts
- generators/client/templates/angular/src/test/javascript/e2e/account/_account.spec.ts
- generators/client/templates/angular/src/test/javascript/e2e/page-objects/_jhi-page-objects.ts
- generators/client/templates/react/src/main/webapp/app/modules/administration/logs/logs.tsx
- generators/entity-client/templates/angular/src/main/webapp/app/entities/_entity-management.component.ts
- generators/entity-client/templates/angular/src/main/webapp/app/entities/infinite-scroll-template.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/no-pagination-template.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/pagination-template.ejs
- generators/entity-client/templates/angular/src/test/javascript/spec/app/entities/_entity-management-detail.component.spec.ts
- generators/entity-client/templates/angular/src/test/javascript/spec/app/entities/_entity-management.component.spec.ts
- generators/entity-client/templates/angular/src/test/javascript/spec/app/entities/_entity-management.service.spec.ts
- generators/entity/index.js
- generators/generator-base-private.js
- test/generator-base-private.spec.js
Following this PR https://github.com/jhipster/generator-jhipster/pull/6771
It's not finished yet, but a lot of errors should be resolved.
I won't have time to finish until tomorrow, so feel free to merge it.
_____
> Fix entity karma unit tests

- test/templates/import-jdl/jdl.jdl
See https://github.com/jhipster/jhipster-core/commit/7f2e6cec7d7424d943482d540f4d3e7ed9fb24b4#diff-f25ce22a35302e04f1024e8c7f31a711
Related to https://github.com/jhipster/generator-jhipster/pull/6785
_____
> Fix tests for import-jdl, by removing 'for' keyword

- generators/client/templates/react/src/main/webapp/app/modules/administration/configuration/configuration.tsx
> React: Fix config screen

- generators/client/templates/angular/src/main/webapp/app/layouts/navbar/_navbar.component.html
> fix navbar account menu position

- generators/entity-server/templates/src/main/java/package/service/dto/_EntityDTO.java
Fix for this: https://github.com/jhipster/generator-jhipster/issues/6801
> Fix DTO getter issue

- generators/server/templates/src/main/java/package/config/_CacheConfiguration.java
- generators/server/templates/src/main/resources/config/_application-dev.yml
- generators/server/templates/src/main/resources/config/_application-prod.yml
- generators/server/templates/src/test/java/package/config/_WebConfigurerTest.java
require https://github.com/jhipster/jhipster-dependencies/pull/16
require https://github.com/jhipster/jhipster/pull/35
> support Hazelcast Management Center

- generators/server/templates/_build.gradle
- generators/server/templates/_pom.xml
Related to https://github.com/jhipster/jhipster-dependencies/commit/1ac9960a062369bd2e60178f865338c9f2149a94#diff-600376dffeb79835ede4a0b285078036
_____
> Fix Cassandra build, using lz4-java

- generators/server/templates/_gradle.properties
- generators/server/templates/_pom.xml
See http://mapstruct.org/news/2017-10-18-mapstruct-1_2_0_Final-is-out/
> Upgrade to spring-boot 1.5.9 and mapstruct to 1.2.0.Final

- generators/server/templates/src/main/java/package/config/_LoggingConfiguration.java
> skipping only parts of log config when eureka isn't there

- generators/client/templates/react/src/main/webapp/app/modules/login/login-modal.tsx
- generators/client/templates/react/src/main/webapp/app/reducers/authentication.ts
> Fix login error display

- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management-model.tsx
> fix bootstrap style on checkbox (form : edit user)

- generators/client/index.js
- generators/client/templates/angular/src/main/webapp/app/account/activate/_activate.service.ts
- generators/client/templates/angular/src/main/webapp/app/account/password-reset/finish/_password-reset-finish.service.ts
- generators/client/templates/angular/src/main/webapp/app/account/password-reset/init/_password-reset-init.service.ts
- generators/client/templates/angular/src/main/webapp/app/account/password/_password.service.ts
- generators/client/templates/angular/src/main/webapp/app/account/register/_register.service.ts
- generators/client/templates/angular/src/main/webapp/app/account/sessions/_sessions.service.ts
- generators/client/templates/angular/src/main/webapp/app/admin/audits/_audits.service.ts
- generators/client/templates/angular/src/main/webapp/app/shared/auth/_account.service.ts
- generators/client/templates/angular/src/main/webapp/app/shared/user/_user.service.ts
- generators/client/templates/angular/src/test/javascript/spec/app/shared/user/_user.service.spec.ts
- generators/client/templates/angularjs/src/main/webapp/app/services/auth/_account.service.js
- generators/client/templates/angularjs/src/main/webapp/app/services/auth/_activate.service.js
- generators/client/templates/angularjs/src/main/webapp/app/services/auth/_password-reset-finish.service.js
- generators/client/templates/angularjs/src/main/webapp/app/services/auth/_password-reset-init.service.js
- generators/client/templates/angularjs/src/main/webapp/app/services/auth/_password.service.js
- generators/client/templates/angularjs/src/main/webapp/app/services/auth/_register.service.js
- generators/client/templates/angularjs/src/main/webapp/app/services/auth/_sessions.service.js
- generators/client/templates/angularjs/src/main/webapp/app/services/user/_user.service.js
> refactor uaa url prefix

- generators/cleanup.js
> Clean old app.main-aot.ts file

- generators/client/prompts.js
Major contribution ;) to #6789
> Change to "Angular 5" in prompt  [ci skip]

- generators/server/templates/gradle/_profile_dev.gradle
- generators/server/templates/gradle/_profile_prod.gradle
Those are not needed since changes where introduced in #6828
ping @jdubois
> remove unneeded logback level var in gradle build 

- generators/client/templates/angular/src/main/webapp/content/scss/__bootstrap-variables.scss
> Fix variable names for BS4 colors

- generators/client/index.js
- generators/client/templates/angular/src/main/webapp/app/admin/audits/_audits.service.ts
- generators/client/templates/angular/src/main/webapp/app/admin/configuration/_configuration.service.ts
- generators/client/templates/angular/src/main/webapp/app/admin/health/_health.service.ts
- generators/client/templates/angular/src/main/webapp/app/admin/logs/_logs.service.ts
- generators/client/templates/angular/src/main/webapp/app/admin/metrics/_metrics.service.ts
> prefix URL with SERVER_API_URL if required

- generators/client/templates/angular/src/test/javascript/spec/app/account/password-reset/finish/_password-reset-finish.component.spec.ts
Related to https://github.com/jhipster/generator-jhipster/issues/6581
As I'm still learning Angular, it will not increase a lot the coverage but it's better than nothing...
_____
> Improve tests for password-reset-finish.component

- README.md
> Fix link for Open Collective [ci skip]

- generators/server/templates/_build.gradle
> Upgrade Gradle APT Plugin to 0.13

- generators/server/templates/_README.md
> Fix layout of service worker code sample in README [ci skip]

- package-lock.json
- package.json
- yarn.lock
Fixes [this issue](https://github.com/jhipster/jhipster-core/issues/169) from the JCore issue tracker
> Updated the JCore dep's version to v1.4.3

- generators/client/templates/angular/src/main/webapp/app/admin/metrics/_metrics.component.html
- generators/client/templates/angular/src/main/webapp/app/shared/auth/_user-route-access-service.ts
- generators/entity-client/templates/angular/src/main/webapp/app/entities/_entity-management.component.html
- generators/server/templates/_pom.xml
- generators/server/templates/src/main/java/package/domain/_PersistentAuditEvent.java
- generators/server/templates/src/test/java/package/web/rest/_TestUtil.java
> Fix some indentation

- generators/client/templates/angular/src/main/webapp/app/admin/user-management/_user-management-detail.component.html
Use jhi-boolean component as described here https://github.com/jhipster/ng-jhipster/pull/50 
and documented here https://github.com/jhipster/ng-jhipster/pull/54
> use jhi-boolean component in user management detail

- generators/server/templates/_build.gradle
- generators/server/templates/gradle/_liquibase.gradle
> Fix 'toURL' is deprecated warning

- generators/client/templates/angularjs/src/main/webapp/app/components/util/_jhi-item-count.directive.js
> remove translate attributes when not using i18n (angularJS)

- generators/upgrade/index.js
- test/cli.spec.js
- fix #6864
- correct test cli on windows
> Directories with space are not working (upgrade sub-generator)

- generators/entity-client/templates/angular/src/test/javascript/spec/app/entities/_entity-management.service.spec.ts
Applying same logic as in:
https://github.com/jhipster/generator-jhipster/blob/master/generators/entity-client/templates/angular/src/main/webapp/app/entities/_entity.service.ts#L28-L30
https://github.com/jhipster/generator-jhipster/blob/master/generators/entity-client/templates/angular/src/main/webapp/app/entities/_entity.service.ts#L42
> fix entity service test in gateway if entity belongs to microservice

- generators/client/templates/react/_package.json
- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management-model.tsx
The new version of availity-reactstrap-validation fixes the issue when selecting value in select form (react).
The commit, which fixes, is : 
https://github.com/Availity/availity-reactstrap-validation/commit/59fc2dbf67b6e8265c0fc744aeed56a3cf23453a
> Update availity-reactstrap-validation version to fix issue in selecting value (for react)

- generators/client/templates/react/src/main/webapp/app/reducers/authentication.ts
When you logout, the page doesn't display the logout page even if the user is logout.
> Fix display after calling logout in react app

- generators/languages/templates/src/main/webapp/i18n/de/_global.json
This is a pretty trivial change, I just fixed the German translation of "Open".
> Fix German translation of entity.action.open.

- generators/client/templates/react/_package.json
- generators/client/templates/react/src/main/webapp/app/config/constants.ts
- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management-detail.tsx
- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management.tsx
REACT : 
Format dates like 'DD/MM/YY hh:mm' in two screens (user-management)
> Format dates 'DD/MM/YY hh:mm' in user management screens (react)

- generators/client/templates/angular/_package.json
- generators/client/templates/react/_package.json
Fix PR #6880
Tested with angular on:
- Windows 10: cmd, powershell and git bash
- Ubuntu 17.10 : bash
- Mac OSX High Sierra
For React on windows 10 only.
> Lint tested on most platforms

- generators/client/templates/angular/src/test/javascript/spec/_test.module.ts
> Fixed #6869, incorrect import when using custom prefix

- generators/client/templates/angular/src/main/webapp/app/account/register/_register.component.html
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/_user-management-dialog.component.html
- generators/client/templates/angularjs/src/main/webapp/app/account/register/_register.html
- generators/client/templates/angularjs/src/main/webapp/app/admin/user-management/_user-management-dialog.html
- generators/languages/templates/src/main/webapp/i18n/en/_global.json
- generators/languages/templates/src/main/webapp/i18n/en/register.json
- generators/server/files.js
- generators/server/templates/src/main/java/package/config/_CacheConfiguration.java
- generators/server/templates/src/main/java/package/config/_Constants.java
- generators/server/templates/src/main/java/package/repository/_UserRepository.java
- generators/server/templates/src/main/java/package/security/_DomainUserDetailsService.java
- generators/server/templates/src/main/java/package/service/_SocialService.java
- generators/server/templates/src/main/java/package/service/_UserService.java
- generators/server/templates/src/main/java/package/web/rest/vm/_LoginVM.java
- generators/server/templates/src/test/java/package/security/_DomainUserDetailsServiceIntTest.java
- generators/server/templates/src/test/java/package/service/_SocialServiceIntTest.java
> support login with both email and username

- generators/server/templates/src/main/java/package/domain/_SocialUserConnection.java
With a new generetion with the mongod and social login option : 
```
> Task :compileJava
/Users/tk/social-active/src/main/java/fr/socialactive/app/domain/SocialUserConnection.java:97: error: cannot find symbol
return id;
^
symbol:   variable id
location: class SocialUserConnection
/Users/tk/social-active/src/main/java/fr/socialactive/app/domain/SocialUserConnection.java:101: error: cannot find symbol
this.id = id;
^
symbol: variable id
/Users/tk/social-active/src/main/java/fr/socialactive/app/domain/SocialUserConnection.java:203: error: cannot find symbol
if (!id.equals(user.id)) {
^
symbol:   variable id
location: variable user of type SocialUserConnection
/Users/tk/social-active/src/main/java/fr/socialactive/app/domain/SocialUserConnection.java:203: error: cannot find symbol
if …
```
> fix error compile use mongodb and social login

- .travis.yml
- generators/client/index.js
- generators/server/templates/_build.gradle
- travis/samples/ms-ngx-gateway-consul-clustered/.yo-rc.json
- travis/samples/ngx-couchbase/.yo-rc.json
- travis/samples/ngx-h2mem-social-ws-nol2/.yo-rc.json
- travis/samples/ngx-mariadb-oauth2-sass-infinispan/.yo-rc.json
- travis/samples/ngx-mariadb-oauth2-sass-nocache/.yo-rc.json
- travis/samples/ngx-mongodb-kafka-cucumber/.yo-rc.json
Following this PR https://github.com/jhipster/generator-jhipster/pull/6876 and comments from Deepu.
_____
> Travis improvements review

- generators/entity/prompts.js
> fix #5629 typos

- generators/client/templates/angular/_package.json
It should fix https://github.com/jhipster/generator-jhipster/issues/6910
Tested with Yarn and NPM : see my comments in the code for details
_____
> Use uglify-es 3.2.2 to solve critical transitive dependency bug

- generators/client/templates/react/src/main/webapp/app/modules/administration/logs/logs.tsx
React : 
Finalize log page with some styles and translations
> Log page : style and translation (react)

- generators/server/templates/_gradle.properties
- generators/server/templates/gradle/_liquibase.gradle
Coud not execute liquibase tasks
Fix #6913
> Add version for liquibase-hibernate5 with gradle

- test/utils.spec.js
adding more tests to utils.spec.js
> add more tests to utils.spec.js

- generators/client/templates/angular/src/main/webapp/app/admin/user-management/_user-management-detail.component.html
- generators/server/templates/_build.gradle
- generators/server/templates/_pom.xml
- generators/server/templates/gradle/_profile_prod.gradle
- generators/server/templates/src/main/resources/config/_application.yml
Based on @raphaelbrugier #6788 
Sorry, I have closed the previous PR to do some small changes. @raphaelbrugier you will keep attribution for your commit.
Before merging let's make sure there is not problem with the gradle build.
> Add git information to /info endpoint

- generators/client/templates/angular/src/test/javascript/spec/app/admin/audits/_audits.component.spec.ts
> Fix month in audit component tests

- generators/generator-constants.js
- generators/server/templates/src/main/docker/_jhipster-registry.yml
> Update the jhipster-registry to v3.2.4 

- generators/entity-client/templates/angular/src/test/javascript/e2e/entities/_entity.spec.ts
- travis/samples/.jhipster/Place.json
Fix https://github.com/jhipster/generator-jhipster/issues/6919
> Fix unused import in e2e tests for entities with byte+text

- generators/client/templates/react/src/main/webapp/app/modules/administration/configuration/configuration.tsx
React : 
Finalize the configuration screen (display, css, translate, order)
> Finalize configuration screen (react)

- generators/server/templates/src/main/java/package/config/_SecurityConfiguration.java
Remove bean as it is already configured by Spring Boot
> Remove Bean SecurityEvaluationContextExtension

- generators/client/templates/react/src/main/webapp/app/config/constants.ts
- generators/client/templates/react/src/main/webapp/app/modules/administration/metrics/metrics.tsx
React : 
Format the numbers on the metrics page (same display that angular app).
> Format numbers on metrics page (react)

- generators/entity/index.js
fix https://github.com/jhipster/generator-jhipster/issues/6930
_____
> Fix entities for nodatabase with Gateway

- generators/docker-prompts.js
- generators/kubernetes/prompts.js
- generators/kubernetes/templates/_deployment.yml
- generators/kubernetes/templates/db/_couchbase.yml
- generators/openshift/templates/_deployment.yml
- generators/openshift/templates/db/_couchbase.yml
couchbase generator - initial commit - k8s and oc
> add couchbase generator - k8s and openshift

- generators/client/templates/angular/src/main/webapp/app/_polyfills.ts
> Improve IE compatibility for javascript function includes

- generators/generator-base-private.js
- test/generator-base-private.spec.js
The special cases are:
- Nil and empty strings
- Double-quotes (replaced by `\"`)
- Empty-when-trimmed lines
Also added tests
Fixes #6918
> Updated the #formatAsApiDescription method to deal with special cases

- generators/client/templates/angularjs/src/test/javascript/_protractor.conf.js
Similar PR: https://github.com/jhipster/generator-jhipster/pull/6847 https://github.com/jhipster/generator-jhipster/pull/6474
It should definitely fix this, for AngularJS. I think we did this for Win32 :)
Can someone test it on Windows plz ?
- generate project
- `./mvnw`
- `gulp itest`
Here my `.yo-rc.json` file:
```yaml
{
"packageName": "io.github.pascalgrimaud"
},
"jhipsterVersion": "4.13.3",
"baseName": "jhipster",
"packageName": "io.github.pascalgrimaud",
"packageFolder": "io/github/pascalgrimaud",
"authenticationType": "jwt",
"cacheProvider": "ehcache",
"enableHibernateCache": true,
"websocket": false,
"devDatabaseType": "h2Disk",
"prodDatabaseType": "mysql",
"searchEngine": false,
"messageBroker": …
```
> Fix selenium chromedriver for AngularJS

- generators/client/templates/angular/src/main/webapp/app/_vendor.ts
This PR is for fix #6975 and part of #6899 
> missing imports in vendor.ts

- generators/client/templates/angular/_package.json
- generators/client/templates/angular/webpack/_webpack.prod.js
- generators/entity-client/templates/react/src/main/webapp/app/entities/_entity.reducer.ts
- generators/entity-client/templates/react/src/main/webapp/app/entities/_entity.tsx
React 
Add the field search when the option **elastic search** is taken.
Pagination and sort are not handle on this PR.
> React - Field search -Elastic search option (no pagination and sort)

- generators/entity-client/templates/react/src/main/webapp/app/entities/_entity-detail.tsx
- generators/entity-client/templates/react/src/main/webapp/app/entities/_entity-dialog.tsx
- generators/entity-client/templates/react/src/main/webapp/app/entities/_entity.tsx
React : 
Handle all the types of relationships for the entities
PR **finished**
> React : handle relationships for the entities

- .travis.yml
- travis/scripts/00-install-jhipster.sh
> Travis: fix URL and path when cloning generator-jhipster [ci skip]

- generators/entity-server/templates/src/main/java/package/common/get_template.ejs
- generators/entity-server/templates/src/main/java/package/repository/_EntityRepository.java
- generators/entity-server/templates/src/test/java/package/web/rest/_EntityResourceIntTest.java
- generators/server/templates/_build.gradle
- generators/server/templates/_pom.xml
- generators/server/templates/gradle/_profile_dev.gradle
- generators/server/templates/src/main/java/package/config/_CloudDatabaseConfiguration.java
- generators/server/templates/src/main/java/package/config/_DatabaseConfiguration.java
- generators/server/templates/src/main/java/package/config/_ElasticsearchConfiguration.java
- generators/server/templates/src/main/java/package/config/_SecurityConfiguration.java
- generators/server/templates/src/main/java/package/config/cassandra/_CassandraConfiguration.java
- generators/server/templates/src/main/java/package/domain/_User.java
- generators/server/templates/src/main/java/package/repository/_PersistentTokenRepository.java
- generators/server/templates/src/main/java/package/repository/_UserRepository.java
- generators/server/templates/src/main/java/package/service/dto/_UserDTO.java
- generators/server/templates/src/main/resources/config/_application-dev.yml
- generators/server/templates/src/test/java/package/security/oauth2/_OAuth2AuthenticationServiceTest.java
- generators/server/templates/src/test/java/package/web/rest/_AccountResourceIntTest.java
- generators/server/templates/src/test/java/package/web/rest/_LogsResourceIntTest.java
- generators/server/templates/src/test/java/package/web/rest/_ProfileInfoResourceIntTest.java
- generators/server/templates/src/test/java/package/web/rest/errors/_ExceptionTranslatorIntTest.java
- generators/server/templates/src/test/resources/config/_application.yml
- travis/build-samples.sh
- travis/scripts/05-run.sh
> Fix spring boot 2

- generators/kubernetes/files.js
- generators/kubernetes/index.js
- generators/kubernetes/templates/_deployment.yml
- generators/kubernetes/templates/console/_jhipster-console.yml
- generators/kubernetes/templates/console/_jhipster-dashboard-console.yml
- generators/kubernetes/templates/console/_jhipster-elasticsearch.yml
- generators/kubernetes/templates/console/_jhipster-logstash.yml
- generators/kubernetes/templates/console/_jhipster-zipkin.yml
- generators/openshift/index.js
- generators/openshift/templates/monitoring/_jhipster-monitoring.yml
- test/kubernetes.spec.js
elk update to use jhipster-import-dashboards
> k8s and oc - elk update to use jhipster-import-dashboards

- generators/client/templates/angularjs/src/main/webapp/app/components/util/_data-util.service.js
Fix for https://github.com/jhipster/generator-jhipster/issues/6988
> added fix as its already used in angularx for opening blobs

- generators/client/templates/angularjs/src/main/webapp/app/components/util/_data-util.service.js
> fixing the data-utils issue

- generators/client/templates/angular/_package.json
- generators/client/templates/react/_package.json
Fix github security alert on marked
> Upgrade webpack-notifier

- package-lock.json
- package.json
- yarn.lock
Fixes two issues:
- JDL Export: patterns are now correctly exported
- no more `Cannot set property 'microserviceName' of undefined` (huge thanks to @ruddell for this one)
> Updated JCore to v1.4.4

- generators/client/templates/angular/_package.json
- generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/_notification.interceptor.ts
- generators/client/templates/angular/src/test/javascript/spec/app/admin/audits/_audits.component.spec.ts
- generators/client/templates/angular/src/test/javascript/spec/app/admin/user-management/_user-management.component.spec.ts
> updating angular and bootstrap to the latest version

- generators/server/templates/src/main/java/package/security/oauth2/_OAuth2CookieHelper.java
- generators/server/templates/src/test/java/package/security/oauth2/_OAuth2CookieHelperTest.java
Fix #6986
Tested by generating a UAA and Gateway and logging in from http://127.0.0.1:8080/
> allow uaa cookie generation using ip

- generators/heroku/index.js
- package.json
- test/heroku.spec.js
Making an offering to the CI Gods that this passes on Travis.
> Added simple Heroku tests

- generators/client/templates/angular/src/main/webapp/app/_app-routing.module.ts
- generators/client/templates/angular/src/main/webapp/app/_app.constants.ts
I think we had routing debugging in angular 1 using angular-ui router,  with this PR I propose to do the same in Angular 5.
Maybe too verbose ?
> Enable angular router tracing in dev mode

- generators/heroku/index.js
See https://github.com/jhipster/generator-jhipster/pull/7045#issuecomment-360484198
> Force heroku-cli-deploy plugin install, so it never errors

- generators/server/templates/src/main/java/package/config/_OAuth2SsoConfiguration.java
> Fix OAuth microservices compile error

- generators/client/templates/angular/_package.json
> Angular CLI upgrade to 1.6.6

- generators/client/files-angular.js
- generators/client/templates/angular/src/main/webapp/app/admin/_admin.module.ts
- generators/client/templates/angular/src/main/webapp/app/admin/audits/_audits.component.html
- generators/client/templates/angular/src/main/webapp/app/admin/audits/_audits.component.ts
- generators/client/templates/angular/src/main/webapp/app/admin/audits/_audits.route.ts
- generators/client/templates/angular/src/main/webapp/app/admin/audits/_audits.service.ts
- generators/client/templates/angular/src/test/javascript/spec/app/admin/audits/_audits.component.spec.ts
- generators/client/templates/angular/src/test/javascript/spec/app/admin/audits/_audits.service.spec.ts
- generators/client/templates/react/src/main/webapp/app/config/constants.ts
- generators/client/templates/react/src/main/webapp/app/modules/administration/audits/audits.tsx
- generators/client/templates/react/src/main/webapp/app/reducers/administration.ts
- generators/client/templates/react/src/main/webapp/app/shared/layout/header/header.tsx
- Use same mechanism as user management
- Audit table is not sortable by Extra data
- Cassandra is ignored as audits are not enabled for it
Fix #6974
> Rework on Audits components

- generators/client/templates/angular/_package.json
> Upgrade ng-bootstrap to 1.0.0

- generators/server/templates/src/main/java/package/config/_WebConfigurer.java
- generators/server/templates/src/test/java/package/config/_WebConfigurerTest.java
> Remove unused HazelcastInstance

- generators/client/templates/angular/src/main/webapp/app/account/social/_social-auth.component.ts
> enable remember-me when authenticating through social login

- generators/import-jdl/index.js
- package-lock.json
- package.json
- yarn.lock
From v1.4.4 to v1.4.5
Also updated the code to use the new methods (the former ones being
deprecated), the behavior is the same.
> Updated the JCore dependency

- generators/entity-client/templates/angular/src/main/webapp/app/entities/_entity.model.ts
- generators/entity-server/templates/src/main/java/package/service/dto/_EntityDTO.java
Model should contain both id and other entity field name when using DTOs
Fix #7093
> Generate missing related entity field in ng model when using DTOs

- generators/docker-compose/templates/_jhipster-registry.yml
- generators/server/templates/src/main/docker/_app.yml
- generators/server/templates/src/main/docker/_jhipster-registry.yml
- generators/server/templates/src/main/java/package/config/_MicroserviceSecurityConfiguration.java
- generators/server/templates/src/main/resources/config/_application.yml
> Change OAuth for microservices to use jwk.key-set-uri

- generators/docker-compose/templates/_jhipster-registry.yml
- generators/server/templates/src/main/docker/_app.yml
- generators/server/templates/src/main/docker/_jhipster-registry.yml
> Add clientId and clientSecret for Docker

- generators/entity-server/templates/src/main/java/package/common/get_all_template.ejs
- generators/entity-server/templates/src/main/java/package/repository/_EntityRepository.java
- generators/entity-server/templates/src/main/java/package/service/_EntityService.java
- generators/entity-server/templates/src/main/java/package/service/impl/_EntityServiceImpl.java
- generators/entity-server/templates/src/main/java/package/web/rest/_EntityResource.java
- generators/entity-server/templates/src/test/java/package/web/rest/_EntityResourceIntTest.java
Fix for this: https://github.com/jhipster/generator-jhipster/issues/6791
> Use Pageable in many-to-many relationship

- generators/entity-client/templates/angular/src/main/webapp/app/entities/_entity.model.ts
- generators/entity-server/templates/src/main/java/package/service/dto/_EntityDTO.java
Model should contain both id and other entity field name when using DTOs
Fix #7093 for JHipster v5
I'll work later in another PR on extracting most code from template to share it with React as I first want to enable ng template checking option.
> Fix #7093 for JHipster 5

- generators/client/templates/angular/src/main/webapp/app/account/password-reset/init/_password-reset-init.component.html
- generators/server/templates/src/main/java/package/config/_WebConfigurer.java
> Using constants for Charset

- generators/client/templates/angular/_package.json
- generators/client/templates/angular/_tsconfig-aot.json
- generators/client/templates/angular/_tsconfig.json
- generators/client/templates/react/_package.json
- generators/client/templates/react/_tsconfig.json
Fix for #7084 for angular and react codebase
> Use tslib to reduce js artifacts size

- generators/client/templates/angular/_package.json
- generators/client/templates/angular/_tsconfig-aot.json
Now that related issues have been merged on master, we can enable this useful option.
I have tested it on few samples but not all, let's wait for Travis ;)
Fix #7103
> Enable fullTemplateTypeCheck for angular compiler

- README.md
> Remove ng1 build in README [ci skip]

- generators/server/templates/src/main/java/package/config/_WebConfigurer.java
> add decoding for static asset path

- generators/client/templates/angular/src/main/webapp/app/admin/user-management/_user-management-dialog.component.ts
- generators/client/templates/angular/src/main/webapp/app/core/auth/_principal.service.ts
- generators/client/templates/angular/src/main/webapp/app/core/user/_user.model.ts
- generators/client/templates/angular/src/main/webapp/app/shared/auth/_has-any-authority.directive.ts
- generators/entity-server/templates/src/main/java/package/repository/_EntityRepository.java
- generators/entity-server/templates/src/main/java/package/service/_EntityQueryService.java
- generators/entity-server/templates/src/main/java/package/service/dto/_EntityDTO.java
- generators/entity-server/templates/src/main/java/package/service/impl/_EntityServiceImpl.java
- generators/server/templates/src/main/java/package/config/_SecurityConfiguration.java
- generators/server/templates/src/main/java/package/service/_UserService.java
This should reduce the "code smell" count by at around 60.  I also updated several ejs conditions to use `<%_` instead of `<%`
> sonar code smell fixes

- generators/server/templates/src/main/java/package/client/AuthorizedFeignClient.java.ejs
- generators/server/templates/src/main/java/package/client/AuthorizedUserFeignClient.java.ejs
- generators/server/templates/src/main/java/package/config/FeignConfiguration.java.ejs
> Fix package netflix.feign renamed to openfeign

- generators/server/templates/src/main/resources/config/application.yml.ejs
- generators/server/templates/src/test/resources/config/application.yml.ejs
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0.0-RC1-Release-Notes#jackson
> remove jackson.serialization.write_dates_as_timestamps property

- generators/server/files.js
- generators/utils.js
Fix https://github.com/jhipster/generator-jhipster/issues/7163
> Fix ejs noi18n and nodatabase

- generators/server/templates/pom.xml.ejs
See https://github.com/jhipster/generator-jhipster/commit/d7f3288c698937c921a28e36907a24db186d85d5#commitcomment-27773126
> Upgrade to Spring Boot 2.0.0.RC2 for Maven

- generators/server/files.js
- generators/server/templates/src/main/resources/banner-react.txt
Useless pull request, but I think React deserves this ;)
> Add specific banner for React [ci skip]

- generators/utils.js
See @deepu105's comment: https://github.com/jhipster/generator-jhipster/pull/7169/files#r170464851
> Improve the fix for ejs noi18n

- generators/client/templates/angular/_package.json
- generators/client/templates/angular/webpack/_webpack.prod.js
> fixing production build failure

- generators/client/templates/angular/src/main/webapp/app/admin/configuration/configuration.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/configuration/configuration.service.ts.ejs
See https://github.com/jhipster/jhipster-registry/issues/242#issuecomment-368666128 for details
The configuration screen will displayed this missing part (`/management/env`):
> Fix configuration page for Spring Boot 2

- generators/server/templates/build.gradle.ejs
This is to support https://github.com/jhipster/jhipster-kotlin/pull/20. Welcome to any more "cleaner" alternatives.
> Added a fix to allow the addition of kotlin class files to the classpath

- generators/entity-client/templates/angular/src/test/javascript/spec/app/entities/entity-management-dialog.component.spec.ts.ejs
- generators/entity-client/templates/angular/src/test/javascript/spec/app/entities/entity-management.component.spec.ts.ejs
> Remove unnecessary boilerplate code in unit tests

- generators/client/templates/angular/package.json.ejs
> upgrade ngtools & webpack-cli to latest version

- generators/entity-client/index.js
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity.model.ts.ejs
- generators/generator-base-private.js
- test/generator-base-private.spec.js
Refactor Angular entity.model.ts.ejs template so that it gets simpler to maintain and test, and also to share common code with React.
> Extract functions from entity model template

- generators/docker-compose/templates/jhipster-registry.yml.ejs
- generators/generator-constants.js
- generators/rancher-compose/templates/docker-compose.yml.ejs
- generators/server/files.js
- generators/server/templates/src/main/docker/jhipster-registry.yml.ejs
- generators/server/templates/src/main/resources/config/application.yml.ejs
Related to https://github.com/jhipster/jhipster-registry/pull/247
Fix https://github.com/jhipster/generator-jhipster/issues/7218
> Fix OAuth2 for Microservice

- generators/generator-constants.js
> Upgrade to Yarn 1.5.1 and NPM 5.7.1

- generators/server/files.js
> Make redirect back to :9000 work on gateway

- generators/entity/prompts.js
> properly validate enum class names and values

- generators/client/templates/react/src/test/javascript/karma.conf.js.ejs
> use correct build directory for react karma test results

- generators/client/templates/angular/tslint.json.ejs
> align tslint rules with prettier output

- generators/client/templates/react/src/main/webapp/app/modules/account/settings/settings.tsx.ejs
> Add a missing translation

- generators/client/templates/react/src/main/webapp/app/modules/login/login-modal.tsx.ejs
Add focus on username input in login modal and clickable remember text 
> add convenience in React login modal

- generators/server/index.js
- generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs
- generators/server/templates/src/main/java/package/service/SocialService.java.ejs
- generators/server/templates/src/main/java/package/service/UserService.java.ejs
- generators/server/templates/src/test/java/package/service/SocialServiceIntTest.java.ejs
- generators/server/templates/src/test/java/package/web/rest/UserResourceIntTest.java.ejs
- generators/server/templates/src/test/resources/config/application.yml.ejs
Fix #6968
- clear cache and delete users between tests in SocialServiceIntTest
- factor out cacheManagerIsAvailable into a server generator variable
---
> fix tests for mongo+social

- generators/client/templates/react/src/test/javascript/spec/app/modules/administration/user-management/user-management.reducer.spec.ts.ejs
> add tests for user-management reducer actions

- generators/client/files-react.js
- generators/client/templates/react/src/main/webapp/app/app.css.ejs
- generators/client/templates/react/src/main/webapp/app/app.scss.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/metrics/metrics-modal.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/metrics/thread-item.tsx.ejs
> fix React thread dump modal in metrics page

- generators/client/templates/react/src/main/webapp/app/modules/account/register/register.tsx.ejs
> fix React register page when no i18n

- generators/kubernetes/index.js
- generators/kubernetes/templates/db/couchbase.yml.ejs
- generators/kubernetes/templates/db/mongodb.yml.ejs
- generators/kubernetes/templates/deployment.yml.ejs
- test/kubernetes.spec.js
- mongo and couch dbs' deployment object to statefulset
- replica config for mongo and couch dbs'
> replica config - mongo and couch db

- generators/server/templates/src/main/java/package/config/CacheConfiguration.java.ejs
- generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs
> Fix compile issue with React

- .travis.yml
- generators/generator-constants.js
- travis/scripts/04-tests.sh
- travis/scripts/05-run.sh
- travis/scripts/06-sonar.sh
- upgrade NPM to 8.10.0
- log output to OFF for backend tests
- no need to relaunch tests before Sonar analyze
- no retry Protractor tests when it failed
_____
> Minor Travis improvements

- generators/client/templates/react/src/main/webapp/app/modules/administration/metrics/metrics-modal.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/metrics/metrics.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management-dialog.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management.reducer.ts.ejs
- center value in metrics progress bars
- fix activate checkbox alignement in user management modals
- reset create/edit user modal when switching between both (remove id row when creating user)
> improve React metrics progress bars display + fix user mngmt modals

- generators/client/templates/angular/src/main/webapp/app/admin/configuration/configuration.component.html.ejs
> Fix configuration page which is not responsive

- generators/client/templates/react/src/main/webapp/app/config/constants.ts
- generators/entity-client/templates/react/src/main/webapp/app/entities/_entity-dialog.tsx
- generators/entity-client/templates/react/src/main/webapp/app/entities/react_validators.ejs
React : PR in progress
Handle validations for the entities forms
> React : Validations forms entities

- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.reducer.ts.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs
> Add a simple error alert when an entity creation, update or deletion fails

- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management.tsx.ejs
> React : Add an onClick function to be able to easily toggle user activation

- generators/client/templates/angular/package.json.ejs
- generators/client/templates/react/package.json.ejs
See the ticket: https://github.com/jhipster/generator-jhipster/issues/7031
See the commit: https://github.com/jhipster/generator-jhipster/commit/407c71c5b7f885348ba2c39af4468c9801e90ac7
_____
> Remove the fix for source-map

- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-dialog.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.reducer.ts.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs
> add React sorting and pagination with links for entities

- generators/server/templates/gradle.properties.ejs
- generators/server/templates/pom.xml.ejs
Needed new version of jhipster-dependencies: See https://github.com/jhipster/jhipster/pull/48
> Update Spring Platform to Cairo-RC1, dependencies and plugins versions

- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-dialog.tsx.ejs
> React : Fix entity dialog

- generators/client/templates/react/src/main/webapp/app/modules/administration/configuration/configuration.tsx.ejs
> React : configuration page fix

- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-dialog.tsx.ejs
> React : Fix entity User relationship

- generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
- generators/entity-server/templates/src/main/java/package/domain/imports.ejs
- generators/entity/index.js
Improve JSon serialization on bidirectional relationships
read other relationship field name and provide it in @JsonIgnoreProperties
Fix #6793
> Improve JSon serialization on bidirectional relationships

- generators/server/templates/src/main/java/package/config/UaaConfiguration.java.ejs
> Fixed JHipster UAA does not work on the master branch #7301

- generators/server/templates/src/main/java/package/config/MicroserviceSecurityConfiguration.java.ejs
> Add Authorization header request matcher for microservices

- .travis.yml
- travis/scripts/00-install-jhipster.sh
- travis/scripts/03-replace-version-generated-project.sh
> Travis: rework with the merge of jhipster-dependencies+jhipster-server

- generators/client/index.js
When generating a gateway, there is a error message in console, because the `serviceDiscoveryType` is not defined:
```
______________________________________________________________________________
? Which *type* of application would you like to create? Microservice gateway
? What is the base name of your application? gateway
? As you are running in a microservice architecture, on which port would like your server to run? It should be unique to avoid port conflicts. 8080
? What is your default Java package name? io.github.pascalgrimaud
? Which service discovery server do you want to use? JHipster Registry (uses Eureka, provides Spring Cloud Config support and monitoring dashboards)
? Which *type* of authentication would you like to use? OAuth 2.0 / OIDC Authentication (stateful, works …
```
> Fix undefined serviceDiscoveryType

- generators/client/templates/angular/webpack/webpack.common.js.ejs
> fix warning due to angular system import

- generators/client/files-react.js
- generators/client/templates/react/src/main/webapp/app/shared/util/entity-utils.ts.ejs
- generators/client/templates/react/src/test/javascript/spec/app/shared/util/entity-utils.spec.ts.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-dialog.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.reducer.ts.ejs
> React: Fix entity enum and relationship dialog

- generators/server/templates/pom.xml.ejs
Depends on https://github.com/jhipster/jhipster/pull/52
> Update jacoco-maven-plugin to 0.8.1

- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs
Fix a plural that I forgot in my last PR.
> React : Plural bug fix

- generators/client/templates/react/src/main/webapp/app/shared/reducers/authentication.ts.ejs
> Fix React uaa auth

- generators/server/templates/pom.xml.ejs
> fix instructions for continuous compilation in pom.xml

- generators/client/templates/react/package.json.ejs
> Update @types/react to fix react build issue

- generators/generator-base.js
> Fix getEntityJson in generator-base to read entity json files in the correct directory when using microservices

- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management-dialog.tsx.ejs
> Fix react user management modal

- generators/entity/index.js
> Fix undefined clientRootFolder

- generators/kubernetes/templates/registry/application-configmap.yml.ejs
- generators/kubernetes/templates/registry/jhipster-registry.yml.ejs
- generators/openshift/templates/registry/application-configmap.yml.ejs
- generators/openshift/templates/registry/jhipster-registry.yml.ejs
> Use the new registry's spring_security_user_password prop

- generators/client/templates/react/src/main/webapp/app/app.tsx.ejs
I think that would be an improvement because the current position is hiding useful buttons in the navbar.
> React : Change toast position

- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/index.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management-delete-dialog.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management-dialog.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management.reducer.ts.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-delete-dialog.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-dialog.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/index.tsx.ejs
> Remove React entity CRUD dialogs

- generators/client/templates/angular/package.json.ejs
- generators/client/templates/react/package.json.ejs
- travis/scripts/05-run.sh
Fix https://github.com/jhipster/generator-jhipster/issues/7388
> Fix random e2e failures with gecko to false

- generators/info/index.js
> Remove bower and gulp from jhipster info as ng1 has been removed

- generators/entity-server/templates/src/main/java/package/service/dto/EntityDTO.java.ejs
Follow [#7312](https://github.com/jhipster/generator-jhipster/issues/7312)
- [X ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [X ] Tests are added where necessary
- [X ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed
> DTO toString  X to One method

- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs
> Fix React entity redirect

- generators/server/templates/src/main/java/package/service/UserService.java.ejs
> Fix regression on oauth2 access_token forwarding from gateway to microservices

- generators/client/templates/react/src/main/webapp/app/routes.tsx.ejs
> User with only admin role should have access to account details

- generators/client/templates/react/src/main/webapp/app/shared/util/entity-utils.ts.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs
I don't think that this is the best way to do it. I think we should do something about that code duplication.
> React: Fix many to many relationship

- .vscode/launch.json
- generators/app/index.js
- generators/client/index.js
- generators/entity-client/index.js
- generators/entity-i18n/index.js
- generators/entity-server/index.js
- generators/entity/index.js
- generators/generator-base-private.js
- generators/generator-base.js
- generators/server/files.js
- generators/server/index.js
- travis/samples/app-sample-dev/.yo-rc.json
> Blueprint updates

- generators/client/templates/react/src/main/webapp/app/app.scss.ejs
- generators/client/templates/react/src/main/webapp/app/modules/home/home.scss.ejs
- generators/client/templates/react/src/main/webapp/app/shared/layout/header/header.scss.ejs
- generators/client/templates/react/src/main/webapp/app/shared/layout/password/password-strength-bar.scss.ejs
fix #7446 
See also PR #7448 from @agaspardcilia 
> react: correct indentation of scss.ejs files

- generators/client/templates/react/src/main/webapp/app/modules/account/password-reset/init/password-reset-init.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/audits/audits.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/gateway/gateway.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/health/health.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/metrics/metrics-modal.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/metrics/metrics.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/metrics/thread-item.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management-detail.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/home/home.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/login/login-modal.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/shared/layout/footer/footer.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-detail.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs
Unify bootstrap usage by changing every bootstrap classNames by their reactstrap equivalent.
> unify bootstrap usage

- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management.tsx.ejs
> Fix a typo

- generators/client/templates/react/src/test/javascript/spec/app/shared/reducers/authentication.spec.ts.ejs
> React : Fix auth reducer test when OAuth2 is enabled

- generators/server/templates/build.gradle.ejs
- generators/server/templates/gradle.properties.ejs
- generators/server/templates/pom.xml.ejs
- travis/scripts/00-install-jhipster.sh
- travis/scripts/03-replace-version-generated-project.sh
Complementing this PR on the server lib (renaming artifact)
https://github.com/jhipster/jhipster/pull/56
If approved, please merge both at the same time.
Mutual dependent PRs, so Travis fails. But together they pass:
https://travis-ci.org/erikkemperman/jhipster/builds/365654942
> Rename jhipster server-side artifacts

- generators/server/templates/gradle.properties.ejs
- generators/server/templates/pom.xml.ejs
As requested [here](https://github.com/jhipster/generator-jhipster/pull/7481#issuecomment-381163037).
> Align versions

- generators/server/templates/src/main/java/package/config/oauth2/OAuth2JwtAccessTokenConverter.java.ejs
I messed PR #7326 reopening a PR
>  Make JWT claims reachable from SecurityContext when used OAuth2 + JWT

- generators/entity-client/templates/react/src/test/javascript/spec/app/entities/entity-reducer.spec.ts.ejs
See https://travis-ci.org/hipster-labs/jhipster-travis-build/builds/366422334
It should fix them
_____
> React: fix react tests for NoSQL

- generators/client/templates/react/src/main/webapp/app/modules/administration/metrics/metrics.tsx.ejs
> Fix React metrics page

- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.reducer.ts.ejs
- generators/entity-client/templates/react/src/test/javascript/spec/app/entities/entity-reducer.spec.ts.ejs
The previous implementation was creating a lot of code duplication. 
This PR shouldn't be merged before Devoxx since it can easily creates bugs.
> Refactor react's blob support

- generators/client/templates/react/src/main/webapp/app/modules/account/password/password.tsx.ejs
The class name was wrong. It was prolly due to some copy pasta.
> React: Change password page class name

- generators/server/templates/src/main/resources/logback-spring.xml.ejs
> Fix the commented out file appender config in logback-spring.xml

- .travis.yml
Following this PR https://github.com/jhipster/generator-jhipster/pull/7050 and waiting a new release of jhipster/jhipster, I change to use master branch, instead of release
_____
> Travis: use jhipster/jhipster master branch

- generators/kubernetes/files.js
- generators/kubernetes/index.js
- generators/kubernetes/templates/README-KUBERNETES.md.ejs
- generators/kubernetes/templates/_apply.sh
- generators/kubernetes/templates/deployment.yml.ejs
- generators/kubernetes/templates/messagebroker/kafka.yml.ejs
- generators/openshift/files.js
- generators/openshift/index.js
- generators/openshift/templates/apply.sh.ejs
- generators/openshift/templates/deployment.yml.ejs
- generators/openshift/templates/messagebroker/kafka.yml.ejs
- test/kubernetes.spec.js
> fix for issue #7345

- generators/server/templates/src/main/java/package/config/MetricsConfiguration.java.ejs
Quick fix until jhipster migrate to micrometer
> 7497 : fix gateway monitor issue cannot use setMetricRegistry() and setMetricsTrackerFactory() together

- generators/server/templates/src/main/docker/app.yml.ejs
- generators/server/templates/src/main/docker/jhipster-registry.yml.ejs
See https://www.jhipster.tech/docker-compose/
So we can simply uncommented to reduce the memory use
_____
> Docker: add _JAVA_OPTIONS commented to reduce memory use [ci skip]

- generators/client/templates/react/src/test/javascript/spec/app/shared/reducers/authentication.spec.ts.ejs
> React: Fix auth reducer test when using oauth2

- .travis.yml
> No Travis cache for jhipster-framework

- generators/client/templates/angular/src/main/webapp/swagger-ui/index.html.ejs
- generators/client/templates/react/src/main/webapp/swagger-ui/index.html.ejs
> Fix JWT-Token is not given to Swagger-UI (#7444)

- generators/client/templates/react/src/main/webapp/app/shared/reducers/application-profile.ts.ejs
- generators/client/templates/react/src/test/javascript/spec/app/shared/reducers/application-profile.spec.ts.ejs
> React: fix profile reducer

- generators/server/templates/src/main/java/package/config/WebConfigurer.java.ejs
This endpoint is used for authenticating with the UAA through the gateway.   Related to #3575
> add cors config for uaa gateway auth endpoint

- generators/client/files-react.js
- generators/client/templates/react/src/main/webapp/app/config/icon-loader.ts.ejs
- generators/client/templates/react/src/main/webapp/app/index.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/audits/audits.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/gateway/gateway.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/health/health.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/metrics/metrics.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management-delete-dialog.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management-detail.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management-update.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/shared/layout/header/header.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/shared/reducers/application-profile.ts.ejs
- generators/client/templates/react/src/test/javascript/spec/app/shared/reducers/application-profile.spec.ts.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-delete-dialog.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-detail.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs
- generators/generator-base.js
For some reason var names are in camel case while others are in kebab case for `/management/info`. We might need to get more consistent with that.
> Adds React icons loader + fix profile reducer

- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity.model.ts.ejs
https://www.typescriptlang.org/docs/handbook/enums.html#string-enums
Fix #7556 
> use a string enum for the entity enum in typescript

- generators/entity-client/files.js
- generators/generator-base.js
The first Travis test is failing on the lint stage, this fixes it
> fix lint for travis

- generators/client/templates/react/src/main/webapp/app/shared/util/entity-utils.ts.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs
I don't really know if it's the proper way to fix that.
> React : Fix a bug that was preventing relation field to be set to "empty"

- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.model.ts.ejs
> use a string enum for the entity enum in typescript [react]

- generators/client/templates/react/package.json.ejs
> Upgrade react-jhipster to 0.5.1

- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management-update.tsx.ejs
> Fixed activated checkbox

- package-lock.json
- package.json
- yarn.lock
> Updated the JCore to v2.0.3

- generators/client/templates/angular/package.json.ejs
> Update webpack version

- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-detail.tsx.ejs
> Improve React entity detail page display

- generators/client/templates/react/src/main/webapp/app/shared/layout/header/header.tsx.ejs
> fix admin menu in case of not using h2

- generators/client/templates/angular/package.json.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/ng_validators.ejs
> add jhiMin max

- generators/client/templates/angular/src/main/webapp/app/shared/constants/input.constants.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity.service.ts.ejs
Serialize LocalDate as Date ('YYYY-MM-DD') with Moment.js before sending it to server instead of DateTime
Fix #7569
> Fix LocalDate serialization by Moment.js

- generators/client/templates/react/src/test/javascript/spec/app/shared/layout/header/menus/account.spec.tsx.ejs
> fix broken test: react-oauth2

- generators/client/templates/react/src/main/webapp/app/modules/administration/administration.reducer.ts.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management.reducer.ts.ejs
- generators/client/templates/react/src/main/webapp/app/shared/reducers/authentication.ts.ejs
> add uaa path to api paths in react where needed

- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-detail.component.ts.ejs
OnDestroy is not used here
- [x ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
> Unused import on Angular entity component

- generators/client/templates/angular/src/main/webapp/app/core/index.ts.ejs
- generators/server/files.js
> fix build when using skipUserManagement

- generators/server/templates/_gradle.properties
- generators/server/templates/_pom.xml
Fixes https://github.com/jhipster/generator-jhipster/issues/7591
Dependent on https://github.com/jhipster/jhipster-dependencies/pull/40
> Update spring-boot to 1.5.13-RELEASE

- generators/server/templates/src/main/resources/config/application.yml.ejs
> Disable consul config watch to fix logstash logs loss

- package.json
- yarn.lock
It should fix https://github.com/jhipster/generator-jhipster/issues/7596
_____
> Upgrade lodash to 4.17.10

- generators/server/files.js
- test/app.spec.js
Related to https://github.com/jhipster/generator-jhipster/issues/7605
_____
> Fix Elasticsearch with OAuth2

- generators/server/templates/src/main/java/package/gateway/accesscontrol/AccessControlFilter.java.ejs
Maybe I'm misunderstanding this code, but it seems to me it will never work if there is a contextPath set, without these changes.
>  Pay attention to contextPath

- generators/generator-constants.js
> Upgrade to Yarn 1.6.0

- generators/server/files.js
- generators/server/templates/src/main/java/package/config/dbmigrations/InitialSetupMigration.java.ejs
- test/app.spec.js
Fix https://github.com/jhipster/generator-jhipster/issues/7605
The problem was the missing file `InitialSetupMigration.java` which is needed to initialize the Authorities
_____
> Fix OAuth2+MongoDB

- generators/client/templates/angular/package.json.ejs
- generators/client/templates/react/package.json.ejs
Fix #7551 
I did a test in my own Travis and it is confirmed to fixed issues with node 10: https://travis-ci.org/PierreBesson/generator-jhipster/builds/379130053
> upgrade node-saas and saas-loader to support Node 10

- generators/client/prompts.js
> move the prompt to angular 6

- generators/client/templates/angular/package.json.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/audits/audits.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/gateway/gateway.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/health/health.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management-delete-dialog.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management-detail.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management-update.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/layouts/navbar/navbar.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/shared/shared-libs.module.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-delete-dialog.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-detail.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.html.ejs
- generators/generator-base.js
#7634 broke all the icons because FontAwesome now needs some javascript in order to work...
So we need to use the Angular Font Awesome lib.
> Use Angular FontAwesome

- generators/client/templates/angular/package.json.ejs
- generators/server/templates/pom.xml.ejs
Related to https://github.com/jhipster/generator-jhipster/pull/7636
_____
> Fix sonar analyze with Jest

- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity.service.ts.ejs
- test/entity.spec.js
> Remove whitespace and set static on ProfileInfoVM

- .travis.yml
- generators/generator-constants.js
Related to @PierreBesson's https://github.com/jhipster/generator-jhipster/issues/7551#issuecomment-391511415
> Upgrade to Node 8.11.2 LTS and Yarn 1.7.0

- generators/upgrade/index.js
> add upgrade cli flag options to the --help output

- generators/entity-server/templates/src/main/java/package/common/delete_template.ejs
- generators/entity-server/templates/src/main/java/package/common/save_template.ejs
Review:
https://github.com/jhipster/generator-jhipster/commit/39fb0b4a5115c6b63b19f39983cc62d760687880#r29107819
Review:
https://github.com/jhipster/generator-jhipster/commit/3bcae4aa7e587be187fc06e675a8b80813aa11a8#r29107881
> Fix source generation formatting

- generators/entity-server/index.js
> remove extra log during entity generation [ci skip]

- generators/heroku/index.js
> Add prod profile when building with Gradle on Heroku

- generators/client/templates/react/src/test/javascript/spec/app/shared/reducers/authentication.spec.ts.ejs
> adjust expectations of react-oauth2 test

- generators/generator-constants.js
Fix https://github.com/jhipster/generator-jhipster/issues/7693
> Revert to Yarn 1.6.0 because of problem with yarn link

- generators/generator-base.js
Icon currently does not appear
> fix entity navbar icon

- generators/client/templates/angular/src/main/webapp/app/app.main.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/layouts/navbar/navbar.component.html.ejs
> set preserveWhitespaces to true and align items in menu

- generators/server/templates/build.gradle.ejs
- generators/server/templates/gradle.properties.ejs
- generators/server/templates/pom.xml.ejs
Cf., this depends on [this server lib PR](https://github.com/jhipster/jhipster/pull/70).
I'll cancel Travis: it will fail because of mutually dependent changes, see here for passing tests where both generator and server-lib PRs are applied:
https://travis-ci.org/erikkemperman/generator-jhipster/builds/385069631
https://travis-ci.org/erikkemperman/jhipster/builds/385070081
> Bump dependencies

- generators/client/templates/react/src/test/javascript/e2e/modules/administration/administration.spec.ts.ejs
Related to https://github.com/jhipster/generator-jhipster/issues/7694#issuecomment-392664759
Sorry, confident PR, I didn't test it. Too bad connexion this morning in my train
Similar code for Angular: https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/test/javascript/e2e/admin/administration.spec.ts.ejs#L84
_____
> Fix e2e for React+Cassandra

- generators/generator-base.js
> add fixed width to icons in navbar needle insertions

- generators/server/templates/src/main/java/package/config/UaaConfiguration.java.ejs
reported in #7711, related to #7301
> encode client secret correctly for service to service communication

- generators/server/templates/gradle.properties.ejs
- generators/server/templates/pom.xml.ejs
Related to discussion here:
https://github.com/jhipster/generator-jhipster/issues/7606#issuecomment-393768409
____
> Upgrade to JHipster Dependencies 2.0.7

- generators/server/templates/src/main/java/package/domain/User.java.ejs
Related to 7ff7760e94c998d97212c161ed1ea2ac65085ef9
> match initial schema so liquibase:diff shows no diff on new app

- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-detail.component.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.route.ts.ejs
- [X ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed
> Fix #7723 - Change Angular resolver behavior

- generators/client/index.js
- generators/server/index.js
Fix https://github.com/jhipster/generator-jhipster/issues/7731
_____
> Fix applicationType value in config when using jhipster server [ci skip]

- generators/kubernetes/files.js
- generators/kubernetes/index.js
- generators/kubernetes/prompts.js
- generators/kubernetes/templates/README-KUBERNETES.md.ejs
- generators/kubernetes/templates/_apply.sh
- generators/kubernetes/templates/deployment.yml.ejs
- generators/kubernetes/templates/ingress.yml.ejs
- generators/kubernetes/templates/istio/destination-policy.yml.ejs
- generators/kubernetes/templates/istio/route-rule.yml.ejs
- generators/kubernetes/templates/registry/consul.yml.ejs
- generators/kubernetes/templates/registry/jhipster-registry.yml.ejs
- generators/kubernetes/templates/service.yml.ejs
#7337 
- tested with both eureka and consul
- included routerule and destinationpolicy rules
This is with minimal change to the existing code base. We can slowly introduce more features to it and over the period of time redundant components can be decoupled.
> Istio - intial commit

- generators/server/files.js
- generators/server/templates/README.md.ejs
- generators/server/templates/build.gradle.ejs
- generators/server/templates/pom.xml.ejs
- generators/server/templates/src/main/docker/Dockerfile.ejs
- generators/server/templates/src/main/docker/entrypoint.sh.ejs
Following the great advice from @gclayburg.
> Docker build improvements

- generators/server/prompts.js
- test/app.spec.js
> Change swagger-codegen to openapi-generator in prompt

- generators/server/templates/README.md.ejs
- generators/server/templates/build.gradle.ejs
- generators/server/templates/gradle/swagger.gradle.ejs
- generators/server/templates/pom.xml.ejs
> Use gradle plugin for API-First option

- generators/generator-base.js
Fix https://github.com/jhipster/generator-jhipster/issues/7763
> Fix message after logo [ci skip]

- package-lock.json
- package.json
- yarn.lock
> Updated JCore dep to v3.0.2

- .vscode/launch.json
Should work out of the box and attach to the integrated terminal.
> Fix VScode launch.json debug configuration

- generators/server/templates/build.gradle.ejs
To fix the issue from https://github.com/n0mer/gradle-git-properties/issues/107
> Bump gradle-git-properties version to 1.5.1

- generators/client/templates/angular/tsconfig-aot.json.ejs
Aligns prod profile with dev profile. Related to #7692 and #7701
> Angular: preserve whitespaces in prod as it is preserved in dev

- generators/client/templates/angular/webpack/webpack.prod.js.ejs
- generators/client/templates/react/webpack/webpack.prod.js.ejs
Caused by 6104182daa22b5c04a255aee0998d30d48a9ad3a
Mentioned in #7790
Fix #7791
> fix scss image path in prod

- generators/generator-base-private.js
- generators/import-jdl/index.js
- test/import-jdl.spec.js
- test/templates/import-jdl/.yo-rc.json
- test/templates/import-jdl/single-app-and-entities.jdl
Used provided ways to get the config file (`.yo-rc.json`) content to be read and used by the generators.
> Updated application/entity generation

- generators/server/files.js
- generators/server/index.js
- generators/server/prompts.js
- generators/server/templates/pom.xml.ejs
> Make Hazelcast optional when Gateway has no Service Discovery.

- generators/server/templates/gradle.properties.ejs
- generators/server/templates/pom.xml.ejs
Forgot to align this when spring-boot was upgraded in the server lib
> Bump spring-boot property to 2.0.3.RELEASE

- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-delete-dialog.component.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-detail.component.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.ts.ejs
Rename a variable name (route) by it's class name (ActivatedRoute) to prevent some conflicts with common name route.
Example JDL: https://github.com/FireWolf2007/transport-logistic/blob/master/route-service/route-service.jh
> Rename route -> activatedRoute

- generators/generator-constants.js
- generators/server/templates/pom.xml.ejs
Travis says [all right](https://travis-ci.org/erikkemperman/generator-jhipster/builds/394095828).
> Minor upgrades to some mvn plugins, and scala

- generators/server/templates/build.gradle.ejs
> Added a missing closing double quote to dependency "spring-retry"

- generators/gae/index.js
> Fixed instance class labels

- .travis.yml
- generators/generator-constants.js
> Upgrade to Node 8.11.3 and NPM 6.1.0

- generators/client/templates/react/package.json.ejs
- generators/client/templates/react/src/test/javascript/jest.conf.js.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/7834
_____
> Fix Jest folder for React, which is not created

- .travis.yml
- travis/samples/ms-ngx-gateway-eureka-oauth2/.yo-rc.json
Fix https://github.com/jhipster/generator-jhipster/issues/7667
_____
> Travis: add OAuth2 Microservices

- generators/client/templates/angular/src/main/webapp/app/core/auth/auth-session.service.ts.ejs
Use Rxjs 6 syntax for auth-session-service
> use pipe for auth-session-service

- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity.service.ts.ejs
Use Rxjs 6 syntax for angular services.
Do you prefer little PR or one for all?
> use rxjs 6 syntax for Angular services

- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.route.ts.ejs
Please wait travis: I didn't test as it was a really simple change
> use rxjs6 syntax for Angular resolver

- generators/languages/templates/src/main/webapp/i18n/uz-lat/global.json.ejs
There were two extra commas in json. This messed up json validation during app generation
> Fixed json structure

- generators/server/templates/src/main/resources/config/application-dev.yml.ejs
- generators/server/templates/src/test/resources/config/application.yml.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/7870
> Fix issue in H2Memory database

- generators/server/templates/src/main/java/package/web/rest/util/HeaderUtil.java.ejs
> Refactor Server HeaderUtil class

- generators/spring-controller/index.js
> spring controller: typo [ci skip]

- generators/ci-cd/templates/.gitlab-ci.yml.ejs
> add artifacts expiry tag in gitlab ci file

- generators/generator-base.js
- package-lock.json
- Removes unused line (the value is set in the line under it)
- Update package-lock.json to reflect current version v5.0.1
> polish (unused line, npm package-lock.json)

- generators/server/templates/src/main/java/package/config/LiquibaseConfiguration.java.ejs
> Don't add cache dependency in Liquibase if cache is disabled

- generators/entity/index.js
- generators/entity/prompts.js
Not sure if there is a better way to do this
Fix #7696
> prevent required relations to the same entity

- generators/client/templates/react/src/main/webapp/app/config/translation.ts.ejs
- generators/client/templates/react/src/main/webapp/app/shared/layout/header/header-components.tsx.ejs
- generators/client/templates/react/src/main/webapp/manifest.webapp.ejs
- generators/client/templates/react/webpack/webpack.common.js.ejs
- generators/generator-base-private.js
- generators/server/templates/src/main/java/package/config/WebConfigurer.java.ejs
> Move images to content directory and add cache headers on i18n bundles

- generators/generator-base-private.js
- generators/generator-base.js
Related to https://github.com/jhipster/generator-jhipster/issues/7896
@leighadellinger : what do you think ?
@PierreBesson :
- the code is really simple, and it should work for all OS
- as discussed during  the OnBoarding, I reduce the timeout for git connection from 15sec to 5sec
> Check home directory

- generators/client/files-angular.js
- generators/client/files-react.js
- generators/client/index.js
- generators/entity-client/files.js
- generators/entity-client/index.js
- generators/entity-server/files.js
- generators/entity-server/index.js
- generators/generator-base.js
- generators/server/files.js
- generators/server/index.js
- generators/server/templates/src/main/resources/i18n/messages.properties.ejs
- generators/spring-service/index.js
Following the discussion in this PR https://github.com/jhipster/generator-jhipster-blueprint/pull/3
_____
> Blueprint: fix write files

- generators/client/templates/react/src/main/webapp/app/shared/layout/header/menus/account.tsx.ejs
> Correct translation key in account menu

- generators/client/templates/angular/package.json.ejs
> Bump ng-jhispter dependency version

- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/react_validators.ejs
- generators/entity-client/templates/react/src/test/javascript/e2e/entities/entity-update-page-object.ts.ejs
- generators/entity-server/templates/src/main/java/package/common/field_validators.ejs
- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIntTest.java.ejs
- generators/entity/index.js
- generators/entity/prompts.js
Fixed it as it was mentioned in #7842
> Fix react input for text blobs

- generators/generator-base-private.js
- test/generator-base-private.spec.js
> Made the imports for both angularX & react relationships the same

- generators/client/templates/react/src/test/javascript/e2e/modules/administration/administration.spec.ts.ejs
https://github.com/jhipster/generator-jhipster/commit/c579d661eb46a63d22a0ac806a917f85cb2015aa#r29643052
> remove condition on test import

- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs
> Fix multiselect in react

- generators/docker-compose/templates/jhipster-registry.yml.ejs
- generators/generator-constants.js
- generators/kubernetes/templates/registry/jhipster-registry.yml.ejs
- generators/openshift/templates/registry/jhipster-registry.yml.ejs
- generators/rancher-compose/templates/docker-compose.yml.ejs
- generators/server/templates/src/main/docker/app.yml.ejs
- generators/server/templates/src/main/docker/jhipster-registry.yml.ejs
Related to this ticket: https://github.com/jhipster/jhipster-registry/issues/281
Fixed by this PR: https://github.com/jhipster/jhipster-registry/pull/282
See official documentation: https://cloud.spring.io/spring-cloud-config/multi/multi__spring_cloud_config_server.html#composite-environment-repositories
_____
> Switch to composite mode for defining the configserver sources

- generators/client/templates/react/package.json.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-delete-dialog.tsx.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.reducer.ts.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs
> Fix React infinite scrolling

- generators/client/templates/react/src/main/webapp/app/config/icon-loader.ts.ejs
This icons were imported but never actually added to the icon library.
> React: add icons

- Dockerfile
2 changes:
- remove libs for Puppeteer
- add libpng-dev for React
_____
> Docker: add libpng dev

- generators/generator-base.js
- generators/spring-controller/index.js
- generators/spring-service/index.js
Fix https://github.com/jhipster/generator-jhipster/issues/7925
_____
> blueprint: fix controller and service

- generators/client/index.js
- package.json
- yarn.lock
> upgrade to yeoman 3

- generators/client/files-angular.js
- generators/client/files-react.js
- generators/entity-client/files.js
- generators/entity-client/index.js
- generators/entity-server/files.js
- generators/entity-server/index.js
- generators/server/files.js
- generators/server/index.js
- generators/spring-controller/index.js
- generators/spring-service/index.js
Related to https://github.com/jhipster/generator-jhipster/pull/7971#pullrequestreview-137267667
> blueprint: remove conditions

- generators/ci-cd/index.js
- generators/ci-cd/prompts.js
- generators/ci-cd/templates/.gitlab-ci.yml.ejs
- generators/ci-cd/templates/circle.yml.ejs
- generators/ci-cd/templates/jenkins/Jenkinsfile.ejs
- generators/ci-cd/templates/travis.yml.ejs
- generators/generator-base.js
- generators/server/templates/pom.xml.ejs
- test/ci-cd.spec.js
- test/templates/ci-cd/gradle-ngx-npm/.yo-rc.json
- test/templates/ci-cd/gradle-ngx-yarn/.yo-rc.json
- test/templates/ci-cd/maven-ngx-npm/.yo-rc.json
- test/templates/ci-cd/maven-ngx-yarn/.yo-rc.json
- test/templates/ci-cd/maven-ngx-yarn/pom.xml
Fix https://github.com/jhipster/generator-jhipster/issues/7904
Fix https://github.com/jhipster/generator-jhipster/issues/7978
All changes are listed here: https://github.com/jhipster/generator-jhipster/issues/7904#issue-337273283
All tests I did:
- Maven + Angular project:
- Travis CI with sonarcloud.io analyze + Heroku deployment
- GitLab CI with sonarcloud.io analyze + Heroku deployment
- Jenkins with Artifactory + Sonar
- Gradle + React project:
- Travis CI with sonarcloud.io analyze + Heroku deployment
- GitLab CI with sonarcloud.io analyze + Heroku deployment
- Jenkins with Sonar
_____
> CICD: improvement

- generators/app/index.js
- generators/generator-base-private.js
Fix https://github.com/jhipster/generator-jhipster/issues/7977
_____
> Remove git connection check, used for Bower with AngularJS

- generators/entity-server/files.js
> blueprint: fix enum for entity-server

- package-lock.json
- package.json
- yarn.lock
> Updated JCore dependency to v3.1.0

- generators/entity/prompts.js
Related to https://github.com/jhipster/generator-jhipster/issues/7911#issuecomment-401707094
_____
> Remove beta tag for DTO [ci skip]

- generators/server/templates/pom.xml.ejs
See https://sonarcloud.io/coding_rules?open=squid%3AS4684&rule_key=squid%3AS4684
Related to this ticket https://github.com/jhipster/generator-jhipster/issues/7911
I didn't add `fix` word, as there is still the CSRF rules.
_____
> Sonar: ignore persistent entities rules

- generators/server/templates/pom.xml.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/7911
_____
> Sonar: ignore CSRF rule for JWT Token

- generators/client/templates/angular/src/main/webapp/swagger-ui/index.html.ejs
- generators/client/templates/react/src/main/webapp/swagger-ui/index.html.ejs
> Improved CSRF handling in swagger UI for UAA

- generators/generator-base.js
> prevent underscore from being in UAA base name

- generators/server/templates/build.gradle.ejs
- generators/server/templates/gradle/docker.gradle.ejs
- generators/server/templates/gradle/sonar.gradle.ejs
* Update plugins to the latest version
* Removes the ugly deprecation warning about upcoming gradle 5
> Gradle plugin updates

- generators/server/templates/src/main/java/package/config/LiquibaseConfiguration.java.ejs
> Set liquibase change log parameters from spring boot configurations

- generators/client/templates/react/src/test/javascript/spec/app/shared/reducers/authentication.spec.ts.ejs
> Add unit test for login action

- generators/client/templates/react/src/test/javascript/spec/app/shared/reducers/authentication.spec.ts.ejs
> Skip login unit test case when authentication type is oauth2

- generators/app/index.js
- generators/client/index.js
- generators/server/templates/gradle/profile_dev.gradle.ejs
- generators/server/templates/gradle/profile_prod.gradle.ejs
- generators/server/templates/pom.xml.ejs
fix https://github.com/jhipster/generator-jhipster/issues/8033
_____
> Improve webpack maven profile

- generators/generator-constants.js
> Upgrade to Yarn 1.9.2 and NPM 6.2.0

- generators/client/templates/react/src/main/webapp/app/modules/account/activate/activate.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/account/password-reset/finish/password-reset-finish.tsx.ejs
- generators/server/templates/src/main/resources/config/application-dev.yml.ejs
- generators/server/templates/src/main/resources/templates/mail/activationEmail.html.ejs
- generators/server/templates/src/main/resources/templates/mail/passwordResetEmail.html.ejs
Fix #7912
Fix #7890 (unless someone sees any other issues with UAA+React)
> Fix query params react

- generators/server/templates/src/main/java/package/config/dbmigrations/InitialSetupMigration.java.ejs
- generators/server/templates/src/main/resources/config/couchmove/changelog/V0.1__initial_setup/user__admin.json.ejs
- generators/server/templates/src/main/resources/config/couchmove/changelog/V0.1__initial_setup/user__anonymoususer.json.ejs
- generators/server/templates/src/main/resources/config/couchmove/changelog/V0.1__initial_setup/user__system.json.ejs
- generators/server/templates/src/main/resources/config/couchmove/changelog/V0.1__initial_setup/user__user.json.ejs
> Fix native language for MongoDB and Couchbase

- generators/client/templates/react/src/main/webapp/app/shared/util/entity-utils.ts.ejs
- generators/client/templates/react/src/test/javascript/spec/app/shared/util/entity-utils.spec.ts.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs
> React: refactor the way relations are handled

- generators/upgrade/index.js
> Add --no-verify to git commit command in upgrade sub-generator

- generators/generator-base-private.js
Based on discussion here:
https://github.com/jhipster/generator-jhipster/issues/5289#issuecomment-409673821
> Update constructor generator to allow true values

- generators/client/templates/angular/package.json.ejs
- generators/client/templates/angular/webpack/webpack.prod.js.ejs
- generators/client/templates/react/package.json.ejs
- generators/client/templates/react/webpack/webpack.prod.js.ejs
It is fast, can see ~50% speed up in (angular) prod build 🤞
Lets see what travis says
> Move to Terser plugin instead of UglifyJS

- generators/app/index.js
- generators/client/index.js
fix #8002
`uaaBaseName` wasn't passed to the subgen when skipping the server.
> Fix missing parameter when skipping server

- generators/server/templates/gradle.properties.ejs
- generators/server/templates/pom.xml.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/8067
Dependent on https://github.com/jhipster/jhipster/pull/83
> Update spring-boot to 2.0.4, spring-cloud to Finchley.SR1 and other dependencies

- generators/server/templates/src/main/resources/config/application.yml.ejs
- Fixes #8092 
r? @mraible  @jdubois 
Check this https://github.com/spring-cloud/spring-cloud-netflix/issues/3126
> fix zuul authorization token not forwarded

- generators/client/templates/angular/src/main/webapp/app/vendor.ts.ejs
Required for the ongoing PR: https://github.com/jhipster/ng-jhipster/pull/73
> add faSortUp and faSortDown icons

- generators/server/templates/src/main/java/package/security/oauth2/OAuth2AuthenticationService.java.ejs
- generators/server/templates/src/test/java/package/security/oauth2/OAuth2AuthenticationServiceTest.java.ejs
> throw correct exception on bad password for UAA

- generators/server/templates/README.md.ejs
- generators/server/templates/gradle/sonar.gradle.ejs
- generators/server/templates/pom.xml.ejs
- generators/server/templates/src/main/docker/sonar.yml.ejs
> Sonar reporting improvements

- generators/heroku/index.js
- generators/heroku/templates/application-heroku.yml.ejs
- test/heroku.spec.js
This supports @mraible's changes in https://github.com/jhipster/generator-jhipster/issues/7810
> Replace heroku elasticsearch addon with bonsai

- generators/client/templates/angular/package.json.ejs
- generators/client/templates/react/package.json.ejs
This resolves 5 moderate vulnerabilities in dependencies of node-sass.
Fix #8127
> upgrade to node-sass 4.9.3

- generators/client/templates/angular/src/main/webapp/app/app.module.ts.ejs
> Configure global datepicker's min date

- generators/client/templates/angular/package.json.ejs
- generators/client/templates/react/package.json.ejs
This resolves 2 high vulnerabilities in dependencies of protractor
Fix #8128
> upgrade to protractor 5.4.0

- generators/client/templates/angular/package.json.ejs
- generators/client/templates/react/package.json.ejs
This resolves 5 low vulnerabilities in dependencies of browser-sync.
Fix #8129
> upgrade to browser-sync 2.24.6

- generators/client/templates/angular/package.json.ejs
- generators/client/templates/angular/webpack/webpack.dev.js.ejs
- generators/client/templates/angular/webpack/webpack.prod.js.ejs
- generators/client/templates/react/package.json.ejs
- generators/client/templates/react/webpack/webpack.dev.js.ejs
- generators/client/templates/react/webpack/webpack.prod.js.ejs
> Replace node-sass with sass

- generators/server/templates/build.gradle.ejs
- generators/server/templates/pom.xml.ejs
Depends on https://github.com/jhipster/jhipster/pull/89.
> Upgrade JJWT to 0.10.5

- generators/client/templates/angular/src/main/webapp/app/shared/login/login.component.ts.ejs
> Polish angular comments [ci skip]

- travis/samples/.jhipster/TestManyRelPaginDTO.json
> Remove Travis sample with DTO and no service

- test/entity.spec.js
> assert client-root-folder is set correctly for microservices

- .travis.yml
- generators/generator-constants.js
> Upgrade to Node 8.11.4, NPM 6.4.1, Yarn 1.9.4

- generators/client/templates/angular/src/main/webapp/app/shared/constants/input.constants.ts.ejs
> Change DATE_TIME_FORMAT to 24 hour clock

- generators/server/templates/_gradle.properties
- generators/server/templates/_pom.xml
Dependent on https://github.com/jhipster/jhipster-dependencies/pull/42
> Update spring-boot to 1.5.15.RELEASE (spring-platform Brussels-SR12)

- generators/client/templates/react/src/test/javascript/e2e/util/utils.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-delete-dialog.component.html.ejs
- generators/entity-client/templates/angular/src/test/javascript/e2e/entities/entity-page-object.ts.ejs
- generators/entity-client/templates/angular/src/test/javascript/e2e/entities/entity.spec.ts.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-delete-dialog.tsx.ejs
- generators/entity-client/templates/react/src/test/javascript/e2e/entities/entity-page-object.ts.ejs
- generators/entity-client/templates/react/src/test/javascript/e2e/entities/entity.spec.ts.ejs
Test to delete last element of the entity list:
- click on last delete button
- check dialog title
- click on confirm button
- check an element has been removed
Fix #7844
> Create delete method in protractor test

- generators/server/templates/gradle/sonar.gradle.ejs
- generators/server/templates/pom.xml.ejs
> update jacoco to current version 0.8.2

- generators/ci-cd/index.js
- generators/ci-cd/templates/.gitlab-ci.yml.ejs
- generators/ci-cd/templates/jenkins/Jenkinsfile.ejs
- generators/ci-cd/templates/travis.yml.ejs
Following this commit https://github.com/jhipster/generator-jhipster/commit/74f9525c0771d8ae4ec11a6ce38a05cd25c6f9f8#diff-826b1965e64cb5ef8452013ed545504e
I think it's better to add this directly to the package.json
_____
> React: update snapshot for CICD sub gen

- .travis.yml
- generators/app/index.js
- generators/client/index.js
- generators/generator-base-private.js
- generators/generator-base.js
- generators/import-jdl/index.js
- test/client.spec.js
- test/templates/all-languages/.yo-rc.json
- test/templates/default-microservice/.yo-rc.json
- travis/samples/app-sample-dev/.yo-rc.json
- travis/samples/ms-micro-consul/.yo-rc.json
- travis/samples/ms-micro-eureka/.yo-rc.json
- travis/samples/ms-ngx-gateway-consul/.yo-rc.json
- travis/samples/ms-ngx-gateway-eureka-oauth2/.yo-rc.json
- travis/samples/ms-ngx-gateway-eureka/.yo-rc.json
- travis/samples/ms-ngx-gateway-uaa/.yo-rc.json
- travis/samples/ngx-couchbase/.yo-rc.json
- travis/samples/ngx-default/.yo-rc.json
- travis/samples/ngx-gradle-fr/.yo-rc.json
- travis/samples/ngx-h2mem-ws-nol2/.yo-rc.json
- travis/samples/ngx-mariadb-oauth2-sass-infinispan/.yo-rc.json
- travis/samples/ngx-mongodb-kafka-cucumber/.yo-rc.json
- travis/samples/ngx-psql-es-noi18n/.yo-rc.json
- travis/samples/ngx-session-cassandra-fr/.yo-rc.json
- travis/samples/react-default/.yo-rc.json
- travis/samples/react-noi18n-es-ws-gradle-session/.yo-rc.json
- travis/samples/uaa/.yo-rc.json
- travis/scripts/00-install-jhipster.sh
- travis/scripts/04-tests.sh
- travis/scripts/05-run.sh
Related to https://github.com/jhipster/generator-jhipster/issues/8162
_____
> Switch to NPM as default client package manager

- package-lock.json
- package.json
- yarn.lock
See https://github.com/jhipster/generator-jhipster/pull/8178
> Update to JHipster Core 3.3.0

- Dockerfile
> Docker: switch to NPM as default client package manager

- package-lock.json
- package.json
- test/templates/import-jdl/jdl.jdl
- yarn.lock
> Updated JCore dependency to v3.3.1

- generators/server/templates/build.gradle.ejs
- generators/server/templates/pom.xml.ejs
> Remove non-free and unused org.json dependency

- generators/server/templates/build.gradle.ejs
Somehow parts from the liquibase stuff landed at the wrong place, sorry for that :(
closes #8235
> remove wrongly added code

- generators/server/templates/src/main/java/package/config/UaaConfiguration.java.ejs
this sets up the authorities for the registry to manage
UAA microservices/gateways through the admin controls
Related to https://github.com/jhipster/jhipster-registry/pull/278
> add admin authority to uaa internal client

- generators/entity-i18n/templates/i18n/entity_pl.json.ejs
- generators/languages/templates/src/main/webapp/i18n/pl/gateway.json
- generators/languages/templates/src/main/webapp/i18n/pl/global.json.ejs
- generators/languages/templates/src/main/webapp/i18n/pl/health.json.ejs
As it's my first time here, congrats and thanks for such a great app @jdubois and all of you, guys!
I stumbled upon not translated `jhi-count` while working on my app, so I looked into translation files and managed to translate rest of the entries and also (i think) improved some. Standard pluralisation does not work well with polish nouns and templates look better without it by default, so i removed it. I also tweaked alerts a bit, so they work with every noun gender.
> Polish translation files update

- generators/server/prompts.js
fix No database - Text duplicate in the generator step Fix #8243.
I did my internal test and work well!
Fix #8243
> fix No database duplicate.

- generators/generator-constants.js
> Added Bengali Language

- generators/generator-constants.js
- generators/languages/templates/src/main/resources/i18n/messages_bn.properties.ejs
- package-lock.json
> Fix Bengali language

- README.md
> Update badges [ci skip]

- azure-pipelines.yml
> Azure: set up CI with Azure Pipelines [ci skip]

- generators/client/templates/angular/package.json.ejs
- generators/client/templates/react/package.json.ejs
> Pretty lint configuration in package.json

- generators/client/templates/angular/package.json.ejs
- generators/client/templates/react/package.json.ejs
> #8299 Use npx instead of npm for prettier:format command

- generators/docker-compose/templates/jhipster-registry.yml.ejs
- generators/rancher-compose/index.js
- generators/rancher-compose/templates/docker-compose.yml.ejs
- generators/server/templates/src/main/docker/jhipster-registry.yml.ejs
> add uaa profile to jhipster registry docker-compose files

- generators/entity-client/templates/angular/src/test/javascript/e2e/entities/entity.spec.ts.ejs
- generators/entity-client/templates/react/src/test/javascript/e2e/entities/entity.spec.ts.ejs
> Check the entity is saved and can be correctly serialized after creation

- generators/server/templates/src/main/java/package/config/OAuth2SsoConfiguration.java.ejs
Activate @Secured and @PreAuthorize, otherwise it won't be taken into account in gateways
- [ X] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [X ] Tests are added where necessary
- [X ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed
> Activation of Secured and Preauthorize on Gw

- generators/docker-compose/index.js
> Add serverPort for Docker Compose and OAuth 2.0

- generators/server/templates/src/main/java/package/config/MessagingConfiguration.java.ejs
> Change time and message of kafka heartbeat

- package-lock.json
- package.json
> Updated the JCore dep to v3.3.3

- generators/server/templates/src/test/java/package/security/SecurityUtilsUnitTest.java.ejs
- [x ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
> [skip-ci] Spacing on javadoc

- generators/entity-server/templates/src/main/java/package/service/dto/EntityCriteria.java.ejs
My first contribution for the generator, I am not familiar with ejs.
I try to fix issue: [#8049](https://github.com/jhipster/generator-jhipster/issues/8049), could someone check the code I put and correct me if this is wrong?
I do not know how to launch tests (except yarn test but fails on my pc) and how to generate with the ejs.
Thanks
@deepu105 @lmbai @PierreBesson
> Add equals/hashCode to criterias

- generators/languages/templates/src/main/webapp/i18n/de/global.json.ejs
- [x ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed
> fixed change password for german language

- generators/entity/prompts.js
> Escaped quotes in regex validations

- generators/heroku/index.js
Upgrade the heroku plugin to the latest version. Just deployed an app without any prolems.
> upgrade heroku gradle plugin to latest version

- cli/run-yeoman-process.js
- generators/client/templates/react/package.json.ejs
- generators/generator-base-private.js
> core: improvements

- generators/app/index.js
- generators/generator-base-private.js
- test/blueprint.spec.js
> Testable blueprint

- generators/languages/templates/src/main/webapp/i18n/tr/global.json.ejs
#8254 currentpassword and currentpassword.placeholder properties do not exist in Turkish global.json.ejs file
> #8254 Update global.json.ejs

- generators/entity-server/templates/src/main/java/package/common/get_all_template.ejs
- generators/entity-server/templates/src/main/java/package/service/EntityQueryService.java.ejs
- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIntTest.java.ejs
> Add count-by-criteria REST call with tests

- generators/server/templates/src/test/java/package/service/UserServiceIntTest.java.ejs
> Fix user locale is set correctly test in UserServiceIntTest

- generators/heroku/index.js
> Fix spaces issue with registry's username/password when using heroku

- generators/heroku/templates/application-heroku.yml.ejs
- test/heroku.spec.js
> Fix application-heroku.yml when both elasticsearch and mongodb are used

- generators/generator-base.js
- generators/server/templates/src/main/resources/config/application.yml.ejs
- test/entity.spec.js
- test/templates/default-gateway/.jhipster/Bar.json
- test/templates/default-gateway/.jhipster/Foo.json
- test/templates/default-gateway/.yo-rc.json
- test/utils/expected-files.js
Fix #8021
Also added tests for generating microservice entities on the gateway to ensure the expected files are generated.
> fix microservice proxy path

- generators/client/templates/angular/src/main/webapp/content/css/global.css.ejs
- generators/client/templates/angular/src/main/webapp/content/scss/global.scss.ejs
> Remove duplication of CSS selector "a:hover"

- generators/client/templates/angular/webpack/webpack.prod.js.ejs
- generators/client/templates/react/webpack/webpack.prod.js.ejs
- generators/server/files.js
- generators/server/templates/README.md.ejs
- generators/server/templates/gradle/docker.gradle.ejs
- generators/server/templates/pom.xml.ejs
- generators/server/templates/src/main/jib/entrypoint.sh.ejs
> Initial jib integration

- generators/languages/templates/src/main/webapp/i18n/id/activate.json.ejs
- generators/languages/templates/src/main/webapp/i18n/id/audits.json
- generators/languages/templates/src/main/webapp/i18n/id/configuration.json
- generators/languages/templates/src/main/webapp/i18n/id/error.json
- generators/languages/templates/src/main/webapp/i18n/id/gateway.json
- generators/languages/templates/src/main/webapp/i18n/id/global.json.ejs
- generators/languages/templates/src/main/webapp/i18n/id/health.json.ejs
- generators/languages/templates/src/main/webapp/i18n/id/home.json
- generators/languages/templates/src/main/webapp/i18n/id/login.json
- generators/languages/templates/src/main/webapp/i18n/id/logs.json
- generators/languages/templates/src/main/webapp/i18n/id/metrics.json
- generators/languages/templates/src/main/webapp/i18n/id/password.json
- generators/languages/templates/src/main/webapp/i18n/id/register.json
- generators/languages/templates/src/main/webapp/i18n/id/reset.json.ejs
- generators/languages/templates/src/main/webapp/i18n/id/sessions.json
- generators/languages/templates/src/main/webapp/i18n/id/settings.json
- generators/languages/templates/src/main/webapp/i18n/id/user-management.json
translate some words and fix inconsistent translation
#6092
> update Bahasa Indonesia translation

- generators/docker-base.js
This fix @PierreBesson issue:
https://github.com/jhipster/generator-jhipster/pull/8352#issuecomment-424015424
> Fix docker test command with jib

- generators/server/templates/gradle/docker.gradle.ejs
- generators/server/templates/pom.xml.ejs
- generators/server/templates/src/main/jib/entrypoint.sh.ejs
This upgrade permits to declare environment variables directly in the build tool file (Maven/Gradle) rather than a shell script hack.
if you want a deeper look on the issue fixed with `jib 0.9.11` check the [Milestone report](https://github.com/GoogleContainerTools/jib/milestone/26)
> Move to jib 0.9.11

- generators/docker-utils.js
You've been too fast with #8406 😉 
I made a global search on `dockerfile:build` and `buildDocker` that were the last remaining occurences.
> fix docker missing image gen. command

- .travis.yml
- azure-pipelines.yml
- generators/generator-constants.js
> Upgrade to Node 8.12.0 and Yarn 1.10.1

- generators/server/templates/pom.xml.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/8405
> Fix webpack profile when missing node_modules

- generators/server/templates/src/main/java/package/gateway/responserewriting/SwaggerBasePathRewritingFilter.java.ejs
- generators/server/templates/src/test/java/package/gateway/responserewriting/SwaggerBasePathRewritingFilterTest.java.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/8196
Fix #8328 
> Fix Swagger UI for Microservices

- generators/server/templates/pom.xml.ejs
> Jib: polish template [ci skip]

- .travis.yml
- generators/client/templates/angular/src/test/javascript/protractor.conf.js.ejs
- generators/client/templates/angular/webpack/webpack.dev.js.ejs
- generators/client/templates/react/src/test/javascript/protractor.conf.js.ejs
- generators/client/templates/react/webpack/webpack.dev.js.ejs
> CI: rename JH_var to JHI_var

- generators/server/templates/src/test/java/package/service/UserServiceIntTest.java.ejs
> Fix the UserServiceIntTest with OAuth2

- generators/client/templates/angular/src/main/webapp/app/home/home.component.ts.ejs
> Remove unused code when using oauth2

- generators/client/templates/angular/src/main/webapp/app/shared/shared-libs.module.ts.ejs
- travis/scripts/05-run.sh
Following https://github.com/jhipster/generator-jhipster/pull/8285
Ping @hdurix 
> Travis: fix speed up for noi18n + protractor

- generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs
> Fix wrong user_id type with oauth2 and OneToOne relationship

- generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
> Fix formatting

- generators/server/templates/gradle/profile_prod.gradle.ejs
> Fix gradle prod build issues #8471

- generators/client/templates/react/webpack/webpack.common.js.ejs
Follow the best practices mentioned in [https://webpack.js.org/configuration/](https://webpack.js.org/configuration/)
- Use RegExp only in test and for filename matching
- Use arrays of absolute paths in include and exclude
> [React] Fix webpack configuration module/rules/exclude

- generators/ci-cd/index.js
- generators/ci-cd/prompts.js
- generators/ci-cd/templates/azure-pipelines.yml.ejs
- test/ci-cd.spec.js
Related to https://github.com/jhipster/generator-jhipster/issues/8337
Here the result: https://dev.azure.com/pascalgrimaud/jhipster-ngx-psql-es-noi18n/_build/results?buildId=165&view=logs
Lack of time, I didn't test other config (Gradle, Yarn etc...). Hope it will work.
Ping @jdubois
_____
> CICD: Azure Pipelines support

- generators/server/templates/gradle/docker.gradle.ejs
> sync entrypoint for gradle

- generators/server/templates/src/test/java/package/cucumber/stepdefs/UserStepDefs.java.ejs
> Use Cucumber Expression instead of Regular Expression in steps

- generators/server/templates/src/main/java/package/config/UaaWebSecurityConfiguration.java.ejs
> Remove checked exception from init()

- generators/languages/templates/src/main/resources/i18n/messages_de.properties.ejs
- generators/languages/templates/src/main/webapp/i18n/de/audits.json
- generators/languages/templates/src/main/webapp/i18n/de/error.json
- generators/languages/templates/src/main/webapp/i18n/de/global.json.ejs
- generators/languages/templates/src/main/webapp/i18n/de/reset.json.ejs
- generators/languages/templates/src/main/webapp/i18n/de/tracker.json
- added translations for remaining english/default texts
- beautified some translations
- fixed some comma errors
> Update of german translations

- generators/server/templates/src/main/docker/config/realm-config/jhipster-realm.json.ejs
- add missing /* as context path
> Bugfix to correct webOrigins in web_app

- azure-pipelines.yml
> Azure: reduce number of builds to 10

- generators/server/templates/src/test/java/package/security/jwt/TokenProviderTest.java.ejs
> clean up double import

- generators/entity-server/templates/src/test/gatling/user-files/simulations/EntityGatlingTest.scala.ejs
There is a Gatling issue when choosing Enum + Required.
My add here is:
```javascript
} else if (fields[idx].fieldIsEnum) { %>"<%= fields[idx].fieldValues.split(',')[0] %>"
```
I split to different lines as the code was not really readable
_____
> Fix Gatling for Enum

- generators/entity-client/templates/angular/src/main/webapp/app/entities/ng_validators.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/react_validators.ejs
- generators/entity/index.js
> Escape simple quote in pattern when using React

- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management-update.tsx.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management.reducer.ts.ejs
- generators/client/templates/react/src/main/webapp/app/shared/model/user.model.ts.ejs
> React: Fix user management data prefilling issue

- generators/server/prompts.js
- generators/server/templates/pom.xml.ejs
> Add API-first option for reactive apps

- generators/docker-compose/templates/central-server-config/application.yml.ejs
- generators/server/templates/src/main/resources/config/application-dev.yml.ejs
- generators/server/templates/src/main/resources/config/application-prod.yml.ejs
> Change the sleuth percentage property -> probability

- generators/docker-compose/templates/jhipster-registry.yml.ejs
- generators/server/templates/src/main/docker/app.yml.ejs
- generators/server/templates/src/main/docker/jhipster-registry.yml.ejs
When playing with Microservices + Docker-Compose, these options are needed, otherwise, you won't be able to start everything locally.
_____
> Docker-Compose: limit memory to 512m

- generators/client/templates/angular/package.json.ejs
- generators/client/templates/react/package.json.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/8528
Related to this PR: https://github.com/jhipster/generator-jhipster/pull/8530 -> as discussed @deepu105 , here another proposal. What do you think?
_____
> Reduce webpack logs in dev

- generators/entity-server/templates/src/main/java/package/common/get_all_template.ejs
> [Code Standards] Remove space

- generators/server/files.js
- test/utils/expected-files.js
> Generate correct Feign configuration for JWT gateways

- .travis.yml
- test-integration/scripts/25-sonar-analyze.sh
> Travis: migrate to tests integration

- generators/client/templates/angular/src/main/webapp/index.html.ejs
- generators/client/templates/react/src/main/webapp/index.html.ejs
@pascalgrimaud told me that JHipster needed a message when the front is not compiled, so I did my best to add a cute loader and a message that appears after 4 seconds.
What do you think ?
> add pacman loader and message

- generators/app/index.js
- generators/server/index.js
When generating a microservice, `git commit` is done before the `npm install`
This PR will fix it because I change the place where `npm install` should be done.
But it will reveal another problem with `jhipster import-jdl`
_____
> Fix git commit with microservices

- test/utils/expected-files.js
> Fix npm test with new loading.css file

- generators/entity-server/templates/src/test/gatling/user-files/simulations/EntityGatlingTest.scala.ejs
> follow redirects in gatling test  manually when using oauth

- generators/entity-server/templates/src/main/java/package/common/inject_template.ejs
- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIntTest.java.ejs
- generators/entity/index.js
Fix #8550 
I did a refactor of inject_template to avoid having repeated conditions and have something more "clear".
The issue was because when having an entity using DTO with a relationship with User the resource can't save the User since the DTO doesn't contain all user's data.
@mraible do you think the logic below will need to be the same in case of an entity using DTO? If yes that means the DTO must contain all user's data...
```javascript
<%_ if (saveUserSnapshot) { %>
if (<%= instanceName %>.getUser() != null) {
// Save user in case it's new and only exists in gateway
userRepository.save(<%= instanceName %>.getUser());
}
```
-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) …
> [WIP] Fix relationship with user using microservice and oauth

- generators/app/index.js
Related to https://github.com/jhipster/generator-jhipster/issues/8547
Now, when using `jhipster import-jdl file.jdl`, all applications are correctly committed with git.
_____
> Fix git commit for import-jdl

- generators/gae/templates/appengine-web.xml.ejs
- generators/server/templates/src/main/resources/config/application.yml.ejs
-   [ x Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed
Also removes `logging.file` from `application.yml` for #8582
> Updated Google App Engine Generator for latest JHipster

- generators/client/files-react.js
- generators/client/templates/angular/package.json.ejs
- generators/client/templates/angular/postcss.config.js.ejs
- generators/client/templates/react/package.json.ejs
- generators/client/templates/react/postcss.config.js.ejs
> client: add autoprefixer for postCSS

- generators/docker-compose/templates/traefik.yml.ejs
correct second point of #8578 
> change default traefik port for dashboard

- .travis.yml
Related to https://github.com/jhipster/generator-jhipster/issues/8379
> Travis: use chrome headless

- generators/server/templates/build.gradle.ejs
- generators/server/templates/gradle.properties.ejs
- generators/server/templates/pom.xml.ejs
Depends on https://github.com/jhipster/jhipster/pull/105
Included fix for 2 CVEs: https://spring.io/blog/2018/10/16/spring-project-vulnerability-reports-published
> Update Spring-boot version to 2.0.6 & dependencies

- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIntTest.java.ejs
> Move userRepository arg for int test

- generators/client/templates/angular/src/main/webapp/index.html.ejs
- generators/client/templates/react/src/main/webapp/index.html.ejs
> check if error element is still in dom

- .travis.yml
- generators/utils.js
> replace validation placeholders for React when i18n disabled

- generators/client/templates/angular/src/main/webapp/index.html.ejs
- generators/client/templates/react/src/main/webapp/index.html.ejs
> Indent index html [ci skip]

- generators/ci-cd/templates/.gitlab-ci.yml.ejs
- generators/server/templates/build.gradle.ejs
- generators/server/templates/gradle/profile_dev.gradle.ejs
In order to have e.g. `liquibaseValidate` working correctly the classpath must be the main resources dir. for the `liquibaseDiffChangelog` the compiled main classes dir is correct.
> correct classpath for gradle liquibaseDiffChangelog

- generators/server/templates/src/test/resources/config/application.yml.ejs
> remove the unused version property from test's application.yml

- generators/generator-base.js
> #8561 read skipClient option from entity json

- generators/client/templates/angular/src/main/webapp/app/core/user/user.service.ts.ejs
Removed unused import
-   [x ] Tests are added where necessary
-   [x ] Documentation is added/updated where necessary
-   [x ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed
> Unused import

- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity.service.ts.ejs
Avoids a weird undefined error when http response is different than a OK and that the object contains a date
-   [x ] Tests are added where necessary
-   [x ] Documentation is added/updated where necessary
-   [x ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed
> Avoid undefined exception when response !== 200

- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.route.ts.ejs
Encourages best practices filtering for ok status and returning strongly typed element from method
-   [x ] Tests are added where necessary
-   [x ] Documentation is added/updated where necessary
-   [x ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed
Encourages bests practices by returning strongly typed value of the resolve method, as well as filtering for ok status on http response
> Strongly typed return of the resolve method

- generators/client/templates/angular/src/main/webapp/app/core/auth/account.service.ts.ejs
The account that was returned was not the good one.
Regards,
-   [X ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [X ] Tests are added where necessary
-   [X ] Documentation is added/updated where necessary
-   [X ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed
> Return account model on account service

- generators/app/index.js
> gitInitialized needs to be set if repo is already initialized

- generators/client/templates/angular/src/main/webapp/app/shared/util/datepicker-adapter.ts.ejs
> ensure date value is a Moment object before calling isValid

- generators/client/templates/angular/src/main/webapp/app/core/login/login.service.ts.ejs
correct error 1 and 3 for  #8578
> add location pathname in url for login (oauth2)

- test-integration/scripts/10-install-jhipster.sh
Following discussion in this ticket: https://github.com/jhipster/generator-jhipster/issues/8642
_____
> CI: use npm ci

- generators/client/templates/angular/package.json.ejs
- generators/client/templates/react/package.json.ejs
> Format generated package.json

- azure-pipelines.yml
> Azure: remove maximum execution time

- generators/aws-containers/templates/base.template.yml.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/audits/audits.route.ts.ejs
- generators/client/templates/angular/src/main/webapp/index.html.ejs
- generators/client/templates/react/src/main/webapp/app/app.css.ejs
- generators/client/templates/react/src/main/webapp/app/app.scss.ejs
- generators/client/templates/react/src/main/webapp/app/shared/reducers/action-type.util.ts.ejs
- generators/client/templates/react/src/main/webapp/index.html.ejs
- generators/client/templates/react/src/test/javascript/spec/app/config/axios-interceptor.spec.ts.ejs
- generators/server/templates/src/main/java/package/config/ReactiveSortHandlerMethodArgumentResolver.java.ejs
- generators/server/templates/src/main/resources/config/bootstrap.yml.ejs
Only one of the fixes that actually does anything (audit component defaultSort)
> spelling fixes

- generators/client/templates/angular/package.json.ejs
> upgrade to ng-bootstrap 4.0.0, to be fully compatible with Angular 7

- .gitignore
- .travis.yml
> Update gitignore for vscode and comments in Travis file [ci skip]

- generators/aws-containers/templates/application.template.yml.ejs
- generators/client/templates/angular/src/main/webapp/app/account/password/password-strength-bar.component.ts.ejs
- generators/client/templates/react/src/main/webapp/app/shared/layout/password/password-strength-bar.tsx.ejs
- generators/server/templates/src/main/java/package/config/CacheConfiguration.java.ejs
@deepu105 To answer your question on how I found these, half were in a note that I added to over time. The others were from [scspell](https://github.com/myint/scspell), there are too many false positives though.
> spelling fixes [ci skip]

- .travis.yml
- Dockerfile
- azure-pipelines.yml
- generators/generator-constants.js
Fix https://github.com/jhipster/generator-jhipster/issues/8682
Another PR: https://github.com/jhipster/jhipster-devbox/pull/98
_____
> Upgrade to Node 10.13.0 LTS

- generators/server/templates/src/main/java/package/config/DatabaseConfiguration.java.ejs
closes #8639 
But first, have to validate whether this approach is fine. r? @jdubois 
> fix(port): makes h2 DB to take a port within the range)

- generators/client/templates/angular/package.json.ejs
> Remove exports-loader

- generators/client/templates/angular/package.json.ejs
> Remove tapable

- generators/entity-server/templates/src/main/java/package/common/inject_template.ejs
- generators/kubernetes/templates/deployment.yml.ejs
- generators/kubernetes/templates/registry/jhipster-registry.yml.ejs
- generators/openshift/templates/registry/jhipster-registry.yml.ejs
- generators/server/templates/src/main/resources/config/application-prod.yml.ejs
> Change the jwt secret property to the base64 secret where it was missing

- generators/client/templates/angular/package.json.ejs
> Remove raw-loader

- generators/server/templates/src/main/docker/app.yml.ejs
- updated condition check
Fixes #8674
> Remove keycloak.yml inclusion for micoservices with oauth2

- package-lock.json
- package.json
Most important change in this release: apps are validated after parsing
> Updated JCore dep to v3.5.0

- Dockerfile
Related to https://github.com/jhipster/generator-jhipster/pull/8725
_____
> Use fixed Node version instead of latest [ci skip]

- .travis.yml
- azure-pipelines.yml
- test-integration/scripts/03-system.sh
- test-integration/scripts/10-install-jhipster.sh
- test-integration/scripts/11-generate-entities.sh
- test-integration/scripts/13-replace-version-generated-project.sh
- test-integration/scripts/23-package.sh
- test-integration/scripts/24-tests-e2e.sh
> Ci improve logs

- generators/server/templates/src/test/java/package/web/rest/AuditResourceIntTest.java.ejs
> Add unit test for equals/hashCode() methods of PersistentAuditEvent

- generators/kubernetes/templates/console/jhipster-elasticsearch.yml.ejs
> remove storageClassName fields from jhipster-elasticsearch.yml.ejs

- package-lock.json
- package.json
Point 3: the deployment config for the JDL needs some doc, but this is mergeable.
> Updated the JCore dependency to v3.6.1

- .travis.yml
- test-integration/scripts/11-generate-entities.sh
- test-integration/scripts/20-docker-compose.sh
- test-integration/scripts/25-sonar-analyze.sh
> Sonar: launch analyze

- azure-pipelines.yml
- test-integration/scripts/20-no-memory-limit-elasticsearch.sh
> Azure: no memory limit when using Elasticsearch

- generators/client/templates/angular/angular.json.ejs
> set the correct client package manager npm/yarn in angular.json

- generators/server/templates/src/main/resources/config/application-dev.yml.ejs
- generators/server/templates/src/main/resources/config/application.yml.ejs
> correct spring boot configuration

- generators/server/templates/src/main/java/package/security/PersistentTokenRememberMeServices.java.ejs
> Correctly delete tokens with JPA

- generators/client/templates/angular/src/main/webapp/app/admin/admin.module.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/app.module.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/shared/shared-libs.module.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/shared/shared.module.ts.ejs
- test-integration/scripts/23-package.sh
> init jhipster module in app to have only one alert listener

- test/cli/cli-utils.spec.js
- test/cli/cli.spec.js
- test/cli/import-jdl.spec.js
These are the ones I forgot in my previous PR:
https://github.com/jhipster/generator-jhipster/pull/8493
> Clean eslint oriented instructions in tests #2

- test-integration/scripts/25-sonar-analyze.sh
> CI: increase sleep for Sonar results and display Sonar container logs

- generators/client/templates/angular/package.json.ejs
- generators/client/templates/react/package.json.ejs
> update ng-jhipster and react-jhipster

- generators/client/templates/angular/package.json.ejs
- generators/client/templates/angular/webpack/webpack.common.js.ejs
- generators/client/templates/angular/webpack/webpack.dev.js.ejs
> Update Webpack version for Angular

- generators/client/templates/react/package.json.ejs
> client: angular: remove unused dependency

- .travis.yml
- azure-pipelines.yml
- cli/import-jdl.js
- cli/utils.js
- generators/client/templates/angular/package.json.ejs
- generators/client/templates/react/package.json.ejs
- generators/client/templates/react/src/test/javascript/spec/app/config/notification-middleware.spec.ts.ejs
- generators/client/templates/react/src/test/javascript/spec/app/modules/account/password/password.reducer.spec.ts.ejs
- generators/client/templates/react/src/test/javascript/spec/app/modules/account/register/register.reducer.spec.ts.ejs
- generators/client/templates/react/src/test/javascript/spec/app/modules/account/settings/settings.reducer.spec.ts.ejs
- generators/client/templates/react/src/test/javascript/spec/app/shared/auth/private-route.spec.tsx.ejs
- test-integration/samples/.gitignore
- test-integration/samples/jdl-default/app.jdl
- test-integration/scripts/01-display-configuration.sh
- test-integration/scripts/04-git-config.sh
- test-integration/scripts/11-generate-entities.sh
- test-integration/scripts/12-generate-project.sh
- test/cli/cli-utils.spec.js
- test/cli/import-jdl.spec.js
> CI with JDL

- package-lock.json
- package.json
Fixes an issue when exporting to JDL with a deployment conf setup.
> Updated JCore dep version to v3.6.7

- generators/client/templates/angular/src/main/webapp/content/css/loading.css.ejs
- generators/client/templates/react/src/main/webapp/static/css/loading.css.ejs
> Merge duplicate CSS selector

- test-integration/scripts/25-sonar-analyze.sh
It should fix the Sonar analyze with jq
_____
> Fix Sonar analyze with jq

- generators/ci-cd/index.js
- generators/ci-cd/templates/.gitlab-ci.yml.ejs
- generators/ci-cd/templates/azure-pipelines.yml.ejs
- generators/ci-cd/templates/jenkins/Jenkinsfile.ejs
- generators/ci-cd/templates/travis.yml.ejs
- generators/client/templates/react/package.json.ejs
- test/cli/cli-utils.spec.js
Fix https://github.com/jhipster/generator-jhipster/issues/8612
_____
> CICD: fix React snapshots

- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.reducer.ts.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs
- generators/entity-client/templates/react/src/test/javascript/spec/app/entities/entity-reducer.spec.ts.ejs
Fix #8506
Depends on the react-jhipster PR linked below
> implement pagination for react elasticsearch

- test-integration/scripts/20-docker-compose.sh
- test-integration/scripts/23-package.sh
- test-integration/scripts/24-tests-e2e.sh
> CI: use uaa with dev profile

- generators/client/templates/angular/src/main/webapp/app/shared/alert/alert-error.component.ts.ejs
> Refacto addErrorAlert()

- README.md
Here the migration of daily builds:
- old repo: https://github.com/hipster-labs/jhipster-travis-build
- new repo: https://github.com/hipster-labs/jhipster-daily-builds
I plan to add Docker-Compose builds, CICD builds and if possible, Kubernetes builds.
_____
> Update README with Azure builds [ci skip]

- generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIntTest.java.ejs
> Fix custom validators with @Autowired repos/services

- generators/server/templates/build.gradle.ejs
- generators/server/templates/pom.xml.ejs
> JDK 11 support

- generators/client/templates/angular/.prettierignore.ejs
- generators/client/templates/angular/package.json.ejs
- generators/client/templates/react/.prettierignore.ejs
- generators/client/templates/react/package.json.ejs
- generators/generator-base-private.js
> Enable prettier for Markdown and json files in root directory

- README.md
> Update logo in README [ci skip]

- generators/generator-base.js
> Fix lint errors by applying prettier

- generators/entity-server/templates/src/main/java/package/service/dto/EntityCriteria.java.ejs
- generators/server/templates/src/main/java/package/web/rest/errors/ExceptionTranslator.java.ejs
> Fix critical sonar issues

- generators/server/templates/gradle.properties.ejs
- generators/server/templates/pom.xml.ejs
Depends on https://github.com/jhipster/jhipster/pull/131
> Upgrade spring-boot version to 2.0.7.RELEASE

- generators/client/templates/angular/src/main/webapp/app/core/auth/account.service.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/core/login/login.service.ts.ejs
> move user preferred lang selection to login service for UAA

- generators/server/templates/pom.xml.ejs
- test/app.spec.js
- test/utils/expected-files.js
> Make sure pom.xml doesn't have any reference to liquibase if no sql database is used

- generators/generator-constants.js
- Yarn version upgraded to 1.12.3
> Bumped yarn version

- generators/client/templates/angular/src/main/webapp/app/account/sessions/sessions.component.html.ejs
- generators/client/templates/angular/src/main/webapp/index.html.ejs
- generators/client/templates/react/src/main/webapp/app/modules/account/sessions/sessions.tsx.ejs
- generators/client/templates/react/src/main/webapp/index.html.ejs
> fix "occurred" typo

- generators/languages/templates/src/main/webapp/i18n/fr/health.json.ejs
> Fix some typos in the French translation

- generators/app/index.js
- generators/aws-containers/index.js
- generators/ci-cd/index.js
- generators/client/index.js
- generators/common/index.js
- generators/entity/index.js
- generators/export-jdl/index.js
- generators/generator-base-docker.js
- generators/generator-base-private.js
- generators/server/index.js
- generators/spring-controller/index.js
- generators/spring-service/index.js
- generators/upgrade/index.js
> Fix invocation from Yeoman and factor the check that generator has been invoked from JHipster CLI

- generators/common/index.js
> Pass 'client-hook' option to common blueprint

- generators/client/templates/angular/src/main/webapp/app/layouts/navbar/navbar.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/layouts/navbar/navbar.scss.ejs
- generators/generator-constants.js
- Refactor navbar styles to reduce customization done on top of bootstrap styles and reuse bootstrap variables
- Sync navbar template with bootstrap
> Refactor navbar template and styles

- generators/server/templates/src/test/java/package/web/rest/TestUtil.java.ejs
> Do not create a mapper for every call to convertObjectToJsonBytes

- generators/server/templates/src/main/java/package/config/CacheConfiguration.java.ejs
- generators/server/templates/src/main/java/package/web/rest/AccountResource.java.ejs
> Remove finals that are now implicit

- generators/generator-base-private.js
instead of always using moment. Follow up of https://github.com/jhipster/jhipster-vuejs/pull/144#issuecomment-449386970
> make date field type configurable

- generators/entity/index.js
- generators/generator-base.js
- test/entity.spec.js
- test/templates/default-gateway/.jhipster/Baz.json
- test/utils/expected-files.js
> Handle database type in entity subgen

- generators/server/files.js
- generators/server/templates/src/main/java/package/config/lazy/LazyInitBeanFactoryPostProcessor.java.ejs
- generators/server/templates/src/main/resources/logback-spring.xml.ejs
- test/utils/expected-files.js
This is gives a huge performance boost, but is considered experimental, so this is only configured in dev mode for the moment.
See #8954
> Lazy init Spring Beans at start-up.

- generators/client/templates/angular/src/test/javascript/jest.conf.js.ejs
- generators/client/templates/react/src/test/javascript/jest.conf.js.ejs
> Exclude javascript test directory from coverage reports

- generators/server/files.js
- generators/server/prompts.js
- generators/server/templates/src/main/java/package/config/DatabaseConfiguration.java.ejs
- generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs
- generators/server/templates/src/main/java/package/repository/reactive/CustomReactiveN1qlCouchbaseRepository.java.ejs
- generators/server/templates/src/main/java/package/repository/reactive/ReactiveN1qlCouchbaseRepository.java.ejs
- generators/server/templates/src/main/java/package/service/UserService.java.ejs
- travis/samples/reactive-couchbase/.yo-rc.json
https://github.com/jhipster/generator-jhipster/issues/7608
This needs spring-boot 2.1.0 as it fixes https://github.com/spring-projects/spring-data-couchbase/pull/171
> Add Couchbase reactive option

- generators/server/templates/src/main/java/package/config/LoggingConfiguration.java.ejs
Removed duplicated comment and assignation.
Related issue : https://github.com/jhipster/generator-jhipster/issues/9024
Note :
The modification was done through github online editor thus no test nor build including this change have yet been done.
> Remove duplication

- generators/client/templates/react/src/main/webapp/app/app.css.ejs
css don't have comment like '//'
[Comment in css](https://developer.mozilla.org/en-US/docs/Web/CSS/Comments)
> fix comment of app.css.ejs

- generators/server/templates/build.gradle.ejs
https://www.jhipster.tech/configuring-ide-idea/
can remove "Exclude directories" node
> exclude node_modules  dir in idea project

- generators/client/templates/angular/src/main/webapp/app/entities/entity.module.ts.ejs
- generators/client/templates/angular/tslint.json.ejs
- generators/entity-client/files.js
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-delete-dialog.component.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.module.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.route.ts.ejs
- generators/entity-client/templates/angular/src/test/javascript/e2e/entities/entity.spec.ts.ejs
- generators/generator-base.js
- generators/utils.js
> angular: Lazy load entities

- generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity_constraints.xml.ejs
> fix generation of FK constraints for @ManyToMany

- .travis.yml
- Dockerfile
- azure-pipelines.yml
- generators/generator-constants.js
> Upgrade to Node 10.15.0

- generators/entity-server/templates/src/main/java/package/common/delete_template.ejs
- generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs
As per https://github.com/jhipster/generator-jhipster/pull/8685#discussion_r247340776, this will remove blank lines.
Also remove some trailing whitespaces and a blank line in `delete` method.
> Remove blank lines in generated code

- generators/server/templates/src/test/java/package/cucumber/CucumberContextConfiguration.java.ejs
when moving the file to parent folder, I didn't update the package
Fix #9043
> fix package on new CucumberContextConfiguration class

- generators/server/templates/src/main/java/package/service/UserService.java.ejs
This also fixes the failing `webflux-mongodb` test for Azure Pipelines as also discussed in https://github.com/jhipster/generator-jhipster/pull/9063#issuecomment-454417337
> fix UserService.java.ejs for reactive

- generators/client/templates/angular/src/main/webapp/app/admin/audits/audits.component.ts.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management.component.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.html.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.ts.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/infinite-scroll-template.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/pagination-template.ejs
> Reduntant this.queryCount and this.totalItems? #9057 commit

- azure-pipelines.yml
- test-integration/scripts/04-git-config.sh
- Remove execution of `00-init-env.sh` from `04-git-config.sh` as it is not needed by git config
- Use Azure official env var for `$(Build.Repository.LocalPath)`. See also [Azure Pipelines - Predefined build variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=vsts#build-variables)
- Use `$(JHI_SCRIPTS)` to define path of `20-no-memory-limit-elasticsearch.sh`
> CI build scripts improvements

- generators/entity/prompts.js
- generators/generator-base-private.js
- generators/generator-base.js
- generators/languages/index.js
- generators/languages/prompts.js
- test/blueprint/languages-blueprint.spec.js
- test/utils/expected-files.js
Related to https://github.com/jhipster/jhipster-vuejs/issues/132
This is needed in Vue.js blueprint.
cc @sahbi-ktifa 
Now, I understand the amount of work you did in blueprint / refactoring yeoman. I spent days on this!
That's why I assigned to you @murdos, if you can help in review.
_____
> blueprint for languages sub generator

- generators/server/templates/src/main/resources/config/liquibase/changelog/initial_schema.xml.ejs
> avoid error: max key length, shortend the email field to 191. see: #8604

- generators/upgrade/index.js
- test/upgrade.spec.js
This branch is based on my other PR #8932
> Handle blueprint in upgrade subgenerator

- generators/server/templates/pom.xml.ejs
- test/app.spec.js
> Don't define unnecessary node.version and npm.version properties if skipClient

- generators/ci-cd/templates/.gitlab-ci.yml.ejs
- generators/ci-cd/templates/jenkins/Jenkinsfile.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/9035
Fix bug introduced by https://github.com/jhipster/generator-jhipster/pull/8986
_____
> Fix CICD test folder and jenkins user

- generators/server/templates/src/main/java/package/service/UserService.java.ejs
> Add null checking when getting preferred_username from IDP

- generators/client/templates/angular/package.json.ejs
Depends on https://github.com/jhipster/generator-jhipster/pull/9066
> Bump angular versions

- generators/entity/index.js
> Do not warn when otherEntityRelationshipName is missing and other entity is User

- test-integration/scripts/25-sonar-analyze.sh
> Sonar: no use of jq

- generators/entity-server/templates/src/main/java/package/service/dto/EntityDTO.java.ejs
- test/entity.spec.js
> Api docs into dto: tests and missing change from code review

- generators/languages/templates/src/main/webapp/i18n/es/error.json
> adding missing strings

- generators/languages/templates/src/main/resources/i18n/messages_es.properties.ejs
> Adding missing string

- generators/upgrade/index.js
> Upgrade: Fix incorrect parameter for npm

- generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics.component.html.ejs
- generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics.component.ts.ejs
> fix: do not display datasource/http metric component if datasource/http values are missing

- generators/entity-server/templates/src/main/java/package/service/impl/EntityServiceImpl.java.ejs
Hi, this is a tiny fix for the ServiceImpl.java template. Just adding a newline, as the result bothers me a little.
Let me know if you want me to open an issue.
Thank you for your job!
Massimo
> fix the newline in the service implementation

- azure-pipelines.yml
- generators/ci-cd/templates/azure-pipelines.yml.ejs
> [v5.x_maintenance] Azure: fix permission denied with NPM

- test-integration/scripts/23-package.sh
> CI: fix war path for uaa

- generators/generator-transforms.js
Files mark as 'deleted' has not content defined.
We have to skip them.
#9211 
Same as #9213 but for v5.
(I'm not sur I have to do 2 PR but if it can help I do).
> [v5 maintenance] Add 'not delete state' condition on file when applying prettierTransform

- generators/client/templates/react/.editorconfig
- generators/common/templates/.prettierrc.ejs
- generators/common/templates/editorconfig.ejs
- generators/entity-client/templates/react/.editorconfig
- generators/generator-transforms.js
- test/app.spec.js
Based on discussion https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jhipster-dev/s-BtFM-PSyg/AxaoR9pxFgAJ
> angular: change tabWidth for angular

- package-lock.json
- package.json
> Updated JCore to v3.6.10

- generators/client/files-angular.js
- generators/client/files-react.js
- generators/client/index.js
- generators/client/templates/angular/package.json.ejs
- generators/client/templates/angular/src/main/webapp/WEB-INF/web.xml.ejs
- generators/client/templates/angular/tsconfig-aot.json.ejs
- generators/client/templates/angular/webpack/webpack.dev.js.ejs
- generators/client/templates/angular/webpack/webpack.prod.js.ejs
- generators/client/templates/react/package.json.ejs
- generators/client/templates/react/src/main/webapp/WEB-INF/web.xml.ejs
- generators/client/templates/react/webpack/webpack.dev.js.ejs
- generators/client/templates/react/webpack/webpack.prod.js.ejs
- generators/common/index.js
- generators/generator-base-private.js
- generators/generator-constants.js
- generators/server/index.js
- generators/server/templates/build.gradle.ejs
- generators/server/templates/gradle/docker.gradle.ejs
- generators/server/templates/gradle/profile_dev.gradle.ejs
- generators/server/templates/gradle/profile_prod.gradle.ejs
- generators/server/templates/pom.xml.ejs
- generators/server/templates/src/main/docker/.dockerignore.ejs
- generators/server/templates/src/test/java/package/config/WebConfigurerTest.java.ejs
- test/utils/expected-files.js
> Move client app to classpath:/public

- .travis.yml
- azure-pipelines.yml
- generators/server/templates/build.gradle.ejs
- generators/server/templates/gradle.properties.ejs
- generators/server/templates/pom.xml.ejs
- generators/server/templates/src/main/java/package/config/OAuth2Configuration.java.ejs
- generators/server/templates/src/main/java/package/config/lazy/LazyInitBeanFactoryPostProcessor.java.ejs
> Switch to jhipster-dependencies master branch

- generators/generator-transforms.js
little esLint fix to generator-transform.js
> fix lint in generator-transform

- generators/server/templates/build.gradle.ejs
- generators/server/templates/gradle.properties.ejs
- generators/server/templates/pom.xml.ejs
> Update mapstruct version to 1.3.0.Final

- generators/gae/index.js
Fix https://github.com/jhipster/generator-jhipster/issues/9237
> fix: allow use gae generator with custom db name

- generators/client/templates/angular/package.json.ejs
> Update angular dependencies

- generators/entity-client/index.js
- generators/entity-i18n/index.js
- generators/entity-server/index.js
- generators/entity/index.js
- generators/spring-controller/index.js
- generators/spring-service/index.js
This is actually the same code also used in other blueprint generators
such as client, server, etc.
Relates to issue 2 of #9232
> Also resolve blueprint from options or configOptions

- generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics.service.ts.ejs
- generators/client/templates/angular/src/test/javascript/spec/app/admin/metrics/metrics.service.spec.ts.ejs
- generators/client/templates/react/src/main/webapp/app/modules/administration/administration.reducer.ts.ejs
- generators/server/templates/src/main/resources/config/application.yml.ejs
As discussed with @pascalgrimaud and @PierreBesson, remove invalid character from jhi-metrics to remove the error in the console when launching the app
Related to jhipster/jhipster#181
> Remove invalid character from uri

- CONTRIBUTING.md
update link to `Google JavaScript Style Guide`
> fix broken link in documentation

- generators/client/templates/angular/package.json.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.ts.ejs
- generators/entity/prompts.js
- generators/generator-base.js
- test-integration/samples/README.md
Updating core generator to use the new dataUtils.setFileData() per [this discussion](https://github.com/jhipster/ng-jhipster/pull/88#issuecomment-457581776)
----
> Use updated dataUtils.setFileData() and handle returned promise

- generators/client/index.js
- generators/docker-compose/templates/traefik/traefik.toml.ejs
- generators/entity-client/templates/angular/src/main/webapp/app/entities/entity.service.ts.ejs
- generators/entity-client/templates/react/src/main/webapp/app/entities/entity.reducer.ts.ejs
- generators/server/templates/src/main/resources/config/application.yml.ejs
Related to #9098
For some reason, microservices don't work on master for me (see #9261).  I tested these changes with v5.8.2 and it worked. Will need more testing.
I wasn't sure about the `context-path` config, but I believe it's for Istio and we would need the path to match the microservice URL paths.
> update microservice path prefix to begin with /services/

- azure-pipelines.yml
Related to https://github.com/jhipster/generator-jhipster/issues/9263
> CI: fix Azure with React session build

- package-lock.json
- package.json
Update yeoman dependencies:
- `yeoman-generator: 3.2.0`
- `yeoman-environment: 2.3.4`
- `yeoman-test: 1.9.1`
I have tested these for the main generator and the Kotlin and VueJS blueprints for #9266
I will create similar PRs for the blueprints
> Update yeoman dependencies

- generators/server/templates/gradle.properties.ejs
- generators/server/templates/pom.xml.ejs
> Update spring-boot version to 2.1.3.RELEASE

- package-lock.json
- package.json
> Updated JCore's dep

- package-lock.json
- package.json
> upgrade jhipster-core for v5.x_maintenance

- generators/server/templates/src/main/java/package/service/UserService.java.ejs
> Add missing semicolon to UserService

- generators/gae/index.js
- generators/gae/templates/application-prod-gae.yml.ejs
> feat: allow use of postgresql with gae

- generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs
- generators/server/templates/src/main/java/package/web/rest/UserResource.java.ejs
- generators/server/templates/src/main/java/package/web/rest/errors/ExceptionTranslator.java.ejs
- generators/server/templates/src/main/resources/config/application.yml.ejs
This PR along with https://github.com/jhipster/jhipster/pull/188 are an attempt to fix issue #9282.
The JHipster PR will need to be merged first and then this one in order for everything to work properly
> Use config property "jhipster.clientApp.name" and `enableTranslation` flag when using HeaderUtil methods

- generators/generator-base.js
- generators/internal/needle-api/index.js
- test/needle-api/needle-client.spec.js
> Fix needleApi injection, external resources public API and add unit tests 

- generators/app/index.js
- generators/generator-base.js
- generators/server/index.js
- generators/server/templates/src/main/java/package/web/rest/AuditResource.java.ejs
- test/app.spec.js
- test/utils/expected-files.js
> Add missing UAA gateway mocha tests

- generators/server/templates/pom.xml.ejs
> Fix #9317 outputDirectory is not a valid configuration for

- generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs
- package-lock.json
Add required parameter for required relationship
Fix #9128
> Fix missing required validation on relationship on React

- generators/server/templates/src/main/java/package/repository/PersistentTokenRepository.java.ejs
- generators/server/templates/src/main/java/package/security/PersistentTokenRememberMeServices.java.ejs
> Fix couchbase token repository not compiling.

- generators/app/index.js
- generators/server/templates/src/main/java/package/config/ReactiveSecurityConfiguration.java.ejs
- generators/server/templates/src/main/java/package/config/WebConfigurer.java.ejs
- test-integration/samples/webflux-mongodb/.yo-rc.json
> Serve static content in reactive apps

- generators/entity-server/templates/src/main/java/package/common/get_all_template.ejs
- generators/entity-server/templates/src/main/java/package/service/EntityQueryService.java.ejs
- generators/entity-server/templates/src/main/java/package/service/EntityService.java.ejs
- generators/entity-server/templates/src/main/java/package/service/dto/EntityCriteria.java.ejs
- generators/entity-server/templates/src/main/java/package/service/impl/EntityServiceImpl.java.ejs
- generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs
- generators/server/templates/src/main/java/package/aop/logging/LoggingAspect.java.ejs
- generators/server/templates/src/main/java/package/config/ReactivePageableHandlerMethodArgumentResolver.java.ejs
- generators/server/templates/src/main/java/package/config/ReactiveSortHandlerMethodArgumentResolver.java.ejs
- generators/server/templates/src/main/java/package/config/UaaConfiguration.java.ejs
- generators/server/templates/src/main/java/package/config/UaaWebSecurityConfiguration.java.ejs
- generators/server/templates/src/main/java/package/config/audit/AuditEventConverter.java.ejs
- generators/server/templates/src/main/java/package/config/oauth2/OAuth2JwtAccessTokenConverter.java.ejs
- generators/server/templates/src/main/java/package/security/PersistentTokenRememberMeServices.java.ejs
- generators/server/templates/src/main/java/package/security/oauth2/OAuth2AuthenticationService.java.ejs
- generators/server/templates/src/main/java/package/security/oauth2/OAuth2CookieHelper.java.ejs
- generators/server/templates/src/main/java/package/security/oauth2/OAuth2SignatureVerifierClient.java.ejs
- generators/server/templates/src/main/java/package/web/rest/AccountResource.java.ejs
Yet some more minor javadoc fixes(less this time :) ) as I did another pass comparing with the Kotlin code to make sure they are aligned.
> Javadoc fixes

- generators/internal/needle-api/needle-base.js
- generators/internal/needle-api/needle-server-maven.js
- test/needle-api/needle-client-i18n.spec.js
- test/needle-api/needle-client-webpack.spec.js
- test/needle-api/needle-server-cache.spec.js
- test/needle-api/needle-server-gradle.spec.js
- test/needle-api/needle-server-liquibase.spec.js
- test/needle-api/needle-server-maven.spec.js
- test/needle-api/templates/src/main/resources/config/liquibase/changelog/dummy_changelog.xml.ejs
Adding tests for the needle API:
-   [x] base (done in #9151)
-   [X] client (done in #9233)
-   [x] client-angular (started at  #9151 and finished at #9321)
-   [X] client-i18n
-   [X] client-react (done in #9151)
-   [x] client-webpack
-   [x] server-cache
-   [x] server-gradle
-   [x] server-liquibase
-   [x] server-maven
------
> Add needle api unit tests

- generators/generator-constants.js
> Update npm to 6.8.0

- .travis.yml
- Dockerfile
- azure-pipelines.yml
- generators/generator-constants.js
> Update Node to 10.15.2

- package-lock.json
- package.json
Note: It is also possible to add `[skip ci]` to your commit message to skip Travis tests
> Updated the JCore dep to v3.6.12

- generators/aws/lib/s3.js
- generators/server/files.js
- generators/server/prompts.js
- generators/server/templates/src/main/java/package/config/ReactiveSecurityConfiguration.java.ejs
- generators/server/templates/src/main/java/package/config/WebConfigurer.java.ejs
- generators/server/templates/src/main/java/package/service/UserService.java.ejs
- generators/server/templates/src/main/java/package/service/util/RandomUtil.java.ejs
- generators/server/templates/src/main/java/package/web/rest/AccountResource.java.ejs
- generators/server/templates/src/main/resources/config/application-dev.yml.ejs
- generators/server/templates/src/main/resources/config/application-prod.yml.ejs
- generators/server/templates/src/test/java/package/repository/CustomAuditEventRepositoryIT.java.ejs
- generators/server/templates/src/test/java/package/security/SecurityUtilsUnitTest.java.ejs
- generators/server/templates/src/test/java/package/service/UserServiceIT.java.ejs
- generators/server/templates/src/test/java/package/web/rest/AccountResourceIT.java.ejs
- generators/server/templates/src/test/resources/config/application.yml.ejs
Note : no support for remember-me (the checkbox is still present in the front but has no effect)
> Support for session auth in reactive apps

- generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs
> Make the prometheus endpoint public

- generators/aws-containers/index.js
- generators/aws/index.js
- generators/ci-cd/index.js
- generators/cloudfoundry/index.js
- generators/docker-compose/index.js
- generators/gae/index.js
- generators/generator-base-docker.js
- generators/generator-base-private.js
- generators/heroku/index.js
- generators/openshift/templates/db/cassandra.yml.ejs
- generators/openshift/templates/db/couchbase.yml.ejs
- generators/openshift/templates/db/elasticsearch.yml.ejs
- generators/openshift/templates/db/mariadb.yml.ejs
- generators/openshift/templates/db/mongodb.yml.ejs
- generators/openshift/templates/db/mysql.yml.ejs
- generators/openshift/templates/db/postgresql.yml.ejs
- generators/openshift/templates/deployment.yml.ejs
- generators/openshift/templates/messagebroker/kafka.yml.ejs
- generators/openshift/templates/monitoring/jhipster-metrics.yml.ejs
- generators/openshift/templates/monitoring/jhipster-monitoring.yml.ejs
- generators/openshift/templates/registry/jhipster-registry.yml.ejs
- generators/server/index.js
> Use prettier transform for deployment subgens

- generators/client/templates/angular/package.json.ejs
- generators/client/templates/angular/webpack/webpack.common.js.ejs
Update to Angular 7.2.7 and other minor and patch releases
In continuation of #9333 
Relates to #9285 
> Update node dependencies for Angular apps

- generators/kubernetes-helm/files.js
- test/kubernetes.helm.spec.js
> Fix Kubernetes Helm Sub Generator test due to changes in #8987
