jhipster/generator-jhipster

test-integration/samples/jdl-default/app.jdl
As discussed in #9212, I have added more entities and relationships that cover more test cases that I have copied over from https://github.com/pvliss/jhipster-core/blob/64786e8429b68e3ff0fbfd6384723340ca205456/test/test_files/big_sample.jdl.
This will cause the CI builds to fail and an upgrade to jhipster-core that contains https://github.com/jhipster/jhipster-core/pull/304 will be needed in order for everything to pass successfully
Relates to #9212 and #9202  …
=> This improves the JDL import test for the CI by adding more cases

generators/server/templates/src/main/java/package/service/UserService.java.ejs
Fixes https://github.com/jhipster/generator-jhipster/issues/9400.
=> Set locale to 'en' if not specified by IdP

generators/entity-server/templates/src/main/java/package/common/get_all_template.ejs, generators/entity-server/templates/src/main/java/package/common/search_template.ejs, generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs, generators/server/templates/src/main/java/package/web/rest/AuditResource.java.ejs, generators/server/templates/src/main/java/package/web/rest/UserResource.java.ejs
=> Use new generatePaginationHttpHeaders

generators/server/templates/build.gradle.ejs, generators/server/templates/pom.xml.ejs, generators/server/templates/src/main/java/package/config/WebConfigurer.java.ejs
=> Use Netty instead of Undertow for reactive apps

generators/server/templates/src/main/java/package/domain/User.java.ejs, generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs, generators/server/templates/src/main/java/package/security/DomainUserDetailsService.java.ejs, generators/server/templates/src/main/java/package/service/UserService.java.ejs, generators/server/templates/src/main/java/package/web/rest/AccountResource.java.ejs, generators/server/templates/src/main/java/package/web/rest/UserResource.java.ejs, generators/server/templates/src/test/java/package/service/UserServiceIT.java.ejs, generators/server/templates/src/test/java/package/web/rest/AccountResourceIT.java.ejs, generators/server/templates/src/test/java/package/web/rest/UserJWTControllerIT.java.ejs, generators/server/templates/src/test/java/package/web/rest/UserResourceIT.java.ejs, generators/server/templates/src/test/java/package/web/rest/errors/ExceptionTranslatorIT.java.ejs
=> Add cassandra support for reactive apps

generators/languages/templates/src/main/webapp/i18n/fr/global.json.ejs
=> Fix french translation for the password component

generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management-update.component.html.ejs, generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management-update.component.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/app/admin/user-management/user-management-update.component.spec.ts.ejs
Replace ngModel occurrence with corresponding reactive form control, update tests
=> Fix user management create/edit flows

generators/generator-constants.js
=> Use openjdk 11 JRE docker image fix #9448

generators/server/templates/src/main/java/package/config/LoggingConfiguration.java.ejs, generators/server/templates/src/main/resources/config/application-dev.yml.ejs, generators/server/templates/src/main/resources/config/application-prod.yml.ejs, generators/server/templates/src/main/resources/config/application.yml.ejs, generators/server/templates/src/main/resources/config/bootstrap.yml.ejs, generators/server/templates/src/test/resources/config/application.yml.ejs
Fix #9428 
Included fix for logging the version broken since migration to SB2.
=> Format logs in Json

.travis.yml, Dockerfile, azure-pipelines.yml, generators/generator-constants.js
Update Node to 10.15.3
Changelog: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#2019-03-05-version-10153-dubnium-lts-bethgriggs
=> Update Node to 10.15.3

generators/generator-constants.js
Changelog: https://github.com/npm/cli/blob/latest/CHANGELOG.md#v690-2018-02-20
=> Update npm to 6.9.0

generators/server/templates/build.gradle.ejs, generators/server/templates/gradle/wrapper/gradle-wrapper.properties
Update Gradle to 5.3
Changelog: https://docs.gradle.org/5.3/release-notes.html
=> Update Gradle to 5.3

generators/entity-server/templates/src/main/java/package/repository/EntityRepository.java.ejs
=> User entityInstance instead of entityTableName in JPQL queries

generators/cleanup.js
Related with https://github.com/jhipster/generator-jhipster/issues/9276
Fix #9439
=> Remove AUTH2 classes not used.

generators/server/templates/src/main/java/package/config/lazy/LazyInitBeanFactoryPostProcessor.java.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/9261
=> Fix lazy init bean with Gateway application

generators/kubernetes-helm/files.js, generators/kubernetes-helm/templates/app/requirements.yml.ejs, generators/kubernetes-helm/templates/app/values.yml.ejs, generators/kubernetes-helm/templates/csvc/requirements.yml.ejs, generators/kubernetes-helm/templates/csvc/values.yml.ejs, generators/kubernetes-helm/templates/helm-apply.sh.ejs, generators/kubernetes-helm/templates/helm-upgrade.sh.ejs, generators/kubernetes/files.js, generators/kubernetes/templates/db/postgresql.yml.ejs, generators/kubernetes/templates/deployment.yml.ejs, generators/kubernetes/templates/istio/gateway/jhipster-console-gateway.yml.ejs, generators/kubernetes/templates/istio/gateway/jhipster-grafana-gateway.yml.ejs, generators/kubernetes/templates/kubectl-apply.sh.ejs
- update helm generated services 
- remove kiali, as the latest istio release includes it out of the box
- helm services version upgrade
=> update helm generator for istio changes

generators/server/templates/build.gradle.ejs, generators/server/templates/pom.xml.ejs
Related with jhipster/generator-jhipster#9416
=> Remove spring-security-oauth2-autoconfigure

generators/server/templates/src/main/docker/elasticsearch.yml.ejs
=> Change docker compose file version number from 2.2 to 2 for elasticsearch

generators/generator-base-private.js, test/blueprint/scoped-blueprint.spec.js
Tested locally with a scoped blueprint and it generated the expected files
Fix #9223
=> add support for scoped blueprint packages

generators/generator-base-private.js, generators/server/templates/build.gradle.ejs, generators/server/templates/pom.xml.ejs, generators/server/templates/src/test/java/package/repository/CustomAuditEventRepositoryIT.java.ejs
=> Add support for Java 12

generators/utils.js
=> Fix i18n templates path when using a blueprint

generators/client/templates/angular/src/main/webapp/app/core/auth/user-route-access-service.ts.ejs, generators/client/templates/angular/src/main/webapp/app/core/core.module.ts.ejs, generators/client/templates/angular/src/main/webapp/app/shared/shared.module.ts.ejs, generators/server/templates/src/main/java/package/client/OAuth2InterceptedFeignConfiguration.java.ejs, generators/server/templates/src/main/java/package/security/OAuth2AuthenticationSuccessHandler.java.ejs, generators/server/templates/src/main/java/package/web/rest/GatewayResource.java.ejs
=> some sonarqube cleanup

.travis.yml, azure-pipelines.yml, test-integration/scripts/22-tests-frontend.sh
=> CI: allow config with Yarn

generators/client/index.js, generators/client/prompts.js, generators/client/templates/angular/package.json.ejs, generators/client/templates/angular/src/main/webapp/app/layouts/navbar/navbar.component.html.ejs, generators/client/templates/angular/src/main/webapp/app/layouts/navbar/navbar.scss.ejs, generators/client/templates/angular/src/main/webapp/content/scss/_bootstrap-variables.scss.ejs, generators/client/templates/angular/src/main/webapp/content/scss/global.scss.ejs, generators/client/templates/angular/src/main/webapp/content/scss/vendor.scss.ejs, generators/client/templates/react/package.json.ejs, generators/client/templates/react/src/main/webapp/app/_bootstrap-variables.scss.ejs, generators/client/templates/react/src/main/webapp/app/app.scss.ejs, generators/client/templates/react/src/main/webapp/app/shared/layout/header/header.scss.ejs, generators/client/templates/react/src/main/webapp/app/shared/layout/header/header.tsx.ejs
=> Add bootswatch themes question

generators/generator-constants.js, generators/server/index.js, generators/server/templates/pom.xml.ejs
=> Remove maven "cc" profile

test-integration/scripts/25-sonar-analyze.sh
Related to https://github.com/jhipster/generator-jhipster/issues/9495
=> Try to fix Sonar analysis at Sonarcloud

generators/server/templates/build.gradle.ejs
Fixes regression after merge of #9516 
Fixes #9514 
=> Fix invalid gradle build file generated when using UAA

generators/common/templates/README.md.ejs, generators/docker-base.js, generators/docker-utils.js
=> [WIP] removing package command in ./mvnw package -Pprod verify jib:dockerBuild

generators/entity-server/templates/src/main/java/package/service/dto/EntityCriteria.java.ejs
See issue #9084
It requires https://github.com/jhipster/jhipster/pull/182 to be merged first to fully test generated code (otherwise will not compile)
=> Criteria copy method and constructor (to check)

generators/server/templates/gradle.properties.ejs, generators/server/templates/pom.xml.ejs
Depends on https://github.com/jhipster/jhipster/pull/232
=> Update spring-boot version to 2.1.4.RELEASE

generators/client/templates/angular/src/test/javascript/spec/app/admin/audits/audits.service.spec.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/app/admin/configuration/configuration.service.spec.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/app/admin/logs/logs.service.spec.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/app/admin/metrics/metrics.service.spec.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/app/core/user/user.service.spec.ts.ejs, generators/entity-client/templates/angular/src/test/javascript/spec/app/entities/entity-management.service.spec.ts.ejs
=> angular: fix async tests

Dockerfile
Following https://github.com/jhipster/generator-jhipster/pull/9518
It will fix our Docker image
Back to ubuntu:bionic, to be consistent with our DevBox
_____
=> Fix Docker image with SDKMAN

generators/client/templates/angular/package.json.ejs, generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management.component.html.ejs, generators/client/templates/angular/src/main/webapp/content/scss/global.scss.ejs, generators/client/templates/angular/src/test/javascript/jest.conf.js.ejs, generators/client/templates/angular/tslint.json.ejs, generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.html.ejs
I also removed a CSS class that made the entities buttons look too large when they had alot of space...
=> Bump angular dependencies

.travis.yml, azure-pipelines.yml, generators/server/templates/gradle.properties.ejs, generators/server/templates/pom.xml.ejs
=> Use next jhipster-bom development version (3.0.1-SNAPSHOT)

generators/common/templates/README.md.ejs
Related to https://github.com/jhipster/generator-jhipster/issues/9569
=> Update generated README, related to integration tests [ci skip]

generators/server/templates/build.gradle.ejs, generators/server/templates/gradle/wrapper/gradle-wrapper.properties, generators/server/templates/gradlew
Release Notes: https://docs.gradle.org/5.4/release-notes.html
=> Update to Gradle 5.4

generators/server/templates/build.gradle.ejs
=> Gradle - Remove workaround for long paths at Windows

generators/server/templates/build.gradle.ejs, generators/server/templates/pom.xml.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/9571
=> Put back snapshot repository for master branch

generators/common/templates/README.md.ejs
Related to https://github.com/jhipster/generator-jhipster/pull/9583#discussion_r277061529
=> [ci skip] use maven verify for launching tests + integration tests

generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs, generators/server/templates/build.gradle.ejs, generators/server/templates/pom.xml.ejs, generators/server/templates/src/test/java/package/AbstractCassandraTest.java.ejs, generators/server/templates/src/test/java/package/CassandraKeyspaceIT.java.ejs, generators/server/templates/src/test/java/package/config/WebConfigurerTest.java.ejs, generators/server/templates/src/test/java/package/config/timezone/HibernateTimeZoneIT.java.ejs, generators/server/templates/src/test/java/package/gateway/responserewriting/SwaggerBasePathRewritingFilterTest.java.ejs, generators/server/templates/src/test/java/package/repository/CustomAuditEventRepositoryIT.java.ejs, generators/server/templates/src/test/java/package/security/DomainUserDetailsServiceIT.java.ejs, generators/server/templates/src/test/java/package/security/SecurityUtilsUnitTest.java.ejs, generators/server/templates/src/test/java/package/security/jwt/JWTFilterTest.java.ejs, generators/server/templates/src/test/java/package/security/jwt/TokenProviderTest.java.ejs, generators/server/templates/src/test/java/package/security/oauth2/AudienceValidatorTest.java.ejs, generators/server/templates/src/test/java/package/security/oauth2/CookieCollectionTest.java.ejs, generators/server/templates/src/test/java/package/security/oauth2/CookieTokenExtractorTest.java.ejs, generators/server/templates/src/test/java/package/security/oauth2/OAuth2AuthenticationServiceTest.java.ejs, generators/server/templates/src/test/java/package/security/oauth2/OAuth2CookieHelperTest.java.ejs, generators/server/templates/src/test/java/package/service/MailServiceIT.java.ejs, generators/server/templates/src/test/java/package/service/UserServiceIT.java.ejs, generators/server/templates/src/test/java/package/service/mapper/UserMapperIT.java.ejs, generators/server/templates/src/test/java/package/web/rest/AccountResourceIT.java.ejs, generators/server/templates/src/test/java/package/web/rest/AuditResourceIT.java.ejs, generators/server/templates/src/test/java/package/web/rest/ClientForwardControllerIT.java.ejs, generators/server/templates/src/test/java/package/web/rest/LogoutResourceIT.java.ejs, generators/server/templates/src/test/java/package/web/rest/LogsResourceIT.java.ejs, generators/server/templates/src/test/java/package/web/rest/UserJWTControllerIT.java.ejs, generators/server/templates/src/test/java/package/web/rest/UserResourceIT.java.ejs, generators/server/templates/src/test/java/package/web/rest/errors/ExceptionTranslatorIT.java.ejs, generators/spring-controller/templates/src/test/java/package/web/rest/ResourceIT.java.ejs
=> Upgrade to JUnit 5

generators/client/templates/angular/src/test/javascript/jest.conf.js.ejs, generators/client/templates/react/src/test/javascript/jest.conf.js.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/9568
Thanks suggestion at https://github.com/facebook/jest/issues/7914#issuecomment-464352069
_____
=> Fix jest path for Windows

generators/server/templates/src/test/java/package/security/DomainUserDetailsServiceIT.java.ejs, generators/server/templates/src/test/java/package/security/oauth2/CookieCollectionTest.java.ejs, generators/server/templates/src/test/java/package/security/oauth2/OAuth2CookieHelperTest.java.ejs
This is more fluent and readable, and also more consistent with other existing tests.
=> Switch remaing JUnit assertions to AssertJ assertions

generators/client/templates/angular/src/main/webapp/app/core/login/login.service.ts.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/9588
_____
=> Fix UAA for noi18n gateway

generators/entity-client/templates/react/src/main/webapp/app/entities/react_validators.ejs
=> Fix Regex with escaped content is stripped #9559

generators/entity/index.js, test-integration/samples/.jhipster/MapsIdParentEntityWithoutDTO.json, test-integration/samples/.jhipster/MicroserviceOperation.json, test-integration/samples/.jhipster/Operation.json, test-integration/samples/.jhipster/Place.json, test-integration/samples/.jhipster/TestManyRelPaginDTO.json, test-integration/samples/.jhipster/TestManyToMany.json, test-integration/samples/.jhipster/TestManyToOne.json, test-integration/samples/.jhipster/TestTwoRelationshipsSameEntity.json
=> Remove relationship.otherEntityRelationshipNameUndefined

generators/heroku/templates/Procfile.ejs
This ensures that the sample data is not loaded into the Heroku database.
=> Add prod Maven profile to Heroku release phase for liquibase

generators/server/index.js, generators/server/prompts.js, generators/server/templates/pom.xml.ejs, generators/server/templates/src/main/resources/config/application-prod.yml.ejs
related [issue](https://github.com/jhipster/generator-jhipster/issues/9557)
=> removed enforcing cache provider to hazelcast and added a warning to user in prompt.

generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs, generators/server/templates/src/main/java/package/web/rest/UserJWTController.java.ejs, generators/server/templates/src/test/java/package/web/rest/UserJWTControllerIT.java.ejs
The AuthenticationManagerBuilder is already configured with the UserDetailsService and PasswordEncoder beans in AuthenticationConfiguration (InitializeUserDetailsBeanManagerConfigurer).
=> Simplify security configuration

generators/server/templates/gradle/profile_dev.gradle.ejs, generators/server/templates/gradle/profile_prod.gradle.ejs
As reported by @pascalgrimaud in https://github.com/jhipster/generator-jhipster/pull/9517#issuecomment-486072102.
Caused by https://github.com/jhipster/generator-jhipster/pull/9517/commits/6d0f7ba5dd876eec35c4434b09e53f8299c08cad
=> Gradle - Fix jvmArgs when using infinispan

generators/client/templates/react/src/main/webapp/app/shared/layout/header/header.scss.ejs
=> react: Update condition to correctly apply default header styles

generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/9561
_____
=> React: fix label for, to allow focus

generators/server/templates/src/main/java/package/config/DefaultProfileUtil.java.ejs
=> Remove unused getActiveProfiles method

generators/client/templates/react/src/test/javascript/spec/app/shared/reducers/authentication.spec.ts.ejs
=> react: oidc: fix logout reducer test

generators/server/templates/pom.xml.ejs
=> Update frontend-maven-plugin version to 1.7.6

generators/kubernetes/templates/db/postgresql.yml.ejs, generators/kubernetes/templates/deployment.yml.ejs
=> k8s: fix PostgreSQL username

generators/server/index.js, generators/server/prompts.js
Handling the no database option for monoliths is now trivial.
=> Add the no database option for monoliths

generators/client/templates/react/package.json.ejs, generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs, generators/server/templates/src/main/docker/config/realm-config/jhipster-realm.json.ejs
=> Update dependencies and use Keycloak 6 realm

generators/server/templates/src/main/java/package/web/rest/AccountResource.java.ejs, generators/server/templates/src/test/java/package/service/UserServiceIT.java.ejs, generators/server/templates/src/test/java/package/web/rest/AccountResourceIT.java.ejs
=> Improve OAuth2 user tests

generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
Since #9638 is merged and then I learned more that which is need a PR.
=> Fix bug when service/repository is used then elasticsearch repository save times is different

generators/server/prompts.js
=> Add cassandra option to prompts in reactive apps

generators/server/templates/build.gradle.ejs, generators/server/templates/pom.xml.ejs
align some conditions
alert if there is dependency covergences
=> Update maven-compiler-plugin version to 3.8.1 & fix condition for cumcumber tests

generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs
Remember-me must be removed when there's no database.
=> Fix session auth with no database

generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs
=> Fix wrong relationship value is being inserted in fake data

generators/server/templates/src/main/resources/swagger/api.yml.ejs
This adds security definitions to the OAS. They won't be used by openapi-generator's plugin but they can be handy when testing the generated endpoints with swagger-ui or swagger-editor in REPL mode.
=> Add security schemes to OAS

test-integration/scripts/11-generate-entities.sh
The section I removed is duplicated, it matches the code right below it.
=> remove duplicate entity copy section

generators/client/templates/angular/package.json.ejs, generators/client/templates/react/package.json.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/9658
_____
=> Fix postinstall for webdriver-manager with Windows

generators/server/templates/src/main/docker/Dockerfile.ejs, generators/server/templates/src/main/docker/entrypoint.sh.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/9677
_____
=> Dockerfile: use jar instead of war [ci skip]

generators/server/templates/src/main/java/package/security/SecurityUtils.java.ejs, generators/server/templates/src/test/java/package/security/SecurityUtilsUnitTest.java.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/9613
_____
=> OAuth2: fix getCurrentUserLogin

generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs
The fix done in #9655 should also be done for skipUserManagement apps with DB.
=> Fix session auth with skipUserManagement

generators/server/templates/src/main/docker/Dockerfile.ejs
=> change adduser command for openjdk11 docker image

generators/server/templates/src/main/java/package/config/UaaConfiguration.java.ejs
=> Fixed word 'acces' to 'access';

test-integration/scripts/20-docker-compose.sh
=> CI: start Keycloak before Registry

generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs, generators/server/files.js, generators/server/templates/src/main/resources/config/liquibase/master.xml.ejs
That way they're not duplicated in all added_entity changelogs
=> Liquibase: Define DBMS specific properties only at one place

generators/app/index.js
=> Blueprint feature is now stable enough, we can remove the BETA mention

generators/app/index.js, generators/app/prompts.js
This has never been implemented, and the login and logout subgens have been removed (see PR #9368)
=> Remove mentions of account linking with JHipster online

generators/client/templates/angular/src/main/webapp/app/shared/login/login.component.html.ejs, generators/client/templates/react/src/main/webapp/app/modules/login/login-modal.tsx.ejs, generators/client/templates/react/src/main/webapp/app/shared/layout/menus/account.tsx.ejs
=> Remove dead links in login modal for skipUserManagement

generators/client/templates/angular/src/test/javascript/e2e/admin/administration.spec.ts.ejs
=> Fix e2e test for skipUserManagement apps

generators/client/templates/react/src/test/javascript/e2e/modules/account/account.spec.ts.ejs
=> Fix react e2e tests for skipUserManagement

generators/generator-constants.js
=> Use adoptopenjdk/openjdk11:alpine-jre as base docker image

generators/server/templates/src/main/resources/config/application-dev.yml.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/9407
_____
=> Elasticsearch: remove health check in dev

generators/client/templates/angular/src/main/webapp/app/layouts/navbar/navbar.component.html.ejs, generators/client/templates/angular/src/main/webapp/app/vendor.ts.ejs, generators/client/templates/react/src/main/webapp/app/config/icon-loader.ts.ejs, generators/client/templates/react/src/main/webapp/app/shared/layout/menus/account.tsx.ejs, test-integration/samples/ngx-default/.yo-rc.json, test-integration/samples/react-default/.yo-rc.json
=> Fixed password menu icon from 'clock' to 'lock' and completed 'uz-cyr' language support

generators/client/files-react.js, generators/client/templates/react/src/main/webapp/app/modules/administration/administration.reducer.ts.ejs, generators/client/templates/react/src/main/webapp/app/shared/layout/menus/admin.tsx.ejs, generators/client/templates/react/src/test/javascript/spec/app/modules/administration/administration.reducer.spec.ts.ejs
=> Remove unused audit code

generators/common/templates/README.md.ejs, generators/generator-constants.js, generators/server/files.js, generators/server/index.js, generators/server/templates/build.gradle.ejs, generators/server/templates/gradle/war.gradle.ejs, generators/server/templates/pom.xml.ejs
=> Upgrade jib to 1.2.0

generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs
In the template entity-update
Fix #9694 
=> fix react display of translated properties in option

generators/server/templates/build.gradle.ejs
=> update gradle sonar plugin to 2.7.1

generators/server/templates/build.gradle.ejs
=> add classpath jar creation for windows os

generators/client/index.js, generators/client/prompts.js, generators/generator-base.js, generators/server/index.js
=> Add a no client option

generators/server/templates/gradle/sonar.gradle.ejs, generators/server/templates/pom.xml.ejs
=> Upgrade jacoco plugin to version 0.8.4 

generators/server/templates/gradle.properties.ejs, generators/server/templates/pom.xml.ejs
Depends on https://github.com/jhipster/jhipster/pull/261
=> Upgrade spring-boot version to 2.1.5.RELEASE

generators/server/files.js, generators/server/prompts.js, generators/server/templates/src/main/java/package/config/CacheConfiguration.java.ejs, generators/server/templates/src/main/java/package/service/UserService.java.ejs, generators/server/templates/src/main/java/package/service/dto/UserDTO.java.ejs, generators/server/templates/src/test/java/package/service/UserServiceIT.java.ejs, generators/server/templates/src/test/java/package/web/rest/AccountResourceIT.java.ejs
=> Add no database option for Oauth2/OIDC apps

generators/server/templates/src/main/java/package/config/WebConfigurer.java.ejs
This shows an unused variable warning otherwise.
=> disps variable is not used if !skipClient

generators/server/templates/src/main/java/package/config/LoggingConfiguration.java.ejs
=> Use logging utils methods

cli/utils.js, generators/app/index.js, generators/aws/index.js, generators/entity/index.js, generators/generator-base.js, generators/languages/index.js, generators/server/index.js, package-lock.json
Fix https://github.com/jhipster/generator-jhipster/issues/9739
=> Handle errors

generators/entity-server/files.js, generators/entity-server/templates/src/main/resources/config/liquibase/data/table.csv.ejs
=> Partially fix validation rules for Faker

generators/server/templates/src/main/resources/swagger/api.yml.ejs
=> Add dev server urls to API-first's OAS

generators/ci-cd/templates/.gitlab-ci.yml.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/9761
_____
=> GitLab CI/CD: add artifact classes needed by jib [ci skip]

generators/generator-constants.js
Related to 
- https://github.com/jhipster/jhipster-registry/issues/353
- https://github.com/jhipster/jhipster-registry/issues/356
_____
=> Upgrade to jhipster-registry v5.0.1

generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs
=> Add possibility to also authenticate by Basic auth on JWT monoliths

generators/languages/templates/src/main/resources/i18n/messages_es.properties.ejs
There were a couple of errors and translations that are better this way
=> improving the Spanish version

generators/entity-server/templates/src/main/resources/config/liquibase/data/table.csv.ejs
=> fix blob fake data generation

generators/languages/templates/src/main/webapp/i18n/es/global.json.ejs
There is one translation that I feel fits better: I changed `artículos` to `elementos`. Those who have a deep knowledge in Spanish (I'm native btw) please let me know.
=> Improving and adding missing translations

generators/server/templates/gradle/sonar.gradle.ejs, generators/server/templates/gradle/war.gradle.ejs
=> Gradle - Fix deprecation warnings

generators/common/templates/editorconfig.ejs
=> add correct indent for yml files

generators/entity-server/templates/src/main/java/package/service/mapper/EntityMapper.java.ejs
=> ignore collection helper method in DTO mapper

generators/server/templates/src/main/docker/config/README.md.ejs, generators/server/templates/src/main/docker/jhipster-registry.yml.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/9786
_____
=> Registry: update link about git configuration [ci skip]

generators/client/templates/angular/package.json.ejs, generators/client/templates/react/package.json.ejs
=> Fix Lux theme compilation issues

generators/kubernetes/templates/monitoring/jhipster-prometheus-crd.yml.ejs
=> Fix prometheus operator error status

generators/kubernetes/templates/monitoring/jhipster-prometheus-crd.yml.ejs
=> Fix error on up Prometheus with K8S.

test-integration/scripts/00-init-env.sh
Related to https://github.com/jhipster/generator-jhipster/pull/9789#issuecomment-495738745
@pvliss : it should be fixed now. Thanks for finding this!
_____
=> CI: fix OpenJDK 11 with Azure

generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/auth-expired.interceptor.ts.ejs, generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/errorhandler.interceptor.ts.ejs, generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.html.ejs, generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.ts.ejs, generators/generator-base-private.js, package-lock.json
Fix some angular relation validation misgeneration
=> Angular relation required validation

generators/client/templates/angular/src/main/webapp/app/shared/shared.module.ts.ejs
=> remove unused and confusing import

generators/client/templates/react/src/main/webapp/app/config/axios-interceptor.ts.ejs
=> client: react: fix nil pointer error on react client

generators/server/templates/build.gradle.ejs
This is to fix issue: https://github.com/jhipster/generator-jhipster/issues/9787
=> Update hazelcast gradle logic to match maven

.travis.yml, Dockerfile, azure-pipelines.yml, generators/generator-constants.js
See https://github.com/nodejs/node/releases/tag/v10.16.0
=> Update Node to 10.16.0

generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs, generators/server/templates/src/main/java/package/service/UserService.java.ejs, generators/server/templates/src/test/java/package/service/UserServiceIT.java.ejs
=> Fix users deleted if they have already been activated

generators/ci-cd/templates/.gitlab-ci.yml.ejs
Related to https://github.com/jhipster/generator-jhipster/issues/9426
_____
=> CICD: add run for React, as it's used with test-ci [skip ci]

package-lock.json, package.json
See https://github.com/axios/axios/pull/1485, which has been shipped with v0.19.0
=> Updated the axios dep version to fix CVE warning

generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
Fixes compilation problem of this issues #9820
=> Mongo compile error with required relationships

generators/entity-server/templates/src/main/java/package/common/save_template.ejs
Fixes compilation problem, also related to this issue:
https://github.com/jhipster/generator-jhipster/issues/9820
=> fixes compilation problem for mondogodb/casandra (pkType)

generators/client/templates/react/package.json.ejs, generators/client/templates/react/src/main/webapp/app/modules/administration/administration.reducer.ts.ejs, generators/client/templates/react/src/main/webapp/app/modules/administration/audits/audits.tsx.ejs, generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management.reducer.ts.ejs, generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management.tsx.ejs, generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.html.ejs, generators/entity-client/templates/react/src/main/webapp/app/entities/entity.reducer.ts.ejs, generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs
Needs jhipster/react-jhipster#31 to be merged and release to pass ci
Fix #9808 
=> Fix pagination

generators/client/needle-api/needle-client-angular.js
=> fix duplicated routes when reimporting jdl

generators/server/templates/src/main/java/package/web/rest/errors/ExceptionTranslator.java.ejs, generators/server/templates/src/test/java/package/web/rest/errors/ExceptionTranslatorTestController.java.ejs
Depends on https://github.com/jhipster/jhipster/pull/285
=> Update problem-spring version to 0.24.0

generators/client/templates/angular/package.json.ejs
Following this PR: #9825
_____
=> Upgrade ng-jhipster to 0.10.1

azure-pipelines.yml
Related to https://github.com/jhipster/generator-jhipster/pull/9825/files#r289740320
_____
=> Set NG_CLI_ANALYTICS to false

generators/server/templates/build.gradle.ejs, generators/server/templates/pom.xml.ejs, generators/server/templates/src/test/java/package/config/DatabaseConfigurationIT.java.ejs
See https://github.com/jhipster/jhipster/pull/287
=> Use mainstream Couchbase testcontainer

README.md
=> Daily builds: add missing badges [skip ci]

cli/utils.js
Avoid side effects cased as part of #9783 
=> Minor refactor for command suggestion logic

generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management.reducer.ts.ejs, generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management.tsx.ejs, generators/entity-client/templates/react/src/main/webapp/app/entities/entity.reducer.ts.ejs, generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs
=> Remove pagination with cassandra in react

generators/client/templates/react/src/test/javascript/spec/app/modules/administration/user-management/user-management.reducer.spec.ts.ejs
Linked to #9863. I forgot to update this frontend test
=> fix user-management tests with react and cassandra

generators/client/templates/angular/package.json.ejs
=> Bump ngx-webstorage to fix peer warnings during install

generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs, generators/server/templates/src/main/docker/config/realm-config/jhipster-realm.json.ejs, generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs
=> Map authorities from access token claim

generators/client/templates/react/package.json.ejs
Fixes https://nvd.nist.gov/vuln/detail/CVE-2019-10742.
=> Upgrade Axios to fix vulnerability

.vscode/launch.json, cli/import-jdl.js, test/cli/import-jdl.spec.js
=> Reimporting jdl

generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs, generators/entity-server/templates/src/main/java/package/service/dto/EntityCriteria.java.ejs, generators/entity-server/templates/src/main/java/package/service/dto/EntityDTO.java.ejs, generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs, generators/entity-server/templates/src/main/resources/config/liquibase/data/table.csv.ejs, generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs, generators/entity/index.js, generators/entity/prompts.js, generators/server/templates/src/main/java/package/config/DatabaseConfiguration.java.ejs, generators/server/templates/src/main/resources/config/liquibase/master.xml.ejs, package-lock.json, package.json, test-integration/samples/.jhipster/BankAccount.json, test-integration/samples/.jhipster/FieldTestEntity.json, test-integration/samples/.jhipster/FieldTestInfiniteScrollEntity.json, test-integration/samples/.jhipster/FieldTestMapstructEntity.json, test-integration/samples/.jhipster/FieldTestPagerEntity.json, test-integration/samples/.jhipster/FieldTestPaginationEntity.json, test-integration/samples/.jhipster/FieldTestServiceClassEntity.json, test-integration/samples/.jhipster/FieldTestServiceImplEntity.json, test/templates/export-jdl/.jhipster/Employee.json, test/templates/import-jdl/jdl.jdl
Requires https://github.com/jhipster/jhipster-core/pull/331
=> UUID field type for sql databases

generators/ci-cd/templates/.gitlab-ci.yml.ejs, generators/ci-cd/templates/azure-pipelines.yml.ejs, generators/ci-cd/templates/travis.yml.ejs
=> CICD: set NG_CLI_ANALYTICS to false

generators/entity/index.js, generators/generator-base.js
=> Handling of table and column names when jhiPrefix is empty

generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs, generators/entity-server/templates/src/main/java/package/domain/imports.ejs
=> remove unused imports for entities

generators/generator-constants.js, generators/server/templates/build.gradle.ejs, generators/server/templates/gradle.properties.ejs, generators/server/templates/pom.xml.ejs
=> Upgrade jhipster registry and lib

generators/server/templates/src/main/java/package/security/oauth2/AuthorizationHeaderUtil.java.ejs, generators/server/templates/src/main/java/package/service/UserService.java.ejs, generators/server/templates/src/main/java/package/web/rest/AccountResource.java.ejs
Fixes https://github.com/jhipster/generator-jhipster/issues/9903.
=> Add support for AuthToken with OAuth 2.0 Resource Server

generators/client/templates/angular/angular.json.ejs, generators/client/templates/angular/package.json.ejs
=> Bump angular dependencies and sync angular cli json

generators/generator-base.js, generators/server/needle-api/needle-server-maven.js, generators/server/templates/pom.xml.ejs, test/needle-api/needle-server-maven.spec.js
=> Add new needle API to add a new annotation processor for Maven

test/needle-api/needle-client-angular.spec.js, test/needle-api/needle-client-i18n.spec.js, test/needle-api/needle-client-react.spec.js, test/needle-api/needle-client-webpack.spec.js, test/needle-api/needle-client.spec.js, test/needle-api/needle-server-cache.spec.js, test/needle-api/needle-server-gradle.spec.js, test/needle-api/needle-server-liquibase.spec.js, test/needle-api/needle-server-maven.spec.js
- Don't run each test twice with blueprint 'generator-jhipster-myblueprint' and 'myblueprint'
- Cleaned contexts (rename, regroup, delete empty ones, ...)
=> Clean needle-api unit tests

generators/server/templates/src/main/resources/config/liquibase/master.xml.ejs
This fixes issue https://github.com/jhipster/generator-jhipster/issues/9917
=> Update uuidType to include mysql when mariadb. Azure reports mariadb as mysql

generators/client/templates/angular/angular.json.ejs
=> Fix for Angular CLI usage

generators/entity-server/templates/src/main/java/package/service/EntityQueryService.java.ejs, generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs, generators/server/templates/build.gradle.ejs, generators/server/templates/gradle.properties.ejs, generators/server/templates/pom.xml.ejs, generators/server/templates/src/main/java/package/config/DefaultProfileUtil.java.ejs, generators/server/templates/src/main/java/package/domain/PersistentAuditEvent.java.ejs, generators/server/templates/src/main/java/package/web/rest/AuditResource.java.ejs, generators/server/templates/src/main/java/package/web/rest/UserResource.java.ejs
Depends on https://github.com/jhipster/jhipster/pull/293
=> Update spring-boot to 2.1.6 and dependencies

generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
To be cleaner for the JHipster conf
#ConferenceDrivenDevelopment 
=> Change a wrong comment

generators/server/templates/src/main/java/package/service/UserService.java.ejs, generators/server/templates/src/test/java/package/service/UserServiceIT.java.ejs, package-lock.json
=> Adjust UserService to handle JWT Auth with Okta

package.json
=> Set inquirer npm dependency resolution to 6.3.1 fix #9952

generators/entity-server/files.js, generators/entity/index.js
=> fix #9973: add variable to know when to generate fake data text file

generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
and increase the code coverage to check more field types and more filters - following #9836 
=> Fix to use greaterThanOrEquals in the tests

generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs, generators/server/templates/src/main/java/package/security/DomainUserDetailsService.java.ejs, generators/server/templates/src/test/java/package/security/DomainUserDetailsServiceIT.java.ejs
=> user by email with authorities is now case insensitive

generators/client/templates/angular/src/main/webapp/app/shared/login/login.component.html.ejs, generators/client/templates/angular/src/main/webapp/app/shared/login/login.component.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/app/shared/login/login.component.spec.ts.ejs
Created new pull request with test case update
=> change default remember me option to "false" in login modal

cli/cli.js
This reverts commit c77d5cfe78b6d09763ef2283297b0e3b378ed188.
Fix https://github.com/jhipster/generator-jhipster/issues/10006
=> Revert "improve performance"

generators/server/templates/pom.xml.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/9944
_____
=> Fix packaging with just git init

generators/server/templates/src/main/resources/config/application-dev.yml.ejs, generators/server/templates/src/main/resources/config/application-prod.yml.ejs, package-lock.json
Those are slight improvement I made on my side to simplify the configuration.
-   [ x] Tests are added where necessary
-   [ x] Documentation is added/updated where necessary
-   [ x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed
=> No need to specify the mail from for dev and prod

generators/server/templates/src/test/java/package/web/rest/KafkaResourceIT.java.ejs
=> Fix Kafka tests when using OAuth2

generators/ci-cd/templates/.gitlab-ci.yml.ejs
=> CICD: polish GitLab CI

generators/server/templates/gradle.properties.ejs, generators/server/templates/pom.xml.ejs
This will use Spring-cloud Greenwich.SR2 and new dependencies from Jhipster BOM lib
=> Use snapshot JHipster lib version 3.0.4-SNAPSHOT

generators/app/index.js
We might want to update the checkBlueprint method instead to check for the version also ?
=> fix use of blueprint without skip-checks flag

generators/client/templates/angular/src/main/webapp/app/shared/auth/has-any-authority.directive.ts.ejs
=> correct the jsdoc of generated has-any-authority.directive.ts

generators/client/templates/angular/src/main/webapp/app/admin/gateway/gateway.component.html.ejs
=> fix button align gateway component

CONTRIBUTING.md, rfcs/0-jhipster-rfc-template.md
I explained my ideas about the RFC process on the mailing list: https://groups.google.com/forum/#!topic/jhipster-dev/AlCQvPzOEaw
=> Create and document the RFC process and add an RFC template

generators/entity-server/templates/src/main/java/package/common/get_all_template.ejs, generators/entity-server/templates/src/main/java/package/common/search_template.ejs, generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs, generators/server/templates/src/main/java/package/web/rest/AuditResource.java.ejs, generators/server/templates/src/main/java/package/web/rest/UserResource.java.ejs
Instead of binding UriComponentsBuilder, we get the URI builder from `ServletUriComponentsBuilder.fromCurrentRequest()` for servlet apps and `UriComponentsBuilder.fromHttpRequest(request)` for reactive ones
Fix #9690
Fix #10008
=> Fix pagination link generation

generators/server/templates/src/main/docker/app.yml.ejs, generators/server/templates/src/main/docker/consul.yml.ejs
=> make app.yml coherent with extends consul

generators/generator-base-private.js, package-lock.json, package.json
This removes the need to install `yo` globally to use blueprints
=> Use the yo cli script from generator-jhipster node modules 

generators/aws/index.js, generators/aws/lib/eb.js, generators/aws/lib/s3.js, generators/aws/prompts.js, generators/cloudfoundry/index.js, generators/generator-base.js, generators/heroku/index.js
A War is built instead of a Jar so it can used with Tomcat.
Fix #9685
=> Fix aws beanstalk generator

generators/server/templates/pom.xml.ejs
=> Update maven plugin versions

generators/server/templates/build.gradle.ejs
=> Update com.github.node-gradle.node version to 1.5.1

generators/client/templates/react/src/main/webapp/app/shared/layout/header/header.tsx.ejs
Do you think that it will be good to use **Hooks** in React components ?
Here I began to use **useState** and **useEffect** in the file: header.tsx
=> [React] Start to use Hooks (here in the header)

generators/client/templates/react/src/main/webapp/app/modules/administration/configuration/configuration.tsx.ejs
WIP on #9891 
One component : Configuration
=> [React] Hooks (configuration component)

generators/client/templates/react/src/main/webapp/app/modules/administration/health/health.tsx.ejs, generators/client/templates/react/src/main/webapp/app/modules/administration/logs/logs.tsx.ejs
=> [React] Hooks (health and logs components)

generators/client/templates/react/src/main/webapp/app/modules/account/activate/activate.tsx.ejs
=> [React] Hooks (activate component)

generators/client/templates/react/src/main/webapp/app/modules/account/settings/settings.tsx.ejs
=> [React] Hooks (settings component)

generators/client/templates/react/src/main/webapp/app/modules/administration/metrics/metrics.tsx.ejs
=> [React] Hooks (metrics component)

generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management-detail.tsx.ejs
=> [React] Hooks (user-management-detail component)

generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management-delete-dialog.tsx.ejs, generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management-update.tsx.ejs
WIP on #9891
Components : user-management-delete-dialog and user-management-update
=> [React] Hooks (user-management-delete-dialog and user-management-update components)

generators/client/templates/react/src/main/webapp/app/modules/login/login.tsx.ejs
=> [React] Hooks (login component)

generators/client/templates/react/src/main/webapp/app/app.tsx.ejs
=> [React] Hooks (app component)

generators/client/templates/react/src/main/webapp/app/modules/account/password/password.tsx.ejs, generators/client/templates/react/src/main/webapp/app/modules/account/register/register.tsx.ejs
WIP on #9891 
Two components : password and register
=> [React] Hooks (password and register components)

generators/client/templates/react/src/main/webapp/app/modules/administration/audits/audits.tsx.ejs
=> [React] Hooks (audits component)

generators/client/templates/react/src/main/webapp/app/modules/home/home.tsx.ejs
=> [React] Hooks (home component)

generators/client/templates/react/src/main/webapp/app/modules/account/password-reset/finish/password-reset-finish.tsx.ejs
WIP on #9891
One component : PasswordResetFinish
=> [React] Hooks (password-reset-finish component)

generators/cloudfoundry/index.js, generators/entity/index.js, generators/gae/index.js, generators/generator-base.js, generators/heroku/index.js, generators/server/index.js
Fix #9933
-   [] Documentation is added/updated where necessary
-   [] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed
=> Disable Hibernate cache when cacheProvider is disabled or set to memcached

generators/entity-server/templates/src/test/gatling/user-files/simulations/EntityGatlingTest.scala.ejs
=> Fix Gatling tests for OAuth2 Microservices

generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics.component.html.ejs
=> Remove an unclosed div that was lost on the metrics page

generators/server/templates/src/main/docker/app.yml.ejs, generators/server/templates/src/main/docker/kafka.yml.ejs
Fix #10048 (the Spring Boot app was resolving to `localhost` instead of `kafka`)
=> Change hostname to "kafka"

generators/generator-constants.js
See https://github.com/yarnpkg/yarn/releases/tag/v1.17.3
=> Update yarn version to 1.17.3

generators/client/templates/react/package.json.ejs, package-lock.json, package.json
See https://snyk.io/vuln/SNYK-JS-LODASH-73638
=> Updated lodash version to latest to fix security issue

generators/generator-constants.js
See:
https://github.com/GoogleContainerTools/jib/releases/tag/v1.4.0-maven
https://github.com/GoogleContainerTools/jib/releases/tag/v1.4.0-gradle
=> Update JIB version to 1.4.0

generators/server/prompts.js, test-integration/samples/webflux-mongodb/.yo-rc.json
=> Remove cache option for reactive apps

generators/generator-base-docker.js, generators/kubernetes/templates/db/mssql.yml.ejs
Added the MSSQL manifest template for K8s.
=> added the mssql template in kubernetes/templates/db/mssql.yml.ejs #10089 

generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
=> Fix java integration test #10095

generators/server/templates/src/main/java/package/web/rest/vm/ManagedUserVM.java.ejs
=> correct the toString() of generated ManagedUserVM.java

generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.route.ts.ejs
=> simplify the assignment

generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
=> fix javadoc error

generators/client/templates/angular/src/main/webapp/app/admin/admin.module.ts.ejs, generators/client/templates/angular/src/main/webapp/app/core/language/language.helper.ts.ejs, generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.module.ts.ejs
=> simplify the if condition

.travis.yml, azure-pipelines.yml, generators/server/templates/build.gradle.ejs, generators/server/templates/gradle.properties.ejs, generators/server/templates/pom.xml.ejs
Just to check if the JHipster 3.0.3 is compatible with current master branch
_____
=> JHipster lib 3.0.3

generators/common/templates/gitignore.ejs
=> git ignore sts cache [skip ci]

generators/server/templates/src/main/docker/monitoring.yml.ejs, test-integration/scripts/20-docker-compose.sh
=> Align compose file version for monitoring.yml

generators/generator-base.js, generators/server/index.js, generators/server/templates/src/main/docker/app.yml.ejs, generators/server/templates/src/main/docker/cassandra-cluster.yml.ejs, generators/server/templates/src/main/docker/cassandra-migration.yml.ejs, generators/server/templates/src/main/docker/cassandra.yml.ejs, generators/server/templates/src/main/docker/consul.yml.ejs, generators/server/templates/src/main/docker/couchbase-cluster.yml.ejs, generators/server/templates/src/main/docker/couchbase.yml.ejs, generators/server/templates/src/main/docker/elasticsearch.yml.ejs, generators/server/templates/src/main/docker/hazelcast-management-center.yml.ejs, generators/server/templates/src/main/docker/jhipster-registry.yml.ejs, generators/server/templates/src/main/docker/kafka.yml.ejs, generators/server/templates/src/main/docker/keycloak.yml.ejs, generators/server/templates/src/main/docker/mariadb.yml.ejs, generators/server/templates/src/main/docker/memcached.yml.ejs, generators/server/templates/src/main/docker/mongodb-cluster.yml.ejs, generators/server/templates/src/main/docker/mongodb.yml.ejs, generators/server/templates/src/main/docker/monitoring.yml.ejs, generators/server/templates/src/main/docker/mssql.yml.ejs, generators/server/templates/src/main/docker/mysql.yml.ejs, generators/server/templates/src/main/docker/postgresql.yml.ejs, generators/server/templates/src/main/docker/sonar.yml.ejs, generators/server/templates/src/main/docker/swagger-editor.yml.ejs
=> Replace hard-code compose version number with variable

generators/entity-server/templates/src/main/java/package/service/EntityQueryService.java.ejs
=> Declare createSpecification method as protected instead of private in EntityQueryService

generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.html.ejs, generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs
=> make html 'create a new Entity' coherent with english json file

generators/server/templates/src/main/java/package/config/WebConfigurer.java.ejs
This fixes the CORS issue in https://github.com/jhipster/generator-jhipster/issues/9903 which is a result of https://github.com/jhipster/generator-jhipster/pull/9262
=> Added CORs support for microservices prefixed with /services/

generators/client/templates/react/package.json.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/10157
_____
=> Try to fix e2e for React

generators/common/templates/README.md.ejs, generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs
=> Add CSP rule to allow Workbox URL for PWAs

.travis.yml, Dockerfile, azure-pipelines.yml, generators/generator-constants.js
See https://github.com/nodejs/node/releases/tag/v10.16.1
=> Update Node version to 10.16.1

generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.html.ejs
This change will allow to set a link to another module.
Already been used in entity-management-detail.component.html.ejs
https://github.com/jhipster/generator-jhipster/blob/405ebaf2d04a4f07285ba35bf621404a1efd34c4/generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-detail.component.html.ejs#L82
https://github.com/jhipster/generator-jhipster/blob/405ebaf2d04a4f07285ba35bf621404a1efd34c4/generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-detail.component.html.ejs#L87
https://github.com/jhipster/generator-jhipster/blob/405ebaf2d04a4f07285ba35bf621404a1efd34c4/generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-detail.component.html.ejs#L91
Part of …
=> Use absolute routerLink instead of relative.

generators/server/templates/gradle.properties.ejs, generators/server/templates/pom.xml.ejs
=> Use jhipster lib 3.0.4

generators/server/templates/src/main/resources/logback-spring.xml.ejs
=> Reduce logs from PostgreSQL

README.md
Related to https://github.com/jhipster/jhipster.github.io/pull/767
_____
=> Add new bronze sponsors: UX Planet and PapersOwl [ci skip] [skip-ci]

generators/entity-client/files.js, generators/entity-client/templates/angular/src/main/webapp/app/entities/entity.model.ts.ejs, generators/entity-client/templates/angular/src/main/webapp/app/entities/enumerations/enum.model.ts.ejs, generators/entity-client/templates/angular/src/test/javascript/spec/app/entities/entity-management.service.spec.ts.ejs, generators/entity-client/templates/react/src/main/webapp/app/entities/entity.model.ts.ejs, generators/entity-client/templates/react/src/main/webapp/app/entities/enumerations/enum.model.ts.ejs, generators/generator-base-private.js
=> feature(enums): make frontend enums global

generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management.component.ts.ejs, generators/client/templates/angular/src/main/webapp/app/home/home.component.ts.ejs
In user-management and home component, events handled by eventManager are not unsubscribed. It causes anormal behavior as requesting multiple times the API for a resource for example.
Fix #10153 
=> [Angular] Add eventManager event unsubscriptions

generators/server/templates/pom.xml.ejs
=> Update pom.xml.ejs to fix issue #10180

generators/server/files.js, generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs
Original author: @Hawkurane
Fix #9877 - similar to https://github.com/jhipster/generator-jhipster/pull/9896 but without conflicts
_____
=> removed zuul proxy dependent files for gateways without service discovery

generators/server/templates/pom.xml.ejs
This enables spring-boot-annotations-processor during compilation.
=> to fix issue #10194

generators/server/templates/build.gradle.ejs, generators/server/templates/gradle.properties.ejs, generators/server/templates/pom.xml.ejs
Depends on https://github.com/jhipster/jhipster/pull/367
=> Update Spring-boot to 2.1.7.RELEASE and other dependencies

generators/server/templates/src/main/java/package/web/rest/errors/ExceptionTranslator.java.ejs, generators/server/templates/src/test/java/package/web/rest/errors/ExceptionTranslatorIT.java.ejs, generators/server/templates/src/test/java/package/web/rest/errors/ExceptionTranslatorTestController.java.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/10049
=> Remove trailing DTO from object name in validation messages

generators/generator-base-private.js
=> Fix Yeoman execution in Windows

package-lock.json, package.json
=> Updated the JCore dep to v4.3.0

generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs
This pull requests handles csp problem related to image uploads. 
Closes #10227
=> Add csp header to allow data urls for image uploads

generators/server/templates/src/test/java/package/web/rest/KafkaResourceIT.java.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/10218
_____
=> Fix UAA+Kafka integration tests

generators/server/templates/src/main/java/package/config/WebConfigurer.java.ejs, generators/server/templates/src/test/java/package/config/WebConfigurerTest.java.ejs
=> Remove mimemappings for skip-client app's WebConfigurer

generators/ci-cd/templates/travis.yml.ejs
Change the way jdk is loaded. Removed default jdk loading using bionic distribution and added using scripts.
#10175 and #10216 (comment)
=> Java11 CI modification

.travis.yml, Dockerfile, azure-pipelines.yml, generators/generator-constants.js
See https://github.com/nodejs/node/releases/tag/v10.16.3
=> Update Node version to 10.16.3 and Npm to 6.10.3

generators/generator-constants.js
See:
https://github.com/GoogleContainerTools/jib/releases/tag/v1.5.0-maven
https://github.com/GoogleContainerTools/jib/releases/tag/v1.5.0-gradle
=> Update JIB version to 1.5.0

generators/generator-constants.js
See https://github.com/npm/cli/releases/tag/v6.11.0
=> Update npm version to 6.11.0

generators/generator-constants.js
See https://github.com/npm/cli/releases/tag/v6.11.1
=> Update npm version to 6.11.1

generators/generator-constants.js
See https://github.com/npm/cli/releases/tag/v6.11.2
=> Update npm version to 6.11.2

generators/server/files.js
Remove duplicate code block.
Fix #10273
=> Remove duplicate code block

generators/client/templates/angular/src/main/webapp/app/admin/health/health.component.html.ejs, generators/client/templates/angular/src/main/webapp/app/admin/logs/logs.component.html.ejs, generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management.component.html.ejs, generators/client/templates/react/src/main/webapp/app/modules/administration/health/health.tsx.ejs, generators/client/templates/react/src/main/webapp/app/modules/administration/logs/logs.tsx.ejs, generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management.tsx.ejs, generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.html.ejs, generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs
Use `aria-describedby` attribute for tables using the page heading.
updates #10258
=> add describedBy to tables

generators/ci-cd/templates/.gitlab-ci.yml.ejs, generators/ci-cd/templates/travis.yml.ejs
Remove SonaQube analysis on PRs
Fixes #10269
=> Remove SonarQube analysis on PRs 

generators/client/templates/angular/package.json.ejs, generators/client/templates/angular/webpack/webpack.dev.js.ejs
- We don't need this anymore as angular now supports dynamic imports.
---
=> Remove angular-router-loader dev dependency

generators/common/templates/README.md.ejs, generators/common/templates/sonar-project.properties.ejs, generators/server/templates/pom.xml.ejs
=> Use xml format for Jacoco reports in Sonarqube 

generators/client/templates/angular/src/test/javascript/jest.conf.js.ejs, generators/client/templates/react/src/test/javascript/jest.conf.js.ejs
=> Use build directory to contain jest cache

generators/server/templates/build.gradle.ejs, generators/server/templates/gradle/wrapper/gradle-wrapper.properties, generators/server/templates/gradlew
=> update gradle to 5.6.1

generators/server/templates/src/main/resources/config/application-dev.yml.ejs, generators/server/templates/src/main/resources/config/application-prod.yml.ejs
=> Fix infinispan time-to-live-seconds default values and descriptions

generators/client/templates/angular/package.json.ejs
=> Bump angular dependency versions

generators/server/templates/src/test/java/package/service/UserServiceIT.java.ejs
=> rename USLocal tests in UserServiceIT

generators/ci-cd/templates/travis.yml.ejs
=> Correct SonarQube Analysis

generators/entity-server/templates/src/main/resources/config/liquibase/fake-data/table.csv.ejs
=> fix issues with faker patterns that breaks csv

generators/generator-constants.js
See https://github.com/npm/cli/releases/tag/v6.11.3
=> Update NPM version to 6.11.3

generators/client/templates/angular/.eslintignore.ejs, generators/client/templates/angular/.eslintrc.json.ejs, generators/client/templates/angular/.huskyrc.ejs, generators/client/templates/angular/.lintstagedrc.js.ejs, generators/client/templates/angular/tsconfig.e2e.json.ejs, generators/client/templates/react/.eslintignore.ejs, generators/client/templates/react/.eslintrc.json.ejs, generators/client/templates/react/.huskyrc.ejs, generators/client/templates/react/.lintstagedrc.js.ejs, generators/client/templates/react/tsconfig.e2e.json.ejs
=> Add license headers

generators/kubernetes/templates/deployment.yml.ejs, generators/kubernetes/templates/ingress.yml.ejs, generators/kubernetes/templates/istio/gateway.yml.ejs
For #10343 - issue based on https://medium.com/@simionrazvan/microservices-using-jhipster-kubernetes-istio-bf75e992612a
=> Update /services prefix for the Kubernetes generator

generators/client/templates/angular/src/main/webapp/app/account/account.route.ts.ejs, generators/client/templates/angular/src/main/webapp/app/app-routing.module.ts.ejs, generators/client/templates/angular/src/main/webapp/app/app.module.ts.ejs
=> Lazy load account module

generators/client/templates/angular/.eslintrc.json.ejs, generators/client/templates/angular/package.json.ejs
=> Use jhipster eslint shareable configurations

generators/client/templates/react/.eslintrc.json.ejs, generators/client/templates/react/package.json.ejs
=> react: use jhipster eslint shareable configurations

generators/client/templates/angular/src/main/webapp/app/app.module.ts.ejs, generators/client/templates/angular/src/main/webapp/app/core/core.module.ts.ejs, generators/client/templates/angular/src/main/webapp/app/shared/shared-libs.module.ts.ejs, test-integration/scripts/23-package.sh
This is the simplified version of the #10340
Closes #10340 for now
=> Improve shared libs, main and core modules, simplified

generators/server/templates/src/main/java/package/service/UserService.java.ejs
=> Fix Compilation Error for Gateway Application

generators/server/files.js, generators/server/templates/src/main/java/package/config/ApplicationProperties.java.ejs, generators/server/templates/src/main/java/package/repository/PersistenceAuditEventRepository.java.ejs, generators/server/templates/src/main/java/package/service/AuditEventService.java.ejs, generators/server/templates/src/main/resources/config/application-dev.yml.ejs, generators/server/templates/src/main/resources/config/application-prod.yml.ejs, generators/server/templates/src/test/java/package/service/AuditEventServiceIT.java.ejs, generators/server/templates/src/test/java/package/web/rest/AuditResourceIT.java.ejs, test/utils/expected-files.js
Related to https://github.com/jhipster/jhipster/pull/379
Fixes #10253
=> Add support for scheduled audit event deletion

generators/server/templates/gradle.properties.ejs, generators/server/templates/pom.xml.ejs
Depends on https://github.com/jhipster/jhipster/pull/396
=> Update spring-boot version to 2.1.8 and dependencies

generators/client/templates/angular/src/main/webapp/app/core/auth/account.service.ts.ejs
=> [angular] replace old "for" by esX method in angular account service

generators/spring-controller/index.js, generators/spring-controller/templates/src/test/java/package/web/rest/ResourceIT.java.ejs
Fix tests when generating a Spring Controller in OAuth2 app
____
=> Fix integration tests with OAuth2 for Spring Controller

.travis.yml, generators/client/templates/react/package.json.ejs
=> update webdriver to support chrome 76

generators/client/templates/react/src/main/webapp/app/modules/login/login.tsx.ejs
=> Fix popup sign (react)

generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management.tsx.ejs
=> [React] Hooks (user-management component)

generators/kubernetes-helm/templates/csvc/values.yml.ejs, generators/kubernetes/prompts.js, generators/kubernetes/templates/console/jhipster-console.yml.ejs, generators/kubernetes/templates/deployment.yml.ejs, generators/kubernetes/templates/ingress.yml.ejs, generators/kubernetes/templates/istio/gateway.yml.ejs, generators/kubernetes/templates/istio/gateway/grafana-gateway.yml.ejs, generators/kubernetes/templates/istio/gateway/jaeger-gateway.yml.ejs, generators/kubernetes/templates/istio/gateway/jhipster-console-gateway.yml.ejs, generators/kubernetes/templates/istio/gateway/jhipster-grafana-gateway.yml.ejs, generators/kubernetes/templates/istio/gateway/kiali-gateway.yml.ejs, generators/kubernetes/templates/k8s-addons.sh.ejs, generators/kubernetes/templates/kubectl-apply.sh.ejs, generators/kubernetes/templates/monitoring/jhipster-grafana.yml.ejs
=> Fix Istio URL issues 

.travis.yml, azure-pipelines.yml
=> Use back jhipster bom release instead of project master branch

generators/entity-server/templates/src/main/java/package/service/EntityQueryService.java.ejs
=> reference correct class in JavaDoc for EntityQueryService

generators/app/index.js, generators/upgrade/index.js, generators/utils.js
This is second part of what was initially submitted in https://github.com/jhipster/generator-jhipster/pull/10389
This refactor should help reduce duplicated code/logic and prevent bug fixed on one side, but not the other.
=> Factorize the code that construct blueprints list

generators/entity-server/templates/src/main/resources/config/cql/changelog/added_entity.cql.ejs, generators/entity/index.js, test-integration/samples/.jhipster/CassBankAccount.json
=> enable use of enumerations with Cassandra

generators/entity-client/templates/angular/src/main/webapp/app/entities/infinite-scroll-template.ejs, generators/entity-client/templates/angular/src/main/webapp/app/entities/no-pagination-template.ejs, generators/entity-client/templates/angular/src/main/webapp/app/entities/pagination-template.ejs
=> fix search params not retriving issue

generators/server/templates/gradle/docker.gradle.ejs, generators/server/templates/pom.xml.ejs
=> Correct JIB configuration for maven and gradle

generators/server/needle-api/needle-server-maven.js, test/needle-api/needle-server-maven.spec.js
This is mostly a disambiguation of artifactId/groupId to strengthen the tests and be sure each test is relevant. I found an empty test that I removed and added a missing test for `addMavenDependency`
=> Improve needle-server-maven unit tests

generators/generator-base.js, generators/server/needle-api/needle-server-maven.js, generators/server/templates/pom.xml.ejs, test/needle-api/needle-server-maven.spec.js
NB: This PR includes commits from https://github.com/jhipster/generator-jhipster/pull/10429
- Add additional 'other' parameter to Maven addRepository() so other pieces of info like name, releases, snapshots can be added
- Add needle for Maven plugin management
- Use full needle expression so things are inserted at right place
=> Completed needle server maven

generators/server/templates/build.gradle.ejs, generators/server/templates/pom.xml.ejs, test/templates/ci-cd/maven-ngx-yarn/pom.xml
See https://github.com/jhipster/generator-jhipster/pull/10356#issuecomment-531991194
=> Remove unused Hibernate Envers dependency

generators/client/templates/angular/src/main/webapp/app/layouts/navbar/navbar.component.ts.ejs
=> correct version display

generators/client/files-angular.js, generators/client/templates/angular/src/main/webapp/app/admin/admin.module.ts.ejs, generators/client/templates/angular/src/main/webapp/app/admin/admin.route.ts.ejs, generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management.component.ts.ejs, generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management.module.ts.ejs, generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management.route.ts.ejs, test/utils/expected-files.js
Modularize user management just like the other entities.
=> Implement UserManagementModule.

generators/client/templates/react/src/main/webapp/app/config/notification-middleware.ts.ejs
=> React with OAuth2 Network Error Fix

generators/server/files.js, generators/server/templates/src/main/java/package/config/DatabaseConfiguration.java.ejs, generators/server/templates/src/main/java/package/config/ReactiveSecurityConfiguration.java.ejs, generators/server/templates/src/main/java/package/repository/PersistenceAuditEventRepository.java.ejs, generators/server/templates/src/main/java/package/security/SpringSecurityAuditorAware.java.ejs, generators/server/templates/src/main/java/package/service/AuditEventService.java.ejs, generators/server/templates/src/main/java/package/web/rest/AuditResource.java.ejs, generators/server/templates/src/main/java/package/web/rest/UserJWTController.java.ejs, generators/server/templates/src/test/java/package/web/rest/UserJWTControllerIT.java.ejs
* Completely removes DB auditing code for reactive apps as it's never triggered
* Makes AuditEvent CRUD reactive
* Creates audit event during JWT authentication
=> Add security audits for reactive apps

generators/server/templates/src/main/java/package/service/AuditEventService.java.ejs, generators/server/templates/src/main/java/package/service/util/RandomUtil.java.ejs
Just fixing the 2 new warnings from the recent analysis
=> fix new sonar warnings

generators/server/templates/src/main/resources/config/application-dev.yml.ejs, generators/server/templates/src/main/resources/config/application-prod.yml.ejs
When you generate an application with package `io.github.jhipster`, it will fail with this error:
```
SyntaxError: Map keys must be unique; "io.github.jhipster" is repeated (18:9)
16 | logging:
17 |     level:
> 18 |         ROOT: INFO
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 19 |         io.github.jhipster: INFO
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 20 |         io.github.jhipster: INFO
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 21 | 
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 22 | management:
| ^
23 |     metrics:
24 |         export:
25 |             prometheus:
at e (/home/pgrimaud/projects/jhipster/generator-jhipster/node_modules/prettier/parser-yaml.js:1:323)
at …
```
=> Fix duplicate key when generating app with package io.github.jhipster

generators/server/templates/gradle.properties.ejs, generators/server/templates/pom.xml.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/10427
=> Rollback liquibase version to 3.6.3 and liquibase-hibernate to 3.6

generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs
Before:
```
<changeSet id="20190121114007-1" author="jhipster">
<createTable tableName="xyz" remarks="abc">
<column name="id" type="bigint" autoIncrement="${autoIncrement}">
<constraints primaryKey="true" nullable="false"/>
</column>
<column name="code" type="varchar(255)">
<constraints nullable="false" />
</column>
<column name="name" type="varchar(255)">
<constraints nullable="true" />
</column>
<column name="other_table_id" type="bigint">
<constraints unique="true" nullable="true" uniqueConstraintName="ux_xyz_other_table_id" />
</column>            <column name="another_table_id" type="bigint">
<constraints unique="true" nullable="true" uniqueConstraintName="ux_xyz_another_table_id" />
</column>
<column name="third_one_id" type="bigint">
<constraints nullable="false" />
</column> …
```
=> Fix formatting of the liquibase changelog that creates table

generators/entity/index.js, test/blueprint/entity-blueprint.spec.js
=> Entity blueprint: allow blueprints to create custom configs.

generators/server/templates/src/main/resources/logback-spring.xml.ejs, generators/server/templates/src/test/resources/logback.xml.ejs
=> Tune logback for reactive apps

generators/server/templates/build.gradle.ejs
=> Fixing #10457

generators/server/templates/src/main/java/package/security/SecurityUtils.java.ejs
=> Refactor SecurityUtils

generators/client/templates/react/src/main/webapp/app/modules/account/settings/settings.reducer.ts.ejs
Fix #10369 
/!\ When logging off and logging on again, the language is still ltr instead of rtl, which is wrong.
=> rtl fix when changing settings in account menu

test-integration/scripts/21-tests-backend.sh
Fix error described in https://github.com/jhipster/generator-jhipster/pull/10398#issuecomment-533879349
=> Fix Gradle microservice build in CI

generators/server/needle-api/needle-server-cache.js, generators/server/templates/src/main/java/package/config/CacheConfiguration.java.ejs, generators/server/templates/src/main/java/package/config/CacheFactoryConfiguration.java.ejs, generators/server/templates/src/main/resources/config/application-dev.yml.ejs, generators/server/templates/src/main/resources/config/application-prod.yml.ejs, test/needle-api/needle-server-cache.spec.js
=> change CacheConfiguration for Infinispan Provider

generators/client/templates/react/src/main/webapp/app/modules/account/settings/settings.reducer.ts.ejs
=> adding check enableI18nRTL for RTL language in settings.reducer.ts

generators/server/templates/src/main/java/package/config/CacheConfiguration.java.ejs, generators/server/templates/src/main/resources/config/application-prod.yml.ejs
Caused By:
* https://github.com/jhipster/generator-jhipster/issues/10321
Related To:
* https://github.com/jhipster/generator-jhipster/pull/10322
* https://github.com/infinispan/infinispan-spring-boot/issues/123
=> Enabled infinispan stats by default in prod profile

azure-pipelines.yml, generators/entity/index.js, generators/server/files.js, generators/server/index.js, generators/server/templates/src/main/java/package/config/CacheConfiguration.java.ejs, generators/server/templates/src/main/java/package/config/CloudDatabaseConfiguration.java.ejs, generators/server/templates/src/main/java/package/config/DatabaseConfiguration.java.ejs, generators/server/templates/src/main/java/package/repository/AuthorityRepository.java.ejs, generators/server/templates/src/main/java/package/repository/PersistenceAuditEventRepository.java.ejs, generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs, generators/server/templates/src/main/java/package/repository/reactive/CustomReactiveN1qlCouchbaseRepository.java.ejs, generators/server/templates/src/main/java/package/repository/reactive/ReactiveN1qlCouchbaseRepository.java.ejs, generators/server/templates/src/main/java/package/security/DomainUserDetailsService.java.ejs, generators/server/templates/src/main/java/package/service/AuditEventService.java.ejs, generators/server/templates/src/main/java/package/service/UserService.java.ejs, generators/server/templates/src/main/java/package/web/rest/AccountResource.java.ejs, generators/server/templates/src/main/java/package/web/rest/UserResource.java.ejs, generators/server/templates/src/test/java/package/security/DomainUserDetailsServiceIT.java.ejs, generators/server/templates/src/test/java/package/service/UserServiceIT.java.ejs, generators/server/templates/src/test/java/package/web/rest/AccountResourceIT.java.ejs, generators/server/templates/src/test/java/package/web/rest/UserJWTControllerIT.java.ejs, generators/server/templates/src/test/java/package/web/rest/UserResourceIT.java.ejs
as there is no mix now with non-reactive repositories
Also disables entity gen for reactive apps
=> Put reactive repositories in package/repository folder

generators/client/templates/angular/package.json.ejs, generators/client/templates/angular/src/main/webapp/app/app.module.ts.ejs, generators/client/templates/angular/src/main/webapp/app/core/core.module.ts.ejs
Fixes #10476
Depends on related `ng-jhipster` change jhipster/ng-jhipster#110, actions needed are:
* merge jhipster/ng-jhipster#110
* release new version of the `ng-jhipster`
* update this PR with the new version of the `ng-jhipster`
* merge this PR
I marked this PR as draft. Draft check can be removed after updating this PR with the new `ng-jhipster` version.
I moved also HTTP interceptor to core module which makes code better readable. …
=> Fix dependency injection in Angular if i18n is enabled

generators/server/templates/src/test/java/package/cucumber/CucumberContextConfiguration.java.ejs, generators/server/templates/src/test/java/package/cucumber/CucumberIT.java.ejs, generators/server/templates/src/test/java/package/cucumber/stepdefs/UserStepDefs.java.ejs
=> use last package of cucumber (mandatory for V5.0.0 of cucumber-jvm)

generators/client/templates/angular/src/main/webapp/app/account/settings/settings.component.ts.ejs, generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management-update.component.ts.ejs, generators/client/templates/angular/src/main/webapp/app/layouts/navbar/navbar.component.ts.ejs
=> remove unused variable when i18n disabled

.github/workflows/generator.yml, test-integration/scripts/10-install-jhipster.sh
=> Integrate github actions and move generator unit tests from travis

generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics.component.ts.ejs, generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management-update.component.ts.ejs, generators/client/templates/angular/src/main/webapp/app/blocks/config/uib-pagination.config.ts.ejs, generators/client/templates/angular/src/main/webapp/app/core/core.module.ts.ejs, generators/client/templates/angular/src/main/webapp/app/shared/alert/alert-error.component.ts.ejs
This PR:
* removes unused injected services
* if injected service is used only in constructor then don't create class field (reference for good explanation: https://stackoverflow.com/a/48571668)
=> Clean constructor parameters in Angular

generators/server/templates/src/test/resources/config/bootstrap.yml.ejs
When executing tests /  integration tests with Consul application, there are some error in logs. This PR will disable Consul during tests:
```
com.ecwid.consul.transport.TransportException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8500 [localhost/127.0.0.1] failed: Connexion refusée (Connection refused)
at com.ecwid.consul.transport.AbstractHttpTransport.executeRequest(AbstractHttpTransport.java:77)
at com.ecwid.consul.transport.AbstractHttpTransport.makeGetRequest(AbstractHttpTransport.java:34)
at com.ecwid.consul.v1.ConsulRawClient.makeGetRequest(ConsulRawClient.java:128)
at com.ecwid.consul.v1.catalog.CatalogConsulClient.getCatalogServices(CatalogConsulClient.java:120)
at com.ecwid.consul.v1.ConsulClient.getCatalogServices(ConsulClient.java:372)
at …
```
=> Disable consul in tests

generators/languages/templates/src/main/webapp/i18n/nl/reset.json.ejs
=> Fixed grammer to resolve: #10518

generators/ci-cd/templates/jenkins/Jenkinsfile.ejs
the current jenkinsfile fails at "frontend tests" : 
```
Archive JUnit-formatted test results -- **/target/test-results/TESTS-*.xml -- (self time 3s)
Recording test results
No test report files were found. Configuration error?
```
the test results are under test and integrationTest subfolders (same pattern as backend tests) : 
```
(...)/target/test-results
$ls -l
total 288
-rw-r--r-- 1 jhipster jhipster  68234 Sep 24 16:02 clover.xml
-rw-r--r-- 1 jhipster jhipster 172549 Sep 24 16:02 coverage-final.json
drwxr-xr-x 2 jhipster jhipster   4096 Sep 24 16:00 integrationTest
drwxr-xr-x 2 jhipster jhipster   4096 Sep 24 16:02 jest
-rw-r--r-- 1 jhipster jhipster  31884 Sep 24 16:02 lcov.info
drwxr-xr-x 3 jhipster jhipster   4096 Sep 24 16:02 lcov-report
drwxr-xr-x 2 jhipster jhipster   4096 Sep …
```
=> fix jenkinsfile for "frontend tests"

generators/server/templates/gradle.properties.ejs, generators/server/templates/pom.xml.ejs
Depends on https://github.com/jhipster/jhipster/pull/416
See https://github.com/mapstruct/mapstruct/releases/tag/1.3.1.Final
=> Update mapstruct version to 1.3.1.Final

generators/server/templates/build.gradle.ejs, generators/server/templates/pom.xml.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/10423
Depends on https://github.com/jhipster/jhipster/pull/420
=> Use new oracle driver package

generators/client/templates/angular/package.json.ejs, generators/client/templates/react/package.json.ejs, generators/generator-constants.js
=> chore: bump yarn version

generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
Fixes #10355 - will work after https://github.com/jhipster/jhipster/pull/421 is merged.
=> Add tests for the new 'notEqual' and 'contains'/'doesNotContain' filters

generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs, generators/server/templates/src/main/java/package/security/oauth2/AudienceValidator.java.ejs, generators/server/templates/src/main/resources/config/application.yml.ejs, generators/server/templates/src/test/java/package/security/oauth2/AudienceValidatorTest.java.ejs
- Closes #10449 
- Dependent on https://github.com/jhipster/jhipster/pull/417
---
=> Externalize audience to Jhipster properties

generators/kubernetes/templates/deployment.yml.ejs
=> improve k8s deployement liveness probe fix #10547

.github/workflows/applications.yml, .travis.yml, test-integration/scripts/00-init-env.sh
=> chore: Migrate cassandra travis pipeline to github actions CI

.github/workflows/applications.yml, .github/workflows/generator.yml, .travis.yml
=> chore: move applications pipeline from travis to github ci

generators/client/templates/angular/webpack/webpack.prod.js.ejs
=> Remove duplicate key "toplevel"

generators/entity-client/files.js, generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-detail.component.html.ejs, generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.html.ejs, generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.module.ts.ejs, generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.route.ts.ejs, generators/entity-client/templates/angular/src/main/webapp/app/entities/entity.service.ts.ejs, generators/entity-client/templates/angular/src/test/javascript/e2e/entities/entity-page-object.ts.ejs, generators/entity-client/templates/angular/src/test/javascript/e2e/entities/entity.spec.ts.ejs, generators/entity-client/templates/angular/src/test/javascript/spec/app/entities/entity-management.service.spec.ts.ejs, generators/entity/index.js, generators/generator-base.js, test-integration/samples/.jhipster/Label.json
=> Readonly entity: Angular client

generators/entity-client/files.js, generators/entity-client/templates/react/src/main/webapp/app/entities/entity-detail.tsx.ejs, generators/entity-client/templates/react/src/main/webapp/app/entities/entity.reducer.ts.ejs, generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs, generators/entity-client/templates/react/src/main/webapp/app/entities/index.tsx.ejs, generators/entity-client/templates/react/src/test/javascript/e2e/entities/entity-page-object.ts.ejs, generators/entity-client/templates/react/src/test/javascript/e2e/entities/entity.spec.ts.ejs, generators/entity-client/templates/react/src/test/javascript/spec/app/entities/entity-reducer.spec.ts.ejs
=> Readonly entity: React client

generators/client/templates/angular/src/main/webapp/app/account/activate/activate.component.ts.ejs, generators/client/templates/angular/src/main/webapp/app/account/password/password.component.html.ejs, generators/client/templates/angular/src/main/webapp/app/account/password/password.component.ts.ejs, generators/client/templates/angular/src/main/webapp/app/account/sessions/sessions.component.ts.ejs, generators/client/templates/angular/src/main/webapp/app/account/settings/settings.component.ts.ejs, generators/client/templates/angular/src/main/webapp/app/admin/health/health.component.ts.ejs, generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management-update.component.ts.ejs, generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management.component.ts.ejs, generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management.route.ts.ejs, generators/client/templates/angular/src/main/webapp/app/core/auth/account.service.ts.ejs, generators/client/templates/angular/src/main/webapp/app/core/auth/auth-jwt.service.ts.ejs, generators/client/templates/angular/src/main/webapp/app/core/auth/user-route-access-service.ts.ejs, generators/client/templates/angular/src/main/webapp/app/core/language/language.helper.ts.ejs, generators/client/templates/angular/src/main/webapp/app/core/login/login-modal.service.ts.ejs, generators/client/templates/angular/src/main/webapp/app/core/login/login.service.ts.ejs, generators/client/templates/angular/src/main/webapp/app/core/user/user.service.ts.ejs, generators/client/templates/angular/src/main/webapp/app/home/home.component.ts.ejs, generators/client/templates/angular/src/main/webapp/app/layouts/navbar/navbar.component.ts.ejs, generators/client/templates/angular/src/main/webapp/app/layouts/profiles/page-ribbon.component.ts.ejs, generators/client/templates/angular/src/main/webapp/app/layouts/profiles/profile.service.ts.ejs, generators/client/templates/angular/src/main/webapp/app/shared/login/login.component.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/app/account/sessions/sessions.component.spec.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/app/account/settings/settings.component.spec.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/app/core/user/account.service.spec.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/app/core/user/user.service.spec.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/helpers/mock-account.service.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/helpers/mock-login.service.ts.ejs, generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.ts.ejs
Made some improvements to leverage the reactive programming features of rxJs with Angular. 
I also cleaned up some useless asynchronous code (ie language Helper)
=> Use observables across Angular app

.travis.yml, azure-pipelines.yml, generators/server/templates/gradle.properties.ejs, generators/server/templates/pom.xml.ejs
=> Upgrade jhipster lib 3.0.6

generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs, generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
Fixes #8800
⚠️ https://github.com/jhipster/generator-jhipster/pull/10562 should be merged before
=> Readonly entity: Server

generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
=> Only generate SMALLER_* constants in integration test when they'll be used

.github/workflows/applications.yml, .github/workflows/generator.yml
=> chore (ci) : Reduce default job timeout in github ci

generators/generator-constants.js
As per https://github.com/jhipster/jhipster.github.io/pull/820#issuecomment-539933461 we need to change Belorussian to Belarusian.
=> Change Language Name to Belarusian

generators/entity-server/files.js
Missing change following https://github.com/jhipster/generator-jhipster/pull/10549
=> When skipping database changelog, don't update liquibase master.xml

generators/entity/index.js, generators/entity/prompts.js
=> Ask for readOnly in entity subgenerator prompt

generators/server/templates/gradle.properties.ejs, generators/server/templates/pom.xml.ejs
Regular minor update
[skip ci]
=> update openapi plugin to 4.1.3

.github/workflows/applications.yml, README.md, test-integration/scripts/00-init-env.sh
This is a probable fix for #10594. Since GitHub actions doesn't seem to have a method to restart successful CI runs; I am going to close and open this PR several times to test this out.  
Fixes #10594
=> Fix for Couchbase Testcontainers Failure

generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs
This is a probable fix for #10600.
=> Microservices + Mongo : Maven (or gradle) build is broken

generators/generator-constants.js
See https://github.com/npm/cli/releases/tag/v6.12.0
=> Update npm version to 6.12.0

generators/app/index.js, generators/generator-base-private.js, test/blueprint/app-blueprint.spec.js
=> Check compatibility with JHipster version used by blueprint(s)

azure-pipelines.yml, test-integration/scripts/00-init-env.sh
Reverts jhipster/generator-jhipster#10608
This should be reverted as per my comment; https://github.com/jhipster/generator-jhipster/issues/10594#issuecomment-541376750
=> Revert "Retiring the use of Azul JDK and go fo OpenJDK"

test-integration/scripts/20-docker-compose.sh, test-integration/scripts/24-tests-e2e.sh
Reverts jhipster/generator-jhipster#10609
Related to : #10594
=> Revert "Reintroduce Couchbase Docker Start"

generators/common/templates/README.md.ejs
Related to https://github.com/jhipster/generator-jhipster/issues/10363
=> Improve server start up command for Gradle if using live reload

generators/client/needle-api/needle-client-react.js, generators/client/templates/react/src/main/webapp/app/routes.tsx.ejs, generators/client/templates/react/src/test/javascript/e2e/page-objects/navbar-page.ts.ejs, generators/entity-client/templates/react/src/main/webapp/app/entities/entity-detail.tsx.ejs, generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs, test/needle-api/needle-client-react.spec.js
Proposition to fix #10301 (I added the `entity/` prefix in Angular routes for entities)
Edit: following @vishal423 suggestion, I removed the entity/ prefix in React routes
=> Fix urls inconsistencies with entities

generators/docker-base.js, generators/docker-compose/index.js
=> Added redis support for docker-compose generator

generators/server/templates/src/test/java/package/config/DatabaseConfigurationIT.java.ejs
Increase couch-base container memory.
Probable resolution for  #10594
=> Couchbase Container Increase Memory Quota

README.md
=> Remove duplicated sponsor links

generators/generator-constants.js, generators/server/index.js, generators/server/templates/build.gradle.ejs, generators/server/templates/gradle/sonar.gradle.ejs, generators/server/templates/gradle/wrapper/gradle-wrapper.properties, generators/server/templates/gradlew, generators/server/templates/pom.xml.ejs
* Update gradle to 5.6.3
* Externalize Jacoco version 
* Jacoco version updated from 0.8.4 >> 0.8.5
=> Update gradle and externalize jacoco version

generators/generator-constants.js
See https://github.com/GoogleContainerTools/jib/blob/master/jib-maven-plugin/CHANGELOG.md#170
=> Update JIB version to 1.7.0

generators/server/templates/src/test/resources/config/application.yml.ejs
=> Fix Cucumber (with Elasticsearch) integration tests

generators/entity-i18n/templates/i18n/entity_es.json.ejs
Closes https://github.com/jhipster/generator-jhipster/issues/10652
=> Fix 'entity not found' Spanish translation

generators/kubernetes/templates/README-KUBERNETES.md.ejs
=> remove obsolete information from kubernetes readme

.travis.yml, azure-pipelines.yml, generators/client/templates/angular/package.json.ejs, generators/client/templates/react/package.json.ejs
=> Upgrade Ubuntu and ChromeDriver to Latest

generators/app/index.js, generators/entity-server/files.js, generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs, generators/entity/index.js, generators/server/index.js, generators/server/templates/src/main/resources/config/application-dev.yml.ejs, test/entity.spec.js, test/templates/psql-with-no-fake-data/.yo-rc.json, test/utils/expected-files.js
=> New CLI flag to disable fake data generation

generators/ci-cd/templates/travis.yml.ejs
Closes #10655 which had two issues:
* multiline bash script
* hung apt commands
Replaces previous PR (#10656) which only handled the first case.
Fully working build here: https://travis-ci.com/amirdt22/jhipstest/builds/132979495
=> ci-cd travis yml fixes: multiline+jdk11 apt

generators/app/prompts.js
=> Promote reactive option out of experimental

generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs
=> correct comment regarding faker.js

generators/entity-server/templates/src/test/java/package/domain/EntityTest.java.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/10700
_____
=> Fix relationships with User for OAuth2 app

generators/server/templates/src/main/resources/templates/error.html.ejs, generators/server/templates/src/main/resources/templates/mail/activationEmail.html.ejs, generators/server/templates/src/main/resources/templates/mail/creationEmail.html.ejs, generators/server/templates/src/main/resources/templates/mail/passwordResetEmail.html.ejs
This fixes the remaining sonar bugs for our mail templates.
=> fix remaining sonar bugs for mail templates

generators/entity-i18n/templates/i18n/entity_es.json.ejs
=> Fix 'search for entity' Spanish translation

generators/export-jdl/index.js, test/export-jdl.spec.js
Now takes into account the output file
Fixes https://github.com/jhipster/jhipster-core/issues/391
=> Updated the JDL export subgen

generators/server/templates/build.gradle.ejs, generators/server/templates/gradle/wrapper/gradle-wrapper.properties
Update to latest 5.x version. Afterwards I will go on with testing 6.x release candidates.
https://docs.gradle.org/5.6.4/release-notes.html
=> Update gradle to 5.6.4

generators/generator-constants.js
See https://github.com/npm/cli/releases/tag/v6.13.0
=> Update npm version to 6.13.0

generators/server/templates/gradle.properties.ejs, generators/server/templates/pom.xml.ejs
And the gradle node plugin to 2.2.0
https://github.com/TNG/ArchUnit/releases/tag/v0.12.0
https://github.com/node-gradle/gradle-node-plugin/releases
=> update arch unit to 0.12.0

generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/auth-expired.interceptor.ts.ejs, generators/client/templates/angular/src/main/webapp/app/core/auth/state-storage.service.ts.ejs
Resolves #10551
Now login modal is opened also for JWT authentication.
`...PreviousState` and `...DestinationState` from `state-storage.service` were used in some older versions, currently only dead code (`stateStorageService.getDestinationState()` is always **null**) was remaining in `auth-expired.interceptor`, so I removed this dead and redundant code.  
Before was constantly `stateStorageService.storeUrl('/')` executed, now current url is stored - so if user logs in then user is routed to the last accessed url.
For session authentication before was used `AuthServerProvider.logout()` but this was not clearing `accout` from `AccountService`, so I replaced this with `LoginService.logout` which is clearing also `account` from `AccountService`.
As Angular router lacks reload functionality …
=> Open login modal if JWT is expired in Angular

generators/client/templates/angular/package.json.ejs
fixes #10629 
change in ng-jhipster is done by jhipster/ng-jhipster#111
=> Fix sorting icons in Angular

generators/server/templates/pom.xml.ejs, generators/server/templates/src/test/resources/config/application.yml.ejs
=> Remove deprecated H2 property MULTI_THREAD

test-integration/scripts/21-tests-backend.sh
Following https://github.com/jhipster/generator-jhipster/pull/10466
cc @atomfrede 
_____
=> Fix gradle backend tests, for not using webpack with microservice

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .travis.yml, cli/import-jdl.js, generators/export-jdl/index.js, package-lock.json, package.json, rfcs/0-jhipster-rfc-template.md, rfcs/1-jhipster-rfc-k8s-operator.md, test-integration/samples/jdl-default/app.jdl, test/templates/documents-with-relations/orders-model.jdl, test/templates/import-jdl/jdl-ambiguous.jdl
Also fixed the JDL export if the app to export to JDL contains a rememberMeKey, fixed in v6.0.1
I think the linter had fun linting the project's files, that's why there are more changes than expected.
=> Updated JCore to v6.0.1

.github/workflows/applications.yml, .travis.yml, azure-pipelines.yml, generators/server/templates/gradle.properties.ejs, generators/server/templates/pom.xml.ejs
=> Upgrade jhipster lib 3.0.7

generators/ci-cd/templates/.gitlab-ci.yml.ejs
Somehow we added `no-transfer-progress` to all ci configs except gitlab. 
=> make gitlab ci job execution less verbose

test-integration/samples/.jhipster/FieldTestPagerEntity.json, test-integration/samples/.jhipster/TestPager.json
=> Replaced pager deprecated option by pagination

generators/server/templates/src/main/resources/logback-spring.xml.ejs
+ standardization of conditioning in lockback config template 
=> Configure Kafka logger level only if Kafka is used

generators/upgrade/index.js, test/upgrade.spec.js
=> Fix upgrade tests

test-integration/samples/.jhipster/TestManyToMany.json, test-integration/samples/.jhipster/TestManyToOne.json, test-integration/samples/.jhipster/TestOneToOne.json
Following https://github.com/jhipster/generator-jhipster/pull/10760 by @murdos 
_____
=> CI: remove entities related to TestPager

generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs
=> Fix fake data with UUID

generators/generator-constants.js, generators/kubernetes-base.js, generators/kubernetes-helm/index.js, generators/kubernetes-helm/templates/app/requirements.yml.ejs, generators/kubernetes-helm/templates/csvc/requirements.yml.ejs, generators/kubernetes-helm/templates/helm-apply.sh.ejs
=> update helm service dependency versions

generators/client/templates/angular/src/main/webapp/swagger-ui/index.html.ejs, generators/client/templates/react/src/main/webapp/swagger-ui/index.html.ejs
=> Sorting swagger resources alphabetically

generators/client/templates/angular/package.json.ejs
=> Use ng-jhipster version 0.11.4

generators/ci-cd/templates/.gitlab-ci.yml.ejs
=> fix maven gitlab ci cache in build docker job

cli/cli.js, cli/jhipster.js, generators/aws-containers/index.js, generators/aws-containers/lib/cloudFormation.js, generators/aws-containers/lib/ecr.js, generators/aws-containers/lib/ssm.js, generators/aws-containers/lib/utils.js, generators/aws-containers/prompts.js, generators/client/prompts.js, generators/generator-base-blueprint.js, generators/generator-base-private.js, test/blueprint/app-blueprint.spec.js, test/generator-base-private.spec.js
=> Cleanup unnecessary `eslint-disable-*` comment blocks

package.json
=> Arrange devDependencies in package.json alphabetically

generators/export-jdl/index.js, package-lock.json, package.json
=> Updated JCore to v6.0.4 & fixed the JDL export error logging 

generators/generator-constants.js
=> update gradle to 6.0.1

generators/client/templates/react/src/main/webapp/app/modules/login/logout.tsx.ejs, generators/entity-client/templates/react/src/test/javascript/e2e/entities/entity.spec.ts.ejs
=> [React] Hooks (logout component)

generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs, generators/server/templates/src/main/resources/config/liquibase/changelog/initial_schema.xml.ejs
=> Simplify condition to define ID as autoincrement or sequence in liquibase change log

generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs
- Includes problem library authentication entry point in the OIDC flow to not redirect when an unauthenticated user tries to access a protected resource.
- Closes #10642 
---
=> fix: Fix cors warning in the OIDC flow

generators/client/templates/angular/webpack/utils.js.ejs, generators/client/templates/react/webpack/utils.js.ejs
=> Simplify if-else construct

Dockerfile
=> Add tzdata as package to the docker image

generators/entity/index.js
Fix https://github.com/jhipster/generator-jhipster/issues/10802
______
=> Save readOnly configuration for Entities

generators/ci-cd/index.js, generators/ci-cd/prompts.js, test/ci-cd.spec.js
Related to https://github.com/jhipster/jhipster.github.io/pull/851
cc @vishal423 : hope you're ok with this change
_____
=> Rename GitHub CI to GitHub Actions

generators/client/templates/angular/package.json.ejs
2 PR-s in this new version 0.11.5: jhipster/ng-jhipster#115 and jhipster/ng-jhipster#116
=> Upgrade to ng-jhipster v0.11.5

package-lock.json, package.json
For https://github.com/jhipster/generator-jhipster/issues/10824
=> Updated JCore to v6.0.5

.github/workflows/applications.yml, .github/workflows/generator.yml
related to https://github.com/jhipster/generator-jhipster/issues/10817
for more visibility
_____
=> GitHub actions rename jobs

README.md
[skip ci] NO_CI
related to https://github.com/jhipster/generator-jhipster/issues/10817
=> GitHub Actions: add badges

generators/server/prompts.js
=> exclude no-db for uaa servers, fix #10843

generators/cleanup.js, generators/server/files.js, generators/server/templates/src/test/java/package/service/mapper/UserMapperTest.java.ejs, test/utils/expected-files.js
=> Remove SpringBootTest from UserMapper test

generators/ci-cd/index.js, generators/ci-cd/prompts.js, generators/ci-cd/templates/github-ci.yml.ejs, test/ci-cd.spec.js, test/templates/ci-cd/gradle-ngx-npm/.yo-rc.json, test/templates/ci-cd/gradle-ngx-yarn/.yo-rc.json, test/templates/ci-cd/maven-ngx-npm/.yo-rc.json, test/templates/ci-cd/maven-ngx-yarn/.yo-rc.json
=> Add docker publish option to Github CI

generators/app/index.js, generators/entity-server/files.js, generators/entity-server/templates/src/main/resources/config/liquibase/fake-data/table.csv.ejs, generators/generator-base-private.js, generators/generator-base.js, test/entity.spec.js, test/utils/expected-files.js
Fix faker reproducibility of dates and enums.
And implement reproducibility for liquibase files
Fixes #10372
=> Fix faker and implement liquibase reproducibility

generators/common/templates/README.md.ejs, generators/kubernetes/templates/README-KUBERNETES.md.ejs
Align with the proposed wording in our documentation. Also see https://github.com/jhipster/jhipster.github.io/pull/854
=> remove simple, easily and other words from documentation

.travis.yml, Dockerfile, azure-pipelines.yml, generators/generator-constants.js
=> Upgrade to NodeJS 12.13.1 LTS

generators/azure-spring-cloud/templates/pom-profile.xml.ejs
Use a stable version of the Azure Spring Cloud dependency
=> Use stable dependency

generators/ci-cd/prompts.js, generators/ci-cd/templates/github-ci.yml.ejs, test/ci-cd.spec.js
=> Add Sonar, Artifactory and Heroku integrations to Github Actions

generators/ci-cd/templates/github-ci.yml.ejs
=> Fix Sonar step in Github Actions

generators/server/templates/src/test/java/package/service/MailServiceIT.java.ejs
=> Fix Sonar smell in MailServiceIT

.github/workflows/applications.yml, azure-pipelines.yml, generators/server/templates/gradle.properties.ejs, generators/server/templates/pom.xml.ejs
=> Switch to jhipster bom version 3.0.8-SNAPSHOT

generators/generator-constants.js
=> Update yarn version to 1.19.2 and npm version to 6.13.2

generators/generator-constants.js
=> Update jib version to 1.8.0

generators/server/templates/gradle.properties.ejs, generators/server/templates/pom.xml.ejs
=> Update spring-boot to 2.1.11 and other dependencies

generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs
=> Don't use @Transactional when user relationship exists

generators/app/index.js, generators/cleanup.js, generators/generator-base-private.js, generators/upgrade/index.js
Fixes https://github.com/jhipster/generator-jhipster/issues/10840
This PR will rename the files and create a commit before the generation with the new jhipster version.
=> Migrate problematic localization files on upgrade.

generators/entity-server/templates/src/main/resources/config/liquibase/fake-data/table.csv.ejs
=> Fix issue with fake data

generators/server/templates/src/main/resources/swagger/api.yml.ejs
=> Add Problem reusable definition to OAS

generators/server/templates/src/main/resources/swagger/api.yml.ejs
=> Add Basic auth to OAS for JWT monolith

generators/entity-client/templates/angular/src/main/webapp/app/entities/enumerations/enum.model.ts.ejs, generators/entity-client/templates/angular/src/test/javascript/spec/app/entities/entity-management.service.spec.ts.ejs, generators/entity-client/templates/react/src/main/webapp/app/entities/enumerations/enum.model.ts.ejs, generators/utils.js
The back-end already works
Fixes #10903
=> Supported custom values for enums (front-end)

generators/client/templates/angular/src/main/webapp/app/admin/logs/log.model.ts.ejs, generators/client/templates/angular/src/main/webapp/app/admin/logs/logs.component.ts.ejs, generators/client/templates/angular/src/main/webapp/app/admin/logs/logs.service.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/app/admin/logs/logs.component.spec.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/app/admin/logs/logs.service.spec.ts.ejs
=> Strict Typescript option in logs module in Angular

generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics.component.html.ejs, generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics.component.ts.ejs, generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics.module.ts.ejs, generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics.route.ts.ejs, generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics.service.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/app/admin/metrics/metrics.component.spec.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/app/admin/metrics/metrics.service.spec.ts.ejs
Metrics module for #10631 
Some notes:
* removed prefix from component and service name and changed component name to standard according to #10220 
* FYI: metrics endpoint code is here: https://github.com/jhipster/jhipster/blob/master/jhipster-framework/src/main/java/io/github/jhipster/config/metric/JHipsterMetricsEndpoint.java#L45-L65
* FYI: nice JSON to Typescript conversion tool: https://app.quicktype.io/ …
=> Strict Typescript option in metrics module in Angular

generators/client/templates/angular/src/test/javascript/e2e/page-objects/jhi-page-objects.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/app/account/settings/settings.component.spec.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/helpers/mock-account.service.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/helpers/mock-alert.service.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/helpers/mock-login.service.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/helpers/spyobject.ts.ejs
This is general test components PR for #10631 
From helpers only 3 mocks are included because some mocks are cleaned by layouts PR and some mocks are already cleaned.
=> Strict Typescript option in general test components in Angular

generators/kubernetes/templates/db/mssql.yml.ejs, generators/server/templates/src/main/docker/mssql.yml.ejs, test/templates/compose/11-mssql/src/main/docker/mssql.yml
=> Use Express edition as the default mssql server

generators/server/prompts.js, generators/server/templates/build.gradle.ejs, generators/server/templates/pom.xml.ejs, generators/server/templates/src/main/java/package/web/rest/KafkaResource.java.ejs, generators/server/templates/src/test/java/package/web/rest/KafkaResourceIT.java.ejs
=> Add Kafka support to reactive apps

cli/cli.js
Fixes #10934
Refer: https://nodejs.org/api/process.html#process_process_exit_code
=> Set exitCode Rather Than Letting Node to Exit Abruptly

cli/cli.js, cli/import-jdl.js, cli/utils.js
=> Set process.exitCode directly when subProcess exist with non 0 value.

cli/run-yeoman-process.js, cli/utils.js
Reverts jhipster/generator-jhipster#10948
As discussed here: https://github.com/jhipster/generator-jhipster/issues/10934#issuecomment-565799765
cc @SudharakaP @mshima
=> Revert "Remove Explicit Calls to process.exit and Set the exitCode Instead"

generators/generator-constants.js
See https://github.com/jhipster/jhipster-registry/issues/391
cc @pascalgrimaud
=> Upgrade to jhipster-registry v6.0.1

generators/kubernetes/templates/deployment.yml.ejs, generators/openshift/templates/deployment.yml.ejs, generators/server/templates/src/main/docker/app.yml.ejs, generators/server/templates/src/main/resources/config/application-dev.yml.ejs, generators/server/templates/src/main/resources/config/application-prod.yml.ejs, test/templates/compose/01-gateway/src/main/docker/app.yml, test/templates/compose/02-mysql/src/main/docker/app.yml, test/templates/compose/06-uaa/src/main/docker/app.yml, test/templates/compose/08-monolith/src/main/docker/app.yml, test/templates/compose/09-kafka/src/main/docker/app.yml
=> Add createDatabaseIfNotExist=true to the MySQL connection String

generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/notification.interceptor.ts.ejs, generators/client/templates/react/src/main/webapp/app/config/notification-middleware.ts.ejs
This is client side change for jhipster/jhipster#507 for Angular and React
Closes #10877 
=> Allow any characters in alert parameter

generators/client/templates/react/package.json.ejs
Following https://github.com/jhipster/generator-jhipster/issues/10678
_____
=> Upgrade to react-jhipster v0.9.1

generators/ci-cd/templates/azure-pipelines.yml.ejs
add clientPackageManager for azure pipeline for use with serverless projects
See jhipster/generator-jhipster#10937
=> Add clientPackageManager to Azure Pipeline

generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/notification.interceptor.ts.ejs, generators/client/templates/angular/tsconfig-aot.json.ejs, generators/client/templates/angular/tsconfig.json.ejs, generators/client/templates/angular/tslint.json.ejs
=> Switch on strict Typescript option in Angular

generators/entity-client/files.js, generators/entity-server/files.js, generators/entity-server/templates/src/main/resources/config/liquibase/fake-data/table.csv.ejs, generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs, generators/generator-base-private.js, generators/generator-base.js, generators/utils.js, test/entity.spec.js, test/generator-base-private.spec.js, test/templates/reproducible/.jhipster/Foo.json, test/templates/reproducible/.yo-rc.json, test/utils.spec.js
This PR addresses https://github.com/jhipster/generator-jhipster/pull/10897#issuecomment-564269736 and https://github.com/jhipster/generator-jhipster/pull/10897#issuecomment-564255169
- Use faker to provide seed for Randexp
- Use entity's changelogDate to initialize faker seed, so changing the entity's order will not change the fake data.
=> Improve reproducibility

generators/ci-cd/templates/github-ci.yml.ejs
- Refer [sample pipeline execution](https://github.com/vishal423/sample-app-temp/commit/f0cefa4be10d7e86706eb9409e9457e36e6f7d5e/checks?check_suite_id=362026736) on a project generated with `skip-server` flag.
- I am not quite sure on other integrations supported in the github pipeline when `skip-server` flag is used. @cbornet can you check those?
--
=> fix (github ci): Improve github actions to build and test frontend only apps

generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.html.ejs, generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.ts.ejs, generators/entity-client/templates/angular/src/main/webapp/app/entities/pagination-template.ejs, generators/entity-client/templates/angular/src/test/javascript/spec/app/entities/entity-management.component.spec.ts.ejs
Closes #10931 
Fixed all problems and replaced suspicious code described in https://github.com/jhipster/generator-jhipster/issues/10931#issuecomment-565909336
=> Fix entity pagination in Angular

generators/azure-app-service/templates/github/workflows/azure-app-service.yml.ejs, generators/azure-spring-cloud/templates/github/workflows/azure-spring-cloud.yml.ejs
This is the same as #10976 but for the Azure sub-generators.
So if #10976 is successful, this should be merged!
=> Add Maven  --batch-mode option to improve CI readability in Azure sub-generator

generators/kubernetes/templates/console/jhipster-console.yml.ejs, generators/kubernetes/templates/console/jhipster-dashboard-console.yml.ejs, generators/kubernetes/templates/console/jhipster-logstash.yml.ejs, generators/kubernetes/templates/console/jhipster-zipkin.yml.ejs, generators/kubernetes/templates/db/couchbase.yml.ejs, generators/kubernetes/templates/db/elasticsearch.yml.ejs, generators/kubernetes/templates/db/mariadb.yml.ejs, generators/kubernetes/templates/db/mongodb.yml.ejs, generators/kubernetes/templates/db/mssql.yml.ejs, generators/kubernetes/templates/db/mysql.yml.ejs, generators/kubernetes/templates/db/postgresql.yml.ejs, generators/kubernetes/templates/messagebroker/kafka.yml.ejs
=> Add resource limits for Kubernetes specs

generators/server/templates/gradle.properties.ejs, generators/server/templates/pom.xml.ejs
=> update no http plugin to 0.0.4

generators/client/templates/angular/src/main/webapp/app/account/activate/activate.component.ts.ejs, generators/client/templates/angular/src/main/webapp/app/account/password-reset/finish/password-reset-finish.component.ts.ejs, generators/client/templates/angular/src/main/webapp/app/account/password-reset/init/password-reset-init.component.ts.ejs, generators/client/templates/angular/src/main/webapp/app/account/password/password.component.ts.ejs, generators/client/templates/angular/src/main/webapp/app/account/sessions/sessions.component.ts.ejs, generators/client/templates/angular/src/main/webapp/app/admin/audits/audits.component.ts.ejs, generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management-update.component.ts.ejs, generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management.component.ts.ejs, generators/client/templates/angular/src/main/webapp/app/app.constants.ts.ejs, generators/client/templates/angular/src/main/webapp/app/core/auth/account.service.ts.ejs, generators/client/templates/angular/src/main/webapp/app/core/auth/auth-jwt.service.ts.ejs, generators/client/templates/angular/src/main/webapp/app/core/tracker/tracker.service.ts.ejs, generators/client/templates/angular/src/main/webapp/app/core/user/user.model.ts.ejs, generators/client/templates/angular/src/main/webapp/app/layouts/error/error.component.ts.ejs, generators/client/templates/angular/src/main/webapp/app/shared/auth/has-any-authority.directive.ts.ejs, generators/client/templates/angular/src/main/webapp/app/shared/login/login.component.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/app/account/password-reset/finish/password-reset-finish.component.spec.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/app/account/register/register.component.spec.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/app/admin/audits/audits.component.spec.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/app/admin/audits/audits.service.spec.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/app/admin/logs/logs.service.spec.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/app/admin/metrics/metrics.service.spec.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/app/admin/user-management/user-management.component.spec.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/app/core/user/account.service.spec.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/helpers/mock-active-modal.service.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/helpers/mock-event-manager.service.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/helpers/mock-language.service.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/helpers/mock-route.service.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/helpers/mock-state-storage.service.ts.ejs, generators/client/templates/angular/webpack/utils.js.ejs
I was browsing Angular code after finishing PR-s for the #10631 and made some minor polishing:
* shortened code in some places
* changed `!!` to `Boolean()` everywhere
* moved private method at the end of the Angular classes
* changed some `any` to strict type
* removed unused variable
* grouped imports so that external imports are in the first group and internal imports in the second group
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob …
=> Polish Angular templates

generators/server/templates/src/main/java/package/Application.java.ejs, generators/server/templates/src/main/java/package/ApplicationWebXml.java.ejs, generators/server/templates/src/main/java/package/security/PersistentTokenRememberMeServices.java.ejs, generators/server/templates/src/main/java/package/service/UserService.java.ejs, generators/server/templates/src/test/java/package/service/UserServiceIT.java.ejs
Optimize imports of recently changed classes
=> Optimize imports

generators/client/templates/react/package.json.ejs
Following https://github.com/jhipster/generator-jhipster/pull/10914
The resolutions need to be updated, as we have failures with React+Yarn:
https://dev.azure.com/hipster-labs/jhipster-daily-builds/_build?definitionId=22&_a=summary
_____
=> Fix resolutions for React with Yarn

generators/server/templates/src/main/java/package/web/rest/errors/ExceptionTranslator.java.ejs
Import optimization & formatting
=> Optimize code for ExceptionTranslator

generators/server/templates/src/main/resources/templates/error.html.ejs
Cleans up the page.
We should also validate if this is still useful or not, as it's not reachable anymore:
- If you are a human, you will get the error message from the front-end
- If you use the API, this is taken care of by Zalando Problems
So maybe this should be removed
=> Clean up the error.html page

.github/workflows/angular.yml, .github/workflows/generator.yml, .github/workflows/react.yml, .github/workflows/triage.yml, rfcs/0-jhipster-rfc-template.md, rfcs/1-jhipster-rfc-k8s-operator.md, rfcs/2-jhipster-rfc-jhipster-control-center.md
Closes #10905
As `npm run lint-fix` reformatted also lists in RFC-s then adding also these RFC list changes to this PR.
=> Formatted generator files with npm run lint-fix

generators/ci-cd/templates/github-ci.yml.ejs
=> fix (github ci): Fix duplicate run command in the package app step

generators/azure-spring-cloud/index.js, generators/azure-spring-cloud/templates/github/workflows/azure-spring-cloud.yml.ejs
The extension is now officially listed
=> use the new az spring-cloud extension

generators/entity/index.js
Fix potential problems with other fields like happened with otherEntityRelationshipNamePlural at #10984.
=> Issue 10984 follow up

README.md
=> Fix link for SonarCloud

.github/workflows/angular.yml, .github/workflows/react.yml, azure-pipelines.yml, generators/server/templates/gradle.properties.ejs, generators/server/templates/pom.xml.ejs
=> Upgrade jhipster lib 3.1.0

generators/client/templates/react/src/main/webapp/app/app.scss.ejs, generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs
Fix alignment of checkboxes in React.
**Before in update User:**
**After in update User:**
------------------------------------------------------------
**Before in Entity:**
**After in Entity:**
`className="form-check-input"`might not be required as it seems automatically added. I will check deeper (every input) and make an eventual other PR
=> Fix alignment of checkboxes in React.

generators/generator-constants.js
=> Upgrade to jhipster-registry v6.0.2

generators/server/templates/src/main/java/package/service/MailService.java.ejs, generators/server/templates/src/main/java/package/service/UserService.java.ejs
Fixes https://github.com/jhipster/generator-jhipster/issues/10646
=> Add validations for users with null email.

generators/server/prompts.js, generators/server/templates/src/main/java/package/config/ReactiveSecurityConfiguration.java.ejs, generators/server/templates/src/main/java/package/web/rest/AccountResource.java.ejs, generators/server/templates/src/main/java/package/web/rest/UserJWTController.java.ejs, generators/server/templates/src/test/java/package/web/rest/AccountResourceIT.java.ejs, generators/server/templates/src/test/java/package/web/rest/UserJWTControllerIT.java.ejs
=> Support no database & skipUserManagement in reactive apps

package-lock.json, package.json
=> Bumped the JCore dep to v6.0.6

CONTRIBUTING.md
=> Add Information About Building a Snapshot Version

generators/client/templates/react/src/main/webapp/app/config/axios-interceptor.ts.ejs, generators/client/templates/react/src/main/webapp/app/config/websocket-middleware.ts.ejs, generators/client/templates/react/src/main/webapp/app/shared/reducers/authentication.ts.ejs, generators/client/templates/react/src/test/javascript/spec/app/shared/reducers/authentication.spec.ts.ejs
=> Use defined prefix (custom or jhi) for local/session storage (React)

generators/kubernetes-helm/files.js, generators/kubernetes-helm/templates/helm-apply.sh.ejs, generators/kubernetes-helm/templates/helm-upgrade.sh.ejs, generators/kubernetes/templates/istio/gateway/jhipster-grafana-gateway.yml.ejs, generators/languages/templates/src/main/resources/i18n/messages_zh_TW.properties.ejs, generators/languages/templates/src/main/webapp/i18n/uz-Cyrl-uz/health.json.ejs, generators/server/templates/src/main/java/package/repository/reactive/CustomReactiveN1qlCouchbaseRepository.java.ejs, generators/server/templates/src/main/java/package/web/rest/AuthInfoResource.java.ejs
Related with https://github.com/jhipster/generator-jhipster/pull/11048
=> Update copyright header

generators/kubernetes/templates/console/jhipster-logstash.yml.ejs
=> Remove double license header [ci skip]

generators/client/templates/react/src/main/webapp/app/shared/util/date-utils.ts.ejs, generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management-update.component.ts.ejs, generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs
Fix #8846
Set datetime-local by default with the date: today 00:00
=> datetime-local: default value

package-lock.json, package.json
=> Update yeoman-generator to 4.4.0, and yeoman-environment to 2.7.0

generators/docker-compose/files.js, generators/docker-compose/index.js, generators/kubernetes/templates/deployment.yml.ejs, generators/kubernetes/templates/service.yml.ejs, generators/server/files.js, generators/server/templates/pom.xml.ejs, generators/server/templates/src/main/java/package/Application.java.ejs, generators/server/templates/src/main/java/package/security/oauth2/UaaSignatureVerifierClient.java.ejs, generators/server/templates/src/main/java/package/security/oauth2/UaaTokenEndpointClient.java.ejs, generators/server/templates/src/main/java/package/web/filter/RouteDetectorFilter.java.ejs, generators/server/templates/src/main/resources/config/application.yml.ejs
Re-introduces #10763 while also fixing #10967.
fix #8967
fix #9027
=> UAA Improvements / Docker Compose Fixes

generators/generator-base-blueprint.js
Fixes https://github.com/jhipster/generator-jhipster/issues/10663
=> Unify blueprint configuration

generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs
=> Add check for OidcUserAuthority

generators/server/templates/gradle.properties.ejs, generators/server/templates/pom.xml.ejs
=> Update to jhipster bom 3.2.0-SNAPSHOT version

generators/client/templates/angular/src/test/javascript/spec/helpers/spyobject.ts.ejs
=> Polish SpyObject in Angular

generators/entity-server/templates/src/main/java/package/common/get_all_template.ejs, generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs
This PR fixes regression from #11029 which removed newline in `EntityResource.java` https://github.com/jhipster/generator-jhipster/pull/11029/files#diff-b81c22d422fbf88bea9c9c3f64ecef57L241-R241 and cleans more in `EntityResource.java`
1. Missing newline issue sample:
before #11029:
```
@GetMapping("/test-one-to-ones/{id}")
public ResponseEntity<TestOneToOne> getTestOneToOne(@PathVariable Long id) {
```
after #11029:
```
@GetMapping("/test-one-to-ones/{id}")    public ResponseEntity<TestOneToOne> getTestOneToOne(@PathVariable Long id) {
```
This PR restores this newline.
2. Additionally this PR polishes `EntityResource.java` to make it better understandable - as result of this cleaning some wrong spaces and newlines were removed.
-   Please make sure the below checklist is followed for …
=> Add missing newline and more cleaning in EntityResource.java

generators/kubernetes/prompts.js
=> fix kubernetes manifest generation when dynamic storage is disabled

package-lock.json, package.json
=> Update yo version to 3.1.1

generators/client/templates/angular/src/main/webapp/app/admin/configuration/configuration.component.html.ejs, generators/server/templates/src/main/resources/static/microservices_index.html.ejs
=> Fix some Sonar Analyze

generators/generator-constants.js, generators/openapi-client/files.js, generators/server/index.js, generators/server/templates/gradle.properties.ejs, generators/server/templates/pom.xml.ejs
fix https://github.com/jhipster/generator-jhipster/issues/11010
=> Add jackson-databind-nullable dependency with openapi-generator

generators/client/templates/angular/package.json.ejs
=> Use alphabetical dependencies order in Angular package.json

generators/generator-base-private.js
This PR shortens generated Angular entity update component source code 5-7 lines per relationship.
=> Shorten Angular entity update component

generators/client/templates/angular/src/main/webapp/app/layouts/navbar/navbar.component.html.ejs
=> Fix Bootswatch navbar in primary variant

generators/server/files.js, generators/server/templates/src/main/java/package/repository/PersistenceAuditEventRepository.java.ejs, generators/server/templates/src/test/java/package/service/AuditEventServiceIT.java.ejs, generators/server/templates/src/test/java/package/web/rest/AuditResourceIT.java.ejs
=> Add audit tests for reactive apps

generators/server/templates/src/main/java/package/service/UserService.java.ejs
=> single quote while using indexOf on a character

.github/workflows/angular.yml, generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.html.ejs, generators/entity-client/templates/angular/src/test/javascript/e2e/entities/entity-page-object.ts.ejs, generators/entity-client/templates/angular/src/test/javascript/e2e/entities/entity.spec.ts.ejs, generators/entity-server/templates/src/main/resources/config/liquibase/fake-data/table.csv.ejs
=> Remove unwanted fake data for entity linked to User with MapIds & oauth2

cli/cli.js, cli/import-jdl.js, cli/utils.js
=> Change cli logs from fatal to error.

generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs, generators/server/templates/src/main/java/package/service/EmailAlreadyUsedException.java.ejs, generators/server/templates/src/main/java/package/service/InvalidPasswordException.java.ejs, generators/server/templates/src/main/java/package/service/UsernameAlreadyUsedException.java.ejs, generators/server/templates/src/main/java/package/web/rest/AccountResource.java.ejs, generators/server/templates/src/test/java/package/config/WebConfigurerTest.java.ejs, generators/server/templates/src/test/java/package/security/DomainUserDetailsServiceIT.java.ejs, generators/server/templates/src/test/java/package/web/rest/UserJWTControllerIT.java.ejs
- Update deprecated methods (java)
- Remove warnings (java)
- Remove unused imports (java)
=> Fix: Deprecated methods / Warnings / Imports

generators/server/templates/src/test/java/package/ArchTest.java.ejs
=> Fix arch test for packages containing 'service' or 'repository'

generators/server/templates/build.gradle.ejs, generators/server/templates/pom.xml.ejs
=> Clean maven/gradle dependencies

generators/client/templates/angular/src/main/webapp/app/admin/audits/audits.component.html.ejs, generators/server/templates/src/test/java/package/web/rest/AccountResourceIT.java.ejs, generators/server/templates/src/test/java/package/web/rest/TestUtil.java.ejs, generators/server/templates/src/test/java/package/web/rest/UserResourceIT.java.ejs
Noticed those while upgrading an application
=> Fix some spacing and blank lines

.github/workflows/angular.yml, .github/workflows/react.yml, azure-pipelines.yml, generators/server/templates/gradle.properties.ejs, generators/server/templates/pom.xml.ejs
=> Update Jhipster bom version to 3.2.0

generators/client/templates/react/src/main/webapp/app/shared/error/error-boundary.tsx.ejs, generators/server/templates/src/main/java/package/security/jwt/JWTConfigurer.java.ejs, generators/server/templates/src/main/java/package/security/jwt/JWTFilter.java.ejs, generators/server/templates/src/main/java/package/security/jwt/TokenProvider.java.ejs, generators/server/templates/src/test/java/package/service/AuditEventServiceIT.java.ejs, generators/server/templates/src/test/java/package/service/MailServiceIT.java.ejs
PR to improve quality code:
-   [x] Unnecessary semicolon
-   [x] Declaration can have final modifier
-   [x] The declared exception is never thrown
-   [x] Simplify statement
Check:
=> Some improvements (quality code)

generators/generator-base.js
Correcting the mistake pointed out at, https://github.com/jhipster/generator-jhipster/pull/11140#discussion_r368277179
=> Workaround for ShellJS Directory Creation - Correct Mistake in PR #11140

generators/generator-constants.js
=> update gradle version to 6.1

package-lock.json, package.json
@DanielFran thanks to Jon, there's a good reason for me to make a new release ;)
=> Bumped the JCore dep to v6.0.7

generators/kubernetes-helm/templates/helm-apply.sh.ejs
=> update - helm@3 client support

.github/workflows/angular.yml, .github/workflows/react.yml, azure-pipelines.yml, generators/server/templates/gradle.properties.ejs, generators/server/templates/pom.xml.ejs
=> Update Spring boot version to 2.2.4

.github/workflows/angular.yml, .github/workflows/react.yml, azure-pipelines.yml, generators/server/templates/gradle.properties.ejs, generators/server/templates/pom.xml.ejs
=> Update Jhipster bom version to 3.3.0

generators/common/templates/README.md.ejs
=> [skip ci] fixed path for application.yml for OAuth & OIDC configs

generators/client/templates/angular/package.json.ejs, generators/client/templates/react/package.json.ejs
=> Fix Git commit in React in Windows

.github/workflows/gradle-wrapper-validation.yml
- add copyrights
- indent to 4 spaces
- add skip ci condition
=> GitHub Actions: update Gradle wrapper validation

.github/workflows/angular.yml, generators/entity-server/templates/src/main/java/package/service/dto/EntityDTO.java.ejs, generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs, generators/entity-server/templates/src/test/java/package/service/dto/EntityDTOTest.java.ejs, generators/entity-server/templates/src/test/java/package/service/mapper/EntityMapperTest.java.ejs, generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs, generators/generator-base-private.js, generators/generator-base.js
=> Refactor type detection in DTO test

package-lock.json, package.json
=> Update yeoman-generator to 4.5.0

generators/generator-constants.js
=> Update npm version to 6.13.7

generators/generator-constants.js
=> Upgrade to jhipster-registry v6.1.0

generators/generator-constants.js
=> Update JIB version to 2.0.0

generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs, generators/entity-server/templates/src/main/java/package/domain/imports.ejs, generators/entity-server/templates/src/main/java/package/repository/EntityRepository.java.ejs, generators/entity-server/templates/src/main/java/package/repository/reactive/EntityReactiveRepository.java.ejs, generators/entity-server/templates/src/main/java/package/repository/search/EntitySearchRepository.java.ejs, generators/entity-server/templates/src/main/java/package/service/EntityQueryService.java.ejs, generators/entity-server/templates/src/main/java/package/service/EntityService.java.ejs, generators/entity-server/templates/src/main/java/package/service/dto/EntityDTO.java.ejs, generators/entity-server/templates/src/main/java/package/service/impl/EntityServiceImpl.java.ejs, generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs, generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs, generators/server/templates/src/main/java/package/web/rest/AccountResource.java.ejs
=> Fix blank lines and polish entity server templates

.github/workflows/gradle-wrapper-validation.yml, README.md
=> npm run lint-fix fixes

.github/workflows/react.yml, generators/client/templates/react/src/main/webapp/app/shared/layout/menus/entities.tsx.ejs, generators/client/templates/react/src/test/javascript/e2e/util/utils.ts.ejs, generators/client/templates/react/src/test/javascript/protractor.conf.js.ejs, generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs, generators/entity-client/templates/react/src/test/javascript/e2e/entities/entity-page-object.ts.ejs, generators/entity-client/templates/react/src/test/javascript/e2e/entities/entity.spec.ts.ejs
- Fixes protractor flaky tests
- Related to #10824 
----
=> Fix react e2e tests

generators/kubernetes/templates/db/postgresql.yml.ejs
=> fix k8s mount-path config for psql, fix #11184

generators/server/templates/src/main/java/package/security/oauth2/AudienceValidator.java.ejs, generators/server/templates/src/main/java/package/web/rest/LogoutResource.java.ejs, generators/server/templates/src/test/java/package/repository/CustomAuditEventRepositoryIT.java.ejs, generators/server/templates/src/test/java/package/security/oauth2/AudienceValidatorTest.java.ejs, generators/server/templates/src/test/java/package/web/rest/LogoutResourceIT.java.ejs
=> Some improvements (imports, final, variables)

generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs, generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
=> Fix many to many user with oauth and microservice

generators/entity-server/templates/src/main/java/package/service/mapper/EntityMapper.java.ejs
=> Add map method for UUID and byte[]

generators/server/templates/gradle.properties.ejs, generators/server/templates/pom.xml.ejs
=> Upgrade jhipster dependencies to 3.4.0

generators/server/templates/src/main/java/package/web/filter/RefreshTokenFilter.java.ejs
Reverts jhipster/generator-jhipster#11149
Related to https://github.com/jhipster/generator-jhipster/issues/11236
This doesn't seem to fix the problem and therefore I am reverting it. 😢
=> Revert "Increase Number of Seconds to Expiry of Access Tokens to 90 Seconds"

generators/server/templates/src/main/resources/config/liquibase/changelog/initial_schema.xml.ejs
=> Fixes initial schema creation fails with Oracle 18c XE

generators/entity-server/templates/src/main/java/package/service/EntityService.java.ejs, generators/entity-server/templates/src/main/java/package/service/impl/EntityServiceImpl.java.ejs
=> remove extra-line in entity service and entity service impl

.github/workflows/react.yml
Following https://github.com/jhipster/generator-jhipster/pull/11207
_____
=> CI: fix react build with missing webpack profile

generators/docker-base.js
Based on [this](https://github.com/jhipster/generator-jhipster/pull/11038#discussion_r366267205) discussion 
-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green 🤞
=> fix: getAllJHipsterConfig to force config search based on path

generators/app/index.js, test/blueprint/multiple-app-blueprints.spec.js
Proof of concept and fix for https://github.com/jhipster/generator-jhipster/issues/11142
=> Fix App Blueprint conflicts with multiples blueprints.

generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management.tsx.ejs
use `userManagement.activated` and `userManagement.deactivated` for the activation button in react.
=> fix: use activated translation

generators/gae/index.js, generators/gae/templates/pom-gae-build-profile.xml.ejs
Fixes https://github.com/jhipster/generator-jhipster/issues/11253
=> Add Prod Profile to GAE Deployment Command

generators/server/templates/build.gradle.ejs, generators/server/templates/pom.xml.ejs, generators/server/templates/src/test/java/package/AbstractCassandraTest.java.ejs, generators/server/templates/src/test/java/package/CassandraKeyspaceIT.java.ejs, generators/server/templates/src/test/resources/config/application.yml.ejs
Reverts jhipster/generator-jhipster#11256
I am reverting this back for the moment since starting from this it seems to introduce the cassandra failures again. Will do more investigation on the possibility of removing this dependency. :smile:
=> Revert "refactor: remove cassandra unit"

.github/workflows/angular.yml, .github/workflows/react.yml, azure-pipelines.yml
=> Switch to master branch of jhipster dependencies

generators/generator-base.js
=> Remove Skip Tests for Cloud Sub-Generators; AWS, Azure, CloudFoundry and Heroku

generators/client/needle-api/needle-client-angular.js
=> Improve regex in addIcon() method to handle edge cases

generators/generator-base-private.js
=> Fix in generator-base-private.js 

generators/languages/templates/src/main/webapp/i18n/fr/global.json.ejs
=> Fix french translations

generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs
=> Fix issue #11222 : react in a few scenarios, the entity list page can invoke up to 4 calls to the backend API #11222

README.md
Following https://github.com/jhipster/jhipster.github.io/pull/894
=> Add new Bronze Sponsor: MiniTool [skip ci]

.github/workflows/react.yml, azure-pipelines.yml
=> ci: Enable e2e tests in react workflows

generators/kubernetes/templates/db/postgresql.yml.ejs
=> change subMount to subPath

generators/kubernetes/templates/db/elasticsearch.yml.ejs
There is no issue, but a running discussion on the group about this issue. I accidentally copied the claim configuration from MariaDB and forgot to change it to the proper PVC
=> fix k8s elasticsearch pvc pick in deployment

generators/client/needle-api/needle-client-angular.js, generators/generator-base.js, test/needle-api/needle-client-angular.spec.js
=> Add admin routing needle function

generators/entity-client/files.js
Refactor writeClientFiles.
https://github.com/jhipster/generator-jhipster/pull/11239#discussion_r377791008
=> Refactor entity-client's writeClientFiles

generators/kubernetes/templates/db/elasticsearch.yml.ejs
=> Fix ElasticSearch on Kubernetes

generators/client/templates/react/src/test/javascript/e2e/modules/account/account.spec.ts.ejs
=> react (e2e): wait for the settings page title to be displayed before trying assertion

package-lock.json, package.json
=> Update yeoman-environment to 2.8.0

generators/server/templates/src/main/java/package/config/CacheConfiguration.java.ejs
=> Update CacheConfiguration.java.ejs - Fix violation of [ant:checkstyle] [NoHttp] rule

generators/generator-constants.js
Linked issues: https://github.com/jhipster/generator-jhipster/issues/11324
-   [x ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
=> k8s: update apiVersion for Ingress object type

.github/workflows/angular.yml, .github/workflows/generator.yml, .github/workflows/react.yml, Dockerfile, azure-pipelines.yml, generators/generator-constants.js
=> Upgrade to Node.js 12.16.0 LTS

generators/kubernetes-knative/index.js, generators/kubernetes-knative/templates/README-KUBERNETES-KNATIVE.md.ejs
=> update readme doc - knative [skip ci]

README.md
Add badge to readme for newly added Windows build. :smile:  
=> Add Windows Official Badge to Readme [skip ci]

.github/workflows/angular.yml, .github/workflows/generator.yml, .github/workflows/gradle-wrapper-validation.yml, .github/workflows/react.yml, generators/ci-cd/templates/github-ci.yml.ejs
This corrects a mistake I've made in https://github.com/jhipster/generator-jhipster/pull/11304
=> Correct Mistake in Adding Support for [skip ci] in GitHub Actions

azure-pipelines.yml
Related to https://github.com/jhipster/generator-jhipster/pull/11335
=> Revert Attempt to Stop Azure Pipeline Builds from Running on PRs

.github/workflows/triage.yml
=> Update GitHub Triage Issues Action

generators/kubernetes/templates/registry/consul.yml.ejs
=> patch update for #11038

generators/cleanup.js
Fixes https://github.com/jhipster/generator-jhipster/issues/11347
=> Fix upgrade

.github/workflows/label-cleanup.yml
=> Add Workflow to Cleanup Labels [skip ci]

generators/entity-server/templates/src/main/java/package/common/save_template.ejs
=> Use java bean method when fluent method is not available

generators/entity-server/index.js, generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
remove no longer necessary boilerplate in IT tests, use JUnit 5 annotations
=> cleanup entity integration tests template

cli/commands.js, generators/upgrade-config/USAGE, generators/upgrade-config/index.js, generators/upgrade/index.js, test/upgrade-config/blueprint-config-conflict-abort.spec.js, test/upgrade-config/blueprint-config-conflict-choice.spec.js, test/upgrade-config/blueprint-config-conflict-ignore.spec.js, test/upgrade-config/blueprint-config.spec.js
Implement upgrade path for https://github.com/jhipster/generator-jhipster/issues/10663
=> Add support to unifying blueprint config on upgrade

generators/entity-client/templates/react/src/main/webapp/app/entities/enumerations/enum.model.ts.ejs
=> Always define string enum for React

cli/import-jdl.js, generators/export-jdl/index.js, package-lock.json, package.json
=> update jhipster core to 7.0.0

cli/import-jdl.js, test/cli/import-jdl.spec.js
Forward creationTimestamp option to jhipster-core.
Needed for https://github.com/jhipster/jhipster-core/pull/409
=> Reproducible jdl

generators/generator-base-private.js, generators/generator-base.js, generators/upgrade/index.js, test/upgrade.spec.js
- Remove all callbacks. Upgrade is much more understandable now.
=> Upgrade cleanup

generators/generator-base-private.js, generators/generator-base.js
Import and use debug package so `npm test` can be easily debugged.
=> Use debug package

generators/generator-base-private.js
=> Fix warning call

generators/server/templates/build.gradle.ejs, generators/server/templates/gradle.properties.ejs, generators/server/templates/pom.xml.ejs
Using neo4j and testcontainers managed version from jhipster bom
=> use managed versions for neo4j dependencies

test-integration/samples/README.md, test-integration/samples/ngx-neo4j/.yo-rc.json, test-integration/scripts/11-generate-entities.sh
Just the samples. Test will be done in daily builds (except we have capacity left or can remove another configuration).
=> add neo4j to sample store

generators/client/files-angular.js, generators/client/files-react.js, generators/client/templates/angular/src/main/webapp/app/admin/docs/docs.scss.ejs, generators/client/templates/react/src/main/webapp/app/modules/administration/docs/docs.scss.ejs, test/utils/expected-files.js
Fixes #11330 
This just sets the background of the iframe in which swagger is displayed to white for every theme.
This improves readability in dark themes a lot and should not notably interfere with light themes (tested default and darkly)
=> Fix readability for swagger-ui with dark themes

generators/server/files.js
Following this https://github.com/jhipster/generator-jhipster/pull/11069
Stupid from me.
Currenty we have:
```html
<!DOCTYPE html>
<html lang="<% if (enableTranslation) { %><%= nativeLanguage %><% } else { %>en<% } %>">
<head>
```
With this fix, we'll have:
```html
<!DOCTYPE html>
<html lang="en">
<head>
```
=> Fix template index.html for microservices

generators/server/templates/src/main/resources/config/application-dev.yml.ejs, generators/server/templates/src/main/resources/config/application-prod.yml.ejs
As we didn't use Spring Kafka anymore, it needs to be clean.
cc @ctamisier @fdelbrayelle 
_____
=> Clean Kafka configuration with old Spring Kafka

.github/workflows/angular.yml, .github/workflows/generator.yml, .github/workflows/react.yml, generators/azure-app-service/templates/github/workflows/azure-app-service.yml.ejs, generators/azure-spring-cloud/templates/github/workflows/azure-spring-cloud.yml.ejs, generators/ci-cd/templates/github-ci.yml.ejs
=> Upgrade actions/checkout to v2

generators/server/templates/src/test/java/package/web/rest/AccountResourceIT.java.ejs, generators/server/templates/src/test/java/package/web/rest/UserJWTControllerIT.java.ejs
=> Remove passwordEncoder with no db

package-lock.json, package.json
=> Update yeoman-generator to 4.6.0 and yeoman-test to 2.2.0

generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs, generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity_constraints.xml.ejs, generators/server/templates/build.gradle.ejs, generators/server/templates/gradle.properties.ejs, generators/server/templates/pom.xml.ejs, generators/server/templates/src/main/resources/config/liquibase/changelog/initial_schema.xml.ejs, generators/server/templates/src/main/resources/config/liquibase/master.xml.ejs, test/needle-api/templates/src/main/resources/config/liquibase/changelog/dummy_changelog.xml.ejs
See:
- https://github.com/liquibase/liquibase-hibernate/issues/222
- https://github.com/liquibase/liquibase/pull/927
---
=> Update Liquibase version to 3.8.7

generators/ci-cd/index.js, generators/ci-cd/templates/.gitlab-ci.yml.ejs, generators/ci-cd/templates/github-ci.yml.ejs, generators/client/index.js, generators/common/index.js, generators/common/templates/README.md.ejs
=> Use SUPPORTED_CLIENT_FRAMEWORKS in templates

generators/entity-server/index.js, generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity.xml.ejs, generators/entity-server/templates/src/main/resources/config/liquibase/changelog/added_entity_constraints.xml.ejs, generators/generator-constants.js, generators/server/index.js, generators/server/templates/build.gradle.ejs, generators/server/templates/pom.xml.ejs, generators/server/templates/src/main/resources/config/liquibase/changelog/initial_schema.xml.ejs, generators/server/templates/src/main/resources/config/liquibase/master.xml.ejs
This should ease future updates
=> Use constants for liquibase version and liquibase DTD version

generators/server/templates/gradle/docker.gradle.ejs, generators/server/templates/pom.xml.ejs
=> Fix Jib permissions to entrypoint

generators/server/templates/src/main/resources/config/application.yml.ejs
=> Simplify hazelcast logic in application.yml template

generators/server/templates/gradle/docker.gradle.ejs
=> Fix gradle definition for JIB

generators/generator-constants.js
=> Update npm version to 6.14.2

cli/cli.js, cli/utils.js, generators/client/files-angular.js, generators/client/files-react.js, generators/client/index.js, generators/client/needle-api/needle-client-angular.js, generators/client/needle-api/needle-client-i18n.js, generators/client/needle-api/needle-client-react.js, generators/client/needle-api/needle-client.js, generators/common/index.js, generators/entity/index.js, generators/generator-base-private.js, generators/generator-base.js, generators/languages/index.js, generators/server/index.js, generators/utils.js, test/app-client-custom-path.spec.js, test/blueprint/client-blueprint-custom-path.spec.js, test/cli/cli.spec.js, test/templates/blueprint-cli-shared/cli/sharedOptions.js, test/templates/blueprint-cli-shared/generators/foo/index.js, test/templates/blueprint-cli-shared/package.json, test/templates/blueprint-cli/cli/sharedOptions.js, test/templates/blueprint-cli/generators/foo/index.js, test/utils/utils.js
Fixes https://github.com/jhipster/generator-jhipster/issues/9960
=> Implement output path customizer

.github/workflows/angular.yml, .github/workflows/generator.yml, .github/workflows/react.yml, Dockerfile, azure-pipelines.yml, generators/generator-constants.js
=> Upgrade to Node.js 12.16.1 LTS

generators/app/index.js, generators/common/templates/.prettierrc.ejs, generators/generator-base-private.js, package-lock.json, package.json, test/app.spec.js
1st step for https://github.com/jhipster/generator-jhipster/issues/10641
@murdos : thanks for pointing me in my other PRs. After our lunch yesterday, I gave a try and you're right: it was easier than expected !
I don't think it's a breaking change here as I didn't introduce the hook with Java, only for our generated code. So we won't change the custom code of our users.
What do you think ?
cc @hdurix @murdos @clementdessoude @Shaolans @Hawkurane @jdubois 
cc @jhipster/developers too
_____
-   [ ] Coding Rules & Commit …
=> Use prettier-java for preformatting before writing disk

package-lock.json, package.json
=> Updated the JCore dep to v7.1.1

generators/generator-base-blueprint.js, generators/generator-base-private.js, generators/generator-base.js, test/blueprint/client-blueprint-custom-path.spec.js, test/blueprint/client-blueprint.spec.js, test/blueprint/common-blueprint.spec.js, test/blueprint/entity-blueprint.spec.js, test/blueprint/entity-client-blueprint.spec.js, test/blueprint/entity-i18n-blueprint.spec.js, test/blueprint/entity-server-blueprint.spec.js, test/blueprint/languages-blueprint.spec.js, test/blueprint/sbs-blueprint.spec.js, test/blueprint/server-blueprint.spec.js, test/blueprint/spring-controller-blueprint.spec.js, test/blueprint/spring-service-blueprint.spec.js, test/needle-api/needle-client-angular.spec.js, test/needle-api/needle-client-i18n.spec.js, test/needle-api/needle-client-react.spec.js, test/needle-api/needle-client-webpack.spec.js, test/needle-api/needle-client.spec.js, test/needle-api/needle-server-cache.spec.js, test/needle-api/needle-server-gradle.spec.js, test/needle-api/needle-server-liquibase.spec.js, test/needle-api/needle-server-logback-spring.spec.js, test/needle-api/needle-server-maven.spec.js, test/templates/fake-blueprint/generators/server/index.js
Fixes https://github.com/jhipster/generator-jhipster/issues/11173.
=> Implement side-by-side blueprints.

test/upgrade.spec.js
Path commit for https://github.com/jhipster/generator-jhipster/pull/11150
=> Pass upgradeConfig prompt option on test

generators/server/index.js
Fix https://github.com/jhipster/generator-jhipster/issues/11431
_____
=> Fix testsNeedCsrf variable

generators/ci-cd/templates/.gitlab-ci.yml.ejs, test/ci-cd.spec.js, test/templates/ci-cd/npm-skip-server/.yo-rc.json
See https://gitlab.com/pascalgrimaud/jhipster-sample-app-20200305/pipelines/123715209
Fix https://github.com/jhipster/generator-jhipster/issues/11274
_____
=> GitLab: fix skip server

generators/server/templates/src/main/java/package/config/CacheConfiguration.java.ejs
Fix https://github.com/jhipster/generator-jhipster/issues/11377
_____
=> Fix CacheConfiguration with memcached for Microservice

generators/client/templates/react/package.json.ejs
=> Upgrade to react-jhipster v0.10.0

.github/workflows/angular.yml, .github/workflows/react.yml, azure-pipelines.yml, generators/server/templates/gradle.properties.ejs, generators/server/templates/pom.xml.ejs
=> Upgrade jhipster dependencies 3.6.0

generators/generator-constants.js
=> Upgrade to JHipster Registry v6.1.2 [ci skip]

README.md
Fix https://github.com/jhipster/generator-jhipster/issues/11118
_____
=> Remove dependency badge [ci skip]

generators/entity-server/templates/src/main/java/package/repository/EntityRepository.java.ejs
Trying to fix https://dev.azure.com/hipster-labs/jhipster-daily-builds/_build?definitionId=11&_a=summary
Related to https://github.com/hipster-labs/jhipster-daily-builds/pull/40#issuecomment-590312403
@atomfrede : I tried your project https://github.com/atomfrede/neo4j-jhipster-bank-sample but the integration tests failed. The test context is not correctly built. I don't have more time tonight to investigate
______ …
=> Neo4j: fix compilation with entities

generators/languages/prompts.js
=> Fix languages prompt.

azure-pipelines.yml, generators/entity-server/files.js, generators/entity-server/templates/src/main/java/package/common/delete_template.ejs, generators/entity-server/templates/src/main/java/package/common/get_all_template.ejs, generators/entity-server/templates/src/main/java/package/common/get_template.ejs, generators/entity-server/templates/src/main/java/package/common/inject_template.ejs, generators/entity-server/templates/src/main/java/package/common/save_reactive_template.ejs, generators/entity-server/templates/src/main/java/package/common/save_template.ejs, generators/entity-server/templates/src/main/java/package/repository/EntityReactiveRepository.java.ejs, generators/entity-server/templates/src/main/java/package/repository/EntityRepository.java.ejs, generators/entity-server/templates/src/main/java/package/service/EntityService.java.ejs, generators/entity-server/templates/src/main/java/package/service/impl/EntityServiceImpl.java.ejs, generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs, generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs, generators/entity/index.js, test-integration/scripts/11-generate-entities.sh
=> Support for reactive applications in entity subgenerator

generators/azure-spring-cloud/index.js
=> Improve Gradle support for Azure Spring Cloud

generators/ci-cd/templates/.gitlab-ci.yml.ejs, generators/client/templates/angular/package.json.ejs, generators/client/templates/react/package.json.ejs
Related issue #11274 
Related PR #11438
=> GitLab-ci: add sonar-analyze stage for skipServer option

generators/upgrade/index.js
Fix https://github.com/jhipster/generator-jhipster/issues/11465.
I didn't test. I will test later.
Created the concept.
=> Convert files to absolute before removing.

.github/workflows/angular.yml, .github/workflows/react.yml, azure-pipelines.yml, generators/server/templates/gradle.properties.ejs, generators/server/templates/pom.xml.ejs
=> Upgrade jhipster dependencies 3.7.0 snapshot

generators/info/index.js
It's to avoid some manual replace like:
```
"jwtSecretKey": "***********************************************"
```
```yaml
{
"packageName": "com.apprik.myapp",
"nativeLanguage": "en"
},
"jhipsterVersion": "6.8.0",
"applicationType": "monolith",
"baseName": "myapp",
"packageName": "com.apprik.myapp",
"packageFolder": "com/apprik/myapp",
"authenticationType": "jwt",
"cacheProvider": "ehcache",
"enableHibernateCache": true,
"websocket": false,
"devDatabaseType": "h2Disk",
"prodDatabaseType": "postgresql",
"searchEngine": false,
"messageBroker": false,
"serviceDiscoveryType": false,
"buildTool": "maven",
"enableSwaggerCodegen": false,
"jwtSecretKey": "***********************************************", …
```
=> Replace the JWT Secret from jhipster info

generators/server/templates/src/main/java/package/repository/PersistenceAuditEventRepository.java.ejs, generators/server/templates/src/main/resources/logback-spring.xml.ejs, generators/server/templates/src/test/java/package/security/DomainUserDetailsServiceIT.java.ejs
=> Fix r2dbc following review

generators/server/templates/src/main/java/package/repository/UserRepository.java.ejs
=> Move 'if' to include @Cacheable

generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs
Fix #10743
I applied the fix as suggested in the issue and is working fine.
=> Fix Bad Request: JSON parse error

generators/server/templates/src/main/java/package/web/rest/UserJWTController.java.ejs
=> Disable audit with Cassandra

generators/server/templates/pom.xml.ejs
=> Fix executable war and support JDK 14

generators/entity/index.js, generators/generator-base-private.js, generators/generator-base.js, test/generator-base.spec.js
=> Enable prettier for .jhipster/* and use this.fs for read and verify.

generators/cleanup.js
=> Clean reactive resolver files

generators/server/templates/src/test/resources/config/application.yml.ejs
=> Don't format test logs to Json

generators/common/templates/gitignore.ejs
=> Refine format and correct the spelling of IntelliJ

generators/entity/index.js
=> null check on otherEntityRelationshipName

generators/client/files-angular.js, generators/client/templates/angular/src/test/javascript/spec/app/core/login/login-modal.service.spec.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/app/home/home.component.spec.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/app/layouts/navbar/navbar.component.spec.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/app/shared/alert/alert.component.spec.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/helpers/mock-account.service.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/helpers/mock-login-modal.service.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/test.module.ts.ejs, test/utils/expected-files.js
Add some front-end (angular) tests to improve code coverage
=> Front-end (angular) tests

generators/client/templates/angular/src/test/javascript/spec/app/core/login/login-modal.service.spec.ts.ejs
=> ngx: indent [ci skip]

generators/client/templates/angular/package.json.ejs, generators/client/templates/react/package.json.ejs, generators/server/templates/package.json.ejs, package-lock.json, package.json
First time filing a PR to update openapi-generator-cli to a newer version. Please let me know if there's anything missing.
=> Update openapi-generator-cli to 1.0.12-4.3.0

generators/server/templates/src/main/resources/config/application.yml.ejs
When using Consul `serviceDiscoveryType` with a reactive gateway, the generated YML file contains duplicate "cloud" keys, causing prettier to fail.
Reported on gitter by @werwuifi with `.yo-rc.json`:
<details>
<summary>.yo-rc.json file</summary>
<pre>
{
"packageName": "com.mycompany.myapp",
"nativeLanguage": "de"
},
"jhipsterVersion": "6.8.0",
"applicationType": "gateway",
"baseName": "gateway",
"packageName": "com.mycompany.myapp",
"packageFolder": "com/mycompany/myapp",
"authenticationType": "oauth2",
"cacheProvider": "no",
"enableHibernateCache": false,
"websocket": false,
"databaseType": "couchbase",
"devDatabaseType": "couchbase",
"prodDatabaseType": "couchbase",
"searchEngine": false,
"messageBroker": "kafka", …
=> fix duplicate cloud key in yml

generators/entity-server/templates/src/main/java/package/service/dto/EntityDTO.java.ejs
=> Align equals/hashcode implementation of DTOs and entities

test/templates/compose/04-mongo/src/main/docker/mongodb-cluster.yml
Fix version config server mongodb in integration test template
-   [X ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
=>  patch(fix-11519) - fix config server mongodb version 

generators/server/files.js, generators/server/templates/build.gradle.ejs, generators/server/templates/pom.xml.ejs, generators/server/templates/src/main/java/package/config/ReactorConfiguration.java.ejs, generators/server/templates/src/main/java/package/config/WebConfigurer.java.ejs, generators/server/templates/src/main/java/package/security/jwt/TokenProvider.java.ejs, generators/server/templates/src/main/java/package/service/UserService.java.ejs, generators/server/templates/src/main/java/package/web/rest/UserJWTController.java.ejs
=> Add Hooks.onOperatorDebug() and BlockHound to reactive apps

README.md
=> Update badges for daily-builds in main generator's readme

generators/server/templates/src/test/java/package/web/rest/KafkaResourceIT.java.ejs
Following https://github.com/jhipster/generator-jhipster/issues/11544#issuecomment-609065206
_____
=> Kafka: start testcontainers without NetWork

generators/azure-spring-cloud/templates/pom-profile.xml.ejs
This is automatically management by the JHipster BOM
=> Do not fix the Azure Spring Cloud dependency version

.github/workflows/webflux.yml, README.md, azure-pipelines.yml
=> CI: move Webflux builds from Azure to GitHub Actions

README.md
=> Fix Webflux badge [ci skip]

generators/generator-base.js, generators/utils.js, package-lock.json, package.json
Following https://github.com/jhipster/jhipster-dotnetcore/issues/57
=> Fixes to output customizer.

generators/server/templates/src/test/resources/logback.xml.ejs
It's to avoid having something like that:
```
2020-04-05T21:50:38.5379127Z [INFO] -------------------------------------------------------
2020-04-05T21:50:38.5381699Z [INFO]  T E S T S
2020-04-05T21:50:38.5386750Z [INFO] -------------------------------------------------------
2020-04-05T21:50:40.3980445Z 2020-04-05 21:50:40.389 DEBUG   --- [           main] com.tngtech.archunit.ArchConfiguration   : No configuration found in classpath at archunit.properties => Using default configuration
2020-04-05T21:50:40.9334327Z [INFO] Running io.github.jhipster.sample.ArchTest
2020-04-05T21:50:41.0252566Z 2020-04-05 21:50:41.023  INFO   --- [           main] com.tngtech.archunit.core.PluginLoader   : Detected Java version 11.0.6
2020-04-05T21:50:41.0312878Z 2020-04-05 21:50:41.025 DEBUG   --- [ …
```
=> Reduce logs output for ArchTest

package-lock.json, package.json
=> Bump yeoman-test to 2.4.1 and yeoman-generator to 4.8.0

generators/client/templates/angular/src/main/webapp/app/admin/audits/audits.component.ts.ejs, generators/client/templates/angular/src/main/webapp/app/admin/user-management/user-management.component.ts.ejs, generators/client/templates/angular/src/test/javascript/spec/app/admin/audits/audits.component.spec.ts.ejs, generators/client/templates/react/src/main/webapp/app/modules/administration/audits/audits.tsx.ejs, generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management.tsx.ejs, generators/client/templates/react/src/main/webapp/app/shared/util/entity-utils.ts.ejs, generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.ts.ejs, generators/entity-client/templates/angular/src/main/webapp/app/entities/pagination-template.ejs, generators/entity-client/templates/angular/src/test/javascript/spec/app/entities/entity-management.component.spec.ts.ejs, generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs
Fix #11455
In this PR: 
-   [x] React: pagination not working on history back/forward
-   [x] React: if you refresh on a page greater than 1, it does not reset the page with the good parameter
-   [x] Angular: pagination not working on history back/forward
Checks:
=> Fix: Pagination not working on history back/forward

package-lock.json, package.json
=> Bump yeoman-environment to 2.9.0

generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs
=> Remove unnecessary throws exception in reactive entity integration tests

generators/server/templates/build.gradle.ejs, generators/server/templates/src/main/java/package/config/DatabaseConfiguration.java.ejs
Specific configuration was required for Spring Repositories in order to exclude Elasticsearch repositories from scan of Couchbase repositories
=> Fix usage of both Couchbase and Elasticsearch

generators/server/templates/src/test/java/package/config/DatabaseConfigurationIT.java.ejs
This is related to https://github.com/jhipster/jhipster/pull/662. Due to some api changes on the Couchbase module we have to alter the DatabaseConfiguration tests.
Fixes https://github.com/hipster-labs/jhipster-daily-builds/issues/46
=> Upgrade TestContainers to version 1.14.0

generators/server/templates/pom.xml.ejs
=> Allow to use TLS in prod mode

package-lock.json, package.json
=> Bump yeoman-environment to 2.9.3 and yeoman-generator to 4.8.2

test-cla.txt
This is to test our newly setup CLA
=> testing the CLA

test-cla.txt
=> remove test cla file

generators/generator-base-private.js
=> Remove warning when blueprint is compatible with generator-jhipster

cli/utils.js
Fixes https://github.com/jhipster/generator-jhipster/issues/11617
=> Don't run lookup without blueprints.

package-lock.json, package.json
=> Bump yeoman-environment to 2.9.5 and yeoman-generator to 4.8.3

generators/server/files.js
According to:
https://github.com/jhipster/generator-jhipster/blob/0006be4c84d58b4f40eeab4626845af5ce80aa53/generators/server/templates/src/main/java/package/web/rest/UserJWTController.java.ejs#L20
AuditEventService should be added to neo4j.
AuthorityRepository too:
https://github.com/jhipster/generator-jhipster/blob/e5c143d3c3c2a4415d57056f3f3424f71406f4ae/generators/server/templates/src/test/java/package/web/rest/AccountResourceIT.java.ejs#L364-L367 …
=> Enable audit service for neo4j

generators/entity/index.js
Related to https://github.com/jhipster/generator-jhipster/issues/11520
=> Fix otherEntityRelationshipName initialization

README.md
=> add manwoman bronze sponsor

generators/server/templates/src/main/java/package/config/CacheConfiguration.java.ejs
=> add JBossUserMarshaller to infinispan configuration

generators/generator-constants.js, generators/server/index.js, generators/server/templates/build.gradle.ejs, generators/server/templates/gradle.properties.ejs, generators/server/templates/pom.xml.ejs
This way they don't need to be updated in Maven and Gradle build configuration for each update
=> New constants for SpringBoot and JHipster lib versions + snapshots repository for jhipster lib

generators/server/templates/build.gradle.ejs, generators/server/templates/pom.xml.ejs, generators/server/templates/src/main/java/package/config/DatabaseConfiguration.java.ejs
Fixes https://github.com/jhipster/jhipster/pull/678
=> Fix following update to Couchmove 2.0
