app/index.js
sessionsControllerSpec.js was being copied in for token based authentication, causing 'grunt test' and 'gulp test' to have a failure.
=> sessionsControllerSpec.js is for cookie-based auth.

app/templates/src/main/java/package/domain/_User.java, app/templates/src/main/java/package/web/rest/dto/_UserDTO.java, app/templates/src/test/java/package/web/rest/_AccountResourceTest.java
This PR does the following:
* Adds tests for user registration API (one of them correctly fails, more below)
* Adds bean validation annotations to the user registration DTO (reasons below)
After I wrote the tests initially, two tests failed which are for the following scenarios:
1. Sending an anonymous registration request with `roles=['ROLE_ADMIN']` works, I wanted to get feedback before fixing this test. IMHO the simplest fix is to simply remove `roles` from the DTO and hardcode it as `['ROLE_USER']` as I believe the `/register` endpoint isn't meant for admin registrations. This should be very simply to adjust and I can include it in the PR, it will probably mean I will remove that relevant test altogether since it won't be possible to pass a different role.
2. Saving with **invalid …
=> User registration API tweaks & tests

app/index.js, app/templates/_build.gradle, app/templates/_gradle.properties
Cleanup of a few small issues I encountered when updating a jhipster project. 
* liquibase.gradle is not needed for NoSQL projects
* javax.transaction is needed by AccountResourceTest.java 
* I have added javax.transaction as a **compile** dependency, but perhaps **testCompile** would be more appropriate?
=> Cleanup a few small items.

app/templates/_pom.xml
Note that this will add 7 seconds to the startup time when starting the server with `mvn spring-boot:run`
=> Added yeoman-maven-plugin execution of grunt compass:server task to dev profile, fixes #952

app/templates/_package.json, app/templates/gulpfile.js
Following #960, this renames `gulp server` to `gulp serve`, executing gulp server still works but prints a deprecation note.
Fixes #985
=> Rename gulp server task to gulp serve

app/templates/gulpfile.js
In particular, not all view files were being bundled in the resulting production WAR
Fixes #994
=> Fix gulp build when used in production profile

app/index.js, app/templates/Gruntfile.js, app/templates/_package.json, app/templates/gulpfile.js, app/templates/src/main/scss/main.scss, app/templates/src/main/webapp/_index.html, app/templates/src/test/javascript/_karma.conf.js
Solution was copied from [generator-angular](https://github.com/yeoman/generator-angular) project.
Instead of letting the yeoman generator append the script tags to the index.html file it is now done by wiredep.
After these changes there is no need to manually add the `<script>`-tags to `index.html`after installing bower packages with `bower install --save packagename`. it is now done automatically with the `grunt wiredep` task wich is configured to run on `grunt serve`.
=> Configured wiredep to inject the vendor assets into index.html, fixes #956

app/index.js, app/templates/src/main/java/package/config/_SecurityConfiguration.java, app/templates/src/main/java/package/config/_XAuthConfiguration.java, app/templates/src/main/java/package/security/_AuthenticationProvider.java, app/templates/src/main/java/package/security/xauth/_Token.java, app/templates/src/main/java/package/security/xauth/_TokenProvider.java, app/templates/src/main/java/package/security/xauth/_UserXAuthTokenController.java, app/templates/src/main/java/package/security/xauth/_XAuthTokenConfigurer.java, app/templates/src/main/java/package/security/xauth/_XAuthTokenFilter.java, app/templates/src/main/resources/config/_application.yml, app/templates/src/main/webapp/scripts/app/_app.js, app/templates/src/main/webapp/scripts/components/auth/provider/_auth.xauth.service.js, app/templates/src/main/webapp/swagger-ui/_index.html, app/templates/src/test/javascript/spec/components/auth/_authServicesSpec.js
X-Auth-Token implementation to enable stateless configuration of jhipster.
Switching between the generator options is done explicitely (as shown below) for better code understanding (cookie/token/xauth).
> if (this.authenticationType == 'cookie' || this.authenticationType == 'token')
is more explicit than
> if (this.authenticationType != 'xauth')
For more clarity, 'token' could also be renamed to 'oauth2'
Implement #892
=> Add support for x-auth-token

app/templates/_package.json, app/templates/gulpfile.js
@andidev mentioend in #1010 that the development ribbon makes it to gulp production builds, this PR fixes that.
=> Gulp: Do not show development ribbon in production

app/templates/_liquibase.gradle
excludeObjects is a parameter for diffChangelog so it must be used after diffChangelog
Fix #1021
=> Change order of liquibase exludeObjects parameter

app/templates/src/main/webapp/scripts/app/_app.js
The initialization was matching /rest old mapping for REST API that has been replaced by /api.
=> Fixed cache buster interceptor matcher to '/api'

app/templates/src/test/javascript/spec/app/account/password/_passwordDirectiveSpec.js, app/templates/src/test/javascript/spec/components/auth/_authServicesSpec.js
Now that the cache buster is enabled on /api, the specs should expect requests to API to use cacheBuster query parameter.
Fix PR #1033
=> Fix tests for issue in PR 1033

entity/templates/src/main/webapp/app/_entities.html
ui-sref on entities ids are generated with wrong controller name, a 'Details' is added instead of 'Detail'
=> Issue on ui-sref for ControllerDetail ref

app/templates/src/main/java/package/config/_DatabaseConfiguration.java
When H2 database is configured and fast profile is active, run liquibase but warn the user about this sub optimal combination.
Fix #1042
=>   Fast profile should not disable liquibase when using H2

app/templates/_build.gradle, app/templates/_profile_prod.gradle, app/templates/_yeoman.gradle
The production profile uses gulp instead of grunt when configured to use gulp as frontend builder.
Update #1059
=> Fix gradle and gulp integration

app/templates/src/main/java/package/repository/_CustomAuditEventRepository.java
If the ```CustomAuditEventRepository``` reuses a transaction that is marked for rollback then the ```AuditEvent``` is never saved. The solution is to annotate ```add()``` with:
```
@Transactional(propagation = Propagation.REQUIRES_NEW)
```
=> Use new transaction when saving AuditEvent to prevent rollback

entity/index.js, entity/templates/src/main/java/package/domain/_Entity.java, entity/templates/src/main/java/package/repository/_EntityRepository.java, entity/templates/src/main/resources/config/liquibase/changelog/_added_entity.xml, entity/templates/src/main/webapp/app/_entities.html, entity/templates/src/main/webapp/app/_entity-controller.js, entity/templates/src/main/webapp/app/_entity-detail-controller.js, entity/templates/src/main/webapp/app/_entity-detail.html, entity/templates/src/main/webapp/i18n/_entity_ca.json, entity/templates/src/main/webapp/i18n/_entity_da.json, entity/templates/src/main/webapp/i18n/_entity_de.json, entity/templates/src/main/webapp/i18n/_entity_en.json, entity/templates/src/main/webapp/i18n/_entity_es.json, entity/templates/src/main/webapp/i18n/_entity_fr.json, entity/templates/src/main/webapp/i18n/_entity_kr.json, entity/templates/src/main/webapp/i18n/_entity_pl.json, entity/templates/src/main/webapp/i18n/_entity_pt-br.json, entity/templates/src/main/webapp/i18n/_entity_pt-ru.json, entity/templates/src/main/webapp/i18n/_entity_pt-sv.json, entity/templates/src/main/webapp/i18n/_entity_pt-tr.json, entity/templates/src/main/webapp/i18n/_entity_pt-zh-tw.json
* add backward compatibility to the entity generator, so old .jhipster config files could be used,
* specifying join columns for join tables, so no guessing happens for column names
=> Revert of rollback #1072

app/templates/_package.json
This gets rid of warnings such as "npm WARN package.json jhipster@0.0.0 No repository field." and similar.
=> Add private flag to package.json

entity/index.js
Entity configuration filename is now built from its name with first letter capitalized as java class name.
Now building this name only once.
Fix #1122
=> Entity configuration filename with capitalized first letter

app/templates/src/main/webapp/scripts/app/_app.js, app/templates/src/main/webapp/scripts/app/account/activate/_activate.js, app/templates/src/main/webapp/scripts/app/account/login/_login.js, app/templates/src/main/webapp/scripts/app/account/password/_password.js, app/templates/src/main/webapp/scripts/app/account/register/_register.js, app/templates/src/main/webapp/scripts/app/account/sessions/_sessions.js, app/templates/src/main/webapp/scripts/app/account/settings/_settings.js, app/templates/src/main/webapp/scripts/app/admin/audits/_audits.js, app/templates/src/main/webapp/scripts/app/admin/configuration/_configuration.js, app/templates/src/main/webapp/scripts/app/admin/docs/_docs.js, app/templates/src/main/webapp/scripts/app/admin/health/_health.js, app/templates/src/main/webapp/scripts/app/admin/logs/_logs.js, app/templates/src/main/webapp/scripts/app/admin/metrics/_metrics.js, app/templates/src/main/webapp/scripts/app/error/_error.js, entity/templates/src/main/webapp/app/_entity.js
This is done by setting the `pageTitle` property of the state data to a translation key.
If this attribute is not found then the application name is used.
Future improvements:
- support parameters in translated titles
- service to change title programmatically
Fix #1056
=> Change window title according to current state/view.

app/templates/_pom.xml
Tested successfuly `mvn clean install -Pprod` in following configurations:
- grunt with compass
- gulp without compass
- gulp with compass
Fix #1146
=> Update yeoman-maven-plugin to 0.4 to use same mechanism for grunt and gulp

app/templates/_yeoman.gradle
Gradle's bower task now uses bower global command to remove dependency on local bower installed in project's node_modules directory.
This aligns Gradle on how jhipster yeoman generator and maven build work.
Fix PR #1142 for issue #1138
=> Gradle's bower task now uses bower global command

app/templates/src/main/webapp/scripts/app/admin/health/health.html
Issue:
For any health check which is failing the error message of the failing mail health check is shown.
If the mail health check is successful the error popup for other failing health checks will be empty.
=> Show the correct error message

app/templates/_build.gradle, app/templates/_gradle.properties, app/templates/_pom.xml
Should not impact the existing Java code as the `jassertj-core-java8` is only set when Java 8 is activated. Using the Java8 branch of assertJ enables specific assertions for `Optional` for instance.
=> Fix #1165: Use assertj-core-java8 on Java 8

app/templates/_profile_prod.gradle
This will be consistent with the way bower is handled. It also
solves an issue with `grunt build` stopping because of a warning.
Fix PR #1142 for issue #1138
=> Replace grunt plugin with command execution

app/templates/_yeoman.gradle
Fix bower integration on windows OS as otherwise it errors with a CreateProcess error=2 as it can't find file to launch
=> fix bower integration for windows os

entity/templates/src/main/java/package/domain/_Entity.java
Currently the generated hashCode method of the entities is not null safe. When a sql entity is created, and the hashCode method is called (for example, when adding it to a HashSet), the method throws a null pointer exception since the id field is not yet set.
To fix the issue I have changed the hashCode method to use the java Objects.hashCode helper method that by default is null safe. It is also slightly more readable.
I have also changed the equals method to use the Objects helper method to make it slightly more readable.
=> Fix null pointer issue in hashCode method

app/templates/_build.gradle, app/templates/_gradle.properties
I've update nearly all dependencies when using gradle. Where applicable I've left out the explicit version, so that the spring-boot gradle plugin picks up the ["blessed" version](http://docs.spring.io/spring-boot/docs/1.2.2.RELEASE/reference/htmlsingle/#appendix-dependency-versions] (same as using the version from the parent pom for maven). Nevertheless I kept the updated version in the properties for reference. When spring-boot doesn't have a supported version I've tried to use either the latest version, the one that is explicit mentioned in the pom file or the one matching the supported/blessed version (e.g. jackson is 2.4.5 for all artifacts of jackson).
=> Update gradle dependencies

app/templates/_pom.xml
when I run `mvn spring-boot:run`
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/tam/.m2/repository/org/slf4j/slf4j-log4j12/1.7.10/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/tam/.m2/repository/ch/qos/logback/logback-classic/1.1.2/logback-classic-1.1.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
SLF4J: Detected both log4j-over-slf4j.jar AND slf4j-log4j12.jar on the class path, preempting StackOverflowError. 
SLF4J: See also http://www.slf4j.org/codes.html#log4jDelegationLoop for more details.
Exception in thread "main" …
=> Cassandra - add slf4j-log4j12 exclusion

app/templates/gitignore
Ensuring that the gradle-wrapper jar is checked into git. 
From http://gradle.org/docs/current/dsl/org.gradle.api.tasks.wrapper.Wrapper.html : 
*Generates scripts (for *nix and windows) which allow you to build your project with Gradle, without having to install Gradle.*
*When a user executes a wrapper script the first time, the script downloads and installs the appropriate Gradle distribution and runs the build against this downloaded distribution. Any installed Gradle distribution is ignored when using the wrapper scripts.*
*The scripts generated by this task are intended to be committed to your version control system. This task also generates a small gradle-wrapper.jar bootstrap JAR file and properties file which should also be committed to your VCS. The scripts delegates to this JAR.*
=> Should not ignore the gradle wrapper. Needs to be checked into source control

app/index.js, app/templates/_build.gradle, app/templates/_settings.gradle
Because we don't specify a name in our gradle build file, it assumes the name of project is the name of the top-level folder
Our WAR file on the other hand does use the correct project name (provided by baseName through its config).
This fix generates a ```settings.gradle``` file that contains the project name (rootProject.name)
The war configuration becomes obsolete as both baseName and version have already been provided.removed completely.
war {
baseName = 'ixortalkconfigmgmt'
version =  '0.1-SNAPSHOT'
}
This avoid artifacts like ```workspace-0.1-SNAPSHOT*``` getting uploaded in maven repositories. (workspace being the default folder where each job is built)
=> using correct project name for all artifacts instead of gradle default

app/templates/_build.gradle
Due to multiple versions of net.sf.ehcache and com.codahale.metrics , a Gradle project could not be imported properly in Eclipse. PR fixes following issues :
Compilation errors after importing a Gradle project in Eclipse STS: 
- The method getConfiguration() from the type CacheManager is not visible	CacheConfiguration.java	/jHipster4/src/main/java/com/mycompany/myapp/config	line 57	Java Problem
- The method setMaxBytesLocalHeap(String) is undefined for the type Configuration	CacheConfiguration.java	/jHipster4/src/main/java/com/mycompany/myapp/config	line 57	Java Problem
Runtime errors when starting the application from Eclipse STS
```
[INFO] com.mycompany.myapp.Application - Starting Application on Davys-MacBook-Pro.local with PID 76718 (/Users/ddewaele/Projects/Ixor/jHipster4/bin started …
```
=> fixed gradle dependencies for both net.sf.ehcache and com.codahale.metrics

app/templates/_build.gradle
Cleanup gradle buildfile.
Don't copy project property into seperate ``profile`` property, which is not required (anymore).
=> Remove double if-else statement

heroku/index.js
Heroku build fails if account has multiple apps, by passing the --app parameter we can ensure Heroku knows which app we are talking about.
See https://github.com/jhipster/generator-jhipster/issues/1288
=> pass heroku app name with --app param to heroku

app/templates/gulpfile.js
I believe this ended up this way as support for `ngconstant` was implemented for grunt than ported to gulp.
Fixes #1294
=> Gulp: watch gulpfile.js not Gruntfile.js

.gitattributes, app/templates/gitattributes
Added *.pdf, *.eot, *.ttf, *.gzip and *.gz as extensions to treat as
binary when a generated project is checked into git.
=> Added more binary flags for git

app/templates/src/main/java/package/config/_SecurityConfiguration.java, app/templates/src/main/webapp/scripts/components/auth/provider/_auth.session.service.js, entity/templates/src/test/gatling/simulations/_EntityGatlingTest.scala
I'm not so familiar with this part of Spring Security, but with some debugging I found out that the remember-me form request parameter changed in Spring Security 4 from **_spring_security_remember_me** to **remember-me** 
I've changed the form parameter and explicitly set the parameter name in the SecurityConfiguration so if this changes again in the future it won't have impact anymore. Now the session screen seems to work again. 
Let me know if there are any other issues with this.
More information can be found here:
Docs: http://docs.spring.io/spring-security/site/migrate/current/3-to-4/html5/migrate-3-to-4-xml.html#m3to4-xmlnamespace-remember-me
GitHub: https://github.com/spring-projects/spring-security/commit/5f57e5b0c3726466db4f5d0521ac26423f0d9cd4)
=> change remember-me form request parameter to fix session login

app/templates/_gradle.properties, app/templates/_pom.xml
Update gatling and gatling maven to latest 2.1.5 release.
2.1.5 is not yet in maven central, but it should be available during the day: https://groups.google.com/forum/#!topic/gatling/BViFx0TqU0E
Fix #1344
=> Update gatling to latest version

app/templates/src/main/webapp/_index.html
I'm adding IE9 compatibility to the documentation. Therefore, I'm removing the "browserupgrade" message in the header when accessing the site with IE9.
I'm also removing the lt-ie7 lt-ie8 lt-ie9 classes. IE9 doesn't need any specific CSS rules, unlike IE7 and IE8 did.
=> IE9 compatibility

app/templates/src/main/webapp/scripts/app/account/password/password.html, app/templates/src/main/webapp/scripts/app/account/sessions/sessions.html, app/templates/src/main/webapp/scripts/app/account/settings/settings.html, entity/templates/src/main/webapp/i18n/_entity_pl.json
Title localization on 3 account pages didn't work because of "{{...}}" used in default texts inside &lt;h2&gt;&lt;/h2&gt; tags. Additionally localized pl-PL i18n template for a new entity.
=> Fix title l10n in some account pages

app/templates/src/main/resources/config/_application-dev.yml
Moved data folder for elasticsearch under "target" when using dev profile to be coherent with the volatile aspect of the data just like h2 mem usage, Otherwise we have desynchronization between ES and H2 unless you don't forget to delete the data/ folder in your project home.
=> Moved data folder for elasticsearch under "target" when using dev profile

app/templates/src/main/java/package/_Application.java
If a profile is already defined via environment variable the default profile is not added anymore.
Fix #1408
=> Don't add profile if already defined via environment

app/templates/src/main/java/package/config/_SecurityConfiguration.java
In case using ``oauth`` password reset endpoints are ignored by security configuration.
Fix #1478
=> password reset endpoints are ignore

app/templates/src/main/java/package/config/_DatabaseConfiguration.java
Hikari seems to have change it's guideline for optimal MySQL configuration.
Copied from the link : https://github.com/brettwooldridge/HikariCP/wiki/MySQL-Configuration
~~`useServerPrepStmts` : No longer recommended due to MySQL stability issues
Newer versions of MySQL support server-side prepared statements, this can provide a substantial performance boost. Set this property to true.~~
=> Removing property for MySQL datasource setup

app/templates/Gruntfile.js, app/templates/_pom.xml, heroku/USAGE, heroku/index.js, heroku/templates/_Procfile, heroku/templates/slugignore, heroku/templates/system.properties
This PR improves the existing Heroku generator by adding two new methods of deployment: Git-based and CLI-based. 
```
? Which method of deployment do you want ?
> CLI (recommended)
Git 
```
I will add support for Maven deployment in another PR. 
* Removed Heroku Grunt tasks in favor of "native" commands like `git push` and `heroku deploy`
* Added "heroku" profile to `pom.xml` to clean build artifacts from slug.
* Improved Git init to use root dir, and check for existing repo
* Added generator function to install CLI tool
* Separated `heroku create` into two commands for each deployment type
* Removed default JVM opts (Heroku picks good defaults based on dyno size)
* Removed `slugignore` and `system.properties` templates (not needed with new method)
* Use grunt-shell to wrap `heroku …
=> Improved Heroku generator

heroku/index.js
Deploying to heroku didn't work, because ``gradlew`` could not be found. I've also excluded tests from build command. Will update the documentation accordingly later.
=> Correct buildcommand for gradle during heroku deploy

heroku/index.js
This way, if the build fails, they can just retry and redeploy without running the generator again.
=> Move the Heroku deploy plugin install up in the order. 

app/index.js, app/templates/src/main/webapp/i18n/en/register.json, app/templates/src/main/webapp/scripts/app/account/activate/activate.html, app/templates/src/main/webapp/scripts/app/account/login/login.html, app/templates/src/main/webapp/scripts/app/account/password/password.html, app/templates/src/main/webapp/scripts/app/account/register/register.html, app/templates/src/main/webapp/scripts/app/account/reset/finish/reset.finish.html, app/templates/src/main/webapp/scripts/app/account/reset/request/reset.request.html, app/templates/src/main/webapp/scripts/app/account/sessions/sessions.html, app/templates/src/main/webapp/scripts/app/account/settings/settings.html, app/templates/src/main/webapp/scripts/app/admin/audits/_audits.controller.js, app/templates/src/main/webapp/scripts/app/admin/audits/audits.html, app/templates/src/main/webapp/scripts/app/admin/configuration/configuration.html, app/templates/src/main/webapp/scripts/app/admin/health/health.html, app/templates/src/main/webapp/scripts/app/admin/logs/logs.html, app/templates/src/main/webapp/scripts/app/admin/metrics/_metrics.html, app/templates/src/main/webapp/scripts/app/error/accessdenied.html, app/templates/src/main/webapp/scripts/app/error/error.html, app/templates/src/main/webapp/scripts/app/main/main.html, app/templates/src/main/webapp/scripts/components/navbar/navbar.html, entity/templates/src/main/webapp/app/_entities.html
Corrected all translation content in HTML to reflect same as in json
files, also changed to use translation directive instead of the filter
where possible. First PR to clean up codebase before merging changes to
make i18n optional
=> Correct translation mismatch in html files

entity/templates/src/main/java/package/web/rest/mapper/_EntityMapper.java
When otherEntityName="dealership" differs from relationshipFieldName="shop" generator based on _Mapper.java produces the following lines:
@Mapping(source = "shop.id", target = "dealershipId")
@Mapping(source = "shop.name", target = "dealershipName")
instead of:
@Mapping(source = "shop.id", target = "shopId")
@Mapping(source = "shop.name", target = "shopName")
and maven build throws exception.
This PR fixes the issue.
=> @Mapping.target based on relationshipFieldName instead of otherEntityName

app/index.js, app/templates/_build.gradle, app/templates/_gradle.properties, app/templates/_mapstruct.gradle, entity/index.js
Mapstrcut can be used with gradle and java 8. Mapstruct dependencies are not added for java 7. Still using the same mapstruct version as the current maven build, should maybe consider an update to ``1.0.0.CR1`` released on june 3th.
=> Add mapstruct processor to gradle build

app/templates/Gruntfile.js, app/templates/_package.json
grunt concurrent task on default setup is not usefull as it takes longer
build time, concurrent can be a tip for those who would have lot of slow
tasks together, which is not the case for most jhipster applications
=> remove grunt concurrent as default option

app/templates/src/main/webapp/assets/styles/main.css
The css selector was incorrect, such that the password strength bar looked strange before.
=> Fix password strenghbar style

app/templates/Gruntfile.js
Use relative paths in minified files. This works with context path different from root context and in root context. Need to copy fonts separately otherwise they can't be found.
Fix #1555
=> Use relative paths when minify css

app/templates/_build.gradle
I had no compile errors, but for clarity also excluding it explicitly. See #1680
=> Exclude transitive mapstruct dependency

app/templates/_bower.json, app/templates/src/main/webapp/scripts/app/_app.js, entity/index.js, entity/templates/src/main/java/package/web/rest/_EntityResource.java, entity/templates/src/main/webapp/app/_entities.html, entity/templates/src/main/webapp/app/_entity-controller.js, entity/templates/src/main/webapp/app/_entity-detail-controller.js, entity/templates/src/main/webapp/app/_entity-detail.html, entity/templates/src/main/webapp/app/_entity-dialog-controller.js, entity/templates/src/main/webapp/app/_entity-dialog.html, entity/templates/src/main/webapp/app/_entity.js
Advantages: 
- separate the entity listing functionality, from the editing/creating functionality. So no need to load every related entities on the listing page, only when the dialog needs it. 
- the edit / create dialog have a proper URL, so it is easy to link from other parts of the application
- less html magic in the controllers (currently only the delete dialog needs jquery, but it can be fixed in a separate commit)
- emitting events when an entity is modified, which can be used in other parts of the application
=> Refactoring of the edit/new dialogs

app/templates/_gatling.gradle
Remove empty parameter as it doesn't work on windows (I need some windows machine at home)
=> Remove empty parameter

app/templates/_pom.xml
Mapstruct was already added for java when using gradle.
Fix #1722
=> Include mapstruct only for java8

entity/templates/src/main/resources/config/liquibase/changelog/_added_entity.xml
It should not be possible to insert multiple rows with the same foreign key in the one to one relationship database table.
If this is done by accident the crud interface fails with the following exception
```org.hibernate.HibernateException: More than one row with the given identifier was found: ```
=> Add unique constraint on relationship column in one to one owner entity

app/templates/Gruntfile.js
Instead of copy&paste htmlmin options, reuse them in ngtemplates.
=> Reuse htmlmin options in ngtemplates

heroku/index.js
Similar to my prior pull request https://github.com/jhipster/generator-jhipster/pull/1311, the --app parameter should also now be passed along with the heroku deploy:jar command to prevent errors if there's multiple heroku apps in the same folder.
=> specify heroku app name to heroku:deploy jar command

app/templates/src/main/java/package/config/_JacksonConfiguration.java, app/templates/src/test/java/package/web/rest/_TestUtil.java, entity/index.js, entity/templates/src/main/java/package/web/rest/dto/_EntityDTO.java, entity/templates/src/test/java/package/web/rest/_EntityResourceTest.java
With this PR, there is no more annotations in the domain file for the json ser/deser on joda types as it is configured globally on the mapper.
=> Configure jackson to serialize joda date types globally

entity/index.js, entity/templates/src/main/java/package/web/rest/_EntityResource.java, entity/templates/src/main/webapp/app/_entities.html, entity/templates/src/main/webapp/app/_entity-detail.html, entity/templates/src/main/webapp/app/_entity-dialog-controller.js, entity/templates/src/main/webapp/app/_entity-dialog.html, package.json
- ask for other entity relationship name on owner side
- add underscore javascript library to generator
- sort packages in package.js in alphabetic order
- expose a new util object in templates (added contains method)
- add dropdown to select id on relationship owner entity in create/update dialog
- add presentation of relatinship id in all ohter html crud pages (on owner side)
- add filter parameter to findAll in REST query which returns only objects with no relationship
- query with filter parameter when getting the ids for one-to-one relationships in entity-dialog-controller
fix #1468
=> Add id dropdown to one-to-one-relationship

app/templates/src/main/resources/config/liquibase/changelog/_initial_schema.xml
The oauth_access_token table definition is incorrect 
I ran into this issue (double authentication_id in oauth_access_token) : https://github.com/spring-projects/spring-security-oauth/issues/463
changed the oauth_access_token table model to avoid it
=> Update _initial_schema.xml (oauth_access_token table definition)

entity/index.js
I have done some heavy testing where I tested to generate all field types and relationships available for SQL and CASANDRA databases. I have compared the output of the generated source code before changes with after changes and they are the same. So the code should be ok to merge.
fix #1753
=> remove in memory variables from entity json

entity/templates/src/main/webapp/app/_entity-detail.html
change the way that entity detail values are displayed to use plain text instead of input controls
Fix #1735
=> use plain text in entity detail view

app/templates/_pom.xml
This is not needed anymore per #1628
Configuration steps are explained here:
https://github.com/michaelisvy/jhipster.github.io/blob/master/configurin
g_ide_eclipse.md
Testing: I have generated a project and imported it successfully in
Eclipse/STS 3.6.2
=> Removed m2eclipse configuration

app/templates/src/main/webapp/scripts/components/auth/provider/_auth.oauth2.service.js, app/templates/src/main/webapp/scripts/components/auth/provider/_auth.xauth.service.js
Originally found using oauth.  I compared oauth and xauth to session
and saw that _auth.session.service.js was already using the 
encodeURIComponent function, so I made the fix for both oauth and xauth
Fix #1834
=> URI encode username and password before posting during login

app/templates/_package.json
Upgrade proxy-middleware to 0.13.1 for passing csrf cookie correctly.
Fixes #1454
=> Upgrade proxy-middleware to 0.13.1 for passing csrf cookie correctly.

entity/templates/src/main/java/package/domain/_Entity.java, entity/templates/src/main/java/package/domain/field_validators.ejs
They were due to sub templating introduced with #1749.
=> Remove some blank lines after annotations for entity field validation.

app/templates/_build.gradle
Maven uses 0.0.1-SNAPSHOT as artifact version, gradle now too (before it was 0.1-SNAPSHOT).
=> Align artifact version to mvn build

entity/templates/src/main/java/package/web/rest/mapper/_EntityMapper.java, entity/templates/src/main/webapp/app/_entities.html, entity/templates/src/main/webapp/app/_entity-detail.html, entity/templates/src/main/webapp/app/_entity-dialog.html
This is the renamed version of #1851 and it contains a bit more.
Lots of entity relationship generator bugfixes when using dto and otherEntityField option. It also makes the ids (or otherEntityField texts) clickable
It is fully tested with and without dto option and with or without otherEntityField option with all relationship types.
the following setup of entities (in jdl) where used for testing
```
entity MultiRelationalEntity{
}
entity OneToOneEntity{
}
entity OneToManyEntity{
}
entity ManyToManyEntity{
}
relationship ManyToOne{
MultiRelationalEntity{oneToMany} to OneToManyEntity{multiRelational}
}
relationship OneToOne{
MultiRelationalEntity{oneToOne} to OneToOneEntity{multiRelational}
}
relationship ManyToMany{
MultiRelationalEntity{manyToMany} to ManyToManyEntity{multiRelational}
} …
```
=> Entity relationship bugfixes and refactoring

entity/templates/src/main/webapp/app/_entity-dialog-controller.js, entity/templates/src/main/webapp/app/_entity-dialog.html, entity/templates/src/main/webapp/i18n/_entity_ca.json, entity/templates/src/main/webapp/i18n/_entity_da.json, entity/templates/src/main/webapp/i18n/_entity_de.json, entity/templates/src/main/webapp/i18n/_entity_en.json, entity/templates/src/main/webapp/i18n/_entity_es.json, entity/templates/src/main/webapp/i18n/_entity_fr.json, entity/templates/src/main/webapp/i18n/_entity_hu.json, entity/templates/src/main/webapp/i18n/_entity_it.json, entity/templates/src/main/webapp/i18n/_entity_ja.json, entity/templates/src/main/webapp/i18n/_entity_kr.json, entity/templates/src/main/webapp/i18n/_entity_nl.json, entity/templates/src/main/webapp/i18n/_entity_pl.json, entity/templates/src/main/webapp/i18n/_entity_pt-br.json, entity/templates/src/main/webapp/i18n/_entity_ru.json, entity/templates/src/main/webapp/i18n/_entity_sv.json, entity/templates/src/main/webapp/i18n/_entity_tr.json, entity/templates/src/main/webapp/i18n/_entity_zh-cn.json, entity/templates/src/main/webapp/i18n/_entity_zh-tw.json
Further entity improvments
- Add empty options to select inputs so that relationship can be resetted
- Add current value of relationship to select inputs of one to one relatinships (today the current value is displayed as a blank option which is confusing)
- Treat one to one relationships to the User object differently since it is not possible to modify the UserResource from the entity generator. Instead of showing user id's not in a relationship, show all user ids in the select input. The user will not be able to select user ids already used in a relationship since an sql exception will be thrown. A future improvement would be to make this error message more readable to the user. 
- Capitalize relationship field names in translations
=> Entity relationship improvements

app/index.js, app/templates/src/main/java/package/config/audit/_AuditEventConverter.java, app/templates/src/main/java/package/repository/_PersistenceAuditEventRepository.java, app/templates/src/main/java/package/service/_AuditEventService.java, app/templates/src/main/java/package/web/rest/_AuditResource.java, app/templates/src/main/webapp/scripts/components/admin/_audits.service.js, app/templates/src/test/java/package/web/rest/_AuditResourceTest.java, test/test-creation.js
change URL mappings to /api/audits and handle methods dispatching based on parameters
add tests for AuditResource
fix bug where PersistenceAuditEventRepository has String as ID type for SQL databases (schema declares autoincremented bigint)
add alternative Optional-based service API if Java 8 is used
resolve https://github.com/jhipster/generator-jhipster/issues/1899
=> More RESTful access to AuditEvents

app/templates/_README.md
create README.md with build instructions for Grunt and Gradle
This is a first pass combining things from the JHipster Mini-Book and
the current Angular/Grunt project I’m working on for a client. In our
environment, we have a remote backend on GAE, so it’s easy to
build/test the client w/o having a backend running. This section could
probably be improved to show how to test with ‘gradlew bootRepackage’.
This is just a first pass and meant for improvement to handle the
various options.
#1880
=> README.md with build instructions

app/index.js
make maven and gradle equally supported options
by removing the recommended label for maven
will update the documentation site as well
fix #1942
=> remove recommended for maven

entity/templates/src/main/resources/config/liquibase/changelog/_added_entity.xml
Liquibase creates "real" type as "float" and in H2 "FLOAT" is an alias for "DOUBLE". See https://github.com/liquibase/liquibase/pull/496
This makes the tests fail if an entity has a float field
This PR uses float4 which is correct for both H2 and postgres to represent floats
=> fix error with float types and H2 database

entity/templates/src/main/java/package/web/rest/_EntityResource.java
Since Swagger imposes that the operationId is unique in the spec, springfox will enumerate the methods that have the same names. For instance if you have Foo, Bar and Baz entities, you will have "createUsingPOST", "createUsingPOST_1", "createUsingPOST_2" operation names for the POST operation which is not very nice especially when you generate client code with swagger-codegen.
This PR changes the methods names to createFoo, createBar and createBaz.
=> Use unique operation names per resource

CONTRIBUTING.md
Add documentation about (Yeoman/EJS) templates to 'Contributing guidelines'.
Fixes #1749
=> Add documentation about (Yeoman/EJS) templates

app/templates/src/main/resources/config/liquibase/changelog/_initial_schema.xml, app/templates/src/main/resources/config/liquibase/master.xml, entity/templates/src/main/resources/config/liquibase/changelog/_added_entity.xml
The xsd version is behind the used liquibase version used in pom
=> update liquibase xsd version

app/templates/_package.json
update browser-sync for gulp
updated to 2.9.1 and tested on MacOSX with Safari, FireFox, and Chrome
Fix #1639
=> update browser-sync for gulp

cloudfoundry/templates/_manifest.yml
Setting a specific buildpack will make sure the behaviour of the application is consistent on all Cloud Foundry providers. Bluemix uses a different default buildpack that doesn't use Java 8 by default, so currently Java 8 apps fail.
=> Specify Cloud Foundry buildpack

entity/templates/src/main/java/package/domain/field_validators.ejs, entity/templates/src/main/java/package/web/rest/dto/_EntityDTO.java
Pull request according to the issue reported [2025](https://github.com/jhipster/generator-jhipster/issues/2025).
When it is created an entity numeric field as numeric, if validation maximum value is greater than Integer.MAX_VALUE(2147483647 in Java), the "Max" annotation must include a "L" at the end (as Long number).
=> Added support for max long valitation greater than Integer.MAX_VALUE

app/templates/src/main/webapp/scripts/components/navbar/navbar.html, script-base.js
On smaller devices the navbar i collapsed and when clicking on the menu items that opens a new view the navbar is not hidden. This is a fix that makes the navbar hide when a menu item with a state change is clicked.
Tested and it works fine with added entities as well.
=> Hide navbar menu in collapse mode when menu item with ui state change is clicked

app/templates/Gruntfile.js
The longer "src/main/webapp/scripts/**/*.js" path seems to override the shorter "src/main/webapp/**/*.html" path, so changes in html-templates didn't get picked up by browsersync.
=> browsersync ignores changes on angular templates

app/index.js, app/templates/_Dockerfile_cassandra, app/templates/_docker-compose-prod.yml, app/templates/_docker-compose.yml
Hello,
**Description** :
As discussed in #1674 (which is closed), I want to propose this.
This is a first pull request about docker-compose, to know if I'm in correct way.
The main goal is to provided the other services **for the developer to start faster** !
After generating a new JHipster project, you'll have a new `docker-compose.yml` file in the folder project.
You can simply ignore this file or... if you like Docker, you can start the service needed by your project.
For example, you decided to build a new project with MySQL in DEV (instead of H2)
```
yo jhipster
docker-compose up -d
mvn spring-boot:run
```
You don't have to install or configure a new database.
At the moment, it works with MySQL, PostgreSQL, MongoDB, Cassandra.
With Cassandra, you have to build the image, inject the …
=> Generate docker-compose

entity/index.js, entity/templates/src/main/java/package/domain/_Entity.java, package.json
relates to jhipster/jhipster-uml#46
fix #1949
=> add class and field comments to entity generator

app/templates/src/main/resources/config/_application-prod.yml
I'm testing elasticsearch and I got the same problem #1660
In development profile, no error because it's an embedded Elasticsearch
In production profile, I got this error when starting the app :
```
[INFO] com.mycompany.myapp.config.ThymeleafConfiguration - loading non-reloadable mail messages resources
[ERROR] org.springframework.data.elasticsearch.repository.support.AbstractElasticsearchRepository - failed to load elasticsearch nodes : org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []
[INFO] com.mycompany.myapp.Application - Started Application in 24.697 seconds (JVM running for 25.311)
```
The elasticsearch logs :
```
[2015-10-03 19:29:33,589][WARN ][http.netty               ] [Spike] Caught exception while handling client http …
```
=> Fix Elasticsearch default port in profile production

app/index.js, app/templates/_docker-compose-prod.yml, app/templates/_docker-compose.yml
I added Elasticsearch for production profile, if search engine is Elasticsearch :
* MySQL : elasticsearch + mysql
* PostgreSQL : elasticsearch + psql
* Oracle : only elasticsearch, because there isn't official docker database 12c
@atomfrede : could you test this, if you have time ? Thanks in advance.
=> Add elasticsearch for docker-compose

app/templates/src/main/webapp/_index.html
Not sure this is wanted since it does not follow 
```
Policy 1: technologies used by JHipster have their default configuration used as much as possible
```
but it really annoys me that google chrome tries to translate the webpage when in fact there is already a translate mechanism in angular. 
Please feel free to close this if this is not wanted.
=> remove annoying google translation popup question

entity/index.js, entity/templates/src/main/webapp/app/_entity-detail-controller.js, entity/templates/src/test/javascript/spec/app/_entity-detail-controller.spec.js
Watchers on root scope should be cleaned up or it can lead to memory leaks.  Attach a listener to the scope, so that when it's destroyed ($scope.$on('$destroy'...) call the unsubcribe method returned from the $rootScope.$on(...) call
=> Remove watcher from $rootScope upon $scope destroy

app/templates/src/main/java/package/security/xauth/_TokenProvider.java
Fixed  #2095 using a fixed time string comparison
=> fixed timing attack vulnerability in TokenProvider

app/templates/_README.md
improve first line of generated README.md to not contain the name of the project and use "This application" instead. Also replaced duplicate references to the word "JHipster" to use a URL in the second instance
Fix #2188
=> improve first line of generated README.md

app/templates/src/main/java/package/security/_SecurityUtils.java
Minor change to method name that makes more sense
=> rename SecurityUtils.getCurrentLoginId() to SecurityUtils.getCurrentUserId()

languages/index.js
When I tried to add new language in a project
```
$ yo jhipster:languages
Languages configuration is starting
? Please choose additional languages to install: Spanish
events.js:85
throw er; // Unhandled 'error' event
^
ReferenceError: /home/david/Development/NodeJs/workspace/generator-jhipster-dalbelap/languages/templates/src/main/resources/i18n/_messages_es.properties:19
17| email.reset.text1=Se ha solicitado el reinicio de contraseña para su cuenta de <%= baseName %>, por favor, haga clic en el enlace de abajo para reiniciarla:
18| email.reset.text2=Saludos,
>> 19| <%_ if (enableSocialSignIn) { _%>
20| # Social validation e-mail
21| email.social.registration.title=Activación de cuenta jhipster
22| email.social.registration.greeting=Estimado {0}
``` 
I just added this line to …
=> Fix languages template with Social authentication option

app/templates/_Dockerfile_cassandra, app/templates/_docker-compose-prod.yml, app/templates/_docker-compose.yml
2 changes :
* use an official tags version, instead of the latest (to avoid a new update version of database/service which we didn't test)
* mysql : change the start cmd with lower_case_table_name (deprecated) to lower_case_table_names
=> docker-compose : use tags version instead of latest

app/index.js, app/templates/src/main/java/package/config/_ElasticSearchConfiguration.java
By default, elasticsearch uses its own ObjectMapper and not the one created by spring-boot
Fix #2241
=> Fix elastic search serialization of jsr310 types

app/templates/src/main/java/package/config/_ElasticSearchConfiguration.java
Since elastic search has it owns settings for json serialization, it is preferable to use a dedicated object mapper
=> Use dedicated object mapper for elasticsearch

app/templates/src/test/resources/config/_application.yml
Fix https://github.com/jhipster/generator-jhipster/issues/2218 to launch tests when a mongodb instance is running
Add +100 to port, like Cassandra port for unit tests
=> Change default mongo port for unit tests

app/templates/src/main/java/package/web/rest/_AccountResource.java
If the application is not deployed in the root context the baseUrl should link to:
http://myhost:80/myContextPath
instead of:
http://myhost:80
=> added contextPath to baseUrl for links in emails to support applications not deployed in root context as well

app/templates/src/main/java/package/config/_OAuth2ServerConfiguration.java, app/templates/src/main/java/package/config/_SecurityConfiguration.java, app/templates/src/main/java/package/domain/_OAuth2AuthenticationAccessToken.java
This brings basic support for 3-legged oauth support to open your API to the world
There is still a lot of room for improvement:
- the approval page is spring security's default one which is quite ugly
- the /oauth/authorize endpoint is secured with stateless basic auth. It would be better to use the jhipster's login form but this one should redirect back to the authorize page after login which is currently not the case.
- springfox could be used to document the authorization (securityDefinitions) but then it doesn't work anymore with password oauth. I guess this is because when there is securityDefinitions the auth bearer that we pass from angular is overridden.
- for SQL databases, you can configure as many client apps as you want by adding rows in the oauth_client_details table. …
=> Support 3-legged oauth2 flows (authorization_code and implicit)

app/templates/_build.gradle
Don't know why it was in ``build.gradle`` (maven don't has it), so I removed it, not problems so far.
=> remove jetty from testcompile

app/templates/src/main/resources/i18n/_messages_en.properties, app/templates/src/main/resources/i18n/_messages_fr.properties, languages/templates/src/main/resources/i18n/_messages_ca.properties, languages/templates/src/main/resources/i18n/_messages_da.properties, languages/templates/src/main/resources/i18n/_messages_de.properties, languages/templates/src/main/resources/i18n/_messages_es.properties, languages/templates/src/main/resources/i18n/_messages_gl.properties, languages/templates/src/main/resources/i18n/_messages_hu.properties, languages/templates/src/main/resources/i18n/_messages_it.properties, languages/templates/src/main/resources/i18n/_messages_ja.properties, languages/templates/src/main/resources/i18n/_messages_ko.properties, languages/templates/src/main/resources/i18n/_messages_nl.properties, languages/templates/src/main/resources/i18n/_messages_pl.properties, languages/templates/src/main/resources/i18n/_messages_pt_br.properties, languages/templates/src/main/resources/i18n/_messages_pt_pt.properties, languages/templates/src/main/resources/i18n/_messages_ro.properties, languages/templates/src/main/resources/i18n/_messages_ru.properties, languages/templates/src/main/resources/i18n/_messages_sv.properties, languages/templates/src/main/resources/i18n/_messages_tr.properties, languages/templates/src/main/resources/i18n/_messages_zh_cn.properties, languages/templates/src/main/resources/i18n/_messages_zh_tw.properties
Like @deepu105 says, change jhipster by baseName and add new line above social translate block.
=> Fix base name for social email translation

app/templates/src/main/java/package/config/_OAuth2ServerConfiguration.java
Let's remove the usage of the database for storing the client details so that everybody can login again.
A correct implementation of multi-client app oauth can be discussed later.
Fix #2069
=> Revert jdbc clientdetails

CONTRIBUTING.md
I had so much trouble the first time I got the "This branch has conflicts that must be resolved" message that I think we could help the contributors to solve this cleanly.
=> Add conflict resolution instructions to CONTRIBUTING

app/templates/src/main/resources/config/liquibase/changelog/_initial_schema.xml
The login index size was not following the `enableSocialSignIn` rule
=> Small change in inital schema

app/templates/src/main/webapp/scripts/app/admin/metrics/_metrics.controller.js
The Metrics modal requires the thread dump content as an array, but
/dump returns { content: [], ...}.  Updated the metrics.controller.js
to return response.data.content when resolving the threadDump.
I thought about putting the .content into the MonitoringService
but doing that would restrict other client code from using any of the
other information in the /dump response.
Addresses jhipster/generator-jhipster#2342
=> Pull .content from threadDump for metrics modal

app/templates/_docker-compose-prod.yml
In prod profile, a 2-node cluster will be spawned by docker-compose.
A simple ```docker-compose scale <your-app-name>-prod-cassandra-node=3``` for instance will spawn 3 more nodes that will add themselves to the ring.
By default only localhost is set as contact-points for the datastax driver. This is only needed at the driver startup. After that the driver will get the other nodes IPs and use them (meaning that even if the seed node fails, the app will continue to see the cluster).
=> Configure a cassandra cluster in prod profile

entity/templates/src/main/java/package/domain/_Entity.java, travis/samples/app-mongodb/.jhipster/BankAccount.json
Also reverted https://github.com/cbornet/generator-jhipster/commit/a512b69939245e6e29848db65cacd6f3edf3a5a6 to make our ci build test blob for mongo
fix #2329
=> replace column annotation for mongo entities

.travis.yml, travis/scripts/01-generate-project.sh
When upgrading lib, there can be conflict between grunt lib and gulp lib.
So split grunt lib and gulp lib (delete the useless lib) before generating project
=> Travis : split grunt lib and gulp lib

entity/index.js, entity/templates/src/main/java/package/common/delete_template.ejs, entity/templates/src/main/java/package/common/get_all_stream_template.ejs, entity/templates/src/main/java/package/common/get_all_template.ejs, entity/templates/src/main/java/package/common/get_filtered_template.ejs, entity/templates/src/main/java/package/common/get_template.ejs, entity/templates/src/main/java/package/common/inject_template.ejs, entity/templates/src/main/java/package/common/save_template.ejs, entity/templates/src/main/java/package/common/search_template.ejs, entity/templates/src/main/java/package/repository/_EntityRepository.java, entity/templates/src/main/java/package/service/_EntityService.java, entity/templates/src/main/java/package/service/impl/_EntityServiceImpl.java, entity/templates/src/main/java/package/web/rest/_EntityResource.java, entity/templates/src/test/java/package/web/rest/_EntityResourceIntTest.java
Option to choose service layer with or without interface/impl
Most of the code in `_entityResource.java` has been moved into `common/*.ejs` files and is resusedin service as well, so there is very little duplication of code also is much easier to maintain (as per https://github.com/jhipster/generator-jhipster/issues/1749)
works with DTO and non DTO options
works with and without pagination (findAll will fail in casandra it was already as such)
=> Add service layer option for entity sub gen

app/index.js, app/templates/_Dockerfile_cassandra, app/templates/_docker-compose-prod.yml, app/templates/docker/cassandra/_cassandra.sh, app/templates/docker/opscenter/_Dockerfile, travis/scripts/04-docker-compose.sh
* Datastax Opscenter (community edition) is spawned by docker-compose and accessible at ```http://localhost:8888```
* The datastax-agent is installed and started on each node. The agent automatically connects to the opscenter container to send its metrics.
=> Add datastax opscenter to dockerized cassandra

app/templates/src/main/java/package/web/rest/util/_PaginationUtil.java
fix `last` pagination link header having page = -1 when there were no
results retrieved by spring
fix #2050
=> fix `last` link header

entity/index.js, entity/templates/src/main/java/package/domain/_Entity.java
This adds swagger annotations in the generated entities based on the "javadoc" field of the entity json file.
The doc is then accessible in swagger-ui and used when generating clients with swagger-codegen
=> Add swagger doc annotations from javadoc

app/templates/gulpfile.js
- Open a browser window automatically when you type 'gulp'.
- Change from gulp.run to gulp.start since run is deprecated.
http://stackoverflow.com/questions/21905875/gulp-run-is-deprecated-how-do-i-compose-tasks
=> Improve the gulp experience so it's like grunt.

app/templates/Gruntfile.js, app/templates/gulpfile.js
I made this pull request because after generating my project, I actually had to use a company specific parent and not the default one. The project used it's inherited versionand no project version was defined. I could not execute any Grunt task.
I actually spent an entire day figuring this outbecause the error I had with our without --stack was of no help at all : 
TypeError: Cannot read property '0' of undefined
Warning: Task "default" not found. Use --force to continue.
This pull request is made to ensure that the pom.xml file has a defined project version or an inherited parent version.
The updated template code throws an exception otherwise to indicate the source of the error.
=> Ensures the pom.xml file has a defined project version or an inherited parent version

app/templates/src/main/webapp/scripts/app/account/password/_password.directive.js
Replace 'backroung' with 'background-color' CSS key in password.directive.js to match jasmine tests in password.directive.spec.js
=> Fix password strength indicator style 

entity/templates/src/main/java/package/web/rest/mapper/_EntityMapper.java
The logic for the fix is already in the generator, but the array was being reset each loop.  I moved the array declaration outside of the loop and projects can now be built successfully.
=> Fix EntityMapper to only create one mapping for each entity

app/templates/src/main/webapp/scripts/app/account/password/_password.controller.js, app/templates/src/test/javascript/spec/app/account/password/_password.controller.spec.js
If you submit non matching form after you changed the password successfully; you would get error error message and success message at the same time.  Other messages should be set to `null`, so does `$scope.doNotMatch`.
*The changes were tested.*
=> avoid to show doNotMatch error with other result messages

app/templates/src/main/java/package/web/rest/_UserResource.java
This PR fixes the following in Administration -> User management:
When changing the login to a login that is already in use the error message is:
E-mail is already in use!
When changing the login to a login that is already in use and also the email to the email of the login already in use (e.g. user to admin and user@localhost to admin@localhost), a ConstraintViolationException is thrown.
=> fix user management server-side validation

app/templates/_build.gradle, modules/index.js, script-base.js
add some needles in gradle build file for my [swagger2markup](https://github.com/atomfrede/generator-jhipster-swagger2markup) generator. With the new needles you can
* add additional build script plugins
* apply from an external gradle script
* add a new dependency
=> add needles to gradle build file

app/templates/_pom.xml, modules/index.js, script-base.js
Add 2 needles for maven, needed by [generator-jhipster-swagger2markup](https://github.com/atomfrede/generator-jhipster-swagger2markup) and [generator-jhipster-docker](https://github.com/pascalgrimaud/generator-jhipster-docker)
* add dependency
* add plugin
As discussed in dev mailing list, this solution has an issue if something is changed when upgrading.
We have to find a solution to do something like bower
=> Needles maven : dependency and plugin

.travis.yml, app/templates/src/test/javascript/_protractor.conf.js, travis/samples/app-websocket/.jhipster/BankAccount.json, travis/samples/app-websocket/.jhipster/Label.json, travis/samples/app-websocket/.jhipster/Operation.json, travis/samples/app-websocket/.yo-rc.json, travis/scripts/05-run.sh
Add protractor tests to sample/app-websocket ; I think 1 project is enough.
I did the same thing : https://github.com/mraible/21-points/pull/17
I don't know if Travis will return error if one test failed => so I will monitor :eyes: the Travis builds logs, when someone PR
=> Travis : add protractor tests to 1 project

app/templates/src/test/javascript/spec/app/account/activate/_activate.controller.spec.js, app/templates/src/test/javascript/spec/app/account/login/_login.controller.spec.js, app/templates/src/test/javascript/spec/app/account/password/_password.controller.spec.js, app/templates/src/test/javascript/spec/app/account/password/_password.directive.spec.js, app/templates/src/test/javascript/spec/app/account/register/_register.controller.spec.js, app/templates/src/test/javascript/spec/app/account/settings/_settings.controller.spec.js, app/templates/src/test/javascript/spec/app/admin/health/_health.controller.spec.js, app/templates/src/test/javascript/spec/components/auth/_auth.services.spec.js, entity/templates/src/test/javascript/spec/app/_entity-detail-controller.spec.js
fix jasmine test heirarchy by fixing test names and moving entity
controller tests under `Controller Tests`
fix #2493
=> fix jasmine test heirarchy

app/templates/_pom.xml
See #2225 
The issue with Cloud Foundry deployment should be fixed with cf CLI  v6.14.1
I don't have a CF account so I cannot test. Can somebody confim that it works ?
=> Set executable war to true by default

entity/templates/src/main/java/package/domain/_Entity.java
Add multiple entities with id null in a collection with cascade
persistence lead to persist only one entity, because they are
equals. Without business key, entites with null primary key
should be never equals with anything.
Fix #2543
=> change equals method in entity template

app/templates/src/main/webapp/scripts/components/tracker/_tracker.service.js
showActivity() function in TrackerController gets called multiple times when User Tracker page is revisited. This is cause the Tracker listener promise does is not reseted on unsubscribe.
Please note that the User Tracker page seems to work anyway though showActivity() gets called multiple times. So the fix is not visual.
=> Prevent promise calls from stacking after unsubscription

app/templates/_build.gradle
Fix https://github.com/jhipster/generator-jhipster/issues/2561
- app.war is inchanged
- app.war.original => doesn't contain tomcat-embed libs anymore
Same code for maven :
https://github.com/jhipster/generator-jhipster/blob/3becfa8c7e1fea1700eb6eec6395e435470c6c27/app/templates/_pom.xml#L706-L708
@atomfrede can you merge it, if it's correct for you ?
=> Gradle packaging : remove tomcat-embed libs in war.original

app/templates/_pom.xml
#2553 splitted cucumber / not cucumber tests execution
=> Hazelcast 2nd level cache + Cucumber test failing #2553

package.json, script-base.js, test/test-creation.js
Remove these warnings during `npm test` by adding 2 dependencies **yeoman-assert** and **yeoman-test** :
```
(!) yeoman.assert is deprecated. Instead `require('yeoman-assert')`. See https://github.com/yeoman/generator/issues/883
(!) yeoman.test is deprecated. Instead `require('yeoman-test')`.
```
It should remove the last warning about generators.Base (see https://github.com/jhipster/generator-jhipster/issues/2594) :
```
(!) require('yeoman-generator').generators.Base is deprecated. Use require('yeoman-generator').Base directly
```
=> Yeoman : fix deprecated warning

app/templates/src/main/scss/main.scss, app/templates/src/main/webapp/assets/styles/main.css, entity/templates/src/main/webapp/app/_entities.html, entity/templates/src/main/webapp/i18n/_entity_ca.json, entity/templates/src/main/webapp/i18n/_entity_da.json, entity/templates/src/main/webapp/i18n/_entity_de.json, entity/templates/src/main/webapp/i18n/_entity_en.json, entity/templates/src/main/webapp/i18n/_entity_es.json, entity/templates/src/main/webapp/i18n/_entity_fr.json, entity/templates/src/main/webapp/i18n/_entity_gl.json, entity/templates/src/main/webapp/i18n/_entity_hu.json, entity/templates/src/main/webapp/i18n/_entity_it.json, entity/templates/src/main/webapp/i18n/_entity_ja.json, entity/templates/src/main/webapp/i18n/_entity_kr.json, entity/templates/src/main/webapp/i18n/_entity_nl.json, entity/templates/src/main/webapp/i18n/_entity_pl.json, entity/templates/src/main/webapp/i18n/_entity_pt-br.json, entity/templates/src/main/webapp/i18n/_entity_pt-pt.json, entity/templates/src/main/webapp/i18n/_entity_ro.json, entity/templates/src/main/webapp/i18n/_entity_ru.json, entity/templates/src/main/webapp/i18n/_entity_sv.json, entity/templates/src/main/webapp/i18n/_entity_ta.json, entity/templates/src/main/webapp/i18n/_entity_tr.json, entity/templates/src/main/webapp/i18n/_entity_zh-cn.json, entity/templates/src/main/webapp/i18n/_entity_zh-tw.json
"Create new <Entity>"button is left aligned (padding removed)
Search bar is now an input group (input followed by search icon) and left-aligned.
Search bar text "Search a <Entity>" is now in a tooltip.
The text "Search a <Entity>" was not localized, added english.
When shrinking the window (and search is enabled), the text "Create new
button" is removed  on smaller screen sizes and only the icon is visible, text is available as a tooltip.
The "View", "Edit", and "Delete" buttons are now inside button group.
Fix #2552
=> Fixed Improve entity list UI (#2552)

app/templates/src/main/webapp/swagger-ui/_index.html
The swagger*:index*;html was loading spec file by using absolute URL: /v2/api-docs, this did not work when app used a context path.
Now we use a relative URL.
Fix #2607
=> Fix #2607 by using relative URL to swagger spec file

app/templates/src/main/resources/config/_application-dev.yml, app/templates/src/main/resources/h2.server.properties
With the current setting, as there is no username, the h2-console will put "admin:admin" as default username/password instead of keeping the fields empty so you have to manually empty the fields. This PR sets a username so the user can directly connect to the database when he opens the console. This is a major improvement for productivity :smile:
=> Put a username for H2 database

app/templates/Gruntfile.js, app/templates/gulpfile.js
The X-Forwarded-Host header is used by springfox to fill the host field in swagger spec.
With this PR, swagger now works in browser-sync
=> Browser sync proxy sets X-Forwarded-Host header

app/templates/src/main/webapp/scripts/app/admin/audits/_audits.controller.js
Very small change, the Audits page currently fetches audits for the entire year.
=> return the correct date from the previousMonth function during January

app/templates/src/main/java/package/config/_SecurityConfiguration.java
This has already been done for OAuth. This PR is to bring it to session auth
OPTIONS are only used for CORS preflight requests and because as per the spec, the browser shall not include auth cookies in preflight requests, we need to whitelist them for cross-domain situations
=> Whitelist OPTIONS requests

entity/index.js
This is somewhat inline with what @jdubois suggested in #2668 
When running `yo jhipster:entity` on an existing entity the below options are given
- If the user did a `yo jhipster:entity Foo --force` entity is regenerated directly (like we already do)
- Otherwise a new question is asked `Do you want to update the entity? This will replace the existing files for this entity, all your custom code will be overwriiten` this will have options 
* Yes, re generate the entity
* [BETA] Yes, add more fields and relationships
* [BETA] Yes, remove fields and relationships
* No, exit
- If Add is selected, use the current options for creating an attribute/relation
- If Remove is selected, give choice to select attributes/relations and remove the selected attribute/relation, this will reset the …
=> add entity update feature

app/templates/src/main/webapp/scripts/app/account/password/_password.directive.js, entity/templates/src/main/webapp/app/_entities.html
Remove the translate filter from the entity listings page (breaks the JS currently) and remove the translation from the password directive, for projects without translation enabled.
Fix #2698
=> Remove translation from projects without translation enabled

app/cleanup.js, app/index.js, package.json, script-base.js
When we rename/remove generated files we have to programatically remove them in app/index.js.
This list of files are becoming very large and if the user would want to have a file called something that is in our remove list the file will get removed every time the user updates jhipster.
To avoid this we could make the generator only remove the files once by giving the remove a version. Thereby the remove will only take place if the current installed version is less than the remove version which is the version when the remove got added.
=> only remove files once when updating jhipster

app/templates/src/main/java/package/async/_ExceptionHandlingAsyncTaskExecutor.java
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/jhipster/generator-jhipster/2715)
=> Tasks that executes with the ExceptionHandlingAsyncTaskExecutor are not being wrapped - fixed #2714

app/templates/gradle/_yeoman.gradle
gulp and grunt default behaviour is not same in gradle, this makes both behave in the same way
=> make gulp and grunt defaults similar

app/templates/_package.json, app/templates/gulpfile.js
* Added gulp-sourcemaps to the build flow
* JS sourcemaps are now generated and debugging production builds work
* Uglify doesn't mangle variable names any more so we are able to check variables content while debugging (but the output JS file is a little bigger)
* Now uglifying AFTER concatenating files to let uglify fully optimize the output
=> Generate JS source maps for JS in prod (gulp)

app/index.js, app/templates/Gruntfile.js, app/templates/gulpfile.js, app/templates/src/main/webapp/_index.html, app/templates/src/main/webapp/content/css/vendor.css, app/templates/src/main/webapp/scss/main.scss, app/templates/src/main/webapp/scss/vendor.scss
I figured the bootstrap style sheets should be a part of vendor.css, in stead of app.css. We're not supposed to edit the contents of `bower_components`, and so we don't expect the output of bootstrap-sass to change as often as our own styles, and therefore would prefer this to be in vendor.css to facilitate browser caches.
=> Sass-bootstrap: move output to vendor.css

heroku/index.js, heroku/templates/_Procfile
This PR improves Heroku support now that the boot timeout is 90 seconds. It includes:
It also fixes two bugs in random name generation, and changes the default MySQL addon to JawsDB instead of ClearDB (due to better success in the wild). 
/cc @mraible
=> Heroku improvments

app/templates/_build.gradle
With gradle, when only one test fail, the report isn't generated.
Removing too the println to be less wordy
=> Allow test continue if fail and generate the report

generators/client/templates/src/main/webapp/swagger-ui/_index.html, generators/server/templates/_gradle.properties, generators/server/templates/_pom.xml
Adds auth headers (such as CSRF,OAuth, ...) to springfox swagger-ui index.html (not using the webjar)
THis way we get all features from springfox such as support for multiple dockets.
=> Upgrade springfox to 2.3.1 and enhance swagger-ui

generators/server/templates/_build.gradle
The gradle build is broken for microservices. I think we should add a Travis build for a microservice app and microservice gateway with gradle and maven. @jdubois Can I can do it by myself ?
=> Fix a typo in gradle spring cloud dependency name

generators/server/templates/src/main/java/package/config/_DatabaseConfiguration.java, generators/server/templates/src/main/resources/config/_application-dev.yml, generators/server/templates/src/main/resources/config/_application-prod.yml
See #2769 
Note : it uses spring.datasource.hikari : this is not the current path for 1.3.2 but will be in 1.4.0
Now all Hikari configs are accessible by configuration. Eg :
```yaml
spring.datasource.hikari.connection-test-query: SELECT 1 FROM DUAL
```
=> Read hikari conf from application.yml

generators/entity/templates/src/test/java/package/web/rest/_EntityResourceIntTest.java, generators/server/templates/src/main/java/package/domain/util/_JSR310DateTimeSerializer.java
Fix #2689 
The format is ```yyyy-MM-dd'T'HH:mm:ss.SSSZ``` which should be supported by most clients and is the official ES5 one.
=> Use a fixed datetime format

generators/client/templates/_bower.json
Fix #2828 
Related to #2808 #2774 
I'd tried to update angular to 1.5.0, but is having some many errors in 'gulp test'.
=> Update angular* and angular-translate

generators/client/templates/gulp/utils.js
When --skip-server flag is set, gulp should not parse pom.xml or build.gradle to extract project version as these files don't exist.
In this case, the version is direcly set in gulp/utils.js
Fix #2810
=> When --skip-server flag is set, gulp should not parse pom.xml for version

generators/server/index.js, generators/server/templates/src/main/java/package/config/apidoc/_SwaggerConfiguration.java, generators/server/templates/src/main/java/package/web/rest/_GatewaySwaggerApiResource.java
This is fully functional and allows viewing and "trying out" the microservices API on the gateway's Swagger-UI.
To pass the JWT access authorization, the backend microservices app must be configured to have the same jwtsecret property as the gateway but this is already documented in the [registry's Readme](https://github.com/jhipster/jhipster-registry).
=> Aggregate microservices swagger docs on the gateway

generators/server/templates/_pom.xml
Linked to #2582, the `<% if(!skipClient) {%>` tag was also skipping `<plugins>` and `</pluginExecutions>` xml tags in the pom.xml file.
=> Fix pom.xml when generating application with --skipClient flag

generators/entity/templates/src/main/java/package/web/rest/mapper/_EntityMapper.java, generators/server/index.js, generators/server/templates/src/main/java/package/web/rest/mapper/_UserMapper.java, travis/samples/app-default-from-scratch/.jhipster/RelationshipTestMapstructEntity.json, travis/samples/app-mysql/.jhipster/RelationshipTestMapstructEntity.json, travis/samples/app-psql-es-noi18n/.jhipster/RelationshipTestMapstructEntity.json
I added UserMapper to the generated project.  This Mapper should probably be used elsewhere in the code but for now this pull should fix the two issues related to MapStruct (#2867 and #2006).  I added the Travis tests back as requested in the issue.
The biggest difference is when an entity has a relationship with User, it uses the userFromId method in UserMapper instead of declaring it in each entity.
There might be a better way to go from Sets of Authorities to Sets of Strings  and back in the UserMapper, please advise.
=> Add user mapper

generators/server/index.js, generators/server/templates/src/main/docker/_registry.yml, test/test-creation.js, travis/scripts/03-docker-compose.sh
new docker-compose file : registry.yml
It uses the official [jhipster/jhipster-registry](https://hub.docker.com/r/jhipster/jhipster-registry) image
To start the registry :
```
docker-compose -f src/main/docker/registry.yml up -d
```
Travis build should not display stacktrace anymore (for gateway and microservice build)
=> docker-compose file : registry

generators/entity/index.js
The current fields and relationships should be displayed when regenerating an entity or adding more fields and relationships.
This PR also add some colors to the relationships list + adds header + shows relationships in a similar way as the fields are shown `fieldName (ClassName) relationship-type`
screenshot
I'm a bit unsure of the placement of the declaration of the `logFieldsAndRelationships` function, so please review this
=> show fields and relationships on add more fields regeneration + improve its look

generators/client/templates/src/main/webapp/app/_app.state.js, generators/client/templates/src/main/webapp/app/account/_account.state.js, generators/client/templates/src/main/webapp/app/admin/_admin.state.js, generators/client/templates/src/main/webapp/app/entities/_entity.state.js, generators/client/templates/src/main/webapp/app/home/_home.state.js, generators/client/templates/src/main/webapp/app/layouts/error/_error.state.js
I think it would make sense to rename the app main ui-router state to `app` from `site` just for consistency
=> rename app state site to app

generators/server/index.js, generators/server/templates/src/main/resources/config/liquibase/changelog/_initial_schema.xml, generators/server/templates/src/main/resources/config/mongeez/master.xml
Related to #2811
Allow not generating server code that concerns user management with the --skip-server-management flag.
Include some tweaks to liquibase and mongeez database changelogs to pass the tests when user management has been removed.
=> Separate user management server code 

generators/client/templates/src/main/webapp/app/components/util/_sort.directive.js
fix jQuery error when predicate has a period in it by surrounding it with quotes
fix #2928
=> fix jQuery error when predicate has a period in it

generators/server/index.js
Change constant name RESOURCE_DIR to SERVER_MAIN_RES_DIR for microservice and gateway bootstrap configuration files.
=> Fix config server related bad merge

app/templates/gulpfile.js
ng-constants was generated in wrong directory.
update #2960
=> fix path for ng constants

generators/client/templates/src/main/webapp/app/admin/tracker/_tracker.service.js, generators/server/templates/src/main/java/package/config/_WebsocketSecurityConfiguration.java, generators/server/templates/src/main/java/package/security/jwt/_JWTConfigurer.java, generators/server/templates/src/main/java/package/security/jwt/_JWTFilter.java
Similar to oauth, this fix adds the current JWT token as a query param for the tracker (websocket) url. The query param is checked in the JWTFilter, if there is no JWT token in the header. This allows to authenticate the user during a STOMP connect frame.
=> adds JWT Token for websockets

generators/client/templates/src/main/webapp/content/css/main.css, generators/client/templates/src/main/webapp/scss/main.scss
Make sort icons less visually intrusive in entity table by using lighter grey and switching back to black with a pointer when mouse is over.
Here is a screenshot below though the mouse pointer is wrong due to the capture tool, it should be the usual hand.
=> Style sort icons to make them less visually intrusive in entity table

generators/server/templates/src/main/resources/config/liquibase/changelog/_initial_schema.xml
FOREIGN keys might fail on strict dbms servers setup because of the different sizes.
=> username should have same size as user.login

generators/server/templates/src/main/docker/_dev.yml, generators/server/templates/src/main/docker/_prod.yml, generators/server/templates/src/main/docker/cassandra/_Cassandra-Dev.Dockerfile, generators/server/templates/src/main/docker/cassandra/_Cassandra-Prod.Dockerfile
All new images have been tested manually by generating an appropriate JHipster app.
Upgrades :
- mysql from 5.7.9 to 5.7.11
- psql from 9.4.5 to 9.5.1
- mongo from 3.0.7 to 3.2.3
- cassandra from 2.2.3 to 2.2.5
- elasticsearch from 1.7.3 to 1.7.5
Notes:
- elasticsearch 2+ doesn't work
- cassandra 3+ doesn't work
=> Upgrade image in docker-compose files

generators/client/templates/src/main/webapp/swagger-ui/_index.html
I was just getting errors on the swagger page, in an app generated from latest master. It looks like swagger-ui version 2.1.4 (@jdubois updated recently) needs JSONEditor.
EDIT [this](https://github.com/jhipster/generator-jhipster/commit/72bfc62fb0c7eba178c19b4f9d56e6e6d43dccb3) is where it started.
=> Include JSONEditor script, needed for swagger-ui 2.1.4

generators/server/templates/_pom.xml
This dependency disappeared recently from _pom.xml
Fix #3010
=> add missing hibernate envers dependency

generators/entity/templates/src/main/java/package/web/rest/dto/_EntityDTO.java, generators/server/templates/src/test/java/package/web/rest/_AccountResourceIntTest.java
The Tranactional annotation is normally only used with SQL (based off of _UserService.java) so removing that should allow AccountResourceIntTest to compile and run for mongo and cassandra.
Removing the Lob annotation for Mongo allows Mongo projects with entities containing blobs to compile/upload files and images.
Fix #3010
=> only use @Transactional with sql and @Lob without mongodb

generators/entity/templates/src/main/resources/config/liquibase/changelog/_added_entity.xml
This increases the max blob size for MySQL from 64 KB to 4 GB.  
Fix #2934
=> use longblob in entity liquibase changelogs when using mysql

generators/client/templates/_package.json, generators/client/templates/gulpfile.js
As reported in [#3017](https://github.com/jhipster/generator-jhipster/issues/3017), the current master branch generates an app with broken production build. This is a quick-and-dirty workaround, the proper fix would probably be to prepend a `;` to all scripts which now follow the module pattern,
```js
;(function(){
/* ... */
})();
```
=> Use gulp-footer to insert semi-colons before concatenating scripts

generators/client/templates/gulpfile.js
The locations of protractor spec files was changed recently, but the corresponding gulp task was not.
=> Fix protractor gulp task for new spec locations

generators/client/templates/src/main/webapp/app/components/alert/_alert-error.directive.js, generators/client/templates/src/main/webapp/app/components/alert/_alert.directive.js, generators/client/templates/src/main/webapp/app/components/alert/_alert.service.js
While working on #3043 I realized that I've refactored wrongly the alert and alert-error directives into components. 
In directives, second parameter in `.directive('jhiAlertError', jhiAlertError)` was a function, in components it has to be a variable. So I fixed it and turned functions into variables. 
I followed [this issue](https://github.com/johnpapa/angular-styleguide/issues/662) to stay consistent with Johnpapa's style.
=> Fix jhiAlert and jhiAlertErrors components

generators/client/templates/_package.json
Current version we get for gulp-protractor doesn't actually use the (huge) protractor 3 dependency, thought it would be good to update?
=> Update gulp-protractor to 2.1.0

generators/server/templates/_build.gradle
exclude tomcat via global config according to offical boot documentation
close #2948
=> exclude tomcat from global config

generators/client/templates/src/main/webapp/app/account/password/_password-strength-bar.directive.js
Switched from the attrs.passwordToCheck into a scope value, which is a proper way to pass attributes in directives as it isolates the scope.
=> Refactoring password-strength-bar directive

generators/client/index.js, generators/client/templates/src/main/webapp/app/account/settings/_settings.controller.js, generators/client/templates/src/main/webapp/app/account/settings/settings.html, generators/client/templates/src/main/webapp/app/admin/configuration/_configuration.controller.js, generators/client/templates/src/main/webapp/app/admin/configuration/_configuration.service.js, generators/client/templates/src/main/webapp/app/admin/configuration/_configuration.state.js, generators/client/templates/src/main/webapp/app/admin/health/_health.controller.js, generators/client/templates/src/main/webapp/app/admin/health/_health.modal.controller.js, generators/client/templates/src/main/webapp/app/admin/health/_health.service.js, generators/client/templates/src/main/webapp/app/admin/health/_health.state.js, generators/client/templates/src/main/webapp/app/admin/metrics/_metrics.controller.js, generators/client/templates/src/main/webapp/app/admin/metrics/_metrics.modal.controller.js, generators/client/templates/src/main/webapp/app/admin/metrics/_metrics.service.js, generators/client/templates/src/main/webapp/app/admin/metrics/_metrics.state.js, generators/client/templates/src/main/webapp/app/admin/tracker/_tracker.controller.js, generators/client/templates/src/main/webapp/app/admin/tracker/_tracker.service.js, generators/client/templates/src/main/webapp/app/admin/tracker/_tracker.state.js, generators/client/templates/src/main/webapp/app/admin/user-management/_user-management-dialog.controller.js, generators/client/templates/src/main/webapp/app/admin/user-management/_user-management.controller.js, generators/client/templates/src/main/webapp/app/blocks/handlers/_state.handler.js, generators/client/templates/src/main/webapp/app/components/language/_language.controller.js, generators/client/templates/src/main/webapp/app/components/language/_language.service.js, generators/client/templates/src/main/webapp/app/layouts/navbar/navbar.html, generators/client/templates/src/main/webapp/app/services/auth/_auth.service.js, generators/client/templates/src/main/webapp/app/services/auth/_auth.session.service.js, generators/client/templates/src/main/webapp/app/services/auth/_principal.service.js, generators/client/templates/src/test/javascript/e2e/admin/_administration.js, generators/client/templates/src/test/javascript/spec/app/admin/health/_health.controller.spec.js
Fix #2921.
I renamed services that could clash with user-generated services with Jhi prefix. Also renamed Health and Metrics Controllers into HealthCheck and MetricsMonitoring as suggested by @deepu105.
=> Renaming clashing services and controllers

generators/client/index.js, generators/client/templates/src/main/webapp/app/blocks/config/_translation-storage.provider.js, generators/client/templates/src/main/webapp/app/blocks/config/_translation.config.js, generators/client/templates/src/main/webapp/app/blocks/config/_translation.storage.js, generators/client/templates/src/main/webapp/app/components/language/_language.service.js, test/test-creation.js
Language cookie should be cleared if the language is not installed in the running jhipster application.
This is to prevent a cryptic error when running two different jhipster applications with different language support localhost.
e.g. see atomfreds comment https://github.com/jhipster/generator-jhipster/pull/2970#issuecomment-191408930
=> Reset language cookie if language is not installed

generators/server/templates/src/main/java/package/config/_JHipsterProperties.java, generators/server/templates/src/main/java/package/config/_SecurityConfiguration.java, generators/server/templates/src/main/java/package/security/_CustomPersistentRememberMeServices.java, generators/server/templates/src/main/resources/config/_application.yml, generators/server/templates/src/test/resources/config/_application.yml
camel case generated java class and variable
changed 
- class name: Rememberme to RememberMe  
- variable name: rememberme to rememberMe
=> correct camel casing of class and variable - RememberMe

generators/client/templates/_eslintrc.json, generators/client/templates/gulpfile.js
Fix #3105 
As suggested by @gmarziou in [this discussion](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jhipster-dev/DqVSbTskrjw/cipLhz6KAgAJ), I updated the eslint rule to check only local variables and to not check function arguments.
I also fixed an unused gulp require `gulp-util` when protractor wasn't selected as a test framework.
=> Fix unused variables injected in angular controllers and unused gulp require

generators/server/templates/_pom.xml
Run 'gulp build' from maven with --no-notification option to avoid blocking on Windows.
Fix #3110
=> Run 'gulp build' from maven with --no-notification option

generators/server/index.js, generators/server/templates/src/main/java/package/config/_GatewayConfiguration.java, generators/server/templates/src/main/java/package/config/apidoc/_SwaggerConfiguration.java, generators/server/templates/src/main/java/package/gateway/responserewriting/_SwaggerBasePathRewritingFilter.java, generators/server/templates/src/test/java/package/gateway/responserewriting/_SwaggerBasePathRewritingFilterTest.java
Fix #3046 
Don't rely anymore on a hard-coded path-mapping to access the micro-services API throught Swagger UI. This is achieved by rewriting the "Base URL" (see the bottom part of Swagger UI) when the JSON swagger-docs is passing through the gateway.
=> Gateway filter to rewrite microservices Swagger URL path

generators/server/templates/src/main/java/package/security/_CustomPersistentRememberMeServices.java
If the jhipsterproperties class gets refactored (i.e. name change), then the CustomPersistentRememberMeServices would not work as it was looking for the properties in a kind of hard-coded way. 
By injecting the JHIpster properties to the constructor method, we have a cleaner way of creating the CustomPersistentRememberMeServices instance without hard-coded properties.
=> added injection of jhipsterproperties to CustomPersistentRememberMeServices

generators/entity/index.js
Fix #2987.
I worked with @PierreBesson on this. We updated the entity generator by following this use case : 
1. Create an entity in a microservice app with the `--skip-client` flag. We added a "microserviceName" field in the entity JSON. This is only added to the entities generated in a microservice. We do this because we need this information to prefix the service name to the URL in angular services.
So the gateway's client entity knows to request the microservice at `/app1/api/foos` and not at `/api/foos`.
2. Create an entity in the gateway with` --skip-server` flag.
3. You will be asked if you to generate the entity from a microservice. You will have to put the path of the microservice folder (eg :` /home/ippon/microservice`) and it will copy and paste Foo.JSON from the microservice …
=> Generate front-end code on Gateway from microservice entity

generators/entity/templates/src/main/webapp/app/services/_entity-search.service.js, generators/entity/templates/src/main/webapp/app/services/_entity.service.js
Applications with uppercased characters caused a 404 error in the gateway because the gateway request was for example `myappSQL/api/...` instead of `myappsql/api/...`.
So I added `toLowerCase()` after the microserviceName variable in entity services.
=> Add 'toLowerCase()' to microserviceName in entity services

generators/client/templates/_package.json, generators/client/templates/gulpfile.js, generators/client/templates/src/main/webapp/app/blocks/interceptor/_auth.interceptor.js, generators/client/templates/src/main/webapp/app/services/auth/_auth.jwt.service.js
While working on an application without protractor, I saw that eslint throwed some errors about unused imports. 
So I removed the yargs import if the application is not using protractor and two other eslint errors in the same time (one indent and one "use angular.isDefined instead of !== undefined").
I also removed the gulp-util from package.json if the app doesn't use protractor.
=> Removing unused Gulp imports and fix eslint errors

generators/entity/index.js, generators/entity/templates/src/test/gatling/simulations/_EntityGatlingTest.scala
Gatling tests weren't generated when the user wanted to generate an entity from a microservice if the user set the `--skip-server` flag. If this flag wasn't set, it generated the gatling tests but URL were wrong (no microservice name before `/api/...`).
Now it properly adds the microservice name prefix to the URL on remote entities gatling tests.
=> Generate Gatling tests for gateway entities from remote microservice

generators/server/index.js
When application type is microservice, default server port should be 8081.
=> For microservice, default server port should be 8081

generators/server/templates/src/main/resources/config/_application-prod.yml, generators/server/templates/src/main/resources/config/_bootstrap-dev.yml, generators/server/templates/src/main/resources/config/_bootstrap-prod.yml
Use app name for a gateway file on config server rather than always "gateway" which does not work when you have multiple gateways.
Fix #3161
=> Use app name for a gateway file on config server

generators/server/templates/src/main/java/package/web/rest/_AccountResource.java
I've implemented the mentioned workaround and checked some other endpoints for missing plain text response type.
update #3127
=> correct response types in account resource

generators/server/templates/_pom.xml
I get the following deprecated warning when running `mvn clean install`
```
[INFO] --- maven-sortpom-plugin:2.3.1:sort (default) @ forskolenatet ---
[WARNING] DEPRECATED: The SortPom plugin has moved to <groupId>com.github.ekryd.sortpom</groupId> <artifactId>sortpom-maven-plugin</artifactId>
[WARNING] DEPRECATED: Please update the plugin reference
```
the sortpom maven plugin seems to be renamed and moved to github so I updated the pom.xml
=> update sortpom maven plugin

generators/cloudfoundry/index.js
use ``./gradlew`` on linux/mac and just ``gradlew`` on windows. 
@jdubois  @deepu105 Why is the build command generated again (and without ``-Pprod``) when setting up the push command? It is not used afterwards as far as I can tell.
=> differentiate between win32 and linux/mac environment when running

generators/server/templates/_pom.xml
The "jhipster/" prefix should not be added to users docker images.
They are now generated without prefix.
=> remove jhipster prefix for maven docker build

generators/app/USAGE, generators/client/USAGE, generators/import-jdl/USAGE, generators/import-jdl/index.js, generators/server/USAGE, package.json
I would like to keep this as the first iteration of the sub generator (its based on jhuml 1.6.1), this works with JDL files from JDL studio well and I have tested it with few combinations
TODO:
1. Need to move to jhipster-domain-language module instead of JHUML 1.6.1
cc @MathieuAA lets add the feature first so it 3.0 has it and we will move to the new lib when its ready as an enhancement.
fix #3118
=> Add import-jdl sub generator

generators/server/templates/gradle/_liquibase.gradle, generators/server/templates/gradle/_profile_dev.gradle, generators/server/templates/gradle/_profile_prod.gradle, generators/server/templates/src/main/java/package/config/_Constants.java, generators/server/templates/src/main/java/package/config/_DatabaseConfiguration.java, generators/server/templates/src/main/java/package/config/apidoc/_GatewaySwaggerResourcesProvider.java, generators/server/templates/src/main/java/package/config/apidoc/_SwaggerConfiguration.java, generators/server/templates/src/main/java/package/config/liquibase/_AsyncSpringLiquibase.java
profile switches to disable liquibase/swagger
For jar|war it can be added as `--spring.profiles.active=prod|dev,no-liquibase|no-swagger`
For Gradle local bootRun `./gradlew -Pno-liquibase -Pno-swagger` or `./gradlew -Pprod -Pno-liquibase -Pno-swagger`
Can someone check for maven local run 
part of #3151 but no-cache seems to be tougher than I thought will do it as a seperate PR
=> Profile switches for no-swager and no-liquibase

generators/entity/index.js, generators/entity/templates/src/main/webapp/app/entities/_entity-management.state.js
Fix #3192.
This variable caused bugs when using different DB types in microservice architecture. For example, if the gateway has an SQL DB and a microservice a Mongo one, the type in gateway front-end generated code will be wrong.
Moreover I didn't understand the point of validating the id using a regex (or a type) in client part. It was made by @andidev in b071e5bbb68ca821beb00d8d0c91d111c099ef93 so if you have any suggestion please tell me
=> Remove entityUrlType variable in entity subgen

generators/docker-compose/index.js, generators/docker-compose/templates/_docker-compose.yml, generators/docker-compose/templates/central-server-config/_application.yml, generators/docker-compose/templates/elk.yml, generators/docker-compose/templates/log-monitoring/log-config/logstash.conf, generators/docker-compose/templates/log-monitoring/log-data/.gitignore, generators/docker-compose/templates/registry.yml
Fix #3193 .
Just a migration of the [Jhipster docker compose generator](https://github.com/jhipster/generator-jhipster-docker-compose). 
For now it works with SQL and Mongo databases, I got some trouble with Cassandra so if someone can help on this I'd be pleased.
As we discussed, shall I remove the question about profile as docker will be probably used to deploy application in production profile ?
=> Add docker-compose sugenerator

generators/entity/templates/src/test/gatling/simulations/_EntityGatlingTest.scala
During performance tests I've got many bugs thrown by Gatling about "undefined variables". That's because even if a request failed, for example "create foo", the user was pursuing the scenario and trying to do "get created foo" even if it wasn't created.
So I added `exitHereIfFailed` in important requests (authentication and create entity) to make the user leaves if the request is not successful.
=> Improve Gatling tests

generators/server/templates/src/main/java/package/domain/_AbstractAuditingEntity.java
Removed unnecessary @NotNull annotations in fields with @CreatedBy and @CreatedDate
=> #3135 AbstractAuditEntity does not need to have @NotNull

generators/client/templates/src/main/webapp/app/account/reset/finish/reset.finish.html
This will correctly hide the password reset form on a successful password reset.
=> Add missing vm to password reset HTML

generators/server/templates/src/main/java/package/config/_WebConfigurer.java
I believe this (finally) addresses [#3220](https://github.com/jhipster/generator-jhipster/issues/3220) properly.
Tested cases:
- running in IDE
- running with `mvn spring-boot:run`
- running with `java -jar target/foo.war` from an abitrary cwd
- deploying to external servlet container (tomcat 8)
=> Detect properly if setDocumentRoot will work

generators/client/templates/gulpfile.js
I just noticed that the `languages` gulp task doesn't work if `.yo-rc.json` lists only a single language.
It turns out that the glob that was used, `angular-i18n/angular-locale_{...}` doesn't match anything if there is only a single item between the braces! Maybe this is a bug in `glob-stream`, it certainly seems unexpected behaviour to me.
Anyway, this PR remedies the situation by using an array instead of a glob.
=> Fix i18n copy for the case of a single language

app/templates/_build.gradle, app/templates/_profile_dev.gradle, app/templates/_profile_fast.gradle, app/templates/_profile_prod.gradle, app/templates/_yeoman.gradle
``processResources`` doesn't depend on ``gulp build`` anymore. Dev profile excutes ``ngConstansts:dev`` to make sure the constant are on ``dev`` mode even when ``prod`` was used before. 
close #3204
=> gulp build is not executed when running in dev mode

generators/entity/templates/src/main/webapp/app/services/_entity.service.js
When no date field is found in the entity, DateUtils is not injected into the factory but is still found in the function parameters.
=> Only inject DateUtils into angular factory when entity has a date field

travis/configstore/insight-generator-jhipster.json, travis/configstore/insight-yo.json, travis/install/02-install-jhipster-stack.sh, travis/samples/app-cassandra/.yo-rc.json, travis/samples/app-default-from-scratch/.yo-rc.json, travis/samples/app-gateway/.yo-rc.json, travis/samples/app-gradle/.yo-rc.json, travis/samples/app-hazelcast-cucumber/.yo-rc.json, travis/samples/app-jwt/.yo-rc.json, travis/samples/app-microservice/.yo-rc.json, travis/samples/app-mongodb/.yo-rc.json, travis/samples/app-mysql/.yo-rc.json, travis/samples/app-oauth2/.yo-rc.json, travis/samples/app-psql-es-noi18n/.yo-rc.json, travis/samples/app-social-websocket/.yo-rc.json, travis/scripts/01-generate-project.sh, travis/scripts/05-run.sh
@jdubois : I made some change, so it will be easy for you to filter/track these projects by baseName / rememberMeKey
- change all baseName to `travis*`
- all `"rememberMeKey": "f19f0827c622eb9b81f5227a869ccd44932d78eb"`
- add no-insight json to travis build
We already use [`yo jhipster --force --no-insight`](https://github.com/jhipster/generator-jhipster/blob/master/travis/scripts/01-generate-project.sh#L14) but to be sure for JHipster stats
=> Travis: change baseName and force no insight

generators/docker-compose/index.js
Fix #3238 
Now putting the relative path to the dockerfile in `context` property.
=> Fix Cassandra Dockerfile path in docker-compose subgenerator

travis/scripts/01-generate-project.sh
The dependencies has been updated here : https://github.com/jhipster/jhipster-travis-build/issues/1
So now, the phantomjs cache is correct, no need to delete before yo jhipster
The main issue was travis failed randomly to download phantomjs-2.1.1 :
```yaml
Error requesting archive.
Status: 403
Request options: {
"uri": "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2",
"encoding": null,
"followRedirect": true,
"headers": {
"User-Agent": "npm/2.14.20 node/v4.4.1 linux x64"
},
"strictSSL": true
}
Response headers: {
"x-amz-request-id": "CE53C953C448DC25",
"x-amz-id-2": "M7eyD4paNl+LiHllYkA/OKdrhJvo+IyU93irKSeod1w3s7dDjvzXZMsL8gVQHZme1fwIiK3IGq4=",
"content-type": "application/xml",
"transfer-encoding": "chunked",
"date": "Wed, 23 Mar 2016 08:07:17 GMT", …
```
=> Travis: keep phantomjs prebuilt

travis/install/04-cache.sh
Travis provides by default: phantomjs 2.0.0
We use phantomjs 2.1.1
Fix https://github.com/jhipster/jhipster-travis-build/issues/1
=> Travis phantomjs cache

generators/server/templates/src/main/docker/_Dockerfile
It's to save ~40MB on every Docker image
Before:
```shell
REPOSITORY          TAG                 IMAGE ID            CREATED              SIZE
jhigateway          latest              227cf8eb40c0        About a minute ago   296.4 MB
mspsql              latest              4937e453f3b5        7 minutes ago        288.5 MB
msmongo             latest              78de03b54d80        7 minutes ago        264.6 MB
```
After:
```shell
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
jhigateway          latest              c6a8058ce055        11 seconds ago      259.4 MB
mspsql              latest              9f10b026c8f7        4 minutes ago       251.3 MB
msmongo             latest              bb1c3f6a53fb        5 minutes ago       227.4 MB
```
=> Docker-compose: use jre-alpine instead of jdk-alpine 

generators/server/templates/src/main/java/package/config/_GatewayConfiguration.java, generators/server/templates/src/main/java/package/config/_JHipsterProperties.java, generators/server/templates/src/main/java/package/config/apidoc/_GatewaySwaggerResourcesProvider.java, generators/server/templates/src/main/java/package/config/apidoc/_SwaggerConfiguration.java, generators/server/templates/src/main/resources/config/_application-dev.yml, generators/server/templates/src/main/resources/config/_application-prod.yml, generators/server/templates/src/test/resources/config/_application.yml
This is as per request by @cbornet earlier.
swagger can be enabled or disabled from `application-*.yml` as well. its disabled by default in production to retain current behavior
so if someone wants swagger in production they can enable it by setting `jhipster.swagger.enabled: true` and then they can use the `no-swagger` switch for finer control at run time
=> enable swagger via application property

generators/server/templates/src/main/java/package/domain/_User.java
Adding nullable to the email column annotation makes the User.java class match the initial liquibase schema.  
Fix #3261
=> Fix mvn liquibase:diff goal

generators/client/templates/src/main/webapp/app/blocks/interceptor/_auth-expired.interceptor.js
If a user enters the wrong password on the way to a secured state, the login window reappears but $rootScope.previousStateName changes to 'accessdenied'
This change prevents prevents the 'accessdenied' state from being stored in the previousStateName.  It fixes the flow so that if a user enters an incorrect password but then fixes his mistake on another login attempt, he is correctly redirected to the destination state.
=> Fix auth-expired redirect after one failed login attempt

generators/docker-compose/templates/central-server-config/_application.yml
Add a trailing slash to fix it. Same as here: https://github.com/jhipster/jhipster-registry/pull/27
=> fix configserver.status URL so that it can be opened in a browser

generators/client/index.js, generators/docker-compose/index.js, generators/server/index.js, generators/server/templates/src/main/docker/_app.yml, generators/server/templates/src/main/docker/_mongodb.yml, generators/server/templates/src/main/docker/mongodb/MongoDB.Dockerfile, generators/server/templates/src/main/docker/mongodb/scripts/init_replicaset.js
As the title says, I'm adding a cluster support when the user wants to use a MongoDB database. I used [this guide](https://sebastianvoss.com/docker-mongodb-sharded-cluster.html) to help me configure MongoDB.
* Create a replicaset of X node
* Create a server config node
* Add a shard of this replicaset into the Mongo router (`mongos`)
1. Create an app with MongoDB Cluster Mode (I added a question)
2. Build the image : `docker-compose -f src/main/docker/mongo.yml build`
3. Run the DB : `docker-compose -f src/main/docker/mongo.yml up -d `
4. Scale the mongodb-node : `docker-compose -f src/main/docker/mongo.yml scale appname-mongodb-node=3`
Please note that[ you have to use an odd number of node](https://docs.mongodb.org/manual/core/replication-introduction/).
5. Init the replicaset by …
=> Cluster Mode for MongoDB

generators/heroku/index.js
This PR fixes a few problems with the Heroku generator, and likely resolves #3248. Changes include:
* Put both `productionBuild` and `productionDeploy` in the `end` priority. This was needed because something was causing the `copyHerokuFiles` to run in-line with `productionBuild`.
* Fix a bug when adding and existing Heroku app to the JHipster app's git remotes.
=> Various Heroku fixes

generators/heroku/index.js, generators/heroku/templates/_Procfile, generators/heroku/templates/_application-heroku.yml, generators/heroku/templates/_bootstrap-heroku.yml
This PR adds basic support for deploy JHipster microservices to Heroku. It adds the following changes:
* Detects if the app has a database, and added the `HerokuDatabaseConfiguration.java` only if it does.
* Detects if the applicationType is "microservice" or "gateway" and prompts for the Registry URL if it is either.
=> Fix #3279: Added support for Heroku microservices

generators/server/templates/src/test/java/package/_AbstractCassandraTest.java, travis/scripts/02-generate-entities.sh
when starting the embedded cassandra for the tests, also apply all the cql scripts, *_added_entity_*.cql generated by the jhipster:entity generator
=> Fix #3290 - automaticaly pick all CQL scripts

generators/app/index.js, generators/client/index.js, generators/modules/index.js
Suggested in  #3054 by @deepu105 and @kkorada.
Now the user can pass the --jhi-prefix flag in the main generator : `yo jhipster --jhi-prefix foo` instead of passing it in the client sub-generator.
=> Add --jhi-prefix option in main generator

generators/client/templates/_bower.json, generators/client/templates/gulpfile.js
Not sure that this is okey to do but I cant find where angular-scenario is used and it works without it and it is deprecated since angular 1.2. Though lets see if the CI builds pass first.
Could someone comment on this if this is no problem? If it's a problem please close this issue.
=> remove angular-scenario in bower.js from devDependencies since it is deprecated

generators/server/templates/src/main/docker/_mysql.yml
@jdubois saw a warning when the mySQL docker container was starting, saying that "SSL is not configured".
This command sets an unencrypted connection, that's what JHipster does (all datasources have the useSSL=false parameter in their url) so it's fine.
=> Adding skip-ssl option in mysqld docker command

generators/docker-compose/index.js
Because of my PR #3301 the docker-compose subgenerator was exiting after asking for apps if there was no MongoDB apps in the directory.
I was calling `return` after an `async()` call, so now I do this `return` before and it works !
Sorry for this
=> Fixing Docker Compose subgen if no MongoDB applications

generators/languages/templates/src/main/webapp/i18n/pt-br/user-management.json
Fixing a json syntax error in the webapp/i18n/pt-br/user-management.json (a 'd' place in an incorrect place).
=> Fix a json syntax error in the user-management pt-br i18n file 

generators/languages/index.js
Fix #3334
Removing currentLanguages from if block before prompting (or not) the user for the languages to install as suggested by @andidev
=> Fix broken language subgenerator

generators/docker-compose/index.js
The docker compose subgenerator was picking the incorrect service `appname-mongodb`. It was picking the one in the `mongodb.yml` file instead of picking the one in the `mongodb-cluster.yml` one.
=> Fix Docker compose subgenenrator when using MongoDB Cluster

generators/client/index.js, generators/client/templates/src/main/webapp/app/admin/user-management/_user-management-dialog.html, generators/client/templates/src/main/webapp/app/blocks/handlers/_state.handler.js, generators/entity/index.js, generators/modules/index.js, generators/server/index.js
Doing `=== null` can cause problems as null doesn't equals `undefined` in some cases.
In our case, we have to do `=== undefined` to check if a variable is defined or not. `=== null` has to be used only when we explicitly set a variable to `null`.
=> Replacing null triple equal comparisons by undefined

generators/server/templates/src/main/java/package/config/_SecurityConfiguration.java
Requires authentication to access all non mapped URIs so that proxified service APIs are protected.
Fix #3336
=> Requires authentication for proxified service APIs on Gateways

generators/server/templates/src/main/resources/config/_bootstrap-prod.yml
Now that @jdubois introduced retries to wait for the config server, having a commented out URI in bootstrap-prod.yml seems like a bad idea as the app will stay blocked and display no error message if the user forget to set it.
=> remove comment for config server bootstrap-prod uri

generators/server/templates/_pom.xml
mvn -Pprod clean should not delete node_modules folder for build performance reason and to be consistent with gradle.
=> mvn -Pprod clean should not delete node_modules folder

generators/entity/index.js, generators/entity/templates/src/main/java/package/domain/_Entity.java, generators/entity/templates/src/main/java/package/repository/_EntityRepository.java, generators/entity/templates/src/main/java/package/web/rest/dto/_EntityDTO.java, generators/entity/templates/src/main/java/package/web/rest/mapper/_EntityMapper.java, generators/entity/templates/src/main/webapp/app/entities/_entity-management-detail.html, generators/entity/templates/src/main/webapp/app/entities/_entity-management-dialog.controller.js, generators/entity/templates/src/main/webapp/app/entities/_entity-management-dialog.html, generators/entity/templates/src/main/webapp/app/entities/_entity-management.html
Hello,
I've changed all declarations and uses of `<% someEntityName %>s` by `<% someEntityNamePlural %>`. Plural version of entity or relation name is calculated before in js with **pluralize**.
This PR is a completion of https://github.com/jhipster/generator-jhipster/pull/2719
Please feel free to comment and criticize.
Thanks,
=> Better management of plural in relations

generators/docker-compose/templates/_docker-compose.yml
The `&` character where espaced into `&amp;` which caused issues in the  datasource url envirnoment variable (ie: `SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/sample?useUnicode=true&characterEncoding=utf8&useSSL=false`)
Do I win the award of the smallest PR in the world ? :smile:
=> Fix escaped characters in generated docker compose YML

generators/client/templates/src/main/webapp/app/layouts/navbar/navbar.html
...since it makes the navbar flicker when angular-animate module is added. The collapse class is automatcally added by the uib-collapse.
=> remove collapse css class from navbar div 

generators/client/templates/_bower.json
Use dasherizedBaseName for name in bower.json so an app name with uppercased letters like "gatewayIssue" turns into "gateway-issue".
Fix #3392
=> Name in bower.json should not contain uppercased letters

generators/docker-compose/index.js, generators/docker-compose/templates/_docker-compose.yml
Fix #3380 
So now we can select monolithic apps in the subgenerator docker-compose. If it detects that there are more than 1 gateway or monolithic, it map each app port starting from 8080.
At the end it shows the mapping to inform the user about the URL of each app.
As we map the port, we can't scale the gateway or monolithic app for the moment.
=> Support monolithic apps in docker-compose subgenerator

generators/server/templates/src/main/java/package/config/_LoggingConfiguration.java
Fix #3364 issue for stacktraces over 8K sent through an UDP socket.
=> add a length limit for logstash-encoder forwarded stacktraces fix #3364

generators/docker-compose/index.js
Make the docker-compose subgen for monolith automatically activate logs and metrics monitoring if the ELK option as been selected. Those are the same props that we set by default for microservices using the config server.
=> add monitoring props in monolith docker-compose env variables

generators/server/templates/src/main/java/package/service/_MailService.java
SONAR: If a private field is declared but not used in the program, it can be considered dead code and should therefore be removed. This will improve maintainability because developers will not wonder what the variable is used for.
=> Remove this unused "from" private field.

generators/server/templates/src/main/java/package/service/_MailService.java
Define a constant instead of duplicating this literal "baseUrl" 3 times.
Define a constant instead of duplicating this literal "user" 4 times.
SONAR: Duplicated string literals make the process of refactoring error-prone, since you must be sure to update all occurrences. On the other hand, constants can be referenced from many places, but only need to be updated in a single place.
=> Define a constant instead of duplicating this literal "user" 4 times.

generators/server/templates/src/main/docker/_Dockerfile
This new ENV in Dockerfiles `JHIPSTER_SLEEP` can be used to wait before starting an application. If not used, same behavior like currently.
With docker engine: -e JHIPSTER_SLEEP=10
With docker-compose: in "environment" session
=> Add env var to wait before starting a Docker container

generators/entity/templates/src/main/webapp/app/entities/_entity-management-dialog.html
The id does not provide any meaningful information in the entity creation dialog as the actual database id has not been assigned yet anyway.
fix #3401.
=> hide id field while creating an entity

generators/client/templates/src/test/javascript/_karma.conf.js
The current Karma config minifies JS and adds cover information. However, if it's run from the command line with the --debug option it would help if the developer if the JS files remain readable.
Sample command line start:
```
./node_modules/karma/bin/karma start src/test/javascript/karma.conf.js --debug
```
It might be worthwhile to add this to this page too:
http://jhipster.github.io/running-tests/
=> Disable Karma JS minification to help debugging if it's run with --debug

generators/client/index.js, generators/server/index.js
Currently the --skip-user-management flag isn't available when generating client-only or server-only. Please review as this might not be the correct way to add this option.
=> Allow --skip-user-management when using client and server subgenerators

generators/heroku/templates/_Procfile, generators/heroku/templates/_application-heroku.yml
For microservice applications:
* Set the `eureka.instance.hostname` and `non-secure-port` automatically
* Set `eureka.instance.prefer-ip-address` to false 
For gateway applications:
* Add `-Xmx256m` to the default `Procfile`
I've found that the gateway uses very little heap and a lot of off-heap memory (probably for buffers and streams). Setting max heap lower will allow more room for off-heap as to not exceed the quota on a free dyno (i.e. prevents [R14 errors](https://devcenter.heroku.com/articles/error-codes#r14-memory-quota-exceeded))
=> Better microservice and gateway config for Heroku profile

generators/server/templates/gradle/_profile_dev.gradle
don't add gulp/node tasks to gradle dev profile when client is not generated
close #3442
=> respect skipClient option

generators/server/templates/_build.gradle, generators/server/templates/_gradle.properties, generators/server/templates/gradle/_liquibase.gradle, generators/server/templates/gradle/_mapstruct.gradle, generators/server/templates/gradle/_profile_dev.gradle, generators/server/templates/gradle/_profile_prod.gradle
Instead of defining seperate ``group``, ``module`` and ``version`` for each dependency we can now use the simplified version ``"group:module:version"``. With that change it is easy to copy and paste dependency from maven central.
Also see https://github.com/jhipster/generator-jhipster/pull/3424
=> use simplified gradle dependency definition

generators/server/templates/_build.gradle
``mavenLocal`` was not used for builds (only for buildScripts) such that each dependency was downloaded again even when it is available already in local maven repository (e.g. ``~/m2``).
=> share .m2 dependencies with gradle build

generators/server/templates/_build.gradle
The build was broken on master for microservices and gateways as I had forgotten to also add the spectator depency for gradle.
=> add missing spectator dependency for microservices gradle build

generators/server/templates/_build.gradle
On the master, a dependency is missing when generating the app for gradle and cassandra
```
Could not resolve all dependencies for configuration ':testCompileClasspath'.
> Could not find org.cassandraunit'cassandra-unit-spring:2.1.3.1:.
Required by:
com.mycompany.myapp:mono-gradle-cass:0.0.1-SNAPSHOT
```
It's a typo in the group name declaration.
The first commit add a travis test case.
I'll add a second commit with the fix after the CI shows the failure.
=> missing dependency with gradle and cassandra

generators/server/templates/_travis.yml
#3485 
.travis.yml file is currently being generated with Node.js version
0.12, which is outdated and does not build correctly. Current LTS
version is 4.4.3
=> Update Node.js version on generated .travis.yml

generators/server/templates/_build.gradle
Surrounding the cucumber sections of the `build.gradle` file with conditionals
=> Fix #3482: Clean Cucumber task from `build.gradle`

generators/server/index.js, generators/server/templates/src/main/resources/config/cql/changelog/README.md, generators/server/templates/src/test/java/package/_AbstractCassandraTest.java, generators/server/templates/src/test/java/package/_CassandraKeyspaceUnitTest.java
When generating a microservice with Cassandra database, tests are failing:
- the cql/changelog folder is empty and causes an NPE when trying to iterate in the scripts when starting the cassandra unit cluster
- the User table does not exist for a microservice app, therefore CassandraKeyspaceUnitTest#shouldHaveUserTableCreated() test does not work anymore
=> Fix cassandra microservice tests

generators/client/templates/src/main/webapp/app/admin/user-management/_user-management-dialog.html
Currently user-management.state.js sets user.id to null on the /new state entry, making the comparison `user.id === undefined` false.  This changes the comparison to `user.id === null` which will return the correct value.
This issue comes from #3343.  This comparison to null is appropriate because we explicitly set user.id to null (meeting the condition stated in the referenced PR).
=> fix activated checkbox to be disabled when creating a user

generators/client/templates/src/main/webapp/app/admin/audits/_audits.service.js, generators/client/templates/src/main/webapp/swagger-ui/_index.html, generators/server/index.js
When using uaa authentication:
* MicroserviceSecurityConfiguration needs to be generated for gateways (otherwise requests to "health", "configprops", etc. are unauthorized. The gateway is also a resource server (like microservice applications) in this case.
* Add token for swagger requests (authorization 'uaa' was left out)
* Call uaa server for audits (since audits are on the uaa server, requests must go to /uaa/api/audits instead of api/audits)
=> Fix some uaa bugs

generators/client/templates/src/main/webapp/app/blocks/interceptor/_auth-expired.interceptor.js, generators/client/templates/src/main/webapp/app/components/login/_login.controller.js, generators/client/templates/src/main/webapp/app/services/auth/_auth.service.js
https://github.com/jhipster/generator-jhipster/issues/3454
Looks like the Auth.logout() is not actually required:
- If we are already logged out the previous state is the one we want to get back to - do not erase it.
- If we are just hitting logout button, the sessionStorage is already empty anyway, nothing to erase.
=> Fix 3454 Clean up Auth JS services and remove previous state erase in Auth.logout()

generators/server/templates/src/main/java/package/config/_WebConfigurer.java
[Feature] Maven multi module project issue with resolving path during startup #3431 
All is need in multi module project is to resolve intermediate path. Originally jhipster will look into core module only.
=> Fix Maven multi module project issue with resolving path during startup #3431

generators/client/templates/src/main/webapp/app/admin/user-management/_user-management-detail.html
user-management-detail.html page not displaying the authorities due to missing 'vm.' on the code
I'm using 3.1.0, this might be the issue on 3.0.0 too.
Submitted a PR
=> Update _user-management-detail.html to fix missing 'vm.'

generators/server/templates/_pom.xml
Since the move to `frontend-maven-plugin` was merged, I noticed Eclipse/STS shows an error. I just investigated a bit and it turns out that the lifecycle mapping metadata section of `pom.xml` must be slightly changed to stop the complaints.
=> Fix lifecycle mapping in Eclipse/STS

generators/languages/templates/src/main/webapp/i18n/cs/_global.json, generators/languages/templates/src/main/webapp/i18n/en/_global.json
The app checks if a new password is at least 4 characters long, but the message says 5. Fixed for EN and CS.
Also fixed minor typos in CS.
=> Fixed new password and email validation messages (EN, CS)

generators/client/templates/gulpfile.js, generators/client/templates/src/main/webapp/_index.html
@jdubois please see if the steps are ok. @jhipster/developers let me know if any more steps needs to be added.
The gulp task is required only if we dont want the content in html at all, else angular takes care of not showing the content if gulp install runs successfully
fix #3541
=> add default troubleshooting steps fix #3541

generators/app/index.js, generators/generator-base.js
This shows a nice notification to user when there is an updated JHipster version available via npm
fix #3555
=> notify updated version availability

generators/server/templates/src/main/docker/_cassandra.yml, generators/server/templates/src/main/docker/cassandra/scripts/_autoMigrate.sh, generators/server/templates/src/main/docker/cassandra/scripts/_execute-cql.sh, generators/server/templates/src/main/resources/config/cql/create-tables.cql
This is a follow-up of the discussion with @pascalgrimaud and @jdubois  in #3288
This pull request adds a table to track the cql scripts executed in cassandra and avoid run them twice, similar to what is done by liquibase/flyway.
The `auto-migrate.sh` and `execute-cql.sh` scripts use the `schema_version` table to only run cql scripts from the changelog folder once.
If a cql script is changed after being executed, an error will be reported.
1. Start the docker container for cassandra with docker-compose:
- `docker-compose -f src/main/docker/cassandra.yml up -d`
2. Add some cql scripts in the changelog folder
3. Execute the cql scripts (see below)
There are now 3 ways to execute the cql scripts without restarting the cassandra cluster:
- Run the automatic migration from a docker container: …
=> schema management for Cassandra

generators/server/templates/src/main/java/package/_Application.java, generators/server/templates/src/main/java/package/_ApplicationWebXml.java, generators/server/templates/src/main/java/package/config/_WebConfigurer.java, generators/server/templates/src/main/resources/config/_application.yml
This is based on the discussion in #3224 
This sets a default profile properly when no profile is passed as `--spring.profiles.active` or `-Dspring.profiles.active` set in `JAVA_OPTS` or as `-Pprod` in build.
I have tested this from IDE, as executable war, via boot run and deployed in tomcat. This seems to work properly.
I have also set the placeholder in `application.yml` so that it can be replaced by the build tool to set an active profile while packaging and that also works in all the above mentioned methods.
Now additional work needs to be done to do the replacement of the value in the file moved to `target|build` folder during `mvn package` or `gradle bootRepackage | gradle war` But I guess that can be done as another PR.
@erikkemperman since ill be away for few days you can give it …
=> Set default profile

generators/entity/index.js, generators/entity/templates/src/main/java/package/domain/_Entity.java, generators/entity/templates/src/main/java/package/repository/_EntityRepository.java, generators/entity/templates/src/main/java/package/web/rest/dto/_EntityDTO.java, generators/entity/templates/src/main/resources/config/cql/changelog/_added_entity.cql, generators/entity/templates/src/main/webapp/app/entities/_entity-management-detail.html, generators/entity/templates/src/main/webapp/app/entities/_entity-management-dialog.controller.js, generators/entity/templates/src/main/webapp/app/entities/_entity-management-dialog.html, generators/entity/templates/src/main/webapp/app/entities/_entity-management.html, generators/entity/templates/src/main/webapp/app/services/_entity.service.js, generators/entity/templates/src/test/java/package/web/rest/_EntityResourceIntTest.java, generators/server/index.js, generators/server/templates/src/main/java/package/config/_JacksonConfiguration.java, generators/server/templates/src/main/java/package/config/cassandra/_CassandraConfiguration.java, generators/server/templates/src/main/java/package/config/cassandra/_CustomZonedDateTimeCodec.java, generators/server/templates/src/main/java/package/config/cassandra/_package-info.java
LocalDate is mapped to the new "date" CQL type (cassandra v3 only)
ZonedDatetime is mapped to "timestamp" instead of ```tuple<timestamp,varchar>``` thanks to a custom codec.
Fix #3548
=> Use JSR310 dates for cassandra

generators/server/templates/src/test/java/package/_AbstractCassandraTest.java
I think the embedded Cassandra need more time than 10000ms to start, else the Unit Tests will fail:
```log
2016-05-13 20:59:51.809 ERROR   --- [           main] o.c.utils.EmbeddedCassandraServerHelper  : Cassandra daemon did not start after 10000 ms. Consider increasing the timeout
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 18.766 sec <<< FAILURE! - in com.mycompany.myapp.CassandraKeyspaceUnitTest
com.mycompany.myapp.CassandraKeyspaceUnitTest  Time elapsed: 18.76 sec  <<< FAILURE!
java.lang.AssertionError: Cassandra daemon did not start within timeout
at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:132)
at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServ …
```
=> Add more time to embedded cassandra

.travis.yml, travis/install/01-install-docker-compose.sh, travis/install/03-checkVersion.sh, travis/install/04-cache.sh, travis/scripts/01-generate-project.sh, travis/scripts/02-generate-entities.sh, travis/scripts/03-docker-compose.sh, travis/scripts/04-tests.sh, travis/scripts/05-run.sh
The node_modules cache is completely broken with npm3, so I remove it.
All changes:
- upgrade docker 1.10 to 1.11
- upgrade node 4.4.3 to 4.4.4
- use maven wrapper to be consistent with gradle wrapper
- use new repo jhipster-travis-cache
- use m2 for gradle
- remove the cache for node_modules: doesn't work well with npm3
=> Travis: cache improvements

generators/server/templates/src/main/java/package/web/rest/util/_PaginationUtil.java
I had an issue using the `PaginationUtil`
In my case, I provided a baseUrl already containing request-params: `"/api/reports?filter=true"`
Then the old implementations added `page` and `size` parameters without checking, resulting in:  `"/api/reports?filter=true?page=1&size=20"`
This result contains 2 `?`
This fix uses Spring `UriComponentsBuilder` for handling such cases.
=> PaginationUtil: if baseUrl already contains request-params, no second '?' should be added

generators/entity/templates/src/main/webapp/app/entities/_entity-management-delete-dialog.controller.js, generators/entity/templates/src/main/webapp/app/entities/_entity-management-detail.controller.js, generators/entity/templates/src/main/webapp/app/entities/_entity-management-dialog.controller.js, generators/entity/templates/src/main/webapp/app/entities/_entity-management.controller.js, generators/entity/templates/src/main/webapp/app/entities/infinite-scroll-template.ejs, generators/entity/templates/src/main/webapp/app/entities/no-pagination-template.ejs, generators/entity/templates/src/main/webapp/app/entities/pagination-template.ejs
Some polish in entities controllers:
* Declaring functions on the bottom and assign them to `vm` in the top of the file: [Rule Y033](https://github.com/johnpapa/angular-styleguide/tree/master/a1#style-y033)
* Not assign `loadAll` function to `vm`, it's never called from the view it's an useless assignment.
=> Entity controllers polish to follow JohnPapa Style

generators/entity/templates/src/main/webapp/app/entities/_entity-management.state.js
We need to resolve promise before displaying modal to create/edit/delete an entity. To do so, we should return `$promise` when we get the entity from her service.
If we do not resolve the promise we could open the dialog without the data inside if the server is too slow.
We don't have to do `$promise.then(...)` because [ui-router](https://github.com/angular-ui/ui-router/wiki#resolve) will automatically wait for the promise to be resolved:
> If any of these dependencies are promises, they will be resolved and converted to a value before the controller is instantiated
=> Return $promise in entity management state resolves

travis/install/02-install-jhipster-stack.sh
Related to https://github.com/yeoman/yo/issues/441
Here the error logs in our Travis build:
```
yo --version
/home/travis/.nvm/versions/node/v4.4.4/lib/node_modules/yo/lib/cli.js:18
var tabtab = new (require('tabtab').Commands.default)({
^
TypeError: require(...).Commands.default is not a function
at Object.<anonymous> (/home/travis/.nvm/versions/node/v4.4.4/lib/node_modules/yo/lib/cli.js:18:14)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Function.Module.runMain (module.js:441:10)
at startup (node.js:139:18)
at node.js:968:3
```
=> Use stable older version of yeoman

generators/client/templates/src/main/webapp/app/account/reset/finish/_reset.finish.controller.js
The form error messages should be cleared when submitting the password reset form.  
Fixes: If you enter non-matching passwords then submit the form correctly, the error messages remains displayed under the success message.
=> hide password reset error messages on form submission

generators/docker-compose/templates/_docker-compose.yml
Using the docker-compose sub generator.
When no gateway is selected, the jhipster-registry config is not in docker-compose.yml file
=> docker-compose: fix missing registry when there is no gateway

generators/server/templates/_pom.xml, generators/server/templates/gradle/_profile_dev.gradle, generators/server/templates/gradle/_profile_prod.gradle
As discussed [here](https://github.com/jhipster/generator-jhipster/commit/d3133965df11716c3271f674d79c286480864cd1#commitcomment-17518049), this makes the handling of profiles (more) uniform across Maven and Gradle builds.
PS @deepu105 You [asked](https://github.com/jhipster/generator-jhipster/pull/3587#issuecomment-219926663) me to update the documentation -- I'll gladly do that, of course, but perhaps let's first deal with this PR, so I don't have to update the docs twice?
=> Uniform profile handling maven/gradle

generators/client/templates/src/main/webapp/app/components/util/_jhi-item-count.directive.js
Issue: the component jhiItemCount(jhi-item-count.directive.js) will shows the wrong range when the number of entity exceeds to 20, for example:
just plus 1 to fix it.
=> fix showing wrong pages of component jhi-item-count

generators/server/templates/src/main/resources/templates/error.html
Error pages served via https currently give the following error:
```
Mixed Content: The page at 'https://jhipsterwebsite.org/non-existent-path' was loaded over HTTPS, but requested an insecure script 'http://linkhelp.clients.google.com/tbproxy/lh/wm/fixurl.js'. This request has been blocked; the content must be served over HTTPS.```
=> change http to https so search box appears on websites with https

generators/client/templates/src/main/webapp/app/admin/audits/_audits.service.js, generators/client/templates/src/main/webapp/app/services/auth/_account.service.js, generators/client/templates/src/main/webapp/app/services/auth/_activate.service.js, generators/client/templates/src/main/webapp/app/services/auth/_auth.jwt.service.js, generators/client/templates/src/main/webapp/app/services/auth/_password-reset-finish.service.js, generators/client/templates/src/main/webapp/app/services/auth/_password-reset-init.service.js, generators/client/templates/src/main/webapp/app/services/auth/_password.service.js, generators/client/templates/src/main/webapp/app/services/auth/_register.service.js, generators/client/templates/src/main/webapp/app/services/auth/_sessions.service.js, generators/client/templates/src/main/webapp/app/services/user/_user.service.js
so names like "UserService" used as "userservice" in XHTTP calls against the edge server, since this is the proper name building of service names from Eureka server
=> fixes wrong UAA url for custom UAA base names in client generator

generators/entity/templates/src/main/webapp/app/entities/infinite-scroll-template.ejs
If i enabled infinite scroll on a page, the angular sent lots and lots of requests to the server because vm.links.last was not declared
=> fix infinite-scroll template (sent multiple requests on page load)

generators/server/templates/src/main/java/package/service/_SocialService.java
In some cases, facebook does not provide a username, which caused the old implementation to crash
=> Fix possible NPE in SocialService

.travis.yml, travis/install/04-cache.sh, travis/scripts/02-generate-entities.sh, travis/scripts/04-tests.sh, travis/scripts/05-run.sh
15 days ago, Travis improved their cache system.
See here : https://github.com/travis-ci/travis-ci/issues/4393
Official doc: https://docs.travis-ci.com/user/caching/
It fits perfectly what we need here, because every build is too different. And these new caches will be available to all PR.
What have been done here:
- upgrade to node 4.4.5 LTS
- add cache for every build
- no need to clone : [jhipster-travis-build](https://github.com/jhipster/jhipster-travis-build) or [jhipster-travis-cache](https://github.com/jhipster/jhipster-travis-cache)
- check maven or gradle wrapper instead of application's name
We won't see any improvment until this PR is merged, and after the merge, the 1st full build will cache everything, so benefits will be seen for the next builds.
@jdubois :
At the moment, …
=> Travis: use new system matrix cache by Travis

Dockerfile
running any clean commands in a separate RUN doesn't have the wanted effect. The files would be deleted, but the image size would stay the same, because they still exist in a lower layer.
=> fix APT cleanup in Dockerfile

Dockerfile
From PR #3700, `apt-get clean` is in the same command as `npm install -g` line when it should have `&&` between the two.  It currently installs the npm packages apt-get@0.1.0 and clean@4.0.2
=> fix Dockerfile to properly clean apt repository

generators/client/templates/src/main/webapp/app/admin/user-management/_user-management.controller.js, generators/client/templates/src/main/webapp/app/admin/user-management/_user-management.state.js, generators/client/templates/src/main/webapp/app/admin/user-management/user-management.html
Pagination for user-management still uses the older method (refreshing/viewing/deleting a User resets the page back to 1).  This aligns user-management pagination with the way entities do it, offering a much better user experience.
I will open a separate PR for client-2 (let me know if this isn't the right way)
=> set up sorting and pagination for user-management to match entities

generators/entity/templates/src/main/java/package/web/rest/_EntityResource.java
The import statement throws an error when creating an entity using DTOs and Cassandra.
Because `@Transactional` is unused in the EntityResource file, I removed it rather than including it for only SQL
=> fix entities that use DTOs with Cassandra

generators/app/prompts.js, generators/client-2/templates/_package.json
RC2 came out yesterday. We should keep up with the latest and greatest. 
Question: Does anyone know what the difference between `core-js` and `es6-shim` is? angular-cli uses es6-shim, but it looks like angular2-seed uses core-js.
* angular-cli: https://github.com/angular/angular-cli/commit/4113f3060d919a1aad2ce47c1609f96c12f2ab99
* angular2-seed: https://github.com/mgechev/angular2-seed/blob/master/package.json
=> Simplify Angular 1.x vs. 2.x choice. Upgrade to Angular 2 rc2.

generators/server/templates/src/main/docker/central-server-config/application.yml
Remove the default conf for eureka in jhipster-registry.yml as this will make clients not running in docker fail.
The usecase in question:
- launch the registry with: `docker-compose -f src/main/docker/jhipster-registry up -d`
- develop your app and launch using mvn or IDE
=> Fix jhipster-registry.yml for a development usecase

generators/server/templates/_README.md
This argument is useless since: #3587
=> Remove now useless '--spring.profiles.active=prod' from README

generators/server/templates/_pom.xml
Updating the maven docker plugins to the latest version that includes a fix for building images using docker for mac (see https://github.com/spotify/docker-maven-plugin/issues/218)
=> Update maven docker plugin to get around docker for mac issue

generators/entity/index.js, generators/entity/templates/src/main/webapp/app/entities/_entity-management-detail.controller.js, generators/entity/templates/src/main/webapp/app/entities/_entity-management-detail.html, generators/entity/templates/src/main/webapp/app/entities/_entity-management.state.js, generators/entity/templates/src/test/javascript/spec/app/entities/_entity-management-detail.controller.spec.js
* add new state for detail editing, such that the user can stay on the detail page
* don't use back anymore, because otherwise the edit dialog will open again
* therefore publish the previous state to the detail page (in case not found, the entity list is used)
close #3695
=> add edit button to detail page

generators/entity/templates/src/main/resources/config/liquibase/changelog/_added_entity_constraints.xml
change fk key name for many-to-many relationship to use the correct plural column name,
which was earlier having singular column name and also was interchanged entity and otherEntity name
implement constraint name length check for second foreign key in many-to-many relationship
implement constraint name length check for MySQL foreign key in many-to-one and one-to-one reln
fix jhipster/generator-jhipster#2443, fix jhipster/generator-jhipster#3814, fix jhipster/generator-jhipster#3815
=> change foreign key constraint name and validate constraint name length

generators/upgrade/index.js
I've added a task which installs jhipster locally right before the app generation, so now when you run 
`yo jhipster:upgrade`
it will:
1. check out on the jhipster_upgrade branch
2. clean up the folder (_cleanUp task)
3. install jhipster with needed versioin
4. and then run _generate task, which will use installed locally jhipster and generate correct app
So now upgrade process is independent of the installed globally version and we can upgrade projects generated before 3.4.0. And it also fixes issues when we have several projects generated with different jhipster versions.
=> Fix for issue with upgrading projects generated prior JHipster 3.4.0 #3761

generators/server/index.js
Currently jhi_user and jhi_authorities are always created when using MongoDB.  Microservices and applications built with --skip-user-management should not create these collections.
=> only create user and authorities tables when needed in mongo apps

generators/generator-base.js, generators/server/index.js, generators/server/prompts.js, generators/server/templates/src/main/java/package/config/_MicroserviceSecurityConfiguration.java, generators/server/templates/src/main/java/package/config/_UaaConfiguration.java, generators/server/templates/src/main/resources/config/_application-dev.yml, generators/server/templates/src/main/resources/config/_application-prod.yml
A shared secret with which to sign JWTs is great when there is no single service responsible for all JWT creation. However, in the case of OAuth2, the authorization server creates and usually signs the token with its private key. The authorization server also exposes its public key to other services so that they can verify the JWT and grant/deny access accordingly.
Some advantages of asymmetric (i.e. public/private key) cryptography vs symmetric (i.e. shared secret) cryptography are:
1. Simpler key management. Asymmetric cryptography only needs to keep the private key safe (on the authorization server) while the public key can be freely exposed. Furthermore, resource servers can dynamically ask the authorization server for its public key. Symmetric cryptography means that the secret must …
=> Use authorization server's public key on resource servers

generators/generator-base.js
This changes the stripHtml regex to also check for `translate=` attributes containing `\ \+\{\}\'` (spaces, plus signs, brackets, single quotes).   The following line now has translation removed correctly: 
`-            <span translate="{{'notransApp.Specialty.' + vm.foo.specialty}}">{{vm.foo.specialty}}</span>		`
`+            <span>{{vm.foo.specialty}}</span>`
From https://github.com/ruddell/translation-removal-example/commit/2614377c7e26d02082826fb1280f21f01782043d
Fix #3851
=> remove translation on enum type correctly

generators/entity/templates/src/main/webapp/app/entities/_entity-management-detail.html, generators/entity/templates/src/main/webapp/app/entities/_entity-management.html
Tested this to ensure it works with both the default Long id and the user-customized String id that some users prefer.
Fix #3858
=> remove double brace to be consistent and allow other ID types

generators/docker-compose/index.js, generators/server/templates/src/main/docker/_app.yml, generators/server/templates/src/main/docker/central-server-config/application.yml
This line disappeared from app.yml in [this change](
https://github.com/jhipster/generator-jhipster/commit/ed91094d943794f25273e933eaf6ee36b6f33560#diff-0eb6bd7d70ceede187ac70836f037149).  Without it, the gateways and microservices throws the error when running `docker-compose -f src/main/docker/app.yml up` :
```
2016-07-17 02:06:24.622  INFO 8 --- [           main] com.netflix.discovery.DiscoveryClient    : Getting all instance registry info from the eureka server
optionsgateway-app_1            | 2016-07-17 02:06:24.751 ERROR 8 --- [           main] c.n.d.s.t.d.RedirectingEurekaHttpClient  : Request execution error
optionsgateway-app_1            | 
optionsgateway-app_1            | com.sun.jersey.api.client.ClientHandlerException: java.net.ConnectException: Connection refused
```
=> add eureka info into jhipster-registry's application.yml generated in src/main/docker

generators/client/templates/gulpfile.js, generators/entity/templates/src/main/webapp/app/entities/_entity-management.state.js
Small fixes for running eslint on a generated project.
No client-2 PR because there is no swagger-ui task in the angular-2 client/gulpfile.js yet.  I think we need to copy over the changes from this PR https://github.com/jhipster/generator-jhipster/commit/00336c19cd17602732bf7915e5805825ee65f09a? I can do it tomorrow as @PierreBesson is on vacation.
=> eslint fixes

generators/entity/index.js
Because gateways use skip-server when generating entities from a microservice, enum translation files are not created and the entity management state has `$translatePartialLoader.addPart('');` which prevents the loading of the state.
Reported https://github.com/jhipster/generator-jhipster/issues/1776#issuecomment-235081448
=> fix gateway translation errors for entities with enum fields

generators/import-jdl/index.js
When there is an exception thrown that is of type `Error` the error handling prints "[object Object]". This change checks if there is a message property and prints that, otherwise it assumes its a string. This is the one place I was having issue with, but the same problem exists anywhere that pattern is used.
=> Improve error message for parsing JDL's

generators/server/index.js, generators/server/templates/src/main/java/package/config/_OAuth2ServerConfiguration.java, generators/server/templates/src/main/resources/config/_application-dev.yml, generators/server/templates/src/main/resources/config/_application-prod.yml, generators/server/templates/src/main/resources/config/liquibase/changelog/_initial_schema.xml, generators/server/templates/src/main/resources/config/liquibase/oauth_client_details.csv
The previous behavior to config oauth2 client details is just using hardcode. This PR will drop that hardcode and store the oauth2 client details into database.
The details of this PR are:
1. configure spring security oauth2 with jdbc
2. configure liquibase to insert oauth2 client details into database
NOTE: this PR **only** modified the sql part, the mongodb part is still using the hardcode.
=> move oauth2 client details into database

generators/generator-base.js, test/test-creation.js
This fixes #3889, where `baseName` can create class names that have invalid Java syntax for class names.
=> Revert mainClassName to be 'Application'

generators/entity/index.js, generators/entity/templates/src/main/resources/config/liquibase/changelog/_added_entity_constraints.xml, generators/generator-base.js, travis/samples/.jhipster/TestCustomTableName.json, travis/samples/.jhipster/TestManyToMany.json, travis/samples/.jhipster/TestManyToOne.json, travis/samples/.jhipster/TestOneToOne.json, travis/scripts/02-generate-entities.sh
Fix #3723, this is Option 2 from @jdubois's post in the issue.  It also fixes relationships with user when using a customized jhiPrefix.
Only thing left is to add a test using custom table names to the entity generation step.
=> Fix constraints when customizing table name

generators/client/templates/_bower.json, generators/client/templates/_package.json, generators/client/templates/src/test/javascript/_protractor.conf.js
This also upgrades Protractor to 4.0 and fixes the out-of-the-box experience with `gulp itest`.
Fixes #3887.
=> Upgrade npm and bower dependencies to latest versions

generators/client/templates/src/main/webapp/swagger-ui/_index.html
Swagger is broken on master, v2.1.4 used underscore.js and v2.1.5 (latest) uses lodash.js
Client-2 still has the older version of bower.json (updated in #3888) so this doesn't affect it yet.
=> update swagger resources to match latest version

generators/client/templates/src/test/javascript/_karma.conf.js
=> set correct path for junit-reporter output

generators/heroku/index.js
This PR updates the Heroku generator to use the new [heroku-cli-deploy](https://www.npmjs.com/package/heroku-cli-deploy) plugin instead of the old Github repo for the plugin. The latter with soon be obsolete. 
You may notice that the `--jar` option has been removed. However, this flag is still supported in the new version (but it's undocumented). This should make the transition easy for anyone already using the plugin.
=> Update heroku generator for new cli package install

generators/server/templates/src/main/docker/_app.yml
We finally have swagger/swagger UI working perfectly in docker. Both with src/main/docker/app.yml and the docker-compose subgen.
Big thanks to @ruddell @marcelinobadin for coming after me and fixing some bugs.
This will let us do amazing demos of JHipster microservice.
=> Use the swagger profile in docker-compose

generators/client/templates/gulpfile.js
This fixes `gulp inject` to inject installed bower dependences from bower.json.  
You can reproduce the issue by installing something with bower (for example `bower install underscore --save`) and running `gulp inject`, the  files will not be found in index.html.  
Another way to reproduce this is to remove any of the files between `` and run `gulp inject`.  No files will be injected.
Originally reported on [StackOverflow](http://stackoverflow.com/questions/37816714/gulp-task-injectvendor-does-not-inject-bower-dependencies/37826202#37826202)
=> fix gulp inject task to inject bower dependencies correctly

generators/entity/templates/src/main/webapp/i18n/_entity_it.json
changed `us` to `un` - correct italian version.
=> Fix typo in `i18n/_entity_it.json`

generators/server/templates/_gradle.properties, generators/server/templates/_pom.xml
Starting from the liquibase version bump in #3900, running `mvn liquibase:diff` on a project throws the following error:
`[ERROR] Failed to execute goal org.liquibase:liquibase-maven-plugin:3.5.1:diff (default-cli) on project mastertest: Execution default-cli of goal org.liquibase:liquibase-maven-plugin:3.5.1:diff failed: An API incompatibility was encountered while executing org.liquibase:liquibase-maven-plugin:3.5.1:diff: java.lang.NoSuchMethodError: liquibase.structure.core.ForeignKey.addForeignKeyColumn(Lliquibase/structure/core/Column;)V`
According to https://github.com/liquibase/liquibase-hibernate/issues/117, reverting liquibase from 3.5 -> 3.4.2 is the only option to fix this for now.
=> revert liquibase to fix mvn:liquibase diff command

generators/client/templates/src/main/webapp/app/admin/tracker/_tracker.service.js
No websocket access token was set when using UAA, resulting with an Access Is Denied error.  Originally reported [here](http://stackoverflow.com/questions/38879751/executorsubscribablechannelclientinboundchannel-access-denied)
=> set access_token for websockets when using UAA

generators/generator-base.js, test/test-creation.js
PR #3890 introduced a backward compatibility for projects generated since JHipster 3.x
As discussed in the issue, I propose an alternative fix that preserves backward compatibility, is motre convenient for microservices architecture and fixes #3889 with base names that are not valid java classes.
Fix #3889
=> Java main class name backward compatible and avoiding compilation issue

generators/import-jdl/index.js
There is already a check in the code, but this.skipClient was undefined so it always tried to run `gulp inject:app`
=> import-jdl load skipClient config to skip gulp for microservices

generators/entity/index.js, generators/entity/prompts.js, generators/generator-base.js, travis/samples/.jhipster/TestCustomTableName.json
Prompts the user to enter a shorter table name when the entity has relationships and DB is Oracle or if table name is more 30 char long.
Also updates the logic of creating joint table names and constraint names as per discussion in #3839
@jdubois please see if this is ok for you
fix #3974
=> Table name prompt for oracle

generators/entity/templates/src/main/webapp/app/entities/infinite-scroll-template.ejs
Fix for Multiple, irrelevant GET Requests on elastic search with an infinite scroll.   #3999
=> Fix for #3999

generators/server/templates/_build.gradle
Buildinfo is now added to ``META-INF`` when using gradle.
update #3574
=> add build info to gradle builds

generators/entity/templates/src/main/java/package/domain/_Entity.java
With fluent methods, the following JDL generates two different `addDevice` and `removeDevice` in DeviceRelationship.java
```
entity Device
entity DeviceRelationship
DeviceRelationship{originatingDevice} to Device{originatingDeviceRelationship},
DeviceRelationship{destinationDevice} to Device{destinationDeviceRelationship}
}
```
=> fix add and remove methods for two relationships with same entity

generators/aws/index.js, generators/aws/lib/aws.js
AWS Subgenerator fails silently because `generator` is set in the `try` after the error occurs.  
I also updated the paths to show the appropriate folder to install aws npm dependencies because monoliths/gateways use the local node_modules.  This should also be updated in the AWS documentation http://jhipster.github.io/aws/
=> install aws subgenerator dependencies if they are missing

generators/server/templates/src/main/java/package/domain/_SocialUserConnection.java
Mongo apps do not have hibernate so compiling fails on generation, moved hibernate imports so they are only imported for SQL.  Also removed unused JsonDeserialize/JsonSerialize imports.
=> fix monogdb with social login

generators/server/index.js, generators/server/templates/_build.gradle, generators/server/templates/_pom.xml, generators/server/templates/src/test/java/package/security/_WithMockOAuth2Authentication.java, generators/server/templates/src/test/java/package/security/_WithMockedOAuthUserSecurityContextFactory.java
so the developer may test the security behaviour, without physically interact
with an uaa or other OAuth2 authorization server, using users may not really
exists.
You simply annotate test methods with 
`@WithMockOAuth2Authentication`
or
`@WithMockOAuth2Authentication(scope = "web-app")`
or
`@WithMockOAuth2Authentication(roles = { ... })`
partially solving my ideas mentioned in #3797
the usage is quite simple and can be reviewed here: https://github.com/ExtremeEnvironment/message-service/blob/master/src/test/java/de/extremeenvironment/messageservice/web/rest/MessageResourceIntTest.java
I am about writing UAA docs currenty, and would cover this, too. I already used that approach several times and it helps a lot during development using uaa.
=> adds an usefull annotation for emulating OAuth2 security contextes in tests

generators/generator-base.js, generators/generator-constants.js
I fix 2 issues here:
In https://github.com/jhipster/generator-jhipster/issues/4009, @tsaqova mentionned
> here are my schema, i change mysql version to 5.7.13 as workaround because 5.7.14 can't have 2 timestamp column (from zonedatetime) in one table by default
Here the error log on Travis build:
```
liquibase.exception.DatabaseException: Invalid default value for 'zoned_date_time_required_field' [Failed SQL: CREATE TABLE travisMysql.field_test_entity (id BIGINT AUTO_INCREMENT NOT NULL, string_field VARCHAR(255) NULL, string_required_field VARCHAR(255) NOT NULL, string_minlength_field VARCHAR(255) NULL, string_maxlength_field VARCHAR(20) NULL, string_pattern_field VARCHAR(255) NULL, integer_field INT NULL, integer_required_field INT NOT NULL, integer_min_field INT NULL, integer_max_field …
```
=> Fix mysql version and travis mysql build

generators/entity/templates/src/main/webapp/app/entities/_entity-management-dialog.html
When generating an entity with a field of type CBlob (Text), we use a `textarea` for representing the field in a form. We generate a self-closing `<textarea ... />` field, but it's invalid to do so[1][2]. In my tests, the issue only came to my attention when running my application as an executable fat WAR with the production profile.
What would happen then is that the self-closing `texarea` would eat all the rest of my page contents, leaving me with many missing fields and no submit buttons.
YMMV. I've no idea why it only broke on production builds.
This pull requests fixes this by adding the closing tag `</textarea>`.
Reference:
1. Per [HTML5 spec](https://www.w3.org/TR/html-markup/syntax.html), void elements that are allowed to self-close are: `area, base, br, col, command, embed, hr, …
=> Add closing tag for textarea

generators/server/templates/src/main/java/package/aop/logging/_LoggingAspect.java
The LoggingAspect will fail when an Exception with null cause is catched.
The proposed pr handles this case.
=> Handling cause when it is null

generators/server/templates/src/main/java/package/security/_SecurityUtils.java
I think that isAuthenticated() should return false when ```SecurityContextHolder.getContext().getAuthentication()``` is null
=> SecurityUtils.isAuthenticated() should return false if no auth

generators/server/templates/_build.gradle, generators/server/templates/_gradle.properties, generators/server/templates/_pom.xml, generators/server/templates/src/main/java/package/config/_ThymeleafConfiguration.java, generators/server/templates/src/main/java/package/security/_AjaxLogoutSuccessHandler.java, generators/server/templates/src/main/java/package/service/_MailService.java, generators/server/templates/src/main/java/package/service/_SocialService.java, generators/server/templates/src/main/java/package/service/util/_RandomUtil.java, generators/server/templates/src/main/java/package/web/rest/_AccountResource.java
I was aligning some versions and noticed that jhipster depends on a [5.5 years old version](https://mvnrepository.com/artifact/commons-lang/commons-lang) of commons-lang :-)
Guess it happened because they sneakily changed the groupId and artifactId.
Anyway, this PR brings this dependency [up to date](https://mvnrepository.com/artifact/org.apache.commons/commons-lang3).
=> Upgrade commons-lang

generators/generator-base.js
Fix #3984
The phrase "using the default name instead" was removed from the error message because the user is re-prompted.
=> check for underscore in microservice base names and fix message

generators/server/templates/_build.gradle, generators/server/templates/_pom.xml, generators/server/templates/gradle/_profile_prod.gradle, generators/server/templates/src/main/resources/config/_application.yml
Finally fixes #3574 
cc @gmarziou
Add the following in the /info endpoint **only when doing a prod build**
```
"git": {
"commit": {
"id": {
"abbrev": "324b701",
"describe": "v1-2-324b701"//only for maven as the gradle git-commit plugin doesn't support it yet
}
},
"branch": "master"
}
```
What it does:
- Set `management.info.git.mode` to `full` this is needed so that every property present in the `git.properties` file will end up in /info. I think this is the natural way to use it since in the default `simple` mode it will only put the commit id and branch in /info.
- Setup the git-commit plugin for both maven and gradle and restrict it to a subset of git properties : `git.commit.abbrev`, `git.branch` and `git.commit.id.describe` (unfortunately not available for gradle).
Another advantage …
=> Add git commit data to /info endpoint in prod build

generators/server/index.js, generators/server/templates/src/main/docker/_app.yml, generators/server/templates/src/main/docker/_jhipster-registry.yml, generators/server/templates/src/main/docker/central-server-config/README, generators/server/templates/src/main/docker/central-server-config/docker-config/application.yml, generators/server/templates/src/main/docker/central-server-config/localhost-config/application.yml, test/test-creation.js
Fix #4097
After considering the problem all morning and discussing this at the office with @jdubois. I have found a solution that fixes the issue with service discovery not working when the registry is  in docker and the app started the normal way. Thanks @pascalgrimaud for submitting the bug and finding its cause :+1:.
So basically I put 2 configuration dirs, a `docker-config` for app.yml and a `localhost-config` for jhipster-registry.yml.
=> Separate configuration sources used by jhipster-registry.yml and app.yml

generators/server/templates/src/main/docker/_app.yml
Find by @eoinverling on gitter
When generating a gateway project, in `src/main/docker/app.yml` file, the comment part about using docker cassandra is incorrect
Another minor issue:
- when using the docker-compose sub generator, the cassandra part is not generated in the new `docker-compose.yml` file. It's because we have to detect if it's commented or not. So for the moment, I suggested the user to copy it manually
=> Improve comment in app.yml to use docker cassandra for rate limiting

generators/client-2/templates/_package.json, generators/client-2/templates/gulp/_copy.js, generators/client-2/templates/src/main/webapp/app/_app.ng2module.ts, generators/client-2/templates/src/main/webapp/app/layouts/navbar/navbar.html, generators/client-2/templates/src/main/webapp/system.config.js
Wired ng-bootstrap
Tested Navbar with ng-bootstrap elements
There is a problem with adding `NgbModules` in `app.ng2modules.ts` as a whole after this is fixed [angular-2] (https://github.com/angular/angular/issues/11280), we can do that.
=> WIP : Added ng-bootstrap 

generators/server/templates/_pom.xml, generators/server/templates/gradle/_profile_dev.gradle, generators/server/templates/src/main/java/package/config/_DefaultProfileUtil.java, generators/server/templates/src/main/java/package/web/rest/_ProfileInfoResource.java, generators/server/templates/src/main/resources/config/_application-dev.yml
There is a minor glitch, which can be solved by documentation.
When the app is run from an IDE using the Application.java main file only dev profile will be activated by default. the swagger profile would need to be explicitly enabled if required. This is due to the issue [here ](https://github.com/spring-projects/spring-boot/issues/6833#issuecomment-246026401)
This issue does not affect bootRun or running packaged war.
Fix #4059
=> Remove workaround to set default profile

generators/client-2/templates/src/main/webapp/app/components/_common.module.ts
This partially fixes OAuth2 and JWT apps for the NG2 branch - error was thrown due to missing `auth-session.service`
=> import the correct AuthServerProvider based on selected auth

generators/generator-constants.js
=> migrate the java docker image from _/java to _/openjdk

generators/client-2/templates/src/main/webapp/app/_app.ng2module.ts, generators/client-2/templates/src/main/webapp/app/blocks/interceptor/_notification.interceptor.ts, generators/client-2/templates/src/main/webapp/app/components/_common.ng2module.ts, generators/client-2/templates/src/main/webapp/system.config.js
I followed ng-bootstrap docs and changelog to fix the `404 traceur not found` issue, it's fixed. As @deepu105 suggested I commented the import in `NotificationInterceptor` so it's partially fixed.
Now the error I get is `Only selectors matching element names are supported, got: [ngbDatepickerMonthView] ` from the UpgradeAdapter.
=> Fix SystemJS config and Alert Service error

generators/docker-compose/index.js
When using the sub generator docker-compose for **monolithic** application, the property "SPRING_CLOUD_CONFIG_URI" shouldn't be defined in the `docker-compose.yml` file
=> docker-compose: remove useless config for monolithic application

generators/server/templates/src/main/java/package/config/_FeignConfiguration.java
since this is not needed, if using mock beans for testing feign clients.
I have already provided a better documentation how to test components the same way, without activating test profile. As @deepu105 wished to remove all mixups with test stuff, and it is possible to provide the identical solution without test profile exclusion, this PR removes that exclusion
=> removes test profile exclusion from feign

generators/server/templates/_build.gradle, generators/server/templates/_pom.xml
Using a profile not activated by default.
To use, activate the "shell" maven profile in the IDE. With maven use ```./mvnw -Pdev,shell ... ```
Fix #4167
=> Add remote shell

generators/heroku/index.js, generators/heroku/templates/_application-heroku.yml
This PR makes it easier to run `yo jhipster:heroku` again after it has already been run the first time. It will automatically detect the Heroku app name, instead of asking for it again, and it will skip steps like app creation that aren't needed.
This also means that users are encourage to run `yo jhipster:heroku` every time they deploy their application. The instructions in the output have been updated accordingly.
I've also fixed some output formatting in the Maven build process.
=> Better support for re-running the Heroku generator

generators/server/templates/src/main/java/package/config/_DefaultProfileUtil.java, generators/server/templates/src/main/java/package/web/rest/util/_HeaderUtil.java, generators/server/templates/src/main/java/package/web/rest/util/_PaginationUtil.java
[Sonar] utility classes should not have a public constructor.
This commit will  break code of users who have instanciated these classes or extended them
Also, Joshua Bloch said in Effective Java that the best way to create utiility classes is to use an enum. 
But, I didn't go futher than just making default constructor private and making classes final
=> [Sonar] utility classes should not have a public constructor

generators/client-2/index.js, generators/client-2/templates/_gulpfile.js, generators/client-2/templates/_package.json
clean up remaining references to `typings` (after previous commit switched to npm "@types")
=> remove typings references

generators/server/index.js, generators/server/templates/src/main/java/package/config/_OAuth2ServerConfiguration.java, generators/server/templates/src/main/java/package/config/dbmigrations/_InitialSetupMigration.java, generators/server/templates/src/main/java/package/config/oauth2/_MongoDBApprovalStore.java, generators/server/templates/src/main/java/package/config/oauth2/_MongoDBAuthorizationCodeServices.java, generators/server/templates/src/main/java/package/config/oauth2/_MongoDBClientDetailsService.java, generators/server/templates/src/main/java/package/config/oauth2/_OAuth2AuthenticationReadConverter.java, generators/server/templates/src/main/java/package/domain/_OAuth2AuthenticationApproval.java, generators/server/templates/src/main/java/package/domain/_OAuth2AuthenticationClientDetails.java, generators/server/templates/src/main/java/package/domain/_OAuth2AuthenticationCode.java, generators/server/templates/src/main/java/package/repository/_OAuth2ApprovalRepository.java, generators/server/templates/src/main/java/package/repository/_OAuth2ClientDetailsRepository.java, generators/server/templates/src/main/java/package/repository/_OAuth2CodeRepository.java
Basically, same as #3772 but this time for mongo.
=> Add oauth2 client details storage support for mongo

generators/docker-compose/prompts.js, generators/kubernetes/index.js, test/test-kubernetes.js
Related to https://github.com/jhipster/generator-jhipster/pull/4165
@PierreBesson : I put back the test. Hopefully, it detected a minor issue on kubernetes sub generator, when you introduced consul support ;-)
=> Kubernetes: put back tests on registry password

generators/entity/templates/src/main/webapp/app/entities/_entity-management-dialog.html
If an entity contains a blob field, currently the blob's button 'hijacks' the `enter` to open the file dialog or clear the chosen file.  This fix improves the user experience by making the `enter` button submit the form as usual.  Everything else works the same.
This is part of the entity subgenerator so it doesn't need an Angular2 PR.
=> make enter submit the form instead of clear blobs

generators/client-2/templates/src/main/webapp/app/layouts/navbar/navbar.html
uiSrefActive in ui-router 1.0-beta.3 has problems when uiSref are added/removed from DOM.
remove the uiSrefActive directives from places that might exhibit the behavior until ui-router 1.0-beta.4 is released.
This should halt the "observable unsubscribed" errors
This means those dropdown menus won't be highlighted for now.
See also https://github.com/angular-ui/ui-router/issues/3046
=> remove uiSrefActive from dropdowns (temporarily)

generators/server/templates/src/main/java/package/config/_MicroserviceSecurityConfiguration.java
Fix #4005
This was the cleanest way I could find to fix the issue.  Normally Hazelcast calls the discovery client in CacheConfiguration.  You can confirm the call to `discoveryClient.getInstances(serviceId)` is the reason the app works by commenting it out and the app won't find any UAA servers (the issue).   Without a call to the discovery client, the UAA route is never loaded.  Please let me know if there's a better way.
Pinging @xetys as he was the other person working on the issue.
=> load initial UAA servers from discovery client if not using hazelcast

generators/client-2/templates/src/main/webapp/app/_app.main.ts, generators/client-2/templates/src/main/webapp/app/_app.ng2module.ts, generators/client-2/templates/src/main/webapp/app/components/_common.ng2module.ts, generators/client-2/templates/src/main/webapp/app/shared/component/jhi-item-count.component.ts, generators/client-2/templates/src/main/webapp/app/shared/directive/sort-by.directive.ts, generators/client-2/templates/src/main/webapp/app/shared/directive/sort.directive.ts
inject `UrlRouter` from `ui-router-ng2` triggers ng2 initialization
this is apparently necessary because none of the ui-router-ng2 code was injected, so it never got initialized.  Injecting `UrlRouter` triggers DI which in turn initializes the ng1-to-ng2 code, which in turn registers states, etc.
Fell free to squash or whatever. I merged from deepu105/ng2-ui-router
=> ng2: fix ui-router-ng2 initialization

generators/client-2/templates/src/main/webapp/app/_app.module.ts, generators/client-2/templates/src/main/webapp/app/_app.ng2module.ts, generators/client-2/templates/src/main/webapp/app/_app.state.ts, generators/client-2/templates/src/main/webapp/app/home/_home.state.ts, generators/client-2/templates/src/main/webapp/app/layouts/error/_error.state.ts
@christopherthielen I migrated the admin routes to ui-router-ng2 but when i tried the same for the app state and home state it doesnt work. any hints? I tried both `UIRouterModule.forRoot` and `UIRouterModule.forChild` but nothing happens and there is no console error
=> migrate home states to ui-router-ng2

generators/docker-compose/index.js, generators/docker-compose/prompts.js, generators/server/index.js, generators/server/templates/src/main/java/package/_Application.java, generators/server/templates/src/main/java/package/config/_CacheConfiguration.java, generators/server/templates/src/main/java/package/config/_LoggingConfiguration.java
If you run the generator on an old microservice, `serviceDiscoveryType` could be undefined.  This sets the default to `eureka` so the project can compile.
I also changed all comparisons from 'no' to false to match the value put in the .yo-rc.json.
=> set default serviceDiscoveryType if missing in .yo-rc.json

generators/docker-compose/index.js, generators/docker-compose/prompts.js, generators/kubernetes/prompts.js, test/test-docker-compose.js, test/test-kubernetes.js
I'm working on kubernetes sub generator and I found that the sub generator for docker-compose is broken when I choose monolith application.
So I'm fixing it and I added npm tests for these configurations
=> Docker-compose subgenerator: fix monolith application

generators/server/templates/_pom.xml
Create a profile (called IDE) that includes mapstruct processor and any tweaks that should be only applied to the IDE.
I didn't find that Gradle needs such a profile. Please correct me if I'm wrong, I'm no Gradle expert.
Docs being updated in jhipster/jhipster.github.io#307
=> Create a profile (called IDE) that includes mapstruct processor

generators/server/index.js
Fix the current README which has all links broken, with undefined value:
```
This application was generated using JHipster , you can find documentation and help at [https://jhipster.github.io/documentation-archive/vundefined](https://jhipster.github.io/documentation-archive/vundefined).
```
```
[JHipster Homepage and latest documentation]: https://jhipster.github.io
[JHipster  archive]: https://jhipster.github.io/documentation-archive/vundefined
[Using JHipster in development]: https://jhipster.github.io/documentation-archive/vundefined/development/
[Using Docker and Docker-Compose]: https://jhipster.github.io/documentation-archive/vundefined/docker-compose
[Using JHipster in production]: https://jhipster.github.io/documentation-archive/vundefined/production/
[Running tests page]: …
```
=> Fix generated README [ci skip]

generators/entity/templates/src/test/gatling/simulations/_EntityGatlingTest.scala, generators/server/index.js, generators/server/templates/_build.gradle, generators/server/templates/_gradle.properties, generators/server/templates/_pom.xml, generators/server/templates/gradle/_gatling.gradle, generators/server/templates/src/test/gatling/conf/logback.xml
* Upgrade gatling to latest 2.2.0
* Add ``logback.xml`` to overwrite gatling logging at a central place
* Some new gradle tasks and configuration options:
*  ``gatlingRun -PgatlingSimulationClass=SIMULATION_TO_EXECUTE`` you can execute one specific gatling test
*  ``gatlingRunAll`` runs all simulation in ``src/test/gatling/simulations``
* Add commented property to maven plugin to run multiple simulations. Maybe we could add a profile to execute all gatling tests (e.g. in CI) as ``simulationClass`` and ``runMultipleSimulations`` always results in the default behaviour (= asking which simulation to execute). I was able to overwrite ``simulationClass`` via command line parameters, but not ``runMultipleSimulations``
EDIT: I will update the documentation accordingly soon.
=> Gatling update

generators/client/templates/_bower.json
this bootstrap upgrade depends on jquery 3, used by jhipster,
see http://blog.getbootstrap.com/2016/07/25/bootstrap-3-3-7-released/
=> upgrade to bootstrap 3.3.7

generators/generator-base.js, generators/modules/index.js
Without `addEntryToEhcache` in modules/index.js, calling addEntityToEhcache from a module throws `Undefined: this.addEntryToEhcache`.
Also, when calling `addEntryToEhcache` from a module, this.packageName is always undefined.  I tried to bind(this) on `jhipsterFunc.addEntryToEhcache` but the module threw an error stating that it couldn't bind to undefined.  By making the method more generic, modules can now correctly add ehcache entries.
=> add addEntryToEhcache to modules index and generify it

.travis.yml, travis/samples/app-gateway-uaa/.yo-rc.json, travis/samples/app-gateway-uaa/uaa/.yo-rc.json, travis/scripts/01-generate-project.sh, travis/scripts/02-generate-entities.sh, travis/scripts/03-docker-compose.sh, travis/scripts/04-tests.sh, travis/scripts/05-run.sh
Fix https://github.com/jhipster/generator-jhipster/issues/4280
Here all the changes:
- add travis build for uaa
- it was a little bit complex because we need to generate 2 apps (uaa + gateway), test both and start both
- it is a perfect to test https://github.com/jhipster/generator-jhipster/issues/4283
- launch curl or protractor -> that means we will now test if the application is correctly started
See the previous build in 3.9.0 which failed:
https://travis-ci.org/pascalgrimaud/generator-jhipster/builds/166540393
With 3.9.1, it should be fixed
To resume:
- total of 16 builds
- 4 slots left to test NG2
- Elapsed time: 40min~
=> Travis: add uaa+gateway build

generators/client/templates/gulp/_inject.js
Add error handler for app injections, without this any code mistake is going to fail all the app to injects the js files silently
=> Add error handler for app injections

travis/scripts/05-run.sh
I'm trying to add more time to uaa build.
Otherwise, we can have this. Here 2 differents logs from Travis, for the same uaa build:
Build failed:
```
2016-10-19 05:15:23.583  INFO 6693 --- [           main] com.netflix.discovery.DiscoveryClient    : Getting all instance registry info from the eureka server
2016-10-19 05:15:23.828  INFO 6693 --- [           main] com.netflix.discovery.DiscoveryClient    : The response status is 200
2016-10-19 05:15:23.831  INFO 6693 --- [           main] com.netflix.discovery.DiscoveryClient    : Starting heartbeat executor: renew interval is: 30
2016-10-19 05:15:23.837  INFO 6693 --- [           main] c.n.discovery.InstanceInfoReplicator     : InstanceInfoReplicator onDemand update allowed rate per min is 4
2016-10-19 05:15:23.845  INFO 6693 --- [ …
```
=> Travis: give more time to uaa build

generators/entity/templates/src/test/java/package/web/rest/_EntityResourceIntTest.java
as this is not needed, since the UAA does not need to fetch the token from uaa for public key.
close #4228
=> restricts usage of SecurityBeanOverrideConfiguration to UAA applications

generators/client/templates/_gulpfile.js
There is an old problem ( http://stackoverflow.com/questions/36411296/gulp-not-refresh-on-changes-to-imported-scss-files )  when using sass if you create some imports inside main.scss and go to one of this imported files and made changes you had to go back to main.scss and save it to the imports changes take effects. 
This problem is related to the "changed" plugin don't letting gulp-sass work like it should.
=> fix sass imports not updating the main.css file

generators/aws/lib/rds.js
Not able to deploy to AWS.
Deploy for evaluation by the team.
To get a jHipster project deployed in to AWS the name of the protocol needs to be lowercase 'tcp'.  
Here is my .yo-rc.json file (cleaned):
```
{
"jhipsterVersion": "3.0.0",
"baseName": "InDepth2",
"packageName": "org.tr.indepth",
"packageFolder": "org/tr/indepth",
"authenticationType": "session",
"hibernateCache": "no",
"clusteredHttpSession": "no",
"websocket": "no",
"devDatabaseType": "mysql",
"prodDatabaseType": "mysql",
"searchEngine": "no",
"buildTool": "maven",
"enableSocialSignIn": false,
"useSass": false,
"applicationType": "monolith",
"testFrameworks": [
"gatling",
"cucumber",
"protractor"
],
"enableTranslation": true,
"nativeLanguage": "en", …
```
=> Changed TCP to tcp

generators/client-2/index.js, generators/client-2/templates/src/main/webapp/app/_app.ng2module.ts, generators/client-2/templates/src/main/webapp/app/blocks/config/_http.config.ts, generators/client-2/templates/src/main/webapp/app/blocks/interceptor/_auth-expired.interceptor.ts, generators/client-2/templates/src/main/webapp/app/shared/_XSRF-strategy.provider.ts, generators/client-2/templates/src/main/webapp/app/shared/_index.ts, generators/client-2/templates/src/main/webapp/app/shared/auth/_csrf.service.ts, generators/client-2/templates/src/main/webapp/swagger-ui/_index.html
Hi,
This [pull ](https://github.com/jhipster/generator-jhipster/pull/4368) enables default CSRF for spring and angular when session auth. I'm managed to get it work for angular, but bad news is that I couldn't make it to work with websockets (it's working with ng1 and will be enabled from v3.10). For some reason stomp client is ignoring any headers provided in tracker.service.ts, so I'm stucked with it.
Any help/suggestion?
=> Add Spring CSRF default implementation [ng2]

generators/entity/prompts.js
Fix #4404.  I also fixed the remove confirmation messages which would display even if no entities/relationships were chosen
=> skip prompting for relationships to remove when no relationships exist

generators/entity/index.js, generators/entity/prompts.js
Skip table and field validation for apps that use `--skip-server`.  Also don't prompt for entity DTO and Service options as those only affect the server.
Fix #4399
=> skip table and field validation for apps that skip server

generators/entity/templates/src/test/java/package/web/rest/_EntityResourceIntTest.java
Fix #4229 
I also removed values of clob test strings because they are not generated anyway . They can be generated in the same way but clob field has some validation problems. I can open new issue for this.
=> fill test strings with stream to avoid constant string too long error

generators/entity/templates/src/test/gatling/simulations/_EntityGatlingTest.scala
The EntityGatlingTest template expects an authenticationType value of oauth2 when the jhipster-generators uses "uaa"
=> AuthenticationType value mismatch in gatling test templates

generators/client-2/templates/src/main/webapp/app/shared/auth/_auth-jwt.service.ts
a little start on fixing UAA auth in client-2
the 2nd part would be to store this in localstorage and intercept **all** api HTTP calls using some interceptor.
However, intercepting was a quite straigt forward task in ng1 and got somehow more tricky in ng2...currently there is a WIP PR pending (#4414) with this. To be honest, I am not sure what is wrong with that PR, but I cant start my own one here, coz its double work...
this little change can be merged anywhere, as this part has to be done anyway
=> changes the token call for uaa auth

generators/kubernetes/files.js, generators/kubernetes/index.js, generators/kubernetes/templates/_deployment.yml, generators/kubernetes/templates/db/_kafka.yml, test/templates/compose/09-kafka/.yo-rc.json, test/templates/compose/09-kafka/src/main/docker/app.yml, test/templates/compose/09-kafka/src/main/docker/kafka.yml, test/templates/compose/09-kafka/src/main/docker/mysql.yml, test/test-kubernetes.js
I'm opening this PR to track the progress in adding the Kafka support to the Kubernetes generator.
The initial ticket to add supports for all technologies to the kubernetes generator is #4205
The implementation adds a Kafka and a Zookeepeer deployment.
The monolith works, both in GKE and minikube.
The microservices version don't work on minikube or GKE.
Both the gateway and the service can not reach the Kafka node.
But even without Kafka, a microservice architecture don't start on my local minikube.
Without Kafka, it is working on GKE thought
> Can someone confirm microservices work locally on minikube w/o Kafka and test my generator microservice?
The current implementation generates a different Kafka/Zookeeper pair for every Gateway/microservice
In contrast, the docker-compose generator …
=> add kafka to the kubernetes generator

generators/server/templates/src/main/java/package/config/_CloudDatabaseConfiguration.java, generators/server/templates/src/main/java/package/config/_DatabaseConfiguration.java
* Most of JSR310 types are already handled by CustomConversions so they can be removed
* Use spring-data-mongo auto-configuration instead of extending AbstractMongoConfiguration
=> Simplify mongo configuration

generators/entity/prompts.js
During your (excellent!) Devoxx2016 talk you said you wanted to take this out of beta because it always works.
=> Remove "Beta" from entity prompts

Dockerfile
Related to https://github.com/jhipster/generator-jhipster/issues/4317
To allow the use of `yo jhipster --yarn` (https://github.com/jhipster/generator-jhipster/pull/4426) with the Docker image
=> Install yarn in Docker image [ci skip]

generators/client/templates/gulp/_serve.js
/oauth was not served by the Browsersync live reload. This patch enables oauth with live reload.
=> Enable oauth with live reload

generators/entity/index.js
If the user manually specifies `no` or `false` for `searchEngine` in the entity.json file, the `@Document` annotation and search repository classes should be skipped.
The `no`/`false` value should be added by JDL when the entity is excluded from searching (ie `search all with elasticsearch except entityB`), but for now it is a manual process.
Related to #3269
=> load entity searchEngine config if present

generators/entity/templates/src/test/java/package/web/rest/_EntityResourceIntTest.java
Fix #4249
New instances are created for mocked fields of tests between `@PostConstruct` method and `@Before` method.
This is confusing when using Mockito methods in test methods as these are not affect objects used in setup method.
It could be caused by another issue but changing `@PostConstruct` to `@Before` works well.
Is there any specific reason to use `@PostConstruct`?
=> change @PostConstruct to @Before in tests

generators/import-jdl/index.js
Display the full error when the import-idl does not parse the file, including the number of the line where the error occurred.
=> Display the line number when import-jdl cannot parse

generators/client-2/index.js
Similar issue to the one discussed at the bottom of [this commit](https://github.com/jhipster/generator-jhipster/commit/5dc5cfa3c737b72aea3084a4e5cabbeca599bd5d#comments
), but for angularVersion (only affects ng2)
=> fix angularVersion undefined message for projects without translation

generators/server/templates/src/main/java/package/security/jwt/_TokenProvider.java
Rename the `tokenValidityInSeconds` fields to `...Milliseconds` since they are really milliseconds after the init method :)
This is a minor refactoring, because when porting our code to JWT this troubled me for a 'second' before I realize the fields were in fact used as milliseconds.
=> Refactoring - rename TokenProvider fields seconds to milliseconds

travis/scripts/06-sonar.sh
Very minor improvement
Only try launch sonar analyze to sonarsource if the repo is jhipster/generator-jhipster
=> Travis: sonar analyze for official repo

generators/entity/index.js
Fix #4311
Moved `validateTableName` after `setupVars`, so the `entityTableName` value of json file will be validated instead of entity name when regenerating
=> Load entity.json before validateTableName to get entityTableName

generators/client/templates/src/main/webapp/app/blocks/interceptor/_notification.interceptor.js, generators/client/templates/src/main/webapp/app/components/alert/_alert-error.directive.js, generators/entity/index.js, generators/entity/templates/src/main/webapp/i18n/_entity_ca.json, generators/entity/templates/src/main/webapp/i18n/_entity_cs.json, generators/entity/templates/src/main/webapp/i18n/_entity_da.json, generators/entity/templates/src/main/webapp/i18n/_entity_de.json, generators/entity/templates/src/main/webapp/i18n/_entity_el.json, generators/entity/templates/src/main/webapp/i18n/_entity_en.json, generators/entity/templates/src/main/webapp/i18n/_entity_es.json, generators/entity/templates/src/main/webapp/i18n/_entity_fr.json, generators/entity/templates/src/main/webapp/i18n/_entity_gl.json, generators/entity/templates/src/main/webapp/i18n/_entity_hi.json, generators/entity/templates/src/main/webapp/i18n/_entity_hu.json, generators/entity/templates/src/main/webapp/i18n/_entity_it.json, generators/entity/templates/src/main/webapp/i18n/_entity_ja.json, generators/entity/templates/src/main/webapp/i18n/_entity_kr.json, generators/entity/templates/src/main/webapp/i18n/_entity_mr.json, generators/entity/templates/src/main/webapp/i18n/_entity_nl.json, generators/entity/templates/src/main/webapp/i18n/_entity_pl.json, generators/entity/templates/src/main/webapp/i18n/_entity_pt-br.json, generators/entity/templates/src/main/webapp/i18n/_entity_pt-pt.json, generators/entity/templates/src/main/webapp/i18n/_entity_ro.json, generators/entity/templates/src/main/webapp/i18n/_entity_ru.json, generators/entity/templates/src/main/webapp/i18n/_entity_sk.json, generators/entity/templates/src/main/webapp/i18n/_entity_sv.json, generators/entity/templates/src/main/webapp/i18n/_entity_ta.json, generators/entity/templates/src/main/webapp/i18n/_entity_tr.json, generators/entity/templates/src/main/webapp/i18n/_entity_zh-cn.json, generators/entity/templates/src/main/webapp/i18n/_entity_zh-tw.json
Fix #4075
Entity created/updated/deleted alert messages are moved under `microserviceAppName` if the generated entity belongs to a microservice to be able to show them.
=> Get microservice alert and error headers from gateway

generators/server/templates/gradle/_gatling.gradle
Just a small fix to remove deprecations warning about [left shift operator](https://docs.gradle.org/3.2/release-notes#the-left-shift-operator-on-the-task-interface).
=> remove deprecated left shift operator

generators/server/templates/_gradle.properties, generators/server/templates/_pom.xml
avoiding the following issue on Postgresql 9.6.1 running 'mvn clean compile liquibase:diff':
[ERROR] Failed to execute goal org.liquibase:liquibase-maven-plugin:3.4.2:diff (default-cli) on project poc: Error setting up or running Liquibase: liquibase.command.CommandExecutionException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: org.postgresql.util.PSQLException: ERROR: column am.amcanorder does not exist
=> upgrade postgresql version

generators/app/index.js, generators/client/index.js, generators/server/index.js, generators/server/templates/_pom.xml, test/test-creation.js
Related to https://github.com/jhipster/generator-jhipster/issues/4317
Steps:
1) create folder, then, `yarn link generator-jhipster` or `npm link generator-jhipster`
2) generate project: `yo jhipster --yarn` -> the config will save the option in `.yo-rc.json`
3) regenerate project: `yo jhipster --force` -> it will use the config, so yarn
If you choose maven, the `pom.xml` will use the frontend-maven-plugin with yarn
For gradle [here](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/gradle/_profile_prod.gradle#L55), it will still use npm install because the `com.moowork.node` doesn't support yarn yet
I tested with node-sass too
> Travis official support for Yarn is merged and will be activated on monday
So I will update our Travis build in another PR, …
=> Yarn saved in config

generators/entity/templates/src/test/java/package/web/rest/_EntityResourceIntTest.java, generators/server/templates/src/test/java/package/web/rest/_TestUtil.java
The matcher matches if the Instant represented by the string is the same as the one hold by the reference ZonedDateTime.
Fix #4491
=> Use a custom matcher for ZonedDateTime test

generators/server/templates/src/main/java/package/security/_SecurityUtils.java
so the static function are usable in all kinds of authentications, supported by JHipster
also changed the class to Java 8 Stream API usage instead of explicit loops
fix #4526
=> makes the SecurityUtil more generic to Authentication

generators/server/templates/src/main/java/package/config/social/_SocialConfiguration.java
When deployed behind a reverse proxy, the application pushed towards the social (google, facebook, ...) a callback url computed on the request: which normally leads to http://localhost:8080/signin/google behing refused by the social app as non granted.
Both ```ConnectController``` and  ```ProviderSigninController``` accept the applicationUrl parameter which can be declared in Environment as spring.application.url. 
See http://docs.spring.io/spring-social/docs/current/reference/htmlsingle/#creating-connections-with-connectcontroller
=> Fixing callback url when deployed behind reverse proxy

generators/server/templates/_gradle.properties, generators/server/templates/_pom.xml
This updates HV to the latest and greatest. I'm not 100% sure about the POM change, in that case you seem to get the HV version from the Spring Boot dependencies POM. I can rework or split it up as needed.
=> Upgrading to Hibernate Validator 5.3.3.Final

generators/server/templates/_gradle.properties, generators/server/templates/_pom.xml
This is just bug fixes release (https://hibernate.atlassian.net/secure/ReleaseNote.jspa?projectId=10031&version=25600). Don't know why Travis CI is not happy with some of build configs. It shows "The command "sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3" failed and exited with 2 during" errors
=> Upgrade Hibernate to 5.2.5.Final

generators/app/index.js, generators/app/prompts.js, generators/client/index.js, generators/client/templates/_package.json, generators/generator-base.js, generators/generator-constants.js
So in the app generator, the generator asks for additional jhipster-generator to install, so it's more easy to discover them.
Open questions, how to detect if the version supports the current one?
=> Implement additional module installation step in the client generator

generators/docker-compose/index.js, generators/docker-compose/templates/alertmanager-conf/_config.yml, package.json
@jdubois I just noticed that this was merged by mistake. Can it be removed before the release...
It was part of my prometheus PR. I thought I removed it but I must have made a mistake when rebasing.
This is actually useless because it doesn't work.
=> [Prometheus] remove uuid generation for the alerting webhook

generators/server/templates/_build.gradle, generators/server/templates/_gradle.properties
There are some Hazelcast dependency version errors and a missing JCache dependency at Gradle. Both are correct at Maven.
@jdubois you may want to merge this before releasing a Hibernate 5 / Hazelcast related version update.
=> Fix Hazelcast versions and add missing JCache dependency

generators/server/index.js
When a .yo-rson file has already been created, js files are generated instead of ts files.
=> jhipster re-generation get's the correct angular2 option

generators/entity/templates/src/main/resources/config/liquibase/changelog/_added_entity.xml
Liquibase recently changed how Postgresql handles blobs ([link](https://github.com/liquibase/liquibase/pull/600)), it now generates an `oid` for `blob` instead of `bytea`.  Changing it to `longblob` keeps the current behavior.
We should also be using `boolean` instead of `bit` for the Boolean type to let Liquibase determine the correct field type for the database.  It currently is hardcoded to `bit` which breaks Booleans for Postgresql (and maybe Oracle?).  To avoid a checksum change for everyone, I only changed this for Postgresql apps.
To reproduce the issue, generate an app that uses Postgresql and an entity with a boolean or blob.  Attempting to create that entity will give a 500 error
=> fix boolean and blob field types for postgresql

generators/languages/templates/src/main/webapp/i18n/it/reset.json
The italian translation for the recover password form is wrong.
=> Translation mismatch in recover/change password

generators/server/templates/src/main/resources/config/liquibase/changelog/_initial_schema.xml
Currently can't login with error 
```
ERROR: column "token" is of type oid but expression is of type bytea
Hint: You will need to rewrite or cast the expression.
```
Related to my previous PR #4590, I also found the original issue way back #1940
=> Fix oauth2 for postgresql

generators/kubernetes/templates/_deployment.yml
Following a [discussion on the mailing list](https://groups.google.com/forum/#!topic/jhipster-dev/W44XX9W9Y4Y), I suggest we add this to be able to deploy to minikube without pushing to an external registry (using `eval $(minikube docker-env)`).
It could also be argued that it is a sensible default and should not cause problems if images are tagged properly.
=> add an imagePullPolicy: IfNotPresent to k8s deployment files

generators/entity/index.js
Related to https://github.com/jhipster/generator-jhipster/issues/4549
Still issue with the build : app-psql-es-noi18n
The user can't log into the application, so the protractor failed
=> Missing clientFw when using sub generator entities

generators/client/files-angularjs.js, generators/client/templates/angularjs/src/main/webapp/app/layouts/error/_error.state.js
This fixes:
- login.service.js which prevented logging in for Angular 1 apps without translation
- error.state.js missed by regex due to different format
Fixes the second bullet point under Angular 1 in @pascalgrimaud's comment #4549
=> remove translation from projects with it disabled [ng1]

generators/client/templates/angular/src/main/webapp/app/admin/health/_health-modal.component.ts, generators/client/templates/angular/src/main/webapp/app/admin/health/_health.component.ts, generators/client/templates/angular/src/main/webapp/app/admin/metrics/_metrics.component.ts, generators/client/templates/angular/src/main/webapp/app/admin/metrics/_metrics.service.ts, generators/client/templates/angular/src/main/webapp/app/shared/_shared-common.module.ts
This only fixes compile errors if jhiPrefix is different from default. There could be more things to do to complete ng2-jhiPrefix support.
Also fixed URL in metrics.service.
=> Fix ng2 jhiPrefix compile errors

generators/client/templates/angular/src/main/webapp/app/account/activate/_activate.state.ts, generators/client/templates/angular/src/main/webapp/app/account/password-reset/finish/_password-reset-finish.state.ts, generators/client/templates/angular/src/main/webapp/app/account/password-reset/init/_password-reset-init.state.ts, generators/client/templates/angular/src/main/webapp/app/account/password/_password.state.ts, generators/client/templates/angular/src/main/webapp/app/account/register/_register.state.ts, generators/client/templates/angular/src/main/webapp/app/account/sessions/_sessions.state.ts, generators/client/templates/angular/src/main/webapp/app/account/settings/_settings.component.ts, generators/client/templates/angular/src/main/webapp/app/account/settings/_settings.state.ts, generators/client/templates/angular/src/main/webapp/app/account/social/_social.state.ts, generators/client/templates/angular/src/main/webapp/app/admin/audits/_audits.state.ts, generators/client/templates/angular/src/main/webapp/app/admin/configuration/_configuration.state.ts, generators/client/templates/angular/src/main/webapp/app/admin/gateway/_gateway.state.ts, generators/client/templates/angular/src/main/webapp/app/admin/health/_health.state.ts, generators/client/templates/angular/src/main/webapp/app/admin/logs/_logs.state.ts, generators/client/templates/angular/src/main/webapp/app/admin/metrics/_metrics.state.ts, generators/client/templates/angular/src/main/webapp/app/admin/user-management/_user-management-dialog.component.ts, generators/client/templates/angular/src/main/webapp/app/home/_home.state.ts, generators/client/templates/angular/src/main/webapp/app/layouts/error/_error.state.ts, generators/client/templates/angular/src/main/webapp/app/shared/language/_language.service.ts, generators/client/templates/angular/src/main/webapp/app/shared/login/_login.component.ts, generators/client/templates/angular/src/main/webapp/app/shared/login/_login.service.ts, generators/client/templates/angular/src/main/webapp/app/shared/social/_social.component.ts
The regexp doesn't expect multiple whitespaces.
This is introduced with this commit: 
https://github.com/jhipster/generator-jhipster/commit/350d0e659367333ef0a4f3213a64c1d2d7cabbba
=> Fix configuration when translation is disabled

generators/server/templates/_build.gradle, generators/server/templates/gradle/_profile_prod.gradle, generators/server/templates/gradle/_yeoman.gradle
* Add a nodeDl property to use a downloaded node/npm (as with frontend-maven-plugin). Default is deactivated.
* Add a workaround for gradle-node-plugin/issues/134 (only works for npm so even if yarn was used at project generation, it fallsback to npm if nodeDl flag is on)
Fix #4667
=> Add a gradle flag to build using downloaded node/npm

generators/entity/templates/server/src/main/java/package/domain/_Entity.java
If `relationshipFieldNamePlural` matches `otherEntityName`, it doesn't add/remove the entity from the correct relationship.
Thanks to @brunnels for pointing this out
Example entity name that causes this issue is `ToolDeviceData`:
```java
public ImportIssue addToolDeviceData(ToolDeviceData toolDeviceData) {
toolDeviceData.add(toolDeviceData);
toolDeviceData.getImportIssues().add(this);
return this;
}
public ImportIssue removeToolDeviceData(ToolDeviceData toolDeviceData) {
toolDeviceData.remove(toolDeviceData);
toolDeviceData.getImportIssues().remove(this);
return this;
}
```
After this change:
```java
public ImportIssue addToolDeviceData(ToolDeviceData toolDeviceData) {
this.toolDeviceData.add(toolDeviceData);
toolDeviceData.getImportIssues().add(this);
return this;
}
public ImportIssue …
```
=> fix many-to-many to same entity

generators/app/index.js
fix #4729 
After the change the order is correct:
=> fix the order of the generator questions

generators/server/templates/_build.gradle
This PR is enhanced version of fix jhipster/generator-jhipster#4683 where gulp bufferOutput=true is assigned only in Windows.
Opening new PR because GitHub doesn't allow updates on closed PR-s.
=> fix random error/hanging of gradlew after executing gulp plugin in Windows

generators/server/templates/_pom.xml
Letter v in <yarn.version>**v**0.17.10</yarn.version> parameter couse reinstall Yarn with the same version
[INFO] Yarn 0.17.10 was installed, but we need version v0.17.10
[INFO] Installing Yarn version v0.17.10
[INFO] Unpacking C:\Users\RobertM\.m2\repository\com\github\eirslett\yarn\0.17.10\yarn-0.17.10.\yarn-0.17.10.msi into C:\Temp\jhipster_portfel\node\yarn
[INFO] Installed Yarn locally.
[INFO]
=> correct Yarn version name  _pom.xml

generators/server/templates/_gradle.properties, generators/server/templates/_pom.xml
See: https://spring.io/blog/2016/12/23/spring-boot-1-4-3-available-now
To be consistent, I updated:
- the registry: https://github.com/jhipster/jhipster-registry/pull/93
- jhipster server lib: https://github.com/jhipster/jhipster/pull/3
=> Upgrade to Spring Boot 1.4.3

generators/app/index.js, generators/app/templates/_skipClientApp.package.json
Fix #4218
Add a minimal package.json and npm/yarn install step after generation for skipClient apps. 
TODO
=> Add generator-jhipster as an npm/yarn dependency if the app is a microservice

generators/aws/lib/aws.js, generators/aws/lib/eb.js, generators/aws/lib/s3.js
- The npm package `node-uuid` was deprecated in favor of `uuid`
- Microservices now have a local generator-jhipster so the config is very simple
- We install the npm packages for the users, so the error messages should just say what went wrong
=> AWS Subgenerator Polish

package.json
Yarn currently complains with `warning generator-jhipster > insight > node-uuid@1.4.7: use uuid module instead`
=> get rid of jhipster's node-uuid deprecation warnings

generators/client/templates/angular/src/main/webapp/app/admin/user-management/_user-management-detail.component.html, generators/client/templates/angular/src/main/webapp/content/css/_main.css, generators/client/templates/angularjs/src/main/webapp/app/admin/user-management/_user-management-detail.html, generators/client/templates/angularjs/src/main/webapp/content/css/_main.css, generators/client/templates/angularjs/src/main/webapp/scss/_main.scss, generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management-detail.component.html, generators/entity/templates/client/angularjs/src/main/webapp/app/entities/_entity-management-detail.html
From the Migration documents of Bootstrap 4
`.dl-horizontal has been dropped. Instead, use .row on <dl> and use grid column classes (or mixins) on its <dt> and <dd> children.`
=> Bootstrap 4 - dl-horizontal has been dropped

generators/app/index.js, test/test-creation.js, test/test-expected-files.js, test/test-utils.js
Related to https://github.com/jhipster/generator-jhipster/pull/4597
When generating a microservice application, the package.json is
```yaml
{
"devDependencies": {
"generator-jhipster": ""
}
}
```
It should be instead:
```yaml
{
"devDependencies": {
"generator-jhipster": "3.12.1"
}
}
```
Another thing: https://github.com/jhipster/generator-jhipster/blob/master/generators/app/index.js#L340-L355
The goal of skip install is to skip `npm install` or `yarn install`, with the `package.json` created.
In the case of microservices, the `package.json` is not created. Is it intentional @PierreBesson ?
I should write npm test too, but I don't have time tonight. It can be done later
=> Microservices: fix generator-jhipster version in package json

generators/docker-compose/index.js, generators/kubernetes/files.js, generators/kubernetes/index.js, generators/kubernetes/templates/_deployment.yml, generators/kubernetes/templates/registry/_application-configmap.yml, generators/kubernetes/templates/registry/_consul-config-loader.yml, generators/kubernetes/templates/registry/_consul.yml, generators/kubernetes/templates/registry/_jhipster-registry.yml, test/test-kubernetes.js
It took me quite some time to get everything to work 😄 but now it's glorious !
I also did some changes for the jhipster-registry and now we can set the central config easily from a kubernernetes configmap (`application-config.yml` works the same way for the registry and consul)
Now we are almost at parity with docker-compose, it's only missing monitoring and cassandra (very nice example here : https://github.com/kubernetes/kubernetes/tree/master/examples/storage/cassandra).
=> Consul support for Kubernetes and improvements

generators/client/templates/angular/src/main/webapp/app/shared/tracker/_tracker.service.ts
Stateless authentication has to add extra parameters to the "url" variable of the tracker service.
You can reprodude this issue by choosing stateless authentication (JWT, OAuth2...) and spring websocker when generating project.
=> Remove const restriction for "url" variable for tracker service.

generators/server/templates/gitignore
`.factorypath` also needs to be excluded from git for Eclipse users.
More @ https://www.gitignore.io/api/eclipse
=> Git ignore for Java annotation processor in Eclipse

generators/client/templates/angular/src/test/javascript/_protractor.conf.js, generators/client/templates/angularjs/src/test/javascript/_protractor.conf.js, generators/server/templates/_README.md, generators/server/templates/src/main/resources/config/_application-dev.yml, generators/server/templates/src/main/resources/config/_application-prod.yml
On my PC, I have a service running at port 8080, so each time I generate a monolith, I have to manually change the port to a different value in several files.
This allows me to change port in `.yo-rc.json` and re-generate.
I only changed the templated files, there are probably other files to modify too but I'd like to get feedback before going further.
=> Allow setting server port for monolith apps

generators/server/templates/src/main/docker/_mysql.yml
yo jhipster:docker-compose generate docker-compose.yml . and not set mysql charset , although  [application-prod.ym](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/resources/config/_application-prod.yml#L64) set the jdbc string use utf-8 but it was still throw exception when insert the unicode character( e.g. chinese )
=> Update _mysql.yml set mysql charset

generators/server/templates/gradle/_liquibase.gradle
update the _liquibase.gradle file to generate a JAR manifest with all the classpath dependencies to avoid Windows limits as is done in bootRun
Fix #4848
=> add support for long paths in Windows for liquibaseDiffChangelog gradle task

generators/client/templates/angular/webpack/_webpack.prod.js
Previously, the `stats.html` file (4.5 MB) was generated in `target/www` folder and so was included in war file.
=> Webpack stats are now generated in target folder

generators/server/templates/src/main/java/package/config/_UaaConfiguration.java, generators/server/templates/src/main/resources/config/_application.yml
Related to https://github.com/jhipster/generator-jhipster/issues/4704, I forgot to fix it for UAA.  401s now have the correct CORS headers (when enabled).
=> fix uaa cors with 401

generators/client/templates/angular/src/main/webapp/app/shared/tracker/_tracker.service.ts
When logging out, the subscription === undefined, and rose following error:
> Cannot read property 'unsubscribe' of undefined.
=> Fixed cannot logout issue.

generators/ci-cd/USAGE, generators/ci-cd/index.js, generators/ci-cd/prompts.js, generators/ci-cd/templates/_.gitlab-ci.yml, generators/ci-cd/templates/_Jenkinsfile, generators/ci-cd/templates/_circle.yml, generators/heroku/USAGE, generators/heroku/index.js, generators/heroku/templates/_heroku.gradle
Following discussion on #4600 
This PR is for a subgen to generate CI/CD config files with options
Currently supported pipelines and integrations are:
Feature | Jenkins | Gitlab | Circle |
| ----- |:-------:|:------:|:------:|
Yarn|x (Maven)|x (Maven)|
Gitlab status|x|N/A|
SonarQube|x|
Build in Docker|x|x|N/A|
Gatling tests| |x (for basic apps)
Deploy to Heroku|x|x|x|
TODO/Next/ideas:
* Support NG2+
* Travis CI
* Gatling / Protractor / Cucumber tests
* Github
* AWS / CloudFoundry / Kubernetes deployment
* Build a docker image and publish to a docker registry
* Publish to Artifactory
* Git flow (master/develop/MR/PR/tags)
* Generator tests
* jhipster.github.io doc
Notes:
* I reused templates from generator-jhipster-ci. Kudos to @pascalgrimaud 
* I haven't tested enough Gitlab and Circle …
=> Add a sub generator for various CI/CD pipelines

generators/server/templates/src/main/java/package/service/dto/_UserDTO.java, generators/server/templates/src/main/java/package/service/mapper/_UserMapper.java
When creating a many-to-many relationship to a User using the generator:
- UserDTO needs the id field to make the JPA relation. I moved it from ManagedUserVM.
- UserDTO needs the login (to show in the table when there is no pagination)
I had to remove `@Mapping(target = "id", ignore = true)`, was it necessary before for some reasons ?
As the User is the target entity it is a **unidirectional** many-to-many, too hard or risky to change the User class right ?
So after the generation we have:
`public EntityA addUser(User user) {`
` this.users.add(user);`
`user.getEntityAS().add(this);` //does not compile and need to be remove manually (so far)
`return this;`
`    }`
The strange thing about this PR is that we have the 'id' field in UserDTO which is mainly use in the subclass ManagedUserVM. …
=> fix many-to-many relationship when User is the target Entity

generators/client/templates/angular/_package.json
Following deps are for angular 1:
"@types/angular": "1.6.2",
"@types/angular-animate": "1.5.6",
"@types/angular-mocks": "1.5.8",
=> Delete ng1 deps from ng2 package.json

generators/entity/templates/client/angular/src/main/webapp/app/entities/infinite-scroll-template.ejs
fix this error (when using blob):
```
ERROR in [at-loader] src/main/webapp/app/entities/field-test-infinite-scroll-entity/field-test-infinite-scroll-entity.component.ts:48:9 
Type '(base64String: string) => string' is not assignable to type 'number'.
Child html-webpack-plugin for "index.html":
[./node_modules/html-webpack-plugin/lib/loader.js!./src/main/webapp/index.ejs] ./~/html-webpack-plugin/lib/loader.js!./src/main/webapp/index.ejs 1.82 kB {0} [built]
[./node_modules/lodash/lodash.js] ./~/lodash/lodash.js 540 kB {0} [built]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 509 bytes {0} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 517 bytes {0} [built]
error Command failed with exit code 2.
```
=> ng2: fix the type of byteSize

generators/server/templates/src/main/resources/config/liquibase/changelog/_initial_schema.xml
The fields in question are:
* additional_information
* autoapprove
=> Change oauth_client_details column lengths to match Oracle 11g limits

generators/server/templates/src/main/resources/config/liquibase/changelog/_initial_schema.xml
=> shorten foreign key names to fit oracle length limit of 30

generators/client/templates/angular/src/main/webapp/app/admin/user-management/_user-management.component.html, generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management.component.html
When an entity contains more than one word, the link on the ID in the entity table was broken.  For example: `logEntry` should be `log-entry`
User management ID also pointed to the wrong place
=> fixes ID links for entity and user-management components

travis/scripts/04-tests.sh
Related to https://github.com/jhipster/generator-jhipster/issues/4302
I don't know if it's too early. But with this PR, the 3 builds for ng2 will fail, so maybe we should wait before merging it and I can rebase too when needed
=> Travis: add ng2 karma tests

generators/entity/templates/client/i18n/_entity_sr.json, generators/entity/templates/client/i18n/_enum_sr.json
When submiting support for sr I was following this https://github.com/jhipster/generator-jhipster/pull/4486 This means that Vietnamese language also lack support for entities. 
@tientq can you follow this PR and do the same for Vietnamese language after review ?
=> Add missing entity translates for serbian [ci skip]

generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management-dialog.component.html
=> Fix Backslashes in validation patterns are not escaped in 'translateValues'

generators/client/templates/angular/src/main/webapp/app/layouts/navbar/_navbar.component.html
fixes bug where home navigation bar item always stays highlighted as if it is selected even when navigating to other sections
=> Fixes Home Navigation Item Selection

generators/server/templates/_build.gradle, generators/server/templates/_gradle.properties
The `spring-security` version is pinned to `4.2.1` (like in maven).
close #4975
=> Pin spring security version

generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/_http.provider.ts
When using angular-cli on a JHipster project, the AOT compilation fails on `http.provider.ts` because of `useFactory` property  using a lambda rather than a named function.
See https://medium.com/@isaacplmann/making-your-angular-2-library-statically-analyzable-for-aot-e1c6f3ebedd5#.hylx41wiy
=> Prepare for AOT

generators/client/templates/angular/src/main/webapp/content/css/_global.css, generators/client/templates/angular/src/main/webapp/content/scss/_global.scss
In the main.component that wraps the entire site, there is a css property "card" that sets the padding for the content.  This is set to 30px prior to my change.  However, on small screens, say 400 pixels width, 30 left and 30 right padding is too much.  This change makes the padding a percentage of screen size.  I set it to 1.5%, which looks good to me but is subjective.  This translates to:
400w px : ~6px padding
800w px: ~12px padding
1200w px: ~18px padding
=> Main Component Padding 

generators/client/templates/angular/src/main/webapp/swagger-ui/_index.html
Correction of name of JWT Token in Swagger (only for Angular2)
caused by ng2-webstorage (lowercase)
=> Correction of name of JWT Token in Swagger

generators/client/templates/angular/src/main/webapp/app/shared/auth/_auth-oauth2.service.ts
I couldn't reproduce this until I ran protractor, then I couldn't log in as admin.  I remembered the protractor tests change the password to `newpassword` and I noticed that worked to log in the admin.
So the real issue is that when you click `Sign out` with Oauth2, it would redirect to `/` before completing the logout, making the `Sign in` element invisible.  Then every other test would fail as it expected the password to be `admin` but it was never changed back from `newpassword`.  I copied the JWT logout method and it now works as expected.
Fix #4982
=> fix oauth2 logout

generators/client/templates/angular/_tsconfig.json
By default, tsc includes **/* and our tsconfig.json excludes node_modules, I found it's better to include source folders explicitly (white list versus black list approach).
By defining includes explicitly, compilation time went from 12.80s to 11.15s with some variations of course.
=> Tuning tsc

generators/client/templates/angular/src/main/webapp/app/shared/auth/_has-any-authority.directive.ts, generators/client/templates/angular/src/main/webapp/app/shared/auth/_has-authority.directive.ts
Use a more semantic BS4 class name (`invisible`) for hiding elements in has-auth rather than `hidden-xs-up`
=> Use invisble class name for hiding elements in has-auth

generators/client/templates/angular/src/main/webapp/app/shared/auth/_auth-oauth2.service.ts, generators/client/templates/angular/src/main/webapp/app/shared/auth/_auth-session.service.ts, generators/client/templates/angular/src/main/webapp/app/shared/auth/_principal.service.ts, generators/client/templates/angular/src/main/webapp/app/shared/tracker/_tracker.service.ts
Some session/oauth were disconnecting websockets on logout, but jwt/uaa were not.  This means that logged out users incorrectly show up in the tracker.
Because `auth-oauth2.service.ts` injected `tracker.service.ts` to disconnect on logout, I couldn't inject `tracker.service.ts` into `auth-oauth2.service.ts` to get the token like expected (circular reference).
I moved the disconnection to the same method where it connects - if the user logs out while connected, the first route change will disconnect them.
Fix #5050
=> fix oauth ws and always disconnect ws when logging out

generators/client/templates/angular/src/main/webapp/app/shared/auth/_has-any-authority.directive.ts, generators/client/templates/angular/src/main/webapp/app/shared/auth/_has-authority.directive.ts
Reverts jhipster/generator-jhipster#5054 because it creates a gap in menu
Ref #5063
=> Revert "Use invisble class name for hiding elements in has-auth"

generators/app/index.js
Related to https://github.com/jhipster/generator-jhipster/issues/5065
I don't put `fix` or `close` as @gmarziou suggested another solution too
```
Welcome to the JHipster Generator v4.0.0
Documentation for creating an application: https://jhipster.github.io/creating-an-app/
Application files will be generated in folder: /home/pgrimaud/tmp/23-toto
WARNING! Your node version is too old (v4.5.0). You should use at least Node v6.9.0+
? (1/15) Which *type* of application would you like to create? (Use arrow keys)
❯ Monolithic application (recommended for simple projects) 
Microservice application 
Microservice gateway 
[BETA] JHipster UAA server (for microservice OAuth2 authentication) 
```
=> Check node version when using the generator. Need at least 6.9.0+

generators/client/templates/angular/webpack/_webpack.dev.js
Without this change 144 warnings from `Reflect.ts` are shown in Windows:
* in command line window on dev server start and on every HMR
* also in web browser console on load and on every HMR
=> remove Reflect.ts warnings from console also in Windows

generators/client/templates/angular/src/main/webapp/app/admin/user-management/_user-management-delete-dialog.component.ts, generators/client/templates/angular/src/main/webapp/app/admin/user-management/_user-management-dialog.component.ts, generators/client/templates/angular/src/main/webapp/app/admin/user-management/_user-modal.service.ts, generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management-delete-dialog.component.ts, generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management-dialog.component.ts, generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-popup.service.ts
The router should navigate away from the popup route on close, and the escape key didn't call clear or save (which handled the routing).  This is the same as how it handled it in NG1
Fix #5100
=> move popup router navigation to popup service

generators/client/templates/angular/src/main/webapp/app/account/password-reset/finish/_password-reset-finish.component.ts, generators/client/templates/angular/src/main/webapp/app/account/password-reset/init/_password-reset-init.component.ts, generators/client/templates/angular/src/main/webapp/app/account/register/_register.component.ts, generators/client/templates/angular/src/main/webapp/app/admin/configuration/_configuration.component.ts
Warnings looked like 
```
WARNING in ./src/main/webapp/app/admin/configuration/configuration.component.ts
[33, 5]: Implement lifecycle hook interface OnInit for method ngOnInit in class JhiConfigurationComponent (https://goo.gl/w1Nwk3)
@ ./src/main/webapp/app/admin/index.ts 10:9-59
@ ./src/main/webapp/app/admin/admin.module.ts
@ ./src/main/webapp/app/app.module.ts
@ ./src/main/webapp/app/app.main.ts
@ multi (webpack)-dev-server/client?http://localhost:9060 webpack/hot/dev-server ./src/main/webapp/app/app.main
```
=> cleanup TypeScript warnings

generators/server/templates/gitignore
Thanks @jeffrey-anderson for narrowing down that issue to git.   This issue only affects NG1 apps after v4
`build/` ignored all directories named `build`, including those in bower_components (ngInfiniteScroll and angular-loading-bar have them).  We already ignore `/build/` so this recent addition should be removed.  Here's an [example commit](https://github.com/ruddell/git-bower-jhipster-issue/commit/4d3fcb0ca1417729c03509d46ec76ba92bb3ff8f) of what changes
Fixes #5142, #5113 and #5119
=> only ignore gradle's 'build' folder

generators/client/templates/angular/src/main/webapp/app/admin/user-management/_user-management.component.html, generators/entity/index.js, generators/entity/prompts.js, generators/entity/templates/client/angular/src/test/javascript/spec/app/entities/_entity-management-detail.component.spec.ts, generators/server/prompts.js
Gateways that use UAA don't require a database.
Also, I simplified some of the conditions for databaseType prompt:
- Don't prompt if a databaseType is already selected
- Removed database prompt that appear when social login is enabled because that can't be selected until afterwards.
=> enable 'no database' option for uaa+gateway combination, polish prompts

generators/server/templates/_pom.xml, generators/server/templates/gradle/_sonar.gradle
Was there a specific reason why we didn't update jacoco for quite a long time (especially in gradle)?
=> update jacoco to latest version

generators/client/files-angular.js, generators/client/templates/angular/src/main/webapp/app/_app.module.ts, generators/client/templates/angular/src/main/webapp/app/home/_home.module.ts, generators/client/templates/angular/src/main/webapp/app/home/_home.route.ts, generators/client/templates/angular/src/main/webapp/app/home/_index.ts, generators/client/templates/angular/src/main/webapp/app/layouts/_layout-routing.module.ts
Home page should have its own module to keep app.module simple and high level and because it gives some structure to users for modifying it.
Remove layout block dependency on home route as it deals only with layout not content.
Polish of  #5127
=> Define a module for home

generators/server/templates/gradle/_profile_dev.gradle
Currently in gradle there are 2 quite inconvenient differences from maven:
1. In `dev` profile maven doesn't execute any frontend tasks but gradle executes `yarn/npm install` (it also triggers `webpack` from `postInstall` in `package.json`) and `webpack` second time. It makes every app startup with gradle very slow.
As a side note: in code https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/gradle/_profile_dev.gradle#L67 I can see that there is tried to achieve the same behaviour as with maven but in gradle all tasks are also project properties, so `webpack.onlyIf { project.hasProperty('webpack') }` always returns true.
2. In `webpack` profile maven doesn't execute `npm/yarn install` but gradle executes. Beside install steps it causes double `webpack` …
=> sync gradle dev profile with maven dev profile in Angular 2

generators/client/templates/angular/src/main/webapp/app/account/social/_social-register.component.ts
Fix Travis build ng2+social+websocket:
> ERROR in [at-loader] src/main/webapp/app/account/social/social-register.component.ts:6:35 
TS2307: Cannot find module '../shared'.
webpack: Failed to compile.
=> Fix shared folder for ng2+social+websocket

generators/docker-compose/prompts.js
When a monolith's serviceDiscoveryType was false or missing, the docker-compose generator would assume you needed a registry.  This fixes it for the kubernetes subgen as well since it uses the same prompts.
This is the issue discussed at the bottom in https://github.com/jhipster/generator-jhipster/issues/4955#issuecomment-278998120 @PierreBesson @jdubois
=> skip docker-compose registry config for monoliths without service discovery

generators/entity/index.js, generators/import-jdl/index.js
This makes it so users can refresh their UI (if they haven't run `yarn start`) after generating entities and see the entities under the Entities menu.
If they have `yarn start` running, it will likely recompile faster, but the entity post-build does not cause `yarn start` to refresh again.
Fixes #5062.
=> Run `webpack:build:dev` after generating entities.

generators/client/templates/angular/src/main/webapp/app/admin/gateway/_gateway.component.html
You can set tags using bootstrap.yml, e.g.:
```
spring:
application:
name: PerunDatahelper
profiles:
active: #spring.profiles.active#
cloud:
consul:
discovery:
tags: app=${spring.application.name}, profile=${spring.profiles.active}, a=b, c=d, e=f, g=h, i=j
```
result:
=> Fix for displaying Consul  instances and metadata

generators/client/templates/angular/src/main/webapp/app/shared/user/_user.service.ts
`req.filter` is always undefined so it isn't used, someone in Gitter asked what this line does.
=> remove unused line in user.service.ts

generators/server/templates/src/main/java/package/config/_MicroserviceSecurityConfiguration.java, generators/server/templates/src/main/java/package/config/_SecurityConfiguration.java, generators/server/templates/src/main/java/package/config/_UaaConfiguration.java
This lets developers set up simple unauthenticated health checks (I wanted it for Rancher). We already open it up for Consul.
While admins get a full report, users and anonymous users get:
```
curl 'http://localhost:8080/management/health' 
{
"description" : "Spring Cloud Eureka Discovery Client",    # Not there for monoliths
"status" : "UP"
}
```
> Shows application health information (when the application is secure, a simple ‘status’ when accessed over an unauthenticated connection or full message details when authenticated).
http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html
=> open health endpoint for all apps

generators/client/templates/angular/_package.json
Related to  #5225 https://github.com/jhipster/generator-jhipster/issues/5188#issuecomment-280256476
```
ERROR in ./src/main/webapp/content/images/hipster.png
Module build failed: Error: spawn /home/vagrant/projects/jhipster-gradle/node_modules/pngquant-bin/vendor/pngquant ENOENT
at exports._errnoException (util.js:1022:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
at onErrorNT (internal/child_process.js:359:16)
at _combinedTickCallback (internal/process/next_tick.js:74:11)
at process._tickCallback (internal/process/next_tick.js:98:9)
@ ./~/css-loader!./src/main/webapp/app/home/home.css 6:307-350
@ ./src/main/webapp/app/home/home.css
@ ./src/main/webapp/app/home/home.component.ts
@ ./src/main/webapp/app/home/index.ts
@ ./src/main/webapp/app/app.module.ts
@ …
```
=> add pngquant and phatomjs rebuild to postinstall

generators/client/templates/angular/_package.json
Fix following warning during yarn install:
> warning angular-cli@1.0.0-beta.28.3: angular-cli has been renamed to @angular/cli. Please update your dependencies.
=> angular-cli has been renamed as @angular/cli

generators/server/templates/src/main/java/package/_Application.java
ApplicationProperties class is defined but not loaded.
I'm thinking to load this class to be available for injection, instead of letting the developer to do it.
JHipsterProperties class is loaded by spring.factories file (JHipster core library).
=> @EnableConfigurationProperties -> ApplicationProperties.class

generators/server/templates/_gradle.properties, generators/server/templates/_pom.xml, generators/server/templates/src/main/java/package/config/_WebConfigurer.java, generators/server/templates/src/main/resources/config/_application-dev.yml
After this patch, if you enable TLS[1], HTTP/2 will be enabled for requests. If you don't enable TLS, HTTP/1.1 will still be used.
NOTE: I tried to use Apache with mod_proxy and mod_ssl (pointing to 8080), and found it doesn’t work. Deploying to Cloud Foundry or Heroku (and enabling SSL) doesn't work either.
[1] See [Wikipedia](https://en.wikipedia.org/wiki/Transport_Layer_Security) to see why I call it TLS instead of SSL.
=> Add HTTP/2 Support and instructions for enabling TLS

generators/server/templates/gradle/_profile_dev.gradle, generators/server/templates/gradle/_profile_prod.gradle
it seems you can't define more than one `it.replace(..)` per `filter` in `processResources` in gradle
fix #5240
=> fixes bootstrap templating in gradle for microservices

generators/app/index.js, generators/server/index.js, generators/upgrade/index.js
I have something working well, but with two minor downsides:
- For NG1, `bower install` always needs to run afterwards (and during the upgrade process, to get any updates because we check them in).
- yarn.lock was giving me issues when the upgrade switches git branches, so I use  `--no-lockfile` during the upgrade process. This means that at the end of an upgrade, yarn.lock is changed
To test, delete node_modules/generator-jhipster after generating an older project and use your linked generator-jhipster to run `yo jhipster:upgrade`.  The upgrade process installs a local version matching the package.json and upgrades the project correctly.
Sample apps showing the commits from the generator from v4.0.2 to v4.0.3:
NG1 Example: https://github.com/ruddell/upgrade-ng1/commits/master
NG2 …
=> Fix upgrade subgen

generators/entity/index.js
add null check for otherEntityData so entity generation will still work if the related entity does not exist yet -- note, an error will still appear on the console but generation will work
Fix #5265
=> add null check to entity generation

.travis.yml, generators/client/index.js
2 important changes:
- the generator will retry (2 times) to launch yarn if it failed, during the generator phase
- I move the generator phase to the 'install' phase of Travis -> it seems much better, and failed less!
I hope it will reduce the random failures... :(
=> Retry yarn when it failed

generators/client/templates/angular/_package.json
This solves the following issue:
/Users/mraible/dev/BugTracker/node_modules/awesome-typescript-loader/src/instance.ts:332
const changedFiles = Object.keys(mtimes).map(toUnix);
=> Upgrade awesome-typescript-loader to 3.0.7

generators/server/templates/src/main/resources/config/_application.yml
>The default order of the OAuth2 resource filter has changed from 3 to SecurityProperties.ACCESS_OVERRIDE_ORDER - 1. This places it after the actuator endpoints but before the basic authentication filter chain. The default can be restored by setting security.oauth2.resource.filter-order = 3
Fix #5298
=> set oauth2 resource filter-order to the old default

generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management-dialog.component.html
Toggling is more untuitive because it means that when you click first time on icon, the datepicker popup opens and when you click a second time it closes.
With previous behavior using open(), you could not close the datepicker popup by clicking on its icon.
=> ngbDatepicker icon now toggles rather than opens

generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management-dialog.component.html
This was causing compilation warnings which were difficult to understand because they refered to typescript file while the issue was in the template.
=> Wrong hidden condition on required relationship error

generators/server/templates/src/main/resources/config/_application.yml
for the same reason as there, with spring boot 1.5.1 the filter order changed.
we should do a 4.0.7 release very soon do make oauth2 grea..aah working again :smile: 
fix #5285
=> adds oauth2 filter order also for uaa server

generators/client/templates/angularjs/src/main/webapp/app/admin/user-management/_user-management.html
Like for the user deletion, we can not deactivate our own account in the user management page.
If this is accepted, I can apply it on ng2.
We still can edit our own account with the dialog and deactivate it but it 'requires more clicks'.
or should we disable the deactivation in the user edition as well ?
or nothing of all of this ?
=> prevent deactivate himself, ng1

generators/entity/templates/client/angularjs/src/main/webapp/app/entities/_entity-management-dialog.html
it fixes having a big checkbox in the middle using firefox (or chrome not on a mac..)
When using Boolean type in the entity generator
it seems that form-control class is just for textual input:
https://www.w3schools.com/bootstrap/bootstrap_forms.asp
=> do not use form-control class for checkbox

generators/server/templates/_build.gradle
interpolation in groovy takes place in double quote strings, not in single quote strings  
this problem was introduced in https://github.com/jhipster/generator-jhipster/commit/7e72dc66e698a1eed03c5f893af74c712289d5d2
=> fix gradle nodeInstall

generators/client/templates/angular/webpack/_webpack.dev.js
both the spring-websocket and Browsersync use websocket so they will be grabbing the websocket port. the best way is to separate the Browsersync websocket port to a different one otherwise the spring-websocket will not work in the way as expected.
One typical error would refer to this ticket https://github.com/BrowserSync/browser-sync/issues/625.
this change requires BrowserSync version 2.8.1+
=> to avoid conflict of grabbing websocket port

generators/server/templates/src/main/resources/config/cql/changelog/_insert_default_users.cql
Without that, a user can register with the same existing email
See the code in the repo `jhipster-sample-app-cassandra`: https://github.com/jhipster/jhipster-sample-app-cassandra/blob/master/src/main/java/io/github/jhipster/sample/web/rest/UserResource.java#L122
=> Cassandra: insert data into user_by_email

generators/entity/templates/server/src/main/java/package/common/get_all_template.ejs, generators/entity/templates/server/src/main/java/package/common/search_template.ejs, generators/server/templates/src/main/java/package/web/rest/_AuditResource.java, generators/server/templates/src/main/java/package/web/rest/_UserResource.java, generators/server/templates/src/main/java/package/web/rest/util/_PaginationUtil.java
Actually those functions throw the URISyntaxException no more, so the throws clause is unnecessary
=> remove unnecessary throws clause

generators/server/templates/_README.md
Add links to relative paths in project README file. 
For example on Github, or Gitlab, it creates real links on your project, see [there](https://github.com/hdurix/jhipster-readme-with-links).
=> Add links to project files and folders in README.md

generators/server/templates/_README.md
As discussed [there](https://github.com/jhipster/generator-jhipster/pull/5358#discussion_r104285923), remove `index.html` link as it is malformed and handled by webpack.
=> remove index href in README [ci skip]

generators/languages/templates/src/main/webapp/i18n/fr/home.json, generators/languages/templates/src/main/webapp/i18n/fr/login.json
Respectons notre belle langue :)
Not optimal for `Github` because the href link has got an extra space even if the typo is respected.
=> add missing spaces in french translation

generators/client/templates/angularjs/src/main/webapp/app/admin/user-management/_user-management-detail.html, generators/client/templates/angularjs/src/main/webapp/content/css/_main.css, generators/client/templates/angularjs/src/main/webapp/scss/_main.scss, generators/entity/templates/client/angularjs/src/main/webapp/app/entities/_entity-management-detail.html
The AngularJS apps still use Bootstrap 3 so I'm switching back the change.
Fix #5373
=> use dl-horizontal for ng1 apps

travis/samples/.jhipster/TestCustomTableName.json, travis/samples/.jhipster/TestEntity.json
Related to https://github.com/jhipster/generator-jhipster/issues/5391#issuecomment-285345005
So the tests I did:
:x: add the fix commit from v4.0.7, the build failed: https://travis-ci.org/pascalgrimaud/generator-jhipster/builds/209798754
```
Results :
Tests in error: 
TestCustomTableNameResourceIntTest.initTest:88->createEntity:79 » TransactionRequired
TestEntityResourceIntTest.initTest:88->createEntity:79 » TransactionRequired N...
Tests run: 427, Failures: 0, Errors: 2, Skipped: 0
[INFO] Total time: 01:23 min
[INFO] Finished at: 2017-03-11T03:35:01+11:00
[INFO] Final Memory: 49M/262M
[INFO] …
```
=> Travis: add relationshipValidateRules to required for some entities

generators/upgrade/index.js
This should finally fix the upgrade generator
NG1 apps have the date of project generation in the gulpfile.js.  This means there will always be a conflict with gulpfile.js during the upgrade process and `gulp install` will fail.  This PR skips `gulp install`.  I didn't see this error when I tested my last PR because the projects were all generated on the same day.
Fix #5366
=> skip gulp install for ng1 apps during upgrade process

generators/client/templates/angular/_package.json, generators/client/templates/angular/src/main/webapp/app/_vendor.ts, generators/client/templates/angular/src/main/webapp/content/css/_vendor.css, generators/client/templates/angular/src/main/webapp/content/scss/_vendor.scss
`webpack:build` recompiles whole project - it's annoyingly slow if repeatedly changing-debugging some third party lib
new task `webpack:build:vendor` compiles only vendor part and is very quick
=> add quick method for recompiling vendor part

generators/generator-base.js
Minor fix: remove extra space in banner in v4.1.0
v4.0.8:
```
╰─$ jh                                                                                                                                                                                                       127 ↵
██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
https://jhipster.github.io
Welcome to the JHipster Generator v4.0.8
``` …
=> Remove extra space in banner [ci skip]

generators/server/templates/src/main/java/package/config/social/_SocialConfiguration.java
Removing unnecessary throws clause to resolve sonar reported bug(major) "Define and throw a dedicated exception instead of using a generic one".
=> Removing throws clause to resolve "sonar" bug

generators/server/files.js
Oauth2 apps are currently broken as the database has `<%= baseName %>` instead of the actual baseName.  This started happening in v4.1.0 (it's fine in v4.0.8)
=> properly template oauth_client_details.csv

generators/entity/templates/client/i18n/_enum_nl.json
There is no `_enum_nl.json` file. This breaks the JDL parser (and probably also the entity generator) when adding an enum with i18n support for Dutch.
=> Added missing _enum_nl.json file for the Dutch language

generators/server/templates/src/main/java/package/config/_LoggingConfiguration.java
Logstash log enriching with application name, port, etc was broken by the migration to constructor injection.
This caused things like this in Kibana:
This PR fixes the issue.
=> Fix LoggingConfiguration log enriching

CONTRIBUTING.md
add a missing space after '###' so it's correctly displayed on github
=> fix CONTRIBUTING.md markdown

generators/import-jdl/index.js
@jdubois @deepu105 A warning: the trick I used to make it work consists in actually writing the options in the JSON files. If you're not okay with this, I'll try to tweak the `index.js` a bit more so as not to do this, but I'd rather not to.
=> [5471] options are now passed when importing JDL files

generators/server/templates/_pom.xml
[ci skip] fix pom.xml whitespace off for cucumber line
fix for issue #5491
=> [ci skip] fix pom.xml whitespace off for cucumber line

generators/client/templates/angular/src/main/webapp/app/shared/alert/_alert-error.component.ts, generators/server/templates/src/main/java/package/web/rest/errors/_CustomParameterizedException.java, generators/server/templates/src/main/java/package/web/rest/errors/_ParameterizedErrorVM.java, generators/upgrade/index.js
Modify params attribute of ParameterizedErrorVM  template to be key/value pair (Map) so that the client-side is able to perform string interpolation of multiple parameters within a message.  
See `alert-error.component.ts` and notice that calls to the function addErrorAlert, which performs  interpolation, use key/value pairs (json object) to specify interpolation parameters.  Using an array will not work for case where there are multiple placeholders (params).
Current implementation uses a "params" array which translates to json as, for example:
```
{
"message" : "error.myCustomError",
"params" : ["param 1 value", "param 2 value"]
}
} 
```
A map is required to support the feature correctly:
```
{
"message" : "error.myCustomError",
"params" : {
"param0" : "Program 4",
"param1" : "another …
```
=> Modify ParameterizedErrorVM to support client-side interpolation of multiple params

generators/server/templates/_build.gradle, generators/server/templates/_pom.xml
`metrics-spring` no longer depends on `net.codahale.metrics`:
http://mvnrepository.com/artifact/com.ryantenney.metrics/metrics-spring/3.1.3
same for `cassandra-driver-core`:
http://mvnrepository.com/artifact/com.datastax.cassandra/cassandra-driver-core/3.1.4
`hikaricp` no longer depends on `sun.tools`:
http://mvnrepository.com/artifact/com.zaxxer/HikariCP/2.6.0
`liquibase-core` no longer depends on `jetty-servlet`:
http://mvnrepository.com/artifact/org.liquibase/liquibase-core/3.5.3
And some minor maven/gradle alignment for good measure.
=> Dependencies cleanup

generators/client/templates/angular/_package.json, generators/client/templates/angular/_tsconfig-aot.json
It took a while to figure this out, since we already specify a path below. 
It fixes [this](https://github.com/jhipster/generator-jhipster/pull/5495#issuecomment-291016939)
@jdubois @pascalgrimaud
=> This stops generating js & js.map in the same folder

generators/entity/templates/server/src/test/java/package/web/rest/_EntityResourceIntTest.java
Currently a **required**  `one-to-many` relationship yields to a compilation error in the appropriate *ResourceIntTest.java class.
```
jhipster-test/src/test/java/de/test/web/rest/AResourceIntTest.java:[82,22] incompatible types: de.test.domain.B cannot be converted to java.util.Set<de.test.domain.B>
```
It fails since a one-to-many relations is handled wrong: trying to access a `set` method which is expecting a set of b's.
Reproducible with the following JDL used in a fresh project:
```
entity A {}
entity B {}
A{b required} to B
}
```
As the relation to B is many A only has a set of B's. Thus we also need to add one item to the set, similar to the many-to-many case.
Cheer's,
Marco
=> Fixed missing 'one-to-many' relationship case for required relation

generators/entity/files.js, generators/generator-base.js
This change allows modules to use addEntityToEhcache and addEntryToEhcache.  Currently (from a module), addEntryToEhcache fails with the below error:
```
Unable to add undefined.domain.EntityAuditEvent.class.getName() to CacheConfiguration.java file.
/private/tmp/jhi/mono/src/main/java/undefined/config/CacheConfiguration.java doesn't exist
```
=> pass packageName and packageFolder to addEntityToEhcache

generators/server/templates/src/main/resources/config/_application.yml
in AngularJs 1 both `/#/home` and `/#/` are working (route `home` is defined with path `/`)
in Angular 2 (4) only `/#/` is working (no route `home` exists, home component path is empty string)
so changing redirect to `/#/` which works both in AngularJs 1 and Angular 2 (4)
=> fix social sign in redirect in Angular 2

generators/client/templates/angular/webpack/_webpack.common.js, generators/client/templates/angular/webpack/_webpack.vendor.js
use `woff2?` instead `woff|woff2`
=> Optimize webpack file loader pattern for woff and woff2 files

generators/rancher-compose/index.js, generators/rancher-compose/templates/_docker-compose.yml
When gateway has a port different to 8080, load balancing service could not bind to it.
Also add monitoring configuration on all application not only on monolith
=> Fixing issue on rancher-compose module for non default port on gateway

generators/ci-cd/templates/_.gitlab-ci.yml, generators/ci-cd/templates/_circle.yml, generators/ci-cd/templates/_travis.yml, generators/ci-cd/templates/jenkins/_Jenkinsfile
change the deployment type because WebSockets don't work with the webapp-runner.jar used by heroku-maven-plugin but work when deployed as a Spring Boot standalone application
close #5507
=> change heroku deployment to deploy as standalone application

generators/client/files-angular.js, generators/client/templates/angular/_.angular-cli.json, generators/client/templates/angular/_proxy.conf.json
Fix integration issues with AngularCli regarding styling, polyfills and content loading.
Also add default proxy configuration when using ng serve instead of yarn start. User can now run `ng serve —proxy-conf proxy.conf.json` to use his backend.
Related to #5558
=> Fix AngularCli integration issues

generators/client/templates/angular/src/main/webapp/app/shared/auth/_user-route-access-service.ts
* When the state doesn't require any authority `true` is returned
* Someone should check if the login modal opens multiple times (sometimes I hat that, sometimes not, I looks like it depends on the requested, protected page/route)
* I am open for better suggestions
close #5542
=> allow state change when no authorities are required

generators/server/templates/src/main/docker/_Dockerfile
The /tmp volume doesn't serve a purpose for us (original purpose seems to be Tomcat related).  Removing it shouldn't cause any issues as users can still declare a tmp volume if they wish (which would go along with Policy 1).  This was done in the registry already https://github.com/jhipster/jhipster-registry/pull/105
Original reasoning was from https://spring.io/guides/gs/spring-boot-docker/ (same place the old `touch` command we removed came from)
>	We added a VOLUME pointing to "/tmp" because that is where a Spring Boot application creates working directories for Tomcat by default. The effect is to create a temporary file on your host under "/var/lib/docker" and link it to the container under "/tmp". This step is optional for the simple app that we wrote here, but can be necessary for …
=> remove tmp volume from dockerfile

generators/server/templates/src/main/java/package/service/dto/_UserDTO.java, generators/server/templates/src/main/java/package/web/rest/_UserResource.java
Validates the `managedUserVM` in the WS layer (like in AccountResource)
- [] Tests are added where necessary, **supplementary tests could be written when having a null or empty login for example but it might not be worth the amount of code for this.., let me know**
=> user validation in WS layer

generators/server/templates/src/main/java/package/web/rest/util/_HeaderUtil.java
createFailureAlert() might not only be used for entity creation (currently on user update as well)
=> change log label

generators/generator-base.js
When you are on an active menu in Entity, it is not displayed as selected.
=> Fix an active entity in menu

CONTRIBUTING.md
For the issues or pulls, you suggest searching open or closed issue/PR
yet the link you give only displays open items.
=> change hypertext link to display open and closed issues/PR

generators/client/templates/angular/src/main/webapp/app/shared/login/_login.component.html
When language selected is french, "Sign in" left-align is not well displayed.
=> Fix "sign in" left align when langage different from english

generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management-dialog.component.ts, generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity.service.ts
The same code is repeated twice for updating and inserting entity - this can be refactored to a separate function
=> Reduce code duplication on entity save response handling

generators/server/templates/src/main/java/package/web/rest/errors/_ExceptionTranslator.java
Logs the exception with the stacktrace when exception is handled by `@ExceptionHandler(Exception.class)`.
In production, a RuntimeException that leads for the client to a `ErrorConstants.ERR_INTERNAL_SERVER_ERROR` should be logged server side (message and stacktrace) to know what is wrong
WDYT?
=> log exception with stacktrace

generators/client/templates/angular/src/main/webapp/app/shared/auth/_principal.service.ts, generators/client/templates/angular/src/main/webapp/app/shared/auth/_user-route-access-service.ts
use the 'direct' response, because hasAnyAuthority returns a promise,
which is evaluated to true, always.
=> ng2 : Fix UserRouteAccessService

generators/server/templates/src/main/docker/_Dockerfile
this allows the user to specify options like memory limit by
providing environment variables.
after running a workload of ~10 services (with replicas on top) in kubernetes, I run into heavy memory issues, were entire nodes were crashing as running Java in docker with default settings allocates nearly all the memory. This PR **does not change that**!! But now the user can provide 
```
ENV JAVA_OPTS = " -Xmx300m -Xms300m" 
```
in any way, like from CMD, in docker-compose, rancher-compose or kubernetes deployment, to **really** limit the JVM memory usage.
I can add docs to this for kubernetes
I decided not do set any options, in favor of not breaking change existing setups. I personally run my containers with 300m limits and have noticed no performance issues in any way.
- Please make sure …
=> adds $JAVA_OPTS to Dockerfile

generators/docker-compose/index.js
When using the sub generator docker-compose, the generated docker-compose.yml is incorrect, because of this: `- >-` :
```yaml
version: '2'
services:
gateway-app:
image: gateway
environment:
- SPRING_PROFILES_ACTIVE=prod,swagger
- EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
- SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
- >-
SPRING_DATASOURCE_URL=jdbc:mysql://gateway-mysql:3306/gateway?useUnicode=true&characterEncoding=utf8&useSSL=false
- SPRING_DATA_CASSANDRA_CONTACTPOINTS=gateway-cassandra
- JHIPSTER_SLEEP=30
- JHIPSTER_REGISTRY_PASSWORD=admin
ports:
- 8080:8080
gateway-mysql:
image: mysql:5.7.13
environment:
- MYSQL_USER=root
- MYSQL_ALLOW_EMPTY_PASSWORD=yes
- …
```
=> Fix yaml files generated by docker-compose sub generator [ci skip]

generators/server/templates/src/main/java/package/config/dbmigrations/_InitialSetupMigration.java, generators/server/templates/src/main/java/package/domain/_AbstractAuditingEntity.java, generators/server/templates/src/main/java/package/domain/_User.java, generators/server/templates/src/main/java/package/repository/_UserRepository.java, generators/server/templates/src/main/java/package/service/_UserService.java, generators/server/templates/src/main/java/package/service/dto/_UserDTO.java, generators/server/templates/src/main/java/package/web/rest/vm/_ManagedUserVM.java, generators/server/templates/src/test/java/package/service/_UserServiceIntTest.java
Note that the default Jackson Instant deserializer is less permissive than the ZonedDateTime one as it only accepts strings ending by "Z" or "+0000" and doesn't accept timezone offsets. The Instant deserializer can easily be modified with a Jackson2ObjectMapperBuilderCustomizer bean if necessary.
The fields modified here are read/serialize only so it doesn't break anything.
=> Replace ZonedDateTime by Instant where possible

generators/client/templates/angular/src/main/webapp/app/account/activate/_activate.component.html
The entire message was replaced by just the part (missing the sign in link)
Fix #5717 
=> fix activate success translation display

generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity.service.ts
Related to https://github.com/jhipster/generator-jhipster/pull/5684/files#r114883076
Missing a condition, otherwise, when an entity has only localDate, it will fail during TS compilation
=> Fix entity with localdate only

generators/docker-compose/templates/_jhipster-registry.yml
When using the new registry, this missing config is needed.
Steps to reproduce:
- generate a gateway
- build with: `./mvnw package -Pprod docker:build`
- create a new folder: `compose`
- generate the compose file with: `yo jhipster:docker-compose` and select the previous gateway
- edit `jhipster-registry.yml` and replace `jhipster/jhipster-registry:v2.6.0` by `jhipster/jhipster-registry:develop`
- then, run with: `docker-compose up`
- you'll get this error for jhipster-registry:
```
jhipster-registry_1  | java.net.URISyntaxException: Illegal character in authority at index 7: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
jhipster-registry_1  | 	at java.net.URI$Parser.fail(URI.java:2848)
jhipster-registry_1  | 	at …
```
=> Fix docker-compose when using new registry [ci skip]

generators/client/templates/angular/_package.json, generators/client/templates/angular/webpack/_webpack.common.js, generators/generator-base.js, generators/languages/index.js
This is needed for the new way of loading translations - after the initial generation if a user adds a language with `yo jhipster:languages`, it needs to be added here as well or no translations load
=> add each language to webpack.common.js via language subgen

generators/entity/templates/server/src/main/java/package/repository/_EntityRepository.java, generators/server/templates/src/main/java/package/aop/logging/_LoggingAspect.java
LoggingAspect no longer logs every single bean in the affect packages but only those complying with the naming convention.
Fixes #5715
=> restrict aspect logging to Service, Repository and Resource beans

generators/generator-constants.js, generators/server/templates/src/main/docker/_mysql.yml, test/templates/compose/01-gateway/src/main/docker/mysql.yml, test/templates/compose/02-mysql/src/main/docker/mysql.yml, test/templates/compose/06-uaa/src/main/docker/mysql.yml, test/templates/compose/08-monolith/src/main/docker/mysql.yml, test/templates/compose/09-kafka/src/main/docker/mysql.yml
=> upgrade mysql and add flag for explicit defaults for timestamp

generators/server/files.js, generators/server/templates/src/test/resources/config/_application.yml
We were still copying Cassandra yml files for gateways after removing it for rate-limiting
=> only copy Cassandra files for apps that use Cassandra

.travis.yml
Related to JHipster CLI (https://github.com/jhipster/generator-jhipster/pull/5726 and https://github.com/jhipster/generator-jhipster/issues/5747), the flag `--ignore-engines` when launching `yarn install` should not be necessary
=> Travis: remove ignore engines when launching yarn install

generators/rancher-compose/templates/_docker-compose.yml
Change to registry volume mount for Consul Registry sidekick in Rancher. Allows the configuration to be deployed to Rancher correctly when Consul has been selected.
Fix for #5778
=> Change registry volume mount for Consul Registry sidekick

generators/languages/templates/src/main/webapp/i18n/ko/_health.json
fix duplicate key for "stacktrace" and add missing translations in i18n/ko/_health.json
=> fix duplicate key and add translations to Korean

generators/server/templates/gradle/_profile_prod.gradle
Currently frontend test when using ng1 also contains webpack, which doesn't work :)
When merging this PR webpack is only used when angular is used and gulp only when ng1 is selected.
=> remove webpack for ng1

generators/kubernetes/index.js
When generating Kubernetes configuration, the instructions are not correct, because the displayed folder must be in lowercase
___
=> Kubernetes: display correctly the folder name to lowercase [ci skip]

generators/server/templates/src/main/resources/_logback-spring.xml
Some minor change in the logback configuration:
1) `io.github.jhipster` at same level than `packageName`, specially when building for prod
2) add in comment the appender-ref to `FILE`, so the logfile won't be empty when uncomment the first part
_____
=> Same level for io.github.jhipster than the packageName

generators/heroku/index.js
Fixes two issues with the Heroku CLI invocation on MacOS (10.12.5)
- Heroku generator fails if the plugin has already been installed; the install command returns a -1 error code, causing the program to abort. This fix checks to see if the plugin is already available. If it is, do not install it again.
- If your Heroku account has not been verified, then you cannot install AddOns (such as the Database AddOn). Previous behaviour silently swallows error.
@jkutner would you mind having a look at this?
=> modify interaction with Heroku CLI for plugin install and new Heroku account

generators/server/templates/src/test/java/package/config/_WebConfigurerTest.java
Unix Path are misinterpreted on windows system. Using FilenameUtils.separatorsToSystem from apache commons to make the path system independent.
Fix #5805
=> Correct a unit test failure on windows OS

generators/heroku/templates/_application-heroku.yml
It needs to be under `hikari` to work. I've also reduce it to 8 because the maximum allowed (at least for JawsDB) is 10. So, when the app in launched, it is impossible to connect with any other client to the database. Which is super annoying. 8 seems to be a good compromise.
=> Pool max size not set correctly

generators/client/templates/angular/src/main/webapp/_index.html, generators/client/templates/angular/src/main/webapp/app/layouts/navbar/_navbar.component.html
Related to #5620, this allows a user to deploy the app to any context path without needing to change the base href.  When deploying to the root path, it works the same as in the past.
=> use relative base instead of absolute path for context paths and proxies

generators/server/templates/src/main/docker/_app.yml
The “EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE” environment variable specified in the _app.yml file contains an invalid hyphen(-) character. When the container is started, this variable is not set. This change replaces the hyphen with an underscore, which Spring Boot can still read due to its relaxed binding rules. This change aligns the _app.xml file it to the Kubernetes+Openshift versions of this template.
=> Change Eureka Environment variable to valid character

generators/entity/index.js
closes #5591
I didn't find any test relative to validation. I did search for `validateEntityName()` inside the test directory and checked `generator-jhipster/test/test-entity.js` without success . Such tests would be beneficial for the application but I don't have time to do that from scratch in the near future.
Unlike the following code sample, I don't have a capture group `(the things inside parentheses are captured)`, should I ?
```javascript
validateEntityName() {
if (!(/^([a-zA-Z0-9_]*)$/.test(this.name))) {
this.error(chalk.red('The entity name cannot contain special characters'));
} 
```
=> add a validation rule to forbid entity name beginning with a number

generators/upgrade/index.js
=> WIP: Fix automatic upgrade

generators/client/templates/angularjs/src/main/webapp/app/components/alert/_alert-error.directive.js
When angular receive an error from a webservice,
There are 2 differents cases:
1) either X-pocApp-error and X-pocApp-params are sent in the headers
2) either httpResponse.data is populated with an ErrorVM structure
The test `if (errorHeader)` : is always 'true'.
because we have `var errorHeader=httpResponse.headers(headers[0])` and `httpResponse.headers(headers[0])` is never undefined (or null or false...). 
It's either a String in the case of 1) or an Object (the headers) in the case of 2).
And It seems the way to handle this properly is already done in notification.interceptor.js 
(https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angularjs/src/main/webapp/app/blocks/interceptor/_notification.interceptor.js)
(check the the same commit of the …
=> fix check on errorHeader

generators/generator-base.js, test/test-generator-base.js
Normally `this.fs` is yeoman's in-memory filesystem (mem-fs) so once
file is read from disk it's not re-read.
Using jhipster-core function `readEntityJSON` means we always read from
disk and have most up to date and consistent state.
This came up when implementing a change in `import-jdl` generator where
entities needed to be re-read after they've been changed by the import.
=> use the real fs when reading entity JSON files

generators/entity/templates/server/src/main/java/package/domain/_Entity.java
Should hopefully close [#130 from the JHCore project](https://github.com/jhipster/jhipster-core/issues/130) and the related #5969. 
The variable `fieldInJavaBeanMethod` was used for the accessors, and `fieldNameCapitalized` was built for the `#toString` method, and only used once.
- [] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
=> Made the #toString method use the right getter names

generators/entity/templates/client/i18n/_entity_ro.json
Updated Romanian (ro) translations to correct some misspellings, uniformize expressions and add some missing diacritics. This is an update for the previous pull request as it missed the file \generators\entity\templates\client\i18n\_entity_ro.json
=> Updated Romanian (ro) translations (2)

generators/entity/templates/server/src/main/resources/config/liquibase/changelog/_added_entity.xml, generators/entity/templates/server/src/main/resources/config/liquibase/changelog/_added_entity_constraints.xml, generators/server/templates/src/main/resources/config/liquibase/changelog/_initial_schema.xml, generators/server/templates/src/main/resources/config/liquibase/master.xml
liquibase 3.5.3 is used, so this xsd file version in the xml can be set to 3.5 as well.
And being able to see the context attribute valid like in the following migration:
`<include context="!test" file="classpath:config/liquibase/changelog/20170630140601_partial_index.sql" relativeToChangelogFile="false"/>`
=> set liquibase xsd file to 3.5

generators/server/templates/src/main/resources/config/_application-dev.yml
This is needed to make call from Swagger UI to the management endpoints work when proxying from browsersync.
Linked to https://github.com/jhipster/jhipster/pull/19
=> enable management endpoints CORS when using the dev profile

generators/client/templates/angularjs/_gulpfile.js, generators/client/templates/angularjs/src/main/webapp/app/_app.constants.js, generators/client/templates/angularjs/src/main/webapp/app/blocks/config/_translation.config.js
When I deploy the app with a war file to tomcat or using the jhipster deployment script to heroku,
the translation json files (e.g. global.json, home.json, ...) are not necessarily reloaded by $translateProvider. This causes that the updated translations are not loaded and I have to manually delete the browser cache..
I have most of the time a `200  (from disk cache)` with chrome or a `200 cached` with firefox. 
I firstly investigate in `WebConfigurer` through `initCachingHttpHeadersFilter` and add `cachingHttpHeadersFilter.addMappingForUrlPatterns(disps, true, "/i18n/*");`, thinking that the caching rules are not applied to i18n url => but I still have the same problem..
Then I tried `$translateProvider.useLoaderCache(false);` => same problem..
So through this PR, I added a "cacheBuster" …
=> cacheBuster with build timestamp for translation json files

generators/client/templates/angularjs/_gulpfile.js, generators/client/templates/angularjs/src/main/webapp/app/_app.constants.js
- Remove  build timestamp for dev build because it updates 'app.constants.js' everytime we run 'gulp' which could be annoying (and useless).
- Change to double quotes in `.constant('BUILD_TIMESTAMP', "");` as gulp produces double quote rather than simple ones...
=> Do not use build timestamp for dev

generators/entity/files.js, generators/entity/templates/server/src/test/gatling/user-files/simulations/_EntityGatlingTest.scala, generators/server/files.js, generators/server/templates/_pom.xml, generators/server/templates/gradle/_gatling.gradle, test/test-creation.js, test/test-entity.js
This PR is intended to update Gatling (versions, structure, ...).
Concerning the structure, in particular the new "user-files" dir, I've follow the official documentation (http://gatling.io/docs/current/general/bundle_structure/)
In the pom.xml, we can use default args to give to all gatling tests (http://gatling.io/docs/current/cookbook/passing_parameters/).
I also added a dir, "target/gatling/results/${maven.build.timestamp}/" in pom.xml, to have different folders each time you launch Gatling tests.
In addition, if a BigDecimal field of an entity is required, when gatling tries to create the entity, the call fails.
So I added a case when an entity field is a BigDecimal. 
Maven and Yarn tests are OK.
---------------------------------------------------
- Please make sure the below …
=> Up-to-date Gatling

generators/generator-base.js
Fix error when a module try to add new dependency to `package.json` that doesn't have any dependencies.
Ref: https://github.com/jhipster/jhipster-sample-app/blob/master/package.json#L11
=> Fix error undefined when modify package.json

generators/server/files.js
Add gitkeep file on features folder to avoid cucumber test issue issue when pushing and pulling with git
=> add .gitkeep file for cucumber

generators/client/files-angular.js, generators/client/templates/angular/src/main/webapp/app/account/password/_password.route.ts, generators/client/templates/angular/src/main/webapp/app/account/sessions/_sessions.route.ts, generators/client/templates/angular/src/main/webapp/app/account/settings/_settings.route.ts, generators/client/templates/angular/src/main/webapp/app/admin/_admin.route.ts, generators/client/templates/angular/src/main/webapp/app/admin/user-management/_user-management.route.ts, generators/client/templates/angular/src/main/webapp/app/layouts/navbar/_navbar.component.html, generators/client/templates/angular/src/main/webapp/app/layouts/navbar/_navbar.component.ts, generators/client/templates/angular/src/main/webapp/app/shared/_index.ts, generators/client/templates/angular/src/main/webapp/app/shared/auth/_authorities-constants.ts, generators/client/templates/angular/src/main/webapp/app/shared/auth/_has-any-authority.directive.ts, generators/client/templates/angular/src/main/webapp/app/shared/user/_user.service.ts, generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management-dialog.component.ts, generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management.route.ts
Added a new AuthoritiesConstants class on angular 2 client side in auth folder, similar with the java server one.
All "hard-coded" references of form 'ROLE_ADMIN', 'ROLE_USER' are now changed to AuthoritiesConstants.ADMIN, AuthoritiesConstants.USER.
Please note that I also removed an unused 'authorities' property in _entity-management-dialog.component.ts
=> Changed role strings in angular 2 client to typed properties of a new AuthoritiesConstants class

generators/client/templates/angular/src/main/webapp/app/shared/_shared-common.module.ts
By adding a default local provider, the Date/Number string will format and display as local style not US style.
already answered by this link:
https://stackoverflow.com/questions/34904683/how-to-set-locale-in-datepipe-in-angular2
=> add a default locale provider
